### ISSUE TITLE
Taking backup from postgresql 9.6 as pod

### ISSUE THREAD

**Issue by arvindsaket** [pgbackrest/pgbackrest#1005]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.25

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I want to know, how to setup pgbackrest for taking backup from postgresql 9.6 cluster running as pods.

**Comment by dwsteele** [comment]
We recommend you look at something like Crunchy Containers (https://github.com/CrunchyData/crunchy-containers) if you are interested in running pgBackRest in containers.
