### ISSUE TITLE
pgbackrest backup from remote machine.

### ISSUE THREAD

**Issue by arvindsaket** [pgbackrest/pgbackrest#1006]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.25

2. PostgreSQL version:9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Is it possible to take pgbackrest backup from the remote machine? Is it possible to take pgbackup backup from remote machine without installing the pgbackrest on the PostgreSQL host?

**Comment by dwsteele** [comment]
> Is it possible to take pgbackrest backup from the remote machine?

Yes, see https://pgbackrest.org/user-guide-centos7.html#repo-host.

>  Is it possible to take pgbackup backup from remote machine without installing the pgbackrest on the PostgreSQL host?

No.
