### ISSUE TITLE
ERROR: [039]: timeout after 60000ms waiting for read from 'xxxs3-internal.xxx.xxx-oss.com:443'

### ISSUE THREAD

**Issue by nefumc** [pgbackrest/pgbackrest#1007]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.26dev

2. PostgreSQL version:11.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
epository host server: centos 7.6
database server : centos 7.6

4. Did you install pgBackRest from source or from a package?
build from master
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
--
pgbackrest.conf：
[global]
backup-standby=y
process-max=3
repo1-retention-full=9999999
repo1-path=/pgbackrest
start-fast=y
log-path=/xx/pgbackrest
exclude=archive
archive-timeout=600
protocol-timeout=3600
io-timeout=600
repo1-s3-bucket=xx
repo1-s3-endpoint=xx
repo1-s3-port=443
repo1-s3-key=xx
repo1-s3-key-secret=xx
repo1-s3-verify-tls=xx
repo1-s3-region=xx
repo1-type=s3

[global:backup]
process-max=8

[global:archive-push]
process-max=3
spool-path=/xx/archive_spool

[global:restore]
process-max=6

[global:archive-get]
process-max=3
7. Describe the issue:
pgbackrest --stanza=pg-xxxxxn --repo1-retention-full=10 --log-level-console=info expire

I have set io-timeout=600（10min），but when pgbackrest expire have this error:
ERROR: [039]: timeout after 60000ms waiting for read from 'xxxxxpgsql.s3-internal.xxxxxx.xxxx-oss.com:443'
timeout is 60000ms（1min）

**Comment by dwsteele** [comment]
Good catch. This option was being ignore for the expire command.

Fixed at 6f41ce1182c3417f4.

**Comment by dwsteele** [comment]
The `io-timeout` option went out with the 2.26 release. Let us know if anything looks wrong.
