### ISSUE TITLE
configure: error: library 'crypto' is required

### ISSUE THREAD

**Issue by BVishwamitra** [pgbackrest/pgbackrest#1008]
I am using REDHAT 6.7, I have installed both openssl and openssl-devel in /usr/lib64 but it is throwing below error

checking for EVP_get_digestbyname in -lcrypto... no
configure: error: library 'crypto' is required

I am trying to install pgbackrest2.25 with PostgreSQL 9.3.

**Comment by BVishwamitra** [comment]
[src]# yum install make gcc openssl-devel libxml2-devel lz4-devel
Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Install Process
Package 1:make-3.81-20.el6.x86_64 already installed and latest version
Package gcc-4.4.7-16.el6.x86_64 already installed and latest version
Package openssl-devel-1.0.1e-42.el6.x86_64 already installed and latest version
Package libxml2-devel-2.7.6-20.el6.x86_64 already installed and latest version
No package lz4-devel available.

**Comment by BVishwamitra** [comment]
I can see below message in config.log

configure:3011: gcc  -c   conftest.c >&5
conftest.c:59: error: expected ';', ',' or ')' before 'text'
conftest.c: In function 'main':
conftest.c:113: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'newvar'
conftest.c:113: error: 'newvar' undeclared (first use in this function)
conftest.c:113: error: (Each undeclared identifier is reported only once
conftest.c:113: error: for each function it appears in.)
conftest.c:123: error: 'for' loop initial declarations are only allowed in C99 mode
conftest.c:123: note: use option -std=c99 or -std=gnu99 to compile your code
configure:3011: $? = 1

**Comment by dwsteele** [comment]
> checking for EVP_get_digestbyname in -lcrypto... no

It looks like `libcrypto` is not being installed in the standard location or your PATH is broken. You can set CPPFLAGS and LDFLAGS to let configure know the location of `libcrypto`. Here's an example of that in the MacOS build: https://github.com/pgbackrest/pgbackrest/blob/2e6938fad9ab4e93c472a3f86812ed82fba1df4d/.cirrus.yml#L36

However, I recommend that you use the pre-built packages available at https://yum.postgresql.org/.

**Comment by BVishwamitra** [comment]
Hi dwsteele,

Thanks for quick reply. I tried in all possible ways but still facing same issue

[root@tsepos-db-n1 src]# ./configure LDFLAGS='-L/usr/lib64'
checking for gcc... gcc
checking whether the C compiler works... yes
....
....
checking for EVP_get_digestbyname in -lcrypto... no
configure: error: library 'crypto' is required

yum --installroot=/tmp/openssl/ install openssl openssl-devel

[root@tsepos-db-n1 src]# ./configure LDFLAGS='-L/tmp/openssl/usr/lib64'
checking for gcc... gcc
checking whether the C compiler works... yes
....
....
checking for EVP_get_digestbyname in -lcrypto... no
configure: error: library 'crypto' is required

**Comment by dwsteele** [comment]
On a RHEL 6 system `libcrypto` is normally located at:
```
$ whereis libcrypto
libcrypto: /usr/lib64/libcrypto.so
```
So it looks like: your path is still wrong, you are missing the library, or the library does not contain the expected function. Since it looks like you installed the `openssl-devel` package I'm not sure what's wrong. 

Again, there is likely something broken on your host. Have you tried building on a clean host? Have you considered using the packages at yum.postgresql.org?
