### ISSUE TITLE
ERROR: [070]: link 'pg_tblspc/16384' (/srv/pgsql/pginst01/11/ts001) destination is a subdirectory of or the same directory as link 'instance.env.sh' (/srv/pgsql/pginst01/11)

### ISSUE THREAD

**Issue by ChristCava** [pgbackrest/pgbackrest#1012]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.25

2. PostgreSQL version: 11.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Red Hat Enterprise Linux Server release 7.7 (Maipo)

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
the error encountered was not present in version 2.19

error message : ERROR: [070]: link 'pg_conf' (/srv/pgsql/pginst01/11/pg_conf/) destination is a subdirectory of or the same directory as link 'instance.env.sh' (/srv/pgsql/pginst01/11)

The particularity of our pg_data tree is that it includes symbolic links on files or directories pointing to identical paths for example:
- the link /srv/pgsql/pginst01/11/pg_data/pg_hba.conf which points to the file /srv/pgsql/pg_hba.conf 
- the link /srv/pgsql/pginst01/11/pg_data/pg_hba_maintenance.conf that point to the /srv/pgsql/pg_hba_maintenance.conf file
- the link /srv/pgsql/pginst01/11/pg_data/pg_conf that points to the /srv/pgsql/pginst01/11/pg_conf directory
- the link /srv/pgsql/pginst01/11/pg_data/instance.env.sh which points to the file /srv/pgsql/pginst01/11/instance.env.sh
- the link /srv/pgsql/pginst01/11/pg_data/pg_tblspc/16384 points to the /srv/pgsql/pginst01/11/ts001 directory 

[cfg&logs.tar.gz](https://github.com/pgbackrest/pgbackrest/files/4544701/cfg.logs.tar.gz)

**Comment by dwsteele** [comment]
> the error encountered was not present in version 2.19

Yes, there seems to be error in the C implementation introduced in 2.20. It is not excluding file link vs path link comparisons correctly.

Just to be sure, it would be helpful to verify the links in PGDATA. Can you run:
```
ls -lah /srv/pgsql/pginst01/11/pg_data
```
and post the results?

**Comment by ChristCava** [comment]
the result:
[postgres@vhlpsq11001.retraite.lan, Tue Apr 28 16:13:27]> /var/lib/pgsql
$ ls -lah /srv/pgsql/pginst01/11/pg_data
total 124K
drwx--S---. 19 postgres postgres 4.0K Apr 28 11:59 .
drwx--S---.  6 postgres postgres  138 Apr 28 15:27 ..
-rw-------.  1 postgres postgres  263 Apr  3 09:02 backup_label.old
-rw-r--r--.  1 postgres postgres 1.5K Apr  3 11:27 .barman-recover.info
drwxr-sr-x.  3 postgres postgres   28 Apr 10 12:36 barman_xlog
drwx------.  7 postgres postgres   67 Apr 10 12:36 base
-rw-------.  1 postgres postgres   82 Apr 28 00:00 current_logfiles
drwx------.  2 postgres postgres 4.0K Apr 28 15:10 global
lrwxrwxrwx.  1 postgres postgres   38 Apr 27 17:28 instance.env.sh -> /srv/pgsql/pginst01/11/instance.env.sh
lrwxrwxrwx.  1 postgres postgres   27 Apr 17 22:16 log -> /srv/logs/pgsql/pginst01/11
drwx------.  2 postgres postgres    6 Sep 24  2019 pg_commit_ts
lrwxrwxrwx.  1 postgres postgres   30 Apr 28 11:59 pg_conf -> /srv/pgsql/pginst01/11/pg_conf
drwx------.  2 postgres postgres    6 Sep 24  2019 pg_dynshmem
lrwxrwxrwx.  1 postgres postgres   22 Apr 27 17:28 pg_hba.conf -> /srv/pgsql/pg_hba.conf
lrwxrwxrwx.  1 postgres postgres   34 Apr 17 22:16 pg_hba_maintenance.conf -> /srv/pgsql/pg_hba_maintenance.conf
lrwxrwxrwx.  1 postgres postgres   24 Apr 17 22:16 pg_ident.conf -> /srv/pgsql/pg_ident.conf
drwx------.  4 postgres postgres   68 Apr 28 16:11 pg_logical
drwx------.  4 postgres postgres   36 Apr 10 12:35 pg_multixact
drwx------.  2 postgres postgres   26 Apr 17 22:17 pg_notify
lrwxrwxrwx.  1 postgres postgres   22 Apr 17 22:16 .pgpass -> /var/lib/pgsql/.pgpass
drwx------.  2 postgres postgres    6 Apr  1 10:27 pg_replslot
drwx------.  2 postgres postgres    6 Sep 24  2019 pg_serial
drwx------.  2 postgres postgres    6 Sep 24  2019 pg_snapshots
drwx------.  2 postgres postgres    6 Apr 17 22:17 pg_stat
drwx------.  2 postgres postgres  183 Apr 28 16:13 pg_stat_tmp
drwx------.  2 postgres postgres   18 Apr 27 08:46 pg_subtrans
drwx------.  2 postgres postgres   19 Apr 28 08:42 pg_tblspc
drwx------.  2 postgres postgres    6 Sep 24  2019 pg_twophase
-rw-------.  1 postgres postgres    3 Sep 24  2019 PG_VERSION
lrwxrwxrwx.  1 postgres postgres   30 Apr 17 22:16 pg_wal -> /srv/pgsql/pginst01/11/pg_wal/
drwx------.  2 postgres postgres 4.0K Apr 10 12:35 pg_xact
lrwxrwxrwx.  1 postgres postgres   32 Apr 17 22:16 pitr.conf -> /srv/pgsql/pginst01/11/pitr.conf
-rw-------.  1 postgres postgres  238 Apr 27 14:00 postgresql.auto.conf
-rw-------.  1 postgres postgres  163 Apr 17 22:17 postgresql.auto.conf.old
-rw-------.  1 postgres postgres  163 Mar 27 16:34 postgresql.auto.conf.origin
-rw-------.  1 postgres postgres  24K Apr 17 22:16 postgresql.conf
-rw-------.  1 postgres postgres  24K Apr 17 22:17 postgresql.conf.old
-rw-------.  1 postgres postgres  24K Jan 29 20:53 postgresql.conf.origin
-rw-------.  1 postgres postgres   65 Apr 17 22:17 postmaster.opts
-rw-------.  1 postgres postgres  114 Apr 17 22:17 postmaster.pid
-rw-r--r--.  1 postgres postgres  257 Apr 17 22:16 recovery.done

**Comment by dwsteele** [comment]
OK, thanks, that matches what you described originally so I think the patch looks good. You can have look at the PR #1015 if you like.

We just released 2.26 so we're not inclined to do another release so soon. You'll probably need to stay on 2.19 until 2.27 is released because I don't see a workaround for this.

**Comment by dwsteele** [comment]
@ChristCava How would you like your name to appear in the release notes?

**Comment by ChristCava** [comment]
Yes no problem, all thanks for your work.

**Comment by dwsteele** [comment]
This has been fixed at baf8cb90684fe. Thank you for the report!
