### ISSUE TITLE
Recovery without Current Backup

### ISSUE THREAD

**Issue by Argha-2890** [pgbackrest/pgbackrest#1017]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.24

2. PostgreSQL version:11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package? Source

5. Primary Conf :

```
[mdb]
pg1-path=/data/patroni1

[global]
log-level-file=detail
repo1-host=10.0.0.24
repo1-host-user=pgbackrest
```

Standby Conf :

```
[global]
repo1-host=10.0.0.24
repo1-path=/data/pgbackrest
log-level-file=detail

[mdb]
pg1-host=10.0.0.31
pg1-path=/data/patroni3
```

Repository Conf :

```
[global]
repo1-path=/data/pgbackrest
repo1-retention-full=2
start-fast=y

[mdb]
pg1-host=10.0.1.59
pg1-path=/data/patroni1

```

7. Describe the issue:

I want to perform PITR on a slave database to restore some deleted data. Now the last backup taken was 8 hours back. There were multiple modifications made in between which were not backed up but those modifications should be present in wal archive location in pbackrest server. My query is how to perform PITR to a time before the accidental deletion was made.

**Comment by Argha-2890** [comment]
For example my last Backup was taken on 29th April 12:00 AM. There were multiple modifications made after that and I want to restore suppose till 3:00AM. Just want to know whether pgbackrest could be used to do that

**Comment by dwsteele** [comment]
Please see https://pgbackrest.org/user-guide.html#pitr.

**Comment by Argha-2890** [comment]
I have gone through the document and performed PITR successfully. But I guess my query was unrelated to pgBackRest. Thanks.

**Comment by dwsteele** [comment]
> But I guess my query was unrelated to pgBackRest

Yes, it's really more to do with PostgreSQL but we have the docs since it is a common ask. Glad you got it working!

**Comment by Argha-2890** [comment]
@dwsteele - I am running a delayed replica (1 hour lag) in my cluster. So, in case I want to start recovery till a particular point of time to recover lost data. Basically I want to bring this delayed slave onto the current timeline. How can I use pgBackRest to do this activity, i.e. what would be my restore_command to perform this recovery?

**Comment by dwsteele** [comment]
If your  replica has not reached the point in time you need then you could just create a recovery.conf file that specifies the target (and removes the delay) then restart the standby to play forward to the target.

If the standby has passed the target already then you'll need to restore and do PITR as normal.
