### ISSUE TITLE
Can I integrate pgbackrest into repmgr?

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#1020]
pgBackRest version:  2.26
PostgreSQL version: 12.2
Operating system/version - CentOS 7
Installed from package
repmgr 5.1

I want to integrate pgbackrest as the default cloning method within repmgr.  I see barman capability is there.  Has anybody had luck trying to make pgbackrest the default cloning method?  I'm sure bunch of folks would rather use pgbackrest, rather than pg_basebackup.

**Comment by dwsteele** [comment]
We don't have any experience with repmgr. For HA we have used Pacemaker/Corosync in the past and now prefer Patroni. pgBackRest works well with both of those solutions.

Please let us know if you get pgBackRest working with repmgr (or don't). It would be good to know one way or the other.

**Comment by MichaelDBA** [comment]
I now have a HA cluster with repmgr and pgbouncer.  I find out a way to register an existing standby that was not cloned by repmgr!  Not in the docs, but i still used their APIs to do it.  That means I can continue to use pgbackrest as my backup solution in this environment.  repmgr has some barman config stuff for repmgr so that the repmgr apis can clone from barman repo.  But I can do that with pgbackrest and still keep my repmgr nodes registered with repmgr.  Interesting but I use pgbouncer as my VIP switch when failover occurs.  There is a plugin within repmgr to execute a custom script upon failover.  That script tunes pgbouncer.ini to point to the newly promoted standby, my VIP logic.

**Comment by dwsteele** [comment]
Good to know, thanks!

**Comment by MichaelDBA** [comment]
[https://planet.postgresql.org/] now has the blog that redirects to here:

[https://elephas.io/working-with-repmgr-using-other-3rd-party-tools-for-setting-up-a-standby/]

**Comment by dwsteele** [comment]
Excellent!
