### ISSUE TITLE
Not able to build pg_backrest from source.

### ISSUE THREAD

**Issue by M-Thirumal** [pgbackrest/pgbackrest#1029]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.26

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu - 20.04

4. Did you install pgBackRest from source or from a package?
Yes

5. Describe the issue:
Not able to build pgbackRest. Getting the following error
```
checking for deflate in -lz... no 
configure: error: library 'z' is required
```
It works in Ubuntu 19.10

**Comment by dwsteele** [comment]
Looks like 20.04 is not installing `libz-dev` unlike prior Ubuntu versions. We'll add that to the package list in the docs:
```
sudo apt-get install make gcc libpq-dev libssl-dev libxml2-dev pkg-config \
       liblz4-dev libzstd-dev libbz2-dev libz-dev
```
