### ISSUE TITLE
Add verify command

### ISSUE THREAD

**Issue by dwsteele** [pgbackrest/pgbackrest#1032]
Add a command to verify the contents of the repository in order to alert users to missing WAL or inconsistent/non-PITR backups that would invalidate a restore.

By the default the command will:

1. Verify that backup/archive.info and their copies are valid
    1. Files exist
    2. Checksums match
    3. PG histories match
2. Verify WAL by reporting:
    1. Checksum mismatches
    2. Missing WAL
    3. Skipped duplicates
    4. Additional WAL skipped
    5. Size matches expected WAL size (**NOTE:** all WAL will be expected to be of the same size - variable WAL sizes are not supported)
3. Verify all manifests/copies are valid
    1. Files exist
    2. Checksums match
4. Verify backup files using manifest
    1. Files exist
    2. Checksums and size match
    3. Ignore files with references when every backup will be validated, otherwise, check each file referenced to another file in the backup set. For example, if request to verify a single incremental backup, then the manifest may have references to files in another (prior) backup which then must be checked.
5. Verify whether a backup is consistent, valid and can be played through PITR
    * Consistent = no gaps (missing or invalid) in the WAL from the backup start to backup end for a single backup (not backup set)
    * Valid = Consistent and all backed up PG files it references (including ones in a prior backup for DIFF and INCR backups) are verified as OK
    * PITR = Consistent, Valid and no gaps in the WAL from the start of the backup to the last WAL in the archive (timeline can be followed)
6. The command can be modified with the following options:
    * --set - only verify the specified backup and associated WAL (including PITR)
    * --no-pitr only verify the WAL required to make the backup consistent.
    * --fast - check only that the file is present and has the correct size.
7. Additional features (which may not be in the initially released version):
    1. WARN on extra files
    2. Check that history files exist for timelines after the first (the first timeline will not have a history file if it is the oldest timeline ever written to the repo)
    3. Check that copies of the manifests exist in backup.history

**Assumptions**

The following must be assumed to be true:
1. There is no access to the PostgreSQL cluster
2. Only the ability to read from the pgBackRest repository exists - no write capability
3. No lock will be taken therefore archiving, backups and expiration will continue and may cause archives or backups to be added or removed during the verification process
4. Archive and Backup info files are required to exist in order for archives and backups to be verified
5. A valid manifest file will be required to verify backup files
6. The archive-start and archive-stop for a single backup (not a set) will never cross a timeline
7. Neither links nor tables spaces will be verified

**Comment by QwerTech** [comment]
+1
We would need this feature

**Comment by Bralva** [comment]
up! +

we've got a error  'unable to open missing file' on s3 repo /repo/backup/blaablacl12/20221205-134902F/pg_data/base/16399/17350.gz during restore --delta

and have this entry in manifest.info file but don't have it on s3 storage!

we saw that we have 17350.1.gz but in manifest we have

```
pg_data/base/16399/17350={"checksum":"90d64467eca0543df205398f51b508c5d4b8ffb7","checksum-page":true,"repo-size":251632013,"size":1073741824,"timestamp":1670232104}
pg_data/base/16399/17350.1={"checksum":"c2d1074120fd19604cfc4648ab8598f119f4dc87","checksum-page":true,"repo-size":50077330,"size":226361344,"timestamp":1670237515}

```

**Comment by dwsteele** [comment]
The verify command was released in https://pgbackrest.org/release.html#2.39. This issue should have been closed then.

@Bralva Please don't piggyback on old issues. If you are having a problem you can submit a new issue with all required information.
