### ISSUE TITLE
Backup repo on standby server?

### ISSUE THREAD

**Issue by kmatt** [pgbackrest/pgbackrest#1033]
Please provide the following information when submitting an issue :

1. pgBackRest version: 2.26
2. PostgreSQL version: 11
3. Operating system/version: CentOS 7
4. Did you install pgBackRest from source or from a package? yum

Main server:

```
[main]
pg1-path=/localdata/pgdata11

[global]
archive-timeout=180
compress-type=lz4
log-level-file=detail
repo1-host=dwh2.xxx.net
repo1-host-user=postgres
```

Standby / repo server:

```
[main]
pg1-host=dwh1.xxx.net
pg1-path=/localdata/pgdata11

[global]
archive-timeout=180
compress-type=lz4
repo1-host-user=postgres
repo1-path=/backup/pgbackrest
repo1-retention-full=10
```

7. Describe the issue:

Attempting to configure the standby host to be both the repo server and the hot standby - limited to two machines in this case.

A `backup` run on the repo server works as expected, but I'm uncertain how to configure for hot standby on the same machine. 

Have gone through section 17 in the docs, but I seem to wind up with either repo or standby, but not both. Uncertain if the stanza is incomplete, or they cannot be combined:

```
dwh2 $ pgbackrest --stanza=main --delta --type=standby restore
ERROR: [072]: restore command must be run on the PostgreSQL host
```

**Comment by kmatt** [comment]
I will add that I have not been successful in performing a single restore to a Postgres instance on the repo server for similar reasons.

**Comment by MichaelDBA** [comment]
Looks like you are running the pgbackrest restore from the standby/repo host, but you are pointing the primary host in your stanza on the standby: pg1-host=dwh1.xxx.net.

**Comment by kmatt** [comment]
@MichaelDBA That makes sense. Would this imply that the backup should be run on the master server? I probably got into that config state by running the backup command from the repo host.

**Comment by kmatt** [comment]
Using this as a guide: https://info.crunchydata.com/blog/pgbackrest-performing-backups-on-a-standby-cluster

I reversed the backup roles, placing the repo path on the master running the backup command there, then running the restore on the standby. This allows the restore to launch, but it would still be preferable to locate the backup off of the primary host:

Master (dwh1):

```
[global]
archive-timeout=180
compress-type=lz4
log-level-file=detail
repo1-path=/backup/pgbackrest

[main]
pg1-path=/localdata/pgdata11
pg1-port=5439
```

Standby (dwh2):

```
[global]
archive-timeout=180
compress-type=lz4
repo1-host=dwh1.stackpath.net
repo1-host-user=postgres
repo1-path=/backup/pgbackrest
repo1-retention-full=10
delta=y

[main]
pg1-path=/localdata/pgdata11
pg1-port=5439
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=dwh1.xxx.net user=postgres
recovery-option=recovery_target_timeline=latest
```

**Comment by MichaelDBA** [comment]
I think **backup-standby=y** should be in your main stanza if you are backing up from the standby.

**Comment by kmatt** [comment]
I seem to have a working set of configs. If there is nothing wrong from a best practices standpoint I can close the issue.

Master:

```
[global]
archive-timeout=180
compress-type=lz4
log-level-file=detail
repo1-path=/backup/pgbackrest
repo1-host=dwh2.xxx.net
repo1-host-user=postgres

[main]
pg1-path=/localdata/pgdata11
```

Standby:

```
[global]
archive-timeout=180
compress-type=lz4
repo1-host-user=postgres
repo1-path=/backup/pgbackrest
repo1-retention-full=10
# comment out for restore?
#backup-standby=y
delta=y

[main]
pg1-host=dwh1.xxx.net
pg1-host-user=postgres
pg1-path=/localdata/pgdata11
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=dwh1.xxx.net user=postgres
recovery-option=recovery_target_timeline=latest
```

**Comment by dwsteele** [comment]
These look reasonable, but I will caution you that asymmetric configurations (i.e., primary and standby are different) are harder to maintain and can cause difficulties during failover.
