### ISSUE TITLE
pgbackrest recovery interrupted multiple times and taking long time  

### ISSUE THREAD

**Issue by narendrapostgresdba** [pgbackrest/pgbackrest#1035]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.26

2. PostgreSQL version:  source (10.4) target (10.12)
 
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

source server OS CentOS Linux release 7.6.1810  (sydcosafpp001.enterprisenet.org)
target server OS  CentOS Linux release 7.7.1908 (SYDCOSAPPP001.ENTERPRISENET.ORG)
4. Did you install pgBackRest from source or from a package?

installed with package 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

[global]
repo1-host=sydcosafpp001.enterprisenet.org
repo1-host-user=postgres
repo1-host-config=/etc/pgbackrest.conf
repo1-path=/pgBACKUP/A4_sydcosafpp001
process-max=10
archive-async=y
archive-get-queue-max=104857600

[A4_sydcosafpp001]
pg1-path=/Postgres/pgDATA/data

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

we are trying to restore postgres instance of size 1.9TB . Restore completed . But recovery taking too much time and it interrupted multiple times .

2020-05-09 21:11:36.352 AEST,,,8590,,5eb60c9a.218e,6338,,2020-05-09 11:51:22 AEST,1/0,0,FATAL,XX000,"WAL ends before end of online backup",,"All WAL generated while online backup was taken must be available at recovery.",,,,,,,""
2020-05-09 21:11:37.072 AEST,,,8587,,5eb60c99.218b,1,,2020-05-09 11:51:21 AEST,,0,LOG,00000,"startup process (PID 8590) exited with exit code 1",,,,,,,,,""
2020-05-09 21:11:37.072 AEST,,,8587,,5eb60c99.218b,2,,2020-05-09 11:51:21 AEST,,0,LOG,00000,"terminating any other active server processes",,,,,,,,,""

to apply logs of size 50GB , it is taking more time than the restore time 

<img width="738" alt="recovery error" src="https://user-images.githubusercontent.com/65272799/81776388-51a2ee80-950c-11ea-9903-306b817d0104.PNG">

**Comment by dwsteele** [comment]
The recovery process in Postgres is single-process while pgBackRest is multi-process, so it's not unusual for recovery to take longer than restore. Improving recovery speed would require changes in core Postgres.

I'm curious about this, though:
```
WAL ends before end of online backup
```
What does your `recovery.conf` file look like? I imagine the interruption is because it is having trouble getting archive files for some reason. Can you also post the contents of `/var/log/pgbackrest/A4_sydcosafpp001-archive-async.log`?

**Comment by narendrapostgresdba** [comment]
Hello David ,

Thanks for checking this . unfortunately we don't have recovery file now .
I am attaching the archive  get async  log file .

Regards,
Narendra

**Comment by dwsteele** [comment]
I don't see an attachment?

**Comment by narendrapostgresdba** [comment]
I am attaching it 
[A4_sydcosafpp001-archive-get-async.log](https://github.com/pgbackrest/pgbackrest/files/4629392/A4_sydcosafpp001-archive-get-async.log)

**Comment by dwsteele** [comment]
The only thing I can see is that `archive-get` is running pretty slowly. Not possible to see why from this log but it's probably slow network/storage. Also, setting `process-max=10` for `archive-get` is pretty excessive and might be causing contention. A higher setting for `archive-get-queue-max` would probably be beneficial -- for performance I would recommend 1GB.

Even so, it mostly seems to be keeping up but there were occasional slowdowns that would cause `archive-timeout` to expire. The default is 60 seconds, which is rarely an issue, but you can bump that up to whatever you want, e.g. `archive-timeout=300`.

So, for better performance and reliability I would recommend trying:
```
process-max=4
archive-get-queue-max=1g
archive-timeout=300
```
These tweaks are normally not needed but you appear to have high latency in your storage/network.
