### ISSUE TITLE
unable to create stanza on a dedicate repository server - ERROR [037]

### ISSUE THREAD

**Issue by mfishzon19** [pgbackrest/pgbackrest#1036]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

**sudo -u pgbackrest pgbackrest
pgBackRest 1.25 - General help**

2. PostgreSQL version:
**PostgreSQL 11.7 (Ubuntu 11.7-2.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

dedicated repository - **Ubuntu 18.04.4 LTS**
postgres db server -  **Ubuntu 18.04.4 LTS**

4. Did you install pgBackRest from source or from a package?

**apt-get**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) - 

repository => pgbackrest.conf
**[infra]
pg1-host=172.31.4.207
pg1-path=/var/lib/postgresql/11/main

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y**

pg_host => pgbackrest.conf
**[infra]
pg1-path=/var/lib/postgresql/11/main

[global]
log-level-file=detail
repo1-host=172.31.10.56**

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

**archive_command = 'pgbackrest --stanza=infra archive-push %p'      
archive_mode=on
listen_addresses='*'
max_wall_senders = 3
wal_level = replica
port = 5432**   

    - errors in the postgresql log file before or during the time you experienced the issue

**ERROR: [099]: expected '{' at ''
LOG:  archive command failed with exit code 99
DETAIL:  The failed archive command was: pgbackrest --stanza=infra archive-push pg_wal/000000020000000200000007
WARNING:  archiving write-ahead log file "000000020000000200000007" failed too many times, will try again later**

This is the same pg-host I used for testing a single host installation. I made sure I stopped and deleted a stanza. Could this be a problem?

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

infra-stanza-create.log - 

2020-05-14 19:05:15.315 P00   INFO: stanza-create command begin 1.25: --config=/etc/pgbackrest/pgbackrest.conf --db1-host=172.31.4.207 --db1-path=/var/lib/postgresql/11/main --log-level-console=info --stanza=infra
2020-05-14 19:05:15.973 P00  ERROR: [031]: remote process on '172.31.4.207' terminated unexpectedly [031]: ERROR: [031]: invalid option '--command=stanza-create'
2020-05-14 19:05:15.974 P00  ERROR: [031]: remote process on '172.31.4.207' terminated unexpectedly [031]: ERROR: [031]: invalid option '--command=stanza-create'
2020-05-14 19:05:15.974 P00   INFO: stanza-create command end: aborted with exception [031]

7. Describe the issue:
while trying to create stanza:
sudo -u pgbackrest pgbackrest --stanza=infra --log-level-console=debug stanza-create

ERROR [037]: : stanza-create command requires option: db1-path
HINT: does this stanza exist?

tried adding g the --config parameter - same result

Any ideas? 

Thanks you.

**Comment by dwsteele** [comment]
It looks like you may be running an old version of pgBackRest on `172.31.4.207`. Try running `pgbackrest version` on that host. The versions on all hosts must match.

**Comment by mfishzon19** [comment]
thank you, the reposistory server was the only one running version 1, both pg_primary and pg_standby where on version 2. the issue can now be closed. thanks for your help again.

**Comment by mfishzon19** [comment]
resolved
