### ISSUE TITLE
Issues while restoring a specific full backup on a new server  

### ISSUE THREAD

**Issue by BhargavKamineni** [pgbackrest/pgbackrest#1042]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:pgBackRest 2.07

2. PostgreSQL version:10.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
databaseserver: NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"

Restore server:NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
repo-path=/fs-b01-a/backups
repo1-retention-full=1
start-fast=y
process-max=4
repo1-cipher-pass=generate cipher
repo1-cipher-type=aes-256-cbc

[tpgpts1na]
db-path=/fs-a01-a/databases/tpgpts1eu
db-port=8192

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

    - errors in the postgresql log file before or during the time you experienced the issue

pgbackrest --stanza=tpgpts1na --log-level-console=info --db-path=/tmp/red/ --set=220200511-104739F restore --delta
2020-05-19 11:47:42.891 P00   INFO: restore command begin 2.07: --delta --log-level-console=info --pg1-path=/tmp/red/ --process-max=4 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/fs-b01-a/backups --set=220200511-104739F --stanza=tpgpts1na
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/tmp/red/' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
ERROR [075]: : backup set 220200511-104739F is not valid
2020-05-19 11:47:43.024 P00   INFO: restore command end: aborted with exception [075]

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Hi Team,

backup setup: 

Backrepository exits on the database server and we are taking full and incr backups and we have a script to push these backups(backup + backinfo file +arcive info file) to s3 bucket (we are not using s3 backup option of backrest)

Now while restoring a full backup by fetching from s3 on to  a new server we are observing below error

 pgbackrest --stanza=tpgpts1na --log-level-console=info --db-path=/tmp/red/ --set=220200511-104739F restore --delta
2020-05-19 11:47:42.891 P00   INFO: restore command begin 2.07: --delta --log-level-console=info --pg1-path=/tmp/red/ --process-max=4 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/fs-b01-a/backups --set=220200511-104739F --stanza=tpgpts1na
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/tmp/red/' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
ERROR [075]: : backup set 220200511-104739F is not valid
2020-05-19 11:47:43.024 P00   INFO: restore command end: aborted with exception [075]

[backrest_conf.txt](https://github.com/pgbackrest/pgbackrest/files/4650208/backrest_conf.txt)

**Comment by BhargavKamineni** [comment]
Hi Team,

Any help regarding the above issue?

**Comment by mattbunter** [comment]
I am not with the pgbackrest team, but to confirm that you see the backups from your new machine, try : 

pgbackrest --stanza=tpgpts1na --log-level-console=info info

If you cannot, then there might be something in pgbackrest.conf that needs adjusting.

**Comment by dwsteele** [comment]
If it's not in info restore won't see it. Copying the repo can be tricky if you are only trying to copy parts of it. Any reason why you are not letting pgBackRest manage the repo in S3? It would be faster and more reliable.

**Comment by BhargavKamineni** [comment]
We are in process of moving it to backrest managed s3, But David if we want to copy parts of repo, for instance, a old full backup on to a new server what are the files needs to e taken care ?
My assumption:
1) backup.info file  
2)Archive file

In my case these two files are present and i am trying to restore by setting up same pgbackrest config 

Any other  files/steps i am missing here ?

**Comment by dwsteele** [comment]
Well, you'd need the backups that you want to restore and any WAL associated with the backup (unless you used `archive-copy` when you did the backup). If the backup has dependencies (i.e., on FULL, DIFF, etc.) then you would also need to copy all the dependencies.

The only safe and reliable way to do what you want is to clone the entire repo. We don't have any procedures to copying parts of repos at this time.

**Comment by BhargavKamineni** [comment]
Thanks David for the information
