### ISSUE TITLE
Q : Best practices One Primary, Three standbys

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#1045]
1. pgBackRest version:
2.26
2. PostgreSQL version:
12
3. Operating system/version 
CentOS Linux release 7.5.1804 (Core)
4. Did you install pgBackRest from source or from a package?
RPM

QUESTION : on the standbys (which are NOT backedup) how much pgbackrest configuration should be done to ensure that if there is a switchover, normal backups and pushing to the correct directory is OK?

I am tempted to think that only an up to date pgbackrest.conf is needed, without even creating a stanza.

For info : we are using S3 and each node will have it's own bucket (so master with be PG1, standby will have PG2 etc.).

**Comment by dwsteele** [comment]
> we are using S3 and each node will have it's own bucket

The primary and standbys are logically all the same database and should share a stanza and bucket. For instance, you can restore from backups to create a new standby if one fails. See https://pgbackrest.org/user-guide-centos7.html#replication

> on the standbys (which are NOT backedup) how much pgbackrest configuration should be done

All of it. The configurations should be as symmetric as possible so there's little or no reconfiguration to do on failover. Again, all the standbys should be configured with the same bucket as the primary.

**Comment by mattbunter** [comment]
OK, I'll have the same pgbackrest.conf on each server. We'll backup on the primary with the same scripts on the standbys but with an 'is_in_recovery' check so that only the primary is getting backed up. 

We handle standby creation using repmgr (we've used it for a while now).

**Comment by mattbunter** [comment]
on the standbys (which are NOT backedup) how much pgbackrest configuration should be done

All of it. The configurations should be as symmetric as possible so there's little or no reconfiguration to do on failover. Again, all the standbys should be configured with the same bucket as the primary.

Just to clarify your sentence above, I haven't created a stanza on the standbys. If I need to could you confirm, and explain why I need to?

**Comment by dwsteele** [comment]
The primary and standbys share one stanza. They are logically one database system.

So what I'm talking is just configuration. Using the same configuration on each host does not equal running `stanza-create` on each host.

**Comment by mattbunter** [comment]
Thankyou for the reply. I appreciate the clarification.
