### ISSUE TITLE
QUESTION : Logrotate and pgbackrest

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#1056]
1. pgBackRest version:
2.26
2. PostgreSQL version:
12
3. Operating system/version 
CentOS 7.7
4. Did you install pgBackRest from source or from a package?
Yum/RPM

I would like to use the following logrotate setting for STANZA-backup and STANZA-expire : 

/var/log/pgbackrest/pgsql1-backup.log {
        missingok
        compress
        rotate 26
        maxsize 100M
        weekly
        create 0600 postgres postgres
        endscript
    }
	
/var/log/pgbackrest/pgsql1-expire.log {
        missingok
        compress
        rotate 26
        maxsize 100M
        weekly
        create 0600 postgres postgres
        endscript
    }

Is this OK? Perms for the logs are 640 (default install using RMPs/Yum. Our security people don't like even group reads, they want 600.

Thanks in advance.

**Comment by dwsteele** [comment]
This is what comes with the Debian package and seems to work fine:
```
/var/log/pgbackrest/*.log {
       weekly
       rotate 10
       delaycompress
       compress
       compressoptions -9
       notifempty
       missingok
}

**Comment by mattbunter** [comment]
Perfect, thank you for the clarification.
