### ISSUE TITLE
repo-retention-full-type-option can be wrong in documentation

### ISSUE THREAD

**Issue by huseynsnmz** [pgbackrest/pgbackrest#1057]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.27

2. PostgreSQL version:
12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.8.2003 (Core)

4. Did you install pgBackRest from source or from a package?
PostgreSQL RPM Repository package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

```
[global]
repo1-path=/var/lib/pgbackrest
repo1-host-user=postgres
log-level-console=info
log-level-file=detail

[primary]
pg1-path=/var/lib/pgsql/12/data
pg1-port=5432
compress=n
repo1-retention-full=1
repo1-retention-full-type=30
```

7. Describe the issue:

When I look at the documentation, it says in full retention type option example like:

https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-full-type

> default: count
> example: repo1-retention-full-type=30

but when I write it, I am getting the following error:

`ERROR: [032]: '30' is not allowed for 'repo1-retention-full-type' option`

I believe it needs to be "time" in the documentation:

```
default: count
example: repo1-retention-full-type=time
```

**Comment by dwsteele** [comment]
Good catch! Fixed at 9efbafc84c.
