### ISSUE TITLE
Causes of "WAL segment _ was not archived before the _ms timeout" ?

### ISSUE THREAD

**Issue by kmatt** [pgbackrest/pgbackrest#1059]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.27

2. PostgreSQL version: 11.7

3. Operating system/version: CentOS 7.7.1908

4. Did you install pgBackRest from source or from a package? yum

5. Please attach the following as applicable: In comments

7. Describe the issue:

Temporarily using standby as repo host (until dedicated repo server available). For a few days all was working with nightly full backups and streaming replication. Backups started failing with the error example below, and same occurred attempting differential and incremental backups.

Deleted stanza, recreated backup configs and full backup and restore on standby successful, but first subsequent diff backup attempt failed.

pgbackrest `archive-timeout` > Postgres `archive_timeout` and `checkpoint_timeout`

No errors are recorded in the Postgres logs, streaming is not interrupted. Trying to determine the cause.

```
...
2020-05-31 17:32:32.068 P04   INFO: backup file dwh1.xxx.net:/localdata/pgdata11/base/29433997/2508970456 (0B, 100%)
2020-05-31 17:32:32.068 P02   INFO: backup file dwh1.xxx.net:/localdata/pgdata11/base/29433997/2507623786 (0B, 100%)
2020-05-31 17:32:32.068 P01   INFO: backup file dwh1.xxx.net:/localdata/pgdata11/base/29433997/2507601802 (0B, 100%)
2020-05-31 17:32:32.088 P00   INFO: diff backup size = 136.2GB
2020-05-31 17:32:32.088 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2020-05-31 17:32:32.292 P00   INFO: backup stop archive = 000000010000263B00000025, lsn = 263B/25CAE2E0
2020-05-31 17:32:32.412 P00   INFO: check archive for segment(s) 000000010000263A000000F8:000000010000263B00000025
ERROR: [082]: WAL segment 000000010000263A000000F8 was not archived before the 300000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
2020-05-31 17:37:33.301 P00   INFO: backup command end: aborted with exception [082]
```

**Comment by kmatt** [comment]
Primary:

```
$ cat /etc/pgbackrest.conf
[global]
archive-timeout=300
compress-type=lz4
process-max=4
log-level-console=info
log-level-file=detail
repo1-host=dwh2.xxx.net
repo1-host-user=postgres
repo1-path=/backup/pgbackrest
repo1-retention-full=1
start-fast=y

[main]
pg1-path=/localdata/pgdata11
pg1-port=5432
```

Standby:
```
$ cat /etc/pgbackrest.conf
[global]
archive-timeout=300
compress-type=lz4
process-max=4
log-level-console=info
log-level-file=detail
repo1-host-user=postgres
repo1-path=/backup/pgbackrest
repo1-retention-full=1
#start-fast=y
delta=y
#backup-standby=y

[main]
# Comment out hostname for full restore on standby (?)
pg1-host=dwh1.xxx.net
pg1-host-user=postgres
pg1-port=5432
pg1-path=/localdata/pgdata11
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=dwh1.xxx.net port=5432 user=postgres
recovery-option=recovery_target_timeline=latest
```

**Comment by kmatt** [comment]
Primary PG config:

```
wal_level = replica
wal_compression = on
checkpoint_timeout = 2min
archive_mode = on
archive_command = 'pgbackrest --stanza=main archive-push %p'
archive_timeout = 60
max_wal_senders = 10
min_wal_size = 256MB
max_wal_size = 4GB
```

**Comment by dwsteele** [comment]
```
HINT: check the PostgreSQL server log for errors.
```
Any errors should be in the PostgreSQL log since it is the process calling `archive-push`.

**Comment by dwsteele** [comment]
Also, hard to tell from here, but maybe the hosts are now pointing at two different repos? So, you are archiving to one, but trying to backup to another.

Locating the repo on the standby is tricky to configure and we don't recommend it, but it is possible.

**Comment by kmatt** [comment]
@dwsteele No errors in the Postgres logs at all. The tricky part is this was working, and I'm trying to determine what changed that stopped it. With my configs versioned in a git repo, I can't see what changed there, but not eliminating anything yet.

Noting that repo on standby is a non-optimal and temporary config until I can get my dedicated repo server online, I may not be clear on on the docs:

> but maybe the hosts are now pointing at two different repos?

Which segments would that be defined in? The [global] or [stanza-name] sections?

And which keys? `repo1-` ?

Asking since I have the repo server name in `repo1-host`, `repo1-host-user` and `repo-1-path` on the primary as it points to the standby server, but no `host` key on the standby host since the repo is local to that machine.

**Comment by kmatt** [comment]
No errors were logged with any `archive-` commands.

I did notice that when an error was logged on backup like:

    `ERROR: [082]: WAL segment 000000010000263A000000F8 was not archived before the 300000ms timeout`

on the standby was logging segments that assuming a sequence were far behind the above number:

    `INFO: pushed WAL file '000000010000261B00000030' to the archive`

I increased pgbackrest.conf to `archive-timeout=10000` and once the standby caught up, the backup logged a successful finish.

It appears that during the backup, segments were generating at a rate requiring a long `archive-timeout`. Does that seem likely the problem, and would it indicate that PostgreSQL should be configured with a larger `max_wal_size` or other parameters to slow the rate (considering recovery time on a full restore is not a primary concern)?

**Comment by kmatt** [comment]
@dwsteele Following up on the above, it appears that backups are waiting for WAL segments "far in the future". 
Primary:

    2020-06-02 16:30:39.680 P00   INFO: pushed WAL file '00000001000026F400000004' to the archive

Which is far behind the segment the backup almost 90 minutes ago is looking for:

`pgbackrest --type=diff backup`:

    2020-06-02 14:06:53.748 P00   INFO: check archive for segment(s) 000000010000271D000000DF:000000010000271F00000052

What factors cause the backup to look for a segment that far ahead in the sequence?

**Comment by kmatt** [comment]
Did catch one error logged on the primary:

    2020-06-02 16:56:35 GMT [9589]: [1-1] [local] user=postgres,db=template1,client=[local],app=[unknown] ERROR:  could not stat directory "pg_wal": No such file or directory

`pg_wal` does exist in the cluster. Will run again with debug log level to see if I can spot what full path its attempting to use.

**Comment by kmatt** [comment]
Replaced with #1060 which uses a simpler configuration and addresses a specific question.
