### ISSUE TITLE
Pgbackrest- ERROR: [056]: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by Dlalotra** [pgbackrest/pgbackrest#1063]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1.      pgBackRest version: 2.15-1

2.      PostgreSQL version: PostgreSQL 10.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

3.      Operating system/version - Red Hat Enterprise Linux Server release 7.7 (Maipo)

4.      Did you install pgBackRest from source or from a package?
From RPM package downloaded from "https://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgbackrest-2.15-1.rhel7.x86_64.rpm".

5.      Please attach the following as applicable:

pgbackrest.conf file(s)
bash-4.2$ cat pgbackrest.conf
[global]
repo1-path=/pgbackrest/icl-opatch-cl21_PG
log-path=/optware/pgsql-10/pgbackrest/log
spool-path=/optware/pgsql-10/pgbackrest/spool

[icl-opatch-cl21_PG_stanza]
pg1-path=/optware/pgsql-10/data
pg1-port=1524
pg1-socket-path=/optware/pgsql-10/data

postgresql.conf settings applicable to pgBackRest -
bash-4.2$ grep archive postgresql.conf
archive_command = 'pgbackrest --stanza=icl-opatch-cl21_PG_stanza --config=/optware/pgsql-10/pgbackrest/pgbackrest.conf archive-push %p'
archive_mode = on

·        `pg_hba.conf-
bash-4.2$ cat pg_hba.conf
#TYPE DATABASE USER ADDRESS METHOD
#"local" is for Unix domain socket connections only
local all all scram-sha-256
#IPv4 local connections:
#host all all 127.0.0.1/32 trust
#IPv6 local connections:
#ost all all ::1/128 trust
#Allow replication connections from localhost, by a user with the
#replication privilege.
#local replication all trust
host all all 127.0.0.1/32 scram-sha-256
host all all 0.0.0.0/0 md5
#host all all 0.0.0.0/0 scram-sha-256
host all all 0.0.0.0/0 scram-sha-256
host all all 0.0.0.0/0 scram-sha-256

log file in /var/log/pgbackrest for the commands run (e.g. /var/log/pgbackrest/mystanza_backup.log)
bash-4.2$ tail icl-opatch-cl21_PG_stanza-backup.log
2020-06-09 06:45:56.725 P00 ERROR: [056]: fe_sendauth: no password supplied
2020-06-09 06:45:56.728 P00 INFO: backup command end: aborted with exception [056]

-------------------PROCESS START-------------------
2020-06-09 07:00:42.626 P00 INFO: backup command begin 2.15: --config=/optware/pgsql-10/pgbackrest/pgbackrest.conf --log-level-stderr=info --log-path=/optware/pgsql-10/pgbackrest/log --pg1-path=/optware/pgsql-10/data --pg1-port=1524 --pg1-socket-path=/optware/pgsql-10/data --repo1-path=/pgbackrest/icl-opatch-cl21_PG --stanza=icl-opatch-cl21_PG_stanza --type=incr
2020-06-09 07:00:42.626 P00 WARN: option repo1-retention-full is not set, the repository may run out of space
HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
2020-06-09 07:00:43.140 P00 INFO: last backup label = 20200608-035030F_20200608-040054I, version = 2.15
2020-06-09 07:00:43.149 P00 ERROR: [056]: fe_sendauth: no password supplied
2020-06-09 07:00:43.151 P00 INFO: backup command end: aborted with exception [056]
bash-4.2$

Describe the issue:
Pgbackrest and PostgreSQL instance are installed on the same host. When the local connection setting is set to 'trust' in pg_hba.conf, pgbackrest is able to run with backup command without any issues. But when the setting is changed from 'trust' to 'md5' or 'scram-sha-256' pgbackrest fails with error- "ERROR: [056]: fe_sendauth: no password supplied".
Q1. How can I supply the password while running pgbackrest backup command when pg_hba entry for local are 'md5' or 'scram-sha-256' ? I do not want to use 'trust' or 'peer' or 'ident'.
Q2. Does pgbackrest login into the database for taking backups or other operations? I couldn't find it documented anywhere.
Q3. Can a different user other than 'postgres' be used for backup? Does this user needs to exist both at the OS level and inside database? What permissions are required inside database?

Please help

**Comment by dwsteele** [comment]
*Note*: 2.15 is a pretty old version of pgbackrest. We recommend you upgrade to 2.27.

> Q1. How can I supply the password while running pgbackrest backup command when pg_hba entry for local are 'md5' or 'scram-sha-256' ? I do not want to use 'trust' or 'peer' or 'ident'.

You can supply a password using a .pgpass file, see https://www.postgresql.org/docs/current/libpq-pgpass.html. That said, `peer` authentication is generally the best solution.

> Q2. Does pgbackrest login into the database for taking backups or other operations? I couldn't find it documented anywhere.

Yes, all backups must connect to the database. See https://www.postgresql.org/docs/current/continuous-archiving.html#BACKUP-LOWLEVEL-BASE-BACKUP.

> Q3. Can a different user other than 'postgres' be used for backup? Does this user needs to exist both at the OS level and inside database? What permissions are required inside database?

On PG10 the OS user must be `postgres` but the database user can be custom. On PG11, both the OS user and database user can be custom, but you'll need to `initdb -g` or add group read/write to the cluster manually: https://www.postgresql.org/docs/11/app-initdb.html.  Here's an example of creating a backup user on PG11:
```
create user pgbackrest;
grant pg_read_all_settings to pgbackrest;
grant execute on function pg_start_backup(text, boolean, boolean) to pgbackrest;
grant execute on function pg_stop_backup(boolean, boolean) to pgbackrest;
grant execute on function pg_switch_wal() to pgbackrest;
grant execute on function pg_create_restore_point(text) to pgbackrest;
```
We are planning to document this process in the user guide but this is the basic idea. We don't feel it is worthwhile to logon as a separate user in PG <= 10 since the OS user must still be `postgres`.

**Comment by Dlalotra** [comment]
Thanks for the quick response.
Q1. If I create a backup user inside database and grant above permissions inside my PostgreSQL V10.11 instance,  will I be able to perform all backup and restore related operations using Pgbackrest which could been  possible otherwise with postgres database user?

Q2. Do I need permissions on all Backup Control Functions for achieving above or the one given earlier is sufficient?

Table 9.79. Backup Control Functions
https://www.postgresql.org/docs/10/functions-admin.html

I will perform the testing and get back.

Thanks.

**Comment by Dlalotra** [comment]
I could see pgbackrest user can create tables with the above granted permissions. Can you please help to understand what all other activities this user can perform in database? Any way we can restrict it?

Thanks.

**Comment by dwsteele** [comment]
Unfortunately, by default all users can create objects in the `public` schema. The `pgbackrest` user is not special in this regard.

See https://blog.dbi-services.com/avoiding-access-to-the-public-schema-in-postgresql/ for details.

**Comment by Dlalotra** [comment]
Alright. Any other permissions this pgbackrest user will have apart from what we have granted above and create table? Can this user be considered as superuser in a way because it can read all system wide settings?

Thanks.

**Comment by dwsteele** [comment]
To be clear, the user does not have create object permissions, the public schema does. So it applies to every other user in your system that has connect privileges to that database.

Certainly assigning `pg_` roles, etc. gives some super user capabilities. That's why we use a very specific list which we consider to be relatively benign. It is still a lot better than running as the actual superuser.

**Comment by Dlalotra** [comment]
Just discovered a new thing. While doing restore using Pgbackrest, database is getting recovered to the latest state restoring all the tables which were part/not part of the last backup by replaying of the WAL files. 
But when the restore is ran second time, it is still only restoring /recovering the same tables again as after first restore. Tables created after the first restore are lost. Any idea for this strange behaviour?

Thanks.

**Comment by dwsteele** [comment]
That's standard for PITR in PG10. Your backup was done on timeline 1 so it follows timeline 1 on the second restore instead of timeline 2 which was created by the first restore.

If you want to follow the timeline of the last restore then specify `--target-timeline=latest`. This is the default behavior on PG >= 11.
