### ISSUE TITLE
Restore to a new Stanza for backup/restore test

### ISSUE THREAD

**Issue by gbryant200** [pgbackrest/pgbackrest#1069]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

## 3. Operating system/version:

- Primary: Ubuntu 18.04

- Standby: Ubuntu 18.04

- Repo: Ubuntu 18.04

## 4. Did you install pgBackRest from source or from a package?
initially from source (2.25) but updated by package (to 2.27)

### Primary
**pgbackrest.conf** 
```
[north_anneal]
pg1-path=/data/postgresql/11/main

[global]
log-level-file=detail
repo1-retention-diff=2
repo1-retention-full=4
repo1-host=na-backup

[global:archive-push]
compress-level=3
```
**postgresql.conf**
```
data_directory = '/data/postgresql/11/main'
archive_mode = on
archive_command = 'pgbackrest --stanza=north_anneal archive-push %p' 
listen_addresses = '*'
#max_wal_senders = 10 --> default of 10
#wal_level = replica --> default
port = 5432
```
### Standby
**pgbackrest.conf**
```
[north_anneal]
pg1-path=/data/postgresql/11/main
recovery-option=primary_conninfo=host=na-db1 port=5432 user=replicator

[global]
log-level-file=detail
repo1-host=na-backup
```
**postgresql.conf**
```
data_directory = '/data/postgresql/11/main'
archive_mode = on
archive_command = 'pgbackrest --stanza=north_anneal archive-push %p' 
listen_addresses = '*'
#max_wal_senders = 10 --> default of 10
#wal_level = replica --> default
port = 5432
```
### Repo
**pgbackrest.conf** 
```
[north_anneal]
pg1-host=na-db1
pg1-path=/data/postgresql/11/main
pg2-host=na-db2
pg2-path=/data/postgresql/11/main

[na_backup]
pg1-path=/data/postgresql/11/na_backup_test

[global]
repo1-path=/data/pgbackrest
repo1-retention-full=2
start-fast=y

[global:backup]
# finish backup from standby
backup-standby=y
# number of CPUs to use for backup
process-max=2

[global:restore]
# number of CPUs to use for restore
process-max=3
```
**pgbackrest user crontab** 
```
# full backup once/day at 23:08; the pgbackrest configuration
# has the retention settings for backups /etc/pgbackrest/pgbackrest.conf
08 23 * * * pgbackrest --type=full --stanza=north_anneal backup

# differential backup every 2 hours (after a full backup)
0 */2 * * * pgbackrest --type=diff --stanza=north_anneal backup
```
## 7. Describe the issue:
Everything was working from a 'backup' standpoint.  I was getting a full-backup on my **Repo** once/day with differentials every 2 hours.

I wanted to test my backup by restoring it on the **Repo** so I installed the same version of PostgreSQL on my **Repo**.

Now I have permission errors when I try to run a backup and I can't create the new [na_backup] stanza.

I've added the `postgres` user to the `pgbackrest` group and vice versa but apparently there are issues with group access to specific directories.

When I attempt to run a backup as the pgbackrest user:
`pgbackrest@na-backup:~$ pgbackrest --stanza=north_anneal --log-level-console=info --type=full backup`

```
2020-06-10 17:00:38.866 P00   INFO: backup command begin 2.27: --backup-standby --log-level-console=info --pg1-host=na-db1 --pg2-host=na-db2 --pg1-path=/data/postgresql/11/main --pg2-path=/data/postgresql/11/main --process-max=2 --repo1-path=/data/pgbackrest --repo1-retention-full=2 --stanza=north_anneal --start-fast --type=full
ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/north_anneal-backup.lock': Permission denied
       HINT: does the user running pgBackRest have permissions on the '/tmp/pgbackrest/north_anneal-backup.lock' file?
2020-06-10 17:00:38.866 P00   INFO: backup command end: aborted with exception [050]
```

Trying to add the new stanza as the pgbackrest user:
`pgbackrest --stanza=na_backup --log-level-console=info stanza-create`

```
2020-06-10 17:05:33.860 P00   INFO: stanza-create command begin 2.27: --log-level-console=info --pg1-path=/data/postgresql/11/na_backup_test --repo1-path=/data/pgbackrest --stanza=na_backup
ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/na_backup-archive.lock': Permission denied
       HINT: does the user running pgBackRest have permissions on the '/tmp/pgbackrest/na_backup-archive.lock' file?
2020-06-10 17:05:33.870 P00   INFO: stanza-create command end: aborted with exception [050]
```
It appears that installing PostgreSQL after pgBackRest is installed, the /tmp/pgbackrest directory ownership changes to postgres:postgres.

Changing the ownership of /tmp/pgbackrest to pgbackrest:pgbackrest corrected the ability to run a backup (at least manually).

Trying to create the new stanza as the pgbackrest user:
`pgbackrest --stanza=na_backup --log-level-console=info stanza-create`

```
2020-06-10 17:10:53.493 P00   INFO: stanza-create command begin 2.27: --log-level-console=info --pg1-path=/data/postgresql/11/na_backup_test --repo1-path=/data/pgbackrest --stanza=na_backup
WARN: unable to check pg-1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432': FATAL:  role "pgbackrest" does not exist
ERROR: [056]: unable to find primary cluster - cannot proceed
2020-06-10 17:10:53.496 P00   INFO: stanza-create command end: aborted with exception [056]
```

I added the `pg1-user=postgres` to the stanza definition:
```
[na_backup]
pg1-path=/data/postgresql/11/na_backup_test
pg1-user=postgres
```
`pgbackrest --stanza=na_backup --log-level-console=info stanza-create`

```
2020-06-10 17:25:24.402 P00   INFO: stanza-create command begin 2.27: --log-level-console=info --pg1-path=/data/postgresql/11/na_backup_test --pg1-user=postgres --repo1-path=/data/pgbackrest --stanza=na_backup
WARN: unable to check pg-1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432 user='postgres'': FATAL:  Peer authentication failed for user "postgres"
ERROR: [056]: unable to find primary cluster - cannot proceed
2020-06-10 17:25:24.404 P00   INFO: stanza-create command end: aborted with exception [056]
```
**FATAL:  Peer authentication failed for user "postgres"**

I can switch to the postgres user and run psql and connect to the postgres database as normal.

I dropped the default 'main' postgresql cluster and created a new cluster using pg_createcluster

`pg_lscluster` shows:

`Ver Cluster        Port Status Owner    Data directory                     Log file`

`11  na_backup_test 5432 online postgres /data/postgresql/11/na_backup_test /var/log/postgresql/postgresql-11-na_backup_test.log`

port 5432 is open in the firewall; I can connect to the postgres database remotely as well with pgAdmin.

### Repo
**pg_hba.conf** 
```
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
host    all             all             0.0.0.0/0               md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
```

Any ideas what's wrong with the setup?

I also tried modifying the permissions on `/tmp/pgbackrest` to give group +rw (and with the postgres user in the pgbackrest group) tried to add the stanza as the postgres user.

`postgres@na-backup:/tmp$ pgbackrest --stanza=na_backup --log-level-console=info stanza-create`

```
WARN: unable to open log file '/var/log/pgbackrest/na_backup-stanza-create.log': Permission denied
      NOTE: process will continue without log file.
2020-06-10 18:31:17.998 P00   INFO: stanza-create command begin 2.27: --log-level-console=info --log-level-file=off --pg1-path=/data/postgresql/11/na_backup_test --repo1-path=/data/pgbackrest --stanza=na_backup
ERROR: [047]: unable to create path '/data/pgbackrest/archive/na_backup': [13] Permission denied
2020-06-10 18:31:18.534 P00   INFO: stanza-create command end: aborted with exception [047]
```

Do I need to give the postgres user and pgbackrest user permissions to everything that each other has permissions to?

**Comment by gbryant200** [comment]
I changed the PostgreSQL data directory mode to 750 and I was able to successfully create the stanza.

Now on to testing the restore.

**Comment by gbryant200** [comment]
I was able to create the stanza using the --no-online option in the command line.

When I tried to check the stanza:
`pgbackrest --stanza=na_backup --log-level-console=info check`

```
2020-06-11 10:38:13.037 P00   INFO: check command begin 2.27: --log-level-console=info --pg1-path=/data/postgresql/11/na_backup_test --repo1-path=/data/pgbackrest --stanza=na_backup
WARN: unable to check pg-1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432': FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied
ERROR: [027]: no database found
       HINT: check indexed pg-path/pg-host configurations
2020-06-11 10:38:13.038 P00   INFO: check command end: aborted with exception [027]
```

**Comment by dwsteele** [comment]
You don't need to create a new stanza to restore a backup. In general it is best *not* to restore backups to the repo host, but if you do you'll need to specify `--reset-pg1-host` because your configuration is telling pgbackrest that pg1 is located on another host.

The main issue you seem to have run into here is running pgbackrest as multiple users on the repo host and causing permissions problems. The seconday issue is that configuration can get confusing when you are trying to use a host for multiple purposes, i.e. as a repo host and as a test server for Postgres.

It is best practice to leave the repo host alone and use another host for testing restores. An example of restoring to a new host is here: https://pgbackrest.org/user-guide.html#replication. Testing this way preserves the integrity of your repo host and when you are done the test host can be removed without impacting the rest of your system.

**Comment by gbryant200** [comment]
Thanks for the reply.

I was thinking about it and figured I might not need another stanza but was wondering how I'd tell pgbackrest where to restore to.

I don't want to create another standby server; just verify that the backup of the main cluster restores properly.

I had to add the pgbackrest user as a super user on the repo's PostgreSQL install and add pg1-user=pgbackrest on the unnecessary stanza to get it to 'check' properly when I ran pgbackrest as the pgbackrest user.

This is an impressive piece of software.  Thank you for creating it!

**Comment by dwsteele** [comment]
> I was thinking about it and figured I might not need another stanza but was wondering how I'd tell pgbackrest where to restore to.

You can use `--pg1-path` to specify any restore path you like. You'll also need to set `--reset-pg1-host` to let pgBackRest know that you want to restore locally. Again, we don't really recommend this approach.

> I don't want to create another standby server; just verify that the backup of the main cluster restores properly.

A restore is a good start, but actually starting the cluster and running some sanity checks (e.g. amcheck, pg_dump, etc.) is also a good idea.

> I had to add the pgbackrest user as a super user on the repo's PostgreSQL install and add pg1-user=pgbackrest on the unnecessary stanza to get it to 'check' properly when I ran pgbackrest as the pgbackrest user.

This doesn't sound right -- if backup is working check should work just fine as the same user. If you are trying to run "check" in a restore configuration on a host that is otherwise configured as a backup host you can expect to get failures. Check is for ensuring that `backup` and `archive-push` work.
