### ISSUE TITLE
Report min/max transaction timestamps for WAL archive from info command

### ISSUE THREAD

**Issue by loop-evgeny** [pgbackrest/pgbackrest#1070]
1. pgBackRest version: 2.27
2. PostgreSQL version: 12.3
3. Operating system/version: Ubuntu 18.04

I'd like to find out, for monitoring purposes, the timestamp of the latest transaction in pgBackRest's WAL archives, i.e. the time to which I could restore my PostgreSQL instance from the backups + WAL archives. Currently the `info` command shows the timestamp for backup, but not for WAL archives:

```
...
    db (current)
        wal archive min/max (12-1): 000000010000000000000001/000000010000000000000010

        full backup: 20200610-010003F
            timestamp start/stop: 2020-06-10 01:00:03 / 2020-06-10 01:00:57
            wal start/stop: 000000010000000000000009 / 000000010000000000000009
...
```

It shows the min and max WAL filenames. Is there a way for me to get the timestamps from those, as workaround? It would be great if pgBackRest itself reported this info, though!

**Comment by dwsteele** [comment]
We are planning deeper WAL inspection but don't have a firm timeline for when that will be available, or if it will report timestamps in the way you want.

Meanwhile, you can use pg_waldump to get the information you want: https://www.postgresql.org/docs/current/pgwaldump.html.

**Comment by loop-evgeny** [comment]
Thanks. I tried pg_waldump, but could't see any transaction timestamps in there.

What is the recommended way of monitoring that WAL archives stored by pgBackRest are up-to-date then?

**Comment by dwsteele** [comment]
> I tried pg_waldump, but could't see any transaction timestamps in there.

The transaction timestamps are tied to commits so perhaps the WAL file did not have commit records or you do not have commit timestamps enabled.

> What is the recommended way of monitoring that WAL archives stored by pgBackRest are up-to-date then?

`check_pgbackrest` and `pgmonitor` are options, but there are others. You can also check yourself by checking the last wal segment archived from Postgres (https://www.postgresql.org/docs/10/monitoring-stats.html#PG-STAT-ARCHIVER-VIEW) against what pgbackrest reports in the (json) info command (https://pgbackrest.org/user-guide.html#monitor).

**Comment by loop-evgeny** [comment]
Please consider this issue as a feature request for reporting WAL timestamps whenever you implement the deeper WAL inspection! :)

**Comment by dwsteele** [comment]
@loop-evgeny We'll keep it in mind when we get to that feature.
