### ISSUE TITLE
Downloadable RPMs?

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#1073]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2.27

2. PostgreSQL version:

9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

RHEL 6

4. Did you install pgBackRest from source or from a package?

Package

5. Please attach the following as applicable:

N/A

7. Describe the issue:

Last year, I was able to download a pgbackrest RPM from the Postgres YUM repository. However, now it (and barman, for that matter) don't seem to be there (https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-latest-x86_64/).

Where can I download it from?  (Our servers can't directly access the internet, and have no development tools on them, so prebuilt binaries are a requirement.)

Thanks

**Comment by RonJohn2** [comment]
Found it under https://download.postgresql.org/pub/repos/yum/common/redhat/.

**Comment by dwsteele** [comment]
Yes, here's more info about the move https://yum.postgresql.org/news-newreporpmsreleased.php.
