### ISSUE TITLE
QUESTION : WARN: a timeline switch has occurred since the 20200607-033002F backup, enabling delta checksum

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#1074]
1. pgBackRest version:
2.26
2. PostgreSQL version:
12
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS 7.7
4. Did you install pgBackRest from source or from a package?
RPM

We did some failover and switchover tests the other day. We now have the above WARN line some of the diff backup output. However the latest FULL and DIFF do not have this WARN line. 

Should I be worried? --repo1-retention-full=3 we do one full each week with diffs every day.

TIA,

Matt

**Comment by dwsteele** [comment]
This is normal behavior after a failover. The file timestamps on a standby are not usable until a new full backup is made so we automatically enable checksums for incr/diff until then. Checksum backups generally take longer so the warning is just there to let you know that the change was made.

**Comment by dwsteele** [comment]
Seems like a hint would be in order. Have a look at #1075 and see if the language looks good to you.

Also let us know if you would like your name to appear differently in the release notes.

**Comment by mattbunter** [comment]
Yeah that looks like a good idea. I leave up to you and the pgbackrest team for your release notes.

**Comment by dwsteele** [comment]
> Yeah that looks like a good idea.

Cool.

> I leave up to you and the pgbackrest team for your release notes.

Well, I'd say it's more up to you how you prefer your name to be written. Is "Matt Bunter" OK?

**Comment by mattbunter** [comment]
"Matt Bunter" is fine.
