### ISSUE TITLE
Multiple repositories with different retention

### ISSUE THREAD

**Issue by fvannee** [pgbackrest/pgbackrest#1082]
Documentation states having multiple repositories is not supported at the moment. Two questions:
- Is this a feature that's likely going to be added?
- Is there currently a workaround for a simple case as follows:
Suppose I want to have one repository locally and one repository in AWS S3. I'd use the local repository regularly, however this one would have a limited retention time. In AWS S3 we could store everything.
Would it work to have the local repo defined in pgbackrest and then copy all new files (with some other tool) to S3? Or would that result in clashes with the `backup.info` file once backups are dropped in the local repo file.
Any other solutions (without just running pgbackrest twice and doing the backup twice)?

**Comment by dwsteele** [comment]
> Is this a feature that's likely going to be added?

Yes, but we don't have a timeline.

> Would it work to have the local repo defined in pgbackrest and then copy all new files (with some other tool) to S3?

Yes -- the repository is designed to be copied and there are plenty of people doing exactly this. The only catch is that when you need to restore you'll need to change some settings.

**Comment by bradnicholson** [comment]
> Yes -- the repository is designed to be copied and there are plenty of people doing exactly this. The only catch is that when you need to restore you'll need to change some settings.

For the long term archive case, I assume this would be making a static copy of the main archive, and not syncing it (without deletes from the secondary copy)

I assume manifest files would get sync'd with the later case, and although the physical files would be there, pgBackRest would't know about them?

**Comment by fvannee** [comment]
Ok thank you. Yeah, I think the `backup.info` needs some manual changes then when trying to restore older content, because otherwise PgBackrest indeed doesn't know about these backups.

**Comment by dwsteele** [comment]
If you do the sync while a backup/expire is in progress then you may end up with partial backups. Generally pgBackRest will detect these immediately but I can imagine some race conditions where a backup would look valid enough for the restore to start and then fail partway through because files are missing/invalid.
