### ISSUE TITLE
having question regarding pgbackrest restoration 

### ISSUE THREAD

**Issue by narendrapostgresdba** [pgbackrest/pgbackrest#1084]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

we have pgbackrest  backup configured to NAS storage . in case any case DB server can not bring up , is there any way we can restore the  pgbackrest backup data to a different server by attaching the NAS to the new server ?

**Comment by dwsteele** [comment]
> is there any way we can restore the pgbackrest backup data to a different server by attaching the NAS to the new server ?

Just build a new server with the same `pgbackrest` configuration and storage mount and you'll be able to restore as usual. See https://pgbackrest.org/user-guide.html#quickstart/perform-restore for details.

**Comment by narendrapostgresdba** [comment]
Thank you very much for your response

**Comment by dwsteele** [comment]
You are welcome!
