### ISSUE TITLE
Database Not Restored

### ISSUE THREAD

**Issue by gbryant200** [pgbackrest/pgbackrest#1087]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.27

2. PostgreSQL version: 11.8

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 1 server running Ubuntu 18.04

4. Did you install pgBackRest from source or from a package? source initially; updated via package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
[na_backup]
pg1-path=/data/postgresql/11/main

[global]
repo1-path=/data/pgbackrest
repo1-retention-full=2
start-fast=y
process-max=2

[global:restore]
# number of CPUs to use for restore
process-max=3
```
`postgresql.conf` settings applicable to pgBackRest

```
archive_mode = on
archive_command = 'pgbackrest --stanza=na_backup archive-push %p'
listen_addresses = '*'
#max_wal_senders = 10
#wal_level = replica
```
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

6. Describe the issue:

I have pgbackrest and postgresql currently installed on the same server for testing.  I created a 'pgbench' database in PostgreSQL; did a pgbench initialize and ran a couple pgbench commands.  I ran a full backup.

```
full backup: 20200626-105413F
            timestamp start/stop: 2020-06-26 10:54:13 / 2020-06-26 10:54:24
            wal start/stop: 000000050000000000000015 / 000000050000000000000015
            database size: 45.6MB, backup size: 45.6MB
            repository size: 4.4MB, repository backup size: 4.4MB
```
```
pgbackrest --stanza=na_backup --set=20200626-105413F info
stanza: na_backup
    status: ok
    cipher: none

    db (current)
        wal archive min/max (11-1): 000000010000000000000001/0000000A0000000000000017

        full backup: 20200626-105413F
            timestamp start/stop: 2020-06-26 10:54:13 / 2020-06-26 10:54:24
            wal start/stop: 000000050000000000000015 / 000000050000000000000015
            database size: 45.6MB, backup size: 45.6MB
            repository size: 4.4MB, repository backup size: 4.4MB
            database list: pgbench (16385), postgres (13125)

```

The pgbench database is listed in the above backup set.

I stopped postgresql and deleted the data directory.

`find /data/postgresql/11/main -mindepth 1 -delete`

I ran a restore (tried as root and as postgres)

`pgbackrest --stanza=na_backup --log-level-console=detail restore'

no errors listed in the console log; however the pgbench database didn't get restored; the console log shows .../base/16385/* all as (0B, 100%)

I also tried using the --db-include=pgbench option and that didn't work either.

### Stanza Check (as postgres user; fails as root)
```
postgres@na-backup:/data$ pgbackrest --stanza=na_backup --log-level-console=info check
2020-06-26 12:40:53.696 P00   INFO: check command begin 2.27: --log-level-console=info --pg1-path=/data/postgresql/11/main --repo1-path=/data/pgbackrest --stanza=na_backup
2020-06-26 12:40:54.603 P00   INFO: WAL segment 0000000B0000000000000017 successfully archived to '/data/pgbackrest/archive/na_backup/11-1/0000000B00000000/0000000B0000000000000017-ac5f3888954c45a8481980a36a52791dae180ea7.gz'
2020-06-26 12:40:54.603 P00   INFO: check command end: completed successfully (908ms)
```
error running check as root:
```
WARN: unable to check pg-1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432 user='postgres'': FATAL:  Peer authentication failed for user "postgres"
ERROR: [027]: no database found
       HINT: check indexed pg-path/pg-host configurations
```

### pg_hba.conf
```
local   all             postgres                                peer
local   all             pgbackrest                              peer
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
host    all             all             0.0.0.0/0               md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
```

Any ideas?

**Comment by dwsteele** [comment]
> no errors listed in the console log; however the pgbench database didn't get restored

What exactly do you mean? Were you not able to connect to it?

> the console log shows .../base/16385/* all as (0B, 100%)

Are they all zero-byte, or just the ones at the end of the log? A normal cluster has many zero-byte files and they always get restored last.

We'd need to see the restore log to do any more analysis.

> Stanza Check (as postgres user; fails as root)

`root` does not have permissions to connect to PostgreSQL and a connection is required for the `check` command.
