### ISSUE TITLE
Unable to create stanza using S3 for the repository storage

### ISSUE THREAD

**Issue by mfishzon19** [pgbackrest/pgbackrest#1089]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  
2.27

2. PostgreSQL version:
11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
18.04.4 LTS (Bionic Beaver)

4. Did you install pgBackRest from source or from a package?
apt-get

5. Please attach the following as applicable:
   `pgbackrest.conf` (primary pg-host)
  
**log file in `/var/log/pgbackrest`:**
-------------------PROCESS START-------------------
2020-06-30 18:16:40.167 P00   INFO: stanza-create command begin 2.27: --log-level-console=debug --log-level-file=detail --pg1-path=/var/lib/postgresql/11/main --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/pgbackup --repo1-s3-bucket=test-pg-bucket --repo1-s3-endpoint=s3.us-west-1.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-west-1 --repo1-type=s3 --stanza=infra_s3
2020-06-30 18:16:40.705 P00  ERROR: [039]: S3 request failed with 403: Forbidden
                                    *** URI/Query ***:
                                    /pgbackup/archive/infra_s3/archive.info
                                    *** Request Headers ***:
                                    authorization: <redacted>
                                    content-length: 0
                                    host: test-pg-bucket.s3.us-west-1.amazonaws.com
                                    x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
                                    x-amz-date: <redacted>
                                    *** Response Headers ***:
                                    content-type: application/xml
                                    date: Tue, 30 Jun 2020 18:16:39 GMT
                                    server: AmazonS3
                                    transfer-encoding: chunked
                                    x-amz-id-2: m+aVLCijLfFjv/u5SUfcjL62JX/PFVgGt4Ggfhm+mrGBS4btoUkxo0nUUDw66cAyfdgP3z6JkBQ=
                                    x-amz-request-id: D1D737EDF068437F
2020-06-30 18:16:40.706 P00 DETAIL: socket statistics: objects 1, sessions 1, retries 0
2020-06-30 18:16:40.706 P00 DETAIL: tls statistics: objects 1, sessions 1, retries 0
2020-06-30 18:16:40.706 P00   INFO: http statistics: objects 1, sessions 1, requests 1, retries 0, closes 0
2020-06-30 18:16:40.706 P00   INFO: stanza-create command end: aborted with exception [039]

**cat  /etc/pgbackrest/pgbackrest.conf**
[infra]
repo1-host=172.31.10.56
pg1-path=/var/lib/postgresql/11/main

[infra_s3]
pg1-path=/var/lib/postgresql/11/main

process-max=4
repo1-cipher-pass=zWaf6XtpjIVZC5444yXB+cgFDFl7MxGlgkZSaoPvTGirhPygu4jOKOXf9LO4vjfO
repo1-cipher-type=aes-256-cbc
repo1-path=/pgbackup
repo1-retention-diff=2
repo1-retention-full=2
repo1-s3-bucket=test-pg-bucket
repo1-s3-endpoint=s3.us-west-1.amazonaws.com

repo1-s3-key=xxXXXxxxxXXxxxXxXxxxxxxX
repo1-s3-key-secret=xxXXXxxxxXXxxxXxXxxxxxxXxxxxxXXXXxx

repo1-s3-region=us-west-1
repo1-type=s3
start-fast=y
compress-level=3

[global]
log-level-file=detail

**S3 bucket Policy:**
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::redacted:root"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::test-pg-bucket",
            "Condition": {
                "StringEquals": {
                    "s3:prefix": [
                        "",
                        "pgbackup"
                    ],
                    "s3:delimiter": "/"
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::redacted:root"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::test-pg-bucket",
            "Condition": {
                "StringLike": {
                    "s3:prefix": "pgbackup/*"
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::redacted:root"
            },
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::test-pg-bucket/pgbackup/*"
        }
    ]
}

**OUTPUT OF 
 sudo -u postgres pgbackrest --stanza=infra_s3 --log-level-consol=debug stanza-create > stanza_create_debug.log**
[stanza_create_debug.log](https://github.com/pgbackrest/pgbackrest/files/4853802/stanza_create_debug.log)

7. Describe the issue:
Experiencing some strange permission issues with S3 - not able to create the stanza. There is one thing that I am doing that could be a problem but I am not sure. I am trying to set up 2 repositories

1) On the dedicated repository server,  where backups and WALs are archived to the local file system(on the repository server)
2) On the primary pg-host, where backups and WALs are archived to an s3 bucket.

I have 1) working as expected, but when trying to set up 2) - i get this error message. Is it possible that the dual repository situation is causing the problem?

Thanks.

**Comment by dwsteele** [comment]
I'm not immediately seeing the issue, but your configuration is definitely unconventional.

In any case it won't work because `archive_command` won't understand that there are multiple stanzas in the repo that refer to the same cluster. It'll also make restore a nightmare.

We don't support multiple repos yet. Typically people either sync their local repo to s3 or create multiple config files and then create an archive_command that will archive to both (i.e. `archive_command = command1 && command 2`. The latter has some issues -- in particular that two async archivers cannot share the same spool directory or they will lose WAL. So, caution is required.

The safest option is to sync your local repo to s3 using the aws cli sync comand.
