### ISSUE TITLE
[Feature request] Some kind of "pre-expire" callback hook for the "backup" command

### ISSUE THREAD

**Issue by kmoppel** [pgbackrest/pgbackrest#1092]
Main idea - would be great if one could specify some script that is called just before the "auto-expire" of the regular "backup" command. Here in our use we'd want to make sure that all "to be expired" backups are copied off-site.

Even nicer of course would be built in support for such "remote archiving" (together with needed WAL) to S3 or normal FS mounts.

**Comment by pgstef** [comment]
Hi,

I think the pre/post-backups hooks are something that will be added in the future (see https://github.com/pgbackrest/pgbackrest/projects/2#card-8957002).

In the meantime, should we add an extra option to disable "automatic" purge after the backup ? This would let users dry-run expire in external scripts before running the real purge themselves ?

**Comment by kmoppel** [comment]
Ah nice, good to see it written down already :)
@pgstef sure, this "disable auto-purge" flag would make life a already easier. Currently one needs to archive off-site somewhere between the nightly runs but on failures / slowness there's still a chance that it's wiped before finished.

**Comment by dwsteele** [comment]
In the meantime, you can run your backup with maxed out retention options to prevent expiration from happening. For example if you want to prevent full/diff backup expiration you could do something like:
```
pgbackrest --repo1-retention-full=9999999 --repo1-retention-diff=9999999 ...
```
Expire will still run but it won't have anything to do.

**Comment by bradnicholson** [comment]
Is success of the post-backup expiration tied to success of the backup command?  I _think_ it is, and if the backup succeeds and the expiration fails, the backup fails.  We use the high expiration workaround and I seem to recall having backup failures in such cases (although I don''t recalls the exact specifics - the failure might have been from our caller not catching that case properly).

Also, the expire command performance degrades as the number of backups grows.  It's especially noticeable with s3 type storage.  While not a big deal, it is burning compute for no real reason when doing manual expirations.

**Comment by pgstef** [comment]
The main logic is there https://github.com/pgbackrest/pgbackrest/blob/master/src/main.c#L116. 

I would have to try to confirm but I'm not sure the exit code will report an error:
```
$ pgbackrest backup  --stanza=my_stanza --type=full
...
P00   INFO: backup command end: completed successfully (8425ms)
P00   INFO: expire command begin 2.27
P00   INFO: expire full backup 20200709-160925F
P00   INFO: remove expired backup 20200709-160925F
ERROR: [060]: unable to remove '/var/lib/pgbackrest/archive/my_stanza/12-1/0000000100000000/00000001000000000000000B-8c0758056def23dcdf21bb7d9dbb88b868ced7a6.gz': [1] Operation not permitted
P00   INFO: expire command end: aborted with exception [060]

$ echo $?
0
```

@bradnicholson, what do you call a backup failure ?

Also, the expire command run after a backup or manually seems to be exactly the same. So, I'm not really following the `burning compute for no real reason`. You still have to run the expire command one way or the other (manual or automatically after the backup).

**Comment by dwsteele** [comment]
> Is success of the post-backup expiration tied to success of the backup command?

Yes -- expire will not run unless the backup is successful. Even if it did, it probably wouldn't do anything because a failed backup does not count towards retention.

> Is success of the post-backup expiration tied to success of the backup command?

Is this true even if there is nothing to expire? Feel free to send a debug log so we can look for bottlenecks.

**Comment by dwsteele** [comment]
@kmoppel Ask and ye shall receive, apparently! Have a look PR #1098 and see if that would work for you.

**Comment by bradnicholson** [comment]
> what do you call a backup failure ?

If the caller to pgBackRest fails to complete.  I haven't seen this case is a while, and don't have logs to look at.  But I do remember seeing cases in the past where the backup succeeded and the expire triggered by backup failed (for no fault of pgBackRest - transient connectivity causes).  Based on the snippet about it must have been something different.

> Yes -- expire will not run unless the backup is successful
I meant the inverse,  if the backup succeeds and the expire fails, does that fail the entire backup?  Based on the response above, no.

> Is this true even if there is nothing to expire? Feel free to send a debug log so we can look for bottlenecks.
I will next time is see it.  I _think_ it's the overhead of processing the manifest.  But I also don't think we've seen this on later versions that re-wrote that stuff in C.  So it might be a non-issue now.

**Comment by dwsteele** [comment]
> I meant the inverse, if the backup succeeds and the expire fails, does that fail the entire backup?

Ah, I see. No, expire failing does not fail the backup.

> But I also don't think we've seen this on later versions that re-wrote that stuff in C.

We made a lot of performance improvements during the C migration so that's possible. I'm not very motivated to check the Perl code to confirm, though...

**Comment by kmoppel** [comment]
@dwsteele Awesome, thanks for the ultra-quick response :) The user side of the PR looks good also - could not be any easier also I guess, setting one flag :D

**Comment by dwsteele** [comment]
`expire-auto` option committed in PR #1098.
