### ISSUE TITLE
doc tip retention time period

### ISSUE THREAD

**Issue by jacks33** [pgbackrest/pgbackrest#1094]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.27
2. PostgreSQL version:
10
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
rhel 7.7
4. Did you install pgBackRest from source or from a package?
community package

Example for https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-full-type
is repo1-retention-full-type=30
should be repo1-retention-full-type=time

Tiago ANASTACIO

**Comment by dwsteele** [comment]
This has been reported and fixed at 9efbafc84c4a. We haven't done a release so the website has not been updated.

It might make sense to patch this, though, so it doesn't get reported again.

**Comment by dwsteele** [comment]
I patched 2.27 docs to fix this. Should be visible online now.
