### ISSUE TITLE
too much of archives generated with pgbackrest

### ISSUE THREAD

**Issue by aogb** [pgbackrest/pgbackrest#1096]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.26

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: ubuntu

4. Did you install pgBackRest from source or from a package? Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[demo]
pg1-path=/pgdata/postgresql/data
[global]
repo1-path=/pgdata/pgbackrest
repo1-retention-full=2

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_command - 'pgbackrest --stanza=demo archive-push %p'
archive_mode - On
listen_addresses - *
max_wal_senders = 3
wal_level = replica

    - errors in the postgresql log file before or during the time you experienced the issue
N/A
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I am having too much of archives generated. I have over 271GB of archives in my /pgbackrest/archive. How do i manage this? Is there a command to purge archives with pgbackrest? my mount point is getting filled please advice.

**Comment by aogb** [comment]
max_wal_size = 1GB
min_wal_size = 80MB

**Comment by pgstef** [comment]
Hi,

What's the output of `pgbackrest info` ?
Have you taken full backups already ? By default, only the archives older than the 2 full backups you ask to keep in the configuration will be expired.

**Comment by aogb** [comment]
@pgstef  Thanks I got it. After I took 2 full backups, I got the issue resolved.
This case can be closed.
