### ISSUE TITLE
 pgbackrest to restore to a remote host for a DR purposes? 

### ISSUE THREAD

**Issue by aogb** [pgbackrest/pgbackrest#1097]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.26

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu Linux

4. Did you install pgBackRest from source or from a package? Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
pgbackrest.conf file(s)
[demo]
pg1-path=/pgdata/postgresql/data
[global]
repo1-path=/pgdata/pgbackrest
repo1-retention-full=2
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

archive_command - 'pgbackrest --stanza=demo archive-push %p'
archive_mode - On
listen_addresses - *
max_wal_senders = 3
wal_level = replica
    - errors in the postgresql log file before or during the time you experienced the issue
N/A
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
N/A
7. Describe the issue:
Is it possible to use pgbackrest to restore to a remote host for a DR purposes? 
Scenario - Production and DR are in a separate region
pgbackrest takes backup on production and i want to restore to build my DR database.

**Comment by dwsteele** [comment]
> Is it possible to use pgbackrest to restore to a remote host for a DR purposes?

Yes. Your repo (or repo-host) will need to be accessible from both regions. Then you just run restore on the DR database.

An easy way to make your repo available to multiple regions is to locate it in S3. We also have Azure support coming in the next release.

**Comment by aogb** [comment]
it is azure to azure so no blockage between the two regions.
Currently my repo-host is my master node. I run pgbackrest backup on it and have it stored in an Object storage in azure.
So if I get it you correctly, I will also have pgbackrest installed on my DR and initiate the restore from there.

Could you please give an example of what the configuration would look like?

Here is my configuration on the master node
[demo]
pg1-path=/pgdata/postgresql/data
[global]
repo1-path=/pgdata/pgbackrest
repo1-retention-full=2

**Comment by dwsteele** [comment]
I meant Azure *storage*. If the repo is in Azure (or S3) storage then it is easy to share between any two hosts.

Azure storage support will be in the next release which is expected in about a week.

**Comment by aogb** [comment]
This is a very good news. Happy to hear the functionality in Azure Storage.
I'll wait for this functionality then.
Please do let me know when the release is out next week.

**Comment by dwsteele** [comment]
> Please do let me know when the release is out next week.

The best this to do is "watch" to project but select "release notifications" only.
