### ISSUE TITLE
Getting STACK TRACE when running any type of backup

### ISSUE THREAD

**Issue by ejberdecia** [pgbackrest/pgbackrest#1099]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.24

2. PostgreSQL version: Primary 11.6 Standby 11.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
Primary -  Linux 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Standby - Linux  3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

4. Did you install pgBackRest from source or from a package?
source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
When attempting to run any type of backup (full, incr, diff) from the stand-by cluster the command eventually comes back with;
2020-07-09 14:33:38.621 P00   INFO: last backup label = 20200708-133415F_20200708-185644I, version = 2.24
2020-07-09 14:33:38.621 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
ASSERT: [025]: no output required by command
        STACK TRACE:
        protocol/client:protocolClientReadOutput:218:(trace log level required for parameters)
        protocol/client:protocolClientExecute:(trace log level required for parameters)
        db/db:dbFreeResource:(trace log level required for parameters)
        command/backup/backup:cmdBackup:(debug log level required for parameters)
        main:main:(debug log level required for parameters)

[35p-primary-pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/4897614/35p-primary-pgbackrest.conf.txt)
[36p-standby-pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/4897615/36p-standby-pgbackrest.txt)
[detaild_debug_log.txt](https://github.com/pgbackrest/pgbackrest/files/4897616/detaild_debug_log.txt)

[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/4897617/postgresql.conf.txt)

**Comment by dwsteele** [comment]
I'm guess some unexpected error is happening and putting the protocol in a bad state.  Can you generate a trace log and provide the last 1000 lines before the error?

**Comment by ejberdecia** [comment]
I'm working on getting those log.s
Efrain J. Berdecia 

    On Friday, July 10, 2020, 04:17:48 PM EDT, David Steele <notifications@github.com> wrote:  
 
 


I'm guess some unexpected error is happening and putting the protocol in a bad state. Can you generate a trace log and provide the last 1000 lines before the error?

**Comment by ejberdecia** [comment]
Here is the trace file from the standby. The command I'm ran is;
pgbackrest --stanza=drm_prod --log-level-console=trace backup --type=full &> pgbackrest_trace_out.txt

I also attempted to strace the pgbackrest process on the primary and I attached the output here.

[primary_strace.txt](https://github.com/pgbackrest/pgbackrest/files/4913076/primary_strace.txt)
[pgbackrest_trace_out.txt](https://github.com/pgbackrest/pgbackrest/files/4913077/pgbackrest_trace_out.txt)

**Comment by dwsteele** [comment]
I think this is your problem: ` --protocol-timeout=9`. This is a very small timeout given the default is `1800`. Even a small amount of network jitter is going to cause a timeout. I can see all your timeouts are pretty low and this will lead to instability overall.

You should be getting a timeout error, but since we are right in the middle of the list command the protocol is in an unexpected state so you are getting a protocol format error instead. We do need to figure out a better way to report this but the root of your problem is the very low protocol timeout.

**Comment by ejberdecia** [comment]
I had lower the timeouts to trigger the error. Let me run with the default timeouts and see what happens.

**Comment by dwsteele** [comment]
Ah, I see. Looks like you triggered another error instead so hard to know what the original error was -- if it was different.

**Comment by ejberdecia** [comment]
Thanks. I've gone ahead and reset all time outs to default and so far have been able to run the backups without any issues.
I do believe there was something going on with our in-house ssh configuration.
I think we can close this ticket. Thank you so much for your response.
Thanks,Efrain J. Berdecia 

    On Monday, July 13, 2020, 12:43:17 PM EDT, David Steele <notifications@github.com> wrote:  
 
 


I think this is your problem:  --protocol-timeout=9. This is a very small timeout given the default is 1800. Even a small amount of network jitter is going to cause a timeout. I can see all your timeouts are pretty low and this will lead to instability overall.

You should be getting a timeout error, but since we are right in the middle of the list command the protocol is in an unexpected state so you are getting a protocol format error instead. We do need to figure out a better way to report this but the root of your problem is the very low protocol timeout.

**Comment by dwsteele** [comment]
OK. If you see the issue again be sure to let us know.

I'm going to link this issue to #1044 since that's an open issue regarding incorrect error reporting after the protocol layer gets in a bad state. They are essentially the same problem.
