### ISSUE TITLE
Postgres Fails to Start After Restore Due to Settings Mismatch

### ISSUE THREAD

**Issue by jaemoore** [pgbackrest/pgbackrest#1100]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.15

2. PostgreSQL version: 11.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Centos 7

4. Did you install pgBackRest from source or from a package? package I believe

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s):

```
[phantom]
pg1-host=10.1.19.74
pg1-path=/opt/phantom/data/db
pg1-socket-path=/tmp

[global]
repo1-path=/opt/phantom/data/ibackup/repo/pg
log-path=/var/log/phantom/backup
repo1-retention-full=1
repo1-retention-archive-type=incr
repo1-retention-archive=2
start-fast=y
stop-auto=y
process-max=2
repo1-host-user=postgres

[global:archive-push]
compress-level=3
```

- `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

```listen_addresses = '*'
archive_mode = on
max_wal_senders = 3
wal_level = replica
archive_command = 'pgbackrest --stanza=phantom archive-push %p'
```

- errors in the postgresql log file before or during the time you experienced the issue

`ERROR: hot standby is not possible because max_connections = 750 is a lower setting than on the master server (its 
value was 2500)`

- log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

I can get this if needed, but I don't think it's particularly relevant.

7. Describe the issue:

After a restore, postgres will fail to restart due to a postgres settings mismatch between the machine where the backup was taken and the machine where we are restoring.

The pg_log will contain this error message:

`ERROR: hot standby is not possible because max_connections = 750 is a lower setting than on the master server (its value was 2500)`

This only started after we upgraded from 9.4 to 11.6

It also seems to occur with other settings than `max_connections`, but I have to confirm that with our performance engineer. I'll update this issue once I've confirmed it with him.

**Comment by jaemoore** [comment]
Additionally, our workaround for this issue was the reset `max_connections` to 2000, start up postgres, revert `max_connections` to 750 and restart postgres.

**Comment by dwsteele** [comment]
The behavioral change is because PG11 enables `hot_standby` by default. If you want the old behavior you can disable `hot_standby`. See https://www.postgresql.org/docs/11/hot-standby.html#HOT-STANDBY-ADMIN for details.
