### ISSUE TITLE
Why backup aborted when primary set archive_mode = always 

### ISSUE THREAD

**Issue by Wim1234** [pgbackrest/pgbackrest#1101]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.26
2. PostgreSQL version: 12.1 
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
 CentOS 7.6
4. Did you install pgBackRest from source or from a package?  yes

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
     There are two pg node, A and B
     A is primary, B is standby
     At first, A set archive_mode = always
     When I perform backup, it aborted to says:
      " archive_mode=always not supported"
    after change A archive_mode = on,  backup work well......
  
   I have a question:  
       PG document  ver12.1      Section 26.2.9  
       When a server is not in recovery mode, there is no difference between on and always modes.

  why  our pgbackreset  src/command/check/common.c     function checkDbConfig
   if (  !isStandby ... )
      if (archive_mode == always ) 
            ABORT

**Comment by dwsteele** [comment]
We do this to catch configuration problems early since we don't currently support archiving from a standby. The goal is generally to have the same configuration on the primary and standby to facilitate failover.

Standbys can produce WAL that has binary differences from the primary (though logically the same) so it may be hard to determine which is authoritative.
