### ISSUE TITLE
backup  and stanza check  failing 

### ISSUE THREAD

**Issue by narendrapostgresdba** [pgbackrest/pgbackrest#1102]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.27

2. PostgreSQL version:9.6.12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:Red Hat Enterprise Linux Server release 7.3 

4. Did you install pgBackRest from source or from a package?package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

postgres=# show archive_command;
                    archive_command
--------------------------------------------------------
 pgbackrest --stanza=*****  archive-push %p
(1 row)

postgres=# show listen_addresses;
 listen_addresses
------------------
 *
(1 row)

postgres=# show max_wal_senders;
 max_wal_senders
-----------------
 6
(1 row)

postgres=# show wal_level;
 wal_level
-----------
 replica
(1 row)

postgres=# show port;
 port
------
 5432
(1 row)

postgres=#

7. Describe the issue:

out pgbackrest backup failing  with below error 

2020-07-10 19:26:21.854 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2020-07-10 19:56:22.465 P00  ERROR: [057]: query 'select lsn::text as lsn,
                                           pg_catalog.pg_xlogfile_name(lsn)::text as wal_segment_name,
                                           labelfile::text as backuplabel_file,
                                           spcmapfile::text as tablespacemap_file
                                      from pg_catalog.pg_stop_backup(false)' timed out after 1800000ms
2020-07-10 19:56:23.669 P00   INFO: backup command end: aborted with exception [057]

when we ran stanza check command , even it is failing 

ERROR: [082]: WAL segment 000000010000F841000000A0 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
2020-07-13 00:40:06.064 P00   INFO: check command end: aborted with exception [082]

**Comment by dwsteele** [comment]
It looks like your archiving is falling far enough behind that it cannot always complete before archive-timeout. Check your PG log for errors and if that looks OK then implement async archiving to increase your throughput: https://pgbackrest.org/user-guide-centos7.html#async-archiving
