### ISSUE TITLE
Change compress-type on existing stanza?

### ISSUE THREAD

**Issue by kmatt** [pgbackrest/pgbackrest#1103]
1. pgBackRest version: 2.27
2. PostgreSQL version: 11
3. Operating system/version: CentOS 8

If a current stanza and archive was created with `compression-type=lz4`, can the compression algorithm be changed in pgbackrest.conf to `compress-type=zstd` allowing subsequent archiving and backups to use the new compression type, or does the stanza and archive need to be recreated?

**Comment by dwsteele** [comment]
You can change `compress-type` any time you like, but for backups it won't take effect until the next full backup (WAL changes immediately). For other backup types you'll get a WARN that is has been reset to the type in the last full and the backup proceeds with the old type. If you don't want to get warnings, change it the night before your next full backup.
