### ISSUE TITLE
pgbackrest restore does not restore the folder pg_wal 

### ISSUE THREAD

**Issue by rachid-casa** [pgbackrest/pgbackrest#1106]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.15

2. PostgreSQL version:
11.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.7.1908 (Core)

4. Did you install pgBackRest from source or from a package?
from the package

7. Describe the issue:

**Comment by rachid-casa** [comment]
[restore.log](https://github.com/pgbackrest/pgbackrest/files/4926116/restore.log)
[task_vor_restore.log](https://github.com/pgbackrest/pgbackrest/files/4926117/task_vor_restore.log)
[content_pg_wal_after_backup.log](https://github.com/pgbackrest/pgbackrest/files/4926118/content_pg_wal_after_backup.log)
[start_pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/4926119/start_pgbackrest.log)
[content_pg_wal_vor_backup.log](https://github.com/pgbackrest/pgbackrest/files/4926120/content_pg_wal_vor_backup.log)
[patroni_parameters.log](https://github.com/pgbackrest/pgbackrest/files/4926121/patroni_parameters.log)

**Comment by rachid-casa** [comment]
[no_wal_files_are_restored.log](https://github.com/pgbackrest/pgbackrest/files/4926213/no_wal_files_are_restored.log)

**Comment by dwsteele** [comment]
Duplicate of #1108.
