### ISSUE TITLE
pg_wal folder will not be backuped. postgres will not be restarted (wal files are missing to be started)

### ISSUE THREAD

**Issue by rachid-casa** [pgbackrest/pgbackrest#1108]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.15.1-1

2. PostgreSQL version:
11.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

CentOS Linux release 7.8

4. Did you install pgBackRest from source or from a package?

Package

5. Please attach the following as applicable:

see the attached files

7. Describe the issue:
We dump the database with the following options:
sudo -u postgre pgbackrest --stanza=data_db --log-level-console=info backup --type=full

Problem pg_wal folder will not be backuped

We restore the database with the following option:
sudo -u postgres pgbackrest --stanza=data_db  --log-level-console=info restore

The problem is: 
pg_wal folder will not be restored since it was not be backuped.

postgres will not be started when restore is successfully completed.

See the attached files

**Comment by rachid-casa** [comment]
[no_wal_files_are_restored.log](https://github.com/pgbackrest/pgbackrest/files/4930426/no_wal_files_are_restored.log)
[restore.log](https://github.com/pgbackrest/pgbackrest/files/4930427/restore.log)
[task_vor_restore.log](https://github.com/pgbackrest/pgbackrest/files/4930428/task_vor_restore.log)
[content_pg_wal_after_backup.log](https://github.com/pgbackrest/pgbackrest/files/4930429/content_pg_wal_after_backup.log)
[start_pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/4930430/start_pgbackrest.log)
[content_pg_wal_vor_backup.log](https://github.com/pgbackrest/pgbackrest/files/4930431/content_pg_wal_vor_backup.log)
[patroni_parameters.log](https://github.com/pgbackrest/pgbackrest/files/4930432/patroni_parameters.log)

**Comment by pgstef** [comment]
That's pretty much the idea of the archiving process. Since files in pg_wal could be recycled/removed by PG while your backup is running, you need the archived wal by the archive_command.

In your recovery.conf file, you should have a restore_command. That command will get back the wals PG needs from the archive directory on startup.

Can you start your restored PG ? What does the PostgreSQL logs say at startup ?

**Comment by rachid-casa** [comment]
The content of recovery.conf is:

primary_slot_name = 'Host_nic_name'
standby_mode = 'on'
recovery_target_timeline = 'latest'

PG logs say at startup:

2020-07-14 17:29:33.690 CEST []   54871 WARNING:  recovery command file "recovery.conf" specified neither primary_conninfo nor restore_command
2020-07-14 17:29:33.690 CEST []   54871 HINT:  The database server will regularly poll the pg_wal subdirectory to check for files placed there.
2020-07-14 17:29:33.690 CEST []   54871 LOG:  entering standby mode
2020-07-14 17:29:33.690 CEST [[unknown]] postgres 127.0.0.1(54820) 54872 FATAL:  the database system is starting up
2020-07-14 17:29:33.690 CEST [[unknown]] postgres 127.0.0.1(54824) 54873 FATAL:  the database system is starting up
2020-07-14 17:29:33.691 CEST [[unknown]] postgres 127.0.0.1(54828) 54874 FATAL:  the database system is starting up

What schoukd i put in the recovery.conf to get back the wals PG from the archive directory on startup?

Thanks 
Best regards
