### ISSUE TITLE
archive-get:async completes successfully on failure

### ISSUE THREAD

**Issue by jwpit** [pgbackrest/pgbackrest#1110]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.27

2. PostgreSQL version: 10

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Debian

4. Did you install pgBackRest from source or from a package? apt.postgresql.org

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

2020-07-20 10:25:35.293 P00   INFO: get 8 WAL file(s) from archive: 00000004000221750000003C...000000040002217500000043
2020-07-20 10:25:36.418 P02 DETAIL: unable to find 00000004000221750000003D in the archive
2020-07-20 10:25:37.245 P00   INFO: archive-get:async command end: completed successfully (1954ms)

archive-get:async completes successfully, even if it can not find the files.
This can only be seen in debug mode.
I would expect that the command fails, if it cannot find the files.

**Comment by jwpit** [comment]
[abc-archive-get-async.log.gz](https://github.com/pgbackrest/pgbackrest/files/4946580/abc-archive-get-async.log.gz)
Debug log attached

**Comment by dwsteele** [comment]
The `archive-get:async` process does not fail as a whole because one job fails. The failure of a specific file is reported to PostgreSQL when it tries to retrieve that file.

Also, a missing WAL file is not considered to be a hard error because it will probably show up later. If the restore_command returns a hard error (not 0 or 1) to PostgreSQL then it will panic and shut down. We'd rather PostgreSQL keep trying so we return 1 instead to let it know that the file is missing.

**Comment by jwpit** [comment]
Hi David,
it would be useful to see this in the Log on the info level, regardless of the returncode.

**Comment by dwsteele** [comment]
Depending on how large `archive-get-queue-max` is this can cause a lot of log churn at the `info` log level for something that is a normal condition. If you want to see these messages set your log level to `detail`.
