### ISSUE TITLE
Azure Repository Storage Setup with pgbackrest

### ISSUE THREAD

**Issue by aogb** [pgbackrest/pgbackrest#1111]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

Please provide the following information when submitting an issue (feature requests or general comments can skip this):

pgBackRest version: 2.26

PostgreSQL version: 12

Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu Linux

Did you install pgBackRest from source or from a package? Source

Please attach the following as applicable:

pgbackrest.conf file(s)
pgbackrest.conf file(s)
[demo]
pg1-path=/pgdata/postgresql/data
[global]
repo1-path=/pgdata/pgbackrest
repo1-retention-full=2
postgresql.conf settings applicable to pgBackRest (archive_command, archive_mode, listen_addresses, max_wal_senders, wal_level, port)
archive_command - 'pgbackrest --stanza=demo archive-push %p'
archive_mode - On
listen_addresses - *
max_wal_senders = 3
wal_level = replica
- errors in the postgresql log file before or during the time you experienced the issue
N/A
- log file in /var/log/pgbackrest for the commands run (e.g. /var/log/pgbackrest/mystanza_backup.log)
N/A
7. Describe the issue:
Happy to hear the compatibility is out. Could you please point me to a pointer on how to about the setup?
This i have been longing for. It will be mostly appreciated.

**Comment by dwsteele** [comment]
Documentation is here: https://pgbackrest.org/user-guide.html#azure-support

**Comment by aogb** [comment]
Could you please explain the content of the pgbackrest config file?

repo1-azure-account=pgbackrest
repo1-azure-container=demo-container
repo1-azure-key=YXpLZXk=
repo1-cipher-pass=zWaf6XtpjIVZC5444yXB+cgFDFl7MxGlgkZSaoPvTGirhPygu4jOKOXf9LO4vjfO
repo1-cipher-type=aes-256-cbc
repo1-path=/demo-repo
repo1-retention-diff=2
repo1-retention-full=2
repo1-type=azure

**Comment by cmwshang** [comment]
You can find all of the options explained in the Configuration section of the User Guide: https://pgbackrest.org/configuration.html - note drop the "1" index after repo when searching (e.g. repo-azure-account instead of repo1-azure-account) - the index is for future mulit-repo support so the Configuration reference does not list the index when providing definitions.
