### ISSUE TITLE
Uncaught ExecuteError: local-1 process did not exit when expected  thrown at common/exec.c:101

### ISSUE THREAD

**Issue by argdenis** [pgbackrest/pgbackrest#1112]
1. pgBackRest version: 2.27

2. PostgreSQL version: 11

3. PostgreSQL Master and 1 Slave Server with Centos 7 and a Backup repo Server Centos 7.

4. Instaled from Package.

[global]
repo1-path=/
repo1-retention-full-type = time
repo1-retention-full=15
start-fast=y
stop-auto=y
backup-standby=n
archive-timeout = 600
repo1-host-user=postgres
log-level-console=warn
log-level-file=debug

#Stanzas 
[master-01]
process-max=10
pg1-host=master-01
pg1-path=/pgdata/cliente/data
pg1-port=5442
pg2-host=db-slave-pro-01
pg2-path=/pgdata/cliente/data
pg2-port=5442

7. Describe the issue:
the only problem here is this error:
Uncaught ExecuteError: local-1 process did not exit when expected  thrown at common/exec.c:101
The backup finishes successfully but with the exit code 124. Therefore the script crashes

**Comment by dwsteele** [comment]
Thanks for reporting! We've seen this a few times (#917 and #982) but there wasn't quite enough information to figure out what was going on. The attached PR #1119 should fix both of the issues that are causing this problem. Feel free to have a look.

Also, please let us know how you would like your name to appear in the release notes.

**Comment by argdenis** [comment]
> Thanks for reporting! We've seen this a few times (#917 and #982) but there wasn't quite enough information to figure out what was going on. The attached PR #1119 should fix both of the issues that are causing this problem. Feel free to have a look.
> 
> Also, please let us know how you would like your name to appear in the release notes.

Thanks a lot
i definitely would like that my name appears.

**Comment by argdenis** [comment]
argdenis its good. thks
