### ISSUE TITLE
question on asynchronous archiving

### ISSUE THREAD

**Issue by jacks33** [pgbackrest/pgbackrest#1114]
Hello, 

I'm seeking the behaviour of pgbackrest when FS of spool-path directory is full 
and archive-push-queue-max threshold is not reached.

So I force an error on archiving: changing repository owners and rights.
because when there are no errors pgbackrest generates ok files which size is 0 byte.

It seems pgbackrest does not handle this as an error, just as if it's a postgres error.

Then How can I reproduce the case, which kind of archiving errors are considered as so by pgbackrest ?

Thank you

**Comment by dwsteele** [comment]
> because when there are no errors pgbackrest generates ok files which size is 0 byte.

If the spool path is not writable I would expect to see errors.

> It seems pgbackrest does not handle this as an error, just as if it's a postgres error.

Not sure what you mean -- the error is reported in the Postgres log but it is pgBackRest that generates it.

I think you'll need to give more details about what you are doing and what errors you are seeing (or not seeing).
