### ISSUE TITLE
Support Google Cloud Storage / Bucket

### ISSUE THREAD

**Issue by strigona-worksight** [pgbackrest/pgbackrest#1115]
#631 and #743 have been locked. Any chance that this can be put back on the roadmap?

**Comment by dwsteele** [comment]
It is on the roadmap (https://github.com/pgbackrest/pgbackrest/projects/2#card-33945748) but we don't currently have a planned date for it. It is fairly high priority for us but we have a few projects that need to come first.

**Comment by strigona-worksight** [comment]
Thanks - I thought I searched the project, must have used the wrong term :)
