### ISSUE TITLE
Bug(s) in async archive-get and archive-push

### ISSUE THREAD

**Issue by levkk** [pgbackrest/pgbackrest#1116]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.27 and 2.28

2. PostgreSQL version: 12.2 and 12.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 18.04

4. Did you install pgBackRest from source or from a package?
A .deb package from the repository

5. Please attach the following as applicable:
*pgbackrest.conf*
```
[main]
pg1-path=/var/lib/postgresql/12/main

[global]
archive-async=y
process-max=8
io-timeout=600
repo1-retention-diff=2
repo1-retention-full=2
repo1-type=s3
repo1-path=/red_node_15
repo1-s3-bucket=our-s3-repo
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-region=us-east-1
spool-path=/var/spool/pgbackrest
archive-timeout=3600
start-fast=y
archive-get-queue-max=10GB
archive-push-queue-max=1TB

[global:archive-push]
compress-level=1
process-max=32

[global:archive-get]
process-max=16
```

*postgresql.conf*
```
restore_command = '. /var/lib/postgresql/.pgbackrest_creds && pgbackrest --stanza=main archive-get %f "%p"'
archive_command = '. /var/lib/postgresql/.pgbackrest_creds && pgbackrest --stanza=main archive-push %p'
```

The file `/var/lib/postgresql/.pgbackrest_creds` contains the AWS S3 credentials exported as `PGBACKREST_` variables.

7. Describe the issue:

Both _async_ `archive-get` and `archive-push` seem to suffer from bugs.

`archive-get` gets locked up on a particular WAL segment and just hangs, blocking recovery. `archive-push` failed to upload a few segments creating "holes" in the archive.

The bugs seem to be isolated to the async behavior: I removed `archive-async=y` from the config and `archive-get` immediately unblocked and continued fetching segments. The logs have no ERROR lines and the command returns successfully or not at all (by hanging indefinitely).

`archive-push` missing WAL files in the archive bug is infrequent enough: only 1-2 files were missing in about 2 million files, but it occurred consistently on several of my databases. I have not tried removing `archive-async=y` option from `archive-push` because my databases write 10-15 WAL segments per second during busy periods and it would not be able to archive fast enough.

Logs from `archive-get` being stuck:
[pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/4967708/pgbackrest.log)

The logs were extracted about 30 minutes after they were last written, showing the process just being stuck / not logging anything and not reporting success.

I've also noticed the pgbackrest process turning into a zombie very frequently (`[defunct] pgbackrest`) during recovery from archive and during archiving.

Edit:

For `archive-get` async, I'm noticing the spool directory contains no WAL files anymore when the process hangs. It's supposed to have 5GB at all times -- assuming of course there is still WAL in the archive to get, which is definitely the case, since the replica is ~2 days behind the primary.

**Comment by dwsteele** [comment]
> archive-push missing WAL files in the archive bug is infrequent enough

This is worrisome but there's not a lot to go on here.

> archive-get gets locked up on a particular WAL segment

The problem here is that the Postgres recovery process is using a lot of file descriptors and our process inherits all of them. If we run out of file descriptors during the fork and detach then things go badly. We're not sure how to fix that as we have never been able to repro it -- we always see an out of descriptors error.

I've been resisting having a loop to just go through and close all the descriptors but maybe it would make sense to at least do it for `archive-get:async`.

Anyway, it is very unlikely that you need `process-max=16` for archive-get. Unless your latency is extremely high 2-4 is enough to stay ahead of PostgreSQL replay.

**Comment by levkk** [comment]
> This is worrisome but there's not a lot to go on here.

I will try to get you more debug information. Maybe `archive-push` setting `process-max=32` runs into the same issue as `archive-get`? The `postgres` user has a 1024 soft and a 2048 hard limit on open files. I should of given it more.

> Anyway, it is very unlikely that you need process-max=16 for archive-get. Unless your latency is extremely high 2-4 is enough to stay ahead of PostgreSQL replay.

You are 100% right, I managed to max out the recovery process at 4 processes.

**Comment by dwsteele** [comment]
> I will try to get you more debug information. Maybe archive-push setting process-max=32 runs into the same issue as archive-get?

Perhaps, but that doesn't explain why there are files missing. The push should be retried until it succeeds. But, we'd really need to have more info to even start to look into this.

> You are 100% right, I managed to max out the recovery process at 4 processes.

We have been resisting running a loop to close file descriptors that we inherit (it's slow), but I think if we do it just for async archive-get it should be OK. We'll look to do that for the next release.

**Comment by levkk** [comment]
> Perhaps, but that doesn't explain why there are files missing. The push should be retried until it succeeds. But, we'd really need to have more info to even start to look into this.

Please let me know if you have any specific information I can collect. I can probably run pgBackRest with `--log-level-file=debug` for `archive-push`. It usually takes a couple weeks before it manifests.

**Comment by dwsteele** [comment]
PR #1130 proactively closes file descriptors passed from Postgres, so that should at least help with the archive-get issue.

> I can probably run pgBackRest with --log-level-file=debug for archive-push

That would certainly be helpful, but to gather useful information we'd also need `--log-subprocess` so we can see what the local process did with the file. Beware that this can generate a lot of logs.

**Comment by levkk** [comment]
I haven't had the chance to do debug logging yet, however I've correlated the occurrence to high usage of S3. I was restoring a large cluster from backup at the time (24 databases). Any chance this could be somewhere in the error handling / S3 rate limiting? This happened on multiple of my databases at the same time:

![Screen Shot 2020-08-19 at 2 18 30 PM](https://user-images.githubusercontent.com/9561483/90690670-faa56780-e226-11ea-9598-a4beb748323a.png)

The curves appearing out of nowhere are replicas coming online from a backup and replaying WAL. The increasing curves on the right are replicas from the same cluster that hit a "hole" in the archive and could not recover further.

**Comment by dwsteele** [comment]
OK. Debug logs are what we need here. Basically, we want to figure out if the WAL segment never made it to the repo, or if something happened to it later.

**Comment by levkk** [comment]
@dwsteele Hi David! Just tried out version 2.29, and I noticed that Postgres occasionally fails to start when recovering from a backup if asynchronous mode is enabled in pgBackRest. The error is `could not find redo location referenced by checkpoint record`. Postgres log indicates it recovered the first WAL record after the backup started and then it crashes with that error immediately afterwards. Maybe related to the file descriptor change (proactively closing them after forking)? Disabling async helps.

**Comment by dwsteele** [comment]
I'm pretty mystified by this. Seems like it must be something else since 94d3a01f seems pretty clear cut.

Any thoughts on this, @sfrost?

**Comment by sfrost** [comment]
I'd actually suspect an issue with recovery.signal and standby.signal both existing and the restore getting interrupted and restarted and then confused because PG only removed one of those files and the other was still there.

After doing a restore, before starting PG, make sure that only *one* of those files exists and see if you're still running into issues.

This has already been fixed in pgbackrest and will be out with the next release so that it won't end up creating both anymore.

**Comment by dwsteele** [comment]
I wondered about that, but why would using sync archiving help? Perhaps something had been cleared by the time that change was made?

**Comment by sfrost** [comment]
honestly, I kinda doubt it's got anything to do with that. :)

took a while to puzzle through what was happening with the two files existing and sometimes one of them being removed and then the other, etc.  I'd definitely make sure it isn't related to that first.

**Comment by dwsteele** [comment]
Closing since #1438 appears to fix the issue.
