### ISSUE TITLE
Can we add a time based retention policy?

### ISSUE THREAD

**Issue by ejberdecia** [pgbackrest/pgbackrest#1121]
My understanding is that currently we only base our retention policy on the number of full, incr, diff backup types we are taking.
Can we add a retention policy for each type of backups based on a minimum time frame.

I.e.;
repo1-rentention-full-time=1 month
repo1-rentention-full=3

A setup like this would retain 3 full backups but will make sure we retain at least 1 of those full backups that goes back at least 1 month.

The values for the time frames can be;
xxx hour
xxx day
xxx week
xxx month
xxx year

**Comment by pgstef** [comment]
Hi,

Time-based retention has been added in 2.27. See https://pgbackrest.org/release.html for the details.

```
Time-based retention for full backups. The --repo-retention-full-type option allows retention of full backups based on a time period, specified in days. (Contributed by Cynthia Shang, Pierre Ducroquet. Reviewed by David Steele.)
```

This option will help you configure it : https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-full-type.

```
The --repo-retention-full-type option allows retention of full backups based on a time period, specified in days.

The new option will default to 'count' and therefore will not affect current installations. Setting repo-retention-full-type to 'time' will allow the user to use a time period, in days, to indicate full backup retention. Using this method, a full backup can be expired only if the time the backup completed is older than the number of days set with repo-retention-full (calculated from the moment the 'expire' command is run) and at least one full backup meets the retention period. If archive retention has not been configured, then the default settings will expire archives that are prior to the oldest retained full backup. 

For example, if there are three full backups ending in times that are 25 days old (F1), 20 days old (F2) and 10 days old (F3), then if the full retention period is 15 days, then only F1 will be expired; F2 will be retained because F1 is not at least 15 days old.
```

For a concrete example, you can see https://pgstef.github.io/2020/05/25/pgbackrest_preview_tour_of_retention_policy_options.html#full-backups-time-based-expiration.

Does that answer your question ?

Kind regards,
