### ISSUE TITLE
./configure pgcrypto error message

### ISSUE THREAD

**Issue by did16** [pgbackrest/pgbackrest#1122]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
 pgbackrest-release-2.28

2. PostgreSQL version:
PostgreSQL 12.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Red Hat Enterprise Linux Server release 7.5 (Centos)

4. Did you install pgBackRest from source or from a package?
source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
When I run ./configure, I get the following error message : 
>>
[root@DCEYY1CV src]# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... -std=gnu99
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether C compiler accepts -Wno-clobbered... yes
checking for /usr/pgsql-12/bin/pg_config... no
checking for PQconnectdb in -lpq... yes
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking libpq-fe.h usability... yes
checking libpq-fe.h presence... yes
checking for libpq-fe.h... yes
checking for EVP_get_digestbyname in -lcrypto... no
**configure: error: library 'crypto' is required**
<<
How can we solve this issue ?
Thanks in advance

**Comment by pgstef** [comment]
Hi,

Do you have the `openssl-devel` package installed on your system ?

The complete list of packages needed to compile the sources can be found here : https://pgbackrest.org/user-guide-centos7.html#build

Kind Regards,
