### ISSUE TITLE
Issues with taking backup to s3 (minio)

### ISSUE THREAD

**Issue by pawsuch** [pgbackrest/pgbackrest#1124]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **2.28, 2.29dev**

2. PostgreSQL version:  **PostgreSQL 11.8 (Ubuntu 11.8-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: **Ubuntu 18.04.4 LTS**

4. Did you install pgBackRest from source or from a package? **Package and source**

5. Please attach the following as applicable:
    **Config and logs enclosed**

7. Describe the issue:
I'm trying to perform a backup to Minio, however the backup does not succeed due to 82 exception, `ERROR: [082]: WAL segment ************ was not archived before the 60000ms timeout.`

This happens only with minio. When I do the backup locally everything works fine. I tried it on Ubuntu and Centos, with pgBackrest installed from package and compiled from the latest sources - every time when I try to use Minio's S3 it fails. Postgres does not report any issues with log archiving (see the files).
The files were created in minio according to the specs from pgbackrest.conf file, so the access rights should be fine.

I attached logs and configs - did I missed something in the configuration?

BR
[pg_settings.conf.txt](https://github.com/pgbackrest/pgbackrest/files/4986670/pg_settings.conf.txt)
[pgbackrest_backup.log.txt](https://github.com/pgbackrest/pgbackrest/files/4986671/pgbackrest_backup.log.txt)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/4986672/pgbackrest.conf.txt)
[postgres.log.txt](https://github.com/pgbackrest/pgbackrest/files/4986673/postgres.log.txt)

**Comment by dwsteele** [comment]
If minio is not configured for host-style URIs then you'll need to set `repo1-s3-uri-style=path`.

**Comment by pawsuch** [comment]
Perfection! Thanks @dwsteele
