### ISSUE TITLE
pgbackrest to S3 with IAM Instance Profile assigned to server

### ISSUE THREAD

**Issue by JBromage** [pgbackrest/pgbackrest#1126]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.28-1.rhel7; also tested on 2.27-2.rhel7  

2. PostgreSQL version:
11.8

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.8.2003 / 3.10.0-1127.13.1.el7.x86_64

4.  pgBackRest installed via yum

5. Please attach the following as applicable:
    - pgbackrest.conf:
process-max=8
compress-level=7
compress-type=lz4

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
2020-07-28 13:17:59.241 UTC [2177] WARNING:  aborting backup due to backend exiting before pg_stop_backup was called
2020-07-28 13:36:59.330 P00   INFO: archive-push command begin 2.28
    - log file 
2020-07-28 13:17:59.243 P00  ERROR: [039]: HTTP request failed with 400 (Bad Request):
                                    *** URI/Query ***
                                    *** Response Content ***:
                                    <?xml version="1.0" encoding="UTF-8"?>
                                    <Error><Code>ExpiredToken</Code><Message>The provided token has expired.
2020-07-28 13:18:00.044 P00 DETAIL: socket statistics: objects 2, sessions 88, retries 0
2020-07-28 13:18:00.044 P00 DETAIL: tls statistics: objects 2, sessions 88, retries 0
2020-07-28 13:18:00.044 P00   INFO: http statistics: objects 2, sessions 88, requests 92, retries 86, closes 1
2020-07-28 13:18:00.044 P00   INFO: backup command end: aborted with exception [039]

( this bit was a backup resume--->) -------------------PROCESS START-------------------

7. Describe the issue:
I'm evaluating pgbackrest at the moment, and have been using an IAM instance profile which is associated to an IAM role that has the necessary S3 bucket permissions, and uses a VPC S3 endpoint. The latter works absolutely fine for a very small database, as I've got a cron script that runs every hour to refresh the values in pgbackrest.conf for repo1-s3-key, repo1-s3-key-secret, & repo1-s3-token thus giving me a token that is valid for 6 hours, which seems to be fine for a backup that completes within the 6 hr window for 
However... Moving on to test pgbackrest against a 5TB test database server, using the above is not viable - its fine for archive-push, as this runs on demand and picks up the refreshed security token, but a full backup is a different story.... I don't expect a 5TB full backup to necessarily complete within 6 hours... in this test  ( including a backup resume which will run a checksum, it took 11 hours )

I know the workaround as such would be to use an IAM user so I could request temporary credentials that persist for longer than 6 hours for any database server that's > 1TB, but I have 2 questions

1. Does 11hrs for a 5TB database server backup to S3 sound reasonable / have I missed a setting?
2. Are there any plans to add some sort of countdown timer to the code to enable the ability to re-read the values of repo1-s3-key, repo1-s3-key-secret, & repo1-s3-token  from pgbackrest.conf every (?5 hrs ) so it would be possible to use instance profiles? 

Please let me know if you need any additional information or would like me to try anything in the test rig I've got.

**Comment by dwsteele** [comment]
> Does 11hrs for a 5TB database server backup to S3 sound reasonable / have I missed a setting?

This sounds reasonable for `process-max=8`.

> Are there any plans to add some sort of countdown timer to the code to enable the ability to re-read the values...

The plan is to have pgBackRest get the keys/token automatically in the next release. So there won't be anything for you to script, it will just be pgbackrest config.

**Comment by JBromage** [comment]
Thanks for confirming the speed is fairly typical. 
Just to clarify, for the automatic get of keys/token, will that require an IAM user,  or will it also apply to IAM instance profiles?

**Comment by dwsteele** [comment]
We're planning to pull the credentials using `http://169.254.169.254/latest/meta-data/iam/security-credentials/<role>` so I believe a role is required. We're also open to suggestions and would appreciate anyone willing to help us test.

**Comment by joey-coleman** [comment]
That is indeed an IAM instance profile/role, and we would almost certainly be happy to help test (I am a colleague of @JBromage).

A related question to this is if pgBackrest will automatically refresh the credentials from the instance profile location — are you planning to use AWS' C++ SDK Credential Provider to fetch them "automatically"? If so, I think we're likely good (AWS's documentation on the instance profile credential provider calls out that it refreshes every 5m).

**Comment by dwsteele** [comment]
> A related question to this is if pgBackrest will automatically refresh the credentials from the instance profile location 

Yes, we will fetch new credentials automatically before the old credentials expire.

> are you planning to use AWS' C++ SDK Credential Provider to fetch them

No, we're a pure C project and unfortunately there's no C API. But, the calls are relatively simple -- it's really testing that's tricky.

**Comment by JBromage** [comment]
> We're planning to pull the credentials using `http://169.254.169.254/latest/meta-data/iam/security-credentials/<role>` so I believe a role is required. We're also open to suggestions and would appreciate anyone willing to help us test.

I'd  like to be involved in testing - also more than happy to share details of the config I've been using for my evaluation testing so you've better eyes on what I've been doing with pgbackrest

**Comment by dwsteele** [comment]
> also more than happy to share details of the config I've been using for my evaluation testing so you've better eyes on what I've been doing with pgbackrest

If it is not too much trouble. It would be helpful to compare with the procedure we are developing.

**Comment by JBromage** [comment]
Here you go - I've tried to make it as brief but detailed as possible:
[pgbackrest_info.log](https://github.com/pgbackrest/pgbackrest/files/5041512/pgbackrest_info.log)

**Comment by dwsteele** [comment]
Thank you! This is helpful.

We are using `http://169.254.169.254/latest/meta-data/iam/security-credentials/<role>` to get credentials. A PR should be ready soon.

**Comment by JBromage** [comment]
Ok - I can set up an IAM user rather than an instance profile to test if you'd like

**Comment by dwsteele** [comment]
I have linked PR #1137 which implements this feature. Closing this issue since any discussion should take place on the PR.
