### ISSUE TITLE
./configure fails on FreeBSD 12.1. Unable to find 

### ISSUE THREAD

**Issue by rgacote** [pgbackrest/pgbackrest#1129]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.28

2. PostgreSQL version: 12.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: FreeBSD 12.1

4. Did you install pgBackRest from source or from a package?
Attempting to install from source:
wget https://github.com/pgbackrest/pgbackrest/archive/release/2.28.tar.gz

5. Please attach the following as applicable: n/a

7. Describe the issue:
./configure fails with:

    checking for pkg-config... no
    checking for xmlSaveToBuffer in -lxml2... yes
    checking libxml/parser.h usability... no
    checking libxml/parser.h presence... no
    checking for libxml/parser.h... no
    configure: error: header file <libxml/parser.h> is required

- Checked that libxml2-2.9.10
- Have tried with and without the --with-libxml2  flag. 
- Confirmed that `xml2-config --cflags` returns `-I/usr/local/include/libxml2 -I/usr/include`
- Noticed that `/usr/local/include/libxml2` does not contain any header files (only a directory). 
- The .h files are actually in /usr/local/include/libxml2/libxml directory.
- Read the very useful Luca Ferrari article:
https://fluca1978.github.io/2020/06/12/pgbackrestOnFreeBSD.html
- Chatted w/M.r Ferrari who said he did not have to do anything special when build the project. 
- Spent some time trying to debug the ./configure script

I'm new to FreeBSD so this may be a fairly straight-forward beginner's error. 
Appreciate any insight anyone has. 

Full output of the ./configure is below:

    [rgacote@auv2-bsd12 ~/pgbackrest-release-2.28/src]$ ./configure
    checking for gcc... no
    checking for cc... cc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether cc accepts -g... yes
    checking for cc option to accept ISO C89... none needed
    checking for cc option to accept ISO C99... none needed
    checking build system type... x86_64-unknown-freebsd12.1
    checking host system type... x86_64-unknown-freebsd12.1
    checking whether C compiler accepts -Wno-clobbered... no
    checking for pg_config... yes
    checking for PQconnectdb in -lpq... yes
    checking how to run the C preprocessor... cc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking libpq-fe.h usability... yes
    checking libpq-fe.h presence... yes
    checking for libpq-fe.h... yes
    checking for EVP_get_digestbyname in -lcrypto... yes
    checking for SSL_new in -lssl... yes
    checking for pkg-config... no
    checking for xmlSaveToBuffer in -lxml2... yes
    checking libxml/parser.h usability... no
    checking libxml/parser.h presence... no
    checking for libxml/parser.h... no
    configure: error: header file <libxml/parser.h> is required

**Comment by dwsteele** [comment]
Here's how we do the build for testing: https://github.com/pgbackrest/pgbackrest/blob/release/2.28/.cirrus.yml#L12

So, we are having the same experience as Luca. Not too surprising since he has been helping us with FreedBSD for a while. It looks to me like something is wrong with xml2-config, but I don't have any idea what it could be.

One thing you can do is set the path to your includes using `CPPFLAGS` and your libs using `LDFLAGS`. So, in your case (for `CPPFLAGS`, at least:
```
export CPPFLAGS=/usr/local/include/libxml2/libxml;./configure
```
