### ISSUE TITLE
Modify pgBackRest backup destination or naming convention. 

### ISSUE THREAD

**Issue by avinashvallarapu** [pgbackrest/pgbackrest#1138]
We have a multi-tenant database where each tenants data is stored in a tenant specific schema. And each schema will be stored in a tenant specific tablespace. These tablespaces are each encrypted using tenant specific encryption keys at rest. 

Now, when we perform a Full backup, we would like to pre-create the backup directory and the tablespace directories so that we handle the encryption of backups with tenant specific keys. 

$ mkdir -p 20200811-012044F/pg_tblspc/16502
$ mkdir -p 20200811-012044F/pg_tblspc/16501
$ pgbackrest backup --stanza=percdb --log-level-console=info

I see that this directory naming convention is based on the current datetime. How can we modify this so that backup directory can be parameterized ? 

For example,

export BACKUP_DEST=/backups/today
And pgBackRest should automatically generated backup in this directory.

**Comment by dwsteele** [comment]
I see what you are trying to do here but it is a very specific use case which will only work on certain storage types.

This isn't something we support and we aren't likely to. The backup directory names are very structured and are used all through the code. It would be a big change and there's no benefit to general users.
