### ISSUE TITLE
Backup only from Standby : "Unable to find primary cluster - cannot proceed"

### ISSUE THREAD

**Issue by Argha-2890** [pgbackrest/pgbackrest#1139]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.28

2. PostgreSQL version: 11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.94

4. Did you install pgBackRest from source or from a package? - Source

5. Please attach the following as applicable:
 
pgbackrest.conf : 

```

[sdb]
pg1-path=/data/patroni2

[global]
log-level-file=detail
repo1-path=/data/pgbackrest
repo1-host-user=postgres
repo1-retention-full=2
```

7. Describe the issue: I want to take a backup only from the standby. But I'm getting the below issue while trying to create a stanza 

```
 pgbackrest --stanza=sdb --log-level-console=info stanza-create
2020-08-11 13:38:53.616 P00   INFO: stanza-create command begin 2.28: --log-level-console=info --log-level-file=detail --pg1-path=/data/patroni2 --repo1-path=/data/pgbackrest --stanza=sdb
ERROR: [056]: unable to find primary cluster - cannot proceed
2020-08-11 13:38:54.220 P00   INFO: stanza-create command end: aborted with exception [056]
```

**Comment by cmwshang** [comment]
Be sure your installation and configuration files on your standby, repo and host are correct. See https://pgbackrest.org/user-guide.html#replication on setting up a standby and https://pgbackrest.org/user-guide.html#standby-backup for backing up from standby.

**Comment by Argha-2890** [comment]
@cmwshang - I am aware of both the options. However, what I am looking for is performing backup only from the standby. Is that possible?

**Comment by sfrost** [comment]
No, you can't backup from *only* the standby with pgbackrest today.  We don't really recommend such a configuration as there doesn't seem to be a good use-case for it, maybe you can explain why you don't want to have a backup that includes stats and other things that we can get from the primary with very little effort...?  Why does it make sense to *only* use the standby?

**Comment by Argha-2890** [comment]
@sfrost - This query was partly due to my curiosity as I wanted to check whether it's feasible to use only the standby for backups to avoid load on the primary. 

Could you please confirm how the backup-standby option will work in case I am using a shared NFS storage instead of a remote repository?.. Do we need to have SSH enabled between the primary and standby for it to work?

**Comment by dwsteele** [comment]
> I wanted to check whether it's feasible to use only the standby for backups to avoid load on the primary

There is very little load on the primary -- it is primarily used to call pg_start_backup() and pg_stop_backup(). Some files are copied but the vast majority come from the standby.

> Do we need to have SSH enabled between the primary and standby for it to work?

Yes. This is a good idea anyway. At some point your standby will be your primary and vice versa. If your hosts are setup the correctly then backups and archiving can proceed without interruption after a failover.

**Comment by Argha-2890** [comment]
@dwsteele - Appreciate your inputs.
