### ISSUE TITLE
WAL archiving to Azure times out

### ISSUE THREAD

**Issue by dtseiler** [pgbackrest/pgbackrest#1141]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.28

2. PostgreSQL version: 9.6.18 and 10.13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04 (VM hosted on Azure)

4. Did you install pgBackRest from source or from a package? PGDG Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s): here is the 9.6 one, the 10 is identicial except for pg1-path obviously.

```
[postgres2]
pg1-path=/var/lib/postgresql/9.6/main
pg1-port=5432

[global]
log-level-console=info
log-level-file=info
compress-type=lz4
archive-async=y
process-max=2
repo1-cipher-pass=xxx
repo1-cipher-type=aes-256-cbc
repo1-retention-full=2
repo1-type=azure
repo1-path=/

# Azure
repo1-azure-account=foo
repo1-azure-key=fee
repo1-azure-container=fum

[global:restore]
process-max=4

[global:archive-push]
process-max=3
```

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

```
archive_mode = on
archive_command = '/usr/bin/pgbackrest --stanza=postgres2 archive-push %p' 
listen_addresses = '*'
port = 5432
max_wal_senders = 10
wal_level = replica
```

    - errors in the postgresql log file before or during the time you experienced the issue

No errors in postgresql log. WAL archiving silently times out.

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Failure at end of backup:

```
2020-08-13 01:00:32.565 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2020-08-13 01:30:32.594 P00  ERROR: [057]: query 'select lsn::text as lsn,
                                           pg_catalog.pg_xlogfile_name(lsn)::text as wal_segment_name,
                                           labelfile::text as backuplabel_file,
                                           spcmapfile::text as tablespacemap_file
                                      from pg_catalog.pg_stop_backup(false)' timed out after 1800000ms
```

The PG10 DB backup failed with the WAL timeout:

```
2020-08-13 01:00:19.870 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2020-08-13 01:00:21.172 P00   INFO: backup stop archive = 0000000500000D520000002D, lsn = D52/2D00F5E0
2020-08-13 01:00:21.185 P00   INFO: check archive for segment(s) 0000000500000D520000002D:0000000500000D520000002D
2020-08-13 01:01:21.309 P00  ERROR: [082]: WAL segment 0000000500000D520000002D was not archived before the 60000ms timeout
                                    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
                                    HINT: check the PostgreSQL server log for errors.
```

7. Describe the issue:

WAL archives timing out 100% of time on two of our DB hosts. Rolled out pgbackrest yesterday and it has never archived a WAL file yet. The stanza was created. Backup files were pushed during the scheduled backup, but WAL archiving times out every time. Testing with the `check` command times out after 60 seconds:

```
$ pgbackrest --stanza=postgres2 check
2020-08-13 14:00:04.310 P00   INFO: check command begin 2.28: --log-level-console=info --log-level-file=info --pg1-path=/var/lib/postgresql/9.6/main --pg1-port=5432 --repo1-azure-account=<redacted> --repo1-azure-container=foo --repo1-azure-key=<redacted> --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/ --repo1-type=azure --stanza=postgres2
ERROR: [082]: WAL segment 000000040000100700000053 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
2020-08-13 14:01:06.447 P00   INFO: http statistics: objects 1, sessions 1, requests 17, retries 0, closes 0
2020-08-13 14:01:06.447 P00   INFO: check command end: aborted with exception [082]
```

Like I said, it happens 100% of the time with these two databases in our staging environment. We deployed to 38 databases (19 each in staging & UAT) and all others work fine. However we need to understand and fix this problem before we can deploy to prod.

**Comment by dwsteele** [comment]
The errors from `archive_command` are in the Postgres logs -- what do they say?

**Comment by dwsteele** [comment]
Sorry, just read through more carefully and saw this `No errors in postgresql log.`. This is pretty odd. Try bumping `log-level-console` up to debug and see what happens.

**Comment by dtseiler** [comment]
in pgbackrest.conf now:
```
log-level-console=debug
```

in postgresql log:
```
2020-08-13 14:40:26.824 GMT [21579] postgres@postgres - psql LOG:  duration: 883.377 ms  statement: select pg_switch_xlog();
```

after more than 2 minutes nothing else in the log related to archiving or pgbackrest.

**Comment by dwsteele** [comment]
Try adding `--log-level-console=debug` directly to the `archive_command`.

**Comment by dtseiler** [comment]
Problem was not with pgbackrest. Both cases had a hung wal-g process that postgresql was still waiting for. Killing those processes had postgresql pick up the new archive_command and things are much better.
