### ISSUE TITLE
Unable to restore backup from one node to a seperate/remote node.

### ISSUE THREAD

**Issue by bharathregal** [pgbackrest/pgbackrest#1142]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **2.27**

2. PostgreSQL version: **11.5**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
**2 database servers with pgbackrest installed.**

4. Did you install pgBackRest from source or from a package?
**From Package.**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

**INFO: restore command begin 2.27: --delta --log-level-console=info --log-level-file=debug --pg1-path=/opt/postgres/bigsql/data/pg11 --process-max=2 --repo1-path=/var/lib/pgbackrest --set=20200802-150208F --stanza=big1
ERROR: [075]: backup set 20200802-150208F is not valid
P00   INFO: restore command end: aborted with exception [075]**

7. Describe the issue:
**Goal is to backup database from Node1(DBServer) and restore to Node2(DBServer) using pgbackrest. We were able to restore to the same node successfully but were unable to restore backupfile from Node1 to Node2. We were using pgdump for this purpose but wanted to replace pgdump with a PITR solution like pgbackrest.

Does PGBackrest have capability/feature to restore DB to a remotenode? Any other tools which can do above usecase?**

**Comment by dwsteele** [comment]
This is supported, you'll just need to have your repo located in when both servers can access it, for instance on a repo host (https://pgbackrest.org/user-guide.html#repo-host) or on S3 (https://pgbackrest.org/user-guide.html#s3-support). In either case the PG host is configured the same for the primary and standby. See (https://pgbackrest.org/user-guide.html#replication) for restoring to a standby.
