### ISSUE TITLE
Generating email alert from crontab after backups performed by schueduling with pgbackrest.

### ISSUE THREAD

**Issue by yeswithae** [pgbackrest/pgbackrest#1143]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.28

2. PostgreSQL version:psql (PostgreSQL) 12.1 (Ubuntu 12.1-1.pgdg18.04+1)

3. Operating system/version -  Ubuntu 18.04 LTS

4. Did you install pgBackRest from source or from a package:From Package

5. Please attach the following as applicable:
@pgbackrest conf:
  [rtt_cluster]
pg1-path=/var/lib/postgresql/12/rtt_cluster

[global]
repo1-path=/mnt/volume_blr1_01/dbbackup
repo1-cipher-pass=zWaf6XtpjIVZC5444yXB+cgFDFl7MxGlgkZSaoPvTGirhPygu4jOKOXf9LO4vjfO
repo1-cipher-type=aes-256-cbc
repo1-retention-full=1
repo1-retention-diff=2
log-level-file=detail

[global:archive-push]
compress-level=3
@postgresql.conf:
archive_command = 'pgbackrest --stanza=rtt_cluster archive-push %p'
archive_mode = on
listen_addresses = '*'
log_line_prefix = ''
max_wal_senders = 3
wal_level = replica

7. Describe the issue:
In crontab,I have scheduled full backup and diff based on requirement.Whenever backup happens It has to generate alert to mail.
I have tried the command mentioned for getting warning after completion of backups( sudo -u postgres pgbackrest --stanza=rtt_cluster --type=incr --log-level-file=warn backup).Still,I am Unable to get any warnings or alerts.Can,you please help me to get this.

**Comment by dwsteele** [comment]
`--log-level-file=warn` just sets the log level so if there are no warnings (usually the case) you won't get any output. The best thing is to set `--log-level-file=info` and use something like `tail_n_mail` to search for the backup completed log message, which will be `backup command end: completed successfully` on success and `backup command end: aborted with exception` on error.
