### ISSUE TITLE
how to syncronize multiple pgbackrest repositories for DR ( disaster recovery) purpose 

### ISSUE THREAD

**Issue by alizaaliza** [pgbackrest/pgbackrest#1145]
we are evaluating  use of pgbackrest  in our environments  .  it is most robust and reliable tool. 
environments include request to support DR .  (disaster recovery).
we would like to know if pgbackrest  already has support for synchronizing 2 repositories?
if not, than how it is recommended to synchronize  master repository with DR repository?

thanks in advance, Aliza.

**Comment by dwsteele** [comment]
Currently we don't automatically sync two repositories, though that functionality (in some form) is expected to be implemented this Fall.  However, you can use rsync to sync two repositories and this is pretty common for DR repositories.

**Comment by alizaaliza** [comment]
David thanks a lot,  
we would like to use rsync to synchronize archive directories, and take local backups at DR . 
( avoid syncing full backups over DR network)

when we try to backup remote/stand by leader we get:
It is impossible to backup DR leader as standby, even with backup-standby=y.
ERROR: [056]: unable to find primary cluster - cannot proceed 


we manage to backup at the DR only if we remove from the DR/pgbackrest.conf   the  specification of the replica, and leave the leader only. 

is there a way to enable backup at the DR without removing the replica from pgbackrest.conf ?

**Comment by dwsteele** [comment]
`backup-from-standby` requires contact with the primary.
