### ISSUE TITLE
Requesting to post a solution on restores on remote nodes . say backup on hots1 and restore the same backup on host2,host3..hostn.. I get error like "invalid backup set"

### ISSUE THREAD

**Issue by martinvijayster** [pgbackrest/pgbackrest#1147]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by pgstef** [comment]
Hi,

There are several ways to restore a backup set on another host than the backup host.
It really depends on your architecture, how/where your perform the backups etc...

To be able to help / advice you, we'll need you to provide the information requested in the issue description (pgBackRest / PostgreSQL version, OS, configuration files, steps performed, logs,...)

Kind regards

**Comment by martinvijayster** [comment]
Hi Stefan,

pgBackRest  Version: 2.27
PostgreSQL version : 11.5 
OS, configuration files :, **pgbackrest.conf**
[dev5]
pg1-path=/opt/postgres/bigsql/data/pg11/
log-level-console=info
pg1-socket-path=/var/run/postgresql/


[global]
log-level-file=detail
repo1-path=/var/lib/pgbackrest/
#repo-cipher-pass=Waf6XtpjIVZC5444yXB+cgFDFl7MxGlgkZSaoPvTGirhPygu4jOKOXf9LO4vjfO
#repo1-cipher-type=aes-256-cbc
#repo1-path=/var/lib/pgbackrest
repo1-retention-diff=1
repo1-retention-full=2
repo1-s3-bucket=
repo1-s3-endpoint=
#repo1-s3-key=
#repo1-s3-key-secret=
#repo1-s3-region=None
#repo1-s3-verify-ssl=y
start-fast=y
stop-auto=y

[global:archive-push]
compress-level=3

steps performed ::::
Commands I used:
backup
-------------
pgbackrest --stanza=big1  --log-level-console=info --type=full backup

I copied my backupfile to a managed s3 folder in the new server and applied the restore commands below:
restore
---------
pgbackrest --stanza=big1 --delta  --set=20200702-151505F  restore

 logs ::
--------
I copy my backup taken from one server to other new server  and on restoring them I get below error
Error messages from log files:

-------------------PROCESS START-------------------
2020-08-11 18:16:18.531 P00   INFO: restore command begin 2.27: --delta --log-level-console=info --log-timestamp --pg1-path=/opt/postgres/bigsql/data/pg11 --repo1-path=/var/lib/pgbackrest --set=20200702-151505F --stanza=big1
2020-08-11 18:16:18.533 P00  ERROR: [075]: backup set 20200702-151505F is not valid
2020-08-11 18:16:18.533 P00   INFO: restore command end: aborted with exception [075]

Error message 2:
==========
2020-08-12 16:25:38.774 P00   INFO: restore command begin 2.27: --delta --log-level-console=info --log-level-file=debug --pg1-path=/opt/postgres/bigsql/data/pg11 --process-max=2 --repo1-path=/var/lib/pgbackrest --set=20200802-150208F --stanza=big1

ERROR: [075]: backup set 20200802-150208F is not valid

2020-08-12 16:25:38.776 P00   INFO: restore command end: aborted with exception [075]

Pls drop  me a solution ASAP on priority as I need on  a High priority basis  ..

Pls let me know if you know any information more
,...

**Comment by martinvijayster** [comment]
here are my postgresql.conf parameters
-------------------------------------------
listen_addresses='*'
port=5432(normal port)
archive_mode = on 
max_wal_senders=10
archive_command = 'pgbackrest --stanza=big1 archive-push %p' 
wal_level=replica

**Comment by pgstef** [comment]
First of all, you don't need the `repo1-s3*` options in your configuration file if the backups are stored locally (on a posix filesystem).

How do you copy your backup to some other location ? What do you copy exactly ?

The pgBackRest configuration on the host where you try to restore could be interesting to see also.

To know if "20200802-150208F" is a valid backup set or not, could you run `pgbackrest --stanza=big1 info` ?

**Comment by martinvijayster** [comment]
Hi Stefan,
All of my scenarios is for Cross/remote node restores.
repo1-s3  is just my S3 bucket details .just I copy my backup files in 2 ways  
I)copy backups into S3 location and download it to my target server and restore them. 
2)SCP command to transfer backups to target servers
after copying the backups and restore command on them,
In this process, I am getting the above error

Pls drop me with the fix as you were stating
"There are several ways to restore a backup set on another host than the backup host.
It really depends on your architecture, how/where your perform the backups etc..."

**Comment by pgstef** [comment]
I don't have a "fix". I said it was possible to perform restores on other hosts **but** it depends on the architecture.

I specifically asked you what you copy because simply copy the backup set directory isn't enough. We don't have that possibility yet.

Usually, I store the backups on a shared location (definitively not locally on the production server...) and I mount that shared location on the host where I want to restore the backup (on **read-only** mode, to be sure it won't mess with the production backups). This shared location could be a S3 bucket directly. 

By the way, the `repo1-s3` parameters won't be used unless you set the repo-type (https://pgbackrest.org/configuration.html#section-repository/option-repo-type). 

The other possibility would be to have a dedicated backup host.

In any case, `pgbackrest --stanza=big1 info` should behave correctly on the host where you want to restore to make sure everything's fine.

In your situation, I guess you could try to synchronize the complete pgbackrest repository (`/var/lib/pgbackrest/`) to the host where you want to perform the restore but I would rather suggest you to store your backups on a shared (and safe) location rather than keeping it locally on your production server...

**Comment by dwsteele** [comment]
Agree with @pgstef. This is supported, but it is best to have your repo located in when both servers can access it, for instance on a repo host (https://pgbackrest.org/user-guide.html#repo-host) or on S3 (https://pgbackrest.org/user-guide.html#s3-support). In either case the PG host is configured the same for the primary and standby. See (https://pgbackrest.org/user-guide.html#replication) for restoring to a standby.

Please understand that issues are primarily for reporting bugs. We'll help out with specific problems but won't do system architecture for you.

**Comment by martinvijayster** [comment]
ok I go with your comments.I am going forward with a backup host(repository host) as suggested by you.

I get this below bug on backup from a repository host

creating a full backup
2020-08-17 14:05:42.222 P00   INFO: backup command begin 2.27: --backup-standby --compress --log-level-console=info --log-level-file=debug --pg1-host=dev-bigsql-04.test.villagemd.com --pg1-host-user=postgres --pg1-path=/opt/postgres/bigsql/data/pg11 --pg1-socket-path=/var/run/postgresql --process-max=2 --repo1-path=/var/lib/pgbackrest --repo1-retention-diff=7 --repo1-retention-full=7 --stanza=big1 --type=full
ERROR: [056]: unable to find standby cluster - cannot proceed
2020-08-17 14:05:43.197 P00   INFO: backup command end: aborted with exception [056]
pls help me spot out the error

**Comment by martinvijayster** [comment]
Here in my entire setup we are not using replication ie primary and standby but using a passwordless SSH setup across nodes .
will it work without replication setups

**Comment by pgstef** [comment]
Yes, it will work without Streaming Replication. In the backup command, there's "--backup-standby". That means you requested a backup from a replicated standby PG host. Remove that from your configuration and it should work better.
