### ISSUE TITLE
Does pgBackRest use log_line_prefix from postgresql.conf?

### ISSUE THREAD

**Issue by kmatt** [pgbackrest/pgbackrest#1153]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.28

2. PostgreSQL version: 11.0

3. Operating system/version: CentOS 7.8.2003

4. Did you install pgBackRest from source or from a package? yum

Describe the issue:

pgBackRest seems to emit messages into the Postgres logs in a format that does not match that set in postgresql.conf `log_line_prefix`. This makes watching for log events with tail_n_mail difficult: https://github.com/bucardo/tail_n_mail/issues/35

Is there an approach for configuring pgBackRest log messages to match those emitted by the postmaster?

**Comment by dwsteele** [comment]
We are not planning to change this behavior. It's common for logs from `archive_command` to end up in the PG logs and the cost/benefit here does not look favorable.

You can always set `--log-level-console=none` on your `archive_command` and monitor the `archive-async` log for errors (assuming you have async logging enabled).
