### ISSUE TITLE
Restore not working

### ISSUE THREAD

**Issue by ssgottik** [pgbackrest/pgbackrest#1155]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.28

2. PostgreSQL version:12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos7

4. Did you install pgBackRest from source or from a package? 
 --- Package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Before taking the backup I created a database called sportsdb and loaded some dummy data into it. Once the data is  loaded I have taken full backup using below command : 

pgbackrest --stanza=***** backup

-bash-4.2$ pgbackrest info
stanza: ****
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1): 000000010000000000000006/000000010000000000000006

        full backup: 20200821-001634F
            timestamp start/stop: 2020-08-21 00:16:34 / 2020-08-21 00:16:50
            wal start/stop: 000000010000000000000006 / 000000010000000000000006
            database size: 48.8MB, backup size: 48.8MB
            repository size: 5.9MB, repository backup size: 5.9MB

And restored using below commands ---used 3 options but sportsdb is not getting restored 👍 

pgbackrest --stanza=7epdb restore

pgbackrest --stanza=7epdb --delta --db-include=sportsdb restore

pgbackrest --stanza=7epdb --log-level-console=info --db-path=/pgData/pg12 restore

**Comment by pgstef** [comment]
Hi,

Could you please share your `pgbackrest.conf` file and `postgresql.conf` specific settings (archive_command, archive_mode, listen_addresses, max_wal_senders, wal_level, port) ?

What does `pgbackrest --stanza=7epdb --log-level-console=info check` return ?

Do you try to restore on the same host / directory as your primary cluster ? 

Kind regards,
