### ISSUE TITLE
restore single database back to the cluster of databases

### ISSUE THREAD

**Issue by aogb** [pgbackrest/pgbackrest#1157]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

Please provide the following information when submitting an issue (feature requests or general comments can skip this):

pgBackRest version: 2.28

PostgreSQL version: 12

Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu Linux

Did you install pgBackRest from source or from a package? Source

Please attach the following as applicable:

pgbackrest.conf file(s)
pgbackrest.conf file(s)
[demo]
pg1-path=/pgdata/postgresql/data
[global]
repo1-path=/pgdata/pgbackrest
repo1-retention-full=2
postgresql.conf settings applicable to pgBackRest (archive_command, archive_mode, listen_addresses, max_wal_senders, wal_level, port)
archive_command - 'pgbackrest --stanza=demo archive-push %p'
archive_mode - On
listen_addresses - *
max_wal_senders = 3
wal_level = replica

errors in the postgresql log file before or during the time you experienced the issue
N/A
log file in /var/log/pgbackrest for the commands run (e.g. /var/log/pgbackrest/mystanza_backup.log)
N/A
Describe the issue:
I have a cluster of databases in a single postgresql instance  and one of the database was accidentally dropped. Could you please guide on how to restore this single database back to the cluster of databases?

**Comment by aogb** [comment]
My use case is i want to be able to restore the single database back to the cluster of database. I do not want the situation where entire database would be restored as sparse, zeroed files because I have only specified to restore the single database.

**Comment by dwsteele** [comment]
If you want to restore a database into an existing cluster you'll need to `pg_dump` the database then restore it.

**Comment by aogb** [comment]
the use case is the database was dropped and I cannot take or have pg_dump of the database. Is there no way to recover or restore such?

**Comment by dwsteele** [comment]
You'll have to restore the backup using pgBackRest to another host, then pg_dump the database and restore it into the cluster. Or if the data in the other databases is not important, you can use PITR to recover all the databases to the time just before you dropped the one database, see https://pgbackrest.org/user-guide.html#pitr.

**Comment by aogb** [comment]
Yes i thought about the first option you mentioned but i still struggles restoring to another host.
Any pointer restoring to another host would be helpful.

Thank you.
