### ISSUE TITLE
[Doc] Add description of 'pgbackrest info' in command references

### ISSUE THREAD

**Issue by Krysztophe** [pgbackrest/pgbackrest#1158]
The [command reference for `pgbackrest info` ](https://pgbackrest.org/command.html#command-info) does not describe what is the meaning of the different sizes returned by the output.

It is hidden in the User Guides, that I won't read anymore now that I'm accustomed to pgBackRest.

This would be the same text as in https://pgbackrest.org/user-guide.html#quickstart/backup-info

**Comment by sfrost** [comment]
Hah. yeah, I tend to agree with this.

**Comment by dwsteele** [comment]
Makes sense to me.

**Comment by dwsteele** [comment]
Done in PR #1185.

**Comment by Krysztophe** [comment]
Thanks !
