### ISSUE TITLE
backup replica - does it mitigate possible lag

### ISSUE THREAD

**Issue by alizaaliza** [pgbackrest/pgbackrest#1162]
Hi David, 

We have leader/replica architecture and want to perform backups of replica (with copy_archive=y option)
Does pgbackrest take into consideration possible lags on replica side as start/stop wal files names are taken 
from leader cluster but  datafiles themselves are taken from replica.
thanks in advance Aliza/Oleg.

**Comment by dwsteele** [comment]
The backup is started on the primary but we wait until the standby catches up to the backup start `lsn` before proceeding with the backup. You can see how that works here: https://github.com/pgbackrest/pgbackrest/blob/release/2.29/src/command/backup/backup.c#L889.

**Comment by oleg-beltz** [comment]
Does this wait condition have any timeout or will wait indefinitely till standby catch up?

**Comment by dwsteele** [comment]
It will wait indefinitely as long as there is *some* progress within `archive-timeout` (default 60 seconds).
