### ISSUE TITLE
Question: Performance concern while restoring a series of incremental backups

### ISSUE THREAD

**Issue by insafk** [pgbackrest/pgbackrest#1166]
Hello,

We are evaluating pgBackRest, and our main focus is to restore as quickly as possible, backup sizes wouldn't matter that much.

I have one question regarding restoring from multiple incremental backups.

Let's say we've taken a full backup on Sunday, and then daily incremental backups.

So the sizes could be:

```
Sunday FullBackup 300GB
Monday IncrBackup 115GB
Tuesday IncrBackup 90GB
...
...
...
Saturday IncrBackup 40GB
```
Now, while restoring, will pgBackRest extract all of the backups ie, 300+115+90+...+40GB (or) will it apply any intelligence to reduce the data to be restored?
Like, let's say, multiple versions of the same file exist in each of the Incremental-Backups, so it's better to extract the final version of the file alone. Is there any such optimization done?

**Comment by sfrost** [comment]
pgbackrest will look at the manifests and determine the exact set of files which are needed for the restore and will restore only those files and only once.

If you'd like fast restore times then you should also be looking at pgbackrest's --delta restore option, which will further avoid copying files from the repository by checking if the existing file's SHA hash matches the hash that we have stored in the manifest, when you're restoring over top of an existing PG cluster.

**Comment by insafk** [comment]
Thank you, Stephen, for the quick response.

Closing the issue.
