### ISSUE TITLE
recovery failing 

### ISSUE THREAD

**Issue by narendrapostgresdba** [pgbackrest/pgbackrest#1168]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.27

2. PostgreSQL version:11.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Red Hat Enterprise Linux Server release 7.7

4. Did you install pgBackRest from source or from a package? package 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

we are trying to restore backup from NAS which is attached to two servers (source and target ) . restore got completed , but when we tried to start postgres instance getting error as below .

2020-09-08 05:44:01.500 EDT [13480] LOG:  starting point-in-time recovery to 2020-09-07 23:04:34-04
2020-09-08 05:45:01.530 EDT [13480] LOG:  invalid checkpoint record
2020-09-08 05:45:01.530 EDT [13480] FATAL:  could not locate required checkpoint record
2020-09-08 05:45:01.530 EDT [13480] HINT:  If you are not restoring from a backup, try removing the file "/pgDATA/11/data/backup_label".
2020-09-08 05:45:01.534 EDT [13477] LOG:  startup process (PID 13480) exited with exit code 1
2020-09-08 05:45:01.534 EDT [13477] LOG:  aborting startup due to startup process failure
2020-09-08 05:45:01.728 EDT [13477] LOG:  database system is shut down

**Comment by pgstef** [comment]
Hi,

Could you please provide:
* `pgbackrest.conf`;
* `pgbackrest info` output;
* the restore command you used;
* the content of the generated `recovery.conf`.

It look likes something is missing to reach the time point you requested. If a timeline switch occurred after your last backup, you might need to add `--target-timeline=latest` to your restore command. The info command output will give us more information to help.

Kind regards

**Comment by narendrapostgresdba** [comment]
Hi ,

please find requested info below

 [global]
repo1-host=*38.*
repo1-host-user=postgres
repo1-host-config=/etc/pgbackrest.conf
repo1-path=/pgBACKUP2/**
process-max=8
archive-async=y
archive-get-queue-max=104857600

[*]
pg1-path=/var/lib/pgsql/11/data


    status: ok (backup/expire running)
    cipher: none

    db (current)
        wal archive min/max (11-1):
0000000100000E860000001A/0000000100000E920000008D

        full backup: 20200906-200002F
            timestamp start/stop: 2020-09-06 20:00:02 / 2020-09-06 22:19:58
            wal start/stop: 0000000100000E860000001A /
0000000100000E8600000042
            database size: 1972.3GB, backup size: 1972.3GB
            repository size: 208.1GB, repository backup size: 208.1GB

        incr backup: 20200906-200002F_20200907-230002I
            timestamp start/stop: 2020-09-07 23:00:02 / 2020-09-07 23:04:34
            wal start/stop: 0000000100000E8B00000082 /
0000000100000E8B00000082
            database size: 1973.3GB, backup size: 43.5GB
            repository size: 208.3GB, repository backup size: 5GB
            backup reference list: 20200906-200002F

        incr backup: 20200906-200002F_20200908-230002I
            timestamp start/stop: 2020-09-08 23:00:02 / 2020-09-08 23:06:28
            wal start/stop: 0000000100000E920000006E /
0000000100000E920000006F
            database size: 1974.3GB, backup size: 61.7GB
            repository size: 208.4GB, repository backup size: 6.9GB
            backup reference list: 20200906-200002F,
20200906-200002F_20200907-230002I


 nohup pgbackrest  --stanza=*   --db-path=/pgDATA/11/data  restore
 --set=20200906-200002F_20200907-230002I >> restore_08092020.log &

recovery.conf file generated with below entry

restore_command = 'pgbackrest --pg1-path=/pgDATA/11/data --stanza=****
archive-get %f "%p"'

I added one more entry to the file before starting the instance

recovery_target_time ='2020-09-07 23:04:34'

Regards,
Narendra

**Comment by pgstef** [comment]
Hi,

Your `recovery_target_time` seems to match with the stop time of the backup set. With that target, PostgreSQL apparently can't reach its consistency point. Your target seems then to be just a little bit too early. 

Try to increase your `recovery_target_time` a little bit, like a few ms.
(You normally don't need to perform a restore again. Just change the setting and restart your pg service)

Given you pgBackRest, I would recommend you to use the `--type=time --target=...` of the restore command (https://pgbackrest.org/command.html#command-restore). This will generate the `recovery_target_time` **and** also select the right backup set to apply. So you won't need to provide the `--set` option.

Regards,

**Comment by narendrapostgresdba** [comment]
Hi,

I changed the time and it worked.

Thanks for your help

Regards,
Narendra
