### ISSUE TITLE
configure pgbackrest  both as  "local" and "remote" on the same server

### ISSUE THREAD

**Issue by alizaaliza** [pgbackrest/pgbackrest#1169]
Hi to the pgbackrest team

we have topology with   leader/replica and remote standby with additional  leader/replica.
we would like to locate pgbackrest repository on NFS . 
1) run the archive/restore via pgbackrest in "local" mode, so pgbackrest will read/write directly to NFS
2) run backups from separated backup server.
( motivation is to simplify the system, avoid additional load balancer and multiple backup servers)

we faced some issues, and would like to ask
is it at all possible to support such functionality?

**Comment by dwsteele** [comment]
That all looks fine but you haven't provided configuration or stated the problem you are having, so it is hard to say for sure.

What you are doing looks pretty much like the setup described in https://pgbackrest.org/user-guide-centos7.html#repo-host.

**Comment by alizaaliza** [comment]
HI David, thanks, it works.

we configured the pgbackrest backup server to work also with postgres user instead of pgbackrest user, and all works:

ie
1) “archive” with stand-alone configuration ( directly to NFS) and backup from backup separated 
2) backup with “Dedicated Repository Host” configuration

and now all work well,
tx!

**Comment by dwsteele** [comment]
Glad you got it working!

**Comment by alizaaliza** [comment]
Yes. thanks a lot!
sincerely!
great organized product.
