### ISSUE TITLE
Is it possible to give global/default values for all stanza(value for path, port and some other params)?

### ISSUE THREAD

**Issue by insafk** [pgbackrest/pgbackrest#1176]
Hello,

Is it possible to set a default value for pg1-path, pg1-port, pg1-user and so on for all the stanza's within the repo?
We'll be deploying each of the PG servers in the same path, port and so on. The only value that differs will be the hostname/IP. 

### Current approach

```ini
[stanza1]
pg1-host=dbhost1_1
pg1-port=6000
pg1-socket-path=/tmp
pg1-path=/home/test/db/datadir
pg1-user=backupuser
pg2-host=dbhost1_2
pg2-port=6000
pg2-socket-path=/tmp
pg2-path=/home/test/db/datadir
pg2-user=backupuser

[stanza2]
pg1-host=dbhost2_1
pg1-port=6000
pg1-socket-path=/tmp
pg1-path=/home/test/db/datadir
pg1-user=backupuser
pg2-host=dbhost2_2
pg2-port=6000
pg2-socket-path=/tmp
pg2-path=/home/test/db/datadir
pg2-user=backupuser

[global]
repo-path=/home/test/pgbackrest/repo
start-fast=y

[global:backup]
process-max=8
```

### Preferred approach

```ini
[global]
or
[allstanza]
pg*-port=6000
pg*-path=/home/test/db/datadir
pg*-socket-path=/tmp
pg*-user=backupuser

[stanza1]
pg1-host=dbhost1_1
pg2-host=dbhost1_2

[stanza2]
pg1-host=dbhost2_1
pg2-host=dbhost2_2

[global]
...
...
```

Which makes the conf file easier to manage.

Is it possible?

Thanks

**Comment by pgstef** [comment]
Hi,

At this time, I don't think that will be possible. `pg*-` options are [stanza only](https://pgbackrest.org/configuration.html#section-stanza). Global section is more intended to contain the repo configuration.

I would suggest to use the configuration include path. By default [/etc/pgbackrest/conf.d](https://pgbackrest.org/configuration.html#section-repository/option-repo-host-config-include-path). There, you can create (eg.) 1 file per stanza:

```
$ cat /etc/pgbackrest/conf.d/stanza.conf 
[stanza1]
pg1-host=dbhost1_1
pg1-port=6000
pg1-socket-path=/tmp
pg1-path=/home/test/db/datadir
pg1-user=backupuser
pg2-host=dbhost1_2
pg2-port=6000
pg2-socket-path=/tmp
pg2-path=/home/test/db/datadir
pg2-user=backupuser
```

That's the easiest approach when using some configuration management tool.

Maybe @dwsteele will have a clue if we could support stanza-only options in the global part in the future or not.

Kind regards

**Comment by dwsteele** [comment]
It's not possible to default the pg* options in this way. It's a bigger feature than you'd think because of integration with the various ways we do config, though I don't think it's impossible.

However, at this time it's not something we are planning.

**Comment by insafk** [comment]
Thank you for your replies.

The model suggested by @pgstef seems good enough for now.
