### ISSUE TITLE
Archive push unexpectedly fails pgBackRest version on PG server does not match version on repository host

### ISSUE THREAD

**Issue by loop-evgeny** [pgbackrest/pgbackrest#1183]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.28/2.29

2. PostgreSQL version: 12.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package? APT package

I have pgBackRest configured to push to a remote repository host. After it was upgraded to 2.29 on the PostgreSQL server, but remained at 2.28 on the repository host archive push failed with the following error:

```
2020-09-22 07:41:48.214 UTC [49513] LOG:  archive command failed with exit code 39
2020-09-22 07:41:48.214 UTC [49513] DETAIL:  The failed archive command was: pgbackrest --stanza="mystanza" archive-push "pg_wal/00000003000000050000008E"
ERROR: [039]: expected value '2.29' for greeting key 'version' but got '2.28'
```

That is quite a gotcha! It's an unexpected, and (as far as I can see), undocumented, limitation. I would expect minor version upgrades to preserve over-the-wire compatibility, just like I'd expect rsync 3.1.1 to be able to sync with rsync 3.1.2.

This has bitten users before, e.g. #1026 and #768. A comment in #768 says "The versions must match. We'd like to remove this requirement some day but during the C migration the protocol is changing with every version." Is that still on-going? If so, it should at least be documented in https://pgbackrest.org/user-guide.html#repo-host.

I'd suggest creating and documenting a versioning strategy that allows users to avoid such nasty surprises. That is, the user should be able to tell from the version number whether a change is breaking or not and [allow only non-breaking upgrades using APT pinning](https://askubuntu.com/a/1006944/298003). The typical policy would be to increment the major version number for backwards-incompatible changes.

**Comment by loop-evgeny** [comment]
For now I will just have to dpkg-hold the exact pgBackRest package version so it's not automatically upgraded at all.

**Comment by dwsteele** [comment]
> Is that still on-going?

The C migration is complete but we are rapidly adding features. Even though the protocol does not change much any more there are still things we expect the remote to be able to do with each new feature.

However, we are starting to work towards a capability system so the older remote only errors when you attempt to use a new feature. We don't know when this work will be complete.

> I'd suggest creating and documenting a versioning strategy

Agreed that this limitation should be documented and we'll do so before we close this issue. We'll also add a hint to the error you got to make it clearer that the pgBackRest versions must match.

**Comment by dwsteele** [comment]
See PR #1184 for new hint and documentation. Better?

Also, let us know if you'd like to appear in the release notes as other than `loop-evgeny`.

**Comment by loop-evgeny** [comment]
That looks good, thank you!
