### ISSUE TITLE
pgBackRest setup with firewall blocking connections from backup->DB 

### ISSUE THREAD

**Issue by jjoooosseepp** [pgbackrest/pgbackrest#1187]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.29
2. PostgreSQL version:
11
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu
4. Did you install pgBackRest from source or from a package?
package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Hi, as I haven't found any help on the topic and no better place to ask this question I'll ask it here.
Is it possible to set up the pgbackrest (in backup server) in a way that it does not need to connect to the DB servers?

A strange question so I'll elaborate a bit. The setup in the company where I work is such that we have separate backup servers that are quite closed off and all the files are either pushed to or pulled from there. 
I'm investigating the possibility to start using pgbackrest but I'm getting blocked by the stanza creation part in the backup server because it tries to contact the DB and getting blocked by the firewall ( traffic orginating from backup going towards to DB servers is not allowed ).
I understand that without two-way communication between backup and DB servers we cannot use all the features of pgbackrest but at this point in time I'd like to set up a simple solution where the pgbackrest takes care of the archive_command in the master and restore_command in the standby servers. So I don't see a reason why the backup server would even need to initate any communications towards the DB.

**Comment by cmwshang** [comment]
You should be able to create the stanza with the --no-online option https://pgbackrest.org/command.html#command-stanza-create

**Comment by dwsteele** [comment]
You might be able to create the stanza this way (if you have ssh access not not PG access) but you won't be able to make a backup. Currently backups must be taken from the repo host if there is one.

An alternative is to mount the storage to the PG host and do the backup directly from that host.
