### ISSUE TITLE
Add Support For Azure Government Blob

### ISSUE THREAD

**Issue by brimo2k** [pgbackrest/pgbackrest#1188]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.29

2. PostgreSQL version: 11.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

 Ubuntu 18.04.2 LTS

4. Did you install pgBackRest from source or from a package?

via APT

5. Please attach the following as applicable:

[azureblob]
pg1-path=/psql/postgresql/11/main
repo1-azure-host=**core.usgovcloudapi.net**
repo1-azure-account=<redacted>
repo1-azure-container=<redacted>
repo1-azure-key=<redacted>
repo1-cipher-pass=<redacted>
repo1-cipher-type=aes-256-cbc
repo1-retention-full=8
repo1-retention-diff=48
start-fast=y
process-max=2
compress-level=3
repo1-type=azure

7. Describe the issue:

Since pgbackrest seems to be fully working with Azure Blob Storage Container now; it would be simple to also support the Government sector host format.

I'm not quite sure how to the URI is built to fetch the resource but in the Azure docs you can see the difference in endpoints for their blob service: 

 *.blob.core.windows.net ("Normal Azure -- existing support") 

 *.blob.core.usgovcloudapi.net ("Azure Gov -- Add support")

Specifying the `repo-azure-host` simply to core.usgovcloudapi.net yields (and the same for core.windows.net)  :

DEBUG:     common/io/socket/client::sckClientOpen: retry HostConnectError: unable to get address for 'core.usgovcloudapi.net': [-5] No address associated with hostname

There may be an issue with the Resource endpoint building when specifying manually.

edit: document specifying the endpoint difference (scroll to storage)
https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure

**Comment by dwsteele** [comment]
Host and endpoint are not exactly the same thing -- with an endpoint we prepend the container but with a host we do not. The host option is primarily intended for testing with a local implementation such as Azurite.

So, looks like we would need to add a `repo-azure-endpoint` option that defaults to `blob.core.windows.net`.

Would you be able to test that for us if we provide a branch with the change? You'd need to be comfortable building from source using the instructions at https://pgbackrest.org/user-guide.html#build.

**Comment by brimo2k** [comment]
@dwsteele Sure thing. I could build and test. It's the least I can do for you guys and this awesome piece of software. Thanks!

**Comment by dwsteele** [comment]
OK, we'll put together a PR and tag you when we're ready for you to test. Thanks!

**Comment by dwsteele** [comment]
@brimo2k PR #1190 implements this feature. Please have a look.

**Comment by brimo2k** [comment]
@dwsteele - Compiled, and ran beautifully. Let me know if there are any specific tests that need to be ran or verified or anything like that. I seem to be archiving WAL logs and just finished a Full & Differential backup to Azure Gov Blob. I don't suppose there should be any issues with restore; though I would be willing to do so if that would complete the pull request verification. 

Thanks!

**Comment by dwsteele** [comment]
It wouldn't hurt to do a restore, but you have covered all the driver functions with archive-push/backup.

Also let us know if you would like to appear in the release notes as other than @brimo2k.

**Comment by dwsteele** [comment]
Committed at 9377d050.
