### ISSUE TITLE
[025]: invalid sleep for online backup time with wait remainder

### ISSUE THREAD

**Issue by vitabaks** [pgbackrest/pgbackrest#1189]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.29
2. PostgreSQL version:
9.3.16
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

database server: Debian GNU/Linux 7 (3.2.0-4-amd64)
repository host server: Debian GNU/Linux 8 (3.16.0-4-amd64)

4. Did you install pgBackRest from source or from a package?

 from source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

No errors in the postgresql log
pgbackrest log:  [tvmail-backup.log](https://github.com/pgbackrest/pgbackrest/files/5310341/tvmail-backup.log)

7. Describe the issue:
The problem arose after upgrading from version 2.23 to 2.29.

```
ASSERT: [025]: invalid sleep for online backup time with wait remainder
        --------------------------------------------------------------------
        If SUBMITTING AN ISSUE please provide the following information:

        version: 2.29
        command: backup
        options: --archive-check --no-archive-copy --no-backup-standby --compress --compress-level=6 --log-level-console=debug --log-level-file=debug --pg1-host=<server_ip> --pg1-path=/var/lib/postgresql/9.3/main --pg1-port=5432 --process-max=1 --repo1-path=/home/backuper/pgbackrest --repo1-retention-archive=2 --repo1-retention-archive-type=full --repo1-retention-full=4 --no-resume --stanza=tvmail --start-fast --stop-auto --type=full

        stack trace:
        command/backup/backup:backupTime:331:(backupData: {BackupData}, waitRemainder: true)
        command/backup/backup:cmdBackup:(void)
        main:main:(debug log level required for parameters)
        --------------------------------------------------------------------
2020-10-01 10:35:26.597 P00   INFO: backup command end: aborted with exception [025]
2020-10-01 10:35:26.597 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)
2020-10-01 10:35:26.597 P00  DEBUG:     common/lock::lockRelease: => true
2020-10-01 10:35:26.597 P00  DEBUG:     common/exit::exitSafe: => 25
2020-10-01 10:35:26.597 P00  DEBUG:     main::main: => 25
```

**Comment by vitabaks** [comment]
There were no problems during the checks in the test segment.

**Comment by vitabaks** [comment]
The problem has been resolved.

I accidentally copied a binary file compiled for debian 8, but in this case I needed a pgbackrest binary file compiled for debian 7 ...

**Comment by vitabaks** [comment]
There was a problem again

error:

> 2020-10-05 10:16:14.856 P00   INFO: execute exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
> WARN: the cluster is already in backup mode but no pgBackRest backup process is running. pg_stop_backup() will be called so a new backup can be started.
> 2020-10-05 10:16:19.422 P00   INFO: backup start archive = 000000010000286B00000026, lsn = 286B/260004B8
> ASSERT: [025]: invalid sleep for online backup time with wait remainder
>         --------------------------------------------------------------------
>         If SUBMITTING AN ISSUE please provide the following information:
> 
>         version: 2.29
>         command: backup
>         options: --archive-check --no-archive-copy --no-backup-standby --compress --compress-level=6 --log-level-console=info --log-level-file=detail --pg1-host=192.168.156.210 --pg1-path=/var/lib/postgresql/9.3/main --pg1-port=5432 --process-max=1 --repo1-path=/home/backuper/pgbackrest --repo1-retention-archive=2 --repo1-retention-archive-type=full --repo1-retention-full=4 --no-resume --stanza=tvmail --start-fast --stop-auto --type=full
> 
>         stack trace:
>         command/backup/backup:backupTime:331:(debug log level required for parameters)
>         command/backup/backup:cmdBackup:(debug log level required for parameters)
>         main:main:(debug log level required for parameters)
>         --------------------------------------------------------------------
> 2020-10-05 10:16:22.735 P00   INFO: backup command end: aborted with exception [025]

**Comment by vitabaks** [comment]
I ran the backup command several times in a row and after several attempts the backup was successful.
That is, it does not work stably.

With more recent versions of debian (8,9,10) and postgres (9.4,10,11) do not have such a problem.

**Comment by dwsteele** [comment]
This is an odd issue. It could be some kind of clock skew on older OSes / versions of PG. I guess we could put retry here (https://github.com/pgbackrest/pgbackrest/blob/release/2.30/src/command/backup/backup.c#L331) to fix this. Feel free to have a look at the logic here and make sure it seems right to you.

**Comment by vitabaks** [comment]
The time difference between the pgBackRest repository and the PostgreSQL server is no more than 15 seconds.

I did not of clock skew between OS and PG
```
postgres=# \! date
Thu Oct  8 16:01:28 MSK 2020
postgres=# select now();
              now
-------------------------------
 2020-10-08 16:01:28.912721+03
```

The backup is still executed after only a few attempts.

P.S.
I understand that these are too old OS and PG versions, but this service is already without support and we are not sure that it will work correctly on the new PG version.

**Comment by dwsteele** [comment]
Added retries in #1248 which should address this issue. Please have a look.
