### ISSUE TITLE
pg lib can't found error

### ISSUE THREAD

**Issue by longtian001** [pgbackrest/pgbackrest#1200]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.30
2. PostgreSQL version:
(PostgreSQL) 11.0
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

CentOS Linux release 7.8.2003 (Core)

4. Did you install pgBackRest from source or from a package?
from source, as following:

# export PATH=/opt/pgsql/11.0/bin:$PATH
# export LD_LIBRARY_PATH=/opt/pgsql/11.0/lib
# tar zxvf pgbackrest-release-2.30.tar.gz
# cd pgbackrest-release-2.30/src
# ./configure
# make
# make install
install -d /usr/local/bin
install -m 755 pgbackrest /usr/local/bin
#

5. Please attach the following as applicable:
 repsitory host:
$ more /etc/pgbackrest/pgbackrest.conf 
[main]
pg1-path=/pgdata
pg1-port=5432
pg1-host=192.168.43.185
pg2-path=/pgdata
pg2-port=5432
pg2-host=192.168.43.7

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y
$ 

db-host():
# more /etc/pgbackrest/pgbackrest.conf 
[main]
pg1-path=/pgdata
pg1-port=5432

[global]
log-level-file=detail
repo1-host=192.168.43.249
repo1-host-user=postgres
# 

all pg db postgres's setting:
$ more .bash_profile 
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
export PGROOT=/opt/pgsql/11.0
export PATH=$PGROOT/bin:$PATH:$HOME/.local/bin:$HOME/bin
export LD_LIBRARY_PATH=$PGROOT/lib:${LD_LIBRARY_PATH}
$ 

7. Describe the issue:

when i run command on repository, error like following:
$  pgbackrest --stanza=main --log-level-console=info stanza-create
2020-10-18 17:52:19.721 P00   INFO: stanza-create command begin 2.30: --log-level-console=info --pg1-host=192.168.43.185 --pg2-host=192.168.43.7 --pg1-path=/pgdata --pg2-path=/pgdata --pg1-port=5432 --pg2-port=5432 --repo1-path=/var/lib/pgbackrest --stanza=main
WARN: unable to check pg-1: [UnknownError] remote-0 process on '192.168.43.185' terminated unexpectedly [127]: pgbackrest: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
WARN: unable to check pg-2: [UnknownError] remote-0 process on '192.168.43.7' terminated unexpectedly [127]: pgbackrest: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
ERROR: [056]: unable to find primary cluster - cannot proceed
2020-10-18 17:52:20.034 P00   INFO: stanza-create command end: aborted with exception [056]
$ 

################################################################################
pgbackrest can't find libpq.so.5

**Comment by dwsteele** [comment]
Did you `sudo yum install postgresql-libs` as specified in https://pgbackrest.org/user-guide-centos7.html#installation?

There are packages available from yum.postgresql.org and I would recommend using those rather than building your own.

**Comment by longtian001** [comment]
Sometimes I will compile PG from source,
Maybe pgbackrest find libpq.so.5 in the OS's default lib dirs,
I also set LD_LIBRARY_PATH ENV , but it still show the errors above.
I have installed postgresql-libs,no errors found .

 thanks.
