### ISSUE TITLE
What method is used to copy backup to pgbackreset repository?

### ISSUE THREAD

**Issue by internetuser2008** [pgbackrest/pgbackrest#1202]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.2

2. PostgreSQL version: 10

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Linux

4. Did you install pgBackRest from source or from a package? package yum

5. What method is to copy backups from Postgres to pgbackrest repository?

6. Can that data be encrypted in transit? if so how?

7. I would like to set password for local postgres user on the master, how do I supply postgres user password, or create a backup user to preform a backup?

**Comment by pgstef** [comment]
Hi,

The copy happens at the file-system level, not using the Streaming Replication protocol (like `pg_basebackup`). 

The encryption has to be defined at the `stanza-create` time: https://pgbackrest.org/configuration.html#section-repository/option-repo-cipher-type.

The PostgreSQL access will be needed to execute `pg_start_backup()`, `pg_stop_backup()` and `pg_switch_wal()` at least. With PG 10, I think you'll need a `superuser` role if you don't want to use the `postgres` default one (and then configure the [pg-user](https://pgbackrest.org/configuration.html#section-stanza/option-pg-user) option).

The other point is the system user you'll use to perform the backup. This user needs to access the PGDATA directory to copy and be able to connect to PG with the provided `pg-user`. And then, use the PostgreSQL authentication methods to supply the password (like `~/.pgpass`).

The complete setup will depend on your situation (where's the repo located, multiple PG nodes,...). It can be tricky but it's possible.

What's your exact pgBackRest version? 2.02 ? If yes, it's a release that came out in May 2018... I'd really advice you to use the latest one (2.30).

Kind regards

**Comment by dwsteele** [comment]
Data is always encrypted in transit. When there are multiple hosts in your configuration, SSH is used for transport. TLS is used for S3/Azure requests.

In addition, if the repo is encrypted then the cluster data will be encrypted before leaving the database host.

**Comment by internetuser2008** [comment]
Thank you for clarifying.
