### ISSUE TITLE
Support for AWS credentials from env vars

### ISSUE THREAD

**Issue by james-callahan** [pgbackrest/pgbackrest#1203]
Does pgbackrest support AWS credentials from the environment?

  - `AWS_REGION`
  - `AWS_ACCESS_KEY`/`AWS_SECRET_ACCESS_KEY`
  - ambient EC2 credentials
  - IAM roles for service accounts (IRSA)

If not, could support be added?

**Comment by james-callahan** [comment]
Oh I see that https://github.com/pgbackrest/pgbackrest/pull/1137 was recently merged which appears to add support for ambient EC2 credentials; so that's at least one item ticked off.

**Comment by dwsteele** [comment]
You can set any pgBackRest option in an environment variable, see: https://pgbackrest.org/command.html#introduction

To automatically retrieve temporary credentials, see https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-key-type and https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-role.

**Comment by james-callahan** [comment]
For e.g. IRSA, AWS injects the environment variables `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE`: this isn't a place software can choose its own environment vars. See https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#pod-configuration for more information.

I believe the current "automatic" credentials only support using the role from EC2 metadata.

**Comment by dwsteele** [comment]
> I believe the current "automatic" credentials only support using the role from EC2 metadata.

And of course they couldn't just make EKS work the same way. Sigh.

Do you have an example of what this file (`AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token`) looks like? I did not find it in a brief scan of the docs.

It seems like you could break this out into pgBackRest env vars in a startup script. Presumably these env vars get updated with new credentials from time to time but I'm not sure how a running process is supposed to pick those changes up.

**Comment by james-callahan** [comment]
> Do you have an example of what this file (`AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token`) looks like? I did not find it in a brief scan of the docs.

it looks to be a JWT token.
But I don't think the format of the contents matter: I believe you send the entire contents of this file to https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html in the `WebIdentityToken` parameter


> It seems like you could break this out into pgBackRest env vars in a startup script. Presumably these env vars get updated with new credentials from time to time but I'm not sure how a running process is supposed to pick those changes up.

I think you have to renew your token by hitting the `AssumeRoleWithWebIdentity` endpoint every 15 minutes to 12 hours (you can pick expiry with the `DurationSeconds` parameter I think? though I think admins can set a max time, so you may not get the duration you request). Therefore doing it in a startup script wouldn't work.

**Comment by dwsteele** [comment]
This looks like a good feature, but we don't have any plans to work on it in the foreseeable future. There are simply too many higher priority items in our roadmap.

The trick with this feature is having the right environment to test it in, which we don't have. If you write a patch we'd be willing to add the unit tests and configuration changes. Most of the machinery you need is already in the "auto" type in (https://github.com/pgbackrest/pgbackrest/blob/release/2.30/src/storage/s3/storage.c#L319) so you'd just need to re-purpose that to work in your environment. It'll be easy enough for us to do the rest of the integration at that point.

I'm closing the issue but if you write a patch you can submit a PR for it.

**Comment by james-callahan** [comment]
> @james-callahan EKS service auth has been implemented in PR #1527.

I've left a review; I didn't see any major issues. 

> It has not been tested in a real environment, though.
> 
> Any chance you would be able to test this feature? Feature freeze for our next release is Oct 15.

Any idea how we can do so when we use the postgres operator? (e.g. I'm not sure how to go about building a custom images with your branch of pgbackrest). Alternatively, to we can try and do it outside of the context of the operator; but I'm not sure what pieces we would need? Is there some subcommand/test suite we can use to confirm S3 connectivity without having to spin up a whole postgres etc?
