### ISSUE TITLE
Issue using pgBackRest in a Kubernetes environment as repository

### ISSUE THREAD

**Issue by Sryther** [pgbackrest/pgbackrest#1209]
1. pgBackRest version: **2.28**

2. PostgreSQL version: **11.8**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

I'm running pgBackRest in a Kubernetes cluster. I have 3 databases (masters) and I want to deploy pgBackRest as a repository. 

4. Did you install pgBackRest from source or from a package?

I'm using a custom Docker image based on Debian slim where I build from the sources. Here is the [Dockerfile](https://gist.github.com/Sryther/fcec74d462d04dcbd478f95abf2939cd).

5. Please attach the following as applicable:
    - `pgbackrest.conf` files : [repo](https://gist.github.com/Sryther/c928a65f34da5f8f1119ad13dc758bfc) and [a database](https://gist.github.com/Sryther/bbcf6efb7bf220c1c72d0517f3bd4d5f)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`) : [postgresql.conf](https://gist.github.com/Sryther/fa5df84b07bfe20103074a5c62eee519)
    - errors in the postgresql log file before or during the time you experienced the issue : I don't have them yet :/
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`) : [pgbackrest check result](https://gist.github.com/Sryther/9bfa619e05e48f288dc8e23d3f05497d)

7. Describe the issue:

I can't achieve to work with pgBackRest and my PostgreSQL servers. If at any time the PgBackRest server is restarted, my databases are going crazy, trying to access pgBackRest. The archive_command returns a error code and somehow the main process is killed so my PostgreSQL stops. When the PostgreSQL server tries to start again, the archive_command seems to fail and then again the PostgreSQL stops. I can't achieve to let a PostgreSQL alive with pgBackRest beside.

pgBackRest has access to any databases with ssh and the databases have access to pgBackRest with ssh too.

I used to use Barman to get my backups but I wanted to change to pgBackRest since it handles specific databases backups (not the whole PostgreSQL).

I get inspired by the timescaledb-kubernetes system from timescale: https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/pgbackrest.yaml.

I think I'm misunderstanding how pgBackRest should be configured in my case. Any help is welcome :) Thanks!

**Comment by dwsteele** [comment]
> The archive_command returns a error code and somehow the main process is killed so my PostgreSQL stops

This should not happen. The PostgreSQL archiver process should retry indefinitely until archiving resumes or the disk becomes full. If the disk is filling up then you will need to allow enough space for possible archiving outages.

If the disk is not full, then you may have some other configuration issue. pgBackRest is being successfully deployed on Kubernetes (see https://github.com/CrunchyData/crunchy-containers) so I don't think this is a pgBackRest issue.

Are there any errors in the PostgreSQL log? If it is panicking and shutting down there should be something.

**Comment by Sryther** [comment]
@dwsteele 
The disks aren't full. I'm currently configuring a preproduction environment and I don't have much data in the databases (only ~300Mb of 50Gb).
I know my issue is certainly caused by my configuration but I can't find where. Sorry to open a issue here if it's not a pgBackRest issue. Maybe should I ask on another platform? 

I'll check the resource you linked: [CrunchyData/crunchy-containers - bin/postgres-ha/pgbackrest](https://github.com/CrunchyData/crunchy-containers/tree/master/bin/postgres-ha/pgbackrest), thank you for that :).

Do you see any mistakes in my archive_command or pgbackrest.conf (in my original post)?

By the way, is there any recommendation about using/not using pgBackRest as a remote repository in such environment (cluster with Kubernetes)?
I kinda feel like I'm doing it wrong since the complexity of the deployment is higher than other deployment:
- a pgBackRest deployment with 2 containers: a container with pgBackRest binaries and ssh client, a container for ssh server to communicate with PostgreSQL servers ;
- a PostgreSQL deployment with 2 containers : a container with PostgreSQL & pgBackRest binaries and ssh client, a container for ssh server to communication with pgBackRest server.

I would like to use the public images of PostgreSQL to avoid supporting it myself.

I'm going to attach later the psql logs.

Thanks again!

**Comment by dwsteele** [comment]
Closing since no further info has been provided. Feel free to attach logs anytime.
