### ISSUE TITLE
The chain of incremental backups is broken

### ISSUE THREAD

**Issue by ViperRu** [pgbackrest/pgbackrest#1213]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.30

2. PostgreSQL version: 11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 16.04

4. Did you install pgBackRest from source or from a package? From source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) [pgbackrest.conf](https://github.com/pgbackrest/pgbackrest/files/5427750/pgbackrest.conf.txt)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Previous incremental backups are removed from the "backup reference list" of next incremental backup from time to time. For example: Backup was created as "20201011-034748F_20201023-030302I" without "20201011-034748F_20201022-030302I and 20201011-034748F_20201021-030302I" in the "backup reference list":

        incr backup: 20201011-034748F_20201021-030302I
            timestamp start/stop: 2020-10-21 03:03:02 / 2020-10-21 03:03:29
            wal start/stop: 00000001000000040000001E / 00000001000000040000001E
            database size: 173.9MB, backup size: 120.5MB
            repository size: 39MB, repository backup size: 33.6MB
            backup reference list: 20201011-034748F, 20201011-034748F_20201018-030302D, 20201011-034748F_20201019-030302I, 20201011-034748F_20201020-030303I

        incr backup: 20201011-034748F_20201022-030302I
            timestamp start/stop: 2020-10-22 03:03:02 / 2020-10-22 03:03:28
            wal start/stop: 00000001000000040000004D / 00000001000000040000004D
            database size: 191.6MB, backup size: 138.6MB
            repository size: 44.3MB, repository backup size: 38.9MB
            backup reference list: 20201011-034748F, 20201011-034748F_20201018-030302D, 20201011-034748F_20201019-030302I, 20201011-034748F_20201020-030303I, 20201011-034748F_20201021-030302I

        incr backup: 20201011-034748F_20201023-030302I
            timestamp start/stop: 2020-10-23 03:03:02 / 2020-10-23 03:03:30
            wal start/stop: 00000001000000040000007B / 00000001000000040000007B
            database size: 206.2MB, backup size: 154.9MB
            repository size: 49.3MB, repository backup size: 44.2MB
            backup reference list: 20201011-034748F, 20201011-034748F_20201018-030302D, 20201011-034748F_20201019-030302I, 20201011-034748F_20201020-030303I

May be this normal situation in some cases?

**Comment by dwsteele** [comment]
This is normal. The reference list does not include all the prior backups in the set, only the ones that *this* backup requires for a successful restore. It is often the case that PostgreSQL overwrites the same files between incrementals. Those updated files are stored in the new backup and do not need to be retrieved from an older backup.

**Comment by ViperRu** [comment]
Thank you for explain.
