### ISSUE TITLE
Not default dbname='postgres'

### ISSUE THREAD

**Issue by longtian001** [pgbackrest/pgbackrest#1214]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.30
2. PostgreSQL version:
11.5
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.4.1708 (Core)
4. Did you install pgBackRest from source or from a package?
source
5. Please attach the following as applicable:
------pgbackrest.conf-----
[global]
repo1-path=/var/lib/pgbackrest
process-max=3
log-level-console=info
repo1-retention-full=2
start-fast=y

[global:archive-push]
compress-level=3

[main]
pg1-path=/data/atlasdb
pg1-host-user=atlasdb
pg1-socket-path=/data/atlasdb

7. Describe the issue:

my default DB not postgres, but it is atlasdb,what can I do,if i want to backup it normal?

errors info:

$ pgbackrest --stanza=main check
2020-10-25 19:17:59.042 P00   INFO: check command begin 2.30: --log-level-console=info --pg1-path=/data/atlasdb --pg1-socket-path=/data/atlasdb --repo1-path=/var/lib/pgbackrest --stanza=main
WARN: unable to check pg-1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432 host='/data/atlasdb'': FATAL:  database "postgres" does not exist
ERROR: [027]: no database found
       HINT: check indexed pg-path/pg-host configurations
2020-10-25 19:17:59.047 P00   INFO: check command end: aborted with exception [027]
$ 

key info:
dbname='postgres'

May I change it to another?

**Comment by dwsteele** [comment]
There is no explicit pgBackRest option but you can use the PG standard PGDATABASE env variable. Since we use libpq to communicate with Postgres all these env variables will work: https://www.postgresql.org/docs/current/libpq-envars.html

**Comment by longtian001** [comment]
I have changed following code, compile from source,and it runs ok.

# vi src/postgres/interface.h，66 line

#define PG_DB_POSTGRES                                              "postgres"

modified 

#define PG_DB_POSTGRES                                              "atlasdb"


thanks.

**Comment by dwsteele** [comment]
We have added a `pg-database` option for the next release so you won't need to do a custom compile.

**Comment by longtian001** [comment]
it's greate. thank you.
________________________________
发件人: David Steele ***@***.***>
发送时间: 2020年12月2日 2:38
收件人: pgbackrest/pgbackrest ***@***.***>
抄送: longtian001 ***@***.***>; State change ***@***.***>
主题: Re: [pgbackrest/pgbackrest] Not default dbname='postgres' (#1214)


We have added a pg-database option for the next release so you won't need to do a custom compile.

―
