### ISSUE TITLE
Is there a way to avoid passwordless ssh between standby and primary for backups from standby ?

### ISSUE THREAD

**Issue by avinashvallarapu** [pgbackrest/pgbackrest#1219]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: Latest

2. PostgreSQL version: 12.4
3. Operating system/version - Backups to S3 from Standby/Replica

4. Did you install pgBackRest from source or from a package? RPM

7. Describe the issue:

We have a Primary/Standby setup and an S3 bucket configured for Backups. Requirement is to push backups from Standby. As per security standards, we cannot have passwordless SSH between Standby and Primary. Is this possible today for a full backup with pgBackRest. 

WARN: unable to check pg-1: [UnknownError] remote-0 process on '192.168.72.10' terminated unexpectedly [255]: postgres@192.168.72.10: Permission denied (publickey,password).
ERROR: [056]: unable to find primary cluster - cannot proceed
2020-10-27 14:08:46.244 P00   INFO: backup command end: aborted with exception [056]

**Comment by pgstef** [comment]
Hi,

Currently, pgBackRest can only operate through SSH. It doesn't require a ssh user without password but recommend using ssh keys (without passphrase). Perhaps an ssh-agent could help with the passphrase but you'll have to find the solution system-side.

I personally don't see any other solution for now unfortunately.

Kind regards

**Comment by dwsteele** [comment]
Correct, and any other solution would also have to be "passwordless" but would be less well-known than SSH.

As @pgstef mentioned, SSH requires certs so not just anybody can logon to the account. Also the command to be run can be locked down with SSH as we do in the user guide:
```
(echo -n 'no-agent-forwarding,no-X11-forwarding,no-port-forwarding,' && \
       echo -n 'command="/usr/bin/pgbackrest ${SSH_ORIGINAL_COMMAND#* }" ' && \
       sudo ssh root@repository cat /home/pgbackrest/.ssh/id_rsa.pub) | \
       sudo -u postgres tee -a /var/lib/postgresql/.ssh/authorized_keys
```

**Comment by kethineni1** [comment]
you can run minio on the repo server and connect using s3 token.

**Comment by dwsteele** [comment]
> you can run minio on the repo server and connect using s3 token.

Good thought, but this does not help with communication between the standby and primary.
