### ISSUE TITLE
pgbackrest backup got timeout when using minio and GCS as its gateway.(Crunchy data deployed in GKE)

### ISSUE THREAD

**Issue by AbbasgoriS4** [pgbackrest/pgbackrest#1224]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.27

2. PostgreSQL version:
12.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Google Kubernetes Engine

4. Did you install pgBackRest from source or from a package?
using crunchy data 4.4.0

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

**the content inside pgbackrest.conf file **
[main]
#pg1-path=/data/db

**from postgresql.conf**
archive_command = 'source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest archive-push "%p"'
archive_mode = 'True'
archive_timeout = '60'
listen_addresses = '0.0.0.0'
max_wal_senders = '6'
wal_keep_segments = '8'
wal_level = 'logical'
wal_log_hints = 'on'

**postgresql log while experiencing issue**
there are no error logs while getting failed
7. Describe the issue:
If I set repo as local then the flow works fine. but It's gatting failed only when I set repo as s3. It's able to create objects and push the tar files that I can see in minios but after doing all that still, it got timeout.
I ran **pgbackrest backup --repo1-retention-full=2 --archive-timeout=60 --db-host=10.0.1.85 --db-path=/pgdata/pgo-minio --repo1-type=s3 --no-repo1-s3-verify-tls --log-level-console=detail** inside pgbackrest pod and these are the last logs from it.

**2020-11-02 07:47:52.955 P01 INFO: backup file 10.0.1.87:/pgdata/pgo-minio/base/1/13174 (0B, 100%)
2020-11-02 07:47:53.065 P01 INFO: backup file 10.0.1.87:/pgdata/pgo-minio/base/1/13169 (0B, 100%)
2020-11-02 07:47:53.066 P00 INFO: full backup size = 31MB
2020-11-02 07:47:53.066 P00 INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2020-11-02 07:47:53.268 P00 INFO: backup stop archive = 000000010000000000000016, lsn = 0/16000050
2020-11-02 07:47:53.488 P00 DETAIL: wrote 'backup_label' file returned from pg_stop_backup()
2020-11-02 07:47:53.589 P00 INFO: check archive for segment(s) 000000010000000000000015:000000010000000000000016
ERROR: [082]: WAL segment 000000010000000000000015 was not archived before the 60000ms timeout
HINT: check the archive_command to ensure that all options are correct (especially --stanza).
HINT: check the PostgreSQL server log for errors.
2020-11-02 07:48:54.772 P00 DETAIL: socket statistics: objects 2, sessions 4, retries 0
2020-11-02 07:48:54.772 P00 DETAIL: tls statistics: objects 2, sessions 4, retries 0
2020-11-02 07:48:54.772 P00 INFO: http statistics: objects 2, sessions 4, requests 23, retries 2, closes 0
2020-11-02 07:48:54.772 P00 INFO: backup command end: aborted with exception [082]**

I even tried with timeout 1800s but it just waited for 30m and then failed with the same error.

**Comment by dwsteele** [comment]
pgBackRest defaults to host-style URIs (because S3 does) but Minio does not which can lead to strange errors like this. Try setting `--repo1-s3-uri-style=path`.

**Comment by AbbasgoriS4** [comment]
Thanks for the response @dwsteele, The issue is solved after changing URI style to path.
