### ISSUE TITLE
Restore previous backup

### ISSUE THREAD

**Issue by denis-argentin** [pgbackrest/pgbackrest#1225]
1. pgBackRest version: 2.28

2. PostgreSQL version: 11

3. Operating system/version:
Centos7 Master
Centos7 Slave
Centos7 Backup-host
Centos7 Restore-test 

4. Installed from a package.

```
[global]
repo1-path=/
repo1-retention-full-type = time
repo1-retention-full=15
start-fast=y
stop-auto=y
backup-standby=n
archive-timeout = 600
repo1-host-user=postgres
log-level-file=info
```

I run my pgbackrest every 2 days
My repo is like this:
20201016-214504F  20201021-214504F  20201026-214503F  20201030-214505F  backup.history  backup.info.copy
20201019-214504F  20201023-214504F  20201028-214504F  20201102-214504F  backup.info     latest

On another dedicated server (Restore test), I download only the first backup 20201016-214504F, and try to perform the restore, but i can't. I use this command:
`sudo -u postgres pgbackrest --stanza=$PGHOST --delta --type=time "--target=2020-10-19 22:15:06" restore`.

Maybe all the others backups should be on the same repo to restore the first one, right?.
But supose that i lost all the other backups. How do I restore this leftover?

**Comment by cmwshang** [comment]
It is not clear to me what you mean by "I download only" but see FAQ "Time-based Point-in-Time Recovery does not appear to work, why?" https://pgbackrest.org/faq.html#time-based-pitr for possible explanations.

**Comment by dwsteele** [comment]
If you are trying to copy a single backup out of the repository then that won't work. You didn't provide any error messages but I'm guessing it is something like `unable to find backup.info`.  Even if you copied that, where would the WAL come from for recovery?

You can make a copy of the entire repo (e.g. with rsync) if you like, but you can't cherry-pick parts of the repo and expect it to work.

**Comment by denis-argentin** [comment]
Sorry, Let me explain.

The "/archive" is a "GCS Fuse" mounted, in both servers (repo and tester) but not the "/backup" because GCS Fuse has a terrible performace for that. 
So the repo server do pgbackrest backup and gsutil send to Storage.
The restore-test server copy the last backup (not the entire repo) locally on /backup dir and run the restore processes to the latest time.
This test processes run every 15 days automatically and it works ok for me to test the integrity.

But now when I try to restore note the latest but the oldest exactly the error you mentioned. 

i just wanted to restore an old backup isolated, no need for wal's

**Comment by denis-argentin** [comment]
```
[root@backup-restore ~]# sudo -u postgres pgbackrest --stanza=$PGHOST --type=time "--target=2020-10-19 22:15:06" restore --force
ERROR: [037]: restore command requires option: pg1-path
       HINT: does this stanza exist?
[root@backup-restore ~]# sudo -u postgres pgbackrest --stanza=db-master-pro-01 --type=time "--target=2020-10-19 22:15:06" restore --force
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/pgdata/db-master-pro-01' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
ERROR: [055]: unable to load backup manifest file '/backup/db-master-pro-01/20201102-214504F/backup.manifest' or '/backup/db-master-pro-01/20201102-214504F/backup.manifest.copy':
       FileMissingError: unable to open missing file '/backup/db-master-pro-01/20201102-214504F/backup.manifest' for read
       FileMissingError: unable to open missing file '/backup/db-master-pro-01/20201102-214504F/backup.manifest.copy' for read

```

**Comment by dwsteele** [comment]
Again, this is *not* going to work with a partial copy of the repo. Even if it did, restoring the backup without performing PostgreSQL recovery (which requires WAL) is not a very good test.
