### ISSUE TITLE
pgbackrest2.27 test.pl  need co7-test, but docker.com only have co7-base  ? why ?how? 

### ISSUE THREAD

**Issue by Wim1234** [pgbackrest/pgbackrest#1228]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
       2.27
2. PostgreSQL version:
       12.0
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
      CentOS  7.6
4. Did you install pgBackRest from source or from a package?
      From source 
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
        
perl test/test.pl --vm=co7

Unable to find image 'pgbackrest/test:co7-test' locally
Trying to pull repository docker.io/pgbackrest/test ... 
/usr/bin/docker-current: manifest for docker.io/pgbackrest/test:co7-test not found.
See '/usr/bin/docker-current run --help'.

https://hub.docker.com/r/pgbackrest/test/tags?page=1&name=co7     
    Only have  co7-base  ， no nay co7-test 

  how can I get help from some documents about the test of pgbackreset ?
  Thank you very much ....

**Comment by dwsteele** [comment]
The contributing documentation is here: https://github.com/pgbackrest/pgbackrest/blob/master/CONTRIBUTING.md.

It looks like you already have an environment built so you can start here: https://github.com/pgbackrest/pgbackrest/blob/master/CONTRIBUTING.md#with-docker

You'll notice the first example is building the `u18` container. In your case you need to replace `u18` with `co7`.

**Comment by Wim1234** [comment]
Thanks U very much.
It begin to work...
but..

pgbackrest/test/test.pl   hang  at this
P1-T26/86 - vm=co7, module=common, test=io-tls
2020-11-12 17:28:15.254 P00 DETAIL: executing command: docker exec -i -u wim test-0 bash -l -c 'cd /home/wim/test/gcov-co7-0 && rm -f test.gcda && make -j 4 -s 2>&1 && valgrind -q --gen-suppressions=all  --leak-check=full --leak-resolution=high --error-exitcode=25 ./test.bin 2>&1'
2020-11-12 17:33:34.013 P00   WARN: process has been running for 300 seconds with no output
 2020-11-12 17:38:35.034 P00   WARN: process has been running for 300 seconds with no output

does my env miss something ?  about tls ?

**Comment by dwsteele** [comment]
The TLS test may not work correctly if your DNS service is not compliant with the spec. It is common for ISPs to return "helpful" result pages rather than a DNS error.

Try a non-network test like `--module=common --test=type-string` and see if that works.

**Comment by Wim1234** [comment]
2020-11-25 22:43:51.062 P00  ERROR: [125]: P1-T43/85 - vm=co7, module=storage, test=remote (err1-2.6s):

    run 001 - storageNew()
        000.004s          l0063 -     get remote repo storage

    TEST FAILED WITH TestError:

    --------------------------------------------------------------------------------
    EXPECTED RESULT FROM STATEMENT: storageRepoGet(strNew(STORAGE_TYPE_POSIX), false)

    BUT GOT UnknownError: remote-0 process on 'localhost' terminated unexpectedly [126]: bash: /home/wim/test/bin/co7/pgbackrest: Is a directory

    THROWN AT:
    common/exec:execCheck:185:(trace log level required for parameters)
    common/exec:execEof:(trace log level required for parameters)
    common/io/read:ioReadEofDriver:(trace log level required for parameters)
    common/io/read:ioReadInternal:(trace log level required for parameters)
    common/io/read:ioReadLineParam:(trace log level required for parameters)
    common/io/read:ioReadLine:(trace log level required for parameters)
    protocol/client:protocolClientNew:(trace log level required for parameters)
    protocol/helper:protocolRemoteGet:(debug log level required for parameters)
    storage/helper:storageRepoGet:(type: {"posix"}, write: false)
    test/module/storage/remoteTest:testRun:63:(void)
    test:main:(argListSize: 1, argList: (char *[]))
    --------------------------------------------------------------------------------

**Comment by Wim1234** [comment]
/home/wim/test/bin/co7/pgbackrest   is  a directory.

**Comment by dwsteele** [comment]
Well, `/home/wim/test/bin/co7/pgbackrest` definitely should not be a directory. I'm not sure how that happened.

Perhaps try removing `/home/wim/test` and trying again?
