### ISSUE TITLE
unable to restore with pgo restore(with pgbackrest backup)

### ISSUE THREAD

**Issue by Bhagi33** [pgbackrest/pgbackrest#1229]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:4.2

2. PostgreSQL version:12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: NAME="CentOS Linux",VERSION="7 (Core)"

4. Did you install pgBackRest from source or from a package? no, postgres crunchy operator using by default

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
we have crunchy postgres operator installed.
I am trying to full cluster restore  from cluster A(rmgl ) to cluster B(restored-cluster) with pgbackrest backup of cluster A. with following command.
pgo create cluster restored-cluster --restore-from rmgl -n pg-cron-12-ver

Note: this cluster rmgl is running with specific user id. 

 kubectl get po -n pg-cron-12-ver|grep restor
restored-cluster-bootstrap-lzzzj             0/1     Evicted             0          103m
restored-cluster-bootstrap-qdkvl             0/1     ContainerCreating   0          99m

Error:
 kubectl get events -n pg-cron-12-ver|grep restore

 pod/restored-cluster-bootstrap-qdkvl   MountVolume.SetUp failed for volume "restore-pv-demo" : mount command failed, status: Failure, reason: Failed to create bind mount directory: /opt/mapr/k8s/mounts/259d7136-dec1-4d1f-93ba-34c3a8ee59cf-restore-pv-demo

  Warning   FailedMount   pod/restored-cluster-bootstrap-qdkvl   Unable to mount volumes for pod "restored-cluster-bootstrap-qdkvl_pg-cron-12-ver": timeout expired waiting for volumes to attach or mount for pod "pg-cron-12-ver"/"restored-cluster-bootstrap-qdkvl". list of unmounted volumes=[pgdata]. list of unattached volumes=[pgdata user-volume primary-volume root-volume sshd crunchyadm dshm pgbackrest-config pgconf-volume pgo-pg-token-znk6n]

**Comment by dwsteele** [comment]
This does not appear to be a pgBackRest issue. You'll want to ask this question over at https://github.com/CrunchyData/crunchy-containers.
