### ISSUE TITLE
Only create either standby.signal or recovery.signal, not both

### ISSUE THREAD

**Issue by keithf4** [pgbackrest/pgbackrest#1236]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.30

2. PostgreSQL version: 12.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS7

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

When pgBackRest runs a restore with --type=standby on PG12, it still creates a recovery.signal file even though a standby.signal file is created and overrides the recovery.signal file. If the system is ever promoted in the future, it still leaves a recovery.signal file behind. In some edge case with pg_upgrade (still investigating) this causes an issue where pg_upgrade things the old data dir is still in recovery mode.

Discussed this a bit with @sfrost and he noted it would be good to only create either the standby.signal file or the recovery.signal (not both) file as needed, depending on what the target action is in the end. 

Also investigating postgresql itself to see if we can have it clean up the recovery.signal file at the end of the target action if possible, but no guarantees there.

**Comment by dwsteele** [comment]
Hmm, I feel like `recovery.signal` may have been required in this case when I first wrote the code, but there were a flurry of changes to PG12 as various issues were discovered. Or perhaps it was wrong all along.

Anyway, looks like @pgstef has created a patch, so we'll run that through testing.

**Comment by dwsteele** [comment]
Closing the issue since there is now a PR to track it.
