### ISSUE TITLE
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '$PGDATA' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted

### ISSUE THREAD

**Issue by JPCOSTA78** [pgbackrest/pgbackrest#1238]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  pgBackRest 2.30

2. PostgreSQL version: postgres (PostgreSQL) 12.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:    

Linux version 5.3.18-24.37-default (geeko@buildhost) (gcc version 7.5.0 (SUSE Linux)) #1 SMP Wed Nov 4 09:38:41 UTC 2020 (c145e08)

4. Did you install pgBackRest from source or from a package?

yes

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

when doing a restore with --delta i face this Warning: but the restore works fine and finish with success.

pgbackrest --stanza=<XXXXXXX> --delta --type=time "--target=2020-11-18 16:56:20.214604+01" restore

Any idea how i can clear this warning when doing a restore command  ? 

WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/data/postgres' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.

Thanks

**Comment by JPCOSTA78** [comment]
this was a side effect from this other warning: 

WARN: unable to open log file '/var/log/pgbackrest/XXXXXXXX-restore.log': Permission denied
      NOTE: process will continue without log file.
When fixed the other warning disappear

**Comment by JPCOSTA78** [comment]
found the the issue

**Comment by dwsteele** [comment]
I doubt this was a side effect of the log issue, rather now that you have files in PGDATA the `delta` option is not complaining anymore. If you want to avoid the warning on an empty dir then omit `delta`.
