### ISSUE TITLE
【question】 archive_command 

### ISSUE THREAD

**Issue by yangvipguang** [pgbackrest/pgbackrest#1241]
archive_command = 'pgbackrest --stanza=really-pg archive-push %p'

does the  archive command  mean that when a new wal segment is created， pgbackrest will  execute incr backup？

**Comment by pgstef** [comment]
Hi,

No. The PostgreSQL `archive_command` setting is triggered each time a new WAL segment is generated, as explained in detail [here](https://www.postgresql.org/docs/current/continuous-archiving.html).

The `archive-push` command will bring a copy of that WAL file into the pgBackRest repository (in the archives directory) before PostgreSQL removes or recycles it.

To take a backup, you need to use the `backup` command and specify which `--type` of backup you want: full, diff, incr.

There are always 2 parts: backups and archives. Basically, continuous archiving is the way to "save" the data generated between 2 backups. But I suggest you read the PostgreSQL doc mentioned above to have more details on that topic.

Kind regards

**Comment by yangvipguang** [comment]
@pgstef   very thanks for  your rely。 But i have a little question.  
i know every time a new WAL segment is generated , it will trigger archive_command. will  itl execute incr backup  like the below.? because I never configure a  incr backup schedule every minute.
![image](https://user-images.githubusercontent.com/11416887/100311155-14a2d300-2fea-11eb-8bf4-7938ccbb6d73.png)

**Comment by pgstef** [comment]
Hi,

No, incremental backups are only taken by the `pgbackrest backup --type=incr` command. 

To take the full backup, you must use `--type=full`. If you don't specify any type, the default will be incremental.

You should check your cron logs. I suspect it wasn't reloaded since you modified it or simply don't like the `*/8`.

Kind regards

**Comment by yangvipguang** [comment]
@pgstef  thanks , It's my problem, the cron task is wrong.
