### ISSUE TITLE
pgdg-common: pgbackrest rpm uses /etc/pgbackrest.conf

### ISSUE THREAD

**Issue by 2019-05-10** [pgbackrest/pgbackrest#1243]
Not sure if the issue originates here.
The pgbackrest from Postgres' pgdg-common repository uses as config 
/etc/pgbackrest.conf
whereas according to the docs the default should be 
/etc/pgbackrest/pgbackrest.conf

Same goes for the Debian package.

**Comment by dwsteele** [comment]
`/etc/pgbackrest/pgbackrest.conf` is the default location since 2.0 but the packages were never updated to match. We did this so the main config and the include dir (plus any future dirs) would be in the same place.

**Comment by 2019-05-10** [comment]
Wouldn't that mean one has to always set 
`--config` 
or
`--config-include-path` 
or
`--config-path` 
when pgbackrest looks by default for `/etc/pgbackrest/pgbackrest.conf`?

**Comment by cmwshang** [comment]
The defaults are provided as a convenience and the options allow you to configure the system to suit your needs.

**Comment by dwsteele** [comment]
`/etc/pgbackrest/pgbackrest.conf` is checked first and if it does not exist then `/etc/pgbackrest.conf` is used. This was done to provide a smooth transition from 1.x to 2.x.

**Comment by 2019-05-10** [comment]
I see.
Thanks for the explanation.
