### ISSUE TITLE
feature request : list of restore points

### ISSUE THREAD

**Issue by sebastienruiz** [pgbackrest/pgbackrest#1244]
Hi,

is it possible to implement an option in pgbackrest to list all the restore points in backuped WAL ?

**Comment by dwsteele** [comment]
This is a feature we have discussed, but we have no timeline for implementation.

It's a fair amount of work to implement WAL-parsing across multiple versions of Postgres and that needs to be done before this feature can be implemented.

**Comment by gtskaushik** [comment]
This will be a very useful feature

**Comment by dwsteele** [comment]
Agreed. We do have a project card for it but it depends on being able to scan the WAL which is not trivial: https://github.com/pgbackrest/pgbackrest/projects/2#card-36219117

**Comment by dwsteele** [comment]
Closing since this is already in our backlog.
