### ISSUE TITLE
Docs/questions regarding repository host/cloud storage/retention/promotion

### ISSUE THREAD

**Issue by MikeN123** [pgbackrest/pgbackrest#1245]
Hi. I'm currently in the process of installing pgbackrest, and am digging through all the available documentation. During that process, a couple of things are still a bit unclear to me. I thought it would be good to summarise my questions here. If anyone is in the position to answer them, and if people agree the documentation could be extended, I'm more than willing to try and make a PR for that. If there is a better place to ask these questions, please let me know as well.

- The exact position of the repository host is unclear to me, with regards to:
  - Is a repository host also recommended when storing to cloud storage? The documentation seems to strongly recommend a repository host, but from some of the issues here I get the idea that it would be a SPOF for backups and is better omitted?
  - If using a repository host, what config options should be set on the repository host, and what on the database hosts? E.g., `repo-cipher-pass` seems to be a 'repository' option, but in some places I read encryption already takes place on the database host. Should it be available on the repo host or the db host, or on both hosts?
  - What are the options to limit SSH access between the hosts. A forced command is already in the docs, but this seems to allow _all_ pgbackrest commands (e.g., it seems I could run an `expire` or `stanza-delete` from a db host). The user guide does say 'If the postgres user does restores on the repository host it is best not to also allow the postgres user to perform backups.', but to be honest I'm not sure what it is referring to.
- It seems the discussion of retention policies does lay out all the available options, but does not really discuss practical retention considerations. The documentation seems to strongly suggest not to expire WAL, but as I see it, quite a lot of people may want to have something like 'full backups every week, allow PITR for the last week'. Always having all WAL available also raises the question how many full/diff/incr backups would still be useful. As I see it, if full WAL is available, you can always do a PITR from your oldest backup and any intermediate backups are only useful to reduce recovery time. Or am I missing something here? Of course these settings are very situation-specific, but I think the documentation might benefit from some practical examples that show various retention scenarios?
- The documentation is quite light on promotion of a standby. This makes sense, as it is mostly a Postgres matter. But I am wondering what happens if a standby is promoted, but the master is still active. In that case, it seems both will be archiving WAL and your backups may be ruined. Is there a way to recover from this, or should you just always make very sure your master if shutdown if a standby is promoted? There is a short note about `archive-mode` in the user guide, but it does not really say a lot about what would happen.

**Comment by sfrost** [comment]
Greetings,

There's a lot to unpack in here and I don't think I'm going to hit on everything, but just quickly:

- We would love to have a PR from you to improve the documentation!  Always great to have others who want to contribute to the project.
- A repo host isn't required, but it can be useful to have a repo host to manage the timing of backups performed across multiple systems
- Encryption does happen on the DB host.
- Limiting the pgbackrest commands that can be run through SSH between the hosts further (beyond just requiring that it be pgbackrest that is being run) would certainly be interesting but has implications when it comes to the pgbackrest protocol and option passing.  We could possibly make it tighter but in doing so might create upgrade challenges for users who choose to carefully restrict such commands.  Perhaps that's alright, but it is a risk for us when it comes to ongoing maintenance.  Do you have specific thoughts regarding what should be controlled?
- Expiring WAL means losing the ability to restore to any point-in-time between the backups, which is unfortunate.  Having backups (of any type) can *significantly* reduce the amount of time required to get back to a working system (as of a specific point in time).  Replaying WAL isn't anywhere near as fast as performing a restore with pgbackrest, therefore it's useful to have more backups which then reduce the amount of WAL required to get to a particular point in time.
- If a standby is promoted while the primary is still operating (which is, indeed, a *very* bad situation and one which a lot of effort should be spent on to avoid), then the primary and the promoted replica *should* be on different timelines and therefore not conflicting with each other (the WAL files they will be archiving will have different filenames as timeline is a part of the WAL filename), and you can decide on restore which timeline you wish to follow.  If things go very badly and you somehow manage to have two primary servers running with the *same* timeline, then you (today) get into a race situation where the first host to archive a WAL file to pgbackrest "wins" and the other host will get errors when it tries to archive WAL (if two hosts attempt to archive the same WAL in the same stanza/cluster to pgbackrest, pgbackrest will compare them and throw an error if they're different).  We are contemplating changing pgbackrest and the repo format to accept archiving both and allowing a user to choose between them, but that's not been done yet as it requires a repo format change.

**Comment by MikeN123** [comment]
Thanks for your elaborate reply! I haven't been able to look into this further yet, but hope to do some work on it over the holidays.

As for the repo host with cloud storage, I'm wondering what the flow is in that case. Will data then go to the repo host and then to the cloud storage? A comment [here](https://github.com/pgbackrest/pgbackrest/issues/909#issuecomment-576374354) seems to discourage it for SPOF reasons, hence my question.

And if encryption happens on the DB host, should `repo-cipher-pass` be set on the DB host or on the repo host? I have been looking at the code for a while now, but it's hard to grasp not being a daily C programmer. Of course this is something I could probably figure out myself by simply building a setup and trying things.

> Do you have specific thoughts regarding what should be controlled?

Well, I think, in an ideal world, you would want to try to prevent a DB host from deleting backups from the repo host. That would probably be the most important feature.

**Comment by pgstef** [comment]
Hi,

> As for the repo host with cloud storage, I'm wondering what the flow is in that case. Will data then go to the repo host and then to the cloud storage? A comment [here](https://github.com/pgbackrest/pgbackrest/issues/909#issuecomment-576374354) seems to discourage it for SPOF reasons, hence my question.

The `backup` command would be executed on the repo host. That process would fetch data from the db host (primary or standby) and then store it in the repo storage (S3 or Azure).
The `archive-push` command, triggered by the PG archiver process would send data to the repo threw the repo host. So first to the repo host and then to the cloud storage.
A repo host might be a SPOF for backups and archives. If your repo host is down, then it won't trigger backups and the db host won't be able to push the archives to the repo. PG will stack the archives until your repo host is up again. So I don't think it's a really big problem. You can even add the [archive-push-queue-max](https://pgbackrest.org/configuration.html#section-archive/option-archive-push-queue-max) option in your db host configuration to prevent PG to crash in case of disk issue due to a failing archiving system.

> And if encryption happens on the DB host, should `repo-cipher-pass` be set on the DB host or on the repo host? I have been looking at the code for a while now, but it's hard to grasp not being a daily C programmer. Of course this is something I could probably figure out myself by simply building a setup and trying things.

I believe that the encryption configuration should stay with the repo configuration (so, on your repo host if you use one).

Here's a working example:

* db host
```ini
# pgbackrest.conf 
[global]
repo1-host=backup-srv

[my_stanza]
pg1-path=/var/lib/pgsql/13/data
```

* repo host
```ini
# pgbackrest.conf 
[global]
repo1-path=/somewhere_local
repo1-retention-full=1
start-fast=y
repo1-cipher-type=aes-256-cbc
repo1-cipher-pass=FIXME

[my_stanza]
pg1-host=pgsql-srv
pg1-host-user=postgres
pg1-path=/var/lib/pgsql/13/data
```

> Well, I think, in an ideal world, you would want to try to prevent a DB host from deleting backups from the repo host. That would probably be the most important feature.

If your repo is directly attached to your db host, it will be able to create new backups and expire old ones. But if you setup a repo host, the backup/expire commands must be run on that host. On the db host, you would then have an error like `ERROR: [072]: expire command must be run on the repository host`.

If you want a working example with repo host, you can have a look at [this blog post](https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html). Then you're repo location doesn't really matter. It can be local, nfs, cifs, S3, Azure,...

Using a repo host has benefits and drawbacks. It's totally up to you regarding your requirements.

Kind Regards and Happy Holidays,

**Comment by MikeN123** [comment]
Thanks for your explanation and examples! And best wishes for 2021!

> If your repo is directly attached to your db host, it will be able to create new backups and expire old ones. But if you setup a repo host, the backup/expire commands must be run on that host. On the db host, you would then have an error like ERROR: [072]: expire command must be run on the repository host.

That is correct if you run `pgbackrest`, but the thing is, you can also just SSH into the other host. The forced command is only restricting access to the `pgbackrest` binary, thus this works from the DB host (where on my repository host, the `postgres` user is used instead of the default):

```
xxx@a-psql-03:~postgres/ > sudo -u postgres ssh postgres@xxx /usr/bin/pgbackrest expire --stanza=main --log-level-console=info
2020-12-31 21:51:50.845 P00   INFO: expire command begin 2.31: --exec-id=11469-8cb73e13 --log-level-console=info --pg1-host=xxx --repo1-azure-account=<redacted> --repo1-azure-container=a-psql-03 --repo1-azure-key=<redacted> --repo1-azure-key-type=sas --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/a-psql-03-repo --repo1-retention-full=14 --repo1-retention-full-type=time --repo1-type=azure --stanza=main
2020-12-31 21:51:51.033 P00   INFO: time-based archive retention not met - archive logs will not be expired
2020-12-31 21:51:51.033 P00   INFO: expire command end: completed successfully (189ms)
```

As it seems the client is able to retrieve arbitrary options from the server anyway, using the `configOption` call, it would be able to retrieve the Azure/S3 secrets anyway, so in the end it does not really matter for my use case.
