### ISSUE TITLE
WAL archive timeout error

### ISSUE THREAD

**Issue by dboyleitrs** [pgbackrest/pgbackrest#1246]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.30

2. PostgreSQL version: 12.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  Debian 8.3.0

4. Did you install pgBackRest from source or from a package?  Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` ->  ATTACHED
    - `postgresql.conf` ->   ATTACHED
    - errors in the postgresql log file before or during the time you experienced the issue. -> There are no errors in the postgres log
    - `pgbackrest.log` -> ATTACHED

7. Describe the issue:

I'm deploying a new 3 node Postgres cluster to AWS using Kubernetes. The database has no non-system data. 

The cluster starts up fine: a primary is declared and the other two nodes connect to the primary and are declared backups. 

I am archiving to S3 as you can see from my configuration.

This `stanza-create` command runs fine:
  `pgbackrest --stanza=poddb stanza-create --log-level-stderr=debug || exit 1`

Then this `backup` command is run:
   `pgbackrest --stanza=poddb --type=full --log-level-stderr=debug backup || exit 1`

After the timeout period (which I've increased to 480 seconds) is reached, I'm seeing this in the pgbackrest log file:
```
ERROR: [082]: WAL segment 000000010000000000000002 was not archived before the 480000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
       --------------------------------------------------------------------
       If SUBMITTING AN ISSUE please provide the following information:
       
       version: 2.30
       command: backup
       options: --archive-timeout=480 --compress-level=3 --compress-type=lz4 --config=/etc/pgbackrest/pgbackrest.conf --log-level-stderr=debug --pg1-path=/var/lib/postgresql/data --pg1-port=5432 --pg1-socket-path=/var/run/postgresql --process-max=4 --repo1-cipher-type=none --repo1-retention-diff=2 --repo1-retention-full=2 --repo1-s3-bucket=itrs-c2dev-pgbackup --repo1-s3-endpoint=s3.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-2 --repo1-type=s3 --stanza=poddb --start-fast --type=full
       
       stack trace:
       command/archive/common:walSegmentFind:465:(storage: {type: s3, path: {"/var/lib/pgbackrest"}, write: false}, archiveId: {"12-1"}, walSegment: {"000000010000000000000002"}, timeout: 480000)
       command/backup/backup:backupArchiveCheckCopy:(manifest: {Manifest}, walSegmentSize: 16777216)
       command/backup/backup:cmdBackup:(void)
       main:main:(debug log level required for parameters)
       --------------------------------------------------------------------
```

I know my S3 config is correct because I see the entire `var/lib/pgbackrest/*` directory structure in the AWS S3 web console. 

My WAL data shouldn't be very large because as previously mentioned, there is no non-system data being created or replicated, so I guess 480 seconds should be long enough.

One thing I see in my pgbackrest debug log file is this line a few times before the WAL timeout error happens:
`DEBUG:     common/io/http/request::httpRequestProcess: retry FileReadError: unexpected eof while reading line`

This is my first time using pgbackrest so I guess I'm looking for troubleshooting help at this point. 

[pg_issue.zip](https://github.com/pgbackrest/pgbackrest/files/5618997/pg_issue.zip)

**Comment by dwsteele** [comment]
One of the hints in the error message is `HINT: check the PostgreSQL server log for errors.` If the archive command is error'ing out the errors will appear in the PG log since PG is the one calling the `archive-push` command. But you said there were no errors in the log, so...

Your `archive_command` is `/etc/timescaledb/scripts/pgbackrest_archive.sh` so this script might be swallowing the error. Is this script online somewhere we can see the source? If not can you post it?

But, in general, this error means that archiving is not happening, or not happening in a timely fashion. The trick is finding out why.

If you are using Patroni this might be your issue: https://github.com/timescale/timescaledb-kubernetes/issues/198

> DEBUG: common/io/http/request::httpRequestProcess: retry FileReadError: unexpected eof while reading line

This is fairly typical. Without retries S3 would not work at all.

**Comment by dboyleitrs** [comment]
Thanks for the prompt reply.

You asking me about the `archive` script prompted me to find it and review it, and it turns out the script wasn't enabled. I corrected that and a few other missing parameter issues, so I'm further along but now faced a new set of issues.

Now I'm seeing this on the primary node at startup:
```
ERROR: [055]: unable to load info file '/var/lib/pgbackrest/backup/poddb/backup.info' or '/var/lib/pgbackrest/backup/poddb/backup.info.copy':
       FileMissingError: unable to open '/var/lib/pgbackrest/backup/poddb/backup.info': No such file or directory
       FileMissingError: unable to open '/var/lib/pgbackrest/backup/poddb/backup.info.copy': No such file or directory
       HINT: backup.info cannot be opened and is required to perform a backup.
       HINT: has a stanza-create been performed?
       --------------------------------------------------------------------
       If SUBMITTING AN ISSUE please provide the following information:
       
       version: 2.30
       command: restore
       options: --config=/etc/pgbackrest/pgbackrest.conf --delta --force --link-all --log-level-console=detail --log-level-stderr=debug --pg1-path=/var/lib/postgresql/data --process-max=4 --repo1-cipher-type=none --repo1-s3-bucket=itrs-c2dev-pgbackup --repo1-s3-endpoint=s3.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-2 --repo1-type=s3 --stanza=poddb
       
       stack trace:
       info/infoBackup:infoBackupLoadFile:643:(storage: {type: s3, path: {"/var/lib/pgbackrest"}, write: false}, fileName: {"<REPO:BACKUP>/backup.info"}, cipherType: 0)
       command/restore/restore:cmdRestore:(void)
       main:main:(debug log level required for parameters)
       --------------------------------------------------------------------
```

**Comment by dwsteele** [comment]
Not only is there no backup, either `/var/lib/pgbackrest` is invalid or `stanza-create` has not been run yet.

As for why Patroni is trying to restore the primary -- you'll need to review your config or work that with the Patroni team.

**Comment by dboyleitrs** [comment]
Yes, it seems that things are running out of order now. Not sure why.

Thank you for your assistance, it definitely got me further along.
