### ISSUE TITLE
monitor pgbackrest backup 

### ISSUE THREAD

**Issue by yangvipguang** [pgbackrest/pgbackrest#1250]
when i run the pgbackrest query sql：
![image](https://user-images.githubusercontent.com/11416887/100838956-61851e80-34ae-11eb-905c-5376cd109554.png)

it will  report an error：
![image](https://user-images.githubusercontent.com/11416887/100839059-8bd6dc00-34ae-11eb-97da-3591afc1ae0a.png)

**Comment by pgstef** [comment]
Hi,

Could you provide more information about your setup as requested in the issue template please ?

Typically:
- pgBackRest version
- PostgreSQL version
- operating system/version

It would also be interesting to verify if your SQL user can execute the `pgbackrest --output=json info` command.

You can do that with:

```bash
$ sudo -iu postgres psql
psql (13.1)
Type "help" for help.
postgres=# \c
You are now connected to database "postgres" as user "postgres".
postgres=# \! pgbackrest --output=json info
...
```

Kind regards
