### ISSUE TITLE
Allow to set the config directory via autoconf

### ISSUE THREAD

**Issue by mbanck** [pgbackrest/pgbackrest#1251]
The default config file seems to be hardcoded to `/etc/{pgbackrest/,}pgbackrest.conf` (not sure whether the `pgbackrest` directory is needed, I think both work?); however, for sites that install pgbackrest locally the usually used `postres` user will not have the permission to create `/etc/pgbackrest` or `/etc/pgbackrest.conf`. So it would be nice if one could set that via e.g. `--sysconfdir=/foo/bar/pgbackrest`. Well, one can set that, but it's not being used by pgBackRest. Another option would be to optionally check `$PREFIX/etc/[pgbackrest]/pgbackrest.conf` as configuration file location.

As an aside, `--log-level-console=debug` is not helpful at all about where/how pgBackRest tries to find/read its configuration file, all I see is
```
2020-12-03 13:52:23.633 P00  DEBUG:     config/load::cfgLoad: => void
```

**Comment by cmwshang** [comment]
/etc/pgbackrest/pgbackrest.conf is checked first and if it does not exist then /etc/pgbackrest.conf is used. This was done to provide a smooth transition from 1.x to 2.x. For more custom configurations see the Command page https://pgbackrest.org/command.html an excerpt is below but there are also options for overriding per PG or repo host (see Configuration page https://pgbackrest.org/configuration.html (example: https://pgbackrest.org/configuration.html#section-repository/option-repo-host-config))

**4.2.7 Config Option (--config)**
pgBackRest configuration file.
Use this option to specify a different configuration file than the default.
```
default: /etc/pgbackrest/pgbackrest.conf
example: --config=/conf/pgbackrest/pgbackrest.conf
```

**4.2.8 Config Include Path Option (--config-include-path)**
Path to additional pgBackRest configuration files.
Configuration files existing in the specified location with extension .conf will be concatenated with the pgBackRest configuration file, resulting in one configuration file.
```
default: /etc/pgbackrest/conf.d
example: --config-include-path=/conf/pgbackrest/conf.d

```
**4.2.9 Config Path Option (--config-path)**
Base path of pgBackRest configuration files.
This setting is used to override the default base path setting for the --config and --config-include-path options unless they are explicitly set on the command-line.

For example, passing only --config-path=/conf/pgbackrest results in the --config default being set to /conf/pgbackrest/pgbackrest.conf and the --config-include-path default being set to /conf/pgbackrest/conf.d.
```
default: /etc/pgbackrest
example: --config-path=/conf/pgbackrest
```

**Comment by mbanck** [comment]
Ok, thanks.

However, that does not change the fact that the default for all of those are hardcoded to `etc`, I think it would be useful to let the admin configure that at configure time.

It's not a big issue though, of course.

**Comment by dwsteele** [comment]
This would be a good improvement, but depending of which file names got replaced in the code it might require additional testing. In other words, does `--sysconfdir=/foo/bar/pgbackrest` override both default locations, or just one of them? If both, then we'd need to write tests to check that case.

So, we'd be happy to accept the configure change and new tests as a patch but it doesn't seem high priority enough to work on it ourselves.

**Comment by mbanck** [comment]
AFAICT, the default location is hardcoded to `/etc`, so (right now) setting `--sysconfdir` to anything does nothing. So the new feature would be to honor `--sysconfdir`. I don't have the resources right now to work on this either, but maybe in the future.

**Comment by dwsteele** [comment]
> AFAICT, the default location is hardcoded to /etc, so (right now) setting --sysconfdir to anything does nothing.

Right. We added configure (initially to support lz4, which is not always present) long after this code was written.

It'd be pretty easy to get configure to create a constant, harder to get satisfactory coverage in the tests if this constant overrides *both* of the current locations. Note that no additional testing would be required if we were just updating the `/etc` part to PGBACKREST_CONFIG_ORIG_PATH_FILE and the config paths. But, the config paths (`--config` and `--config-include`) are auto-generated code (still done by Perl) so some changes there would be needed to use the constant.

**Comment by mschout** [comment]
I added `--with-configdir=DIR` to support this.

Ideally we would just rely on `--sysconfdir`, which defaults to `$prefix/etc` to compute this, but I didn't want to change default behaviour of `/etc/pgbackrest` regardless of what `$prefix` was set to.

I can adjust if it is deemed appropriate, let me know.

**Comment by mschout** [comment]
I've submitted a FreeBSD port with this patch here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=251687

**Comment by dwsteele** [comment]
PR #1255 has been merged so closing this issue.
