### ISSUE TITLE
Support more OS packages release.

### ISSUE THREAD

**Issue by bzhaoopenstack** [pgbackrest/pgbackrest#1252]
Hi, team.

I saw the [doc](https://pgbackrest.org/user-guide.html#installation), pgbackrest only release the debian packages in postgresql community apt repo, but no yum packages are available in communiy yum repo(https://download.postgresql.org/). Correct me if I'm wrong.

So the first questions is, does team have a plan to support yum packages release?
Before that, is there any official repo towards pgbackrest packages release? 

And I saw there are already 2.30 pgbackrest arm64 debain packages release in https://apt.postgresql.org/pub/repos/apt/pool/main/p/pgbackrest/ . If you are interested in release yum packages, which mentioned in first question. 

So the second question is, How about also support arm64 yum packages?

We can help you guys during the progress, such as , donating (VM)resource to build package, human resource to help community release and so on.

**Comment by pgstef** [comment]
Hi,

The packages are provided by the PGDG community directly. For the yum packages: https://yum.postgresql.org/contact/.

And those packages are already provided in the yum repos. What I understand from your question is to verify if **arm64** packages are available. I'm not sure when they announced this https://yum.postgresql.org/news/aarch64-support-is-available/ but I think **arm64** packages are available for rhel7 and rhel8: https://yum.postgresql.org/common/redhat/rhel-7-aarch64/repoview/pgbackrest.html.

Kind regards,

**Comment by bzhaoopenstack** [comment]
@pgstef Thank you very much, you make the question clear. Yeah, you are right, we want to make pgbackrest to support the new ARCH. But seems, most past of the work had been done in upstream. That's perfect and make me so excited. For the new ARCH, we all think that would be good if all softwares can support / run well on it.. Thank you, team. If you guys have some plans towards ARM, please let me know. Very appreciated.

**Comment by pgstef** [comment]
Hi,

> f you guys have some plans towards ARM, please let me know.

As stated before, the PostgreSQL community is building the packages, not us. And it seems that **arm64** for rhel7 and rhel8 are available already.

I then don't really understand what you're expecting from us..

**Comment by bzhaoopenstack** [comment]
Hi, 
Oh, sorry, I'm really don't know the relationship bewteen pgbackrest community and PG community. so does it mean that actually, pgbackrest community doesn't have confidence that pgbackrest can run on ARM, and doesn't know whether there is any possible issues during running on ARM?

Might be I make a mis-understanding, as I saw there are some arm64 packages on PG community repo, so I thought pgbackrest community has a cooperation with PG community for supporting arm64. So it isn't the truth, right? It's only PG community actions. Pgbackrest team didn't push or ask PG community to release pgbackrest arm64 packages before, right?

Our goal is making PG full ecosystem to support ARM well. So we plan to make the whole PG stack technology software can have the arm64 release  and official commnity test toward arm64 platform(such as travis CI, or some other platform which can support test on arm64), which are around PG.

That's why we are here to request the communities which is one part of the PG full stack eco-sys to support arm64. And find some ways to cooperate with upstream teams to make things better. Even human resources or test resources will be involved. So I asked pgbackrest team whether you have plan to support arm and release arm packages. ;-)

**Comment by dwsteele** [comment]
The pgBackRest project does support and test on arm64 (see https://travis-ci.org/github/pgbackrest/pgbackrest/jobs/748165830). We also test on ppc64le, s390x, and i386.

So, to be clear, the pgBackRest project supports arm64 and the yum.postgresql.org maintainers generate arm64 packages for pgBackRest.

**Comment by bzhaoopenstack** [comment]
@dwsteele  Thanks for clear.
