### ISSUE TITLE
Questions about backup from standby

### ISSUE THREAD

**Issue by pawellrus** [pgbackrest/pgbackrest#1254]
Hello. 
I have a pgsql cluster of 3 nodes. Cluster is being managed by stolon.
Initially i didn't deploy separate repository host.
Every host should send backups/wals to S3 repository. Backup script first checks if current  host a master and then runs backup command. Same for archive-push command.

Now I want to take backups from standby host. I created ssh-key and distributed it over all 3 hosts. So every host can do paswordless ssh to 2 another hosts as postgres user.

But backup from standby is not working.
I get an **'ERROR: [056]: unable to find primary cluster - cannot proceed'** every time when i try to start backup not from master.
Debug log gives errors like this

    unable to check pg-3: [LockAcquireError] raised from remote-0 protocol on 'db-3': raised from remote-0 protocol on 'db-1': unable to acquire lock on file '/tmp/pgbackrest/stanzaname-backup.lock': Resource temporarily unavailable

Even when I try to run backup from master - i get same results when other hosts is listed in pgbackrest.conf. When I delete them - it works again.

So question is typical - when i was wrong? Maybe I should deploy repository host to make backups from standby work?

I'll appreciate any help. Thank you.

**Comment by pgstef** [comment]
Hi,

If you set `archive_mode` to `on`, only the primary server will push WAL archives. So, there's no specific check to add there for `archive-push`.

Since you didn't provide any information requested in the issue template to help, I only can guess you're reaching the same kind of issue related [here](https://github.com/pgbackrest/pgbackrest/issues/1197#issuecomment-708381800).

**Comment by pawellrus** [comment]
@pgstef thank you for the advice. It seems that it helped. 
I use pgbackrest 2.28 and Oracle Linux 7.

> If you set archive_mode to on, only the primary server will push WAL archives. 

So I don't need to write custom check to archive_command? Is it actual for any 2.x versions?

**Comment by pgstef** [comment]
Well that's a PostgreSQL behavior, not related to pgBackRest only: https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-ARCHIVE-MODE. 

When `archive_mode=on`, the PostgreSQL archiver process will only run on primary clusters. Then it's the `archive_command` that will call archive-push. So yes, if you set `archive_mode=on` (not `always`), you don't need any custom stuff in the archive_command.
