### ISSUE TITLE
Pgbackrest upgrade questions

### ISSUE THREAD

**Issue by threenotrump** [pgbackrest/pgbackrest#1266]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.28

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Centos 7

4. Did you install pgBackRest from source or from a package? package

Hi

One of my servers hit the bug in this issue : https://github.com/pgbackrest/pgbackrest/issues/1112

So i need to upgrade pgbackrest.

I have searched the issues for upgrading pgbackrest and @dwsteele mentioned that database servers and repository host must be same version but he wanted to change this requirement.

Do still database servers and repository host must be the same pgbackrest version?

While upgrading pgbackrest can postgres stay open?

Is it as simple as yum update pgbackrest or there are possible pitfalls?

Best Regards

Burak Yurdakul

**Comment by pgstef** [comment]
Hi,

I didn't check lately but I think it's still the case that repo host and db servers versions must match. The [RN for v2.30](https://pgbackrest.org/release.html) states: "Add note that pgBackRest versions must match when running remotely.". So, I believe it's still the case.

Between 2.28 and 2.31 there's some nice improvements but, as far as I know, no real pitfall. A simple `yum update pgbackrest` should work then. PG can indeed stay open while upgrading pgBR.

Kind regards,

**Comment by dwsteele** [comment]
> While upgrading pgbackrest can postgres stay open?

You may get some transient errors while upgrading, but it is fine to leave PostgreSQL running.

**Comment by threenotrump** [comment]
Thank you gentlemen for answering my questions.

Thank you for developing great software .

Closing the issue.

Best Regards

Burak Yurdakul
