### ISSUE TITLE
S3[minio] old backups are not getting deleted

### ISSUE THREAD

**Issue by kesavkolla** [pgbackrest/pgbackrest#1270]
1. pgBackRest version: 2.9

2. PostgreSQL version: 13.1

3. Operating system/version - Red Hat 8.3.1-5

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
[global]
repo1-retention-full=1
repo1-retention-diff=2
repo1-s3-verify-tls=n
repo1-type=s3
compress-level=9
start-fast=y
[global:archive-push]
compress-level=3

6. Describe the issue:
I've ran several backup commands every time I run backup command a new incr is getting generated in my s3 bucket. The old incrementals are not getting delted. I ran expire command also still the old backup files are not getting delted. If the repo type is s3 the retentions are not getting honored.

Is there any way to expire old backups from s3?

**Comment by pgstef** [comment]
Hi,

Your retention policy options are counting [`full`](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-full) and [`diff`](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-diff) backups. The incremental backups will only expire when the backup they're referring to expires too.

So, you'll need to take some `--type=full` or `--type=diff` backups to expire the incremental. By default, the `backup` command takes incremental backups indeed (unless no full backup exists).

You can find more examples of how the retention options works in [this](https://pgstef.github.io/2020/05/25/pgbackrest_preview_tour_of_retention_policy_options.html) blog post.

Kind regards

**Comment by dwsteele** [comment]
And to clarify, it is not *possible* to expire incremental backups independently because each one depends on *all* the incremental backups before it as well as the diff/full it is based on.

**Comment by dwsteele** [comment]
Also see https://pgbackrest.org/user-guide.html#concept/backup for details on each backup type.

**Comment by kesavkolla** [comment]
Thanks for the explanation. Yes If I take diff backup then the retention setting is working. Is there is any way to delete my previous incr backups?

```
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13-1): 000000010000000000000004/00000001000000000000002B

        full backup: 20210106-023358F
            timestamp start/stop: 2021-01-06 02:33:58 / 2021-01-06 02:35:12
            wal start/stop: 000000010000000000000004 / 000000010000000000000005
            database size: 53.8MB, backup size: 53.8MB
            repository size: 6.3MB, repository backup size: 6.3MB

        incr backup: 20210106-023358F_20210107-045037I
            timestamp start/stop: 2021-01-07 04:50:37 / 2021-01-07 04:50:47
            wal start/stop: 000000010000000000000021 / 000000010000000000000021
            database size: 54.2MB, backup size: 19.1MB
            repository size: 6.2MB, repository backup size: 2.3MB
            backup reference list: 20210106-023358F

        incr backup: 20210106-023358F_20210107-045106I
            timestamp start/stop: 2021-01-07 04:51:06 / 2021-01-07 04:51:08
            wal start/stop: 000000010000000000000023 / 000000010000000000000023
            database size: 54.2MB, backup size: 8.3KB
            repository size: 6.2MB, repository backup size: 427B
            backup reference list: 20210106-023358F, 20210106-023358F_20210107-045037I

        incr backup: 20210106-023358F_20210107-045130I
            timestamp start/stop: 2021-01-07 04:51:30 / 2021-01-07 04:51:32
            wal start/stop: 000000010000000000000025 / 000000010000000000000025
            database size: 54.2MB, backup size: 8.3KB
            repository size: 6.2MB, repository backup size: 427B
            backup reference list: 20210106-023358F, 20210106-023358F_20210107-045037I

        diff backup: 20210106-023358F_20210107-143710D
            timestamp start/stop: 2021-01-07 14:37:10 / 2021-01-07 14:37:21
            wal start/stop: 00000001000000000000002A / 00000001000000000000002A
            database size: 54.2MB, backup size: 19.1MB
            repository size: 6.2MB, repository backup size: 2.3MB
            backup reference list: 20210106-023358F

        diff backup: 20210106-023358F_20210107-143735D
            timestamp start/stop: 2021-01-07 14:37:35 / 2021-01-07 14:37:46
            wal start/stop: 00000001000000000000002B / 00000001000000000000002B
            database size: 54.2MB, backup size: 19.1MB
            repository size: 6.2MB, repository backup size: 2.3MB
            backup reference list: 20210106-023358F
```

If I run expire command the incr backups are not getting deleted.

**Comment by pgstef** [comment]
Your current `incr` are linked to your 1st `full` backup. They will expire when that full backup will expire too.
Given your retention policy options, next time you'll take a `--type=full` successful backup, all your current backups will expire.

**Comment by kesavkolla** [comment]
Yes that is correct. Thanks for your explanation. Now I understood the relation.

**Comment by dwsteele** [comment]
Or use the `--set` option for `--expire`: https://pgbackrest.org/command.html#command-expire.
