### ISSUE TITLE
Restore backup using pgBackRest to another host

### ISSUE THREAD

**Issue by aogb** [pgbackrest/pgbackrest#1276]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
     2.31
2. PostgreSQL version:
     12.5
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 7.9
DB sever
Repository Server
4. Did you install pgBackRest from source or from a package?
package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[demo]
pg1-path=/pgdata/postgresql/data

[global]
log-level-file=detail
repo1-host=repo-host

Repository HOST 
[demo]
pg1-host=db1
pg1-path=/pgdata/postgresql/data

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I have a database server with repository host. Setup is fantastic with no issues. I am able to backup the database from the repository host. 
I have use case where i want to be able to restore the backup using pgBackRest to another host and then pg_dump the database and restore it into the cluster as the data in the other databases are  important, I cannot use PITR to recover all the databases to the time just before the database was dropped

What do I need to include in my configuration to get this achieved?

**Comment by pgstef** [comment]
Hi,

As long as your other host can reach the repo on the repo host, you could probably use the same config as your current db host. Indeed, the restore command need to be performed from the db host (so, from your other new host).

What's important is, **BEFORE** starting your PG service after restoring the backup, disable the archiver process (`archive_mode` to `off` or `archive_command` to `/bin/true`). This will avoid messing with the proper archives in the repo.

Hope this help.
Kind regards.

**Comment by aogb** [comment]
Absolutely right...this helps

Thank you.
