### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by mawenbin666** [pgbackrest/pgbackrest#1279]
1. pgBackRest version:2.31

2. PostgreSQL version:12.3

3、Installation error
```
./configure
.build/common/crypto/hash.o: In function `cryptoHashFreeResource':
hash.c:(.text+0xeff): undefined reference to `EVP_MD_CTX_free'
.build/common/crypto/hash.o: In function `cryptoHashNew':
hash.c:(.text+0x1158): undefined reference to `EVP_MD_CTX_new'
.build/common/io/tls/client.o: In function `asn1ToStr':
client.c:(.text+0x3a9): undefined reference to `ASN1_STRING_get0_data'
.build/common/io/tls/client.o: In function `tlsClientOpen':
client.c:(.text+0x735): undefined reference to `OPENSSL_sk_num'
client.c:(.text+0x747): undefined reference to `OPENSSL_sk_value'
client.c:(.text+0x75b): undefined reference to `OPENSSL_sk_pop_free'
client.c:(.text+0x8ab): undefined reference to `OPENSSL_sk_pop_free'
.build/common/io/tls/client.o: In function `tlsClientNew':
client.c:(.text+0xb81): undefined reference to `TLS_method'
client.c:(.text+0xbd4): undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status
make: *** [pgbackrest] Error 1
```

**Comment by pgstef** [comment]
Hi,

On which platform are you trying to build ? Could you provide the steps you followed to get those errors ?

Did you installed the build dependencies stated in the user guide ?

Example for debian/ubuntu:
```
sudo apt-get install make gcc libpq-dev libssl-dev libxml2-dev pkg-config \
       liblz4-dev libzstd-dev libbz2-dev libz-dev
```

Kind regards,

**Comment by mawenbin666** [comment]
> Hi,
> 
> On which platform are you trying to build ? Could you provide the steps you followed to get those errors ?
> 
> Did you installed the build dependencies stated in the user guide ?
> 
> Example for debian/ubuntu:
> 
> ```
> sudo apt-get install make gcc libpq-dev libssl-dev libxml2-dev pkg-config \
>        liblz4-dev libzstd-dev libbz2-dev libz-dev
> ```
> 
> Kind regards,

os version :centos 7.8

**Comment by dwsteele** [comment]
RHEL build instructions are here: https://pgbackrest.org/user-guide-centos7.html#build.

However, you would be better off getting the pre-built packages from yum.postgresql.org.
