### ISSUE TITLE
pgbackrest how to keep special backup not be deleted when execute pgbackrest expire

### ISSUE THREAD

**Issue by pg-chaos** [pgbackrest/pgbackrest#1280]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.27

2. PostgreSQL version:11.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:linux

4. Did you install pgBackRest from source or from a package?
rpm

6. Describe the issue:
pgbackrest how to keep special backup not be deleted when execute pgbackrest expire

expire cmd：pgbackrest --stanza=xxxx --repo1-retention-full=7 --repo1-retention-full-type=count --log-level-console=info expire

**Comment by pgstef** [comment]
Hi,

This isn't possible yet. There's an entry in the [backlog](https://github.com/pgbackrest/pgbackrest/projects/2#card-8956942) regarding this feature but, as far as I know, not planned yet.

Kind regards,

**Comment by pg-chaos** [comment]
i very need this feature, please raise priority

**Comment by dwsteele** [comment]
I have added this issue to the backlog card and we'll let you know when it gets scheduled.

**Comment by dwsteele** [comment]
Backlog card is: https://github.com/pgbackrest/pgbackrest/projects/2#card-8956942
