### ISSUE TITLE
postgres/patroni(remote-stand-by) -- delta restore does not sync databases

### ISSUE THREAD

**Issue by alizaaliza** [pgbackrest/pgbackrest#1283]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:pgBackRest 2.25

2. PostgreSQL version:12.2

3. Operating system/version -4.19.2-1.el7.elrepo.x86_64 #1 SMP Tue Nov 13 16:18:09 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` 

7. Describe the issue: delta restore of destroyed site (from remote site) , finish successfully , but actually does not synchronize the restored db.
layout: postgresql/patroni-remote stand by/pgbackrest  : configuration of 4 postgresql servers in 2 sites. remote standby layout. ( DR)
we work on fail over to DR site + healing "old" master site. with following steps
1) stop master-site haproxy and stop patroni on both servers of site 1 ( old master site)
2) change site 2 to be stand alone site ( curl -sS -XPATCH -d  '{"standby_cluster": null}' http://10.247.94.156:8007/config)
3) site 2 becomes stand alone ( good) and manage to execute more inserts of new data
4) on  the "destroyed- site" , change the db to stand by , with patroni edit config , ( while patroni is down)
5) use manual delta restore to restore "destroyed- site" from remote repository of the DR ( that is active now)
6) delta restore is successful, but replication does not resume, because "destroyed- site" databases are at timeline 6 and the (DR) active site is at timeline 7

how can I fix my procedure , to be able to use delta-restore in such case?

thanks in advance , Aliza.
[README.txt](https://github.com/pgbackrest/pgbackrest/files/5863060/README.txt)

[rm_stb01.zip](https://github.com/pgbackrest/pgbackrest/files/5863050/rm_stb01.zip)

**Comment by pgstef** [comment]
Hi,

The command you used to restore (with its logs) and the PostgreSQL logs on the node failing would help. Could you provide that information?

In your zip file, the `postgresql.auto.conf` for 10.147.249.124 is a bit weird. It should contain the `restore_command`. Did you use `--type=none` or `--type=preserve` ?

**Comment by alizaaliza** [comment]
Hi Thanks for the  response.

restore command that i used while patroni and pgs are down :
/usr/bin/pgbackrest --stanza=stanza07 --delta restore

**Comment by dwsteele** [comment]
> postgresql.auto.conf for 10.147.249.124 is a bit weird. It should contain the restore_command

Agreed. You'll want to check `postgresql.auto.conf` right after running the restore command (before starting Patroni or Postgres) to make sure `restore_command` is present. If another process is removing it I'm not sure what we can do to help with that.

> PostgreSQL logs on the node failing would help

Yes, they would.

**Comment by alizaaliza** [comment]
Thanks a lot , I would arrange that

**Comment by alizaaliza** [comment]
hi, 
are you looking for "restore_command" ?.  it exist as fixed command at postgresql.conf

restore_command = 'pgbackrest --stanza=stanza07 archive-get %f %p'

**Comment by pgstef** [comment]
Hi,

At this point, we'll need the PostgreSQL logs on the node failing to help further unfortunately.

**Comment by alizaaliza** [comment]
hi , Thanks for your response!
I am working still on this issue, and will pack it all. still can you please review my flow(first message) , and let me know if  ,my flow is correct - or should I change one of the steps?

**Comment by pgstef** [comment]
Hi,

If I get your workflow right and remove the patroni side of things:
* Site 1 - PG1 : primary
* Site 1 - PG2, Site 2 - PG3, Site 2 - PG4 : standbys

t0 : backup of PG1
t1 : stop PG1 and PG2, promote PG3, backup of PG3
t2 : restore on PG1 and PG2 (using `--delta`)

That workflow seems fine to me. It's then only a matter of configuration management.

**Comment by alizaaliza** [comment]
Thanks for your patients , I will update.
