### ISSUE TITLE
pgbackrest S3 old backup retention (expire) doesn't work properly

### ISSUE THREAD

**Issue by bimcas** [pgbackrest/pgbackrest#1284]
Info:

1. pgBackRest version: 2.31

2. PostgreSQL version: 12.5

3. Operating system/version: only one node with CentOS Linux release 7.7.1908

4. I installed pgBackRest from RPM package - **pgbackrest-2.31-1.rhel7.x86_64.rpm** Repo https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/

5. My configuration files:

- `pgbackrest.conf`
```
[main]
 pg1-path=/postgres/data

[global]
repo1-type=s3
repo1-s3-endpoint=XXXXXXXXXXX
repo1-s3-verify-ssl=n
repo1-cipher-type=none
repo1-s3-bucket=XXXXXXXXX
repo1-path=/xxx/xxx
repo1-s3-key=XXXXXXXXXXX
repo1-s3-key-secret=XXXXXXXXXX
repo1-s3-region=us-east-1
repo1-retention-full-type=count
repo1-retention-full=2
repo1-retention-diff=2
start-fast=y
stop-auto=y
process-max=4

[global:archive-push]
compress-level=3
```
    
 - `postgresql.conf` 
```
archive_command = 'pgbackrest --stanza=main archive-push %p'
archive_mode = 'on'
port = '5432'
max_wal_senders = '10'
wal_level = 'replica'
restore_command = 'pgbackrest --stanza=main archive-get %f %p'
```

 - No errors in the PostgreSQL log file before or during the time of the issue
  
 - log file in `/var/log/pgbackrest`

```
2021-01-26 15:51:58.154 P00   INFO: full backup size = 48.2MB
2021-01-26 15:51:59.691 P00   INFO: new backup label = 20210126-154830F
2021-01-26 15:52:02.511 P00   INFO: backup command end: completed successfully (213076ms)
2021-01-26 15:52:02.674 P00   INFO: expire full backup set: 20210126-142231F, 20210126-142231F_20210126-143223I
2021-01-26 15:52:02.795 P00   INFO: remove expired backup 20210126-142231F_20210126-143223I
2021-01-26 15:52:03.476 P00   INFO: remove expired backup 20210126-142231F
2021-01-26 15:53:39.581 P00   INFO: remove expired backup 20210126-141446F
ERROR: [042]: timeout after 60000ms waiting for read from 'XXXXXXXXXXXXXXXXXXXX:443'
2021-01-26 15:55:39.777 P00   INFO: expire command end: aborted with exception [042]
```
7. The issue:
As you see from pgbackrest log info, full backup was successful. The restore process also works and successful. It's OK and respect to pgbackrest.
**The issue appears during old backup retention. It seems that pgbackrest stuck with removing the expired backup from S3 storage.**

It also strange that after this action command **pgbackrest info** doesn't show removed expired backups:

```
stanza: main
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1): 000000120000000000000036/000000140000000000000056

        full backup: 20210126-143613F
            timestamp start/stop: 2021-01-26 14:36:13 / 2021-01-26 14:38:03
            wal start/stop: 000000140000000000000053 / 000000140000000000000053
            database size: 48.2MB, backup size: 48.2MB
            repository size: 5.8MB, repository backup size: 5.8MB

        full backup: 20210126-154830F
            timestamp start/stop: 2021-01-26 15:48:30 / 2021-01-26 15:51:58
            wal start/stop: 000000140000000000000055 / 000000140000000000000055
            database size: 48.2MB, backup size: 48.2MB
            repository size: 5.8MB, repository backup size: 5.8MB
```
but I can find all previuosly removed expired backups in S3 storage (all folders and files):

```
20210126-112535F/        <-- bad (expired backup)
20210126-130155F/        <-- bad (expired backup)
20210126-142231F/        <-- bad (expired backup)
20210126-143613F/        <-- good
20210126-154830F/        <-- good
backup.history/
backup.info
backup.info.copy
```

So, it's a pity, but pgbackrest old (expired) backups retention (clean) doesn't work in S3 storage. I should remove them manually. 

Do you have any idea how to solve it?

**Comment by bimcas** [comment]
Is it possible to change the timeout setting to **expire** command? Maybe 60s aren't enough time to remove expired backups if they are big in size.

I tried to use --archive-timeout, but command failed:
```
pgbackrest --stanza=main --log-level-console=info --archive-timeout=320 expire
ERROR: [031]: option 'archive-timeout' not valid for command 'expire'
```

**Comment by bimcas** [comment]
I execute 'expire' command many times (8 or more):
`pgbackrest --stanza=main --log-level-console=info expire`

And finally, I got the result:
`2021-01-27 12:43:57.598 P00   INFO: expire command end: completed successfully (3142ms)`

Now I have only two full backups in my S3 storage:
```
20210126-143613F/
20210126-154830F/
backup.history/
backup.info
backup.info.copy
```

So, the issue is the timeout setting in my case, I mean that not enough time to complete expired backup clean.
It seems that workaround could be the regular cronjob with the command:
`pgbackrest --stanza=main expire`

**Comment by dwsteele** [comment]
Files are batch deleted on S3-compatible storage 1000 at a time. My guess is that your server is slow and is not able to delete 1000 files before the timeout.

The best option to use here is `io-timeout`, though I do not recommend setting it too high as we've never really tested with large settings: https://pgbackrest.org/configuration.html#section-general/option-io-timeout

I would try `io-timeout=90` and if that does not work then bump it up by 30 second intervals until it expires reliably.

**Comment by bimcas** [comment]
Thanks. I'll try io-timeout. I have one more question regarding pgbackrest. 

Is it possible to have a backup solution like Daily, Weekly, Monthly with pgbackrest?
I mean that every day pgbackrest creates DAILY backups. On Sunday pgbackrest creates Weekly backup and retention removes all Daily backups. Next week will be the same: Daily backups and on Sunday again Weekly backup and retention remove all Daily backups of that week. In this case, at the end of the month, we'll have 3 or 4 Weekly backups and then on the last day of the month pgbackrest creates Monthly backup and retention removes all Weekly backups. Now we'll keep Monthly backup till the end of the next month. Monthly retention removes old Monthly backup and creates a new one. 
Next month all procedure repeats again: DAILY backups, Weekly backups and on the last day of the month Monthly backup.

Is it possible to implement it with pgbackrest? If yes, how I can do this? Do you have any manual on how to do it?

Thanks in advance.

**Comment by pgstef** [comment]
Hi,

It's not possible directly within pgBackRest. Time retention is based on full backups only. We have 3 [types](https://pgbackrest.org/command.html#command-backup/category-command/option-type) of backups (full, diff, incr) but we only can expire [full](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-full) and [diff](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-diff) based on their number.

You could achieve something like that "manually", using the [expire --set](https://pgbackrest.org/command.html#command-expire/category-command/option-set) command.

Imagine, you schedule a **full** backup the 1st Sunday of the month (it would be your monthly backup). Then, the other days, take **incr** backups. The next Sunday's, you take **diff** backups. After a successful **diff** (weekly) backup, you could query pgBackRest asking the list of all the **incr** (daily) backups and expire them one by one using the expire command [_theoretically, expiring the 1st **incr** would remove the other ones since they refer to this one_].
Finally, if you set the retention of **full** backups to 1, the next successful **full** backup will expire the previous one and all the **diff** backups in between too.

But that's a bit tricky and leave you with complex cron tasks/schedule.

Maybe an improvement idea would be to accept a regular expression for the `expire --set` option in the future.

**Comment by bimcas** [comment]
Thank you very much for your time and idea.

Have a great day.
