### ISSUE TITLE
Backup from the standby and creating replica using method pgbackrest

### ISSUE THREAD

**Issue by rachid-casa** [pgbackrest/pgbackrest#1288]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.31-1

2. PostgreSQL version:
12.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Red Hat Enterprise Linux 7.9

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
postgres=# show archive_command ;
                            archive_command                            
 pgbackrest --stanza=data_db archive-push %p --log-level-console=debug
 archive_mode 
--------------
 on
              listen_addresses               
---------------------------------------------
 127.0.0.1,service_adresse
 max_wal_senders 
-----------------
 10
 wal_level 
-----------
 replica
(1 Zeile)
 port 
------
 5432

    - errors in the postgresql log file before or during the time you experienced the issue

backup command end: aborted with
exception [082]

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We are using patroni-1.6.5-1.rhel7.x86_64

Backup work fine on the primary

But the backup on the replic does not work. I receive the message:

2021-01-28 19:15:06.518 P02   INFO: backup file
x90070.adm.denic.de:/data/application/postgresql/patroni_db4/base/14186/14024
(0B, 100%)
2021-01-28 19:15:06.529 P00   INFO: full backup size = 444.1MB
2021-01-28 19:15:06.530 P00   INFO: execute non-exclusive
pg_stop_backup() and wait for all WAL segments to archive
2021-01-28 19:15:06.748 P00   INFO: backup stop archive =
0000001000000003000000FA, lsn = 3/FA0005C8
2021-01-28 19:15:06.764 P00   INFO: check archive for segment(s)
0000001000000003000000FA:0000001000000003000000FA
ERROR: [082]: WAL segment 0000001000000003000000FA was not archived
before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are
correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2021-01-28 19:16:07.011 P00   INFO: backup command end: aborted with
exception [082]

Creating replica (bootstrap) using method pgbackrest does not work: pgbackrest exited with code=31

pgbackrest.con (on primary and on slave are same) 
[data_db]
pg1-host=pg_host_primary
pg1-path=/data/application/postgresql/patroni_db1
pg2-host=pg_host_slave
pg2-path=/data/application/postgresql/patroni_db4
pg1-socket-path=/data/application/postgresql/patroni_db1
pg2-socket-path=/data/application/postgresql/patroni_db4
[global]
repo1-path=/data/dumps/postgres/backup
repo1-retention-full=1
stop-auto=y
start-fast=y
log-level-console=info
log-level-file=detail
log-timestamp=y
[global:backup]
process-max=2

Please could you help?

See the attached files

[postgresql_log.log](https://github.com/pgbackrest/pgbackrest/files/5917091/postgresql_log.log)
[data_db-backup.log.gz](https://github.com/pgbackrest/pgbackrest/files/5917092/data_db-backup.log.gz)

**Comment by pgstef** [comment]
Hi,

First of all, quick remark regarding your configuration file. It's usually best to set `pg1-*` as the locally running PG cluster and avoid `*-host` option for it. That means having different configuration for primary and standby.

Is your `repo1-path=/data/dumps/postgres/backup` a directory shared between the 2 hosts ? (And are the 2 hosts clocks in sync too ?)

From the standby logs:
```
2021-01-28 18:49:07.518 P00   INFO: check archive for segment(s) 0000001000000003000000F6:0000001000000003000000F6
2021-01-28 18:50:07.614 P00  ERROR: [082]: WAL segment 0000001000000003000000F6 was not archived before the 60000ms timeout
```

From the primary:
```
2021-01-28 18:49:07.532 P00   INFO: pushed WAL file '0000001000000003000000F6' to the archive
```

This means your standby don't find the archive in its repo (within 60sec) while the primary pushed it correctly. So my guess would be that you don't share the repo between the 2 hosts or that your clocks are not synced.

That's for the backup part. Regarding the restore "bootstrap" now, the `031` is **OptionInvalidError**. Did you get the log or the command executed ? It could be interesting that you try the restore manually since Patroni probably provides an invalid option to the restore command.

**Comment by rachid-casa** [comment]
Many thanks for your feedback.

repo1-path=/data/dumps/postgres/backup is directory and not shared between the 2 hosts.
Does it mean, that we can run the backup on the slave only if the repo1-path is shared between the 2 hosts?
 
Regarding the restore "bootstrap": I droped the data_directory on the slave and i start patroni. Patroni did not bootstrap from the leader using pgbackrest.  Patroni use pgbasebackup to bootstrap from the leader.

I receive the message:
INFO: replica has been created using basebackup

I have the following configuration in patroni "postgresql.yml" in the postgresql sections 
postgresql:
.
.
  postgresql:
    create_replica_methods:
        - pgbackrest
        - basebackup
    pgbackrest:
        command: /usr/bin/pgbackrest --stanza=data_db --delta restore
        keep_data: True
        no_params: True
 
 What schoud i adjust so that the replica will be created using pgbackrest and not pgbasebackup?

 Thanks

**Comment by pgstef** [comment]
Well, by default, with `archive_mode=on`, the primary PG cluster pushes the archives to the repo. A few operations have to happen on the primary server even if you take a backup from the standby server (meaning most of the data files will come from the standby).

But at the end, all the archives (from the primary) and the backups (from primary and standby) should reach the same location (shared repo). That's even more important if you want to restore a backup to create your standby server. You'll need the archives pushed from the primary server to be applied on top of your last backup.

So yes, you need to store your repo on a shared location (or use a specific repo host / backup server). It can be nfs/cifs mount point, or even S3 buckets / Azure containers. See the [`repo-type`](https://pgbackrest.org/configuration.html#section-repository/option-repo-type) option about that.

It's also probably why the patroni create method doesn't work.

First, share a repo for both of your PG instances (primary/standby) and then try the restore command manually. Then, try with patroni.

**Comment by rachid-casa** [comment]
Thanks for the suggestions. I will test it as soon as possible.
Kind regards
