### ISSUE TITLE
libxml2 not found on FreeBSD 12.2 when compiling 2.31

### ISSUE THREAD

**Issue by fluca1978** [pgbackrest/pgbackrest#1291]
Trying to compile pgbackrest 2.31, FreeBSD 12.2, I have to manually specify where libxml2 is:

```
% CFLAGS="-I/usr/local/include/libxml2/" LDFLAGS="-I/usr/local/include/libxml2/"  ./configure  --prefix=/usr/local/
```

Please note that both libxml2 is installed and xml2-config is available, but without specifying CFLAGS it is not possible to find it:

```
% pkg info | grep libxml2
libxml2-2.9.10_2               XML parser library for GNOME

% xml2-config 
Usage: xml2-config [OPTION]

Known values for OPTION are:

  --prefix=DIR          change libxml prefix [default /usr/local]
  --exec-prefix=DIR     change libxml exec prefix [default /usr/local]
  --libs                print library linking information
                        add --dynamic to print only shared libraries
  --cflags              print pre-processor and compiler flags
  --modules             module support enabled
  --help                display this help and exit
  --version             output version information
```

If I execute the `configure` without flags, the system seems unable to find libxml2:

```
./configure
...
checking for pkg-config... no
checking for xmlSaveToBuffer in -lxml2... yes
checking libxml/parser.h usability... no
checking libxml/parser.h presence... no
checking for libxml/parser.h... no
configure: error: header file <libxml/parser.h> is required
```

Same happens compiling against head d350d1cc2139038d6f45cfcb5b59a5dc5994d269.
This old commit (before introduction of XML2 config variable) seems to work: 600a51815feacb149add2bb777d6a3b4d284c8aa. However it is one year old, so I could be mislead from XML2 related stuff.

**Comment by dwsteele** [comment]
We build and test on FreeBSD now and we haven't seen this issue. Here's the env/test: https://github.com/pgbackrest/pgbackrest/blob/release/2.32/.cirrus.yml#L12

So it seems like this might be an issue in your env, perhaps a missing path, custom config, or missing package. Try the setup above and see if that works. If not we are willing to take suggestions on changes to configure, as long as they work in all our envs.

**Comment by fluca1978** [comment]
The responsible was `pkgconf` that was missing due to a broken line on my ansible script.
I've tested that removing `pkgconf` the error appears, while having it in place fixes the problem.
Sorry for the noise.

**Comment by dwsteele** [comment]
No worries, we appreciate you keeping an eye on FreeBSD.
