### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by msqr** [pgbackrest/pgbackrest#1293]
I use [poudriere](https://github.com/freebsd/poudriere) and [portshaker](https://github.com/smortex/portshaker) to build various packages that don't exist in the official FreeBSD ports tree. I needed to include pgBackRest so I created a [databases/pgbackrest](https://github.com/SolarNetwork/freebsd-custom-ports/tree/main/databases/pgbackrest) port configuration. Just posting here in case anyone else is looking to build pgBackRest with poudriere. Or even better, if someone was interested in maintaining an official FreeBSD port this could serve as a starting point. Cheers!

**Comment by dwsteele** [comment]
Cool! Know anyone who might be interested, @fluca1978?

**Comment by fluca1978** [comment]
My dream!
I'm not  a package mantainer, but I would like to help in this!

**Comment by keithf4** [comment]
I'd be up for helping to test this as well! I use `portmaster` myself. I put the port config that @msqr made into place and portmaster ran the compile/install without any issues. Had an update for my postgres port today too
```
===>>> The following actions were performed:
        Upgrade of postgresql10-client-10.15 to postgresql10-client-10.16
        Installation of databases/postgresql-libpqxx (postgresql-libpqxx-7.2.0)
        Upgrade of postgresql10-server-10.15 to postgresql10-server-10.16
        Installation of textproc/p5-YAML (p5-YAML-1.30)
        Installation of databases/pgbackrest (pgbackrest-2.32_1)
```
However, I don't see it actually creating a binary file anywhere? I looked in /usr/local/bin (where I would expect it to be), /usr/bin, and /bin

**Comment by msqr** [comment]
@keithf4 here's what I see after installing the package on my systems:

```
% pkg info -l pgbackrest
pgbackrest-2.32_1:
	/usr/local/bin/pgbackrest
	/usr/local/share/licenses/pgbackrest-2.32_1/LICENSE
	/usr/local/share/licenses/pgbackrest-2.32_1/MIT
	/usr/local/share/licenses/pgbackrest-2.32_1/catalog.mk
```

FYI I just [committed an update](https://github.com/SolarNetwork/freebsd-custom-ports/commit/0b8ffd21a40e8570495ed9d86cd92ee789d05f0d) to the `Makefile` that simplifies the build and removes some unnecessary dependencies.

**Comment by keithf4** [comment]
Just ran the update for 2.32_1 and now the binary is showing up. Not sure what was going on before. And help command at least seems to work. Will try setting up and running some backups when I get a chance.
```
$ which pgbackrest
/usr/local/bin/pgbackrest

pgbackrest help                                                                                        
pgBackRest 2.32 - General help                                                                                                              
                                                                                                                                            
Usage:                                                                                                                                      
    pgbackrest [options] [command]                                                                                                          
                                                                                                                                            
Commands:                                                                                                                                   
    archive-get     Get a WAL segment from the archive.                                                                                     
    archive-push    Push a WAL segment to the archive.                                                                                      
    backup          Backup a database cluster.                                                                                              
    check           Check the configuration.                                                                                                
    expire          Expire backups that exceed retention.                                                                                   
    help            Get help.                                                                                                               
    info            Retrieve information about backups.                                                                                     
    repo-get        Get files from a repository.                                                                                            
    repo-ls         List files in a repository.                                                                                             
    restore         Restore a database cluster.                                                                                             
    stanza-create   Create the required stanza data.                                                                                        
    stanza-delete   Delete a stanza.                                                                                                        
    stanza-upgrade  Upgrade a stanza.                                                                                                       
    start           Allow pgBackRest processes to run.                                                                                      
    stop            Stop pgBackRest processes from running.                                                                                 
    version         Get version.                                                                                                            
                                                                                                                                            
Use 'pgbackrest help [command]' for more information.
```

**Comment by keithf4** [comment]
Actually, I figured out the problem. That install in my last message was on a second server and worked fine. First server I'd accidentally named `pkg-plist` as `pkg-list`. All is good now on both systems!

Some other things that would be useful for the port would be to make default locations. 


Default log location should be fine as on other OS's
`/var/log/pgbackrest`

Is there a way to have it look in the expected user etc location on FreeBSD by default vs the root level `/etc/`? Right now I have to manually give the --config option for every command to find the config file here

`/usr/local/etc/pgbackrest`

I know on other OS's it has the default home directory and repo location as `/var/lib/pgbackrest`. The default postgres user home directory on FreeBSD is `/var/db/postgres`. Perhaps have it be `/var/db/pgbackrest`?

With this configuration
```
[global]
repo1-path=/var/db/pgbackrest
repo1-retention-full=2
log-level-console=info

[main]
pg1-path=/tank/pgdata/10
```
I was able to get a successful create & backup run as the postgres user using the above directory locations
```
$ pgbackrest --stanza=main --config=/usr/local/etc/pgbackrest/pgbackrest.conf stanza-create
2021-02-22 15:03:23.149 P00   INFO: stanza-create command begin 2.32: --config=/usr/local/etc/pgbackrest/pgbackrest.conf --exec-id=53329-04b060c4 --log-level-console=info --pg1-path=/tank/pgdata/10 --repo1-path=/var/db/pgbackrest --stanza=main
2021-02-22 15:03:23.818 P00   INFO: stanza-create for stanza 'main' on repo1
2021-02-22 15:03:23.916 P00   INFO: stanza-create command end: completed successfully (767ms)
```
```
$ pgbackrest --config=/usr/local/etc/pgbackrest/pgbackrest.conf --stanza=main info
stanza: main
    status: ok
    cipher: none

    db (current)
        wal archive min/max (10): 000000010000003C00000069/000000010000003C0000006D

        full backup: 20210222-151311F
            timestamp start/stop: 2021-02-22 15:13:11 / 2021-02-22 15:17:12
            wal start/stop: 000000010000003C0000006D / 000000010000003C0000006D
            database size: 380.6MB, database backup size: 380.6MB
            repo1: backup set size: 53.2MB, backup size: 53.2MB
```

**Comment by msqr** [comment]
> Is there a way to have it look in the expected user etc location on FreeBSD by default vs the root level `/etc/`? Right now I have to manually give the --config option for every command to find the config file here
> 
> `/usr/local/etc/pgbackrest`

I wished for that as well, but didn't find a way to configure the build with a custom config prefix of `/user/local`. I didn't spend a lot of time looking, though. Perhaps @dwsteele you would know if the build supports such an option?

**Comment by dwsteele** [comment]
@mschout has an open PR #1255 for configuring the base config path so we should have that fairly soon.

The rest can be configured via `pgbackrest.conf`, though we would not object to configure switches for them.

**Comment by msqr** [comment]
Awesome, so after #1255 the FreeBSD port could configure `/usr/local` as the base config path.

**Comment by mschout** [comment]
I have a FreeBSD port request open as well, which I will update after #1255 is merged. FYI.\

See: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=251687

**Comment by mschout** [comment]
Ok thanks @msqr I'll update it to include that as well.

**Comment by mschout** [comment]
I updated the port shar.  Hopefully a committer will merge it soon so that it will be in the ports tree.

**Comment by mschout** [comment]
Guess since it still hasn't been picked up I should make another shar for v2.33

**Comment by dwsteele** [comment]
@msqr @keithf4 @fluca1978 Some comments over at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=251687 might help move that package along...

**Comment by mschout** [comment]
I updated the port to 2.33 release.  I see someone change the assignee so hopefully thats good news.

**Comment by mschout** [comment]
pgbackrest has been committed to the FreeBSD ports tree.  This can be closed.

See: https://cgit.freebsd.org/ports/commit/?id=c49969ef4f68de362c260f7822e212c8045f7e6a
