### ISSUE TITLE
pgbackrest archive timeout when performing backups

### ISSUE THREAD

**Issue by jonnyaces2020** [pgbackrest/pgbackrest#1303]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
>2.29
2. PostgreSQL version:
>PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
>Red Hat Enterprise Linux Server release 7.9 (Maipo)

4. Did you install pgBackRest from source or from a package?
>source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
>attached
7. Describe the issue:
Hello we have set up a new stanza to start taking backups using pgbackrest of our postgres cluster, but everytime I run a check or try to run a full backup I receive the following error:
ERROR: [082]: WAL segment 00000001000071AF000000EF was not archived before the 360000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
2021-02-18 09:29:54.098 P00   INFO: check command end: aborted with exception [082]

it's a different wal segment every time, but the same issue.
why is this happening and what can I do to fix this?

Thanks,

Jon
[postgresql-Thu.log](https://github.com/pgbackrest/pgbackrest/files/6004019/postgresql-Thu.log)
[pgbackrestinfo20210218.txt](https://github.com/pgbackrest/pgbackrest/files/6004021/pgbackrestinfo20210218.txt)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/6004022/pgbackrest.conf.txt)

**Comment by pgstef** [comment]
Hi,

The error is due to the failing PG `archive_command`:
```
ERROR: [037]: option 'pg1-path' must be specified when relative wal paths are used
       HINT: is %f passed to archive-push instead of %p?
       HINT: PostgreSQL may pass relative paths even with %p depending on the environment.
2021-02-18 09:23:04 CST::@:[91284] LOG:  archive command failed with exit code 37
2021-02-18 09:23:04 CST::@:[91284] DETAIL:  The failed archive command was: pgbackrest --stanza=pgpeccon1 archive-push pg_wal/00000001000070DF000000A9
```

You request the **pgpeccon1** stanza in your `archive-push` command but configured **pg_cluster1**. The stanza parameter should be identical in your `archive-push`,  `check` or `backup` commands.

Fixing that in `archive_command` should help.

Kind regards,

**Comment by jonnyaces2020** [comment]
Thanks pgstef great catch, however, I've modified in postgresql.conf and reloaded as follows:

                 archive_command
-------------------------------------------------
 pgbackrest --stanza=pg_cluster1 archive-push %p

then i switched wal a few times:
select pg_switch_wal();
select pg_switch_wal();

then i restarted the stanza:
pgbackrest --stanza=pg_cluster1 --log-level-console=info stop
pgbackrest --stanza=pg_cluster1 --log-level-console=info start

and i'm still getting an error when running a check:
$ pgbackrest --stanza=pg_cluster1 --log-level-console=info check
2021-02-18 12:37:14.852 P00   INFO: check command begin 2.29: --archive-timeout=360 --buffer-size=8388608 --log-level-console=info --pg1-path=/data/pgsql/12/data --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/postgres --repo1-s3-bucket=dbis-db-backup --repo1-s3-endpoint=s3.us-east-1.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --repo1-type=s3 --stanza=pg_cluster1
ERROR: [082]: WAL segment 00000001000071B300000087 was not archived before the 360000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
2021-02-18 12:43:16.138 P00   INFO: check command end: aborted with exception [082]

**Comment by jonnyaces2020** [comment]
i also ran a full backup and got the same issue again:

2021-02-18 14:28:34.098 P00   INFO: full backup size = 7093.6GB
2021-02-18 14:28:34.098 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2021-02-18 14:28:34.301 P00   INFO: backup stop archive = 00000001000071B5000000AB, lsn = 71B5/AB86F358
2021-02-18 14:28:34.650 P00   INFO: check archive for segment(s) 00000001000071B3000000D8:00000001000071B5000000AB
2021-02-18 14:34:35.521 P00  ERROR: [082]: WAL segment 00000001000071B3000000D8 was not archived before the 360000ms timeout
                                    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
                                    HINT: check the PostgreSQL server log for errors.
2021-02-18 14:34:35.524 P00   INFO: backup command end: aborted with exception [082]

**Comment by pgstef** [comment]
> then i restarted the stanza:

This step wasn't needed. Changing the configuration file will effect the next command running immediately.

>  I've modified in postgresql.conf and reloaded as follows

I'll assume you mean reloaded the PG config.

At this point, you'll need to follow the HINT:
> HINT: check the PostgreSQL server log for errors.

The output of the `archive-push` command are stored in the PG logs since PG `archive_command` triggers it. It might indicate if/why that command is failing.

**Comment by jonnyaces2020** [comment]
Thank you again for the help, I ended up bumping up the archive_timeout to 720, once that was done it was able to push through and complete the backup

**Comment by dwsteele** [comment]
360 seconds should be more than enough to archive a single WAL file, so it looks like you are seriously IO constrained.
