### ISSUE TITLE
repo-ls on remote host

### ISSUE THREAD

**Issue by fluca1978** [pgbackrest/pgbackrest#1304]
I'm probably unable to understand how the new command `repo-ls` works from the remote host (the backupped host).

On the backup machine it works fine:
```
$ pgbackrest  --output text  repo-l
archive
backup
```

but on the remote machine, the one that is running a PostgreSQL that is backed up by `pgbackrest` I'm unable to get the repository content:

```
 % pgbackrest  --repo-path /backup/pgbackrest --repo-host carmensita --repo-host-user backup  --output json  repo-ls 
ERROR: [031]: invalid option '--repo-host'
```

and without the `--repo-host` option it does nothing:

```
% pgbackrest  --repo-path /backup/pgbackrest   --output text  repo-ls
```

My `pgbackrest.conf` file on the remote machine is:

```
% sudo cat /usr/local/etc/pgbackrest.conf
[global]
repo1-path = /backup/pgbackrest
repo1-host-user = backup
repo1-host = carmensita
```

What am I missing?

**Comment by dwsteele** [comment]
I think you want either:
```
pgbackrest  --repo1-path /backup/pgbackrest --repo1-host carmensita --repo1-host-user backup  --output json  repo-ls
```
or:
```
pgbackrest  --config /usr/local/etc/pgbackrest.conf --output json  repo-ls
```

**Comment by fluca1978** [comment]
Shame on me!
Today I did not took my caffeine and was not realizing the missing repo index.
Thanks, it worked (of course both ways are good).
