### ISSUE TITLE
removing WALs from a backup in order to break a backup by purpose

### ISSUE THREAD

**Issue by fluca1978** [pgbackrest/pgbackrest#1306]
_DISCLAIMER: I'm trying to understand better how pgbackrest works and how one could possibily break it. I'm not ranting about this wonderful tool._

I'm running version 2.32 from a Fedora machine against a FreeBSD PostgreSQL 12.5 cluster.

I've done a single full backup from a new cluster installation:
```
$ pgbackrest --stanza miguel info
stanza: miguel
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12): 000000010000000000000001/000000010000000000000004

        full backup: 20210222-104127F
            timestamp start/stop: 2021-02-22 10:41:27 / 2021-02-22 10:46:31
            wal start/stop: 000000010000000000000003 / 000000010000000000000003
            database size: 24.0MB, database backup size: 24.0MB
            repo1: backup set size: 2.9MB, backup size: 2.9MB

$ pgbackrest --stanza miguel check
2021-02-22 10:48:18.467 P00   INFO: check command begin 2.32: --exec-id=6948-956bf26a --log-level-console=info --pg1-host=miguel --pg1-host-user=postgres --pg1-path=/postgres/12/data --repo1-path=/backup/pgbackrest --stanza=miguel
2021-02-22 10:48:18.657 P00   INFO: check repo1 configuration (primary)
2021-02-22 10:48:18.768 P00   INFO: check repo1 archive for WAL (primary)
2021-02-22 10:48:19.482 P00   INFO: WAL segment 000000010000000000000005 successfully archived to '/backup/pgbackrest/archive/miguel/12-1/0000000100000000/000000010000000000000005-75be032ee591a13bce79a3210c8a568722ba7da0.gz' on repo1
2021-02-22 10:48:19.590 P00   INFO: check command end: completed successfully (1126ms)
```

so fine, so good.
Now I tried to break the backup by purpose removing the WALs in the `archive` directory:

```
$ rm /backup/pgbackrest/archive/miguel/12-1/0000000100000000/000000010000000000000006-2038c2cc32c5d4561aedb87b50ececa6558c18ef.gz 
```

and then checked it again, and it appears to be safe (at least to me):

```
$ pgbackrest --stanza miguel check
2021-02-22 10:50:16.072 P00   INFO: check command begin 2.32: --exec-id=7088-518f8a19 --log-level-console=info --pg1-host=miguel --pg1-host-user=postgres --pg1-path=/postgres/12/data --repo1-path=/backup/pgbackrest --stanza=miguel
2021-02-22 10:50:16.278 P00   INFO: check repo1 configuration (primary)
2021-02-22 10:50:16.416 P00   INFO: check repo1 archive for WAL (primary)
2021-02-22 10:50:17.119 P00   INFO: WAL segment 000000010000000000000007 successfully archived to '/backup/pgbackrest/archive/miguel/12-1/0000000100000000/000000010000000000000007-94aaaf4c42c2b12293a710194d991e460f23d402.gz' on repo1
2021-02-22 10:50:17.224 P00   INFO: check command end: completed successfully (1155ms)

$ pgbackrest --stanza miguel info
stanza: miguel
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12): 000000010000000000000002/000000010000000000000007

        full backup: 20210222-104127F
            timestamp start/stop: 2021-02-22 10:41:27 / 2021-02-22 10:46:31
            wal start/stop: 000000010000000000000003 / 000000010000000000000003
            database size: 24.0MB, database backup size: 24.0MB
            repo1: backup set size: 2.9MB, backup size: 2.9MB
```

Now, I was expecting pgBackRest finding out that something was missing, at least because the manifest for that backup should not match the situation on disk. Apprently there is something I did not understand.

Then, I tried to recover the backup, so on the target machine:

```
% sudo -u postgres pgbackrest  --config /usr/local/etc/pgbackrest.conf  --stanza miguel  --delta restore
```

and the cluster was able to start. I suppose this because of the `--delta-restore` option, so that the missing WAL was not in the backup but in the cluster, and PostgreSQL was happy.

What am I missing here?

**Comment by pgstef** [comment]
Hi,

The check command only check if the archiving system is working. Not if the backups are OK.
The archives aren't stored in any manifest either. So, the info command will only look at the oldest and newest WAL file in the repo, not checking in between. Doing so would take a lot of time/resources since the amount of WAL archives could be really huge.

All the wals required for the restore were probably in your pg_wal directory indeed. You could retry without delta or cleaning the pg_wal directory before restore.

For now, there's no way to detect missing wal files in pgBackRest itself afaik. (That's why I usually install check_pgbackrest too)
I know @cmwshang is working on a `verify` command but I don't think it checks all the WAL files in the repos yet.

**Comment by fluca1978** [comment]
> For now, there's no way to detect missing wal files in pgBackRest itself afaik. (That's why I usually install check_pgbackrest too)
> I know @cmwshang is working on a `verify` command but I don't think it checks all the WAL files in the repos yet.

it's all clear, but as far as I know even check_pgbackrest does not detect the missing WAL, or I don't get the point in your suggestion about installing it:

```
% sudo -u backup /usr/lib64/nagios/plugins/check_pgbackrest -s archives  -S miguel

WAL_ARCHIVES OK - 6 WAL archived, latest archived since 1m12s | latest_archive_age=72s num_archives=6
```

**Comment by pgstef** [comment]
Well it should: https://github.com/pgstef/check_pgbackrest/blob/master/check_pgbackrest#L674.
Perhaps adding `--debug --list-archives --extended-check --output=human` would help understand why it doesn't :confused:

What do you get if you use `pgbackrest repo-ls archive/miguel/12-1/0000000100000000` ?

**Comment by fluca1978** [comment]
> --debug --list-archives --extended-check --output=human

I'm not sure, but after updating to check_pgbackrest HEAD I've got it:

```
% sudo -u backup ./check_pgbackrest --output=human -s archives  -S miguel 
Service        : WAL_ARCHIVES
Returns        : 2 (CRITICAL)
Message        : wrong sequence, 1 missing file(s) (000000010000000000000006 / 000000010000000000000006)
...
```

And in fact, the 0x06 is missing from the repo:

```
% sudo -u backup pgbackrest repo-ls archive/miguel/12-1/0000000100000000
000000010000000000000002-f302ff85b8b0e57749de020cee7ac6afd24d4893.gz
000000010000000000000003-0ea012775714ea4e9afbdce78d6ac865fe6dfdbf.gz
000000010000000000000003.00000028.backup
000000010000000000000004-2639b1e171bd38501538846e3b9eb58677bfbfd3.gz
000000010000000000000005-75be032ee591a13bce79a3210c8a568722ba7da0.gz
000000010000000000000007-94aaaf4c42c2b12293a710194d991e460f23d402.gz
000000010000000000000008-71c53883785d01862e10a08effd82c447562eea1.gz
```
Thanks.
