### ISSUE TITLE
WARN: unable to check pg-1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432': could not connect to server: No such file or directory                                         Is the server running locally and accepting                                         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"? 2021-03-02 02:10:01.622 P00  ERROR: [056]: unable to find primary cluster - cannot proceed 2021-03-02 02:10:01.622 P00   INFO: backup command end: aborted with exception [056]

### ISSUE THREAD

**Issue by bsingh786** [pgbackrest/pgbackrest#1322]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.28

2. PostgreSQL version: 12.3 (postgresql open source)

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos8

4. Did you install pgBackRest from source or from a package?  Source 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
We are getting the below issue while executing the backup through pgbackrest.

2021-03-02 02:10:01.620 P00   INFO: backup command begin 2.28: --archive-check --archive-copy --compress --db-timeout=7200 --log-level-console=detail --log-level-file=detail --log-level-stderr=detail --log-path=/apayrman/pgbackrest/backup/log --pg1-path=/apayothr/pgsql/12.3/data --process-max=12 --protocol-timeout=9000 --repo1-path=/apayrman/pgbackrest --repo1-retention-archive=8 --repo1-retention-full=2 --stanza=uatpgdbserver --start-fast --stop-auto
2021-03-02 02:10:01.622 P00   WARN: unable to check pg-1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432': could not connect to server: No such file or directory
                                        Is the server running locally and accepting
                                        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2021-03-02 02:10:01.622 P00  ERROR: [056]: unable to find primary cluster - cannot proceed
2021-03-02 02:10:01.622 P00   INFO: backup command end: aborted with exception [056]

DB version :- postgresql 12.3(open source)

OS :- Centos8

Pgbackrest version :- 2.28

Pgbackrest.conf parameters :- 

[uatpgdbserver]
pg1-path=/apayothr/pgsql/12.3/data
db-timeout=7200
db1-user=postgres

[global]
repo1-path=/apayrman/pgbackrest
compress=y
retention-archive=8
retention-full=2
process-max=12
log-path=/apayrman/pgbackrest/backup/log
start-fast=y
stop-auto=y
protocol-timeout=9000
archive-check=y
archive-copy=y

Please suggest the solution for above issue.

**Comment by dwsteele** [comment]
Closing since this was cross-posted to pgsql-general and answered there: https://www.postgresql.org/message-id/CAFD-joP-=bK-9X8wo55dHFfztBiumjGn=EGQ8jUJPsEGVC0_Bw@mail.gmail.com.

**Comment by bsingh786** [comment]
Hi David,

I had raised this issue with postgresql community but they said it is not
related to postgres and asked to contact pgbackrest community for
resolution.

Could you plz reopen this case as still resolution not provided.

Thanks.

**Comment by pgstef** [comment]
Reid Thompson answered you:

```
>  unable to connect to 'dbname='postgres' port=5432': could not connect to server: No such file or directory
>                                         Is the server running locally and accepting
>                                         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

it's telling you right here why it failed; and what to check for.
you've configured pgbackrest to connect to the local postgres db using
the unix domain socket. That socket was not present when you attempted
to run pgbackrest.
```
The first question to answer: **is your PG cluster running?** 

Some general thoughts about your configuration:
- `db1-user` should be `pg1-user`.
- Is there a reason for you to set `db-timeout=7200` and `protocol-timeout=9000`? Have you noticed timeouts before?
- `compress=y` and `archive-check=y` are the default value.
- `retention-full` should be `repo1-retention-full`, same for `repo1-retention-archive`.
- Your retention settings are really strange. You want to keep WAL archives for 8 full backups but only keep 2 of them. You'll end up with unneeded WAL archives in your repo. Unless you want less WAL archives than backups (and then break your PITR capability), don't use `repo1-retention-archive`.

That said, the problem here is how to reach the PG cluster, if it's running. Are you executing the `pgbackrest` commands from the same server where your database cluster is running? Did the `stanza-create` and `check` commands run fine? What does `psql -c "show unix_socket_directories;"` tell you?

**Comment by bsingh786** [comment]
Hi Stefan,

Thanks for your reply.

The first question to answer: *is your PG cluster running?*

*>> Yes it's up and running.*

Are you executing the pgbackrest commands from the same server where your
database cluster is running? Did the stanza-create and check commands run
fine? What does psql -c "show unix_socket_directories;" tell you?

>> Yes, pgbackrest is configured on same server where DB cluster running
and we are executing the pgbackrest command on DB server.

>> Stanza-create and check command running without any issue.

>> unix_socket_directories is '/tmp .

Thanks..

**Comment by pgstef** [comment]
Given your `unix_socket_directories`, you need to set `pg1-socket-path=/tmp` (or add `/var/run/postgresql` to your `unix_socket_directories`).

**Comment by bsingh786** [comment]
Thank you Stefan ,it's working now.

Thanks.
