### ISSUE TITLE
Create a standby server with PostgreSQL 12 and pgbackrest

### ISSUE THREAD

**Issue by julienc256** [pgbackrest/pgbackrest#1324]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
**2.31**

2. PostgreSQL version:
**11.11 and 12.5**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
**Red Hat Enterprise Linux Server release 7.6 (Maipo)**
**2 servers : one master and one slave for replication**
Name of master machine is dvsgddw00b00004
Name of slave machine is dvsgddw00b00005

4. Did you install pgBackRest from source or from a package?
From a package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file :

[49R]
pg1-path=/pgqdata/pgsrvref/data
**recovery-option=primary_conninfo=host=dvsgddw00b00004 user=replicator application_name=SLAVE_dvsgddw00b00005
recovery-option=standby_mode=on**

[global]
log-level-file=detail
repo1-host=dvsgddw00b00004
repo1-path=/pgqdata/backup/pgsrvref/pgbackrest
repo1-host-user=postgres

    - `postgresql.conf` settings applicable to pgBackRest :

archive_command=pgbackrest --stanza=49R archive-push %p
archive_mode=on
max_wal_senders=10
wal_leve|=replica
listen_addresses=localhost,dvsgddw00b00005
port=5432

No errors found

7. Describe the issue:
From what I understood, the parameter « recovery-option=standby_mode=on » in pbbackrest.conf is no longer used in postgresql 12.
Instead I have to add the « --type=standby » in pgbackrest command

Is that true ? I hope so !

But some machines I use are still using PostgreSQL 11, and I want to use the same postgresql.conf whatever version of PostgreSQL 11 or 12)
So in the postgresql.conf file I remove the line « recovery-option=standby_mode=on » and instead I add the parameter « --recovery-option=standby_mode=on » in pgbackrest command (for the machine running PostgreSQL 11)

So :
If postgresql 12, the command is : pgbackrest --stanza=...    --type=standby
If postgresql 11, the command is : pgbackrest --stanza=...    --recovery-option=standby_mode=on

And same postgresql.conf for postgresql 11 and 12

BUT the problem is that after recovery on the slave that turns on PostgreSQL 11, the primary_conninfo line in recovery.conf file is not present !!!!!!

It seems that if --recovery-option parameter is present in pgbackrest command, then all « recovery-option » parameters in postgresql.conf are discared !!!
I really think the best solution would be to take into account « --recovery-option=standby_mode=on » that is on the pgbackrest command, AND the recovery-option=primary_conninfo=... (and other recovery-option parameters) that are on the pgbackrest.conf.

It's a pity that if the recovery-option parameter is present as a command parameter, then it overwrites all recovery options in postgresql.conf, even if the options are different !

**Comment by pgstef** [comment]
Hi,

First of all, please don't use master/slave. The correct names are primary/standby. Thanks.

It seems you mix `postgresql.conf` for PG with `pgbackrest.conf` for pgBackRest. Which configuration file would you like to be the same for PG 11 and 12? `primary_conninfo` should be in `recovery.conf` with PG 11, while it should be in `postgresql.conf` (or `postgresql.auto.conf`) with PG 12. Furthermore, if those are 2 different PG clusters, you should have 2 stanzas configured in `pgbackrest.conf`. So I don't really understand your problem.

Anyway, an example with PG 12:

```bash
$ cat pgbackrest.conf
...
[my_stanza]
pg1-path=/var/lib/pgsql/12/data
recovery-option=primary_conninfo=host=primary

$ pgbackrest --stanza=my_stanza --type=standby restore

$ cat postgresql.auto.conf 
...
# Recovery settings generated by pgBackRest restore on 2021-03-08 16:37:11
primary_conninfo = 'host=primary'
restore_command = 'pgbackrest --stanza=my_stanza archive-get %f "%p"'
```

Now, same with PG 11:

```bash
$ cat pgbackrest.conf
...
[my_stanza]
pg1-path=/var/lib/pgsql/11/data
recovery-option=primary_conninfo=host=primary

$ pgbackrest --stanza=my_stanza --type=standby restore

$ cat /tmp/restored_data/recovery.conf 
# Recovery settings generated by pgBackRest restore on 2021-03-08 16:46:28
primary_conninfo = 'host=primary'
restore_command = 'pgbackrest --stanza=my_stanza archive-get %f "%p"'
standby_mode = 'on'
```

The options set in the configuration file are parsed and used in the pgBackRest commands. In the `info` log-level output of the restore command, you should see `--recovery-option=primary_conninfo=host=primary`. So put it in the config or use it in the command-line is the same.

The issue you seem to describe comes from that options parsing. You specify `recovery-option` twice. Once in command-line, once in configuration file. If you provide any other recovery setting in the command line, you will erase what is in the configuration file. It's not linked to any specific PG version.

```bash
$ pgbackrest --stanza=my_stanza --recovery-option=standby_mode=on restore --pg1-path=/tmp/restored_data
-bash-4.2$ cat /tmp/restored_data/recovery.conf 
# Recovery settings generated by pgBackRest restore on 2021-03-08 16:47:50
standby_mode = 'on'
restore_command = 'pgbackrest --stanza=my_stanza archive-get %f "%p"'
```

Is there a reason why you don't use [`--type=standby`](https://pgbackrest.org/command.html#command-restore/category-command/option-type) with your PG 11 command instead?

**Comment by julienc256** [comment]
Thank you for your detailed answer !

So I will use `--type=standby` with my PG 11 & 12 commands.

Thus, the contents of pgbackrest_slave.conf will be :

`[<my_stanza>]
pg1-path=/pgqdata/pgsrvref/data
recovery-option=primary_conninfo=host=<hostname_primary> user=replicator application_name=SLAVE_<hostname_standby>

[global]
...
`

And the restore command will be (whatever PG 11 or 12) : 
`pgbackrest --stanza=<my_stanza> restore --config=/etc/pgbackrest_slave.conf --pg1-path=/pgqdata/pgsrvref/data --type=standby`

Is that Ok ?

**Comment by pgstef** [comment]
You don't need to specify `--pg1-path` in your restore command unless you want to overload what's in your configuration file.
`pgbackrest --stanza=<my_stanza> restore --config=/etc/pgbackrest_standby.conf --type=standby` should be enough if you have the `recovery-option=primary_conninfo...` in your configuration file.

**Comment by cmwshang** [comment]
@julienc256 this is also pointed out in the pgBackRest documentation:
User Guide: https://pgbackrest.org/user-guide.html#upgrading/v1-v2
Configuration reference: https://pgbackrest.org/configuration.html#section-stanza, and https://pgbackrest.org/configuration.html#section-repository
We are open to suggestions on improving the documents, though, if you'd like to suggest/contribute improvements.

**Comment by julienc256** [comment]
Hi again,

I have another question : why can't we create a stanza on a standby server ?

**Comment by pgstef** [comment]
@julienc256 

It is possible to take a backup from a standby server, with the [`backup-standby`](https://pgbackrest.org/user-guide.html#standby-backup) option.
However, it's an "hybrid" situation:
- the backup command can be run on the standby server
- `pg_start/stop_backup` functions are executed on the primary
- we'll wait the replay location on standby to reach the start location
- copy most of the data files from the standby server

Are you worrying about the `stanza-create` command? [There](https://github.com/pgbackrest/pgbackrest/commit/31c7824a4d84cbf5a0ba0938f4caa546fa67af0a) has been some changes with those commands lately, so probably you'll want to try it with the new release (2.33) coming next month.

**Comment by julienc256** [comment]
Thank you for your reply !

I have another problem, that would be great if you can help me, here it is :

I setup a replication with a primary and a standby server. Replication works fine, as seen in the $PGLOG file of standby server :
`started streaming WAL from primary at 0/xxxxxxxx on timeline 1`

**Then I want to test failover**. There is already a script that makes it (it is a quite short script, that launches a « pg_ctl -D ${PGDATA} promote » on the standby server)

Before launching the script, I stop the primary server (to simulate a failure of it)

Then I launch failover, to promote standby server

Scripts launches well, failover is done, but in the $PGLOG file I see this :

```
2021-03-19 18:26:21 CET;17164;;;00000;LOG:  received promote request
2021-03-19 18:26:21 CET;17164;;;00000;LOG:  redo done at 0/A000028
2021-03-19 18:26:21 CET;17164;;;00000;LOG:  last completed transaction was at log time 2021-03-19 18:25:25.674835+01
2021-03-19 18:26:22 CET;17164;;;00000;LOG:  selected new timeline ID: 2
2021-03-19 18:26:22 CET;17164;;;00000;LOG:  archive recovery complete
2021-03-19 18:26:22 CET;17162;;;00000;LOG:  database system is ready to accept connections
ERROR: [055]: unable to load info file '/pgqdata/backup/pgsrvref/pgbackrest/archive/49R/archive.info' or '/pgqdata/backup/pgsrvref/pgbackrest/archive/49R/archive.info.copy':
       FileMissingError: unable to open missing file '/pgqdata/backup/pgsrvref/pgbackrest/archive/49R/archive.info' for read
       FileMissingError: unable to open missing file '/pgqdata/backup/pgsrvref/pgbackrest/archive/49R/archive.info.copy' for read
       HINT: archive.info cannot be opened but is required to push/get WAL segments.
       HINT: is archive_command configured correctly in postgresql.conf?
       HINT: has a stanza-create been performed?
       HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
2021-03-19 18:26:22 CET;18096;;;00000;LOG:  archive command failed with exit code 55
2021-03-19 18:26:22 CET;18096;;;00000;DETAIL:  The failed archive command was: pgbackrest --stanza=49R archive-push pg_wal/00000002.history
```

How to solve this problem ?

I first had the Idea to create a stanza on the standby server, but it's not possible to create a stanza on a standby server ! (I get the error : ERROR: [027]: primary database not found)

My second idea was to create a stanza on the server before it becomes standby (before replication, when it is still in standalone mode). So I create stanza on both servers, setup replication, then I retry failover, but I get another error :

```
2021-03-25 10:31:28 CET;21439;;;00000;LOG:  received promote request
2021-03-25 10:31:28 CET;21439;;;00000;LOG:  redo done at 0/B000028
2021-03-25 10:31:28 CET;21439;;;00000;LOG:  last completed transaction was at log time 2021-03-25 10:30:22.237136+01
2021-03-25 10:31:29 CET;21439;;;00000;LOG:  selected new timeline ID: 2
2021-03-25 10:31:29 CET;21439;;;00000;LOG:  archive recovery complete
2021-03-25 10:31:29 CET;21437;;;00000;LOG:  database system is ready to accept connections
ERROR: [044]: PostgreSQL version 12, system-id 6940652206543116101 do not match repo1 stanza version 12, system-id 6940652527417242031
       HINT: are you archiving to the correct stanza?
2021-03-25 10:31:29 CET;23084;;;00000;LOG:  archive command failed with exit code 44
2021-03-25 10:31:29 CET;23084;;;00000;DETAIL:  The failed archive command was: pgbackrest --stanza=49R archive-push pg_wal/00000002.history
ERROR: [044]: PostgreSQL version 12, system-id 6940652206543116101 do not match repo1 stanza version 12, system-id 6940652527417242031
       HINT: are you archiving to the correct stanza?
```


So my question is :

What method should be adopted for failover to work well with pgbackrest ?

**Comment by pgstef** [comment]
It sounds like your repo isn't mounted the same way on both your servers.
All PG replicas should share the same repo/stanza. That's what indexing (pg1, pg2, pg3,..) is made for. Then, your `archive_mode` and `archive_command` could be the same on all your PG hosts.
If I didn't gave it already, [here](https://pgstef.github.io/2020/09/04/combining_pgbackrest_and_streaming_replication.html) is a simple example to illustrate that situation.

**Comment by julienc256** [comment]
Thanks !

But I am still trying to understand ...

What I understood (correct me if I am wrong), is that :

As soon as standby server is promoted, the archive command « pgbackrest --stanza=49R archive-push pg_wal/xxxxxxxx.history » is launched on this server.
But ... As no stanza had been created on this server (because it was a standby server and we can't create a stanza on a standby), the pgbackrest archive-push command fails !

**Comment by pgstef** [comment]
`stanza-create` only creates sub-folders specific to that stanza inside the repository. All your PG hosts (within the same cluster) should share the same repo, so, the same stanza. You don't have to create another stanza.
Just make sure your repo is available on both servers and that your configuration match. As described in the example I gave you...

**Comment by julienc256** [comment]
Ok !
repo1-path (and eventually log-path) must be accessible by both primary and standby. So it must be a remote path, is that correct ?

**Comment by pgstef** [comment]
Well, there are entire chapters in PG [docs](https://www.postgresql.org/docs/current/high-availability.html) about replication, fail-over,.. I'm not sure why we'd want to add such PG basics inside our docs then.

Anyway, the [`repo1-*`](https://pgbackrest.org/configuration.html#section-repository) settings are indeed there to define the location of your backups (repo host, S3, Azure, GCS, NFS,..). One of the most important rules when speaking about backups is that you shouldn't keep your backups locally on your PG hosts.

In the example I already provided, the backups are stored in a NFS mount point. So `repo1-path` is the mount path, `repo1-type` is then posix or cifs (if you use a cifs share rather than nfs). `repo1-type` may even be S3/azure/... if you have external storage. That's totally up to you to define where you want to store your backups (and there are configuration examples for S3 and azure in the user-guide).

If you want to store your backup on a remote server, that's what we call "repository host" in the user-guide (or in [this example](https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html)).

**Comment by julienc256** [comment]
Thank you for your answer !
I began to read the example you gave to me, but it's for now a little bit too tricky for me.
I need to rise in skills by continuing to read documentation, lot of documentation. It 's really time consuming.
In fact there are already existing tools which do replication, fail-over, sync ... These tools use rsync, tar, gzip ... and work well.
But... I have been told to integrated pgbackrest into these tools. Being not an expert, this is a really painful task !
pgbackrest is a tool for expert users !

**Comment by julienc256** [comment]
Hi again,

After hours of tests and readings, me and my colleagues see no other solution than to create a stanza once the standby server has been promoted.
How to du a backup on the new primary if no stanza has been created ? So creating a stanza seems necessary therefore.

When promoting the standby server, there is this error :
`ERROR: [055]: unable to load info file '/pgqdata/backup/pgsrvref/pgbackrest/archive/49R/archive.info' or '/pgqdata/backup/pgsrvref/pgbackrest/archive/49R/archive.info.copy':
       FileMissingError: unable to open missing file '/pgqdata/backup/pgsrvref/pgbackrest/archive/49R/archive.info' for read
       FileMissingError: unable to open missing file '/pgqdata/backup/pgsrvref/pgbackrest/archive/49R/archive.info.copy' for read
       HINT: archive.info cannot be opened but is required to push/get WAL segments.
       HINT: is archive_command configured correctly in postgresql.conf?
       HINT: has a stanza-create been performed?
       HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.`

But never mind, we won't take it into account

**Comment by pgstef** [comment]
You'll then end-up with multiple stanza, configuration and backups. That won't allow you to restore a backup to create a new replica or refresh an old primary. That's not really how it's supposed to work so I don't really understand how you end up with that conclusion.

Be aware that, even without any PITR tool, from PG basic point of view, when speaking about streaming replication, it could happen that your standby server comes out of sync because the primary recycled its wal files before the replica gets it. In that case, having the `restore_command` configured to point on the backup repository where your primary `archive_command` send its wal archives is very helpful. Because your replica will then be able to catch-up its delay and restart the streaming connection afterwards.

It's very common use to have a dedicated backup location (on site with CIFS or NFS exports, in the cloud S3, Azure, GCS,..) and so, reaching that location from all your PG hosts inside the same stanza configuration can be very helpful.

**Comment by julienc256** [comment]
Ok !
Actually the restore_command works well.
I understand I don't have to create another stanza. But how to deal with the stanza when standby server becomes new primary server and old primary server becomes new standby server ? The stanza should be transferred from old primary to new primary, isn't it ? So how to do that ?

**Comment by julienc256** [comment]
Thanks again.

In fact in our case, the repository is a local directory on the primary host. (primary and standby are 2 distant machines)
In /etc/pgbackrest.conf on the primary we have this :
```
[global]
repo1-path=/pgqdata/backup/pgsrvref/pgbackrest
...
```

On the standby we have this :
`recovery-option=primary_conninfo=host=<hostname_primary>

...
repo1-host=<hostname_primary>
repo1-path=/pgqdata/backup/pgsrvref/pgbackrest
...
`

Then we make a restore on the standby by typing this :
`pgbackrest --stanza=<stanza> --config=/etc/pgbackrest_slave.conf --standby restore`
And the restauration works well. After restauration is done, replication is in place.

But probem arises after, when we want to do a failover. We created a stanza on the newly primary (which was standby). But as you say, we must no create a 2nd stanza.

Are we obliged to change our repository configuration ?

**Comment by pgstef** [comment]
Then, your first server is acting as "repo-host" for the second one. That's very uncommon. If you configure `repo1-host` on your standby, you won't be able to execute the backup command locally there.

If you really don't have any backup storage anywhere (GCS, Azure, S3,...) or even a simple NAS in your network, perhaps you could consider creating a dedicated backup host to act as repo-host and where to store your backups. But we definitely **not** recommend to store backups on the PG hosts!

If you really want to keep your repo storage on your first PG host, then you should probably use NFS export/mount to simplify your configuration and avoid `repo1-host` config.

Following one of those 2 examples should help you keep your configuration settings simpler:
* [repo-host example](https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html)
* [nfs example](https://pgstef.github.io/2020/09/04/combining_pgbackrest_and_streaming_replication.html)

I should also mention that if your repository location isn't reachable, your archiving system will be blocked. Which can lead to disk space issues and PG PANIC/shutdown. Storing it on your first PG host is then a risk to block your second PG host after fail-over if the first server is down for too long.

**Comment by julienc256** [comment]
Yes that's it : the primary is acting as "repot-host" for the standby. But I don't have the possibility to change this configuration. I have not the ability to do that, nor use NFS export/mount.

Even if this is not the ideal configuration, it worked well before using pgbackrest !

Thanks for the links, I am reading these carefully. It helps me to better understand !

**Comment by julienc256** [comment]
Ok I read again https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html and I better understood !

In your example, you have a dedicated repository host « backup-srv » to backup a PostgreSQL 3-nodes cluster.
Having a dedicated repository host is the ideal configuration we should have !

But I was not the one who decided on the architecture, and I have no power to change it.

**Comment by dwsteele** [comment]
> Nevertheless your answers are very constructive, I will try to share them with the people who designed the architecture !

Please do. This is not the correct way to implement a backup repository. The repository should never be on the same machine where the cluster is located. A failure of the primary hardware/disk also means losing all your backups and WAL.
