### ISSUE TITLE
Building pgbackrest rpm package without requiring lz4 dependency

### ISSUE THREAD

**Issue by bioflash** [pgbackrest/pgbackrest#1330]
Is that possible for us to build pgbackrest rpm package without requiring lz4 dependency if we won't use it for compression?
How to do that by ourself?

**Comment by pgstef** [comment]
Hi,

The spec file used by the packaging team is [there](https://git.postgresql.org/gitweb/?p=pgrpms.git;a=tree;f=rpm/redhat/master/common/pgbackrest/master). Issues related to the packages can be addressed on the [redmine](https://redmine.postgresql.org/projects/pgrpms/issues) tracker.

I guess you could remove the lz4 part and then build your own package but I don't really get the interest of that. Package dependencies aren't really heavy or overly complicated imho.

```
  24 %if 0%{?fedora} >= 30 || 0%{?rhel} >= 8
  25 Requires:       lz4-libs libzstd
  26 BuildRequires:  lz4-devel bzip2-devel
  27 %endif
  28 %if 0%{?rhel} && 0%{?rhel} <= 7
  29 Requires:       lz4 libzstd
  30 BuildRequires:  lz4-devel bzip2-devel
  31 %endif
  32 %if 0%{?suse_version} && 0%{?suse_version} <= 1499
  33 Requires:       liblz4-1_7 libzstd1
  34 BuildRequires:  liblz4-devel libbz2-devel
  35 %endif
  36 %if 0%{?suse_version} && 0%{?suse_version} >= 1500
  37 Requires:       liblz4-1 libzstd1
  38 BuildRequires:  liblz4-devel libbz2-devel
  39 %endif
```

**Comment by bioflash** [comment]
Thanks for your info.
