### ISSUE TITLE
getting Error while restoring 

### ISSUE THREAD

**Issue by narendrapostgresdba** [pgbackrest/pgbackrest#1331]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.32

2. PostgreSQL version: 9.6.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  source : RHEL 7.3 target : CENTOS  7.8

4. Did you install pgBackRest from source or from a package?  package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

I am trying to restore postgres from one server to another server . but getting below error 

2021-03-12 01:31:47.059 P00   WARN: contents of directory link 'pg_xlog' will be restored in a directory at the same location
2021-03-12 01:31:47.438 P00  ERROR: [047]: unable to create path '/pgBACKUP': [13] Permission denied
2021-03-12 01:31:47.539 P00   INFO: restore command end: aborted with exception [047]

[global]
repo1-host=source server 
repo1-host-user=postgres
repo1-host-config=/etc/pgbackrest.conf
repo1-path=/pgBACKUP/XYZ
process-max=12
archive-async=y
archive-get-queue-max=104857600

[stanzaname]
pg1-path=/pgDATA/data

on source server , we have backup on /pgBACKUP FS  .on target server we don't  have /pgBACKUP FS exists . data directory and pg_wal directory both exists . 

not able to get what is missing here 

7. Describe the issue:

**Comment by pgstef** [comment]
You'd like to restore backups from **serverA** stored in `/pgBACKUP/XYZ` on **serverB**, but `/pgBACKUP/XYZ` doesn't exist on that server? I don't really see how it could work, you need to reach the backup repo from **serverB**.

How did you plan to reach the backups from **serverB**?

**Comment by pgstef** [comment]
Hm, I just saw the `repo1-host` option. You don't have to specify `repo1-path` if you use a repo host. Removing that option should help.

Your source server will act as **repository** and target server as **pg-primary** in [this](https://pgbackrest.org/user-guide-centos8.html#repo-host/config) example.

I just hope for you that in your source server, your backups doesn't stay locally on the same machine as your PG database ;-)

**Comment by narendrapostgresdba** [comment]
Hi Stefan ,

Our source database backup resides on local FS only .

Regards,
Narendra

**Comment by narendrapostgresdba** [comment]
Hi Stefan,

I just commented repo_path and tried but still got the same error .

#repo1-path=/pgBACKUP/XYZ

2021-03-12 02:52:41.546 P00   WARN: contents of directory link 'pg_xlog'
will be restored in a directory at the same location
2021-03-12 02:52:41.884 P00  ERROR: [047]: unable to create path
'/pgBACKUP': [13] Permission denied
2021-03-12 02:52:41.985 P00   INFO: restore command end: aborted with
exception [047]

not sure why it is trying to create /pgBACKUP

**Comment by pgstef** [comment]
> Our source database backup resides on local FS only

You should then pray to never lose your PG server because you would lose your backups too then...

Anyway, I think we'll need more details on your setup (configuration files from source and target server + commands you're running) because I managed to get something working pretty easily with the following example:

```bash
# serverA
root# cat<<EOC > "/etc/pgbackrest.conf"
[global]
repo1-path=/pgBACKUP/XYZ
repo1-retention-full=1
log-level-console=info
start-fast=y

[stanza]
pg1-path=/var/lib/pgsql/9.6/data
EOC
root# mkdir -p /pgBACKUP/XYZ
root# chown -R postgres: /pgBACKUP/XYZ
root# cat<<EOC >> "/var/lib/pgsql/9.6/data/postgresql.auto.conf"
wal_level = replica
archive_mode = on
archive_command = 'pgbackrest --stanza=stanza archive-push %p'
EOC
root# systemctl restart postgresql-9.6
root# sudo -iu postgres pgbackrest --stanza=stanza stanza-create
root# sudo -iu postgres pgbackrest --stanza=stanza check
root# sudo -iu postgres pgbackrest --stanza=stanza --type=full backup
root# pgbackrest info
stanza: stanza
    status: ok
    cipher: none
    db (current)
        wal archive min/max (9.6): 000000010000000000000005/000000010000000000000005
        full backup: 20210312-095048F
            timestamp start/stop: 2021-03-12 09:50:48 / 2021-03-12 09:51:00
            wal start/stop: 000000010000000000000005 / 000000010000000000000005
            database size: 21MB, database backup size: 21MB
            repo1: backup set size: 2.4MB, backup size: 2.4MB

# serverB
root# sudo -iu postgres ssh serverA echo "working..."
root# cat<<EOC > "/etc/pgbackrest.conf"
[global]
repo1-host=serverA
repo1-host-user=postgres
log-level-console=info

[stanza]
pg1-path=/var/lib/pgsql/9.6/data
EOC
root# sudo -iu postgres pgbackrest info
stanza: stanza
    status: ok
    cipher: none
    db (current)
        wal archive min/max (9.6): 000000010000000000000005/000000010000000000000005
        full backup: 20210312-095048F
            timestamp start/stop: 2021-03-12 09:50:48 / 2021-03-12 09:51:00
            wal start/stop: 000000010000000000000005 / 000000010000000000000005
            database size: 21MB, database backup size: 21MB
            repo1: backup set size: 2.4MB, backup size: 2.4MB
root# systemctl stop postgresql-9.6
root# rm -rf /var/lib/pgsql/9.6/data/*
root# sudo -iu postgres pgbackrest --stanza=stanza restore |grep P00
P00   INFO: restore command begin 2.32: ...
P00   INFO: restore backup set 20210312-095048F
P00   INFO: write /var/lib/pgsql/9.6/data/recovery.conf
P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
P00   INFO: restore command end: completed successfully (8125ms)
root# cat<<EOC >> "/var/lib/pgsql/9.6/data/postgresql.auto.conf"
archive_mode = off
EOC
root# systemctl start postgresql-9.6
```

Don't forget to disable archiving on your restored cluster to avoid it push WAL archives in your production repo.

To understand your issue, as said, I'd need the config of source/target servers + the commands you run. 
You should probably first see if `pgbackrest info` works on the target server, and then add `--log-level-console=debug --log-subprocess` to your restore command to get more details about the error you get.

Kind regards,

**Comment by narendrapostgresdba** [comment]
Hi ,

Here is the config files

target  server

[global]
repo1-host=ABC
repo1-host-user=postgres
repo1-host-config=/etc/pgbackrest.conf
#repo1-path=/pgBACKUP/XYZ
process-max=12
archive-async=y
archive-get-queue-max=104857600

[XYZ]
pg1-path=/pgDATA/data


source  server


[XYZ]
db-path=/pgDATA/data


[global]
process-max=12
repo-path=/pgBACKUP/XYZ
retention-full=1
retention-archive=2
start-fast=y
log-level-file=detail
archive-async=y
db-timeout=3600

[global:archive-push]
process-max=4


Restore command used :

nohup pgbackrest  --stanza=XYZ  --db-path=/pgDATA/data  restore
 --type=time  --target='2021-03-11 11:07:07 EST' --log-level-console=debug
--log-subprocess &

Error details

2021-03-12 05:57:20.394 P00   INFO: restore command begin 2.32:
--exec-id=71970-569426a1 --log-level-console=debug --log-subprocess
--pg1-path=/pgDATA/data --process-max=12 --repo1-host=ABC
 --repo1-host-config=/etc/pgbackrest.conf --repo1-host-user=postgres
--stanza=XYZ --target="2021-03-11 11:07:07 EST" --type=time
2021-03-12 05:57:22.827 P00   WARN: automatic backup set selection cannot
be performed with provided time '2021-03-11 11:07:07 EST', latest backup
set will be used
                                    HINT: time format must be YYYY-MM-DD
HH:MM:SS with optional msec and optional timezone (+/- HH or HHMM or HH:MM)
- if timezone is omitted, local time is assumed (for UTC use +00)
2021-03-12 05:57:49.384 P00   INFO: restore backup set 20210311-060942F
2021-03-12 05:57:49.384 P00   WARN: contents of directory link 'pg_xlog'
will be restored in a directory at the same location
2021-03-12 05:57:49.773 P00  ERROR: [047]: unable to create path
'/pgBACKUP': [13] Permission denied
2021-03-12 05:57:50.202 P00   INFO: restore command end: aborted with
exception [047]

**Comment by pgstef** [comment]
In your source server config: `db-path` -> `pg1-path`, `repo-path` -> `repo1-path`.
You don't need to provide `--db-path=/pgDATA/data` in your restore command either (and that would be `--pg1-path` though).

Regarding the `WARN: contents of directory link 'pg_xlog' will be restored in a directory at the same location` message, by default, symlinked directories and files are restored as normal directories and files in $PGDATA. So, on your source server, `/pgDATA/data/pg_xlog` is a probably a link. What's its target path?

Anyway, at this point, I don't think this will fix your issue. You run the command with `log-level-console=debug` but get the log file content, so we don't have the debug output. So change `--log-level-console` to `--log-level-file=debug` to get more details about the issue.

**Comment by narendrapostgresdba** [comment]
our pg_xlog is targeting to /pgWAL/pg_xlog   -> same path exists at target
as well .

Now in the log file got below info


--------------------
                                    If SUBMITTING AN ISSUE please provide
the following information:

                                    version: 2.32
                                    command: restore
                                    options: --exec-id=87590-15251299
--log-level-file=debug --log-subprocess --pg1-path=/pgDATA/data
--process-max=12 --repo1-host=tparhepgsi003.enterprisenet.org
--repo1-host-config=/etc/pgbackrest.conf --repo1-host-user=postgres
--stanza=tparhepgsi003 --target="2021-03-11 11:07:07 EST" --type=time

                                    stack trace:

storage/posix/storage:storagePosixPathCreate:387:(trace log level required
for parameters)

storage/posix/storage:storagePosixPathCreate:(trace log level required for
parameters)

storage/posix/storage:storagePosixPathCreate:(trace log level required for
parameters)

storage/storage:storagePathCreate:(this: {type: posix, path: {"/"}, write:
true}, pathExp: {"/pgBACKUP/temptbs/PG_9.6_201608131"},
param.errorOnExists: false, param.noParentCreate: false, param.mode: 0700)

command/restore/restore:restoreCleanBuild:(manifest: {Manifest})

command/restore/restore:cmdRestore:(void)
                                    main:main:(debug log level required for
parameters)

--------------------------------------------------------------------
2021-03-12 06:29:18.582 P00   INFO: restore command end: aborted with
exception [047]
2021-03-12 06:29:18.582 P00  DEBUG:     common/lock::lockRelease:
(failOnNoLock: false)
2021-03-12 06:29:18.582 P00  DEBUG:     common/lock::lockRelease: => false
2021-03-12 06:29:18.582 P00  DEBUG:     common/exit::exitSafe: => 47
2021-03-12 06:29:18.582 P00  DEBUG:     main::main: => 47


seems some tablespace present in /pgBACKUP location and it has permission
of 700 . Now i change it 755 . and also the path /pgBACKUP not exists on
target , so I used  --tablespace-map=vuetemp_tbs=/pgDATA/TBS/vuetemp_tbs
 option . Now restore got initiated .

Thanks for your help .

**Comment by pgstef** [comment]
> our pg_xlog is targeting to /pgWAL/pg_xlog

You might need to use the [`--link-all`](https://pgbackrest.org/command.html#command-restore/category-command/option-link-all) in your restore command if you want to keep the symlink on the target server then.

> storage/storage:storagePathCreate:(this: {type: posix, path: {"/"}, write: true}, pathExp: {"/pgBACKUP/temptbs/PG_9.6_201608131"}...
>
> seems some tablespace present in /pgBACKUP location and it has permission of 700.
> Now i change it 755 and also the path /pgBACKUP not exists on target, so I used --tablespace-map=vuetemp_tbs=/pgDATA/TBS/vuetemp_tbs option.
> Now restore got initiated.
> Thanks for your help.

`tablespace-map` or `tablespace-map-all` are indeed the good approach to relocate your tablespaces on the target server. Glad the debug output helped.

Kind regards
