### ISSUE TITLE
Question: HA options for Dedicated Backup admin host

### ISSUE THREAD

**Issue by gowtham500** [pgbackrest/pgbackrest#1333]
## Env info

1. pgBackRest version: 2.31 (Installed from source and running on dedicated backup admin host)

2. PostgreSQL version: 13.2 ( three node cluster)

3. Operating system/version - CentOS 7.7

## Will this work ? 

1. Use a dedicated backup admin host.
2. Configure repo-path to a highly available NFS.
3. Incase the current backup admin host - goes down, mount NFS to new backup admin host.
4. Configure new backup admin host with the same SSH key access and all prerequisites.
5. Update pgbackrest.conf in all nodes to the new backup admin host.
5. Now can the new backup admin host continue to backup data and WAL files to the same NFS ?

## Questions
1. Are we good with this procedure, can you please help in case if I missed any steps? 
2. If this is not a good solution - are there any better solutions?

**Comment by dwsteele** [comment]
This plan looks reasonable to me, but of course you'll need to test it to be sure.
