### ISSUE TITLE
Backup restore fails with "unable to set ownership for"

### ISSUE THREAD

**Issue by sezaru** [pgbackrest/pgbackrest#1335]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.32

2. PostgreSQL version: 13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.04

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

*server file:* 

```
[business_db]
pg1-path=/var/lib/postgresql/13/business_db

[global]
log-level-file=detail
repo1-host=<ip>
```

*backup server file:*

```
[business_db]
pg1-host=<ip>
pg1-host-port=<port>
pg1-host-user=business_db

pg1-port=<ip>
pg1-path=/var/lib/postgresql/13/business_db
pg1-user=business_db

[global]
repo1-path=/var/lib/pgbackrest

repo1-retention-full=1

repo1-cipher-pass=<my_cipher>
repo1-cipher-type=aes-256-cbc

process-max=2

start-fast=y

[global:archive-push]
compress-level=3
```

- `postgresql.conf` settings applicable to pgBackRest:
*archive_command*: 'pgbackrest --stanza=business_db archive-push %p'

7. Describe the issue:

When running a backup restore with command `sudo -u business_db pgbackrest --stanza=business_db restore` I end up receiving the following error message:

```
ERROR: [088]: unable to set ownership for '/var/lib/postgresql/13/business_db/postgresql.auto.conf': [1] Operation not permitted
```

Running the same command with strace, shows me that `pgbackrest` is trying to run `chown` to change ownership of the file to root:

```
chown("/var/lib/postgresql/13/business_db/postgresql.auto.conf", 0, 0) = -1 EPERM (Operation not permitted)
```

I don't understand why `pgbackrest` is trying to chown as root, my database is running as a custom user `business_db` and the file `postgresql.auto.conf` has the following permissions:

```
-rw-------  1 business_db business_db   88 Mar 14 19:32 postgresql.auto.conf
```

More information:

- Postgresql server is running as `business_db` user, not as `root`;
- This is the command I used to create the backup:
```
sudo -u pgbackrest pgbackrest --stanza=business_db --type=full --log-level-console=info backup
```

Any idea why is this happening?

**Comment by sezaru** [comment]
Turns out that the issue was because my Postgres directory is a symlink to another harddrive. Changing the symlink to a mount --bind fixed the issue.

**Comment by dwsteele** [comment]
Was it a symlink on the original system or where you were restoring?

**Comment by sezaru** [comment]
The symlink is on my server where the PostgreSQL instance is running, not on my backup server.

Basically, I have a separate temporary (temporary meaning that I'm using it for now for our product pilot) HD for database storage.

So `/var/lib/postgresql/13/business_db` links to `/mnt/data/business_db`.

Does that answer your question?
