### ISSUE TITLE
Can't restore to a specific LSN

### ISSUE THREAD

**Issue by jcoleman** [pgbackrest/pgbackrest#1339]
We current have `--type=xid` so that you can set an xid as the `--target` for a restore, but the same isn't currently possible for an LSN (though `recovery.conf` does support such).

It'd be pretty sweet to be able to use an lsn :)

(I may at some point be able to get a PR for this, but it'll be at least a few weeks, maybe longer, if so.)

**Comment by dwsteele** [comment]
Yeah, this was definitely an omission on our part when the LSN target was added to PG10.

We have a release coming up pretty soon so you'd have plenty of time to make the next release in June, if nobody beats you to it.

**Comment by dwsteele** [comment]
@pgstef opened a PR for this issue so closing.
