### ISSUE TITLE
Do not sign Content-Length header

### ISSUE THREAD

**Issue by bbockelm** [pgbackrest/pgbackrest#1340]
Overview
---------

When pgBackRest generates a S3 GET request, it includes a `Content-Length:0` header _and_ signs it as part of the S3 backup process.

I don't think the `Content-Length` header is not strictly necessary (doesn't a `GET` always have an empty body?) and this is causing a curious failure for me.

For ... reasons ... my S3 instance sits behind a load-balancing proxy (particularly, Traefik 2.2).  When it sees the `GET` request with a zero-length `Content-Length`, it appears to strip off that particular header.  The S3 backend (Ceph's RGW) sees a signed request requiring `Content-Length` in the signature but not in the request itself; it (correctly!) rejects the request with a 403 due to an incorrect signature.

Example authorization header:

```
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20210321/us-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=<redacted 2>
```

I'm not going to admit how many hour I spent before I figured this out (broke down and write a Python implementation of V4 signature generators to play the game of "spot the difference").

I realize that the setup is esoteric - but I claim not entirely unreasonable.  Given a proxy might rewrite the request in several different ways - including switching to a chunked encoding - can we simply drop this header?  It works with other S3 clients so I'm guessing signing `Content-Length` is relatively uncommon.

Many Thanks!

Details
-------

1. pgBackRest version: 4.6.1

2. PostgreSQL version: 13

3. Operating system/version: Linux

4. Did you install pgBackRest from source or from a package?  Installed via CrunchyData postgres-operator

**Comment by dwsteele** [comment]
> I'm not going to admit how many hour I spent before I figured this out (broke down and write a Python implementation of V4 signature generators to play the game of "spot the difference").

Oh, I can imagine!

> Given a proxy might rewrite the request in several different ways - including switching to a chunked encoding - can we simply drop this header?

Yeah, we are probably over-signing here but there didn't seem to be any harm in it.

I'd need to look into it a bit more, but it seems stripping content-length is going to disable our connection reuse, which will probably impact performance. Unless your proxy thinks that S3 is going to ignore content-length here and not calculate it based on EOF. I guess that's really between you and your proxy.

This would seem to be a pretty simple change -- unless there are unintended consequences.

**Comment by dwsteele** [comment]
We would appreciate it if you could test PR #1341 in your environment. Thanks!
