### ISSUE TITLE
Questions for production dedicated host repository

### ISSUE THREAD

**Issue by enalbert** [pgbackrest/pgbackrest#1344]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.32

2. PostgreSQL version: 9.6.x, 10.x and 12.x

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL7

4. Did you install pgBackRest from source or from a package? package

Questions:
I'm planning deploy pgbackrest in production environment with 30 standalone database clusters and some clusters with replicas.

1.- Using dedicated host repository with 4 cores and 4Gb, it will be able backup these 30 remote postgresql clusters at same time (nightly window)? (or I need more resources).

2.- If I backup the repository of the dedicated server with traditional methods (tape, etc.) and I need to recover the repo from two months ago to be able to restore a currently expired postgres backup of a specific server, what steps should I follow?

Regards

**Comment by pgstef** [comment]
Hi,

1. I guess it will depend on the size of your databases and the exact time you trigger the backup commands. It's hard to predict. There are a lot of parameters to evaluate (I/O speed, network bandwidth,...). Furthermore, it will also depend on the backup type you'll trigger: full, diff, incr,... The only way to make sure is to try imho. 

2. Manifest files are important. I guess you'll need to restore your repo backup (from the tape) and create a new configuration pointing to that old repo image (or use the multi-repo feature but I think it would be safer to use a separate configuration file).

**Comment by enalbert** [comment]
In the previous case of recovering from tape, would it be necessary to recover the entire repo, which would include all the old backups and wals of all the servers? or a selective recovery could be performed to recover only the affected server?

**Comment by pgstef** [comment]
I guess only restoring the stanza directories you want to restore should be enough. Manifest files are the most important. Then only the backup set you wish to restore (if it's a diff/incr, remember to restore also the referenced backup sets).

Regarding the archives, that will depend which point in time you want to recover. If only backup consistency, then you'll need at least the wal archives between "start wal" and "stop wal" location of each backup set.

**Comment by dwsteele** [comment]
Restoring individual stanzas is fine. Just make sure to get the stanza from both the `archive` and `backup` directories.

I wouldn't try to restore parts of the archive -- that adds a lot of complexity and it is easy to get it wrong.
