### ISSUE TITLE
apt-get installs old version

### ISSUE THREAD

**Issue by nrayburn-tech** [pgbackrest/pgbackrest#1345]
1. pgBackRest version:
2.24

2. PostgreSQL version:
N/A

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 20

4. Did you install pgBackRest from source or from a package?
Package. My only apt repositories are the official ubuntu sources.

5. Describe the issue:
`sudo apt-get install pgbackrest` installs 2.24, instead of the expected latest (2.32).  I may have missed something, but I didn't see any requirements to add a custom repository for the install.

**Comment by dwsteele** [comment]
That's the version that comes with 20.04. If you'd like newer versions: https://pgbackrest.org/user-guide.html#build
```
Debian/Ubuntu packages for pgBackRest are available at apt.postgresql.org.
```
Perhaps you didn't see it because it is in the build section. Not sure I want to move it because the idea is to discourage people from building their own binaries. Maybe a link from install would work.

**Comment by nrayburn-tech** [comment]
I think it may just be a misunderstanding on my end then.  These are the various ways to retrieve the project.
- 2.24 comes with the Ubuntu repos.
- I can add the postgresql repo to my apt list, and get newer versions.  (This doesn't require compiling from source.  Right?)
- I can compile from source with the provided directions.

Is that right?

**Comment by dwsteele** [comment]
> 2.24 comes with the Ubuntu repos.

Yes, but this depends on your version of Ubuntu. With 20.10 you would get pgbackrest 2.28.

> I can add the postgresql repo to my apt list, and get newer versions. (This doesn't require compiling from source. Right?)

Correct.

> I can compile from source with the provided directions.

Yes, though this is not recommended if packages are available for your platform.

**Comment by nrayburn-tech** [comment]
Just a misunderstanding on my end then.

I thought that’s how it worked, but having the repos listed under the build section led me to believe it meant I could get it from there, but I would still have to build it myself. Linux is still relatively new to me, so I doubt this is a common misunderstanding.

Thanks for the information. (And the project)
