### ISSUE TITLE
Question: How to do PITR recovery on a DB which is not yet in backup manifest

### ISSUE THREAD

**Issue by gowtham500** [pgbackrest/pgbackrest#1352]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

## Environment
1. pgBackRest version: 2.32
1. PostgreSQL version: 13.2
1. Operating system: CentOS 7
1. Did you install pgBackRest from source or from a package? Downloaded from PG online repo
1. Pgbackrest setup: 3 node async cluster with dedicated backup admin host.

## pgbackrest.conf on each of the nodes.
```
[pgtimescale13]
pg1-path=/app/pgsql/13/data
archive-async=y
log-level-file=detail
spool-path=/app/spool/pgbackrest
repo1-host=dedicated_backup_admin_fqdn
log-path=/app/log/pgbackrest

[global:archive-get]
process-max=2

[global:archive-push]
process-max=2
```

## pgbackrest.conf on dedicated backup admin host

```
[pgtimescale13]
pg1-host=node1_fqdn
pg1-path=/app/pgsql/13/data
pg2-host=node2_fqdn
pg2-path=/app/pgsql/13/data
pg3-host=node3_fqdn
pg3-path=/app/pgsql/13/data

[global]
backup-standby=n
process-max=2
repo1-path=/data/pgbackrest
repo1-retention-full=2
repo1-retention-diff=6
start-fast=y
log-level-file=detail
log-path=/data/log/pgbackrest
```

## PostgreSQL settings
```
archive_command: /bin/pgbackrest --stanza=pgtimescale13 archive-push %p
wal_level: replica
max_wal_senders: 10
archive_mode: on
listen_adddresses: "fqdn"
```

## Scenario

1. We have 3 dbs in PG, pgbackrest is taking full, diff and incr backups succesfully.
2. Wal archive is succesfull.
3. Now I create a 4th DB and create tables in it.
4. Incremental, diff or full backups have not yet kicked in. The next incremental backup will be in 2 hours.
5. Backup manifest - [db] section does not have this 4th DB.
5. The 4th DB has 3 tables. Somebody drops table 3 by mistake.
6. They record the time as 2021-03-30 07:05:32  and ask to do PITR.
7. This time is well ahead of last backup's - backup stop time. (atleast 1 hour ahead)

## Expected Behaviour.

1. Running PITR
`pgbackrest --stanza=pgtimescale13 --delta restore --log-level-console=info --type=time "--target=2021-03-30 07:05:32"  --target-action=promote --process-max=10`

2. Expecting all data to come back as of 2021-03-30 07:05:32

## Actual Behaviour

1. Running PITR
`pgbackrest --stanza=pgtimescale13 --delta restore --log-level-console=info --type=time "--target=2021-03-30 07:05:32"  --target-action=promote --process-max=10`

2. Start Postgres and connect to it.
3. Unable to connect to DB 4 with error "The database subdirectory "base/44729" is missing."

## PITR Recovery Logs
```

2021-03-30 07:08:16.138 UTC [76588] db=,user=,app=,client= LOG:  starting point-in-time recovery to 2021-03-30 07:05:32+00
2021-03-30 07:08:16.750 UTC [76588] db=,user=,app=,client= LOG:  restored log file "00000030.history" from archive
2021-03-30 07:08:17.977 UTC [76588] db=,user=,app=,client= LOG:  restored log file "00000030000000C5000000A9" from archive
2021-03-30 07:08:17.989 UTC [76588] db=,user=,app=,client= LOG:  redo starts at C5/A9000028
2021-03-30 07:08:17.991 UTC [76588] db=,user=,app=,client= LOG:  consistent recovery state reached at C5/A9000100
2021-03-30 07:08:17.993 UTC [76585] db=,user=,app=,client= LOG:  database system is ready to accept read only connections
2021-03-30 07:08:18.009 UTC [76588] db=,user=,app=,client= LOG:  restored log file "00000030000000C5000000AA" from archive
2021-03-30 07:08:18.142 UTC [76588] db=,user=,app=,client= LOG:  restored log file "00000030000000C5000000AB" from archive
2021-03-30 07:08:18.262 UTC [76588] db=,user=,app=,client= LOG:  restored log file "00000030000000C5000000AC" from archive
2021-03-30 07:08:18.286 UTC [76588] db=,user=,app=,client= LOG:  recovery stopping before commit of transaction 966560, time 2021-03-30 07:06:30.153178+00
2021-03-30 07:08:18.286 UTC [76588] db=,user=,app=,client= LOG:  redo done at C5/AC0001E0
2021-03-30 07:08:18.286 UTC [76588] db=,user=,app=,client= LOG:  last completed transaction was at log time 2021-03-30 07:05:17.547864+00
2021-03-30 07:08:18.904 UTC [76588] db=,user=,app=,client= LOG:  selected new timeline ID: 49
2021-03-30 07:08:18.963 UTC [76588] db=,user=,app=,client= LOG:  archive recovery complete
2021-03-30 07:08:19.592 UTC [76588] db=,user=,app=,client= LOG:  restored log file "00000030.history" from archive
2021-03-30 07:08:19.719 UTC [76585] db=,user=,app=,client= LOG:  database system is ready to accept connections
```

## Questions

1. Will we not able to do PITR on a Db which has not  yet come in backup manifest ?
2.  Or is there any other mistake in above procedure - please advise.
3. This issue does not seem to occur if the DB is in the backup manifest

**Comment by pgstef** [comment]
Hi,

I just ran the following test since I don't think not having the db included in the restored backup set would be a problem:

```bash
# Initial situation
$ pgbackrest info --stanza=my_stanza --set=20210330-104933F
stanza: my_stanza
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13): 0000000100000001000000DA/0000000100000001000000DA

        full backup: 20210330-104933F
            timestamp start/stop: 2021-03-30 10:49:33 / 2021-03-30 10:50:59
            wal start/stop: 0000000100000001000000DA / 0000000100000001000000DA
            database size: 4.4GB, database backup size: 4.4GB
            repo1: backup set size: 249.0MB, backup size: 249.0MB
            database list: db1 (16384), db2 (16385), db3 (16386), postgres (13319)

# Create new database and drop table
$ createdb db4
$ /usr/pgsql-13/bin/pgbench -i -s 10 db4
$ psql -Atc "select current_timestamp,current_setting('datestyle'),txid_current();"
2021-03-30 10:54:00.718247+02|ISO, MDY|535
$ psql -d db4 -c "DROP TABLE pgbench_accounts"
DROP TABLE
$ psql -c "SELECT pg_switch_wal();"

# Restore and check recovery settings
root# systemctl stop postgresql-13.service
$ rm -rf /var/lib/pgsql/13/data/*
$ pgbackrest restore --stanza=my_stanza --type=time --target="2021-03-30 10:54:00" --target-action=promote --target-exclusive --no-delta
$  cat /var/lib/pgsql/13/data/postgresql.auto.conf 
restore_command = 'pgbackrest --stanza=my_stanza archive-get %f "%p"'
recovery_target_time = '2021-03-30 10:54:00'
recovery_target_inclusive = 'false'
recovery_target_action = 'promote'

# Start the recovery and check restored data
root# systemctl start postgresql-13.service
$ psql -d db4 -c "SELECT COUNT(*) FROM pgbench_accounts"
  count  
---------
 1000000
(1 row)
```

The database creation should be in the archives and then replayed during recovery. I'm wondering what happened between your backup (which seems to be on the timeline id **30**) and your actual restore (generating new timeline id **49**).
Is your `recovery_target_timeline` defined on `latest`? And do you have other `000000xx.history` in the archives repo?

**Comment by gowtham500** [comment]
HI @pgstef , 

Thanks for the reply, recovery_target_timeline is latest. I will check on the difference in timeline - i think multiple recoveries resulted in this. Will try to retry.

Regarding history in the archives repo - Yes we do have, should we remove them. If so can you please provide an example

**Comment by pgstef** [comment]
Handling timelines is like time traveling in sci-fi movies. Same timestamp appear on different timelines with different state.
Each recovery (or standby promotion) will result on generating a new timeline. It is then impossible for me to tell you what to do with those history files unless I know exactly what those timelines contains. So I wouldn't delete it.

If you're sure that all those timelines (after **30**, which was the current timeline during your backup) have been generated AFTER the table was dropped, I would recommend to follow that 30th timeline for your restore, using `--target-timeline=current` which will set `recovery_target_timeline` and ask PG to follow the same timeline as the restored backup.

If your table is not there, you'll have to try multiple restores, using `--target-timeline=31`, 32,... until you find it.
For the test restores, to avoid to pollute your production backup repository, I would recommend using the `--archive-mode=off` option to avoid your restored cluster to archive history or wal files.

**Comment by gowtham500** [comment]
Hello @pgstef , 

This time started with a new cluster.
1. Took a full backup.
2. Created a 4th DB and a new table in it. Backup set does not contain the 4th DB.
3. Dropped the 4th DB. Noted time before DB drop as 2021-03-30 11:00:47.090953+00
4. Disabled archive_mode.
5. Wiped away the data directory. 

`pgbackrest --stanza=pgtest restore --log-level-console=info --type=time "--target=2021-03-30 11:00:47" --target-action=promote --process-max=10`

```
2021-03-30 11:07:06.138 UTC [29956] db=,user=,app=,client= LOG:  starting point-in-time recovery to 2021-03-30 11:00:47+00
2021-03-30 11:07:06.685 UTC [29974] db=postgres,user=postgres,app=[unknown],client=10.142.208.213 FATAL:  the database system is starting up
2021-03-30 11:07:06.694 UTC [29976] db=postgres,user=postgres,app=[unknown],client=10.142.208.213 FATAL:  the database system is starting up
2021-03-30 11:07:07.633 UTC [29956] db=,user=,app=,client= LOG:  restored log file "000000130000004A000000CD" from archive
2021-03-30 11:07:07.644 UTC [29956] db=,user=,app=,client= LOG:  redo starts at 4A/CD000028
2021-03-30 11:07:07.654 UTC [29956] db=,user=,app=,client= LOG:  restored log file "000000130000004A000000CE" from archive
2021-03-30 11:07:07.660 UTC [29956] db=,user=,app=,client= LOG:  consistent recovery state reached at 4A/CE000088
2021-03-30 11:07:07.661 UTC [29952] db=,user=,app=,client= LOG:  database system is ready to accept read only connections
2021-03-30 11:07:07.669 UTC [29956] db=,user=,app=,client= LOG:  restored log file "000000130000004A000000CF" from archive
2021-03-30 11:07:07.714 UTC [29956] db=,user=,app=,client= LOG:  recovery stopping before commit of transaction 335253, time 2021-03-30 11:01:19.794863+00
2021-03-30 11:07:07.714 UTC [29956] db=,user=,app=,client= LOG:  redo done at 4A/CF001EB8
2021-03-30 11:07:07.714 UTC [29956] db=,user=,app=,client= LOG:  last completed transaction was at log time 2021-03-30 11:00:10.358217+00
2021-03-30 11:07:07.993 UTC [29956] db=,user=,app=,client= LOG:  selected new timeline ID: 20
2021-03-30 11:07:08.104 UTC [29956] db=,user=,app=,client= LOG:  archive recovery complete
```
### Error While connecting to the 4th DB.
DETAIL:  The database subdirectory "base/74577" is missing.

### Questions
1. This time didnt see any timeline or .history files issue.
2. Can you please let me know which step is wrong here.  recovery_target_timeline is latest.

**Comment by gowtham500** [comment]
Hello @pgstef ,

Is not 00000013 in hex, which translates to decimal 19, and the cluster after recovery goes to 20. Is my understanding wrong ?

**Comment by pgstef** [comment]
Hm, you're right indeed, that's hexadecimal. My bad, sorry.
I thought you mentioned having a table dropped. I'll re-try my test case with db created+dropped after the backup.
Did you performed a `pg_switch_wal()` after you dropped your db to make sure everything went into the wal archives? Also, did you created some data inside that dropped db/tables ? (like using pgbench i.e.)

**Comment by gowtham500** [comment]
Hello @pgstef , Yes I did switch wal twice after I dropped the DB. pgbackrest last archive also showed the lastest WAL. 
I didnt use pgbench to create tables. I just did this with simple INSERTs.
\c db_name
CREATE TABLE TEST (a int)
INSERT INTO TEST values(1);
INSERT INTO TEST values(2);

**Comment by pgstef** [comment]
Hm, I just ran another test using your create table and dropped db, but can't get the same error message.

```bash
# Initial situation
$ $ pgbackrest info --stanza=my_stanza --set=20210330-143311F
stanza: my_stanza
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13): 00000001000000000000001C/00000001000000000000001C

        full backup: 20210330-143311F
            timestamp start/stop: 2021-03-30 14:33:11 / 2021-03-30 14:33:34
            wal start/stop: 00000001000000000000001C / 00000001000000000000001C
            database size: 494.8MB, database backup size: 494.8MB
            repo1: backup set size: 30.0MB, backup size: 30.0MB
            database list: db1 (16384), db2 (16385), db3 (16386), postgres (13319)

# Create new database and drop database
$ createdb db_name
$ psql -d db_name -c "CREATE TABLE TEST (a int);"
$ psql -d db_name -c "INSERT INTO TEST values(1);"
$ psql -d db_name -c "INSERT INTO TEST values(2);"
$ psql -c "SELECT pg_switch_wal();"

$ psql -Atc "select current_timestamp,current_setting('datestyle'),txid_current();"
2021-03-30 14:44:12.243104+02|ISO, MDY|526
$ dropdb db_name
$ psql -c "SELECT pg_switch_wal();"

# Restore and check recovery settings
root# systemctl stop postgresql-13.service
$ rm -rf /var/lib/pgsql/13/data/*
$ pgbackrest restore --stanza=my_stanza --type=time --target="2021-03-30 14:44:00" --target-action=promote --target-exclusive --no-delta
$ cat /var/lib/pgsql/13/data/postgresql.auto.conf 
restore_command = 'pgbackrest --stanza=my_stanza archive-get %f "%p"'
recovery_target_time = '2021-03-30 14:44:00'
recovery_target_inclusive = 'false'
recovery_target_action = 'promote'

# Start the recovery and check restored data
root# systemctl start postgresql-13.service
$ psql -d db_name -c "SELECT * FROM TEST;"
 a 
---
 1
 2
(2 rows)
```

The only way to get the error message is to go past the dropdb time:

```bash
$ psql -d db_name -c "SELECT * FROM TEST;"
psql: error: FATAL:  database "db_name" does not exist
DETAIL:  The database subdirectory "base/16453" is missing.
```

If you can explore your wal file, you might be able to find the right transaction id / time and use it in combination with `--target-exclusive`:

```bash
$ pg_waldump 00000001000000000000001E 
...
rmgr: Database    len (rec/tot):     38/    38, tx:        527, lsn: 0/1E0001A8, prev 0/1E000130, desc: DROP dir 1663/16453
rmgr: Transaction len (rec/tot):     66/    66, tx:        527, lsn: 0/1E0001D0, prev 0/1E0001A8, desc: COMMIT 2021-03-30 14:44:32.920267 CEST; inval msgs: catcache 21; sync
...
```

**Comment by gowtham500** [comment]
Hello @pgstef ,

Thanks for quick reply and testing again, I see that you use  --target-exclusive even when the timestamp is before the DB drop, so should this be used likewise or is it difficult to tell and we have to rely on xid for most accurate recovery?

**Comment by dwsteele** [comment]
Just as a note here, `drop database` is not atomic so it is pretty easy (especially when using a timestamp) to get right in the middle of it during recovery. See #1350 for details.
