### ISSUE TITLE
pgBackRest backup results in Segmentation Fault

### ISSUE THREAD

**Issue by avinashvallarapu** [pgbackrest/pgbackrest#1354]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **2.32**

2. PostgreSQL version: **12.1**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Backup running locally on the PG Server. **OS Version : CentOS 7.8**

4. Did you install pgBackRest from source or from a package?
**Package from PGDG**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) : 
[global]
# Path where backups and archive are stored
repo1-path=/archivedir/mypgdb_pgbackrest
# Max processes to use for compress/transfer
process-max=8
# Level for console logging [default=warn]
log-level-console=info
# Level for file logging [default=info]
log-level-file=info
[mypgdb]
pg1-path=/datadir/mypgdb/pgdata
pg1-port=5432

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`) - NA as all these are appropriately set. 
 
       name       |                                           setting                                           
------------------+---------------------------------------------------------------------------------------------
 archive_command  | pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb archive-push %p
 archive_mode     | on
 listen_addresses | *
 max_wal_senders  | 10
 port             | 5432
 wal_level        | logical
(6 rows)
 
    - errors in the postgresql log file before or during the time you experienced the issue :  No errors in Postgres logs.
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    
Backup command used : pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb --log-level-console=debug --log-level-file=debug 
   
[mypgdb-backup_debug.log](https://github.com/pgbackrest/pgbackrest/files/6233156/mypgdb-backup_debug.log)

**7. Describe the issue:**

We have a database with 2000 tenants (1 schema per each tenant) and 2 tablespaces per each schema. When pgBackRest runs against this database of size 491 GB but with 4000 tablespaces, it fails with Segmentation Fault. 

Following is the only entry observed in dmesg. 

[Wed Mar 31 00:30:58 2021] pgbackrest[46482]: segfault at 7f97c5d8c010 ip 00000000004447fa sp 00007ffe43a4eef0 error 4 in pgbackrest[400000+c4000]
[Wed Mar 31 00:46:43 2021] pgbackrest[47511]: segfault at 7fafcad64010 ip 00000000004447fa sp 00007fff7d057f10 error 4 in pgbackrest[400000+c4000]

When we ran it the first time with no debugging, it just printed a message as following : 
Segmentation Fault

So, we then enabled the debug mode and ran the backup twice and attached the messages/log to this issue. We renamed the stanza names and directory locations to avoid exposing our environment info publicly.

**Comment by avinashvallarapu** [comment]
Following are the contents of the directory : 

-  $ ls -alrth
total 300K
drwx------  6 postgres postgres 4.0K Mar  9 03:31 ..
drwx------  2 postgres postgres 4.0K Mar  9 03:57 pg_twophase
drwx------  2 postgres postgres 4.0K Mar  9 03:57 pg_snapshots
drwx------  2 postgres postgres 4.0K Mar  9 03:57 pg_serial
drwx------  4 postgres postgres 4.0K Mar  9 03:57 pg_multixact
drwx------  2 postgres postgres 4.0K Mar  9 03:57 pg_dynshmem
drwx------  2 postgres postgres 4.0K Mar  9 03:57 pg_commit_ts
-rw-------  1 postgres postgres    3 Mar  9 03:57 PG_VERSION
drwx------  2 postgres postgres 4.0K Mar  9 03:57 pg_replslot
lrwxrwxrwx  1 postgres postgres   23 Mar  9 04:00 pg_wal -> /waldir/mypgdb/pg_wal
-rw-------  1 postgres postgres  26K Mar  9 04:05 postgresql.conf.org
-rw-------  1 postgres postgres  27K Mar  9 04:05 postgresql.conf
-rw-------  1 postgres postgres 5.2K Mar  9 04:20 pg_hba.conf
-rw-------  1 postgres postgres 2.4K Mar  9 04:20 pg_ident.conf
-rw-r-----  1 postgres postgres   46 Mar  9 22:46 custom_sql.sql
drwx------  7 postgres postgres 4.0K Mar 10 00:21 base
drwx------  2 postgres postgres 128K Mar 29 12:39 pg_tblspc
drwx------  2 postgres postgres 4.0K Mar 29 14:03 pg_subtrans
drwx------  2 postgres postgres  12K Mar 30 17:56 pg_xact
-rw-------  1 postgres postgres  497 Mar 31 00:00 postgresql.auto.conf
drwx------  2 postgres postgres 4.0K Mar 31 00:01 pg_notify
-rw-------  1 postgres postgres   61 Mar 31 00:01 postmaster.opts
-rw-------  1 postgres postgres   97 Mar 31 00:02 postmaster.pid
drwx------  2 postgres postgres 4.0K Mar 31 00:02 pg_stat
drwx------  2 postgres postgres 4.0K Mar 31 00:02 global
-rw-------  1 postgres postgres   48 Mar 31 07:00 current_logfiles
drwx------ 18 postgres postgres 4.0K Mar 31 07:00 .
drwx------  4 postgres postgres 4.0K Mar 31 20:18 pg_logical
drwx------  2 postgres postgres 4.0K Mar 31 20:37 pg_stat_tmp

Here is the log file that includes the log when backup command was run with catchsegv
[pgbackrest_catchsegv.log](https://github.com/pgbackrest/pgbackrest/files/6239982/pgbackrest_catchsegv.log)

**Comment by dwsteele** [comment]
I don't see anything too unusual in your directory, though `postgresql.conf.org`, `custom_sql.sql`, and `current_logfiles` really shouldn't be there. It's better not to store anything in the PGDATA dir -- it leads to accidents.

Can you run `catchsegv` again with pgBackRest debug symbols installed (there should be a dbg package available from PGDG)? There still not enough information to debug.

**Comment by avinashvallarapu** [comment]
Sure, i understand about postgresql.conf.org, custom_sql.sql. But, current_logfiles is expected by default. 
Will remove those 2 files and check if we can succeed.

**Comment by dwsteele** [comment]
Yes, you are correct about `current_logfiles`. I don't usually use `csv` logging so I forgot about it.

**Comment by avinashvallarapu** [comment]
Removed the 2 files : postgresql.conf.org and custom_sql.sql from the data directory. 
Installed debuginfo.
yum install pgbackrest-debuginfo.x86_64 -y

Attached the log file here. 
[pgbackrest4-debug.log](https://github.com/pgbackrest/pgbackrest/files/6246180/pgbackrest4-debug.log)

**Comment by avinashvallarapu** [comment]
Interesting to see that pgBackRest is successful when all the 2000 schemas and their tablespaces (4000) have been dropped. What we are doing next is - checking if it gets successful with 500 schemas and 1000 tablespaces.

I still suspect that it didn't like pg_tblspc directory in the data directory somehow. 
It contains sub-directories with symlinks to 4000 different directories right !!!

We may want to see while reading or scanning what file or directory is it getting into Segmentation fault, may be. 
Is there some additional code that i could put somewhere to debug this better ? I didn't find much information with debug package, unless i missed something.

**Comment by avinashvallarapu** [comment]
Tested with 500 schemas and 1000 tablespaces, now pgBackRest fails. Just to avoid some doubts around Corruption, pg_dump and pg_basebackup succeeds.

**Comment by avinashvallarapu** [comment]
And finally tested with 100 schemas and 200 tablespaces. pgBackRest works well. 
So, it is i think clear that the number of tablespaces matter for pgBackRest with this test.

**Comment by avinashvallarapu** [comment]
Here is something interesting.

ERROR: [100]: unable to fork: [12] Cannot allocate memory
2021-04-02 07:09:44.371 P00   INFO: backup command end: aborted with exception [100]

=======================
**250 schemas and 500 tablespace**
pgdata - 538 directories, 26755 files
tablespaces - 1270 directories, 154816 files
index - 1276 directories, 177375 files

2021-04-02 05:33:08.250 P00   INFO: full backup size = 87.1GB
2021-04-02 05:33:08.253 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2021-04-02 05:33:09.055 P00   INFO: backup stop archive = 000000010000048100000086, lsn = 481/86742FA0
2021-04-02 05:33:09.066 P00   INFO: check archive for segment(s) 000000010000048100000086:000000010000048100000086
2021-04-02 05:33:17.691 P00   INFO: new backup label = 20210402-051441F
2021-04-02 05:33:28.989 P00   INFO: backup command end: completed successfully (1127979ms)
2021-04-02 05:33:28.989 P00   INFO: expire command begin 2.32: --config=/etc/pgbackrest/mypgdb-primary.conf --exec-id=50675-7f445298 --log-level-console=info --log-level-file=info --repo1-path=/archivedir/mypgdb_pgbackrest --stanza=mypgdb
2021-04-02 05:33:29.000 P00   INFO: option 'repo1-retention-archive' is not set - archive logs will not be expired
2021-04-02 05:33:29.000 P00   INFO: expire command end: completed successfully (11ms)

=================
**350 schemas and 700 tablespaces**
pgdata - 738 directories, 36657 files
tablespaces - 1570 directories, 215016 files
index - 1576 directories, 246875 files

2021-04-02 06:25:11.405 P00   INFO: full backup size = 91.4GB
2021-04-02 06:25:11.409 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2021-04-02 06:25:11.711 P00   INFO: backup stop archive = 000000010000048300000053, lsn = 483/53B55188
2021-04-02 06:25:11.722 P00   INFO: check archive for segment(s) 000000010000048300000053:000000010000048300000053
2021-04-02 06:25:24.427 P00   INFO: new backup label = 20210402-055847F
2021-04-02 06:25:40.791 P00   INFO: backup command end: completed successfully (1614123ms)
2021-04-02 06:25:40.792 P00   INFO: expire command begin 2.32: --config=/etc/pgbackrest/mypgdb-primary.conf --exec-id=57356-a008157f --log-level-console=info --log-level-file=info --repo1-path=/archivedir/mypgdb_pgbackrest --stanza=mypgdb
2021-04-02 06:25:40.808 P00   INFO: option 'repo1-retention-archive' is not set - archive logs will not be expired
2021-04-02 06:25:40.808 P00   INFO: expire command end: completed successfully (17ms)
=======================
450 instances
pgdata - 938 directories, 46555 files
tablespaces - 1870 directories, 275216 files
index - 1876 directories, 316375 files
=== Run 1===
bash-4.2$ catchsegv pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb --type=full backup
2021-04-02 06:51:21.611 P00   INFO: backup command begin 2.32: --config=/etc/pgbackrest/mypgdb-primary.conf --exec-id=64732-76873841 --log-level-console=info --log-level-file=info --pg1-path=/datadir/mypgdb/pgdata --pg1-port=5432 --process-max=8 --repo1-path=/archivedir/mypgdb_pgbackrest --stanza=mypgdb --type=full
WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space
      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
2021-04-02 06:51:22.320 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the next regular checkpoint completes
2021-04-02 06:51:37.237 P00   INFO: backup start archive = 000000010000048500000022, lsn = 485/22146240
ERROR: [100]: unable to fork: [12] Cannot allocate memory
2021-04-02 06:59:27.357 P00   INFO: backup command end: aborted with exception [100]
bash-4.2$
=== Run 2 ===


$ catchsegv pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb --type=full backup
2021-04-02 07:01:27.775 P00   INFO: backup command begin 2.32: --config=/etc/pgbackrest/mypgdb-primary.conf --exec-id=65417-82c312bc --log-level-console=info --log-level-file=info --pg1-path=/datadir/mypgdb/pgdata --pg1-port=5432 --process-max=8 --repo1-path=/archivedir/mypgdb_pgbackrest --stanza=mypgdb --type=full
WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space
      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
2021-04-02 07:01:28.484 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the next regular checkpoint completes
2021-04-02 07:01:37.897 P00   INFO: backup start archive = 000000010000048500000024, lsn = 485/24000028
WARN: resumable backup 20210402-065122F of same type exists -- remove invalid files and resume
ERROR: [100]: unable to fork: [12] Cannot allocate memory
2021-04-02 07:09:44.371 P00   INFO: backup command end: aborted with exception [100]
=======================

**Comment by dwsteele** [comment]
> It contains sub-directories with symlinks to 4000 different directories right !!!

Hmmm -- the tablespaces are outside of $PGDATA right? There should only be links in pg_tblspc, not subdirectories. Can you provide a listing (`ls -lah`) of the pg_tblspc directory?

**Comment by dwsteele** [comment]
> I didn't find much information with debug package, unless i missed something.

Not sure why that didn't give more info. I realized that to see the next level of recursion you'll need to bump the log level to `trace`. Then I think we'll see that it blows up when reading `pg_tblspc`.

I think at this point we have enough info to try to reproduce this in a test env. Even if it turns out that there is something here we don't support (like tablespaces inside PGDATA) there definitely should not be a segfault.

**Comment by avinashvallarapu** [comment]
Just to help reproducing the same issue, we have created 2 scripts with instructions, that is being attached here. 
[Test_Case_reproduce.zip](https://github.com/pgbackrest/pgbackrest/files/6251719/Test_Case_reproduce.zip)

# Pre-requisite before running the script.

mkdir -p /bkup/datatblspc
mkdir -p /bkup/indextblspc
chown -R postgres:postgres /bkup/datatblspc
chmod 700 -R /bkup/datatblspc
chown -R postgres:postgres /bkup/indextblspc
chmod 700 -R /bkup/indextblspc

# Script 1 : generate_schemas.sh
This script would create 500 schemas with 300 empty tables in each schema. It also creates 2 tablespaces for each schema, one for data and another for index. Tables are created in schema specific data tablespace and Indexes are created in schema specific index tablespace.

We can then reproduce the same issue by running the following commands. 

yum install pgbackrest -y
mkdir -p /etc/pgbackrest
mkdir -p /archivedir/mypgdb_pgbackrest
chown -R postgres:postgres /archivedir/mypgdb_pgbackrest
chmod -R 700 /archivedir/mypgdb_pgbackrest

**vi /etc/pgbackrest/mypgdb-primary.conf**
[global]
repo1-path=/archivedir/mypgdb_pgbackrest
process-max=4
log-level-console=info
log-level-file=info
[mypgdb]
pg1-path=/var/lib/pgsql/12/data
pg1-port=5432

## Set archive_command
archive_command = 'pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb archive-push %p'

## Create Stanza and run pgBackRest
pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb stanza-create
pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb check
pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb info
pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb backup --type=full
catchsegv pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb backup --type=full --log-level-console=debug --log-level-file=debug

## Following error is visible in the test.
b/pgsql/12/data"}, write: false}, pathExp: {"/var/lib/pgsql/12/data"}, callback: (function *), callbackData: *void, param.level: 0, param.errorOnMissing: true, param.sortOrder: 1, param.expression: null, param.recurse: false)
2021-04-03 01:13:11.842 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)
ERROR: [094]: unable to reallocate 536870912 bytes
2021-04-03 01:13:11.902 P00   INFO: backup command end: aborted with exception [094]

# Script 2 : delete_test_data.sh
This script would help in the cleanup of all the schemas and tablespaces created by the previous script.

**Comment by dwsteele** [comment]
See PR #1356 for a fix. Please try it out.

The issue was that the code that checks for invalid links was not very efficient since typically < 20 or so tablespaces are present, even on very large clusters. It is unlikely that having 4000 tablespaces is a good idea. Tablespaces only improve performance when they are located on separate storage devices. Otherwise they are just a maintenance hassle.

**Comment by avinashvallarapu** [comment]
Agreed David. I would hate to recommend such a design too. But, this is indeed a different requirement for a directory level  encryption in a multi-tenant database. Was unavoidable. Will surely test this and let you know.

**Comment by dwsteele** [comment]
Ah, I see. I had a feeling there was some unusual requirement under all of this.

**Comment by avinashvallarapu** [comment]
Thank You so much for your prompt response. The patch worked well. Any thoughts around when this patch will be applied to the official build ? 

Performed backup and recovery test with 1000 schemas and 2000 tablespaces after applying this patch using the following steps.

```
yum install -y git make gcc postgresql12-devel openssl-devel libxml2-devel lz4-devel libzstd-devel bzip2-devel
mkdir -p /repos && cd /repos
git clone https://github.com/pgbackrest/pgbackrest.git
cd /repos/pgbackrest
git checkout dev-tsbug
git pull
cd /repos/pgbackrest/src/
PG_CONFIG=/usr/pgsql-12/bin/pg_config ./configure CPPFLAGS=-I/usr/pgsql-12/include LDFLAGS=-L/usr/pgsql-12/lib
make
cp pgbackrest /usr/bin/
src]# pgbackrest version
pgBackRest 2.34dev

```
**Backup test**
```
$ time pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb backup --type=full
real	23m8.086s
user	4m14.155s
sys	10m15.789s

```
**Restore test**

```
pg_ctl -D /var/lib/pgsql/12/data stop -mf
rm -rf /bkup/datatblspc/*
rm -rf /bkup/indextblspc/*
rm -rf /var/lib/pgsql/12/data/*

$ pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb info
        full backup: 20210407-223143F
            timestamp start/stop: 2021-04-07 22:31:43 / 2021-04-07 22:54:21
            wal start/stop: 000000010000000000000099 / 000000010000000000000099
            database size: 3.4GB, database backup size: 3.4GB
            repo1: backup set size: 146.5MB, backup size: 146.5MB

$ ls -alrth /archivedir/mypgdb_pgbackrest/backup/mypgdb/20210407-223143F/backup.manifest
-rw-r-----. 1 postgres postgres 72M Apr  7 22:54 /archivedir/mypgdb_pgbackrest/backup/mypgdb/20210407-223143F/backup.manifest
            
$ time pgbackrest --config=/etc/pgbackrest/mypgdb-primary.conf --stanza=mypgdb --set=20210407-223143F --link-all restore
...
...
2021-04-07 23:31:57.564 P00   INFO: restore command end: completed successfully (1547524ms)
real	25m47.688s
user	14m24.370s
sys	8m7.253s

```
Restore completed successfully as also validated with manual verification.

**Comment by dwsteele** [comment]
> The patch worked well. Any thoughts around when this patch will be applied to the official build?

It needs to be reviewed but should probably be in master sometime next week. If you mean in a release, the next release is scheduled for June 7.
