### ISSUE TITLE
problems with backup

### ISSUE THREAD

**Issue by avosluck** [pgbackrest/pgbackrest#1362]
when I try to set up a backup on pgBackRest 2.32, I get this error

sudo -u pgbackrest pgbackrest --stanza=main check
ERROR: [082]: WAL segment 000000010000000000000007 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.

my config on repo :
[main]
pg1-host=172.16.0.11
pg1-path=/var/lib/postgresql/13/main

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y

config on postgres node:
[global]
log-level-file=detail
log-path=/var/log/pgbackrest
repo1-type=posix
repo1-host=172.16.0.1
repo1-host-user=postgres

[main]
pg1-path=/var/lib/postgresql/13/main
process-max=2
recovery-option=recovery_target_action=promote

archive_command = 'pgbackrest --stanza=main archive-push %p'

**Comment by pgstef** [comment]
Hi,

At first look, I don't see any specific error in your configurations (even if you could remove the repo1-type from your db host config).

However, a lot of things could not work (ssh connection between hosts, PG archiver process..).

The error message asks you to check PostgreSQL logs to get a more detailed explanation on why the archiving system is failing. Could you check that? And list PG processes to make sure the archiver is running?

**Comment by avosluck** [comment]
> Hi,
> 
> At first look, I don't see any specific error in your configurations (even if you could remove the repo1-type from your db host config).
> 
> However, a lot of things could not work (ssh connection between hosts, PG archiver process..).
> 
> The error message asks you to check PostgreSQL logs to get a more detailed explanation on why the archiving system is failing. Could you check that? And list PG processes to make sure the archiver is running?

dealt with the problem, there was a problem in access.
But the question arose, before restoring from a backup, do you need to turn off the entire patroni cluster or master node? how to properly recover from a backup if I have a patroni cluster

**Comment by dwsteele** [comment]
> how to properly recover from a backup if I have a patroni cluster

You will want to check the Patroni docs for that.
