### ISSUE TITLE
Backup fails with 'unable to write to remote-0 process on '<host>' write: [32] Broken pipe'

### ISSUE THREAD

**Issue by MannerMan** [pgbackrest/pgbackrest#1367]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 3.32

2. PostgreSQL version: 13.2

3. Operating system/version: CentOS 8 x64

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
* `pgbackrest.conf` file(s)

```
[dev-pg-f3c014]
pg1-path=/var/lib/pgsql/13/data
pg2-host=dev-pg-f3c014-db001.sto3.dev.int
pg2-path=/var/lib/pgsql/13/data

[global]
process-max=8
repo1-path=/
repo1-retention-full-type=time
repo1-retention-full=14
repo1-cipher-type=none
repo1-s3-bucket=dev-pgbackrest
repo1-s3-endpoint=seaweed-backup001-vip.sto4.dev.int
repo1-s3-key=dev-pgbackrest
repo1-s3-key-secret=<redacted>
repo1-s3-uri-style=path
repo1-s3-region=us-east-1
repo1-type=s3
start-fast=y
backup-standby=y
archive-async=n
archive-timeout=300
spool-path=/var/spool/pgbackrest
checksum-page=y
expire-auto=n
protocol-timeout=3600
log-subprocess=n
compress-type=zst
compress-level=4
buffer-size=1MB
log-level-console=warn
log-level-file=debug

[global:archive-push]
process-max=2
compress-level=3
log-level-file=info

[global:archive-get]
process-max=4
log-level-file=info
```

* `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

(from the primary server; db001)
```
archive_command = '/usr/bin/pgbackrest --stanza=dev-pg-f3c014 archive-push %p'
archive_mode = on
listen_addresses = '*'
max_wal_senders = 10
wal_level = logical
port = 5432
```

* errors in the postgresql log file before or during the time you experienced the issue
No errors logged in postgresql

* log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
Complete backup log: (log-level: debug)
[dev-pg-f3c014-backup.zip](https://github.com/pgbackrest/pgbackrest/files/6302434/dev-pg-f3c014-backup.zip)

7. Describe the issue:

We're running pgbackrest on 15 postgres v13.2 clusters, each cluster with one primary and two replicas. We run our backups from one of the replicas (db002). We have the fun postgres setup from #1149, i.e. we have a few million files in our pgdata directory. Our backups have been running for a while now on these clusters, but intermittently we get backup failures with the error below:
```
2021-04-12 12:39:07.492 P00  ERROR: [064]: unable to write to remote-0 process on 'dev-pg-f3c014-db001.sto3.dev.int' write: [32] Broken pipe
                                    --------------------------------------------------------------------
                                    If SUBMITTING AN ISSUE please provide the following information:
                                    
                                    version: 2.32
                                    command: backup
                                    options: --archive-timeout=300 --backup-standby --buffer-size=1048576 --checksum-page --compress-level=4 -
-compress-type=zst --exec-id=2491169-8c962384 --no-expire-auto --log-level-console=warn --log-level-file=debug --no-log-subprocess --pg2-host=
dev-pg-f3c014-db001.sto3.dev.int --pg1-path=/var/lib/pgsql/13/data --pg2-path=/var/lib/pgsql/13/data --process-max=8 --protocol-timeout=3600 -
-repo1-cipher-type=none --repo1-path=/ --repo1-retention-full=14 --repo1-retention-full-type=time --repo1-s3-bucket=dev-pgbackrest --repo1-s3-
endpoint=seaweed-backup001-vip.sto4.dev.int --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --repo1-s3-
uri-style=path --repo1-type=s3 --stanza=dev-pg-f3c014 --start-fast --type=full
                                    
                                    stack trace:
                                    common/io/fdWrite:ioFdWrite:83:(trace log level required for parameters)
                                    common/io/write:ioWriteFlush:(trace log level required for parameters)
                                    common/exec:execWrite:(trace log level required for parameters)
                                    common/io/write:ioWriteFlush:(trace log level required for parameters)
                                    protocol/client:protocolClientWriteCommand:(trace log level required for parameters)
                                    protocol/client:protocolClientExecute:(trace log level required for parameters)
                                    db/db:dbFreeResource:(trace log level required for parameters)
                                    main:main:(debug log level required for parameters)
                                    --------------------------------------------------------------------
2021-04-12 12:39:07.492 P00   WARN: unable to write to remote-0 process on 'dev-pg-f3c014-db001.sto3.dev.int' write: [32] Broken pipe
2021-04-12 12:44:29.536 P00 DETAIL: statistics: {"http.client":{"total":2},"http.request":{"total":195115},"http.session":{"total":2},"socket.
client":{"total":2},"socket.retry":{"total":1},"socket.session":{"total":2},"tls.client":{"total":2},"tls.session":{"total":2}}
2021-04-12 12:44:29.536 P00   INFO: backup command end: aborted with exception [064]
2021-04-12 12:44:29.536 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)
2021-04-12 12:44:29.537 P00  DEBUG:     common/lock::lockRelease: => true
2021-04-12 12:44:29.537 P00  DEBUG:     common/exit::exitSafe: => 64
2021-04-12 12:44:29.537 P00  DEBUG:     main::main: => 64
```
Some clusters get the error at every backup, and some get it more intermittently. From the error above, it appears as if the connection to the primary server (db001) is dropped and the backup therefore fails. I know pgbackrest fetches a few files from the primary as it's doing the backup. Due to the high amount of files our backups can take quite a while to complete (~4 hours for full backup). I guess that could be related, although sometimes the backups fail quite fast as well.
Not sure how to troubleshoot this issue, any direction would be appreciated.  We run CIS-level hardening on our hosts so it could be some issue with lowered SSH timeouts, but I need to find out which such setting we should tune in that case, or if we can configure something in pgbackrest that might help. I have tried increasing `protocol-timeout` to `3600` but that did not solve the issue.

Please let me know if I can provide any further information that might help.

**Comment by dwsteele** [comment]
It definitely looks like the connection is timing out while the resumable backup is being cleaned up. There are two things going on here:

1) Files in resume are not being deleted in batch, which for S3 is pretty slow.
2) Our protocol keep-alives are not being performed in resume so the connection is more likely to die if local timeouts are agressive.

One thing you could try for now is to disable resume (--no-resume) which is of dubious value on S3 anyway since it requires reading the files back from S3. `--no-resume` does a batch delete so it should be a lot faster.

**Comment by MannerMan** [comment]
@dwsteele Ah, I see - thanks for the tip! I have disabled the resume feature in pgbackrest config (`resume=n`) and should have some results within a day or two!

**Comment by MannerMan** [comment]
@dwsteele Setting `resume=n` did indeed fix the issue! Thanks a lot! 
It would have been helpful if pgbackrest did a little bit more logging for these types of operations I think. We also ran into an issue previously with expiration that is performed after backup is complete (very silent in logs here as well) that take a long time to complete for us, which were causing backup timeouts. Took a while to find; we now run expiry as a separate job on another day which works well.

**Comment by MannerMan** [comment]
Would you like to keep this issue around for any improvements regarding improvements for protocol keep-alives or similar? If not, this issue can be closed. Thanks again!

**Comment by MannerMan** [comment]
@dwsteele 

We appear to have run into this issue again on some servers, even though we have disabled resumable backup (`resume=n` in pgbackrest.conf)

```
-------------------PROCESS START-------------------
2021-06-10 07:22:08.279 P00   WARN: backup '20210606-121542F' cannot be resumed: partially deleted by prior resume or invalid
2021-06-10 07:46:03.176 P00  ERROR: [064]: unable to write to remote-0 process on 'prod-pg-f3c172-db001.prod.int' write: [32] Broken pipe
2021-06-10 07:46:03.177 P00   WARN: unable to write to remote-0 process on 'prod-pg-f3c172-db001.sto3.prod.int' write: [32] Broken pipe
```

**Comment by dwsteele** [comment]
Could be the delete is still taking too long in some cases. Even in batch mode only 1000 (S3 restriction) can be deleted at a time, so there might be thousands of batches to be processed.

But since this is only 25 minutes later it makes me wonder if something else is dropping the connection, unless you have set protocol-timeout lower than 3600 again.

**Comment by dwsteele** [comment]
`expire` will remove any resumable backups, so running that before your backups should help.

The fact that the connection is dying with a broken pipe rather than a timeout message from the remote makes me think that there is something on your system dropping the connection due to idleness. We're still looking at how we can send keep alives during this operation, but protocol timeout is being rendered more or less useless it seems.

**Comment by MannerMan** [comment]
@dwsteele Thank you, we have been troubleshooting our backups for some weeks now and found [a performance issue](https://github.com/chrislusf/seaweedfs/issues/2145) in our S3 storage. This was resolved, and by running a manual `expire` as suggested before doing another backup run (that could succeed now that our S3 was performing well) made backups succeed. 
Unsure if the S3 performance issue we had was the original cause of the broken pipe error, since that issue is now resolved and we cleaned up the remaining failed backups using `expire`. I'll leave it up to you if you want to close this issue or keep it around as an improvement for the mentioned keepalived problem.

Thanks for helping!

**Comment by dwsteele** [comment]
Thanks for the update! I have added cards https://github.com/pgbackrest/pgbackrest/projects/2#card-64552446 and https://github.com/pgbackrest/pgbackrest/projects/2#card-64552551 for the updates we would like to do, so we can close this issue now.
