### ISSUE TITLE
pgbackrest with standby configuration

### ISSUE THREAD

**Issue by aogb** [pgbackrest/pgbackrest#1370]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.33
2. PostgreSQL version:
12.6
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: I do have all the servers mentioned with same same OS/version on all.
RHEL 7.8

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
   repository host server
 [demo]
pg1-host=pgdb
pg1-path=/pgdata1/postgres/data

[global]
repo1-path=/u01/pgbackrest
repo1-retention-full-type=time
repo1-retention-full=3
start-fast=y

database server
[demo]
pg1-path=/pgdata1/postgres/data

[global]
log-level-file=detail
repo1-host=backup-repo

standby server
None
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    
listen_addresses = '*'
max_wal_senders = 10
wal_keep_segments = 100
max_replication_slots = 10
wal_level = 'replica'
hot_standby = on
archive_mode = on
archive_command = 'pgbackrest --stanza=demo archive-push %p'
shared_preload_libraries = 'repmgr,pg_stat_statements'

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I have setup pgbackrest on my backup server and my primary database with cronjob to backup from my primary database but my standby is left out.

I am confused here on how integrate my standby here. How does my standby comes in to picture?
For example, if my primary is unable and i have switchover to standby, how would the pgbackrest be used? Do i have to create a separate stanza for standby? these are my doubt and concerns. Please assist and guide.

**Comment by pgstef** [comment]
Hi,

I agree it's not very clean in the user-guides. However, you can find the info in the [configuration reference](https://pgbackrest.org/configuration.html#section-stanza):

```
Indexing: All pg- options are indexed to allow for configuring multiple PostgreSQL hosts. For example, a single primary is configured with the pg1-path, pg1-port, etc. options. If a standby is configured then index the pg- options on the repository host as pg2- (e.g. pg2-host, pg2-path, etc).
```

So, the idea is to add all your PG nodes (primary and replicas) inside the same stanza section. If you define both servers in the stanza section, the backup command will search in the list the primary and take the backup from that node.

Perhaps [this](https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html) example would help you see it a bit more clearly.

Kind regards

**Comment by julienc256** [comment]
Hi,
I allow myself a question here, because it is related to the subject :
I have two postgresql servers on the same machine.
So I intend to create two stanzas.
But in the pgbackrest.conf file, what is the correct content :

Content 1 :
[stanza**1**]
repo-path=...
log-path=...
pg-path=...

[stanza**2**]
repo-path=...
log-path=...
pg-path=...

Or

Content 2 :
[stanza**1**]
repo**1**-path=...
log**1**-path=...
pg**1**-path=...

[stanza**2**]
repo**2**-path=...
log**2**-path=...
pg**2**-path=...

**Comment by pgstef** [comment]
@julienc256: it depends. Are those 2 PG clusters linked together or not?

`pg1*`, `pg2*`,... inside the same stanza section is for linked PG clusters (primary/standbys).
**[stanza1]** and **[stanza2]** with `pg1*` inside of each stanza section is for unrelated PG clusters (2 primary's).

`repo*` options are usually inside the **[global]** section and would be there to specify 1 or more repositories to store all your stanzas. Basically speaking, the multi repo feature allow to have copies of backups and WAL archives in separate locations to increase redundancy (more info about the multi repo feature can be found in [this](https://blog.crunchydata.com/blog/introducing-pgbackrest-multiple-repository-support) nice blog post).

**Comment by julienc256** [comment]
Thanks !

Those 2 PG clusters are not linked together.

**Comment by dwsteele** [comment]
If you put the repo options inside the stanza you will need to monitor them separately. In other words, you can't just run `info` and get info about both stanzas. You'd need to run `info --stanza=stanza1` and `info --stanza=stanza2` separately.

**Comment by aogb** [comment]
"If you define both servers in the stanza section, the backup command will search in the list the primary and take the backup from that node" - 
the backup command must always backup from the primary PG node?

**Comment by pgstef** [comment]
> the backup command must always backup from the primary PG node?

Unless you specify the [backup-standby=y](https://pgbackrest.org/configuration.html#section-backup/option-backup-standby) option, yes. And even in that case, the primary server has to be reachable because pgBackRest uses a hybrid technique that uses both the primary and standby to make the backup:
- backup is started on the primary
- backup start when replay location on standby reaches start backup location
- data replicated files are copied from the standby

**Comment by aogb** [comment]
Looking at the techniques involved, backing up from the primary would be advisable?

**Comment by pgstef** [comment]
Nope. That's the point of that technique. If you want to reduce load on your primary, backup from standby is fine. The all point of that technique is to make sure that you will backup actual data, not old data from an "out of sync" or "delayed" standby.

**Comment by aogb** [comment]
Thank you for the quick response.
I am used to backing up from the primary never tried from standby - does it behave the same way? In the sense that if I backup from the standby would the wal files from primary be automatically archived as that would keep growing if not?

**Comment by pgstef** [comment]
The archiving system won't change since it relies on PG `archive_command`, usually running on the primary indeed (using `archive_mode=on`). Only the replicated data files will then come from the standby server.

**Comment by aogb** [comment]
Sorry I didn't get the statement.
Does that mean the wal files in primary would keep growing if backups are initiated from the standby?

**Comment by pgstef** [comment]
Wal archives come from PG itself, using `pgbackrest archive-push ..` to send archives to the repo. So at the end, no matter if you take backups from primary or standby, everything should end in the same repo (depending of your config and if using multi-repo feature or not ofc).
Then comes the `expire` command. Once triggered, it will clean archives and backups according to your retention settings.

**Comment by aogb** [comment]
I will set it up and test . Thank you.
And lastly, you shared this link with me "https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html"

[global]
repo1-host=backup-srv
repo1-host-user=pgbackrest
log-level-console=info
log-level-file=debug

[mycluster]
pg1-path=/var/lib/pgsql/13/data
recovery-option=primary_conninfo=host=pg1-srv user=replic_user

In my own case, I am using repmgr for my replication can i replace "replic_user" with "repmgr" in my config?

**Comment by pgstef** [comment]
I don't use repmgr, so I can't be sure. If you use repmgr for creating /refreshing your standbys, you won't need that `recovery-option`. I assume it will use pg_basebackup for that purpose though, which only works on empty directories.

So, or you rely on repmgr and don't need that `recovery-option`. However, this `primary_conninfo` is your actual PG setting so you can adjust it with what you need for your case.
