### ISSUE TITLE
is external pgbackrest needed in Patroni HA

### ISSUE THREAD

**Issue by czterocyty** [pgbackrest/pgbackrest#1376]
I wanted to integrate together Patroni and pgBackRest.

I have 3-node Patroni cluster with one master and two streaming replicas. Each host has access to same backup location on NAS mounted in Linux using NFS, `/backup/pgbackrest`.

I doubt if external pgRestBack host is really needed in such setup. On each host I installed pgBestRack and created stanza with the same name. Each pgbackrest.conf has the same repository path. Isn't it that that repo path is a kind of state for all nodes in the cluster?

```
[prod]
pg1-path=/data/postgresql/data

[global]
repo1-path=/backup/pgbackrest

[global:archive-push]
compress-level=3
```

I setup full backup command using cron on each host but added a test if host is a Patroni master and only then invoke `pgbackrest --stanza=prod backup`.

The `archive_command` is `pgbackrest --stanza=prod archive-push %p` on each host, but as slaves are streaming replication, archive_command is not invoked over there. Only if switchover did happen.

Versions
* Timescale 1.7.5, PostgreSQL 12.6
* Patroni 2.0.2
* pgBackRest 2.33 built from sources
* everything contained in a docker container

Summary of my questions
1. Do I really need to have dedicated pgbackrest host?
1. Is pgBackRest really a daemon, cause I didn't found any information about that?

**Comment by pgstef** [comment]
Hi,

No, you don't need a repository host in that setup since the repository is directly attached to the db hosts. So your setup should work. `stanza-create` should just be used once to initiate the repository content (sub-directories and manifests).

PG will indeed trigger the `archive_command` and the cron will trigger backups.

What do you mean by **daemon** ?

**Comment by czterocyty** [comment]
Thanks, @pgstef 
By daemon I was referring to Starting and Stopping commands. It gets more clear to me now that it's more of some state inside repository that prevents some next pgbackrest commands from running.

**Comment by pgstef** [comment]
Well, it's up to the user to run the pgbackrest commands (manually, or via `archive_command` or cron,...). So no, the commands won't be triggered by any pgbackrest background worker.
And indeed, there's some sort of protection using locks (stored in [lock-path](https://pgbackrest.org/configuration.html#section-general/option-lock-path)).
