### ISSUE TITLE
wal archive timeout with s3 repo

### ISSUE THREAD

**Issue by allus** [pgbackrest/pgbackrest#1380]
1. pgBackRest version:
2.33
2. PostgreSQL version:
13.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
redhat
4. Did you install pgBackRest from source or from a package?
source

6. Describe the issue:
when execute backup command or check command, it failed. 
`ERROR: [082]: WAL segment 00000000100000000000000043 was not archived before the 600000ms timeout`
it failed because storageList always return nothing
`DEBUG: /src/storage/storage::storageList: =>{[]}` 
but all wal file had been upload to my bucket, file 00000000100000000000000043 as well.

my configure looks like:
`repo1-s3-bucket=demo
repo1-s3-endpoint=30.102.74.14:8088
repo1-s3-key=sdhhowjeojoigih
repo1-s3-secret=123
repo1-type=s3
repo1-s3-region=default
repo1-s3-verify-tls=n
repo1-path=/demo
repo1-s3-ca-file=/home/dev/public.crt
repo1-storage-host=30.102.74.14
repo1-storage-port=8088
repo1-s3-uri-style=host
`

**Comment by dwsteele** [comment]
See the FAQ: https://pgbackrest.org/faq.html#timeout

**Comment by allus** [comment]
> See the FAQ: https://pgbackrest.org/faq.html#timeout

Thank you, but I can't find the answer in the FAQ, my  WAL has been archived, writting or reading files from bucket works fine. The problem is that storageList function can't return the file list. The http reponse  is ListAllMyBucketsResult, not the ListBucketResult.
I try minio and ceph rgw, same problem. 
"aws s3 ls" command works with minio. I not sure my pgbackrest s3 configure is correct or not.

**Comment by dwsteele** [comment]
You probably need path-style URIs, which is not the default. See https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-uri-style.

**Comment by allus** [comment]
> You probably need path-style URIs, which is not the default. See https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-uri-style.

You are right. thanks again.

**Comment by dwsteele** [comment]
Glad it's working! Sorry I jumped the gun on that one -- we see this error very frequently and usually the FAQ is the right call. I just wasn't paying enough attention this time.
