### ISSUE TITLE
Skip Tablespace during restore

### ISSUE THREAD

**Issue by mroisset** [pgbackrest/pgbackrest#1382]
Hello,

Thanks for this wonderful tool!

Are you considering implementing an option that would allow to skip a list of tablespaces during a restore? It would be really helpful for test environments (skip archive tablespaces for instance..)?

**Comment by sfrost** [comment]
PG is still going to try and write into that tablespace during recovery, so we'd have to play the same trick as we do with individual database restore, which is to write out sparse files into the directory where the tablespace is ...

Not sure that I really see it as a useful enough use-case for us to write a bunch of code and tests for it...

**Comment by mroisset** [comment]
I do understand. So would you suggest to relocate TBS to /dev/null and after restore, drop TBS, as for databases?

**Comment by dwsteele** [comment]
> So would you suggest to relocate TBS to /dev/null

Not sure what you mean here. Postgres will expect files in the tablespace to be actual files.

And, yes, after recovery completes you can drop the tablespaces.

**Comment by dwsteele** [comment]
This does not appear to be something we are interested in implementing at this time, so closing.
