### ISSUE TITLE
ERROR: [058] when creating a stanza on the 2nd postgresql server

### ISSUE THREAD

**Issue by julienc256** [pgbackrest/pgbackrest#1390]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
**2.33**
2. PostgreSQL version:
**12.5**
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Linux RedHat 7.8
4. Did you install pgBackRest from source or from a package?
From rpm package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

**Content of /etc/pgbackrest.conf :
[global]
retention-full=2
start-fast=y
process-max=1

[global:restore]
process-max=2

[DEMO1]
repo1-path=/pgqdata/backup/pgserver1/pgbackrest
pg1-path=/pgqdata/pgserver1/data
log-path=/opt/pgsql/log/pgserver1/pgbackrest

[DEMO2]
repo1-path=/pgqdata/backup/pgserver2/pgbackrest
pg1-path=/pgqdata/pgserver2/data
log-path=/opt/pgsql/log/pgserver2/pgbackrest**

7. Describe the issue:
On the same machine, I have two PostgreSQL servers pgserver1 and pgserver2 that are not linked together :
 1  <>  PostgreSQL : 12.5 - PostgreSQL Server : pgserver1 - PostgreSQL Port : 5432
             PGDATA /pgqdata/pgserver1/data
             PGHOME /opt/pgsql/na/12.5

 2  <>  PostgreSQL : 12.5 - PostgreSQL Server : pgserver2 - PostgreSQL Port : 5433
             PGDATA /pgqdata/pgserver2/data
             PGHOME /opt/pgsql/na/12.5

I first successfully created Stanza for the 1st server.

Then I try to create Stanza for the 2nd server :
**pgbackrest --stanza=DEMO2 --log-level-consol=info stanza-create**

But I get the following error :
**ERROR: [058]**: version '12' and path '/pgqdata/pgserver1/data' queried from cluster do not match version '12' and '/pgqdata/pgserver2/data' read from '/pgqdata/pgserver2/data/global/pg_control'
       HINT: the pg1-path and pg1-port settings likely reference different clusters.

Why is there a reference to pgserver1 in the error message ? I clearly specified DEMO2 Stanza !
What would then be the correct /etc/pgbackrest.conf file ?
Thanks for any answer !

**Comment by pgstef** [comment]
Because you didn't specifed `pg1-port=5433` for the 2nd stanza. And the default port is 5432. So, when the command connects to PG using 5432, it gets another pg-data than the one you provided in pg1-path.

Add `pg1-port=5433` will solve your issue, as indicated in the **HINT**. But if you still want to run multiple instances on the same server, you should try to avoid having one using 5432 for safety reasons or everything (not only pgBackRest) will default to connect to that instance.

**Comment by julienc256** [comment]
Thanks for your quick reply, it worked ! :)
