### ISSUE TITLE
ERROR: [044]: PostgreSQL version 12, system-id 6951009988004524187 do not match stanza version 12

### ISSUE THREAD

**Issue by beer1970** [pgbackrest/pgbackrest#1391]
After re-installing Postgres db with seperate pgbackrest pods in a k8s cluster with s3 for storing the archive backups we are getting the error of a mismatch in system-id's

`2021-05-07 22:14:20.438 UTC [841440] DETAIL:  The failed archive command was: source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-archive-push-local-s3.sh pg_wal/00000002.history
ERROR: [044]: PostgreSQL version 12, system-id 6951009988004524187 do not match stanza version 12, system-id 6942435948829917354
       HINT: are you archiving to the correct stanza?
`
Is their a way to reset the  system-id without removing the backups?

Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.31

2. PostgreSQL version: 12.6

3. Operating system/version -Crunchy data 4.6.1 with image centos8-12.6-4.6.1 in k8s cluster

4. Did you install pgBackRest from source or from a package? Crunchydata

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Postgresql.conf

archive_command = 'source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-archive-push-local-s3.sh %p'
archive_mode = 'True'
archive_timeout = '60'
cluster_name = 'sonar-db'
hot_standby = 'on'
jit = 'False'
listen_addresses = '0.0.0.0'
log_directory = 'pg_log'
log_min_duration_statement = '60000'
log_statement = 'none'
max_connections = '100'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '6'
max_worker_processes = '8'
port = '5432'
shared_buffers = '128MB'
shared_preload_libraries = 'pgaudit.so,pg_stat_statements.so,pgnodemx.so'
temp_buffers = '8MB'
track_commit_timestamp = 'off'
unix_socket_directories = '/tmp'
wal_keep_segments = '8'
wal_level = 'logical'
wal_log_hints = 'on'
work_mem = '4MB'
hba_file = '/pgdata/sonar-db/pg_hba.conf'
ident_file = '/pgdata/sonar-db/pg_ident.conf'

7. Describe the issue:

Backup fails

`2021-05-07 22:14:20.438 UTC [841440] DETAIL:  The failed archive command was: source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-archive-push-local-s3.sh pg_wal/00000002.history
ERROR: [044]: PostgreSQL version 12, system-id 6951009988004524187 do not match stanza version 12, system-id 6942435948829917354
       HINT: are you archiving to the correct stanza?
`
Command:

`
time="2021-05-07T22:27:36Z" level=info msg="crunchy-pgbackrest starts"
time="2021-05-07T22:27:36Z" level=info msg="debug flag set to %tfalse"
time="2021-05-07T22:27:36Z" level=info msg="backrest backup command requested"
time="2021-05-07T22:27:36Z" level=info msg="backrest command will be executed for both local and s3 storage"
time="2021-05-07T22:27:36Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --type=incr --repo1-retention-full-type=time --repo1-retention-full=4 --db-host=10.233.114.95 --db-path=/pgdata/sonar-db ; pgbackrest backup --stanza=db --type=incr --repo1-retention-full-type=time --repo1-retention-full=4 --db-host=10.233.114.95 --db-path=/pgdata/sonar-db --repo1-type=s3 --no-repo1-s3-verify-tls]"
`

Config 

`
      COMMAND:                           backup
      MODE:                              pgbackrest
      COMMAND_OPTS:                      --stanza=db --type=incr --repo1-retention-full-type=time --repo1-retention-full=4 --db-host=10.233.114.95 --db-path=/pgdata/sonar-db
      PITR_TARGET:
      PODNAME:                           sonar-db-backrest-shared-repo-5dcb959c68-scjn5
      PGBACKREST_STANZA:
      PGBACKREST_DB_PATH:
      PGBACKREST_REPO1_PATH:
      PGBACKREST_REPO1_TYPE:             posix
      PGHA_PGBACKREST_LOCAL_S3_STORAGE:  true
      PGHA_PGBACKREST_S3_VERIFY_TLS:
      PGBACKREST_LOG_PATH:               /tmp
      NAMESPACE:                         l12m-sonarqube (v1:metadata.namespace)
`

**Comment by pgstef** [comment]
Hi,

First, you have to understand that you would store in the same stanza tree data from 2 different clusters. This would then add some complexity to your repo, including not being able to replay the new WAL archives generated on your old backups... Imho, it would be cleaner to rename your old stanza directory and create a new one for the new cluster.

To be honest I've never tried but perhaps the [stanza-upgrade](https://pgbackrest.org/command.html#command-stanza-upgrade) would work for that. It's more designed to be applied after PG major version upgrade, but it would worth trying in your case.

Kind regards

**Comment by dwsteele** [comment]
You can use `stanza-upgrade` in this case, even when the version has not changed. This lets pgBackRest know that the change in the cluster id was intentional (normally this is a sign of an accident or misconfiguration). All the old backups will be accessible and will expire on the normal schedule.
