### ISSUE TITLE
Restoring backup to a different server

### ISSUE THREAD

**Issue by galenspikes** [pgbackrest/pgbackrest#1397]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.33

2. PostgreSQL version: 12.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7.9

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We already have a backup schedule using pgbackrest, and we push full and diffs to AWS S3, and this is for several PostgreSQL servers I admin. Is there a way for me to take the backup of a specific database from one server, and restore it on another server? For example, dev_application on Dev Server, restore to prod_application on Prod Server.

**Comment by pgstef** [comment]
Hi,

The PITR backup mechanic in PG mean taking a backup of the complete db cluster. Also meaning you'll have to restore it all.

What you'd want is to "extract" a db using pg_dump and inject it in another cluster using pg_restore. You could restore a backup on you dev server, using the [db-include](https://pgbackrest.org/command.html#command-restore/category-command/option-db-include) option to minimize the disk space needed, then use pg_dump/pg_restore to get the data you want to retrieve.

Kind regards
