### ISSUE TITLE
Allow for new symlink creation/mapping (not just existing symlinks)

### ISSUE THREAD

**Issue by dtseiler** [pgbackrest/pgbackrest#1409]
Writing to request a feature that would be similar to `link-map` but also support creation of symlinks where perhaps there wasn't one before.

For example I'm setting up a replica that will eventually split off (to move one particularly busy database), and I'd like the replica to have `pg_wal` on a separate volume where the original primary DB doesn't have that separation. I'm currently updating my restore script to do this linking but having pgbackrest handle this just like it does for `link-all` or `link-map` would be a useful feature.

**Comment by dwsteele** [comment]
This seems like a good idea, and I don't think it would be too hard. He says, optimistically...

**Comment by cbandy** [comment]
I also would like to relocate (symlink) `pg_wal` during restore. In my case, however, some of my backups already have a symlink and some do not.

It would be great if I could specify where I want `pg_wal` and it ends up there regardless of backup set, PITR, etc.

**Comment by dwsteele** [comment]
@dtseiler @cbandy This has been implemented in PR#1520. Please review and approve if it looks good.
