### ISSUE TITLE
Is there a way to occassionally create a full backup with a different retention policy?

### ISSUE THREAD

**Issue by cloud-account** [pgbackrest/pgbackrest#1411]
Hello,

The "multi-repo" feature allows to create backups with retention policy defined per repository.
Full backups can be scheduled individually for each repository, but WALs are pushed to all configured repositories:

> "The archive-push command will always push WAL to the archive in all configured repositories but backups will need to be scheduled individually for each repository. In many cases this is desirable since backup types and retention will vary by repository."
https://pgbackrest.org/user-guide.html#multi-repo

Let's assume that standard backup retention is 2 weeks (repo1).
Once a year I want to backup a database with retention set to 5 years (repo2 or different method). I'm interested in a "self-contained" full backup only.
Is there a way to achieve that without continuously streaming WAL to repo2?

One way would be to configure a second stanza ("long-retention") for the same database and change archive_command to:
`archive_command = 'pgbackrest --stanza=long-retention archive-push %p'`.
After taking a long-term full backup, archive_command would have to be changed to "standard-retention" (2 weeks).
But this breaks continuous archiving of WAL to repo1 ("standard-retention"). The database cannot be restored to a point within the long-term full backup window.

Thank you

**Comment by pgstef** [comment]
Hi,

With the current implementation, one possible approach would be to:
- add definition of `repo2` in configuration file
- take backup
- remove definition of `repo2` in configuration file
That would avoid reloading PG to change the `archive_command`.

However, I believe that multi-repo has mainly been designed for redundancy purpose. How often would you trigger your "5 years retention" backups? Is that repo going to be available anytime? 

If retaining so many WAL archives is the underlying issue (not because repo availability but because of disk space), then defining a specific [repo-retention-archive](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-archive) would do the trick IMHO.

But if you're talking about long term self-contained backup, without any WAL archives (outside the ones needed for consistency), with repo availability being an issue, perhaps `pg_basebackup` would be more fitting this requirement?

Kind regards

**Comment by cloud-account** [comment]
Hi,

> But if you're talking about long term self-contained backup, without any WAL archives (outside the ones needed for consistency), with repo availability being an issue, perhaps pg_basebackup would be more fitting this requirement?

I would like to use one backup/restore solution for PostgreSQL and use it in a centralised way, if possible. 
I want my backups to be maneged and catalogued by one solution.

> However, I believe that multi-repo has mainly been designed for redundancy purpose. How often would you trigger your "5 years retention" backups? Is that repo going to be available anytime?

Due to regulatory requirements and/or business needs we need to have an option to take backups with non-standard retention, e.g.:
default retention - 2 weeks
once a year - keep data for 5 years
once a month - keep data for 3 months
once a week - keep data for 1 month
\+ option to take a non-standard full backup ad hoc  (before major system upgrades, etc.)

> If retaining so many WAL archives is the underlying issue (not because repo availability but because of disk space), then defining a specific repo-retention-archive would do the trick IMHO.

Am I correct in assuming that it has the following drawbacks:
- WAL files needs to be transfered wasting bandwidth, 
- in a public cloud environment it can incur additional costs (transfer, peering, storage, etc.)


> With the current implementation, one possible approach would be to:
    add definition of repo2 in configuration file
    take backup
    remove definition of repo2 in configuration file
    That would avoid reloading PG to change the archive_command.

Ideally, I would like to avoid changing pgbackrest configuration files and use an option/parameter when executing pgbackrest.

Kind regards

**Comment by pgstef** [comment]
What you're trying to create would go against the PG PITR logic. No wal archive = no backup consistency + no point in time recovery.

Adding an option to disable archiving on a specific repository wouldn't probably be that much complicated but then the question would be how to transfer the wal files during the backup which would be needed for consistency. And given the PG archiving system, I'm not sure that part would really be easy currently.

Perhaps @dwsteele will have another idea to help you achieve what you expect but I'm not.

**Comment by dwsteele** [comment]
Do the occasional full backup (or all of them) with `archive-copy` enabled then copy the backup directory wherever you like. This will be a self-contained backup that can be restored by manually copying it backup. All the WAL to make it consistent will be present in the pg_wal path.

We may eventually implement something like #1053, but it is not currently scheduled.

**Comment by cloud-account** [comment]
Thank you for great ideas!
There are some disadvantages though:
- In both cases backups are not catalogued by pgbackrest ("pgbacrest info" will not display entries describing the backups),
- Both solutions require some additional steps (config file modification, using external tool to copy the backup directory,  ...)

What I can think of is to store the information about the retention as metadada with full backups.
In that way, the retention can be defined per backup set. 
Default retention can be defined in a configuration file, but it could be overwritten using command line option.
"pgbackrest expire" would consult the backup metadata to check if the backup can be expired.
