### ISSUE TITLE
Part number must be an integer between 1 and 10000,

### ISSUE THREAD

**Issue by galenspikes** [pgbackrest/pgbackrest#1417]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.33

2. PostgreSQL version: 12.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7.9

4. Did you install pgBackRest from source or from a package? Package

7. Describe the issue:

I am using the same configurations and AWS CLI version on my other servers. For some reason I can't complete full backups to S3. The backup gets killed and the logs throw this error.

2021-05-26 12:23:42.942 P21   INFO: backup file /data-pgsql/base/1/14024 (0B, 74%)
ERROR: [039]: raised from local-2 protocol: HTTP request failed with 400 (Bad Request):
       *** Path/Query ***:
       /db-bkups/pgbackrest/th044/backup/test1/20210526-103523F/pg_data/l_chemical_descriptor.sql.lz4?partNumber=10001&uploadId=LFkdNferOTqhFFoHE6z3lGUNnOE4j28CFmVnvkkz0wrLcHT02OLvnNY1HTSCpnbaxzx2UyLolGbviVS5Or.wJ612Aj_RNjOjkDTlSbN9up63FQ.WkINCP_z22D61cy4G
       *** Request Headers ***:
       authorization: <redacted>
       content-length: 5242880
       content-md5: infEYo02IHpQYkxA8pGBPQ==
       host: edap-ccte.s3.us-east-1.amazonaws.com
       x-amz-content-sha256: 3fd929333374ce5b9ac903c85d6156045c4ddea356588aa27a5db2c91de2ba57
       x-amz-date: <redacted>
       *** Response Headers ***:
       connection: close
       content-type: application/xml
       date: Wed, 26 May 2021 22:16:20 GMT
       server: AmazonS3
       transfer-encoding: chunked
       x-amz-id-2: 6JuSXzGhhRvlVTM3ZSQEV3npbTCnSRCxcGc7CHrfDjEHg7Nv/684AWKD3sigp98ylEdo2GC06pg=
       x-amz-request-id: 6V5D3Z5GZZBBT5A0
       *** Response Content ***:
       <?xml version="1.0" encoding="UTF-8"?>
       <Error><Code>InvalidArgument</Code><Message>Part number must be an integer between 1 and 10000, inclusive</Message><ArgumentName>partNumber</ArgumentName><ArgumentValue>10001</ArgumentValue><RequestId>6V5D3Z5GZZBBT5A0</RequestId><HostId>6JuSXzGhhRvlVTM3ZSQEV3npbTCnSRCxcGc7CHrfDjEHg7Nv/684AWKD3sigp98ylEdo2GC06pg=</HostId></Error>
2021-05-26 18:19:01.043 P00   INFO: backup command end: aborted with exception [039]

bash-4.2$ aws --version
**aws-cli/2.2.1 Python/3.8.8 Linux/3.10.0-1160.24.1.el7.x86_64 exe/x86_64.rhel.7 prompt/off**

I don't understand why my backups would be working on my other servers and not this one, and those data directories are just as big, if not bigger.

**Comment by galenspikes** [comment]
```
bash-4.2$ cat /etc/pgbackrest.conf
[global]
log-level-console=info
repo1-s3-bucket=........
repo1-s3-endpoint=s3.us-east-1.amazonaws.com
repo1-path=/db-bkups/pgbackrest/th044/
repo1-s3-key=....................
repo1-s3-key-secret=.............
repo1-s3-region=us-east-1
repo1-type=s3
repo1-retention-full=13
repo1-retention-diff=6
process-max=25
archive-async=y
archive-push-queue-max=50GB
compress-type=lz4

[global:archive-push]
compress-level=3

[main]
pg1-path=/data-pgsql
```

```
wal_level = replica                     # minimal, replica, or logical
#wal_sync_method = fsync                # the default is the first option
#wal_compression = off                  # enable compression of full-page writes
wal_log_hints = on                      # also do full page writes of non-critical updates
#wal_init_zero = on                     # zero-fill new WAL files
#wal_recycle = on                       # recycle WAL files
wal_buffers = 16MB                      # min 32kB, -1 sets based on shared_buffers
#wal_writer_delay = 200ms               # 1-10000 milliseconds
#wal_writer_flush_after = 1MB           # measured in pages, 0 disables
max_wal_size = 8GB
min_wal_size = 4GB
max_wal_senders = 10            # max number of walsender processes
#wal_keep_segments = 0          # in logfile segments; 0 disables
#wal_sender_timeout = 60s       # in milliseconds; 0 disables
#wal_receiver_status_interval = 10s     # send replies at least this often
#wal_receiver_timeout = 60s             # time that receiver waits for
#wal_retrieve_retry_interval = 5s       # time to wait before retrying to
```

After the last failure I changed my min/max wal_size to 15GB/30GB and wondering if that helps. I'm not sure what's different htough.

**Comment by dwsteele** [comment]
Hmmm, how big is `l_chemical_descriptor.sql`? This doesn't look like something that should be in PGDATA.

We don't generally expect files larger than 1GB in PGDATA because that's the max size file PG will create. This file appears to be > 50GB *with* compression.

**Comment by galenspikes** [comment]
Oh you know what, you're absolutely right. This is a dump file I pulled a couple weeks ago on that mount and hadn't deleted it. I didn't think the server would try to treat that as an actual data file. This makes sense, thanks. As long as there isn't an issue with Pgbackrest or AWS.

**Comment by dwsteele** [comment]
pgBackRest only excludes specific files/dir from the backup based on a list that we have extensively tested. So anything unrecognized will be included just be safe.

It's pretty common for some junk to end up in PGDATA, it's just not usually 50GB+. :)
