### ISSUE TITLE
Working directory different from the pg1-path

### ISSUE THREAD

**Issue by fluca1978** [pgbackrest/pgbackrest#1418]
_I've found a working solution to my problem, that I describe below, but I would like to better understand why this is happening._

Running pg host on Ubuntu 18.04, same for the backup host, with pgbackrest 2.33.
The pg hosts are configure to keep data directory as the default in such operating system, that is `/var/lib/postgresql/9.6/main`, and, yes, it is a 9.6 PostgreSQL system.
The operating system `postgres` user has `HOME = /var/lib/postgresql`, I'm not sure if that is a problem.

Once I thought the system was configured, I run `check` but the archiving failed. I tried to reproduce the same command to see what was failing:

```
postgres@pg40:~$ /usr/bin/pgbackrest --pg1-path /var/lib/postgresql/9.6/main  --stanza pg40  archive-push pg_xlog/00000001000000400000005E
ERROR: [032]: PostgreSQL working directory '/var/lib/postgresql' is not the same as option pg1-path '/var/lib/postgresql/9.6/main'
       HINT: is the PostgreSQL data_directory configured the same as the pg1-path option?
```

I checked the working directory, and that was correct. 
The configuration for the stanza is:

```
[pg40]
pg1-path = /var/lib/postgresql/9.6/main
pg1-host = pg40
pg1-host-user = postgres
```

I then tried to change the HOME variable for the `postgres` user and run interactively the same command, but the problem was related to where the user was "projected" into:

```
$ export HOME=/tmp
$ /usr/bin/pgbackrest --pg1-path /var/lib/postgresql/9.6/main  --stanza pg40  archive-push pg_xlog/00000001000000400000005E
ERROR: [032]: PostgreSQL working directory '/tmp' is not the same as option pg1-path '/var/lib/postgresql/9.6/main'
       HINT: is the PostgreSQL data_directory configured the same as the pg1-path option?
```

Then I realized that running the command from within the data directory worked, so what I found as a working solution is to change the directory before archiving:

```
archive_command = 'cd /var/lib/postgresql/9.6/main && pgbackrest --stanza pg40 --pg1-path /var/lib/postgresql/9.6/main archive-push %p'
```

but I'm wondering why and if the above is a correct solution.

**Comment by pgstef** [comment]
Hi,

This is an expected behavior. The check can be found [here](https://github.com/pgbackrest/pgbackrest/blob/0a43be018347292a2d5e7ec68bbde595604bd104/src/command/archive/common.c#L347) in the code.

Why are you trying to execute the `archive-push` command yourself rather then using the provided `check` command ?

The `archive-push` command is supposed to be used by PG itself, so trigger from within the PGDATA directory (aka `pg1-path`). So, it's normal to trigger this command from inside the PG working directory when trying to execute it manually.
Try to remove the "cd ..." from your archive_command (don't forget to reload the PG service) and use the `pgbackrest check` command. This will ask PG to push a new WAL archives to check if the archive_command is running correctly ;-)

Kind regards

**Comment by fluca1978** [comment]
> Why are you trying to execute the `archive-push` command yourself rather then using the provided `check` command ?

Initially I ran `pgbackrest check`, but there was a problem archiving the WALs, so I inspected the postgresql.log and find out that the `archive_command` was failing. Therefore I became the `postgres` user and tried to run the same command manually to see what was causing the failure.
If I remove the `cd /var/lib/postgresql/9.6/main` from the `archive_command` the system is unable to archive the WALs.
I've never encountered this behavior before, I suspetc there is something misconfigured with the ubuntu machines, but I don't understand what.

**Comment by pgstef** [comment]
Using Ubuntu 18.04 isn't really "exotic". Have you tried raising `--log-level-console` in the archive_command to grab more info about the failing error ?

**Comment by fluca1978** [comment]
Uhm...shame on me, apparently I'm not able to reproduce the issue, and now the system archives either wirh or without the `cd` in the `archive_command`. I'm closing this issue since I don't have any other detail so far.
Thanks.

**Comment by mjf** [comment]
I ran into the exactly same issue after disk-full scenario in a 3-node cluster with streaming replication and offsite backups mixed with WAL archiving (all paths etc. set properly). Providing Postgres changing working directory to the full data path fixed it temporarily (i.e. `cd /full/data/path && pgbackrest ...`). After removing the changing working directory to the full data path again it continued to work correctly. Weird. It seems to me as some issue in Postgres itself (such as that under certain circumstances it does not change working directory to the correct data path before executing the command or something alike). It is hardly to imagine but it looks like that to me.

**Comment by dwsteele** [comment]
I've seen problems with postgres changing the working dir in the past, but I have never been able to reproduce it reliably. I've had a look at the code in postgres and it's hard to see how it would not be run.

If anyone can reproduce it reliably I'd be happy to have a look.
