### ISSUE TITLE
pgbackrest archive_command make standby out-of sync

### ISSUE THREAD

**Issue by moindba** [pgbackrest/pgbackrest#1422]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.33
2. PostgreSQL version:
11.9
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS 7.9
4. Did you install pgBackRest from source or from a package?
Package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    archive_command = 'pgbackrest --stanza=pg1 archive-push %p'

7. Describe the issue:
I have 1 Primary and 2 Standby Server, after configuring archive_command = 'pgbackrest --stanza=pg1 archive-push %p' my standbys are getting out-of sync because in recovery.conf of standby servers we have given restore_command = 'cp /S01/pgsql/arch/%f %p' .

Kindly help me with archive_command to make my standby in sync and also can able to take backups using pgbackrest.

**Comment by pgstef** [comment]
Hi,

Unfortunately, you don't provide a lot of information regarding your setup / configuration. `restore_command` is usually the safety net to catch up the Streaming Replication delay. I guess you also configured `primary_conninfo`.

Actually the easiest way would to install pgBackRest on your standby servers too and update your `restore_command` which is usually done automatically by the [restore](https://pgbackrest.org/command.html#command-restore). It would give you something like: `restore_command = 'pgbackrest --stanza=pg1 archive-get %f "%p"'`.

[This](https://pgstef.github.io/2020/09/04/combining_pgbackrest_and_streaming_replication.html) blog post could perhaps help you better understand the situation.

Kind regards
