### ISSUE TITLE
Feature request to add S3 server side encryption by specifying a KMS key id as a config

### ISSUE THREAD

**Issue by tharinduamila-insta** [pgbackrest/pgbackrest#1430]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.34

2. PostgreSQL version: 13.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: debian

4. Did you install pgBackRest from source or from a package?
from source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We would like to utilize the capability AWS offers for encrypting objects at server side by specifying a KMS key id in the request. This would allow us to have better control over who would be authorized to decrypt the stored objects and also not have any secrets in the server box itself reducing the risk of exposing that key.  

We will also be willing to contribute for this feature if it's accepted for the project.

**Comment by dwsteele** [comment]
If this is just a header to add to requests it might not be that hard to implement. If you do the implementation we'll update the unit tests, but for now I don't think we have time to take this on.

**Comment by tharinduamila-insta** [comment]
Hi David, you are correct. It just needs several headers to be sent and I am happy to do the implementation. It'll take me a while before I get around to it too.  Thank you for having a look at the request and for suggesting a way forward with this.
