### ISSUE TITLE
Support GCS retention policy

### ISSUE THREAD

**Issue by haraldschilly** [pgbackrest/pgbackrest#1439]
1. pgBackRest version: 2.34
[...]
7. Describe the issue:

This is quite general. GCS has a feature called [retention policy](https://cloud.google.com/storage/docs/bucket-lock). It prevents an object from any modification/deletion for a given period of time. That makes this more robust against any attacks involving deleting your buckets, project, etc. or just human error.

With that enabled, sending backups doesn't work. It tries to replace metadata files, e.g. causing an error like `Object "[...]backup/<...>/20210624-154118F_20210625-065505I/backup.manifest.copy" is subject to bucket's retention policy and cannot be deleted, overwritten or archived until [couple of days in the future]`.

My thoughts are that these metadata files could have a timestamp, pgbackrest uses the most recent one, and hence never be overwritten, and be cleaned up later when backups are removed. Besides that, there might be other details to take care of, though.

**Comment by dwsteele** [comment]
There would definitely be other issues to take care of, for instance removing prior aborted backups, expiration, etc.

There is no question that this would be a valuable feature, but I'm not sure how it could be implemented with our current repo format. I've added a card for the next repo format to consider this (https://github.com/pgbackrest/pgbackrest/projects/8#card-64556418) but I'm not sure what we can do at present.

One thing to try would be to use `archive-copy` so the backups are self-contained and then update the backup path as read-only once it is complete. Expiration still won't work, of course. Not sure if it is possible to do this with individual objects in GCS.

**Comment by dwsteele** [comment]
See #1494 for another idea on how to do this.
