### ISSUE TITLE
invalid option '--exec-id=153421-173b09b9'`

### ISSUE THREAD

**Issue by m0nt3cr1st0** [pgbackrest/pgbackrest#1441]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.34

2. PostgreSQL version: 10.17

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: testdb -> RHEL8, myrepo-db -> CentOS 7

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
    testdb:
      [maindb]
      pg1-path=/var/lib/pgsql/10/data
      
      [global]
      log-level-file=detail
    myrepo-db:
     [maindb]
    pg1-host=maindb
    pg1-path=/var/lib/pgsql/10/data
    
    [global]
    process-max=4
    compress-type=lz4
    repo1-path=/var/lib/pgbackrest
    repo1-retention-full=2
    start-fast=y 
```
   - postgresql.conf settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue -> None
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
```
    -------------------PROCESS START-------------------
2021-06-28 04:03:40.586 P00   INFO: restore command begin 2.34: --exec-id=153421-173b09b9 --log-level-console=detail --log-level-file=detail --pg1-path=/var/lib/pgsql/10/data --repo1-host=myrepo-db --stanza=maindb
2021-06-28 04:03:41.035 P00  ERROR: [031]: remote-0 process on 'myrepo-db' terminated unexpectedly [31]: ERROR: [031]: invalid option '--exec-id=153421-173b09b9'
2021-06-28 04:03:41.035 P00   INFO: restore command end: aborted with exception [031]
```
7. Describe the issue:
Hello everyone! Thanks in advance for your time. I have been trying to find issues already mentioning this but couldn't find anything, neither on the documentation. 
I have set up replication for my main cluster (maindb) on a different repository host (myrepo-db), now I'm trying to restore this cluster into a different host (testdb) , however when I try to start the restoring process with:
`pgbackrest --stanza=maindb --log-level-console=detail --delta restore`  
I get the following error:
`2021-06-28 04:03:41.035 P00  ERROR: [031]: remote-0 process on 'myrepo-db' terminated unexpectedly [31]: ERROR: [031]: invalid option '--exec-id=153421-173b09b9'`
I couldn't find this option mentioned anywhere in the documentation unfortunately, I didn't mention it on my command either so I'm not sure what's going on there. Could anyone shed some light on it? I will happily document it myself afterwards if needed!

**Comment by cmwshang** [comment]
This usually means you are not running the same version of pgbackrest on all your hosts.

**Comment by m0nt3cr1st0** [comment]
That was it @cmwshang thanks! Is this a known compatibility issue? 
If so, is there anyway to circumvent it besides installing manually the same version on both hosts?

**Comment by cmwshang** [comment]
In the user guide there is a bolded *NOTE* in the installation section https://pgbackrest.org/user-guide.html#repo-host/install indicating the versions must match. The reason is that when options are added to newer versions of the software, older versions are not aware of those options and therefore cannot expect to handle them. 
Hope that answers your question.

**Comment by m0nt3cr1st0** [comment]
It does indeed! Thanks for your help @cmwshang
