### ISSUE TITLE
Add pigz compression tool

### ISSUE THREAD

**Issue by ccavallie** [pgbackrest/pgbackrest#1451]
Hi,
Would it be possible to add the pigz (pronounced pig-zee) compression tool which is much more powerful than gzip and provides a fully gzip compatible format: https://www.zlib.net/pigz/
thank you in advance

**Comment by sfrost** [comment]
pgbackrest already parallelizes operations extensively and is a C program written directly using the zlib library.  pgbackrest also has a number of other compression options, include zstd, which might work better for you if you're unhappy with zlib performance.
