### ISSUE TITLE
Real-time progress bar of copied files

### ISSUE THREAD

**Issue by turnstep** [pgbackrest/pgbackrest#1453]
Was thinking about this when talking about the level of detail when backing up and restoring files. It would be cool if there were some sort of progress bar indicating the total number of files to be copied and a running graphical indicator, like the way yum/dnf and score of other projects do.

**Comment by dwsteele** [comment]
In general I don't think backup/restore is meant to be run in the foreground so not sure this is worth the effort. Percent complete is in the log, though soon that will only be available at detail level.

**Comment by mjf** [comment]
Maybe a stupid idea but what about to implement some log sampling like, for example,
```ini
log-level-sample-file=detail=0.001,info=0.01,warning=0.1
```
or, perhaps,
```ini
log-level-sample-file=detail=1000,info=100,warning=10
```
or, maybe,
```ini
log-level-sample-file-detail=1000
log-level-sample-file-info=100
log-level-sample-file-warning=10
```
or similar option(s) apart from existing logging options to allow extra logging of only every 1000-th detailed, 100th info and 10th warning message into extra log file?

**Comment by dwsteele** [comment]
I think the solution proposed for #1490 would work pretty well for getting progress, so we'll likely go with that. You could always write a tool to show a progress bar, but I don't think that's a direction we want to go with core `pgbackrest`.
