### ISSUE TITLE
Can not run a backup full  INFO: backup command end: aborted with exception [057]

### ISSUE THREAD

**Issue by maipeng** [pgbackrest/pgbackrest#1461]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.32

2. PostgreSQL version:9.5.24

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
database server Debian 9 
epository host server :Debian 10

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - achive_command='pgbackrest --stanza=jv-sql-www-primary-two archive-push %p'
    - archive_mode=on
    - listen_addresses=*
    - max_wal_senders=10
    - wal_level=hot_standby
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I can not run a backup full on a pg instance. I have used the option achive-async=y
Here the command:
/usr/bin/pgbackrest --type=full --stanza=primary-two --db-timeout 7200 backup

thanks for your help.

[pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/6808729/pgbackrest.log)
[postgresql.log](https://github.com/pgbackrest/pgbackrest/files/6808730/postgresql.log)
[pgbackrest_conf.txt](https://github.com/pgbackrest/pgbackrest/files/6808745/pgbackrest_conf.txt)

**Comment by pgstef** [comment]
Hi,

Your setup isn't clear. It seems you're using a PG host + a repo host. Could you provide your PG host pgbackrest settings ?

Your stanza names are unclear too. You're using `jv-sql-www-primary-two` with your archive-push, `primary-two` for you backup command but `server` in you repo host pgbackrest config.

First of all, you should fix that so every commands are targeting the same stanza name (and the stanza is correctly created inside the repo).

Then, try to verify your archiving system with the **check** command.

I see in your PG logs `ERROR: [055]: raised from local-1 protocol: unable to open missing file '/var/lib/postgresql/9.5/main/pg_xlog/000000010000661B0000007E' for read`.
Is `pg_xlog` a symlink ? Does the postgres system user have enough perms to read files from it ?

Kind regards

**Comment by maipeng** [comment]
Hi,
yes it's a pg host and repo host.
here the pg host settings
```
[jv-sql-www-primary-two ]
pg1-host=xxx.xxx.xxx.xxx
pg1-path=/var/lib/postgresql/9.5/main
archive-async=y
spool-path=/var/spool/pgbackrest
```
I have rename the server . It's jv-sql-www-primary-two .
We have run a check 
pgbackrest@wb-infra-backup4:/root$ /usr/bin/pgbackrest --stanza=jv-sql-www-primary-two --log-level-console=info check
2021-07-13 14:49:40.637 P00   INFO: check command begin 2.32: --exec-id=2771-c9367355 --log-level-console=info --log-level-file=detail --pg1-host=10.110.0.249 --pg1-path=/var/lib/postgresql/9.5/main --repo1-path=/data/eu2/pgbackrest --stanza=jv-sql-www-primary-two
2021-07-13 14:49:41.318 P00   INFO: check repo1 configuration (primary)
2021-07-13 14:49:41.521 P00   INFO: check repo1 archive for WAL (primary)
2021-07-13 14:49:55.839 P00   INFO: WAL segment 0000000100006952000000A4 successfully archived to '/data/eu2/pgbackrest/archive/jv-sql-www-primary-two/9.5-1/0000000100006952/0000000100006952000000A4-528e613abbb2360f2e7578f4ffcb6657b0ede2b7.gz' on repo1
2021-07-13 14:49:55.939 P00   INFO: check command end: completed successfully (15303ms)

The user postgres has the acl to read and pg_xlog is not a symlink.

Kind regards

**Comment by pgstef** [comment]
You can then remove the options regarding `archive-push`, `archive-get` or `archive-async` from your repo/backup server config. The archiving system is pushing files from the PG host.

The `check command end: completed successfully` means now that the PG host was able to push a WAL archive to the repo successfully. 

So now, your backups should be working

**Comment by maipeng** [comment]
the first time I have run the command, I did not use archive-push, archive-get or archive-async, and I had this king of error=> ERROR: [055]: raised from local-1 protocol: unable to open missing file '/var/lib/postgresql/9.5/main/pg_xlog/000000010000661B0000007E' for read
2021-07-13 06:20:44.591 P00   INFO: archive-push command end: aborted with exception [055]

that's why I used these 3 options, plus --db-timeout 7200, I still have this error.
Do I have to add some other option like archive-timeout ?
thank you

**Comment by pgstef** [comment]
I don't really understand your setup / question. You're now giving outputs from `archive-push` (which are usually located in PG logs) while the `check` command (testing the archiving system) succeeded.

Are you trying to use the `archive-push` command manually from the repo server? It should be executed by PG itself (archiver process)... not manually.

[**archive-push**](https://pgbackrest.org/command.html#command-archive-push) and [**archive-get**](https://pgbackrest.org/command.html#command-archive-get) are commands (used by PG within the `archive_command` and `restore_command` settings). `archive-async` is an option for those commands. Perhaps [this example](https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html) will give you more insights (before the Streaming Replication part).

Concretely, you could simply have something like:
```
# Repo server config
[global]
repo1-path=/data/eu2/pgbackrest/
repo1-retention-full=2
log-level-console=info
log-level-file=detail

[jv-sql-www-primary-two]
pg1-host=xxx.xxx.xxx.xxx
pg1-path=/var/lib/postgresql/9.5/main

# PG server config
[global]
repo1-host=xxx.xxx.xxx.xxx
log-level-console=info
log-level-file=detail

[global:archive-get]
process-max=2
log-level-console=debug

[global:archive-push]
process-max=4
log-level-console=debug

[jv-sql-www-primary-two]
pg1-path=/var/lib/postgresql/9.5/main
archive-async=y
spool-path=/var/spool/pgbackrest
```

The PG `achive_command` seems good. So, from Repo server and from PG server, this should succeed: `pgbackrest --stanza=jv-sql-www-primary-two check`.
Then, from the Repo server, take a backup: `pgbackrest --stanza=jv-sql-www-primary-two --type=full backup`

So, to be able to help you with the `unable to open missing file`, we'd need a real view of your configs and command used (as required by the Github issue template...).

Kind regards
