### ISSUE TITLE
backup primary AND replica independantly

### ISSUE THREAD

**Issue by kikijolicoeur** [pgbackrest/pgbackrest#1465]
Hello

1. pgBackRest version: 2.33

2. PostgreSQL version: 12.7

3. Operating system/version : debian 10 (buster)

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:

7. Describe the issue: I have a primary and a replica (streaming replica) with patroni. I use pgbackrest to save the primary (in S3). I tried to save the replica. But I have the following error : 
 ERROR: [056]: unable to find primary cluster - cannot proceed. 
I want to save replica independantly of primary because if case of  failover I don't want to have to configure pgbackrest on the promoted replica. The failover can occur in night, and I don't want to run PostgreSQL without backup during some hours.

I am not in the case where I want to use the replica to back up to relieve the primary.
Is there a way to do that ?

Thanks

Christian

**Comment by philflorent** [comment]
Hi,
It's a known pgBackRest limitation. I had asked a similar question. It's possible to build simple mirror configurations with Barman but it's not possible with pgBackRest. 
Notice that things recently changed : archive_mode=always is now possible with pgbackrest >= 2.32 and remaining limitations are lighter. 
As of 2.34 it seems it it's still impossible not to connect to the primary cluster but you can test if your cluster is in standby mode to add dynamically the required arguments if necessary.  
pgbackrest ${STANDBY_BACKUP} 

STANDBY_BACKUP=""  if your cluster is primary 
STANDBY_BACKUP="--pg2-host=??? --pg2-host-user=??? --pg2-path=??? --pg2-port=??? --archive-timeout=??? --backup-standby" if you cluster is secondary

It's not too difficult to determine if cluster is primary or secondary. I see you mentionned Debian, you can to it with pg_lsclusters, state is "online" or "online, recovery". 

Best regards,
Phil

**Comment by pgstef** [comment]
Hi,

With pgBackRest, taking a backup from a standby server will require access to the primary for multiple reasons (mainly safety). The backup control queries (pg_start/stop_backup) will be executed on the primary, fetching the WAL location and then waiting until the standby has replayed the WALs and reached that location before copying the actual data files from the standby,... It's an hybrid situation but you're then sure to copy the actual data from the time you start your backup.

So, defining `pg1-*` and `pg2-*` settings in both primary/standby configs isn't a problem at all. It brings cluster awareness. pgBackRest will be able to detect which one is primary and which one is standby.

```
[stanza-name]
pg1-path=/var/lib/pgsql/13/data
pg2-host=**the other pg node**
pg2-path=/var/lib/pgsql/13/data
```

If I read the exposed question here correctly, there's no real point on taking backups on both servers at the same time. But better configure pgBackRest so in case of fail-over, no configuration change is needed to have the backup running on the new primary. Usually, this is easy to achieve with a dedicated backup server (with cluster awareness, the backup would always be taken from the available primary). Triggering a backup from the standby, using `backup-standby=n` (default) would copy data files from the primary given you explicitly ask to take a backup.

In HA setups, I usually recommend using a dedicated backup server. Or indeed, you could tweak your cron task to only activate the backup task on the primary, using something like `[ `psql -At -c "select pg_is_in_recovery();"` = 'f' ] && pgbackrest backup ...`.

Kind Regards

**Comment by dwsteele** [comment]
We are planning to implement this feature at some point, but simply have not had time. We developed the current methodology because it is safer (the last WAL segment for the backup can be pushed), preserves primary stats/logs, and will be higher performance once we allow the backup to use multiple standbys. However, we recognize that there is a use case for backup from standby only.

I'm not sure that getting a backup overnight is so important. Any backup + WAL = PITR so the critical thing is for the WAL stream be uninterrupted. Missing a single day's backup should not be cause for alarm as long as the archive is healthy.

**Comment by kikijolicoeur** [comment]
Hello.
Thanks David and Phil for your answers. 
I think I will  tweak my cron task.

Best regards
