### ISSUE TITLE
Save backups plus WAL required for restore only

### ISSUE THREAD

**Issue by jamessewell** [pgbackrest/pgbackrest#1471]
Is $subject possible? 

So essentially discard/expire any WAL which isn't needed to make a previous or running backup valid?

**Comment by Tostino** [comment]
Also interested in this, but being configurable would be useful. It would be extremely helpful for me to be able to specify that I want to keep a year of backups, with 3 months of those being PITR.

**Comment by pgstef** [comment]
> Also interested in this, but being configurable would be useful. It would be extremely helpful for me to be able to specify that I want to keep a year of backups, with 3 months of those being PITR.

Depending on how many backups you have in those 3 months, the [retention-archive](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-archive) setting couldn't help you ?

**Comment by Tostino** [comment]
Well that's what I get for not keeping up with development for a bit. Wasn't aware it was already complete! Time to get this in place.

**Comment by dwsteele** [comment]
@jamessewell `--repo1-retention-archive-type=incr --repo1-rentention-archive=1` is the closest you can get. This will expire all WAL not required for consistency before the last backup.

**Comment by dwsteele** [comment]
> Well that's what I get for not keeping up with development for a bit. Wasn't aware it was already complete! Time to get this in place.

@Tostino Not sure what you mean? This feature has been around for at least 3-4 years.
