### ISSUE TITLE
Use a hostname other than "pg1" in the user guide

### ISSUE THREAD

**Issue by turnstep** [pgbackrest/pgbackrest#1476]
Doc improvement idea: use a different hostname other than "pg1" which leads to confusion with the args that require a literal "pg1" not related to the hostname. In the user guide:

 `A new host named pg1 is created to contain the demo cluster and run backrest examples.`

**Comment by dwsteele** [comment]
Suggestions?

**Comment by pgstef** [comment]
Is it really called `pg1`? I've got the feeling that is appears as `pg-primary` ?
Perhaps that mention is some left-over and we should adjust to `pg-primary` too ?

**Comment by dwsteele** [comment]
Good catch, @pgstef. I have added PR #1479 to fix this and one other host name issue.

I would like to rename the hosts from `pg-primary` and `pg-standby` at some point because it would be good to add some failover examples, but this addresses the immediate issue.

**Comment by pgstef** [comment]
> Good catch, @pgstef. I have added PR #1479 to fix this and one other host name issue.

Seen and approved ;-)

> I would like to rename the hosts from `pg-primary` and `pg-standby` at some point because it would be good to add some failover examples, but this addresses the immediate issue.

In such cases, I like to use the "node" term (like vagrant does for example). Why not something like `pg-node1`, `pg-node2`, `repo-node1`,... ? Anyway, that's another day problem :-D

**Comment by dwsteele** [comment]
So, anyone interested in doing the rename to `pg-node1` or `pg-host1`? I personally favor `pg-host1` since `host` is the terminology we use throughout the documentation.
