### ISSUE TITLE
Retention full removes retention diff it should not

### ISSUE THREAD

**Issue by zerkms** [pgbackrest/pgbackrest#1478]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.33

2. PostgreSQL version: 13.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: n/a

4. Did you install pgBackRest from source or from a package? 

It's provided in the crunchydata docker image (postgresql operator, v5)

5. Please attach the following as applicable:
```
		repo1-retention-diff=1
		repo1-retention-full=2
		repo1-retention-full-type=count
```

7. Describe the issue:

At the moment I'm assessing crunchydata PGO v5 operator, and while I'm doing that I have set up the backups to be very frequent, with the following schedules (cron syntax):

```
          full: "*/20 * * * *"
          differential: "7,14,27,34,47,54 * * * *"
          incremental: "3,6,9,12,15,18,21,24,28,31,35,37,43,48,51,55 * * * *"
```

What I have found is when another full happens - it removes way too much.

Let's see that with an example:

At 12:59pm there were the following backups:

* full from 12:20
* full from 12:40
* incremental from 12:43
* differential from 12:54
* incremental from 12:55

This is expected.

Then at 1:00pm a new full backup runs, and after it finishes we end up with:

* full from 12:40
* incremental from 12:43
* full from 1:00

I would expect the following 2 must have been kept, not removed:

* differential from 12:54
* incremental from 12:55

**Comment by pgstef** [comment]
Hi,

As mentioned in the User Guides, that's an expected behavior. Differential and Incremental backups will always be expired when the backup they depend on is expired. Differentials only rely on the prior full backup so it is possible to only keep a few of them using `repo1-retention-diff`. Incremental backups cannot be expired independently — they are always expired with their related full or differential backup.

You can test the expire command manually using the `--dry-run` option if you want to see exactly what would be expired. And you'll also get an idea of it in the info command `backup reference list:`.

Simply said, differential and incremental backups only contain a few files (only the files modified since the last [full] backup) and are not "self-contained" backup sets. Restoring it without the initial backup set isn't possible unfortunately.

Kind Regards

**Comment by zerkms** [comment]
@pgstef that still does not explain why the `differential from 12:54` was removed on new **full** backup.

**Comment by zerkms** [comment]
@pgstef can you please remove the `question` label as it's not a question but clearly a bug.

**Comment by pgstef** [comment]
Hm, that's strange indeed. Could they have been referred to the 12:20 Full ? Did you save the info cmd output somewhere ?
I'm not sure it's so "usual" to have backups running so close to each other. Usually, WAL archives are used for that.

Probably the only way to find out what happened is in the log file of the backup command, in the expire part. Have you that information somewhere ?


> @pgstef can you please remove the `question` label as it's not a question but clearly a bug.

I'll let @dwsteele decide on that, since to me we lack information (like logs, backup reference list,...).

**Comment by zerkms** [comment]
Yep, I will run it manually tomorrow for more detailed logs then. But I witnessed it many times tomorrow.

I suspect the `FFIDIF` would lead to `FIF` no matter how long it was between backups (but I will confirm it tomorrow with more detailed logs, as now it's 2.5 hours after my working day has finshed :-D )

**Comment by pgstef** [comment]
Concretely, the expire logs are usually helpful to understand what's going on.

I've just run a few tests (using the latest `master` branch source code) and was able to reproduce your issue.

Using `repo1-retention-diff=1` and `--repo1-retention-full=2`:

```bash
$ pgbackrest info
stanza: my_stanza
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13): 000000010000000000000007/00000001000000000000000D

        full backup: 20210729-093651F
            timestamp start/stop: 2021-07-29 09:36:51 / 2021-07-29 09:36:59
            wal start/stop: 000000010000000000000007 / 000000010000000000000007
            database size: 23.1MB, database backup size: 23.1MB
            repo1: backup set size: 2.8MB, backup size: 2.8MB

        full backup: 20210729-093703F
            timestamp start/stop: 2021-07-29 09:37:03 / 2021-07-29 09:37:08
            wal start/stop: 000000010000000000000009 / 000000010000000000000009
            database size: 23.1MB, database backup size: 23.1MB
            repo1: backup set size: 2.8MB, backup size: 2.8MB

        incr backup: 20210729-093703F_20210729-093711I
            timestamp start/stop: 2021-07-29 09:37:11 / 2021-07-29 09:37:12
            wal start/stop: 00000001000000000000000A / 00000001000000000000000A
            database size: 23.1MB, database backup size: 14.8KB
            repo1: backup set size: 2.8MB, backup size: 1.6KB
            backup reference list: 20210729-093703F

        diff backup: 20210729-093703F_20210729-093717D
            timestamp start/stop: 2021-07-29 09:37:17 / 2021-07-29 09:37:19
            wal start/stop: 00000001000000000000000B / 00000001000000000000000B
            database size: 23.1MB, database backup size: 15.8KB
            repo1: backup set size: 2.8MB, backup size: 1.7KB
            backup reference list: 20210729-093703F

        incr backup: 20210729-093703F_20210729-093723I
            timestamp start/stop: 2021-07-29 09:37:23 / 2021-07-29 09:37:25
            wal start/stop: 00000001000000000000000D / 00000001000000000000000D
            database size: 23.1MB, database backup size: 17.2KB
            repo1: backup set size: 2.8MB, backup size: 1.8KB
            backup reference list: 20210729-093703F
```
```
INFO: repo1: expire full backup 20210729-093651F
INFO: repo1: expire diff backup set 20210729-093703F_20210729-093717D, 20210729-093703F_20210729-093723I
INFO: repo1: remove expired backup 20210729-093703F_20210729-093723I
INFO: repo1: remove expired backup 20210729-093703F_20210729-093717D
INFO: repo1: remove expired backup 20210729-093651F
INFO: repo1: 13-1 remove archive, start = 000000010000000000000007, stop = 000000010000000000000008
INFO: expire command end: completed successfully (852ms)
```

Using `repo1-retention-diff=2` and `--repo1-retention-full=2`:

```bash
$ pgbackrest info
stanza: my_stanza
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13): 00000001000000000000001D/000000010000000000000028

        full backup: 20210729-101336F
            timestamp start/stop: 2021-07-29 10:13:36 / 2021-07-29 10:13:43
            wal start/stop: 00000001000000000000001D / 00000001000000000000001D
            database size: 23.1MB, database backup size: 23.1MB
            repo1: backup set size: 2.8MB, backup size: 2.8MB

        incr backup: 20210729-101336F_20210729-101420I
            timestamp start/stop: 2021-07-29 10:14:20 / 2021-07-29 10:14:21
            wal start/stop: 00000001000000000000001F / 00000001000000000000001F
            database size: 23.1MB, database backup size: 8.3KB
            repo1: backup set size: 2.8MB, backup size: 403B
            backup reference list: 20210729-101336F

        full backup: 20210729-101434F
            timestamp start/stop: 2021-07-29 10:14:34 / 2021-07-29 10:14:40
            wal start/stop: 000000010000000000000023 / 000000010000000000000023
            database size: 23.1MB, database backup size: 23.1MB
            repo1: backup set size: 2.8MB, backup size: 2.8MB

        incr backup: 20210729-101434F_20210729-101501I
            timestamp start/stop: 2021-07-29 10:15:01 / 2021-07-29 10:15:02
            wal start/stop: 000000010000000000000025 / 000000010000000000000025
            database size: 23.1MB, database backup size: 8.3KB
            repo1: backup set size: 2.8MB, backup size: 401B
            backup reference list: 20210729-101434F

        diff backup: 20210729-101434F_20210729-101503D
            timestamp start/stop: 2021-07-29 10:15:03 / 2021-07-29 10:15:05
            wal start/stop: 000000010000000000000026 / 000000010000000000000026
            database size: 23.1MB, database backup size: 8.3KB
            repo1: backup set size: 2.8MB, backup size: 402B
            backup reference list: 20210729-101434F

        diff backup: 20210729-101434F_20210729-101506D
            timestamp start/stop: 2021-07-29 10:15:06 / 2021-07-29 10:15:08
            wal start/stop: 000000010000000000000027 / 000000010000000000000027
            database size: 23.1MB, database backup size: 8.3KB
            repo1: backup set size: 2.8MB, backup size: 402B
            backup reference list: 20210729-101434F

        incr backup: 20210729-101434F_20210729-101509I
            timestamp start/stop: 2021-07-29 10:15:09 / 2021-07-29 10:15:11
            wal start/stop: 000000010000000000000028 / 000000010000000000000028
            database size: 23.1MB, database backup size: 8.3KB
            repo1: backup set size: 2.8MB, backup size: 403B
            backup reference list: 20210729-101434F
```
```
2021-07-29 10:15:26.169 P00   INFO: repo1: expire full backup set 20210729-101336F, 20210729-101336F_20210729-101420I
2021-07-29 10:15:26.171 P00   INFO: repo1: expire diff backup 20210729-101434F_20210729-101503D
2021-07-29 10:15:26.185 P00   INFO: repo1: remove expired backup 20210729-101434F_20210729-101503D
2021-07-29 10:15:26.193 P00   INFO: repo1: remove expired backup 20210729-101336F_20210729-101420I
2021-07-29 10:15:26.200 P00   INFO: repo1: remove expired backup 20210729-101336F
```

So, it seems the 1st DIFF backup set is "always" expired. We'll have to dig deeper to find out why...

**Comment by zerkms** [comment]
> Concretely, the expire logs are usually helpful to understand what's going on.

My apologies for not doing that, I literally has familiarised myself with the pgbackrest just yesterday, so I haven't properly learned the better way to make _decent reports_ yet. Sorry :-)

**Comment by pgstef** [comment]
> My apologies for not doing that, I literally has familiarised myself with the pgbackrest just yesterday, so I haven't properly learned the better way to make _decent reports_ yet. Sorry :-)

Then probably a quick advice would be to trust the WAL archives between 2 backups and don't try to take so many backups so close to each other (which can likely lead to unpredictable issue when your backups will last longer due to bigger databases).
A good retention policy is 1 full backup per week + 1 diff/incr backup a day (retaining 5 full and 3 diff). This gives 4 weeks of retention and usually covers a lot of DR scenarios. [Here](https://pgconf.ru/en/2021/288719)'s a good example about this.

Anyway, looking at the [differential expiration code](https://github.com/pgbackrest/pgbackrest/blob/f3f0c64a78e2ac425567d792df204e493ad7bb20/src/command/expire/expire.c#L192), what we've both seen seems to be expected: 
```
Full are considered differential for the purpose of retention.
Example: F1, D1, D2, F2, repo-retention-diff=2, then F1,D2,F2 will be retained, not D2 and D1 as might be expected.
```

I agree, this doesn't seem very natural nor well documented. Probably @dwsteele will be able to tell us why it's behaving like this :-)

**Comment by zerkms** [comment]
> and don't try to take so many backups so close to each other

As I mentioned before - I'm assessing a new tool for me (crunchydata PGO) - so I have set up the parameters to extreme so that I could play through different scenarios quicker.

**Comment by dwsteele** [comment]
This is also documented in the user guide, `Since full backups are considered differential backups for the purpose of differential archive retention...`

Basically, the idea is that a full backup is better than a differential so why keep both?

**Comment by zerkms** [comment]
> why keep both?

Because the configuration says one diff backup will be retained?

```
		repo1-retention-diff=1
		repo1-retention-full=2
```
