### ISSUE TITLE
create stanza for ceph Gateway s3 endpoint log error: "[101]:TLS error [1:336031996] unknown protocol"

### ISSUE THREAD

**Issue by aqktjcm** [pgbackrest/pgbackrest#1482]
1. pgBackRest version:
`2.34
`
2. PostgreSQL version:
` 9.6.0
`
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
`centos7.3
`
4. Did you install pgBackRest from source or from a package?
from source

5. Please attach the following as applicable:

- pgbackrest.conf` file(s)

```
[demo]
pg1-path=/home/postgres/pgdata

[global]
process-max=3
log-level-file=debug
repo1-retention-full=2
repo1-path=/
repo1-type=s3
repo1-s3-bucket=pgbackup
repo1-s3-endpoint=101.12.21.43:8082
repo1-s3-region=default
repo1-s3-uri-style=path
repo1-s3-port=8082
repo1-s3-key=RKAEQCG2EZTSD4IMEC77
repo1-s3-key-secret=CjBPUz62aMFF9U2bvBjLWdunFPPEtjCkWYyFtar0
repo1-s3-verify-tls=n

[global:archive-push]
compress-level=3
```

-  postgresql.conf` settings applicable to pgBackRest 

```
archive_command='pgbackrest --stanza=demo archive-push %p',
archive_mode=on, 
listen_addresses='*',
max_wal_senders=3,
wal_level=replica,
port=5432
```
    

- log file in /var/log/pgbackrest/demo-stanza-create.log
```
...
2021-08-05 19:36:41 522 P00 INFO: stanza-create for stanza-create 'demo' on repo1
ERROR: [101]: TLS error [1:336031996] unknown protocol
2021-08-05 19:36:41 641 P00 INFO: stanza-create command end: aborted with expception [101]
```

7. Describe the issue:
`pgbackrest --stanza=demo stanza-create`

**Comment by dwsteele** [comment]
> ERROR: [101]: TLS error [1:336031996] unknown protocol

pgBackRest only allows TLS connections, so my guess is Ceph is insisting on SSL. This article is old but seems to cover the major causes: https://blog.techstacks.com/2010/03/3-common-causes-of-unknown-ssl-protocol-errors-with-curl.html

**Comment by aqktjcm** [comment]
> pgBackRest only allows TLS connections, so my guess is Ceph is insisting on SSL. This article is old but seems to cover the major causes: https://blog.techstacks.com/2010/03/3-common-causes-of-unknown-ssl-protocol-errors-with-curl.html

Unfortunately, our ceph is configured to only support http connections, neither ssl nor tls protocols are used. As you said, this is the problem. 
I want to know if you have any plans to support the http protocol of s3 endpoint.

**Comment by dwsteele** [comment]
Currently, HTTP support is not on the roadmap.
