### ISSUE TITLE
Build pgbackrest 2.34 without bz2

### ISSUE THREAD

**Issue by hlakshmi** [pgbackrest/pgbackrest#1483]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

Is there a way to build pgbackrest 2.34 from source without bz2 library. Right now I am trying to upgrade it from 2.24 to 2.34 and it complains about bz2 doesn't exist. Can I build without bz2 if I don't care about compressions in my backups?

```
checking for BZ2_bzCompress in -lbz2... no
configure: error: library 'bz2' is required
error: Bad exit status from /var/tmp/rpm-tmp.IO0xHG (%build)
```

1. pgBackRest version: 2.34

2. PostgreSQL version: 13.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS 6, 7

4. Did you install pgBackRest from source or from a package? Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by dwsteele** [comment]
bzip2 is not optional because it is widely available. Optional features are very expensive to maintain. 

CentoOS 6 and 7 both have the required development package, see: https://pgbackrest.org/user-guide-rhel.html#build.

**Comment by hlakshmi** [comment]
Thanks @dwsteele
