### ISSUE TITLE
percentage of progress information

### ISSUE THREAD

**Issue by ccavallie** [pgbackrest/pgbackrest#1490]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.29

2. PostgreSQL version: 11.8

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RH 7.7

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Hello, 
We have a 28 TB postgres instance when we perform a backup with the "--log-level-file" parameter set to "info" we get a log file of more than 100Gb and we had to set the "--log-level-file" parameter to "error" to reduce the size of this file but now we don't have any percentage of backup progress which is useful for an 8 Hours operation. Would it be possible to have a log file with only the last percentage of progress information and not a cumulation of all the progress lines.
Thanks for your response
Christophe

**Comment by dwsteele** [comment]
The plan is to add the percent complete to the lock file and then you'll be able to see it in the `info` command. So now we have:
```
stanza: stanza1
    status: ok (backup/expire running)
```
And we would like:
```
stanza: stanza1
    status: ok (backup running 53%)
```
This seems to be more useful in general. This percentage would also be available in the info JSON for automation.

Thoughts?

**Comment by ccavallie** [comment]
It's a good solution,
Thank's

**Comment by MichaelDBA** [comment]
Is this gonna make it to the info command any time soon?

**Comment by jreidthompson** [comment]
Hi Michael,
there is ongoing work related to this with the intent of having something available in the near future.

**Comment by MichaelDBA** [comment]
Thanks for the quick update!  Most appreciated!

**Comment by dwsteele** [comment]
Closing this issue since there is now a PR for it.
