### ISSUE TITLE
ERROR [041] unable to open file backup.manifest.copy for write: [5] Input/output error

### ISSUE THREAD

**Issue by kong1man** [pgbackrest/pgbackrest#1495]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.16

2. PostgreSQL version: 10.14 (Ubuntu 10.14-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 16.04.5 LTS on both primary and standby DB servers

4. Did you install pgBackRest from source or from a package?
Package: pgbackrest
Maintainer: Debian PostgreSQL Maintainers <team+postgresql@tracker.debian.org>
Version: 2.16-1.pgdg16.04+1

5. Please attach the following as applicable:
  - /etc/pgbackrest/pgbackrest.conf
```ini
[global]
archive-timeout=180
process-max=24
repo1-cipher-pass=REDACTED
repo1-cipher-type=aes-256-cbc
repo1-path=/opt/postgres/backup/pgbackrest
repo1-retention-diff=1
repo1-retention-full=1
spool-path=/opt/postgres/wal/pgbackrest
start-fast=y

[warehouse_prod]
pg1-path=/var/lib/postgresql/10/warehouse_prod
pg1-socket-path=/var/run/postgresql/10/warehouse_prod
```
  - /etc/pgbackrest/conf.d/pgbackrest-standby.conf
```ini
[global]
archive-async=n
backup-standby=y

[warehouse_prod]
pg1-host=<primary-db-host>
pg2-path=/var/lib/postgresql/10/warehouse_prod
pg2-socket-path=/var/run/postgresql/10/warehouse_prod
```

7. Describe the issue:
With a few successful backups over a week ago on this new standby DB (`backup-standby=y`), it has been consistently  failing with the following error 1 week ago.  I had options`--log-level-file=trace --log-subprocess`, but have not been able to identify the root cause from the log.  Please help.
```
2021-08-18 15:48:29.409 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)
2021-08-18 15:48:29.409 P00  ERROR: [041]: unable to open file '/opt/postgres/backup/pgbackrest/backup/warehouse_prod/20210818-115502F/backup.manifest.copy' for write: [5] Input/output error
                                    STACK TRACE:
                                    storage/posix/write:storageWritePosixOpen:98:(this: {StorageWritePosix})
                                    common/io/write:ioWriteOpen:(this: {IoWrite})
                                    storage/storage:storagePut:(file: {type: posix, name: {"/opt/postgres/backup/pgbackrest/backup/warehouse_prod/20210818-115502F/backup.manifest.copy"}, modeFile: 0640, modePath: 0750, createPath: false, syncFile: true, syncPath: false, atomic: false}, buffer: {used: 6200054, size: 6200054, limit: <off>})
                                    perl/exec:perlExec:(void)
                                    main:main:(debug log level required for parameters)
2021-08-18 15:48:29.409 P00  TRACE:         protocol/helper::protocolFree: (void)
2021-08-18 15:48:29.409 P00  TRACE:         protocol/helper::protocolFree: => void
2021-08-18 15:48:29.415 P00  DEBUG:     Main::mainCleanup(): iExitCode = 41
```

There are also a few other errors occasionally showed up, which I am unsure if/how they are related.
```
ERROR: [042]: remote process on '<primary-db-host>' terminated unexpectedly [000]: sh: 0: getcwd() failed: No such file or directory
ERROR: [042]: remote process on '<primary-db-host>' terminated unexpectedly [042]: unable to read line after 1830 second(s) from stdio
```

**Comment by dwsteele** [comment]
`[5] Input/output error` generally indicates hardware issues.

I'd also mention that Ubuntu 16.04 is EOL and pgBackRest 2.16 is pretty old. You should be able to get up to 2.32 or so from apt.postgresql.org. I don't think that will help here, though, as I don't think this error is pgBackRest related.

**Comment by kong1man** [comment]
Blaming hardware is quite questionable because we have been able to complete the 15TB DB (compressed into 3.5TB) in 14 hours only to fail on this particular file, sometimes right at the end, sometimes 50%.  We are checking with our sys admins though.

This could be a separate issue, but the failures have been baffling me over the past week.
```
2021-08-17 02:09:42.636 P37   INFO: backup file /var/lib/postgresql/10/warehouse_prod/base/1/12854 (0B, 100%)
2021-08-17 02:09:43.978 P00   INFO: full backup size = 15956GB
2021-08-17 02:09:43.979 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2021-08-17 02:09:44.562 P00   INFO: backup stop archive = 0000000100039EE2000000DD, lsn = 39EE2/DD4012E0
2021-08-17 02:09:44.719 P00  ERROR: [042]: remote process on '<primary-db-host>' terminated unexpectedly [000]: sh: 0: getcwd() failed: No such file or directory
2021-08-17 02:09:44.952 P00   INFO: backup command end: aborted with exception [042]
```

We rely on an old Ubuntu distribution and have to wait for our sys admins to upgrade them all.  Plus, we cannot update pgBackRest one at a time, because the version on primarys and standbys have the the same.   Upgrades will be difficult at this point.

**Comment by dwsteele** [comment]
> Blaming hardware is quite questionable because we have been able to complete the 15TB DB (compressed into 3.5TB) in 14 hours only to fail on this particular file...

From the gcc reference: `“Input/output error.” Usually used for physical read or write errors.` Probably this could also be caused by driver issues, etc., but in general it means the device cannot be accessed properly.

> sh: 0: getcwd() failed: No such file or directory

Not sure here, but it looks like a misconfiguration in SSH or the user (perhaps home dir?) on `<primary-db-host>`.

**Comment by kong1man** [comment]
You may be right about the storage issue, which was against a shared Gluster storage.  We will work with our sys admins to rectify that, and possibly plan the upgrades.

Thank you for your help.
