### ISSUE TITLE
Point-in-Time Recovery the time format

### ISSUE THREAD

**Issue by huiyalin525** [pgbackrest/pgbackrest#1496]
Hello,I have a question.

When I am using Point-in-Time Recovery,  the time format must be used the specified time format? 
for example: '2021-06-03 22:08:10.017082+00'

Can I use other formats?

**Comment by pgstef** [comment]
Hi,

From a PG point of view, the [recovery_target_time](https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-RECOVERY-TARGET-TIME) setting could indeed support other format. See [datatype-datetime](https://www.postgresql.org/docs/current/datatype-datetime.html) and  [datestyle](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-DATESTYLE) for more information.

That being said, using the ISO format is usually the safest and most readable option. There's a format validation in the [restore code](https://github.com/pgbackrest/pgbackrest/blob/ad5e06399008118d81f41fb103ef2e980343899b/src/command/restore/restore.c#L109).

> HINT: time format must be YYYY-MM-DD HH:MM:SS with optional msec and optional timezone (+/- HH or HHMM or HH:MM)

That is required for the automatic backup set selection. But I guess if you use the latest backup set, you could change the `recovery_target_time` manually after the restore and before starting PG...

It really depends on what your trying to achieve I guess. The best way to know is to describe your need and test it.

Kind regards

**Comment by huiyalin525** [comment]
> HINT: time format must be YYYY-MM-DD HH:MM:SS with optional msec and optional timezone (+/- HH or HHMM or HH:MM)

this is very important，I have this question.Because, having optional msec and optional timezone  is more troublesome in some cases.So I want to use 'YYYY-MM-DD HH:MM:SS' to restore the data

**Comment by pgstef** [comment]
> So I want to use 'YYYY-MM-DD HH:MM:SS' to restore the data

You can definitively do that. If timezone is omitted, local time is assumed.
That should then answer your question ;-)

**Comment by huiyalin525** [comment]
> You can definitively do that. If timezone is omitted, local time is assumed.
That should then answer your question ;-)

thanks a lot
