### ISSUE TITLE
pgBackRest 2.35 on Red Hat 8: configure: error: library 'yaml' is required

### ISSUE THREAD

**Issue by wsescu** [pgbackrest/pgbackrest#1498]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2.35

2. PostgreSQL version:

12.x, 13.x

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

```
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.4 (Ootpa)

$  uname -a
Linux host01 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

4. Did you install pgBackRest from source or from a package?

Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Dear pgBackRest support

I can't compile pgBackRest version 2.35 on Red Hat 8. I do get the following error:

**configure: error: library 'yaml' is required**

```
$ cd pgbackrest/pgbackrest-release-2.35/src/
$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... none needed
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether C compiler accepts -Wno-clobbered... yes
checking for pg_config... yes
checking for PQconnectdb in -lpq... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking libpq-fe.h usability... yes
checking libpq-fe.h presence... yes
checking for libpq-fe.h... yes
checking for EVP_get_digestbyname in -lcrypto... yes
checking for SSL_new in -lssl... yes
checking for pkg-config... yes
checking for xmlSaveToBuffer in -lxml2... yes
checking libxml/parser.h usability... yes
checking libxml/parser.h presence... yes
checking for libxml/parser.h... yes
checking for yaml_parser_initialize in -lyaml... no
configure: error: library 'yaml' is required
```

However, the libyaml library is installed.

```
$ rpm -qa | grep yaml
libyaml-0.1.7-5.el8.x86_64
python3-pyyaml-3.12-12.el8.x86_64
```

Configuring the previous version (2.34) on the same host works perfectly.

Cheers,
William

**Comment by dwsteele** [comment]
`libyaml-devel` is now a build-only (i.e. is not linked to pgbackrest) dependency. See https://pgbackrest.org/user-guide-rhel.html#build.

**Comment by wsescu** [comment]
Dear @dwsteele 

Thanks. I see, I need to install the libyaml-devel package, which can only be done, by enabling the
CodeReady Linux Builder repository on Red Hat 8.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/package_manifest/index#CodeReadyLinuxBuilder-repository

Cheers
William

**Comment by dwsteele** [comment]
Not sure why Redhat has made getting to some dev libs harder than others, but there it is. Like I said, this only needs to be installed on the *build* system.
