### ISSUE TITLE
If define pg1-hosts equal local hostname on local PostgreSQL machine archive-push doesn't work

### ISSUE THREAD

**Issue by skilyazhnev** [pgbackrest/pgbackrest#1499]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.33

2. PostgreSQL version: 12\11

3. Operating system/version: oracle Linux 7\8

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

```
[global]
log-level-file=detail
log-level-console=info
log-path=/var/log/pgbackrest
repo1-path=/pg_test
repo1-type=s3
repo1-host-user=backup
repo1-s3-endpoint=minio.local
repo1-s3-port=443
repo1-s3-bucket=backups
repo1-s3-verify-tls=n
repo1-s3-key=backup
repo1-s3-key-secret=backup_password
repo1-s3-region=eu-west-3
process-max=6
compress-level=8
repo1-retention-diff=14
repo1-retention-full=2
delta=y
#backup-standby=y
archive-timeout=50
start-fast=y
archive-copy=y
io-timeout=360

[patroni]
pg1-path=/var/lib/pgsql/12/data
pg2-path=/var/lib/pgsql/12/data
pg3-path=/var/lib/pgsql/12/data
pg1-host=hostname1.local
pg2-host=hostname2.local
pg3-host=hostname3.local
```
    

- `postgresql.conf` settings applicable to pgBackRest 

```
archive_command = 'pgbackrest --stanza=patroni archive-push %p'
archive_mode = 'True'
listen_addresses = '0.0.0.0'
max_wal_senders = '10'
wal_level = 'replica'
port = '5432'
```

```
<msg>    0 611fbde3.e8e5 2021-08-24 17:25:13.079 MSK [59621] LOG:  archive command failed with exit code 72
<msg>    0 611fbde3.e8e5 2021-08-24 17:25:13.079 MSK [59621] DETAIL:  The failed archive command was: pgbackrest --log-level-console=debug --stanza=patroni archive-push pg_wal/00000002.history
2021-08-24 17:25:14.088 P00  DEBUG:     common/io/socket/common::sckInit: (block: false, keepAlive: true, tcpKeepAliveCount: 0, tcpKeepAliveIdle: 0, tcpKeepAliveInterval: 0)
2021-08-24 17:25:14.088 P00  DEBUG:     common/io/socket/common::sckInit: => void
2021-08-24 17:25:14.088 P00   INFO: archive-push command begin 2.33: [pg_wal/00000002.history] --archive-timeout=50 --compress-level=8 --exec-id=90266-d5af22cb --io-timeout=360 --log-level-console=debug --log-level-file=detail --l>
2021-08-24 17:25:14.088 P00  DEBUG:     config/load::cfgLoad: => void
2021-08-24 17:25:14.088 P00  DEBUG:     command/archive/push/push::cmdArchivePush: (void)
2021-08-24 17:25:14.088 P00  DEBUG:     protocol/helper::pgIsLocal: (pgIdx: 0)
2021-08-24 17:25:14.088 P00  DEBUG:     protocol/helper::pgIsLocal: => false
2021-08-24 17:25:14.088 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)
ERROR: [072]: archive-push command must be run on the PostgreSQL host
2021-08-24 17:25:14.088 P00   INFO: archive-push command end: aborted with exception [072]
2021-08-24 17:25:14.088 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)
2021-08-24 17:25:14.088 P00  DEBUG:     common/lock::lockRelease: => false
2021-08-24 17:25:14.088 P00  DEBUG:     common/exit::exitSafe: => 72
2021-08-24 17:25:14.088 P00  DEBUG:     main::main: => 72
<msg>    0 611fbde3.e8e5 2021-08-24 17:25:14.089 MSK [59621] LOG:  archive command failed with exit code 72
<msg>    0 611fbde3.e8e5 2021-08-24 17:25:14.089 MSK [59621] DETAIL:  The failed archive command was: pgbackrest --log-level-console=debug --stanza=patroni archive-push pg_wal/00000002.history
```

7. Describe the issue:

When I define the pg1-host in pgbackrest.conf and the file is located locally (pg1-host == hostname\ip local machine) on the PostgreSQL host (I don't have repository host only minio)
then function "pgIsLocal" return always False and pgbackrest return error "ERROR: [072]: archive-push command must be run on the PostgreSQL host".

If I delete pg1-host from pgbackrest.conf then pgIsLocal return True and I can manage pgbackrest backup and archive-push start work.
Its problem for creating the same config file on hosts and complicates maintenance scripts.

My question is: is it an architectural feature of pgbackrest or a bug?

If it is the first case we need to modified Doc where explicitly write that it is impossible to define pg1-hosts for the local file on PostgreSQL.

**Comment by pgstef** [comment]
Hi,

AFAIK, this is not a bug but a consequence of the internal implementation of `pg*-host`. It shouldn't be used for the locally running cluster (or it would try to access the pg cluster with a remote connection rather than a local one).

Furthermore, that really depends on what you're trying to do. If config need to be the same everywhere, and you take backup from the primary, then you only need pg1-path. Nothing else.

The other possibility is to use a dedicated repo host and define your 3 pg cluster there. It will then be able to detect which one is the primary to backup (or the standby) even in case of failover without you having to change anything in the config...

I understand this can be seen as a "limitation" but imho, there are some possible workarounds.

Hope this helps,
Kind regards

**Comment by skilyazhnev** [comment]
Thanks, that makes sense. 
But I still think it would be nice to mark this in the docs. 
Or this issue will be alert for  guys like me :D

**Comment by dwsteele** [comment]
I'd rather not document this since there are many things *not* to do and it is hard to document them all. But also because we are working on a solution to this by being able to mark a pg or repo host as *local*. When we have that we'll document it.
