### ISSUE TITLE
Incremental backup to S3 fails

### ISSUE THREAD

**Issue by jcollie** [pgbackrest/pgbackrest#1505]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.35
2. PostgreSQL version:
13.4
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Alpine 3.14
4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Incremental backup to S3 fails often (but not always). Error is "ERROR: [055]: pg_control must be present in all online backups" (full debug log attached). When the backup fails immediately retrying almost always succeeds. I've tried both Amazon and Backblaze as S3 backends.

[pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/7110354/pgbackrest.log)

**Comment by jcollie** [comment]
I rebuilt my containers around Rocky Linux 8.4 with packages for PostgreSQL 13.4 and pgBackrest 2.35 from yum.postgresql.org and am seeing the same problem.

**Comment by jcollie** [comment]
Increased memory on the pods to 16GB and am still seeing the issue.

**Comment by pgstef** [comment]
Hi,

Given the logs, the incremental backup seems very fast 13:39:26 -> 13:39:32. Without the delta option enabled, the backup command will rely on timestamps to build the list of files to save. I'm wondering if there could be an issue with your time sync somewhere. (Like the HINT suggests: `HINT: is something wrong with the clock or filesystem timestamps?`)

Could you perhaps try adding the `--delta` option to your config or command ?

Kind regards

**Comment by jcollie** [comment]
Hmm, this is all on a Kubernetes cluster and I checked to make sure that time was in sync on all of the nodes. I've added "--delta" to my config and so far so good. What confuses me is that the incremental backup will fail but an immediate retry will succeed.

**Comment by dwsteele** [comment]
> What confuses me is that the incremental backup will fail but an immediate retry will succeed.

This is possible if the timestamps are not being updated reliably or there is a long delay before they are updated. If `delta` works then I would worry about the reliability of the filesystem that postgres is on. If it is not updating timestamps correctly is it honoring fsync?

**Comment by jcollie** [comment]
It's being backed by cephfs which is about as solid a network filesystem as you get. I have an older postgresql (12.2)/pgbackrest(2.20) cluster on this same system without problems, although I have never run incremental backups on the older database before, only fulls. pgbackrest is also always running inside the same container as postgresql so filesystem caches being out of sync shouldn't be an issue.

**Comment by dwsteele** [comment]
> It's being backed by cephfs which is about as solid a network filesystem as you get.

OK, but I'm pretty sure this is the first time we have seen this pg_control timestamp issue in the wild, so *something* is definitely not right.
