### ISSUE TITLE
stanza-create command requires option: repo1-s3-endpoint

### ISSUE THREAD

**Issue by Tekchanddagar** [pgbackrest/pgbackrest#1510]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.35

2. PostgreSQL version: 13.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.04

4. Did you install pgBackRest from source or from a package? Installed from source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We are using Digitalocean Cloud and our Database machine is hosted on Digitalocean cloud. We have installed the PGBACKREST on our postgresql machine itself. We are able to take the DB backup locally using pgbackrest. But we want to use S3 repository so we keep our backup over S3 bucket. 

But when  I run the below command to create the stanza we are getting error:

`postgres@postgresql-audit:~$ pgbackrest --stanza=test --log-level-console=info stanza-create`

ERROR:

`ERROR: [037]: stanza-create command requires option: repo1-s3-endpoint`

As per my knowledge the `s3-endpoint` can be used only with ec2 instance. And its used when ec2 instance don't have internet access and we want to access S3 bucket using ec2 instance. Then we can assign a role and S3 VPC endpoint to that ec2 instance.

I am very new guy to pgbackrest. So sorry my question can be silly. 

I have go throug the pgbackrest documentation as  well but unable to fix the issue.
[PGBACKRESTDOC](https://pgbackrest.org/user-guide.html)

Can you please help me how we can use the S3 repository with Digitalocean Server using PGBACKREST tool.

Any help will be appriciated.

Thank You
`

**Comment by hunleyd** [comment]
A working S3 config:
```
repo1-s3-bucket: [your bucket]
repo1-s3-key: [your s3 key]
repo1-s3-key-secret: [your s3 key secret]
repo1-s3-region: "us-east-2" (adjust to whatever region your bucket is in)
repo1-s3-endpoint: "s3.us-east-2.amazonaws.com" (adjust to whatever region)
repo1-type: "s3"
repo1-path: [path in the bucket to create the stanza under]
```

**Comment by Tekchanddagar** [comment]
@hunleyd , Thank You for your quick response.
Now the error is changed. Its seems its permission related error on S3 bucket.

I have provided the below permissions on S3 bucket:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::test-ml-lifecycle/*"
        }
    ]
}
```

And below is the config of my `pgbackrest.conf` 

```
[global]
#repo1-path=/var/lib/pgbackrest
repo1-type=s3
repo1-s3-bucket=test-ml-lifecycle
repo1-path=/psql-backup
repo1-s3-endpoint=s3.eu-central-1.amazonaws.com
repo1-s3-key=abc
repo1-s3-key-secret=xyz
repo1-s3-region=eu-central-1
repo1-retention-full=2
repo1-retention-diff=1

[test]
pg1-path=/var/lib/postgresql/13/main
log-level-console=error
log-level-file=debug

[global:archive-push]
compress-level=3
```

ERROR:

`ERROR: [039]: HTTP request failed with 403 (Forbidden):
2021-09-12 13:47:46.926 P00   INFO: stanza-create command end: aborted with exception [039]
`

Do we need to provide any other permission on S3 bucket?

Thank You

**Comment by pgstef** [comment]
Hi,

I've never really used AmazonS3 myself but this seems to be documented in the [user-guide](https://pgbackrest.org/user-guide-rhel.html#s3-support). If I read it correctly, you'd need to add `s3:ListBucket`.

Hope this helps,
Kind regards

**Comment by Tekchanddagar** [comment]
@pgstef , Thank You for your response.
Yes, it was S3 permission issue. Its fixed.

But I have one more question how pgbackrest store the WAL backup?
We added the below entry in our  `postgresql.conf`

```
archive_command = 'pgbackrest --stanza=test archive-push %p'
```

Let say we set the cron entry for 2 time per day for backup then it will took the backup and store over S3.

But we want to reduce the PITR time using pgbackrest then how it upload/store the WAL on S3?

Thank You

**Comment by pgstef** [comment]
That's the basics behind PG [continuous-archiving](https://www.postgresql.org/docs/current/continuous-archiving.html).

Simply said, you need a base backup + wal archives to perform a recovery. But, as long as you have all the wal archives needed, an older base backup also allows to perform the same recovery, only slower.

So, the number of backups (per day / week) is a matter of recovery time objective and disk space. I usually see 1 full backup per week and 1 diff backup per day being enough (with `repo1-retention-full=5`, `repo1-retention-diff=2`) to meet most of the retention and PITR use-cases.

That being said, when `archive_mode` is enabled and `archive_command` properly set-up, each time a new WAL segment will be generated, PG will require to archive the old one before being able to remove/recycle it. (That's easy to see within `pg_wal/archive_status` i.e.)

New wal segments are generated when : the previous one is full (by default 16MB), `archive_timeout` is reached, `pg_switch_wal()` is called. So, no matter when you trigger your backups, PG will continuously send its wal archives to the S3 bucket using the `archive_command`.

You should also monitor and make sure the archiving process is working correctly. Something like:
```bash
$ ps -ef |grep postgres |grep archiver
postgres    5326    5319  0 07:12 ?        00:00:00 postgres: main: archiver last was 00000001000000000000005C
$ psql -x -c "SELECT * FROM pg_stat_archiver;"   
-[ RECORD 1 ]------+------------------------------
archived_count     | 100
last_archived_wal  | 00000001000000000000005C
last_archived_time | 2021-09-13 07:30:45.074097+00
failed_count       | 0
last_failed_wal    | 
last_failed_time   | 
stats_reset        | 2021-09-13 07:12:42.796389+00
```

Hope this helps,
Regards

**Comment by pgstef** [comment]
Hi,

First, please don't comment on closed issues.

> Nice; Where do you use/enter these parameters?

Most often, in the configuration file, in the `[global]` section. See the [user-guide](https://pgbackrest.org/user-guide.html#s3-support) for more information.

Kind regards

**Comment by Tekchanddagar** [comment]
You need to use these parameter inside /etc/pgbackrest.conf file

Thanks
