### ISSUE TITLE
Old version and New version do not match resumable

### ISSUE THREAD

**Issue by fatihmtekin** [pgbackrest/pgbackrest#1511]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.35

2. PostgreSQL version:12.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?
package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

My pgbackrest version was 2.30, but my scheduled backup process was failed. Then I updated pgbackrest version to 2.35. After that, I ran a new backup process, i got this WARN; and there is no any event/activity/process for a long time.

Is there a way to start without resume option?
or
how can i make it compatible 2.30 - 2.35?

2021-09-13 08:53:24.002 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2021-09-13 08:53:27.611 P00   INFO: backup start archive = 000000060000502A000000D4, lsn = 502A/D40694C8
2021-09-13 08:53:27.611 P00   INFO: wait for replay on the standby to reach 502A/D40694C8
2021-09-13 08:53:33.219 P00   INFO: replay on the standby reached 502A/D40694C8
WARN: backup '20210913-064113F' cannot be resumed: new pgBackRest version '2.35' does not match resumable pgBackRest version '2.30'

Thanks a lot.

**Comment by pgstef** [comment]
Hi,

Usually, newer versions should be able to info/restore old backups. But for various reasons, including consistency, backups are only [resumable](https://github.com/pgbackrest/pgbackrest/blob/c38d6926d6c9aa01b895a28e66fc0aa6965350a3/src/command/backup/backup.c#L676) when using the same version.

In your case, taking a new backup using `--no-resume` will allow to take a new backup will the new version and purge the failed backup.

Kind Regards

**Comment by pgstef** [comment]
With the last release, copied files have been moved from INFO log level to [DETAIL](https://github.com/pgbackrest/pgbackrest/blob/c38d6926d6c9aa01b895a28e66fc0aa6965350a3/src/command/backup/backup.c#L1102). See the [release notes](https://github.com/pgbackrest/pgbackrest/releases/tag/release/2.35).

If you raised your `log-level-file` to at least `detail`, you should look at it to find out if there's some activity there.

Kind regards,

**Comment by fatihmtekin** [comment]
Oh sorry, I saw the logs in stanza-backup.log file. Backup process has been started. I couldn't understand why when I couldn't see the information in the console. Thank you for your help.
Thank you so much.
