### ISSUE TITLE
Unable to create stanza with pgbackrest and minio

### ISSUE THREAD

**Issue by hlakshmi** [pgbackrest/pgbackrest#1512]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.34

2. PostgreSQL version: PG 13.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS 6.5

4. Did you install pgBackRest from source or from a package? - Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Running into the following issue when trying to create a stanza with minio/s3
```
pgbackrest --config-path=/home/pce --stanza=trafficdb_coordinator_stanza stanza-create
2021-09-16 00:34:38.871 P00   INFO: stanza-create command begin 2.34: --config-path=/home/pce --exec-id=2944-c0b0c8bc --lock-path=/var/tmp/illumio_pce_data --log-level-console=detail --log-level-file=info --log-path=/var/illumio_pce_data/log --pg1-path=/var/illumio_pce_data/persistent/traffic_datastore --pg1-port=5532 --repo1-path=/repo/traffic_coordinator_backups --repo1-s3-bucket=pgbackrest --repo1-s3-endpoint=minio.local --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=eu-west-3 --no-repo1-storage-verify-tls --repo1-type=s3 --stanza=trafficdb_coordinator_stanza
2021-09-16 00:34:39.299 P00   INFO: stanza-create for stanza 'trafficdb_coordinator_stanza' on repo1
ERROR: [039]: HTTP request failed with 403 (Forbidden):
       *** Path/Query ***:
       /repo/traffic_coordinator_backups/archive/trafficdb_coordinator_stanza/archive.info
       *** Request Headers ***:
       authorization: <redacted>
       content-length: 0
       host: pgbackrest.minio.local
       x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
       x-amz-date: <redacted>
       *** Response Headers ***:
       accept-ranges: bytes
       content-length: 365
       content-type: application/xml
       date: Thu, 16 Sep 2021 07:55:40 GMT
       server: MinIO
       vary: Origin
2021-09-16 00:34:39.329 P00 DETAIL: statistics: {"http.client":{"total":2},"http.request":{"total":1},"http.session":{"total":1},"socket.client":{"total":2},"socket.session":{"total":1},"tls.client":{"total":2},"tls.session":{"total":1}}
2021-09-16 00:34:39.329 P00   INFO: stanza-create command end: aborted with exception [039]
```

Here is my pgbackrest.conf
```
[pce@db0-2x2harishvc1 ~]$ cat pgbackrest.conf

[global]
repo1-path=/repo/traffic_coordinator_backups


repo1-type=s3
repo1-s3-endpoint=minio.local
repo1-s3-bucket=pgbackrest
repo1-s3-verify-tls=n
repo1-s3-key=******
repo1-s3-key-secret=**********
repo1-s3-region=eu-west-3


lock-path=/var/tmp/illumio_pce_data
log-path=/var/illumio_pce_data/log
log-level-console=detail
log-level-file=info
start-fast=y
repo1-retention-full=2
repo1-retention-archive-type=full
repo1-retention-archive=1

[global:archive-push]
compress-level=3

[global:restore]
process-max=4

[global:backup]
process-max=1

[trafficdb_coordinator_stanza]
pg1-path=/var/illumio_pce_data/persistent/traffic_datastore
pg1-port=5532
```
Please let me know if anyone has run into this issue. I am not sure if there's an issue with the MinIO setup or there's a configuration issue with my pgbackrest setup. Please advice and let me know if you need additional details.

**Comment by pgstef** [comment]
Hi,

Have you created the bucket (pgbackrest) and the repo-path (/repo/traffic_coordinator_backups) inside your MINIO_VOLUMES?

Your pgbackrest configuration looks good to me. Perhaps using s3cmd would help you create/list content of the bucket and then make sure your minio setup is fine ?

Kind regards

**Comment by hlakshmi** [comment]
Thanks @pgstef for the quick response. I have confirmed that the bucket `pgbackrest` is created and the repo-path `/repo/traffic_coordinator_backups` exist. Also I am following the guidelines as per your blog (thanks for that) here: https://pgstef.github.io/2019/07/19/pgbackrest_s3_configuration.html

Here is my minio.conf
```
[root@mikecarlton-centos7 ~]# ls -lh /opt/minio/data/pgbackrest/
total 0
drwxr-xr-x. 5 minio minio 87 Sep 16 00:24 repo
[root@mikecarlton-centos7 ~]# ls -lh /opt/minio/data/pgbackrest/repo/traffic_coordinator_backups/
total 0
[root@mikecarlton-centos7 ~]# cat /opt/minio/minio.conf
MINIO_VOLUMES=/opt/minio/data
MINIO_DOMAIN=minio.local
MINIO_OPTS="--certs-dir /opt/minio/certs --address :443 --compat"
MINIO_ROOT_USER=xxxxxxx
MINIO_ROOT_PASSWORD=xxxxxx
```

**Comment by pgstef** [comment]
> Thanks @pgstef for the quick response. I have confirmed that the bucket `pgbackrest` is created and the repo-path `/repo/traffic_coordinator_backups` exist. Also I am following the guidelines as per your blog (thanks for that) here: https://pgstef.github.io/2019/07/19/pgbackrest_s3_configuration.html

That's a very old blog post. I didn't used it lately. It was intended to work on CentOS-7 but you mentioned you're using CentOS-6. That might be a clue. I pretty much only use the minio docker container recently.

How did you created your bucket (or verified it exists) ?

> Here is my minio.conf
> 
> ```
> [root@xxxxx-centos7 ~]# ls -lh /opt/minio/data/pgbackrest/
> total 0
> drwxr-xr-x. 5 minio minio 87 Sep 16 00:24 repo
> [root@xxxxx-centos7 ~]# ls -lh /opt/minio/data/pgbackrest/repo/traffic_coordinator_backups/
> total 0
> [root@xxxxx-centos7 ~]# cat /opt/minio/minio.conf
> MINIO_VOLUMES=/opt/minio/data
> MINIO_DOMAIN=minio.local
> MINIO_OPTS="--certs-dir /opt/minio/certs --address :443 --compat"
> MINIO_ROOT_USER=xxxxxxx
> MINIO_ROOT_PASSWORD=xxxxxx
> ```
> 
> Is there a place where I can check more detailed minio logs? Also, just want to add that minio and Postgres are running on separate nodes.
> 
> P.S: When I try to create a stanza from the same node where minio is running, everything works as expected.

Creating the stanza from the MinIO server ? That's weird, I never installed pgBR on the server (or container) where I installed MinIO.

Perhaps the only difference I see between your pgbr config and mine is [repo1-s3-uri-style=path](https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-uri-style) (which is not the default). And also `repo1-s3-verify-tls` -> `repo1-storage-verify-tls`.

I'm not a MinIO expert, so I'm not sure to be able to help you further to set it up.

Kind regards

**Comment by hlakshmi** [comment]
I forgot to mention that I figured out the issue. Here's the issue in my case so that it may be useful for others. There's a timing difference between my database server and the server where MinIO was running on. So pgbackrest stanza-create fails with the error 403 (seems misleading). Once I did an `ntpupdate` it started working.

**Comment by dwsteele** [comment]
> error 403 (seems misleading)

That error is from MinIO so not a lot we can do about it. Glad you figured it out, though.
