### ISSUE TITLE
Pass a 'yes' on stanza-create prompt when connecting to remote host?

### ISSUE THREAD

**Issue by dimidir** [pgbackrest/pgbackrest#1514]
1. pgBackRest version: 
**2.35**

2. PostgreSQL version: 
**Ubuntu 13.4-1.pgdg18.04+1**

3. Operating system/version: 
**2x 18.04**

4. Did you install pgBackRest from source or from a package? 
**Installed from source**

5. Please attach the following as applicable:
```
# stanza_backup.conf
[stanzaname]
pg1-host=Postgres-1
pg1-path=/datadisk/pgClusterA

[global]
repo1-path=/datadisk/pgbackrest/pgClusterA_repo1
repo1-retention-full=365
repo1-retention-full-type=time
repo1-retention-diff=300
delta=y
#start-fast=y
repo1-cipher-pass=i2eLkq
repo1-cipher-type=aes-256-cbc
log-level-console=info
log-level-file=detail
log-path=/datadisk/pgbackrest/log
#process-max=3


[global:archive-push]
compress-level=3
```
```
#stanza_postgres.conf
[stanzaname]
pg1-path=/datadisk/pgClusterA

[global]
repo1-host=Backup-1
repo1-host-user=postgres
delta=y
#start-fast=y
repo1-cipher-pass=i2eLkq
repo1-cipher-type=aes-256-cbc
log-level-console=info
log-level-file=debug
log-path=/datadisk/pgbackrest/log
#process-max=3


[global:archive-push]
compress-level=3
```

7. Describe the issue:

I am trying to create a stanza via script respectively via configuration mgmt tool (saltstack) on the backup repository server instance of my pgbackrest installation. 

After setting up the passwordless ssh crendetials on both pg1 and repo machines I am only able to create a stanza (on backup/repo machine) when actively dialed in and manually executing the stanza-create command in the shell. (postgres user was used for both pg cluster and pgbackrest)

`sudo -u postgres pgbackrest --stanza=stanzaname --log-level-console=info stanza-create`

Due to the dedicated server repo I get aksed to confirm the host connection with 'yes' + Enter for pgbackrest to connect to the pg machine and create that thing. Works like a charm.  

Now when I try to go through this procedure (on first connections only ofc) automatically with a set flag 'yes' i.e. I get a connection authentication cannot be established:

```
WARN: unable to check pg-1: [UnknownError] remote-0 process on 'Postgres-1' terminated unexpectedly [255]: Host key verification failed.
ERROR: [056]: unable to find primary cluster - cannot proceed
P00   INFO: stanza-create command end: aborted with exception [056]
```

So I need some workaround for this command to accept the authentication prompt. What puzzles me is that even if I connect to the host prior to stanza-create command to accept/add the new host via

```
#from root shell
runuser postgres -c "ssh postgres@postgres.host.tld -tt -o StrictHostKeyChecking=accept-new" 
#or from main user shell
sudo -u postgres ssh postgres@postgres.host.tld -tt -o StrictHostKeyChecking=accept-new

```
with the output: 
`Warning: Permanently added 'postgres.host.tld,10.0.1.4' (ECDSA) to the list of known hosts.`

Still after that the stanza-create command asks for acceptance: 

```
The authenticity of host 'postgres-1 (10.0.1.4)' can't be established.
ECDSA key fingerprint is SHA256:Wxpy3Z8rbWZN3x3xqq0fADXlzePLXfEdat2q1rGTJes.
Are you sure you want to continue connecting (yes/no)?
```

(notes: Everything on private internal network. No firewalls, iptables so on set. After manually confirming with 'yes' everything works fine.)

I tried to pass a 'yes' in several different ways as a manual command for now: 

```
sudo -u postgres pgbackrest --stanza=stanzaname --log-level-console=info stanza-create <<< "yes"

yes | sudo -u postgres pgbackrest --stanza=stanzaname --log-level-console=info stanza-create

echo "yes" | sudo -u postgres pgbackrest --stanza=stanzaname --log-level-console=info stanza-create

printf "yes" | sudo -u postgres pgbackrest --stanza=stanzaname --log-level-console=info stanza-create
```

So any idea why it needs another confirmation?
or
How do I pass a 'yes' to the stanze-create command?

Thanks!

**Comment by pgstef** [comment]
Hi,

> How do I pass a 'yes' to the stanze-create command?

Short answer, you don't.

That's an SSH config issue. When I'm building a new test cluster, I usually trigger a first connection to test the ssh connection with something like: `ssh -o ConnectTimeout=10 -o BatchMode=yes -o StrictHostKeyChecking=no user@host uname -a`. That's often enough.

But it really depends on your infra and ssh configuration.

Regards,

**Comment by dimidir** [comment]
That's what I thougt.. :/
Will have to try out some configs in future then.

Thank you anyway for replying!
