### ISSUE TITLE
timeout issue with archive/.../*.gz.pgbackrest.tmp

### ISSUE THREAD

**Issue by jw1u1** [pgbackrest/pgbackrest#1522]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.31

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS Linux release 7.8.2003 

4. Did you install pgBackRest from source or from a package? rpm

5. Please attach the following as applicable:
 
7. Describe the issue:

After a disk full incident pgbackrest left a file in the WAL archive  "archive/.../*.gz.pgbackrest.tmp" with zero size.
This file made all further archiving retries fail without a specific error message.
At least the Error Message should be more precise.

**Comment by dwsteele** [comment]
It would be helpful if you would provide both the original error message and the retry error message. It's hard to know what you mean by "less precise" without examples.

**Comment by jw1u1** [comment]
It just said archiving failed after running it manually. 
This was probably due to a stuck parallel process, that i had to kill manually:

-------------------PROCESS START-------------------
2021-10-05 08:32:43.275 P00   INFO: archive-push:async command begin 2.31: [/var/lib/pgsql/data/9.6/ngr_cl/pg_xlog] --archive-async --archive-push-queue-max=989073509376 --exec-id=16415-a69b
f895 --log-level-console=off --log-level-stderr=off --pg1-path=/var/lib/pgsql/data/9.6/ngr_cl --process-max=2 --repo1-host=dbo-pg-backup-prod.accdb.server.lan --spool-path=/var/lib/pgsql/wal
s/spool --stanza=ngr
2021-10-05 08:32:43.276 P00   INFO: push 1 WAL file(s) to archive: 00000005000153520000007E
2021-10-05 12:14:04.850 P00   WARN: local-1 process terminated unexpectedly [63]

**Comment by dwsteele** [comment]
`[63]` is the error code return when a process is terminated (https://github.com/pgbackrest/pgbackrest/blob/release/2.35/src/build/error/error.yaml#L45) and in that case there won't be a more detail error given.

However, our plan is to map these return codes back into text so it would at lease say: `local-1 process terminated unexpectedly [TermError]`.

**Comment by dwsteele** [comment]
We've made improvements in both error reporting and the process getting stuck in 2.35.

**Comment by dwsteele** [comment]
More improvements were made in this area for 2.36, so closing. Let us know if you still see similar issues after upgrading to 2.36.
