### ISSUE TITLE
ERROR: [103]: unable to find a valid repository: 

### ISSUE THREAD

**Issue by amarty76** [pgbackrest/pgbackrest#1523]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.35

2. PostgreSQL version:
PostgreSQL 13.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Database server : Red Hat Enterprise Linux Server release 7.9 (Maipo)
Repository host :  Red Hat Enterprise Linux Server release 7.9 (Maipo)

4. Did you install pgBackRest from source or from a package?
from source 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
on repo side 

[X4IT3]
pg1-host=gvecsl8500dds
pg1-port=5433
pg1-path=/grdata/postgres/X4IT3/instance
pg1-host-user=postgres

[global]
log-level-file=detail
repo1-path=/grdata/postgres/pgbackrest
repo1-retention-full-type=time
repo1-retention-full=30
repo1-retention-diff=1
process-max=2
start-fast=y

on database side 
[X4IT3]
pg1-path=/grdata/postgres/X4IT3/instance
pg1-port=5433
pg1-host-user=postgres
spool-path=/grdata/postgres/archive/X4IT3
archive-async=y

[global]
log-level-file=detail
repo1-host=gvecsl6840ids
repo1-host-user=postgres

[global:archive-push]
compress-level=3
process-max=2

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

archive_mode = 'on'
archive_command = 'pgbackrest --stanza=X4IT3 archive-push %p'
listen_addresses = '*'
max_wal_senders = 10
wal_level = replica
port = 5433

    - errors in the postgresql log file before or during the time you experienced the issue

2021-10-05 10:34:36.357 GMT [23650]: [50-line] user=,db=,remote=,app= LOG:  archive command failed with exit code 103
2021-10-05 10:34:36.357 GMT [23650]: [51-line] user=,db=,remote=,app= DETAIL:  The failed archive command was: pgbackrest --stanza=X4IT3 archive-push pg_wal/000000040000004B00000006
ERROR: [103]: unable to find a valid repository:
       repo1: [JsonFormatError] expected '{' at ''

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We have installed pgbackrest with a repository host and a remote database server 
we were able to make the system works properly 
and we detect that if the user postgres where the repository host reside receive a mail (file /var/spool/mail/postgres not empty)
everything crash (all commands info push, backup ...etc) with the strange error : unable to find valid repository.

I try in debug mode (from database host) also the info command that fail with the same error see attachment
pgbackrest --stanza=X4IT3 --log-level-console=debug info

[pgbackrest-info-in- debug.txt](https://github.com/pgbackrest/pgbackrest/files/7285201/pgbackrest-info-in-.debug.txt)

after reseting the file  /var/spool/mail/postgres to 0 
all is working properly again.

I'm not able to provide explanation between the symptom(crash) and the identified cause(mail in the backup user)
reason of my ticket. 
ssh is probably the cause as the same command works localy on the repo server 
but we as we are able to remote ssh between the 2 hosts without error or warning, and only the /var/spool/mail/postgres not empty seems causing trouble.

regards

**Comment by dwsteele** [comment]
My guess is new mail notifications are being sent and messing up the protocol session. You should try disabling mail checking for the postgres user: https://unix.stackexchange.com/questions/180571/turn-off-mail-notification-in-terminal/180573.

**Comment by amarty76** [comment]
hello thanks for your answer
i have added the 
export MAILCHECK=0
in .bashrc in both nodes and it's the same result 
We tried as we are on Rhat to set it to -1 but it's not better neither.

**Comment by amarty76** [comment]
We try to trace the execution between the working and non working run 
it seems an \n is causing the issue somewhere (in line 616)

[CrashTrace - Checkline616.txt](https://github.com/pgbackrest/pgbackrest/files/7286387/CrashTrace.-.Checkline616.txt)
[WorkingTrace -checkline616.txt](https://github.com/pgbackrest/pgbackrest/files/7286389/WorkingTrace.-checkline616.txt)

**Comment by dwsteele** [comment]
Thank you for the logs. An extra LF is being output which breaks the protocol handshake. That's where this message is coming from: `[JsonFormatError] expected '{' at ''`.

We use `ssh -o LogLevel=error` to suppress banners but the mail notifications are output by the shell. In 2.35 I don't see a way around this. It's possible that we could scan until we see our greeting but I'm not sure if that will work well because the notification may come at any time.

For now, I think you need to find a way to suppress new mail notifications. It may be that the link I sent you is not applicable to your system, but I think the general idea is correct.

It may also be helpful to configure `command` in `authorized_keys` as specified in https://pgbackrest.org/user-guide-rhel.html#repo-host/setup-ssh. This may bypass the shell and execute `pgbackrest` directly.
