### ISSUE TITLE
pgBackRest complains when the stanza name starts with the word 'global'

### ISSUE THREAD

**Issue by alhroub** [pgbackrest/pgbackrest#1524]
1. pgBackRest version:
2.35

2. PostgreSQL version:
10

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Centos 7

4. Did you install pgBackRest from source or from a package?
From a package.

5. Please attach the following as applicable:
[pgbackrest@repository ~]$ cat /etc/pgbackrest/pgbackrest.conf
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y
log-level-console=info
log-level-file=info

[pgbackrest@repository ~]$ cat /etc/pgbackrest/conf.d/global_qa.conf
[global_qa]
pg1-host=pg-primary
pg1-path=/var/lib/pgsql/10/data

[postgres@pg-primary ~]$ cat /etc/pgbackrest/pgbackrest.conf
[global]
repo1-host=repository
log-level-console=info
log-level-file=info

[postgres@pg-primary ~]$ cat /etc/pgbackrest/conf.d/global_qa.conf
[global_qa]
pg1-path=/var/lib/pgsql/10/data

postgresql.conf:

listen_addresses = '*'
wal_level = replica
archive_mode = on
archive_command = 'pgbackrest --stanza=global_qa archive-push %p'
max_wal_senders = '10'
hot_standby = on

7. Describe the issue:
We recently tried to call one of our stanzas global_qa and pgBackRest didn’t like it and we got this error:

$ pgbackrest --stanza=global_qa stanza-create
WARN: configuration file contains stanza-only option 'pg1-host' in global section 'global_qa'
WARN: configuration file contains stanza-only option 'pg1-path' in global section 'global_qa'
ERROR: [037]: stanza-create command requires option: pg1-path
       HINT: does this stanza exist?
       
pgBackRest didn’t complain when we renamed the stanza to something else.

**Comment by dwsteele** [comment]
Should be fixed in #1525. Please have a look and approve if it looks good. Thanks!
