### ISSUE TITLE
Get S3 credentials from TMDE in AWS ECS containers

### ISSUE THREAD

**Issue by groner** [pgbackrest/pgbackrest#1532]
AWS ECS runs containers. In ECS containers AWS credentials are obtained from the task metadata endpoint, instead of the instance metadata service used in EC2 instances.

From https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
> ```
> :; curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
>
> {
>     "AccessKeyId": "ACCESS_KEY_ID",
>     "Expiration": "EXPIRATION_DATE",
>     "RoleArn": "TASK_ROLE_ARN",
>     "SecretAccessKey": "SECRET_ACCESS_KEY",
>     "Token": "SECURITY_TOKEN_STRING"
> }
> ```
> 
> Note: The default expiration time for the generated IAM role credentials is 6 hours.

It would be nice if pgbackrest could obtain these credentials directly. It is possible to write a wrapper to load these credentials, but it will not be able to renew the credentials for very long running tasks.

It could be worthwhile using an SDK for this sort of thing as similar issues will come up in EKS (where credentials might come from TMDS or via federation of cluster identity to AWS) and even lambda (useful for short tasks like initdb && pgbackrest stanza-create && pgbackrest backup).

**Comment by dwsteele** [comment]
Closing since there has been no response.
