### ISSUE TITLE
Using Workload Identity / metadata server in GCP/GKE

### ISSUE THREAD

**Issue by haf** [pgbackrest/pgbackrest#1535]
Can I configure pgbackrest to use the ambient service account / workload identity credentials in my GKE cluster?

https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#using_from_your_code

Cross post (expect operator issue to be closed): https://github.com/CrunchyData/postgres-operator/issues/2768

**Comment by dwsteele** [comment]
Looks like this was resolved?
