### ISSUE TITLE
Issues trying to use bz2 compression

### ISSUE THREAD

**Issue by mtmelo** [pgbackrest/pgbackrest#1541]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
version: 2.32

2. PostgreSQL version:
psql (PostgreSQL) 11.11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
One standby with a dedicated server for backup. All of them are CentOS Linux release 7.9.2009 

4. Did you install pgBackRest from source or from a package?
We did it from the official repository page.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

After installing bz2 from yum, I tried using compress-type=bz2 and then the archive starts to fail with the following error:

ASSERT: [025]: bz2 error: [-2] parameter error
        --------------------------------------------------------------------
        If SUBMITTING AN ISSUE please provide the following information:

        version: 2.32
        command: archive-push
        options: [pg_wal/0000000100145BE3000000CF] --compress-level=0 --compress-type=bz2 --exec-id=23959-2cb81b76 --pg1-path=/postgresql/data/11 --process-max=4 --repo1-path=/mnt/backupserver/pgBackRest --repo1-type=cifs --stanza=prod

        stack trace:
        common/compress/bz2/common:bz2Error:71:(test build required for parameters)
            ... function(s) omitted ...
        common/compress/bz2/compress:bz2CompressNew:(trace log level required for parameters)
        command/archive/push/file:archivePushFile:(debug log level required for parameters)
        command/archive/push/push:cmdArchivePush:(debug log level required for parameters)
        main:main:(debug log level required for parameters)
        --------------------------------------------------------------------
[2021-10-18 07:43:32.683 UTC /  /  /  / 3698 - LOG:  archive command failed with exit code 25
[2021-10-18 07:43:32.683 UTC /  /  /  / 3698 - DETAIL:  The failed archive command was: pgbackrest --stanza=prod --repo1-type=cifs archive-push pg_wal/0000000100145BE3000000CF
ASSERT: [025]: bz2 error: [-2] parameter error
        --------------------------------------------------------------------
        If SUBMITTING AN ISSUE please provide the following information:

        version: 2.32
        command: archive-push
        options: [pg_wal/0000000100145BE3000000CF] --compress-level=0 --compress-type=bz2 --exec-id=24238-b0241eb3 --pg1-path=/postgresql/data/11 --process-max=4 --repo1-path=/mnt/backupserver/pgBackRest --repo1-type=cifs --stanza=prod

        stack trace:
        common/compress/bz2/common:bz2Error:71:(test build required for parameters)
            ... function(s) omitted ...
        common/compress/bz2/compress:bz2CompressNew:(trace log level required for parameters)
        command/archive/push/file:archivePushFile:(debug log level required for parameters)
        command/archive/push/push:cmdArchivePush:(debug log level required for parameters)
        main:main:(debug log level required for parameters)
        --------------------------------------------------------------------
[2021-10-18 07:43:33.729 UTC /  /  /  / 3698 - LOG:  archive command failed with exit code 25

**Comment by dwsteele** [comment]
You haven't provided your config but it looks like you are setting `compress-level=0`. Only `1-9` are valid for `bzip2`.
