### ISSUE TITLE
pgbackrest 2.35 build error on RHEL 7 - ppc64le

### ISSUE THREAD

**Issue by devrimgunduz** [pgbackrest/pgbackrest#1548]
Hi,

pgbackrest 2.35 does not compile on RHEL 7 - ppc64le (builds fine on RHEL 8 - ppc64le). Error messages are below. Can you please take a look? Thanks! Devrim

> common/type/variant.c:26:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_FALSE_VAR,                                 false);
 ^~~~~~~~~~~~~~~~~~~
common/type/variant.c:24:71: error: field name not in record or union initializer
     const Variant *name = ((const Variant *)&(const VariantBoolConst){.type = varTypeBool, .data = dataParam})
                                                                       ^
common/type/variant.c:26:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_FALSE_VAR,                                 false);
 ^~~~~~~~~~~~~~~~~~~
common/type/variant.c:24:71: note: (near initialization for '(anonymous)')
     const Variant *name = ((const Variant *)&(const VariantBoolConst){.type = varTypeBool, .data = dataParam})
                                                                       ^
common/type/variant.c:26:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_FALSE_VAR,                                 false);
 ^~~~~~~~~~~~~~~~~~~
common/type/variant.c:24:92: error: field name not in record or union initializer
     const Variant *name = ((const Variant *)&(const VariantBoolConst){.type = varTypeBool, .data = dataParam})
                                                                                            ^
common/type/variant.c:26:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_FALSE_VAR,                                 false);
 ^~~~~~~~~~~~~~~~~~~
common/type/variant.c:24:92: note: (near initialization for '(anonymous)')
     const Variant *name = ((const Variant *)&(const VariantBoolConst){.type = varTypeBool, .data = dataParam})
                                                                                            ^
common/type/variant.c:26:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_FALSE_VAR,                                 false);
 ^~~~~~~~~~~~~~~~~~~
common/type/variant.c:24:53: error: unknown type name 'VariantBoolConst'
     const Variant *name = ((const Variant *)&(const VariantBoolConst){.type = varTypeBool, .data = dataParam})
                                                     ^
common/type/variant.c:27:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_TRUE_VAR,                                  true);
 ^~~~~~~~~~~~~~~~~~~
common/type/variant.c:24:71: error: field name not in record or union initializer
     const Variant *name = ((const Variant *)&(const VariantBoolConst){.type = varTypeBool, .data = dataParam})
                                                                       ^
common/type/variant.c:27:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_TRUE_VAR,                                  true);
 ^~~~~~~~~~~~~~~~~~~
common/type/variant.c:24:71: note: (near initialization for '(anonymous)')
     const Variant *name = ((const Variant *)&(const VariantBoolConst){.type = varTypeBool, .data = dataParam})
                                                                       ^
common/type/variant.c:27:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_TRUE_VAR,                                  true);
 ^~~~~~~~~~~~~~~~~~~
common/type/variant.c:24:92: error: field name not in record or union initializer
     const Variant *name = ((const Variant *)&(const VariantBoolConst){.type = varTypeBool, .data = dataParam})
                                                                                            ^
common/type/variant.c:27:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_TRUE_VAR,                                  true);
 ^~~~~~~~~~~~~~~~~~~
common/type/variant.c:24:92: note: (near initialization for '(anonymous)')
     const Variant *name = ((const Variant *)&(const VariantBoolConst){.type = varTypeBool, .data = dataParam})
                                                                                            ^
common/type/variant.c:27:1: note: in expansion of macro 'VARIANT_BOOL_EXTERN'
 VARIANT_BOOL_EXTERN(BOOL_TRUE_VAR,                                  true);
 ^~~~~~~~~~~~~~~~~~~
cc1: warning: unrecognized command line option '-Wno-implicit-fallthrough'
make[1]: *** [.build/common/type/variant.o] Error 1
make[1]: Leaving directory `/var/lib/pgsql/rpmcommon/BUILD/pgbackrest-release-2.35/src'
error: Bad exit status from /var/tmp/rpm-tmp.ISMGDv (%build)

RPM build errors:

**Comment by dwsteele** [comment]
Any progress here?

**Comment by devrimgunduz** [comment]
Yeah, sorry. Forgot to update.

I updated the patch. Thanks for your help.

Cheers, Devrim
