### ISSUE TITLE
pgbackrest independent stanza for standby?

### ISSUE THREAD

**Issue by Bralva** [pgbackrest/pgbackrest#1553]
1. pgBackRest version:
2.35-2.pgdg100+1 package version
2. PostgreSQL version:
13
3. Operating system/version 
Debian 10 Buster / I have two nodes (master and replica)

4. Explanation / Requirements

* I have independent s3 buckets
* I have two cross dc nodes (master and replica)
* I want to configure independent stanza for replica and master (with different s3 buckets)
* I want to make full backup from standby
* I want to push wal from standby too

How can i do this?

I cant create stanza on standby server!
[056]: unable to find primary cluster

**Comment by benjamin-bergia** [comment]
I have the same issue but a slightly different use case. I don't have SSH access to the primary only a user with replication permissions and some admin user accounts. I provisioned a new standby and setup the streaming replication. Now I would like to create the initial backup directly from my standby. Unfortunately, like @Bralva, whatever I try, pgbackrest always seems to try to access to the primary

**Comment by benjamin-bergia** [comment]
@Bralva 
> I cant create stanza on standby server! [056]: unable to find primary cluster

you can create the stanza without connecting to any db by using `pgbackrest stanza-create --stanza=... --no-online` but you won't be able to take any backup afterward.
