### ISSUE TITLE
Isolate repositories on a dedicated repo host

### ISSUE THREAD

**Issue by Lobo75** [pgbackrest/pgbackrest#1556]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.33

2. PostgreSQL version: 11, 12 , 13, 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  CentOS

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I have a dedicated repository host setup for use by multiple postgres instances that belong to various business areas.  The storage behind the dedicated repository host is a NFS appliance that does data encryption at rest and data deduplication.  I have a requirement to isolate the  repositories for each business areas from each other with in the shared repository host.

The repositories would need to look something like 

/pgbackrest/businessarea1
/pgbackrest/businessarea2

Each repository may need different storage policies for retention and number of backups.

What I have looked at so far is using a unique pgbackrest.conf on the repository host for each area as in:

/etc/pgbackrest/businessarea1.conf which would have repo1-path=/pgbackrest/businessarea1 in it and a unique user account.  

Then use pgbackrest --stanza=businessarea1 --config=/etc/pgbackrest/businessarea1.conf create-stanza or backup as typical commands.  That is working as I expected, I can create/backup the stanza to unique locations based on the repo1-path.  However what is not working is on the postgres hosts the archive-push or restores do not seem to know about the non standard location of the config files.  I have tried various command line options and config setting but cannot seem to hit on one that works.

Am I not understanding correctly how to use or misuse the optional config paths?

Is there a configuration method that I'm not seeing that would isolate the repositories on a single dedicated host?

Thanks.

**Comment by pgstef** [comment]
Hi,

You need to specify on your PG nodes the non-default location for the repo host config. Have you tried [--repo-host-config](https://pgbackrest.org/configuration.html#section-repository/option-repo-host-config) ?

Kind regards,

**Comment by pgstef** [comment]
Also, if you don't want to split your configuration between multiple files, you can define the `repo1-*` options inside the stanza sections (with or without defining a default repo location inside the global section).

**Comment by Lobo75** [comment]
Thank you for the response.

The first suggestion --repo-host-config, when that is used on the postgres host for archive-push I get invalid option.

Moving the repo1-* to the unique stanza config solved part of the issue.  On the dedicated host I created an alternate account as in businessarea1.  Did the ssh key exchange with the postgres host.  The password less keys work as expected.  

What I have not figured out is why using on the dedicated host businessarea1 account running:

pgbackrest --stanza=businessarea1 check 

prompts for a password, looking at a strace it is pulling the correct ssh keys from /home/businessarea1/.ssh/id_rsa just as a plain ssh test connection would.

Is there something in pgbackrest that is looking for the account pgbackrest or postgres?

Thanks.

**Comment by dwsteele** [comment]
By default pgbackrest tries to connect to `postgres` on a pg host and `pgbackrest` on a repo host. You can change the default with `pg-host-user` (https://pgbackrest.org/configuration.html#section-stanza/option-pg-host-user) and `repo-host-user` (https://pgbackrest.org/configuration.html#section-repository/option-repo-host-user).
