### ISSUE TITLE
ERROR: [043]: WAL segment to push required - pgbackrest --stanza=main --log-level-console=info archive-push

### ISSUE THREAD

**Issue by joshinarendra27** [pgbackrest/pgbackrest#1559]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
  pgBackRest 2.35

2. PostgreSQL version:
 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Red Hat Enterprise Linux Server release 7.8 (Maipo)

4. Did you install pgBackRest from source or from a package?
repository

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

  parameters:
    archive_command: pgbackrest --stanza=main archive-push %p
    archive_mode: true
    listen_addresses: '*'
    wal_level: replica
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true

7. Describe the issue:

getting error when running pgbackrest  archive-push command - ERROR: [043]: WAL segment to push required

pgbackrest --stanza=main --log-level-console=info archive-push

2021-11-08 02:56:39.849 P00   INFO: archive-push command begin 2.35: --archive-async --compress-level=3 --exec-id=79126-e2bfec9b --log-level-console=info --log-level-file=detail --pg1-path=/postgres_data/data --process-max=3 --repo1-host=10.57.65.164 --repo1-host-user=postgres --stanza=main
ERROR: [043]: WAL segment to push required
2021-11-08 02:56:39.850 P00   INFO: archive-push command end: aborted with exception [043]

**Comment by pgstef** [comment]
Hi,

[That](https://github.com/pgbackrest/pgbackrest/blob/bb03b3f41942d0b781931092a76877ad309001ef/src/command/archive/push/push.c#L317) error is thrown when no WAL segment to archive is provided to the command. 
Basically said, PG replace the `%p` by the WAL to archive with the archive_command.

The archive-push command is intended to be used by PG itself. What are you trying to achieve by running it manually ?

Kind regards

**Comment by joshinarendra27** [comment]
I want to have seprate WAL backup so that I can restore wal logs separately if any of log file not applied on standby and deleted from primary

**Comment by pgstef** [comment]
> I want to have seprate WAL backup so that I can restore wal logs separately if any of log file not applied on standby and deleted from primary

You already have that. With `archive_command`, PG sends its wal archives to pgbr repo using the `archive-push` command. Those wals are needed for the backup itself ("hot" backup consistency in PG) or simply for PITR.
Using PG `restore_command` + pgbr archive-get in your standby configs will use those archives if the streaming replication lags too much behind the primary.

Archive-push is then intended to take a WAL file from PG and push it to the repo. So definitely not what you are trying to do.

If you really need to copy those archives somewhere else, have a look at your repo content. There should be 2 directories. One for backups and one for archives.

Kind regards
