### ISSUE TITLE
s3 backup endpoint parsing

### ISSUE THREAD

**Issue by dimitrigraf** [pgbackrest/pgbackrest#1560]
1. pgBackRest version: 2.3.5

2. PostgreSQL version: 13

3. Operating system/version: Kubernetes 1.20.7

4. Did you install pgBackRest from source or from a package? container image on Kubernetes `registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0`

5. Please attach the following as applicable:
[db-stanza-create.log.txt](https://github.com/pgbackrest/pgbackrest/files/7502655/db-stanza-create.log.txt)
[pgbackrest_instance.conf.txt](https://github.com/pgbackrest/pgbackrest/files/7502656/pgbackrest_instance.conf.txt)
[s3.conf.txt](https://github.com/pgbackrest/pgbackrest/files/7502657/s3.conf.txt)

7. Describe the issue:

I ran into this issue when using Crunchy PGO with the S3 backup mechanism in place following this tutorial: https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backups/

I've already created an issue in the PGO repo where you can find a detailed description: https://github.com/CrunchyData/postgres-operator/issues/2836

From the answer I got it seems that this is something on the pgbackrest side.

**Comment by dwsteele** [comment]
Yeah, this is in pgBackRest. There's some history here with the legacy Perl code, but it is something we have been meaning to improve.

FWIW `repo-gcs-endpoint` already accepts this format but we have not yet updated S3/Azure to match.
