### ISSUE TITLE
Can't backup with symlinked pg_wal directory

### ISSUE THREAD

**Issue by adamzwakk** [pgbackrest/pgbackrest#1563]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.35

2. PostgreSQL version: 
12.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 18.04

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/7505795/pgbackrest.conf.txt)
[analytics-backup.log](https://github.com/pgbackrest/pgbackrest/files/7505820/analytics-backup.log)

7. Describe the issue:

We are trying to do a pgbackrest backup from a standby server. We have our pg_wal directory symlinked to another drive on primary, and doing this causes pgbackrest to not backup, log files attached. Would we need a "real" pg_wal directory to do a backup?

**Comment by pgstef** [comment]
Hi,

The error doesn't seem to be that you're using a symlink but the symlink itself:
`ERROR: [070]: link 'pg_wal' (/var/lib/postgres_large/temp_wals/pg_wal/) destination is a subdirectory of link 'pg_tblspc/16401' (/var/lib/postgres_large)`.

You're using a tablespace and apparently put your wals inside the same path. Having `/var/lib/postgres_large/pg_wal` and `/var/lib/postgres_large/tablespaceX` (using an adequate name for your tablespace path) should probably be more appropriate.

Kind Regards
