### ISSUE TITLE
Question re: restore_command and restore_target_action

### ISSUE THREAD

**Issue by berlin-ab** [pgbackrest/pgbackrest#1565]
1. pgBackRest version:

2.34

2. PostgreSQL version:

14

Is there a reason that `restore_command` remains in `postgresql.auto.conf` after a restore has been done with `--target-action=promote`? I expected the restore specific configuration to be removed by pgbackrest after the recovery is complete, but before the server is promoted.

**Comment by pgstef** [comment]
Hi,

That's a PG behavior. `--target-action` will only set the PG `recovery_target_action` setting. As soon as the restore command ends and you start the PG service, PG handles the recovery (and the settings).

Previously, those settings were in `recovery.conf` which was then renamed to `recovery.done`. But that behavior has changed with PG 12 to (as far as I understand it) allow a reload of those settings while PG is running.

Your observation is just a side-effect of that PG change.

Kind Regards
