### ISSUE TITLE
is it possible to re catalog a backup accidentally expired and removed with expire command with a S3 versioned storage compatible ?

### ISSUE THREAD

**Issue by momo4200** [pgbackrest/pgbackrest#1578]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

pgBackRest 2.35

2. PostgreSQL version:

psql (PostgreSQL) 13.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Red Hat Enterprise Linux release 8.4

4. Did you install pgBackRest from source or from a package?

from package

7. Describe the issue:

Hi there,
I have a question concerning the possibility to re catalog a backup when using a S3 versioned compatible  storage.

If, for example, we do a mistake by expiring a backup, with a S3 versioned storage it is possible to retrieve the files after deleting the delete markers for the specific files involved in the expired backup.

But how can i recatalog the files that i just "retrieve" ?

Is it safe to restore a version of backup.info and backup.info.copy with the expired backup description and add it back to the current backup.info and backup.info.copy ?

Is the pgbackrest entry in backup.info used to verify integrity of the backup.info file ?

Thanks

**Comment by pgstef** [comment]
Hi,

Imho, it's best to avoid messing with manifests manually. There is a `infoBackupLoadFileReconstruct` function used in the [backup](https://github.com/pgbackrest/pgbackrest/blob/3f7409019df112ec50efb6c3db6f7780c9a63c87/src/command/backup/backup.c#L2048) and [expire](https://github.com/pgbackrest/pgbackrest/blob/3f7409019df112ec50efb6c3db6f7780c9a63c87/src/command/expire/expire.c#L1016).

I think simply copying the full backup directory to the backup repo and the execute the expire command (with the good parameters) again should allow to reconstruct the backup info.

Example:
```bash
$ pgbackrest --stanza=c7pg info
stanza: c7pg
    status: ok
    cipher: aes-256-cbc

    db (current)
        wal archive min/max (14): 00000001000000000000000D/000000010000000000000010

        full backup: 20211130-143359F
            timestamp start/stop: 2021-11-30 14:33:59 / 2021-11-30 14:34:03
            wal start/stop: 00000001000000000000000D / 00000001000000000000000D
            database size: 25MB, database backup size: 25MB
            repo1: backup set size: 3.2MB, backup size: 3.2MB

--> copying the 20211130-125309F old backup directory back to the repo

$ pgbackrest --stanza=c7pg --repo1-retention-full=2 expire
...
WARN: backup '20211130-125309F' found in repository added to backup.info
...

$ pgbackrest --stanza=c7pg info
stanza: c7pg
    status: ok
    cipher: aes-256-cbc

    db (current)
        wal archive min/max (14): 00000001000000000000000D/000000010000000000000010

        full backup: 20211130-125309F
            timestamp start/stop: 2021-11-30 12:53:09 / 2021-11-30 12:53:12
            wal start/stop: 000000010000000000000005 / 000000010000000000000005
            database size: 25MB, database backup size: 25MB
            repo1: backup set size: 3.2MB, backup size: 3.2MB

        full backup: 20211130-143359F
            timestamp start/stop: 2021-11-30 14:33:59 / 2021-11-30 14:34:03
            wal start/stop: 00000001000000000000000D / 00000001000000000000000D
            database size: 25MB, database backup size: 25MB
            repo1: backup set size: 3.2MB, backup size: 3.2MB
```

Kind Regards

**Comment by momo4200** [comment]
Hi there,

thank you very much for this !
I tried on Minio on a versioned bucket and it worked.

recover of deleted set was made with mc command :
./mc undo --insecure --recursive --force minio/pgbackrest/pgbackup/backup/mycluster/YYYYMMDD-HH24MISSF/

and then the expire with retention-full set to the correct number.
I will check with retention-full-type=time if it is still working.

If yes, i will close this question.

Thanks again !

**Comment by momo4200** [comment]
Hi there,

i tried with repo1-retention-full-type=time and it worked.

Thanks again for the tip to "recatalog" expired backup.
