### ISSUE TITLE
A pgbackrest check still refers to old hostname after hostname renamed 

### ISSUE THREAD

**Issue by brunre01** [pgbackrest/pgbackrest#1579]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.32

2. PostgreSQL version: 12.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  CentOS Linux release 7.9.2009 (Core)

4. Did you install pgBackRest from source or from a package?  package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:  Backing up from standby node.  The primary and standby hostname recently changed however when running a 
    pgbackrest --stanza=STANZA_HOSTNAME  check --log-level-console=detail    on the standby host its still referring to old hostname

INFO: check command begin 2.32: --backup-standby --exec-id=10557-9cafbdcf --log-level-console=detail --log-level-stderr=detail --pg1-host=new_hostname --pg1-path=/Postgres/pgDATA/12/data --pg2-path=/Postgres/pgDATA/12/data --repo1-path=/pgBACKUP/pgbackrest --stanza=STANZA_HOSTNAME
WARN: unable to check pg-1: [DbConnectError] raised from remote-0 protocol on 'new_hostname': unable to connect to 'dbname='postgres' port=5432': could not translate host name "old_hostname" to address: Name or service not known
ERROR: [027]: primary database not found
       HINT: check indexed pg-path/pg-host configurations
INFO: check command end: aborted[pgbackrest.conf.on.standby.txt]

The old hostname has been removed from DNS

(https://github.com/pgbackrest/pgbackrest/files/7626376/pgbackrest.conf.on.standby.txt)
[postgresql.conf.params.txt](https://github.com/pgbackrest/pgbackrest/files/7626377/postgresql.conf.params.txt)

**Comment by dwsteele** [comment]
Is there an env var on `new_hostname` with the old hostname? Either `PGBACKREST_PG1_HOST` or `PGHOST`.

**Comment by brunre01** [comment]
The PGHOST env var does reflect the new name and the PGBACKREST_PG1_HOST
has not been set

**Comment by dwsteele** [comment]
OK, if we were specifying a host, it would be part of the connect string and I don't see it, see https://github.com/pgbackrest/pgbackrest/blob/release/2.36/src/postgres/client.c#L143. In any case the only thing we pass there is the socket path.

So the old host was not set by pgbackrest as far as I can see. The error is coming out of libpq so I still think it is something in the env.

**Comment by brunre01** [comment]
would it make sense to remove the pgbackrest package and reinstall?

**Comment by brunre01** [comment]
i upgraded to 2.36  which didnt help either

**Comment by brunre01** [comment]
After updating to v2.36,  i logged out and logged back in again - the
pgbackrest check worked without any failure.

**Comment by brunre01** [comment]
PGHOST was set to the old hostname in the .bashrc file on the primary server. modifying this resolved the problem

**Comment by brunre01** [comment]
Thanks for the assistance
