### ISSUE TITLE
Per-repo configuration (compression, process-max...) ?

### ISSUE THREAD

**Issue by Krysztophe** [pgbackrest/pgbackrest#1580]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):
1. pgBackRest version: 2.35
2. PostgreSQL version: 14
3. Operating system/version : Ubuntu 18/Debian 10
4. Did you install pgBackRest from source or from a package?  Package
7. Describe the issue:

Is it possible to configure the compression, or other options, per repo, in the configuration file ?
If yes, how? I didn't find it in the documentation.

Use case examples:
 * compress quickly on a local repo, and at maximum compression on another repo with a high retention on a slow link
 * use different process-max according to the repo

I know it is possible to override on the command line, which may be the most practical after all.

**Comment by pgstef** [comment]
Hi,

Atm, compression or process-max (i.e.) are general options, not configurable per repo (when using multi-repos in the same config file).

However, command-line options override environment options which override config file options. So, for commands where it's possible to specify on which repo to operate (like the backup command) you could change the process-max option in the command itself indeed. 

Another example would be archive-push. The general options will apply to the command itself which will operate on all repos defined. So, there, it won't be possible to change the behavior per repo unfortunately.

Hope it helps,
Kind Regards,

**Comment by Krysztophe** [comment]
OK, I'll live with that. This limitation is merely theoretical for now.

Thanks for the quick answer.

**Comment by dwsteele** [comment]
I agree that finer grained configuration could be useful for backups (without using env/cmd-line params), but archive-push only runs as fast as the slowest repo so using different compression would not be useful.
