### ISSUE TITLE
2.36 release not on pgdg repo

### ISSUE THREAD

**Issue by Tostino** [pgbackrest/pgbackrest#1583]
I was hit by this issue: https://github.com/pgbackrest/pgbackrest/issues/834 again this week, and I've been unable to upgrade to 2.36 to mitigate it because it's not showing up in my pgdg apt repo: http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64

Any reason this release hasn't been packaged up yet?

**Comment by dwsteele** [comment]
We aren't involved with packaging, but I saw @pgstef had pinged @df7cb about it on pgsql-pkg-debian. I can see the new version up on Debian (https://tracker.debian.org/pkg/pgbackrest) but it does not seem to have hit PGDG.

**Comment by df7cb** [comment]
Sorry for that, I had built the new version a few days ago, but had not promoted the package on apt.postgresql.org from *-pgdg-testing to *-pgdg. Did that now.

**Comment by dwsteele** [comment]
Thank you, @df7cb!
