### ISSUE TITLE
(Doc) Replication slot are not restored

### ISSUE THREAD

**Issue by Krysztophe** [pgbackrest/pgbackrest#1585]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.35

It seems that pgBackRest does not restore replication slots (for the better).

I didn't find it explicitly in the documentation. I've just found a reference in `release.xml`. 

I'll suggest to add a word on it.

**Comment by jreidthompson** [comment]
Hi, yes, this seems like a sensible addition to the docs.  I've added a card to the project board and will plan to schedule it into my queue.  https://github.com/pgbackrest/pgbackrest/projects/2#card-74790384
