### ISSUE TITLE
Allow non-TLS connections to S3 servers

### ISSUE THREAD

**Issue by ron1** [pgbackrest/pgbackrest#1590]
pgbackrest should allow non-TLS connections to S3 servers for the following reasons:
1. The gold standard Amazon S3 allows both HTTP and HTTPS requests.
2. Kubernetes service meshes already provide mTLS between services so to require additional certificate management in order to connect a pgbackrest client to an S3 server via one-way TLS in a k8s cluster introduces unnecessary complexity.
3. Some Kubernetes clusters encrypt traffic between nodes via IPSec thereby eliminating the need to encrypt the connection between a pgbackrest client and an in-cluster S3 server.

Consider enhancing pgbackrest to support non-TLS connections identified either by specification of an http protocol url scheme or port 80.

**Comment by dwsteele** [comment]
This seems reasonable. Added a project card for this feature at https://github.com/pgbackrest/pgbackrest/projects/2#card-74786045.

How would you like your name to appear in the release notes?
