### ISSUE TITLE
Leaking sockets in EINPROGRESS state when firewall blocks partial traffic

### ISSUE THREAD

**Issue by jcoleman** [pgbackrest/pgbackrest#1593]
1. pgBackRest version: 2.35
2. PostgreSQL version: 11.x
3. Operating system/version: Debian Stretch
4. Did you install pgBackRest from source or from a package? Package.

We are seeing what seems to be a socket leak in current pgBackRest during a full backup. If an upload to S3 gets blocked by a firewall the socket ends up stuck in EINPROGRESS. In this particular case it happened because apparently AWS added new CIDRs to S3, and we didn't notice, so routers were blocking the traffic outbound. Because of that retries might actually succeed since they might resolve to a different IP.

Updating the firewall resolved the issue, but it seems that a chunk failing like this shouldn't result in moving on to other files while leaving the socket open (eventually resulting in the process being killed by the OS for too many files open).

Of note here is that we did *not* see any errors in the logs (presumably the sockets leaked because we didn't actually get to some error handling code?)

An example of the fd not being closed:
```
18:19:00 close(85)                      = 0
18:19:00 socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 85
18:19:00 setsockopt(85, SOL_TCP, TCP_NODELAY, [1], 4) = 0
18:19:00 fcntl(85, F_GETFL)             = 0x2 (flags O_RDWR)
18:19:00 fcntl(85, F_SETFL, O_RDWR|O_NONBLOCK) = 0
18:19:00 fcntl(85, F_SETFD, FD_CLOEXEC) = 0
18:19:00 setsockopt(85, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
18:19:00 connect(85, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("52.219.176.148")}, 16) = -1 EINPROGRESS (Operation now in progress)
18:19:00 poll([{fd=85, events=POLLOUT}], 1, 56243) = 1 ([{fd=85, revents=POLLOUT|POLLERR|POLLHUP}])
18:19:01 getsockopt(85, SOL_SOCKET, SO_ERROR, [111], [4]) = 0
18:19:01 select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=500000}) = 0 (Timeout)
18:19:02 stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=108, ...}) = 0
18:19:02 open("/etc/hosts", O_RDONLY|O_CLOEXEC) = 86
18:19:02 fstat(86, {st_mode=S_IFREG|0644, st_size=39596, ...}) = 0
18:19:02 close(86)                      = 0
```

**Comment by dwsteele** [comment]
This leak was caused by the file descriptor variable getting clobbered after a long jump. See PR #1594 for details and the fix.

**Comment by dwsteele** [comment]
> Of note here is that we did not see any errors in the logs

You would need to be at debug level to see the retries. You'll only get an error when all of the retries fail. See https://github.com/pgbackrest/pgbackrest/blob/release/2.36/src/common/io/socket/client.c#L118.

**Comment by jcoleman** [comment]
Thanks for the fast fix!

Re: the error — you’re theorizing we never got to an actual error? And is it advisable to run with debug logs? ISTM regular retries is a bit of an bad situation in genera.

**Comment by dwsteele** [comment]
> Re: the error — you’re theorizing we never got to an actual error?

Seems like it, since the retries eventually worked. You didn't provide any logs, though, so hard to tell. I presume there was a failure eventually when the process ran out of file handles?

> And is it advisable to run with debug logs?

No, they chew up a ton of space. I turn on debug level when something is going wrong.

> ISTM regular retries is a bit of an bad situation in general.

Not sure what you mean here. Without retries S3 is almost unusable. Your case is different, but S3 constantly throws internal errors, slow downs, etc.
