### ISSUE TITLE
Question on repository delete

### ISSUE THREAD

**Issue by Tiago-DBA** [pgbackrest/pgbackrest#1600]
Hi Guys,

I have a very paranoic question, that security team raised to me:

We are using pgbackrest on prems with a dedicated repository host.

Use case: In case of a cyber attack someone could access the repository host with root or linux repository user and remove some or all part of the repository files (backup,wals,...).

As pgbackrest level is there someway (parameter, option, .... )  to handle that use case, if no do you have any idea to manage that ?

Thank you.

**Comment by dwsteele** [comment]
> In case of a cyber attack someone could access the repository host with root or linux repository user and remove some or all part of the repository files

Not much to be done about this. We don't control what superuser and service accounts do.

> As pgbackrest level is there someway (parameter, option, .... ) to handle that use case, if no do you have any idea to manage that ?

If the WAL or backup has been *modified* or partially deleted then we'll detect that on a restore. Of course, it is possible for an attacker to update all the checksums to match, but it would be non-trivial to do so.

If you need to be sure you have an untainted backup, use `--archive-copy` for your full backups, then copy it to read-only storage (like a read-only S3 bucket).

**Comment by Tiago-DBA** [comment]
Thanks David , I 'll look for the read-only storage

**Comment by Tiago-DBA** [comment]
Hi again,

I looked at s3, and I have two questions:

Does pgbackrest backup, archives , and restore capacities works directly in a S3 read only ( it seems to be the "object locked" option in S3) ? 
I understand It is difficult because some meta data files (e.g. manifests) have to be updated many times ?
If it works, should I be able to use the pgbackrest multirepository facility together with a dedicated repository host and a s3 ?

Also about File system snapshot, does PostgreSQL guarantee data persistence and corruption checks when restoring a snapshot ?

Thank you

**Comment by dwsteele** [comment]
> Does pgbackrest backup, archives , and restore capacities works directly in a S3 read only

No, though this is a feature we are considering.

> Also about File system snapshot, does PostgreSQL guarantee data persistence and corruption checks when restoring a snapshot ?

If you do pg_start/stop_backup() and archive WAL generated during the backup, then yes. If not, then you'll need to be sure all volumes are snapped consistently, if you have more than one, and even then I'm not sure I trust it.
