### ISSUE TITLE
Wait for lock to be released

### ISSUE THREAD

**Issue by sezaru** [pgbackrest/pgbackrest#1603]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.35

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.04

4. Did you install pgBackRest from source or from a package? Package

7. Describe the issue:

I have the following in my crontab:
```
20 0-0,4-23 * * * pgbackrest --stanza=data_db --type=incr --log-level-console=info backup

0 2 * * * pgbackrest --stanza=data_db --type=full --log-level-console=info backup
```

As you can see, I create incremental database backups from 04 AM to 24 AM, and at 02 AM I create a full backup.

The issue is that sometimes when the database is having a lot of insertions, the incr backups will take a long time to finish, and when the full backup is called, there is still another pgbackrest instance doing an incr backup making the full backup fail with:

```
2021-12-21 13:17:17.172 P00   INFO: backup command begin 2.35: --exec-id=2412753-9a057150 --log-level-console=info --pg1-host=node1.database.tip-off --pg1-host-port=53475 --pg1-host-user=data_db --pg1-path=/var/lib/postgresql/14/data_db --pg1-port=19753 --pg1-user=data_db --process-max=2 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest --repo1-retention-full=1 --stanza=data_db --start-fast --type=full
ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/data_db-backup.lock': Resource temporarily unavailable
       HINT: is another pgBackRest process running?
2021-12-21 13:17:17.172 P00   INFO: backup command end: aborted with exception [050]
```

Since the full backup is failing, my backup HD just keeps growing (since it will not generate a full backup and trigger old backup expiration), you can see this in the image below, the red line is where normally where the full backup is triggered and removes old backups, as you can see, the full backup is failing with the above error and the disk usage just keep growing:
![image](https://user-images.githubusercontent.com/279828/146937697-4cf40774-2c67-4564-98a7-dddf0e51956c.png)

To fix that, I tried to find an option to wait for lock release, that way I can make the full backup call and pgbackrest would start the full backup when the other pgbackrest process releases the lock. I also tried to see if there is some way to make pgbackrest kill or stop the other pgbackrest process that is using the current lock. I could not find any fix or workaround for this.

So, how do you normally handle this? And is there an option in pgbackrest that I'm not aware of that would help in my case?

Also note that I have other crontab rules for pgbackrest, but they are for other databases that use other lock files, so simply doing a `killall pgbackrest` would not be a solution since it would not only kill the process with the lock I want to acquire, but it would also kill all the other pgbackrest processes that would be eventually running doing backup for other databases.

**Comment by pgstef** [comment]
Hi

> As you can see, I create incremental database backups from 04 AM to 24 AM, and at 02 AM I create a full backup.

First of all, why? Taking an incremental backup every hour + a full backup each day seems really heavy. Can't you simply take 1 backup per day and rely on WAL archives replay for the data generated in between?

> The issue is that sometimes when the database is having a lot of insertions, the incr backups will take a long time to finish, and when the full backup is called, there is still another pgbackrest instance doing an incr backup making the full backup fail

Don't you have the same issue with the next incr backup too? I mean if one of your incr takes more than 1h, the next one won't start...

> To fix that, I tried to find an option to wait for lock release, that way I can make the full backup call and pgbackrest would start the full backup when the other pgbackrest process releases the lock. I also tried to see if there is some way to make pgbackrest kill or stop the other pgbackrest process that is using the current lock. I could not find any fix or workaround for this.
>
> So, how do you normally handle this? And is there an option in pgbackrest that I'm not aware of that would help in my case?

There's no such option in pgBackRest. But you could come to a very simple shell script with a while loop watching at the lock file before triggering the full backup. And in your incr call, skip if the lock already exists with a simple bash condition. If you really need to take that many backups, it's perhaps the fastest option.

> Also note that I have other crontab rules for pgbackrest, but they are for other databases that use other lock files, so simply doing a `killall pgbackrest` would not be a solution since it would not only kill the process with the lock I want to acquire, but it would also kill all the other pgbackrest processes that would be eventually running doing backup for other databases.

You could use the `stop --force` command which will work per stanza and **should** then only kill processes for the requested stanza. But that's not really intended to use for that purpose. You should really consider lowering how often you take backups imho.

Kind Regards

**Comment by sezaru** [comment]
> First of all, why? Taking an incremental backup every hour + a full backup each day seems really heavy. Can't you simply take 1 backup per day and rely on WAL archives replay for the data generated in between?

The issue is that the data that is added to the database takes a long time to be fetched again, so losing too much of it makes the backend being unusable for a long time.

But at the same time that is a good point, maybe I can try to make the incr backups more sparse in time, at first I thought that they would conclude really fast since it is only the diff.

> Don't you have the same issue with the next incr backup too? I mean if one of your incr takes more than 1h, the next one won't start...

Yep, but for that case there is no problem, I'm ok with the backup not starting, just the full backup that takes precedence to the others.

> There's no such option in pgBackRest. But you could come to a very simple shell script with a while loop watching at the lock file before triggering the full backup. And in your incr call, skip if the lock already exists with a simple bash condition. If you really need to take that many backups, it's perhaps the fastest option.

I will try that, it was my plan B anyway, but I wanted to first check if pgbackrest would already have something to handle this case.

Thanks for the help!

Best regards
