### ISSUE TITLE
PostgreSQL Failover with pgBackRest

### ISSUE THREAD

**Issue by blowoffsteam81** [pgbackrest/pgbackrest#1604]
Hello,

i am currently using pgBackRest to backup a local postgresql db cluster.
The way i have set it up is, that my pgBackRest repository is an NFS share on a ZFS storage server.
My quick setup and initial backup attempts are working fine, but even the best backups can`t decrease my downtime completly, in case my main (and currently my only) postgresql server has a hardware failure or there are any other software related issues.

As we are working productively with davinci resolve (requires a very specific, rather outdated 9.5/9.6 version of PSQL) and those databases are hosted on the PostgreSQL server, we obviously can`t afford a few days of downtime, until we purchased new hardware and set it all up again. (1-2 hours on the other hand is ok)

So for a very simple "failover" idea i had the following in mind and would like to know if my approach is feasible.

Basically i would purchase another server, set it up similarly to the primary server. (same OS version, same PSQL version etc.) and would additionally configure this machine as my pgBackRest Backup server. The repository would still be the aforementioned NFS share, with a S3 share offsite as a 2nd repository. PSQL would be installed but wouldn`t start automatically. Now, in case my main server fails i would like to restore from one of my backups to the pgBackRest Backup Server, start PostgreSQL and hopefully have a working database server again, with a little bit, but not significant downtime.

What do you think? Would it be generally preferable to go for log shipping or streaming replication, instead what i have described?
I guess even DRDB would be good solution for my use case but maybe i am wrong.

Thanks in advance for helping me out. :-)

**Comment by pgstef** [comment]
Hi,

That's pretty much the intent of `--target-action=shutdown`. If you don't really need the streaming replication working all the time, you may simply schedule some restore which will refresh the local PG copy (on the 2nd server) and reduce your RTO. Basically, PG will start, replay all the archives and shutdown. It might even be a good way to regularly test your backups (as long as you think about using `--archive-mode=off` to avoid your temporary cluster to pollute your backup repositories).

In that case, you don't have fail-over but you have a disaster recovery plan at least. If that's enough for you.

That being said, asynchronous streaming replication already works pretty fine with PG 9.6. It doesn't add a lot of maintenance effort to have it working imo.

Kind Regards

**Comment by blowoffsteam81** [comment]
Hi pgstef,

thank you very much for your answer, that is very helpful for sure.
Glad to hear that my idea would work in principle. As i am still new to postgresql administration i thought, it might be a little bit 
overwhelming to set up a full working streaming replication (master/slave) setup but i can see your point and it would certainly be an option i would like to go for.

How much of a performance impact would asynchronous streaming replication mean for my main server?
Do you see any benefit in streaming replication over DRDB or maybe even the other way around?

Another question i forgot to ask earlier:
With my current pgBackRest repository on a local ZFS Server, i covered the onsite backup but would like to have an additional copy of that repository offsite. As far as i know pgBackRest supports S3 targets and MultiRepositories just fine.
But i thought instead of running a seperate pgBackRest job on a regular basis and putting additional stress on my main server, i could just copy over my existing repository so another location offsite by using rsync for example.  

Again, thank you very much for your time and effort to help me out.

Kind Regards

**Comment by pgstef** [comment]
> How much of a performance impact would asynchronous streaming replication mean for my main server? Do you see any benefit in streaming replication over DRDB or maybe even the other way around?

I don't know DRDB very well but to me, it will only handle the disk blocks copy in real time (so, synchronously). It's known to be pretty slow and you can't run a postgres service on that copy. That's then an "offline" copy only. While the streaming replication allows to have a standby server running and possibly accepting RO queries.

There shouldn't be any performance impact to have an async replica connected for your main server imo.
The advantage to have the replica actually running is to be able to monitor the replication status (lag,...) and make sure you really have something working. While only having a "cold" copy (backup or DRDB) won't give you any guarantee about it... You never know the status of your backup unless you try to restore it ;-)

pgBR backups + restore with `--target-action=shutdown` to refresh your cold copy is probably easy/simple enough to meet your requirement.

But all this is more about PG knowledge and education rather than a pgBR configuration.

> Another question i forgot to ask earlier: With my current pgBackRest repository on a local ZFS Server, i covered the onsite backup but would like to have an additional copy of that repository offsite. As far as i know pgBackRest supports S3 targets and MultiRepositories just fine. But i thought instead of running a seperate pgBackRest job on a regular basis and putting additional stress on my main server, i could just copy over my existing repository so another location offsite by using rsync for example.

pgBackRest doesn't handle to move/copy backups from one repo to another currently. So, or you use the multi-repo feature which will send archives to all repos defined and then you have to trigger/expire backups individually for each repo. Or you handle the "rsync" to S3 yourself outside pgBackRest.

**Comment by blowoffsteam81** [comment]
So you would consider using rsync to backup my pgBR respositories common practice and a viable choice?
I am asking this casue i think i found someone in here who didn`t recommend using rsync for that, but the context might have been different.

By the way, does the act of creating a backup with pgBR , be it a full one or a differential/incremental, put a meaningful performance burden on postgresql? Lets say i create a full backup of my DB cluster every day and differential versions every hour. 
Besides any disk I/O constraints that might occur, is creating the backup itself something that can impact the 
experience of my users in any noticeable way?

**Comment by pgstef** [comment]
Hi, 

> So, you would consider using rsync to backup my pgBR respositories common practice and a viable choice? I am asking this casue i think i found someone in here who didn't recommend using rsync for that, but the context might have been different.
>
> edit: I think the user i was talking about didn't recommend synchronizing the WAL specifically with rsync, so different scenario.

If you only need your "backups" to be exported/copied somewhere else, you could simply add the `--archive-copy` option to your backup command. That will copy all the wal archives needed for the backup consistency inside the backup directory itself. With that in mind, you could indeed copy pretty easily a backup set to an external repository.

Rsync in PG `archive_command` is not really recommended indeed. But syncing your repo with an external storage shouldn't be an issue imho.

> Besides disk I/O constraints, does the act of creating a backup with pgBR , be it a full one or a differential/incremental, put a meaningful performance burden on postgresql? Lets say i create a full backup of my DB cluster every day and differential versions every hour. I was expecting it does, to a certain degree at least. That's why my train of thought was, copying my local repo offsite via rsync is better than creating a separate repo and let pgBR do the job but due to my lack of knowledge and experience on this, i might be totally wrong.

You should probably read more about PG [docs](https://www.postgresql.org/docs/current/continuous-archiving.html) to understand all this.

Data read (disk I/O), eventually cpu cost for the compression, network bandwidth,... that's common to any backup method I guess. Diff/incr will use timestamp or checksum to figure out which files to backup. From a PG user point of view, if hardware is good enough, there shouldn't be any perf impact for the users.

Taking a backup every hour particularly sounds heavy given you also have continuous archiving. To summarize, backup + wal archives = recovery, older backup + wal archives = slower recovery. It's just a matter of RTO and disk storage. (but again, that's PG knowledge...)

Kind Regards

**Comment by blowoffsteam81** [comment]
Like you said, i have some further reading to do. Many of the questions i asked are due to a lack of understanding of PG itself and i apologize for that. 

Thank you very much and merry christmas of course. :)
