### ISSUE TITLE
pgBackRest + WAL files

### ISSUE THREAD

**Issue by blowoffsteam81** [pgbackrest/pgbackrest#1606]
Hey there,

after some more reading about the inner workings of PG and pgBackRest its now clear to me that pgBR is supposed to backup/archive the WAL, completly independent from when i call my full/differential/incremental pgBR backups with cron. 
(hence the existence of --archive-copy where you can archive the WAL additionally inside the backup.)
Now it all makes more sense to me and all of a sudden i understand, why creating a diff backup job with pgBR every hour is a little bit extreme. Apparently the WAL files are located in the archive folder of my repository but there is still something that i don`t get and just to confirm what i have learned so far, i have another question, this time more pgBR related and therefor (hopefully) less annoying. :-)

Ok, so from my understanding **archive_command = 'pgbackrest --stanza=myrepo archive-push %p'** results in the WAL being archived to the stanza: myrepo, everytime a WAL is fully written. (by default 16MB in size) 
Like i mentioned earlier, the copied WAL is located in the archive folder, inside the pgBR repository.

But if that is correct, shouldn`t i be able to find the exact same WAL files in both locations? 
(with a little bit of delay, until the file is archived over)

Location: pg_xlog
![Location: pg_xlog](https://user-images.githubusercontent.com/62124456/147374881-0e4a387e-38f3-4aee-85f5-6e1e3f184468.jpg)

Location: pgbr_repo
![Location: pgBR repo](https://user-images.githubusercontent.com/62124456/147374889-1381fc84-93ea-4400-a03c-0f2c30649422.jpg)

As the screenshots indicate, the file naming seems to be different and the file created at 1:15 am, doesn`t seem to be in the repository at all, even though it was 1:20am when i took the screenshot. Can you explain to me why that is?
What is the purpose of the backup files and are the *.gz files the actual, archived WAL, with a checksum attached to their filename?

Kind Regards
Dennis

**Comment by dwsteele** [comment]
> As the screenshots indicate, the file naming seems to be different and the file created at 1:15 am, doesn`t seem to be in the repository at all, even though it was 1:20am when i took the screenshot. Can you explain to me why that is?

You should not expect pg_xlog and the repo to be equal. Postgres creates WAL segments for future use which have not been filled yet. Also, the management of WAL varies from version to version. If you have a pg_xlog directory you are running an unsupported version of Postgres (it is pg_wal in all supported versions) so there's no point in commenting on that version. See the Postgres docs for your version WRT WAL management.

> What is the purpose of the backup files

These are informational files generated by Postgres which are not used by pgBackRest (or Postgres). You might be able to find something about them in the postgres docs.

> are the *.gz files the actual, archived WAL, with a checksum attached to their filename?

Yes.

**Comment by blowoffsteam81** [comment]
Thank you for your reply @dwsteele 

> If you have a pg_xlog directory you are running an unsupported version of Postgres (it is pg_wal in all supported versions) so there's no point in commenting on that version. See the Postgres docs for your version WRT WAL management.

I tried to make sure beforehand, that my PSQL version is compatible with pgBackRest.
Correct me if i am wrong but **pgBackRest is able to support PSQL down to version 8.3, correct?**
I am using PostgreSQL version 9.5 on Debian 11. And my DB cluster contains no pg_wal directory, only the pg_xlog directory.

**Comment by dwsteele** [comment]
pgBackRest supports EOL Postgres versions to allow migrations to newer versions. 9.5 has been EOL for over a year, which means no bug fixes, and more importantly, *no security fixes*. There are serious known security vulnerabilities in 9.5. You should upgrade as soon as possible.

**Comment by blowoffsteam81** [comment]
I wish i could but unfortunately the software we are using  (Davinci Resolve) requires us to use PSQL version <=9.6
Other users of Resolve complaint about it already a couple of times, but as of yet, the developers haven`t made the jump to a more recent version.

So to sum it up, i might be better off just dumping my databases to a secure location (or at least as an additional precaution) instead of relying on pgBackRest? As i understand you, technically pgBackRest supports my PSQL version but i shouldn`t bet on it, is that fair to say?

Thanks again @dwsteele.

**Comment by dwsteele** [comment]
pgBackRest works perfectly well with your version of Postgres (and will for another four+ years), it is Postgres that is the problem here.

Running EOL software is never a good idea (doubly so for server software). If the Resolve developers can't be bothered to support current Postgres, I'd wonder what other problems are lurking.
