### ISSUE TITLE
pgbackrest stop command, --stanza option

### ISSUE THREAD

**Issue by ragaoua** [pgbackrest/pgbackrest#1608]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **2.36**

2. PostgreSQL version: **13**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: **Red Hat Enterprise Linux Server release 7.7**

4. Did you install pgBackRest from source or from a package? **Package**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

6. Describe the issue:

The "pgbackrest stop --force" command always applies to all pgbackrest processes (all stanzas), **even when the --stanza option is used**. This means that, if a process regarding another stanza has been running, it will be immediately terminated.

Here's what I've been testing :

~~~bash
# On one terminal, run the backup command
> date ; pgbackrest --stanza=my_cluster-13 --start-fast --type=full backup && echo "backup completed successfully" || echo "something's wrong" ; date
~~~

~~~bash
# While the previous command runs, run the stop command on another terminal
> date ; pgbackrest --stanza=my_other_cluster-13 --force stop
~~~

And here's the outcome :
~~~bash
> date ; pgbackrest --stanza=my_cluster-13 --start-fast --type=full backup && echo "backup completed successfully" || echo "something's wrong" ; date
Tue Dec 28 11:04:20 CET 2021
something's wrong
Tue Dec 28 11:04:21 CET 2021
~~~

~~~bash
> date ; pgbackrest --stanza=my_other_cluster-13 --force stop
Tue Dec 28 11:04:21 CET 2021
~~~

I've search the documentation, and my understanding is that this isn't what's supposed to happen ; all pgbackrest commands only apply to one stanza when it is specified. Am I mistaken ?

# Attachments
## `pgbackrest .conf` :

~~~ini
[global]
log-path=/var/pgbackrest/log
repo-path=/var/pgbackrest
lock-path=/var/pgbackrest/lock
spool-path=/var/pgbackrest/spool
retention-full=2
link-all=y
stop-auto=y
compress-level=2
archive-async=y

[my_cluster-13]
pg1-path=/appli/postgres/my_cluster/13/data
pg1-port=8000
pg1-socket-path=/var/run/postgresql

[my_other_cluster-13]
pg1-path=/appli/postgres/my_other_cluster/13/data
pg1-port=9000
pg1-socket-path=/var/run/postgresql
~~~

### `my_cluster`

~~~ini
archive_command = 'pgbackrest --stanza=my_cluster-13 archive-push %p'
archive_mode = on
listen_addresses = 'localhost'
max_wal_senders = 10
wal_level = hot_standby
port = 8000
~~~

### `my_other_cluster`

~~~ini
archive_command = 'pgbackrest --stanza=my_other_cluster-13 archive-push %p'
archive_mode = on
listen_addresses = 'localhost'
max_wal_senders = 10
wal_level = hot_standby
port = 9000
~~~

### my_cluster-13-backup.log

~~~
-------------------PROCESS START-------------------
2021-12-28 10:33:21.680 P00   INFO: backup command begin 2.36: --compress-level=2 --exec-id=10090-0bdeb491 --lock-path=/var/pgbackrest/lock --log-path=/var/pgbackrest/log --pg1-path=/appli/postgres/my_cluster/13/data --pg1-port=8000 --pg1-socket-path=/var/run/postgresql --repo1-path=/var/pgbackrest --repo1-retention-full=2 --stanza=my_cluster-13 --start-fast --stop-auto --type=full
2021-12-28 10:33:22.149 P00   INFO: backup command end: terminated on signal [SIGTERM]
~~~

### my_other_cluster-13-stop.log

~~~
-------------------PROCESS START-------------------
2021-12-28 11:04:21.246 P00   INFO: stop command begin 2.36: --exec-id=12666-1da48ecf --force --lock-path=/var/pgbackrest/lock --log-path=/var/pgbackrest/log --stanza=my_other_cluster-13
2021-12-28 11:04:21.247 P00   INFO: sent term signal to process 12663
2021-12-28 11:04:21.247 P00   INFO: stop command end: completed successfully (2ms)
~~~

**Comment by jreidthompson** [comment]
We have added a project card to address this. How would you like your name to appear in the release notes?

https://github.com/pgbackrest/pgbackrest/projects/2#card-75533135

**Comment by ragaoua** [comment]
Hi,

Thank you for a fast answer ! Feel free to use my username in the release notes.
