### ISSUE TITLE
 backup:remote process keeps running (forever) after start backup quickly followed by ctl-C

### ISSUE THREAD

**Issue by ikzelf** [pgbackrest/pgbackrest#1614]
1. pgBackRest version: 2.35

2. PostgreSQL version: 12.9

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
>  repo_host rhel 8.4   4.18.0-305.19.1.el8_4.x86_64
>  db_host    rhel 8.4   4.18.0-305.7.1.el8_4.x86_64
>  standby    reel 8.4   4.18.0-305.7.1.el8_4.x86_64

4. Did you install pgBackRest from source or from a package? crunchy-backrest          x86_64          2.35-1Crunchy.el8.centos

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbac
[pgbackrest.log.zip](https://gi
[postgres_pgbackrest.conf.zip](https://github.com/pgbackrest/pgbackrest/files/7816203/postgres_pgbackrest.conf.zip)
thub.com/pgbackrest/pgbackrest/files/7816190/pgbackrest.log.zip)
krest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[pgbackrest.conf.zip](https://github.com/pgbackrest/pgbackrest/files/7816165/pgbackrest.conf.zip)

7. Describe the issue:

After manually starting the backup I did hit ctl-C. After this not all processes on the database hosts where cleaned up. As a matter of fact, they kept running forever, as orphans. Normally this backup runs within a few seconds since it is only a small empty testing cluster.

postgres 1717027       1 47 Jan04 ?        09:57:49 pgbackrest --exec-id=975759-47d08a73 --log-level-console=off --log-level-file=off --log-level-stderr=error --pg1-path=/pgs02/data --process=0 --remote-type=pg --stanza=djiapgs-poccie backup:remote

this was both on the primary as on the standby nodes.
If needed I can assist further testing/debugging when needed.

**Comment by dwsteele** [comment]
This was fixed in 2.36 (at least for the cases we could reproduce) so you should upgrade and let us know if you still see the issue.

**Comment by ikzelf** [comment]
Thanks, where I reproduced the issue with 100% accuracy using 2.35. Now with 2.36 I am no longer able to reproduce.
