### ISSUE TITLE
Pgbackrest patroni pitr

### ISSUE THREAD

**Issue by bikej** [pgbackrest/pgbackrest#1615]
Hi

I have a patroni postgres v13.5 cluster on 3 nodes (centos7). My database is 2.5TB large.

I am investigating pgbackrest as a backup solution.

For now backup works like a charm. 
As for restore I have a fourth postgres server where I restore what I want (for example a single database, than get what I need, dump it and import it to the cluster). 

My question is about PITR. Can I somehow do a pitr restore on my fourth standalone postgres and from there get what I need? 
I don't want to completly whipe the whole cluster. Is this even possible?

I tried it a few times and I always get something like
`FATAL:  requested timeline 17 is not a child of this server's history`

#238

**Comment by pgstef** [comment]
Hi,

Usually, a successful recovery means that when the recovery target is reached, PG switches on a new timeline and promote as primary (accept read-write queries). Your restored PG server (where a PITR has been done) won't be able to be used as a replication standby. It will become a totally standalone node.

So I'd say yes, restore to a standalone server, extract the data you want and import it on your cluster primary PG node should work. But that's more a generic PG question (about PITR, backups and streaming replication). Not specific to patroni or pgbackrest.

Kind Regards

**Comment by bikej** [comment]
OK I think the problem was that I always did a pitr from my last incremental backup and not from last full backup. Now I did a full backup, then dropped some tables, recorded the time and restored to the point in time on my fourth server and postgres started fine and my tables are there.
Again tested it from incremental and could't do anything with my table.

So I would conclude pitr works only from full backup.

**Comment by pgstef** [comment]
> So I would conclude pitr works only from full backup.

That seems to be a very weird conclusion. Incremental backups are just storing files modified since the previous backup. And PITR works fine no matter the backup type. It's probably your example that doesn't work. And fwiw, pgBackRest auto-select the accurate backup set to restore according to the `--type=time --target` provided.

Given you don't give any detail regarding your configuration / PG version / commands and parameters used,... it will be hard to help you diagnose anything though.

**Comment by bikej** [comment]
You were right ofcourse. 
After table creation and after table deletion I executed _select pg_switch_wal();_  to make sure all the changes are archived.
And after restore I executed _select pg_wal_replay_resume();_.

Now I have a sucesfull full restore, incr/diff restore, selected db restore and pitr. Thx for your hints.

**Comment by pgstef** [comment]
> You were right ofcourse. After table creation and after table deletion I executed _select pg_switch_wal();_ to make sure all the changes are archived. And after restore I executed _select pg_wal_replay_resume();_.
> 
> Now I have a sucesfull full restore, incr/diff restore, selected db restore and pitr. Thx for your hints.

Glad you figured it out.

It's important to note that pgBackRest only handles the restore step (preparing the pg_data) but PG handles the recovery. It's then important to understand all the recovery steps and parameters involved. Usually, PG logs are pretty great to understand what's going on.

Fwiw, you can use `--target-action=promote` if you don't want to exec `pg_wal_replay_resume` manually. And the **check** command is triggering a `pg_switch_wal`. So it's possible to only use the pgbr commands if you'd prefer ;-)

Kind Regards
