### ISSUE TITLE
Exit code 082 archive push fails until restarting Postgres

### ISSUE THREAD

**Issue by Tostino** [pgbackrest/pgbackrest#1617]
1. pgBackRest version: 2.36

2. PostgreSQL version: PostgreSQL 10.19 (Debian 10.19-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: All servers run Debian GNU/Linux 9.13 (stretch) (repo, db primary, db replica)

4. Did you install pgBackRest from source or from a package? Package (pgdg)

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) 
[db_pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/7830126/db_pgbackrest.conf.txt)
[repo_pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/7830071/repo_pgbackrest.conf.txt)

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    archive_command = 'pgbackrest --process-max=2 --stanza=main archive-push %p'

    - errors in the postgresql log file before or during the time you experienced the issue
2022-01-07 16:16:26.035 P00   INFO: archive-push command begin 2.36: [pg_wal/000000020000484D000000AF] --archive-async --exec-id=21401-1aa26eeb --log-level-console=detail --pg1-path=/var/lib/postgresql/10/main --process-max=2 --repo1-host=10.136.12.17 --repo1-host-user=backrest --spool-path=/var/spool/pgbackrest --stanza=main
...
ERROR: [082]: unable to push WAL file '000000020000484D000000AF' to the archive asynchronously after 60 second(s)
2022-01-07 16:17:26.054 P00   INFO: archive-push command end: aborted with exception [082]
2022-01-07 16:17:26.056 UTC [2155] LOG:  archive command failed with exit code 82
2022-01-07 16:17:26.056 UTC [2155] DETAIL:  The failed archive command was: pgbackrest --process-max=2 --stanza=main archive-push pg_wal/000000020000484D000000AF
2022-01-07 16:17:26.056 UTC [2155] WARNING:  archiving write-ahead log file "000000020000484D000000AF" failed too many times, will try again later

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
As stated in the prior issue (https://github.com/pgbackrest/pgbackrest/issues/834), I am getting this 082 exit code and have WAL archiving failing. I took the advice from @pgstef and ran the archive command manually with --log-level-console=debug and the result of that is here: [pgbackrest_push.log](https://github.com/pgbackrest/pgbackrest/files/7830092/pgbackrest_push.log)

**Comment by Tostino** [comment]
If it matters, my spool directory is empty and my pg_wal has all the WAL files still sitting there. I'm guessing that's expected, but wanted to mention in case.

**Comment by dwsteele** [comment]
We need to see the `archive-push-async` log. It looks like the problem is in the async process. The archive-push process is just erroring because it never sees any notifications.

**Comment by Tostino** [comment]
Yeah, absolutely, here is the log:
[main-archive-push-async.log](https://github.com/pgbackrest/pgbackrest/files/7831209/main-archive-push-async.log)

**Comment by dwsteele** [comment]
Here's the main error I'm seeing in the log:
```
2022-01-07 15:52:15.363 P00  ERROR: [103]: unable to find a valid repository:
                                    repo1: [StopError] raised from remote-0 ssh protocol on '10.136.12.17': stop file exists for all stanzas
```
Looks the repo host had `pgbackrest stop` run on it?

I also see a ton of abort signals, protocol errors, etc. The protocol errors basically mean that state has been lost due to severe errors in the workers. I would add `--log-subprocess --log-level-file=debug` to the `archive-push` command and then collect the `archive-push-async-local*` logs from the pg host and the `archive-push-async-remote*` logs from the repo host.

But first, make sure that you run `pgbackrest start` on your repo host.

**Comment by Tostino** [comment]
That was me trying to get it back up and running (unsuccessfully) this morning. Not the root cause of it happening. I sigkilled the pgbackrest workers this morning because it almost took my application down by having ~6-8 pgbackrest processes running, eating 100% cpu each. No idea why there were that many archive workers active, I have max-process=2 for my archive command... I then set my archive command to /bin/false then killed them so I can deal with it tonight.

**Comment by Tostino** [comment]
Ignore me, this server got into an out of disk space situation after I had confirmed that it had plenty open, and I didn't think to check again. Unsure if the lack of disk space was the root cause, because I had checked earlier and there was space, but this whole thing is too messed up to even use to troubleshoot.  Sorry for wasting your time, my bad =(.

**Comment by dwsteele** [comment]
Well, hopefully out of space would not be causing lockups. Hopefully we can track this down at some point.
