### ISSUE TITLE
Number of CPUs required on a remote backup server

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#1618]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.35

2. PostgreSQL version:
13.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 7

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
N/A

7. Describe the issue:
Currently, we back up the cluster to a local repository and use 12 threads.  Soon we'll migrate it to a kubernetes container.  Thus, we want to create a remote backup server.
Will we also need 12 CPUs on the backup server?

**Comment by Tostino** [comment]
You are not required to have the same number of cores on your repo server as the threads/processes you run on your db server. For example, I have a 16 core DB server that I backup with 6 threads, but my repo server is a 2 core machine, and is not maxed out CPU wise.

**Comment by dwsteele** [comment]
Exactly. Since compression/decompression is performed on the pg host, the repo host does not need nearly as much horsepower. But you need enough cores to encrypt/decrypt on SSH/TLS. I find 1 repo core per 4 pg cores is more than adequate.

**Comment by RonJohn2** [comment]
@Tostino and @dwsteele thanks for the info.
