### ISSUE TITLE
Priority inversion with very large queues

### ISSUE THREAD

**Issue by fdr** [pgbackrest/pgbackrest#1622]
1. pgBackRest version: 2.36

2. PostgreSQL version: 14

3. Operating system/version: AlmaLinux 8.5

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
  
```
[asdf]
pg1-path=/var/lib/pgsql/12/data

[global]
log-level-console=detail
log-level-file=detail
archive-async=y
process-max=16
repo1-retention-diff=2
repo1-retention-full-type=time
repo1-retention-full=10
compress-type=lz4
archive-mode-check=n

[global:archive-push]
compress-level=6

[global:archive-get]
spool-path=/dat/pgbackrest_spool
archive-get-queue-max=220GB
```

7. Describe the issue:

We noticed that considerably larger instances were taking many times longer than smaller instances to restore a single backup. Upon inspection, postgres was waiting for a segment for a very long time. I tried restarting postgres, the server, and deleting the spool directory several times as I was narrowing things down, but it would always stick at the same segment.

I then noticed that the file system hosting the spool was writing out about as fast it could go, almost five gigabits per second, and I had noticed by this point having cleared the spool directory several times that it was getting (re)filled rapidly. I then noticed the definitely too-huge archive-get-queue-max and shrank it to something more reasonable. Then everything worked very well. Looks like a priority inversion. I plan to adjust the queue max, but perhaps there is an opportunity for optimization here, to avoid inversions that fall short of the cataclysmic that may nonetheless cause delay.

The main differences between larger and smaller instances are:

* More processors, which gets fed into `process-max`
* Much more disk bandwidth

The archive queue is calculated in a way where that remains the same regardless of instance size (for now).

**Comment by dwsteele** [comment]
I don't think this is an inversion, exactly, but last year we did a lot of work to improve overall IO (especially for object stores) so we are doing a lot of work up front which is not ideal for getting the first jobs out quickly when the queue is very large.

Overall we've never seen any evidence that a queue needs to be larger than a few gig. pgBackRest is able to get WAL far faster than PostgreSQL can replay it.

I'm sure there are various optimizations that could be done, but I think just limiting the amount of work that each async process does, say to 128 or 256 segments, would solve the problem and still allow very large queue sizes if they are needed for some reason we have not thought of.

**Comment by fdr** [comment]
Not sure how it's not an inversion, it's using up a lot of resources but not getting the right work done.

**Comment by fdr** [comment]
I suppose you could say there's no prioritization at all (if true), so there's nothing to invert.

**Comment by dwsteele** [comment]
I wasn't able to repro any inversion at all, but I don't have a system large enough to build a 200GB+ queue. All I can see is a delay to the start of work, which then proceeds in order. It could be there are other bottlenecks that I'm not seeing, but using smaller work units should take care of those if they exist. I don't think further optimization of very large queues is worth the time since the are not useful.

**Comment by dwsteele** [comment]
Added a project card for this improvement.

**Comment by fdr** [comment]
Yeah, I think it is a delay is really how it pans out, it just can be rather long. However, it's quite puzzling that rather than being merely suboptimal that getting the next segment is starved out so long and so deterministically. That is not what I would expect from a system that took the simple approach of requesting segments in order and doing no prioritization.

**Comment by dwsteele** [comment]
Fair enough. We used to be better at this but we got complaints about how much IO we were using (i.e. costing!) on object stores. Basically, each process would go do its own work, which really racked up LIST requests. Now we do more work up front to minimize LIST requests but clearly that works poorly for very large queues.

It seems to me the easiest solution is to limit the size for any single async run. This allows very large queues without the overhead of figuring out the entire queue in advance. The performance overall will be slightly lower but we should get the initial segments to postgres more quickly and from there staying ahead should not be an issue.

**Comment by fdr** [comment]
Perhaps there is a simple adaptive algorithm that backrest can learn akin to the 'max wal' setting in Postgres. There's no extra points to getting really far ahead of the server, and there are demerits for suffering a pipeline stall. I was watching the prefetcher in action for a while as I was tweaking the smaller queue sizes and I think there may be some room for improvement, though it's hard to say without a statistic rolling up spool misses.
