### ISSUE TITLE
is there a mailinglist or forum around pgBackRest?

### ISSUE THREAD

**Issue by vrms** [pgbackrest/pgbackrest#1624]
sorry, I wouldn't know where else to ask (no info on this on the pgbackrest.org site unforunately)

so, is there any mailing list or forum where you would be expecting responses on pgbackrest related matters? 
I checked dba.stackexchange.com which does only show very few postings on the matter?

**Comment by pgstef** [comment]
Hi,

> so, is there any mailing list or forum where you would be expecting responses on pgbackrest related matters?

GH issues are pretty much the best place to ask imo. Especially if we'd need logs/configs to help you.

For "small" questions, I guess there's the pgbackrest slack channel on postgresteam.slack.com

Kind Regards

**Comment by vrms** [comment]
thx

> _For "small" questions, I guess there's the pgbackrest slack channel on postgresteam.slack.com_

I am not well versed with slack ... but it looks like that postgresteam.slack.com is a closed group?

**Comment by pgstef** [comment]
> I am not well versed with slack ... but it looks like that postgresteam.slack.com is a closed group?

That's the PG community one : https://www.postgresql.org/community/
Seems like the good link is https://postgres-slack.herokuapp.com/

Once there, you'll find a lot of various channels (general, pgbackrest, patroni,...)
