### ISSUE TITLE
Does repmgr support pgBackRest backup tools?

### ISSUE THREAD

**Issue by wasiualhasib** [pgbackrest/pgbackrest#1629]
**I am facing an issue to work with pgBackRest and repmgr**
- pgBackRest version 2.37 , 
- PostgreSQL 13
- Operating system Centos 7
- repmgr 5.2
- I did install pgBackrest using yum 
I am not able to restore restore those backup data using pgBackRest. Some experts said it will not working with repmgr because LSN number not matched.
 
I need to know below few question
1. Does it support PostgreSQL 13 and repmgr 5.2
2. Is it possible to use with repmgr?
2. If possible how can I restore  in case of repmgr? Actually need to know steps of restoring primary to standby in case of repmgr.
3. Is there a document how can I configure with repmgr? 

pgBackRest document wise it is working well but with repmgr till backup it is working    as expected. But when I am going to restore in that case I found an issue. 
Need experts opinion.

**Comment by pgstef** [comment]
Hi,

First of all, this seems more like a question for repmgr itself. Other tools like Patroni are working just fine with pgBackRest because they implemented a correct use of the commands to (re)build standby servers.

>  I am not able to restore restore those backup data using pgBackRest. Some experts said it will not working with repmgr because LSN number not matched.

What do you mean by that? What's the error you get? Building standby servers with pgBackRest works fine if done correctly.

> pgBackRest document wise it is working well but with repmgr till backup it is working as expected. But when I am going to restore in that case I found an issue. Need experts opinion.

repmgr is built on top of [pgbarman](https://repmgr.org/docs/current/cloning-from-barman.html) and I don't think they will integrate pgBackRest commands for the cloning part.
So, or you use repmgr to clone using pg_basebackup, or you do that part manually with pgBackRest.

I quickly installed repmgr on top a cluster using pgBackRest (used `pgbackrest restore --type=standby` to build the replica) and it seems to work:
```
repmgr=# SELECT * FROM repmgr.nodes;
-[ RECORD 1 ]----+--------------------------------------------------------
node_id          | 1
upstream_node_id | 
active           | t
node_name        | c7pg-1
type             | primary
location         | default
priority         | 100
conninfo         | host=c7pg-1 user=repmgr dbname=repmgr connect_timeout=2
repluser         | repmgr
slot_name        | 
config_file      | /etc/repmgr/14/repmgr.conf
-[ RECORD 2 ]----+--------------------------------------------------------
node_id          | 2
upstream_node_id | 1
active           | t
node_name        | c7pg-2
type             | standby
location         | default
priority         | 100
conninfo         | host=c7pg-2 user=repmgr dbname=repmgr connect_timeout=2
repluser         | repmgr
slot_name        | 
config_file      | /etc/repmgr/14/repmgr.conf

repmgr=# SELECT * FROM pg_stat_replication WHERE application_name='c7pg-2';
-[ RECORD 1 ]----+------------------------------
pid              | 10402
usesysid         | 16393
usename          | repuser
application_name | c7pg-2
client_addr      | 172.18.0.3
client_hostname  | 
client_port      | 39206
backend_start    | 2022-01-20 10:44:18.661204+00
backend_xmin     | 
state            | streaming
sent_lsn         | 0/2A0003D8
write_lsn        | 0/2A0003D8
flush_lsn        | 0/2A0003D8
replay_lsn       | 0/2A0003D8
write_lag        | 
flush_lag        | 
replay_lag       | 
sync_priority    | 0
sync_state       | async
reply_time       | 2022-01-20 10:50:59.924475+00
```

So, the `repmgr primary/standby register` commands are working. The `repmgr standby switchover --siblings-follow` command also seems to work:
```
repmgr=# SELECT * FROM repmgr.nodes;
-[ RECORD 1 ]----+--------------------------------------------------------
node_id          | 2
upstream_node_id | 
active           | t
node_name        | c7pg-2
type             | primary
location         | default
priority         | 100
conninfo         | host=c7pg-2 user=repmgr dbname=repmgr connect_timeout=2
repluser         | repmgr
slot_name        | 
config_file      | /etc/repmgr/14/repmgr.conf
-[ RECORD 2 ]----+--------------------------------------------------------
node_id          | 1
upstream_node_id | 2
active           | t
node_name        | c7pg-1
type             | standby
location         | default
priority         | 100
conninfo         | host=c7pg-1 user=repmgr dbname=repmgr connect_timeout=2
repluser         | repmgr
slot_name        | 
config_file      | /etc/repmgr/14/repmgr.conf

repmgr=# SELECT * FROM pg_stat_replication;
-[ RECORD 1 ]----+------------------------------
pid              | 5486
usesysid         | 24577
usename          | repmgr
application_name | c7pg-1
client_addr      | 172.18.0.2
client_hostname  | 
client_port      | 34860
backend_start    | 2022-01-20 11:04:59.714925+00
backend_xmin     | 
state            | streaming
sent_lsn         | 0/2B000750
write_lsn        | 0/2B000750
flush_lsn        | 0/2B000750
replay_lsn       | 0/2B000750
write_lag        | 
flush_lag        | 
replay_lag       | 
sync_priority    | 0
sync_state       | async
reply_time       | 2022-01-20 11:08:01.157751+00
```

With a little bit of config/testing/practice, I guess you could use repmgr with pgbackrest to take backups and use pgbackrest restore for the "cloning" part.

That being said, it totally depends why you want to use repmgr in the first place. For auto-failover, I'd definitely recommend using Patroni which is well tested with pgBackRest.

Both repmgr and Patroni are external tools (not linked to this project), so I'm not sure it would be up to us to give you that kind of tutorial/user-guide ;-)

Kind Regards

**Comment by wasiualhasib** [comment]
@pgstef Thanks for your answer. May I know how did you configure in postgresql.conf file in  primary and standby server. I think here I did mistake in case of restore and backup command using pgBackRest. That's why I am unable to restore.

**Comment by pgstef** [comment]
> @pgstef Thanks for your answer. If you have any configuration on repmgr and pgBackRest then I need little help on postgresql.conf file configuration on primary and standby server. I think here I did mistake in case of restore and backup in configuration file. That's why I am unable to restore. Only restore issue I moved to pgbarman. If you can solve this issue then I will back to pgBackRest.

Not sure what you're expecting here. I don't have the vms anymore but I didn't had any special config. I followed my usual install setup (for PG and pgBackRest at least, as I already wrote [here](https://pgstef.github.io/2020/09/04/combining_pgbackrest_and_streaming_replication.html)).

PG defaults settings and generated configs from pgBR should allow you to perform a successful recovery / replica refresh pretty easily.

The non-default PG 13 settings I often set are:
```ini
listen_addresses = '*'
archive_mode = on
archive_command = 'pgbackrest --stanza=mycluster archive-push %p'
```

Then using `pgbackrest --stanza=mycluster --type=standby restore` gives this config automatically:
```ini
# Recovery settings generated by pgBackRest restore...
primary_conninfo = 'host=primary user=replic_user'
restore_command = 'pgbackrest --stanza=mycluster archive-get %f "%p"'
```

Repmgr is able to use barman to create/refresh a replica (clone command). It can't do it with pgBackRest. That's their choice ;-) so you have to perform that step yourself using pgBackRest manually. You should first try to setup a replication cluster using pgBackRest before adding repmgr. So you'd have more details about your PG/pgBR settings.

That being said, I don't see how we can help you further given you're really vague about your config/setup/commands used/logs/... If you want more help, follow the issue template and provide the configs/logs/... requested (without using repmgr).

Regards
