### ISSUE TITLE
can we use pgBackRest in patroni standby cluster?

### ISSUE THREAD

**Issue by HalacliSeda** [pgbackrest/pgbackrest#1635]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):
Hello,
I set up the Patroni. I couldn't get a backup in standby cluster. I cannot specify primary server settings. Because I'm already backing up the primary on a separate server. Can I have a backup in the standby cluster independently of the pgbackrest in the primary cluster?

1. pgBackRest version: 2.37

2. PostgreSQL version: 13.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  CentOS8

4. Did you install pgBackRest from source or from a package?
I installed pgbackrest from package with dnf command.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
_On standby leader:_

 cat /etc/pgbackrest.conf 
**[global]
repo1-host=BACKUP-HOST
repo1-host-user=postgres
log-level-console=info
log-level-file=detail

[db-primary]
pg1-path=/pgsql/13/data
pg1-port=5432
compress-type=none
backup-standby=y
archive-async=y**

_On backup server:_
cat /etc/pgbackrest.conf 
**[global]
repo1-path=/var/lib/pgbackrest
repo1-host-user=postgres
process-max=4
log-level-console=warn
log-level-file=detail

[db-primary]
pg1-host=147.182.202.24
pg1-host-user=postgres
pg1-path=/pgsql/13/data
pg1-port=5432
compress-type=none
repo1-retention-full=2
start-fast=y
backup-standby=y**

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
**archive_mode: on 
archive_command:  pgbackrest --stanza=db-primary archive-push %p
listen_addresses: 0.0.0.0
max_wal_senders: 10
wal_level: replica
port: 5432**

    - errors in the postgresql log file before or during the time you experienced the issue
I didn't get postgres log error

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
"ERROR: [056]: unable to find primary cluster - cannot proceed " in db-primary-stanza-create.log.

7. Describe the issue:

I am getting error in stanza-create command on command line:
pgbackrest --stanza=db-primary stanza-create
2022-01-25 13:15:20.237 P00   INFO: stanza-create command begin 2.37: --backup-standby --exec-id=45782-07497398 --log-level-console=info --log-level-file=detail --pg1-path=/pgsql/13/data --pg1-port=5432 --repo1-host=BACKUP-HOST --repo1-host-user=postgres --stanza=db-primary
ERROR: [056]: unable to find primary cluster - cannot proceed
2022-01-25 13:15:20.842 P00   INFO: stanza-create command end: aborted with exception [056]

In standby leader:
postgres=# select pg_is_in_recovery();
 pg_is_in_recovery 
-------------------
 t
(1 row)

Postgres user can passwordless ssh connection between standby leader and backup server.

**Comment by pgstef** [comment]
Hi,

> Hello, I set up the Patroni. I couldn't get a backup in standby cluster. I cannot specify primary server settings. Because I'm already backing up the primary on a separate server. Can I have a backup in the standby cluster independently of the pgbackrest in the primary cluster?

This question can be simply related to a streaming replication cluster without using Patroni, the answer would be the same.
No, you can't backup **only** from the standby. As shown in the [user-guide](https://pgbackrest.org/user-guide.html#standby-backup), the stanza section needs to contain both the primary db and the standby (pg1-2 options).
Quickly said, the backup control session will be executed against the primary db to make sure the standby isn't out of sync. Then, the main data files will be copied from the standby.

Furthermore, by default, the archives are pushed to the repo from the primary cluster. That's then interesting to use the multi-repo feature. Define the 2 repo-hosts on both primary/standby, the archives will be pushed by the primary to both repos. Then you can take backup from 1st repo-host targeting the primary-host and on the 2nd repo-host targeting the standby-host.
If you define the 2 pg hosts in the configurations of your repo-hosts, even in case of failover (using patroni), the backups would be taken accordingly and the archives pushed from the new primary.

Hope this helps,
Kind Regards

**Comment by HalacliSeda** [comment]
Thank you for your quick answer,

Have a nice day
