### ISSUE TITLE
Does pgbackrest 2.37 still not support proxy usage?

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#1639]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.37
2. PostgreSQL version:
12.X
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS 7
4. Did you install pgBackRest from source or from a package?
yum install

7. Describe the issue:
Trying to use in house S3 service, but there's a proxy between it and our DB servers, timeout when trying to create stanza

**Comment by dwsteele** [comment]
If the proxy requires explicit configuration, we don't support it. In general running pgBackRest traffic through a proxy is not ideal and there hasn't been demand.

**Comment by mattbunter** [comment]
OK, thanks for the feedback.
