### ISSUE TITLE
Upgrade pgbackrest version from 2.18 to 2.27

### ISSUE THREAD

**Issue by julienc256** [pgbackrest/pgbackrest#1640]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2.18

2. PostgreSQL version:

11.14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Linux RedHat 7.8
One Master and one Standby running both with pgbackrest 2.18.

4. Did you install pgBackRest from source or from a package?

rpm package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Non applicable 

7. Describe the issue:

This is not an issue, but a question !
We intend to upgrade pgBackrest version from 2.18 to 2.27 (and later to 2.37), because we want to use "repo1-retention-full-type=time" parameter

My question is :

Is there a risk that backup compatibility is no longer guaranteed on the new version ? 

Once v2.27 is installed, can I restore an old backup made with pgBackrest v2.18 ?

Or is it better to make a backup immediately after the upgrade to pgBackrest v2.27 ?

**Comment by dwsteele** [comment]
The repo format has not changed since 1.0, so this should not be a problem.

Of course, it is up to you to test and make sure everything works in your environment.

**Comment by julienc256** [comment]
Thanks for your quick answer ! :)
