### ISSUE TITLE
Question regarding pgbackrest wal archiving in 'hard failover' scenario

### ISSUE THREAD

**Issue by MannerMan** [pgbackrest/pgbackrest#1646]
Hi!

I unsuccessfully searched previous issues/questions here to find an answer, if this question has already been answered I apologize, please point me in the right direction!

I have a three node postgres setup, one primary (DB01) two standbys [02 and 03]
```
      [DB01]   <- primary
    /       \
[DB02]      [DB03]  <- standbys
```

If we do a 'soft failover', I.e. a controlled timeline switch where we promote DB02 to primary, and DB01 & DB03 is attached as a standbys to DB02; It is my understanding that configuring `archive_mode: on` and `archive_command: /usr/bin/pgbackrest [...]` on all nodes should support this case nicely, since archiving will simply stop on DB01 and start on DB02 once it's promoted. Have I understood this correctly?

Things get a bit more tricky in a hard failover situation though, where the cluster might end up with two nodes not in recovery mode:
```
      [DB01]  <- failed primary, perhaps it stopped responding for a few minutes but came back

[DB02] ----- [DB03]  <- attached as standby to DB02
  |
  └ promoted to new primary
```
In this case, both DB01 and DB02 would be archiving from two separate timelines to the same stanza. I guess this would be less than optimal, or how will pgbackrest handle this? Are WAL collisions a concern here or will the WAL from DB02 follow a different sequence since the timeline switch? Are there any best practices to be applied in this case to prevent this situation or other remedies?

**Comment by pgstef** [comment]
Hi,

> If we do a 'soft failover', I.e. a controlled timeline switch where we promote DB02 to primary, and DB01 & DB03 is attached as a standbys to DB02; It is my understanding that configuring `archive_mode: on` and `archive_command: /usr/bin/pgbackrest [...]` on all nodes should support this case nicely, since archiving will simply stop on DB01 and start on DB02 once it's promoted. Have I understood this correctly?

Indeed, archives will only be generated on the primary then.

> In this case, both DB01 and DB02 would be archiving from two separate timelines to the same stanza. I guess this would be less than optimal, or how will pgbackrest handle this? Are WAL collisions a concern here or will the WAL from DB02 follow a different sequence since the timeline switch? Are there any best practices to be applied in this case to prevent this situation or other remedies?

If you come to have 2 primaries, that's what called "split brain". And at some point if you get there, with users writing data at both places, you'll have a lot of joy to bring those back together.
So the first and most important advice is to make sure to avoid the split brain situation. If it's a manual fail-over, make sure the old primary is down before actually promoting a standby. If you rely on an automatic tool, then make sure there's some kind of fencing/stonith or watchdog+witness. Patroni does that pretty good imho.

Now, at some point split brain happened and you have 2 timelines written in the archives. Timeline is part of the WAL filenames (actually the first 8 digits). So you'll be able to find in the repo what archives come from what timeline, and in the `.history` files the point where the timeline switched. So you'll be able to dig deeper thanks to those info.

All this is PG related, not pgBackRest to be clear.

Kind Regards

**Comment by MannerMan** [comment]
> Indeed, archives will only be generated on the primary then.

Thank you for confirming this!

> If you come to have 2 primaries, that's what called "split brain". And at some point if you get there, with users writing data at both places, you'll have a lot of joy to bring those back together. So the first and most important advice is to make sure to avoid the split brain situation. If it's a manual fail-over, make sure the old primary is down before actually promoting a standby. If you rely on an automatic tool, then make sure there's some kind of fencing/stonith or watchdog+witness. Patroni does that pretty good imho.

Yes we are aware of the split-brain issue! Our configuration uses synchronous replication, combined with `synchronous_standby_names ANY 1 (..)` setting on all nodes to ensure that there is at least one synchronous replica attached for a node acting as primary to be able to accept writes. This is our split-brain protection, since it should ensure that a failed/fenced off primary (DB01 in the example above) will never be able to commit a write operation. We use repmgr for manual and automatic failover operations, which has been working well for us so far. I have also heard good things about patroni :)

> Now, at some point split brain happened and you have 2 timelines written in the archives. Timeline is part of the WAL filenames (actually the first 8 digits). So you'll be able to find in the repo what archives come from what timeline, and in the `.history` files the point where the timeline switched. So you'll be able to dig deeper thanks to those info.

Yes, this is the main reason I have created this issue. Even though we have the split-brain protection preventing new writes to a failed primary, it will still (presumably) generate WAL because of the `archive_timeout` setting. As I understand from your reply, even if this should happen the information necessary for recovery is present in the archives. Let's say we have a base-backup taken at DB01 from before a 'hard failover' happened, and both DB01 and 02 wrote WAL to the archive for a while; Would a pgbackrest recovery command automatically follow the timeline switch in the archive and ignore the additional WAL sent by DB01?

> All this is PG related, not pgBackRest to be clear.

Yes I suppose it is, I mainly wanted to know how pgbackrest behaves in a situation where two nodes using the same stanza archives WAL; If it is less of an issue or if we should implement some mechanic to attempt to prevent it.

Thank you kindly for your reply!

**Comment by pgstef** [comment]
> Would a pgbackrest recovery command automatically follow the timeline switch in the archive and ignore the additional WAL sent by DB01?

pgBackRest doesn't do recovery. The restore command only prepares the files for PG to handle the recovery. So it will depend on your PG config. More specifically the PG setting `recovery_target_timeline` which can be set by the `--target-timeline` pgBackRest option.

After PG 12, this setting is set to latest. Which mean that when a recovery will be attempted, it will follow the path of the latest generated timeline. But you could force a specific restore to follow the "current" timeline (the one active when the backup was taken i.e.) to extract data and put those back into the real primary cluster.

**Comment by MannerMan** [comment]
> > Would a pgbackrest recovery command automatically follow the timeline switch in the archive and ignore the additional WAL sent by DB01?
> 
> pgBackRest doesn't do recovery. The restore command only prepares the files for PG to handle the recovery. So it will depend on your PG config. More specifically the PG setting `recovery_target_timeline` which can be set by the `--target-timeline` pgBackRest option.
> 
> After PG 12, this setting is set to latest. Which mean that when a recovery will be attempted, it will follow the path of the latest generated timeline. But you could force a specific restore to follow the "current" timeline (the one active when the backup was taken i.e.) to extract data and put those back into the real primary cluster.

Thank you for clarifying! We'll do some testing in our staging environment to ensure we have configured postgres correctly for this. I'll close this issue now, thank you for your replies, and thanks for providing pgbackrest, it has been working exceptionally well for us!
