### ISSUE TITLE
Expire only remaining backup

### ISSUE THREAD

**Issue by loop-evgeny** [pgbackrest/pgbackrest#1647]
1. pgBackRest version: 2.36
2. PostgreSQL version: 14.1

```
pgbackrest --stanza=... expire --set=20220130-010004F
ERROR: [075]: repo1: full backup 20220130-010004F cannot be expired until another full backup has been created on this repo
ERROR: [104]: expire command encountered 1 error(s), check the log file for details
```

I want to delete the only remaining backup. How do I do that? Should I manually delete the stanza directory and re-create the stanza? I'm not sure what other effect that may have. It would be better if pgBackRest allowed this with the expire command, perhaps with some special option like --yes-i-know-its-the-last-one.

**Comment by pgstef** [comment]
Hi,

The question is more "why" do you want to remove this backup ? It can be expired easily on the next backup...
The archives are expired based on the earliest backup too, so that first is important.
If you really don't need what's currently inside your repo (because those were all test data), then you can simply `stanza-delete`+`stanza-create`?

Regards

**Comment by loop-evgeny** [comment]
The repository host ran out of disk space, and I needed space urgently for something else. I considered deleting and re-creating the stanza, but wasn't sure if that would also delete some configuration, so it was unclear if it was really "safe" to do that. With the `expire` command I could be sure it would only delete data.

**Comment by pgstef** [comment]
`stanza-delete` will only remove the "stanza" directory inside the repo (and then prevent the archive-push command to work until stanza-create). The code can be found [here](https://github.com/pgbackrest/pgbackrest/blob/b1da4e84e8b1fda0299931dbcb9b057ce0d3ce64/src/command/stanza/delete.c#L78) if you want to be verify.

To remove the stanza repo content, you first have to `stop` it and use `--force` to delete when the PG cluster is still up and running. But that should work for your use-case indeed.

I'd have to dig deeper to confirm but probably `force` expire a backup set would only require changing [this](https://github.com/pgbackrest/pgbackrest/blob/b1da4e84e8b1fda0299931dbcb9b057ce0d3ce64/src/command/expire/expire.c#L115). Before looking at it, it would be best to know what @dwsteele thinks about this feature request ;-)

**Comment by dwsteele** [comment]
There are other reasons for this, e.g. the most recent backup might be one in progress. Also, should we just remove all the WAL? It makes the expire code more complicated for little benefit.

In this case I think stanza-delete/stanza-create is the way to go.

**Comment by loop-evgeny** [comment]
stanza-create has some options (--backup-standby, --online). Suppose I don't remember what options I specified when creating the stanza. I don't remember what I specified when creating the stanza, but I presume these are saved somewhere? So if there was "recreate-stanza" command that deleted and re-created it with the same options I suppose that would work, but surely deleting the only backup is easier?

Yes, I would expect all the WAL to be removed. As I understand, it's tied to a backup set and useless without one - is that right?

**Comment by dwsteele** [comment]
> I don't really see why backup-standby would be used

Looks like a copy-paste error from way back. I'm testing without these options and I'll commit if it works.

**Comment by dwsteele** [comment]
backup-standby option removed from stanza commands at 5cbb4a3e6b13598.

**Comment by dwsteele** [comment]
The stanza info should not depend on any options except the pg* configuration, so running stanza-delete/stanza-create will give the the same stanza info before, provided the cluster has not changed.

While I can see how this feature could be occasionally useful, it does not seem worth the extra code complexity and tests, so we are not planning on implementing it at this time.
