### ISSUE TITLE
Configuration file location - CentOS7 - pgbackrest-2.37-1.rhel7.x86_64

### ISSUE THREAD

**Issue by aleszeleny** [pgbackrest/pgbackrest#1649]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: `pgbackrest-2.37-1.rhel7.x86_64`

2. PostgreSQL version: *Client*: `postgresql14-14.1-1PGDG.rhel7.x86_64`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

*Repository host*: `CentOS Linux release 7.9.2009 (Core)`

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) : *default RPM created content*
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`): *No postgres server installed nor used - repository host setup only*
    - errors in the postgresql log file before or during the time you experienced the issue: *N/A*
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`): *N/A*

7. Describe the issue:

While preparing a new repository host on CentOS7 I've found a potential inconsistency. The [manual](https://pgbackrest.org/configuration.html#introduction) states:

> The default location for the configuration file is `/etc/pgbackrest/pgbackrest.conf`. If no file exists in that location then the old default of `/etc/pgbackrest.conf` will be checked.

While the most recent available RPM on PGDG repository:
```$ sudo yum info pgbackrest.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.icm.edu.pl
 * epel: mirror.hosting90.cz
 * extras: ftp.icm.edu.pl
 * updates: ftp.agh.edu.pl
Installed Packages
Name        : pgbackrest
Arch        : x86_64
Version     : 2.37
Release     : 1.rhel7
Size        : 814 k
Repo        : installed
From repo   : pgdg-common
Summary     : Reliable PostgreSQL Backup & Restore
URL         : http://www.pgbackrest.org/
License     : MIT
Description : pgBackRest aims to be a simple, reliable backup and restore system that can
            : seamlessly scale up to the largest databases and workloads.
            : 
            : Instead of relying on traditional backup tools like tar and rsync, pgBackRest
            : implements all backup features internally and uses a custom protocol for
            : communicating with remote systems. Removing reliance on tar and rsync allows
            : for better solutions to database-specific backup challenges. The custom remote
            : protocol allows for more flexibility and limits the types of connections that
            : are required to perform a backup which increases security.
```
Created the configuration file in the (according to the manual mentioned above) "old" location:
```$ ls -l /etc/pgbackrest*
-rw-r--r-- 1 root root 82  3. led 20.53 /etc/pgbackrest.conf
```
As mentioned in the manual, it will work (and that is true, using that on other servers), but from a maintenance point of view, I'd like to  clarify which location to use:
* RPM created: `/etc/pgbackrest.conf`
* The manual mentioned: `/etc/pgbackrest/pgbackrest.conf`

In terms of the configuration handling during RPM updates. I assume that since RPM installed the "old" style placed configuration file, during RPM updates, this will be properly handled (not overwritten), but it might be, that you suggest using the new configuration file placement in `/etc/pgbackrest/pgbackrest.conf` and future RPM versions will be capable to handle the fact that the configuration file, despite not previously installed by RPM shall be preserved.

Which location for the configuration file, considering the options mentioned above, is preferred?
Thanks for any hints/suggestions.
Ales Zeleny

**Comment by dwsteele** [comment]
The new location (`/etc/pgbackrest/pgbackrest.conf`) is preferred. My understanding is it is really hard to move the config file in the packages without causing problems and that's why it never happened (Debian, too).

Not really sure what can be done about this. We don't maintain the packages.

**Comment by aleszeleny** [comment]
Hello,

thanks for the clean answer and for all the amazing work on pgBackRest!
