### ISSUE TITLE
S3 InternalError when WAL expiry is configured

### ISSUE THREAD

**Issue by alex-richman-onesignal** [pgbackrest/pgbackrest#1650]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.37

2. PostgreSQL version:
10-1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 18.04 LTS

4. Did you install pgBackRest from source or from a package?
Package from the postgres repo

Related to https://github.com/pgbackrest/pgbackrest/issues/929 but I didn't want to necro that issue.

Our DBs generate a fair bit of WAL (>200MB/s), so there are lots of archived WAL files hanging around in S3.  When an archive retention policy is configured, expiry fails with:
```
2022-02-07 14:53:16.121 P00   INFO: repo1: expire full backup 20220205-011002F
2022-02-07 14:53:16.230 P00   INFO: repo1: remove expired backup 20220205-011002F
ERROR: [060]: repo1: unable to remove file '.../archive/main/10-1/xxxxx': [InternalError] We encountered an internal error. Please try again.
ERROR: [104]: expire command encountered 1 error(s), check the log file for details
2022-02-07 15:15:02.201 P00   INFO: expire command end: aborted with exception [104]
```

The backup files in `.../backup/` are successfully cleaned up, it's just the WALs that fail.  Per the above issue I tried increasing io-timeout to 3600s, but this didn't seem to help.

In my experience with S3 you get 5xxs for 3 reasons:
1. Occasionally for no reason.  These are typically transient and are easily handled by a retry or two.
2. The rate of operations exceeds the max 3500 writes per second per partition, and S3 drops some ops while it repartitions keys in the background.
3. Concurrent writes to the same key race against each other

Pgbackrest already retries 5xxs, so (1) is unlikely (particularly with a big io-timeout).
(3) is possible but unlikely, and would indicate a bug in how pgbackrest queues and processes DELETEs.  We're using multiple processes, do they work off a common list of objects generated by the parent process or do they individually list and delete objects?
(2) seems most likely, but I've measured the aggregate request rate via tcpdump and it's only around 500/s, far lower than the per partition limit.

Would you be able to advise on the probability of (3), and anything adjacent I have missed?

Cheers,
- Alex.

**Comment by dwsteele** [comment]
This has come up a few times but I have not been to figure out why the retries were not working as expected. But now I see exactly why. Since this a batch delete operation it will only be retried if the *entire* batch fails. In the case of a single file failure there is no retry.

In this case we could retry the entire batch, but I think it is probably simpler to just retry the delete for each file that fails.

Thoughts?

**Comment by dwsteele** [comment]
Linking #929, which is likely caused by the same issue.

**Comment by alex-richman-onesignal** [comment]
Retrying batches seems reasonable, and is presumably easier to implement than splitting the failed keys out and retrying just them.  Perhaps even more so if we could configure the batch size so it could be tuned down if there were issues with lots of failed batches.

**Comment by dwsteele** [comment]
Actually, it looks like retrying the individual failed keys might be easier since we already read them all to determine if there are errors. I'll see once I get into the code in more detail.

**Comment by dwsteele** [comment]
Definitely much easier to switch over to deleting one at a time. See PR #1653.
