### ISSUE TITLE
How to restore single DB without breaking other DBs ?

### ISSUE THREAD

**Issue by emoxam** [pgbackrest/pgbackrest#1659]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.37

2. PostgreSQL version: psql (PostgreSQL) 14.1 (Ubuntu 14.1-2.pgdg20.04+1)

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:Ubuntu 20.04.3 LTS"

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: After restoring one user DB other broken with "**FATAL: relation mapping file "base/24581/pg_filenode.map" contains invalid data Previous connection kept**". How to restore one DB without touching any other ?

**Comment by pgstef** [comment]
Hi,

That limitation comes from PG itself. The all cluster (all dbs and global objects) are saved during a backup for consistency. On restore, you also have to restore the complete cluster.

One nice pgBR feature is the `db-include` option. It allows to restore only 1 db data files and "zeroed" data files for the other dbs. Those files are necessary for the consistency recovery performed by PG. Once your cluster is up and running, you can drop those zeroed dbs.

If you have a running production cluster, the only option you have (with PG) is to restore your backup somewhere else then extract your restored db with pg_dump and re-inject it in your prod cluster with pg_restore.

Regards
