### ISSUE TITLE
When pgbackrest v2.35 running, Ctrl+C , will  leak the  remote process

### ISSUE THREAD

**Issue by Wim1234** [pgbackrest/pgbackrest#1660]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
     V2.35
2. PostgreSQL version:
   PG9.6
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
   CentOS 7.6
4. Did you install pgBackRest from source or from a package?
    from source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    one DB host
    one REPO host
    normal remote backup

7. Describe the issue:
     Normal one DB+one REPO 
     When backup , it work
     When main process on REPO is running, press Ctrl+C ,  
       main process on REPO exit
    BUT the remote-process on DB host hung, does NOT exit

     Our project already use v2.35 some months , 
     It's diffcult to upgrade to v2.36 or v2.37 ...
     Please help, 
     how to fix the issue in v2.35 ?  
    ( I have tested in v2.36/v2.37, it's OK)
  
     Anybody know how to fix this issue in v2.35 source code, thanks very much!!!

**Comment by pgstef** [comment]
Hi,

Bug fixes aren't back-ported to previous releases because a lot of code could have changed and because from a pgBackRest point-of-view, version update is pretty simple (replace the existing exec file).

What's blocking you to update pgBackRest ?

Regards

**Comment by Wim1234** [comment]
Thank u,  pgstef,

**Comment by pgstef** [comment]
> Can I get some point or key source file, I can merge it in local environment

Feel free to scroll down the commit history... That fix should be between August 23, 2021 (2.35) and November 1, 2021 (2.36).
 
> Our project want to continue use v2.35 I want to fix issue in our local environment....

I definitely won't recommend doing that. Imho there's no point blocking a pgbr update.

**Comment by pgstef** [comment]
To be honest, I quickly scanned the commit history and didn't spot what might have fix this. Perhaps @dwsteele will know.
Given you "planned" to rebuild from source and deploy that fix, I really think it would be better/easier to just update to newer release. The new releases have new features but also performance improvements and important bug fixes.

Just by curiosity, what are the reasons for you to not update to newer release ?
