### ISSUE TITLE
pgbackrest for postgres running inside a container

### ISSUE THREAD

**Issue by TamarNR** [pgbackrest/pgbackrest#1661]
Hi,

I am using the official docker hub image for Psotgresql version 13 running in a container .

Is there a way to use pgbackrest to backup such a a postgres?
will pgbackrest run inside the postgres container, or outside of it?

Are there any kind of instuctions for such a deployment?

Thanks,
Tamar

**Comment by dwsteele** [comment]
> Are there any kind of instuctions for such a deployment?

We don't have any, no. This is a very complex topic and depends a lot on what you need to do.

There are containerized solutions that use pgBackRest. For example, https://github.com/CrunchyData/crunchy-containers. You might want to use something like that or at least use it for guidance.

**Comment by TamarNR** [comment]
Thanks
