### ISSUE TITLE
Recommendation for editing archive_command after switchover OR failover

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#1668]
1. pgBackRest version:
2.37

2. PostgreSQL version:
12,13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS + Ubuntu Bionic

4. Did you install pgBackRest from source or from a package?
package

7. Describe the issue:
After a failover OR a switchover using repmgr, we have to modify the postgresql.conf manually on the new primary to change the archive_command. We backup on our primaries so it's always '/bin/true' on the standbys.
We would be interested in knowing your recommendations.

**Comment by pgstef** [comment]
Hi,

Are you already using pgBackRest on the standbys ? It can be useful in the `restore_command` in case the streaming replication is lagging too far behind, the standbys would be able to use the archives to catch-up the primary.

Regarding the `archive_command`, as long as `archive_mode` is set to **on**, PG won't start the archiver process on standbys. Imo, it's best to set the same archive_command everywhere. So when the standby is promoted, it starts to archive (and you won't miss the switch point / history file in the archives).

The main attention point is split-brain. Make sure your primary is really down before promoting a standby.

Kind Regards
