### ISSUE TITLE
Restoring diff backup does not restore modified configuration files (nor the other files, for example server.crt, server.key)

### ISSUE THREAD

**Issue by raulk89** [pgbackrest/pgbackrest#1678]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **2.37-1**

2. PostgreSQL version: **13.6**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 

**Repository server: CentOS Linux release 7.9.2009 (Core)
Database server: Rocky Linux release 8.5** 

4. Did you install pgBackRest from source or from a package? **package**

7. Describe the issue:

We do weekly full backups and every day we do diff backups.
For the current week, we have the following backups:

```
# su - postgres -c 'pgbackrest --stanza=watsondb info'
.............
.............
full backup: 20220227-173007F
	timestamp start/stop: 2022-02-27 17:30:07 / 2022-02-27 17:44:47
	wal start/stop: 0000000100000005000000AB / 0000000100000005000000AB
	database size: 56.4MB, database backup size: 56.4MB
	repo1: backup set size: 6.6MB, backup size: 6.6MB

diff backup: 20220227-173007F_20220228-173002D
	timestamp start/stop: 2022-02-28 17:30:02 / 2022-02-28 17:30:13
	wal start/stop: 0000000100000005000000AD / 0000000100000005000000AD
	database size: 56.5MB, database backup size: 23.6MB
	repo1: backup set size: 6.6MB, backup size: 1.5MB
	backup reference list: 20220227-173007F

diff backup: 20220227-173007F_20220301-173002D
	timestamp start/stop: 2022-03-01 17:30:02 / 2022-03-01 17:30:16
	wal start/stop: 0000000100000005000000AF / 0000000100000005000000AF
	database size: 56.5MB, database backup size: 23.6MB
	repo1: backup set size: 6.6MB, backup size: 1.5MB
	backup reference list: 20220227-173007F

diff backup: 20220227-173007F_20220302-173002D
	timestamp start/stop: 2022-03-02 17:30:02 / 2022-03-02 17:30:21
	wal start/stop: 0000000100000005000000B1 / 0000000100000005000000B1
	database size: 56.5MB, database backup size: 23.7MB
	repo1: backup set size: 6.6MB, backup size: 1.5MB
	backup reference list: 20220227-173007F
```

I changed postgresql.conf and pga_hba.conf file on 2022-03-02 at 2pm. Also I added server.crt ja server.key files to postgesql data directory at that time approximately.

Same day at 5:30 pm our diff backup fires, crontab command is as follows:
`sudo -u backrest pgbackrest --type=diff --stanza=watsondb --log-level-console=warn backup`

Day later (2022-03-03), when I tried to restore this backup that was created a day before
diff backup: 20220227-173007F_20220302-173002D

Restore command:
`su - postgres -c 'pgbackrest --stanza=watsondb --delta --type=time "--target=2022-03-02 17:30:21" --log-level-console=info restore'`

Output
```
2022-03-03 13:17:36.310 P00   INFO: restore command begin 2.37: --delta --exec-id=4559-5f6c402c --log-level-console=info --log-level-file=detail --pg1-path=/var/lib/pgsql/13/data --repo1-path=/mnt/backup --repo1-type=cifs --stanza=watsondb --target="2022-03-02 17:30:21" --type=time
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/var/lib/pgsql/13/data' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
2022-03-03 13:17:36.385 P00   INFO: repo1: restore backup set 20220227-173007F_20220301-173002D, recovery will start at 2022-03-01 17:30:02
2022-03-03 13:18:06.944 P00   INFO: write updated /var/lib/pgsql/13/data/postgresql.auto.conf
2022-03-03 13:18:06.949 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
2022-03-03 13:18:06.950 P00   INFO: restore size = 56.5MB, file total = 1280
2022-03-03 13:18:06.951 P00   INFO: restore command end: completed successfully (30642ms)
```

And I do not see modified postgresql.conf, pg_hba.conf nor the server.crt and server.key files there at all.

```
# ls -lh /var/lib/pgsql/13/data/
total 128K
-rw------- 1 postgres postgres  259 Mar  1 17:30 backup_label
drwx------ 6 postgres postgres 4.0K Mar  3 13:17 base
-rw------- 1 postgres postgres   30 Mar  1 00:00 current_logfiles
drwx------ 2 postgres postgres 4.0K Mar  3 13:18 global
drwx------ 2 postgres postgres 4.0K Mar  3 13:18 log
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_commit_ts
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_dynshmem
-rw------- 1 postgres postgres 5.7K Mar  5  2021 pg_hba.conf
-rw------- 1 postgres postgres 1.6K Mar  5  2021 pg_ident.conf
drwx------ 4 postgres postgres 4.0K Mar  3 13:18 pg_logical
drwx------ 4 postgres postgres 4.0K Mar  3 13:17 pg_multixact
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_notify
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_replslot
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_serial
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_snapshots
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_stat
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_stat_tmp
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_subtrans
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_tblspc
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_twophase
-rw------- 1 postgres postgres    3 Mar  5  2021 PG_VERSION
drwx------ 3 postgres postgres 4.0K Mar  3 13:17 pg_wal
drwx------ 2 postgres postgres 4.0K Mar  3 13:17 pg_xact
-rw------- 1 postgres postgres  278 Mar  3 13:18 postgresql.auto.conf
-rw------- 1 postgres postgres  28K Mar  5  2021 postgresql.conf
-rw------- 1 postgres postgres    0 Mar  3 13:18 recovery.signal

```

I can confirm, that diff backup **20220227-173007F_20220302-173002D** has these files backed up:

```
# ls -lh /var/lib/pgbackrest/mountpoint2/backup/watsondb/20220227-173007F_20220302-173002D/pg_data/
total 56K
-rwxr----- 1 backrest backrest  225 Mar  2 17:30 backup_label.lz4
drwxr-x--- 2 backrest backrest 1.0K Mar  2 17:30 base
-rwxr----- 1 backrest backrest   49 Mar  2 17:30 current_logfiles.lz4
drwxr-x--- 2 backrest backrest 1.0K Mar  2 17:30 global
drwxr-x--- 2 backrest backrest 1.0K Mar  2 17:30 log
-rwxr----- 1 backrest backrest 3.0K Mar  2 17:30 pg_hba.conf.lz4
drwxr-x--- 2 backrest backrest 1.0K Mar  2 17:30 pg_logical
drwxr-x--- 2 backrest backrest 1.0K Mar  2 17:30 pg_wal
drwxr-x--- 2 backrest backrest 1.0K Mar  2 17:30 pg_xact
-rwxr----- 1 backrest backrest  11K Mar  2 17:30 postgresql.conf.lz4
-rwxr----- 1 backrest backrest 1.8K Mar  2 17:30 server.crt.lz4
-rwxr----- 1 backrest backrest  326 Mar  2 17:30 server.key.lz4

```

**Comment by pgstef** [comment]
Hi,

Your restore was probably wrong given the logs:
```
...restore backup set 20220227-173007F_20220301-173002D, recovery will start at 2022-03-01 17:30:02
```
Using only `restore --type=immediate` would have restored your last backup set and stopped the PG recovery at the backup consistency point (2022-03-02 17:30:21). Adding `--set=20220227-173007F_20220302-173002D` would also make sure this particular backup set is used.

Here, the previous backup set was selected, I think, because you're on the edge of the stop time. I didn't looked at it very deeply but I guess the explanation is [here](https://github.com/pgbackrest/pgbackrest/blob/59a5373cf85e4ad0057b592bfe855495384dfcbd/src/command/restore/restore.c#L303) : 20220302-173002D stop time wasn't strictly **<** than the target time requested.

Kind Regards

**Comment by raulk89** [comment]
No, my restore was correct.

I can confirm this, by checking the database tables, where application inserts logs.

Here you can see there are rows present with yesterdays date's.

proxwdb=# select id, kuupaev from watson.logi_web order by 1 desc limit 2;
  id   |          kuupaev
-------+----------------------------
 10181 | 2022-03-02 16:19:41.309503
 10180 | 2022-03-02 16:19:21.970195
(2 rows)

**Comment by pgstef** [comment]
> No, my restore was correct.

Imo, your restore command wasn't correct for the goal you wanted to achieve.

> I can confirm this, by checking the database tables, where application inserts logs.
> 
> Here you can see there are rows present with yesterdays date's.
> 
> ```
> proxwdb=# select id, kuupaev from watson.logi_web order by 1 desc limit 2;
>   id   |          kuupaev
> -------+----------------------------
>  10181 | 2022-03-02 16:19:41.309503
>  10180 | 2022-03-02 16:19:21.970195
> (2 rows)
> ```
> 
> Diff backup started 2022-03-02 17:30
> 
> When restore would have used **20220227-173007F_20220301-173002D**, then this query should not give me any rows where date is higher than 2022-03-01 17:31...

That's the beauty of PG point-in-time recovery. If you look at your PG logs, you'll see that the recovery started at 2022-03-01 17:30:02, then PG replayed all the wal archives until your target time requested.

> 
> I used 17:30:20, instead of 17:30:21 But no change.
> 
> ```
> # su - postgres -c 'pgbackrest --stanza=watsondb --type=time "--target=2022-03-02 17:30:20" --log-level-console=info restore'
> 2022-03-03 14:02:27.842 P00   INFO: restore command begin 2.37: --exec-id=4864-5e709b12 --log-level-console=info --log-level-file=detail --pg1-path=/var/lib/pgsql/13/data --repo1-path=/mnt/backup --repo1-type=cifs --stanza=watsondb --target="2022-03-02 17:30:20" --type=time
> 2022-03-03 14:02:27.910 P00   INFO: repo1: restore backup set 20220227-173007F_20220301-173002D, recovery will start at 2022-03-01 17:30:02
> 2022-03-03 14:02:53.922 P00   INFO: write updated /var/lib/pgsql/13/data/postgresql.auto.conf
> 2022-03-03 14:02:53.929 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
> 2022-03-03 14:02:53.931 P00   INFO: restore size = 56.5MB, file total = 1280
> 2022-03-03 14:02:53.931 P00   INFO: restore command end: completed successfully (26090ms)
> ```

Same here, your requested target time is lower than the backup stop time. Probably with "2022-03-02 17:30:2**2**" it would work.

However, I still recommend you to use the command I explained with `--type=immediate`. That's a PG trick to stop the recovery at the backup consistency point (what you're apparently trying to do).

Imo, the following command should do what you're expecting: `pgbackrest --stanza=watsondb --type=immediate  --log-level-console=info restore`

Finally, you should read the [restore command doc](https://pgbackrest.org/command.html#command-restore) that explains why another backup set would be selected:
```
The restore command automatically defaults to selecting the latest backup from the first repository where backups exist (see [Quick Start - Restore a Backup](https://pgbackrest.org/user-guide.html#quickstart/perform-restore)). ...The --set option can be passed if a backup other than the latest is desired.

When PITR of --type=time is specified, then the target time must be specified with the --target option. If a backup is not specified via the --set option, then the configured repositories will be checked, in order, for a backup that contains the requested time. If no backup can be found, the latest backup from the first repository containing backups will be used. For other types of PITR, e.g. xid, the --set option must be provided if the target is prior to the latest backup. See [Point-in-Time Recovery](https://pgbackrest.org/user-guide.html#pitr) for more details and examples.
```

And as I pointed with the source code in a previous comment, the `--target` should be strictly greater than the "timestamp stop" of the backup set you want to restore.

Regards

**Comment by tirelibirefe** [comment]
> No, my restore was correct.
> 
> I can confirm this, by checking the database tables, where application inserts logs.
> 
> Here you can see there are rows present with yesterdays date's.
> 
> ```
> proxwdb=# select id, kuupaev from watson.logi_web order by 1 desc limit 2;
>   id   |          kuupaev
> -------+----------------------------
>  10181 | 2022-03-02 16:19:41.309503
>  10180 | 2022-03-02 16:19:21.970195
> (2 rows)
> ```
> 
> Diff backup started 2022-03-02 17:30
> 
> When restore would have used **20220227-173007F_20220301-173002D**, then this query should not give me any rows where date is higher than 2022-03-01 17:31...
> 
> I used 17:30:20, instead of 17:30:21 But no change.
> 
> ```
> # su - postgres -c 'pgbackrest --stanza=watsondb --type=time "--target=2022-03-02 17:30:20" --log-level-console=info restore'
> 2022-03-03 14:02:27.842 P00   INFO: restore command begin 2.37: --exec-id=4864-5e709b12 --log-level-console=info --log-level-file=detail --pg1-path=/var/lib/pgsql/13/data --repo1-path=/mnt/backup --repo1-type=cifs --stanza=watsondb --target="2022-03-02 17:30:20" --type=time
> 2022-03-03 14:02:27.910 P00   INFO: repo1: restore backup set 20220227-173007F_20220301-173002D, recovery will start at 2022-03-01 17:30:02
> 2022-03-03 14:02:53.922 P00   INFO: write updated /var/lib/pgsql/13/data/postgresql.auto.conf
> 2022-03-03 14:02:53.929 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
> 2022-03-03 14:02:53.931 P00   INFO: restore size = 56.5MB, file total = 1280
> 2022-03-03 14:02:53.931 P00   INFO: restore command end: completed successfully (26090ms)
> ```
> 
> Raul

Hello @raulk89 
were you able to figure out the problem?
I have a similar problem that pgbackrest ignores `--type=immediate` command and restores only the latest backup. If you have tested, could you please confirm `--type=immediate` is ignored or not by pgbackrest?

Thanks & Regards
