### ISSUE TITLE
pgbackrest recovery problem in Patroni-PostgreSQL environment

### ISSUE THREAD

**Issue by msuluhan** [pgbackrest/pgbackrest#1681]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.24

2. PostgreSQL version: Version: 12.9-0ubuntu0.20.04.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  Ubuntu 20.04 LTS

4. Did you install pgBackRest from source or from a package?  Official Ubuntu Repository

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
 [global]
repo1-path=/mnt/paylasim/pgBackRestRepo
repo1-retention-diff=18
repo1-retention-full=3
log-level-console=info
log-level-file=debug
start-fast=y
process-max=5
compress-level=9

[beefulldev]
pg1-path=/var/lib/postgresql/12/beefulldev
pg1-port=5433
pg1-socket-path=/var/lib/postgresql/12/beefulldev
```

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: pgbackrest is working in Patroni-PostgreSQL environment. It works very well while taking backup both in test and production environments. I could see it 's taking all the databases in instance.
```

$ pgbackrest --stanza=beefulldev info --set=20220306-153327F_20220306-164835D
stanza: beefulldev
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1): 00000007000000000000005A/000000090000000000000067

        diff backup: 20220306-153327F_20220306-164835D
            timestamp start/stop: 2022-03-06 16:48:35 / 2022-03-06 16:48:45
            wal start/stop: 000000090000000000000066 / 000000090000000000000066
            database size: 415.1MB, backup size: 16.3MB
            repository size: 65.8MB, repository backup size: 2.5MB
            backup reference list: 20220306-153327F
            database list: <there are many databases in the liste> pagila (28767), postgres (13437)
```

So I tried to test a recovery process in test environment. I dropped one of the databases and then stopped all patroni services in 3 servers. 
Then I used following commands to recover instance (one command in each trial)

pgbackrest --stanza=beefulldev --delta --type=immediate --target-action=promote restore
pgbackrest --stanza=beefulldev  --db-include=pagila --delta --type=immediate --target-action=promote restore

So when I try to start Patroni PostgreSQL is waiting for WAL file. When I check this WAL file it's located on repo1-path as compressed file.
```

$ ps -ef | grep postgre
postgres  303188       1  0 Mar07 ?        00:03:11 /usr/bin/python3 /usr/bin/patroni /etc/patroni/config.yml
postgres  303237       1  0 Mar07 ?        00:00:33 postgres -D /var/lib/postgresql/12/beefulldev --config-file=/var/lib/postgresql/12/beefulldev/postgresql.conf --listen_addresses=0.0.0.0 --port=5433 --cluster_name=postgres --wal_level=replica --hot_standby=on --max_connections=300 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=64 --track_commit_timestamp=off --max_replication_slots=10 --max_worker_processes=8 --wal_log_hints=on
postgres  303241  303237  0 Mar07 ?        00:00:02 postgres: postgres: logger   
postgres  303242  303237  0 Mar07 ?        00:00:02 postgres: postgres: startup   waiting for 000000090000000000000066
root      402101  402065  0 14:02 pts/0    00:00:00 su - postgres
postgres  402103  402101  0 14:02 pts/0    00:00:00 -bash
postgres  402324  402103  0 14:05 pts/0    00:00:00 ps -ef
postgres  402325  402103  0 14:05 pts/0    00:00:00 grep postgre

$ find /mnt/paylasim/ -name "000000090000000000000066*" -exec ls -l {} \;
-rwxrwxrwx 1 root root 16487 Mar  6 16:48 /mnt/paylasim/pgBackRestRepo/archive/beefulldev/12-1/0000000900000000/000000090000000000000066-ee41f38d8b26d9b0e969bd1a1b982ca3c4fd82f8.gz
-rwxrwxrwx 1 root root 373 Mar  6 16:48 /mnt/paylasim/pgBackRestRepo/archive/beefulldev/12-1/0000000900000000/000000090000000000000066.00000028.backup
```

Same scenario works on single node PostgreSQL without any problem. Both recover commands work in 2 different scenarios

So how could I recover database with pgbackrest in Patroniz-PostgreSQL environment?

Thanks

**Comment by pgstef** [comment]
Hi,

> pgbackrest --stanza=beefulldev --delta --type=immediate --target-action=promote restore

This command will  indeed restore the cluster and ask PG to stop recovery at the backup consistency point (around the backup end time -> `2022-03-06 16:48:45`).

> pgbackrest --stanza=beefulldev --db-include=pagila --delta --type=immediate --target-action=promote restore

This one will do the same but all other databases will be restored as zeroed files (so, not reachable after the recovery and should be dropped).

> So when I try to start Patroni PostgreSQL is waiting for WAL file. When I check this WAL file it's located on repo1-path as compressed file.
> So how could I recover database with pgbackrest in Patroniz-PostgreSQL environment?

What does your PG logs says about that ? Remind yourself that pgBackRest will restore your files and prepare the config files and then PG will handle the recovery. PG needs to call the `restore_command` to bring back WAL archives from the repo. If it's working when you start the service manually but not when Patroni does it, perhaps there's something to change in Patroni config about recovery options? That would probably be a good question for Patroni people?

Usually, restoring data in an HA cluster could be done the same way you would in a normal streaming replication scenario. Recover a temp cluster, extract the data/db you need with pg_dump and inject in your prod cluster with pg_restore.
If you don't need the other erased data, then your restored cluster can become your new primary and you'll need to re-sync your standbys.

Regards

**Comment by msuluhan** [comment]
Hello @pgstef 

Thanks for the restore_command tip :)
I added  following line into patroni configuration (with edit-config option) 

`restore_command: pgbackrest --stanza=main archive-get %f '/var/lib/postgresql/12/beefulldev/pg_wal'`

BTW %p option did not work because of the relation path error. Therefore I used full path

When I tried to start again postgresql within patroni, followiing errors logged in postgresql log file.
```
2022-03-10 13:21:06.307 +03 - 1 - 591468 - 127.0.0.1 - postgres@postgres - 0FATAL:  the database system is starting up
2022-03-10 13:21:06.308 +03 - 1 - 591471 - 127.0.0.1 - postgres@postgres - 0FATAL:  the database system is starting up
2022-03-10 13:21:06.311 P00   INFO: archive-get command begin 2.24: [0000000C.history, /var/lib/postgresql/12/beefulldev/pg_wal] --compress-level=9 --log-level-console=info --log-level-file=debug --process-max=5 --repo1-path=/mnt/paylasim/pgBackRestRepo --stanza=main
2022-03-10 13:21:06.328 +03 - 1 - 591474 - 127.0.0.1 - postgres@postgres - 0FATAL:  the database system is starting up
2022-03-10 13:21:06.329 +03 - 1 - 591475 - 127.0.0.1 - postgres@postgres - 0FATAL:  the database system is starting up
Segmentation fault (core dumped)
2022-03-10 13:21:06.640 +03 - 2 - 591467 -  - @ - 0FATAL:  could not restore file "0000000C.history" from archive: child process exited with exit code 139
2022-03-10 13:21:06.642 +03 - 6 - 591464 -  - @ - 0LOG:  startup process (PID 591467) exited with exit code 1
2022-03-10 13:21:06.642 +03 - 7 - 591464 -  - @ - 0LOG:  aborting startup due to startup process failure
2022-03-10 13:21:06.646 +03 - 8 - 591464 -  - @ - 0LOG:  database system is shut down
2022-03-10 13:21:07.807 +03 - 6 - 591486 -  - @ - 0LOG:  received fast shutdown request
2022-03-10 13:21:07.808 +03 - 1 - 591489 -  - @ - 0LOG:  database system was shut down in recovery at 2022-03-10 13:10:16 +03
2022-03-10 13:21:07.812 +03 - 1 - 591490 -  - @ - 0LOG:  shutting down
2022-03-10 13:21:07.820 +03 - 7 - 591486 -  - @ - 0LOG:  database system is shut down

```

But the file exists in pgBackRest repo 

```
root@endoks:/mnt/paylasim/pgBackRestRepo/archive/beefulldev/12-1# ls -la
total 28
drwxrwxrwx 2 root root   0 Mar 10 12:53 .
drwxrwxrwx 2 root root   0 Mar  6 15:32 ..
drwxrwxrwx 2 root root   0 Mar  6 16:27 0000000700000000
-rwxrwxrwx 1 root root 257 Mar  6 15:32 00000007.history
drwxrwxrwx 2 root root   0 Mar  6 16:48 0000000800000000
-rwxrwxrwx 1 root root 300 Mar  6 16:27 00000008.history
drwxrwxrwx 2 root root   0 Mar  6 17:05 0000000900000000
-rwxrwxrwx 1 root root 343 Mar  6 16:48 00000009.history
drwxrwxrwx 2 root root   0 Mar  9 13:29 0000000A00000000
-rwxrwxrwx 1 root root  42 Mar  9 13:29 0000000A.history
drwxrwxrwx 2 root root   0 Mar 10 11:40 0000000B00000000
-rwxrwxrwx 1 root root  86 Mar  9 13:29 0000000B.history
drwxrwxrwx 2 root root   0 Mar 10 12:53 0000000C00000000
-rwxrwxrwx 1 root root  43 Mar 10 11:47 0000000C.history
drwxrwxrwx 2 root root   0 Mar 10 12:53 0000000D00000000
-rwxrwxrwx 1 root root  87 Mar 10 12:53 0000000D.history
root@endoks:/mnt/paylasim/pgBackRestRepo/archive/beefulldev/12-1# 
```

PS : /mnt/paylasim is CIFS share mount and postgres user has rw permission on every directory

How do I overcome this problem? 

Thanks 
Murat

**Comment by pgstef** [comment]
Well, `Segmentation fault (core dumped)` is pretty scary...

> BTW %p option did not work because of the relation path error. Therefore I used full path

If you pgbr config was right, it shouldn't be a problem.

> How do I overcome this problem?

:man_shrugging:, if it works manually but not with Patroni, you should look at Patroni. (Hard to help without the entire config/commands picture and tbh, I'm not a Patroni expert)

Anyway, given you use **2.24** release (which is 2 years old already), start by updating pgBR release and then ask help from patroni people.

**Comment by msuluhan** [comment]
Hello @pgstef 

pgBR configuration as follows. The config in single node is very similar and working properly

```
[global]
repo1-path=/mnt/paylasim/pgBackRestRepo
repo1-retention-diff=18
repo1-retention-full=3
log-level-console=info
log-level-file=debug
start-fast=y
process-max=5
compress-level=9

[beefulldev]
pg1-path=/var/lib/postgresql/12/beefulldev
pg1-port=5433
pg1-socket-path=/var/lib/postgresql/12/beefulldev
```

If I don't add restore_command option in patroni config; I recover WAL file manually  (copy the WAL file in pg_wal dir) and then start patroni it works successfully and recovered dropped database


Thanks
Murat
