### ISSUE TITLE
stanza-delete should not be possible from a non-repo host

### ISSUE THREAD

**Issue by bluthg** [pgbackrest/pgbackrest#1682]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 13 (all, I guess)

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.04

4. Did you install pgBackRest from source or from a package? PGDG Repo

5. Please attach the following as applicable:
N/A

7. Describe the issue:
Kind of a follow-up to #1627

Currently sketching a new, pgbackrest-based environment for a client.

The general idea is to separate as much as possible, so that we will end up with
* 4 or 6 DB servers in 3 DCs (managed by Patroni) knowing only one "`repo1-host`" and "`repo1-cipher-pass`"
* 2 or 3 pgBackRest-Servers _not_ knowing the aforementioned `cipher-pass`, but all backed by the same S3 (which only _they_ know the credentials of)

, so if an intruder manages to break into one of the systems, (s)he may either

* steal a backup that is encrypted and destroy the S3 data (which is in turn backed up on tape or snapshots)
* destroy the DB and create a new backup (but the repo has a couple of older ones so we can PITR), but not tamper with existing backups (i.e., can't overwrite them with encrypted versions)

but not hop around with `ssh` or wreak havoc in other ways.

So I tried  (on a DB server as "postgres"):
```
$ pgbackrest --stanza=yyyyyyyy expire --set 20220302-140308F
WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space
      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
ERROR: [072]: expire command must be run on the repository host
```

Which is perfectly fine; we want the repo host to manage it.

But then I did this (again, as "postgres" on the DB server):

```
$ pgbackrest --stanza=yyyyyyyy stop
$ pgbackrest --stanza=yyyyyyyy stanza-delete
ERROR: [038]: postmaster.pid exists - looks like PostgreSQL is running. To delete stanza 'yyyyyyyy' on repo1, shut down PostgreSQL for stanza 'yyyyyyy' and try again, or use --force.

root # service patroni@13-main stop

$ pgbackrest --stanza=yyyyyyy stanza-delete
ERROR: [060]: raised from remote-0 ssh protocol on 'X.X.X.X': unable to remove file 'repo/archive/yyyyyyyyy/13-1/0000001700000054/000000170000005400000009-c117ec0429c0e77ae241897fcbbe1f257f3ebcf8.lz4': [UnknownError] UnknownError
```

But (the majority of) the stanza is gone... 😧

Fair enough, there'd still be the fallback to restore it on S3, but shouldn't `stanza-delete` be forbidden for "remote" execution when a repo-host is in use?

I mean, if there's `ERROR: [072]: expire command must be run on the repository host`, there's obviously some "self-consciousness" on the repo-host side (?), so a similar "sorry, go away"-message for `stanza-delete` would totally suffice.

**Comment by dwsteele** [comment]
> I mean, if there's ERROR: [072]: expire command must be run on the repository host, there's obviously some "self-consciousness" on the repo-host side

Not really, this is simply because making things run remotely is harder than running them locally. In general we'd like all commands to be able to be run remotely.

There was a time when the stanza commands did not run remotely, but that caused a number of automation problems so we added the feature around the time we added multi-repo.

If there are good arguments for limiting certain commands, then perhaps there needs to be some sort of permission system, but that is not on our roadmap.

**Comment by bluthg** [comment]
Hi David & thx for looking into this!
I personally see no reason at all for the DB server(s) to be able to create or delete a - shared + remote - stanza. That's a good argument IMHO...
FWIW, I made us a little wrapper "rbgbackrest", which is put into `authorized_keys` as `command=`:
```
#!/bin/bash
if [[ "$*" =~ 'stanza-' ]]; then 
  echo "Forbidden stanza command given" >&2
  exit 1
fi
/usr/bin/pgbackrest $*
```
That does the job, so it may be useful to add it?

**Comment by dwsteele** [comment]
If we add it, it would be a setting in pgbackrest, not a shell script. But if that works for you, then got for it.

**Comment by bluthg** [comment]
"[...] add it somewhere in the documentation" was what I meant ;-)
Anyway, I'm fine to leave it as is.

**Comment by dwsteele** [comment]
> add it somewhere in the documentation" was what I meant

Ah, I see. But even so we prefer not to add things to the documentation that we are not testing.

We already have an example of filtering the command via SSH. What you are doing is an extension of that.
