### ISSUE TITLE
Remote repo path interpreted as local

### ISSUE THREAD

**Issue by martindomeij** [pgbackrest/pgbackrest#1684]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.33

2. PostgreSQL version: 11.9

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package? Package

Setup with
1 pg host
2 repo hosts

pgbackrest.conf on pg host:
[global]
repo1-host=repo1
repo1-path=/backup/local

repo2-host=repo2
repo2-path=/backup/local

[db]
pg1-path=/var/lib/postgresql/11/db
pg1-port=5434

Because a repo host cannot have both pg-hosts and repo-hosts configured, I can't seem to be able to have configuration for both repo servers on the repo servers, so the pgbackrest.conf on the first repo hosts looks like this:

[global]
repo1-path=/backup/local

[db]
pg1-host=pg1
pg1-path=/var/lib/postgresql/11/db
pg1-port=5434

When trying to create a stanza (either from the pg host or the repo1 host), I am presented with the following error:
$ pgbackrest --stanza=db  stanza-create
WARN: unable to check pg-1: [OptionInvalidValueError] remote-0 process on 'pg1' terminated unexpectedly [32]: ERROR: [032]: local repo1 and repo2 paths are both '/backup/local' but must be different

Not sure what is happening, but for some reason the repo-paths seem to be interpreted as local (by the first repo server?), even though repo1-host and repo2-host options are configured.

Thoughts?

**Comment by pgstef** [comment]
Hi,

I haven't tried it actually but I think this should work:

```ini
# PG node
[global]
repo1-host=repo1
repo2-host=repo2
```
```ini
# Repo1 host
[global]
repo1-path=/backup/local
```
```ini
# Repo2 host
[global]
repo2-path=/backup/local
```

Afaik, `repo*-host` and `repo*-path` shouldn't be used at the same time on db hosts. 
And repo2 calls from the db host will need to find `repo2-*` options defined in the 2nd repo host configs.

Could you try ?
Thanks,

**Comment by martindomeij** [comment]
Yeah, that works... Probably should have figured that out myself. Thank you!

**Comment by martindomeij** [comment]
User error.
