### ISSUE TITLE
Hardware Resource Required for pgBackRest 2.37

### ISSUE THREAD

**Issue by moindba** [pgbackrest/pgbackrest#1689]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.37
2. PostgreSQL version:
11.2
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 7.9
4. Did you install pgBackRest from source or from a package?
RPM
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
1. I want to know How much extra RAM and CPU Required on shared NFS host OR Dedicated Backup Host to Run pgBackrest for 2TB of Database ?
2. How to Optimize pgBackRest to get faster Backups ?

**Comment by dwsteele** [comment]
> I want to know How much extra RAM and CPU Required on shared NFS host OR Dedicated Backup Host to Run pgBackrest for 2TB of Database?

There is no easy answer to this question since it depends on a number of factors: CPU type, compression type/level, data patterns, network speed, etc. You'll need to experiment with your setup to find the best settings.
