### ISSUE TITLE
pgBackRest Meta Data lost

### ISSUE THREAD

**Issue by moindba** [pgbackrest/pgbackrest#1690]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.37
2. PostgreSQL version:
PostgreSQL 11.2
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?
RPM Package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
1. If we lost backup.info / backup.info.copy / archive.info / archive.info.copy then can we restore backups from pgbackrest repository ?
2. We want to create a backup of pgbackrest complete repository on our storage, will it be helpful for us incase actual pgBackRest repository deleted or damaged ?

**Comment by dwsteele** [comment]
> If we lost backup.info / backup.info.copy / archive.info / archive.info.copy then can we restore backups from pgbackrest repository ?

If the repository is encrypted, then there is no way to recover from the loss of these files. Otherwise, it can be done but it is time consuming and error prone and not something we would do or advise on.

> We want to create a backup of pgbackrest complete repository on our storage, will it be helpful for us incase actual pgBackRest repository deleted or damaged?

Yes, you can make backups of the pgbackrest repo and you should.
