### ISSUE TITLE
ERROR: [068]: archive_command must contain pgbackrest

### ISSUE THREAD

**Issue by sethdaniel** [pgbackrest/pgbackrest#1692]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:   2.36

2. PostgreSQL version:   9.3.24 

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  Ubuntu 14 (no one is more painfully aware of how outdated this machine's OS is than me)

4. Did you install pgBackRest from source or from a package?  copied binary from another machine

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

    ```
    [main]
    pg1-path=/var/lib/postgresql/9.3/main

    [global]
    repo1-type=azure
    log-level-console=debug
    log-level-file=debug
    log-level-stderr=debug
    repo1-path=/repo1
    repo1-retention-diff=2
    repo1-retention-full=2
    repo1-azure-account=clutchmypearls
    repo1-azure-container=XXX
    repo1-azure-key=XXX
    repo1-azure-key-type=sas
    archive-timeout=600
    archive-push-queue-max=1GB
    spool-path=/var/spool/pgbackrest
    start-fast=y
    process-max=2
    ```
    
    
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    
        `listen_addresses = '*'`
        `port = 5432 `
        `wal_level = hot_standby`
        `archive_mode = on`
        `archive_command = 'pgbackrest --stanza=main --pg1-path=/var/lib/postgresql/9.3/main archive-push %p'`
        `max_wal_senders = 3`
        
        
        
    - errors in the postgresql log file before or during the time you experienced the issue
    
        ```
        2022-03-10 20:03:42 UTC LOG:  archive command failed with exit code 1
        2022-03-10 20:03:42 UTC DETAIL:  The failed archive command was: /usr/local/bin/omnipitr/bin/omnipitr-archive -l 
        /home/postgres/omnipitr/log/omnipitr-^Y-^m-^d.log -s /home/postgres/omnipitr/state -dr 
        gzip=XXXaws1.XXX.software:/home/XXX-backup/XXX_Customer_810/wal_archive -db /var/tmp/omnipitr/dstbackup -t 
        /var/tmp/omnipitr/ -v "pg_xlog/000000010000153700000065" --gzip-path=/usr/bin/pigz
        ```
        
                
        
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    
        ```
        ERROR: [068]: archive_command '/usr/local/bin/omnipitr/bin/omnipitr-archive -l /home/postgres/omnipitr/log/omnipitr-^Y- 
        ^m-^d.log -s /home/postgres/omnipitr/state -dr gzip=XXX-backup@backup-aws1.XXX.software:/home/XXX- 
        backup/XXX_Customer_810/wal_archive -db /var/tmp/omnipitr/dstbackup -t /var/tmp/omnipitr/ -v "%p" --gzip- 
        path=/usr/bin/pigz' must contain pgbackrest
        ```
    
    

7. Describe the issue:

We are transitioning our servers postgres backup manager from omnipitr to pgbackrest.  As you can see the archive command is set to what it should be but pgbackrest still is grabbing the old one from the `pg_catalog.pg_settings`.  I've been running this same process on a bunch of machines and every once in a while I hit this issue and don't know what is the proper way to rectify.  Help?

**Comment by jreidthompson** [comment]
are you invoking select pg_reload_conf();  after you change the archive_command to 'pgbackres....'?

**Comment by sethdaniel** [comment]
Oh wow.  @jreidthompson you nailed it, it seems.  I do have ansible pulling a `pg_ctlcluster 9.3 main reload` right before this error pops up (it's the last command in the previous playbook which is probably why it didn't occur to me to try this earlier).  Logs are saying everything is hunky dory but when I manually go in and run that command and then the pgbackrest check stanza command afterwards... sure enough it then works.  Thank you so so much.

**Comment by jreidthompson** [comment]
Sure -- glad that it was quick / easy resolution.
