### ISSUE TITLE
pgBackRest support for PostgreSQL 12 / 13 and 14

### ISSUE THREAD

**Issue by moindba** [pgbackrest/pgbackrest#1698]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.37
2. PostgreSQL version:
12.4
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 7
4. Did you install pgBackRest from source or from a package?
RPM Package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
What are the PostgreSQL Versions did pgBackRest will support on RHEL ? does it support PostgreSQL 12 / 13 and 14 Version ?

**Comment by pgstef** [comment]
Hi,

> 6\. What are the PostgreSQL Versions did pgBackRest will support on RHEL ? does it support PostgreSQL 12 / 13 and 14 Version ?

Basically, pgBackRest includes support for versions down to 9.0, but we encourage using PG community supported release (10+ currently).

The user-guide doesn't include those but afaik it's working with 12, 13 and 14.

Kind Regards

**Comment by dwsteele** [comment]
The user guide is specific to certain versions because changes in postgres change the user guide. But overall 9.0-14 are supported on all platforms.

Generating the user guides is pretty expensive in terms of time so we try to cover ans many versions as possible with as few user guides as possible.

**Comment by narendrapostgresdba** [comment]
is pgbackrest supported  on windows environment ?

**Comment by dwsteele** [comment]
@narendrapostgresdba Please don't post to old issues. It is always better to open a new issue.

pgBackRest is currently not supported on Windows. We have plans for a Windows port but I am not able to put a date on that.

**Comment by narendrapostgresdba** [comment]
Thanks for the update
