### ISSUE TITLE
TLS access error

### ISSUE THREAD

**Issue by martindomeij** [pgbackrest/pgbackrest#1702]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 22

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package? Package

7. Describe the issue:
I am trying to recover from this error when trying to archive wal:
repo1: [AccessError] raised from remote-0 tls protocol on 'repo1.ourdomain.net': access denied
repo2: [AccessError] raised from remote-0 tls protocol on 'repo2.ourdomain.net': access denied

I had this working yesterday. Then I changed out the certificates. I am now using public certs with wildcards, like '*.ourdomain.net'.

Would the wildcard be a problem?

I'm not sure if "AccessError" means that it can't authenticate using tls, or if the problem is that the repo server pgbackrest won't give the db server access. If it's the latter, I am undable to understand how to. I have tried all varieties of tls-server-auth=pg1=stanza, including using the fqdn of the pg host, as well as tls-server-auth=\*=\*, to no avail. And like I said, I had it working yesterday, so I'm not really thinking this is the problem. Or is it?

Any thoughts?

**Comment by dwsteele** [comment]
There is no reason to use wildcards. You can reuse the same cert on multiple clients if you like (not recommended), but wildcards will just make it harder (or impossible) to properly configure the CN on the server side with `tls-server-auth`.

**Comment by martindomeij** [comment]
Thank you for your reply.

Yes, that wat my question, if it is possible to configure tls-server-auth with a wildcard cert. The reason for it was just that I had such a cert already in use. But if it is impossible, I will figure out another way.

**Comment by dwsteele** [comment]
I'm not sure that it won't work. We have never tested it because it doesn't make much sense in this context.

You tried `tls-server-auth=*.ourdomain.net=*` and that did not work?

**Comment by martindomeij** [comment]
Ok, I feel embarrassed... Yes it works now. I was certain I had tried that. Sorry for taking up your time...

By the way, the documentation on this matter seems a bit off. From https://pgbackrest.org/command.html:

12.1.2 TLS Server Authorized Clients Option (--tls-server-auth)
TLS server authorized clients.
Clients are authorized on the server by verifying their certificate and checking the certificate CN (Common name) against a list on the server configured with the tls-server-auth.

A CN can be authorized for as many stanzas as needed by repeating the tls-server-auth option, or for all stanzas by specifying tls-server-auth=*.
example: --tls-server-auth=stanza1

If I remember correctly, having just the name of the stanza threw an error. I found the proper syntax in pgstef's blog, (tls-server-auth=host=stanza). Should this be updated, or am I reading it wrong?

**Comment by pgstef** [comment]
Hi,

> Should this be updated, or am I reading it wrong?

It seems @dwsteele already fixed it in [c222ce1](https://github.com/pgbackrest/pgbackrest/commit/c222ce1a5f6f813188b7e87a3838d6dce656e0ff).

However, it now states `Wildcards may not be specified for the client CN`. If you made it work with `tls-server-auth=*.ourdomain.net=*`, perhaps that statement can be changed  too :thinking:

**Comment by martindomeij** [comment]
Indeed it does work with tls-server-auth=*.domain=*, for example, when my cert is for *.domain. Maybe that is a question for another issue, though. Will close this one now. Thank you again for all your help.
