### ISSUE TITLE
got DbConnectError issue when I tried using stanza-create

### ISSUE THREAD

**Issue by hejun2018** [pgbackrest/pgbackrest#1705]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.39 dev
2. PostgreSQL version:
actually is kingbase which based on postgresql9.6
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Linux centos 7.9
4. Did you install pgBackRest from source or from a package?
build from source code 2.39
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

    -[demo]
pg1-path=/opt/kingbase/data
pg1-host-config-path=/etc/pgbackrest
#pg1-host-port=22
#pg1-host-user=cxt
#pg1-host=192.168.200.106
pg1-port=54321
pg1-user=SYSTEM
pg1-password=SYSTEM
pg1-database=kingbase
[global]
repo1-path=/opt/kingbase/backup
[global:archive_push]
compress-level=3 
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_mode = on
#archive_command = ''
archive_dest = '/opt/kingbase/arch'
wal_level = replica
    - 
    - errors in the postgresql log file before or during the time you experienced the issue

    -nothing. 
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
sh-4.2$ pgbackrest --stanza=demo --log-level-console=info stanza-create
WARN: configuration file contains invalid option 'pg1-password'
WARN: unable to open log file '/var/log/pgbackrest/demo-stanza-create.log': No such file or directory
      NOTE: process will continue without log file.
2022-03-28 05:47:01.848 P00   INFO: stanza-create command begin 2.39dev: --exec-id=20464-5acfb4d4 --log-level-console=info --log-level-file=off --pg1-database=kingbase --pg1-path=/opt/kingbase/data --pg1-port=54321 --pg1-user=SYSTEM --repo1-path=/opt/kingbase/backup --stanza=demo
WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='kingbase' port=54321 user='SYSTEM'': could not connect to server: Connection refused
      	Is the server running locally and accepting
      	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.54321"?
ERROR: [056]: unable to find primary cluster - cannot proceed
2022-03-28 05:47:01.860 P00   INFO: stanza-create command end: aborted with exception [056]

7. Describe the issue:
actually I tried using pgbackrest to backup king base which based on postgresql9.7, and king base support pg_rman but actually they changed some system table name like pg_database has changed to sys_database, something like this, so pg_rman has been changed to sys_rman. 
I just thought pgbackrest may support king base, but I got this error, I tried using Navicat to connect king base was just fine.
and I observed king base generated a .s.KINGBASE.54321 under /tmp, so I gave the socket direct is "/tmp", and also I tried touch a .s.PGSQL.54321 under /tmp, but no luck.

could you please give some help on this, may just changed some system level table name so that pgbackrest can connect and continue.

thanks very much.

**Comment by pgstef** [comment]
Hi,

>     2. PostgreSQL version:
>        actually is kingbase which based on postgresql9.6

First of all, I don't have any knowledge of that fork. Never heard about it until today.

>          archive_mode = on
>          #archive_command = ''
>          archive_dest = '/opt/kingbase/arch'
>          wal_level = replica

`archive_dest` isn't a PG option, pgBackRest relies on PG `archive_command`.

>          sh-4.2$ pgbackrest --stanza=demo --log-level-console=info stanza-create
>          WARN: configuration file contains invalid option 'pg1-password'
>          WARN: unable to open log file '/var/log/pgbackrest/demo-stanza-create.log': No such file or directory
>          NOTE: process will continue without log file.
>          2022-03-28 05:47:01.848 P00   INFO: stanza-create command begin 2.39dev: --exec-id=20464-5acfb4d4 --log-level-console=info --log-level-file=off --pg1-database=kingbase --pg1-path=/opt/kingbase/data --pg1-port=54321 --pg1-user=SYSTEM --repo1-path=/opt/kingbase/backup --stanza=demo
>          WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='kingbase' port=54321 user='SYSTEM'': could not connect to server: Connection refused
>          Is the server running locally and accepting
>          connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.54321"?
>          ERROR: [056]: unable to find primary cluster - cannot proceed
>          2022-03-28 05:47:01.860 P00   INFO: stanza-create command end: aborted with exception [056]

The first WARN is very important. `pg1-password` isn't a valid option (as you can see in https://pgbackrest.org/configuration.html#section-stanza). If you need to provide a username/password, you should better use a [.pgpass](https://www.postgresql.org/docs/current/libpq-pgpass.html) file.

The log directory also doesn't seem to be present on your system (`/var/log/pgbackrest/`). When installing from the packages, this directory is automatically created. Perhaps you missed some of the [installation after building from sources](https://pgbackrest.org/user-guide.html#installation) steps? It's usually better / easier to install pgBackRest from the PGDG packages btw.

The unix socket path can be changed by the [`--pg-socket-path`](https://pgbackrest.org/configuration.html#section-stanza/option-pg-socket-path) but if Kingbase changes the socket file name, pgBackRest won't be able to use it imo.

>     6. Describe the issue:
>        actually I tried using pgbackrest to backup king base which based on postgresql9.7, and king base support pg_rman but actually they changed some system table name like pg_database has changed to sys_database, something like this, so pg_rman has been changed to sys_rman.
>        I just thought pgbackrest may support king base, but I got this error, I tried using Navicat to connect king base was just fine.
>        and I observed king base generated a .s.KINGBASE.54321 under /tmp, so I gave the socket direct is "/tmp", and also I tried touch a .s.PGSQL.54321 under /tmp, but no luck.
> 
> 
> could you please give some help on this, may just changed some system level table name so that pgbackrest can connect and continue.

Imho, I don't think we'll be able to support a PG fork if they change PG internal behavior.

Kind Regards

**Comment by hejun2018** [comment]
@pgstef thank you very much for you reply. 

yes, I don't think pgbackrest could support king base ,because I also thought that is wired. but I still want to try that, after I fix /var/log/pgbackrest and create .pgpass, also delete pg-password at pgbackrest.conf, I still got error message:

sh-4.2$ pgbackrest --stanza=demo --log-level-console=info stanza-create
2022-03-29 10:04:57.182 P00   INFO: stanza-create command begin 2.39dev: --exec-id=40847-496dd3ae --log-level-console=info --pg1-database=kingbase --pg1-path=/opt/kingbase/data --pg1-port=54321 --pg1-user=SYSTEM --repo1-path=/opt/kingbase/backup --stanza=demo
WARNING: password file "/opt/kingbase/.pgpass" has group or world access; permissions should be u=rw (0600) or less
WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='kingbase' port=54321 user='SYSTEM'': could not connect to server: Connection refused
      	Is the server running locally and accepting
      	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.54321"?
ERROR: [056]: unable to find primary cluster - cannot proceed
2022-03-29 10:04:57.192 P00   INFO: stanza-create command end: aborted with exception [056]

and output file:

sh-4.2$ cat /var/log/pgbackrest/demo-stanza-create.log 
-------------------PROCESS START-------------------
2022-03-29 10:01:05.656 P00   INFO: stanza-create command begin 2.39dev: --exec-id=40792-5de1cfeb --log-level-console=info --pg1-database=kingbase --pg1-path=/opt/kingbase/data --pg1-port=54321 --pg1-user=SYSTEM --repo1-path=/opt/kingbase/backup --stanza=demo
2022-03-29 10:01:05.668 P00   WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='kingbase' port=54321 user='SYSTEM'': could not connect to server: Connection refused
                                    	Is the server running locally and accepting
                                    	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.54321"?
2022-03-29 10:01:05.669 P00  ERROR: [056]: unable to find primary cluster - cannot proceed
2022-03-29 10:01:05.669 P00   INFO: stanza-create command end: aborted with exception [056]

-------------------PROCESS START-------------------
2022-03-29 10:04:57.182 P00   INFO: stanza-create command begin 2.39dev: --exec-id=40847-496dd3ae --log-level-console=info --pg1-database=kingbase --pg1-path=/opt/kingbase/data --pg1-port=54321 --pg1-user=SYSTEM --repo1-path=/opt/kingbase/backup --stanza=demo
2022-03-29 10:04:57.191 P00   WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='kingbase' port=54321 user='SYSTEM'': could not connect to server: Connection refused
                                    	Is the server running locally and accepting
                                    	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.54321"?
2022-03-29 10:04:57.191 P00  ERROR: [056]: unable to find primary cluster - cannot proceed
2022-03-29 10:04:57.192 P00   INFO: stanza-create command end: aborted with exception [056]

I just wonder if pgbackrest still try to find .s.PGSQL.54321, and could I change some source code at pgbackrest, and let pgbackrest to check .s.kingbase.54321, and see if work fine?

I am sorry for trouble you, but I just want to try. 

thanks.

**Comment by pgstef** [comment]
> I just wonder if pgbackrest still try to find .s.PGSQL.54321, and could I change some source code at pgbackrest, and let pgbackrest to check .s.kingbase.54321, and see if work fine?

afaik, we're relying on PG libpq. So, I don't think there's something you could actually do or change in pgBR source code to change that socket file name.

Other people might have other clues, but imho, I higly doubt pgbackrest can support that kingbase fork.

**Comment by dwsteele** [comment]
A quick glance at the libpq docs (https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) indicates that there is nothing pgbackrest can do to change the socket file name. You would need to modify libpq for that.

Also, as you mentioned above, system tables have been renamed (and https://icode9.com/content-2-1086002.html) so even if you do connect you won't be able to continue. Even if you get everything "working" we have never tested with Kingbase so there is no promise your backups would be any good.

You are welcome to hack on this if you like, but we'd be very unlikely to accept patches, and it's not an effort we have time to support. pgBackRest is Postgres backup software and Kingbase is not Postgres.
