### ISSUE TITLE
Feature request: dynamic pg_start_backup() timeout

### ISSUE THREAD

**Issue by pgguru** [pgbackrest/pgbackrest#1707]
When adjusting the PostgreSQL cluster's `checkpoint_timeout` value high enough, `pgbackrest` will hit its own query timeout when trying to wait politely for a checkpoint to start without `start-fast=y`, which results in a failed backup.

Rather than make the unsuspecting user (me in this completely hypothetical example) tweak a global backrest timeout parameter to match, what about having this timeout be set dynamically by using the database's `checkpoint_timeout` setting and doubling it (or some other near-multiple of this).  This would allow users to tweak their `checkpoint_timeout` while still ensuring that we avoid the immediate full-speed checkpoint required if using `start-fast=y`.

Suggested-by: @sfrost

**Comment by dwsteele** [comment]
This is actually a lot more work that it looks like. By the time we know the checkpoint_timeout the protocol has already been negotiated and all timeouts are set. So we could 1) disconnect and renegotiate with a new timeout or 2) send a new timeout to the remote and propagate that through the IO layers. Either way, we now have a remote we'll need to disconnect or renegotiate again or we'll have the wrong timeout during backup.

That's all very complicated to code and test for something that seems like an edge case. Also, as of 2.37 there is a warning for this condition.

**Comment by pgguru** [comment]
Considering the edge-case nature of this plus the existence of the warning (not to mention how stale this issue is), I will just consider this something we won't do and close the issue.
