### ISSUE TITLE
Question: Is it possible to annotate backup with additional information?

### ISSUE THREAD

**Issue by berlin-ab** [pgbackrest/pgbackrest#1709]
I'd like to be able to create a backup and attach metadata about where the backup originated. Is there a recommended approach for doing this?

**Comment by dwsteele** [comment]
If you mean attach metadata like JSON that will be reported back by pgbackrest in the info command, then no. It sounds like an interesting idea.

One thing you could do is use the backup label (which never changes until removed) to associate metadata with the backup, but that would need to be stored elsewhere.

**Comment by dwsteele** [comment]
@pgstef has created PR #1724 for this feature, so closing. @berlin-ab You should have a look and make sure this does what you need.

**Comment by berlin-ab** [comment]
Thanks! Will do.
