### ISSUE TITLE
check_pgbackrests times out

### ISSUE THREAD

**Issue by martindomeij** [pgbackrest/pgbackrest#1713]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37-1.pgdg18.04+1
check-pgbackrest version: 2.2-1.pgdg18.04+1

2. PostgreSQL version: 11.9-1.pgdg18.04+1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package? Package

7. Describe the issue: check_pgbackrest times out when checking archives. While doing so, it uses 100% of the cpu core it runs on and an increasing amount of memory.

This occurred right after a Postgresql promotion (standby became primary, primary became standby). Could this be the reason, or is it just a coincidence?

Output:

$ /usr/bin/check_pgbackrest --stanza hiteeprod --service archives --repo 1 --debug
DEBUG: pgBackRest info command was : 'pgbackrest info --stanza=hiteeprod --output=json --log-level-console=error --repo=1'
DEBUG: !> pgBackRest info took 0s
DEBUG: Get all the WAL archives and history files...
DEBUG: repo1, archives_dir: archive/hiteeprod/11-1
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest ls command was : 'pgbackrest repo-ls --stanza=hiteeprod archive/hiteeprod/11-1 --output=json --log-level-console=error --repo=1 --recurse'
DEBUG: history file to open : archive/hiteeprod/11-1/00000054.history
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest get command was : 'pgbackrest repo-get --stanza=hiteeprod archive/hiteeprod/11-1/00000054.history --log-level-console=error --repo=1'
DEBUG: !> Get all the WAL archives and history files took 0s
DEBUG: Get all the needed WAL archives...
(after five minutes, it has not gotten past this, and it uses about 9.5 GB memory. After about 10 minutes, it uses about 14.5 GB memory.)

**Comment by martindomeij** [comment]
Update:

This seems indeed have to do with pg promotion. If I create a new backup and expire the old wal files from when the other pg server was primary, the problem goes away.

Can I work around this in any way, exept actually expiring wal files from before the promotion?

**Comment by pgstef** [comment]
Hi,

First of all, check_pgbackrest is a separated project and can be found [here](https://github.com/pgstef/check_pgbackrest). It's best to look/open issues there.

That tool will go way deeper than pgBackRest regarding WAL archives. Basically said, in the info command, pgBackRest will only display the oldest (min) and the newest (max) WAL found in the repo. check_pgbackrest will verify inside the repo that every archives between those 2 min-max exists.

> This occurred right after a Postgresql promotion (standby became primary, primary became standby). Could this be the reason, or is it just a coincidence?

> This seems indeed have to do with pg promotion. If I create a new backup and expire the old wal files from when the other pg server was primary, the problem goes away.

The problem indeed occurs when there's a timeline switch. History files have to be parsed to detect the boundary WAL (WAL where the TL switch happened). And if the history file is missing or the boundary WAL doesn't exist, there's no way to go from min to max and thus, an "infinite loop" risk.

> Can I work around this in any way, exept actually expiring wal files from before the promotion?

This issue has been reported and discussed several times in the project itself. Example [here](https://github.com/pgstef/check_pgbackrest/issues/20#issuecomment-1063882462).

The first thing to do is to prevent missing pieces. If the history file is pushed to the repo when the standby is promoted, there shouldn't be any issue to detect the boundary.
There's also a `--max-archives-check-number` option to limit the number of WAL archives to verify (and force to exit the "infinite loop" if needed).

I recently added a "safeguard" to check if boundary wal can be defined for each TL switch [here](https://github.com/pgstef/check_pgbackrest/commit/1270b32eb6b57f1d70e022053a380843b5b178e2) expecting to help detect the missing pieces sooner. But that will only be part of check_pgbackrest 2.3 release. Feel free to try the dev version to see if it helps in your case.

Kind Regards

**Comment by martindomeij** [comment]
Hello,

I apologize for posting in the wrong project, I did not realize check_pgrackrest was separate.

>If the history file is pushed to the repo when the standby is promoted, there shouldn't be any issue to detect the boundary.
How would I do this? Force an archive push on the primary just before it becomes standby? From standby just before it becomes primary? Both?

**Comment by pgstef** [comment]
> How would I do this? Force an archive push on the primary just before it becomes standby? From standby just before it becomes primary? Both?

If your standby is configured properly (ready to archive), PG should do it at the promotion time (switch timeline and archive the history file at the end of the recovery).

**Comment by martindomeij** [comment]
>If your standby is configured properly (ready to archive), PG should do it at the promotion time (switch timeline and archive the history file at the end of the recovery).

I am not certain I understand all this completely, but this is what it looks like:

The pg promotion took place at 05:55 this morning.

This history file is present on both pg_primary and pg_standby:

$ ls -l pg_wal/00000054.history
-rw------- 1 postgres postgres 3737 Apr 11 05:55 pg_wal/00000054.history

This file is also present on repo1:

$ ls -l 11-1/00000054.history
-rw-r----- 1 postgres postgres 3737 Apr 11 05:55 11-1/00000054.history

The last line of this file reads:

$ tail -1 11-1/00000054.history
83      12B/61000098    no recovery target specified

pg_primary and pg_standby seem to be in agreement regarding the current timeline:

$ psql -p 5436 -c 'SELECT timeline_id FROM pg_control_checkpoint();'
 timeline_id
-------------
          84
(1 row)

Is this amywhere near how it should look?

**Comment by pgstef** [comment]
> Is this anywhere near how it should look?

So you're on timeline 84 and 00000054.history exists in the repo.
What does pgbackrest info min / max wal archives reports ?

**Comment by martindomeij** [comment]
Different stanza this time, as I have expired the wal files from before the pg promtion for the first one.

$ pgbackrest info --stanza=ufoeeprod
stanza: ufoeeprod
    status: ok
    cipher: none

    db (current)
        wal archive min/max (11): 000000530000012B00000016/000000540000012B00000094

        full backup: 20220410-180303F
            timestamp start/stop: 2022-04-10 18:03:03 / 2022-04-10 18:03:08
            wal start/stop: 000000530000012B00000016 / 000000530000012B00000016
            database size: 35.9MB, database backup size: 35.9MB
            repo1: backup set size: 4.1MB, backup size: 4.1MB

        full backup: 20220411-060302F
            timestamp start/stop: 2022-04-11 06:03:02 / 2022-04-11 06:03:07
            wal start/stop: 000000540000012B00000062 / 000000540000012B00000062
            database size: 35.9MB, database backup size: 35.9MB
            repo1: backup set size: 4.2MB, backup size: 4.2MB

**Comment by pgstef** [comment]
Given this info output and the `00000054.history` last line, I think the boundary wal archive would be 000000540000012B00000061 (so only approx 128 wals to check).

It would worth to try `check_pgbackrest --stanza hiteeprod --service archives --output=human --debug --max-archives-check-number=1000` to see the complete debug log. I'm wondering why it couldn't determine a boundary wal.

Anyway, I really think the latest safeguard I added [here](https://github.com/pgstef/check_pgbackrest/blob/1253e2a7536d1eeb32bf30fc420b7ee553679cca/check_pgbackrest#L1085) could help in such cases (and if not, at least give more info). So it would also worth to try the dev version too ;-)

Kind Regards

**Comment by martindomeij** [comment]
$ check_pgbackrest --stanza ufoeeprod --service archives --output=human --debug --max-archives-check-number=1000
DEBUG: pgBackRest info command was : 'pgbackrest info --stanza=ufoeeprod --output=json --log-level-console=error'
DEBUG: !> pgBackRest info took 0s
DEBUG: Get all the WAL archives and history files...
DEBUG: repo1, archives_dir: archive/ufoeeprod/11-1
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest ls command was : 'pgbackrest repo-ls --stanza=ufoeeprod archive/ufoeeprod/11-1 --output=json --log-level-console=error --repo=1 --recurse'
DEBUG: history file to open : archive/ufoeeprod/11-1/00000054.history
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest get command was : 'pgbackrest repo-get --stanza=ufoeeprod archive/ufoeeprod/11-1/00000054.history --log-level-console=error --repo=1'
DEBUG: !> Get all the WAL archives and history files took 0s
DEBUG: Get all the needed WAL archives...
max-archives-check-number limit exceeded.

That's it. No more output...

**Comment by pgstef** [comment]
> That's it. No more output...

`--list-archives` might give us a clue if it found the boundary wal or not. But there will be more info in the dev version (added [some](https://github.com/pgstef/check_pgbackrest/commit/47eb1429f3b4aec31f7330a72ba89932885e7808) today), you could try it ;-)

What I'm expecting to see with the dev version, as an example:
```
DEBUG: history file to open : archive/c7pg/14-1/00000002.history
...
DEBUG: pushed @ 000000010000000000000027 to boundary list
...
DEBUG: List timeline switches and check boundary WALs...
DEBUG: 1 timeline switches happened between 000000010000000000000025 and 00000002000000000000002B
DEBUG: !> List timeline switches and check boundary WALs took 0s
DEBUG: Get all the needed WAL archives...
DEBUG: boundary '000000010000000000000027' reached, jumping to next timeline...
# if --list-archives is enabled
DEBUG: found 000000010000000000000026
DEBUG: found 000000020000000000000027
...
```

**Comment by martindomeij** [comment]
Here we go:

$ ./check_pgbackrest --stanza ufoeeprod --service archives --output=human --debug --list-archives
DEBUG: pgBackRest info command was : 'pgbackrest info --stanza=ufoeeprod --output=json --log-level-console=error'
DEBUG: !> pgBackRest info took 0s
DEBUG: Get all the WAL archives and history files...
DEBUG: repo3, archives_dir: archive/ufoeeprod/11-1
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest ls command was : 'pgbackrest repo-ls --stanza=ufoeeprod archive/ufoeeprod/11-1 --output=json --log-level-console=error --repo=3 --recurse'
DEBUG: history file to open : archive/ufoeeprod/11-1/00000054.history
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest get command was : 'pgbackrest repo-get --stanza=ufoeeprod archive/ufoeeprod/11-1/00000054.history --log-level-console=error --repo=3'
DEBUG: pushed @ 000000010000000400000076 to boundary list
DEBUG: pushed @ 0000000200000007000000D6 to boundary list
DEBUG: pushed @ 000000030000000B000000C6 to boundary list
DEBUG: pushed @ 000000040000000F000000B6 to boundary list
DEBUG: pushed @ 0000000500000015000000E6 to boundary list
DEBUG: pushed @ 0000000600000017000000D9 to boundary list
DEBUG: pushed @ 000000070000001C00000017 to boundary list
DEBUG: pushed @ 000000080000001F00000077 to boundary list
DEBUG: pushed @ 000000090000002300000067 to boundary list
DEBUG: repo2, archives_dir: archive/ufoeeprod/11-1
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest ls command was : 'pgbackrest repo-ls --stanza=ufoeeprod archive/ufoeeprod/11-1 --output=json --log-level-console=error --repo=2 --recurse'
DEBUG: history file to open : archive/ufoeeprod/11-1/00000054.history
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest get command was : 'pgbackrest repo-get --stanza=ufoeeprod archive/ufoeeprod/11-1/00000054.history --log-level-console=error --repo=2'
DEBUG: pushed @ 000000010000000400000076 to boundary list
DEBUG: pushed @ 0000000200000007000000D6 to boundary list
DEBUG: pushed @ 000000030000000B000000C6 to boundary list
DEBUG: pushed @ 000000040000000F000000B6 to boundary list
DEBUG: pushed @ 0000000500000015000000E6 to boundary list
DEBUG: pushed @ 0000000600000017000000D9 to boundary list
DEBUG: pushed @ 000000070000001C00000017 to boundary list
DEBUG: pushed @ 000000080000001F00000077 to boundary list
DEBUG: pushed @ 000000090000002300000067 to boundary list
DEBUG: !> Get all the WAL archives and history files took 0s
DEBUG: List timeline switches and check boundary WALs...
DEBUG: 1 timeline switches happened between 0000005300000127000000D1 and 000000540000012B000000AC
Service        : WAL_ARCHIVES
Returns        : 2 (CRITICAL)
Message        : 00000053 boundary WAL not determined

**Comment by martindomeij** [comment]
Here we go:

$ ./check_pgbackrest --stanza ufoeeprod --service archives --output=human --debug --list-archives --repo=2
DEBUG: pgBackRest info command was : 'pgbackrest info --stanza=ufoeeprod --output=json --log-level-console=error --repo=2'
DEBUG: !> pgBackRest info took 0s
DEBUG: Get all the WAL archives and history files...
DEBUG: repo2, archives_dir: archive/ufoeeprod/11-1
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest ls command was : 'pgbackrest repo-ls --stanza=ufoeeprod archive/ufoeeprod/11-1 --output=json --log-level-console=error --repo=2 --recurse'
DEBUG: history file to open : archive/ufoeeprod/11-1/00000054.history
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest get command was : 'pgbackrest repo-get --stanza=ufoeeprod archive/ufoeeprod/11-1/00000054.history --log-level-console=error --repo=2'
DEBUG: pushed @ 000000010000000400000076 to boundary list
DEBUG: pushed @ 0000000200000007000000D6 to boundary list
DEBUG: pushed @ 000000030000000B000000C6 to boundary list
DEBUG: pushed @ 000000040000000F000000B6 to boundary list
DEBUG: pushed @ 0000000500000015000000E6 to boundary list
DEBUG: pushed @ 0000000600000017000000D9 to boundary list
DEBUG: pushed @ 000000070000001C00000017 to boundary list
DEBUG: pushed @ 000000080000001F00000077 to boundary list
DEBUG: pushed @ 000000090000002300000067 to boundary list
DEBUG: !> Get all the WAL archives and history files took 0s
DEBUG: List timeline switches and check boundary WALs...
DEBUG: 1 timeline switches happened between 000000530000012B0000003B and 000000540000012B000000AD
Service        : WAL_ARCHIVES
Returns        : 2 (CRITICAL)
Message        : 00000053 boundary WAL not determined

**Comment by pgstef** [comment]
Hm, that's an interesting output, Thanks.

First of all, the safeguard regarding the boundary WAL not found seems to work as expected to avoid the infinite loop.

The boundary files pushed are also interesting. It seems that the timelines greater than 9 can't be fetched from the history file. I've pushed a fix [here](https://github.com/pgstef/check_pgbackrest/commit/ba9226dea84b982878d50ae546723018a9cf1c2a) (and moved the boundary list debug to a new `--debug --list-boundaries` option).

Could you try the dev version again? It should fix this issue.

**Comment by martindomeij** [comment]
Looks like you have done it. :)

$ ./check_pgbackrest --stanza ufoeeprod --service archives --latest-archive-age-alert 5h --repo 2
WAL_ARCHIVES OK - 223 unique WAL archived, latest archived since 2m53s | latest_archive_age=173s num_unique_archives=223

$ ./check_pgbackrest --stanza ufoeeprod --service archives --output=human  --repo=2
Service        : WAL_ARCHIVES
Returns        : 0 (OK)
Message        : 223 unique WAL archived
Message        : latest archived since 55s
Long message   : latest_archive_age=55s
Long message   : num_unique_archives=223
Long message   : min_wal=000000530000012B0000003B
Long message   : max_wal=000000540000012C00000018
Long message   : latest_archive=000000540000012C00000018
Long message   : latest_bck_archive_start=000000540000012B00000087
Long message   : latest_bck=20220411-120303F
Long message   : latest_bck_type=full
Long message   : oldest_archive=000000530000012B0000003B
Long message   : oldest_bck_archive_start=000000530000012B0000003B
Long message   : oldest_bck=20220411-000302F
Long message   : oldest_bck_type=full

$ ./check_pgbackrest --stanza ufoeeprod --service archives --output=human --debug --list-archives --repo=2
DEBUG: pgBackRest info command was : 'pgbackrest info --stanza=ufoeeprod --output=json --log-level-console=error --repo=2'
DEBUG: !> pgBackRest info took 0s
DEBUG: Get all the WAL archives and history files...
DEBUG: repo2, archives_dir: archive/ufoeeprod/11-1
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest ls command was : 'pgbackrest repo-ls --stanza=ufoeeprod archive/ufoeeprod/11-1 --output=json --log-level-console=error --repo=2 --recurse'
DEBUG: history file to open : archive/ufoeeprod/11-1/00000054.history
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest get command was : 'pgbackrest repo-get --stanza=ufoeeprod archive/ufoeeprod/11-1/00000054.history --log-level-console=error --repo=2'
DEBUG: !> Get all the WAL archives and history files took 0s
DEBUG: List timeline switches and check boundary WALs...
DEBUG: 1 timeline switch(es) happened between 000000530000012B0000003B and 000000540000012C00000017
DEBUG: !> List timeline switches and check boundary WALs took 0s
DEBUG: Get all the needed WAL archives...
DEBUG: boundary '000000530000012B00000061' reached, jumping to next timeline...
DEBUG: !> Get all the needed WAL archives took 0s
DEBUG: !> Go through needed WAL list and check took 0s
DEBUG: Get all the needed WAL archives for 20220411-000302F...
DEBUG: Get all the needed WAL archives for 20220411-120303F...
DEBUG: !> Go through each backup, get the needed WAL and check took 0s
DEBUG: found 000000530000012B0000003B
DEBUG: found 000000530000012B0000003C
DEBUG: found 000000530000012B0000003D
DEBUG: found 000000530000012B0000003E
DEBUG: found 000000530000012B0000003F
DEBUG: found 000000530000012B00000040
DEBUG: found 000000530000012B00000041
DEBUG: found 000000530000012B00000042
DEBUG: found 000000530000012B00000043
DEBUG: found 000000530000012B00000044
DEBUG: found 000000530000012B00000045
DEBUG: found 000000530000012B00000046
DEBUG: found 000000530000012B00000047
DEBUG: found 000000530000012B00000048
DEBUG: found 000000530000012B00000049
DEBUG: found 000000530000012B0000004A
DEBUG: found 000000530000012B0000004B
DEBUG: found 000000530000012B0000004C
DEBUG: found 000000530000012B0000004D
DEBUG: found 000000530000012B0000004E
DEBUG: found 000000530000012B0000004F
DEBUG: found 000000530000012B00000050
DEBUG: found 000000530000012B00000051
DEBUG: found 000000530000012B00000052
DEBUG: found 000000530000012B00000053
DEBUG: found 000000530000012B00000054
DEBUG: found 000000530000012B00000055
DEBUG: found 000000530000012B00000056
DEBUG: found 000000530000012B00000057
DEBUG: found 000000530000012B00000058
DEBUG: found 000000530000012B00000059
DEBUG: found 000000530000012B0000005A
DEBUG: found 000000530000012B0000005B
DEBUG: found 000000530000012B0000005C
DEBUG: found 000000530000012B0000005D
DEBUG: found 000000530000012B0000005E
DEBUG: found 000000530000012B0000005F
DEBUG: found 000000530000012B00000060
DEBUG: found 000000530000012B00000061
DEBUG: found 000000540000012B00000061
DEBUG: found 000000540000012B00000062
DEBUG: found 000000540000012B00000063
DEBUG: found 000000540000012B00000064
DEBUG: found 000000540000012B00000065
DEBUG: found 000000540000012B00000066
DEBUG: found 000000540000012B00000067
DEBUG: found 000000540000012B00000068
DEBUG: found 000000540000012B00000069
DEBUG: found 000000540000012B0000006A
DEBUG: found 000000540000012B0000006B
DEBUG: found 000000540000012B0000006C
DEBUG: found 000000540000012B0000006D
DEBUG: found 000000540000012B0000006E
DEBUG: found 000000540000012B0000006F
DEBUG: found 000000540000012B00000070
DEBUG: found 000000540000012B00000071
DEBUG: found 000000540000012B00000072
DEBUG: found 000000540000012B00000073
DEBUG: found 000000540000012B00000074
DEBUG: found 000000540000012B00000075
DEBUG: found 000000540000012B00000076
DEBUG: found 000000540000012B00000077
DEBUG: found 000000540000012B00000078
DEBUG: found 000000540000012B00000079
DEBUG: found 000000540000012B0000007A
DEBUG: found 000000540000012B0000007B
DEBUG: found 000000540000012B0000007C
DEBUG: found 000000540000012B0000007D
DEBUG: found 000000540000012B0000007E
DEBUG: found 000000540000012B0000007F
DEBUG: found 000000540000012B00000080
DEBUG: found 000000540000012B00000081
DEBUG: found 000000540000012B00000082
DEBUG: found 000000540000012B00000083
DEBUG: found 000000540000012B00000084
DEBUG: found 000000540000012B00000085
DEBUG: found 000000540000012B00000086
DEBUG: found 000000540000012B00000087
DEBUG: found 000000540000012B00000088
DEBUG: found 000000540000012B00000089
DEBUG: found 000000540000012B0000008A
DEBUG: found 000000540000012B0000008B
DEBUG: found 000000540000012B0000008C
DEBUG: found 000000540000012B0000008D
DEBUG: found 000000540000012B0000008E
DEBUG: found 000000540000012B0000008F
DEBUG: found 000000540000012B00000090
DEBUG: found 000000540000012B00000091
DEBUG: found 000000540000012B00000092
DEBUG: found 000000540000012B00000093
DEBUG: found 000000540000012B00000094
DEBUG: found 000000540000012B00000095
DEBUG: found 000000540000012B00000096
DEBUG: found 000000540000012B00000097
DEBUG: found 000000540000012B00000098
DEBUG: found 000000540000012B00000099
DEBUG: found 000000540000012B0000009A
DEBUG: found 000000540000012B0000009B
DEBUG: found 000000540000012B0000009C
DEBUG: found 000000540000012B0000009D
DEBUG: found 000000540000012B0000009E
DEBUG: found 000000540000012B0000009F
DEBUG: found 000000540000012B000000A0
DEBUG: found 000000540000012B000000A1
DEBUG: found 000000540000012B000000A2
DEBUG: found 000000540000012B000000A3
DEBUG: found 000000540000012B000000A4
DEBUG: found 000000540000012B000000A5
DEBUG: found 000000540000012B000000A6
DEBUG: found 000000540000012B000000A7
DEBUG: found 000000540000012B000000A8
DEBUG: found 000000540000012B000000A9
DEBUG: found 000000540000012B000000AA
DEBUG: found 000000540000012B000000AB
DEBUG: found 000000540000012B000000AC
DEBUG: found 000000540000012B000000AD
DEBUG: found 000000540000012B000000AE
DEBUG: found 000000540000012B000000AF
DEBUG: found 000000540000012B000000B0
DEBUG: found 000000540000012B000000B1
DEBUG: found 000000540000012B000000B2
DEBUG: found 000000540000012B000000B3
DEBUG: found 000000540000012B000000B4
DEBUG: found 000000540000012B000000B5
DEBUG: found 000000540000012B000000B6
DEBUG: found 000000540000012B000000B7
DEBUG: found 000000540000012B000000B8
DEBUG: found 000000540000012B000000B9
DEBUG: found 000000540000012B000000BA
DEBUG: found 000000540000012B000000BB
DEBUG: found 000000540000012B000000BC
DEBUG: found 000000540000012B000000BD
DEBUG: found 000000540000012B000000BE
DEBUG: found 000000540000012B000000BF
DEBUG: found 000000540000012B000000C0
DEBUG: found 000000540000012B000000C1
DEBUG: found 000000540000012B000000C2
DEBUG: found 000000540000012B000000C3
DEBUG: found 000000540000012B000000C4
DEBUG: found 000000540000012B000000C5
DEBUG: found 000000540000012B000000C6
DEBUG: found 000000540000012B000000C7
DEBUG: found 000000540000012B000000C8
DEBUG: found 000000540000012B000000C9
DEBUG: found 000000540000012B000000CA
DEBUG: found 000000540000012B000000CB
DEBUG: found 000000540000012B000000CC
DEBUG: found 000000540000012B000000CD
DEBUG: found 000000540000012B000000CE
DEBUG: found 000000540000012B000000CF
DEBUG: found 000000540000012B000000D0
DEBUG: found 000000540000012B000000D1
DEBUG: found 000000540000012B000000D2
DEBUG: found 000000540000012B000000D3
DEBUG: found 000000540000012B000000D4
DEBUG: found 000000540000012B000000D5
DEBUG: found 000000540000012B000000D6
DEBUG: found 000000540000012B000000D7
DEBUG: found 000000540000012B000000D8
DEBUG: found 000000540000012B000000D9
DEBUG: found 000000540000012B000000DA
DEBUG: found 000000540000012B000000DB
DEBUG: found 000000540000012B000000DC
DEBUG: found 000000540000012B000000DD
DEBUG: found 000000540000012B000000DE
DEBUG: found 000000540000012B000000DF
DEBUG: found 000000540000012B000000E0
DEBUG: found 000000540000012B000000E1
DEBUG: found 000000540000012B000000E2
DEBUG: found 000000540000012B000000E3
DEBUG: found 000000540000012B000000E4
DEBUG: found 000000540000012B000000E5
DEBUG: found 000000540000012B000000E6
DEBUG: found 000000540000012B000000E7
DEBUG: found 000000540000012B000000E8
DEBUG: found 000000540000012B000000E9
DEBUG: found 000000540000012B000000EA
DEBUG: found 000000540000012B000000EB
DEBUG: found 000000540000012B000000EC
DEBUG: found 000000540000012B000000ED
DEBUG: found 000000540000012B000000EE
DEBUG: found 000000540000012B000000EF
DEBUG: found 000000540000012B000000F0
DEBUG: found 000000540000012B000000F1
DEBUG: found 000000540000012B000000F2
DEBUG: found 000000540000012B000000F3
DEBUG: found 000000540000012B000000F4
DEBUG: found 000000540000012B000000F5
DEBUG: found 000000540000012B000000F6
DEBUG: found 000000540000012B000000F7
DEBUG: found 000000540000012B000000F8
DEBUG: found 000000540000012B000000F9
DEBUG: found 000000540000012B000000FA
DEBUG: found 000000540000012B000000FB
DEBUG: found 000000540000012B000000FC
DEBUG: found 000000540000012B000000FD
DEBUG: found 000000540000012B000000FE
DEBUG: found 000000540000012B000000FF
DEBUG: found 000000540000012C00000000
DEBUG: found 000000540000012C00000001
DEBUG: found 000000540000012C00000002
DEBUG: found 000000540000012C00000003
DEBUG: found 000000540000012C00000004
DEBUG: found 000000540000012C00000005
DEBUG: found 000000540000012C00000006
DEBUG: found 000000540000012C00000007
DEBUG: found 000000540000012C00000008
DEBUG: found 000000540000012C00000009
DEBUG: found 000000540000012C0000000A
DEBUG: found 000000540000012C0000000B
DEBUG: found 000000540000012C0000000C
DEBUG: found 000000540000012C0000000D
DEBUG: found 000000540000012C0000000E
DEBUG: found 000000540000012C0000000F
DEBUG: found 000000540000012C00000010
DEBUG: found 000000540000012C00000011
DEBUG: found 000000540000012C00000012
DEBUG: found 000000540000012C00000013
DEBUG: found 000000540000012C00000014
DEBUG: found 000000540000012C00000015
DEBUG: found 000000540000012C00000016
DEBUG: found 000000540000012C00000017
Service        : WAL_ARCHIVES
Returns        : 0 (OK)
Message        : 222 unique WAL archived
Message        : latest archived since 8m33s
Long message   : latest_archive_age=8m33s
Long message   : num_unique_archives=222
Long message   : min_wal=000000530000012B0000003B
Long message   : max_wal=000000540000012C00000017
Long message   : latest_archive=000000540000012C00000017
Long message   : latest_bck_archive_start=000000540000012B00000087
Long message   : latest_bck=20220411-120303F
Long message   : latest_bck_type=full
Long message   : oldest_archive=000000530000012B0000003B
Long message   : oldest_bck_archive_start=000000530000012B0000003B
Long message   : oldest_bck=20220411-000302F
Long message   : oldest_bck_type=full

**Comment by pgstef** [comment]
Great, Thanks.
I think we may now close this issue. I'll see to get a check_pgbackrest new release (2.3) out soon.
Kind Regards
