### ISSUE TITLE
ERROR: [082]: WAL segment was not archived before the 60000ms timeout

### ISSUE THREAD

**Issue by navaneswarareddy** [pgbackrest/pgbackrest#1717]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.38 

2. PostgreSQL version: 13.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos-8

4. Did you install pgBackRest from source or from a package? package 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    
[postgres@manager-4 ~]$ cat /etc/pgbackrest/pgbackrest.conf 
[global]
repo-path=/var/lib/pgbackrest 
backup-user=postgres
retention-full=3
retention-diff=2
process-max=2
log-path=/var/log/pgbackrest
start-fast=y 

[demo]
pg1-path=/var/lib/pgsql/data
pg1-port=5432

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
 
```
show listen_addresses;
 listen_addresses 
------------------
 *
postgres=# show archive_command;
             archive_command              
------------------------------------------
 pgbackrest --stanza=demo archive-push %p

postgres=# show archive_mode;
 archive_mode 
--------------
 on

postgres=# show wal_level;
 wal_level 
-----------
 logical

postgres=# show max_wal_senders;
 max_wal_senders 
-----------------
 3

postgres=# show port;
 port 
------
 5432
(1 row)

```
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

[postgres@manager-4 pgbackrest]$ pgbackrest --stanza=demo check --log-level-console=info
2022-04-16 12:21:03.061 P00   INFO: check command begin 2.38: --exec-id=1211487-45d5410d --log-level-console=info --log-path=/var/log/pgbackrest --pg1-path=/var/lib/pgsql/data --pg1-port=5432 --repo1-path=/var/lib/pgbackrest --stanza=demo
2022-04-16 12:21:03.666 P00   INFO: check repo1 configuration (primary)
2022-04-16 12:21:04.168 P00   INFO: check repo1 archive for WAL (primary)
ERROR: [082]: WAL segment 000000010000000000000033 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2022-04-16 12:22:04.190 P00   INFO: check command end: aborted with exception [082]

**Comment by jreidthompson** [comment]
Are there any errors noted in the postgresql.log or in the pgbackrest logs ( default pgbackrest logs location is in /var/log/pgbackrest )
