### ISSUE TITLE
Issue with Pgbackrest 2.10

### ISSUE THREAD

**Issue by lux7790** [pgbackrest/pgbackrest#1719]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.10

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Linux Debian

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Is that Pgbackuprest too old ? I have an issue "ERROR [046]: : unexpected control version = 1300 and catalog version = 202107181"

**Comment by sfrost** [comment]
Yes.  2.10 is from Feb 2019, over three years old at this point ...
