### ISSUE TITLE
Unable to unpack Int64 when running on 32-bit OS

### ISSUE THREAD

**Issue by rljanus** [pgbackrest/pgbackrest#172]
[root@localhost ~]# uname --all
Linux localhost.localdomain 2.6.32-573.el6.i686 #1 SMP Thu Jul 23 12:37:35 UTC 2015 i686 i686 i386 GNU/Linux

Perl -v: [root@localhost BackRest]# perl -v

This is perl, v5.10.1 (*) built for i386-linux-thread-multi

[root@localhost ~]# sudo -u postgres pg_backrest --stanza=demo --log-level-console=info backup
2016-02-16 13:57:50.661 T00   INFO: backup start: --db-path=/var/lib/pgsql/9.5/data --log-level-console=info --repo-path=/var/lib/backrest --repo-remote-path=/var/lib/backrest --stanza=demo
2016-02-16 13:57:50.697 T00   WARN: no prior backup exists, incr backup has been changed to full
2016-02-16 13:57:50.699 T00   INFO: backup stop
2016-02-16 13:57:50.699 T00  ERROR: [140]: process terminated due to an unhandled exception
Invalid type 'Q' in unpack at /usr/lib/perl5/BackRest/Db.pm line 440.
 at /usr/bin/pg_backrest line 14
        main::__ANON__('Invalid type \'Q\' in unpack at /usr/lib/perl5/BackRest/Db.pm...') called at /usr/lib/perl5/BackRest/Db.pm line 440
        BackRest::Db::info(undef, 'BackRest::File=HASH(0x96f1038)', '/var/lib/pgsql/9.5/data') called at /usr/lib/perl5/BackRest/Backup.pm line 751
        BackRest::Backup::process('BackRest::Backup=HASH(0x924a398)') called at /usr/bin/pg_backrest line 202
        eval {...} called at /usr/bin/pg_backrest line 32
 at /usr/bin/pg_backrest line 238
 at /usr/bin/pg_backrest line 14
        main::__ANON__('Invalid type \'Q\' in unpack at /usr/lib/perl5/BackRest/Db.pm...') called at /usr/share/perl5/Carp.pm line 45
        Carp::confess('Invalid type \'Q\' in unpack at /usr/lib/perl5/BackRest/Db.pm...') called at /usr/bin/pg_backrest line 238

**Comment by dwsteele** [comment]
Added a note to documentation that only 64-bit distributions are supported.  It seems unlikely that anybody would be running a production server on anything else these days so we'll wait for a field report before taking further action.
