### ISSUE TITLE
ERROR: [056]: unable to find primary cluster - cannot proceed

### ISSUE THREAD

**Issue by lux7790** [pgbackrest/pgbackrest#1720]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.38

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Debian 10

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: I'm trying to create the stanza with this command : 
    sudo -u postgres pgbackrest --stanza=backup --log-level-console=info stanza-create

The full message is:
2022-04-21 09:56:47.190 P00   INFO: stanza-create command begin 2.38: --exec-id=79854-bdca8054 --log-level-console=info --pg1-path=/u02/pgdata/14/db_1 --repo1-path=/var/lib/pgbackrest --stanza=backup
WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432': connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
ERROR: [056]: unable to find primary cluster - cannot proceed
2022-04-21 09:56:47.191 P00   INFO: stanza-create command end: aborted with exception [056]

   The content of my pgbackrest.conf is the following:

[global]
repo1-path=/var/lib/pgbackrest

[global:archive-push]
compress-level=3
repo1-retention-full=7

[backup]
pg1-path=/u02/pgdata/14/db_1

**Comment by pgstef** [comment]
Hi,

Is your PG cluster running locally on port 5432?
`"/var/run/postgresql/.s.PGSQL.5432"`

What does `SHOW unix_socket_directories;` gives you?

Example:
```
🐘 postgres@postgres=# show unix_socket_directories ;
 unix_socket_directories 
-------------------------
 /var/run/postgresql
(1 row)

🐘 postgres@postgres=# show port;
 port 
------
 5432
(1 row)
```

**Comment by lux7790** [comment]
Here is my answer:

postgres=# SHOW unix_socket_directories;
 unix_socket_directories
-------------------------
 /tmp
(1 row)

postgres=# show port;
 port
------
 5432
(1 row)

**Comment by pgstef** [comment]
> ## postgres=# SHOW unix_socket_directories;
> unix_socket_directories
> /tmp (1 row)

You need to set [pg1-socket-path](https://pgbackrest.org/configuration.html#section-stanza/option-pg-socket-path) then.
`pg1-socket-path=/tmp` should fix your issue.

Kind Regards,

**Comment by lux7790** [comment]
Here is my new pgbackrest.conf

[global]
repo1-path=/var/lib/pgbackrest
pg1-socket-path=/tmp

[global:archive-push]
compress-level=3
repo1-retention-full=7

[backup]
pg1-path=/u02/pgdata/14/db_1

And the same error message:
root@mercure:/var/run/postgresql/14-main.pg_stat_tmp# sudo -u postgres pgbackrest --stanza=backup --log-level-console=info stanza-create
WARN: configuration file contains stanza-only option 'pg1-socket-path' in global section 'global'
2022-04-21 11:23:47.052 P00   INFO: stanza-create command begin 2.38: --exec-id=77265-aabcdc43 --log-level-console=info --pg1-path=/u02/pgdata/14/db_1 --repo1-path=/var/lib/pgbackrest --stanza=backup
WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432': connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
ERROR: [056]: unable to find primary cluster - cannot proceed
2022-04-21 11:23:47.052 P00   INFO: stanza-create command end: aborted with exception [056]

**Comment by lux7790** [comment]
Is .s.PGSQL.5432 a file or a directory and who is creating it ?

**Comment by lux7790** [comment]
I did a find on .s.PGSQL.5432 and here is the result:
root@mercure:/tmp# ls .s.* -lrth
-rw------- 1 postgres postgres 47 avr 21 11:04 .s.PGSQL.5432.lock
srwxrwxrwx 1 postgres postgres  0 avr 21 11:04 .s.PGSQL.5432

**Comment by lux7790** [comment]
Finally, it's a file !

**Comment by lux7790** [comment]
pgbackrest is still using /var/run/postgresql repository to find the file. I put it in the global section. Is it right ?

**Comment by pgstef** [comment]
Hi,

You should read the error messages:
`WARN: configuration file contains stanza-only option 'pg1-socket-path' in global section 'global'`

Put `pg1-socket-path=/tmp` into your stanza (`[backup]`) section rather than in the global section. Just next to your `pg1-path`.

The socket file is created by Postgres itself when it starts. See the [unix_socket_directories](https://www.postgresql.org/docs/current/runtime-config-connection.html) PG setting:
```
In addition to the socket file itself, which is named .s.PGSQL.nnnn where nnnn is the server's port number, an ordinary file named .s.PGSQL.nnnn.lock will be created in each of the unix_socket_directories directories. Neither file should ever be removed manually. For sockets in the abstract namespace, no lock file is created.
```

Regards
