### ISSUE TITLE
Backup from standby server without SSH communication between the hosts

### ISSUE THREAD

**Issue by jiangphcn** [pgbackrest/pgbackrest#1723]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
v2.38
2. PostgreSQL version:
13.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?
from source code
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

From https://pgstef.github.io/2020/09/04/combining_pgbackrest_and_streaming_replication.html, we can know that it is possible to perform backup from standy/secondary server. Is it possible to perfom backup from standby server without SSH communication between the hosts, i.e. using other protocal or other alternative way?

```
Take backups from the secondary server

pgBackRest can perform backups on a standby server instead of the primary. Both the primary and secondary databases configuration are required, even if the majority of the files will be copied from the secondary to reduce load on the primary.

Remark: To do so, you need to setup a trusted SSH communication between the hosts.
```

Your help is highly appreciated!  Thanks so much!

**Comment by pgstef** [comment]
Hi,

That blog post (illustrating [standby-backup](https://pgbackrest.org/user-guide.html#standby-backup)) was published on September 2020, with pgBackRest 2.29.

There has been a lot of new [features](https://pgbackrest.org/release.html) since then, including [TLS server](https://pgbackrest.org/user-guide-rhel.html#repo-host/config) in 2.37.

TLS connections can indeed replace SSH connections now if TLS server are implemented correctly on all hosts.
(Another example can be found [here](https://pgstef.github.io/2022/02/21/pgbackrest_tls_server.html))

I like to write blog posts to illustrate specific situations but the up-to-date source of truth will always be the official [User Guides](https://pgbackrest.org/user-guide-index.html) :blush:

Kind Regards

**Comment by jiangphcn** [comment]
Hey @pgstef, thanks so much for above information. I am trying to use above information to make configuration. Could you please let this issue open for a few days? I will come back to you soon. 

Thanks again!

**Comment by jiangphcn** [comment]
Hey @pgstef, thanks again for your valuable information above. Could you continue to help? Thanks so much!

Is it possible to use TLS protocal to perform backup in 3 nodes (e,g, in one primary node and 2 secondary nodes) individually? Knowing that it will generate duplicate copies, but it would be great if it is possible.

In recent test, I tried to first configure in primary node, and want to perform backup in primary node first, and then move to perform backup in secondary node.

The `pgbackrest.conf` file in primary node is
```
[global]
repo1-path=/data/backup
repo1-retention-full=2

# general options
process-max=2
log-level-console=info
log-level-file=debug

# tls server options
tls-server-address=*
tls-server-cert-file=/var/lib/postgresql/certs/pg1-srv.crt
tls-server-key-file=/var/lib/postgresql/certs/pg1-srv.key
tls-server-ca-file=/var/lib/postgresql/certs/ca.crt
tls-server-auth=pg1-srv=dbaas
repo1-retention-diff=1
repo1-retention-full-type=count
start-fast=y
archive-async=y
spool-path=/data/backup/spool
compress-level=3
compress-type=lz4
db-timeout=86400

[demo]
pg1-path=/data/db
pg1-host-type=tls
pg1-host-cert-file=/var/lib/postgresql/certs/pg1-srv.crt
pg1-host-key-file=/var/lib/postgresql/certs/pg1-srv.key
pg1-host-ca-file=/var/lib/postgresql/certs/ca.crt
pg1-host=pg1-srv
```
The archive_command in postgresql.conf:

```
archive_command = 'pgbackrest --stanza=dbaas archive-push %p'
```

The TLS server can start
```
$pgbackrest server

2022-05-02 09:50:21.833 P00   INFO: server command begin 2.38: --exec-id=1071-728f35a7 --log-level-console=info --log-level-file=off --tls-server-address=* --tls-server-auth=pg1-srv=demo --tls-server-ca-file=/var/lib/postgresql/certs/ca.crt --tls-server-cert-file=/var/lib/postgresql/certs/pg1-srv.crt --tls-server-key-file=/var/lib/postgresql/certs/pg1-srv.key
```
`stanza` can be created
```
$pgbackrest --stanza=demo --log-level-console=info stanza-create
2022-05-02 11:00:44.835 P00   INFO: stanza-create command begin 2.38: --db-timeout=86400 --exec-id=4001-6ee6cf70 --log-level-console=info --log-level-file=debug --pg1-host=pg1-srv --pg1-host-ca-file=/var/lib/postgresql/certs/ca.crt --pg1-host-cert-file=/var/lib/postgresql/certs/pg1-srv.crt --pg1-host-key-file=/var/lib/postgresql/certs/pg1-srv.key --pg1-host-type=tls --pg1-path=/data/db --repo1-path=/data/backup --stanza=demo
2022-05-02 11:00:45.487 P00   INFO: stanza-create for stanza 'demo' on repo1
2022-05-02 11:00:45.492 P00   INFO: stanza-create command end: completed successfully (669ms)
```
However, we got hung when performing `backup`. It was found that it happens in `archive-push` step.

```
$pgbackrest --stanza=demo --log-level-console=info backup
2022-05-02 10:50:47.828 P00   INFO: backup command begin 2.38: --compress-level=3 --compress-type=lz4 --db-timeout=86400 --exec-id=3613-eeb7a655 --log-level-console=info --log-level-file=debug --pg1-host=pg1-srv --pg1-host-ca-file=/var/lib/postgresql/certs/ca.crt --pg1-host-cert-file=/var/lib/postgresql/certs/pg1-srv.crt --pg1-host-key-file=/var/lib/postgresql/certs/pg1-srv.key --pg1-host-type=tls --pg1-path=/data/db --process-max=2 --repo1-path=/data/backup --repo1-retention-diff=1 --repo1-retention-full=2 --repo1-retention-full-type=count --stanza=demo --start-fast
2022-05-02 10:50:48.602 P00   INFO: last backup label = 20220502-104700F_20220502-104931I, version = 2.38
2022-05-02 10:50:48.602 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2022-05-02 10:50:49.110 P00   INFO: backup start archive = 000000010000000000000015, lsn = 0/15000028
2022-05-02 10:50:49.110 P00   INFO: check archive for prior segment 000000010000000000000014
ERROR: [082]: WAL segment 000000010000000000000014 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
```      

The log in postgresql is

```
May  2 09:43:55 postgresql-27027 postgres[283]: [6] 2022-05-02 09:43:55.276 UTC [283-1] [unknown]@[unknown] LOG:  connection received: host=172.16.132.3 port=34356
[284-1] [unknown]@[unknown] LOG:  connection received: host=127.0.0.1 port=42282May  2 09:43:55 postgres[285]: [6] 2022-05-02 09:43:55.534 UTC [285-1] [unknown]@[unknown] LOG:  connection received: host=127.0.0.1 port=42284May  2 09:43:55 postgresql-27027 postgres[254]: [6] 2022-05-02 09:43:55.884 UTC [254-3] LOG:  archive command failed with exit code 103#0122022-05-02 09:43:55.884 UTC [254-4] DETAIL:  The failed archive command was: pgbackrest --stanza=demo archive-push pg_wal/000000010000000000000001
May  2 09:43:56 postgresql-27027 postgres[290]: [6] 2022-05-02 09:43:56.561 UTC [290-1] [unknown]@[unknown] LOG:  connection received: host=127.0.0.1 port=42286May  2 09:43:57 postgresql-27027 postgres[254]: [7] 2022-05-02 09:43:57.088 UTC [254-5] LOG:  archive command failed with exit code 103#0122022-05-02 09:43:57.088 UTC [254-6] DETAIL:  The failed archive command was: pgbackrest --stanza=demo archive-push pg_wal/000000010000000000000001
May  2 09:43:57 postgresql-27027 postgres[254]: [8] 2022-05-02 09:43:57.088 UTC [254-7] WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
```

**Comment by pgstef** [comment]
First of all, your configuration looks like you're trying to take local backups into `/data/backup` on a PG node (primary).
If that's the case, you shouldn't store your backups locally. And you wouldn't need TLS or SSH connections at this point (`pg1-host` should be used on a dedicated backup server config).

Taking backups from standby servers should work (using TLS or SSH connections) as long as your repository is **shared** between the hosts, because the WAL archives are pushed from the primary server to the backup repository and the standby server should be able to see those archives when taking a new backup.

I didn't tried it but I guess something like this could work :

* On the primary server

```ini
[global]
# repo location and retention
repo1-path=/data/backup
repo1-retention-full=2
repo1-retention-diff=1

# global options
delta=y
start-fast=y
process-max=2
log-level-console=info
log-level-file=debug
archive-async=y
spool-path=/data/spool
compress-type=lz4

# tls server options
tls-server-address=*
tls-server-cert-file=/var/lib/postgresql/certs/pg1-srv.crt
tls-server-key-file=/var/lib/postgresql/certs/pg1-srv.key
tls-server-ca-file=/var/lib/postgresql/certs/ca.crt
tls-server-auth=pg2-srv=demo

[demo]
pg1-path=/data/db
pg2-host-type=tls
pg2-host-cert-file=/var/lib/postgresql/certs/pg1-srv.crt
pg2-host-key-file=/var/lib/postgresql/certs/pg1-srv.key
pg2-host-ca-file=/var/lib/postgresql/certs/ca.crt
pg2-host=pg2-srv
pg2-path=/data/db
```

* On the standby server

```ini
[global]
# repo location and retention
repo1-path=/data/backup
repo1-retention-full=2
repo1-retention-diff=1

# global options
delta=y
start-fast=y
process-max=2
log-level-console=info
log-level-file=debug
archive-async=y
spool-path=/data/spool
compress-type=lz4

# tls server options
tls-server-address=*
tls-server-cert-file=/var/lib/postgresql/certs/pg2-srv.crt
tls-server-key-file=/var/lib/postgresql/certs/pg2-srv.key
tls-server-ca-file=/var/lib/postgresql/certs/ca.crt
tls-server-auth=pg1-srv=demo

[demo]
pg1-path=/data/db
pg2-host-type=tls
pg2-host-cert-file=/var/lib/postgresql/certs/pg2-srv.crt
pg2-host-key-file=/var/lib/postgresql/certs/pg2-srv.key
pg2-host-ca-file=/var/lib/postgresql/certs/ca.crt
pg2-host=pg1-srv
pg2-path=/data/db
backup-standby=y
```

In this configuration, I've assumed your `/data/backup` is an nfs share between the hosts.
I've then set `spool-path=/data/spool` because the spool path should always be local.
`tls-server-auth=pg1-srv=demo` means on pg2-srv, the pg1-srv host should be allowed to connect using TLS when using the stanza called demo.

My biggest question would be why you want to take backups from the primary and the standby. It will come to the same backup space ultimately and the retention policy will be enforced each time the backup command will be successful. So taking a successful backup from standby could expire a backup from the primary.

The configuration will really depend on your use-case (with or without a dedicated backup server,...). Basically the first step is to define where you want to store your backups and archives. **Just keep in mind that you should use the same backup space for primary and standby servers.** And once the stanza-create command succeeds, you should use the check command before using the backup command.

**Comment by jiangphcn** [comment]
Tons of thanks @pgstef for your quick response and detailed explanation. 

Regarding your question 
>My biggest question would be why you want to take backups from the primary and the standby. It will come to the same backup space ultimately and the retention policy will be enforced each time the backup command will be successful. So taking a successful backup from standby could expire a backup from the primary.

There is one restirction in our topology where there is No shared nfs among primary node and secondary nodes in PostgreSql cluster, and they are isolated. 

In order to reduce the impact of backup workload from primary node, we want to perform districuted backup workload every 8 hours, from primary node, to secondary node 1 to secondary node 2. Although there is duplicate copies in each node, it is trade-off. 


Does it also mean that ``` repo1-path=/mnt/backups ``` in https://pgstef.github.io/2020/09/04/combining_pgbackrest_and_streaming_replication.html needs to be shared?

May I ask whether there is way to support our current topology? Thanks again.

**Comment by jiangphcn** [comment]
Thanks again. Appreciate your help and response!

> What do you mean by isolated? The PG nodes can at least reach each other? (streaming replication connection + TLS connection)

I mean that storage for primary nodes and secondary nodes are isolated. The PG nodes can reach each other. 

> Hm, not sure why you would do that. Aren't you familiar with [PG continuous archiving](https://www.postgresql.org/docs/current/continuous-archiving.html)?
It's usually enough to take 1 backup per day and then rely on WAL archives for the point-in-time recovery. Having more frequent backups could indeed make the recovery faster but that's when you generate a very huge load of WAL files.
I often see 1 full backup per week and then 1 incr or diff backup per day.

i happen to know continous archiving. However, backup data can be only stored locally in our topology for now. Your suggestion quite makes sense in most scenario. 

> A way to have 1 repository for the primary and 1 repository for each standby servers? Theoretically, it could. But it would be very hard to configure/achieve and not very reliable. So that's definitely not recommended, even more since we have the multi-repo feature.

Can you share detail to make it happen? Thanks again.

**Comment by dwsteele** [comment]
> Can you share detail to make it happen? Thanks again.

This config is not recommended because it is very likely to end in data loss. Backups should be stored off the pg hosts. Period. We can't stop you from going down this path, but you are on your own.
