### ISSUE TITLE
how to setup with OCI buckets

### ISSUE THREAD

**Issue by sebastianwebber** [pgbackrest/pgbackrest#1725]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.38

2. PostgreSQL version: 9.3.4

3. Operating system/version: CEntOS 7.5

5. Did you install pgBackRest from source or from a package? Installed from rpm https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/pgbackrest-2.38-1.rhel7.x86_64.rpm
--

<br class="Apple-interchange-newline">

6. Please attach the following as applicable:
```ini
; /etc/pgbackrest/pgbackrest.conf
[producao]
pg1-path=/dados/pgdata
pg1-socket-path=/tmp
pg1-host-user=postgres


[global]
repo1-retention-full=10

repo1-type=s3
repo1-path=/var/lib/pgbackrest
repo1-s3-region=ca-montreal-1
repo1-s3-endpoint=ca-montreal-1.oraclecloud.com
repo1-s3-bucket=$bucket_name
repo1-s3-key=$access_key
repo1-s3-key-secret=$access_secret


log-level-file=detail
start-fast=y
process-max=4
log-level-console=info
stop-auto=y
```

7. Describe the issue:

I've tried the configuration above, but is not working:

```bash
[postgres@dbmaster ~]$ pgbackrest --stanza=producao check --log-level-console=info --io-timeout=10
2022-04-29 00:25:00.831 P00   INFO: check command begin 2.38: --exec-id=6536-f24c03fe --io-timeout=10 --log-level-console=info --log-level-file=detail --pg1-path=/dados/pgdata --pg1-socket-path=/tmp --repo1-path=/var/lib/pgbackrest --repo1-s3-bucket=bucket-name-redacted --repo1-s3-endpoint=ca-montreal-1.oraclecloud.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=ca-montreal-1 --repo1-type=s3 --stanza=producao
2022-04-29 00:25:01.356 P00   INFO: check repo1 configuration (primary)
ERROR: [049]: unable to load info file '/var/lib/pgbackrest/archive/producao/archive.info' or '/var/lib/pgbackrest/archive/producao/archive.info.copy':
       HostConnectError: unable to get address for 'bucket-name-redacted.ca-montreal-1.oraclecloud.com': [-2] Name or service not known
       HostConnectError: unable to get address for 'bucket-name-redacted.ca-montreal-1.oraclecloud.com': [-2] Name or service not known
       HINT: archive.info cannot be opened but is required to push/get WAL segments.
       HINT: is archive_command configured correctly in postgresql.conf?
       HINT: has a stanza-create been performed?
       HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
2022-04-29 00:26:22.683 P00   INFO: check command end: aborted with exception [049]
```

Acording to [OCI docs](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm#usingAPI):

```
4 . Use path-based access in your application. Virtual host-style access (accessing a bucket as bucketname.namespace.compat.objectstorage.region.oraclecloud.com) is not supported.
```

Then I've tried this configuration:

```ini
; ...
[global]
; ...
repo1-s3-endpoint=ca-montreal-1.oraclecloud.com
repo1-s3-bucket=$namespace.$compart.$bucket_name
; ...
```

And got a new error:

```bash
[postgres@dbmaster ~]$ pgbackrest --stanza=producao check --log-level-console=info --io-timeout=10
2022-04-29 00:33:55.477 P00   INFO: check command begin 2.38: --exec-id=9047-a62af938 --io-timeout=10 --log-level-console=info --log-level-file=detail --pg1-path=/dados/pgdata --pg1-socket-path=/tmp --repo1-path=/var/lib/pgbackrest --repo1-s3-bucket=namespace-oid.compart-name.bucket-name-redacted --repo1-s3-endpoint=ca-montreal-1.oraclecloud.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=ca-montreal-1 --repo1-type=s3 --stanza=producao
ERROR: [032]: 'namespace-oid.compart-name.bucket-name-redacted' is not valid for option 'repo1-s3-bucket'
       HINT: RFC-2818 forbids dots in wildcard matches.
       HINT: TLS/SSL verification cannot proceed with this bucket name.
       HINT: remove dots from the bucket name.
2022-04-29 00:33:55.477 P00   INFO: check command end: aborted with exception [032]
```

There is some work around to use OCI buckets?

**Comment by pgstef** [comment]
Hi,

I never tried that specific provider but usually S3 clones require [path-style URIs](https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-uri-style). Could you try with `repo1-s3-uri-style=path`?

Also, you'd probably want to change `repo1-path` to something shorter like `repo1-path=/repo1` (that will be the path inside your bucket).

Before triggering the `check` command (and setting the PG `archive_command`), have you performed `stanza-create`?

**Comment by dwsteele** [comment]
The problem is the bucket name `namespace-oid.compart-name.bucket-name-redacted`. RFC-2818 forbids dots in wildcard matches. In other words, if the server certificate gives the host name as `*.myserver.com` then a valid match is `test1.myserver.com` but not `test1.test2.myserver.com`.

PostgreSQL also forbids this (which is why we do) but a lot of TLS implementations are more lax about it.

Does OCI require these extra dots or is it something your org added?

**Comment by sebastianwebber** [comment]
> I never tried that specific provider but usually S3 clones require [path-style URIs](https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-uri-style). Could you try with `repo1-s3-uri-style=path`?

Checking OCI docs i've figured out that the endpoint is different. These is all changes that I've done:

```ini
; ...
[global]
; ...
repo1-path=/pgbackrest
repo1-s3-uri-style=path
repo1-s3-region=ca-montreal-1
repo1-s3-endpoint=https://$namespace_id.compat.objectstorage.ca-montreal-1.oraclecloud.com
repo1-s3-bucket=$bucket_name
repo1-s3-key=$access_key
repo1-s3-key-secret=$access_secret
; ...
```
The main changes were the `endpoint` and the `uri-style`. Please note that the endpoint URL is composed by the region.

> Before triggering the check command (and setting the PG archive_command), have you performed stanza-create?

Yes, i've forgot to run it before.

Now is working!

Hoping that this can help others to use pgbackrest in OCI.

**Comment by dwsteele** [comment]
Thank you for replying with your solution! I'm sure it will be a help to future OCI users.
