### ISSUE TITLE
using a netscaler

### ISSUE THREAD

**Issue by ikzelf** [pgbackrest/pgbackrest#1727]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.36

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: rhel8

4. Did you install pgBackRest from source or from a package? package (crunchy)

7. Describe the issue:

works as a charm with a single backup server. For HA we created simple cluster where a netscaler devides the load over available backup servers. The backup servers share the config and the repositories and are addressed in a round robin method by the netscaler.

The problem when running a backup: ERROR: [082]: WAL segment 0000005000000004000000F7 was not archived before the 60000ms timeout

I think that the backup server initiates a log switch in the database and despite the fact that the WAL segment lands in a shared location the pgbackrest backup command is unable to recognise the reception of the WAL segment. The archive command does succeed without problems, sub second.

What can I do to make this work?

**Comment by dwsteele** [comment]
This seems like it should work. Can you confirm that all the repo hosts are sharing repository storage?

**Comment by ikzelf** [comment]
Thanks for your response David.....
You are right, it works. I missed a configuration line in a database specific config in conf.d/ Sorry about the fuzz, I am happy to see this working as designed. Great job!

**Comment by ikzelf** [comment]
thanks, next is to get the scripting and scheduling such that the backup load is also a bit balanced. All nodes start from their crontab at the same moment. For this I want to use the 
**ERROR: [056]: unable to find primary cluster - cannot proceed
HINT: is another pgBackRest process running?**
message. If that is returned, or there is already a completed backup of this stanza created since the start of the script, skip this one and pick the next stanza.
Monitoring will make sure all stanza get their turn. At least, report when that is not happening.
