### ISSUE TITLE
how can I be sure Stanza works properly?

### ISSUE THREAD

**Issue by tirelibirefe** [pgbackrest/pgbackrest#1728]
Hello,
I've a postgres cluster which was installed by using pgo 5.0.4 on EKS Kubernetes. Nowadays I do a number of tests on it. 
When I describe the postgres cluster which was restored from backup / S3 reports that:

```
  Normal   StanzasCreated         42m   postgrescluster-controller  pgBackRest stanza creation completed successfully
  Warning  UnableToCreateStanzas  42m   postgrescluster-controller  command terminated with exit code 50: ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/db-backup.lock': Resource temporarily unavailable   
       HINT: is another pgBackRest process running?
```

When I look at other details on describtion page and logs, I cannot see any problems. Also I tried to take backup and it worked.

How can I be sure "Stanza" works properly or not?

Thanks & Regrads

**Comment by dwsteele** [comment]
I think you would rather ask this question over at https://github.com/CrunchyData/postgres-operator.
