### ISSUE TITLE
is it possible to not use softlinks to latest?

### ISSUE THREAD

**Issue by spictera** [pgbackrest/pgbackrest#1737]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Our filesystem is a WORM based filesystem (Write Once Read Many).
The softlinks that are created at end of pgbackrest that are pointing to "latest" encounter some trouble for us.
There are no way in posix to update a softlink with new pointer, so the only way is to first remove the old softlink, and create a new softlink.
The filesystem can be configured to allow removals, but it will not than lower the protection, as we can not protect against "ransomware", hence the reason for our questions.

Is it possible to skip the creation of the "softlinks" to latest?
What will be the impact if this softlink does not exist?

**Comment by dwsteele** [comment]
> Is it possible to skip the creation of the "softlinks" to latest?

This is not currently possible when `repo-type=posix`. We expect Posix filesystems to act like Posix filesystems.

> What will be the impact if this softlink does not exist?

pgBackRest does not use this link since most storage drivers do not support symlinks. It exists primarily for user convenience (and there is a lot of history behind it).

In the next (more write-only friendly) repo format we are planning to disable it by default, but they option does not exist yet.

**Comment by dwsteele** [comment]
We have a project card for this (https://github.com/pgbackrest/pgbackrest/projects/8#card-69895306) so closing.
