### ISSUE TITLE
Scality RING 8.5.3 & pgBackrest => does not work

### ISSUE THREAD

**Issue by MonChr** [pgbackrest/pgbackrest#1748]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.38

2. PostgreSQL version:
11.15

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Red Hat Enterprise Linux Server release 7.9

4. Did you install pgBackRest from source or from a package?
From package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
repo1-retention-full=7
repo1-retention-diff=1
repo1-retention-archive-type=full
repo1-retention-full-type=time
repo1-retention-history=1
repo1-type=s3
repo1-s3-uri-style=path
repo1-path=/pgbackrest_test1
repo1-s3-bucket=pgbckrest-tst-bkt-01
repo1-s3-endpoint=xxxxxxxxxxxxxx
repo1-s3-key=xxxxxxxxxxxxxxxxxxxxxxxxx
repo1-s3-key-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
repo1-s3-region=eu-west-3
repo1-s3-verify-tls=n
[pgcluster]
pg1-path=/xxxxxxxxxxxxx/data
pg1-port=5433
pg1-host-user=postgres

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_command = 'pgbackrest --stanza=pgcluster --config=/etc/pgbackrest.conf archive-push %p'
archive_mode = on
listen_addresses = '*'
max_wal_senders = 10
wal_level = replica
port = 5433

    - errors in the postgresql log file before or during the time you experienced the issue
no mistake in log postgresql
the process is just frozen :    
  postgres  89467  47376  1 15:07 ?        00:00:14 pgbackrest --stanza=pgcluster --config=/etc/pgbackrest.conf archive-push pg_wal/000000050000000100000097
pgbackrest --stanza=pgcluster --log-level-file=trace backup
pgbackrest --stanza=pgcluster --log-level-file=trace info

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
attached log (zip) for backup & info command (I had to stop the process)

7. Describe the issue:
Previously, pgBackRest version 2.18 worked with Scality Ring version 8.4
Following the update to 8.5.3, the pbBackRest processes are frozen.
We are also using Barman v19, which continues to work well (with the same account & user), it's also ok with S3browser or aws cli.
What could be the root cause ?
What possible solution do we have available ?
[pgcluster-info.zip](https://github.com/pgbackrest/pgbackrest/files/8679590/pgcluster-info.zip)
[pgcluster-backup.zip](https://github.com/pgbackrest/pgbackrest/files/8679594/pgcluster-backup.zip)

**Comment by MonChr** [comment]
Thank you very much for your feedback, we will question Scality on our side as well.

**Comment by MonChr** [comment]
Hi,
We have opened an incident at Scality (incident #17304).

**Comment by MonChr** [comment]
Here is Scality's answer (I took the liberty of forwarding your answer) :
I tried to compile that stuff with no success, and try to reproduce using a simple s3 client (like) 
 
import logging
import boto3
from botocore.exceptions import ClientError
from botocore.config import Config

import os
#boto3.set_stream_logger('')
config=Config(s3={'addressing_style': 'path'})
s3 = boto3.client("s3","eu-west-2",None,False,None,"http://10.200.5.2/",'VQ8FABCXXZ6X9AILVL3F','9i4EUhCMJe44RBqwZ3VsdZLR2haVyGXmnI+=HwaR95',None,config)
keys = []
kwargs = {'Bucket': "fra-normal","MaxKeys":1}
while True:
    resp = s3.list_objects_v2(**kwargs)
    for obj in resp['Contents']:
        print("KEY IS ", obj['Key'] , " --  TOKEN IS " ,  resp['NextContinuationToken'] )
        try:
            kwargs['ContinuationToken'] = resp['NextContinuationToken']
        except KeyError:
            break
    if not resp['NextContinuationToken']:
      print("EMPTY token, EXIT ")
      break

This should be a client request, and it is passing an empty continuation-token - which I do not know exactly what is the meaning -  but in any case it will not loop.

After reading David Steele's response about NextContinuationToken, I'm wondering if he does listings right. I need confirmation from our development team, but an S3 client sending ListObjects, V1 or V2, should use the IsTruncated field to break the listing loop, instead of checking NextContinuationToken 's presence, [like pgbackrest does](https://github.com/pgbackrest/pgbackrest/blob/19dd015d589ed3efd31a2a238249a150fb3748c1/src/storage/s3/storage.c#L690).
 
In order to respond to the critical situation you are facing, I suggest that my team temporarily patches your S3 cluster to not send an empty NextContinuationTokenfield when IsTruncated is false. This action would not make Scality liable regarding the S3 protocol misunderstanding between us and pgbackrest.
 
Grégoire Doumergue
Scality | EMEA Support Manager

**Comment by dwsteele** [comment]
> In order to respond to the critical situation you are facing, I suggest that my team temporarily patches your S3 cluster to not send an empty NextContinuationTokenfield when IsTruncated is false.

This is seems like the better (at least short-term) solution since it appears to be a change in server behavior causing the issue.

> but an S3 client sending ListObjects, V1 or V2, should use the IsTruncated field to break the listing loop, instead of checking NextContinuationToken 's presence

That sounds reasonable, but I still interpret `NextContinuationToken is sent when isTruncated is true` to mean `NextContinuationToken` will not be included in the response when `IsTruncated` is false. Sending an empty `NextContinuationToken` (which makes it invalid) just seems like a bad idea.

However, we'll look at switching over to `IsTruncated` since this is what `boto3` appears to do.

> We have opened an incident at Scality (incident #17304).

Is it possible to get a link to this issue, if not something internal?

**Comment by dwsteele** [comment]
> Previously, pgBackRest version 2.18 worked with Scality Ring version 8.4

Is this a typo or did you also upgrade from pgbackrest `2.18`? I don't think the behavior has changed on our side, but would be good to clarify.

**Comment by MonChr** [comment]
Hello,
We were already on version 2.18 of pgBackRest and it worked with Scality 8.4
To access the support, you need an account (user + password). We only have one business account, sorry.

**Comment by MonChr** [comment]
avez-vous eut un retour de la part du support Scality  ?

**Comment by MonChr** [comment]
oops, I'm sorry, it is pgBackRest version 2.38 (it's a typo)

**Comment by MonChr** [comment]
![Capture](https://user-images.githubusercontent.com/36842812/168601387-15f787d5-93d5-45ae-a7ec-084794e37473.jpg)

**Comment by MonChr** [comment]
did you get any feedback from Scality support?

**Comment by dwsteele** [comment]
> did you get any feedback from Scality support?

No, not directly. They are welcome to comment on this issue if they have feedback.

**Comment by MonChr** [comment]
> One thing to note is that AWS S3 _does_ omit `NextContinuationToken` when `IsTruncated` is false. So does MinIO and every other S3 clone we have encountered to date.

I hope that Scality will study this indication.

> Whether we change the behavior of pgBackRest or not, it seems sensible for Scality to revert this change that seems to have occurred after 8.4.

We have still not had any feedback on the objective of this development in the new version.

Thank you again for your feedback.

**Comment by MonChr** [comment]
We have not heard back on the changes, specific to our problem, between v8.4 and v8.5.3.
Do you plan to integrate an evolution (switch to IsTruncated) to be compatible with Scability S3?

**Comment by sfrost** [comment]
We've added a card for this: https://github.com/pgbackrest/pgbackrest/projects/2#card-82856359

As it's in planned, it's likely that we'll get to it relatively soon but we can't make any explicit guarantees as to when it'll be in a released version.

**Comment by dwsteele** [comment]
@MonChr This has been implemented in PR #1783. We recommend you test this patch against the affected version of Scality.
