### ISSUE TITLE
full recovery of database ->> --delta option?

### ISSUE THREAD

**Issue by ikzelf** [pgbackrest/pgbackrest#1752]
I have data files and wal files on separate devices.
For some reason some or all datafiles get lost and the wal files remain.

If this is the case I can recover without loss of transactions, what would be very welcome.
When pgbackrest deletes the wal files, the last transactions - that are not yet archived - would be lost.

Is it safe to assume that I can recover the database until end of thread when using --delta?

**Comment by pgstef** [comment]
Hi,

I don't think it will be that simple.

First of all, I guess since you have the pg_wal directory separated, you plan to use the [link-all](https://pgbackrest.org/configuration.html#section-restore/option-link-all) option ?

In theory, your last transactions will indeed be stored into the unarchived wal segments located in pg_wal. And in recovery mode, PG will first look inside its pg_wal directory before triggering the restore_command to fetch a missing local wal from the archives.

Afaict, after the restore command (using delta or not) the pg_wal directory will be empty. So you'd better save the content of your pg_wal directory **before** attempting the restore. And after the restore command, just copy back your unarchived wal segments into the pg_wal directory (and pay attention to the ownership and permissions) before starting your PG server.

**Comment by ikzelf** [comment]
yes, also using link-all.
From my oracle experience, we never even backup and certainly don't restore the online redo logfiles because they could contain the last transactions before the crash that are not yet archived. It would be good it pgbackrest has a clear policy for handling this. When the last transactions are recovered they will also be archived making them safe. Maybe we just need a option like --crash-recovery to handle this? That would be usable to make sure we can restore every committed transaction for which we still have the wal.

**Comment by pgstef** [comment]
> It would be good it pgbackrest has a clear policy for handling this

The policy is pretty clear to me. It follows the **PostgreSQL** recommendation to have a clean pg_wal directory: https://www.postgresql.org/docs/current/continuous-archiving.html#BACKUP-PITR-RECOVERY

> Remove any files present in pg_wal/; these came from the file system backup and are therefore probably obsolete rather than current.

> If you have unarchived WAL segment files that you saved in step 2, copy them into pg_wal/. (It is best to copy them, not move them, so you still have the unmodified files if a problem occurs and you have to start over.)

The content of pg_wal and pg_wal/archive_status could mess up the recovery. And with archive-push we're checking that the wal archives match the PG cluster for the requested stanza. We couldn't verify this for the existing pg_wal directory at restore time.

Imo, the restore preparation steps should be left to the users, not the tool. Ultimately, it's just saving the unarchived wal files and copying them back after the restore command. Though, I agree we should mention/state it clearly somewhere so the users actually know they have to care about that.

Perhaps @dwsteele will have another view on this and have an idea to preserve the unarchived wal segments at restore time...

**Comment by dwsteele** [comment]
It is not a great idea to mix WAL from a failed cluster with what is required for recovery. First, earlier WAL required may be have been recycled. Second, there is no guarantee that the existing WAL is on the same timeline or that there wasn't some kind of split brain that makes the WAL unusable. 

You can certainly do this manually if you are sure you have the right WAL, but it is generally better to let Postgres recover as far as it can from archive and then inject the additional WAL that you want afterwards.

There are so many gotchas here that I'm not sure if this is something we can or should automate. Certainly we have no plans in that direction.

One thing we have considered is adding a command to pgbackrest to push unarchived WAL in a shutdown cluster, see https://github.com/pgbackrest/pgbackrest/projects/2#card-75422224. This might do what you need, and it would be safer.

**Comment by sfrost** [comment]
Note that on a clean shutdown this isn't needed as PG will push out the end of the WAL as part of shutdown.

Allowing pgbackrest to push WAL when a PG instance has crashed, for whatever reason, is a possibility as discussed.  There are certain risks to doing so though, just to be clear.  If you're really worried about this, you'd be much better off having a streaming replica (synchronous if that's required, along with multiple of them to avoid having a SPOF).  Trying to hack this kind of "never lose any transactions" using only a single system is going to end up not working out reliably in the long run (if you can end up losing some of the data files from the one system that has them, you're bound to lose some of the WAL from that system at some point, in which case you're still losing transactions in the event of a crash).  I'd strongly recommend you just accept that you need replication to address this (of course, you should *also* be doing backups regularly, and WAL archiving...).

**Comment by dwsteele** [comment]
We have a project card for offline WAL cleanup (https://github.com/pgbackrest/pgbackrest/projects/2#card-38886528), so closing this issue.
