### ISSUE TITLE
Backing up on Standby, replication handled by repmgr, pgbackrest.conf parameters.

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#1755]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.37 and 2.38
2. PostgreSQL version:
12,13 and 14

4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS 7 and Ubuntu Bionic and Debian Buster

6. Did you install pgBackRest from source or from a package?
Package

8. Please attach the following as applicable:
pgbackrest.conf : 
[global]
repo1-path=/var/lib/pgbackrest
log-level-console=info
log-level-file=info
start-fast=y
process-max=5
repo1-retention-full=4
repo1-s3-bucket=tester
repo1-s3-endpoint=InternalS3
repo1-s3-port=1234
repo1-s3-uri-style=path
repo1-s3-key=xxxxxxxxxxxxyyyyyyyyyzzzzzzzzzzz
repo1-s3-key-secret=123456789
repo1-s3-region=FR
repo1-type=s3
repo1-s3-verify-tls=y

[stanley]
pg1-path=/data/12

postgresql.conf : 
archive_mode=on
archive_command = 'pgbackrest --stanza=stanley  archive-push %p'
listen_addresses='*'
max_wal_senders=10
wal_level='replica'

10. Describe the issue:
We would like to backup on the standby since we have performance issues when doing the backup on the primary.
We use repmgr for management of replication.
Standby has already been created, we do not want to have to re-create the standby (5T db).

I presume repmgr user could be used, without impact. We also normally have the same postgresql.conf and pgbackrest.conf on primary and standby, I presume having the following parameters in the pgbackrest.conf of the primary would not be an issue?
backup-standby=y
delta=y
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=123.123.123.1 user=repmgr
recovery-option=recovery_target_timeline=latest
If not some clarification would be appreciated, especially if there is a switchover/failover.

We will of course test this before using in production, but having these answers would help gain some time.
Thank you in advance.

**Comment by pgstef** [comment]
> backup-standby=y

Afaik, this option won't prevent the backup to run on the primary. If you execute the backup on the primary, it will just fetch the data from the standby. So it all depends on how you trigger your backups. If you only trigger backups from the actual standby, it shouldn't be an issue.

Also, to take a backup from a standby server, you'll need to set up pg2-* options: https://pgbackrest.org/user-guide.html#standby-backup. It's an hybrid situation where the backup control session will be executed on the primary (pg_start/stop_backup,...) but the data will be copied from the standby. So the standby pgbackrest process must be able to connect to the primary.

It's just a question of configuration and backup trigger, but at the end, I don't see why it wouldn't work with repmgr given it works with simple streaming replication.

Kind regards
