### ISSUE TITLE
Pgbackrest fails to archive to S3 repo

### ISSUE THREAD

**Issue by Kamal-Villupuram** [pgbackrest/pgbackrest#1762]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.39

2. PostgreSQL version: 12.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7

4. Did you install pgBackRest from source or from a package? Source 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[pgbackrest_fail_archive_S3repo.txt](https://github.com/pgbackrest/pgbackrest/files/8797964/pgbackrest_fail_archive_S3repo.txt)

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by Kamal-Villupuram** [comment]
pgbackrest installed from source bundle and postgres also run on the same server. I configured repo to S3 bucket and stanza-created successfully. 

But stanza-checks fails with 

[postgres@sl73pgpocdbd032 ~]$ pgbackrest --stanza=pgpoc backup  --config=/pgtool/pgbackrest/conf.d/pgbackrest.conf --log-path=/pgerror/pgpoc/pgbackrest --repo=1
WARN: no prior backup exists, incr backup has been changed to full
ERROR: [082]: WAL segment 00000008000000070000001C was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
[postgres@sl73pgpocdbd032 ~]$ pgbackrest --stanza=pgpoc check --config=/pgtool/pgbackrest/conf.d/pgbackrest.conf --log-level-console=info
2022-05-30 08:43:53.121 P00   INFO: check command begin 2.39: --config=/pgtool/pgbackrest/conf.d/pgbackrest.conf --exec-id=4187398-9aa7dc39 --log-level-console=info --pg1-path=/pgdata/pgpoc/12.x/data --repo1-path=/pgpoc --repo1-s3-bucket=pgbackrest --repo1-s3-endpoint=1xx.xx.xx.xx --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=US --repo1-s3-uri-style=path --repo1-storage-port=9021 --repo1-type=s3 --stanza=pgpoc
2022-05-30 08:43:53.725 P00   INFO: check repo1 configuration (primary)
2022-05-30 08:43:54.072 P00   INFO: check repo1 archive for WAL (primary)

**Comment by sridhar1270** [comment]
Team,
Am getting the same error , stanza creation was successful but check and backup is failing with similar as mentioned above pgbackrest version is 2.37.
INFO: check repo1 configuration (primary)
INFO: check repo1 archive for WAL (primary)
ERROR: [082]: WAL segment 000000010000000000000008 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
INFO: check command end: aborted with exception [082]

**Comment by dwsteele** [comment]
It looks like a configuration error -- perhaps you are checking the wrong repo? But impossible to tell since you did not provide the info that is requested in a new issue.

Please don't reply to old issues. Open a new issue and provide all information requested.

**Comment by sridhar1270** [comment]
Thank you dwsteele will raise an new issue with all info
