### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by SzhiH** [pgbackrest/pgbackrest#1779]
Hello I ran the incremental and full backup tasks respectively, why is the output result a full amount and the rest are all incremental?

stanza: main
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1): 0000000B0000000900000027/0000000B0000000900000031

        full backup: 20220610-130014F
            timestamp start/stop: 2022-06-10 13:00:14 / 2022-06-10 13:00:23
            wal start/stop: 0000000B0000000900000027 / 0000000B0000000900000027
            database size: 31.2MB, backup size: 31.2MB
            repository size: 3.7MB, repository backup size: 3.7MB

        incr backup: 20220610-130014F_20220610-170017I
            timestamp start/stop: 2022-06-10 17:00:17 / 2022-06-10 17:00:20
            wal start/stop: 0000000B0000000900000029 / 0000000B0000000900000029
            database size: 31.2MB, backup size: 8.3KB
            repository size: 3.7MB, repository backup size: 505B
            backup reference list: 20220610-130014F

        incr backup: 20220610-130014F_20220611-130018I
            timestamp start/stop: 2022-06-11 13:00:18 / 2022-06-11 13:00:21
            wal start/stop: 0000000B000000090000002B / 0000000B000000090000002B
            database size: 31.2MB, backup size: 8.3KB
            repository size: 3.7MB, repository backup size: 437B
            backup reference list: 20220610-130014F, 20220610-130014F_20220610-170017I

        incr backup: 20220610-130014F_20220611-170006I
            timestamp start/stop: 2022-06-11 17:00:06 / 2022-06-11 17:00:11
            wal start/stop: 0000000B000000090000002D / 0000000B000000090000002D
            database size: 31.2MB, backup size: 8.3KB
            repository size: 3.7MB, repository backup size: 506B
            backup reference list: 20220610-130014F

        incr backup: 20220610-130014F_20220612-130012I
            timestamp start/stop: 2022-06-12 13:00:12 / 2022-06-12 13:00:15
            wal start/stop: 0000000B000000090000002F / 0000000B000000090000002F
            database size: 31.2MB, backup size: 8.3KB
            repository size: 3.7MB, repository backup size: 437B
            backup reference list: 20220610-130014F, 20220610-130014F_20220611-170006I

        incr backup: 20220610-130014F_20220612-170013I
            timestamp start/stop: 2022-06-12 17:00:13 / 2022-06-12 17:00:16
            wal start/stop: 0000000B0000000900000031 / 0000000B0000000900000031
            database size: 31.2MB, backup size: 8.3KB
            repository size: 3.7MB, repository backup size: 504B
            backup reference list: 20220610-130014F

**Comment by jreidthompson** [comment]
An incremental requires a full in its history. If you invoke incremental without a prior full in its history it recognizes that and performs the required full backup. Subsequent incremental invocations will perform an incremental backup.

**Comment by SzhiH** [comment]
ok，thank you
