### ISSUE TITLE
patroni and pgbackrest

### ISSUE THREAD

**Issue by SzhiH** [pgbackrest/pgbackrest#1780]
Hello, my cluster is built by using Patroni in k8s. In this case, I used pgbackrest to backup successfully. I think it is necessary to stop PostgreSQL for recovery, but if Patroni is stopped, the service will be restarted. If Patroni is stopped, the container will restart again. How can I recover this situation? Please answer. Thank you

**Comment by pgstef** [comment]
Hi,

I'm not using k8s so I'm not sure it will work (and you might probably better seek help with the Patroni team who should know more about this) but probably [Patroni Pause/Resume mode](https://patroni.readthedocs.io/en/latest/pause.html) is what you're looking for.

> Under certain circumstances Patroni needs to temporary step down from managing the cluster, while still retaining the cluster state in DCS. Possible use cases are uncommon activities on the cluster, such as major version upgrades or corruption recovery. During those activities nodes are often started and stopped for the reason unknown to Patroni, some nodes can be even temporary promoted, violating the assumption of running only one master. Therefore, Patroni needs to be able to “detach” from the running cluster, implementing an equivalent of the maintenance mode in Pacemaker.

Regards
