### ISSUE TITLE
v2.32 with --db-include lead to PANIC:  WAL contains references to invalid pages

### ISSUE THREAD

**Issue by fluca1978** [pgbackrest/pgbackrest#1782]
This is something that happened to me with a pgbackrest 2.32 (I know it's old, but it is out of my control) on ubuntu machines running PostgreSQL 9.6 (again, out of my control).

During a restore with a particular database:
```
% pgbackrest --stanza miguel  --pg1-path /restore --db-include db425 --type=time --target='2022-05-30 12:00:00' restore --log-level-console info
...
 P00   INFO: archive-get command begin 2.32: [000000010000010D000000C2, pg_xlog/RECOVERYXLOG] --exec-id=26726-a716aabd --log-level-console=info --pg1-path=/restore --repo1-host=carmensita --repo1-host-user=pgbackrest --repo1-path=/backup/pgbackrest --stanza=miguel
 P00   INFO: found 000000010000010D000000C2 in the repo1:9.6-1 archive
 P00   INFO: archive-get command end: completed successfully (1225ms)
 LOG:  restored log file "000000010000010D000000C2" from archive
 WARNING:  page 4 of relation base/16397/760179 is uninitialized
 CONTEXT:  xlog redo at 10D/C217B7B8 for Heap2/VISIBLE: cutoff xid 976931717 flags 1
 PANIC:  WAL contains references to invalid pages
 CONTEXT:  xlog redo at 10D/C217B7B8 for Heap2/VISIBLE: cutoff xid 976931717 flags 1
 LOG:  startup process (PID 26432) was terminated by signal 6: Aborted
 LOG:  terminating any other active server processes
 LOG:  database system is shut down
```

I tried a few times, same issue.
Then I tried to restore without `--db-include` and it worked absolutely well.

Therefore, if this is a bug related to the old version, forgive me for the noise.
Otherwise, is there something I should be worried about my backup repository?

**Comment by pgstef** [comment]
Hi,

First of all, the good news is that the complete restore works. So it seems limited to the selective restore only.

Not sure it would be related but `16397` sounds like a system db to me and we had some [improvements](https://github.com/pgbackrest/pgbackrest/commit/6942ff569dd950a5146faa0bebfee69e241c4179) in this area after 2.32. It would then definitely worth trying with the latest pgBR release.

A "DETAIL" log level from the restore might also show you the dbs selected for the restore. Example:
```
P00 DETAIL: databases found for selective restore (...)
```

It might then be a good idea to identify which is this `16397` database (from the backup manifest or using the info command) and include it too if needed in your restore command.

Kind Regards

**Comment by dwsteele** [comment]
This can happen if you use a recovery type other than `immediate`. See https://pgbackrest.org/user-guide.html#restore/option-db-include:
```
WARNING: Recovery may error unless --type=immediate is specified. This is because after consistency is reached PostgreSQL will flag zeroed pages as errors even for a full-page write. For PostgreSQL ≥ 13 the ignore_invalid_pages setting may be used to ignore invalid pages. In this case it is important to check the logs after recovery to ensure that no invalid pages were reported in the selected databases. 
```
