### ISSUE TITLE
pgbackrest is working very well but number of wal files increasing

### ISSUE THREAD

**Issue by msuluhan** [pgbackrest/pgbackrest#1787]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.39

2. PostgreSQL version: 12.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04.4 LTS

4. Did you install pgBackRest from source or from a package?   from Ubuntu repo

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
  ---> master server's pgbackrest.conf
[global]
repo1-path=/mnt/db_backup/pgbackrest
repo1-retention-diff=18
repo1-retention-full=3
log-level-console=info
log-level-file=debug
start-fast=y
process-max=5
compress-level=9

[postgres]
pg1-path=/data/postgresql/12/main
 
---> standby server's pgbackrest.conf
[global]
repo1-path=/mnt/db_backup/pgbackrest
repo1-retention-diff=18
repo1-retention-full=3
log-level-console=info
log-level-file=debug
start-fast=y
process-max=5
compress-level=9

[postgres]
pg1-path=/data/postgresql/12/main
recovery-option=primary_conninfo=host=192.168.30.216 user=replicator
recovery-option=primary_slot_name=slot1

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

```
egrep -e 'archive_command|archive_mode|wal_level|port|listen_address|max_wal_senders' postgresql.conf  | grep -v "^#"
listen_addresses = '*'
port = 5432				# (change requires restart)
					# supported by the operating system:
					# supported by the operating system:
wal_level = replica			# minimal, replica, or logical
					# supported by the operating system:
archive_mode = on		# enables archiving; off, on, or always
archive_command = 'pgbackrest --stanza=postgres archive-push %p'
					#   %r = remote host and port

```
so max_wal_senders is 10 by default

    - errors in the postgresql log file before or during the time you experienced the issue (no error)
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I have migrated customer's backup/recovery-replication solution from barman to pgbackrest. Customer is using master/standby solution

--> Taking backups are ok 
--> pgbackrest using NFS disk as repository and both server's pgbackrest uses same repo without any problem
--> backup from master and recovering to standby also worked 
--> Replication is working very well, I am also manually tested it's very fast.
--> I could see following lines in ps output and values are changing  time to time
          postgres: 12/main: walreceiver   streaming 7CD/BC2BE970
          postgres: 12/main: startup   recovering 00000001000007CD000000BC

On master server replication slots as follows, I have created slot1 and slot2
```
 slot_name | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn  | confirmed_flush_lsn 
-----------+--------+-----------+--------+----------+-----------+--------+------------+------+--------------+--------------+---------------------
 slot2     |        | physical  |        |          | f         | f      |            |      |              |              | 
 slot1     |        | physical  |        |          | f         | f      |            |      |              |              | 
 barman    |        | physical  |        |          | f         | f      |            |      |              | 7CB/F9000000 | 

```

I have used primary_slot_name information in standby's pgbackrest configuration (both slot1 and 'slot1') and restarted postgresql after change 
There is no slot_name data in pg_stat_wal_receiver output 

**The problem is number of pg_wal files are increasing continously** 

Thanks
msuluhan

**Comment by dwsteele** [comment]
You have three inactive replication slots. If the replication slots are not active postgres will keep WAL forever waiting for a slot to request it. Please see the postgres documentation on replication slots for more information.

**Comment by dwsteele** [comment]
I still see inactive slots there. This does not appear to be a pgbackrest issue, so there's nothing we can do here. Please refer to the postgres documentation on slots for help.

**Comment by valterartur** [comment]
Hi @dwsteele I have the similar problem but with accumulating snapshot files in postgres/pg_logical/snapshots directory:
```
stolon@postgres-keeper-0:/stolon-data/postgres$ ls -l pg_logical/snapshots/ | wc -l
279240
```
I guess it's wrong behavior. 

I have also connected replication slots, all of them are active and created by debezium. 
```
postgres=# select * from pg_replication_slots;
     slot_name      |  plugin  | slot_type | datoid | database  | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn | wal_status | safe_wal_size 
--------------------+----------+-----------+--------+-----------+-----------+--------+------------+------+--------------+-------------+---------------------+------------+---------------
slot1               | wal2json | logical   |  34117 | db1       | f         | t      |        221 |      |     24334289 | 1B/1F52F6E0 | 1B/785836E0         | reserved   |              
slot2               | wal2json | logical   |  87466 | db2       | f         | t      |        256 |      |     17843578 | 19/F5DA22A8 | 19/F5E4F468         | reserved   |              
slot3               | wal2json | logical   |  99270 | db3       | f         | t      |        225 |      |     16267374 | 18/E5B17B30 | 18/E5B99E48         | reserved   |              
```

Can you please advice if it can be related to replication slots as well?

**Comment by dwsteele** [comment]
@valterartur This does not appear to be a pgbackrest issue. Please refer to the Postgres documentation on slots or contact the Postgres community for help.
