### ISSUE TITLE
 pgbackrest Problems collecting all wals and sending confirmation to postgres (database at least 110TB)

### ISSUE THREAD

**Issue by mazocollo** [pgbackrest/pgbackrest#1791]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.39

2. PostgreSQL version: 13.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Oracle Linux Server 7.9

4. Did you install pgBackRest from source or from a package? Package on pgdg-common

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

postgresql.conf
	archive_command: pgbackrest --stanza=prod_backup archive-push /var/lib/pgsql/13/data/%p
	archive_mode: 'on'
	listen_addresses='*'
	max_wal_senders: 10
	wal_level: replica
	port:5432

pgbackrest.conf

[global]
repo1-host=repo01
repo1-host-user=postgres
repo1-path=/backups/pgsql_lc/pgbackrest
process-max=10
start-fast=y
compress-level=1
archive-async=y
spool-path=/var/spool/pgbackrest
log-path=/var/log/pgbackrest/
log-level-file=info
log-level-stderr=error
log-level-console=error

[prod_backup]
pg1-path=/var/lib/pgsql/13/data

[global:archive-push]
process-max=10
compress-level=1

7. Describe the issue:

Hi

My question:

I have a Postgresql cluster that currently stores 110TB of data. As the database in question is very large for security we store 24h of wal file inside pg_wal and from time to time we delete these wals (after they have already been applied to the replica), we know that this is not the best way to managements the wals, but as the load on this database is very large, for now this was the only alternative found to have some security.

Here is some information about our pg_wal

Current status of the database
• Current base size – 110TB
• Current size of pg_wal – 7.78TB
• Retention of wal files – 24h
• Average wal files per minute - 622
• Average number of wal files per day – 33,024
• Total wal files inside pg_wal (not considering archive_status) – 518,689

To make a full backup via pgbackrest, we have the need to bring the entire range of wals necessary to make the backup consistent, the problem is that both the synchronous and asynchronous approach of pgbackrest find situations that cause us to slow down and consequently hinder us a lot and they seem to make backing up the base unfeasible, but I want to point out that the problem is not pgbackrest, it seems to be more the current settings and the size of our base.

First Approach used to collect wal files - Synchronous
• A thread to collect a wal file and send an “OK” informing postgres that that thread has been archived (.ready to .done).

Problems:
	Speed ​​of collecting wals much slower than generating wals
	Inconsistent full backup due to lack of wals
	Slowness due to using a thread to collect several files, in addition to confirmation to postgres to end the collection process.

Second Approach used to collect wal files – Asynchronous
• Configuration set to 10 threads to collect the available wals, the parallelized wals collection gave us a lot of agility, but in the postgres confirmation step, only one thread informs that that segment was archived (.ready to .done) which ends up taking time, even if the confirmation of each file takes 0ms, 1ms and 5ms (maximum) the amount is so large that it ends up taking a long time to finish confirming everything that was collected.

o Problems:
	Very good fetching speed, but slow postgres archiving speed
	Inconsistent full backup due to lack of wals

Example scenario:
Using 10 threads and an asynchronous approach we collected in 2h a total of 100 thousand wal files, but it took many more than 2 hours for postgres to confirm the archiving of the 100 thousand segments collected in the first execution, with that, the next execution that should be faster ended up with more accumulated wals and the agility we had in the collection ended up being inefficient.

What we thought to solve the problem:
We thought of reducing the retention of wals from 24h to 1h or less, so there would be less files to collect and less confirmation time which can help us solve the problem, but before proceeding with this action or any other that appears, we We would like to know if you know of any alternatives and have any suggestions to give us, would it be possible to evaluate our case within your availability?

**Comment by mazocollo** [comment]
Well, I know that this is not the best way to manage things within Postgres, but the load we have is extremely high and sometimes the archive_command cannot keep up with the entire load of wals and in many situations it just stops working.

To protect us from bursting the filesystem, we configure a cleanup in the crontab that will delete wals that have already been applied to the replica, the current retention keeps 24h of wals, it could be smaller because the application of wals to the replica is always fast, but for safety this amount everything is stored.

There is no configuration in Postgres within this base that manages wals, this management is done manually and we know that it is not recommended, but as I said, it was the only alternative found at that time.

**Comment by dwsteele** [comment]
OK, just wanted to clarify what you are doing.

So yeah, `archive_command` is not very fast and async pgbackrest is able to get ahead of it. Unfortunately `archive_command` is exec'd using `system()`, which is especially slow.

I don't think reducing the retention to 1hr is going to make a difference. You'll still be removing files that the backup needs and the backup will not complete.

I wonder if something if off with your math. You say you are averaging 33,024 WAL files per day but that doesn't seem like much. You also say 622 average per minute which comes out to 895,680 per day which seems much more likely to be a problem. So, which is it?

But even at 622 per minute you should be OK as long as each call to `archive_command` is less than 100ms, which seems reasonable. Are you sure it is `archive_command` which is falling behind rather than compression/transmitting the WAL?

The first thing I would try is to set `compress-type=lz4` and remove `compress-level` (since the default is best). lz4 is far faster than gzip even when gzip is at level one.

**Comment by dwsteele** [comment]
One thing you might consider is increasing the WAL segment size. This can be very beneficial for performance.

You can do this with pg_resetwal, but it requires an outage and might also require rebuilding the replica, which might be too painful.
