### ISSUE TITLE
What's the rule of directory name 13-x in archive/stanza_name

### ISSUE THREAD

**Issue by bjzhangl** [pgbackrest/pgbackrest#1795]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.38

2. PostgreSQL version: 10 or 13

Question:
I notice that in dir archive/stanza_name, there could be 13-1, 13-2, 13-3 etc. Seems it's related to timeline. I want to know when 13-1 is created, when 13-2 and so on. Thanks!

**Comment by dwsteele** [comment]
The number after the dash is incremented after a stanza-upgrade. It is not related to timelines.

**Comment by bjzhangl** [comment]
Thanks! Then does pgbackrest provide a way to check if a stanza-upgrade is needed?

**Comment by dwsteele** [comment]
Any time you do a pg_upgrade, see: https://pgbackrest.org/user-guide.html#upgrade-stanza.
