### ISSUE TITLE
Multiple repo Questions

### ISSUE THREAD

**Issue by Kamal-Villupuram** [pgbackrest/pgbackrest#1797]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.39

2. PostgreSQL version: 12.9

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7

4. Did you install pgBackRest from source or from a package? source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: I have multiple repo configuration. One on S3 and other on local filesystem. I want to delete some backup on local and some specific backups on S3 not the entire stanza. how to delete?

**Comment by pgstef** [comment]
Hi,

Expire --set would be what you're looking for: https://pgbackrest.org/command.html#command-expire.

I think `pgbackrest expire --set=xx --repo=xx` should work. Simply specify the backup set label and repo id where the backup set is stored.

Kind regards

**Comment by Kamal-Villupuram** [comment]
Thanks. I configured two repo's and took backup on Primary on both repo's. But when I query the backup details from Secondary, it shows only the Repo1(s3) but on the repo2. Please advise why? 

[postgres@sl73skmdbq004 ~]$ pgbackrest --stanza=skm1q  --config=/pgtool/scripts/config/pgbackrest.conf info
Warning: program compiled against libxml 209 using older 206
stanza: skm1q
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12): 00000017000009F80000000D/00000017000009F80000001D

        full backup: 20220623-131158F
            timestamp start/stop: 2022-06-23 13:11:58 / 2022-06-23 13:40:15
            wal start/stop: 00000017000009F80000000D / 00000017000009F80000000D
            database size: 432.5GB, database backup size: 432.5GB
            repo2: backup set size: 432.5GB, backup size: 432.5GB

        full backup: 20220623-134713F
            timestamp start/stop: 2022-06-23 13:47:13 / 2022-06-23 14:30:58
            wal start/stop: 00000017000009F80000000F / 00000017000009F80000000F
            database size: 432.5GB, database backup size: 432.5GB
            repo1: backup set size: 432.5GB, backup size: 432.5GB

        incr backup: 20220623-134713F_20220624-002540I
            timestamp start/stop: 2022-06-24 00:25:40 / 2022-06-24 00:28:26
            wal start/stop: 00000017000009F800000015 / 00000017000009F800000015
            database size: 432.5GB, database backup size: 13.8GB
            repo1: backup set size: 432.5GB, backup size: 13.8GB
            backup reference list: 20220623-134713F

        diff backup: 20220623-134713F_20220624-010703D
            timestamp start/stop: 2022-06-24 01:07:03 / 2022-06-24 01:10:55
            wal start/stop: 00000017000009F800000017 / 00000017000009F800000017
            database size: 432.5GB, database backup size: 15.8GB
            repo1: backup set size: 432.5GB, backup size: 15.8GB
            backup reference list: 20220623-134713F
[postgres@sl73skmdbq004 ~]$ 


[postgres@sl73skmdbq005 ~]$ pgbackrest --stanza=skm1q  --config=/pgtool/scripts/config/pgbackrest.conf info
stanza: skm1q
    status: mixed
        repo1: ok
        repo2: error (no valid backups)
    cipher: none

    db (current)
        wal archive min/max (12): 00000017000009F80000000F/00000017000009F80000001D

        full backup: 20220623-134713F
            timestamp start/stop: 2022-06-23 13:47:13 / 2022-06-23 14:30:58
            wal start/stop: 00000017000009F80000000F / 00000017000009F80000000F
            database size: 432.5GB, database backup size: 432.5GB
            repo1: backup set size: 432.5GB, backup size: 432.5GB

        incr backup: 20220623-134713F_20220624-002540I
            timestamp start/stop: 2022-06-24 00:25:40 / 2022-06-24 00:28:26
            wal start/stop: 00000017000009F800000015 / 00000017000009F800000015
            database size: 432.5GB, database backup size: 13.8GB
            repo1: backup set size: 432.5GB, backup size: 13.8GB
            backup reference list: 20220623-134713F

        diff backup: 20220623-134713F_20220624-010703D
            timestamp start/stop: 2022-06-24 01:07:03 / 2022-06-24 01:10:55
            wal start/stop: 00000017000009F800000017 / 00000017000009F800000017
            database size: 432.5GB, database backup size: 15.8GB
            repo1: backup set size: 432.5GB, backup size: 15.8GB
            backup reference list: 20220623-134713F
[postgres@sl73skmdbq005 ~]$

**Comment by pgstef** [comment]
It simply means your repo2 config on `sl73skmdbq005` doesn't point to the same repo2 defined on `sl73skmdbq004`.
Without the detailed configurations as requested in the issue template, we won't be able to help more than that.

Regards

**Comment by Kamal-Villupuram** [comment]
Primary
cat /pgtool/scripts/config/pgbackrest.conf
[skm1q]
pg1-path=/pgdata/skm1q/12.x/data


[global]
repo1-type=s3
repo1-s3-endpoint=test3
repo1-s3-bucket=pgs3test
repo1-s3-key=xxxxxx
repo1-s3-key-secret=xxxxxx
repo1-s3-region=US
repo1-path=/skm1q
repo1-retention-full=1
repo1-s3-uri-style=path
repo1-storage-port=443
repo2-path=/pg_localbackup/pgbackrest
repo2-retention-full=1
archive-async=y
spool-path=/pgerror/skm1q/pgbackrest/spool
start-fast=y
expire-auto=y
process-max=8
log-path=/pgerror/skm1q/pgbackrest
log-level-file=detail
compress-type=none
compress-level-network=0
link-all=y
backup-standby=y

[global:archive-push]
compress-level-network=0
process-max=4

Standby
cat /pgtool/scripts/config/pgbackrest.conf
[skm1q]
pg1-path=/pgdata/skm1q/12.x/data
pg2-host=slskmdbq004
pg2-path=/pgdata/skm1q/12.x/data
pg2-socket-path=/tmp

[global]
repo1-type=s3
repo1-s3-endpoint=test3
repo1-s3-bucket=pgs3test
repo1-s3-key=xxxxxxx
repo1-s3-key-secret=xxxxx
repo1-s3-region=US
repo1-path=/skm1q
repo1-retention-full=1
repo1-s3-uri-style=path
repo1-storage-port=443
repo2-path=/pg_localbackup/pgbackrest
repo2-retention-full=1
archive-async=y
spool-path=/pgerror/skm1q/pgbackrest/spool
start-fast=y
expire-auto=y
process-max=8
log-path=/pgerror/skm1q/pgbackrest
log-level-file=detail
compress-type=none
compress-level-network=0
link-all=y
backup-standby=y

[global:archive-push]
compress-level-network=0
process-max=4

**Comment by Kamal-Villupuram** [comment]
yes..its mounted locally. if i copy the files to standby, does standby able to recognize it?

**Comment by Kamal-Villupuram** [comment]
one more Q: if repo1(s3) is down or unavailable for some reason, will archiving continue on repo2?

**Comment by pgstef** [comment]
> yes..its mounted locally. if i copy the files to standby, does standby able to recognize it?

if you need to copy that means you have 2 separated mount points and not the same shared one. That's not how it is supposed to work. `/pg_localbackup/pgbackrest` needs to be a shared location reachable from both nodes, so the mounted directories should point to the exact same space.

> one more Q: if repo1(s3) is down or unavailable for some reason, will archiving continue on repo2?

I suggest [this reading example](https://pgstef.github.io/2022/04/15/pgbackrest_multi-repositories_tips_and_tricks.html). If `archive-push` is failing because one repo is unavailable, PG `archive_command` will be blocked (PG will then keep the wals to archives until the failing repo is back online). Using async archiving, pgBackRest is able to push to repo2 the wals ready to be archived but not asked by PG yet. So yes, using async archiving, archives will come on repo2, but PG will still keep the wals not archived in repo1.

Regards

**Comment by Kamal-Villupuram** [comment]
Thanks. I got the points. Repo2 is working and i can see files archived there but why below command failed for repo2?


[postgres@sl73skmdbq004 00000017000009F9]$ pgbackrest --repo=1 repo-ls archive/skm1q/12-1/00000017000009F9 |grep 00000017000009F900000012 |wc -l
0
[postgres@sl73skmdbq004 00000017000009F9]$ pgbackrest --repo=2 repo-ls archive/skm1q/12-1/00000017000009F9 |grep 00000017000009F900000012 |wc -l
**ERROR: [032]: key '2' is not valid for 'repo' option**
0
[postgres@sl73skmdbq004 00000017000009F9]$ 


-rw-r-----. 1 postgres postgres 134217728 Jun 24 09:09 00000017000009F900000012-49dca109b54277ed56207d347d9db248b4391b2c
-rw-r-----. 1 postgres postgres 134217728 Jun 24 09:17 00000017000009F900000014-49ccddb7893aa9a30a498ed0361f5dd028714cbe
-rw-r-----. 1 postgres postgres 134217728 Jun 24 09:17 00000017000009F900000013-8f5d9252d42f4a677254b81c7ae95104c3a35e64
-rw-r-----. 1 postgres postgres 134217728 Jun 24 09:25 00000017000009F900000015-1dcce6109583cca24b6f513c299b50b5361deb88
-rw-r-----. 1 postgres postgres 134217728 Jun 24 09:25 00000017000009F900000016-89da4936473407379029f7a0ce894f60cd20f0c7

**Comment by pgstef** [comment]
`--config=/pgtool/scripts/config/pgbackrest.conf` ?
It seems to me that you didn't placed the configuration into the default place. So you need to teach the pgbackrest commands where to find the configuration file...

**Comment by Kamal-Villupuram** [comment]
Another Q on archiving on multiple repo. yes it does archives to the working repository in my case it took about 8mins. Why it took long to archive though its on async mode?  is there any parameter to tune the archiving quickly?

**Comment by pgstef** [comment]
> ... in my case it took about 8mins. Why it took long to archive though its on async mode? is there any parameter to tune the archiving quickly?

The question is too vague sorry. What took 8 mins ? How did you measure it ?
Async archiving isn't a miracle. It's triggered by PG itself. Each time PG triggers its archive_command, archive-push will spawn async processes (based on `process-max`) and look for .ready files. So it can push WAL segments ready to be archived but not asked by PG yet. That means PG have to trigger an archive_command AND have a WAL segment ready. 

I kinda feel like it took 8 mins to generate a new wal to be archived, unless you give more details.

Regards
