### ISSUE TITLE
access pgbackrest with .pgpassfile , 

### ISSUE THREAD

**Issue by daulat0** [pgbackrest/pgbackrest#1798]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.34

2. PostgreSQL version: Postgres 10

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Linux ip-172-31-32-99.us-east-2.compute.internal 4.14.252-195.483.amzn2.x86_64 #1 SMP Mon Nov 1 20:58:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

5. Did you install pgBackRest from source or from a package? package

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I want to authenticate pgbackrest via .pgpass file instead of  "trust" in hba.conf file . But while trying to check the connectivity , I got the below error message. Please help on it.

[root@ip-172-31-32-99 ec2-user]# pgbackrest --stanza=dbtest --log-level-console=info check
2022-06-24 13:41:03.663 P00   INFO: check command begin 2.34: --exec-id=5239-43a0dcc1 --log-level-console=info --pg1-path=/opt/PostgreSQL-10/data --pg1-port=5432 --pg1-socket-path=/tmp --pg1-user=postgres --repo1-path=/opt/pgbackrest --stanza=dbtest
WARN: unable to check pg-1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432 user='postgres' host='/tmp'': fe_sendauth: no password supplied
ERROR: [027]: no database found
       HINT: check indexed pg-path/pg-host configurations
2022-06-24 13:41:03.665 P00   INFO: check command end: aborted with exception [027]
[root@ip-172-31-32-99 ec2-user]#

=pgbackrest.conf:

root@ip-172-31-32-99 pgbackrest]# cat pgbackrest.conf

[global]
repo1-path=/opt/pgbackrest
repo1-retention-full=2

[dbtest]
pg1-path=/opt/PostgreSQL-10/data
pg1-port=5432
pg1-user=postgres
pg1-socket-path=/tmp
[root@ip-172-31-32-99 pgbackrest]#

==DB Log mess
[log_message.txt](https://github.com/pgbackrest/pgbackrest/files/8976655/log_message.txt)
age:

2022-06-24 09:25:41.614 EDT,"postgres","postgres",4240,"[local]",62b5bb55.1090,2,"authentication",2022-06-24 09:25:41 EDT,3/22916,0,LOG,00000,"connection authorized: user=postgres database=postgres",,,,,,,,,""
2022-06-24 09:28:15.216 EDT,"postgres","postgres",4240,"[local]",62b5bb55.1090,3,"idle",2022-06-24 09:25:41 EDT,,0,LOG,00000,"disconnection: session time: 0:02:33.602 user=postgres database=postgres host=[local]",,,,,,,,,"psql"
2022-06-24 09:28:20.503 EDT,,,4443,"[local]",62b5bbf4.115b,1,"",2022-06-24 09:28:20 EDT,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,""
2022-06-24 09:28:47.118 EDT,,,4470,"[local]",62b5bc0f.1176,1,"",2022-06-24 09:28:47 EDT,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,""
2022-06-24 09:41:03.664 EDT,,,5240,"[local]",62b5beef.1478,1,"",2022-06-24 09:41:03 EDT,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,""

**Comment by pgstef** [comment]
Hi,

Did you try to access the db with psql successfully first? The pgpass file should be placed correctly (location + permission) and that's a common source of mistake.

I tried this quick example successfully:

```bash
$ cat ~/.pgpass
#hostname:port:database:username:password
localhost:5432:postgres:superman:loislane

$ chmod 0600 ~/.pgpass
$ cat /var/lib/pgsql/14/data/pg_hba.conf
local   all             all                                     scram-sha-256

$ psql -U superman -d postgres
--> OK

$ cat /etc/pgbackrest.conf 
[global]
repo1-path=/var/lib/pgsql/14/backups

[demo]
pg1-path=/var/lib/pgsql/14/data
pg1-user=superman

[root]# sudo -iu postgres pgbackrest --stanza=demo check --log-level-console=info
2022-06-27 08:01:44.626 P00   INFO: check command begin 2.39: ...
2022-06-27 08:01:45.235 P00   INFO: check repo1 configuration (primary)
2022-06-27 08:01:45.441 P00   INFO: check repo1 archive for WAL (primary)
2022-06-27 08:01:45.542 P00   INFO: WAL segment 000000010000000000000002 successfully archived to '...' on repo1
2022-06-27 08:01:45.542 P00   INFO: check command end: completed successfully (916ms)
```

So, pay attention to the pgpass location, permission and content. And also to the system user executing the pgBackRest command (given the pgpass file should be located in that user home directory).

Hope this help,
Kind Regards

**Comment by daulat0** [comment]
Thanks !

If I checked , it looks, I am able to login with psql without giving password. I have .pgpass under the root user (home directory).

[root@crisil-fresh ~]# pwd
/root
[root@crisil-fresh ~]# ls -ltra
total 100
-rw-r--r--.  1 root root   129 Oct 18  2017 .tcshrc
-rw-r--r--.  1 root root   100 Oct 18  2017 .cshrc
-rw-r--r--.  1 root root   176 Oct 18  2017 .bashrc
-rw-r--r--.  1 root root   176 Oct 18  2017 .bash_profile
-rw-r--r--.  1 root root    18 Oct 18  2017 .bash_logout
drwx------.  2 root root    29 May 13 04:47 .ssh
drwx------.  4 root root    37 May 18 13:01 .config
drwx------.  5 root root    83 May 18 13:02 .npm
-rw-------.  1 root root    41 Jun 20 10:27 .pgpass
-rw-------.  1 root root 29376 Jun 20 12:47 .psql_history
-rw-------.  1 root root 14102 Jun 20 13:16 .viminfo
dr-xr-x---.  5 root root   203 Jun 20 13:16 .
-rw-------.  1 root root 20847 Jun 20 13:47 .bash_history
dr-xr-xr-x. 22 root root  4096 Jun 23 08:57 ..

[root@crisil-fresh ~]# cat .pgpass
localhost:5432:*:postgres:Test@12N4A50

[root@crisil-fresh ~]# cd /PostgreSQL-10/bin/
[root@crisil-fresh bin]# ./psql -d postgres -U postgres
psql (10.2)
Type "help" for help.

postgres=#

[root@crisil-fresh etc]# cd /etc/pgbackrest/
[root@crisil-fresh pgbackrest]# ls -ltr
total 8
drwxr-xr-x. 2 postgres postgres 185 May 20 07:18 log
-rwxr-xr-x. 1 postgres postgres 371 Jun 20 13:16 pgbackrest.conf
[root@crisil-fresh pgbackrest]# cat pgbackrest.conf
[global]
repo1-path=/pgbackrest-bkp/
repo1-retention-full=2
repo1-s3-endpoint=s3.us-east-2.amazonaws.com
repo1-s3-bucket=test_bkp
repo1-s3-region=us-east-2
repo1-type=s3
repo1-s3-key="I have removed it, for security "
repo1-s3-key-secret= " I have removed it, for security "

[test1]
pg1-path=/PostgreSQL-10/data
pg1-port=5432
pg1-user=postgres
pg1-socket-path=/tmp

**Comment by daulat0** [comment]
Could you please share your directory structure and the permissions for postgres and pgbackrest .

**Comment by pgstef** [comment]
> Could you please share your directory structure and the permissions for postgres and pgbackrest .

Sorry, I don't have that anymore, it was just a test machine to show you that using pgpass is working with pgBackRrest. The only issue I found there was a mismatch between pg_hba auth method (md5/scram) and the password_encryption used to create the user password.

As mentioned above: 

> At some point it "should" work but it is always easier to use peer auth, or at least running the pgbackrest commands with the same system user used by PG (because i.e. PG will run the archive-push command, so you might end up with permission issues).

Imho, you should avoid root access and use the same system user for your PG cluster and pgBackRest commands.

**Comment by daulat0** [comment]
Thanks for your suggestions. It is working fine for me now after using .bash_profile .
