### ISSUE TITLE
Question: multiple repositories (one local, one NFS) with dedicated host

### ISSUE THREAD

**Issue by silenius** [pgbackrest/pgbackrest#1803]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.35

2. PostgreSQL version: 13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
 - database server (pg13.lan): FreeBSD 12.3-RELEASE
 - dedicated repository host server (pgbackrest-pg13.lan): FreeBSD 13.1-RELEASE
 - remote NFS server (stout.lan): 13.1-RELEASE 

5. Did you install pgBackRest from source or from a package?

package

6. Please attach the following as applicable:

### Dedicated repository host (pgbackrest-pg13.lan)

**pgbackrest.conf**

```
pgbackrest-pg13% cat /usr/local/etc/pgbackrest/pgbackrest.conf 
[global]
log-level-console = info
log-level-file = detail
log-path = /var/log/pgbackrest
log-timestamp = y
repo1-cipher-pass = xxx
repo1-cipher-type = aes-256-cbc
repo1-path = /data/pgbackrest
repo1-retention-full = 2
repo1-retention-full-type = count
repo1-type = posix
repo2-cipher-pass = xxx
repo2-cipher-type = aes-256-cbc
repo2-path = /nfs/stout_pgbackrest
repo2-retention-full = 6
repo2-retention-full-type = count
repo2-type = posix
start-fast = y
process-max = 8

[global:archive-push]
compress-type = none

[pg13]
pg1-host = pg13.lan
pg1-path = /data/data13
```

### PostgreSQL host (pg13.lan)

**pgbackrest.conf**

```
root@pg13:~ # cat /usr/local/etc/pgbackrest/pgbackrest.conf 
[global]
log-level-console = info
log-level-file = detail
log-path = /var/log/pgbackrest
log-timestamp = y
repo1-host = pgbackrest-pg13.lan
repo1-host-user = pgbackrest
repo1-path = /data/pgbackrest
repo2-host = pgbackrest-pg13.lan
repo2-host-user = pgbackrest
repo2-path = /nfs/stout_pgbackrest
process-max = 4

[pg13]
pg1-path = /data/data13
```
**postgresql.conf**

```
root@pg13:~ # cat /data/data13/conf.d/saltstack.conf 

listen_addresses = 'localhost, pg13.lan'
max_connections = '200'
shared_buffers = '4GB'
work_mem = '512MB'
maintenance_work_mem = '4GB'
checkpoint_timeout = '30min'
max_wal_size = '10GB'
min_wal_size = '80MB'
checkpoint_completion_target = '0.9'
random_page_cost = '3.5'
cpu_tuple_cost = '0.1'
effective_cache_size = '16GB'
from_collapse_limit = '10'
join_collapse_limit = '10'
log_destination = 'stderr'
logging_collector = 'on'
log_directory = '/var/log/pgsql'
log_filename = 'postgresql-%a.log'
log_rotation_age = '1d'
log_statement = 'none'
archive_command = '/usr/local/bin/pgbackrest --stanza=pg13 archive-push %p'
archive_mode = 'on'
max_wal_senders = '10'
wal_level = 'replica'
data_directory = '/data/data13'
hba_file = '/data/data13/pg_hba.conf'
ident_file = '/data/data13/pg_ident.conf'
```

8. Describe the issue:

I'm busy to finalize the installation of pgbackrest to backup our PostgreSQL instances. I have two bare metal server: one located in the same rack as the postgresql server and one remote located in another country (Hetzner). The remote has a ZFS dataset mounted on the local through NFS (V4) over a wireguard link (/nfs/stout_pgbackrest). As you can see in the configuration files I have one backup server with multiple repositories.
I'm testing and everything works quite well, but:
- Backups through the NFS repo are (very) slow, this is because there are a lot of small file writes:
```
(...)
2022-06-30 17:25:28.285 P03 DETAIL: backup file pg13.lan:/data/data13/base/36552/40029 (8KB, 99%) checksum 33985a1ca9ef5a6ec4dcaaeca8264365436a4806
2022-06-30 17:25:28.433 P02 DETAIL: backup file pg13.lan:/data/data13/base/36552/40014 (8KB, 99%) checksum 207860a8c300ce7b1f8b3ffdbcf5493ce4b22d1c
2022-06-30 17:25:28.656 P01 DETAIL: backup file pg13.lan:/data/data13/base/36552/39993 (8KB, 99%) checksum 4725ab922d61f9eb227e6c513c04d8075af2aaf9
2022-06-30 17:25:28.806 P03 DETAIL: backup file pg13.lan:/data/data13/base/36552/39980 (8KB, 99%) checksum 643e3d2814a21b9a306377bb8534b30b3900c0c3
(...)
```

I was wondering if there is a way to speed up that? Would it be better to use two backup server, discard NFS and use SSH only?

I'm mounting the remote with:
```
stout.lan:/pgbackrest /jails/pgbackrest-pg13/nfs/stout_pgbackrest nfs nfsv4,rw,bg,late,minorversion=2,noexec,nosuid,noinet6,proto=tcp,readahead=2,nconnect=2 0 0
```
- If I understand well with one backup server with multiple repositories I have to launch each backup with the `--repo` option. 
Is it OK to have a crontab which looks like:
```
@weekly -n /usr/local/bin/pgbackrest --type=full --stanza=pg13 --repo=1 backup ; /usr/local/bin/pgbackrest --type=full --stanza=pg13 --repo=2 backup 
@900 -n /usr/local/bin/pgbackrest --stanza=data --repo=1 backup ; /usr/local/bin/pgbackrest --stanza=data --repo=2 backup 
```
- anything wrong about my config?

Thank you ! :)

**Comment by dwsteele** [comment]
> I was wondering if there is a way to speed up that?

Small file performance can be improved with bundling: https://pgbackrest.org/user-guide.html#backup/bundle

> Is it OK to have a crontab which looks like

Yes, just make sure backup jobs won't overlap. Currently it is not possible to run backups from the same cluster to multiple repos at the same time.

**Comment by silenius** [comment]
Thank you, it looks like I missed "bundling"

> Currently it is not possible to run backups from the same cluster to multiple repos at the same time.

Ok, it would be a nice feature to add!

**Comment by silenius** [comment]
regarding:

> Yes, just make sure backup jobs won't overlap. 

is it sufficient to check for a `/tmp/pgbackrest/stanza-{archive,backup}.lock` before running the backup?

**Comment by dwsteele** [comment]
> Is it sufficient to check for a /tmp/pgbackrest/stanza-{archive,backup}.lock before running the backup?

Sure is, but you'll just get a lock error from backrest if the backups run concurrently -- it won't do anything bad.

**Comment by silenius** [comment]
for those who are interested, I finally used:
```
root@pgbackrest-pg13:~ # sudo crontab -u pgbackrest -l
@weekly -n /usr/bin/lockf -k /tmp/cron_pgbackrest /usr/local/bin/pgbackrest --type=full --stanza=pg13 --repo=1 backup ; /usr/bin/lockf -k /tmp/cron_pgbackrest /usr/local/bin/pgbackrest --type=full --stanza=pg13 --repo=2 backup
@900 -n /usr/bin/lockf -k /tmp/cron_pgbackrest /usr/local/bin/pgbackrest --type=incr --stanza=pg13 --repo=1 backup ; /usr/bin/lockf -k /tmp/cron_pgbackrest /usr/local/bin/pgbackrest --type=incr --stanza=pg13 --repo=2 backup
```
