### ISSUE TITLE
stanze-create throws erro 52

### ISSUE THREAD

**Issue by mingravity** [pgbackrest/pgbackrest#1804]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 13.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7.9

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

pgbackrest config:

[global]
repo1-path=/pgbackup/instance1
process-max=12
archive-async=y
archive-get-queue-max=104857600

[pgInstance1]
pg1-path=/pg/instance1/data

7. Describe the issue: Trying to run stance-create command throws error [052] unable to sync file, No space left on device. Although there is no issue with the space on the device. 

exact error log output:

ERROR: [052]: unable to sync file 'pgbackup/instance1/archive/pginstance1/archive.info.pgbackrest.tmp' after write: [28] No space left on device

**Comment by dwsteele** [comment]
> ERROR: [052]: unable to sync file 'pgbackup/instance1/archive/pginstance1/archive.info.pgbackrest.tmp' after write: [28] No space left on device

This error is coming from your storage. You'll need to figure out why it thinks it is out of space.

You haven't given any information about your storage, so not really anything we can do to help.
