### ISSUE TITLE
Page-level incremental backups, in roadmap?

### ISSUE THREAD

**Issue by eversonkalaf** [pgbackrest/pgbackrest#1806]
https://github.com/pgbackrest/pgbackrest/issues/959

I have a 3T database, and the incremental backup is getting too big in every hour + ou - 800GB
my autovacuum is disable and run once a day

pgbackrest version: 2.36

**Comment by dwsteele** [comment]
We are currently working on this, see: https://github.com/pgbackrest/pgbackrest/compare/main...dwsteele:pgbackrest:dws-block-incr

But we do not yet know when it will be released.

**Comment by dwsteele** [comment]
Added project card: https://github.com/pgbackrest/pgbackrest/projects/2#card-84439046

**Comment by dwsteele** [comment]
This will be included in pgBackRest 2.44 as an internal feature (i.e. don't use in production) and it would be helpful if you could test against your workload and provide feedback.
