### ISSUE TITLE
Files are batch deleted on S3-compatible storage 1000 at a time. My guess is that your server is slow and is not able to delete 1000 files before the timeout.

### ISSUE THREAD

**Issue by jw1u1** [pgbackrest/pgbackrest#1807]
Files are batch deleted on S3-compatible storage 1000 at a time. 

_Originally posted by @dwsteele in https://github.com/pgbackrest/pgbackrest/issues/1284#issuecomment-768264744_

Hi David,
why don't you recursively delete directorys? This would be much faster.
Is it due to issues with links?
Rgds, Jens

**Comment by dwsteele** [comment]
> why don't you recursively delete directorys? This would be much faster.

I'm not sure what you mean by this. Are you talking about S3?

**Comment by dwsteele** [comment]
So, still not sure what you mean. We are certainly deleting recursively on S3 but delete batches are limited to 1000 per batch. If you have a better idea, please provide a specific example.

**Comment by dwsteele** [comment]
We use the REST API (https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html) not `s3cmd`.
