### ISSUE TITLE
version mismatch for pg-13.3_TDE_1.0beta1

### ISSUE THREAD

**Issue by k0lpaz** [pgbackrest/pgbackrest#1810]
Hi Everyone,

I am using postgres (PostgreSQL) 13.3_TDE_1.0beta1 and pgBackRest 2.38.
OS: Rocky Linux 8.5

I think i have a version mismatch. Is there a pgbackrest version supporting this particular pg version? 

ERROR:

ERROR: [046]: raised from local-12 protocol: unexpected WAL magic 44950
       HINT: is this version of PostgreSQL supported?
       [VersionNotSupportedError] on retry after 0ms

Enclosed you will find the check.log with trace log-level.
[tbl-check.log](https://github.com/pgbackrest/pgbackrest/files/9069933/tbl-check.log)

**Comment by dwsteele** [comment]
You'll need to set `archive-header-check=n` since the WAL headers are encrypted, see https://pgbackrest.org/configuration.html#section-archive/option-archive-header-check.

**Comment by k0lpaz** [comment]
Thanks for the quick response! Haven't paid much attention on the archive-header-check before.
