### ISSUE TITLE
Restore single database using PITR with PostgreSQL?

### ISSUE THREAD

**Issue by daulat0** [pgbackrest/pgbackrest#1811]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.34 and pgBackRest 2.38

3. PostgreSQL version: v.10

4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: NO

5. Did you install pgBackRest from source or from a package? source

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
   

7. Describe the issue:
I need your help to perform the recovery of single database incase any failure /table dropped.
Is it possible to perform the recovery for single database using pgbackrest backup?
Is it possible to restore that table that was deleted/truncated ?
[PITR using pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/9084124/PITR.using.pgbackrest.txt)

**Comment by pgstef** [comment]
Hi,

As you can read in PG [docs](https://www.postgresql.org/docs/current/continuous-archiving.html), PITR can only support restoration of an entire database cluster, not a subset.

What you can do is restore the entire cluster on a temporary machine and extract the db / table you need using `pg_dump` and import it in your actual production system using `pg_restore`.

If you know precisely which database you'd need, you can save a bit of restore time / disk space for that "temporary" restored copy using the [restore --db-include option](https://pgbackrest.org/command.html#command-restore/category-command/option-db-include). Read carefully the description of that option to understand what's going to happen and look at the [user-guide](https://pgbackrest.org/user-guide.html#restore/option-db-include) to see an example.

Kind Regards

**Comment by daulat0** [comment]
Thanks. I used the following ways.
pgbackrest --stanza=dbtest --log-level-console=info  --type=time "--target=2022-07-12 08:38:48.138554-04" --db-path=/opt/PostgreSQL-10/data10 --set=20220712-102128F restore

pgbackrest --stanza=dbtest --log-level-console=info --db-path=/opt/PostgreSQL-10/data10 --db-include=test5 restore
data1
