### ISSUE TITLE
Error in documentation - how to contribute a correction?

### ISSUE THREAD

**Issue by vrms** [pgbackrest/pgbackrest#1812]
I found an error in the documentaion [here](https://pgbackrest.org/user-guide-rhel.html#repo-host/install)

`$ sudo adduser -gpgbackrest -n pgbackrest` should be
`$ sudo adduser -g pgbackrest -n pgbackrest`

actually I am not familiar with the `-n` option neither, but that can be my lack of knowledge on `adduser`.

I am wondering how to contribute here. I don't see any files in the `/doc` subdirectory which one could adjust and send a PR and I guess this is due to the docs being build automatically.

**Comment by dwsteele** [comment]
You can find info on building the docs here: https://github.com/pgbackrest/pgbackrest/blob/main/CONTRIBUTING.md#testing-the-documentation. The source is in https://github.com/pgbackrest/pgbackrest/tree/main/doc/xml.

I tried these commands on CentOS 7 and Rocky 8 and they ran fine. But if you would like to submit a PR to add the space, you are welcome to do so.
