### ISSUE TITLE
Timeout from the expire command during backup retention in s3 repo

### ISSUE THREAD

**Issue by 01012** [pgbackrest/pgbackrest#1813]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.39

2. PostgreSQL version: 12.11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: docker container in docker swarm

4. Did you install pgBackRest from source or from a package? 
i guess from package, included in docker image https://hub.docker.com/r/timescale/timescaledb-ha

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/9102050/pgbackrest.txt)
[backrest.log](https://github.com/pgbackrest/pgbackrest/files/9102052/backrest.log)
archive_mode = on
archive_command = 'pgbackrest --stanza=demo archive-push %p'

6. Describe the issue:
Sometimes expire command end: aborted with exception

```2022-07-13 02:30:11.728 P00  DEBUG:     common/io/http/request::httpRequestProcess: retry FileReadError: timeout after 60000ms waiting for read from 'pgbackrest-demo.s3.storage.selcloud.ru:443'
2022-07-13 02:30:11.847 P00  DEBUG:     common/io/http/response::httpResponseNew: (session: {HttpSession}, verb: {"POST"}, contentCache: true)
2022-07-13 02:31:11.885 P00  ERROR: [042]: repo1: timeout after 60000ms waiting for read from 'pgbackrest-demo.s3.storage.selcloud.ru:443'
2022-07-13 02:31:11.885 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)
2022-07-13 02:31:11.885 P00  ERROR: [104]: expire command encountered 1 error(s), check the log file for details

**Comment by 01012** [comment]
> Not a lot to go on here. Looks like the server is sometimes not responding:
> 
> ```
> timeout after 60000ms waiting for read from 'pgbackrest-demo.s3.storage.selcloud.ru:443
> ```
I guess the server is not responding because deleting the backup is taking too long. Maybe change the error level to a warning or the ability to change the timeout?

**Comment by dwsteele** [comment]
We delete files 1000 at a time (and there are multiple retries within the timeout period). You could try increasing `io-timeout`, but I don't think there's much we can do on our end.

**Comment by 01012** [comment]
thanks
