### ISSUE TITLE
could not link file in wal restore lines

### ISSUE THREAD

**Issue by hyperknot** [pgbackrest/pgbackrest#1815]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.39

2. PostgreSQL version: psql (PostgreSQL) 12.11 (Ubuntu 12.11-1.pgdg18.04+1)

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    
```
[global]
repo1-path=/shared/postgresql/pgbackrest
repo1-retention-full=2
repo1-retention-history=0
repo1-bundle=y
start-fast=y
resume=n
log-path=/shared/logs/CURRENT/pgbackrest
log-level-file=info
process-max=2

[global:restore]
process-max=4
delta=y

[app]
pg1-path=/data/pg12
```

```
archive_command = 'pgbackrest --stanza=app archive-push %p'
archive_mode = on
archive_timeout = 15min
```

```
INFO: restore command begin 2.39: --delta --exec-id=1-71dc2b3f --log-level-console=info --log-level-file=off --log-path=/shared/logs/CURRENT/pgbackrest --pg1-path=/data/pg12 --process-max=4 --repo1-path=/shared/postgresql/pgbackrest --stanza=app
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/data/pg12' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
INFO: repo1: restore backup set 20220710-032706F, recovery will start at 2022-07-10 03:27:06
INFO: write updated /data/pg12/postgresql.auto.conf
INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
INFO: restore size = 36.1GB, file total = 1594
INFO: restore command end: completed successfully (46475ms)
```

7. Describe the issue:

I'm testing pgbackrest restore.

It works well, but in the pg logs I get the following lines:

```
could not link file "pg_wal/000000010000015600000098" to "pg_wal/00000001000001570000006E": File exists
```

In total, I get 18 lines of "could not link file" and 932 lines of "restored log file" lines.

At the end it finishes with:

```
redo done at 15A/A001710
last completed transaction was at log time 2022-07-15 19:41:05.175573+00
restored log file "000000030000015A0000000A" from archive
selected new timeline ID: 4
archive recovery complete
restored log file "00000003.history" from archive
database system is ready to accept connections
```

Before going in production, I wanted to ask, if this is correct like this? I mean are those "could not link file" lines anything to worry about?

**Comment by dwsteele** [comment]
First, I'd make sure that the pg_wal directory is empty when recovery starts (i.e. PostgreSQL is started). Did you make the backup with the `--archive-copy` option?

If pg_wal is empty when recovery starts then this may be a file system issue. What filesystem are you running PostgreSQL on?

Also, the error is coming out of PostgreSQL's `durable_rename_excl()` function, which was recently removed due to some issues after crashes: https://github.com/postgres/postgres/commit/2c902bbf1911a3c3dd68b817209eca9be81e381c. I don't think that's what is going on here, though.

**Comment by hyperknot** [comment]
The host is a Ubuntu 18.04 on default filesystem. The restore script starts by `rm -rf $DATA_DIR`, and afterwards runs initdb, so it's as clean as it can be.

I'll need to look into --archive-copy, I'm not using this nor I understand what does it do.

**Comment by dwsteele** [comment]
> I don't see why would I need to have the archive-copy enabled

You don't -- I was just checking to see if you did.

> I'm doing the very basic config, nothing remote, just a local folder on the same partition, and restoring has this bug.

If it's a bug we believe it's a storage or PostgreSQL bug. pgBackRest does not touch these files or generate this warning.

This has come up once before (https://github.com/pgbackrest/pgbackrest/issues/990) but we never did figure out what was going on.

**Comment by hyperknot** [comment]
Posted it in bugs list here:
https://www.postgresql.org/message-id/flat/CAKw-smBhLOGtRJTC5c%3DqKTPz8gz5%2BWPoVAXrHB6mY-1U4_N7-w%40mail.gmail.com

**Comment by hyperknot** [comment]
Got a reply from Michael Paquier. I'm not at the level of understanding the internals of PG, I might need your help in communicating there.

What I've noticed though, is that I cannot remove the pgbackrest archive folder after a restore is done. The pg data folder's size is the same as reported in the "info" command / database size.

I thought after a restore I wouldn't need the original backup folder, but it seems that the WAL logs are restored from this outside folder? Is it by design?

**Comment by dwsteele** [comment]
> I thought after a restore I wouldn't need the original backup folder, but it seems that the WAL logs are restored from this outside folder? Is it by design?

Yes, it is by design. PostgreSQL needs access to the WAL segments that were created during the backup.

It would be good to see your entire procedure here step by step. Are you starting PostgreSQL immediately after the pgbackrest restore? Any steps in between?

**Comment by hyperknot** [comment]
This is the full script, which reproduces this issue.

```

c.run(f'rm -rf {p.remote_data}/pg12')
c.run(f'mkdir -p {p.remote_data}/pg12')

c.run(
    f'docker run --rm '
    f'--name {p.instance_name} '
    f'-v {p.remote_data}:/data '
    f'-v {p.remote_shared}:/shared ' + f'{p.repo_name}:{version} '
    'pgbackrest --stanza=app --log-level-console=info --log-level-file=off restore',
)

c.run(
    f'docker run --rm '
    f'--name {p.instance_name} '
    f'-v {p.remote_data}:/data '
    f'-v {p.remote_shared}:/shared '
    '--user=postgres '
    f'{p.repo_name}:{version} '
    '/usr/lib/postgresql/12/bin/postgres -D /data/pg12',
)
```
    
`c.run()` is just SSH automation (via Fabric), so these commands are the same as I'd run in the terminal.

**Comment by dwsteele** [comment]
A hint was added to the log message in Postgres to indicate that these log messages are harmless: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=41f613fc257c4d1df97f5f244461d1acb2b65227.
