### ISSUE TITLE
Backups run soon after datacenter promotion fail until replica checkpoint is run

### ISSUE THREAD

**Issue by keithf4** [pgbackrest/pgbackrest#1816]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 

2.39

2. PostgreSQL version: 

14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 

CentOS7

4. Did you install pgBackRest from source or from a package? 

package

5. Please attach the following as applicable:

/etc/pgbackrest.conf:
```
[global]
log-level-console=info
log-level-file=info
start-fast=y
```
/etc/pgbackrest/conf.d/golf.conf
```
[golf]
archive-async=y
archive-header-check=y
archive-timeout=60
backup-standby=y
compress-level=6
compress-type=gz
delta=y
process-max=3
resume=y
spool-path=/var/lib/pgsql/14/golf/spool
stop-auto=n

pg1-host=192.168.122.116
pg1-host-user=postgres
pg1-path=/var/lib/pgsql/14/golf/data
pg1-port=5432

pg2-host=192.168.122.126
pg2-host-user=postgres
pg2-path=/var/lib/pgsql/14/golf/data
pg2-port=5432

pg3-host=192.168.122.136
pg3-host-user=postgres
pg3-path=/var/lib/pgsql/14/golf/data
pg3-port=5432

repo1-host-user=postgres
repo1-path=/var/lib/pgbackrest
repo1-retention-diff=7
repo1-retention-full=4
repo1-type=posix

[golf:archive-get]
process-max=2

[golf:archive-push]
process-max=2
```
```
       name       |                      setting                      
------------------+---------------------------------------------------
 archive_command  | /usr/bin/pgbackrest --stanza=golf archive-push %p
 archive_mode     | on
 listen_addresses | 0.0.0.0
 max_wal_senders  | 10
 port             | 5432
 wal_level        | replica
```

6. Describe the issue:

During a datacenter failover test, we encountered the following issue after promoting the standby datacenter to become the primary. The standby datacenter has replicas itself and pgbackrest is configured to backup from the standby. However, if a backup is run soon after promotion, it fails with the below error since we are configured to backup from standby.
```
$ pgbackrest --stanza=golf backup
2022-07-15 17:18:19.208 P00   INFO: backup command begin 2.38: --archive-timeout=60 --backup-standby --compress-level=6 --compress-type=gz --delta --exec-id=5411-c7148
813 --log-level-console=info --log-level-file=info --pg1-host=192.168.122.116 --pg2-host=192.168.122.126 --pg3-host=192.168.122.136 --pg1-host-user=postgres --pg2-host
-user=postgres --pg3-host-user=postgres --pg1-path=/var/lib/pgsql/14/golf/data --pg2-path=/var/lib/pgsql/14/golf/data --pg3-path=/var/lib/pgsql/14/golf/data --pg1-port
=5432 --pg2-port=5432 --pg3-port=5432 --process-max=3 --repo1-path=/var/lib/pgbackrest --repo1-retention-diff=7 --repo1-retention-full=4 --repo1-type=posix --resume --
stanza=golf --start-fast --no-stop-auto
2022-07-15 17:18:22.270 P00   INFO: last backup label = 20220715-164211F, version = 2.38
2022-07-15 17:18:22.270 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2022-07-15 17:18:23.098 P00   INFO: backup start archive = 000000020000000000000014, lsn = 0/14000028
2022-07-15 17:18:23.098 P00   INFO: wait for replay on the standby to reach 0/14000028
ERROR: [058]: standby is on timeline 1 but expected 2
2022-07-15 17:18:23.422 P00   INFO: backup command end: aborted with exception [058]
```
The replica is 100% caught up, it just has not yet replayed the checkpoint that contains the timeline switch. If we wait the `checkpoint_timeout` or force a CHECKPOINT on the replica, then backups resume working again.

This began happening as of 2.37 and seems to be tied to this change: https://github.com/pgbackrest/pgbackrest/pull/1581

**Comment by dwsteele** [comment]
The standby timeline check has been moved to after the checkpoint in PR #1819. If you could test and verify it fixes the issue that would be very helpful.

**Comment by keithf4** [comment]
Confirmed this fix works for us.

**Comment by dwsteele** [comment]
Thanks! Added you as a reviewer in 2caef37fd55ea12959015f02a106774f6ad711b7.
