### ISSUE TITLE
Pgbackrest backup for multiple clusters on single server

### ISSUE THREAD

**Issue by daulat0** [pgbackrest/pgbackrest#1817]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.34

2. PostgreSQL version: Postgres V.10

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Amazon Linux (amzn2.x86_64)

4. Did you install pgBackRest from source or from a package? Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
[Information.txt](https://github.com/pgbackrest/pgbackrest/files/9130704/Information.txt)

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
We have a single server having postgres v.10 where multiple clusters are running on different-2 ports. We need to take the backup of each cluster via pgbackrest.  How can we take the backup via pgbackrest incase of multiple cluster on single server?

**Comment by pgstef** [comment]
What do you mean by "multiple clusters"? Totally separated (so with different content and not linked together via i.e. streaming replication)?

If that's 2 different clusters, I guess you simply have to define/create 2 different stanzas in the configuration with their own pg-path and pg-port.

**Comment by pgstef** [comment]
Then I guess you simply can use different stanzas. Something like this probably:

```ini
[global]
...

[testdb]
pg1-path=/some_path_to_cluster1
pg1-port=5432

[db2]
pg1-path=/some_path_to/cluster2
pg1-port=5433
```

**Comment by daulat0** [comment]
Yes. It works ! It is a global configuration as mentioned in the config
file.

Is it possible to take backup of a single database via pgBackrest? I think
no , but what is your thought on this?
Thanks for help and suggestions.

**Comment by dwsteele** [comment]
> Is it possible to take backup of a single database via pgBackrest?

No. PostgreSQL does not allow this.
