### ISSUE TITLE
aws s3 bucket name with dots

### ISSUE THREAD

**Issue by svenjochems** [pgbackrest/pgbackrest#1818]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.39

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: ubuntu

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s): 
```
[global]
repo1-path=/pgbackrest
repo1-retention-full=2
repo1-type=s3
repo1-s3-uri-style=path
repo1-s3-bucket=my.bucket
repo1-s3-endpoint=s3..amazonaws.com
repo1-s3-key=xxx
repo1-s3-key-secret=xxx
repo1-s3-region=eu-west-3
start-fast=y

[main]
pg1-path=/var/lib/postgresql/data
pg1-user=postgres

```

7. Describe the issue:
```
pgbackrest stanza-create --stanza main
ERROR: [032]: 'my.bucket' is not valid for option 'repo1-s3-bucket'
       HINT: RFC-2818 forbids dots in wildcard matches.
       HINT: TLS/SSL verification cannot proceed with this bucket name.
       HINT: remove dots from the bucket name.
```

I have a S3 bucket on AWS with one or more dots in the name. This is supported according to the aws [bucket naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html).

When I try to communicate to S3 with pgbackrest I get the warning that dots are not supported in the bucket name. Is there any way to work around this?

**Comment by dwsteele** [comment]
That documentation states specifically not to use dots in buckets that will be accessed by HTTPS:

> For best compatibility, we recommend that you avoid using dots (.) in bucket names, except for buckets that are used only for static website hosting. If you include dots in a bucket's name, you can't use virtual-host-style addressing over HTTPS, unless you perform your own certificate validation. This is because the security certificates used for virtual hosting of buckets don't work for buckets with dots in their names.
>
> This limitation doesn't affect buckets used for static website hosting, because static website hosting is only available over HTTP.

This is because wildcards cannot match multiple hostname parts as specified in RFC-2818:

> Names may contain the wildcard character * which is considered to match any single domain name component or component fragment. E.g., *.a.com matches foo.a.com but not bar.foo.a.com. f*.com matches foo.com but not bar.com.

The only way around this is to set `repo1-storage-verify-tls=n`, which disables all verification and is *not* recommended.
