### ISSUE TITLE
ERROR: [029]: page size is 16384 but must be 8192

### ISSUE THREAD

**Issue by KaiKaiWaWa** [pgbackrest/pgbackrest#1820]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.26

2. PostgreSQL version:11.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Linux xxx 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
4. Did you install pgBackRest from source or from a package?
source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Postgrease database is in 16K block size / page size . When I try to create a pgbackrest stanze, we are getting error as mentioned below -
[postgres@xxxx:/home/postgres]$pgbackrest --stanza=main --log-level-console=info stanza-create
2022-07-22 00:33:55.934 P00   INFO: stanza-create command begin 2.26: --log-level-console=info --pg1-path=/data/pg11/pg_root --repo1-path=/var/lib/pgsql/pgbackrest --stanza=main
ERROR: [029]: page size is 16384 but must be 8192
2022-07-22 00:33:56.440 P00   INFO: stanza-create command end: aborted with exception [029]

**Comment by dwsteele** [comment]
We don't support different page sizes because they are not well tested by PostgreSQL and require a compile-time option to change.

Making the page size larger may not be as beneficial as you think. See https://blog.pgaddict.com/pdf/block-sizes-postgresvision-2022.pdf. It might be useful in certain OLAP scenarious but there are easier ways to optimize.
