### ISSUE TITLE
ERROR: [029]: unable to find child IsTruncated:0 in node ListAllMyBucketsResult

### ISSUE THREAD

**Issue by cernoel** [pgbackrest/pgbackrest#1827]
ERROR: [029]: unable to find child IsTruncated:0 in node ListAllMyBucketsResult

1. pgBackRest version: > 2.39

2. PostgreSQL version: 14

3. Operating system/version: Debian Bullseye

4. Did you install pgBackRest from source or from a package? source
(main branch/2.41-dev), 2.40, 2.39

5. Please attach the following as applicable:
```
[demo]
pg1-path=/var/lib/postgresql/14/main
pg1-port=5432

[global]
repo1-type=s3
repo1-path=/demodb
repo1-bundle=y
repo1-retention-full=1
repo1-retention-full-type=time
repo1-retention-diff=7
repo1-cipher-pass=SECURECIPHERPASS
repo1-cipher-type=aes-256-cbc
repo1-retention-history=60
repo1-storage-host=backup-filer-1.my.lan
repo1-storage-verify-tls=y
repo1-storage-ca-file=/etc/pgbackrest/certs/ca.crt
repo1-host-cert-file=/etc/pgbackrest/certs/client.crt
repo1-host-key-file=/etc/pgbackrest/certs/client.key
repo1-s3-bucket=mydb
repo1-s3-endpoint=mydb
repo1-s3-key=S3KEY
repo1-s3-key-secret=S3CRET
repo1-s3-region=eu-central-1
process-max=4
start-fast=y

log-level-console=debug
log-level-file=debug

[global:archive-push]
compress-level=3

```

7. Describe the issue:
ERROR: [029]: unable to find child 'IsTruncated':0 in node 'ListAllMyBucketsResult' when calling: 
pgbackrest --stanza=demo --log-level-console=info stanza-create

Was testing with [seaweedfs](https://github.com/seaweedfs/seaweedfs) and [minio](https://github.com/minio/minio) s3 provider.

[chrislusf](https://github.com/chrislusf) gave me some hints: there might be a bug in [commit](https://github.com/pgbackrest/pgbackrest/commit/845d82f6825d4101e6a465a435ef056ff6ec15a2) with [SOAPListAllMyBuckets](https://docs.aws.amazon.com/AmazonS3/latest/API/SOAPListAllMyBuckets.html)

when i reverted back to v2.39, then creating the stanza works.

certs (host and client) are generated with [certgen](https://github.com/minio/certgen)

**Comment by dwsteele** [comment]
Hmm, we certainly don't use ListBuckets or the SOAP interface. This code is intended to be used with ListObjectsV2 ([ListBucketResult](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html#AmazonS3-ListObjectsV2-response-ListObjectsV2Output)) and not to list buckets.

We test with Minio so my guess is there is something odd going on with SeaweadFS.

**Comment by cernoel** [comment]
Had the same problem with minio, i first tried with seaweed, then with minio, because i also thought seaweed not might have implemented some stuff pgbackrest needs.

**Comment by dwsteele** [comment]
Then I believe something is off with the Minio configuration. We test extensively with Minio and have not seen this issue.

We should *never* get a `ListAllMyBucketsResult` because do not use the `ListAllMyBuckets` API.

**Comment by cernoel** [comment]
when i create the stanza with v2.39 and then upgrade pgbackrest to 2.40, all other commands (backup, push-archive,.) also work. (without changing the configuration in pgback and minio), so i assume that there is only a problem creating the stanza freshly on a new bucket, since i circumvented the issue by using v2.39, for me the problem is solved with minio. I try to test it with seaweed to see if it fixes it also there... or it might be a issue with the iam policy for the bucket/user .. i will try out some stuff.

**Comment by dwsteele** [comment]
Checking `IsTruncated` is new for 2.40 but should not cause a problem. It is a required field in the `ListBucketResult` response.
