### ISSUE TITLE
ERROR: [054]: unable to sync path

### ISSUE THREAD

**Issue by fatihsazan** [pgbackrest/pgbackrest#1828]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.40

2. PostgreSQL version:12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos8

4. Did you install pgBackRest from source or from a package? package

7. Describe the issue:
When we started the backup with pgbackrest, we were getting unable to sync path error. With repo1-type=cifs, this problem was fixed. When we want to test the backup we have received, we get the same error again.

`pgbackrest --stanza=stbackup --reset-pg1-host --pg1-path=/mnt/xback/pgdata --repo1-type=cifs  restore`
2022-08-03 12:13:17.415 P00   INFO: repo1: restore backup set 20220802-182007F_20220803-113300I, recovery will start at 2022-08-03 11:33:52
2022-08-03 12:13:17.415 P00   INFO: remap data directory to '/mnt/xback/pgdata'
ERROR: [054]: unable to sync path '/mnt/xback/pgdata': [22] Invalid argument
2022-08-03 12:13:17.621 P00   INFO: restore command end: aborted with exception [054]

When pgbackrest restore starts, it creates files under /mnt/xback/pgdata.

--df -h 
Filesystem                       Size  Used Avail Use% Mounted on
/dev/mapper/cl_x-root   80G  1.6G   75G   3% /
devtmpfs                         3.9G     0  3.9G   0% /dev
tmpfs                            3.9G     0  3.9G   0% /dev/shm
tmpfs                            3.9G   57M  3.8G   2% /run
tmpfs                            3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda2                        976M  100M  809M  11% /boot
/dev/sda1                       1022M  9.5M 1013M   1% /boot/efi
/dev/mapper/cl_x-home  8.8G  285M  8.0G   4% /home
tmpfs                            783M     0  783M   0% /run/user/0
//10.10.160.109/xback       36T   30T  6.3T  83% /mnt/xback

**Comment by pgstef** [comment]
Please provide the mount details for /mnt/xback.
`repo1-type` will refer to the backup location, not the PG data path location. As far as I know, we don't have an option to disable directory fsync of the pg-path (as it would be a bad idea to run PG on that kind of storage anyway).

**Comment by fatihsazan** [comment]
> Please provide the mount details for /mnt/xback. `repo1-type` will refer to the backup location, not the PG data path location. As far as I know, we don't have an option to disable directory fsync of the pg-path (as it would be a bad idea to run PG on that kind of storage anyway).

//10.10.160.109/xback /mnt/xback cifs rw,relatime,vers=2.0,sec=ntlmssp,cache=strict,username=xx,domain=xx,uid=1000,forceuid,gid=1000,forcegid,addr=10.10.160.109,file_mode=0755,dir_mode=0755,nounix,serverino,mapposix,rsize=65536,wsize=65536,echo_interval=60,actimeo=1 0 0

**Comment by dwsteele** [comment]
First -- I really, really would not run a Postgres cluster on CIFS, or any network file system for that matter. In our experience this reduces the reliability of the database by a lot.

Having said that, I wonder if we should follow PostgreSQL's lead here and automatically determine when directory fsyncs are allowed: https://github.com/postgres/postgres/blob/REL_15_BETA2/src/backend/storage/file/fd.c#L3730
```
	/*
	 * Some OSes don't allow us to fsync directories at all, so we can ignore
	 * those errors. Anything else needs to be logged.
	 */
	if (returncode != 0 && !(isdir && (errno == EBADF || errno == EINVAL)))
	{
```
There may be other filesystems that don't required directory fsync but are fine for running Postgres. Thoughts, @sfrost?

**Comment by sfrost** [comment]
Not really thrilled with it, but given that PG does it, I suppose we could if it's causing people issues.
