### ISSUE TITLE
pgbackrest archive.info got deleted unexpected while stsrting postgres it says archive.info file is missing 

### ISSUE THREAD

**Issue by Maddysaran** [pgbackrest/pgbackrest#1829]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.40 version
2. PostgreSQL version:
Postgresql 10 version 
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by dwsteele** [comment]
Not much we can do since you did not provide logs, configuration, or a description of the problem.

If this was the issue that was posted to pgsql-admin, you'll want to check the expiration settings on your bucket.

**Comment by Maddysaran** [comment]
Unable to find a valid repository 
File missing error unable to load file archive.info or archive.info.copy 
Unable to open file archive.info



The error is invalid check point record
Fatal : could not locate required checkpoint record

**Comment by Maddysaran** [comment]
Archive.info or archive.info.copy file is deleted after i ran restore command

**Comment by dwsteele** [comment]
None of this is actionable. We'd need the request configuration files and log files for the commands that had an issue. Lastly, we need a precise description of what happened, in some logical order.

I really don't think the restore command remove archive.info and archive.info.copy. What else was done?

And again, do you have any expiration set on your bucket: https://aws.amazon.com/blogs/aws/amazon-s3-object-expiration.
