### ISSUE TITLE
Question: Why pg and repo hosts cannot both be configured as remote ?

### ISSUE THREAD

**Issue by robinportigliatti** [pgbackrest/pgbackrest#1832]
Hello,

I am learning pgBackrest and wanted to make a dedicated backup server.

bd1 => Primary
bck1 => Dedicated backup server and is also used as a local repo (cf repo1)
bck2 => Remote repo (cf repo2)

1. pgBackRest version:
```
pgBackRest 2.40
```
2. PostgreSQL version:
```
postgres=# SELECT version();
-[ RECORD 1 ]----------------------------------------------------------------------------------------------------------------------------
version | PostgreSQL 13.7 (Ubuntu 13.7-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
```
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
All :
```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
4. Did you install pgBackRest from source or from a package? From package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - bd1 => Primary
```
[global]
repo1-host=bck1
repo1-host-port=22
repo1-host-user=postgres
repo1-path=/pgbackups
repo2-host=bck2
repo2-host-port=22
repo2-host-user=postgres
repo2-path=/pgbackups
# et si dépôt distant :  repo1-host , repo1-host-port, repo1-host-user

# le primaire est souvent déjà chargé : juste 2 processus
process-max=2

# Rétention & options classiques
repo1-retention-full=2
repo2-retention-full=2
start-fast=y
compress-type=bz2
compress-level=8

delta=y
log-level-console=info

# archivage : à garder ici en cas de bascule ou de archive_mode=always
[global:archive-push]
compress-type=gz
compress-level=1
log-level-console=info

[demo_stz]
pg1-path=/var/lib/postgresql/13/main

#recovery-option=primary_conninfo=host=bd3 user=repli port=5432
#recovery-option=primary_slot_name=bd1
#recovery-option=recovery_target_timeline=latest
```
    - bck1 => Dedicated backup server and is also used as a local repo (cf repo1)
```
[global]
repo1-path=/pgbackups

# et si dépôt distant :  repo1-host , repo1-host-port, repo1-host-user

# le primaire est souvent déjà chargé : juste 2 processus
process-max=2

# Rétention & options classiques
repo1-retention-full=2
start-fast=y
compress-type=bz2
compress-level=8

delta=y
log-level-console=info

# archivage : à garder ici en cas de bascule ou de archive_mode=always
[global:archive-push]
compress-type=gz
compress-level=1
log-level-console=info

[demo_stz]
db1-path=/var/lib/postgresql/13/main
pg1-host=bd1
pg1-host-port=22
pg1-host-user=postgres
```
    - bck2 => Remote repo (cf repo2)
```
[global]
repo2-path=/pgbackups

# et si dépôt distant :  repo1-host , repo1-host-port, repo1-host-user

# le primaire est souvent déjà chargé : juste 2 processus
process-max=2

# Rétention & options classiques
repo2-retention-full=2
start-fast=y
compress-type=bz2
compress-level=8

delta=y
log-level-console=info

# archivage : à garder ici en cas de bascule ou de archive_mode=always
[global:archive-push]
compress-type=gz
compress-level=1
log-level-console=info

[demo_stz]
db1-path=/var/lib/postgresql/13/main
pg1-host=bd1
pg1-host-port=22
pg1-host-user=postgres
```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
```
archive_command = '/usr/bin/pgbackrest --stanza=demo_stz archive-push %p'
archive_mode = on
listen_addresses = '*'
#max_wal_senders = 10		# max number of walsender processes
#wal_level = replica			# minimal, replica, or logical
port = 5432				# (change requires restart)
```
    - errors in the postgresql log file before or during the time you experienced the issue
```
postgres@bck1:~$ pgbackrest --stanza=demo_stz stanza-create
2022-08-08 14:41:48.898 P00   INFO: stanza-create command begin 2.40: --exec-id=24795-3947a508 --log-level-console=info --pg1-host=bd1 --pg1-host-port=22 --pg1-host-user=postgres --pg1-path=/var/lib/postgresql/13/main --repo1-path=/pgbackups --stanza=demo_stz
WARN: unable to check pg1: [OptionInvalidValueError] remote-0 process on 'bd1' terminated unexpectedly [32]: ERROR: [032]: local repo1 and repo2 paths are both '/pgbackups' but must be different
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
2022-08-08 14:41:49.426 P00   INFO: stanza-create command end: aborted with exception [056]
```

7. Describe the issue:

Not quite an issue but I am intrigued about why it is not possible to create a stanza on one of the repo server and having  error 32.

Since I am able to create a stanza on both bck1 and bck2 from bd1, why are we not able to do so from one dedicated backup server ? 

EDIT : 
Second question:

Why stanza-create has to be performed on bd1 and backup on repo host ?

Robin,

**Comment by robinportigliatti** [comment]
What I find very odd is this behaviour :

We configure the primary to use two repositories.

You can create the stanza from the primary and WAL are pushed on both repo1 and repo2.

When you try to launch the backup command on primary, you have the message `ERROR: [072]: backup command must be run on the repository host`. Why not... but should be possible.

But when you run the backup command on repo1, you can't configure repo1 to know about repo2 because the primary is remote and repo2 is remote too and you have `ERROR: [027]: pg and repo hosts cannot both be configured as remote`.

I think we should be able to do it.

You can run backup command on both repo1 and repo2 but only with repoX-path set to a local path.

**Comment by pgstef** [comment]
Hi,

The `backup` command has to run locally on the backup host and the `archive-push` command has to run locally on the database host. The idea is to _push_ archives and _pull_ backups. That's how it works with the local/remote process implementation.
It's also in the name of a "dedicated backup server". The idea is to take off the backup load from the database host.

Regarding the `stanza-create` and `check` commands, I can use them successfully from the database host or from the backup servers. You simply have to remove `repo1-path` and `repo2-path` from your *db1* config. I usually run it from database hosts though because they have the view on all the repositories and you only have to run it once rather than running `stanza-create` on each repo-host individually.

I admit the `ERROR: [032]: local repo1 and repo2 paths are both '...' but must be different` error can be confusing. I'm not sure where it comes from though.

Here's a simplified configuration that I just used and that seems to work properly:

- *pg1*

```ini
[global]
repo1-host=bck1
repo1-host-user=pgbackrest
repo2-host=bck2
repo2-host-user=pgbackrest

log-level-console=info
log-level-file=debug
process-max=2
compress-type=lz4

[global:archive-push]
compress-level=1
log-level-console=debug

[demo]
pg1-path=/var/lib/pgsql/14/data
```

- *bck1*

```ini
[global]
repo1-path=/backup_space
repo1-retention-full=2
log-level-console=info
log-level-file=debug
process-max=2
compress-type=lz4
delta=y
start-fast=y

[demo]
pg1-host=pg1
pg1-path=/var/lib/pgsql/14/data
```

- *bck2*

```ini
[global]
repo2-path=/backup_space
repo2-retention-full=2
log-level-console=info
log-level-file=debug
process-max=2
compress-type=lz4
delta=y
start-fast=y

[demo]
pg1-host=pg1
pg1-path=/var/lib/pgsql/14/data
```

Kind Regards

**Comment by robinportigliatti** [comment]
Hello @pgstef,

Thanks you, removing `repo1-path` from primary's `pgbackrest.conf` file worked.
