### ISSUE TITLE
looking for archiving/clean-up options

### ISSUE THREAD

**Issue by ikzelf** [pgbackrest/pgbackrest#1835]
1. pgBackRest version: 2.36

I guess this is more like a feature request.

For our clean-up operations we remove databases, their hosts and eventually the backups. Now I am looking for a way to archive the backup and backup configurations, just in case a system was removed that made someone sad.

When looking for options, I see the repo-ls command but I can not find a way to make it list the full path to the backup and archive directions. If I had, I could request those from pgbackrest and move them. Yes, I can try to read and interpret the config files but it would be better is pgbackrest would give this, this would make the procedure more portable.

An other possibility would be to add an archive-stanza option to pgbackrest. This should pickup the configuration for the specified stanza, together with the backups and move them to an archive location before we delete the stanza. In a weekly or monthly procedure we would remove the archive if no-one noticed/complained about the removal of the database.

Does my request make any sense? If not, I would be more than happy to clarify,

**Comment by pgstef** [comment]
The backup directory is pretty easy to parse:
```bash
$ pgbackrest repo-ls backup/stanza_name --filter="(F|D|I)$"
20220816-115234F
20220816-115234F_20220816-115238D
20220816-115234F_20220816-115241I
```

But the question is more: _what is a full path?_
When you speak about an NFS mount point, that's easy. But it isn't when you speak about S3 buckets, Azure containers,... pgBackRest supports multiple types of repository storage so it's probably more complicated than what you initially thought ;-)

Same for the WAL archives. They are stored in stream, and it is not that easy to identify which ones relate to which backup. Using the `--archive-copy` option might help though.

Ultimately, I believe that if we could have an "export to / import from local directory" backup function, it might help in such cases (move to longer retention term storage). That sounds like a good feature request to me but let's see what David thinks about this ;-)

**Comment by ikzelf** [comment]
Thanks for your response Stefan,
in my case it is about an NFS mount.
Something like an export/import --stanza looks like a good option. In that case pgbackrest in the only one that knows/needs to know where the backups are. Give a location to put the export in and all set. To make it fully complete it would also include the configuration files for that stanza. 

I am patiently waiting for more responses. And yes, of course I can script it all but I prefer that the backup tool handles this whenever possible.

A quicky would seem to be to give repo-ls and extra option to make the output full qualified instead of only relative. In that case I would need to write the archiving myself but at least I can use the given fullpath's.

**Comment by dwsteele** [comment]
> Ultimately, I believe that if we could have an "export to / import from local directory" backup function, it might help in such cases

We have a few similar features in mind (export from repo, stand-alone backup), but nothing on the roadmap yet.
