### ISSUE TITLE
Using pgbackrest with CitusDB 11

### ISSUE THREAD

**Issue by iamruhua** [pgbackrest/pgbackrest#1839]
Is that possible?
From my point of view (which is a newbie)
Because CitusDB can be configured with shards and replications, does that mean if I use pgbackrest with CitusDB 11, pgbackrest will backup each citus instance without considering the replication? So if I use 3 replication for each shard, the total storage used by pgbackrest will be 3 times?

**Comment by dwsteele** [comment]
You should be able to use whatever directions CitusDB has for using pg_basebackup and substitute pgBackRest. On a quick search I was not able to find *any* backup instructions for Citus, but I feel like they must be around somewhere.
