### ISSUE TITLE
Request for improvement support archive_mode=always

### ISSUE THREAD

**Issue by mroissetgem** [pgbackrest/pgbackrest#1840]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.40
2. PostgreSQL version:
14
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL8 two standbys + repmgr
4. Did you install pgBackRest from source or from a package?
rpm
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Hello, we use repmgr with automated failover. repmgr requires archive_mode=always on standby. 

Are you planning to implement this feature?
Many thanks
[postgres@~]$ repmgr node status
Node "tsdb-02":
        PostgreSQL version: 14.4
        Conninfo: host=x.x.x.x dbname=repmgr user=repmgr
        Role: standby
        WAL archiving: disabled (on standbys "archive_mode" must be set to "always" to be effective)
        Archive command: pgbackrest --stanza=xx archive-push %p

**Comment by pgstef** [comment]
Hi,

You could already theoretically do it. See the [archive-mode-check](https://pgbackrest.org/configuration.html#section-backup/option-archive-mode-check).

That isn't recommended though. See the documentation warning:

> WAL segments pushed from a standby server might be logically the same as WAL segments pushed from the primary but have different checksums. Disabling archiving from multiple sources is recommended to avoid conflicts.
>
> If this option is disabled then it is critical to ensure that only one archiver is writing to the repository via the archive-push command.

The archives are usually pushed from the primary and, thanks to `archive_mode=on`, the standby being promoted can start archiving as soon as it get promoted. The question is more about **why** you'd need archive-mode set to always and if you can make sure only 1 host is archiving WAL segments.

Kind Regards,

**Comment by dwsteele** [comment]
You can set `archive-mode-check=false` to allow pgbackrest to operate while `archive_mode=always`. But as Stefan says, you may run into WAL segments with different contents depending on whether they come from the primary or the standby.

Further, on some repo types there may be a race condition when files are being written. Object stores such as S3 should be fine, but Posix/CIFS filesystems might cause corruption. To avoid this the standby should be writing to a separate repo from the primary.

In the end, `archive_mode=always` is not supported by pgBackRest for these reasons.

**Comment by mroissetgem** [comment]
Ok sounds good to me. We use S3 buckets so I may setup differents buckets.
Thanks for your feedback. Much appreciated

**Comment by mroissetgem** [comment]
Solved
