### ISSUE TITLE
High CPU util in Minio S3

### ISSUE THREAD

**Issue by glushakov** [pgbackrest/pgbackrest#1843]
Hi
I'm have very high CPU utilization issue on my backup server (I'm using Minio) when using pgbackrest via S3.
In minio trace,  found that pgbackrest sends files with 5MB-parts (in the minio console it looks like s3.PutObjectPart... 5MB...) and thousands of this parts per second, in my opinion, causes high CPU utilization 
For comparison, I also tested wal-g, it sends files of 20MB-parts each and loads the CPU much less.
I also tried to change the parameters associated with the bundle and buffer, but this did not bring any significant changes.
pgbackrest really cuts files by 5 mb parts and it can't be changed?
pgbackrest 2.39
Thanks for any help

**Comment by dwsteele** [comment]
> pgbackrest really cuts files by 5 mb parts and it can't be changed?

Currently this cannot be changed, but it has always been our intention to make this configurable.

I have created a project card for this feature: https://github.com/pgbackrest/pgbackrest/projects/2#card-85158719.

**Comment by dwsteele** [comment]
@glushakov PR #1847 implements this feature, please have a look.

Also, how would you like your name to appear in the release notes?

**Comment by glushakov** [comment]
@dwsteele Thank you very much! 
You can use "Anton G."

**Comment by glushakov** [comment]
@dwsteele 
Hi. 
I was really looking forward to this change https://github.com/pgbackrest/pgbackrest/pull/1847 in the new release, but for some reason it is not there. Can you tell me when it will be added?

**Comment by dwsteele** [comment]
Not sure what you mean. It is in 2.41 which was released yesterday: https://github.com/pgbackrest/pgbackrest/commit/b05d31f531b55b747175cf94c963f95574c54d2b.

**Comment by glushakov** [comment]
@dwsteele 
Sorry, this is probably my misunderstanding. I read the release notes and didn't find this change in them
https://github.com/pgbackrest/pgbackrest/releases/tag/release%2F2.41

**Comment by pgstef** [comment]
Hi,
It's not necessarily because it is not mentioned in the release note that it's not there.
If you look at the [merge commit](https://github.com/pgbackrest/pgbackrest/commit/b05d31f531b55b747175cf94c963f95574c54d2b), you'll see that it's in the main branch **and** in the 2.41 release tag ;-)

**Comment by dwsteele** [comment]
Looks like I forgot to write a release note for this. I'll add one today.

**Comment by dwsteele** [comment]
@glushakov How would you like your name to appear in the release notes?

**Comment by glushakov** [comment]
@dwsteele Thanks. You can use "Anton Glushakov"
