### ISSUE TITLE
restore fails when pg2-path and pg1-host are configured

### ISSUE THREAD

**Issue by robinportigliatti** [pgbackrest/pgbackrest#1844]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

```
pgBackRest 2.40
```

3. PostgreSQL version:

```
 PostgreSQL 10.22 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bi
```

4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

5. Did you install pgBackRest from source or from a package?

From package

7. Please attach the following as applicable:

bd1: Primary

```
[global]
repo1-path=/pgbackups

process-max=2

repo1-retention-full=2
start-fast=y
compress-type=bz2
compress-level=8

delta=y
log-level-console=info

[global:archive-push]
compress-type=gz
compress-level=1
log-level-console=info

[demo_stz]
pg1-path=/var/lib/pgsql/10/data
```

bd2: Standby

```
[global]
repo1-path=/pgbackups

backup-standby=y
process-max=8    

repo1-retention-full=2
repo1-retention-diff=2
start-fast=y
compress-type=bz2
compress-level=8
delta=y
log-level-console=info

[global:archive-push]
compress-type=gz
compress-level=1

[demo_stz]
pg1-host=bd1
pg1-path=/var/lib/pgsql/10/data
pg2-path=/var/lib/pgsql/10/data

recovery-option=primary_conninfo=host=bd1 user=replica port=5432
recovery-option=primary_slot_name=bd2
recovery-option=recovery_target_timeline=latest
```

repo1-path is a shared folder.

8. Describe the issue:

1 - bd2 for some reason must be restored
2 - bd2 - `pgbackrest --stanza=demo_stz --type=standby --delta restore` results in `[037]: restore command requires option: pg1-path`.

Why do I need to comment out `pg1-host` and `pg2-path` to make it work ? Would'nt it be a general use case where I need to restore the standby server even when the backup is configured on a standby ?

Robin,

**Comment by pgstef** [comment]
That should work if you set pg1 being the local host and pg2 the remote. So pg1-path + pg2-path + pg2-host.

That's usually recommended because the indexes are used in priority order 1 > 2 > 3 ...

**Comment by robinportigliatti** [comment]
Thank you
