### ISSUE TITLE
Question about time retention policy

### ISSUE THREAD

**Issue by Maddysaran** [pgbackrest/pgbackrest#1845]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

pls share the retention policy parameter settings in pgbackrest.conf for 35 days..? i am using repo1-retention-full-type =time , repo1-retention-full=35 and repo1-retention-archive-type=full please share me the correct parameter to have 35 days and expire older than 35 days of incr,diff and archive if my settings is incorrect pls do share the correct one

**Comment by pgstef** [comment]
Hi,

As mentioned in the docs about [--repo-retention-full-type](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-full-type):

> Determines whether the repo-retention-full setting represents a time period (days) or count of full backups to keep. If set to time then full backups older than repo-retention-full will be removed from the repository if there is at least one backup that is equal to or greater than the repo-retention-full setting.
>
> For example, if repo-retention-full is 30 (days) and there are 2 full backups: one 25 days old and one 35 days old, no full backups will be expired because expiring the 35 day old backup would leave only the 25 day old backup, which would violate the 30 day retention policy of having at least one backup 30 days old before an older one can be expired.
>
> Archived WAL older than the oldest full backup remaining will be automatically expired unless repo-retention-archive-type and repo-retention-archive are explicitly set. 

`--repo-retention-archive-type` is full by default, so nothing to worry about here. The WAL archives will be removed according to the backups kept.

Setting `repo1-retention-full=35` with `repo1-retention-full-type=time` will keep the latest full backup older than 35 days and remove everything before that backup. It is not really possible to have "precisely" 35 days unless you know exactly your backup schedule but those settings are already a good first start.

Kind Regards
