### ISSUE TITLE
Question: Centralized backup server versus repo

### ISSUE THREAD

**Issue by robinportigliatti** [pgbackrest/pgbackrest#1846]
Hello,

Why didn't you implement the idea of a centralized backup server instead of repo ?

Here is my thought when I teach myself about pgbackrest these past weeks :

* repo should only act as a repo and shouldn't know about pgbackrest.
* The backup server may know about one or more stanza, initiate all necessary backups and push backups to repos.
* The backup server may act as a centralizer where archived wal would be pushed once, instead of multiple repos

Robin,

**Comment by pgstef** [comment]
Hi,

First of all, when using multiple repositories, you'd have a single point of failure with only one backup server. And that's what you want to avoid with multi-repo. However, you can already achieve something like what you describe...

Your repo-host (backup server) may have multiple stanza defined and initiate backups and push them to repos. Currently, the backup command can only stream to 1 repo at a time though.

Then, with one archive-push call, the WAL archive is pushed to all known repos. You can push it to a repo-host which will then send it to the remote repo, or you can directly push it to the remote repo (like S3,...) if you want to avoid the SPOF with your backup server.

The current arch has a lot of flexibility and possibilities. I agree it would be a nice feature to be able to push a backup to all known repositories. But it might be faster to first send it to repo1 and then copy it to repo2 though.
Afaik, the repo-to-repo copy feature is in the [backlog](https://github.com/pgbackrest/pgbackrest/projects/2#card-59620607).

Regards

**Comment by robinportigliatti** [comment]
Hello,

> First of all, when using multiple repositories, you'd have a single point of failure with only one backup server. And that's what you want to avoid with multi-repo. However, you can already achieve something like what you describe...

I understand but I'd rather lose just my scheduler than my scheduler AND my backups if compromised. Both architecture make sound to me.

> Your repo-host (backup server) may have multiple stanza defined and initiate backups and push them to repos. Currently, the backup command can only stream to 1 repo at a time though.

Since stanza is configured to push on a remote repo and if pg1 is remote, backup on repo2 does not work from repo1.

primary

```
[global]
repo1-host=bck1
repo1-host-port=22
repo1-host-user=postgres
repo2-host=bck2
repo2-host-port=22
repo2-host-user=postgres

# et si dépôt distant :  repo1-host , repo1-host-port, repo1-host-user

# le primaire est souvent déjà chargé : juste 2 processus
process-max=2

# Rétention & options classiques
repo1-retention-full=2
repo2-retention-full=2
start-fast=y
compress-type=bz2
compress-level=8

delta=y
log-level-console=info

# archivage : à garder ici en cas de bascule ou de archive_mode=always
[global:archive-push]
compress-type=gz
compress-level=1
log-level-console=info

[demo_stz]
pg1-path=/var/lib/postgresql/14/main

#recovery-option=primary_conninfo=host=bd3 user=repli port=5432
#recovery-option=primary_slot_name=bd1
#recovery-option=recovery_target_timeline=latest
```

bck1 

```
[global]
repo1-path=/pgbackups
repo2-host=bck2

# et si dépôt distant :  repo1-host , repo1-host-port, repo1-host-user

# le primaire est souvent déjà chargé : juste 2 processus
process-max=2

# Rétention & options classiques
repo1-retention-full=2
repo2-retention-full=2
start-fast=y
compress-type=bz2
compress-level=8

delta=y
log-level-console=info

# archivage : à garder ici en cas de bascule ou de archive_mode=always
[global:archive-push]
compress-type=gz
compress-level=1
log-level-console=info

[demo_stz]
pg1-path=/var/lib/postgresql/14/main
pg1-host=bd1
```

backup from repo1 results in:

```
pgbackrest --stanza=demo_stz --repo=2 --type=full backup
2022-08-23 12:12:57.894 P00   INFO: backup command begin 2.40: --compress-level=8 --compress-type=bz2 --delta --exec-id=10958-4704da73 --log-level-console=info --pg1-host=bd1 --pg1-path=/var/lib/postgresql/14/main --process-max=2 --repo=2 --repo2-host=bck2 --repo1-path=/pgbackups --repo1-retention-full=2 --repo2-retention-full=2 --stanza=demo_stz --start-fast --type=full
ERROR: [027]: pg and repo hosts cannot both be configured as remote
2022-08-23 12:12:57.894 P00   INFO: backup command end: aborted with exception [027]
```

This tells me that we can't stream to repo2 when both repo and pg1 are remote.

In your repo-to-repo feature I think it would be nice to implement this feature. What do you think ?

Robin,

**Comment by pgstef** [comment]
> I understand but I'd rather lose just my scheduler than my scheduler AND my backups if compromised. Both architecture make sound to me.

A repo-host is a backup server. And where you store your repo behind it is your choice (local, nfs, S3, Azure,...). So losing the repo-host would only lose the scheduler, not the backups.

> This tells me that we can't stream to repo2 when both repo1 and pg1 are remote.
> 
> In your repo-to-repo feature I think it would be nice to implement this feature. What do you think ?

As shown in the configs I shared with you on issue #1832, you indeed shouldn't define repo2-host on *bck1*. You want to use 2 separated dedicated backup hosts, you should trigger the backups from each one of them. With your example, losing bck1 would lose triggering the backups for repo2. So, you'd have a SPOF, which sounds bad to me compared to using 2 separated hosts.

> When the repo is remote it seems to me that we begin to be limited.

Repo can be local or remote, it doesn't change a lot. What changes is using repo hosts. You just have to understand how it works. It is just the place to pull backups. The repo-type behind the host doesn't change anything.

> It would be nice to be able to:
> 1 - Backup from the primary server => only possible if repo is not remote
> 2 - Backup from the standby server => only possible if repo is not remote

That's a choice. Or you are using a dedicated backup server to pull the backups, or not. However, if you use a remote storage (like nfs or S3), I'm pretty sure you could not define repo-host on pg1 and directly push archives and backups there. If you want to store your repo locally on the repo-host, that's indeed not possible.

> 3 - Backup on the repo from the primary server => possible only from one repo, waiting for repo-to-repo feature for multi repositories backup

Indeed, backup is one repo at a time. Probably we'll have something to copy from one repo to another in the future, but it isn't that easy to do.

> 4 - Backup on the repo from the standby server => not possible

Yes you can (I even wrote a [blog](https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html) post about it). You just have to define pg1-host + pg2-host + backup-standby. But you have the same limit : 1 repo at a time.

Overall, I'm sorry but I don't really get your point nor where you want to go. I kinda feel like you're trying to twist pgbr configs into every ways possible without really understanding the idea behind a repo-host. Usually, users are pushing things (archives and backups) directly from the PG host OR they use a dedicated repo-host (no matter what the repo-type is there) if they want to spare the load on the PG host, but not mixing both.
The repository concept is very flexible and offers a lot of possibilities. It just comes with that one limitation, you can't trigger backups from a PG host when you use a repo-host. And currently, you only can send a backup to 1 repo at a time.

I can't really add anything else to this explanation and, unless David has something else to share about this, I'd suggest we close this question/debate.

Regards,

**Comment by robinportigliatti** [comment]
Hello,

> Overall, I'm sorry but I don't really get your point nor where you want to go. I kinda feel like you're trying to twist pgbr configs into every ways possible without really understanding the idea behind a repo-host.

In fact yes, I had a lot of time to spare on pgbackrest and made a lot of scenarios on how to backup a cluster and arrived at a point where I was blocked on this two subjects.

> The repository concept is very flexible and offers a lot of possibilities. It just comes with that one limitation, you can't trigger backups from a PG host when you use a repo-host. And currently, you only can send a backup to 1 repo at a time.

Do you know why you can't trigger backups from a PG host when you use a repo-host ? Since you can create stanza and push wals to them.

Robin,
