### ISSUE TITLE
Backup Issue after restore "ArchiveMismatchError"

### ISSUE THREAD

**Issue by loehrson** [pgbackrest/pgbackrest#1851]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.40

2. PostgreSQL version:
12.11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
SLES 12 SP5

4. Did you install pgBackRest from source or from a package?
source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
Error in PostgreSQL logfile after Restore from Prod to Test:
repo1: [ArchiveMismatchError] PostgreSQL version 12, system-id 7094136943977743724 do not match repo1 stanza version 12, system-id 7093772844643635643
       HINT: are you archiving to the correct stanza?

7. Describe the issue:
For a refresh of our test environment we did a restore from a production stanza with pgbackrest which worked fine as expected.
After starting up the test, the system-id for this restored cluster obviously changed and the backup fails with the mismatch failure.

From the first sight, I cannot find it in the documentation, how to create a new "incarnation" of my stanza. 
Of course I could recreate the stanza, but is there another way of doing it? Is stanza-upgrade the preferred way of doing this?

Many thanks in advance and all the best
Roland

**Comment by dwsteele** [comment]
The system-id will only change after a `pg_upgrade`.  After `pg_upgrade` you do `stanza-upgrade`. If you didn't do `pg_upgrade` then I'd guess you are archiving to the wrong stanza.

**Comment by loehrson** [comment]
Many thanks for the quick response!
The system-id changed in test because it's a newly created pgbackrest clone from production.
For now, the stanza-upgrade did the job and I can use the same stanza for test as before. Both system-id are now represented in archive.info file. 
probably, for the next clone, I would have to re-create the stanza as the production system-id is already presented.
We can close this question.
