### ISSUE TITLE
Restore cluster from existing repository to new server?

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#1860]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
     v2.07 and v2.40.

2. PostgreSQL version:
    v9.6.24

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
    RHEL 6.10 and RHEL 8.6

4. Did you install pgBackRest from source or from a package?
    postgresql.org repositories

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
    I've got a Pg cluster installed on a RHEL 6.10 VM, and which is backed up locally using PgBR 2.07.  (Don't ask why it's still v2.07; it's depressing.)  Now "they" want me to move the cluster to a new VM running RHEL 8.6.
    After taking a final backup on the old system (let's call it RHEL610), and stopping Pg and PgBR on RHEH610, can I mount RHEH610's repository directory on new server RHEL86 using NFS, and use it to restore the old cluster?

**Comment by dwsteele** [comment]
> Don't ask why it's still v2.07; it's depressing.

Haha, I won't then.

> can I mount RHEH610's repository directory on new server RHEL86 using NFS, and use it to restore the old cluster?

Yes. The pgBackRest repo format has not changed since 1.00 so there should be no problem doing the restore. However, you'll need to rebuild all the indexes due to collation changes between the glibc versions. My guess is you are familiar with this issue, but just in case: https://www.crunchydata.com/blog/postgres-migration-pitstop-collations.

**Comment by RonJohn2** [comment]
> > can I mount RHEH610's repository directory on new server RHEL86 using NFS, and use it to restore the old cluster?
> 
> Yes. The pgBackRest repo format has not changed since 1.00 so there should be no problem doing the restore. 

Fantastic!

However, you'll need to rebuild all the indexes due to collation changes between the glibc versions. My guess is you are familiar with this issue, but just in case: https://www.crunchydata.com/blog/postgres-migration-pitstop-collations.

Yup.  Getting a list of all indices with text (whether varchar, char, etc) fields in them is high on my list.
