### ISSUE TITLE
[Feature request] option to cleanup manifest.gz files

### ISSUE THREAD

**Issue by caizixian** [pgbackrest/pgbackrest#1862]
Thanks for the great project.

I encountered a similar issue to #954. I use pgbackrest to do an incremental  ~every 15 mins (and daily full backup). I only keep the backup for the past week.

I notice that total size of `manifest.gz` files can get quite big due to the frequent backup. I wonder whether pgbackrest can add an option to cleanup the `manifest.gz` files when retiring backups.

**Comment by sfrost** [comment]
Really, you shouldn't be doing backups so often- what's the need for that?  You are archiving WAL, presumably, and that can replay to any point in time.

**Comment by dwsteele** [comment]
There's an option for history retention: https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-history

**Comment by caizixian** [comment]
@dwsteele thanks, that's the flag I was looking for.

@sfrost yes, I wanted to do point in time recovery down to ~15min granularity. I'm wondering whether there a better alternative.

**Comment by pgstef** [comment]
Hi

> @sfrost yes, I wanted to do point in time recovery down to ~15min granularity. I'm wondering whether there a better alternative.

That's exactly what you can do with [continuous WAL archiving](https://www.postgresql.org/docs/current/continuous-archiving.html).

You simply can set PG `archive_timeout` down to 15 minutes or less if you get a clear RPO. 

Kind Regards
