### ISSUE TITLE
Not a issue , A Query Please clarify

### ISSUE THREAD

**Issue by sridhar1270** [pgbackrest/pgbackrest#1863]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.37

2. PostgreSQL version:14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  docker container

4. Did you install pgBackRest from source or from a package? (apt-get install pgbackrest)

7. Describe the Query:
Please confirm , 
with repo storage as s3/minio

 **can i connect to minio /s3 endpoint without https if the config has params repo1-s3-verify-tls=n or repo1-storage-verify-tls=n**

If I can connect without https , what should be the configuration , as if endpoint given http://10.123.123.123
Getting Error **stderr: "ERROR: [029]: expected protocol 'https' in URL**

Any sample configuration where pgbackrest connects to 
1. http s3/minio
2. https s3/minio

Also minio listens on 9000  then can the endpoint be given as  http://10.123.123.123:9000 or 9000 should be specified as value for param repo1-storage-port=9000

Also for any query's should I have to raise a new issue or any forums where pgbackrest related query's can be asked

Thank you.

**Comment by sridhar1270** [comment]
@dwsteele Please confirm , Thanks

**Comment by sfrost** [comment]
https is required currently.

**Comment by sridhar1270** [comment]
Thank you @sfrost
