### ISSUE TITLE
Is there a good interface GUI for pgBackRest?

### ISSUE THREAD

**Issue by hermesalvesbr** [pgbackrest/pgbackrest#1864]
I have 8 databases of my clients to back up and check if the copy is not corrupted. Would pgBackRest help me with this?

If not, could you point me to a panel that would facilitate the management of database backups?

**Comment by dwsteele** [comment]
> I have 8 databases of my clients to back up and check if the copy is not corrupted. Would pgBackRest help me with this?

I'm not quite sure what you are asking here. If you are already using pgBackRest you can use the `verify` command to make sure your backups are not corrupt and the `info` command to get details about current backups.

> If not, could you point me to a panel that would facilitate the management of database backups?

There are a number of vendors that provide GUIs for pgBackRest as part of their cloud or packaged Postgres solutions, but I am not aware of any GUIs for pgBackRest specifically.
