### ISSUE TITLE
ERROR: [056]: unable to find primary cluster - cannot proceed  -  when attempting a backup

### ISSUE THREAD

**Issue by dbamarsh24** [pgbackrest/pgbackrest#1865]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:   2.33

2. PostgreSQL version:   12.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:    Ubuntu 12.3-1.pgdg18.04+1

4. Did you install pgBackRest from source or from a package?    Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
[pgbackrest_conf.txt](https://github.com/pgbackrest/pgbackrest/files/9527120/pgbackrest_conf.txt)
[postgresql_conf.txt](https://github.com/pgbackrest/pgbackrest/files/9527121/postgresql_conf.txt)

When running this command from a script:

pgbackrest --stanza=members_cluster --type=diff backup

...I receive the following error:

2022-09-08 13:23:21.313 P00   INFO: backup command begin 2.33: --exec-id=10764-655874f5 --log-level-console=info --log-level-file=info --log-path=/mnt/pg_backup/pgbackrest/log/members_cluster --pg1-path=/pg_data/data/members_cluster --pg1-port=5432 --process-max=2 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/mnt/pg_backup/pgbackrest --repo1-retention-diff=5 --repo1-retention-full=1 --stanza=members_cluster --type=incr
WARN: unable to check pg-1: [DbQueryError] unable to select some rows from pg_settings
      HINT: is the backup running as the postgres user?
      HINT: is the pg_read_all_settings role assigned for PostgreSQL >= 10?
ERROR: [056]: unable to find primary cluster - cannot proceed
2022-09-08 13:23:21.622 P00   INFO: backup command end: aborted with exception [056]

This command was working, but appears that the last successful backup on this server was on 03/22/22.  Unfortunately, we didn't notice this until just yesterday as our monitoring tool wasn't catching the error.  Is there any way for us to reconnect somehow?  We don't know what the HINT means about pg_read_all_settings role.  We haven't changed anything.

**Comment by sfrost** [comment]
The command you said you ran and what you shared from the log are clearly different as you asked for a --type=diff and the log says --type=incr, so you're mixing things up somewhere.

The error is pretty clear though- the user that pgbackrest logs in as needs to be able to read pg_settings and evidently it isn't able to currently.  That's what you need to fix.  One way to fix it might be to GRANT the user that pgbackrest is logging into PG as that pg_read_all_settings role.  Another would be to have pgbackrest log in as the superuser.  Ultimately, this is a configuration error, not an issue with pgbackrest.

**Comment by dbamarsh24** [comment]
Hi Steve,

Thanks for the quick reply.  Maybe I wasn't clear in my post, so sorry about that.

I have a script that executes a command to do backups nightly.  Depending on the day of the week, it does a full, differential, or incremental backup.  1st of the month is a full, Sundays are differential, and daily is incremental.  For weekdays, the command being executed from the script is:

pgbackrest --stanza=${CLSTR_NAME} --type=incr backup

(sorry, I cut and pasted the wrong line before)

The expanded command I showed was the correct command that was run.

I am running the script as the postgres OS user with no switches on the command line to change user, so I'm assuming I'm running the backup as the postgres database user as well, so superuser.  Note that if I run the command "pgbackrest check --stanza=members_cluster", I do get a response:

postgres@members-pg-stats:~/scripts$ pgbackrest check --stanza=members_cluster
2022-09-09 16:35:10.317 P00   INFO: check command begin 2.33: --exec-id=23822-2f50f8f9 --log-level-console=info --log-level-file=info --log-path=/mnt/pg_backup/pgbackrest/log/members_cluster --pg1-path=/pg_data/data/members_cluster --pg1-port=5432 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/mnt/pg_backup/pgbackrest --stanza=members_cluster
2022-09-09 16:35:10.921 P00   INFO: check repo1 configuration (primary)
2022-09-09 16:35:11.124 P00   INFO: check repo1 archive for WAL (primary)
2022-09-09 16:35:12.327 P00   INFO: WAL segment 000000010000023D0000002E successfully archived to '/mnt/pg_backup/pgbackrest/archive/members_cluster/12-1/000000010000023D/000000010000023D0000002E-e39bee63dc927e862f9243e8c94e5a10f1fb0224.gz' on repo1
2022-09-09 16:35:12.327 P00   INFO: check command end: completed successfully (2011ms)

So, it seems like pgbackrest can connect for some things.  As I said, this was running for a while.  We didn't notice (our bad) when it stopped and no configuration changes were made that I'm aware of.  Not sure what else I can supply to help

**Comment by dbamarsh24** [comment]
If we are unable to address this, would a stanza-delete / stanza-create process address the issue?  I'm aware that it will invalidate all prior backups for restore purposes, but we're way past that right now.

**Comment by dbamarsh24** [comment]
Hi Steve,

Nevermind.  I just found the issue.  Unfortunately, I was unaware that the PGUSER and PGPASSWORD were set to a non-superuser account in one of the config files we're importing to the script.  Because of that, the script wasn't running.  This is definitely a configuration issue.  I'm running the script with the proper user credentials now and it appears to be working.  Thank you for your assistance!!
