### ISSUE TITLE
pgbackrest info --output=json returns incorrect system identifier

### ISSUE THREAD

**Issue by feikesteenbergen** [pgbackrest/pgbackrest#1868]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.40

2. PostgreSQL version: 14.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

`pgbackrest info --output=json` returns a wrong system identifier. It looks truncated.

To reproduce:

```console
postgres@example:~$ pgbackrest repo-get backup/an/backup.info | grep 7101938
db-system-id=7101938132337160242
1={"db-catalog-version":202107181,"db-control-version":1300,"db-system-id":7101938132337160242,"db-version":"14"}
postgres@example:~$ pgbackrest info --output=json | jq '.[0].db[0]'
```
```json
{
  "id": 1,
  "repo-key": 1,
  "system-id": 7101938132337160000,
  "version": "14"
}
```

The system identifier returned by `pg_controldata` is 7101938132337160242, which matches the `backup.info` file of the s3 bucket.

```diff
--- backup.info
+++ info --output=json   
@@ -1 +1 @@
-7101938132337160242
+7101938132337160000
```

The output of the `info --output=json` seems to be truncated somehow, haven't looked at the source code, but perhaps the identifier is handled as a float somewhere?

**Comment by feikesteenbergen** [comment]
Ah, that might be it will check!

**Comment by dwsteele** [comment]
I tried with `jq` 1.6 and it is still truncating.

Anyway, not much we can do about it except document the issue, which we have already done.

**Comment by feikesteenbergen** [comment]
Yeah, I have it with:

```
$ jq --version
jq-1.6
```

**Comment by dwsteele** [comment]
According to the docs it should not truncate these numbers unless math is being done: https://stedolan.github.io/jq/manual/v1.6/#Basicfilters. That was added to the docs in 1.6 but it does not seem to work as far as I can tell.
