### ISSUE TITLE
Backup from any patroni node to S3 without repo server.

### ISSUE THREAD

**Issue by kolbasky** [pgbackrest/pgbackrest#1869]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

**1. pgBackRest version**: 
`2.40`

**2. PostgreSQL version**: 
`14`

**3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each**: 
`Debain 10`

**4. Did you install pgBackRest from source or from a package?** 
`apt package`

**5. Please attach the following as applicable:**
```
[sandbox_pg]
pg1-path=/opt/patroni/data/14/sandbox
pg2-host=test-pg-vm02
pg2-path=/opt/patroni/data/14/sandbox
pg2-host-cert-file=/etc/pgbackrest/test-pg-vm02.crt
pg2-host-key-file=/etc/pgbackrest/test-pg-vm02.key
pg2-host-ca-file=/etc/pgbackrest/ca.crt
pg2-host-type=tls
pg3-host=test-pg-vm03
pg3-path=/opt/patroni/data/14/]sandbox
pg3-host-cert-file=/etc/pgbackrest/test-pg-vm03.crt
pg3-host-key-file=/etc/pgbackrest/test-pg-vm03.key
pg3-host-ca-file=/etc/pgbackrest/ca.crt
pg3-host-type=tls

[global]
repo1-retention-full=3
repo1-type=s3
repo1-path=/sandbox_pg
repo1-s3-endpoint=s3.server.com
repo1-s3-bucket=pg-backup
repo1-s3-uri-style=path
repo1-s3-region=us-west-3
repo1-s3-key=sdasdasdasdasda
repo1-s3-key-secret=asdasdasdafghjdtgv

start-fast=y
delta=y
backup-standby=y

compress-type=lz4

log-level-console=info
log-level-file=debug

tls-server-address=*
tls-server-cert-file=/etc/pgbackrest/test-pg-vm01.crt
tls-server-key-file=/etc/pgbackrest/test-pg-vm01.key
tls-server-ca-file=/etc/pgbackrest/ca.crt
tls-server-auth=test-pg-vm01=sandbox_pg
tls-server-auth=test-pg-vm02=sandbox_pg
tls-server-auth=test-pg-vm03=sandbox_pg
```

archive_command: `pgbackrest --stanza=sandbox_pg archive-push %p`

Error in postgresql logs is `ERROR: [072]: archive-push command must be run on the PostgreSQL host`
Pgbackrest log says
```
ERROR: [082]: WAL segment 000000010000000000000015 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
```
archive-push command looks like so:
`archive-push command begin 2.40: [pg_wal/000000010000000000000001] --compress-type=lz4 --exec-id=29054-30406916 --log-level-console=info --log-level-file=debug --pg1-host=test-pg-vm01 --pg3-host=test-pg-vm03 --pg1-host-ca-file=/etc/pgbackrest/ca.crt --pg3-host-ca-file=/etc/pgbackrest/ca.crt --pg1-host-cert-file=/etc/pgbackrest/test-pg-vm01.crt --pg3-host-cert-file=/etc/pgbackrest/test-pg-vm03.crt --pg1-host-key-file=/etc/pgbackrest/test-pg-vm01.key --pg3-host-key-file=/etc/pgbackrest/test-pg-vm03.key --pg1-host-type=tls --pg3-host-type=tls --pg1-path=/opt/patroni/data/14/sandbox --pg2-path=/opt/patroni/data/14/sandbox --pg3-path=/opt/patroni/data/14/sandbox --repo1-path=/sandbox_pg --repo1-s3-bucket=pg-backup --repo1-s3-endpoint=s3.server.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-west-3 --repo1-s3-uri-style=path --repo1-type=s3 --stanza=sandbox_pg`

**6. Describe the issue:**
I have 3 node patroni cluster and S3 bucket to store backups. Builtin TLS server is used for communication between nodes.
I was trying to setup configuration without separate repo-server, since all the backups are to be stored in S3 anyway.
I want to be able to run backup command from any of the nodes and make backup run with backup-standby=y.
Of course  tls-server-cert-file & tls-server-key-file options differ.
and [sandbox_pg] section differs between nodes - pgN-host and other parameters are specified only for non-local hosts.

_node1_
```
[sandbox_pg]
pg1-path=/opt/patroni/data/14/sandbox
pg2-host=test-pg-vm02
pg2-path=/opt/patroni/data/14/sandbox
pg2-host-cert-file=/etc/pgbackrest/test-pg-vm02.crt
pg2-host-key-file=/etc/pgbackrest/test-pg-vm02.key
pg2-host-ca-file=/etc/pgbackrest/ca.crt
pg2-host-type=tls
pg3-host=test-pg-vm03
pg3-path=/opt/patroni/data/14/sandbox
pg3-host-cert-file=/etc/pgbackrest/test-pg-vm03.crt
pg3-host-key-file=/etc/pgbackrest/test-pg-vm03.key
pg3-host-ca-file=/etc/pgbackrest/ca.crt
pg3-host-type=tls
```
_node2_
```
pg1-host=eefremov-test-pg-vm01
pg1-path=/opt/patroni/data/14/sandbox
pg1-host-cert-file=/etc/pgbackrest/eefremov-test-pg-vm01.crt
pg1-host-key-file=/etc/pgbackrest/eefremov-test-pg-vm01.key
pg1-host-ca-file=/etc/pgbackrest/ca.crt
pg1-host-type=tls
pg2-path=/opt/patroni/data/14/sandbox
pg3-host=eefremov-test-pg-vm03
pg3-path=/opt/patroni/data/14/sandbox
pg3-host-cert-file=/etc/pgbackrest/eefremov-test-pg-vm03.crt
pg3-host-key-file=/etc/pgbackrest/eefremov-test-pg-vm03.key
pg3-host-ca-file=/etc/pgbackrest/ca.crt
pg3-host-type=tls
```
etc

what am i doing wrong?
Is such configuration even possible? Or do I have to setup repohost anyway? In this situation it is more like just a jump-host to me))

**Comment by kolbasky** [comment]
seems, like I made it work by adding another conf file on each node with follwoing contents
/etc/pgbackrest2.conf
```
[sandbox_pg]
pg1-path=/opt/patroni/data/14/sandbox/
pg1-socket-path=/var/run/postgresql

[global]
repo1-type=s3
repo1-path=/sandbox_pg
repo1-s3-endpoint=server.s3.com
repo1-s3-bucket=pg-backup
repo1-s3-uri-style=path
repo1-s3-region=us-west-3
repo1-s3-key=sdfsdfsd
repo1-s3-key-secret=asdasfsdfsdgsgr

compress-type=lz4

log-level-console=info
log-level-file=debug
```
then I changed `archive_command` and `restore_command` in postgres to `pgbackrest --config=/etc/pgbackrest2.conf --stanza=sandbox_pg archive-push` and `pgbackrest --config=/etc/pgbackrest2.conf --stanza=sandbox_pg archive-get %f %p` accordingly.
for all other purposes the default config is used.

I am still not sure if this is the correct way of doing it.

**Comment by kolbasky** [comment]
Does anyone have any ideas on how it should be done?
Since configs are 99% identical it seems to me it should work with one.

**Comment by dwsteele** [comment]
The `archive-get` command always considers `pg1` to be the local pg host. So if you have a host configured for `pg1` it won't work. I'm surprised that `archive-get` works since it performs exactly the same check.

In general, the configuration you want will lead to asymmetric configs on each host.

**Comment by kolbasky** [comment]
Thanks for the clarification. My configs were asymmetric, but localhost was not always pg1. pg1 was local on host1, pg2 was local on host 2 etc. Didn't realize it has to be pg1 always. 

Everything works now as expected with just one config! Thanks again!

p.s.: archive-get also failed. that's why i had to specify another config for both restore and archive commands.

**Comment by dwsteele** [comment]
> archive-get also failed.

Yes, I see I had taken one of your statements above out of context. Glad you have it working now!
