### ISSUE TITLE
Suggestions for getting WAL file path post archiving

### ISSUE THREAD

**Issue by sridhar1270** [pgbackrest/pgbackrest#1870]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.37

2. PostgreSQL version:14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: docker container

4. Did you install pgBackRest from source or from a package? (apt-get install pgbackrest)

Query:
How to get the path of wal file archived,

As WAL file will get archived, when archive time out occurs/ when WAL file size is greater than config size
postgres will call the archive_command  , where  pgbackrest will archive the WAL file in repo
**archive_command='pgbackrest --stanza=main archive-push %p'**  

Anyway, can we get the path of archive WAL in repo?

When the pgbackrest check command is executed it switches a WAL and the path is displayed

```
postgres@225f26f4a63f:/var/log/pgbackrest$ pgbackrest --stanza=main --log-level-console=info check
2022-09-14 20:45:43.913 P00   INFO: check command begin 2.37: --exec-id=10123-4171bf45 --log-level-console=info --pg1-path=/var/lib/postgresql/14/main --repo1-path=/var/lib/pgbackrest --stanza=main
2022-09-14 20:45:44.526 P00   INFO: check repo1 configuration (primary)
2022-09-14 20:45:44.732 P00   INFO: check repo1 archive for WAL (primary)
2022-09-14 20:45:44.935 P00   INFO: WAL segment 00000001000000000000000A successfully archived to '/var/lib/pgbackrest/archive/main/14-1/0000000100000000/00000001000000000000000A-c2476aef0afde00cc42ffcd116cfe8104243ca8e.gz' on repo1
2022-09-14 20:45:44.935 P00   INFO: check command end: completed successfully (1025ms)
postgres@225f26f4a63f:/var/log/pgbackrest$
```
   
**path is '/var/lib/pgbackrest/archive/main/14-1/0000000100000000/00000001000000000000000A-c2476aef0afde00cc42ffcd116cfe8104243ca8e.gz**

Any command/way for getting the archived WAL file path in repo (i.e when archive command is executed by postgres)

pgbackrest info jq only archive min,max wal info exists

ThankYou.

**Comment by kolbasky** [comment]
you can get WAL path inside repo like so
`STANZA=main; WAL=000000010000000100000035; pgbackrest repo-ls --recurse | grep "${STANZA}.*${WAL}"`
there is a built-in --filter option, but i had bad luck using it (double free or corruption error. always). Maybe your milage will vary, though.

**Comment by dwsteele** [comment]
> there is a built-in --filter option, but i had bad luck using it

@kolbasky Have you tried this recently? I believe we fixed a bug in this area a while back but not sure if it was this one specifically.

**Comment by dwsteele** [comment]
> Any command/way for getting the archived WAL file path in repo (i.e when archive command is executed by postgres)

Not specifically, you can do what @kolbasky suggested but it is not very efficient since it will go and grab the entire WAL archive to get the one file path. If it's a one off thats probably fine, but I wouldn't automate it.

**Comment by sridhar1270** [comment]
Thank you @kolbasky @dwsteele for the response , 
**Another query:**
In pgbackrest in archive folder WAL's gets archived in different folders , for example On What basis pgbackrest creates new folders

Is below logic applied , Please clarify

- Create Folder by checking wal file name , i.e say **000000010000001900000000-5a930cc4cd9549e74ee6685e6a3182648aa0efb5.gz**
- By above WAL , get folder name to be 0000000100000019 , and all wal files till 0000000100000019*FF will be placed in side this folder
- When WAL file changes from say 0000000100000019 to 000000010000001A a new folder by name 000000010000001A will be created
- 

First Image , list of dir's in archive folder 
Second Image , contents of 000000010000001A directory

![folders_within_archive](https://user-images.githubusercontent.com/29734645/190316928-4bce9cba-abf9-458a-94a5-a861ee36fd34.jpg)
![Contents_Of_000 1A](https://user-images.githubusercontent.com/29734645/190316934-ebe0e358-58f5-4a63-a746-4f91386a309a.jpg)

**Comment by kolbasky** [comment]
@dwsteele i have tried it as i was writing the reply. pgbackrest version is 2.40

**Comment by dwsteele** [comment]
@kolbasky I was able to reproduce it. I created PR #1871 with a fix.

**Comment by sridhar1270** [comment]
> Hi,
> 
> A WAL segment name has 3 parts of 8 digits:
> 
> * timeline id
> * WAL id
> * WAL segment number (chunks of by default 16Mo)
> 
> So, here you see the segments grouped by WAL id.
> 
> It might look simple to you to get a file path because you're obviously on a local filesystem, but it might not be possible for remote storage (S3, Azure,...). So providing a "fit for all" solution isn't that easy.
> 
> The question would rather be "why" do you need that info? What's the use-case exactly?
> 
> Kind Regards

@pgstef as of now using filter command as suggested by @kolbasky ,able to get the path, need to share the file paths to another app , which copies the wal's for their internal processing  , this can be avoided if pgbackrest multiple repo's is configured 
@pgstef  Thank you, have referred all your blogs w.r.t pgbackrest , it's great, and learnt a lot and was really helpful
