### ISSUE TITLE
option-db-include make other database in the cluster useless. 

### ISSUE THREAD

**Issue by jianheMark** [pgbackrest/pgbackrest#1872]
Follow thorugh: https://pgbackrest.org/user-guide.html#restore/option-db-include
`/usr/local/pgsql15/bin/pg_ctl -D /usr/local/pgsql15/data_42091266 restart`
Since I didn't speify `-l` all the log is in stdout. 
based on log, if I understand correctly.     
You need shut down cluster, do a backup. then recovery selected database say DB1. 
then restart the cluster. now you can only use DB1. 
all other database in this cluster is useless for now. 

So it's possible that I recover DB1 at this time.  and later recover all other databases in the same cluster.

**Comment by dwsteele** [comment]
It's not clear to me what you are asking here.

> You need shut down cluster, do a backup

This is not correct. The cluster should be running when you do a backup.

> So it's possible that I recover DB1 at this time. and later recover all other databases in the same cluster.

If I understand you correctly, then yes, but this statement is pretty vague.

**Comment by jianheMark** [comment]
```
sudo  -u jian pgbackrest --stanza=pgsql15_3 --delta \
    --db-include=test2 --type=immediate \
    --target-action=promote \
    restore
```

After this command, in this cluster,only **test2** can be used/connected, all other (test1,test15) cannot used. 
Bacause the guide said just drop database test1. I am wondering is there any command that not interrupt the test2 usage also. restore test1, test15. 
Obviously  omit --db-include option will work.
And also the following command will work.   
```
sudo -u jian pgbackrest --stanza=pgsql15_3 --delta \
    --db-include=test2 \
    --db-include=test1 \
    --db-include=test15 \
    --type=immediate --target-action=promote \
    --log-level-console=info restore
```

So in the end, I am just wondering what's the use case of --db-include. I feel like, You have more dbs, one have priority restored, but all others is in down time.

**Comment by pgstef** [comment]
Hi,

I still can't see what you're asking. The PG physical backup method requires to backup / restore an entire cluster (with all its databases). The pgBackRest `db-include` option is a "trick" to only restore the specified database(s) and wipe out the others. That saves some disk space and restore time when only 1 db in the cluster is needed.

When you have `test1`, `test2` and `test15`, indeed using `--db-include=test2` will wipe out test1 and test15, so you'll need to `DROP database test1; DROP database test15;` afterwards.

Obviously nor PG nor pgBackRest support multiple point-in-time targets within the same recovery. You only can go back in time to 1 specific target, and the recovery applies to the entire cluster.

If you want to rollback only 1 db but not the others, you'll have to restore using db-include, then extract from that restored cluster that db (using pg_dump) and re-inject it in your other cluster with the other databases (using pg_restore).

Regards
