### ISSUE TITLE
incr backup references latest backup label of an expired backup in a check and fails

### ISSUE THREAD

**Issue by ikzelf** [pgbackrest/pgbackrest#1873]
1. pgBackRest version: 2.40
2. PostgreSQL version: 12.1
3. Operating system/version: rhel-8.6
4. Did you install pgBackRest from source or from a package? yum package
5. conf + log extract in [pgbackrest-2.40-expired.log](https://github.com/pgbackrest/pgbackrest/files/9583177/pgbackrest-2.40-expired.log)

7. Describe the issue:

We did a 
full       20220915-130608F
full       20220915-130650F
incr      20220915-130650F_20220915-130846I
expire  20220915-130650F 
incr      fail

2022-09-16 08:13:07.943 P00  ERROR: [106]: new backup label '20220915-130608F_20220916-081305I' is not later than latest backup label '20220915-130650F_20220915-130846I'

it looks like pgbackrest-2.40 has some memory about the -manually- expired incremental backup that was part of 20220915-130650F 
2022-09-15 13:25:50.529 P00   INFO: repo1: remove expired backup 20220915-130650F_20220915-130846I
2022-09-15 13:25:50.642 P00   INFO: repo1: remove expired backup 20220915-130650F
The new incr backup is correctly based on the full of 0220915-130608F but a consistency check goes wrong.

I think this is a bug. In case this is not a bug, please educate me.

**Comment by dwsteele** [comment]
Looks like a bug to me as well, but not sure how to go about fixing it yet. It could be that we would ignore the history in this case but that may have its own pitfalls.

For now you can make a new full backup to get past this issue.

**Comment by ikzelf** [comment]
Thanks for the confirmation. I expected that the info returned by the info command would be leading here .... That info seems to be correct.

**Comment by dwsteele** [comment]
Info should be correct. This has to do with the manifests stored in `backup.history`. We expect backup labels to be ascending (even vs history), but the introduction of adhoc expire has introduced a bit of an issue with that.

Really not sure how to go about fixing this, but we'll definitely need to review past changes in this area before proceeding.

**Comment by ikzelf** [comment]
In the backup.history I see that the manifest files of the expired backups are available. All of them (since start usage of pgbackrest?)
-rw-r-----. 1 pgbackrest pgbackrest 65431 Sep 12 08:13 20220912-081305F.manifest.gz
-rw-r-----. 1 pgbackrest pgbackrest 65223 Sep 13 08:13 20220912-081305F_20220913-081304I.manifest.gz
-rw-r-----. 1 pgbackrest pgbackrest 65741 Sep 14 08:13 20220912-081305F_20220914-081304I.manifest.gz
-rw-r-----. 1 pgbackrest pgbackrest 65379 Sep 15 08:13 20220912-081305F_20220915-081304I.manifest.gz
-rw-r-----. 1 pgbackrest pgbackrest 65461 Sep 15 13:05 20220912-081305F_20220915-130500I.manifest.gz
-rw-r-----. 1 pgbackrest pgbackrest 65181 Sep 15 13:06 20220915-130608F.manifest.gz
-rw-r-----. 1 pgbackrest pgbackrest 65174 Sep 15 13:07 20220915-130650F.manifest.gz
-rw-r-----. 1 pgbackrest pgbackrest 65316 Sep 15 13:08 20220915-130650F_20220915-130846I.manifest.gz
-rw-r-----. 1 pgbackrest pgbackrest 65501 Sep 19 08:13 20220919-081304F.manifest.gz
-rw-r-----. 1 pgbackrest pgbackrest 65680 Sep 20 08:13 20220919-081304F_20220920-081304I.manifest.gz

Maybe it is an idea to reflect the expiration status of the backups also in the manifests?
What exactly is the intention of those manifest files?
Do they play a role of restores from secondary backup? (1st to disk, 2nd to tape, remove from disk, oops need it, restore from tape and use the manifest to be able to process the restored backup?)

**Comment by pgstef** [comment]
Hi,

There's a retention setting specifically for those files: [`--repo-retention-history`](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-history).

**Comment by ikzelf** [comment]
Thanks, having repo-retention-history=0 to retain the backup history only for unexpired backups could be a valid workaround for us, for now.

**Comment by dwsteele** [comment]
> having repo-retention-history=0 to retain the backup history only for unexpired backups could be a valid workaround for us

Ah, yes, that should work for now.

**Comment by dwsteele** [comment]
@andr-sokolov It looks like https://github.com/arenadata/pgbackrest/commit/ed3c519b5d389e47c1c553e5e597ecacac4e3383 fixes this issue.

Could you submit a PR for it?

**Comment by andr-sokolov** [comment]
> @andr-sokolov It looks like [arenadata@ed3c519](https://github.com/arenadata/pgbackrest/commit/ed3c519b5d389e47c1c553e5e597ecacac4e3383) fixes this issue.
> 
> Could you submit a PR for it?
@dwsteele, Done

**Comment by dwsteele** [comment]
Closing since there is a PR now to fix this.
