### ISSUE TITLE
Backup from Standby with `archive_mode = always`

### ISSUE THREAD

**Issue by rezemble** [pgbackrest/pgbackrest#1876]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: `2.4.0`
2. PostgreSQL version: `12`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: `Debian 5.10.70-1`

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
`pgbackrest.conf`:
```
[main]
pg1-path=/var/lib/postgresql/data
pg1-database=db

[global]
repo1-type=s3
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-bucket=BUCKET
repo1-s3-key=KEY_ID
repo1-s3-key-secret=KEY_SECRET
repo1-s3-region=S3_REGION

process-max=8
start-fast=y
delta=y
repo1-retention-full=2
archive-mode-check=n
archive-check=y
checksum-page=y
```

7. Describe the issue:
I would like to Backup exclusively from a standby server - using it to write WAL Archives as well as Backup.
From what I gathered from similar Tickets, the main reason `archive_mode = always` is discouraged is lack of exclusion locking on the repo archive - this is not an issue in this case, since only the standby actually generated archives - the archiving is working fine, too - but the backup fails, rather predictably, with
```
[056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
```
of course, the standby is in recovery, but does that pose an actual problem in this scenario or could that check just be disabled in this case?

**Comment by pgstef** [comment]
Hi,

Currently, you can't take a backup completely from a standby. You'll have to define both primary and standby in your configs.

Simply said, the backup control session is executed against the primary (pg_start/stop_backup), the backup will also wait that the standby replay is synced with the primary and, finally, copy the pg_control file from the primary.

So, that's kind of an hybrid situation, but the actual data files will come from the standby.

Kind Regards

**Comment by rezemble** [comment]
Hi @pgstef, thanks for the quick reply!
I was afraid of that - we're trying to avoid modifying the primary deployment as much as possible, and since archive lag can theoretically impact primary performance or even cause panic shutdowns with sync use, having a standby instance fail would be "less dramatic" - is the `pg_control` being copied a necessity? From what I figure, Standby instances generally do not have one until promoted - would such a state suffice? being able to restore a backup and subsequently promote it would probably catch the worst scenarios...

I understand it's not currently possible to treat a standby with continuous archiving as a primary - but could it be, or is `pg_control` such a fundamental, non-recoverable issue?

Thank you in advance!

**Comment by pgstef** [comment]
The pg_control information is used at several places, i.e. to ensure your backup [match the repo stanza definition](https://github.com/pgbackrest/pgbackrest/blob/08a44be4c38e4bc72a20c19d764be8a673c9b909/src/command/backup/backup.c#L234).

There are other safety nets, like [making sure the standby replication isn't lagging too far behind the primary](https://github.com/pgbackrest/pgbackrest/blob/08a44be4c38e4bc72a20c19d764be8a673c9b909/src/command/backup/backup.c#L880).

So it's not only just about copying the pg_control file. I don't really get your point about `avoid modifying primary deployment` nor `cause panic shutdowns with sync use` anyway. With the non-exclusive backup method, if you don't archive from the primary, you shouldn't face any performance issue nor panic shutdown due to archive_command failures.

**Comment by rezemble** [comment]
I see, that makes sense - I don't quite understand the last part, ` if you don't archive from the primary` - does that refer to WAL or Backup?

If WAL, would it be sensible to have the `archive_command` only configured on the standby (with `archive_mode = always`) and reference the primary only for access to `pg_control`?

Either way, that would mean having to inject either an SSH or TLS server into the image, since the primary is run in a cloud environment in docker. Do you know of an "official" way to accomplish this?

Either way - thanks a lot!

**Comment by pgstef** [comment]
> I see, that makes sense - I don't quite understand the last part, ` if you don't archive from the primary` - does that refer to WAL or Backup?

archive = shortcut for WAL segment archives indeed.

> If WAL, would it be sensible to have the `archive_command` only configured on the standby (with `archive_mode = always`) and reference the primary only for access to `pg_control`?

You could indeed disable the WAL archiving (disabling archive_mode completely) from your primary and only reference the primary for the backup control session and pg_control stuff.

> Either way, that would mean having to inject either an SSH or TLS server into the image, since the primary is run in a cloud environment in docker. Do you know of an "official" way to accomplish this?

AFAICT, the user-guides are using [docker images](https://github.com/pgbackrest/pgbackrest/blob/main/doc/xml/user-guide.xml#L340). I guess you could find some examples there. 

Ultimately it will depend on the way you're deploying it. I guess there should be some interesting pointers into k8s operators.

Kind Regards,

**Comment by rezemble** [comment]
I've crafted a modified version of the `postgres`-Image (in this case, v12) and a short entrypoint script based on that information.
Just leaving this here in case someone stumbles across this and is looking for a way to make an `ssh` server and `pgBackRest` run in a docker image - however in testing it didn't seem stable enough to sustain backing up data from (crashed with `ERROR: [039]: client state is 'data-get' but expected 'idle'` after a while) - this basic setup seems to be just enough for my use case.
As opposed to other ways of running the ssh server it also doesn't crash on client disconnects (in some configurations, Postgres considers the ssh connection process a "server process" and exits when it ends).

Thank you!

`Dockerfile`:
```dockerfile
FROM postgres:12 AS build-backrest
RUN mkdir /build
WORKDIR /build
RUN apt-get update -y && apt-get install -y make gcc libpq-dev libssl-dev libxml2-dev pkg-config \
  liblz4-dev libzstd-dev libbz2-dev libz-dev libyaml-dev wget
RUN wget -q -O - \
  https://github.com/pgbackrest/pgbackrest/archive/release/2.40.tar.gz | \
  tar zx -C /build
RUN cd /build/pgbackrest-release-2.40/src && ./configure && make


FROM postgres:12
RUN apt update -y && apt install -y python3 python2 postgresql-plpython3-12 openssh-server sudo
COPY --from=build-backrest /build/pgbackrest-release-2.40/src/pgbackrest /usr/bin/pgbackrest

RUN service ssh start
EXPOSE 22

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["postgres"]
```

`entrypoint.sh`:
```bash#!/bin/bash
service ssh restart && /usr/local/bin/docker-entrypoint.sh $@
```

**Comment by rezemble** [comment]
> For new installations we recommend using the built-in TLS server. There are multiple ways that noise can be introduced into SSH sessions (e.g. banners).

thanks for the heads up, I'll look into daemonizing the TLS server in docker, too.
If I manage to produce something working, I'll post an update here..

**Comment by rezemble** [comment]
I think I managed to produce something working, as a reference.

`pgbackrest.service`
```bash
#! /bin/sh

### BEGIN INIT INFO
# Provides:             pgbackrest
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    pgBackRest TLS Server
### END INIT INFO

set -e

test -x /usr/bin/pgbackrest || exit 0

mkdir -p /var/log/pgbackrest/
touch /var/log/pgbackrest/all-server-log

. /lib/lsb/init-functions

start() {
  log_daemon_msg "Starting pgBackRest TLS server" "pgbackrest" || true
  if start-stop-daemon --start --background -c postgres --quiet --oknodo --pidfile /run/pgbackrest.pid --exec /usr/bin/pgbackrest -- server $PGBACKREST_SERVER_OPTS; then
    log_end_msg 0 || true
  else
    log_end_msg 1 || true
  fi
}
stop() {
  log_daemon_msg "Stopping pgBackRest TLS server" "pgbackrest" || true
  if start-stop-daemon --stop --quiet --oknodo --pidfile /run/pgbackrest.pid --exec /usr/bin/pgbackrest; then
    log_end_msg 0 || true
  else
    log_end_msg 1 || true
  fi
}
reload() {
  log_daemon_msg "Reloading pgBackRest TLS server" "pgbackrest" || true
  if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /run/pgbackrest.pid --exec /usr/bin/pgbackrest; then
    log_end_msg 0 || true
  else
    log_end_msg 1 || true
  fi
}
status() {
  status_of_proc -p /run/pgbackrest.pid /usr/bin/pgbackrest pgbackrest && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  reload|force-reload)
    reload
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    log_action_msg "Usage: /etc/init.d/pgbackrest {start|stop|reload|force-reload|restart|status}" || true
    exit 1
esac

exit 0
```

`entrypoint.sh`
```bash
#!/bin/bash

service pgbackrest restart && /usr/local/bin/docker-entrypoint.sh $@
```

`Dockerfile`
```Dockerfile
FROM postgres:12 AS build-backrest
RUN mkdir /build
WORKDIR /build
RUN apt-get update -y && apt-get install -y make gcc libpq-dev libssl-dev libxml2-dev pkg-config \
  liblz4-dev libzstd-dev libbz2-dev libz-dev libyaml-dev wget
RUN wget -q -O - \
  https://github.com/pgbackrest/pgbackrest/archive/release/2.40.tar.gz | \
  tar zx -C /build
RUN cd /build/pgbackrest-release-2.40/src && ./configure && make


FROM postgres:12
EXPOSE 8432
RUN apt update -y && apt install -y python3 python2 postgresql-plpython3-12 openssh-server sudo
COPY --from=build-backrest /build/pgbackrest-release-2.40/src/pgbackrest /usr/bin/pgbackrest
COPY pgbackrest.service /etc/init.d/pgbackrest

RUN chmod +x /etc/init.d/pgbackrest

COPY entrypoint.sh /entrypoint.sh

VOLUME /etc/pgbackrest

ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["postgres"]
```
