### ISSUE TITLE
can PgBackRest able to restore backup on remote server without communication?

### ISSUE THREAD

**Issue by ashwinsirigi** [pgbackrest/pgbackrest#1882]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.37

2. PostgreSQL version:11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos 7

4. Did you install pgBackRest from a source or from a package? Packages

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: I got a requirement to restore full backup which is taken using pgbackrest in our backup server locally. Now we have to restore the full backup in our client environment where there won't able any communication between backup servers and remote client-server. In this scenario is it possible to restore the backup using backup files? and any alternate way to archive it ?

**Comment by pgstef** [comment]
Hi,

pgBackRest needs access to the repository to be able to work. And unless you used the archive-copy option, PG recovery will also need access to the repository to fetch the WAL archives.

So you'll need a way for your target server to get a RO access to your backup repository. If you can't, you could add a second repository (a remote one, like an nfs store or an S3 bucket) on your backup server, take a full backup for that repository (using the multi-repo feature) and then reach that shared space from your target server.

Kind Regards

**Comment by MichaelDBA** [comment]
I'm wondering if a shared NFS drive that is accessible by both the repository host and primary and standby hosts, can be used by the secondary host to do a full restore from the shared repo instead of doing it over the wire to the primary?

**Comment by pgstef** [comment]
As written on slack, the connection to the primary is only needed when performing a backup from standby. 
To restore a backup, you only need access to the repository (repo-host **or** repo-path).

I just don't get your `doing it over the wire to the primary`. If you use a directly attached storage (repo-path) and not a repo host (repo-host), the restore command won't pull anything over SSH (or TLS).
