### ISSUE TITLE
Support for official docker image

### ISSUE THREAD

**Issue by chreniuc** [pgbackrest/pgbackrest#1883]
Is there a plan on adding support for an official docker image?

**Comment by m-thirumal** [comment]
Any update on this issue?

**Comment by woblerr** [comment]
Hi,
You can use this - https://github.com/woblerr/docker-pgbackrest

**Comment by dwsteele** [comment]
We are not planning to support an "official" Docker image. There are already several Dockerized pgBackRest solutions. In addition to the link @woblerr posted, there is also Crunchy Containers (https://github.com/CrunchyData/crunchy-containers).
