### ISSUE TITLE
ERROR: [070]: link 'postgresql.conf' destination '/var/lib/pgsql/13/data' is in PGDATA

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#1885]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.41

2. PostgreSQL version:
13.8

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 8.6

4. Did you install pgBackRest from source or from a package?
Package pgbackrest-2.41-1.rhel8.x86_64.rpm

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) ATTACHED
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`) 
    - errors in the postgresql log file before or during the time you experienced the issue  ATTACHED
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
pgbackrest complain that postgresql.conf is a link to a file in PGDATA.
I have a file named postgresql.conf-site-specific.  postgresql.conf is a symlink to it.  We've been running PgBackRest 2.07 this way for a few years.  This error occurred only when I installed PgBackRest 2.41 on a new server.  (We're migrating from an old RHEL6 system to a new RHEL8 VM.)
Why was this restriction created?
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/9679330/pgbackrest.conf.txt)
[pgbackrest command.log](https://github.com/pgbackrest/pgbackrest/files/9679331/pgbackrest.command.log)

**Comment by dwsteele** [comment]
Links restrictions have generally been created when a user reported a link causing problems with backups (or we found something ourselves).

I didn't find where this was added on a casual inspected and I'm not too inclined to look through four years of commits to find it. You are welcome to do so if you like.

It could be that there is no specific reason and this was a side effect of some other change. But I certainly wouldn't want to make any changes until I knew for sure. The code that checks the links has gotten super-hairy over time (mostly for performance reasons) and I wouldn't want to modify it lightly.
