### ISSUE TITLE
Debian - Install previous pgBackRest version

### ISSUE THREAD

**Issue by devops93** [pgbackrest/pgbackrest#1892]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.41

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Debian 10

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: Is there a way to install the previous version of pgBackRest on Debian 10 (ie pgBackest 2.40)
My actual apt file /etc/apt/sources.list.d/pgdg.list :
`deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main`

Is there a specific repository ?

Thanks

**Comment by pgstef** [comment]
Hi,

The apt packages are maintained by the PGDG community.
You should probably ask your question on the [pgsql-pkg-debian](https://www.postgresql.org/list/pgsql-pkg-debian/) mailing list or look at the [wiki](https://wiki.postgresql.org/wiki/Apt).

I'm not sure you could find old packages easily given we recommend to use the latest version available anyway.

Regards

**Comment by devops93** [comment]
Hi,

I know but we cannot yet mix pgbackrest versions.

Thank you for your reply

**Comment by dwsteele** [comment]
There is an archive of older versions but we are not involved in maintaining it, see: https://pgbackrest.org/faq.html#old-package.
