### ISSUE TITLE
Less info printed in --log-level-console=info?

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#1893]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.41 and 2.07

2. PostgreSQL version:  13.8 and 9.6.24

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  RHEL8.6 and RHEL6.10

4. Did you install pgBackRest from source or from a package? PGDG repositories

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
In v2.07, backups with command line option "--log-level-console=info" would print an INFO line for every file copied.  v2.41 does not seem to do this.  Log files attached.

[pgbackrest 2.07.log](https://github.com/pgbackrest/pgbackrest/files/9735154/pgbackrest.2.07.log)
[pgbackrest 2.41.log](https://github.com/pgbackrest/pgbackrest/files/9735156/pgbackrest.2.41.log)

**Comment by dwsteele** [comment]
These messages were moved to detail level in 2.35. See https://pgbackrest.org/release.html#2.35
