### ISSUE TITLE
How to restore from S3 backup to fresh database?

### ISSUE THREAD

**Issue by furious-luke** [pgbackrest/pgbackrest#1895]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.41

2. PostgreSQL version: 14.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Alpine Linux

4. Did you install pgBackRest from source or from a package? From source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

```
[global]
...
repo1-retention-full-type=time
repo1-retention-full=7
repo1-type=s3
repo1-path=/backups
repo1-s3-region=ap-southeast-2
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-bucket=bucket_name
repo1-s3-key=$BACKUPS_AWS_ACCESS_KEY_ID
repo1-s3-key-secret=$BACKUPS_AWS_SECRET_ACCESS_KEY
start-fast=y
delta=y
compress-type=zst
compress-level=6
log-level-console=info
log-level-file=debug

[demo]
pg1-path=/var/lib/postgresql/data
```

6. Describe the issue:

I'm having difficulty restoring a backup from S3 onto a newly created database. I'm running PostgreSQL and pgBackRest from within a Docker container. I have no problems creating backups on S3, I can see them appearing as changes are made to my databases.

Once I stop the Docker container and launch a new one, I would like to be able to recover the backups on S3 into the new container. However, I have been met with a couple of problems:

1. Attempting to recreate the stanza fails with `ERROR: [028]: backup and archive info files exist but do not match the database`. After having read a separate issue here on GitHub, it seemed that I may not need to recreate the stanza. So, after skipping stanza creation...

2. I then tried to run the restore, leading to `ERROR: [075]: no backup set found to restore`.

I'm a little confused by the above errors. The first error seems to indicate that I cannot create a stanza when backup files exist. pgBackRest certainly seems to be able to detect them. However the restore command indicates that pgBackRest can't find any backup files. Can you please advise the correct way to perform a restore command on a fresh database? Thanks in advance!

**Comment by pgstef** [comment]
Hi,

First of all, as stated previously [here](https://github.com/pgbackrest/pgbackrest/issues/1883#issuecomment-1257089943), we are not planning to support an "official" Docker image currently. So you should probably ask for help on the project providing such images?

Creating a stanza is there to initialize the repository with a new PG cluster. If you want to restore a data directory, you should use the same stanza name and remove the freshly created data (or use the delta option to erase it). If you can see the backups using `pgbackrest --stanza=your_stanza_name info` and don't use specific target options, the restore command should indeed be able to restore it.

Regards

**Comment by furious-luke** [comment]
Hi @pgstef, thanks for your response!

I'm not actually using any of those Dockerized solutions containing pgBackRest. I've simply installed pgBackRest into a Docker image alongside PostgreSQL. I'm not sure asking this question there would be appropriate?

Can you offer any advise on why I'm seeing the error about "no backup sets"?

**Comment by pgstef** [comment]
🤷 did you try the info command?
Did you use the same repo settings and stanza name?

**Comment by furious-luke** [comment]
> :shrug:

Ah, sorry for being a pain. I certainly didn't mean to waste your time with this question. I can appreciate the difficulty in debugging someone else's use-case, I just figured someone from the pgBackRest community may have encountered a similar situation.

As it turns out it's okay, I've whipped up a similar solution to pgBackRest in Go that suits my purposes. Again, thanks for your time!

Cheers!

**Comment by pgstef** [comment]
> Ah, sorry for being a pain. I certainly didn't mean to waste your time with this question.

You're not, no problem with that question. Just that I don't have a clue on what happens with the provided information.

That's why I asked if you used the same repo settings and stanza name. And also what does return the `pgbackrest --stanza=your_stanza_name info` command.

There's a lot of possibilities before reaching the [error](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/restore/restore.c#L378) you mentioned. So we at least need the full restore command you used and its associated log + the output of the info command to try to help if we can ;-)
