### ISSUE TITLE
WARN: 'compress' and 'compress-type' options should not both be set

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#1896]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.41

2. PostgreSQL version: 13.8

3. Operating system/version: RHEL 8.6

4. Did you install pgBackRest from source or from a package? PGDG package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/9746580/pgbackrest.conf.txt)
    - errors in the postgresql log file before or during the time you experienced the issue
[postgresql.log.txt](https://github.com/pgbackrest/pgbackrest/files/9746591/postgresql.log.txt)

7. Describe the issue:
The only active clause (I even stopped and started the localhost stanza) in the config file's [localhost:archive-push] stanza is "compress-type=lz4", but pgbackrest complains about both --compress and --compress-level existing.

**Comment by pgstef** [comment]
Hi,

The answer is pretty clear in the log : `archive-push command begin ... --compress --compress-type=lz4`.
The options are both set. `compress=y` is written in your stanza section `[localhost]`. `[localhost:archive-push]` is there to add or change some values but not to remove it.

Anyway, the [compress](https://pgbackrest.org/configuration.html#section-general/option-compress) option is deprecated and shouldn't be used anymore. You should use `compress-type=none` instead.

Kind regards

**Comment by RonJohn2** [comment]
> Hi,
> 
> The answer is pretty clear in the log : `archive-push command begin ... --compress --compress-type=lz4`. The options are both set. `compress=y` is written in your stanza section `[localhost]`. `[localhost:archive-push]` is there to add or change some values but not to remove it.

Why does `[localhost]` affect `[localhost:archive-push]`?  They are two completely separate config sections.

> Anyway, the [compress](https://pgbackrest.org/configuration.html#section-general/option-compress) option is deprecated and shouldn't be used anymore. You should use `compress-type=none` instead.

I'll make those config modifications.

**Comment by pgstef** [comment]
> Why does `[localhost]` affect `[localhost:archive-push]`? They are two completely separate config sections.

No, they are not. `:archive-push` extends `localhost` to only apply a few settings to a specific command. But it still receives the options from global and main stanza section.

**Comment by dwsteele** [comment]
See https://pgbackrest.org/user-guide.html#quickstart/check-configuration for an explanation of config section precedence (towards the end).
