### ISSUE TITLE
Feature request split spool-path variable in two

### ISSUE THREAD

**Issue by Tiago-DBA** [pgbackrest/pgbackrest#1897]
Hello:

1. pgBackRest version:
2.41

Using asynchronous archiving.
Most part of time we will create the spool-path queue for archive-PUSH outside of pg_data (for logical reasons)
But as you suggest on documentation the spool-path for archive-GET should be in the same FS as pg_data.

I know it is possible to overload the variable by functions, 
example: 
[my_stanza:archive-push]
spool-path=/mypushqueue

[my_stanza:archive-get]
spool-path=/mygetqueue

But I think it should be easier for everybody to split it on two variables, because it should (frequently) be split.

Thank you.

**Comment by dwsteele** [comment]
I don't think it makes sense to split these. `archive-push` only writes zero-length status files into the spool path, which I don't think uses enough write bandwidth to justify separating it.

**Comment by dwsteele** [comment]
> And error files are very small.

Yes, forgot about the error files, but they are quite small. And for common errors (connectivity, etc.) you will just get one error file for all the segments.
