### ISSUE TITLE
Installation on Centos-like distro

### ISSUE THREAD

**Issue by fabriziomello** [pgbackrest/pgbackrest#190]
Just a small contribution to install pgBackRest on Centos-like distro:

1) Dependencies
$ sudo yum install perl-DBD-Pg perl-DBI perl-Net-Daemon perl-PlRPC perl-JSON-PP

2) Download v1.00
$ wget -q -O - \
       https://github.com/pgbackrest/pgbackrest/archive/release/1.00.tar.gz | \
       tar zx -C ~

3) Install pgBackRest
$ sudo cp -r ~/pgbackrest-release-1.00/lib/pgBackRest \
       /usr/lib64/perl5
$ sudo find /usr/lib64/perl5/pgBackRest -type f -exec chmod 644 {} +
$ sudo find /usr/lib64/perl5/pgBackRest -type d -exec chmod 755 {} +
$ sudo cp ~/pgbackrest-release-1.00/bin/pgbackrest /usr/bin/pgbackrest
$ sudo chmod 755 /usr/bin/pgbackrest
$ sudo mkdir -m 770 /var/log/pgbackrest
$ sudo chown postgres:postgres /var/log/pgbackrest

**Comment by dwsteele** [comment]
Hi Fabrízio,

I do have instructions for CentOS 6: https://github.com/pgbackrest/pgbackrest/blob/master/doc/xml/user-guide.xml#L161.  But they have not gotten their own page on the website yet.

It installs into /usr/share/perl5 and this seems to be the convention.  I can see why you selected /usr/lib64 instead but is that required?  Did you find a reference that required/suggested this or did it just make sense?

Thanks,
-David

**Comment by fabriziomello** [comment]
Hi David,

I just install into /usr/lib64 because I found the perl5 directory inside it... Well, I move it to /usr/share/perl5 as you mentioned and all works fine.

Sorry but my perl knowledge is very limited. I still working/testing the tool and if I found some issue I'll report here.

Thanks and congrats for this really nice tool.

Ps: unfortunately last year during the pgcon I didn't watch your presentation... I hope have a chance to meet you in another event.

**Comment by dwsteele** [comment]
Great, glad you are using it!  The CentOS docs should be published online pretty soon.

P.S. I'll be at PGCon again this year but talking about pgaudit instead of pgBackRest.  Hopefully I'll see you there!

**Comment by davidhollenberger** [comment]
Did The CentOS doc ever get published?  I see the instructions in user-guide.xml, but it's not the easiest to read.

Thanks for all your work on this.  It looks great.

**Comment by dwsteele** [comment]
Sorry, not yet.  There are simply too many other priorities at the moment.  In addition, the CentOS/RHEL documentation is basically identical to the Debian/Ubuntu documentation.  The only real difference is in how the postgres server is stopped/started.

If you are having trouble with the Debian/Ubuntu guide on the website then I don't think a CentOS/RHEL version will be any more illuminating.  Please open an issue describing the problems you are having with the documentation and I'll do my best to address them.
