### ISSUE TITLE
Shutdown of hot-standby DB due to pgbackrest package upgrade

### ISSUE THREAD

**Issue by tsutsu** [pgbackrest/pgbackrest#1903]
We run hot-standby replicas, relying on async log-shipping using `pgbackrest archive-get`.

We use a combination of the Ubuntu `pgbackrest` package (on our newer instances based on Ubuntu 22.04) and the PGDG packaged version of `pgbackrest` (on our older Ubuntu 20.04 instances.)

On only one of our replicas (one of the ones using the Ubuntu-supplied version of the package), whenever the `pgbackrest` package gets upgraded, the replica DB instance will suddenly shut down, with the following in the logs:

```
[74343-1] FATAL:  could not restore file "00000004000111D40000005E" from archive: command not found
[555-1] LOG:  startup process (PID 853774) exited with exit code 1
[556-1] LOG:  terminating any other active server processes
```

Presumably, this happens because `apt` temporarily removes `/usr/bin/pgbackrest` during the package upgrade, in advance of installing the new version of it.

Is there a known technique for avoiding this, besides just never upgrading the pgbackrest package? Is there some kind of shim script we can use in our `restore_command`, that would block until the command is available again before proceeding?

(The "bug" here, if any, would be that there's a missing FAQ entry for this 😄 )

Alternately: should we perhaps file a bug in Postgres, suggesting a change in the semantics of `restore_command` to switch to using such "blocking poll for availability of `restore_command` executable" behavior, if the `restore_command` has already succeeded at least once since startup?

Or is this perhaps a bug in Ubuntu's packaging of `pgbackrest`? We haven't noticed the same behavior from our instances that use the PGDG version, so maybe there's some difference in e.g. the upgrade-hook script used in the packages, that enables the PGDG version of the package to "smooth over" the upgrade transition?

**Comment by pgstef** [comment]
Hi,

> Or is this perhaps a bug in Ubuntu's packaging of `pgbackrest`? We haven't noticed the same behavior from our instances that use the PGDG version, so maybe there's some difference in e.g. the upgrade-hook script used in the packages, that enables the PGDG version of the package to "smooth over" the upgrade transition?

I was able to reproduce the error message with PGDG package on PG 14 (so even with a recent PG version). Perhaps asking for advice on the pgsql-pkg-debian might be a good approach: the packagers may have an idea.

> Is there a known technique for avoiding this, besides just never upgrading the pgbackrest package? Is there some kind of shim script we can use in our `restore_command`, that would block until the command is available again before proceeding?

Not upgrading wouldn't be a solution. Aren't you also applying PG minor version updates which requires a PG restart?

If you don't want to restart PG, you could probably comment the restore_command and simply reload before applying the package update (or do it while updating the PG packages too).

You'd have something like this in the logs:
```
LOG:  received SIGHUP, reloading configuration files
LOG:  parameter "restore_command" removed from configuration file, reset to default
.... perform your update ....

LOG:  received SIGHUP, reloading configuration files
LOG:  parameter "restore_command" changed to "..."
P00   INFO: archive-get command begin 2.41: [000000010000000000000013, pg_wal/RECOVERYXLOG] ...
P00   INFO: found 000000010000000000000013 in the repo1: 14-1 archive
P00   INFO: archive-get command end: completed successfully (75ms)
LOG:  restored log file "000000010000000000000013" from archive
```

Kind Regards
