### ISSUE TITLE
PG_WAL not getting cleaned up after full backup

### ISSUE THREAD

**Issue by viki00** [pgbackrest/pgbackrest#1906]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.37

2. PostgreSQL version:
12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu Focal
Master/Standby setup
1 repo server

5. Did you install pgBackRest from source or from a package?
Package

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
   
## PROD ##**
[TEMP]
pg1-path=/data/pgsql/TEMP/data
pg1-port=5700
process-max=8
spool-path=/var/spool/pgbackrest

[global]
repo1-path=/backups/pgbackrest/
log-path=/backups/pgbackrest/log
log-level-console=detail
repo1-retention-full=1
repo1-retention-diff=3
start-fast=y
compress-level=3

[global:archive-push]
compress-level=3

 - `postgresql.conf` 
   archive_command: /usr/bin/pgbackrest --stanza=TEMP archive-push %p
   archive_mode: on
   listen_addresses: *
   max_wal_senders: 25
   wal_level: replica
   port: 5700
   max_wal_size: 150GB
   
    - errors in the postgresql log file before or during the time you experienced the issue
   No errors as such

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
  -------------------PROCESS START-------------------
2022-10-19 21:32:07.362 P00   INFO: backup command begin 2.37: --no-archive-check --compress-level=3 --exec-id=180197-b1ac8bd3 --log-level-console=detail --log-path=/backups/pgbackrest/log --pg1-path=/data/pgsql/datashed/data --pg1-port=5700 --process-max=8 --repo1-path=/backups/pgbackrest/ --repo1-retention-diff=3 --repo1-retention-full=1 --stanza=datashed --start-fast --type=full
2022-10-19 21:32:08.085 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2022-10-19 21:32:46.164 P00   INFO: backup start archive = 0000001D00021FCF0000007D, lsn = 21FCF/7D5E0BB0
2022-10-20 03:24:10.708 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2022-10-20 03:24:12.015 P00   INFO: backup stop archive = 0000001D00022069000000D6, lsn = 22069/D6D801F8
2022-10-20 03:24:12.029 P00   INFO: new backup label = 20221019-213207F
2022-10-20 03:24:20.990 P00   INFO: full backup size = 8192GB, file total = 421734
2022-10-20 03:24:21.035 P00   INFO: backup command end: completed successfully (21133676ms)

7. Describe the issue:
It appears that WAL files in pg_wal are not getting cleaned up after a full backup. 

stanza: TEMP
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12): 0000001D00021D0300000000/0000001D00021DAF0000004F

        full backup: 20221019-213207F
            timestamp start/stop: 2022-10-19 21:32:07 / 2022-10-20 03:24:11
            wal start/stop: 0000001D00021FCF0000007D / 0000001D00022069000000D6
            database size: 8192GB, database backup size: 8192GB
            repo1: backup set size: 1025.7GB, backup size: 1025.7GB

However...if i look at pg_wal, i see wals from Oct 19 at 4:40 am, the full backup was taken at 21:32.

-rw-------  1 postgres nopasswdlogin 16777216 Oct 19 04:40 0000001D0002211600000069
-rw-------  1 postgres nopasswdlogin 16777216 Oct 19 04:40 0000001D00022116000000F1
-rw-------  1 postgres nopasswdlogin 16777216 Oct 19 04:40 0000001D0002211800000082
-rw-------  1 postgres nopasswdlogin 16777216 Oct 19 04:40 0000001D000221160000001A

We do have a replication slot but no lag

 is_slave |    receive     |     replay     | synced | lag 
----------+----------------+----------------+--------+-----
 t        | 22116/1FF6B698 | 22116/1FF6B698 | t      |   0
(1 row)

postgres=# select * from pg_replication_slots;
  slot_name   | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin |  restart_lsn   | confirmed_flush_lsn 
--------------+--------+-----------+--------+----------+-----------+--------+------------+------+--------------+----------------+---------------------
 temp |        | physical  |        |          | f         | t      |     587024 |      |              | 22116/A6A754A0 | 
(1 row)

postgres=# select pg_walfile_name('22116/A6A754A0');
     pg_walfile_name      
--------------------------
 0000001D00022116000000A6
(1 row)

 $ ls -alt | grep 0000001D00022116000000A6
-rw-------  1 postgres nopasswdlogin 16777216 Oct 20 10:02 0000001D00022116000000A6

We create an incredible amount of WALS, it is about 3T from yesterday morning. Any help will be appreciated.

Thanks

**Comment by dwsteele** [comment]
pgBackRest does not clean up the pg_wal directory, PostgreSQL does. But it looks like your archiving is lagging so you should consider enabling async archiving: https://pgbackrest.org/user-guide.html#async-archiving.

You might also consider using lz4 for WAL compression since it is quite a bit faster.

**Comment by viki00** [comment]
Thank you!
