### ISSUE TITLE
pgsql-pgbackrest-query.sql load error 

### ISSUE THREAD

**Issue by rudonx** [pgbackrest/pgbackrest#1910]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

(base) [root@rudonx example]# pgbackrest version
pgBackRest 2.40

2. OS Version

Centos 7.9

[postgres@rudonx ~]$ uname -a
Linux rudonx 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

4. PostgreSQL version:

postgres=# select version();
                                                 version                                                 
---------------------------------------------------------------------------------------------------------
 PostgreSQL 12.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
(1 row)

6. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

7. Did you install pgBackRest from source or from a package?

package

8. Describe the issue:

I would like to follow this guide to monitor backup activity but error occurred : 

Ref: https://pgbackrest.org/user-guide-rhel.html#monitor

![image](https://user-images.githubusercontent.com/73181232/197445085-fb9996b6-602b-4208-bf25-c58eaaf2d1c2.png)

![image](https://user-images.githubusercontent.com/73181232/197445161-6d70e0ed-d59d-46b6-a986-395b2e39ddd5.png)

when I run this commend, it can return results 
```
postgres=#  \! pgbackrest --output=json info

```
![image](https://user-images.githubusercontent.com/73181232/197459468-69d56cda-1308-459d-ba43-f091f1a2086e.png)

Pls help on this issue.

**Comment by gmustdie** [comment]
i got the same problem
Pgbackrest 2.41
Postgresql 14
Ubuntu 20.04

**Comment by dwsteele** [comment]
Looks like a linefeed that is not getting encoded, but I'm not seeing it in our test env. Can you provide the complete json output?

**Comment by Shelestov7** [comment]
Pgbackrest 2.41
Postgresql 14
Ubuntu 20.04

Hi, output: 

`[2022-10-26 10:46:31] [22P02] ERROR: invalid input syntax for type json
  [2022-10-26 10:46:31] Detail: Character with value 0x0a must be escaped.
[2022-10-26 10:46:31] Where: JSON data, line 1: ...HTTP request failed with 301 (Moved Permanently):
[2022-10-26 10:46:31] COPY temp_pgbackrest_data, line 1, column data: "[{"archive":[{"database":{"id":1,"repo-key":1},"id":"14-1","max":"0000000100000002000000ED","min":"0..."
[2022-10-26 10:46:31] SQL statement "copy temp_pgbackrest_data (data)
[2022-10-26 10:46:31] from program
[2022-10-26 10:46:31] 'pgbackrest --output=json info' (format text)"
[2022-10-26 10:46:31] PL/pgSQL function monitor.pgbackrest_info() line 9 at SQL statement
`

**Comment by Shelestov7** [comment]
For me solved. Problem was with S3 repo in config.

**Comment by dwsteele** [comment]
I figured out the issue here -- postgres was converting \n to linefeed in the copy command and the json conversion did not like that. Fixed in #1963.

However, you'll need to fix the permissions errors in your repo. You can see them in the json output, e.g.:
```
"message":"[FileOpenError] unable to load info fi
le '/var/lib/pgbackrest/backup/demo/backup.info' or '/var/lib/pgbackrest/backup/demo/backup.info.copy':\nFileOpenError: unable to open file '/var/lib/pgbackrest/backup/
demo/backup.info' for read: [13] Permission denied\nFileOpenError: unable to open file '/var/lib/pgbackrest/backup/demo/backup.info.copy' for read: [13] Permission deni
ed\nHINT: backup.info cannot be opened and is required to perform a backup.\nHINT: has a stanza-create been performed?"
```

@rudonx @Shelestov7 @gmustdie How would you like your names to appear in the release notes?

**Comment by rudonx** [comment]
@dwsteele Many Thanks. That's nice of you.

Just "rudonx". Thank you

**Comment by gmustdie** [comment]
@dwsteele "Gmustdie". Thank you.

**Comment by Shelestov7** [comment]
Thanks for asking. Ivan Shelestov will be ok.
