### ISSUE TITLE
Does PgBackRest work with AWS RDS?

### ISSUE THREAD

**Issue by brunosantosnet** [pgbackrest/pgbackrest#1912]
We want to use pgBackRest to backup the data that is in the AWS RDS service and when necessary restore to another RDS so that we can store the backup file in the S3 storage service. That's because in S3 I save more than keeping a snapshot of this RDS on AWS itself. It is possible?

Thanks

**Comment by rudonx** [comment]
unfortunately, you can not use pgBackRest on AWS RDS for PostgreSQL because it's a managed service, you don't have underlying OS privileges

**Comment by brunosantosnet** [comment]
Thanks @rudonx
