### ISSUE TITLE
Block-level backup on the basis of pgBackRest

### ISSUE THREAD

**Issue by nikulinas** [pgbackrest/pgbackrest#1913]
1. pgBackRest version:
2.41

2. PostgreSQL version:
14

3. Operating system/version 
Astra Linux CE 2.12.45

4. Did you install pgBackRest from source or from a package?
from source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

6. Describe the issue:
We develop a block level backup for our internal needs and decided to use pgBackRest as a basis (because of MIT license).
Our approach is:
 - add new backup type - "block". This backup procedure is based on "incr" backup type.
 - add new files to manifest with names *_blocks corresponding to a basic data files which were changed since prior backup was saved. Basic data files will still reference to prior backup.
 - add new filter to the beginning of function backupFile(...) which will filter out blocks with lsn less then stopLsn of prior backup. Blocks which was chaned since prior backup was saved will be saved to *_blocks files.
 - add new filter to the end of function restoreFile(...) which will rewrite blocks of basic files from prior backup by blocks from corresponding *_blocks files.

Is our approach valid ?
Look forward to hearing your suggestions, compliments, criticisms or any other feedback.

**Comment by dwsteele** [comment]
> Is our approach valid ?

The basic concept seems valid, though I'd have to see the code to be sure. Is there a repo you can point me at? Not sure I have the time to do a proper review, but I am curious.

We are also working on a block incremental feature, see https://github.com/pgbackrest/pgbackrest/compare/main...dwsteele:pgbackrest:dws-binc-100-cig. This implementation works for any file type (not just pg heap/index files) and focuses on restore performance. 

Note that this is just a prototype, and we have not added compression/encryption support to restore so the backup cannot use either yet. We are hoping to get a preview version into the late November release, but not sure if that will happen yet.

**Comment by dwsteele** [comment]
This branch should now work with all encryption/compression options for backup and restore. Verify has not been implemented yet.

**Comment by jcarnu** [comment]
That will be a very nice feature.
It might be obvious and maybe it will be hard to implement, but will it be difficult to extract metadata from WALs while they are streamed out the pg server to create/maintain a per file changed blocks index, so that, one can avoid full database scan at backup time ?
Does-it make sense ?

**Comment by dwsteele** [comment]
@jcarnu,

> but will it be difficult to extract metadata from WALs while they are streamed out

We have thought about doing this but it will not be part of the initial release. Timestamps work well for indicating updated files and since the segment size is only 1gb scanning the file is (usually) not that big a deal. There are some cases, i.e. single row updates distributed evenly through a very large table, that make the timestamp method less desirable, however. So, WAL-scanning may still be needed in the future.

There are also updates that are not WAL-logged if checksums are disabled, such as hint bits. It could be very unpleasant to rewrite all the hint bits since the last full backup right after restore when things are already stressed.

**Comment by jcarnu** [comment]
Thank you for your feedback and explanations.
I agree for timestamp vs WAL scanning method. WAL scanning may be a good idea in the future.
Actually, what I had in mind about whole table file scanning scanning is that it may be usually not that big deal until it does not come to paid IOPS, but that's another story.
Thanks again for your explanations !

**Comment by dwsteele** [comment]
PR #1916 is ready for final review, so closing this issue.

**Comment by dwsteele** [comment]
This will be included in pgBackRest 2.44 as an internal feature (i.e. don't use in production) and it would be helpful if you could test against your workload and provide feedback.

**Comment by nikulinas** [comment]
@dwsteele 

I have briefly compared your approach with our one.

What I did:
1. Compiled your (original) pgbackrest and our fork
2. Created separated stanzas for them
3. Inited pgbench tables: pgbench -i -s 500 test
4. Created full backups using both pgbackrests: pgbackrest --stanza=local-pg --type=full --compress-type=none backup
5. Started pgbench to change tables content: pgbench -n -c 6 -T 20 test
7. Created incremental block level backups:
	pgbackrest --stanza=local-pg --type=incr backup  (original)
	pgbackrest --stanza=local-pg --type=blocks backup (our fork)

   Approach which uses lsn to determine if block is changed since last backup is 2-3 times faster then approach which uses hash summs (see comment below)

8. Restored database from incremental block level backups:
	pgbackrest --stanza=local-pg restore
   Looks like both (original) pgbackrest and our fork restores database for about the same time

The main difference is in the backup's content:
Approach which uses lsn can not detect and does not backup blocks if lsn did not change since last backup even if block was changed actually, but changes to it was not WAL-logged
Approach which detect changed blocks using hash summs detect any changes, even if changes to it was not WAL-logged (PageHeaderData::pd_flags for example)
Thus, in this test your (original) pgbackrest generated block level backup files with size much larger then our fork, because our fork did not save blocks with changes which was not WAL-logged

**Comment by sfrost** [comment]
Correctness is absolutely critical when doing backups, certainly much more so than backup speed which is of relatively low value (unlike restore speed, which is of high value as restores are done in cases where there is an urgency to get the systems back online).

Thanks for your input but hoping that all changes are properly handled by looking at the LSN isn't something we feel is a strong enough guarantee of correctness for backups.

**Comment by dwsteele** [comment]
> Approach which detect changed blocks using hash summs detect any changes, even if changes to it was not WAL-logged (PageHeaderData::pd_flags for example)

We consider this to be a feature. Reapplying a week's worth of hint bit updates directly after a restore is going to lead to poor performance. This work is already done so it seems better to preserve it at the expense of storage rather than redoing the work.

Also, newly created databases are not the best way to test the block incremental feature since the entire database looks new. Maybe try a vacuum full freeze before running a comparison.

> Approach which uses lsn to determine if block is changed since last backup is 2-3 times faster then approach which uses hash summs

It would great to see some actual times/sizes here.

**Comment by nikulinas** [comment]
I have done test you asked

1. `pgbench -i -s 500 alex`
2. `pgbench -n -c 6 -T 30 alex`
3. `vacuumdb --full --freeze`
4. After that I have the next files:

```
SELECT relfilenode, relname FROM pg_class WHERE relname like 'pgbench_%';
 relfilenode |        relname
-------------+-----------------------
       44885 | pgbench_accounts
       44889 | pgbench_accounts_pkey
       44898 | pgbench_history
       44924 | pgbench_tellers
       44927 | pgbench_tellers_pkey
       45017 | pgbench_branches
       45020 | pgbench_branches_pkey
(7 rows)

```
```
ll -S 44885* 44889* 44898* 44924* 44927* 45017* 45020*
-rw------- 1 alex alex 1073741824 Feb  3 21:44 44885
-rw------- 1 alex alex 1073741824 Feb  3 21:44 44885.1
-rw------- 1 alex alex 1073741824 Feb  3 21:44 44885.2
-rw------- 1 alex alex 1073741824 Feb  3 21:44 44885.3
-rw------- 1 alex alex 1073741824 Feb  3 21:44 44885.4
-rw------- 1 alex alex 1073741824 Feb  3 21:44 44885.5
-rw------- 1 alex alex 1073741824 Feb  3 21:45 44889
-rw------- 1 alex alex  272310272 Feb  3 21:44 44885.6
-rw------- 1 alex alex   49373184 Feb  3 21:45 44889.1
-rw------- 1 alex alex    8986624 Feb  3 21:45 44898
-rw------- 1 alex alex     229376 Feb  3 21:45 44924
-rw------- 1 alex alex     131072 Feb  3 21:45 44927
-rw------- 1 alex alex      32768 Feb  3 21:45 45020
-rw------- 1 alex alex      24576 Feb  3 21:45 45017

```
5. Created full backups using both pgbackrests:
`pgbackrest --stanza=local-pg --type=full --compress-type=none backup`

original pgbackrest created the next files:
```
ll -S 44885* 44889* 44898* 44924* 44927* 45017* 45020*
-rw-r----- 1 alex alex 1073771527 Feb  3 22:02 44885.1.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:02 44885.2.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:02 44885.3.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:02 44885.4.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:03 44885.5.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:02 44885.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:03 44889.pgbi
-rw-r----- 1 alex alex  272319303 Feb  3 22:03 44885.6.pgbi
-rw-r----- 1 alex alex   49376469 Feb  3 22:03 44889.1.pgbi
-rw-r----- 1 alex alex    8987543 Feb  3 22:03 44898.pgbi
-rw-r----- 1 alex alex     229437 Feb  3 22:03 44924.pgbi
-rw-r----- 1 alex alex     131105 Feb  3 22:03 44927.pgbi
-rw-r----- 1 alex alex      32768 Feb  3 22:03 45020
-rw-r----- 1 alex alex      24576 Feb  3 22:03 45017

```
our fork created the next files:
```
ll -S 44885* 44889* 44898* 44924* 44927* 45017* 45020*
-rw-r----- 1 alex alex 1073741824 Feb  3 22:01 44885
-rw-r----- 1 alex alex 1073741824 Feb  3 22:01 44885.1
-rw-r----- 1 alex alex 1073741824 Feb  3 22:01 44885.2
-rw-r----- 1 alex alex 1073741824 Feb  3 22:01 44885.3
-rw-r----- 1 alex alex 1073741824 Feb  3 22:01 44885.4
-rw-r----- 1 alex alex 1073741824 Feb  3 22:01 44885.5
-rw-r----- 1 alex alex 1073741824 Feb  3 22:01 44889
-rw-r----- 1 alex alex  272310272 Feb  3 22:02 44885.6
-rw-r----- 1 alex alex   49373184 Feb  3 22:02 44889.1
-rw-r----- 1 alex alex    8986624 Feb  3 22:02 44898
-rw-r----- 1 alex alex     229376 Feb  3 22:02 44924
-rw-r----- 1 alex alex     131072 Feb  3 22:02 44927
-rw-r----- 1 alex alex      32768 Feb  3 22:02 45020
-rw-r----- 1 alex alex      24576 Feb  3 22:02 45017
```

6. `pgbench -n -c 6 -T 30 alex`

7. Created incremental block level backups:
original pgbackrest
```
time pgbackrest --stanza=local-pg --type=incr backup
41.16user 11.25system 1:11.19elapsed 73%CPU (0avgtext+0avgdata 22744maxresident)k
```

original pgbackrest created the next files:
```
ll -S 44885* 44889* 44898* 44924* 44927* 45017* 45020*
-rw-r----- 1 alex alex 1073771527 Feb  3 22:12 44885.1.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:12 44885.2.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:12 44885.3.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:11 44885.4.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:11 44885.5.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:12 44885.pgbi
-rw-r----- 1 alex alex 1073771527 Feb  3 22:11 44889.pgbi
-rw-r----- 1 alex alex  282182783 Feb  3 22:12 44885.6.pgbi
-rw-r----- 1 alex alex   49376469 Feb  3 22:12 44889.1.pgbi
-rw-r----- 1 alex alex   13018397 Feb  3 22:12 44898.pgbi
-rw-r----- 1 alex alex    1671515 Feb  3 22:12 44885_fsm.pgbi
-rw-r----- 1 alex alex     426097 Feb  3 22:12 44924.pgbi
-rw-r----- 1 alex alex     180285 Feb  3 22:12 44927.pgbi
-rw-r----- 1 alex alex      81920 Feb  3 22:12 45017
-rw-r----- 1 alex alex      40960 Feb  3 22:12 45020
-rw-r----- 1 alex alex      24576 Feb  3 22:12 44898_fsm
-rw-r----- 1 alex alex      24576 Feb  3 22:12 44924_fsm
-rw-r----- 1 alex alex      24576 Feb  3 22:12 45017_fsm
```

our fork:
```
time pgbackrest --stanza=local-pg --type=blocks backup
2.87user 4.13system 0:41.55elapsed 16%CPU (0avgtext+0avgdata 15904maxresident)k
```

our fork created the next files:
```
ll -S 44885* 44889* 44898* 44924* 44927* 45017* 45020*
-rw-r----- 1 alex alex 459282000 Feb  3 22:10 44889_blocks
-rw-r----- 1 alex alex  97096200 Feb  3 22:10 44885.5_blocks
-rw-r----- 1 alex alex  96719000 Feb  3 22:10 44885.1_blocks
-rw-r----- 1 alex alex  96325400 Feb  3 22:10 44885.3_blocks
-rw-r----- 1 alex alex  96120400 Feb  3 22:10 44885.2_blocks
-rw-r----- 1 alex alex  95136400 Feb  3 22:10 44885_blocks
-rw-r----- 1 alex alex  94849400 Feb  3 22:10 44885.4_blocks
-rw-r----- 1 alex alex  34784400 Feb  3 22:10 44885.6_blocks
-rw-r----- 1 alex alex  21566000 Feb  3 22:10 44889.1_blocks
-rw-r----- 1 alex alex   4042600 Feb  3 22:10 44898_blocks
-rw-r----- 1 alex alex   1671168 Feb  3 22:10 44885_fsm
-rw-r----- 1 alex alex    426400 Feb  3 22:10 44924_blocks
-rw-r----- 1 alex alex    172200 Feb  3 22:10 44927_blocks
-rw-r----- 1 alex alex     82000 Feb  3 22:10 45017_blocks
-rw-r----- 1 alex alex     32800 Feb  3 22:10 45020_blocks
-rw-r----- 1 alex alex     24576 Feb  3 22:10 44898_fsm
-rw-r----- 1 alex alex     24576 Feb  3 22:10 44924_fsm
-rw-r----- 1 alex alex     24576 Feb  3 22:10 45017_fsm
-rw-r----- 1 alex alex      8192 Feb  3 22:10 44898_vm
-rw-r----- 1 alex alex      8192 Feb  3 22:10 44924_vm
-rw-r----- 1 alex alex      8192 Feb  3 22:10 45017_vm

```
8. restore from block level backup:

original pgbackrest:
```
time pgbackrest --stanza=local-pg restore
16.15user 17.27system 1:01.49elapsed 54%CPU (0avgtext+0avgdata 17488maxresident)k
```

our fork:
```
time pgbackrest --stanza=local-pg restore
4.31user 16.94system 0:46.69elapsed 45%CPU (0avgtext+0avgdata 16764maxresident)k
```

**Comment by dwsteele** [comment]
Yeah, updates like this represent a worst case scenario for our default block size. It looks like about 1 in 10 pages was updated evenly across the relation which caused us to write the entire block that the page was in.

In the beta implementation we just released you can set the block size using `--repo-block-size-map` (https://pgbackrest.org/configuration.html#section-repository/option-repo-block-size-map).

Your implementation will still be more efficient even with 8k blocks because there is no block map. But they would be a lot closer. Ultimately we feel that checksums are a more reliable way to do incremental backup than LSNs and the blocks maps are the cost of that.
