### ISSUE TITLE
Question about verify statement

### ISSUE THREAD

**Issue by Tiago-DBA** [pgbackrest/pgbackrest#1918]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.41

2. PostgreSQL version: 13

3. Operating system/version - SLES 15
4. 
5. Did you install pgBackRest from source or from a package?
community package

Statement:  pgbackrest verify
Could you please describe use cases of this statement and if it is automatically called from another statement particularly backup/restore/archive-push/archive-get  ?

Thank you very much

**Comment by dwsteele** [comment]
The verify command verifies that the contents of the repo are consistent. It is not used by any other command, though restore does its own version of verify to ensure the restore is consistent.

**Comment by Tiago-DBA** [comment]
Thank you.
Does it warn about gaps in wal files (could happen when using asynchronous archiving) ?
Does it warns if you last backup is too old (regarding current retention settings) ?

**Comment by dwsteele** [comment]
> Does it warn about gaps in wal files (could happen when using asynchronous archiving) ?

Yes.

> Does it warns if you last backup is too old (regarding current retention settings) ?

No, it would be better to get this from the `info` command, but we currently don't report on backups being too old.

**Comment by Tiago-DBA** [comment]
Thank you so much you can close the ticket if you want.
