### ISSUE TITLE
unable to restore to path $PGWAL because it contains files

### ISSUE THREAD

**Issue by mzwettler2** [pgbackrest/pgbackrest#1919]
We are using a linked PGWAL directory:
> lrwxrwxrwx 1 postgres postgres    15 Nov  7 17:50 pg_wal -> /pgwal/pg14_wal

pgbackrest Docu (https://pgbackrest.org/user-guide-rhel.html#quickstart/perform-restore):

> The cluster needs to be stopped (in this case it is already stopped) and all files must be removed from the PostgreSQL data directory.

We found that the PGWAL directory must also be empty, otherwise:

> WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/pgdata/pg14' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
> **ERROR: [040]: unable to restore to path '/pgwal/pg14_wal' because it contains files**
>        HINT: try using --delta if this is what you intended.
> 

This happens even if we use "--force --delta".

QUESTION:
The restore is not working until we also delete the content of the PGWAL directory.
Deleting the PGWAL content also deletes the very last current logfile!
What's going on here?

**Comment by pgstef** [comment]
Hi,

pgBackRest can't predict what's on disk, `--delta` would indeed remove what's on disk but not in the backup. 
In most recovery situations, users are not erasing their production system. That's even what is suggested in PG [docs](https://www.postgresql.org/docs/current/continuous-archiving.html#BACKUP-PITR-RECOVERY):

> If you have the space to do so, copy the whole cluster data directory and any tablespaces to a temporary location in case you need them later. Note that this precaution will require that you have enough free space on your system to hold two copies of your existing database. If you do not have enough space, you should at least save the contents of the cluster's pg_wal subdirectory, as it might contain logs which were not archived before the system went down.

> If you have unarchived WAL segment files that you saved in step 2, copy them into pg_wal/. 

The restore command is there to help you fetch the backup files but you're still responsible of the recovery. So if you know there are unarchived WALs, saving them before the restore is a good thing indeed :+1: 

Kind Regards

**Comment by mzwettler2** [comment]
@pgstef 

Why does pgbackrest require a linked PGWAL to be empty? It could simply restore archived WALs and ignore/overwrite existing ones. There would be no need to save or copy back something manually.

**Comment by pgstef** [comment]
doesn't care about the link. the delta restore will remove everything on disk that is not existing in the backup. that's a standard process for PG backups anyway.
guessing what's on disk would depend on the situation (and have risks of corruption).
it may seem "normal" for your very specific use-case but not for all of them. 

as said, the tool is only there to help you push data files / archives to a safe place and get it back. not to completely handle your DR. this extra copy step should be part of your DR strategy.

**Comment by mzwettler2** [comment]
@pgstef 

Ok. Seems to be a question of faith. 

I would subordinate everything to a standard DR recovery. this should be as automated as possible, without manual intermediate steps. It could be easily achived by using a linked PGWAL and simply restoring any archived WALs needed. No need to save or copy back something or even thinking about it.

**Comment by dwsteele** [comment]
If you have set a restore_command for your recovery then any local WAL that exists in the archive will be ignored anyway. What you are trying to do here is not standard. Standard is to recover from the archive.

If you have unarchived WAL then you should use the archive-push command to archive it or make a copy *outside* PGDATA. What happens if your first recovery is not successful? Postgres may have already recycled the WAL that you need and you'll be in a bad state.

The method pgBackRest uses (the same one in the Postgres docs) ensures that each restore/recovery will work. Not just the first one hoping that there is valid data in pg_wal.
