### ISSUE TITLE
Ubuntu 16.04 - libplrpc-perl not found

### ISSUE THREAD

**Issue by tosigus** [pgbackrest/pgbackrest#192]
Installation on Ubuntu 16.04

```shell
sudo apt install libdbd-pg-perl libdbi-perl libnet-daemon-perl libplrpc-perl
```

```shell
E: Package libplrpc-perl not found
```

Any hints?

**Comment by dwsteele** [comment]
Hi Torsten,

Try:
```
sudo apt install libdbd-pg-perl libdbi-perl
```
I include all the packages in the guide so it doesn't prompt the user at the command line.  In the above command apt will inform you of the other packages it is going to install and require a confirmation.  

I would definitely appreciate it if you attached that output here.

Thanks, David

**Comment by tosigus** [comment]
Hi David,

on a fresh 16.04 Installation with
`sudo apt install libdbd-pg-perl libdbi-perl libnet-daemon-perl libdbd-pg-perl libdbi-perl`
and following your User-Guide, I’ll get when I test with pgbackrest:

`Can't locate pgBackRest/Archive.pm in @INC (you may need to install the pgBackRest::Archive module) (@INC contains: /usr/bin/../lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/bin/pgbackrest line 20.
BEGIN failed--compilation aborted at /usr/bin/pgbackrest line 20.
`

(it worked on my 14.04 Test-Installation)

Thanks for your help!

**Comment by dwsteele** [comment]
It looks like 16.04 has removed /usr/lib/perl5 from the search path.  Try installing the pgBackRest module in /usr/share/perl5. So the install would look like:
```
sudo cp -r ~/pgbackrest-release-1.01/lib/pgBackRest /usr/share/perl5
sudo find /usr/share/perl5/pgBackRest -type f -exec chmod 644 {} +
sudo find /usr/share/perl5/pgBackRest -type d -exec chmod 755 {} +
sudo cp ~/pgbackrest-release-1.01/bin/pgbackrest /usr/bin/pgbackrest
sudo chmod 755 /usr/bin/pgbackrest
sudo mkdir -m 770 /var/log/pgbackrest
sudo chown postgres:postgres /var/log/pgbackrest
```
-David

**Comment by tosigus** [comment]
It works. Thanks!

**Comment by dwsteele** [comment]
Thanks for the heads up.  I will adjust the 16.04 user guide when there is one, which should be pretty soon.
