### ISSUE TITLE
restore instance to new directory?

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#1923]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.07  (Upgrading soon, I promise.)

2. PostgreSQL version:
9.6.24 (Upgrading it soon, too.)

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 6.10

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/10007379/pgbackrest.conf.txt)

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I need to restore a copy of an instance to another directory on the same server as my production database.  Before I do something stupid which stomps all over the live data, I want to verify that my command does what I want it to.
The production PGDATA=/Databases/9.6/data and I want to put the restored instance in /Restored/9.6/data.  Will this work, or am I missing something?
`pgbackrest restore --stanza=localhost --set=20221106-000003F --pg-path=/Restored/9.6/data`

**Comment by dwsteele** [comment]
This should work, yes. We also have several safeguards to avoid overwriting a running cluster.

But, obviously, restoring to a production system is not ideal so...

**Comment by RonJohn2** [comment]
Thanks.  You're correct that I'd prefer to restore to a virgin VM, but that takes **time** and paperwork that the customer does not have.
