### ISSUE TITLE
ERROR: [031]: invalid option '--pg-path=/Restored/9.6/data'

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#1925]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.07

2. PostgreSQL version:
9.6.24

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 6.10

4. Did you install pgBackRest from source or from a package?
Postgresql community package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Why the error?  Is --pg-path not implemented in 2.07?
```
$ pgbackrest restore --stanza=localhost --pg-path=/Restored/9.6/data --set=20221106-000003F --log-level-file=info --log-level-console=info --process-max=8
ERROR: [031]: invalid option '--pg-path=/Restored/9.6/data'

$ pgbackrest help restore
pgBackRest 2.07 - 'restore' command help

Restore a database cluster.

This command is generally run manually, but there are instances where it might
be automated.

Command Options:

  --db-include                     restore only specified databases
[snip]
  --repo-type                      type of storage used for the repository
                                   [default=posix]

Stanza Options:

  --pg-path                        postgreSQL data directory

$ pgbackrest help restore --pg-path
ERROR: [031]: invalid option '--pg-path'

```

**Comment by pgstef** [comment]
Hi,

2.07 is very old (November 2018) but as the the old [documentation](https://github.com/pgbackrest/pgbackrest/blob/release/2.07/doc/xml/reference.xml#L750) already stated:

> All pg- options are indexed to allow for configuring multiple PostgreSQL hosts. For example, a single primary is configured with the pg1-path, pg1-port, etc. options.

So you should probably use `pg1-path` and make sure not to use `db-path` in your config given that's a long time deprecated option name and could potentially conflict.

Regards

**Comment by RonJohn2** [comment]
> Hi,
> 
> 2.07 is very old (November 2018) 

All the EOL software is being replaced "soon", and PgBR 2.07 will be replaced at the same time.

I'd like to install a modern version, but the Postgresql package requires lz4 and zstd (I think those are the packages), which the sysadmins refuse to install, since they aren't in base RHEL 6.10.

> but as the the old [documentation](https://github.com/pgbackrest/pgbackrest/blob/release/2.07/doc/xml/reference.xml#L750) already stated:
> 
> > All pg- options are indexed to allow for configuring multiple PostgreSQL hosts. For example, a single primary is configured with the pg1-path, pg1-port, etc. options.
> 

I suggest then that the documentation refer to `pgX-` instead of just `pg-`.  That, I think, would eliminate confusion and ambiguity.

> So you should probably use `pg1-path` and make sure not to use `db-path` in your config given that's a long time deprecated option name and could potentially conflict.

That worked.  Thank you.

**Comment by dwsteele** [comment]
> I suggest then that the documentation refer to pgX- instead of just pg-. That, I think, would eliminate confusion and ambiguity.

We considered this and `pg?-path`, but decided they are just as confusing after gathering feedback. So, instead we'd getting issues where users specified `pgX-path=/...`.

One possibility here would be to add a hint to the error message. I'll have a look and see if that is feasible.

**Comment by dwsteele** [comment]
> One possibility here would be to add a hint to the error message. I'll have a look and see if that is feasible.

Looks like we had already improved this error message, but I also added a hint in PR #1929.
