### ISSUE TITLE
Question about exclude option

### ISSUE THREAD

**Issue by PeterEgorov** [pgbackrest/pgbackrest#1927]
Whether it is possible to remove all the files of the table from the backup according to the template, if the table has several files. 
For example, 6789.1, 6789.2, 6789.3, etc.

--exclude=base/12345/6789*

**Comment by dwsteele** [comment]
Wildcards are not supported for exclusions and we have no plans to add them. What you are proposing here is not a good idea and might make the cluster unrecoverable.
