### ISSUE TITLE
Problem with archiving

### ISSUE THREAD

**Issue by jppo** [pgbackrest/pgbackrest#1930]
1. pgBackRest version: 2.41

2. PostgreSQL version: 14.1

3. Operating system/version : Centos 7.9

4. Did you install pgBackRest from source or from a package : package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
----------------------------------
[global]
repo1-path=/data/backup/PGBACKREST_LIB
repo1-retention-full-type=count
repo1-retention-full=1
process-max=2
log-level-console=info
log-level-file=debug
archive-async=y
archive-push-queue-max=256MB
spool-path=/data/backup/PGBACKREST_SPOOL

[carto_ref_prod]
pg1-path=/data/pgdata
pg1-port=5432

- `postgresql.conf` settings applicable to pgBackRest 
  (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
---------------------------------------------------------
archive_mode = on
archive_command = 'test -f /tmp/backup_temoin || exit 0 && /bin/pgbackrest --stanza=carto_ref_prod archive-push %f'

max_wal_senders = 10

listen_addresses = '*'
port = 5432

wal_level = replica
----------------------------------------------------------
- errors in the postgresql log file before or during the time you experienced the issue
----------------------------------------------------------
2022-11-17 15:38:48.601 P00   INFO: archive-push command begin 2.41: [00000001000001DA000000B8] --archive-async --archive-push-queue-max=256MB --exec-id=5333-cab101e3 --log-level-console=info --log-level-file=debug --pg1-path=/data/pgdata --process-max=2 --repo1-path=/data/backup/PGBACKREST_LIB --spool-path=/data/backup/PGBACKREST_SPOOL --stanza=carto_ref_prod
ERROR: [073]: unable to list file info for missing path '/data/pgdata/archive_status'
2022-11-17 15:38:48.704 P00   INFO: archive-push command end: aborted with exception [073]
2022-11-17 14:38:48.705 GMT [4891] LOG:  échec de la commande d'archivage avec un code de retour 73
----------------------------------------------------------

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
------------------------------------------------------------
                                    version: 2.41
                                    command: archive-push:async
                                    options: [/data/pgdata] --archive-async --archive-push-queue-max=256MB --exec-id=5425-387cf88c --log-level-console=off --log-level-file=debug --log-level-stderr=off --pg1-path=/data/pgdata --process-max=2 --repo1-path=/data/backup/PGBACKREST_LIB --spool-path=/data/backup/PGBACKREST_SPOOL --stanza=carto_ref_prod
    
                                    stack trace:
                                    storage/iterator.c:storageItrNew:158:(trace log level required for parameters)
                                    storage/storage.c:storageNewItr:(trace log level required for parameters)
                                    storage/storage.c:storageList:(trace log level required for parameters)
                                    command/archive/push/push.c:archivePushReadyList:(trace log level required for parameters)
                                    command/archive/push/push.c:archivePushProcessList:(trace log level required for parameters)
                                    command/archive/push/push.c:cmdArchivePushAsync:(void)
                                    main.c:main:(debug log level required for parameters)
                                    --------------------------------------------------------------------
2022-11-17 15:43:46.560 P00   INFO: archive-push:async command end: aborted with exception [073]
2022-11-17 15:43:46.560 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)
2022-11-17 15:43:46.560 P00  DEBUG:     common/lock::lockRelease: => true
2022-11-17 15:43:46.560 P00  DEBUG:     command/exit::exitSafe: => 73
2022-11-17 15:43:46.560 P00  DEBUG:     main::main: => 73
----------------------------------------------------

7. Describe the issue:
Archiving is not possible with a message found in the "spool" directory,
file "archive/carto_ref_prod/out/global.error" contains :
unable to list file info for missing path '/data/pgdata/archive_status'

===========================================================
Directory structure used :
/data/backup
/data/pgarchives
/data/pgdata
    pg_log link to /data/pglog
    pg_wal link to /data/pgarchives
/data/pglog

All directories are mountpoint for distinct filesystems.

So looking for '/data/pgdata/archive_status' does not work as it is contained in '/data/pgarchives'

Regards

JP P

**Comment by dwsteele** [comment]
Looks like your archive_command is incorrect. The user guide says to use %p:
```
archive_command = 'test -f /tmp/backup_temoin || exit 0 && /bin/pgbackrest --stanza=carto_ref_prod archive-push %p'
```
