### ISSUE TITLE
bug on pgbackrest info using two dedicated  backup hosts posix (setting style ssh) with repositories ciphering

### ISSUE THREAD

**Issue by Tiago-DBA** [pgbackrest/pgbackrest#1932]
[backuphost_1.conf.txt](https://github.com/pgbackrest/pgbackrest/files/10078200/backuphost_1.conf.txt)
[backuphost_2.conf.txt](https://github.com/pgbackrest/pgbackrest/files/10078201/backuphost_2.conf.txt)
[pgbackrest_postgres_host_1.conf.txt](https://github.com/pgbackrest/pgbackrest/files/10078202/pgbackrest_postgres_host_1.conf.txt)
[pgbackrest_postgres_host_2.conf.txt](https://github.com/pgbackrest/pgbackrest/files/10078203/pgbackrest_postgres_host_2.conf.txt)
[stanza_create_from_repository_host.log](https://github.com/pgbackrest/pgbackrest/files/
[pgbackrestinfo_debug.txt](https://github.com/pgbackrest/pgbackrest/files/10078273/pgbackrestinfo_debug.txt)
10078204/stanza_create_from_repository_host.log)
[stanza-create-remote_pghost1.log](https://github.com/pgbackrest/pgbackrest/files/10078205/stanza-create-remote_pghost1.log)
[stanza-create-remote_pghost2.log](https://github.com/pgbackrest/pgbackrest/files/10078206/stanza-create-remote_pghost2.log)

1. pgBackRest version: 2.41

2. PostgreSQL version: 13.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
"SUSE Linux Enterprise Server 15 SP2"

4. Did you install pgBackRest from source or from a package?
community RPMS

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) 
	     backuphost_1.conf.txt
		 backuphost_2.conf.txt
		 pgbackrest_postgres_host_1.conf.txt
		 pgbackrest_postgres_host_2.conf.txt
	 
    - `postgresql.conf` 
			archive_mode = 'True'
            archive_command = '/usr/bin/pgbackrest --stanza=appli1_sandbox archive-push %p'
			listen_addresses = '*'
			port = 54320
			max_wal_senders = '20'
            wal_level = 'logical'
	
    - errors in the postgresql log 
		   => no errors
		   
    - pgbackrest log files:
		stanza_create_from_repository_host.log
		stanza-create-remote_pghost1.log
		stanza-create-remote_pghost2.log]

7. Describe the issue:

Architecture: 2 backup dedicated hosts : type posix , set in ssh way.
All repositories are ciphered.
All stanzas have two postgresql instances.

**On postgres servers**, 'pgbackrest info' gives incomplete information: information from repo 1 is ok, information from repo2 brings an error linked to ciphering (see log file pgbackrestinfo.log for trace)
pgbackrest info
stanza: appli1_sandbox
    status: mixed
        repo1: ok
        repo2: error (other)
               [FormatError] unable to load info file '/pgbackrest/repo/backup/appli1_sandbox/backup.info' or '/pgbackrest/repo/backup/appli1_sandbox/backup.info.copy':
               FormatError: key/value found outside of section at line 1: Salted__T4▒x▒c%▒gq▒▒E▒m▒T▒▒>▒7▒▒▒▒mG▒+▒N)▒▒l▒n▒|▒|▒K▒▒▒'p▒͉▒▒03▒▒▒▒ ▒z▒=ٌ▒:ٯEڢ3l*▒▒5N▒▒9▒▒▒7▒Rƒ7}K▒̘:[g3N▒▒▒$▒▒7▒%f▒▒դ▒▒ ▒l▒▒▒
               FormatError: key/value found outside of section at line 1: Salted__T4▒x▒c%▒gq▒▒E▒m▒T▒▒>▒7▒▒▒▒mG▒+▒N)▒▒l▒n▒|▒|▒K▒▒▒'p▒͉▒▒03▒▒▒▒ ▒z▒=ٌ▒:ٯEڢ3l*▒▒5N▒▒9▒▒▒7▒Rƒ7}K▒̘:[g3N▒▒▒$▒▒7▒%f▒▒դ▒▒ ▒l▒▒▒
               HINT: backup.info cannot be opened and is required to perform a backup.
               HINT: has a stanza-create been performed?
    cipher: mixed
        repo1: aes-256-cbc
        repo2: none

    db (current)
        wal archive min/max (13): 0000000B000000000000007D/0000000B0000000000000081

        full backup: 20221123-181729F
            timestamp start/stop: 2022-11-23 18:17:29 / 2022-11-23 18:17:40
            wal start/stop: 0000000B000000000000007E / 0000000B000000000000007F
            database size: 67.2MB, database backup size: 67.2MB
            repo1: backup set size: 3MB, backup size: 3MB

Moreover this could be fixed if you copy to postgresql servers ciphering parameters this way:

[global]
repo1-cipher-type=aes-256-cbc
repo1-cipher-pass=XXX
repo2-cipher-type=aes-256-cbc
repo2-cipher-pass=XXX

**but** but there is a huge caveat: pgbackrest stanza-create, from a repository server, doesn't work anymore  (attached stanza-create.log and stanza-create-remote ):
pgbackrest stanza-create --stanza=appli1_sandbox
WARN: unable to check pg1: [OptionInvalidValueError] remote-0 process on 'suvm-sles15-bac11.unix.sits.credit-agricole.fr' terminated unexpectedly [32]: ERROR: [032]: local repo1 and repo2 paths are both '/var/lib/pgbackrest' but must be different
WARN: unable to check pg2: [OptionInvalidValueError] remote-0 process on 'suvm-sles15-bac12.unix.sits.credit-agricole.fr' terminated unexpectedly [32]: ERROR: [032]: local repo1 and repo2 paths are both '/var/lib/pgbackrest' but must be different
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?

Thank you very much.

**Comment by dwsteele** [comment]
This is a known issue, see https://github.com/pgbackrest/pgbackrest/projects/2#card-37322479.

For now, the workaround is to get info for each stanza individually, .e.g. `pgbackrest info <stanza>`.
