### ISSUE TITLE
ASSERT: [025]: unable to find '...' in string list in backup command of type diff after update to 2.42

### ISSUE THREAD

**Issue by m-borger** [pgbackrest/pgbackrest#1933]
1. pgBackRest version:
version: 2.42

2. PostgreSQL version:
Tested in 12.13 and 15.0. This report will describe the situation on PG 12.13.

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
`Red Hat Enterprise Linux Server release 7.9 (Maipo)`

4. Did you install pgBackRest from source or from a package?
From repo `pgdg12/7Server/x86_64`

5. Please attach the following as applicable:
I assumed the backup log would be sufficient, if you should need more please let me know.

7. Describe the issue:
Executing a backup like this:
`pgbackrest --stanza=mystanza --type=diff backup`
causes an error like this:
`ASSERT: [025]: unable to find '20221118-190002F' in string list`
See attached file for the complete log.

Only a diff backup is affected, a full backup succeeds as normal. After this full backup another diff also succeeds, so it only seems to be a problem when a diff backup of 2.42 is made on top of a 2.41 full backup.

So making an extra full after the error could be a suitable workaround and might make this issue less urgent.

[backup-mystanza.log](https://github.com/pgbackrest/pgbackrest/files/10090312/backup-mystanza.log)

**Comment by ulfedf** [comment]
Have exactly the same error on Centos 7 and here it occurred when a incremental backup was executed after pgbackrest was upgraded from 2.41 to 2.42.

**Comment by dwsteele** [comment]
Well, that's certainly not good. Provisionally fixed in PR #1935, but I need to think about it a little more.

**Comment by jaymefSO** [comment]
having the same issue as well

ASSERT: [025]: unable to find '20221120-074502F' in string list
        --------------------------------------------------------------------
        If SUBMITTING AN ISSUE please provide the following information:

        version: 2.42
        command: backup
        options: --exec-id=1124298-89053461 --pg1-host=dbsedrver --pg1-path=/var/lib/pgsql/11/data --process-max=2 --repo1-path=/storage/pgbackrest --repo1-retention-diff=3 --repo1-retention-full=5 --repo1-retention-full-type=count --stanza=dbserver --start-fast --type=diff

        stack trace:
        common/type/stringList.c:strLstFindIdx:293:(test build required for parameters)
            ... function(s) omitted ...
        info/manifest.c:manifestBuildIncr:(debug log level required for parameters)
        command/backup/backup.c:backupBuildIncr:(debug log level required for parameters)
        command/backup/backup.c:cmdBackup:(debug log level required for parameters)
        main.c:main:(debug log level required for parameters)

**Comment by dwsteele** [comment]
I spent some more time on the patch and figured out why the tests failed to catch this issue (see PR #1935 for details). We are planning a release in a few days after another round of review.

For now the only mitigations are to create a new full backup or revert to 2.41.

**Comment by dwsteele** [comment]
@m-borger, @uldedf, @jaymefSO How would you like your names to appear in the release notes?

**Comment by ulfedf** [comment]
That’s ok

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: David Steele ***@***.***>
Skickat: Monday, November 28, 2022 5:37:40 AM
Till: pgbackrest/pgbackrest ***@***.***>
Kopia: Ulf Edfors ***@***.***>; Comment ***@***.***>
Ämne: Re: [pgbackrest/pgbackrest] ASSERT: [025]: unable to find '...' in string list in backup command of type diff after update to 2.42 (Issue #1933)


@m-borger<https://github.com/m-borger>, @uldedf, @jaymefSO<https://github.com/jaymefSO> How would you like your names to appear in the release notes?

**Comment by m-borger** [comment]
"Marcel Borger" will be fine. 
Glad that you were able to find the cause of the issue so quickly and also could improve the test that masked the issue.

**Comment by dwsteele** [comment]
pgBackRest 2.43 has been released to fix this bug. We'll leave the issue open for now to make it easier for others to find.

**Comment by dwsteele** [comment]
Closing this since the 2.43 release has been out for a few weeks.
