### ISSUE TITLE
Changing compress-level on existing stanza

### ISSUE THREAD

**Issue by samng01** [pgbackrest/pgbackrest#1936]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.40

2. PostgreSQL version: 14.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  RHEL 8.6

4. Did you install pgBackRest from source or from a package? Package

5. Describe the issue:

A current stanza was created with _compress-level=3_. I am looking to update the pgbackrest.conf file and change the option to _compress-level=9_. Is there a way to apply these changes without recreating the stanza? The only thing I've seen in the documentation is the stanza-upgrade option, which requires a stop and start of the stanza. TIA

**Comment by dwsteele** [comment]
You can change compress-level any time you want. If you change compress-type it will affect the archive immediately but backups will not be change until the next full.
