### ISSUE TITLE
expire operation is taking more time 

### ISSUE THREAD

**Issue by Hulkyk** [pgbackrest/pgbackrest#1937]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.40 

2. PostgreSQL version: 11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 1 master 2 standby 1 backup host

5. Did you install pgBackRest from source or from a package? package

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s):
`
# general options
[global]
log-level-console=info
log-level-file=debug
start-fast=y
delta=y
backup-standby=y
compress-type=lz4
process-max=4
start-fast=y
repo1-retention-full=2
repo1-type=gcs
repo1-cipher-type=none
repo1-gcs-bucket=postgres_bkp
repo1-gcs-key-type=auto
repo1-path=/pgbackrest/prod
spool-path=/var/spool/pgbackrest

[global:archive-push]
process-max=4
archive-async=y
archive-push-queue-max=1000GB

[global:archive-get]
process-max=4
archive-async=y
archive-get-queue-max=20GB

# tls server options
tls-server-address=*
tls-server-cert-file=/etc/pgbackrest/certs/pgbackrest.crt
tls-server-key-file=/etc/pgbackrest/certs/pgbackrest.key
tls-server-ca-file=/etc/pgbackrest/certs/ca.crt
tls-server-auth=primary=demo
tls-server-auth=replica1=demo
tls-server-auth=replica2=demo

[demo]
pg1-host=primary
pg1-path=/var/lib/postgresql/11/main
pg1-host-type=tls
pg1-host-cert-file=/etc/pgbackrest/certs/pgbackrest.crt
pg1-host-key-file=/etc/pgbackrest/certs/pgbackrest.key
pg1-host-ca-file=/etc/pgbackrest/certs/ca.crt
pg1-host-user=postgres
pg2-host=replica1
pg2-path=/var/lib/postgresql/11/main
pg2-host-type=tls
pg2-host-cert-file=/etc/pgbackrest/certs/pgbackrest.crt
pg2-host-key-file=/etc/pgbackrest/certs/pgbackrest.key
pg2-host-ca-file=/etc/pgbackrest/certs/ca.crt
pg2-host-user=postgres
pg3-host=replica2
pg3-path=/var/lib/postgresql/11/main
pg3-host-type=tls
pg3-host-cert-file=/etc/pgbackrest/certs/pgbackrest.crt
pg3-host-key-file=/etc/pgbackrest/certs/pgbackrest.key
pg3-host-ca-file=/etc/pgbackrest/certs/ca.crt
pg3-host-user=postgres`

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

Backup is running file no issue with settings 

    - errors in the postgresql log file before or during the time you experienced the issue - No errors
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

My database size is around 20TB and my backup schedule is like on sunday, i take full backup and for remaining days diff backup  my repo is on gcs bucket, it takes around 32+ hrs for backup and the expire is taking more time like for removing a single diff backup the pgbackrest is taking more that 26+ hrs and its disturbing the backup schedule.

I need your suggestions on how to tune the expire command to run faster.
My backup host is having 4 cores and 16 GB of memory  : Do i need to bump up the specs on backup host  ?
What are the things need to check to address the slowness of expire command  ?
Is there any possibility to remove the repo directly from gcs bucket as expire is taking more time ?

**Comment by dwsteele** [comment]
You should consider enabling file bundling: https://pgbackrest.org/user-guide.html#backup/bundle

This generates fewer files in the repository which makes all operations (including expire) faster.

**Comment by Hulkyk** [comment]
Sure i will look into that feature and does increasing the process-max=8 and memory to 64 GB also help to decrease the full backup time ans expire ?

**Comment by dwsteele** [comment]
`process-max=8` will probably help with full backup time but it won't help with expire.
