### ISSUE TITLE
pgbackrest expects repo1-s3-key even when repo1-s3-role is specified

### ISSUE THREAD

**Issue by rituraj-AU** [pgbackrest/pgbackrest#1939]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: v2.40

2. PostgreSQL version: 13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
pgbackrest.conf: |
    [global]
    compress-level=3
    compress-type=lz4
    process-max=4
    repo1-cipher-type=none
    repo1-path=/my/db/
    repo1-retention-diff=2
    repo1-retention-full=2
    repo1-s3-bucket=my-bucket-dev
    repo1-s3-endpoint=s3.amazonaws.com
    repo1-s3-key=
    repo1-s3-key-secret=
    repo1-s3-key-type=auto
    repo1-s3-region=us-west-2
    repo1-s3-role=my.role
    repo1-type=s3
    spool-path=/var/run/postgresql
    start-fast=y
    [poddb]
    pg1-port=5432
    pg1-host-user=postgres
    pg1-path=/var/lib/postgresql/data
    pg1-socket-path=/var/run/postgresql
    link-all=y
    [global:archive-push]
    [global:archive-get]
```
    - errors in the postgresql log file before or during the time you experienced the issue
```
ERROR: [032]: environment variable 'repo1-s3-key' must have a value
2022-11-29 19:26:34,003 - ERROR - history - Command '['pgbackrest', '--stanza=poddb', 'info', '--output=json']' returned non-zero exit status 32.
Traceback (most recent call last):
  File "/scripts/pgbackrest-rest.py", line 362, in history_refresher
    pgbackrest_out = check_output(['pgbackrest', '--stanza={0}'.format(stanza), 'info', '--output=json']).decode("utf-8")
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pgbackrest', '--stanza=poddb', 'info', '--output=json']' returned non-zero exit status 32.
```
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I am running pgbackrest through a k8s pod which uses kube2iam to assign an AWS role to the pod. The role has permissions to the s3 bucket configured for the backup. However, when I try running the backup, it fails because it expects the s3 key and s3 secret key. It was my understanding that if I use a role then that allows me to avoid specifying secrets keys etc. Am I wrong?
Also, my pgbackrest is being run under timescaledb's preconfigured pgbackrest.
thanks

**Comment by dwsteele** [comment]
Looks like repo1-s3-key is being set to no value in an env var (I also see it in your config):
```
ERROR: [032]: environment variable 'repo1-s3-key' must have a value
```
repo1-s3-key (and PGBACKREST_REPO1_S3_KEY in the env) should not be present when they are not required.

**Comment by rituraj-AU** [comment]
Yeah, there was a conflict in the parent chart causing both values to be injected into the subchart. This is no longer an issue. Thanks for your inputs.
