### ISSUE TITLE
Incorrect size in pgbackrest info for backup size ? 

### ISSUE THREAD

**Issue by blogh** [pgbackrest/pgbackrest#194]
Hi thanks for the great software.

I noticed something strange with this backup size. shouldn't it be 9.2M ?

```
postgres@x64lmwbio9e:/$ du -ch /data01/postgres/bast01 |grep total
337M    total
postgres@x64lmwbio9e:/$ du -ch /backup01/postgres/bast01/pgbackrest/backup/bast01 |grep total
9.2M    total

postgres@x64lmwbio9e:~$ pgbackrest info --stanza bast01
stanza: bast01
    status: ok

    full backup: 20160519-140630F
        start / stop timestamp: 2016-05-19 14:05:53 / 2016-05-19 14:06:30
        database size: 336.3MB, backup size: 336.3MB
        repository size: 4.3MB, repository backup size: 4.3MB
```

**Comment by dwsteele** [comment]
The repo size includes only the files that make up the database backup.  There are also files in the repo, info, history, manifests, etc.  Also, only the file size is counted, but extra space may be used do to block size, etc.  In larger databases this is negligible but in smaller databases it can be disproportionate.

To get a better idea of how much space the actual files are using, try:
```
du -sh --exclude=backup.manifest /backup01/postgres/bast01/pgbackrest/backup/bast01/latest/
```
I'd be interested to see what that returns.

**Comment by blogh** [comment]
Here it is.

```
postgres@x64lmwbio9e:/$ du -sh --exclude=backup.manifest /backup01/postgres/bast01/pgbackrest/backup/bast01/latest/
8.8M    /backup01/postgres/bast01/pgbackrest/backup/bast01/latest/

```

**Comment by dwsteele** [comment]
Ah, I see.  The backup size refers to the size of the backup before compression.  This will be the same as database size for full backups and (hopefully) less for incr/diff backups.

See this section in the user guide for details on info output: http://www.pgbackrest.org/user-guide.html#quickstart/backup-info

**Comment by blogh** [comment]
my bad ... I was so sure i didn't read.  Sorry for the waste of your time.

**Comment by dwsteele** [comment]
No worries.  Glad you like the software!
