### ISSUE TITLE
pgbackrest stanza check taking long time and backups also failing 

### ISSUE THREAD

**Issue by narendrapostgresdba** [pgbackrest/pgbackrest#1944]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.41

2. PostgreSQL version:12.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7.9

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
we are configuring pgbackrest on our system . when we tried stanza check / backup command , getting error . could you please help me to understand the issue . 

pgbackrest.conf file 

[cip_**]
db-path=/pgDATA/12/data

[global]
repo-path=/pgBACKUP/pgbackrest
retention-full=4
retention-archive=4
archive-timeout=86400ms
process-max=4

[global:archive-push]
process-max=5

error from the log file 

ERROR: [037]: option 'pg1-path' must be specified when relative wal paths are used
       HINT: is %f passed to archive-push instead of %p?
       HINT: PostgreSQL may pass relative paths even with %p depending on the environment.
2022-12-09 10:33:39.521 CET [5957] LOG:  archive command failed with exit code 37
2022-12-09 10:33:39.521 CET [5957] DETAIL:  The failed archive command was: pgbackrest --stanza
=cip_*** archive-push pg_wal/000000010000001900000066

**Comment by pgstef** [comment]
Hi,

I'm not sure where your found your configuration examples but you're using deprecated options.
It should look like:
```ini
[demo]
pg1-path=/pgDATA/12/data

[global]
repo1-path=/pgBACKUP/pgbackrest
repo1-retention-full=4
archive-timeout=86400ms
process-max=4

[global:archive-push]
process-max=5
```

Also, what `archive_command` are you using? It should be something like: `pgbackrest --stanza=demo archive-push %p`

`cip_**` is also a weird stanza name. `*` might perhaps be a problem. If possible, avoid that character in your stanza name.

Kind Regards

**Comment by narendrapostgresdba** [comment]
Hi Stefan ,

I changed config and tried stanza check again but , it is not working

==> pgbackrest --stanza=servername  --log-level-console=info check
2022-12-09 15:51:07.276 P00   INFO: check command begin 2.41:
--archive-timeout=86400ms --exec-id=17052-9462c4b5 --log-level-console=info
--pg1-path=/pgDATA/12/data --repo1-path=/pgBACKUP/servername
--stanza=servername
2022-12-09 15:51:07.888 P00   INFO: check repo1 configuration (primary)
2022-12-09 15:51:08.091 P00   INFO: check repo1 archive for WAL (primary)

it is not coming out of the prompt

config file is as below
[ servername  ]
pg1-path=/pgDATA/12/data

[global]
repo1-path=/pgBACKUP/ servername
repo1-retention-full=4
archive-timeout=86400ms
process-max=4

[global:archive-push]
process-max=5

Regards,
Narendra

**Comment by pgstef** [comment]
Look at PG logs to debug archiving issues. You have lots of white-spaces in your config, the problem could perhaps come from there. But hard to say without more logs.

**Comment by narendrapostgresdba** [comment]
Hi Stefan ,

I am getting below error , but pg logs don't have any error .

2022-12-09 16:09:07.527 P00   INFO: check repo1 configuration (primary)
2022-12-09 16:09:07.730 P00   INFO: check repo1 archive for WAL (primary)
ERROR: [082]: WAL segment 0000000100000052000000B1 was not archived before
the 60000ms timeout
       HINT: check the archive_command to ensure that all options are
correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2022-12-09 16:10:07.751 P00   INFO: check command end: aborted with
exception [082]

**Comment by narendrapostgresdba** [comment]
Hi Stefan ,

From the logs , I could see , archive command it is showing old stanza name
.

2022-12-12 07:42:36.309 CET [8383] DETAIL:  The failed archive command was:
pgbackrest --stanza=cip_servername archive-push
pg_wal/000000010000001B00000057
ERROR: [037]: option 'pg1-path' must be specified when relative wal paths
are used

actual archive command looks like this

postgres=# show archive_command;
                  archive_command
----------------------------------------------------
 pgbackrest --stanza=servername archive-push %p


not sure , why it is showing old stanza name in the log file .

==> pgbackrest info
stanza: servername
    status: error (no valid backups)
    cipher: none

    db (current)
        wal archive min/max (12):
000000010000001B00000057/000000010000001B00000067

Regards,
Narendra

**Comment by pgstef** [comment]
Hi,
Did you apply the change by performing a PG reload ? (and did that reload appeared in PG logs?)

**Comment by narendrapostgresdba** [comment]
Hi Stefan,

Yes , when i tried command show archive_command; in psql prompt , it is
giving correct one . But when I ran  stanza check command ,it was showing
old stanza details . Please guide me to troubleshoot further .

Regards,
Narendra

**Comment by pgstef** [comment]
> Please guide me to troubleshoot further

Honestly, I don't know how you ended up in that situation :shrug: 

> when I ran stanza check command ,it was showing old stanza details

What command do you use exactly? What is your new configuration? And what does PG logs show exactly?

> when i tried command show archive_command; in psql prompt , it is giving correct one

Are you sure to connect to the same db as in the pgBackRest command?

Have you looked at the running processes? How did you change your stanza name? Did you turned off the async archiving and stopped the running processes before doing that? There must be some left-overs if your PG cluster doesn't pick-up the correct archive_command. That's a PG config issue you need to fix first.

**Comment by narendrapostgresdba** [comment]
Hello Stefan ,

when I am running backup , getting below error . what could be the possible
issue ?

ERROR: [058]: current checkpoint '1a/22000060' is less than backup start
'59/33000028'

Regards,
Narendra

**Comment by dwsteele** [comment]
This either a configuration error, your storage is not properly fsyncing, or pgbackrest can't see the fsynced data because it is running on a different host from postgres.

Please don't use old issues to bring up a completely new problem. Open a new issue with all the requested info so we have a chance to see what the problem is.
