### ISSUE TITLE
Create full backup (pg streaming replication combined with pgBackRest dedicated repository)

### ISSUE THREAD

**Issue by kocbekju** [pgbackrest/pgbackrest#1945]
Hello. I'm trying to set up Postgres streaming replication combined with pgBackRest dedicated repository. I have three linux servers, two of them are used as database servers and the third one is pgbackrest server. Stanza is called jure.

1. pgBackRest version: **2.42**
2. PostgreSQL version: **14.4**
3. Operating system: **Oracle Linux 8.9**

4. Did you install pgBackRest from source or from a package? **From package** 

 Here is the configuration of each server:

- `db1`

     **pgbackrest.conf**
    `[global]`
     `repo1-host=pgbackrest`
     `repo1-host-user=postgres`
     `repo1-path=/var/lib/pgbackrest`
     `log-level-console=info`
     `log-level-file=debug`

    `[jure]`
    `pg1-path=/var/lib/postgresql/data`

     **postgres.conf**
     `...`
     `# pgBackRest section`
     `archive_command = 'pgbackrest --stanza=jure archive-push %p'`
     `archive_mode = on`
     `listen_addresses = '*'`

- `db2 pgbackrest.conf`

    `[global]`
     `repo1-host=pgbackrest`
     `repo1-host-user=postgres`
     `repo1-path=/var/lib/pgbackrest`
     `log-level-console=info`
     `log-level-file=debug`

    `[jure]`
    `pg1-path=/var/lib/postgresql/data`
     `recovery-option=primary_conninfo=db1 port=18120 user=replic_user #I'm using different postgres port from outside` 

- `pgbackrest pgbackrest.conf`
  
     `[global]`
     `repo1-path=/var/lib/pgbackrest`
     `repo1-retention-full=2`
     `log-level-console=info`
     `log-level-file=debug`
     `start-fast=y`
     `repo1-cipher-type=aes-256-cbc`
     `repo1-cipher-pass=acbd`

     `[jure]`
     `pg1-host=db1`
     `pg1-host-port=22120 # I'm using different SSH port`
     `pg1-path=/var/lib/postgresql/data`

     `pg2-host=db2`
     `pg2-host-port=22120 # I'm using different SSH port`
     `pg2-path=/var/lib/postgresql/data`

     `backup-standby=y`

I was able to create a full backup from db1, triggered on the pgBackRest server, and successfully restore everything from pgBackRest repository to db2. This was triggered on db2 and completed successfully:

`sudo -iu postgres pgbackrest --stanza=jure --type=standby restore`
`INFO: restore command begin 2.42: --exec-id=55-d7aeb2a1 --log-level-console=info --log-level-file=debug --pg1-path=/var/lib/postgresql/data --recovery-option="primary_conninfo=db1 port=18120 user=replic_user" --repo1-host=pgbackrest --repo1-host-user=postgres --repo1-path=/var/lib/pgbackrest --stanza=jure --type=standby`
`INFO: repo1: restore backup set 20221209-114809F, recovery will start at 2022-12-09 10:48:09`
`INFO: write updated /var/lib/postgresql/data/postgresql.auto.conf`
`INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)`
`INFO: restore size = 112.4MB, file total = 3298`
`INFO: restore command end: completed successfully (12423ms)`

The problem appears when I add a second host and `backup-standby=y` option to the pgbackrest.conf file on pgbackrest server. This is the output of a full backup with both hosts added:

`sudo -iu postgres pgbackrest --stanza=jure --type=full backup`
`INFO: backup command begin 2.42: --backup-standby --exec-id=14311-4029d6a0 --log-level-console=info --log-level-file=debug --pg1-host=db1 --pg2-host=db2 --pg1-host-port=22120 --pg2-host-port=22120 --pg1-path=/var/lib/postgresql/data --pg2-path=/var/lib/postgresql/data --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest --repo1-retention-full=2 --stanza=jure --start-fast --type=full`
`INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes`
`INFO: backup start archive = 000000010000000000000026, lsn = 0/26000028`
`INFO: wait for replay on the standby to reach 0/26000028`
`ERROR: [082]: timeout before standby replayed to 0/26000028 - only reached 0/26000000`
`       HINT: is replication running and current on the standby?`
`       HINT: disable the 'backup-standby' option to backup directly from the primary.`

Any advice?

Thanks and best regards,
Jure

**Comment by kocbekju** [comment]
Hello,

I belive it should. I followed [this ](https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html)tutorial and completed all the steps except the last one. I will try to do some changes on the db1 and search for them on the db2.

Thanks and best regards,
Jure

**Comment by kocbekju** [comment]
No, the replication is not working. How can I trigger it?

Best regards,
Jure

**Comment by dwsteele** [comment]
> No, the replication is not working. How can I trigger it?

Please consult the Postgres documentation for setting up replication.question.
