### ISSUE TITLE
So many WAL files and backup issue

### ISSUE THREAD

**Issue by msuluhan** [pgbackrest/pgbackrest#1948]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.24

2. PostgreSQL version:12.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.10

4. Did you install pgBackRest from source or from a package? from repository

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
[global]
repo1-path=/mnt/db_backup/backupData
repo1-retention-diff=6
repo1-retention-full=1
log-level-console=detail
log-level-file=detail
start-fast=y
process-max=4
compress-level=9

[postgres]
pg1-path=/data/patroni
pg1-port=5432
pg1-socket-path=/data/patroni

```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
```

postgres=# select * from pg_file_settings where name in ('archive_command','archive_mode', 'listen_address', 'max_wal_senders', 'wal_level', 'port');
          sourcefile           | sourceline | seqno |      name       |                   setting                    | applied | error 
-------------------------------+------------+-------+-----------------+----------------------------------------------+---------+-------
 /data/patroni/postgresql.conf |          5 |    14 | archive_command | pgbackrest --stanza=postgres archive-push %p | t       | 
 /data/patroni/postgresql.conf |          6 |    15 | archive_mode    | True                                         | t       | 
 /data/patroni/postgresql.conf |         36 |    45 | max_wal_senders | 10                                           | t       | 
 /data/patroni/postgresql.conf |         38 |    47 | port            | 5432                                         | t       | 
 /data/patroni/postgresql.conf |         47 |    56 | wal_level       | replica                                      | t       | 
(5 rows)

postgres=# 
```

    - errors in the postgresql log file before or during the time you experienced the issue
no direct errors 

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
pgbackrest --stanza=postgres --type=full backup

7. Describe the issue:
My biggest issue is there are more than 11000 files in pg_wal directory, pgbackrest is trying push wal files to pgbackrest repository but I think it could not finish before disk space problem

I run the full backup at the same time but I get following error 

```
2022-12-13 19:42:24.727 P01   INFO: backup file /data/patroni/base/1/13323 (0B, 99%)
2022-12-13 19:42:24.735 P03   INFO: backup file /data/patroni/base/1/13320 (0B, 99%)
2022-12-13 19:42:24.737 P02   INFO: backup file /data/patroni/base/1/13315 (0B, 99%)
2022-12-13 19:42:24.739 P01   INFO: backup file /data/patroni/base/1/13310 (0B, 99%)
2022-12-13 19:42:24.746 P03   INFO: backup file /data/patroni/base/1/13305 (0B, 99%)
2022-12-13 19:42:24.747 P02   INFO: backup file /data/patroni/base/1/13300 (0B, 99%)
2022-12-13 19:42:24.747 P01   INFO: backup file /data/patroni/base/1/13295 (0B, 99%)
2022-12-13 19:43:11.648 P04   INFO: backup file /data/patroni/base/16391/452770829 (440.9MB, 99%) checksum 1f4a583f014771ef0c3a2b8bf3271392a71cd787
2022-12-13 19:43:11.747 P00   INFO: full backup size = 221.5GB
2022-12-13 19:43:11.749 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2022-12-13 19:43:11.953 P00   INFO: backup stop archive = 0000001100001D46000000B5, lsn = 1D46/B55206F0
2022-12-13 19:43:11.972 P00 DETAIL: wrote 'backup_label' file returned from pg_stop_backup()
2022-12-13 19:43:11.986 P00   INFO: check archive for segment(s) 0000001100001D3C00000005:0000001100001D46000000B5
ERROR: [082]: WAL segment 0000001100001D3C00000005 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
2022-12-13 19:44:15.101 P00   INFO: backup command end: aborted with exception [082]

so increased archive_timeout parameter and run again, still working

```

So how could I fix this enormous number of WAL files issue ?   Is there any way to wipe out all the current WAL file easily and then I could get full backup again

```
Filesystem                      Size  Used Avail Use% Mounted on
tmpfs                           1.6G  1.5M  1.6G   1% /run
/dev/mapper/ubuntu--vg-LV_root   31G  8.2G   21G  29% /
tmpfs                           7.9G   64K  7.9G   1% /dev/shm
tmpfs                           5.0M     0  5.0M   0% /run/lock
tmpfs                           4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/sda2                       976M  320M  590M  36% /boot
/dev/mapper/datavg-LV_data      521G  435G   60G  88% /data
/dev/mapper/ubuntu--vg-LV_var    11G  3.1G  6.5G  32% /var
172.26.55.31:/DATA/nfsshare    1006G   76G  879G   8% /mnt/db_backup
tmpfs                           1.6G  4.0K  1.6G   1% /run/user/1001
```

Because there is only %12 free space in postgresql data directory 

Thanks

**Comment by pgstef** [comment]
Hi,

First of all, you should look at the PG logs to understand if the archiving system is working and is just too slow or is blocked.

PG will keep all the Wal segments that are not archived yet.

You could wipe those out but setting the archive_command to '/bin/true' which would let PG recycle the Wal segments, but would cause missing archives in your backup repository.

If the archive command is too slow you might speed it up by with async archiving using multiple processes.

Maybe the compression level is too high, certainly with gz. You could try with zstd compression with default level. That might speed it up too.

Kind regards

**Comment by msuluhan** [comment]
Hello pgstef

Thank you so much, async option solved my problem

Best regards
