### ISSUE TITLE
[Feature] Multi-repo "dumb" SSH host support

### ISSUE THREAD

**Issue by kmoppel** [pgbackrest/pgbackrest#1949]
Currently multi-repo can't be made to work with the additional repo being a plain remote host with some folder. This behaviour is pretty unexpected and confusing though imho, as the 1st steps (stanza-create, check / WAL archiving) work OK, until `backup --repo=2` gives you `ERROR: [072]: backup command must be run on the repository host` although the `repo2-host` doesn't even have a `/etc/pgbackrest.conf` file. Multi-repo [documentation](https://pgbackrest.org/user-guide.html#multi-repo) also doesn't mention that exception.

I guess shouldn't be much work to make it behave exactly like in case of S3, i.e. a dumb file storage endpoint? Maybe just removal of some "if" in case pgbackrest.conf not present?

Also I'm aware that there are alternatives like turning the `repo2-host` into a NFS mount instead of plain SSH, or using [rsync](https://github.com/pgbackrest/pgbackrest/issues/1754#issuecomment-1129264252)...but it's obviosly more work / more tools.

And seems I'm not the only one who finds the current behaviour confusing, so I think would be a very nice addition.
`Do you know why you can't trigger backups from a PG host when you use a repo-host ? Since you can create stanza and push wals to them.` https://github.com/pgbackrest/pgbackrest/issues/1846#issuecomment-1224430071

**Comment by dwsteele** [comment]
> Multi-repo [documentation](https://pgbackrest.org/user-guide.html#multi-repo) also doesn't mention that exception.

This is a general limitation and not related to multi-repo.

> I guess shouldn't be much work to make it behave exactly like in case of S3

More work that you might think, since a number of extra file ops need to be run remotely. We just made all the link code run remotely so we may be pretty close, but I have not had time to look into it. But you would still need a fully configured repo host with the pgbackrest binary present. In this config the entire point is to run the backup from the repo host.

> And seems I'm not the only one who finds the current behaviour confusing, so I think would be a very nice addition.

We are working on an SFTP driver that should work as you are hoping, but we don't know when that will be complete.

**Comment by kmoppel** [comment]
Thanks for the update! SFTP indeed sounds very good, looking forward to that - lots of on-prem setups still around with bunch of regular machines with storage attached idling around, so why not to use those instead of going S3 (external + $). 

At the same time also might be a good investment to look at those possible extra file ops more closly still, most things should be implemented as repo hosts work fine. What I've proposed sounds like just a different "mental model". Having a "fully configured repo host" for the secondary repo doesn't also seem necessary actually? Altough of course not a problem to have a config file with some attribute saying this repo host is "dumb" / externally controlled.

**Comment by dwsteele** [comment]
> At the same time also might be a good investment to look at those possible extra file ops more closly still, most things should be implemented as repo hosts work fine.

It is hard to see how this would be better than just using the SFTP driver? We are still planning to support this at some point (with config and pgbackrest installed), but it is not currently on the roadmap.

**Comment by dwsteele** [comment]
@kmoppel The SFTP patch has been submitted as PR #1959. Feel free to give it a try.
