### ISSUE TITLE
Aggressively expire WAL Segments not working

### ISSUE THREAD

**Issue by ndejesus** [pgbackrest/pgbackrest#1950]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.43

2. PostgreSQL version:
14.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 20.04 (LTS)

4. Did you install pgBackRest from source or from a package?
From Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
backup-standby=y
repo1-type=s3
repo1-storage-verify-tls=n
repo1-s3-endpoint=**redacted**
repo1-s3-uri-style=path
repo1-s3-bucket=backup-patroniapps
repo1-s3-key=**redacted**
repo1-s3-key-secret=**redacted**
repo1-s3-region=minio
repo1-path=/pgbackrest
repo1-retention-archive=1
repo1-retention-archive-type=incr
repo1-retention-full=2
start-fast=y
log-level-console=info
log-level-file=debug
delta=y
process-max=2

[patroni-apps]
pg1-path=/data/patroni-apps/member/14/data
pg1-port=5432
pg1-user=postgres
pg1-socket-path=/data/patroni-apps/member/14/data
pg2-host=**redacted**
pg2-path=/data/patroni-apps/member/14/data
pg2-port=5432
pg2-user=postgres
pg2-socket-path=/data/patroni-apps/member/14/data

7. Describe the issue:
As per documentation, if retention-archive-type is set to incr, then:
Pgbackrest will keep archive logs for the number of full, differential, and incremental backups defined by repo-retention-archive
I set it to 1, so my undestanding is that it will keel archive logs for last backup (full/diff/incr inlcuded).
Nevertheless, when i check archive logs in repository, i see archive logs from the second (and older) full.

See output of pgbackrest info command:
stanza: patroni-apps
    status: ok
    cipher: none
    db (current)
        wal archive min/max (14): 0000000E000000C80000000E/0000000E0000014300000047

        full backup: 20221204-000007F
            timestamp start/stop: 2022-12-04 00:00:07 / 2022-12-04 00:13:45
            wal start/stop: 0000000E000000C80000000E / 0000000E000000C800000013
...
        full backup: 20221211-000005F
            timestamp start/stop: 2022-12-11 00:00:05 / 2022-12-11 00:06:08
            wal start/stop: 0000000E000000F900000065 / 0000000E000000F900000073
...
        incr backup: 20221211-000005F_20221214-113001I
            timestamp start/stop: 2022-12-14 11:30:01 / 2022-12-14 11:33:20
            wal start/stop: 0000000E000001400000003A / 0000000E0000014000000040

In minio, we have:
mc ls local/backup-patroniapps/pgbackrest/archive/patroni-apps/14-1
[2022-11-29 11:36:15 CET]   564B STANDARD 0000000E.history
[2022-12-14 15:05:29 CET]     0B 0000000E000000C8/
[2022-12-14 15:05:29 CET]     0B 0000000E000000CB/
...
[2022-12-14 15:05:29 CET]     0B 0000000E00000140/
[2022-12-14 15:05:29 CET]     0B 0000000E00000141/
[2022-12-14 15:05:29 CET]     0B 0000000E00000142/
[2022-12-14 15:05:29 CET]     0B 0000000E00000143/

So we have WAL from 0000000E000000C8, Wal that comes from oldest full backup.
Is this normal?

**Comment by pgstef** [comment]
Hi,

I just tried it (with a simple pgbench run on primary+standby on minio):

```
# --repo1-retention-full=2
# full backup: 20221214-145239F
00000002000000000000006A-2ead18f9c50a5cdf7e057dcbcd255812bc34eb16.gz
00000002000000000000006A.003F60C8.backup
00000002000000000000006B-049088f29e8dbf544211d4988c5d05c8d70ab4ee.gz
00000002000000000000006C-c814863cf86e7027f580e5f12ebdf452c0f00608.gz
00000002000000000000006D-fa40e3d974c50e45bca7f5a10657109802a84b0c.gz
00000002000000000000006E-3e9f3b69a098f1ed637f34a598823c202b10528a.gz
00000002000000000000006F-050d5d7bd8008ae0b45062e53bbb20d6354bbaf6.gz
000000020000000000000070-ba6208083c8edaa697843e7b86e98b94f489365d.gz
# --end full backup
000000020000000000000071-ae3458700742806d9e7c04ea94c936218dd6b91b.gz
000000020000000000000072-f03dc3553f2bba6d66ade01753f8b44416505fb2.gz

# full backup: 20221214-145323F
000000020000000000000073-627f7d0b11ac27c469d38ab8eb705e25a84dba54.gz
000000020000000000000073.00000390.backup
000000020000000000000074-b7d4d2b700e17d81d6085905bd277e30de8993c5.gz
000000020000000000000075-e9f8e7b9ac9b2379a83e16a204a3e909abb45526.gz
000000020000000000000076-266ca28aab97a9b5f2aaf1044daebe7af7c96242.gz
# --end full backup
000000020000000000000077-0790be2f2d14d6392180232fe8183c1da3bfe6ae.gz
000000020000000000000078-07398e95b03f8561f9b4eac44d881b35634ccac5.gz
000000020000000000000079-0a1743f48ace569aadbd86fe04d6b928af157026.gz
00000002000000000000007A-aedd724190894447a0729bc03afd906ac131d3dc.gz
00000002000000000000007B-0caf5de853946661445c1dab7ad83e531bc589ce.gz
00000002000000000000007C-cbe89e7d78d21259b00e372b59f58a98979c5ae5.gz
00000002000000000000007D-8fbd91a81fb33a7b9e7c848f73da65ee0dc4a304.gz
00000002000000000000007E-976d8aea71f1007f0498eb6a8d994c246115b291.gz
00000002000000000000007F-e6bfd65efae808cc945577c25f82d37b9a627ef1.gz
000000020000000000000080-3fabaaf3314114f563c734ff6f6d3b4062caa113.gz
000000020000000000000081-221a475f1b11db45a9bef4ea087a578281e05893.gz
000000020000000000000082-feb891abbf7c8eb3f9548118fd5ba94b1ee8bac4.gz
000000020000000000000083-f5a7ea9ea4c8f47815d807a5561e8666629190ca.gz

# incr backup: 20221214-145323F_20221214-145630I
000000020000000000000084-847a7a75b78d46f618f8b5cc899c50a7be6c25aa.gz
000000020000000000000084.00002C18.backup
000000020000000000000085-795a13d164fec58546dd0bec3a7695306bf5f76b.gz
000000020000000000000086-362dfe99cbcb5f2a4bb1fc965f12c43b9c01720f.gz
000000020000000000000087-c9df3eedf723a155c659a02b904da34410f91683.gz
000000020000000000000088-d09b454bf967f6c3ab90647428bff25079f549b0.gz
000000020000000000000089-d379e8981ab42e26e9bc0cad1950d77b78cbb546.gz
00000002000000000000008A-177a70846fe45c804d30ed477f819f1ac5397085.gz
# --end incr backup
00000002000000000000008B-916361a76b13cf24113ebdcd6b2e1e75ad8539b0.gz
00000002000000000000008C-f6da1db4a4455dc63d2acf9471abeb473512a3cc.gz
00000002000000000000008D-49a3c3b0e0ead615a02d3324ba658c8dbc48701a.gz
```

With `--repo1-retention-archive-type=incr --repo1-retention-archive=1`, we should only keep archives past the last backup (>20221214-145323F_20221214-145630I) + all the archives needed for the backup consistency.
So I'd expect to see 000000020000000000000071 -> 000000020000000000000072 and 000000020000000000000077 -> 000000020000000000000083 removed.

Let's try with the expire command:
```bash
$ pgbackrest expire --stanza=u20pg --dry-run --repo1-retention-full=2 --repo1-retention-archive-type=incr --repo1-retention-archive=1
INFO: [DRY-RUN] expire command begin 2.43: ...
INFO: [DRY-RUN] repo1: 15-1 remove archive, start = 000000020000000000000071, stop = 000000020000000000000072
INFO: [DRY-RUN] repo1: 15-1 remove archive, start = 000000020000000000000077, stop = 000000020000000000000083
INFO: [DRY-RUN] expire command end: completed successfully (42ms)
```

So to me it seems to work with pgBackRest 2.43. You probably might want to list the content of those directories and check your expire command logs to find out what's going on.

Kind Regards

**Comment by ndejesus** [comment]
Ok i see, remaining WAL are those attached to full/incr backup, but there is no wal between two backups, except since last one.
