### ISSUE TITLE
Can't create a stanza

### ISSUE THREAD

**Issue by julienc256** [pgbackrest/pgbackrest#1951]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
**2.37**

2. PostgreSQL version:
**14.5**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
**Linux RedHat 8.2**

4. Did you install pgBackRest from source or from a package?
**RPM install pgbackrest-2.37-1.rhel7.x86_64.rpm**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

- pgbackrest.conf` file /etc/pgbackrest2.conf :
**[global]
repo1-path=/pgqdata/backup/pgserver1/pgbackrest
retention-full=2
start-fast=y
log-path=/opt/pgsql/log/pgserver1/pgbackrest
process-max=1
[global:restore]
process-max=1
[DEMO2]
pg1-path=/pgqdata/pgserver1/data**

- settings :
**archive_command = pgbackrest --stanza=DEMO2 archive-push %p
archive_mode = on
log_line_prefix = %t;%p;%u;%d;%e;
max_wal_senders = 10
wal_level = replica**

7. Describe the issue:
I try to recreate a stanza, but I encounter an error and I I can't solve the problem :

**pgbackrest --stanza=DEMO2 --config=/etc/pgbackrest2.conf --log-level-console=info stanza-create**
2022-12-15 16:02:11.783 P00   INFO: stanza-create command begin 2.37: --config=/etc/pgbackrest2.conf --exec-id=1677643-8d33b705 --log-level-console=info --log-path=/opt/pgsql/log/pgserver1/pgbackrest --pg1-path=/pgqdata/pgserver1/data --repo1-path=/pgqdata/backup/pgserver1/pgbackrest --stanza=DEMO2
**ERROR: [062]: stop file exists for stanza DEMO2**

My question is : how to remove stop files in order that I can create Stanza again ?

I tryed this command :
pgbackrest stanza-delete --stanza=DEMO2 --config=/etc/pgbackrest2.conf

But it shows nothing and returns 0 !!! It doesn't help users...

**Comment by jreidthompson** [comment]
see the documentation for start and stop
 https://pgbackrest.org/command.html#command-start

 https://pgbackrest.org/command.html#command-stop

If you ran the stanza-delete command, then you will have to run the stanza-create again, see
https://pgbackrest.org/command.html#command-stanza-delete

https://pgbackrest.org/command.html#command-stanza-create

**Comment by jreidthompson** [comment]
you have to run pgbackrest --stanza=DEMO2 --config=/etc/pgbackrest2.conf --log-level-console=info start 
to remove the stop file
