### ISSUE TITLE
Question: How to include postgresql configuration files in the backup

### ISSUE THREAD

**Issue by ManisankarKanagasabapathy** [pgbackrest/pgbackrest#1955]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: Latest 2.43

2. PostgreSQL version: 15.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I would like to know how i can include by postgresql.conf, pg_hba.conf and pg_ident.conf configuration files into my backup bundle so that at the time of restore I am not going to look for it in the source server. Ubuntu maintains the configuration files of postgresql separately into /etc/postgresql/15/main/postgresql.conf /etc/postgresql/15/main/pg_hba.conf and ident.conf currently if i take a backup of my postgresql instance these files are not being copied even if i include --pg1-host-config-path=/etc/postgresql/15/main/ in my backup command. What's the proper way ?

**Comment by pgstef** [comment]
Hi,

Usually using symbolic links inside the data directory is the easiest way to go.

Kind Regards

**Comment by ManisankarKanagasabapathy** [comment]
Totally agree that symlink or copy it to data directory is going to work as expected. Just wanted to check if this would be a good feature to add to have a flag like --pg1-copy-config and copy the file to the bundle directly ?

**Comment by pgstef** [comment]
> Just wanted to check if this would be a good feature to add to have a flag like --pg1-copy-config and copy the file to the bundle directly ?

I'm not sure it would worth it tbh. Usually, I tend to think that the configurations should be prepared using some sort of config management system. And if you do it manually, then the symlink method is pretty simple to use and less error-prone than a backup option imo.
