### ISSUE TITLE
How we can supply the password while running pgbackrest backup command when pg_hba entry for local are 'md5'

### ISSUE THREAD

**Issue by Tekchanddagar** [pgbackrest/pgbackrest#1964]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 14.x

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.04 LTS

4. Did you install pgBackRest from source or from a package? From source repository.

5. Describe the issue:

We want to implement the password for postgres user. But when we set `md5` for local in `pg_hba.conf` file and try to create the stanza we are getting below error:

```
ERROR: [056]: fe_sendauth: no password supplied
```
We have went through the pgbackrest doc and didn't found option to pass the password for postgres user in `stanza option`.
https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-bucket

Even we check some old question on forum and found that we can use `.pgpass` file to pass the password. 

https://github.com/pgbackrest/pgbackrest/issues/1063

But we are unable to understand how we can use `.pgpass` file with pgbackrest config.

Can you please help us how we can use the password with pgbackrest?

Thank You

**Comment by dwsteele** [comment]
You should consult the postgres documentation on how to use `.pgpass`: https://www.postgresql.org/docs/current/libpq-pgpass.html. Since pgbackrest uses libpq to communicate with postgres there is no pgbackrest configuration to be done for the password.

**Comment by Tekchanddagar** [comment]
@dwsteele , Thank You for your quick reponse.
> You should consult the postgres documentation on how to use `.pgpass`

We create it and tested successfully. We can create `.pgpass` file inside postgresql home directory i.e `/var/lib/postgresql` for Ubuntu OS. We can pass the below details in `.pgpass` file:

```
localhost:port:database:username:password
```
And then we can set `PGPASSFILE` environment variable :
```
export PGPASSFILE='/var/lib/postgresql/.pgpass'
```
But `PGBACKREST` bydefault use `postgres` user for backup so we created separate DB user for `pgbackrest` with below roles:
```
psql \
 -c 'grant pg_read_all_settings to pgback' \
 -c 'grant execute on function pg_start_backup to pgback' \
 -c 'grant execute on function pg_stop_backup(bool,bool) to pgback' \
 -c 'grant execute on function pg_create_restore_point to pgback' \
 -c 'grant execute on function pg_switch_wal to pgback'
```
And then we used this user in `pgbackrest.conf` file. We tested DB backup and restore with this user and its working fine.
So we are able to set password for `postgres` user.

I have added all points here so it may be helpful for someone.

Thank You
