### ISSUE TITLE
While restoring the test area backup to another test env we are getting error

### ISSUE THREAD

**Issue by Jith2** [pgbackrest/pgbackrest#1971]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.30

2. PostgreSQL version: 12.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Redhat 7.9

4. Did you install pgBackRest from source or from a package? Binary installation

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) 
[global]
repo1-path=/opt/sfw/pgbackrest/lib/pgbackrest
repo1-retention-full=3
log-level-file=detail
log-path=/opt/sfw/logs/pgbackrest/

[demo]
pg1-path=/opt/sfw/data/pgbackrest/pgdata/
#pg1-path=/opt/sfw/data/postgresql-d4-1-db/data/
pg1-socket-path=/opt/sfw/tmp
pg1-port=17200

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
wal_level = replica 
archive_command = 'pgbackrest --stanza=D4STG archive-push %p && pgbackrest --stanza=demo archive-push %p'

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
ERROR: [075]: backup set 20230104-062707F is not valid
2023-01-04 07:14:50.888 P00   INFO: restore command end: aborted with exception [075]
2023-01-04 07:14:50.888 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)
2023-01-04 07:14:50.888 P00  DEBUG:     common/lock::lockRelease: => false
2023-01-04 07:14:50.888 P00  DEBUG:     common/exit::exitSafe: => 75
2023-01-04 07:14:50.888 P00  DEBUG:     main::main: => 75

7. Describe the issue:

When we are trying to restore the backup from one test environment to another test environment we are not able to restore the data
We are trying to implement the pgbackrest in production before that we are trying to check a scenario that postgresql backup restore from one environment to another.

**Comment by Jith2** [comment]
Kindly help me to sort out this issue @pgstef

**Comment by Jith2** [comment]
Our scenario is restoring production DB dump to test environment. Is this scenario possible in pgbackrest. If yes please help me to configure that

**Comment by m-borger** [comment]
Sometimes it can help to see how these kind of scenario's could work, by creating a minimalistic example. I did that some time ago and will share it here for other users who try to grasp the concept of duplicating a database cluster using a backup.

### Attention
Please note that this is not an exact answer to the question, but only an example to show how something like this could be done. Some or even most of the steps could not be suitable for your situation or would need additional actions or configuration .

### Concept
This example is about a database cluster on server "prodserver" with a pgBackRest repository on an NFS server. It will be restored on seperate host "testserver" for use as a test environment.

### Setup prodserver
- Repository available over NFS:
```
[postgres@prodserver ~]$ df -hPT /backup
Filesystem                         Type  Size  Used Avail Use% Mounted on
192.168.9.9:/backup/prodserver  nfs4   20G  5.8G   15G  29% /backup
```
- Empty cluster directory:
```
[postgres@prodserver ~]$ ls -l /pgdata/prdtea
total 0
```
- Configuration for the stanza in `/etc/pgbackrest.conf`:
```
[prdtea]
pg1-path=/pgdata/prdtea
repo1-retention-full-type=count
repo1-retention-full=2
start-fast=y

[global]
repo1-path=/backup/postgres/pgbackrest
log-level-console=info
```
### Create the database cluster
* Create and start:
```
[postgres@prodserver ~]$ pg_ctl initdb -D /pgdata/prdtea/
[postgres@prodserver ~]$ pg_ctl start -D /pgdata/prdtea/
```
* Configure archiving:
```
[postgres@prodserver ~]$ psql -c "alter system set archive_command = 'pgbackrest --stanza=prdtea --log-level-console=info archive-push %p'"
[postgres@prodserver ~]$ psql -c "alter system set archive_mode = 'on'"
```

### Create and check the stanza
* Create:
```[postgres@prodserver ~]$ pgbackrest --stanza=prdtea stanza-create```
* Check:
```[postgres@prodserver ~]$ pgbackrest --stanza=prdtea check```
* You will see a WAL file successfully being archived by archive-push if everything is OK:
```2023-01-06 12:12:34.236 P00   INFO: WAL segment 000000010000000000000001 successfully archived to '/backup/postgres/pgbackrest/archive/prdtea/15-1/some_long_name```

### Make a backup:
* Maybe do some actions in the freshly created database cluster:
```psql -c 'create database mydb'```
* Make a full backup:
```[postgres@prodserver ~]$ pgbackrest --stanza=prdtea backup```
* Show this backup:
```[postgres@prodserver ~]$ pgbackrest --stanza=prdtea info```

### Setup testserver
- The repository for prdtea, above mounted as ```/backup``` is mounted here (read-only) as ```/restore```. The ```/backup``` on the testserver is mounted (read-write) on its own directory in the backup server:
```
[postgres@testserver ~]$ df -hPT /restore /backup
Filesystem                         Type  Size  Used Avail Use% Mounted on
192.168.9.9:/backup/prodserver  nfs4   20G  5.8G   15G  29% /restore
192.168.9.9:/backup/testserver  nfs4   20G  5.8G   15G  29% /backup
```
- Empty cluster directory:
```
[postgres@testserver ~]$ ls -l /pgdata/tsttea
total 0
```

### Basic approach: no backups or archiving on testserver
If you would just make the clone and use it, without being able to back it up and/or do point-in-time recovery, you could just restore the cluster with archiving disabled and start it.
Remind that the exact location for the prodserver repository on this server is ```/restore/postgres/pgbackrest```.
* You could check if the repository is where you would expect it like this:
```
[postgres@testserver ~]$ ls -l /restore/postgres/pgbackrest/backup/prdtea/latest
lrwxrwxrwx 1 1000 pgbackup 16 Jan  6 12:13 /restore/postgres/pgbackrest/backup/prdtea/latest -> 20230106-121343F
```
* Restore using the prdtea repo path to a desired data directory with archiving disabled. Note that you do not need specific configuration entries for this:
```pgbackrest --stanza=prdtea --repo1-path=/restore/postgres/pgbackrest --archive-mode=off --pg1-path=/pgdata/tsttea restore```
* Start the cluster
```pg_ctl -D /pgdata/tsttea start```
* The cluster starts and recovers when needed with the archives provided by the restore_command pgbackrest has set:
```
[postgres@testserver ~]$ psql -c 'show restore_command'
                                                  restore_command
--------------------------------------------------------------------------------------------------------------------
 pgbackrest --pg1-path=/pgdata/tsttea --repo1-path=/restore/postgres/pgbackrest --stanza=prdtea archive-get %f "%p"
(1 row)
```
* You might want to disable this once the cluster is consistent:
```[postgres@testserver ~]$ psql -c 'alter system reset restore_command'```
* And reload:
```[postgres@testserver ~]$ pg_ctl -D /pgdata/tsttea reload```

### Advanced approach: enable archiving on testserver and make backups
Remember, we mounted an entire different and empty ```/backup/postgres/pgbackrest``` on this testserver.
You could still use the same restore command:
* Restore using the prdtea repo path to a desired data directory with archiving disabled:
```[postgres@testserver ~]$ pgbackrest --stanza=prdtea --repo1-path=/restore/postgres/pgbackrest --archive-mode=off --pg1-path=/pgdata/tsttea restore```
* But make sure a ```/etc/pgbackrest.conf``` is available, something like:
```
[tsttea]
pg1-path=/pgdata/tsttea
repo1-retention-full-type=count
repo1-retention-full=2
start-fast=y

[global]
repo1-path=/backup/postgres/pgbackrest
```
* You could then configure the cluster to archive and make backups to its own repository by:
```
[postgres@testserver clone]$ psql -c "alter system set archive_command = 'pgbackrest --stanza=tsttea --log-level-console=info archive-push %p'"
[postgres@testserver ~]$ psql -c "alter system set archive_mode = 'on'"
[postgres@testserver ~]$ psql -c 'alter system reset restore_command'
[postgres@testserver ~]$ pg_ctl -D /pgdata/tsttea restart
[postgres@testserver ~]$ pgbackrest --stanza=tsttea stanza-create
[postgres@testserver ~]$ pgbackrest --stanza=tsttea check
[postgres@testserver ~]$ pgbackrest --stanza=tsttea backup
```

### Other actions not specific to pgBackRest
Of course there might be a lot of things you would want to do after the clone, depending on your situation. This could be things like:
```
psql -c "alter system set cluster_name='tsttea'"
psql -c 'alter database mydb rename to mytestdb'
pg_hba.conf
```
or recovery to a specific point in time, etc., etc.

**Comment by pgstef** [comment]
Hi,

> Could you please let me know why the backup file copy from prod to rest and restore is not working. I know the architecture is not supported but i would like to know the reason

Which backup file? And copied how? You need access to a repository, not only to the backup directory. It is usually easier to share the repository (with RO access) but I imagine that a complete sync of the repository directory could work.

Regarding your original question:
> When we are trying to restore the backup from one test environment to another test environment we are not able to restore the data

Since you don't provide much information like "how" you're trying to do it, we're not going to be able to go you more hints.
What is the restore command used? And what does the info command return?
The error you mention `backup set 20230104-062707F is not valid` means the restore command can't find that backup set inside your repository. And since your archive_command mentions 2 different stanza names, my guess is that you didn't used the good stanza but it's just a bet because you didn't provided any useful information.

Regards

**Comment by Jith2** [comment]
Hi 
We have tried out by installing pgbackrest install in prod and test and took backup in the local location of each server. Here we tried to restore by copying the pgbackrest over scp from prod to test and gave restore command at that time we got the error like 
'backup set 20230104-062707F is not valid'. 

Thanks & regards

**Comment by Jith2** [comment]
Hi,
Could you please help me more on that. How to set up pgbackrest . Once again we are trying to restore the pgbackrest from prod to test via scp and using restore command. 

-> pgbackrest --stanza=demo --log-level-console=detail --log-level-file=detail --delta --type=immediate --target-action=promote --set=20230104-062707F restore

The above command we have used to restore the backup.

To get this done do we need to do any other steps. does the scp from prod to test will work

Thanks & regards
