### ISSUE TITLE
Feature Request: a way for yearly/monthly/weekly/daily backups with their own retention policy/repo. 

### ISSUE THREAD

**Issue by isdinAghmir** [pgbackrest/pgbackrest#1972]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.43

3. PostgreSQL version:
9-10-12-13-14
4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
ubuntu 20.04 - 22.04
5. Did you install pgBackRest from source or from a package?
package via apt

Hello, 

I'm wondering if you can take in count my proposition:  a way for yearly/monthly/weekly/daily backups with their own retention policy. 

They will be full backups, they can even have their own repo. 

repo-daily: xxx-xxxx
repo-weekly: xxx-xxx
repo-yearly: xxx-xxx
repo-monthly: xxx-xxx

if no repo specified it can default to repo1. 

ex:
      - s3://REPO-URL/
         - repo-s3-backup-path/
           - stanzaname/
              - yearly/
                - archive/
                - backup/backup.info
              - monthly/
                - archive/
                - backup/
              - weekly/
                - archive/
                - backup/

I was able to perform something similar but the archive-push, would push the WALS to all the repos.

Creating multiple stanza for this is also not good since it's a pain to maintain such a configuration when you already have multiple stanza for one server. 

The best solution would be something simple supported and maintained by pgbackrest team. 

such as :  pgbackrest --stanza=main --type full --tag yearly  --xxx how_many_to_keep 

For exemple :
- I want to keep 10 yearly full backups
- I want to keep 12 monthly full backups
- I want to keep 2 weekly full backups 

Best Regards,
Thank you for your reading time.

**Comment by dwsteele** [comment]
We are not planning on building something like this into pgbackrest at this time.

You can do a lot of this by building your own retention scheme and expiring the backups you don't want to keep with `expire --set=XXX`. Stefan is working on a patch (#1926) to suppress archive-push to a repo when configured (except when a backup is running). Some combination of these should do what you want.
