### ISSUE TITLE
pgbackrest check seems to ignore PGHOST, PGPORT ....

### ISSUE THREAD

**Issue by LeGEC** [pgbackrest/pgbackrest#1975]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.43

3. PostgreSQL version: 15.0

4. Operating system/version: Ubuntu 22.10 (kinetic)

5. Did you install pgBackRest from source or from a package?
from source

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

```
$ cat pgbackrest_config/pgbackrest.conf
[dev_database]
pg1-path=/<PGDIR>/data
```

running :

```
export PGHOST=$PGDIR/socket
export PGPORT=55150
export PGUSER=replication
export PGPASSWORD=$(cat .secret/replication.txt)
export PGDATABASE=dev_database

pgbackrest --config-path=pgbackrest_config check --stanza=dev_database
```

triggers an error :

```
WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432 host='/<PGDIR>/socket'': connection to server on socket "/<PGDIR>/socket/.s.PGSQL.5432" failed: No such file or directory
      	Is the server running locally and accepting connections on that socket?
```

With the environment variables provided, I would expect pgbackrest to try to connect to socket `.s.PGSQL.55150`, and to database `dev_database` (the error message doesn't mention the user account used to connect, I suspect PGUSER and PGPASSWORD are also ignored).

The configuration of the postgresql server is located in `<DBDIR>/data/`, and spans over 2 files `postgresql.conf` and `custom.conf`,  
`postgresql.conf` contains the instruction :

```
include 'custom.conf'
```

`custom.conf` contains :

```
listen_addresses = '0.0.0.0'
port = 55150
unix_socket_directories = '/<DBDIR>/socket'
unix_socket_permissions = 0700
...
```

---

running `psql` with the same environment variables works as expected :

```
export PGHOST=$DBDIR/socket
export PGPORT=55150
export PGUSER=replication
export PGPASSWORD=$(cat .secret/replication.txt)
export PGDATABASE=dev_database

psql
```

**Comment by jreidthompson** [comment]
Regarding pgbackrest environment variables, see Section 1 Introduction of https://pgbackrest.org/command.html.

for example,
pg-1-path could be
`export PGBACKREST_PG1_PATH=/var/lib/postgresql/12/main
`and
```
[dev_database]
pg1-path=/<PGDIR>/data
```
would be
```
[dev_database]
pg1-path=/var/lib/postgresql/12/main
```

Environment variables override config file variables.  I.E. 
export PG_BACKREST_PG1_PATH=/var/lib/postgresql/12/
does not merge with/expand with config file `pg1-path=/<PGBACKREST_PG1_PATH>/data`
to form` pg1-path=/var/lib/postgresql/12/data`.

If you aren't already using it, --log-level-console=info will result in output to the console a representation of what is being invoked.
ala
```
postgres@raker:~/12$ pgbackrest --stanza=sftp --log-level-console=info stanza-create
2023-01-11 12:51:04.097 P00   INFO: stanza-create command begin 2.44dev: --exec-id=1022365-28668695 --log-level-console=info --pg1-path=/var/lib/postgresql/12/main --repo1-path=/var/tmp/pgbackrest/reposftp --repo1-sftp-account=postgres --repo1-sftp-host=endpoint --repo1-sftp-hostkey-hash=sha1 --repo1-sftp-private-keyfile=/var/lib/postgresql/.ssh/id_rsa --repo1-sftp-public-keyfile=/var/lib/postgresql/.ssh/id_rsa.pub --repo1-type=sftp --stanza=sftp
2023-01-11 12:51:04.701 P00   INFO: stanza-create for stanza 'sftp' on repo1
2023-01-11 12:51:15.824 P00   INFO: stanza-create command end: completed successfully (11727ms)
```
The user guides provide a fairly comprehensive walk through of configuration and usage.  https://pgbackrest.org/user-guide-index.html

**Comment by dwsteele** [comment]
It only ignores PGDATABASE (due to it being set in a Perl version long ago). You can set the database with: https://pgbackrest.org/configuration.html#section-stanza/option-pg-database.

**Comment by dwsteele** [comment]
Your are correct, port is also tied to our option. Again, this is from Perl days. We are afraid to update it because of the breakage it might cause.

I'm surprised that PGHOST does not work, though. We are not forcing that option. See https://github.com/pgbackrest/pgbackrest/blob/main/src/postgres/client.c#L134.
