### ISSUE TITLE
Problem with stanza-create

### ISSUE THREAD

**Issue by LexxterPL** [pgbackrest/pgbackrest#1981]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.43

2. PostgreSQL version:
13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Linux RedHat 8.4

4. Did you install pgBackRest from source or from a package?
yes 
[root@server~]# rpm -qi pgbackrest
Name        : pgbackrest
Version     : 2.43
Release     : 1.rhel8
Architecture: x86_64
Install Date: Wed 18 Jan 2023 04:08:44 PM CET
Group       : Unspecified
Size        : 951098
License     : MIT
Signature   : DSA/SHA1, Mon 28 Nov 2022 04:39:09 PM CET, Key ID 1f16d2e1442df0f8
Source RPM  : pgbackrest-2.43-1.rhel8.src.rpm
Build Date  : Mon 28 Nov 2022 04:39:06 PM CET
Build Host  : koji-rhel8-x86-64-pgbuild
Relocations : (not relocatable)
Vendor      : PostgreSQL Global Development Group
URL         : http://www.pgbackrest.org/
Summary     : Reliable PostgreSQL Backup & Restore
Description :

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    [root@server~]# cat /etc/pgbackrest/pgbackrest.conf
[cluster]
pg1-path=/database/data

[global]
repo1-retention-full=1
repo1-type=s3
repo1-s3-region=us-east-1
repo1-s3-endpoint=s3.myhost.net
repo1-s3-bucket=postgres-bucket
repo1-s3-key=HKL5NX5DTRC0TAO7MQP8
repo1-s3-key-secret=rXFOCwns3Zd4GFZjitxTEkXLhVzm4Gx06wDUHXiK
repo1-s3-ca-file=/etc/pgbackrest/bundle.pem
repo1-s3-verify-tls=y
start-fast=y

# Force a checkpoint to start backup immediately.
start-fast=y
# Use delta restore.
delta=y

# Enable ZSTD compression.
compress-type=zst
compress-level=6

log-level-console=info
log-level-file=debug

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
2023-01-23 20:14:44.061 P00  ERROR: [029]: unable to find child 'IsTruncated':0 in node 'ListAllMyBucketsResult'
                                    --------------------------------------------------------------------
                                    If SUBMITTING AN ISSUE please provide the following information:

                                    version: 2.43
                                    command: stanza-create
                                    options: --exec-id=1945916-8486079d --log-level-console=detail --log-level-file=debug --pg1-path=/database/data --repo1-s3-bucket=postgres-bucket --repo1-s3-endpoint=s3.myhost.net --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --repo1-storage-ca-file=/etc/pgbackrest/bundle.pem --repo1-storage-verify-tls --repo1-type=s3 --stanza=cluster

                                    stack trace:
                                    common/type/xml.c:xmlNodeChildN:261:(test build required for parameters)
                                        ... function(s) omitted ...
                                    storage/s3/storage.c:storageS3ListInternal:(trace log level required for parameters)
                                    storage/s3/storage.c:storageS3List:(trace log level required for parameters)
                                    storage/iterator.c:storageItrPathAdd:(trace log level required for parameters)
                                    storage/iterator.c:storageItrNew:(driver: *void, path: {"/var/lib/pgbackrest/archive/cluster"}, level: 3, errorOnMissing: false, nullOnMissing: false, recurse: false, sortOrder: 0, expression: null)
                                    storage/storage.c:storageNewItr:(this: {type: s3, path: {"/var/lib/pgbackrest"}, write: false}, pathExp: {"<REPO:ARCHIVE>"}, param.level: 0, param.errorOnMissing: false, param.recurse: false, param.nullOnMissing: false, param.sortOrder: 0, param.expression: null, param.recurse: false)
                                    storage/storage.c:storageList:(this: {type: s3, path: {"/var/lib/pgbackrest"}, write: false}, pathExp: {"<REPO:ARCHIVE>"}, param.errorOnMissing: false, param.nullOnMissing: false, param.expression: null)
                                    command/stanza/create.c:cmdStanzaCreate:(void)
                                    main.c:main:(debug log level required for parameters)
                                    --------------------------------------------------------------------

ls -l /var/lib/pgbackrest
drwxrwx---. 2 postgres       postgres       4096 Nov 28 16:39 pgbackrest

**Comment by pgstef** [comment]
Hi,

I notice `repo1-s3-endpoint=s3.myhost.net` in your configuration, that leads to `unable to find child 'IsTruncated':0 in node 'ListAllMyBucketsResult'`. 

IsTruncated is a required field in the ListBucketResult response. That's how the API v2 works as far as i can remember.
As we tend to follow the S3 specs as closely as possible, you might want to check your S3 clone config and/or API compatibility.

Hope this helps,
Kind Regards

**Comment by dwsteele** [comment]
We are expecting a `ListBucketResult` result and this is a `ListAllMyBucketsResult` so there is a lot more wrong here than `IsTruncated` being missing.
