### ISSUE TITLE
Unable to find WAL segment in the archive but it's exist

### ISSUE THREAD

**Issue by msuluhan** [pgbackrest/pgbackrest#1982]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.43

2. PostgreSQL version: 11.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:   Ubuntu 18.04.4 LTS

4. Did you install pgBackRest from source or from a package?  from repository

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

```
**PGBACKREST.CONF**

postgres@frtscddb01:~$ more /etc/pgbackrest.conf
[global]
repo1-path=/backup/backupData
repo1-retention-diff=6
repo1-retention-full=1
log-level-console=detail
log-level-file=detail
start-fast=y
process-max=5
compress-level=9
archive-async=y
archive-timeout=86400

[postgres]
pg1-path=/data/postgresql/11/main

**POSTGRESQL PARAMS**

postgres=# select name, setting from pg_file_settings where name in ('archive_command','archive_mode','listen_addresses','max_wal_senders','wal_level','port','wal_keep_segments');
       name        |                   setting
-------------------+----------------------------------------------
 listen_addresses  | *
 port              | 5432
 wal_level         | replica
 archive_mode      | on
 archive_command   | pgbackrest --stanza=postgres archive-push %p
 listen_addresses  | *
 wal_level         | replica
 max_wal_senders   | 3
 wal_keep_segments | 3000
(9 rows)


**ERRORS IN POSTGRESQL LOG** 

2023-01-25 14:10:06.751 P00   INFO: archive-get command begin 2.43: [0000000100001FB400000008, pg_wal/RECOVERYXLOG] --exec-id=122502-469455d0 --log-level-console=detail --log-level-file=detail --pg1-path=/data/postgresql/11/main --process-max=5 --repo1-path=/backup/backupData --stanza=postgres
2023-01-25 14:10:06.753 P00   INFO: unable to find 0000000100001FB400000008 in the archive
2023-01-25 14:10:06.753 P00   INFO: archive-get command end: completed successfully (3ms)
2023-01-25 14:10:06.899 UTC [122503] LOG:  started streaming WAL from primary at 1FB4/8000000 on timeline 1

```
7. Describe the issue:

I am trying to configure master/replica configuration with pgbackrest
I have configured both server and took succesfull backup from master server. 
After recovering the initial backup on replica server, I tried to start postgresql service and I got above unable to find WAL segment error and postgresql was not starting

I also run pgbackrest command with info and check options, there was no error 

I think I am missing something but could not find out. 

Best regards

**Comment by pgstef** [comment]
Hi,

What's your problem exactly? How can `postgresql was not starting` be consistent with `started streaming WAL from primary at 1FB4/8000000 on timeline 1`?

I mean, the only log extract you're giving looks sane to me. Probably `0000000100001FB400000008` hasn't been archived by the primary yet, so the primary still has it in its pg_wal directory and the standby can then start the streaming replication.

But I don't see anything here suggesting that the standby server refused to start...

Regards

**Comment by msuluhan** [comment]
Hello

Thanks for your reply.

I do understand what do you mean but postgresql database could not start on replica server. It waits on starting up state
Master has created a fresh new wal file, replica applies this file in recovery mode immediatly and process is going like this loop. You could see that in following lines 

```
MASTER NODE 

postgres@frtscddb01:/data/postgresql/11/main/pg_wal$ ls -l | grep -E '0215B00000051|0215B000000BC|0215C00000050|0215C000000A9'
-rw------- 1 postgres postgres 16777216 Jan 27 18:37 000000010000215B00000051
-rw------- 1 postgres postgres 16777216 Jan 27 18:39 000000010000215B000000BC
-rw------- 1 postgres postgres 16777216 Jan 27 18:41 000000010000215C00000050
-rw------- 1 postgres postgres 16777216 Jan 27 18:43 000000010000215C000000A9
postgres@frtscddb01:/data/postgresql/11/main/pg_wal$ date
Fri Jan 27 18:47:03 UTC 2023

REPLICA NODE 
postgres@secondarydb:/data/postgresql/11/main$ for i in 1 2 3 4
> do
> ps -ef | grep "startup   recovering" | grep -v grep
> sleep 129
> done
postgres  50155  50154 27 14:01 ?        01:16:02 postgres: 11/main: startup   recovering 000000010000215B00000051
postgres  50155  50154 27 14:01 ?        01:16:36 postgres: 11/main: startup   recovering 000000010000215B000000BC
postgres  50155  50154 27 14:01 ?        01:17:51 postgres: 11/main: startup   recovering 000000010000215C00000050
postgres  50155  50154 27 14:01 ?        01:18:06 postgres: 11/main: startup   recovering 000000010000215C000000A9
postgres@secondarydb:/data/postgresql/11/main$ date
Fri Jan 27 18:47:04 UTC 2023
postgres@secondarydb:/data/postgresql/11/main$ cd pg_wal
postgres@secondarydb:/data/postgresql/11/main/pg_wal$ ls -l | grep -E '0215B00000051|0215B000000BC|0215C00000050|0215C000000A9'
-rw------- 1 postgres postgres 16777216 Jan 27 18:37 000000010000215B00000051
-rw------- 1 postgres postgres 16777216 Jan 27 18:39 000000010000215B000000BC
-rw------- 1 postgres postgres 16777216 Jan 27 18:41 000000010000215C00000050
-rw------- 1 postgres postgres 16777216 Jan 27 18:43 000000010000215C000000A9
postgres@secondarydb:/data/postgresql/11/main/pg_wal$
```

I have similar environments with postgresql 11 and 12 but there is no issue like that; I mean I could easyly access and run queries on replica server. So my issue replica db is not accessible

Compared pgbackrest.conf, postgresql.auto.conf, recovery.conf with properly running environments.All of them same except hostnames, replication users, pg1-paths, replication slot names :(

Do you have any idea ?

Thanks

**Comment by pgstef** [comment]
Those logs aren't consistent with the `LOG:  started streaming WAL from primary at 1FB4/8000000 on timeline 1` you sent previously.

> So my issue replica db is not accessible

Is should, if standby mode is enabled and the consistency point of the recovery reached.

> Do you have any idea ?
With the limited/partial info you're providing, I don't see what could be wrong, except if you turned off standby mode.

We'd need the standby config (pgbackrest + postgres) + the restore command you used and the complete PG log once the server starts to have a better view of your situation.

**Comment by msuluhan** [comment]
Hello 

I was thinking that I was replied your input

I rechecked every line in postgresql.conf and customer was thinking that barman based replication was working properly. 
The hot_standby parameter was  configured to off. 
So I changed to on and restarted postgresql. 

Thanks for your all time and effort
