### ISSUE TITLE
pgbackrest extensibility - hook

### ISSUE THREAD

**Issue by anayrat** [pgbackrest/pgbackrest#1986]
Hello,

This is more about discussion, idea ;)

Do you plan to add something like backup, restore and expiration hook? Or pgbackrest plugin.

The idea is to let the user creating custom script to handle backup or restore. My use case, is to use the power of pgbackrest with LVM snapshot for example.

But, other people might be interested to implement VM snapshot.

Regards,

**Comment by Manuelraa** [comment]
We would have potential use case to push backups and WAL files to enterprise backup solution for long term storage on expiration.
It would be useful to be able to e.g. execute a bash script before pgBackRest expires a backup/wal and only deleting the backup/wal if script exit code is 0 similar to `archive_command` of PostgreSQL

**Comment by pgstef** [comment]
Hi,

There's a backlog [entry](https://github.com/pgbackrest/pgbackrest/projects/2#card-8957002) for that but I don't think anyone has planned to work on it soon.

Kind Regards

**Comment by anayrat** [comment]
Yes, I've seen the issue https://github.com/pgbackrest/pgbackrest/issues/49

But it is closed and it is not exactly the same feature. This issue is about the ability to execute   scripts  before and after backups.

What I suggest is to be able to execute a command instead of pgbackrest backup. A bit like Postgres' hooks :)

**Comment by dwsteele** [comment]
It is not clear to me why this would be better than wrapping pgbackrest in a script, which is pretty common. Either way, I don't believe anyone is planning to work on this.

**Comment by anayrat** [comment]
I don't see how it is possible to wrap pgbackrest in a script? For example, if I want to use a storage snapshot instead of file copy?

**Comment by dwsteele** [comment]
Ah, I see. That's a completely different thing. We have discussed adding hooks to support storage snapshots but have no current plans to do so.

**Comment by anayrat** [comment]
Yes, it is exactly what I am thinking about. Have some kind of plugin to manage storage snapshot:

- lvm snapshot
- vmware snapshot
- EC2 snapshot

**Comment by sfrost** [comment]
While we're generally open to the idea of supporting that at some point, it's important to consider that snapshots have limitations (getting access to them if the environment where the snapshot exists is no longer functioning properly or isn't available or other such issues...) and risks (a snapshot typically is going to depend on the same storage as the main system meaning that corruption of the main system, one of the things you want backups for to address that risk, likely would also corrupt the snapshot; also important to consider is that accessing the snapshot likely causes load on the same storage that the main system is using...) associated with them that may not be appropriate for backups.
