### ISSUE TITLE
Archives specific retention policy

### ISSUE THREAD

**Issue by Tekchanddagar** [pgbackrest/pgbackrest#1987]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.40

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.04

4. Did you install pgBackRest from source or from a package? From Source

5. Describe the issue: We are using pgbackrest for full backup and diffrential backup and using S3 for storage. Our current config is:
```
repo1-retention-full-type=count
repo1-retention-archive-type=full
repo1-retention-full=5
repo1-retention-diff=3
```
And its working as expected. 

But now we want to increase the count of full backup (From 5 to 13) and want to set archive retention policy to save some space on S3 bucket e.g we want to delete the WAL after 5 full backup and till 5 full backup we want to keep WALs for PITR. We have read some documentation and get some idea. But we are bit confused and has some fear as well. Can you please help us which config we should use from below 2 configs?

First one:
```
repo1-retention-full-type=count
repo1-retention-archive-type=full
repo1-retention-full=13
repo1-retention-diff=3
repo1-retention-archive=5
```
Second:
```
repo1-retention-full-type=count
repo1-retention-archive-type=diff
repo1-retention-full=13
repo1-retention-diff=3
repo1-retention-archive=8
```
Also please suggest if any other change is required.

Thank You

**Comment by pgstef** [comment]
Hi,

Your first idea (`repo1-retention-archive-type=full` + `repo1-retention-archive=5`) will consider only the 5 last full backups for the wal archives retention. So this seems to meet your requirement.

The second idea (`repo1-retention-archive-type=diff` + `repo1-retention-archive=8`) will consider all full backups as differential, so the last 8 full+diff backups will be considered for the wal archives retention. It seems more tricky to go that way.

You should probably create a simple test server (with local backup storage) and use pgbench to generate some activity (wal archives) and try your settings there to make sure it does what you're expecting. But imho, your first idea is probably the good one.

Kind Regards

**Comment by Tekchanddagar** [comment]
@pgstef, Thank You for quick response and your valuable inputs.


> You should probably create a simple test server (with local backup storage) and use pgbench to generate some activity (wal archives) and try your settings there to make sure it does what you're expecting.

Yes, we will do this

Thank You
