### ISSUE TITLE
Question : how do I build the pgbackrest project ?

### ISSUE THREAD

**Issue by LeGEC** [pgbackrest/pgbackrest#1988]
I must have overlooked something, where can I find the instructions to compile pgbackrest ?

I am currently trying to guess from the configuration files I see :

* I see a meson.build file at the root of the project, running `meson src/build` yields `"meson is currently not supported for release builds"`
* I see a `src/build/configure.ac`, running `cd src/build && autoconf && ./configure` works, then running `make` fails with

```
gcc   -std=c99 -Wall -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-clobbered -O2 -D_POSIX_C_SOURCE=200809L -I. -I/usr/include/postgresql -I/usr/include/libxml2 -I. -I.. -c -o .build/config/common.o ../config/common.c -MMD -MP -MF .build/config/common.dep
In file included from ../config/common.c:7:
./common/regExp.h:13:28: error: unknown type name ‘RegExp’
   13 | const char *regExpMatchPtr(RegExp *this, const String *string);
      |                            ^~~~~~
./common/regExp.h:13:48: error: unknown type name ‘String’
   13 | const char *regExpMatchPtr(RegExp *this, const String *string);
      |                                                ^~~~~~
./common/regExp.h:16:1: error: unknown type name ‘String’
   16 | String *regExpMatchStr(RegExp *this, const String *string);
      | ^~~~~~
./common/regExp.h:16:24: error: unknown type name ‘RegExp’
   16 | String *regExpMatchStr(RegExp *this, const String *string);
      |                        ^~~~~~
./common/regExp.h:16:44: error: unknown type name ‘String’
   16 | String *regExpMatchStr(RegExp *this, const String *string);
      |                                            ^~~~~~
../config/common.c: In function ‘cfgParseSize’:
../config/common.c:68:9: warning: implicit declaration of function ‘regExpMatchOne’ [-Wimplicit-function-declaration]
   68 |     if (regExpMatchOne(STRDEF("^[0-9]+(kib|kb|k|mib|mb|m|gib|gb|g|tib|tb|t|pib|pb|p|b)*$"), valueLower))
      |         ^~~~~~~~~~~~~~
make: *** [Makefile:289: .build/config/common.o] Error 1
```

extra note: I have an Ubuntu 22.10 system, I installed the packages mentioned in `CONTRIBUTING.md` : `apt install rsync git devscripts ...`

**Comment by LeGEC** [comment]
@pgstef : thanks for the pointer, I had read it in the past ...

a suggestion would be to copy that section (pretty straightforward by the way, and works on my machine) in one of the `.md` files ?

**Comment by dwsteele** [comment]
Also we'd rather not encourage building from source. There are packages available for most distros.

**Comment by LeGEC** [comment]
Out of curiosity : are there reasons to avoid doing this ?

We have a context were we do not want to install from packages (no root access).

**Comment by dwsteele** [comment]
> are there reasons to avoid doing this ?

Yes. For instance you might link to old/buggy lib version that packagers would know not to use causing corruption in your repo. Most people use packaged versions so if there is any issue it is likely to be spotted and fixed.

**Comment by LeGEC** [comment]
@dwsteele : ok, thanks for the feedback

**Comment by dwsteele** [comment]
Addendum for posterity -- here are two good examples of why it is better to use packages rather than building your own: #1992, #1995.
