### ISSUE TITLE
--target-action=shutdown not valid with option --type=default

### ISSUE THREAD

**Issue by maherbeg** [pgbackrest/pgbackrest#1989]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.40

2. PostgreSQL version: 15.1

3. Operating system/version - centos 7

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

```bash
pgbackrest --stanza=<omitted> --type=default --target-action=shutdown --archive-mode=off restore

ERROR: [031]: option 'target-action' not valid without option 'type' in ('immediate', 'lsn', 'name', 'time', 'xid')
```

7. Describe the issue:
I'm attempting to restore a database to the end of the WAL archives and then shutdown the database afterwards so I can do additional validation separately. It appears that the [configuration option dependencies](https://github.com/pgbackrest/pgbackrest/blob/main/src/build/config/config.yaml#L390-L408) only allow a `type` of `immediate`, `lsn`, `name`, `time`, `xid` when using the `target-action` parameter. 

This looks like a decision that happened early on in the Perl days, so I haven't been able to git blame well enough past that point to figure out why this combination of options isn't allowed. It seems like being able to shutdown the database instead of promoting it should be safe when replaying to the end of the WAL stream.

**Comment by dwsteele** [comment]
Well, `--type=default` just omits `target_action*` from `postgresql.auto.conf`. Without that setting I don't think `recovery_target_action` is valid or will do anything.

Have you tried it by configuring PostgreSQL manually?

**Comment by maherbeg** [comment]
Ah I see. Looking at the [Postgres docs](https://www.postgresql.org/docs/11/recovery-target-settings.html)

>This setting has no effect if no recovery target is set. If [hot_standby](https://www.postgresql.org/docs/11/runtime-config-replication.html#GUC-HOT-STANDBY) is not enabled, a setting of pause will act the same as shutdown.

I'll give this a try real quick with hot_standby = off. It's a bit of a weird permutation of options! I'll report back if this works so others can make use of it.

**Comment by maherbeg** [comment]
Hmm, yeah the `hot_standby=off`doesn't seem to work either. It doesn't seem like there's a way to shutdown Postgres at the end of the recovery stream. In theory you could let it run with a far off time, have Postgres shutdown  because it couldn't reach the final recovery target and then just start up after that. This would unfortunately mask any other failure modes :(

I'll ponder any other solutions but I may not have any good options here.

**Comment by dwsteele** [comment]
> It doesn't seem like there's a way to shutdown Postgres at the end of the recovery stream.

I think the problem is how would "end of the recovery stream" be defined? In theory there is no end...
