### ISSUE TITLE
doc.pl doesn't produce any markdown documentation

### ISSUE THREAD

**Issue by disco-stu** [pgbackrest/pgbackrest#199]
> perl doc/doc.pl --no-exe --out markdown

doesn't produce any markdown output. The html as well as the pdf documentation seems to be build as expected. (I had to apply patch #198 to build the documentation at all.)

Full output:
> perl doc/doc.pl --no-exe --out markdown
> 2016-05-23 21:28:17.242 T00   INFO: render markdown output
> 2016-05-23 21:28:17.295 T00   INFO:     render out: index
> 2016-05-23 21:28:17.448 T00   INFO:         process section: introduction
> 2016-05-23 21:28:17.452 T00   INFO:         process section: features
> 2016-05-23 21:28:17.472 T00   INFO:         process section: getting-started
> 2016-05-23 21:28:17.476 T00   INFO:         process section: contributions
> 2016-05-23 21:28:17.478 T00   INFO:         process section: support
> 2016-05-23 21:28:17.480 T00   INFO:         process section: recognition
> 2016-05-23 21:28:17.485 T00   INFO:     render out: test
> 2016-05-23 21:28:17.627 T00   INFO:         process section: introduction
> 2016-05-23 21:28:17.630 T00   INFO:         process section: testing

> ls -a1F doc/output/markdown
> ./
> ../

**Comment by dwsteele** [comment]
Currently the only markdown docs created are some README.md files and CHANGELOG.md.  I've been phasing out the markdown documentation if favor of the better-formatted html docs on the website.

Honestly I didn't expect to distribute docs with pgBackRest.  The command-line help is extensive and contains the entire command and configuration reference.  Ditto for why there are currently no MAN docs.

**Comment by dwsteele** [comment]
OK, so it looks like you are generating html docs -- hopefully that's enough for at least a first pass at the documentation.  I'm closing this since I currently don't have plans for generate the full docs in Markdown.

**Comment by disco-stu** [comment]
Yeah, I think the html documentation should get the user going.
