### ISSUE TITLE
pgbackrest restore failed with 'unexpected EOF'

### ISSUE THREAD

**Issue by gowu567** [pgbackrest/pgbackrest#1990]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.36

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: debian 10

4. Did you install pgBackRest from source or from a package? from source

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
    `raised from local-1 protocol: remote-1 pprocess on 'backrest-repo'terminated unexpectedly`
sublog:
![img_v2_79ab2c04-fac0-442b-af79-d1ee2bdcebdg](https://user-images.githubusercontent.com/97280345/216572897-25303bc1-ce19-42bb-8f11-40aba3b13d4c.jpg)

**Comment by dwsteele** [comment]
Is this reproducible or did it happen one time? This is generally causes by network issues, firewalls, etc.
