### ISSUE TITLE
Restoring exaqct DB from cluster backup with --db-include=DB ! How ?

### ISSUE THREAD

**Issue by CpServiceSpb** [pgbackrest/pgbackrest#1991]
There is Postgresql 13.9.2 with pgbackrest 2,44 from pgsql repository as deb package on Ubuntu 18.04 x64 LTS no GUI.
There are 1 cluster (default) main and 4 DBs with its own names, for example DB1, DB2, DB3 and DB4.

Cluster archive is made successfully:
`sudo -u postgres pgbackrest --stanza=main --type=full backup`

Then I need to restore either DB2 and DB4 or DB3 only.

I did with delete of ../13/main folder content or without with 
`--delta` switch:
- with delete cluster folder:
`sudo -u postgres pgbackrest --stanza=main --db-include=DB3 --type=immediate restore`
- without delete cluster folder:
`sudo -u postgres pgbackrest --stanza=main --delta --db-include=DB3 --type=immediate --target-action=promote restore`

But in the both cases all 4 DB are restored !
Why ?
What do I am make wrong ?
Which parameters are necessary to add/delete to restore specified exact Dbs ?

**Comment by jreidthompson** [comment]
Per section 12.1.3 Include Database Option (--db-include) of  https://pgbackrest.org/command.html#command-restore. See the documentation re excluded db's being restored as sparse files that can be dropped via the drop database command. 

12.1.3 Include Database Option (--db-include)
Restore only specified databases.
This feature allows only selected databases to be restored. Databases not specifically included will be restored as sparse, zeroed files to save space but still allow PostgreSQL to perform recovery. After recovery, the databases that were not included will not be accessible but can be removed with the drop database command.
NOTE:
built-in databases (template0, template1, and postgres) are always restored unless specifically excluded.
The --db-include option can be passed multiple times to specify more than one database to include.

See Restore Selected Databases for additional information and caveats. https://pgbackrest.org/user-guide.html#restore/option-db-include
