### ISSUE TITLE
Authentication method 10 not supported and scram-sha-256 authentication requires libpq version 10 or above

### ISSUE THREAD

**Issue by daulat0** [pgbackrest/pgbackrest#1992]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: v.2.43

2. PostgreSQL version: 14.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  amzn1.x86_64 #1 SMP Sun Nov 27 06:09:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux**

5. Did you install pgBackRest from source or from a package? Source
by downloading from 
curl -LO https://github.com/pgbackrest/pgbackrest/archive/release/2.43.tar.gz

7. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

8. Describe the issue:

Getting error message " authentication method 10 not supported" while trying to create stanza on postgres14 after upgrading postgres from v.10.2 to Postgres v.14.6. 
I know the Postgres 14 uses scram-sha-256 authentication by default but I checked with md5 and scram-sha-256 authentication (in postgresql.conf) method also. 

I tried after installing library package and getting the different error message like " SCRAM authentication requires libpq version 10 or above ERROR: [056]: unable to find primary cluster - cannot proceed"

Postgres is also installed from source on custom location 
wget https://ftp.postgresql.org/pub/source/v14.6/postgresql-14.6.tar.gz

 ls  /opt/PostgreSQL-14/lib/

libecpg.a            libecpg_compat.so.3.14  libpgcommon.a        libpgport_shlib.a  libpgtypes.so.3.14  libpq.so.5.14
libecpg_compat.a     libecpg.so              libpgcommon_shlib.a  libpgtypes.a       libpq.a             pkgconfig
[Error-pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/10580946/Error-pgbackrest.txt)
[pgbackrest settings.txt](https://github.com/pgbackrest/pgbackrest/files/10580950/pgbackrest.settings.txt)

libecpg_compat.so    libecpg.so.6            libpgfeutils.a       libpgtypes.so      libpq.so            postgresql
libecpg_compat.so.3  libecpg.so.6.14         libpgport.a          libpgtypes.so.3    [`libpq.so.5`](url)

pgbackrest.conf entry:

 cat /etc/pgbackrest/pgbackrest.conf

[global]
repo1-path=/opt/backups
repo1-retention-full=2

[test14]
pg1-path=/opt/PostgreSQL-14/data
pg1-port=5432
pg1-user=postgres
pg1-socket-path=/tmp

**Comment by daulat0** [comment]
I have checked the same on Postgres v.14.5 and pgBackrest v2.39 also. 
But there is same issue.

**Comment by pgstef** [comment]
Hi,

I don't recognize on which OS you are, but given your logs, running pgbackrest commands under the root user is a bad idea usually. 

You may have PG 14 installed but not being the default version in your $PATH. So you might get that fixed and try again.

Kind Regards

**Comment by daulat0** [comment]
We are using amazon linux2 

see the output of 

uname -a

Linux ip-12-1o-20-39.us-east-2.compute.internal 4.14.301-224.520.amzn2.x86_64 #1 SMP Fri Dec 9 09:57:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by daulat0** [comment]
It is working after setting 
export LD_LIBRARY_PATH=/PostgreSQL-14/lib:$LD_LIBRARY_PATH
export PATH=/PostgresSQL-14/bin:$PATH
