### ISSUE TITLE
return value of manifestFileUnpack() is Stack variable !!!

### ISSUE THREAD

**Issue by Monkey-LaoHan** [pgbackrest/pgbackrest#2000]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.43

2. Describe the issue:

Function _manifestFileUnpack()_ 's return value named _result_  was allocated on the stack

The call stack is as follows

 1. manifestFileUnpack()
 2. manifestFileFind()
 3. manifestBuildIncr()

**Comment by Monkey-LaoHan** [comment]
sorry, it's my mistake

**Comment by dwsteele** [comment]
FWIW, this is completely intentional since it is much faster than allocating/freeing memory and we make sure that the struct does not get too large.
