### ISSUE TITLE
2 node HA, rewind + pgbackrest ?

### ISSUE THREAD

**Issue by dsupru** [pgbackrest/pgbackrest#2001]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 
**2.44**
2. PostgreSQL version: 
**12**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
**Ubuntu 20**

4. Did you install pgBackRest from source or from a package? 
**from apt**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
 ```
[telem]
pg1-path=/var/lib/postgresql/12/main
pg2-host=[IP of the second node here]
pg2-path=/var/lib/postgresql/12/main
pg2-user=postgres

[global]

repo1-path=/media/nas/pgbackrest
repo1-cipher-type=aes-256-cbc
repo1-cipher-pass=***KEY***
repo1-retention-full=2
repo1-retention-diff=3

archive-async=y
archive-get-queue-max=1GB
archive-push-queue-max=1GB
spool-path=/var/lib/postgresql/spool
checksum-page=y
log-level-file=info
log-level-console=info
delta=y
start-fast=y
backup-standby=n
process-max=3

[global:archive-push]
compress-level=1
```

  - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
  
 ```
include 'postgresql.base.conf'

archive_command = 'pgbackrest --stanza=telem archive-push %p'
archive_mode = 'on'
cluster_name = 'postgres20'
hot_standby = 'on'
listen_addresses = '0.0.0.0'
max_connections = '1000'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_worker_processes = '10'
port = '5432'
track_commit_timestamp = 'off'
wal_keep_segments = '150'
wal_level = 'replica'
wal_log_hints = 'on'
hba_file = '/etc/postgresql/12/main/pg_hba.conf'
ident_file = '/etc/postgresql/12/main/pg_ident.conf'


primary_conninfo = 'user=repl passfile=/tmp/pgpass host=172.**.**.** port=5432 sslmode=prefer application_name=patroni-dell gssencmode=prefer'
primary_slot_name = 'patroni_dell'
recovery_target = ''
recovery_target_lsn = ''
recovery_target_name = ''
recovery_target_time = ''
recovery_target_timeline = 'latest'
recovery_target_xid = ''
restore_command = 'pgbackrest --stanza=telem archive-get %f %p'
```
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

My apologies if this is the wrong place to ask a question, but is it safe to use pg_rewind with pgbackrest ?

I read @dwsteele comment in another issue that pgbackrest is meant to be used **instead** of rewind rather than with it.
On my 2 node Patroni HA cluster I couldn't come up with another way to rejoin an old master as a replica after a failover (timelines diverge and with just 2 nodes I don't know how to configure pgbackrest to sync them). I read the docs, googled around and just don't see a straightforward way to make it work.

I tried creating 2 configuration files (one like above, another one with multiple repo hosts): 
1 to use on archive-get, another for archive-push, one of each for 2 DB hosts. 
What I was going for was to make a current master push WALs both locally and on the replica host.
And when it's time to recover the replica would just look at the local path for the WALs.
I've ran into a few problems with that idea (errors about 2 pgbackrests pushing to the same repository) so ultimately abandoned it.

If there is a way to make it work, please let me know.

**Comment by dwsteele** [comment]
> is it safe to use pg_rewind with pgbackrest?

This question doesn't make sense to me -- pgbackrest and pg_rewind are completely different tools.

I prefer not to use pg_rewind because it assumes that the failed clusters were shut down cleanly, which in many cases is a bad assumption.

> errors about 2 pgbackrests pushing to the same repository

You can do this by setting `archive-mode-check=n` but this may cause corruption in repos that do no support atomic writes. So, generally safe for S3 but not for Posix. If you do this it is up to you to test and ensure it is working correctly.

I don't have any Patroni experience so can't help you there.

**Comment by dsupru** [comment]
Thank you David !

I run the cluster on Ubuntu VMs so will stay away from that idea. Likely I'll just try to get a third VM to run as a dedicated backup host - seems to be the best option. I suppose at that point both DBs will write to 1 repo so I won't need pg_rewind. If I recall correctly, it also worked without setting `archive-mode-check=n` (I tested it earlier). Pgbackrest configuration is also straightforward in that case.
Reading the docs, I see if I archive daily and retail 2 full backups I will have 2 days of archives kept, so if 1 of my DBs goes down for less than that it should be able to catch up without starting from scratch.

Thanks for this great software !

**Comment by pgstef** [comment]
Hi,

Tbh, it is pretty straightforward to use pgBackRest with Patroni and use it in place of pg_rewind to resync an old primary.
There are lots of blog posts showing how to setup the create_replica_methods config.

The central point is that your repository should be reachable from both nodes. It could be a cloud thing (S3, Azure,..) or a dedicated backup server indeed. Usually the repo-host way is the easiest way for the backup scheduling. As long as you don't enable archive_mode to always, you should only have 1 primary writing to the repo.

There's a nice talk about this subject I'd definitely recommend: https://youtu.be/UNM6if3uIUk

Hope this helps,
Kind Regards
