### ISSUE TITLE
Any way to limit the throughtput during the backup, like pg_basebackup --max-rate ?

### ISSUE THREAD

**Issue by Krysztophe** [pgbackrest/pgbackrest#2003]
1. pgBackRest version: latest

2. PostgreSQL version: latest

3. Operating system/version :   Linux

7. Describe the issue: 

A customer wants to do a full backup during the day but is worried about the impact on the users due to IO concerns (disk & network).

I didn't find a simple way to limit the throughput of `pgbackrest backup` the same way than `pgbasebackup --max-rate`.
Did I miss something? 

(If it's not possible, I may try something with cgroups)

**Comment by dwsteele** [comment]
There is currently no way to do this directly but limiting `process-max` generally works well enough since compression is the major bottleneck in backup.

**Comment by Krysztophe** [comment]
Well, the customer does not compress...

Thanks anyway, this is something to know.

I don't close the issue. as I think it should be a nice feature. Or there should be a hint in the documentation.

**Comment by dwsteele** [comment]
We have a card for this already: https://github.com/pgbackrest/pgbackrest/projects/2#card-8956984, so I'll go ahead and close it.

BTW, I know cgroups have been used for this purpose before. Maybe we should just document that? Sounds like a possible doc contribution...
