### ISSUE TITLE
Is pgbackrest compatible with Postgresql 15.2

### ISSUE THREAD

**Issue by lux7789** [pgbackrest/pgbackrest#2004]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.38
2. PostgreSQL version:
15.2
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Debian(Bulleye)
4. Did you install pgBackRest from source or from a package?
Source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
[pgbackrest_conf.zip](https://github.com/pgbackrest/pgbackrest/files/10792054/pgbackrest_conf.zip)
I installed Postgresql 15.2 and I tried this morning to upgrade the stanza with this command : 
 pgbackrest --stanza=backup --online stanza-upgrade
and I received this error message : 
WARN: unable to check pg1: [VersionNotSupportedError] unexpected control version = 1300 and catalog version = 202209061
      HINT: is this version of PostgreSQL supported?
ERROR: [056]: unable to find primary cluster - cannot proceed

What is wrong ?

Thanks.

Luc

**Comment by pgstef** [comment]
Hi,

Yes it is. PG 15 support was added in [2.39](https://github.com/pgbackrest/pgbackrest/releases/tag/release%2F2.39) in May last year. So you should update your pgBackRest version to the latest release available.

Kind Regards
