### ISSUE TITLE
"stanza-delete command requires option: pg1-path" - why?

### ISSUE THREAD

**Issue by loop-evgeny** [pgbackrest/pgbackrest#2005]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.43

2. PostgreSQL version: 14.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package? Package

7. Describe the issue:

Deleting a stanza requires pg1-path:

```
$ pgbackrest --stanza=behavior-pg14 stanza-delete
ERROR: [037]: stanza-delete command requires option: pg1-path
       HINT: does this stanza exist?
```

It's unclear why this needs to be specified. Isn't the stanza name enough to identify the stanza? The path is not even the same on the backup storage server as on the database server, so it's not needed to delete the files.

```
pgbackrest --stanza=behavior-pg14 stanza-delete --pg1-path=/pgdata/behavior-pg14
```

This works. The path there is the path on the database server, but the files on the backup storage server got deleted just fine anyway.

**Comment by dwsteele** [comment]
This is so we can check to see if the postgres cluster us running. `--force` skips this check but the option is still required.

I suppose we could make pg-path optional when `--force` is specified but it is not something I am planning to work on.

**Comment by loop-evgeny** [comment]
I'm running this on the dedicated repository host, though, where there is no Postgres service running. So the path I specified ("/pgdata/behavior-pg14") does not even exist on that machine, but the command still worked.
