### ISSUE TITLE
Pgbackrest info command : missing data in json output

### ISSUE THREAD

**Issue by Jhiliano** [pgbackrest/pgbackrest#2007]
When a backup is performed the `pgbackrest info` command show the current progress (for example `status: ok (backup/expire running - 65.24% complete)`

However, this information is missing inside the json output (using --output=json argument)

I can only see the 'ok' message:
On 'status' -> 'message' : 'ok'
On 'repo' -> 'status' -> 'message' : 'ok'

(Tested on pgbackrest v2.43)

**Comment by sumanmichael** [comment]
Hello @dwsteele / @jreidthompson

I really appreciate your contribution to [this](https://github.com/pgbackrest/pgbackrest/pull/1621) feature, this is very much needed. But It would be great if we could also bring this to JSON output.

I've made some small changes to the command/info/info.c to include a percentage completion field as a string in backupLockKv. I'd love to get your thoughts on whether you think this approach works. Check out this commit: https://github.com/sumanmichael/pgbackrest/commit/eb0462513bec5f910c004e15819e91eb61a8032e . Let me know your feedback!

**Comment by dwsteele** [comment]
We left this out on purpose because we were not sure how we wanted to represent this number in the JSON. I am OK with using our internal represention (% * 100). So 94% is represented with an integer as 9400.

@sumanmichael We are not planning to format this as a string in the JSON since we would prefer it be easily machine-readable.

**Comment by Jhiliano** [comment]
> We left this out on purpose because we were not sure how we wanted to represent this number in the JSON. I am OK with using our internal represention (% * 100). So 94% is represented with an integer as 9400.
> 
> @sumanmichael We are not planning to format this as a string in the JSON since we would prefer it be easily machine-readable.

You could use a JSON type number with 2 decimals : this could be a better match with the human readable output and easily processed by any programs.

**Comment by Christian-findonflow** [comment]
I know this doesn't seem to be a high priority but it would be a great feature add for us. Tracking progress through JSON is much simpler than having to find a line in some output

**Comment by dwsteele** [comment]
@Christian-findonflow We've been stalled on the double support issue (see above). Perhaps the way forward here is just to add `bytes completed` and `bytes total` to the JSON. Might be useful info and the user can do their own math.

**Comment by Christian-findonflow** [comment]
That would be totally fine for us. We do a bunch of other calcs anyway. Thanks for such a quick response

**Comment by dwsteele** [comment]
If we do bytes now we could always add percent later when we have an acceptable solution.

**Comment by Christian-findonflow** [comment]
Totally, from a visuals perspective having both is good and has very little overhead. Looking forward to getting this!

**Comment by pgstef** [comment]
FWIW, I opened a [PR](https://github.com/pgbackrest/pgbackrest/pull/2141) with the completed vs total bytes report in the json output.

**Comment by dwsteele** [comment]
Closing this issue now that there is PR #2141.
