### ISSUE TITLE
Option archive-header-check bug?

### ISSUE THREAD

**Issue by robert-sjoblom** [pgbackrest/pgbackrest#2013]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.43

2. PostgreSQL version: 10.23, 15.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Centos7 (pg10), Rocky8 (pg15)

5. Did you install pgBackRest from source or from a package?
Package

7. Please attach the following as applicable:
[pgbackrestconf.txt](https://github.com/pgbackrest/pgbackrest/files/10840860/pgbackrestconf.txt)

8. Describe the issue:

We have a use case where we are performing a logical replication upgrade on an existing pg10 cluster to pg15. We do this by initializing a new pg15 cluster (different systemid from pg10) and then replicating to it with logical replication. We would like to archive the transaction log from this new pg15 cluster to the same stanza as the existing pg10 cluster's stanza (since they contain the same data). pgbackrest currently complains about different systemid/version on archive push from pg15. If we do `stanza-upgrade`, then pg10 version will have the same error.

We would like to wait with `stanza-upgrade` until the new pg15 cluster is promoted to handle writes from clients. To keep PITR working during the failover window, we need to be able to archive both versions of the transaction log.

We found the `--archive-header-check` option when invoking pgbackrest. This option, according to the documentation, appears to allow this approach. However, it does not seem to work as expected. As far as we can tell there should be an additional if-check in [push.c](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/archive/push/push.c#L260), like the one we see in [file.c](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/archive/push/file.c#L130) to make this feature work as we expected it to. Is our assumption correct, or have we misinterpreted the documentation? Do you have any additional thoughts or recommendations when upgrading a cluster in this manner? We have been thinking about making our stanzas version-specific, for instance, but with that comes different overhead that needs to be handled.

**Comment by pgstef** [comment]
Hi,

To me, those are 2 different checks. The one in `push.c` is making sure that the archive-push command is pushing to the good repo (comparing the manifest with the pg_control information, while the one in `file.c` is extracting that information from the WAL headers. So that option seems only linked to the 2nd check to me, not the first one.

I don't really see how only storing WAL archives without any backup would help for PITR anyway. In this situation I would recommend to split the stanza to be able to take backups and have WAL archives from both PG clusters.

Kind Regards
