### ISSUE TITLE
Can't do a backup with pgbackrest

### ISSUE THREAD

**Issue by lux7789** [pgbackrest/pgbackrest#2015]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.44
2. PostgreSQL version:
15.2
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Linux Debian 10
4. Did you install pgBackRest from source or from a package?
source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

My issue is that I can't do a backup with my new Pgbackrest 2.44 et Postgresql I have an error,

root@mercure:~# sudo -u postgres /usr/bin/pgbackrest --stanza=backup --log-level-console=info backup
2023-03-01 14:52:37.459 P00   INFO: backup command begin 2.44: --exec-id=5203-01e58951 --log-level-console=info --pg1-path=/u02/pgdata/15/db_3/PG1 --pg1-socket-path=/tmp --repo1-path=/var/lib/pgbackrest --repo1-retention-full=7 --stanza=backup --start-fast
WARN: no prior backup exists, incr backup has been changed to full
2023-03-01 14:52:38.176 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2023-03-01 14:52:38.777 P00   INFO: backup start archive = 000000010000000800000051, lsn = 8/51000028
2023-03-01 14:52:38.777 P00   INFO: check archive for prior segment 000000010000000800000050
**ERROR: [082]: WAL segment 000000010000000800000050 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2023-03-01 14:53:38.800 P00   INFO: backup command end: aborted with exception [082]**

What can I do to solve this issue ?

[pgbackrest.zip](https://github.com/pgbackrest/pgbackrest/files/10860075/pgbackrest.zip)
[backup-backup.zip](https://github.com/pgbackrest/pgbackrest/files/10860100/backup-backup.zip)
[backup-stanza-upgrade.zip](https://github.com/pgbackrest/pgbackrest/files/10860130/backup-stanza-upgrade.zip)

**Comment by pgstef** [comment]
Hi,

Before taking a backup, you have to make sure your archiving system is working.

The log files you sent contains information from pgBackRest 2.44 and 2.38 with lots of miss-configurations (archive_mode not enabled, FileMissingError due to wrong repo-path probably,...).

So you should read the logs:
```
HINT: check the archive_command to ensure that all options are correct (especially --stanza).
HINT: check the PostgreSQL server log for errors.
HINT: run the 'start' command if the stanza was previously stopped.
```

What does your PG logs says about archiving? Are you sure your archive_command points to the correct version of pgBackRest (2.44 not 2.38)?

Before trying to take a backup, make sure the `check` command is working.

Kind Regards

**Comment by pgstef** [comment]
It really looks like a broken pgBackRest installation from sources and probably linked to issue #2014.
That's why we recommend to install using packages provided in the official PGDG repositories.

**Comment by lux7789** [comment]
Thanks for your comment regarding the packages, I'll use the official PGDG repositories next time instead of the binaries.

Even if I have this,
archive_command = '/usr/bin/pgbackrest --stanza=backup archive-push %p'         # command to use to archive a logfile segment
in the postgresql.conf file.

The log give me this,
2023-03-01 17:22:33.516 CET [14278] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-03-01 17:22:33.516 CET [14278] LOG:  listening on IPv6 address "::1", port 5432
2023-03-01 17:22:33.516 CET [14278] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-03-01 17:22:33.521 CET [14278] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-03-01 17:22:33.532 CET [14282] LOG:  database system was shut down at 2023-03-01 17:22:25 CET
2023-03-01 17:22:33.539 CET [14278] LOG:  database system is ready to accept connections
ERROR: [046]: unexpected control version = 1300 and catalog version = 202209061
       HINT: is this version of PostgreSQL supported?
2023-03-01 17:22:33.546 CET [14285] LOG:  archive command failed with exit code 46
2023-03-01 17:22:33.546 CET [14285] DETAIL:  The failed archive command was: pgbackrest --stanza=backup archive-push pg_wal/00000001000000080000004A
ERROR: [046]: unexpected control version = 1300 and catalog version = 202209061
       HINT: is this version of PostgreSQL supported?

**Comment by pgstef** [comment]
I'm pretty sure your /usr/bin/pgbackrest used in the archive_command still points to your old 2.38 release. 
You need to fix that and only use the 2.44 everywhere if you want your PG 15 cluster to work correctly

**Comment by lux7789** [comment]
I'm not convinced I'm using the wrong pgbackrest in /usr/bin!

postgres@mercure:/u02/pgdata/15/db_3/PG1/log$ /usr/bin/pgbackrest help
**pgBackRest 2.44 - General help**

Usage:
    pgbackrest [options] [command]

Commands:
    annotate        Add or modify backup annotation.
    archive-get     Get a WAL segment from the archive.
    archive-push    Push a WAL segment to the archive.
    backup          Backup a database cluster.
    check           Check the configuration.
    expire          Expire backups that exceed retention.
    help            Get help.
    info            Retrieve information about backups.
    repo-get        Get a file from a repository.
    repo-ls         List files in a repository.
    restore         Restore a database cluster.
    server          pgBackRest server.
    server-ping     Ping pgBackRest server.
    stanza-create   Create the required stanza data.
    stanza-delete   Delete a stanza.
    stanza-upgrade  Upgrade a stanza.
    start           Allow pgBackRest processes to run.
    stop            Stop pgBackRest processes from running.
    verify          Verify contents of the repository.
    version         Get version.

Use 'pgbackrest help [command]' for more information.

**Comment by pgstef** [comment]
Are you sure about your archive_command? Have you reloaded your PG configuration? Try `show archive_command;` in psql to make sure.

Because in the logs you provided, it doesn't use the good pgBackRest version 

```
DETAIL: The failed archive command was: pgbackrest --stanza=backup archive-push pg_wal/00000001000000080000004A
```

It doesn't mention /usr/bin.

**Comment by lux7789** [comment]
postgres@mercure:~$ psql postgres
psql (15.2)
Type "help" for help.

postgres=# show archive_command;
              archive_command
--------------------------------------------
 pgbackrest --stanza=backup archive-push %p
(1 row)

Could we change it ?

**Comment by pgstef** [comment]
> Could we change it ?

It depends on how/where you configure your PG settings but yes, you can change it and then your need to reload the PG service to apply the change.

You also can use the pg_settings view to know more about that option.
Example:
```sql
🐘 postgres@postgres=# SELECT * FROM pg_settings WHERE name = 'archive_command';
-[ RECORD 1 ]---+------------------------------------------------------------------
name            | archive_command
setting         | /bin/true
unit            | 
category        | Write-Ahead Log / Archiving
short_desc      | Sets the shell command that will be called to archive a WAL file.
extra_desc      | 
context         | sighup
vartype         | string
source          | configuration file
min_val         | 
max_val         | 
enumvals        | 
boot_val        | 
reset_val       | /bin/true
sourcefile      | /opt/postgresql/datas/14/postgresql.auto.conf
sourceline      | 4
pending_restart | f
```

Anyway, it does mean you have multiple versions of pgBackRest installed locally and the default $PATH of the system user used to start your PG server points to the old one. The better thing you can do imho is to remove all the old versions and install the new correctly everywhere it needs to.

I don't think we'll be able to help you more with this given it really depends on what you did to install pgBackRest.

Kind Regards

**Comment by dwsteele** [comment]
Agreed -- this is really a Postgres configuration issue at this point.
