### ISSUE TITLE
ERROR: [082]: WAL segment 0000002600003CAB000000A9 was not archived before the 1800000ms timeout

### ISSUE THREAD

**Issue by yang793023815** [pgbackrest/pgbackrest#2017]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.39

2. PostgreSQL version:pg 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:a database server, a repository host server,more standbys

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[postgres@postgres-4ebbca07-1-0 postgres-4ebbca07]$ cat postgresql.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
include '/pgconf/postgres.base.conf'

archive_command = '/home/postgres/bin/pre_archive_push.sh %p && pgbackrest archive-push --log-level-console=info %p'
archive_mode = 'True'
cluster_name = 'postgres-4ebbca07'
datestyle = 'iso, mdy'
hot_standby = 'on'
jit = 'False'
listen_addresses = '0.0.0.0'
log_destination = 'csvlog'
log_directory = '/pglog'
log_filename = 'postgresql-%a.log'
log_min_duration_statement = '-1'
log_timezone = 'PRC'
log_truncate_on_rotation = 'on'
logging_collector = 'True'
max_connections = '200'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_worker_processes = '8'
password_encryption = 'md5'
pgaudit.log = 'none'
port = '5432'
superuser_reserved_connections = '20'
synchronous_commit = 'True'
synchronous_standby_names = '"postgres-4ebbca07-0-0"'
timezone = 'PRC'
track_commit_timestamp = 'off'
unix_socket_directories = '/tmp'
wal_keep_size = '128MB'
wal_level = 'logical'
wal_log_hints = 'on'
hba_file = '/pgdata/data/postgres-4ebbca07/pg_hba.conf'
ident_file = '/pgdata/data/postgres-4ebbca07/pg_ident.conf'

# recovery.conf
primary_conninfo = 'user=primaryuser passfile=/tmp/.pgpass host=245.0.2.114 port=5432 sslmode=prefer application_name=postgres-4ebbca07-1-0 gssencmode=prefer channel_binding=prefer'
primary_slot_name = 'postgres_4ebbca07_1_0'
recovery_target = ''
recovery_target_lsn = ''
recovery_target_name = ''
recovery_target_time = ''
recovery_target_timeline = 'latest'
recovery_target_xid = ''
restore_command = '/home/postgres/bin/pre_failover_restore.sh && pgbackrest archive-get %f "%p"'

7. Describe the issue:
time="2023-03-01T02:30:27+08:00" level=info msg="pgbackrest command is: [pgbackrest info --output=json]" env="[    PGBACKREST_LOG_PATH=/tmp PGBACKREST_STANZA=db PGBACKREST_PG1_PATH=/pgdata/data/postgres-6859794b PGBACKREST_REPO1_PATH=/backrestrepo/postgres-6859794b-backups]"
time="2023-03-01T02:30:27+08:00" level=error msg="pgbackrest backup failed" error="exit status 82" output="2023-03-01 02:00:11.397 P00   INFO: backup command begin 2.39: --archive-timeout=1800 --exec-id=40680-86c3740c --no-expire-auto --log-level-console=info --log-path=/tmp --pg1-path=/pgdata/data/postgres-6859794b --pg1-socket-path=/tmp --repo1-path=/backrestrepo/postgres-6859794b-backups --stanza=db --start-fast --type=incr
WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space
      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
2023-03-01 02:00:13.190 P00   INFO: last backup label = 20230227-020014F, version = 2.39
2023-03-01 02:00:13.190 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2023-03-01 02:00:27.904 P00   INFO: backup start archive = 0000002600003CAB000000AA, lsn = 3CAB/AA07A2F0
2023-03-01 02:00:27.904 P00   INFO: check archive for prior segment 0000002600003CAB000000A9
ERROR: [082]: WAL segment 0000002600003CAB000000A9 was not archived before the 1800000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2023-03-01 02:30:27.935 P00   INFO: backup command end: aborted with exception [082]

**Comment by yang793023815** [comment]
pgbackrest Incremental backup error，but the command "select pg_switch_wal()" is success.
and "pgbackrest check --stanza=db --log-level-console=info" also failed,report  ERROR: [082]: WAL segment 0000002600003CAB000000A9 was not archived before the 1800000ms timeout

**Comment by yang793023815** [comment]
the repo-path “/backrestrepo/postgres-6859794b-backups” is on nas,Do I need additional configuration parameters？

**Comment by pgstef** [comment]
Hi,

Is `archive_command = '/home/postgres/bin/pre_archive_push.sh %p && pgbackrest archive-push --log-level-console=info %p'` using the same env settings? (given there's no stanza selected in this command)

```
HINT: check the archive_command to ensure that all options are correct (especially --stanza).
HINT: check the PostgreSQL server log for errors.
HINT: run the 'start' command if the stanza was previously stopped.
```

You need to debut the archiving system. Have you looked at the PG logs (that's where the archive-push logs are sent)?

> "select pg_switch_wal()" is success.

This just asks PG to create a new WAL segment and archive the previous one. Doesn't tell you anything about the archiving itself. You could check [pg_stat_archiver](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ARCHIVER-VIEW) to see if it succeeded or not.

Kind Regards,

**Comment by yang793023815** [comment]
postgres.log:
2023-03-02 15:11:32.701 P00   INFO: archive-push command begin 2.39: [pg_wal/0000002600003C980000009B] --exec-id=10493-cd6bacf7 --log-level-console=info --log-path=/tmp --pg1-path=/pgdata/data/postgres-6859794b --repo1-path=/backrestrepo/postgres-6859794b-backups --stanza=db
2023-03-02 15:11:33.191 P00   INFO: pushed WAL file **'0000002600003C980000009B'** to the archive
2023-03-02 15:11:33.191 P00   INFO: archive-push command end: completed successfully (492ms)

pgbackrest.log:
2023-03-02 02:00:23.917 P00   INFO: check archive for prior segment 0000002600003D1800000055
ERROR: [082]: WAL segment **0000002600003D1800000055** was not archived before the 1800000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2023-03-02 02:30:23.987 P00   INFO: backup command end: aborted with exception [082]


the pgbackrest want archive 0000002600003D1800000055,but the database archive to 0000002600003C980000009B,It seems to be much larger than the database？what should i do now

**Comment by pgstef** [comment]
That's 32699 WALs in-between those 2. That's huge !
Are all those WAL segments not archived yet still needed for the backups or was that test data not archived because the archiving system was blocked for some reason? (If that's the case, you might want to change your archive_command to '/bin/true' until all those archives have been cleaned up by PG before enabling pgBackRest archive-push again.)

The check and backup commands won't succeed unless your archiving system is "up to date". So you should find out how many WALs are generated per minutes on your cluster and find out a way to speed that up. Usually the `pg_stat_archiver` view is helpful to know what's going on.

Also, is your NAS storage fast enough (iops/network bandwidth/...) for such amount of WAL archives? If the storage is fast enough, you can try to speed up the archiving system by changing [compression type](https://pgbackrest.org/configuration.html#section-general/option-compress-type) from gz to zst.

If 30seconds isn't enough for 1 segment to reach the repo, you can raise [archive-timeout](https://pgbackrest.org/configuration.html#section-archive/option-archive-timeout) a little bit.

You can also enable [asynchronous archiving](https://pgbackrest.org/user-guide.html#async-archiving) by defining [archive-async](https://pgbackrest.org/configuration.html#section-archive/option-archive-async) and using multiple [process-max](https://pgbackrest.org/configuration.html#section-general/option-process-max).

Anyway the first step of any backup system is to setup the archiving system and ensure it can keep up. And that's not only related to pgBackRest but to PG itself :-)
