### ISSUE TITLE
Missing access to logfiles stopped pgBackRest from working properly

### ISSUE THREAD

**Issue by andreasscherbaum** [pgbackrest/pgbackrest#2021]
David Steele asked me to log this as an error.

We recently faced a small outage and produced some more WAL, because pgBackRest was not able to open the logfile directory upon startup, and then was consuming CPU but not archiving files. [More details also available here](https://engineering.adjust.com/post/11_tb_wal_in_postgresql/).

Please provide the following information when submitting an issue:

1. pgBackRest version: 2.38

2. PostgreSQL version: 12.11

3. Operating system/version: Gentoo Base System release 2.7

4. Did you install pgBackRest from source or from a package?

Source (Gentoo package, compiled)

5. Please attach the following as applicable:

/etc/pgbackrest/pgbackrest.conf:
```
[global]
repo-path=/mnt/ceph
retention-full=2
retention-diff=6
compress-type=zst
process-max=4
log-level-console=error
log-path=/var/log/pgbackrest
start-fast=y

[global:backup]
process-max=8

[global:archive-push]
process-max=16
archive-async=y

[db-large]
db-path=/var/lib/postgresql/data
archive-mode-check=n
```

```
archive_command = "/usr/bin/pgbackrest --stanza=db-large archive-push %p"
archive_mode = "always"
max_wal_senders = 100
wal_level = logical
```

errors in the postgresql log file before or during the time you experienced the issue:
```
2023-01-28 15:19:17.577 UTC,,,4820,,63d2ab67.12d4,1363028,,2023-01-26 16:33:43 UTC,,0,WARNING,01000,"archiving write-ahead log file ""0000000200093E7A00000062"" failed too many times, will try again later",,,,,,,,,""
2023-01-28 15:19:17.677 UTC,,,4820,,63d2ab67.12d4,1363029,,2023-01-26 16:33:43 UTC,,0,LOG,00000,"archive command failed with exit code 41","The failed archive command was: /usr/bin/pgbackrest --stanza=db-large archive-push pg_wal/0000000200093E7A00000062",,,,,,,,""
2023-01-28 15:19:17.848 UTC,,,4820,,63d2ab67.12d4,1363030,,2023-01-26 16:33:43 UTC,,0,LOG,00000,"archive command failed with exit code 41","The failed archive command was: /usr/bin/pgbackrest --stanza=db-large archive-push pg_wal/0000000200093E7A00000062",,,,,,,,""
2023-01-28 15:19:18.044 UTC,,,4820,,63d2ab67.12d4,1363031,,2023-01-26 16:33:43 UTC,,0,LOG,00000,"archive command failed with exit code 41","The failed archive command was: /usr/bin/pgbackrest --stanza=db-large archive-push pg_wal/0000000200093E7A00000062",,,,,,,,""
2023-01-28 15:19:18.044 UTC,,,4820,,63d2ab67.12d4,1363032,,2023-01-26 16:33:43 UTC,,0,WARNING,01000,"archiving write-ahead log file ""0000000200093E7A00000062"" failed too many times, will try again later",,,,,,,,,""
```

log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`):

This is the part which was not working, because the `x` bit for the log directory was missing:
```
postgres@db ~ $ ls -ld /var/log/pgbackrest/*
ls: cannot access '/var/log/pgbackrest/db-archive-get-async.log': Permission denied
ls: cannot access '/var/log/pgbackrest/db-archive-get-async.log-20220511.gz': Permission denied
ls: cannot access '/var/log/pgbackrest/db-archive-get-async.log-20220512': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-archive-push-async.log': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-archive-push-async.log-20220519.gz': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-archive-push-async.log-20220521.gz': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-archive-push-async.log-20220522.gz': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-archive-push-async.log-20220523.gz': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-archive-push-async.log-20220524': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-expire.log': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-expire.log-20220520': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-stanza-create.log': Permission denied
ls: cannot access '/var/log/pgbackrest/db-large-stanza-create.log-20220515': Permission denied
ls: cannot access '/var/log/pgbackrest/db-restore.log': Permission denied
ls: cannot access '/var/log/pgbackrest/db-restore.log-20220511': Permission denied
ls: cannot access '/var/log/pgbackrest/all-server.log': Permission denied
```

7. Describe the issue:

pgBackRest was not able to open files in the log directory, and then did not archive logfiles.

The missing `x` bit for the log directory was caused by a misconfiguration on our side.

**Comment by dwsteele** [comment]
I am not able to reproduce this on HEAD or 2.38. If I run the async process manually I get the expected warning about the log file:

**Comment by dwsteele** [comment]
I am not able to reproduce this on HEAD or 2.38. If I run the async process manually with bad permissions on /var/log/postgresql I get the expected warning about the log file:
```
P00   WARN: unable to open log file '/var/log/pgbackrest/demo-archive-push-async.log': Permission denied
            NOTE: process will continue without log file.
```
Running via archive_command results in the WAL segments being archived (but no logging) as expected.

In your case it looks like the async archive-push was working fine, i.e. I don't think it was uselessly spinning, but something was preventing the foreground process from reporting on progress. Not sure what that would be without an error message, which was not captured in the CSV log. Bad permissions on spool-path could cause this issue but I would not expect the async process to be able to run in this case either.

Any chance to run the archive command manually with the incorrect permissions to capture the error message? Running with `--log-level-console=debug --log-level-stderr=off` would be helpful. IIRC `log-level-stderr=off` is a good setting to use for CSV logging in any case.

**Comment by dwsteele** [comment]
Hmm, I remember now, CSV logging does not log any output from the archive_command, whether it comes out on stdout or stderr does not matter. Just tested this to be sure. So in your case the only way to get output would be to run manually, which I understand may not be possible on a production system.

**Comment by andreasscherbaum** [comment]
I see if we can set this up and test it.

**Comment by dwsteele** [comment]
That would be awesome. Something definitely seems amiss, but I can't make it happen in my env.
