### ISSUE TITLE
pgbackrest- not working

### ISSUE THREAD

**Issue by vimal113** [pgbackrest/pgbackrest#2022]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 1.10 
2. PostgreSQL version:
PostgreSQL 13.0
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux 7 
4. Did you install pgBackRest from source or from a package?
source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
log-level-console=info
log-level-file=debug

[nydemo]
pg1-path=/apps/dbdata/13/1

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
   
      name       |                    setting
-----------------+------------------------------------------------
 archive_command | pgbackrest --stanza=nydemo archive-push %p
 archive_mode    | on
 max_wal_senders | 10
 port            | 5432
 wal_level       | replica

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I am trying to configure pgbackrest to test diff backups. I configured the pgbackrest and postgresql conf files with appropriate parameters in it. When I try to run stanza-create or stanza-check, it does not give me any output and just goes to next prompt, neither logs are created

[postgres@nydemo etc]$ pgbackrest --stanza=nydemo stanza-create
[postgres@nydemo etc]$ pgbackrest --stanza=nydemo stanza-check
[postgres@nydemo etc]$

**Comment by pgstef** [comment]
Hi,

> 1. pgBackRest version:
>        pgBackRest 1.10

Did you really installed 1.10 ? PG 13 is only supported after 2.30. You should definitely install the latest pgBackRest release available first (2.44) and try again. (And if possible, it is way better to install it using the PGDG packages rather than compiling it from sources where you might forget some steps)

Kind Regards
