### ISSUE TITLE
Incompatibility with PostgresQL 15.x (that uses pg_control version number 1300)

### ISSUE THREAD

**Issue by rafaelp** [pgbackrest/pgbackrest#2024]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.33

2. PostgreSQL version:
15.2  (Debian 15.2-1.pgdg110+1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Debian

7. Did you install pgBackRest from source or from a package?
From a package, running `sudo apt install pgbackrest=2.33-1`

9. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

```
-------------------PROCESS START-------------------
2023-03-12 22:01:32.708 P00   INFO: stanza-create command begin 2.33: --exec-id=48350-408122ae --log-level-console=info --pg1-host=[ip hidden] --pg1-path=/var/lib/postgresql/15/main --repo1-path=/mnt/pg_crunchy_data_backups/g4p6d5ihdzhxnkwqjfrpympvdq --stanza=o2cqrwhyd5brjatvrke6te7ch4
2023-03-12 22:01:33.797 P00  ERROR: [058]: version '15' and path '/var/lib/postgresql/15/main' queried from cluster do not match version '13' and '/var/lib/postgresql/15/main' read from '/var/lib/postgresql/15/main/global/pg_control'
                                    HINT: the pg1-path and pg1-port settings likely reference different clusters.
2023-03-12 22:01:33.897 P00   INFO: stanza-create command end: aborted with exception [058]
```

10. Describe the issue:

It seems there is a problem with PgBackRest and Postgresql 15.x

I'm getting the following error:
`ERROR: [058]: version '15' and path '/var/lib/postgresql/15/main' queried from cluster do not match version '13' and '/var/lib/postgresql/15/main' read from '/var/lib/postgresql/15/main/global/pg_control'`

When I run  `$ sudo /usr/lib/postgresql/15/bin/pg_controldata /var/lib/postgresql/15/main` I get the following:
```
pg_control version number:            1300
...
```

I could confirm that even in PostgreSQL 15.x the pg_control version number is 1300:

https://github.com/postgres/postgres/blob/REL_15_STABLE/src/include/catalog/pg_control.h

**Comment by pgstef** [comment]
Hi,

> pgBackRest version:\n2.33\n\n

The release 2.33 which is very old only support PG up to 13. The pg_control version haven't changed since then but the PG 14 support was added in 2.34, and PG 15 in 2.39.

You should definitely update your pgBackRest to the latest release available (which is a good practice anyway).

Kind regards

**Comment by rafaelp** [comment]
Thanks for your answer @pgstef 

I was using this version because I received a message that the backups was done with this versionm but I could manage to update and make it work. Thanks!
