### ISSUE TITLE
Feature request: expose S3_STS_HOST_STR as a configurable environment variable

### ISSUE THREAD

**Issue by oadekoya** [pgbackrest/pgbackrest#2028]
While trying to configure pgbackrest to use AWS-integrated identity pprovider, we found out that the STS endpoint is hard-coded as **sts.amazonaws.com** [here](https://github.com/pgbackrest/pgbackrest/blob/7e5adc03594a3b7a975001e80902a51df3ddd577/src/storage/s3/storage.c#L388) and that prevents us from using a regional endpoint that resolves to private IP (in an airgapped cluster environment). We even tried to do a manual DNS re-write but the certificate validation failed since pgbackrest expects the CN name to match exactly with the sts endpoint hard-coded. 

So, is it possible to expose the S3 STS credential host such that its configurable for different use cases?

**Comment by dwsteele** [comment]
It is not clear to me from the documentation (https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) that another host can be substituted here.

Have you tried changing the constant and rebuilding to see if it works?

**Comment by oadekoya** [comment]
STS can be isolated to a specific region and that's our use case. We could modify the code and make the constant configurable but we didn't want to be managing the overhead of keeping up with the upstream considering the crunchydata operator we are using also requires building the containers.

**Comment by dwsteele** [comment]
I was only suggesting that you try it once to be sure it works before we look at making this configurable.
