### ISSUE TITLE
TimescaleDB archiving with retention policy

### ISSUE THREAD

**Issue by WillowOfTheBorder** [pgbackrest/pgbackrest#2030]
Hi Community,

I'm looking at archiving data with TimescaleDB.
Typically, I want to have timescaledb running on a box with little disk space and continuously archive it to an S3 bucket.
To do so, I'm using pgBackRest.
The issue is I have a data retention policy on the hypertable that is being backed up, thus my backups are limited to the same data as what is kept into database by the retention policy.
Is there a way to ignore what's been deleted by the data retention policy when performing a backup?

Thanks a lot!

**Comment by dwsteele** [comment]
> Is there a way to ignore what's been deleted by the data retention policy when performing a backup?

This sounds like a question for the TimescaleDB project. My guess would be no.
