### ISSUE TITLE
Multi repo, where one does not archive WAL files.

### ISSUE THREAD

**Issue by andr4229** [pgbackrest/pgbackrest#2031]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.44

2. PostgreSQL version:
psql (11.19 (Debian 11.19-0+deb10u1))

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Debian 10 on both the servers

4. Did you install pgBackRest from source or from a package?
From source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    /etc/pgbackrest.conf
    ```
    [global]
    repo1-type=s3
    repo1-s3-endpoint=eu-central-1.linodeobjects.com
    repo1-s3-bucket=bucket-name
    repo1-s3-key=key
    repo1-s3-key-secret=secret
    repo1-s3-region=eu-central-1

    repo1-path=/repo1
    repo1-retention-full=2
    start-fast=y
    log-level-console=info
    log-level-file=debug
    delta=y
    process-max=2
    backup-standby=y

    [demo]
    pg1-path=/data/patroni
    pg1-port=5432
    pg1-socket-path=/data/patroni
    pg1-host-user=postgres
    pg2-host=xx.xx.xx.xx
    pg2-path=/data/patroni
    pg2-port=5432
    pg2-socket-path=/data/patroni
    pg2-host-user=postgres
    ```

7. Describe the issue:

I have a hard time figuring out how to have multiple repositories, where only one of them receives the WAL files, while the other just keeps the base backup. This is to have one repository where there is PITR for the last 14 days, while the other repository might have Full backup every 3 months where I keep 4 backups, i don't want to make incremental backups or anything but full backup for the second repository.

**Comment by pgstef** [comment]
Hi,

As mentioned at least in #2009 already, there's currently no way to do that (except from commenting out the repo from the config outside backup time).

WAL archives are needed for the backup consistency so the repo must at least contain those.
There's a [WIP](https://github.com/pgbackrest/pgbackrest/pull/1926) about disabling wal archiving on a specific repository, but not ready yet.

Kind Regards

**Comment by andr4229** [comment]
Thanks for the quick response
