### ISSUE TITLE
pgBackRest not compatible with EDB Advanced Server 15

### ISSUE THREAD

**Issue by ruudschilders** [pgbackrest/pgbackrest#2032]
I had created a ticket with EDB for this issue, they told me it would be fixed in 2.45, but the issue remains:

PostgreSQL : EDB Advanced Server 15.2
pgBackRest 2.45
OS: RHEL 8.7

```
 pgbackrest --stanza=tdba15as stanza-create
WARN: unable to check pg1: [VersionNotSupportedError] unexpected control version = 1501 and catalog version = 202209061
      HINT: is this version of PostgreSQL supported?
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
```

It does work with community edition, just not with EPAS

**Comment by pgstef** [comment]
Hi,

First of all, the community project only officially support community PG.

If a fork is changing the control or catalog version, it has to be tested first. 

And to facilitate the fork support, 2.45 contains a new internal option named [pg-version-force](https://github.com/pgbackrest/pgbackrest/commit/740c2258e36613b1b4e76bab452d0e610a399e7f).

Just add `pg-version-force=15` to your stanza configuration section and it should work with EPAS 15 ;-)

Kind regards

**Comment by ruudschilders** [comment]
Clear.
That setting worked.
Thanks
