### ISSUE TITLE
use backblazeb2 s3 , why always repo2: error (no valid backups)

### ISSUE THREAD

**Issue by wacdev** [pgbackrest/pgbackrest#2033]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.45

2. PostgreSQL version:
15.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

docker postgres:15-alpine

5. Did you install pgBackRest from source or from a package?
source

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
[global:archive-get]
process-max=2

[global:archive-push]
process-max=4

[global]
archive-async=y
spool-path=/var/spool/pgbackrest
compress-type=zst
compress-level=9

log-level-console=info
log-level-file=info

repo1-path=/backup/pg
repo1-retention-full=3

repo2-s3-bucket=wac-backup
repo2-s3-endpoint=s3.eu-central-003.backblazeb2.com
repo2-s3-key=
repo2-s3-key-secret=
repo2-s3-region=1
repo2-s3-uri-style=path
repo2-type=s3
repo2-path=/
# keep last 9 backups
repo2-retention-full=9

[site]
pg1-path=/var/lib/postgresql/data
pg1-socket-path=/var/run/postgresql
pg1-port=9997
pg1-user=wac.tax
```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    
unix_socket_directories = '/var/run/postgresql'
port = 9997
archive_command = 'pgbackrest --stanza=site archive-push %p'
archive_mode = on
log_directory = '/log'
log_filename = '%Y-%m-%d_%H%M%S.log'
log_line_prefix = ''
log_rotation_age = 7d
logging_collector = on
max_wal_senders = 3
max_wal_size = 8GB
min_wal_size = 80MB
wal_level = replica

    - errors in the postgresql log file before or during the time you experienced the issue
pg log https://gist.github.com/wacdev/52975fee889c6c345867d67435e6823e

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
debug log : https://gist.github.com/wacdev/93da3f0b95da611b3e0406793a087565

7. Describe the issue:
repo2: error (no valid backups)
<img width="1693" alt="image" src="https://user-images.githubusercontent.com/127726508/227438124-3447959e-1388-40db-a6c3-1d155dbe81e7.png">
I can see init file in backblazeb2
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/127726508/227438920-3c1ea454-8ae0-4fcd-85db-53742f0cb5c7.png">

the file seems never update since init

**Comment by pgstef** [comment]
Hi,

First of all, both your repositories seems to be working since the WAL archives are pushed successfully to them.
However, a backup can only be pushed to 1 repo. So as your logs indicate, the `pgbackrest backup` command is defaulting to repo1. 

If you want to take a backup pushed to repo2, your need to use `pgbackrest backup --repo=2`. I'd suggest to use `--repo=1` when taking the other backups so you'll now to what repo it is pushed without relying on the "default" one.

So the info command is reporting that you only have backups in repo1, not in repo2.

Hope this answer your question.

**Comment by wacdev** [comment]
thanks , it works
