### ISSUE TITLE
Chown operation (same user and group) being executed when restoring

### ISSUE THREAD

**Issue by marceloneppel** [pgbackrest/pgbackrest#2036]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 14.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu Server 22.04 + AWS S3 as the repository

4. Did you install pgBackRest from source or from a package? from a package / also tried from source (to debug the source code)

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
      - [global]
lock-path=/var/snap/charmed-postgresql/common/locks
log-path=/var/snap/charmed-postgresql/common/logs
repo1-retention-full=9999999
repo1-type=s3
repo1-path=*
repo1-s3-region=*
repo1-s3-endpoint=https://s3.amazonaws.com
repo1-s3-bucket=*
repo1-s3-uri-style=host
repo1-s3-key=*
repo1-s3-key-secret=*
start-fast=y
[postgresql-aws]
pg1-path=/var/snap/charmed-postgresql/common/postgresql/pgdata
pg1-socket-path=/var/snap/charmed-postgresql/common/postgresql
pg1-user=backup
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue:
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
      - 2023-03-28 01:56:15.097 P00   INFO: repo1: restore backup set 20230325-195653F, recovery will start at 2023-03-25 19:56:53
2023-03-28 01:56:15.097 P00   INFO: remap data directory to '/var/snap/charmed-postgresql/common/postgresql/pgdata'
2023-03-28 01:56:33.747 P00   INFO: write updated /var/snap/charmed-postgresql/common/postgresql/pgdata/postgresql.auto.conf
ERROR: [088]: unable to set ownership for '/var/snap/charmed-postgresql/common/postgresql/pgdata/postgresql.auto.conf': [1] Operation not permitted
2023-03-28 01:56:33.749 P00   INFO: restore command end: aborted with exception [088]

7. Describe the issue:
When packaging the pgBackRest tool inside a [snap](https://ubuntu.com/core/services/guide/snaps-intro), it works fine for creating backups and listing them (in an S3 bucket). However, when I try to restore the backup I see some chown operations (two: one for `postgresql.auto.conf` and another for `recovery.signal`). As the snap package we are creating restrict the operations that can be run by the user inside of it (like chown), the first chown operation fails and the restore is aborted.

I found two issues that are similar, but not equal to this one: https://github.com/pgbackrest/pgbackrest/issues/1335 and https://github.com/pgbackrest/pgbackrest/issues/624. Also, a candidate for a fix, but that was made in another file: https://github.com/pgbackrest/pgbackrest/commit/e73416e9e39118a3eb7a10d4d3f434ef7cc1c4ba.

In my case, it happens on https://github.com/pgbackrest/pgbackrest/blob/release/2.37/src/storage/posix/write.c#L122 (I also tested in a newer version of pgBackRest). I debugged and saw the user and the group are the same (the ones from the `this->interface` and the ones from `userId()` and `groupId()`)

**Comment by marceloneppel** [comment]
Hi David! Thank you so much for the fix. It was so quick!

I tested it and it works fine inside the snap confinement.

About the restriction, it's something that I don't have all the details to talk about, but the purpose of the restrictions is to avoid the packaged app to have access to system resources, avoiding unexpected behaviour or damage to the system. It was not the case in this situation, but the confinement blocked the chown operation.

**Comment by dwsteele** [comment]
This was committed in #2038.
