### ISSUE TITLE
ERROR 140: process terminated due to an unhandled exception

### ISSUE THREAD

**Issue by tosigus** [pgbackrest/pgbackrest#204]
Same Backup-Job as #201, now we're getting: 

> 2016-05-29 01:08:13.065 T00   INFO: full backup size = 9954.9GB
2016-05-29 01:08:13.067 T00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2016-05-29 01:08:15.290 T00   INFO: archive stop: 0000000100000C94000000C6
2016-05-29 01:08:39.346 T00   INFO: backup stop
2016-05-29 01:08:39.353 T00  ERROR: [140]: process terminated due to an unhandled exception
Redundant argument in sprintf at /usr/share/perl5/pgBackRest/Common/String.pm line 175.
 at /usr/bin/pgbackrest line 14.
    main::__ANON__("Redundant argument in sprintf at /usr/share/perl5/pgBackRest/"...) called at /usr/share/perl5/pgBackRest/Common/String.pm line 175
    pgBackRest::Common::String::timestampFormat("%4d", 1464476919) called at /usr/share/perl5/pgBackRest/Backup.pm line 908
    pgBackRest::Backup::process(pgBackRest::Backup=HASH(0x2fa7d08)) called at /usr/bin/pgbackrest line 201
    eval {...} called at /usr/bin/pgbackrest line 32
 at /usr/bin/pgbackrest line 237.
 at /usr/bin/pgbackrest line 14.
    main::__ANON__("Redundant argument in sprintf at /usr/share/perl5/pgBackRest/"...) called at /usr/share/perl/5.22/Carp.pm line 167
    Carp::confess("Redundant argument in sprintf at /usr/share/perl5/pgBackRest/"...) called at /usr/bin/pgbackrest line 237

The System is on Ubuntu 16.04 LTS, PostgreSQL 9.5. Any hints?

**Comment by dwsteele** [comment]
This is due to Perl 5.22 changing how sprintf works which was likely done for security reasons.

The bug was fixed in #196 but has not been released yet.  I'm expecting to release 1.2 in a few days.

**Comment by dwsteele** [comment]
v1.02 has been released and should fix your issues: https://github.com/pgbackrest/pgbackrest/releases/tag/release/1.02.

Let me know if you see any further issues.

**Comment by tosigus** [comment]
v1.02 fixed the Issue. But /usr/lib/perl5/ should be /usr/share/perl5/ in the documentation, lib did not work for Ubuntu 16.04. Thanks for your outstanding program!

**Comment by dwsteele** [comment]
Yes, I'll be updating the docs soon to reflect that.  BTW, how long did that 10TB backup take?

**Comment by tosigus** [comment]
10 TB to 1 TB Backup-File in 88h (from Xeon E5-2643v3, KVM VM with 6 vCPUs / 32 GB Memory to external SAN). Thanks a lot for the program!
