### ISSUE TITLE
Support for rclone blackend

### ISSUE THREAD

**Issue by orencio** [pgbackrest/pgbackrest#2041]
Related to repository backends, pgbackrest supports: filesystem, S3, Azure, and GCS Compatible Object Store Support.

It should be useful if it supports rclone bakend (<https://rclone.org/>) too like other backup systems like restic (https://github.com/restic/restic). This support open repository backend alternatives (webdav for example).

I haven't seen nothing about it in doc or other issues.

Regards.

**Comment by dwsteele** [comment]
This is not something we are currently considering and it is not clear that their API is a good fit for what we do. As far as I can see we already support most of the storage types supported by rclone that look important (mostly through the S3 API).
