### ISSUE TITLE
Recovery from folder

### ISSUE THREAD

**Issue by birtalevente** [pgbackrest/pgbackrest#2042]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.45

2. PostgreSQL version:
14.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Rocky linux 8.7

4. Did you install pgBackRest from source or from a package?
from rpm

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I just trying to get through a disaster scenario:
Let's say, I have an intact folder with full backup  (backup/stanza/20230401-........) and the cipher-pass, nothing more.
Can I recover from it without the backup/backup.history, backup.info, backup.info.copy? How?

Thanks
Levi

**Comment by dwsteele** [comment]
No -- `backup.info` contains the key required to decrypt `backup.manifest`. `backup.manifest` contains the key used to decrypt the files. Without `backup.info` (or the copy) there is no way to decrypt the backup.

**Comment by birtalevente** [comment]
I just want to understand the encryption mechanism:

There is backup/stanza/backup.info with the key (which is constant in time) to decrypt every backup.manifest in backups (full, inc, diff).
And the keys in every backup.manifest are different, so every backup (full, inc, diff) have different encryption key?

At the archive level archive/stanza/archive.info contain the key for all the WAL log files and this key is unchanged in time?

Pretty obvious, but ask it anyway: the repo-cipher-pass decrypt the backup.info and archive.info?

Thanks
Levi

**Comment by dwsteele** [comment]
> There is backup/stanza/backup.info with the key (which is constant in time) to decrypt every backup.manifest in backups (full, inc, diff).

Yes.

> And the keys in every backup.manifest are different, so every backup (full, inc, diff) have different encryption key?

No. A new key is generated for each full backup and then used for the rest of the backups related to the full (diff, incr). 

> At the archive level archive/stanza/archive.info contain the key for all the WAL log files and this key is unchanged in time?

Yes.

> Pretty obvious, but ask it anyway: the repo-cipher-pass decrypt the backup.info and archive.info?

Yes.
