### ISSUE TITLE
Need start/stop and current running backups info

### ISSUE THREAD

**Issue by MrSairam** [pgbackrest/pgbackrest#2046]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 
v2.44

2. PostgreSQL version: 
11.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
linux 

4. Did you install pgBackRest from source or from a package?
Source

5. Describe the issue:
pgbackrest stop, pgbackrest start does stop/start pgbackrest respectively.
But is there any way to know if pgbackrest is already stopped or started?

Also pgbackrest info gives status as (backup/expire running) when backup/expire runs. Is there a command to know, only the list of all current running backups?

We want to monitor our deployed pgbackrest, having these things will help us.

Thank you.

**Comment by pgstef** [comment]
Hi,

> pgbackrest stop, pgbackrest start does stop/start pgbackrest respectively.
> But is there any way to know if pgbackrest is already stopped or started?
> 
> Also pgbackrest info gives status as (backup/expire running) when backup/expire runs. Is there a command to know, only the list of all current running backups?

Unfortunately, there isn't any simple answer here.

First of all, what are you using the stop/start commands for? The `stop` command is simply locally creating a [lock file](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/control/stop.c#L40) (and trying to stop the running processes if the `--force` option is used). That lock (or "stop file") is used to prevent new processes to run and then the `start` command basically tries to remove that lock.

Then, both [backup](https://github.com/pgbackrest/pgbackrest/blob/main/src/build/config/config.yaml#L61) and [expire](https://github.com/pgbackrest/pgbackrest/blob/main/src/build/config/config.yaml#L74) commands use the same `lock-type: backup`. So currently, from a locking perspective, you can't reliably determine which one is running AFAIK.

> We want to monitor our deployed pgbackrest,

In addition to the info command (with the json output), the easiest way to do that is to look for lock files but you have to know where those lock files would appear and what they are used for.
I guess the fastest way to know if a backup is actually running is monitoring the system processes.

Hope this helps,
Kind Regards

**Comment by MrSairam** [comment]
Hi, thanks for the reply

> First of all, what are you using the stop/start commands for?

During upgrades to pgbackrest(to newer version), we will stop pgbackrest and start after that. So we want to check if it is stop mode or not.

Can I configure the .stop file location? 
If not, can I get its default location to check if any .stop files are created?

> In addition to the info command (with the json output), the easiest way to do that is to look for lock files but you have to know where those lock files would appear and what they are used for.

It will be helpful if we know these lock files location and their use.

Thank you.

**Comment by pgstef** [comment]
The lock path can be changed with the [--lock-path](https://pgbackrest.org/configuration.html#section-general/option-lock-path) setting. It is usually `/tmp/pgbackrest` by default.

The stop file also uses that path, as you can see [here](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/control/common.c#L19). But its name will change if you specify the `--stanza` option or not (`all.stop` or `stanza_name.stop`).

**Comment by MrSairam** [comment]
> The lock path can be changed with the [--lock-path](https://pgbackrest.org/configuration.html#section-general/option-lock-path) setting. It is usually `/tmp/pgbackrest` by default.
> 
> The stop file also uses that path, as you can see [here](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/control/common.c#L19). But its name will change if you specify the `--stanza` option or not (`all.stop` or `stanza_name.stop`).

Thank you for the info.
