### ISSUE TITLE
is it possible to make it support macos M1 chip

### ISSUE THREAD

**Issue by jiangxiaoqiang** [pgbackrest/pgbackrest#2049]
is it posiible to make the pgbackrest support macos?

**Comment by dwsteele** [comment]
pgBackRest supports the M1 chip (Pretty sure since I develop on M1). We had disabled the MacOS CI tests because of some updates that needed to be made to homebrew, but those updates are now complete (750ab8e55).

**Comment by jiangxiaoqiang** [comment]
what should I do to make it running in macOS with M1 chip, compile the source code by myself? I did not found the dmg and also tried brew:



```
> brew install pgBackRest
fatal: not in a git directory
Warning: No remote 'origin' in /opt/homebrew/Library/Taps/homebrew/homebrew-services, skipping update!
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (datawire/blackbird).

You have 10 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Warning: No available formula with the name "pgbackrest". Did you mean packetq?
==> Searching for similarly named formulae and casks...
==> Formulae
packetq

To install packetq, run:
  brew install packetq

```

**Comment by dwsteele** [comment]
There are no packages that I know of for MacOS. You will need to build from source. Here are basic instructions for building the environment: https://github.com/pgbackrest/pgbackrest/blob/main/test/Vagrantfile#L142. You may need to adjust for your environment.

We don't provide instructions for building on MacOS because we do not consider it to be a production environment. Developers use MacOS but they generally know how to do builds.

**Comment by ARCICT** [comment]
Hello,

We use macOS for all our severs in a production environment and we would very much like to run pgbackrest on macOS.
Would it be possible to share the instructions for building it in macOS?

Thank you!

**Comment by ARCICT** [comment]
Hello,

Our production environment is macOS only and we heavily rely on Postgres for obvious reasons.
We also would like an industry grade PostgreSQL backup & restore solution, so we would like to be able to use pgbackrest on our macOS based systems.

We think that we correctly setup the environment as defined in [the link above](https://github.com/pgbackrest/pgbackrest/blob/main/test/Vagrantfile#L142).

Can anyone guide us on what to do next?

Many thanks in advance.

**Comment by dwsteele** [comment]
> Can anyone guide us on what to do next?
``
cd src
./configure
make
```
