### ISSUE TITLE
Add feature to make logical dumps

### ISSUE THREAD

**Issue by glushakov** [pgbackrest/pgbackrest#2050]
Hi!
I would like to offer the following functionality: to teach pgbackrest to do logical dumps of database objects by analogy with pg_dump (pg_dumpall). Perhaps even pgbackrest could just be a wrapper that calls the appropriate utilities.

The main reason why I would like this is - that the most frequent cases is to restore a small amount of data (1-2 tables) without stopping the current database.
With pgbackrest it is necessary to restore the entire backup in another place, like PGDATA2, launch a second instance, transfer tables, etc.

Now we use pgbackrest as the main backup tool in case of a large-scale failure, but we additionally make dumps just for such requests.

But it would be great if everything can be done through one pgbackrest interface (configure the dump type, retention period, etc.)
In addition, pgbackrest can work with s3 storage, and for dumps, I need to place utilities for working with s3 on servers.

**Comment by dwsteele** [comment]
This is a feature that has always been in the back of my mind, but I don't see it happening any time soon (unless you are volunteering to write it). In any case, we'd have to discuss in depth before committing to such a large set of new functionality.

Note that there is already a project that seems to do most of what you need: https://github.com/orgrim/pg_back. Maybe you should have a look at that first.

**Comment by glushakov** [comment]
Thanks a lot!
I'll research tool that you referred
