### ISSUE TITLE
macOS build

### ISSUE THREAD

**Issue by ARCICT** [pgbackrest/pgbackrest#2052]
Hello,

Our production environment is macOS only and we heavily rely on Postgres for obvious reasons.
We also would like an industry grade PostgreSQL backup & restore solution, so we would like to be able to use pgbackrest on our macOS based systems.

We think that we correctly setup the environment as defined in [this link](https://github.com/pgbackrest/pgbackrest/blob/main/test/Vagrantfile#L142).

Can anyone guide us on what to do next?

Many thanks in advance.

**Comment by dwsteele** [comment]
Duplicate of #2049.
