### ISSUE TITLE
How to take pgbackrest backup without failure when 1 node in the patroni 2 node cluster fails.

### ISSUE THREAD

**Issue by ashwinsirigi** [pgbackrest/pgbackrest#2054]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.37

2. PostgreSQL version: 13.9

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS Stream release 8 

4. Did you install pgBackRest from source or from a package? Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[pgbackrest@Pr-IoTDB4 ~]$ cat /etc/pgbackrest/pgbackrest.conf 
[cbdemo]
pg1-host=192.168.232.1
pg1-host-port=22
pg1-port=25432
pg1-path=/disk01/postgresql
pg2-host=192.168.232.2
pg2-host-port=22
pg2-port=25432
pg2-path=/disk01/postgresql

[global]
buffer-size=4MiB
compress-type=gz
backup-standby=y
process-max=4
repo1-path=/nfs/pgsql
repo1-retention-full-type=time
repo1-retention-full=365
repo1-retention-diff=7
repo1-retention-archive=14
repo1-retention-history=0
start-fast=y
log-level-console=info
log-level-file=info

[global:archive-push]
compress-level=6

    - `patroni.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
Below config is from one of the node   
 archive_mode: 'on'
        archive_command: '/usr/bin/pgbackrest --config=/etc/pgbackrest/pgbackrest.conf --stanza=cbdemo archive-push %p'
listen: 192.168.232.1:25432
max_wal_senders: '10'
wal_level: 'replica'
port: 25432

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
When 1 one of node in 2 node patroni cluster is getting failed. Our pgbackrest backups are getting failed with below errors. I am aware  that pgbackrest checks for standby node everytime before performing backup. I have limitation that i cannot have extra node to make 3 node cluster I have to handle this case with 2 nodes. I have tested with --no-backup-standby option which is working. But I am looking for an better alternative solution avoid backup failure?

**Comment by pgstef** [comment]
Hi,

> I am looking for an better alternative solution avoid backup failure

Unfortunately, I don't think there is one. You're asking to take a backup from a standby but don't have one available, so it fails.
What you could probably do is to query Patroni (using an API call or `patronictl list` using a json output format for example) and check if there's a healthy standby or not. Then provide the `--no-backup-standby` option if needed.

**Comment by hunleyd** [comment]
If `backup-standby` wasn't a boolean, it could support 'yes', 'no', and 'if possible' with the latter solving this use case (try using a standby but if none available just use the primary). That way users could opt into the behavior if desired or remain w/ the current functionality if not; `no-backup-standby` would continue to force 'primary only' like it does now.
