### ISSUE TITLE
Question: archive-push not logging to file?

### ISSUE THREAD

**Issue by MannerMan** [pgbackrest/pgbackrest#2055]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.43

2. PostgreSQL version: 10

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Rocky Linux 8

4. Did you install pgBackRest from source or from a package? RPM package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
[dev-pg-app011]
pg1-path=/var/lib/pgsql/10/data

[global]
process-max=2
repo1-path=/
repo1-retention-full-type=time
repo1-retention-full=7
repo1-cipher-type=aes-256-cbc
repo1-cipher-pass=<redacted>
repo1-s3-bucket=dev-pgbackrest
repo1-s3-endpoint=<redacted>
repo1-s3-key=dev-pgbackrest
repo1-s3-key-secret=<redacted>
repo1-s3-uri-style=path
repo1-s3-region=us-east-1
repo1-type=s3
repo1-bundle=y
repo1-bundle-size=1024MiB
repo1-bundle-limit=128MiB
start-fast=y
backup-standby=y
archive-async=n
archive-timeout=300
io-timeout=300
spool-path=/var/spool/pgbackrest
checksum-page=y
expire-auto=n
resume=n
protocol-timeout=3600
log-subprocess=y
compress-type=zst
compress-level=4
buffer-size=1MB
log-level-console=info
log-level-file=info

[global:archive-push]
process-max=2
compress-level=3
log-level-file=info
log-level-console=info

[global:archive-get]
process-max=4
log-level-file=info
log-level-console=info
```

* `postgresql.conf` settings applicable to pgBackRest (`archive_command` )
    
```
archive_command = '/usr/bin/pgbackrest --stanza=dev-pg-app011 archive-push %p'
```

7. Describe the issue:

This is more of a question, perhaps not a bug. We're trying to figure out how to send pgbackrest archive-push log to a separate log file, instead of just stdout (which currently make archive-push logs appear in the postgresql log).
We have configured `[global:archive-push]` section with
```
log-level-file=info
log-level-console=info
```

But logging still _only_ appears through stdout in postgres log, not under `/var/log/pgbackrest/` where one might expect to find something like `dev-pg-app011-archive-push.log`. We could not find any mention in the documentation regarding special handling of archive-push logs. Perhaps we have configured something incorrectly?

**Comment by jreidthompson** [comment]
set your archive_command to 
archive_command = '/usr/bin/pgbackrest --stanza=dev-pg-app011  --log-level-file=info archive-push %p'

setting --log-level-file=   to the level of detail that you want

**Comment by dwsteele** [comment]
`archive-push` and `archive-get` do not log to file (see https://github.com/pgbackrest/pgbackrest/blob/main/src/build/config/config.yaml#L58). I've been thinking about a way to force this, but don't want to suddenly enable logging for everyone. It is extremely verbose.

Generally my recommendation is to enable async archiving, which does log to a file.
