### ISSUE TITLE
Full backup fails with archive timeout error

### ISSUE THREAD

**Issue by hlakshmi** [pgbackrest/pgbackrest#2059]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.39

2. PostgreSQL version: 13.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package? - Source

7. Describe the issue:
We are seeing the following issue where the full backup is failing due to archive timeout error. Can you please help debug the issue?
```
2023-05-03 06:03:18.730 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2023-05-03 06:05:58.886 P00   INFO: backup start archive = 0000000C00006AF300000075, lsn = 6AF3/75168A60
2023-05-03 06:05:58.886 P00   INFO: check archive for prior segment 0000000C00006AF30000005D
2023-05-03 09:59:16.609 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2023-05-03 09:59:16.810 P00   INFO: backup stop archive = 0000000C00006B180000009D, lsn = 6B18/9D4E00F0
2023-05-03 09:59:16.817 P00   INFO: check archive for segment(s) 0000000C00006AF300000075:0000000C00006B180000009D
2023-05-03 10:03:08.744 P00  ERROR: [082]: WAL segment 0000000C00006B14000000EB was not archived before the 60000ms timeout
                                    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
                                    HINT: check the PostgreSQL server log for errors.
                                    HINT: run the 'start' command if the stanza was previously stopped.
2023-05-03 10:03:08.744 P00   INFO: backup command end: aborted with exception [082]
```

**Comment by pgstef** [comment]
Hi,

You've removed an important part of the issue template:

> 5. Please attach the following as applicable:
>     - `pgbackrest.conf` file(s)
>     - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
>     - errors in the postgresql log file before or during the time you experienced the issue
>     - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Having the configuration used might help here.

Given the `check archive for segment(s) 0000000C00006AF300000075:0000000C00006B180000009D` step, 9513 (approximately) have been generated during the backup - which is around 40 wals per minute. 

One of those wals haven't been archived fast enough. Have you, as stated in the error message (`HINT: check the PostgreSQL server log for errors`) checked the Postgres logs to catch the archive command errors?

**Comment by hlakshmi** [comment]
Thanks @pgstef for the input. We looked into the Postgres logs around the failure time and couldn't see any relevant errors. 
I will get the Postgres and pgbackrest config files and attach them here.

**Comment by pgstef** [comment]
> Just in case, this helps - this workload is a very write heavy workload and it could be the reason for lot of WAL generation. Is it possible to workaround the issue by bumping up the wal_keep_size in postgresql.conf?

Nope, `wal_keep_size` wouldn't help here. It is a setting aimed at streaming replicas, nothing to do with WAL archiving.

You should find the traces of the archive-push command (triggered by PG archive_command) inside PG logs. That will tell you if the wal files are archived correctly and how long does it take to archive 1 segment. If needed, you can add some debug log level to the archive-push command to find out more details.

40 wal segments per minute isn't that big (if the wal seg size hasn't been changed from default). So it just might be that the archiving command is too slow (network or storage latency, compression level,...).

Anyway, without configurations and log traces of the archive command, we probably won't be able to help.

Kind Regards
