### ISSUE TITLE
Problem working with multiple repositories

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#2065]
pgBackRest version: 2.43
PostgreSQL version: 9.6.24
Operating system/version - Debian 10
Installed pgBackRest from package

Instructions are useful for setting up from scratch for the first time, but it is unclear how to add another repo to a live pgbackrest environment.  For instance, I have to run create-stanza to initialize my new repo, but since create-stanza does not take a repo as command line argument, it's gonna try to run create-stanza for all repos identified in the config, even the old one, which I don't want it to do, right?  Also, since pgbackrest gives higher priority to repo1, I have to make the new repo, repo1 and rename the old one to repo2.  

The end result of all this is that I want to eventually remove the old repo on the old server and just use the new repo on the new server.  So the use case here is different from the example used in the instructions where it was thinking the new repo was to give DR kinda support or multiple failover options.

Would really be nice if create-stanza supported providing a specific repo on the command line.  Or even perhaps swapping out repo1 with repo2 as I am wanting to do here.

**Comment by hunleyd** [comment]
> For instance, I have to run create-stanza to initialize my new repo, but since create-stanza does not take a repo as command line argument, it's gonna try to run create-stanza for all repos identified in the config, even the old one, which I don't want it to do, right?

There's no harm to existing stanzas in my experience.

> Also, since pgbackrest gives higher priority to repo1,

?? 

pgbackrest sends WAL to every active stanza it knows about so they are all treated identically in that sense.

I'm fairly certain it 'defaults' to the lowest numbered repo that is defined and not paused. So if you only had repo2 and repo3 defined, and didn't specify a repo on your command, it would default to repo2. There's nothing 'special' about repo1.

**Comment by MichaelDBA** [comment]
The documentation says pgbackrest gives higher priority to the lower numbered repos:
`"If there is more than one repository configured and the --repo option is not specified for a command, the repositories will be acted upon in highest priority order (e.g. repo1 then repo2)."`

And in another place...
`"When multiple repositories are configured, WAL will be fetched from the repositories in priority order (e.g. repo1, repo2, etc.). In general it is better if faster/cheaper storage has higher priority. If a repository is specified with the --repo option then only that repository will be searched."`

**Feature request: add the repo option to other commands like create-stanza, check, etc.**

**Comment by dwsteele** [comment]
We will add a note to stanza-create that it is safe to run it on existing repositories.

I think you are making this more complicated than it needs to be. Just add your new repo as repo2 and when it has enough retention then remove repo1. Priority only matters in the case where one repo is going to be significantly cheaper/faster. You can also shuffle the numbers around if you like, but there is really no need to do so.

> Feature request: add the repo option to other commands like create-stanza, check, etc.

The check command currently requires the --repo option (though we are working to remove that requirement. We won't be adding --repo to create-stanza. We considered it and decided there was no need and I can't see that changing now.

**Comment by MichaelDBA** [comment]
Thanks, @dwsteele !  Note in documentation  appreciated.  Also, thanks for confirming that it's safe to run a stanza-create even on an existing stanza without causing any problems.

**Comment by dwsteele** [comment]
Keeping this open as a reminder to update the docs.

**Comment by dwsteele** [comment]
> Keeping this open as a reminder to update the docs.
