### ISSUE TITLE
WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432 user='sa'': connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by damienApp** [pgbackrest/pgbackrest#2068]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
 ==> pgBackRest 2.45

2. PostgreSQL version:
==> postgres (PostgreSQL) 15.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
==>  Red Hat Enterprise Linux release 8.7 (Ootpa)

5. Did you install pgBackRest from source or from a package?
 From ==> https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[pgbacrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/11485181/pgbacrest.conf.txt)
pgbackrest --config=/etc/pgbackrest.conf --log-level-console=info --stanza=prod_backup stanza-create
2023-05-16 09:07:02.489 P00   INFO: stanza-create command begin 2.45: --config=/etc/pgbackrest.conf --exec-id=63528-b9174227 --log-level-console=info --log-level-file=debug --pg1-path=/DATABASE/PGDATA/PGOTVMI625S1/DATA/ --pg1-user=sa --repo1-path=/DATABASE/PGSAVE/PGOTVMI625S1/pgbackrest --stanza=prod_backup
WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432 user='sa'': connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: fe_sendauth: no password supplied
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
2023-05-16 09:07:02.493 P00   INFO: stanza-create command end: aborted with exception [056]

7. Describe the issue:
When I try to create my Stanza I am told that no password is presented, I decided to put my user in trust in the pg_hba.conf file and the same thing does not work either is that someone Any idea how to fix the problem ?

resume pg_hba.conf
"[.....]# Streaming
host    replication         sa         10.34.251.75/32     trust"
[postgres.conf.txt](https://github.com/pgbackrest/pgbackrest/files/11485234/postgres.conf.txt)

**Comment by pgstef** [comment]
Hi,

> host replication sa 10.34.251.75/32 trust

That's a replication connection and using the host ip.

You need to allow the unix socket connection and access to the normal db, not restricting to replication. Also, if you want to avoid `trust` in your pg_hba, you might simply use a pgpass file.

Kind Regards

**Comment by damienApp** [comment]
Thank you for your quick answer, yes I decided to use a PGPASSFILL which is declared as an environment variable here : -> env
FILE_PGPASS=/etc/postgres/pgpass-PGOTVMI625S1
 and which contains this: otvmi625s:5432:*:MyPassword
I know it can read it because the first time I ran it it asked me to change the permissions but still it can't connect.
The modification in trust for pg_hba was just to test if by putting nothing at all it would succeed or not

**Comment by pgstef** [comment]
The pg_hba entry should look like `local all all scram-sha-256` since you'll use the unix socket.
Then in the .pgpass file, the line should look like `localhost:5432:postgres:user:password`.

The underlying issue here is that you try to use the host based connection but pgBackRest is using the unix socket.

To be honest, I never tried to change the default pgpass location when using pgBackRest but imho, I think the environment variable should be PGPASSFILE not FILE_PGPASS.

**Comment by damienApp** [comment]
Ok so I do the modification for environnement variable : 
PGPASSFILE=/etc/postgres/pgpass-PGOTVMI625S1

And for pg_hba.conf : 
# TYPE  DATABASE    USER        CIDR-ADDRESS          METHOD
local   all         all                             scram-sha-256
host    all         all         127.0.0.1/32          password
host    all         all         10.34.251.75/32     password # otvmi625s
# Streaming
host    replication         "sa"         10.34.251.75/32     password # pg_basebackup


But : 
-> sudo systemctl restart PGOTVMI625S1.service
SAND postgres@otvmi625s:/DATABASE/PGDATA/PGOTVMI625S1/DATA [SID= PGOTVMI625S1 ]
->  pgbackrest --config=/etc/pgbackrest.conf --log-level-console=info --stanza=prod_backup stanza-create
2023-05-16 10:34:31.966 P00   INFO: stanza-create command begin 2.45: --config=/etc/pgbackrest.conf --exec-id=171743-e8ede4d2 --log-level-console=info --log-level-file=debug --pg1-path=/DATABASE/PGDATA/PGOTVMI625S1/DATA/ --pg1-user=sa --repo1-path=/DATABASE/PGSAVE/PGOTVMI625S1/pgbackrest --stanza=prod_backup
WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432 user='sa'': connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: fe_sendauth: no password supplied
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
2023-05-16 10:34:31.969 P00   INFO: stanza-create command end: aborted with exception [056]
SAND postgres@otvmi625s:/DATABASE/PGDATA/PGOTVMI625S1/DATA [SID= PGOTVMI625S1 ]
->

**Comment by damienApp** [comment]
In we have /etc/postgres/pgpass-PGOTVMI625S1 : [root@otvmi625s w100396]# cat /etc/postgres/pgpass-PGOTVMI625S1
localhost:5432:postgres:sa:LH5>Gx#f6-K-b63#2gikQC0
When I place it in the default location in pgpass.conf with the same ==> localhost:5432:postgres:sa:LH5>Gx#f6-K-b63#2gikQC0 it's the same error : 
-> pgbackrest --config=/etc/pgbackrest.conf --log-level-console=info --stanza=prod_backup stanza-create
2023-05-16 10:34:31.966 P00 INFO: stanza-create command begin 2.45: --config=/etc/pgbackrest.conf --exec-id=171743-e8ede4d2 --log-level-console=info --log-level-file=debug --pg1-path=/DATABASE/PGDATA/PGOTVMI625S1/DATA/ --pg1-user=sa --repo1-path=/DATABASE/PGSAVE/PGOTVMI625S1/pgbackrest --stanza=prod_backup
WARN: unable to check pg1: [DbConnectError] unable to connect to 'dbname='postgres' port=5432 user='sa'': connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: fe_sendauth: no password supplied
ERROR: [056]: unable to find primary cluster - cannot proceed
HINT: are all available clusters in recovery?
2023-05-16 10:34:31.969 P00 INFO: stanza-create command end: aborted with exception [056]
SAND postgres@otvmi625s:/DATABASE/PGDATA/PGOTVMI625S1/DATA [SID= PGOTVMI625S1 ]

**Comment by pgstef** [comment]
> When I place it in the default location in pgpass.conf 

What do you mean? Where did you placed it? It should be `~/.pgpass`

**Comment by pgstef** [comment]
As stated in [PG docs](https://www.postgresql.org/docs/current/libpq-pgpass.html), the file should be named `.pgpass` and placed in the home directory of the system user used to execute the pgbackrest command.

`psql -U sa -d postgres` should work (with the system user you're launching the pgbackrest commands) before trying it with pgBackRest.
