### ISSUE TITLE
Expire fails with unhandled exception

### ISSUE THREAD

**Issue by gamerscomplete** [pgbackrest/pgbackrest#207]
pgbackrest@pgbackrest-server:~$ pgbackrest expire --stanza=demo --retention-archive=2
2016-06-17 16:36:04.621 T00 ASSERT: option cmd-remote is required
2016-06-17 16:36:04.622 T00  ERROR: [140]: process terminated due to an unhandled exception
option cmd-remote is required at /usr/share/perl5/pgBackRest/Config/Config.pm line 2208.
	pgBackRest::Config::Config::optionGet("cmd-remote") called at /usr/share/perl5/pgBackRest/Config/Config.pm line 2341
	pgBackRest::Config::Config::protocolGet() called at /usr/share/perl5/pgBackRest/Expire.pm line 50
	pgBackRest::Expire::new("pgBackRest::Expire") called at /usr/bin/pgbackrest line 215
	eval {...} called at /usr/bin/pgbackrest line 32
 at /usr/bin/pgbackrest line 14.
	main::__ANON__("option cmd-remote is required at /usr/share/perl5/pgBackRest/"...) called at /usr/share/perl/5.20/Carp.pm line 167
	Carp::confess("option cmd-remote is required") called at /usr/share/perl5/pgBackRest/Config/Config.pm line 2208
	pgBackRest::Config::Config::optionGet("cmd-remote") called at /usr/share/perl5/pgBackRest/Config/Config.pm line 2341
	pgBackRest::Config::Config::protocolGet() called at /usr/share/perl5/pgBackRest/Expire.pm line 50
	pgBackRest::Expire::new("pgBackRest::Expire") called at /usr/bin/pgbackrest line 215
	eval {...} called at /usr/bin/pgbackrest line 32
 at /usr/bin/pgbackrest line 237.
 at /usr/bin/pgbackrest line 14.
	main::__ANON__("option cmd-remote is required at /usr/share/perl5/pgBackRest/"...) called at /usr/share/perl/5.20/Carp.pm line 167
	Carp::confess("option cmd-remote is required at /usr/share/perl5/pgBackRest/"...) called at /usr/bin/pgbackrest line 237

**Comment by dwsteele** [comment]
Hi Chris,

That is certainly a bug.  I can see why it's happening, though.  Your database is remote and expire run on its own is not initializing correctly.

There are two things you can do in the short term:

* Expire is automatically run after every backup so there's generally no reason to run it manually unless you need to force the expiration of backups.
* If you do need to force it then comment out `db-host` in `pgbackrest.conf` before running expire and then uncomment afterwards.

I'll fix this now but I don't think it merits a release, so it will go in 1.03 unless you have a pressing need.

Thanks,
-David

**Comment by gamerscomplete** [comment]
Thanks for the quick response and information on expire, I was indeed under the impression it was a maintenance operation that would need to be ran.

I agree this definitely does not merit a release in and of itself, I just ran into it when I was doing some testing and it was the first time pgbackrest had dumped a big nasty trace instead of a descriptive error message so wanted to bring it up.

Also wanted to say thanks for all the hard work on pgbackrest, I am just getting it implemented but so far it has been very simple to use, very flexible, and also very intuitive.

**Comment by dwsteele** [comment]
If the error type is ASSERT then a stack trace is always printed because in theory asserts should never happen.  So much for that theory.

I figured out why the regression tests weren't catching this issue and it turns out it will be a bit tricky to test.  The fix is pretty trivial, though.

And I appreciate the kind words!

**Comment by dwsteele** [comment]
Well, the fix was pretty trivial to start, but it exposed some untidiness in how options were being handled.  Cleaning that up exposed a few more potential bugs and made everything much easier to test so I'll call it a win.

The interesting thing is I already had an action item to address the core issue but it had been sitting around for a while because we weren't aware of any bugs resulting from it.

Thanks for the report!
