### ISSUE TITLE
Merge command

### ISSUE THREAD

**Issue by aporlov** [pgbackrest/pgbackrest#2071]
Good day! Can you consider adding a new merge command? 
For example, instead of making a full backup, a merge is done. 
All incremental backups are merged with the last full backup and a new full backup is created. 
Old full and incremental backups are deleted according to the retention policy.
Thank you.

**Comment by dwsteele** [comment]
We have a project card for this: https://github.com/pgbackrest/pgbackrest/projects/2#card-59620607. However, we don't know when it will be implemented.
