### ISSUE TITLE
Error with tablespace

### ISSUE THREAD

**Issue by aakashmuthuramalingam** [pgbackrest/pgbackrest#2073]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Database Server: Centos 6

4. Did you install pgBackRest from source or from a package?  Package(Yum)

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[dbbackup]
pg1-path=/var/lib/pgsql/14/data
pg1-port=5432
start-fast=y
[global]
repo1-path=/backup/dbbackups_01
repo1-retention-full=2
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command` - pgbackrest --stanza=dbbackup archive-push %p' , `archive_mode` - ON, `listen_addresses` - *, `max_wal_senders` - 8 , `wal_level` - Logical, `port` - 5432)
    - errors in the postgresql log file before or during the time you experienced the issue - no error
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`) - no error

7. Describe the issue:

Having postgres 14 running on data dir /var/lib/pgsql/14/data and having 10 tablespaces for my each database on /var/pgsql/*(inside each tablespace). Now configured pgbackrest, but it is showing the following error. Even though no tablespace inside data dir. Any help appreciated. Thanks in Advance.

<img width="986" alt="image" src="https://github.com/pgbackrest/pgbackrest/assets/45911698/05afacef-7bdd-40c5-a0f1-ab4b073a9a25">

**Comment by pgstef** [comment]
Hi,
Could you please avoid screenshots and copy/paste the actual error text within a code block?
Kind Regards

**Comment by dwsteele** [comment]
Please **do not** post screen captures of log output. Copy the log output into the issue as text so it can be copied and pasted.

Your links are definitely invalid. `pg_tblspc/517311 links to `/var/pg_table` and `pg_tblspc/16405` links to `/var/pg_table/ts_[redacted]`. So, the second tablespace is *inside* the first tablespace, which pgBackRest does not allow. It makes backup and restore much more complicated and remapping tablespaces hazardous at best.

So, you'll need to resolve this issue before pgBackRest will perform the backup.

**Comment by aakashmuthuramalingam** [comment]
ok, sure. 

```shell
2013-05-23 10:47:28.954 POO INFO: backup start archive 0000002900000002000000BA 
2023-05-23 10:47:20.954 POO INFO: check archive for prior segment 000000290000000000000B9
ERROR (070): link pg_tblspc/16405 (/var/pg_table/ts_test destinationis a subdirectory of link 'pg_tblspc/51731'(/var/pg_table) 
INFO: backup command end: aborted with exception (070)

```
