### ISSUE TITLE
Update on Planned Backup Improvements: Pre/Post Hooks and Detailed Failure Information

### ISSUE THREAD

**Issue by vmatyavin** [pgbackrest/pgbackrest#2074]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45

2. PostgreSQL version: 15

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.04

4. Did you install pgBackRest from source or from a package?  package

5. Describe the issue: 

Hi David,

I noticed in your previous response that there were planned improvements related to backups, including pre/post hooks and more detailed information about failed backups. I'm curious to know if those improvements have been implemented or if there have been any updates in that regard. Could you please provide an update on the status of these planned enhancements?

Thank you!

**Comment by dwsteele** [comment]
It would be helpful if you would link the original issues so I can refresh my memory on these topics.

**Comment by vmatyavin** [comment]
https://github.com/pgbackrest/pgbackrest/issues/747#issuecomment-505188297

**Comment by vmatyavin** [comment]
{
  "archive": {
    "start": "000000080000001400000074",
    "stop": "000000080000001400000074"
  },
  "backrest": {
    "format": 5,
    "version": "2.43"
  },
  "database": {
    "id": 1,
    "repo-key": 1
  },
  "error": false,
  "info": {
    "delta": 8462,
    "repository": {
      "delta": 442,
      "size": 467648354
    },
    "size": 2216361652
  },
  "label": "20230522-004006F_20230522-060008D",
  "lsn": {
    "start": "14/74000028",
    "stop": "14/74000138"
  },
  "prior": "20230522-004006F",
  "reference": [
    "20230522-004006F"
  ],
  "timestamp": {
    "start": 1684717208,
    "stop": 1684717213,
    "duration": 5
  },
  "type": "diff"
}

In what situations the "error" value could be true in this JSON snippet. Could you please provide some insights or examples of scenarios where the "error" value might be set to true?

Thank you!"

**Comment by dwsteele** [comment]
https://github.com/pgbackrest/pgbackrest/blob/main/src/command/info/info.c#L84

**Comment by vmatyavin** [comment]
our log shows this output:

ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
2023-05-24 12:13:19.044 P00   INFO: backup command end: aborted with exception [056]

Can I manually add an error code to a file that was not originally included, specifically error code 056, and will it be recognized and processed correctly?

**Comment by dwsteele** [comment]
> Can I manually add an error code to a file that was not originally included, specifically error code 056, and will it be recognized and processed correctly?

I'm not sure what that means. But if you mean can it be added to the `info` output, then no, at least not easily. This is a transient error -- info is mostly concerned with errors that prevent the repo from being read.
