### ISSUE TITLE
Why is restore time shorter than backup time?

### ISSUE THREAD

**Issue by damienApp** [pgbackrest/pgbackrest#2078]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

    pgBackRest version:
    ==> pgBackRest 2.45

    PostgreSQL version:
    ==> postgres (PostgreSQL) 15.2

    Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
    ==> Red Hat Enterprise Linux release 8.7 (Ootpa)

    Did you install pgBackRest from source or from a package?
    From ==> https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: Just a simple question I think, Why is restore time shorter than backup time ?

**Comment by sfrost** [comment]
Decompression is typically much faster than compression.  While there could be other factors, this is the most likely (and you haven't given us any specific info to go on, so...).

**Comment by damienApp** [comment]
Here more details : 
[pgbacrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/11597821/pgbacrest.conf.txt)
[postgres.conf.txt](https://github.com/pgbackrest/pgbackrest/files/11597822/postgres.conf.txt)

However, I don't seem to be using compression in my configuration nor in my backup command: pgbackrest --stanza=prod_backup --type=full --process-max=5 backup

Here are some measurements: 
| Size of Data directory before archiving (GB) | Size of Data directory after archiving (GB) | Size of Save directory after archiving (GB) | Size of Data directory after backup (GB) | Size of Save directory after backup (GB) | Backup size (GB) | Backup time (min) | Restore time (min) |
|----------------------------------------------|---------------------------------------------|--------------------------------------------|-------------------------------------------|------------------------------------------|------------------|--------------------|---------------------|
| 10                                           | 10                                          | 0.43                                       | 10                                        | 6.3                                      | 6.3              | 1.26               | 1.08                |
| 20                                           | 15                                          | 5.5                                        | 15                                        | 14                                       | 11.1             | 2.02               | 1.39                |
| 30                                           | 24                                          | 8.7                                        | 18                                        | 18                                       | 13.9             | 2.52               | 2                   |
| 180                                          | 180                                         | 102                                        | 77                                        | 158                                      | 73.6             | 13.31              | 10.29               |
| 202                                          | 86                                          | 110                                        | 86                                        | 173                                      | 82.6             | 15.39              | 11.52               |

**Comment by damienApp** [comment]
All right, I understand. Thank you for your reply.
