### ISSUE TITLE
pgBackRest 2.46 - block incremental

### ISSUE THREAD

**Issue by aleszeleny** [pgbackrest/pgbackrest#2079]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.46

3. PostgreSQL version: 14.6

4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS7, Alama Linux 9

5. Did you install pgBackRest from source or from a package? PGDG paclkages

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

  Full backup:     223G
  Increment next day after full backup with 2.45 (without configured beta block level incremental): 116G

7. Describe the issue:
The same cluster using 2.46 with block incremental switched on
 Full backup: 217G
 Next-day incremental backup:  2,1G

Fantastic work on the block incremental backups, many thanks for the immense effort spent on this great feature!

**Comment by dwsteele** [comment]
Thanks! We spent a lot of time on this and it went through many revisions. Glad it is working so well for you.
