### ISSUE TITLE
Should mention debian installation from pg debian repo in docs

### ISSUE THREAD

**Issue by singingfish** [pgbackrest/pgbackrest#2080]
e.g. we're running debian bullseye and while pg 15 is in bullseye a pg 15 compatible pgbackrest is currently not, so we need to add the relevant debian pg repo.  The docs should mention this.  In our case it was http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main

**Comment by dwsteele** [comment]
The docs do mention it here https://pgbackrest.org/user-guide.html#build, but you are not the first person to miss that.

Perhaps we should move this test to the "install" section and then make a reference from "build"? Thoughts, @pgstef?

**Comment by pgstef** [comment]
> Perhaps we should move this test to the "install" section and then make a reference from "build"? Thoughts, @pgstef?

The more we mention it (and even perhaps emphasizing that it's the way we recommend to do), the better imho.
I've sometimes even wondered if we shouldn't mention it on the main page, in the "Getting Started" section. But I wasn't sure what section does people read the most.

**Comment by dwsteele** [comment]
> But I wasn't sure what section does people read the most.
