### ISSUE TITLE
Change pg1host and primary_conninfo in pgbackrest.com for standby backup after failover (Patroni)

### ISSUE THREAD

**Issue by thatWasEzee** [pgbackrest/pgbackrest#2082]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.44
2. PostgreSQL version:
14.6
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.9
4. Did you install pgBackRest from source or from a package?
Package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
To take backup from standby, we have to set pg1host and primary_conninfo as the current leader host. When there is failover by Patroni, wondering if there is an option to automatically change these parameters to new leader host.

**Comment by pgstef** [comment]
Hi,

> When there is failover by Patroni, wondering if there is an option to automatically change these parameters to new leader host.

No, there isn't. You could ask Patroni to do it with one of its callbacks (on_role_change) if really needed.

> To take backup from standby, we have to set pg1host and primary_conninfo as the current leader host.

That's not true. First of all, primary_conninfo would be controlled by Patroni itself. Then there's no obligation to define the primary as pg1. I'm usually using pg1 as the locally running cluster and pg2 being the remote one.

The tricky part, depending on your situation (with/without repo-host, repo-type,...), is to detect on which host to actually run the backup command. Even more when you have several standby servers. What's your current architecture and how do you select on which server to run the backup command currently ?

**Comment by thatWasEzee** [comment]
Thank you for the response. If I do not set the correct leader as pg1-host in pgbackrest.conf, the backup command fails with this error:
```
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
```

You are correct that primary_conninfo is not required to take pgbackrest backup from standby. 

Our logic to detect from which host to run backup is to print the host name from patronictl list command grepping for 'Sync standby'. And if the current host is equal to hostname from above, pgbackrest backup command is executed, else exited. 

So, our question is.. if Patroni fails over the leader node to another node, how can we change the pg1-host to the current new leader automatically? If not manually modifying the pgbackrest.conf, the pgbackrest backup command is failing.

**Comment by thatWasEzee** [comment]
Closed it by accident.

**Comment by pgstef** [comment]
> So, our question is.. if Patroni fails over the leader node to another node, how can we change the pg1-host to the current new leader automatically? If not manually modifying the pgbackrest.conf, the pgbackrest backup command is failing.

You don't have to change the config after a Patroni fail-over. Just set pg1-path (being the local PG node) and pg2-host/pg3-host/... being the other PG nodes (or pg1-host to the other PG node and pg2-path only for the local PG node if you prefer). pgBackRest will detect the primary from the list of PG nodes.

> If I do not set the correct leader as pg1-host in pgbackrest.conf, the backup command fails

It shouldn't fail. But since you didn't provided any detail about this error (config,..), we can't help you find what's missing.
