### ISSUE TITLE
feature request for S3 repository

### ISSUE THREAD

**Issue by kikijolicoeur** [pgbackrest/pgbackrest#2084]
Hi.
Thanks a lot for pgbackrest.
I have thousands PostgreSQL cluster to backup. Each cluster uses pgbackrest with S3 repository. I configured S3 to forbid S3 delete and it works fine. But, if a hacker gained access to the cluster, he cannot delete S3 object but he could modify all objects in S3 and thus destroy the backup.
It would be great if pgbackrest could support object locking. The idea would be to set a S3 retention period in the pgbackrest configuration  that would be used during the putObject to ensure that nobody can modify the object for a certain period of time.
What do you think about it?

Best regards

Christian

**Comment by dwsteele** [comment]
This is a feature we are considering, but it is a lot harder than it looks. We currently depend on being able to overwrite certain files so losing that capability breaks the repository. There are other issues where we discuss this more in depth -- see #1494 for more info.

**Comment by kikijolicoeur** [comment]
Thanks for yout answer. I suppose you make reference to some files like backup.info and backup.info.copy ?

**Comment by dwsteele** [comment]
> I suppose you make reference to some files like backup.info and backup.info.copy

Yes, and `archive.info` and `archive.info.copy`.
