### ISSUE TITLE
ERROR: [043]: path to copy WAL segment required

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#2085]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.36
2. PostgreSQL version:
12
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.6.1810 (Core)
4. Did you install pgBackRest from source or from a package?
RPM
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
log-level-console=info
log-level-file=info
start-fast=y
process-max=8
repo1-s3-bucket=nsdwh
repo1-s3-endpoint=s3.cls.fr
repo1-s3-port=9443
repo1-s3-uri-style=path
repo1-s3-key=blah
repo1-s3-key-secret=secretstuff
repo1-s3-region=FR
repo1-type=s3
repo1-s3-verify-tls=n

[nsdwh]
pg1-path=/data/12

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
 pgbackrest --stanza=nsdwh archive-push %p
on
*
20
replica
5432

7. Describe the issue:
Sorry, I'm dumb. Trying to get an archive to copy to a standby.
[postgres@ns-dwh-prod  pg_wal]$ pgbackrest archive-get 000000010000CC7E000000CF --stanza=nsdwh
2023-06-06 09:08:44.896 P00   INFO: archive-get command begin 2.36: [000000010000CC7E000000CF] --exec-id=30076-2083a960 --log-level-console=info --log-level-file=info --pg1-path=/data/12 --process-max=8 --repo1-path=/var/lib/pgbackrest --repo1-s3-bucket=nsdwh --repo1-s3-endpoint=s3.cls.fr --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=FR --repo1-s3-uri-style=path --repo1-storage-port=9443 --no-repo1-storage-verify-tls --repo1-type=s3 --stanza=nsdwh
ERROR: [043]: path to copy WAL segment required
2023-06-06 09:08:44.896 P00   INFO: archive-get command end: aborted with exception [043]

No idea what I need to supply to get my WAL back into my pg_wal directory or even in /tmp so that I can copy it to another machine.
Apologies, tried /tmp, tried the actual pg_wal directory

**Comment by pgstef** [comment]
Hi,

What are you trying to do exactly? `archive-get` isn't supposed to be run manually. I guess your underlying issue is a standby server with replication lag and your primary which doesn't have the wals for the replication anymore?

The best you can do is to use the standby Postgres `restore_command` setting to fetch the missing wals from the pgBackRest archives using `archive-get`. All you have to do is to have a shared repo between your PG nodes (which I would recommend anyway so you don't lose data when a failover happens). So the standby just need to reach your s3 bucket actually.

Kind Regards

**Comment by mattbunter** [comment]
Apologies, I was sure in the past that I was able to run archive-get and restore some missing wals and send them to my standby (which is not configured with pgbackrest and has no access to the repo).
I just want to get a certain number of wals restored somewhere on the primary to copy them to the standby.

**Comment by dwsteele** [comment]
You can still run it manually, but you need to specify the destination file, .e.g.:
```
pgbackrest archive-get 000000010000CC7E000000CF /path/to/000000010000CC7E000000CF
```

**Comment by mattbunter** [comment]
This is perfect, I have several hours to get, any regex type magic acceptable to use??

**Comment by dwsteele** [comment]
> any regex type magic acceptable to use?

No, since this is not the intended use for this command. Generally, the only reason to use it manually is to grab a particular WAL segment for debugging.

**Comment by mattbunter** [comment]
Thank you for your replies.
