### ISSUE TITLE
Preserving Last Backup of Each Year: Configuring Backup Retention

### ISSUE THREAD

**Issue by zN3utr4l** [pgbackrest/pgbackrest#2087]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **2.46**

2. PostgreSQL version: **14**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: **Docker Alpine**

4. Did you install pgBackRest from source or from a package? **Source**

5. Describe the issue:

What are you trying to do?
I was wondering if it would be possible, through some configuration, to prevent the deletion of the last backup of each year.

For example, if it is 31st December 2022, and I perform a backup, two days later, according to my configuration, the 31st backup will be deleted, is it possible to not delete it?

For instance, by moving each backup to its own folder, such as backup/2022, backup/2023, and every time you look for the backups to delete, deleting them in the current year's folder, or for each year the backups of BACKUP_RETENTION_DAYS are deleted but starting from December 31st, that is, according to my configuration, BACKUP_RETENTION_DAYS=2, the backups of December 31st and December 30th will remain in the system.

I have already done a script, but how can i execute this on pre pruning?

```
#!/bin/sh

folder="/archive"

for file in "$folder"/*.tar.gz; do
    created_year=$(stat -c %y "$file" | cut -d'-' -f1)

    # If the file was created in a previous year
    if [ "$created_year" -lt "$(date +%Y)" ]; then
        # Create the year folder if it doesn't exist
        mkdir "$folder/$created_year"

        # Move the file to the year folder if it's newer than the current year file
        latest_year_file=$(ls -t "$folder/$created_year/"*.tar.gz 2>/dev/null | head -n1)
        if [ "$latest_year_file" ]; then
            if [ "$file" -nt "$latest_year_file" ]; then
                mv -v "$latest_year_file" "$folder"
                mv -v "$file" "$folder/$created_year"
            fi
        else
            mv -v "$file" "$folder/$created_year"
        fi
    fi
done
```

**Comment by dwsteele** [comment]
There is no way to do this directly with pgBackRest retention and I would caution you against modifying the contents of the repository yourself. You are likely to end up with unusable backups.

What you could do is set full retention very high (e.g. repo1-retention-full=99999) and implement your own expiration. You can do this by getting the list of full backups from the info command (using --output=json) and then run `expire --set=XXX` for any full backups you want to expire.

This is non-trivial but would be a lot safer than what you are attempting with your attached script.

**Comment by zN3utr4l** [comment]
Perfect, I'll try and let you know
