### ISSUE TITLE
Changing compress-type midstream

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#2092]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.46

2. PostgreSQL version: 15.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 8.6

4. Did you install pgBackRest from source or from a package? PGDG repository.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:  currently, the config file has "compress-type=lz4", but I'd like to change it to "compress-type=zst".  Is there anything else to do, other than "pgbackrest stop" then "pgbackrest start"?

If I need to restore some time in the next few weeks, will "pgbackrest restore" automagically notice that some incrementals and archive backups are lz4 and others zst?  (I presume so, but want to verify.)

**Comment by dwsteele** [comment]
For archiving you can just change compress type and it will start using the new compression type as soon as the async process restarts or immediately if async is not enabled. No need to stop/start.

For backup it is a bit more complicated. Backup sets must have the same compression so the compression can't be changed until the next full. If you change it earlier you'll get warnings that it is being set back to the prior value until the next full. What I usually do is make the change right before the next full backup, but if you don't mind the warnings it doesn't hurt to change it earlier.
