### ISSUE TITLE
Add timezone offset to pgbackrest info

### ISSUE THREAD

**Issue by philrhurst** [pgbackrest/pgbackrest#2093]
It would be helpful if the `pgbackrest info` output included the timezone offset for the `timestamp start/stop`. It makes it clear what PITR targets are available (since timezone offsets should be included there, per the User Guide)

Example:

```
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (14): 00000003000000000000003C/00000007000000000000005B

        full backup: 20230614-121304F
            timestamp start/stop: 2023-06-14 12:13:04+00 / 2023-06-14 12:13:30+00
            wal start/stop: 00000003000000000000003C / 00000003000000000000003D
            database size: 49.2MB, database backup size: 49.2MB
            repo1: backup set size: 8MB, backup size: 8MB
```

**Comment by dwsteele** [comment]
This seems like a reasonable request but there doesn't appear to be a portable way to do it. Unlike Postgres we enforce C99/Posix compliance and that means both ways Postgres uses (HAVE_STRUCT_TM_TM_ZONE, HAVE_INT_TIMEZONE) do not appear to be available to us.

Maybe @sfrost has thoughts on this?

**Comment by RonJohn2** [comment]
> This seems like a reasonable request but there doesn't appear to be a portable way to do it. Unlike Postgres we enforce C99/Posix compliance and that means both ways Postgres uses (HAVE_STRUCT_TM_TM_ZONE, HAVE_INT_TIMEZONE) do not appear to be available to us.

Could you add a "memo" noting the DB server timestamp's timezone (like "America/New_York")?  That would at least give the users something to work with.

**Comment by dwsteele** [comment]
> Could you add a "memo" noting the DB (and PgBackRest, if they're separate) server timestamp's timezone (like "America/New_York")?

Timezone name is available, but I don't see that as being hugely useful since it won't give DST info. Easy enough to just run `date` anyway. I think what people want here is to be able to copy and paste datetimes from the info command to `--target` or into PG recovery configuration.

I think we might be able to play some games with gmtime() vs localtime() to extract the offset. I'll have a look into that.

**Comment by dwsteele** [comment]
> I think we might be able to play some games with gmtime() vs localtime() to extract the offset. I'll have a look into that.

This seems to have worked, though it is a bit ugly. See PR #2095.
