### ISSUE TITLE
connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  relation mapping file "base/99102/pg_filenode.map" contains invalid data

### ISSUE THREAD

**Issue by lux7789** [pgbackrest/pgbackrest#2097]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.44
2. PostgreSQL version:
15.2
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
4. Did you install pgBackRest from source or from a package?
 Source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

classe=# \c postgres
You are now connected to database "postgres" as user "postgres".
postgres=# \c template0
connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "template0" is not currently accepting connections
Previous connection kept
postgres=# \c template1
You are now connected to database "template1" as user "postgres".
template1=# \c keycloak
connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  relation mapping file "base/96507/pg_filenode.map" contains invalid data
Previous connection kept
template1=# \c pgbench
connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  relation mapping file "base/99102/pg_filenode.map" contains invalid data
Previous connection kept

7. Describe the issue:
After a restore of the database "classe" with this command :`pgbackrest --config=/etc/pgbackrest.conf --stanza=backup --log-level-console=info  --db-include=classe --type=time "--target=2023-06-14 14:35:46" --delta --target-action=promote restore`

I have those errors reported above in section 5).  How can I connect to those failing database ?

**Comment by jreidthompson** [comment]
You cannot, you specifically requested that only the db classe be restored.  See https://pgbackrest.org/command.html#command-restore. If you want those db's to be available you will need to alter your restore command.

12.1.3 Include Database Option (--db-include)
Restore only specified databases.
This feature allows only selected databases to be restored. Databases not specifically included will be restored as sparse, zeroed files to save space but still allow PostgreSQL to perform recovery. After recovery, the databases that were not included will not be accessible but can be removed with the drop database command.
NOTE:
built-in databases (template0, template1, and postgres) are always restored unless specifically excluded.
The --db-include option can be passed multiple times to specify more than one database to include.

See Restore Selected Databases for additional information and caveats.

**Comment by dwsteele** [comment]
Well, built-in databases are restored, but in this case looks like these databases have been recreated since their oid is > 16384 (thus they are not recognized as built-in). So in this case you'll need to explicitly include them.

**Comment by lux7789** [comment]
Hi,

I explicitly included all db with --db-include. It worked fine.

Thanks.
