### ISSUE TITLE
Experiencing a high number of zombie processes with archive-push in async mode

### ISSUE THREAD

**Issue by valterartur** [pgbackrest/pgbackrest#2098]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgbackrest version
pgBackRest 2.39

2. PostgreSQL version:
PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Operating System: Ubuntu 22.04.2 LTS
Deployment: Kubernetes using Stolon

5. Did you install pgBackRest from source or from a package?
Built from source: [pgBackRest 2.39](https://github.com/pgbackrest/pgbackrest/archive/release/2.39.tar.gz)

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
[global]
repo1-path=/primary
repo1-type=s3
repo1-s3-endpoint=minio:9000
repo1-s3-bucket=pg-archive
repo1-s3-verify-tls=y
repo1-storage-ca-file=/certs/ca.crt
repo1-s3-region=us-east-1
repo1-s3-uri-style=path
repo1-retention-full=1
repo1-bundle=y
repo1-bundle-limit=10MiB
repo1-bundle-size=30MiB
start-fast=y
stop-auto=y
io-timeout=900
process-max=4
log-level-console=info
log-level-file=debug
log-path=/tmp
delta=y
archive-async=y
spool-path=/stolon-data/pgbackrest
archive-push-queue-max = 100GiB
exclude=postgresql.auto.conf

[backup]
pg1-path=/stolon-data/postgres
```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
```
effective_io_concurrency = '200'
timezone = 'Etc/UTC'
checkpoint_timeout = '15min'
datestyle = 'iso, mdy'
checkpoint_completion_target = '0.9'
listen_addresses = '10.244.33.10'
ssl = 'on'
max_wal_size = '30GB'
ssl_cert_file = '/certs/tls.crt'
log_timezone = 'Etc/UTC'
min_wal_size = '80MB'
ssl_key_file = '/certs/tls.key'
max_replication_slots = '20'
default_text_search_config = 'pg_catalog.english'
ssl_ca_file = '/certs/ca.crt'
dynamic_shared_memory_type = 'posix'
port = '5432'
synchronous_standby_names = ''
archive_mode = 'on'
shared_buffers = '2048MB'
wal_level = 'logical'
hot_standby = 'on'
wal_keep_size = '128'
shared_preload_libraries = 'decoderbufs,wal2json'
max_connections = '1000'
archive_command = 'PGPASSWORD=$PGADMINPWD pgbackrest --stanza=backup archive-push %p'
unix_socket_directories = '/tmp'
max_wal_senders = '47'
```
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
```
 ls -a /var/log/pgbackrest/
.  ..
```
We have also configured debug logs to file but it states that all the operations were successful. Attaching the debug log
[backup-archive-push-async.log](https://github.com/pgbackrest/pgbackrest/files/11803510/backup-archive-push-async.log)

7. Describe the issue:
We are experiencing an issue where running archive-push in async mode causes a large number of zombie processes to be generated. Our database is highly dynamic with extensive insertions and deletions. Over time, the accumulation of zombie processes makes PostgreSQL extremely slow and almost inoperable. Restarting the instance temporarily resolves the issue.

This issue bears similarities to [#1116](https://github.com/pgbackrest/pgbackrest/issues/1116), but we're encountering it in a newer version (2.39).

We are able to reproduce this issue by executing this simple script.
```
CREATE TABLE my_large_table (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    age INT,
    address VARCHAR(255),
    phone_number VARCHAR(20),
    email VARCHAR(255),
    created_at TIMESTAMP
);

CREATE OR REPLACE FUNCTION insert_large_data() RETURNS VOID AS $$
DECLARE
    batch_size INT := 1000;
    total_batches INT := 10000; 
    i INT := 0;
BEGIN
    WHILE i < total_batches LOOP
        INSERT INTO my_large_table (name, age, address, phone_number, email, created_at)
        SELECT
            md5(random()::text) AS name,
            floor(random() * 100)::INT AS age,
            md5(random()::text) AS address,
            floor(random() * 10000000000)::BIGINT::VARCHAR AS phone_number,
            md5(random()::text) || '@example.com' AS email,
            NOW() AS created_at
        FROM generate_series(1, batch_size);
        
        i := i + 1;
    END LOOP;
END;
$$ LANGUAGE plpgsql;
SELECT insert_large_data();
DROP FUNCTION insert_large_data();
```
When executed, this script reliably reproduces the issue with the accumulation of zombie processes.
```
stolon@postgres-keeper-0:/$ ps aux | grep pgbackrest
stolon      8463  0.0  0.0      0     0 ?        Z    16:08   0:00 [pgbackrest] <defunct>
stolon      8475  0.0  0.0      0     0 ?        Z    16:08   0:00 [pgbackrest] <defunct>
stolon      8514  0.0  0.0      0     0 ?        Z    16:08   0:00 [pgbackrest] <defunct>
stolon      8562  0.0  0.0      0     0 ?        Z    16:09   0:00 [pgbackrest] <defunct>
stolon      8623  0.0  0.0      0     0 ?        Z    16:09   0:00 [pgbackrest] <defunct>
stolon      8710  0.0  0.0      0     0 ?        Z    16:09   0:00 [pgbackrest] <defunct>
stolon      8789  0.0  0.0      0     0 ?        Z    16:09   0:00 [pgbackrest] <defunct>
stolon      8861  0.0  0.0      0     0 ?        Z    16:09   0:00 [pgbackrest] <defunct>
stolon      8956  0.0  0.0      0     0 ?        Z    16:10   0:00 [pgbackrest] <defunct>
stolon      9028  0.0  0.0      0     0 ?        Z    16:10   0:00 [pgbackrest] <defunct>
stolon      9117  0.0  0.0      0     0 ?        Z    16:10   0:00 [pgbackrest] <defunct>
stolon      9190  0.0  0.0      0     0 ?        Z    16:10   0:00 [pgbackrest] <defunct>
stolon      9281  0.0  0.0      0     0 ?        Z    16:10   0:00 [pgbackrest] <defunct>
stolon      9379  0.0  0.0      0     0 ?        Z    16:11   0:00 [pgbackrest] <defunct>
stolon      9457  0.0  0.0      0     0 ?        Z    16:11   0:00 [pgbackrest] <defunct>
stolon      9533  0.0  0.0      0     0 ?        Z    16:11   0:00 [pgbackrest] <defunct>
stolon      9599  0.0  0.0      0     0 ?        Z    16:11   0:00 [pgbackrest] <defunct>
stolon     10315  0.0  0.0   6612  2312 pts/2    S+   16:14   0:00 grep --color=auto pgbackrest
```
These zombie processes have stolon-keeper (PID 1) as their parent process.
```
stolon@postgres-keeper-0:/proc/8463$ ps 1
PID TTY      STAT   TIME COMMAND
1 ?        Ssl    0:50 stolon-keeper --data-dir /stolon-data --log-level warn
```
Switching to synchronous archiving eliminates the zombie processes but we are concerned about potential performance impacts.

Questions:
Is this a known issue or a configuration problem?
Are there any recommended configurations or workarounds to prevent zombie processes without switching to synchronous archiving?

**Comment by tr-arturvalter** [comment]
Just tested with 2.46, same situation

**Comment by valterartur** [comment]
Just tested with 2.46, same situation

**Comment by valterartur** [comment]
Sorry for the late response,  I wanted to share some findings that could be beneficial for those who might encounter a similar situation in the future.

For anyone using Stolon in a containerized environment, it's crucial to ensure that Stolon is not running as the init process in your container. The init process has specific responsibilities that typical application processes are not designed to handle.

In the case of Stolon, it isn't designed to manage processes as the init process would. Instead, I recommend using a utility like tini to manage your Stolon process.

For more detailed understanding:
https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by dwsteele** [comment]
> Sorry for the late response, I wanted to share some findings that could be beneficial for those who might encounter a similar situation in the future.

Thanks for the response and for reporting this. No doubt it will be useful information for others.
