### ISSUE TITLE
Lots of "page misalignment in file" Warnings while doing a backup

### ISSUE THREAD

**Issue by ajayrahul97** [pgbackrest/pgbackrest#2099]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45

2. PostgreSQL version: 9.4.26

3. Operating system/version -  Ubuntu 20.04.1 LTS

4. Did you install pgBackRest from source or from a package? : Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
 - [seg0]
pg1-socket-path = /tmp
pg1-user        = myadmin
log-path        = /usr/local/ajay/logs
repo1-type      = posix
repo1-path      = /home/myadmin/ajay/archive/seg0

7. Describe the issue:
I'm using pgbackrest to backup a huge database (402gb, containing TPCDS data).
On doing a full/incr backup I see a lot of page misalignment warnings in the log. My logs are flooded with these warnings. I'm unable to understand the reason. Any guidance on how to avoid these warnings would be appreciated.

```
2023-06-08 23:11:23.148 P00   WARN: page misalignment in file /data/cluster/ajay/seg0/base/87936/55208.257: file size 11829024 is not divisible by page size 32768
2023-06-08 23:11:23.429 P00   WARN: page misalignment in file /data/cluster/ajay/seg0/base/87936/55364.2177: file size 11765840 is not divisible by page size 32768
2023-06-08 23:11:23.451 P00   WARN: page misalignment in file /data/cluster/ajay/seg0/base/87936/55308.2177: file size 11785216 is not divisible by page size 32768
2023-06-08 23:11:23.481 P00   WARN: page misalignment in file /data/cluster/ajay/seg0/base/87936/55260.2177: file size 11755528 is not divisible by page size 32768
2023-06-08 23:11:24.111 P00   WARN: page misalignment in file /data/cluster/ajay/seg0/base/87936/55468.2177: file size 11754672 is not divisible by page size 32768
2023-06-08 23:11:24.435 P00   WARN: page misalignment in file /data/cluster/ajay/seg0/base/87936/55416.2177: file size 11752848 is not divisible by page size 32768
2023-06-08 23:11:24.464 P00   WARN: page misalignment in file /data/cluster/ajay/seg0/base/87936/55256.2177: file size 11751608 is not divisible by page size 32768

```

I looked into https://github.com/pgbackrest/pgbackrest/issues/327 - which is a similar issue, but this seems to be only for a certain set of files. Is it safe to comment out the warning in backup.c ? Any points on why this warning appears would also be helpful. Thank you !!

**Comment by ajayrahul97** [comment]
The database that I'm using has append-only tables, where the segment files can be different and not divisible by PG_PAGE_SIZE_DEFAULT. I want to understand more on the consequences of removing the warning. I checked backup.c, the code sets checksumPageError = true and displays the warning here : 
`if (!pckReadBoolP(checksumPageResult))
                            {
                                checksumPageErrorList = NULL;

                                // ??? Update formatting after migration
                                LOG_WARN_FMT(
                                    "page misalignment in file %s: file size %" PRIu64 " is not divisible by page size %u",
                                    strZ(fileLog), copySize, PG_PAGE_SIZE_DEFAULT);
                            }`

Could you please elaborate on why you recommend not to comment out the warning ?
Thanks !

**Comment by woblerr** [comment]
Hi

Is it Greenplum? If so, please, see this PR [pgbackrest/pull/1833](https://github.com/pgbackrest/pgbackrest/pull/1833)

**Comment by dwsteele** [comment]
> Could you please elaborate on why you recommend not to comment out the warning?

Because we don't test this way. If you modify the code you have created a fork and are on your own for testing that it works correctly. I would recommend setting `--checksum-page=n` as I mentioned above.

**Comment by ajayrahul97** [comment]
@dwsteele Thank you for the clarification. 
We have our own pgbackrest fork, and we have been testing on Append Optimized tables on Greenplum. AO tables have various sizes; they are not organized by pages; hence this page misaligment warning always shows up. We have successfully tested backing up and restoring these AO tables. We have some follow up questions. 

1. What is the motivation behind this page misalignment check?  Will the checksum integrity be compromised because of page misalignment? If yes, then what are the consequences.
2. Can this page misalignment with AO tables impact incremental backup / delta restore? 
3. What causes the following error in the mainfest file? These failures do not seem to fail the backup command. We are able to successfully restore this backup as well. 
`pg_data/base/16384/20083.769={"bni":16,"bno":80806892,"checksum":"23e65f8605297bd3cf84847be70dac6335b441f2","checksum-page":false,"checksum-page-error":[[25198592,25198611]],"rck":"40ee717332e709245c02e8da345ea0518f6e6b1e","repo-size":655432,"size":655360,"timestamp":1687400838} `

**Comment by ajayrahul97** [comment]
> Hi
> 
> Is it Greenplum? If so, please, see this PR [pgbackrest/pull/1833](https://github.com/pgbackrest/pgbackrest/pull/1833)

@woblerr Thank you for the input. Yes we are using Greenplum. We are waiting for the PR to be merged. Our pgbackrest fork contains changes pertaining to WAL and Page size, Catalog Version etc which are greenplum centric.

**Comment by dwsteele** [comment]
All the checks we have are intended to verify that the data is correct. All or some of them may not be applicable in your case, but I'm not going to venture any opinions on that since I am not familiar with your pgBackRest fork or AO tables in Greenplum.
