### ISSUE TITLE
stanza-create command fails when using Contabo S3 

### ISSUE THREAD

**Issue by danclimasevschi** [pgbackrest/pgbackrest#2101]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
`2.45`

2. PostgreSQL version:
`14`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
`Ubuntu 22.04.2 LTS`

4. Did you install pgBackRest from source or from a package?
package:   `pgbackrest/now 2.45-1.pgdg22.04+1 amd64 [installed,local]`

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s):
 ```
[main]
pg1-path=/home/pgdata
[global]
repo1-path=/postgres-backup
repo1-retention-full=4
repo1-retention-diff=7
repo1-s3-bucket=eu2
repo1-s3-endpoint=contabostorage.com/postgres-backup
repo1-s3-key=KEY
repo1-s3-key-secret=SECRET
repo1-s3-region=eu2
repo1-type=s3
start-fast=y
[global:archive-push]
compress-level=3 
```

7. Describe the issue:
Trying to run stanza-create fails:

```shell
postgres@HOST:~$ pgbackrest --config /etc/pgbackrest/pgbackrest.conf --log-level-console=info --stanza=main stanza-create
2023-06-23 09:29:20.801 P00   INFO: stanza-create command begin 2.45: --config=/etc/pgbackrest/pgbackrest.conf --exec-id=1980-8f32be5e --log-level-console=info --pg1-path=/home/pgdata --repo2-path=/postgres-backup --repo2-s3-bucket=eu2 --repo2-s3-endpoint=contabostorage.com/postgres-backup --repo2-s3-key=<redacted> --repo2-s3-key-secret=<redacted> --repo2-s3-region=eu2 --repo2-type=s3 --stanza=main
2023-06-23 09:29:21.406 P00   INFO: stanza-create for stanza 'main' on repo2
ERROR: [029]: unable to find child 'IsTruncated':0 in node 'ListAllMyBucketsResult'
2023-06-23 09:29:21.502 P00   INFO: stanza-create command end: aborted with exception [029]
```
Debug log:

```shell
       version: 2.45
       command: stanza-create
       options: --config=/etc/pgbackrest/pgbackrest.conf --exec-id=2094-8a02ca5a --log-level-console=debug --pg1-path=/home/pgdata --repo1-path=/postgres-backup --repo1-s3-bucket=eu2 --repo1-s3-endpoint=contabostorage.com/postgres-backup --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=eu2 --repo1-type=s3 --stanza=main

       stack trace:
       common/type/xml.c:xmlNodeChildN:238:(test build required for parameters)
           ... function(s) omitted ...
       storage/s3/storage.c:storageS3ListInternal:(trace log level required for parameters)
       storage/s3/storage.c:storageS3List:(trace log level required for parameters)
       storage/iterator.c:storageItrPathAdd:(trace log level required for parameters)
       storage/iterator.c:storageItrNew:(driver: *void, path: {"/postgres-backup/archive/main"}, level: 3, errorOnMissing: false, nullOnMissing: false, recurse: false, sortOrder: 0, expression: null)
       storage/storage.c:storageNewItr:(this: {type: s3, path: /postgres-backup, write: false}, pathExp: {"<REPO:ARCHIVE>"}, param.level: 0, param.errorOnMissing: false, param.recurse: false, param.nullOnMissing: false, param.sortOrder: 0, param.expression: null, param.recurse: false)
       storage/storage.c:storageList:(this: {type: s3, path: /postgres-backup, write: false}, pathExp: {"<REPO:ARCHIVE>"}, param.errorOnMissing: false, param.nullOnMissing: false, param.expression: null)
       command/stanza/create.c:cmdStanzaCreate:(void)
       main.c:main:(debug log level required for parameters)
```

FWIW: Contabo is using `Ceph`
FWIW2: aws cli works perfectly fine with it.

I am attaching a log where I ran `verifiy`, `check` and `stanza-create` commands with debug level logging.
[pgbackrest_command_output.txt](https://github.com/pgbackrest/pgbackrest/files/11846989/pgbackrest_command_output.txt)

Thanks for the awesome project!

**Comment by dwsteele** [comment]
> ERROR: [029]: unable to find child 'IsTruncated':0 in node 'ListAllMyBucketsResult'

`IsTruncated` is a required field for ListObjectsV2 (https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html), which is what we request from the server. Unfortunately some servers ignore this request and return V1 results, which have been deprecated for eight years or more.

AWS CLI fails back to V1, we don't. Contact your vendor about getting this fixed (we've seen other vendors fix it when the issue is pointed out to them).

You can search issues for `IsTruncated` to get more info on past similar issues.

**Comment by danclimasevschi** [comment]
> > ERROR: [029]: unable to find child 'IsTruncated':0 in node 'ListAllMyBucketsResult'
> 
> `IsTruncated` is a required field for ListObjectsV2 (https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html), which is what we request from the server. Unfortunately some servers ignore this request and return V1 results, which have been deprecated for eight years or more.
> 
> AWS CLI fails back to V1, we don't. Contact your vendor about getting this fixed (we've seen other vendors fix it when the issue is pointed out to them).
> 
> You can search issues for `IsTruncated` to get more info on past similar issues.

Thanks. I imagine you run tests against different S3 providers(who probably comply with `V2`). Any chance you could include them in the documentation?

Best regards,
Dan

**Comment by dwsteele** [comment]
> I imagine you run tests against different S3 providers

We don't have the time or resources to do anything like this. It can be very version dependent and most platforms don't advertise versions, or they vary based on server, product, etc. Far too much for us to keep track of, even if we wanted to.

We test on AWS (when we make driver changes) and use Minio for CI. We also have unit tests that test every line and condition in the driver for any regression.

**Comment by danclimasevschi** [comment]
To anyone interested, `DigitalOcean`'s Spaces also do not work.

**Comment by dwsteele** [comment]
We are open to the idea that something is wrong with our driver, but in past discussions we have found the issue to be on the vendor side.

**Comment by yrul1kethis** [comment]
Don't know if it helps, but:

I got the same 'IsTruncated' problem on a self-hosted Ceph S3 and, well, set log level to trace, read it for a while and found out that our S3 doesn't support _bucket.endpoint_  kind of path (throws HTTP 404). So, I used the key --repo-s3-uri-style with _path_ value, and my stanza was successfully created. 
pgbackrest version 2.46, OS Debian 11

**Comment by dwsteele** [comment]
> found out that our S3 doesn't support bucket.endpoint kind of path (throws HTTP 404)

Interesting that the result is a mangled reply (missing IsTruncated) instead of 404.
