### ISSUE TITLE
dedicated host with docker containers and backup scheduling

### ISSUE THREAD

**Issue by drembaru** [pgbackrest/pgbackrest#2102]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.46

2. PostgreSQL version: 15.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Debian 12 (bookworm) docker container for both repository host and primary host

4. Did you install pgBackRest from source or from a package? Package (Debian 12)

First: Thanks a lot for developing pgbackrest!

My question: I have a dedicated host setup with two docker container, the repository host where the repository is stored and the primary host where the database is running. Is it safe, to run backups from a third container, that shares the necessary volumes with the repository host that only gets started for doing the backups?

This way it would be possible to avoid scheduling the backups from within the repository host container and instead start the backup docker container from outside. This makes scheduling way easier. In the end the idea is to run everything in a kubernetes cluster and use kubernetes CronJobs for backup scheduling.

Thanks in advance for your help and let me know if anything is unclear.

**Comment by dwsteele** [comment]
> My question: I have a dedicated host setup with two docker container, the repository host where the repository is stored and the primary host where the database is running. Is it safe, to run backups from a third container, that shares the necessary volumes with the repository host that only gets started for doing the backups?

This generally not a safe thing to do. The problem is that even if the blocks are flushed to disk on fsync, another host might be holding blocks in cache that it does not realize have been updated (since it was done on another system). So, this might work 98% of the time but cause silent corruption the other 2% (or much more). You won't know there was corruption until you run into bad data during normal operation after a restore.

**Comment by drembaru** [comment]
Thanks a lot for the quick reply. I feared that this might not be safe, so I will avoid this problem by doing the backups from within the repository host container. Feel free to close the issue :)
