### ISSUE TITLE
pgbackrest backup restore on new machine

### ISSUE THREAD

**Issue by daulat0** [pgbackrest/pgbackrest#2107]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45

2. PostgreSQL version: 14.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Primary server : Amazon Linux2 
Remote server (New Machine) : Amazon Linux2 

4. Did you install pgBackRest from source or from a package?

Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    
`archive_command:  pgbackrest --stanza=testdb1 archive-push %p
`archive_mode` = on
`listen_addresses`,  '*"
`max_wal_senders`, 10
 `wal_level`, Replica
 `port`): 5432
    - errors in the postgresql log file before or during the time you experienced the issue : No error
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We are taking postgres backup via pgbackrest on s3 bucket and we need to restore that backup on separate server.
Anyone please suggest me how we can restore that backup on different server incase our primary goes down due to any reason. 

Thanks

**Comment by pgstef** [comment]
Hi,

Your "different" server will need a pgbackrest configuration with access to the s3 bucket where the backups are stored. 
And then you simply can run the restore command. However, you'll have to define your PG recovery target by yourself.

At this point I would defenitely recommend to already try that now: don't wait for a real disaster to test restore your backup.
Give your new server a RO access to your backup repository and try a restore with the `--archive-mode=off` option to disable wal archiving on the test server.

Kind Regards

**Comment by daulat0** [comment]
Thanks for quick response, can you please suggest the pgbackrest.conf options for remote server.  I have access to s3 bucket.
Are these options correct for new server ?

pg1-path=
pg1-port=
pg1-user=
pg1-socket-path=
repo1-path=
repo1-s3-endpoint=
repo1-s3-bucket=
repo1-s3-region=
repo1-type=s3
repo1-s3-key=
repo1-s3-key-secret=

**Comment by daulat0** [comment]
Do I need to create a stanza on new server using the same s3 bucket (secrete and access key) which is used by primary server? Please suggest.

**Comment by pgstef** [comment]
Create stanza = initialize the repository content (gather info about the PG cluster like version and system-id + create sub-directories for archives and backups). So since you simply want to restore a backup from that existing repository, you don't need to create the stanza again.

But as I mentioned previously already you'll have to adjust your configuration to use the same "stanza" (which is just a name/label to identify from where your backups and archives are coming from). That's why I also suggested a RO access to the bucket and using the `--archive-mode=off` restore option.
