### ISSUE TITLE
SSH banners seem to cause backup failures

### ISSUE THREAD

**Issue by gamerscomplete** [pgbackrest/pgbackrest#211]
I am getting a consistent failure to complete a remote backup. The database im testing with is fairly large at 4tb and runs for about 14 hours each time before failing with the same message each time. I am not positive that the banner is the cause of the error but it spits out my SSH banner every time before it fails. 

I tried to figure out what was going on with the code but I am not the greatest at Perl and I didn't understand what that function is doing. 

Error seems to be raised from
pgbackrest/lib/pgBackRest/Protocol/IO.pm line 300

2016-06-22 03:07:36.616 T00  ERROR: [141]: remote process terminated: ######################################################################
                                           # WARNING : Unauthorized access to this system is forbidden and will #
                                           # be prosecuted by law. By accessing this system, you agree that     #
                                           # your actions may be monitored if unauthorized usage is suspected.  #
                                           #                                                                    #
                                           # All connections are monitored and recorded                         #
                                           # Disconnect immediately if you are not an authorized user!          #
                                           #                                                                    #
                                           ######################################################################
                                           ERROR [141]: unable to read line after 1830 seconds
2016-06-22 03:07:36.722 T00   INFO: backup stop

**Comment by dwsteele** [comment]
Try adding `LogLevel quiet` to your `~/.ssh/config`.  Banners interfere with the protocol handshake.

**Comment by gamerscomplete** [comment]
The LogLevel removed the banner from the logs but did not stop it from failing. Now it just dies with

2016-06-23 04:50:02.609 T00  ERROR: [141]: remote process terminated: ERROR [141]: unable to read line after 1830 seconds

No errors on the database side. Any suggestions?

**Comment by dwsteele** [comment]
Did that work?  I've added a few new fixes to master that should help without adding that flag and they'll be out in the next release.

**Comment by dwsteele** [comment]
Hi Chris, I'm going to close this as I believe it will be resolved with changes made for 1.03.

**Comment by dwsteele** [comment]
1.03 has been release with these fixes.
