### ISSUE TITLE
An example of monitoring pgBackRest archive delay from within PostgreSQL 15+ not relaying on pgbackrest info

### ISSUE THREAD

**Issue by covalenthq-rj** [pgbackrest/pgbackrest#2110]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):
1. pgBackRest version: pgbackrest 2.44
2. PostgreSQL version: PostgreSQL 15 or higher
3. Operating system/version: linux/ubuntu22.04
4. Did you install pgBackRest from source or from a package: package
5. Attached the following:
    - `pgbackrest.conf`  [postgresql.conf.zip](https://github.com/pgbackrest/pgbackrest/files/11961617/postgresql.conf.zip)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)  [pgbackrest.conf.zip](https://github.com/pgbackrest/pgbackrest/files/11961616/pgbackrest.conf.zip)
7. Describe the issue: On very large db (10+TB) and high transactional systems, when using remote WAL archive storage like S3 type, storage, network could not keep up or some configurations settings could be not be optimal and the  `pgbackrest info` command could not retrieve data about WAL archiving in fast enough or reliable manner. To monitor WAL archive delay from server to the remote storage information about the last WAL file archived by pgbackrest and oldest Postgres WAL file ready to archive could be used.  An example of monitoring pgBackRest archive delay from within PostgreSQL 15+ can get useful information: [pgsql-pgbackrest-archive_delay.sql.zip](https://github.com/pgbackrest/pgbackrest/files/11961604/pgsql-pgbackrest-archive_delay.sql.zip)

**Comment by dwsteele** [comment]
Not quite sure what you are asking for here. There are examples of monitoring (including in Postgres) here https://pgbackrest.org/user-guide.html#monitor.

Some S3 clones are very slow to return prefix lists, which in turn can make info slow. Not sure what we can do there except to recommend you use a faster S3 clone (or AWS, which generates these lists pretty quickly).

**Comment by covalenthq-rj** [comment]
In cases there is not much of an option to use faster S3 clones due to
status quo/etc, maybe it could be helpful to other users to add an example
into documentation of monitoring not relying on the info. In the posted
description of the issue #2110 is an example of a plpgsql stored function
doing that.

**Comment by dwsteele** [comment]
OK, I see. The link did not come through in my email, but I see it now on Github.

I didn't spend a lot of time looking at the code, but wouldn't `select last_archived_wal, last_archived_time from pg_stat_archiver` be better to get this information?

**Comment by covalenthq-rj** [comment]
The view pg_stat_archiver could help with awareness about the WAL archiving
delay, but there are relatively lots of valid scenarios where the WAL
file(s) were not archived/generated for longer period of time (low activity
on postgresql server, scheduled outage/maintenance, etc). In our case we
specifically looked into the gap/delay between  when was the WAL ready for
archiving and when the pgbackrest was able to push it on remote storage. In
one case we saw the gap was 8 hours and growing and it caused the
incremental/full backup to fail. Direct comparison between the last WAL
file archived by pgbackrest and the oldest Postgres WAL file ready to
archive could provide more clarity.

**Comment by pgstef** [comment]
Watching the `.ready` files is a good approach. But then it has to be compared to the latest archived.
Looking inside the repo (using repo-ls or info) to get the latest wal archived is the only way to be sure of what's inside the repo. 
As suggested by David, you could compare the `.ready` files to pg_stat_archiver.last_archived_wal, that would give a better approx than using the spool path (as you do in your example) imho. Using the spool path for this will only work with async archiving and might get confused in case of fail-over for example.

**Comment by covalenthq-rj** [comment]
The async archiving is the most interesting case probably from performance view. The WAL files archiving has most sense on the master/primary instance and it could be checked by something like  `select pg_is_in_recovery()`.  Work in progress example, relevant to ubuntu is attached: [pgsql-pgbackrest-async_archive_delay.sql.zip](https://github.com/pgbackrest/pgbackrest/files/12042950/pgsql-pgbackrest-async_archive_delay.sql.zip)

**Comment by dwsteele** [comment]
Closing this, but hopefully it will be useful to anyone looking for this type of monitoring.
