### ISSUE TITLE
2.46 - restore incremental - lz4 error: [-13] ERROR_frameType_unknown

### ISSUE THREAD

**Issue by fmbiete** [pgbackrest/pgbackrest#2112]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.46

2. PostgreSQL version: 15.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: backup was created from a RHEL9 server - backup standby, it's being restored to RHEL8 server

4. Did you install pgBackRest from source or from a package? source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) - attached config file of the source server (standby) where the backup was created: [pgbackrest_source_rhel9.txt](https://github.com/pgbackrest/pgbackrest/files/11979918/pgbackrest_source_rhel9.txt)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`) - not applicable for restore, but let me know if you need it
    - errors in the postgresql log file before or during the time you experienced the issue - not applicable
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`) [error_log_detail.txt](https://github.com/pgbackrest/pgbackrest/files/11979915/error_log_detail.txt)

7. Describe the issue:
I'm trying to restore a backup created in a server into another. Server have the same PostgreSQL version, but different RHEL version (I don't think this is the cause, because it worked with <2.46 versions)
The backup was created using bundle, block level incrementals, compression lz4, standby (source is a multi-node cluster). We have daily backups (6 incrementals, 1 full)

When I'm trying to restore from an incremental (any incremental) I get this error:
```
ERROR: [029]: raised from local-4 protocol: lz4 error: [-13] ERROR_frameType_unknown
       [FormatError] on retry after 300ms: [same message]
       [FormatError] on retry after 15309ms: [same message]
2023-07-07 03:22:13.337 P00   INFO: restore command end: aborted with exception [029
```

When I restore from the full backups it works
```
2023-07-07 03:37:00.390 P00 DETAIL: sync path '/postgresql/data0/data/pg_xact'
2023-07-07 03:37:00.390 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
2023-07-07 03:37:00.390 P00 DETAIL: sync path '/postgresql/data0/data/global'
2023-07-07 03:37:00.391 P00   INFO: restore size = 1.4GB, file total = 2089
2023-07-07 03:37:00.391 P00   INFO: restore command end: completed successfully (4345ms)
```

**Comment by dwsteele** [comment]
Hmm, that's certainly not good. I think things to try in order would be:

1) Try to restore on RHEL9 so the same version of lz4 is used. The release notes for lz4 the last few years include fixes for a variety of corruption bugs. Unlikely that you would have hit one, but we should rule that out.

2) Try with a different compression format, e.g. something very stable like gz.

3) If neither of those work then we'll want to have a look at more detailed logs (probably good to do this in any case since it may take a while to try 1 and 2). To get the log detail you'll need to add `--log-level-file=debug --log-subprocess` to the restore. When the error occurs look for the log file `[stanza]-restore-local-XXX.log` where XXX is the local process where the error occurred (004 in the error you posted). Send at least the last 10,000 lines of that log.

Depending on what we find we may need to get more, but this should get us started. Thanks!

**Comment by dwsteele** [comment]
> I tried the "verify" command, but it doesn't seem to work correctly with bundle/block level (I got a bunch of missing file errors; it looks for .lz4 files, but there are .pgbi files)

That's definitely an oversight in verify, which has been fixed here in #2120. 

> restore command begin 2.46: --delta --exec-id=468389-263b29d7 --lock-path=/var/lib/pgsql/lock --log-level-console=detail --log-level-file=debug --log-path=/var/lib/pgsql/log --log-subprocess --pg1-path=/postgresql/data0/data --process-max=8 --repo1-path=/pgbackup/primary_server --repo1-type=cifs --set=20230630-000004F_20230705-031503I --stanza=primary_server --target-action=promote --type=immediate

I noticed you are using CIFS. We have seen instances of corruption on CIFS where the sync fails but success is returned. In these cases we have seen messages in syslog. Anything like that where the backups were run?

Usually verify would help with this but of course that won't work here.

**Comment by dwsteele** [comment]
Another thing you could try is to run verify and just look at the final summary for checksum failures (or filter out the missing files). I can see from the logs that the problematic file is inside a bundle so verify should be able to check it:
```
2023-07-11 04:32:20.194 P00  DEBUG:     storage/storage::storageNewRead: (this: {type: cifs, path: /pgbackup/primary_server, write: false}, fileExp: {"<REPO:BACKUP>/20230630-000004F/bundle/4"}, param.ignoreMissing: false, param.compressible: false, param.offset: 1732633, param.limit: {253})
2023-07-11 04:32:20.194 P00  DEBUG:     storage/storage::storageNewRead: => {type: posix, name: /pgbackup/primary_server/backup/primary_server/20230630-000004F/bundle/4, ignoreMissing: false}
```
Furthermore, the file does not appear to be a block incremental. If it was there would be a map read (maps are not compressed) followed by block reads (which are compressed).

Also, this file is coming from the full backup -- not one of the incrementals. My guess is it got "fixed" by the file being updated and included in an incremental.

**Comment by fmbiete** [comment]
Is it from the full backup? That's strange, because I can restore that full backup without triggering the error, that was my original work around, restore that full and then pitr until the end of the incremental I wanted.

I don't see checksum errors in the verify, only missing files (thank you for fixing that). 
[verify.txt](https://github.com/pgbackrest/pgbackrest/files/12026144/verify.txt)

I should change cifs to posix, we are using NAS, but originally we wanted to make sure we don't use any type of links by mistake. I don't see any error in those servers related to that unit anyway, and the unit is mounted as NFS not CIFS

**Comment by dwsteele** [comment]
> Is it from the full backup?

That's what it looks like. It could be that the offset got munged somewhere along the way. To check that we would need the `backup.manifest` file for the `20230630-000004F` and `20230630-000004F_20230705-031503I` backups.

> I should change cifs to posix

Specifying CIFS on a Posix system is dangerous because CIFS does not require/allow directory syncs (so we skip them). Probably not what is going on here but it can lead to data loss.

**Comment by fmbiete** [comment]
[20230630-000004F_20230705-031503I_backup.manifest.gz](https://github.com/pgbackrest/pgbackrest/files/12027789/20230630-000004F_20230705-031503I_backup.manifest.gz)
[20230630-000004F_backup.manifest.gz](https://github.com/pgbackrest/pgbackrest/files/12027791/20230630-000004F_backup.manifest.gz)

**Comment by dwsteele** [comment]
It looks like what is happening is the block incremental info is being lost for `base/16529/16532_fsm` so the incremental is trying to fetch it from the full backup as a normal stored file. That obviously doesn't work well.

The only way I can see in the code that this could happen is if the file got smaller at some point (which seems very unlikely). Just to verify this is not happening, can we also get the following manifests: `20230630-000004F_20230701-000004I`, `20230630-000004F_20230702-000004I`, `20230630-000004F_20230703-000004I`, `20230630-000004F_20230704-000004I`?

Thanks!

**Comment by dwsteele** [comment]
Also, whatever backups logs you have would be helpful, i.e. `primary_server-backup.log*`. Thanks!

**Comment by fmbiete** [comment]
One thing that could be important; we are using backup standby. The backup is always executed in the backup server
Until 20230703 the primary role was in the "secondary_server", so the backups for 20230630-20230703 were created in "primary_server"

20230704, 20230705 backups were created in "secondary_server" (because the primary role moved to "primary_server").

pgbackrest detected this timeline change
```
2023-07-04 00:00:06.202 P00   WARN: a timeline switch has occurred since the 20230630-000004F_20230703-000004I backup, enabling delta checksum
                                    HINT: this is normal after restoring from backup or promoting a standby
```
if I'm not wrong the block incremental info is stored in the backup stanza. The backup stanza is the same NFS share for all the servers in the cluster. 


[20230630-000004F_20230701-000004I_backup.manifest.gz](https://github.com/pgbackrest/pgbackrest/files/12037809/20230630-000004F_20230701-000004I_backup.manifest.gz)
[20230630-000004F_20230702-000004I_backup.manifest.gz](https://github.com/pgbackrest/pgbackrest/files/12037811/20230630-000004F_20230702-000004I_backup.manifest.gz)
[20230630-000004F_20230703-000004I_backup.manifest.gz](https://github.com/pgbackrest/pgbackrest/files/12037812/20230630-000004F_20230703-000004I_backup.manifest.gz)
[20230630-000004F_20230704-000004I_backup.manifest.gz](https://github.com/pgbackrest/pgbackrest/files/12037813/20230630-000004F_20230704-000004I_backup.manifest.gz)
[primary_server-backup.log_20230630.gz](https://github.com/pgbackrest/pgbackrest/files/12037814/primary_server-backup.log_20230630.gz)
[primary_server-backup.log_20230701.gz](https://github.com/pgbackrest/pgbackrest/files/12037815/primary_server-backup.log_20230701.gz)
[primary_server-backup.log_20230702.gz](https://github.com/pgbackrest/pgbackrest/files/12037817/primary_server-backup.log_20230702.gz)
[primary_server-backup.log_20230703.gz](https://github.com/pgbackrest/pgbackrest/files/12037818/primary_server-backup.log_20230703.gz)
[primary_server-backup.log_20230704.gz](https://github.com/pgbackrest/pgbackrest/files/12037819/primary_server-backup.log_20230704.gz)
[primary_server-backup.log_20230705.gz](https://github.com/pgbackrest/pgbackrest/files/12037820/primary_server-backup.log_20230705.gz)
[primary_server-backup.log_20230706.gz](https://github.com/pgbackrest/pgbackrest/files/12037821/primary_server-backup.log_20230706.gz)

**Comment by dwsteele** [comment]
Thank you for the additional logs and manifests. I was able to figure out what was going on and fixed it in #2123. You were right, the fail over was a factor.

The sequence of events to hit this bug was fairly convoluted in this case (see PR for more info) but there are definitely simpler (but still unlikely) ways to hit the bug.

**Comment by fmbiete** [comment]
Awesome, thank you so much!

**Comment by dwsteele** [comment]
Closing this since there are PRs for both issues raised here.
