### ISSUE TITLE
pgbackrest full backup is underutilizing network bandwidth

### ISSUE THREAD

**Issue by thecatontheflat** [pgbackrest/pgbackrest#2114]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.46

2. PostgreSQL version: 15.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 22.04

4. Did you install pgBackRest from source or from a package? `apt install pgbackrest`

7. Describe the issue:

I am running a full backup and it looks like pgbackrest is underutilizing network bandwidth.

I have tried running it against 3 different repo setups:
- Azure (public network)
- self-hosted minio  (local network)
- sshfs mounted folder (local network)

In case of Azure, `atop` reported reaching only 1Gbps (while the server is on the 2Gbps public uplink).
In case of both local network repos (self-hosted minio and sshfs), according the `atop`, the bandwidth usage barely reached 700Mbps (while the server has 6Gbps private uplink).

My DB server spec:
AMD Ryzen 9 5900X - 12c/24t - 3.7 GHz/4.8 GHz
128 GB ECC 2666 MHz

Postgres data directory is installed on a ZFS

pgbackrest config for Azure

```
[global]
process-max=12
repo1-block=y
repo1-bundle=y
repo1-retention-full=1

repo1-path=/XXX
repo1-azure-account=XXX
repo1-azure-container=XXX
repo1-azure-key=XXX
repo1-type=azure

start-fast=y
compress-level=6
log-level-console=detail
```

pgbackrest config for self hosted minio
```
[global]
process-max=18
repo1-block=n
repo1-bundle=n
repo1-retention-full=1

repo1-type=s3
repo1-s3-endpoint=XXX
repo1-storage-port=9000
repo1-s3-uri-style=path
repo1-path=/XXX
repo1-s3-key=XXX
repo1-s3-key-secret=XXX
repo1-s3-bucket=backups
repo1-s3-region=eu-west-1
repo1-s3-verify-ssl=n

start-fast=y
compress-level=6
log-level-console=detail
```

pgbackrest config for sshfs mounted folder
```
[global]
process-max=18
repo1-block=n
repo1-bundle=n
repo1-retention-full=1

repo1-path=/XXX

start-fast=y
compress-level=6
log-level-console=detail
```

I have also tried removing `compress-level` just to see if it would fill the bandwidth, buit nothing changed.

Could you please help?

**Comment by thecatontheflat** [comment]
It seems to perform better as I increase `process-max` to some ridiculous number, like x5 of the server thread count (`process-max=124`). I read in the docs that it is recommended to set it to 25% of the CPUs (threads?) for the backup and to 100% of the CPUs (threads?) for restore. In my case even when set it to 500% of the CPU count, `htop` reports that the CPU load is barely reaching 50%:

<img width="993" alt="Screenshot 2023-07-09 at 14 33 34" src="https://github.com/pgbackrest/pgbackrest/assets/727581/d4e0e130-0380-4815-8a2e-acc328617e7f">


Did I misinterpret that docs and should simply try and tweak the `process-max` to an acceptable value performance-wise, disregarding its correspondence to the actual CPU cores count?

**Comment by dwsteele** [comment]
If you want to maximize network utilization you can disable compression `compress-type=none` or use a faster compression type, e.g. `compress-type=zstd`. The default `gzip` compression is fairly slow.

**Comment by dwsteele** [comment]
We don't recommend setting `process-max` too high for backups as it can have adverse effects on database performance. In your other issue you say backups are running in six hours and this seems pretty reasonable to me.

**Comment by thecatontheflat** [comment]
Thank you! I must have misunderstood the docs. I thought that `compress-level` and `compress-type` could be used instead of on another, e.g. `compress-level=1` equals to `compress-type=lz4`

I will experiment with both and will get back.

**Comment by thecatontheflat** [comment]
> If you want to maximize network utilization you can disable compression `compress-type=none` or use a faster compression type, e.g. `compress-type=zstd`. The default `gzip` compression is fairly slow.

Thanks! I must have misunderstood the docs. I thought that compress-level and compress-type could be used instead of one another, e.g. compress-level=1 equals to compress-type=lz4.

I will experiment with both and will get back.



> We don't recommend setting `process-max` too high for backups as it can have adverse effects on database performance. In your other issue you say backups are running in six hours and this seems pretty reasonable to me.

Understood. Regarding the `process-max`. It was just my attempt to experiment with different settings to see what's bottlenecking.
