### ISSUE TITLE
[Question] Is it possible to convert a diff backup into a full?

### ISSUE THREAD

**Issue by thecatontheflat** [pgbackrest/pgbackrest#2115]
Our DB cluster is 20TB (multiple Citus powered servers). 
A full backup on a single server takes about 6 hours to complete.

I was wondering if it's possible to convert a differential backup into a full one somehow, so we can save this time and bandwidth, when I saw this had been asked already in 2018 https://github.com/pgbackrest/pgbackrest/issues/644 and the corresponding card was created https://github.com/pgbackrest/pgbackrest/projects/2#card-17933730

Is there any chance it gets a higher priority in the Project board?

**Comment by dwsteele** [comment]
This feature has a fairly high priority for us but we don't know when we'll be able to start working on it.
