### ISSUE TITLE
Impossible to provide an identity file (private key) for SSH command

### ISSUE THREAD

**Issue by pgiraud** [pgbackrest/pgbackrest#2116]
pgBackRest version: 2.46

I couldn't find a way to provide the identity (private key) to use for a public key authentication.

I don't think there is a dedicated option for this. I also tried to change the "--cmd-ssh" option to "/usr/bin/ssh -i /path/to/id_rsa", but I get an error like:

```
RROR: [102]: remote-0 process on 'the-host' terminated unexpectedly [102]: unable to execute '/usr/bin/ssh -i /path/to/id_rsa': [2] No such file or directory
```

By the way, this also happens with a simple "/usr/bin/ssh -q".

I have a rather weird case (in a functional testing environment) where the SSH keys are not installed in `~/.ssh/` and this would be very useful. Is there a workaround?

Related to https://github.com/pgbackrest/pgbackrest/issues/867

**Comment by dwsteele** [comment]
This won't work since we don't parse it into separate params:
```
/usr/bin/ssh -i /path/to/id_rsa
```
You might be able to create a shell wrapper to pass the parameters you need.

SSH support is not deprecated yet but going forward we are focused primarily on TLS support. I'm not sure how excited I am about adding options to SSH for what is very much an edge case.

**Comment by pgiraud** [comment]
> This won't work since we don't parse it into separate params:
> 
> ```
> /usr/bin/ssh -i /path/to/id_rsa
> ```
> 
> You might be able to create a shell wrapper to pass the parameters you need.

This looks like a valid workaround. Thanks.

> 
> SSH support is not deprecated yet but going forward we are focused primarily on TLS support. I'm not sure how excited I am about adding options to SSH for what is very much an edge case.

I fully understand the lack of interest for this addition. We also try to educate our customers to prefer TLS over SSH.
