### ISSUE TITLE
Question - Restore - Target format

### ISSUE THREAD

**Issue by robinportigliatti** [pgbackrest/pgbackrest#2117]
Hello,

In France we operate like this:
Standard Time: UTC +1 Central European Time (CET)
Daylight Saving Time: UTC +2 Central European Summer Time (CEST)

Example:

If we tell it target='2023-06-15 21:00:01', it will restore in UTC time, which is 2 hours less in summer, and 1 hour less in winter.
If we tell it target='2023-06-15 21:00:01+01' and it's summer, it will restore with 1 hour less.
If we tell it target='2023-06-15 21:00:01 CEST' and it's winter, it will restore with 1 hour less.

In PostgreSQL we can execute `SELECT '2023-06-15 21:00:01 Europe/Paris'::timestamp with time zone at time zone 'UTC';`

But with pgBackrest we can't:

```
2023-07-10 15:01:50.732 P00   INFO: restore command begin 2.46: [anonymized] --target="2023-07-10 14:00:00 Europe/Paris" --target-action=promote --type=time
ERROR: [029]: automatic backup set selection cannot be performed with provided time '2023-07-10 14:00:00 Europe/Paris'
       HINT: time format must be YYYY-MM-DD HH:MM:SS with optional msec and optional timezone (+/- HH or HHMM or HH:MM) - if timezone is omitted, local time is assumed (for UTC use +00)
```

In my restore script I do not wish to specify CET or CEST time. Is there a workaround to not specify CET or CEST ?

Robin,

**Comment by pgstef** [comment]
Hi,

> In my restore script I do not wish to specify CET or CEST time. Is there a workaround to not specify CET or CEST ?

The auto-select can't work with full time zone names. The HINT clearly indicates that the [timezone should be a numeric offset from UTC](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/restore/restore.c#L97) (which is also PG recovery_target_time preferred style).

If you don't want to pass the offset, the easiest workarounds are to use the system timezone or pick the backup set you want to restore. BTW, the timezone offset has been added to the info command output [lately](https://github.com/pgbackrest/pgbackrest/commit/9efd5cd0bb40c5dc2fcac2e21c9b62e554b94db6).

Regards

**Comment by robinportigliatti** [comment]
Thank you
