### ISSUE TITLE
pgbackrest hangs when doing a full backup

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#212]
Using the latest version, v 1.02 on debian wheezy.  I think this is reproduceable by creating the same error for the dbport line in pgbackrest.conf as explained below.  Even after fixing the typo in this conf file, archiving is still broken for model instance.

This is the command and the last few lines of output that shows it hanging on the wait for all WAL segments to archive:
`sudo -u postgres pgbackrest --stanza=demo --type=full --log-level-console=info backup

2016-06-24 08:35:36.217 T03   INFO: backup file /pgdata/demo/base/1/11887 (0B)
2016-06-24 08:35:36.658 T00   INFO: backup file /pgdata/demo/global/pg_control (8KB) checksum 2cab5c49f4aaacf8db852cc37a07acfcd6d4a809
2016-06-24 08:35:36.661 T00   INFO: full backup size = 25.7MB
2016-06-24 08:35:36.661 T00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
 execute exclusive pg_stop_backup() and wait for all WAL segments to archive`

I have another stanza on this same server, model.  The pg log file shows that the pgbackrest archive_command is failing for this other instance.  I think it is because I had a typo for the pgbackrest.conf port for this other stanza, model.  Notice the letter "i" on the db-port line. 
[model]
db-path=/pgdata/lenderx2
db-port=5433     i

You will see this error in the pg log file along with the archiving errors for this other stanza/cluster instance, model.  Here are some lines from pg log file:
2016-06-24 08:19:24 CDT [29448-2] DETAIL: The failed archive command was: pgbackrest --stanza=model archive-push pg_xlog/000000010000000000000001 ERROR [107]: '5433 i' is not valid for 'db-port' option 
2016-06-24 08:19:25 CDT [29448-3] LOG: archive command failed with exit code 107 

model uses port 5433, demo uses port 5438.

In sum, it appears that if you have multiple stanzas on the same box and one of those stanzas has an archiving problem, it will affect the backups for all other stanzas running on that same box.

Here are my 2 stanzas:
`[model]
db-path=/pgdata/lenderx2
db-port=5433

[demo]
db-path=/pgdata/demo
db-port=5438`

**Comment by sfrost** [comment]
Are you sure that archiving for the demo stanza is correctly working?

Full configs for everything, along with appropriate log information from both instances, would be helpful for debugging.

**Comment by MichaelDBA** [comment]
Not a bug after all.  I had copied the same archive_command string from one instance to the other, so both were pointing to the same stanza: model.

Once I fixed the archive_command, the backup worked as expected.

**Comment by dwsteele** [comment]
OK, good - I was honestly not sure how this could be happening.
