### ISSUE TITLE
Very low transfer speed to SFTP repo, but raw SFTP works fine

### ISSUE THREAD

**Issue by delavei** [pgbackrest/pgbackrest#2121]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.46

2. PostgreSQL version: 15.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Docker containers using Debian 12.0 (bookworm), host running Linux 5.15.0-75
SFTP server container is using OpenSSH_9.2p1 Debian-2, OpenSSL 3.0.9

4. Did you install pgBackRest from source or from a package? apt install pgbackrest

5. Please attach the following as applicable:
    - `pgbackrest.conf`:
[stanza]
pg1-path=/var/lib/pgsql/data

[global]
repo1-cipher-pass=xxxxxx
repo1-cipher-type=aes-256-cbc
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2

repo2-cipher-pass=xxxxxxx
repo2-cipher-type=aes-256-cbc
repo2-path=/home/pgbackrest/data
repo2-sftp-host-key-hash-type=sha256
repo2-sftp-private-key-file=/var/lib/postgresql/.ssh/id_ed25519
repo2-sftp-public-key-file=/var/lib/postgresql/.ssh/id_ed25519.pub
repo2-sftp-host=database_backup_repo
repo2-sftp-host-user=pgbackrest
repo2-type=sftp
repo2-retention-full=2

compress-type=gz
compress-level=6

[global:archive-push]
compress-level=3

7. Describe the issue:
I have two docker containers, one running PostgreSQL with pgBackRest installed and the other one running OpenSSH server with internal sftp. 
When I try to run full backup to local repo, it takes around 13 seconds (log with timestamps for files in detailed output attached). 
When I run the same backup to remote SFTP repo though running on the same host, it takes around 16 minutes (another detailed log with timestamps for files attached). Backup compressed size is only around 28 MB. When I tried to copy raw Postgres data folder (which is around 260 MB), through SFTP connection (command "put -r var/lib/pgsql/data/") from one container to another it took around 6 seconds.
What I noticed in detailed log when backing up to sftp repo was, that first files took around a second to transfer. Their raw size was around 25 MB so I guess after compression it might have been around 2-3MB. So from the beginning the transfer was around 2MB/s which is awfully slow when both containers run on the same host, but it corresponds with what my monitoring solution was reporting as network traffic. However as the backup progressed, I noticed that only roughly 2-3 files are processed per second, even if their size was 16KB (or even lower to 0B). Which would amount for something around 50 KB/s transfer speed. Also during the whole process none of the resources were maxed out, monitoring reported CPU load below 1% and 6GB of free memory.
In config i purposefully didn't specify process-max, as I wanted to use default value of 1. (weirdly, container launched 3 processes for SFTP, but never mind). This was because the original raw sftp transfer also used only one sftp process and reached 40-50MB/s., so I wanted to have relevant comparison.
In addition, backup to the slow SFTP repo failed (as is written in the corresponding log in the end). When I tried to increase number of processes with adding process-max=16 
[pgbackrest-local_repo_detail.log](https://github.com/pgbackrest/pgbackrest/files/12031098/pgbackrest-local_repo_detail.log)
[pgbackrest-remote_sftp_repo_detail.log](https://github.com/pgbackrest/pgbackrest/files/12031100/pgbackrest-remote_sftp_repo_detail.log)
[pgbackrest-remote_sftp_x16_repo_detail.log](https://github.com/pgbackrest/pgbackrest/files/12031101/pgbackrest-remote_sftp_x16_repo_detail.log)
(container launched 18 processes), backup took roughly 27 seconds (log attached) and completed successfully.
Also I add that I do not use any resource throttling in docker, everything is default, which means no resource limits on host.

What is going on? What have I misconfigured? Or is this correct behaviour? Why is such a huge difference between raw SFTP transfer and SFTP transfer in pgBackRest?

**Comment by sfrost** [comment]
This has been addressed in 2.47.  If you have further issues with sftp speed please let us know.
