### ISSUE TITLE
Pgbackrest backup is failed after enabling timescaledb extension in postgresql 15

### ISSUE THREAD

**Issue by Tekchanddagar** [pgbackrest/pgbackrest#2122]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.46

2. PostgreSQL version: 15

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 22.04

4. Did you install pgBackRest from source or from a package? Source

5. Describe the issue: We are using postgresql 15 and pgbackrest is working fine with it. 

But when we are enabling the `timescaledb extension` then pgbackrest backup is failed. We used below doc to install and configure timescaledb extension:

[https://docs.timescale.com/self-hosted/latest/install/installation-linux/](url)

And enable the extension and used in `postgresql.conf` file
```
shared_preload_libraries = 'timescaledb'
```
**We are getting below error:**

```
2023-07-13 07:59:48.623 P00   INFO: backup command begin 2.46: --compress-level-network=3 --compress-type=zst --exec-id=597783-58f062bd --log-level-console=detail --log-level-file=info --pg1-path=/var/lib/postgresql/15/main --pg1-user=pgback --pg-version-force=15 --process-max=2 --repo1-path=/audit-db --repo1-retention-diff=3 --repo1-retention-full=5 --repo1-s3-bucket=abc --repo1-s3-endpoint=s3.abc.amazonaws.com --repo1-s3-key-type=auto --repo1-s3-region=abc --repo1-type=s3 --stanza=xyz --start-fast --type=full
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
2023-07-13 07:59:49.353 P00 DETAIL: statistics: {"http.client":{"total":2},"http.close":{"total":3},"http.request":{"total":7},"http.session":{"total":4},"socket.client":{"total":2},"socket.session":{"total":4},"tls.client":{"total":1},"tls.session":{"total":1}}
2023-07-13 07:59:49.353 P00   INFO: backup command end: aborted with exception [056]
```
But when we disable the below line from `postgresql.conf` file and rsetart the `patroni service` then backup is working fine
```
#shared_preload_libraries = 'timescaledb'
```
So its seems pgbackrest is not working with postgresql-15 after enabling the `timescaledb extension` and when we use it `postgresql.conf` file with `shared_preload_libraries`

Can you please help us?

Thank You

**Comment by pgstef** [comment]
Hi,

I've just tested and pgBackRest seems to work pretty fine with the timescale extension:
```sql
tsdb=# \dx
                                               List of installed extensions
    Name     | Version |   Schema   |                                     Description                                      
-------------+---------+------------+--------------------------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.11.1  | public     | Enables scalable inserts and complex queries for time-series data (Apache 2 Edition)
(2 rows)
```
```bash
$ pgbackrest --stanza=demo backup
2023-07-13 08:30:55.224 P00   INFO: backup command begin 2.46: ...
...
2023-07-13 08:31:02.028 P00   INFO: backup command end: completed successfully (6804ms)
```

Imho, the problem is not the extension itself but more your current architecture which you're not describing. 
You're mentioning `restart the patroni service`, and the ERROR is `unable to find primary cluster` while you only have pg1 options defined.

Do you have multiple PG hosts running with Patroni? Probably you should have a look at the `patronictl -c patroni.yml topology` output to figure out if the node where you try to run the backup is actually the primary or not.

Kind Regards

**Comment by dwsteele** [comment]
It might be that some Timescale error is preventing the primary from starting, so all pgBackRest can find for the backup is a standby.

**Comment by Tekchanddagar** [comment]
@pgstef , Thank You for quick response.
I raised this question on the basis of my collegue findings. But now i did all the testing and found Postgresql 15+Patroni+Pgbackrest+Timescaledb extestion is working fine.

He created a user `pgback` and was using this user for pgbackrest backup but was not giving right permission to this user. Below permission are required for `pgback` user:

```
grant pg_read_all_settings to pgback;
grant execute on function pg_backup_start to pgback;
grant execute on function pg_backup_stop to pgback;
grant execute on function pg_create_restore_point to pgback;
grant execute on function pg_switch_wal to pgback;
```
Thank you and sorry from my side to create an issue without checking the issue from end to end.
Will take care in future for sure.

Thanks.
