### ISSUE TITLE
pgBackRest not compatible with EDB Advanced Server 12

### ISSUE THREAD

**Issue by Aman1si14** [pgbackrest/pgbackrest#2129]
PostgreSQL : EDB Advanced Server 12.15.19
pgBackRest 2.43
OS: RHEL 9

Build a binary using rhel9 but getting below issue 

```
pg_basebackup: error: incompatible server version 12.15.19
pg_basebackup: removing data directory "/data/enterprisedb/12"
```

**Comment by pgstef** [comment]
Hi,

You're pasting an error message about `pg_basebackup` which isn't related to pgBackRest.

I didn't specifically tried pgBackRest 2.43, but at least the latest release (2.47) is working with EPAS 12:

```bash
$ psql -d postgres -h /var/run/edb/as12 -c "show server_version"
 server_version 
----------------
 12.15.19
(1 row)

$ pgbackrest version
pgBackRest 2.47

$ pgbackrest info   
stanza: demo
    status: ok
    cipher: aes-256-cbc

    db (current)
        wal archive min/max (12): 000000010000000000000006/00000001000000000000000F

        full backup: 20230727-072756F
            timestamp start/stop: 2023-07-27 07:27:56+00 / 2023-07-27 07:28:01+00
            wal start/stop: 000000010000000000000006 / 000000010000000000000007
            database size: 49.6MB, database backup size: 49.6MB
            repo1: backup set size: 7.9MB, backup size: 7.9MB
```

If you have an issue with `pg_basebackup`, it may be related to the RHEL9 packages. Given EPAS is a commercial product, you might ask your support directly.

Kind Regards

**Comment by Aman1si14** [comment]
@pgstef. My current hypothesis is that this is due to the fact that we have two versions of libpq installed on the system, one used by our from-source pgbackrest build, and one because EDB provides one itself . However , I have deleted the files from edb path so that it can use the system one . But even though it is giving me the above err .

**Comment by pgstef** [comment]
> But even though it is giving me the above error . Can you suggest something here ?

As I mentioned already, the error you pasted is about `pg_basebackup` (so Postgres binaries), not related to pgBackRest itself.

You should get your EPAS installation fixed and, since this is a commercial software, use their support in this area if needed. And use the binaries provided with EPAS for a better compatibility.

libpq should indeed point to those binaries:

```bash
$ ldd /usr/bin/pgbackrest |grep libpq
  libpq.so.5 => /usr/edb/as12/lib/libpq.so.5
```

[Installing](https://www.enterprisedb.com/docs/supported-open-source/pgbackrest/02-installation/) the pgBackRest packages from the PGDG repositories on top of the EPAS 12 packages just work fine. I quickly tested it this morning on centos7 without any issue.

Also, compiling pgBackRest yourself can be pretty painful and we'd defenitely recommend to use the packages provided by the community (and also the latest pgBackRest release, given you might need the `pg-version` option once you'll upgrade EPAS to a newer release).

If you really want to compile pgBackRest yourself, you'll need to make some research by yourself. I know I tried it a while ago and made it work pretty easily by using the EPAS packages rather than the PostgreSQL one and adding these flags before configure/make:
```
export CPPFLAGS='-I /usr/edb/as12/include'
export PATH=/usr/edb/as12/bin/:$PATH
export LDFLAGS='-L/usr/edb/as12/lib'
```

I'm not sure we can do more over here to help you fix how you installed your system.
Kind Regards

**Comment by Aman1si14** [comment]
@pgstef When I tried to use the edb path , it is failing with the below error in rhel 9 :

`/usr/local/bin/pgbackrest: /usr/edb/as12/lib/libpq.so.5: no version information available (required by /usr/local/bin/pgbackrest)`

**Comment by dwsteele** [comment]
Again, please check with EDB support if you are having trouble building against their product. The best thing to do is use the packages from yum.postgresql.org, but if you insist on building from source you'll need support from EDB to get that done.

**Comment by pgstef** [comment]
Honestly, building against EPAS sources isn't that complicated.

I just tried on Rocky 9 with these simple steps:

* Install EPAS 12

```bash
dnf install -y epel-release
dnf config-manager --set-enabled crb
dnf -y install edb-as12-server
PGSETUP_INITDB_OPTIONS="-E UTF-8 --data-checksums" /usr/edb/as12/bin/edb-as-12-setup initdb
systemctl enable edb-as-12
systemctl start edb-as-12
```

* Install build requirements

```bash
dnf install -y make gcc openssl-devel libxml2-devel lz4-devel libzstd-devel bzip2-devel libyaml-devel libssh2-devel
dnf install -y edb-as12-server-devel
```

* Download latest sources and build

```bash
mkdir -p /build
wget -q -O - \
	https://github.com/pgbackrest/pgbackrest/archive/release/2.47.tar.gz | \
	tar zx -C /build

export CPPFLAGS='-I /usr/edb/as12/include'
export PATH=/usr/edb/as12/bin/:$PATH
export LDFLAGS='-L/usr/edb/as12/lib'
cd /build/pgbackrest-release-2.47/src && ./configure && make
cp pgbackrest /usr/bin/
chmod 755 /usr/bin/pgbackrest
```

* Setup pgBackRest configuration

```bash
mkdir -p -m 770 /var/log/pgbackrest
chown -R enterprisedb: /var/log/pgbackrest
mkdir -p /etc/pgbackrest
touch /etc/pgbackrest/pgbackrest.conf
chmod 640 /etc/pgbackrest/pgbackrest.conf
chown enterprisedb: /etc/pgbackrest/pgbackrest.conf
```

```ini
# /etc/pgbackrest/pgbackrest.conf
[global]
repo1-path=/var/lib/edb/as12/backups/
repo1-retention-full=2
start-fast=y
log-level-console=info
log-level-file=debug
delta=y
process-max=2

[demo]
pg1-path=/var/lib/edb/as12/data
pg1-user=enterprisedb
pg1-port=5444 
```

* Init pgBackRest

```bash
$ pgbackrest stanza-create --stanza=demo
P00   INFO: stanza-create command begin 2.47: ...
P00   INFO: stanza-create for stanza 'demo' on repo1
P00   INFO: stanza-create command end: completed successfully

$ pgbackrest check --stanza=demo
P00   INFO: check command begin 2.47: ...
P00   INFO: check repo1 configuration (primary)
P00   INFO: check repo1 archive for WAL (primary)
P00   INFO: WAL segment 000000010000000000000002 successfully archived to ...
P00   INFO: check command end: completed successfully
```

Everything went just fine with the flags I posted earlier. There's nothing wrong with pgBackRest itself.
It's really a system configuration problem but we indeed probably won't be able to help more than that.
I also +1 on using the packages provided in the PGDG repositories. That's also what is recommended in [EDB docs](https://www.enterprisedb.com/docs/supported-open-source/pgbackrest/02-installation/).
