### ISSUE TITLE
Unable to Restore Backup with pgBackRest on a Docker Container with PostgreSQL Service

### ISSUE THREAD

**Issue by zN3utr4l** [pgbackrest/pgbackrest#2134]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: `2.47`

2. PostgreSQL version: `14`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
 `Docker timescale/timescaledb:2.11.1-pg14 Container`

5. Did you install pgBackRest from source or from a package? 

`Source`
```
FROM alpine:latest as pgbackrest-stage

ARG BACKREST_VERSION="2.47"
ARG BACKREST_DOWNLOAD_URL="https://github.com/pgbackrest/pgbackrest/archive/release"

RUN apk --update add \
    build-base \
    wget \
    make \
    gcc \
    libpq-dev \
    openssl-dev \
    libxml2-dev \
    pkgconfig \
    lz4-dev \
    zstd-dev \
    bzip2-dev \
    zlib-dev \
    yaml-dev \
    && wget ${BACKREST_DOWNLOAD_URL}/${BACKREST_VERSION}.tar.gz -O /tmp/pgbackrest-${BACKREST_VERSION}.tar.gz \
    && mkdir -p /tmp/pgbackrest-release \
    && tar -xzf /tmp/pgbackrest-${BACKREST_VERSION}.tar.gz --strip-components=1 -C /tmp/pgbackrest-release \
    && cd /tmp/pgbackrest-release/src \
    && ./configure \
    && make
```

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    
    ```
    # https://pgbackrest.org/configuration.html

    [global]
    repo1-bundle=y
    repo1-cipher-pass=bla bla
    repo1-cipher-type=aes-256-cbc
    repo1-path=/var/lib/pgbackrest
    # https://github.com/pgbackrest/pgbackrest/issues/2087
    # collection hypertables retention + 20 days
    repo1-retention-full=568
    repo1-retention-full-type=time
    log-path=/var/lib/pgbackrest/log
    log-level-console=info
    log-level-file=debug
    log-subprocess=y
    # start-fast=y 
    compress-type=bz2
    # https://github.com/pgbackrest/pgbackrest/issues/386#issuecomment-319393163 for restore 
    archive-copy=y
    archive-async=y
    archive-push-queue-max=1024MB
    spool-path=/var/spool/pgbackrest
    archive-get-queue-max=256MB
    archive-missing-retry=y
    
    [test]
    pg1-path=/var/lib/postgresql/data
    
    [global:archive-get]
    process-max=2
    
    [global:archive-push]
    compress-level=9
    compress-type=bz2
    process-max=3
    ```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
  
    ```
    listen_addresses = '172.20.0.5, 127.0.0.1, localhost'
    restore_command = 'pgbackrest --stanza=test archive-get %f "%p"'
    archive_command = 'pgbackrest --stanza=test archive-push %p'
    archive_mode = on
    wal_level = replica
    max_wal_senders = 20
    ```

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
```
    2023-07-31 11:36:07.055 P00   INFO: restore command begin 2.46: --delta --exec-id=37-3a8862f7 --log-level-console=info --log-level-file=debug --log-path=/var/lib/pgbackrest/log --log-subprocess --pg1-path=/var/lib/postgresql/data --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest --spool-path=/var/spool/pgbackrest --stanza=test
ERROR: [038]: unable to restore while PostgreSQL is running
       HINT: presence of 'postmaster.pid' in '/var/lib/postgresql/data' indicates PostgreSQL is running.
       HINT: remove 'postmaster.pid' only if PostgreSQL is not running.
2023-07-31 11:36:07.055 P00   INFO: restore command end: aborted with exception [038]
```

7. Describe the issue:

I'm trying to restore a backup previously taken with pgBackRest on a Docker container that contains an image generated by PostgreSQL. However, I can't stop the PostgreSQL service inside the container using the `pg_ctl -D "$PGDATA" -w stop` command as it shuts down the entire container, including pgBackRest installed on top of it.

backup command: `pgbackrest --stanza=test --type=full backup`

1. Is there a way to restore a backup with pgBackRest on a PostgreSQL database running on a Docker container without stopping the PostgreSQL service?
2. Are there any other methods or commands I can try to perform the backup restore without having to shut down the container?

I have inserted the `archive-copy=y` option because, as stated in this comment (https://github.com/pgbackrest/pgbackrest/issues/386#issuecomment-319393163), I need to copy the backup to another PC and insert it into another container. Can you confirm that this is the right method?

Thank you in advance.

**Comment by pgstef** [comment]
Hi,

> 1. Is there a way to restore a backup with pgBackRest on a PostgreSQL database running on a Docker container without stopping the PostgreSQL service?

Unfortunately no. But it's no a pgBackRest problem. It's a PG behavior. You need to stop the cluster before trying to perform a recovery.

>     2. Are there any other methods or commands I can try to perform the backup restore without having to shut down the container?

Seems to be a question for your container provider given it will highly depend on the entry point. This is more a generic "how to perform a PG recovery in a container" than simply using pgBackRest. I haven't tested it on an official postgres docker image either tbh, that's an interesting question.

> I have inserted the `archive-copy=y` option because, as stated in this comment ([#386 (comment)](https://github.com/pgbackrest/pgbackrest/issues/386#issuecomment-319393163)), I need to copy the backup to another PC and insert it into another container. Can you confirm that this is the right method?

If you know how to restore it manually, yes. But pgBackRest won't be able to restore it for you. The easiest way is to share the repo (in RO mode) where you need to restore a backup. Keeping a backup locally on the same server/disks/container than your database is dangerous anyway so you'll need a way to export that.

**Comment by pgstef** [comment]
> If I have 2 distant postgres instances, not on the same network, can't I copy the backup folder from one instance to the other in order to perform a restore on another pc?

As written, if you restore it manually, yes. But not with pgBackRest itself who needs an initialized repo with an up-to-date backup.info file to operate.

**Comment by zN3utr4l** [comment]
what do you mean by restore manually?
not pgbackrest --stanza=bla restore?

**Comment by pgstef** [comment]
> what do you mean by restore manually? not pgbackrest --stanza=bla restore?

You won't be able to use the `pgbackrest` command for the reasons already written previously.
Manually means extract and copy the files and configuration yourself, without using pgBackRest.

That's pretty clear in the comment you linked:

> This directory can be restored directly on a dev server and backrest does not even need to be installed since the backup directory is a consistent cluster (even tablespace links are rewritten). You'll need to do a recursive gunzip if the backup is compressed. I wouldn't recommend this for production usage but it works great for dev/staging environments.

**Comment by zN3utr4l** [comment]
So I just need to copy from the folder `backup/STANZA/BACKUP-NAME/pg_data/pg_wal` the files, unzipped, to the pg_wal folder of the new postgres instance?

**Comment by pgstef** [comment]
You have `compress-type=bz2` + `archive-copy=y`. So all the WAL archives needed for the backup consistency should be stored in the backup directory directly.

You'll need to copy the entire backup set and then recursively extract the compressed files from that backup set.

We don't have a procedure for that since you're going outside pgBackRest repository. You'll have to experiment that yourself but it shouldn't be that complicated given David's comment.

**Comment by zN3utr4l** [comment]
Instead if I had a net link between the 2 postgres services is it possible or is pgbackrest specialized in backup/restore of the same service?

**Comment by pgstef** [comment]
I don't really get your question sorry.
pgBackRest works with a repository (or even multiple repositories). And there are various repository types supported (nfs, cifs, s3, azure,...).
To restore a backup set contained in this repository, from any server you want, that server needs access to the repository (the best is a RO access).
If you export a backup set outside the repository, you'll need to deal with the uncompress/unencrypt restore process yourself.

**Comment by zN3utr4l** [comment]
Sorry, I'm currently using the default option ("posix"). So in order to be able to restore from one service to another I need the 2nd service, the one that must receive the restore, to have access to the folder where the first service performs the backups, in my configurations repo1-path=/var/lib/ pgbackrest.
 it's right?

**Comment by pgstef** [comment]
yes. your second server needs access to the repository where you push the backups from your first server.

posix is fine if you use a dedicated backup server or an nfs mount point. otherwise that also means your backups are only stored locally, next to your PG data - which is kinda dangerous.

**Comment by zN3utr4l** [comment]
Does this also have to be done with postgres off? Because I tried to do it with postgres turned on and it doesn't work, putting the pg_wals present in the backup in the postgres data/pg_wal folder
