### ISSUE TITLE
Possible memory leak in pgbackrest v2.46 while running backupArchiveCheckCopy() function from backup.c

### ISSUE THREAD

**Issue by AlekseiNC** [pgbackrest/pgbackrest#2135]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.46

2. PostgreSQL version: 12.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 8.7

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
Config from the backup server side: 
[global]
repo1-path=/u01/backup
repo1-host-user=pguser
repo1-retention-full=2
repo1-retention-full-type=count
processes-max=4
log-path=/var/log/pgbackrest
log-level-console=info
log-level-file=debug
start-fast=y

[stanname]
pg1-path=/u01/db/data
pg1-port=5432
pg1-host=172.12.13.45
pg1-user=postgres
pg1-host-user=pguser

7. Describe the issue:
The backup performs from separate server. 
During the final stage of full backup I observe increasing memory consumption. It happens while pgbackrest checks archived wal files within repository. We have a lot of wal files gerated during the full backup (around 7000) and the backup is performing several hours (the database is pretty high loaded). 
In the pgbackrest.log I didn't find any error or warning messages. 
pmap -X pid_of_pgbackrest shows that heap is growing constantly during backupArchiveCheckCopy() function work. Over 7Mb per second is increasing. 
In the pgbackrest.log I see about 2-3 WAL files can be checked during this time. 
Eventually it leads to Out Of Memory situation on the backup server. According to the log it doesn't manage to perform scan over all amount of archived wal files, RAM + swap is over.

**Comment by dwsteele** [comment]
I have not been able to identify a memory leak here, even when checking 100k WAL.

However, checking very large numbers of segments was pretty slow (and used a lot of list requests on object stores) so I created #2169 to optimize this process.

**Comment by dwsteele** [comment]
Closing since there has been no response.
