### ISSUE TITLE
What are the best practices of pgbackrest migration from v2.34 to 2.45 

### ISSUE THREAD

**Issue by daulat0** [pgbackrest/pgbackrest#2137]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45 

2. PostgreSQL version: 14.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: : Amazon Linux

4. Did you install pgBackRest from source or from a package?  :Source

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We are planning to upgrade pgbackrest from v2.34 to 2.45. Please suggest what are the best practices/steps of doing pgbackrest upgrade (Migrate). Do we need down for Postgres Cluster etc.

**Comment by pgstef** [comment]
Hi,

There are no specific best practices, except to maybe try it on a test server first. And you should target the latest release available (2.47), not the 2.45 which is 5 months old already.

As the [user-guide](https://pgbackrest.org/user-guide.html#upgrading/v2.x) says:

> Upgrading from v2.x to v2.y is straight-forward. The repository format has not changed, so for most installations it is simply a matter of installing binaries for the new version. It is also possible to downgrade if you have not used new features that are unsupported by the older version. 

That being said, 2.34 (June 2021) to 2.47 is a big jump. You should read the release notes to understand the changes (new features, behavior changes,...) that have been introduced and if they matter to your current setup.

Ultimately, it's just a matter of installing the new binaries. You don't need to stop PostgreSQL for that but if you use a repository host, it should have the same pgBackRest there and on the PG nodes too. That's probably the most frequently reported misunderstanding.

Kind Regards
