### ISSUE TITLE
Failed restore: unable to open missing file for read

### ISSUE THREAD

**Issue by aleszeleny** [pgbackrest/pgbackrest#2139]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **2.46**

2. PostgreSQL version: **14.8**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

- DB server: CentOS Linux release 7.8.2003 (Core)
- Repository: CentOS Linux release 7.9.2009 (Core)

4. Did you install pgBackRest from source or from a package?
RPM packages from the pgdg YUM repository were used.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
**pg1-host configuration**
**/etc/pgbackrest/pgbackrest.conf**

```
# Ansible managed

[global]
repo1-path=/pgbackrest
repo1-host=192.168.64.253
repo1-host-user=pgbackrest
log-level-file=detail
log-level-console=info

[global:archive-push]
archive-async=y
process-max=4
compress-type=lz4
compress-level=3

```

**/etc/pgbackrest/conf.d/prod_archive_stanza.conf**

```
# Ansible managed

[prod_archive]
pg1-path=/pgsql/cluster/14/data
repo1-block=y
repo1-bundle=y
```

**repo1-host configuration**
**/etc/pgbackrest/pgbackrest.conf**

```
# Ansible managed

[global]
repo1-path=/pgbackrest
repo1-retention-full=4
start-fast=y
buffer-size=16MiB
compress-type=lz4
compress-level=3
process-max=4
log-level-console=info
log-level-file=detail
```

**/etc/pgbackrest/conf.d/prod_archive_stanza.conf**

```
# Ansible managed

[prod_archive]
pg1-path=/pgsql/cluster/14/data
pg1-host=192.168.64.107
pg1-host-user=postgres
repo1-block=y
repo1-bundle=y
process-max=6
```

-  `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

PostgreSQL instance configuration parameters:
```
-bash-4.2$ egrep '^(archive_command|archive_mode|listen_addresses|max_wal_senders|wal_level|port)' postgresql.conf
listen_addresses = '*'		# what IP address(es) to listen on;
port = 5432				# (change requires restart)
wal_level = logical			# minimal, replica, or logical
archive_mode = on		# enables archiving; off, on, or always
archive_command = 'pgbackrest --stanza=prod_archive archive-push %p'		# command to use to archive a logfile segment
max_wal_senders = 30		# max number of walsender processes
```

    - errors in the postgresql log file before or during the time you experienced the issue - **none**
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Logs from the repository server
**prod_archive-backup.log**
**prod_archive-expire.log**

Logs from server where database restore was performed (dedicated server for restore test to validate backups, i.e. the production machine still operates normally):
**prod_archive-restore.log**
The restore was several times canceled (because of testing what paralel level can smoothly hanlde the magnetic disks based array attached to the machine used for restores testing), it was intdended. Tha failure can be easily found in the log anyway.
As another test, I've already started restore from a previous backup set to the failed one, which was in progress in the time I've copied the log file, so the error message is not at the end of the log file.

Checking teh file presence on the repository host:
```
[pgbackrest@sts-svc-pgbackrest253 pgbackrest]$ ls -l /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.lz4
ls: cannot access /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.lz4: No such file or directory
```
There were no error messages in systeml logs (journal, dmesg).

7. Describe the issue:
The restore command failed with the error message:
[prod_archive-backup.log.gz](https://github.com/pgbackrest/pgbackrest/files/12288956/prod_archive-backup.log.gz)
[prod_archive-expire.log.gz](https://github.com/pgbackrest/pgbackrest/files/12288960/prod_archive-expire.log.gz)
[prod_archive-restore.log.gz](https://github.com/pgbackrest/pgbackrest/files/12288961/prod_archive-restore.log.gz)

```
2023-08-07 19:21:39.981 P00  ERROR: [055]: raised from local-2 protocol: raised from remote-2 ssh protocol on '192.168.66.253': unable to open missing file '/pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.lz4' for read
                                    [FileMissingError] on retry after 1446ms: [same message]
                                    [FileMissingError] on retry after 16448ms: [same message]
2023-08-07 19:21:39.981 P00   INFO: restore command end: aborted with exception [055]
```

**Comment by pgstef** [comment]
Hi,

I notice you're using pgBackRest version `2.46` and `repo1-block=y repo1-bundle=y`. There has been a few fixes in 2.47. Could you try with the latest release please? The error is about a big file so I'm not sure this will change anything but it would be good to check.

The error raised seems to come from the restore of the backup set `20230805-010001F_20230807-010000I` and the `base/23848/30818343` file seems to be referenced from `20230805-010001F`:
```
P00 DETAIL: reference pg_data/base/23848/30818343 to 20230805-010001F
P00 DETAIL: reference pg_data/base/23848/30818343.1 to 20230805-010001F
P00 DETAIL: reference pg_data/base/23848/30818343_fsm to 20230805-010001F
```
And those files seem to have been successfully included in the backup:
```
DETAIL: backup file 192.168.64.107:/pgsql/cluster/14/data/base/23848/30818343.1 (1GB, 62.07%) checksum 3ea516fb182b918704cf1824408835594a2dc9ba
DETAIL: backup file 192.168.64.107:/pgsql/cluster/14/data/base/23848/30818343 (1GB, 62.89%) checksum 8d8f931649e57481160f79bbab8915d46a51d010
DETAIL: backup file 192.168.64.107:/pgsql/cluster/14/data/base/23848/30818343.2 (1GB, 87.27%) checksum 72f57c3349d765120b922b3d7f8f1814169df864
DETAIL: backup file 192.168.64.107:/pgsql/cluster/14/data/base/23848/30818343.3 (888.2MB, 98.07%) checksum bc291f6190e24a28bb86211704fcbfebe33dba4e
```

I'm not sure what's going on here. Let's hope your backup repo hasn't been corrupted by any external process.
Could you try to list the content of `ls /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343*`? There should be multiple files there.

It would maybe also be a good idea to run the verify command (2.47).

Kind Regards

**Comment by aleszeleny** [comment]
Hello, first of all, thanks for a super fast response!
Unsurprisingly, an attempt to restore from a different set referencing the same full backup has failed with the same error:

```
2023-08-08 10:50:30.112 P02 DETAIL: restore file /pgsql/cluster/14/data/base/23848/24853.223 (1GB, 38.23%) checksum 7f0399de9aef4afe85aa5e0de839ce1e851c4162
2023-08-08 10:50:34.694 P03 DETAIL: restore file /pgsql/cluster/14/data/base/23848/24853.222 (1GB, 38.25%) checksum 40723937eff7ca506ba41b819237a621645ad3b4
ERROR: [055]: raised from local-1 protocol: raised from remote-1 ssh protocol on '192.168.66.253': unable to open missing file '/pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/24853.224.lz4' for read
       [FileMissingError] on retry after 664ms: [same message]
       [FileMissingError] on retry after 15666ms: [same message]
2023-08-08 10:50:37.190 P00   INFO: restore command end: aborted with exception [055]
```

The repository server is a dedicated machine, nothing else is running there. We have already been running restores for another stanzas and it worked like a charm. This is a 7+TiB instance, so getting a dedicated machine for restoring tests takes some time, that it why the restore was not tested before.

2.47 will require us to upgrade all DB servers and the repository, assuming from the docs, that the identical version is required, or shall I just give a try to upgrading pgBackRest to 2.47 on the restore test machine (I guess the key is the version creating the backups here, as we are facing a missing file in the repository)?

Could I set dome very detail logging for given sanaza expire command to ensure the file was not accidentally deleted by an expire command?

Kind regards Ales Zeleny

**Comment by aleszeleny** [comment]
Sorry, yes, there are multiple files, as you expect:

```
[pgbackrest@sts-svc-pgbackrest253 ~]$ ls -l /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343*
-rw-r----- 1 pgbackrest pgbackrest 634514752  5. srp 05.32 /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.1.lz4
-rw-r----- 1 pgbackrest pgbackrest 468803444  5. srp 07.38 /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.2.pgbi
-rw-r----- 1 pgbackrest pgbackrest 297366246  5. srp 08.33 /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.3.pgbi
-rw-r----- 1 pgbackrest pgbackrest 635226122  5. srp 05.35 /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.pgbi
```

Regarding the pgBackrest upgrade, is 2.47 compatible with 2.46 (i.e. can I upgrade the pgBackRest repository first and afterward, step-by-step upgrade pg hosts)?

Thanks Ales Zeleny

**Comment by aleszeleny** [comment]
I've upgraded to 2.47 and the `verify ` command is now running. 
I'll post an update, once completed.


BTW, I did the upgrade so fast as I've found in the manual following chapter:

https://pgbackrest.org/user-guide.html#upgrading/v2.x

> 3.2
> Upgrading pgBackRest from v2.x to v2.y
> Upgrading from v2.x to v2.y is straight-forward. The repository format has not changed, so for most installations it is simply a matter of installing binaries for the new version. It is also possible to downgrade if you have not used new features that are unsupported by the older version.

But it resulted in an error (upgraded one pg host to 2.47, while the repository (and all other hosts) were still at 2.46):

```
-bash-4.2$ pgbackrest --stanza=prod check
ERROR: [037]: check command requires option: pg1-path
       HINT: does this stanza exist?
-bash-4.2$ pgbackrest --stanza=prod_archive check
2023-08-08 12:42:09.912 P00   INFO: check command begin 2.47: --exec-id=24391-e21116ff --log-level-console=info --log-level-file=detail --pg1-path=/pgsql/cluster/14/data --repo1-host=192.168.64.253 --repo1-host-user=pgbackrest --repo1-path=/pgbackrest --stanza=prod_archive
2023-08-08 12:42:10.532 P00   INFO: check repo1 configuration (primary)
ERROR: [039]: expected value '2.47' for greeting key 'version' but got '2.46'
       HINT: is the same version of pgBackRest installed on the local and remote host?
2023-08-08 12:42:10.680 P00   INFO: check command end: aborted with exception [039]
```


Might it be I did something wrong, or does the manual need some small update on how to perform upgrades without archiving interruption?

**Comment by pgstef** [comment]
> Might it be I did something wrong, or does the manual need some small update on how to perform upgrades without archiving interruption?

You didn't got it wrong, the same version of pgBackRest should indeed be installed on the local PG host and the remote repository host. PG will keep retrying to push the archives until it succeeds. So even if it fails for a few seconds that shouldn't break archiving.

I thought we were already mentioning this limitation in the user-guides but apparently not. Could be a good addition indeed.

> ```
> [pgbackrest@sts-svc-pgbackrest253 ~]$ ls -l /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343*
> -rw-r----- 1 pgbackrest pgbackrest 634514752  5. srp 05.32 /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.1.lz4
> -rw-r----- 1 pgbackrest pgbackrest 468803444  5. srp 07.38 /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.2.pgbi
> -rw-r----- 1 pgbackrest pgbackrest 297366246  5. srp 08.33 /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.3.pgbi
> -rw-r----- 1 pgbackrest pgbackrest 635226122  5. srp 05.35 /pgbackrest/backup/prod_archive/20230805-010001F/pg_data/base/23848/30818343.pgbi
> ```

Given this list, I don't think anything is missing in the repo. So there's a chance [this fix in 2.47](https://github.com/pgbackrest/pgbackrest/commit/4c27d74bbd3a44d8ab1af140277d3cd8302060c2) might help but it also might be an issue with the restore config (hard to say without the test server config).
At least the restore command used (`--delta --log-level-console=detail --log-level-file=detail --pg1-path=/pgsql/cluster/14/data --process-max=4 --repo1-host=192.168.66.253 --repo1-host-user=pgbackrest --repo1-path=/pgbackrest --stanza=prod_archive`) doesn't seems to mention repo1-block/repo1-bundle. Not sure it would have an impact though.

**Comment by pgstef** [comment]
On a quick review of your config, I'd advise to put all repo settings to the global section (repo1-block/bundle) and the compress-type too. And `repo1-path=/pgbackrest` isn't needed when repo1-host is used. But that shouldn't have a big impact.

I don't expect an issue with verify given the `ls` output you provided.

**Comment by aleszeleny** [comment]
I've tried to restore another instance (small one ~200GiB, except another stanza, same configuration) from backups based on the last full from Sat/Sun night and it has failed the same way:

```
2023-08-08 14:36:55.917 P02 DETAIL: restore file /pgsql/cluster/14/data/base/16452/9755942 (1GB, 39.49%) checksum 9fbdcbe700adb519fd55111c76501fc0a41b166d
2023-08-08 14:36:55.975 P03 DETAIL: restore file /pgsql/cluster/14/data/base/16452/9755952 (1GB, 40.04%) checksum 3716efbd04f5b8e3cab865f6dbc5f8c02d043bcf
2023-08-08 14:37:07.946 P01 DETAIL: restore file /pgsql/cluster/14/data/base/16452/9755939 (1GB, 40.58%) checksum 16eb5f8a48949945b7c90bd27eb945d4202bd819
2023-08-08 14:37:07.958 P02 DETAIL: restore file /pgsql/cluster/14/data/base/16452/9755932.1 (1GB, 41.12%) checksum 1fa56928ef72ef3ed6c999d9e31ec1bc8b19c1b5
2023-08-08 14:37:09.446 P00  ERROR: [055]: raised from local-4 protocol: raised from remote-4 ssh protocol on '192.168.66.253': unable to open missing file '/pgbackrest/backup/prod_replicaweb/20230805-123552F/pg_data/base/16452/9755932.2.lz4' for read
                                    [FileMissingError] on retry after 286ms: [same message]
                                    [FileMissingError] on retry after 15287ms: [same message]
2023-08-08 14:37:09.446 P00   INFO: restore command end: aborted with exception [055]
```

That makes me nervous, so far I have no issues while restoring an instance using pgBackrest. So the `verify` command was faster (the big archive instance verify is still running) and it reports no issues:
```
2023-08-08 14:48:19.467 P00   INFO: verify command begin 2.47: --buffer-size=16MiB --exec-id=21266-76ea5184 --log-level-console=info --log-level-file=detail --process-max=4 --repo1-path=/pgbackrest --stanza=prod_replicaweb --verbose
2023-08-08 15:34:39.836 P00   INFO: stanza: prod_replicaweb
                                    status: ok
                                      archiveId: 14-1, total WAL checked: 55585, total valid WAL: 55585
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230715-122201F, status: valid, total files checked: 9513, total valid files: 9513
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230715-122201F_20230716-020840I, status: valid, total files checked: 9604, total valid files: 9604
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230715-122201F_20230717-021634I, status: valid, total files checked: 9638, total valid files: 9638
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230715-122201F_20230718-020803I, status: valid, total files checked: 9590, total valid files: 9590
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230715-122201F_20230719-024725D, status: valid, total files checked: 9638, total valid files: 9638
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230715-122201F_20230720-022311I, status: valid, total files checked: 9691, total valid files: 9691
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230715-122201F_20230721-021708I, status: valid, total files checked: 9624, total valid files: 9624
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230722-122156F, status: valid, total files checked: 9651, total valid files: 9651
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230722-122156F_20230723-021510I, status: valid, total files checked: 9637, total valid files: 9637
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230722-122156F_20230724-021955I, status: valid, total files checked: 9692, total valid files: 9692
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230722-122156F_20230725-021834I, status: valid, total files checked: 9673, total valid files: 9673
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230722-122156F_20230726-024946D, status: valid, total files checked: 9700, total valid files: 9700
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230722-122156F_20230727-021922I, status: valid, total files checked: 9125, total valid files: 9125
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230722-122156F_20230728-021753I, status: valid, total files checked: 9286, total valid files: 9286
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230729-122944F, status: valid, total files checked: 9518, total valid files: 9518
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230729-122944F_20230730-020710I, status: valid, total files checked: 9611, total valid files: 9611
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230729-122944F_20230731-022526I, status: valid, total files checked: 9658, total valid files: 9658
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230729-122944F_20230801-021537I, status: valid, total files checked: 9620, total valid files: 9620
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230729-122944F_20230802-025003D, status: valid, total files checked: 9720, total valid files: 9720
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230729-122944F_20230803-021809I, status: valid, total files checked: 9617, total valid files: 9617
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230729-122944F_20230804-021729I, status: valid, total files checked: 9703, total valid files: 9703
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230729-122944F_20230804-183425I, status: valid, total files checked: 9612, total valid files: 9612
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230805-123552F, status: valid, total files checked: 8949, total valid files: 8949
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230805-123552F_20230806-021259I, status: valid, total files checked: 9045, total valid files: 9045
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230805-123552F_20230807-021813I, status: valid, total files checked: 9211, total valid files: 9211
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20230805-123552F_20230808-021508I, status: valid, total files checked: 9377, total valid files: 9377
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
2023-08-08 15:34:39.837 P00   INFO: verify command end: completed successfully (2780372ms)
[pgbackrest@sts-svc-pgbackrest253 ~]$ echo $?
0
```

So it makes me hard to understand, how it might happen that the **verify** command reports no issues, while an attempt to restore files on missing file(s) in the repository.

Afterward, I performed the 200GiB instance restore from the previous (29/07/2023) full backup and it proceeded without any issues.

Is there something I can do to help diagnose the discrepancy between failed restore and successful verify command?

Thanks a lot!

**Comment by aleszeleny** [comment]
> Did you use 2.47 for the new restore test?
YES

The listing:
```
[pgbackrest@sts-svc-pgbackrest253 ~]$ ls /pgbackrest/backup/prod_replicaweb/20230805-123552F/pg_data/base/16452/9755932*
/pgbackrest/backup/prod_replicaweb/20230805-123552F/pg_data/base/16452/9755932.1.lz4   /pgbackrest/backup/prod_replicaweb/20230805-123552F/pg_data/base/16452/9755932.3.lz4
/pgbackrest/backup/prod_replicaweb/20230805-123552F/pg_data/base/16452/9755932.2.pgbi  /pgbackrest/backup/prod_replicaweb/20230805-123552F/pg_data/base/16452/9755932.pgbi
```

> Verify mainly compares what's inside the backup manifests and what's on disk. It doesn't really guarantee a restore or a recovery will work. Remember the Schrödinger's law of backup... (The condition of any backup is unknown until a restore is attempted)

That is exactly why we are running restore tests :-)

But, **how does it happen that pgBackRest attempts to restore a file not present in the manifest file**? In such a case, the instance recovery will fail, but pgBackrest is failing to copy a file and I thought (which is different from _know_...) is controlled by the manifest file entries.

> When did you enabled block-level backups exactly? After 29/07/2023?

Way before, I upgraded to 2.46 (first block level stable release) a few days after 2.46 was released. Upgrade to 2.47 today.

> If my assumption is correct, you'll need to take a new backup with 2.47

That is something I'll definitely do to have a recent valid full backup.

Kind regards Ales Zeleny

**Comment by aleszeleny** [comment]
You are right, the files are in the manifest:

```
[pgbackrest@sts-svc-pgbackrest253 20230805-123552F]$ grep "pg_data/base/16452/9755932.2" backup.manifest*
backup.manifest:pg_data/base/16452/9755932.2={"bi":44,"bic":8,"bim":26618,"checksum":"87f5ac0d08f6b5c68d22b75f4d784e8a8e47764c","rck":"bff0c47c6027513e4c3067be7581453e5e8c3f13","repo-size":226915076,"size":1073741824,"timestamp":1688879598}
backup.manifest.copy:pg_data/base/16452/9755932.2={"bi":44,"bic":8,"bim":26618,"checksum":"87f5ac0d08f6b5c68d22b75f4d784e8a8e47764c","rck":"bff0c47c6027513e4c3067be7581453e5e8c3f13","repo-size":226915076,"size":1073741824,"timestamp":1688879598}
[pgbackrest@sts-svc-pgbackrest253 20230805-123552F]$ cd ../20230805-123552F_20230808-021508I
[pgbackrest@sts-svc-pgbackrest253 20230805-123552F_20230808-021508I]$ grep "pg_data/base/16452/9755932.2" backup.manifest*
backup.manifest:pg_data/base/16452/9755932.2={"checksum":"87f5ac0d08f6b5c68d22b75f4d784e8a8e47764c","rck":"bff0c47c6027513e4c3067be7581453e5e8c3f13","reference":"20230805-123552F","repo-size":226915076,"size":1073741824,"timestamp":1688879598}
backup.manifest.copy:pg_data/base/16452/9755932.2={"checksum":"87f5ac0d08f6b5c68d22b75f4d784e8a8e47764c","rck":"bff0c47c6027513e4c3067be7581453e5e8c3f13","reference":"20230805-123552F","repo-size":226915076,"size":1073741824,"timestamp":1688879598}
```

So it looks to me, it does not satisfy what you mention
> Verify mainly compares what's inside the backup manifests and what's on disk.

Otherwise, I'd expect an error, that a file from the manifest file is missing on the disk, or do I miss something?

The discrepancy between the full backup manifest and files on the disk:

```
[pgbackrest@sts-svc-pgbackrest253 20230805-123552F]$ grep "pg_data/base/16452/9755932" backup.manifest*
backup.manifest:pg_data/base/16452/9755932={"bi":44,"bic":8,"bim":26602,"checksum":"4902158140ec59c8289acac92c93a8bb5a823de8","rck":"c77c1f8fb8212619616bcb89b59ed9410b7d1518","repo-size":229445298,"size":1073741824,"timestamp":1688879598}
backup.manifest:pg_data/base/16452/9755932.1={"checksum":"1fa56928ef72ef3ed6c999d9e31ec1bc8b19c1b5","rck":"d0f666d839470eeff8ae8077c8fab99ffb759009","repo-size":227296145,"size":1073741824,"timestamp":1685434361}
backup.manifest:pg_data/base/16452/9755932.2={"bi":44,"bic":8,"bim":26618,"checksum":"87f5ac0d08f6b5c68d22b75f4d784e8a8e47764c","rck":"bff0c47c6027513e4c3067be7581453e5e8c3f13","repo-size":226915076,"size":1073741824,"timestamp":1688879598}
backup.manifest:pg_data/base/16452/9755932.3={"checksum":"96a5fbfffd5b9b9d11ced567d09a7e9591994e22","rck":"ab045ca99fd2479a1c9b926fa5595bc2c66fa716","repo-size":76532644,"size":394280960,"timestamp":1685436697}
backup.manifest:pg_data/base/16452/9755932_fsm={"bi":4,"bic":7,"bim":211,"bni":36,"bno":10187106,"checksum":"61247e9b593cc13aed84c6b27b90e97624d9d12d","rck":"078060b587ea5f1caf37d07e801dab31b73f961a","repo-size":603461,"size":909312,"timestamp":1688879598}
backup.manifest:pg_data/base/16452/9755932_vm={"bi":4,"bic":7,"bim":41,"bni":5,"bno":10271696,"checksum":"72db529fcc07e63f1c37a57cf3315cc4861a032a","rck":"e1df1eda0155445847008959eb7e24f029b65d1a","repo-size":1044,"size":114688,"timestamp":1688879598}
backup.manifest.copy:pg_data/base/16452/9755932={"bi":44,"bic":8,"bim":26602,"checksum":"4902158140ec59c8289acac92c93a8bb5a823de8","rck":"c77c1f8fb8212619616bcb89b59ed9410b7d1518","repo-size":229445298,"size":1073741824,"timestamp":1688879598}
backup.manifest.copy:pg_data/base/16452/9755932.1={"checksum":"1fa56928ef72ef3ed6c999d9e31ec1bc8b19c1b5","rck":"d0f666d839470eeff8ae8077c8fab99ffb759009","repo-size":227296145,"size":1073741824,"timestamp":1685434361}
backup.manifest.copy:pg_data/base/16452/9755932.2={"bi":44,"bic":8,"bim":26618,"checksum":"87f5ac0d08f6b5c68d22b75f4d784e8a8e47764c","rck":"bff0c47c6027513e4c3067be7581453e5e8c3f13","repo-size":226915076,"size":1073741824,"timestamp":1688879598}
backup.manifest.copy:pg_data/base/16452/9755932.3={"checksum":"96a5fbfffd5b9b9d11ced567d09a7e9591994e22","rck":"ab045ca99fd2479a1c9b926fa5595bc2c66fa716","repo-size":76532644,"size":394280960,"timestamp":1685436697}
backup.manifest.copy:pg_data/base/16452/9755932_fsm={"bi":4,"bic":7,"bim":211,"bni":36,"bno":10187106,"checksum":"61247e9b593cc13aed84c6b27b90e97624d9d12d","rck":"078060b587ea5f1caf37d07e801dab31b73f961a","repo-size":603461,"size":909312,"timestamp":1688879598}
backup.manifest.copy:pg_data/base/16452/9755932_vm={"bi":4,"bic":7,"bim":41,"bni":5,"bno":10271696,"checksum":"72db529fcc07e63f1c37a57cf3315cc4861a032a","rck":"e1df1eda0155445847008959eb7e24f029b65d1a","repo-size":1044,"size":114688,"timestamp":1688879598}
[pgbackrest@sts-svc-pgbackrest253 20230805-123552F]$ ll pg_data/base/16452/9755932*
-rw-r----- 1 pgbackrest pgbackrest 227296145  5. srp 12.36 pg_data/base/16452/9755932.1.lz4
-rw-r----- 1 pgbackrest pgbackrest 226915076  5. srp 12.36 pg_data/base/16452/9755932.2.pgbi
-rw-r----- 1 pgbackrest pgbackrest  76532644  5. srp 12.46 pg_data/base/16452/9755932.3.lz4
-rw-r----- 1 pgbackrest pgbackrest 229445298  5. srp 12.36 pg_data/base/16452/9755932.pgbi
```

It looks to me, that such a case shall be detected by the `verify` command, isn't it?

Can I do something to help diagnose it?

P.S.: The big archive instance verify command did not report any issues ending with a success message.

**Comment by pgstef** [comment]
> So it looks to me, it does not satisfy what you mention
> 
> > Verify mainly compares what's inside the backup manifests and what's on disk.
> 
> Otherwise, I'd expect an error, that a file from the manifest file is missing on the disk, or do I miss something?

`9755932.pgbi`, `9755932.1.lz4`, `9755932.2.pgbi`, `9755932.3.lz4` are on disk and the manifest have the block-incremental info in the manifest for the `.pgbi`. So there's no error to report in verify imo.

However, `9755932.2` is not `.pgbi` in 20230805-123552F_20230808-021508I anymore while it refers to it from 20230805-123552F. That's most probably why the restore look for `9755932.2.lz4` when it is actually `.pgbi`.

I think it is in line with the bug-fix I mentioned earlier: "_It was possible for block incremental info to be lost if a file had been modified in such a way that block incremental would be disabled_". So for that specific case, taking a new backup with 2.47 should copy the block incremental info in case the file ends up being referenced to a prior backup.

But I don't know if we could change the restore command to detect the "broken" situation too. @dwsteele might know more about this issue?

**Comment by aleszeleny** [comment]
Hello, thanks for the analysis!
I haven't mentioned that explicitly (except the directory name in prompt, my failure), the manifest file above is from **FULL** backup, that is why the missing `9755932.2`  file is an issue (not only from the perspective of being unable to restore the database) that I'll expect shall be detected by `verify` command as this is just a fact check between the manifest content and files on disk, so I'd suggest adding such a check not only to `restore` command but also to the `verify` command.
For sure I have no idea, how complicated such a check implementation is, so consider it as a potential improvement.

Full backups by version 2.47 are running, so I hope we'll be safe. The downside is, that I have to restore all the database instances in order of being sure the backups are valid since the `verify` command is now proven not to detect such an issue. (the idea was to run the restore tests in a different period than the full backups schedule rather than testing each backup every day).

Thanks for your immense support and despite any difficulties the pgBackrest is a great tool I like a lot, thanks for developing and supporting it!

**Comment by dwsteele** [comment]
Unfortunately verify does not check files that are a reference to a prior backup. It also does not reconstruct the block-level incrementals in the same way that restore does. The reason for this is it would multiply the work verify has to do so much that it would take *much* longer than it does now. We are planning a single-backup verify that would make allow us to get around this. In your case, the files on disk are fine, but the manifest itself is broken. We won't be able to detect that in all cases (though we could in this case if we rechecked the files referenced from the full backup).

Overall, your issue seems consistent with the bug that was fixed in 4c27d74b (and released in 2.47). As you have noted, your full backups are fine, and new diff backups off those fulls will also be OK. But any of your current diff/incr backups must be considered suspect (unless you restore them to test).

We thought this bug was fairly hard to hit but evidence is accumulating that it is not so hard to hit after all.

**Comment by aleszeleny** [comment]
Hi, I'll be offline until the end of the week, so sorry for the late responses if you need some information and/or tests, I'll try to manage them on Monday, if possible.
From my present view - we have backups created by 2.47, next week I'll perform restore tests to make sure the 2.47 is producing valid backups suitable for restores.

Kind regards
Ales Zeleny

**Comment by dwsteele** [comment]
> From my present view - we have backups created by 2.47, next week I'll perform restore tests to make sure the 2.47 is producing valid backups suitable for restores.

We'd appreciate that!

**Comment by aleszeleny** [comment]
Hi, I'll be offline until the end of the week, so sorry for the late responses if you need some information and/or tests, I'll try to manage them on Monday, if possible.
From my present view - we have backups created by 2.47, next week I'll perform restore tests to make sure the 2.47 is producing valid backups suitable for restores.

Kind regards
Ales Zeleny

**Comment by aleszeleny** [comment]
FYI: 6 PG instances/stanzas in total approx 11TiB from an incremental backup 2 days after full backups created using version 2.47 were restored & recovered without any issues.

Kind regards
Ales Zeleny

**Comment by dwsteele** [comment]
Excellent, thank you for reporting back!
