### ISSUE TITLE
Statement Timeout Error message in pgbackrest log file

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#214]
I get these messages as the last few lines in my pgbackrest log file:

2016-07-18 01:02:21.740 T12   INFO: backup file /pgdata/lenderx2/base/1/11897 (0B)
2016-07-18 01:02:21.740 T08   INFO: backup file /pgdata/lenderx2/base/1/11887 (0B)
2016-07-18 01:02:23.079 T00   INFO: backup file /pgdata/lenderx2/global/pg_control (8KB) checksum 8b05f87d50bc204509e866f3bc3fbd1e50d22f5f
2016-07-18 01:02:23.130 T00   INFO: full backup size = 1894.6GB
2016-07-18 01:02:23.130 T00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2016-07-18 01:32:23.199 T00  ERROR: [134]: statement timed out after 1800.056 second(s):
                                           select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), null as labelfile, null as spcmapfile from pg_stop_backup() as lsn
2016-07-18 01:32:23.245 T00   INFO: backup stop

**Comment by dwsteele** [comment]
Hi Michael,

It looks like you have not correctly configured archiving:
http://www.pgbackrest.org/user-guide.html#quickstart/configure-archiving

If you are running 1.03 you can use the check command to make sure that your configuration is correct:
http://www.pgbackrest.org/user-guide.html#quickstart/check-configuration

If you think archiving is correctly configured then check the postgres log for errors.

-David

**Comment by MichaelDBA** [comment]
Thanks for the check command!  Even though it generated unhandled exceptions in your code, I could tell by the module names where to look and I found my configuration problem.  I have attached the unhandled exceptions below so you can handle them better.

postgres@msp0llexm021:/pglog/lenderx2$ pgbackrest --stanza=lenderex2 --log-level-console=info check
2016-07-19 10:17:32.406 T00   INFO: check start: --buffer-size=8388608 --log-level-console=info --log-level-file=info --repo-path=/pgdata/pgbackrest --stanza=lenderex2
2016-07-19 10:17:32.407 T00 ASSERT: option db-path is required
2016-07-19 10:17:32.407 T00   INFO: check stop
2016-07-19 10:17:32.408 T00  ERROR: [140]: process terminated due to an unhandled exception
option db-path is required at /usr/share/perl5/pgBackRest/Config/Config.pm line 2371
        pgBackRest::Config::Config::optionGet('db-path') called at /usr/share/perl5/pgBackRest/Archive.pm line 1080
        pgBackRest::Archive::check('pgBackRest::Archive=HASH(0x1096da8)') called at /usr/bin/pgbackrest line 117
        eval {...} called at /usr/bin/pgbackrest line 32
 at /usr/bin/pgbackrest line 14
        main::__ANON__('option db-path is required at /usr/share/perl5/pgBackRest/Con...') called at /usr/share/perl/5.14/Carp.pm line 80
        Carp::confess('option db-path is required') called at /usr/share/perl5/pgBackRest/Config/Config.pm line 2371
        pgBackRest::Config::Config::optionGet('db-path') called at /usr/share/perl5/pgBackRest/Archive.pm line 1080
        pgBackRest::Archive::check('pgBackRest::Archive=HASH(0x1096da8)') called at /usr/bin/pgbackrest line 117
        eval {...} called at /usr/bin/pgbackrest line 32
 at /usr/bin/pgbackrest line 250
 at /usr/bin/pgbackrest line 14
        main::__ANON__('option db-path is required at /usr/share/perl5/pgBackRest/Con...') called at /usr/share/perl/5.14/Carp.pm line 80
        Carp::confess('option db-path is required at /usr/share/perl5/pgBackRest/Con...') called at /usr/bin/pgbackrest line 250

**Comment by dwsteele** [comment]
Looks like a bit of a copy-pasto in the config dependencies.  Will fix.

**Comment by dwsteele** [comment]
Fixed in 5893c3cd2e7e6d.  The error message now looks like this:
```
postgres@db-master:/$ pgbackrest --stanza=demo --log-level-console=info check
ERROR [112]: check command requires option: db-path
HINT: does this stanza exist?
```
It's not a big enough issue to justify a release so it will come out with 1.04.

**Comment by MichaelDBA** [comment]
How we lookin for the release that allows pgbackrest to run against a 
slave instead of a master?


-- 

Respectfully Yours,

Michael Vitale

Michael@sqlexec.com <mailto:michaelvitale@sqlexec.com>

703-600-9343

**Comment by dwsteele** [comment]
Still targeting next week.
