### ISSUE TITLE
Restore over NFS?

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#2143]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.46

2. PostgreSQL version: 15.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 8.6 on both servers.

4. Did you install pgBackRest from source or from a package? PGDG repository.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Circumstance: server1 has Pg, pgbackrest and **local** backup storage (/var/lib/pgsql/backups).  I'd like to restore a backup set to server2.

Can I just mount server1://var/lib/pgsql/backups on for example server2 /var/lib/pgsql/rmtbackups, then set repo1-path to /var/lib/pgsql/rmtbackups, and finally `pgbackrest restore --stanza=... .--type=time --target="<very recent past>"`?

That seems too easy, though.

**Comment by pgstef** [comment]
Hi,

> server1 has Pg, pgbackrest and local backup storage (/var/lib/pgsql/backups)

Am I the only one to think that's a very bad idea to keep the backups on the same storage than the PG data? If you lose your server, you'll lose everything :-(

> Can I just mount server1://var/lib/pgsql/backups on for example server2 /var/lib/pgsql/rmtbackups, then set repo1-path to /var/lib/pgsql/rmtbackups, and finally `pgbackrest restore --stanza=... .--type=time --target="<very recent past>"`?

If the mount point and pgBackRest configuration on server2 are correct, yes that should work. Small tips: use a RO mount and use the --archive-mode=off option, so you make sure the restored server2 doesn't push any WAL archive to the repo.

> That seems too easy, though.

Why ? The hard part is sharing the repo ;-)

**Comment by RonJohn2** [comment]
> Hi,
> 
> > server1 has Pg, pgbackrest and local backup storage (/var/lib/pgsql/backups)
> 
> Am I the only one to think that's a very bad idea to keep the backups on the same storage than the PG data? If you lose your server, you'll lose everything :-(

It's a VM on one of many ESXi servers, and mount points are all SAN LUNS that get regularly snapshotted.  Thus, losing everything to a hardware problem is the least of my worries.

> 
> > Can I just mount server1://var/lib/pgsql/backups on for example server2 /var/lib/pgsql/rmtbackups, then set repo1-path to /var/lib/pgsql/rmtbackups, and finally `pgbackrest restore --stanza=... .--type=time --target="<very recent past>"`?
> 
> If the mount point and pgBackRest configuration on server2 are correct, yes that should work. Small tips: use a RO mount and use the --archive-mode=off option, so you make sure the restored server2 doesn't push any WAL archive to the repo.

Thanks for those tips.

> > That seems too easy, though.
> 
> Why ? The hard part is sharing the repo ;-)

There's **always** an unforeseen issue... :dagger:

**Comment by pgstef** [comment]
> There's **always** an unforeseen issue... dagger

In this case that will most probably be with permissions. But sharing a repo is the common practice for restore tests :+1:
