### ISSUE TITLE
Question about seperating backup and wal locations

### ISSUE THREAD

**Issue by ajrpayne** [pgbackrest/pgbackrest#2147]
I couldn't find anything in the docs, so I thought I'd ask here. Could one do something like the below?

```
[demo]
repo1-path=/backup-location

[demo:archive-get]
repo1-path=/wal-location

[demo:archive-push]
repo1-path=/wal-location
```

I assume that the backup and WAL archive repo1-path must be the same, but was curious just the same.

**Comment by pgstef** [comment]
Hi,

You can't do that from the configurations directly. Backups and archives should be in the same repository (since one is mostly useless without the other). Many commands are using files in both locations.

Kind Regards

**Comment by dwsteele** [comment]
If you just want archive and backup to be on different storage devices, you can pre-create the directory structure with symlinks or mounts for `archive` and `backup` to wherever you like. But logically they need to part of the same directory structure.
