### ISSUE TITLE
Is it possible to restore a database without touching the other databases ? 

### ISSUE THREAD

**Issue by damienApp** [pgbackrest/pgbackrest#2149]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
==> pgBackRest 2.45

2. PostgreSQL version:
 ==> postgres (PostgreSQL) 15.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
==> Red Hat Enterprise Linux release 8.7 (Ootpa)

4. Did you install pgBackRest from source or from a package?
From ==> https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/12369583/postgresql.conf.txt)

    - `postgresql.conf` setti
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/12369581/pgbackrest.conf.txt)
ngs applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
  

7. Describe the issue:
8. Hello, I would like to know if it is possible to restore a database while keeping the other databases. For example, I have two databases, test1 and test2, and the application drops test2. I'd like to be able to restore test2 while keeping the changes made in test1. I haven't seen anything in the docs about how to do this, apart from being able to include or exclude databases, but all the data is reloaded.

**Comment by pgstef** [comment]
Hi,

That's not possible with [PostgreSQL physical backups](https://www.postgresql.org/docs/current/continuous-archiving.html).
To re-import a database into a working PG cluster, you need to use logical exports (pg_dump/pg_restore).

What you can do is to restore a pgBackRest backup on another server until the target point you want (PG point-in-time recovery), then use pg_dump to export test2 and pg_restore to import it in you working cluster.

The db-exclude/include options will help you save time and space when you'll restore the cluster to extract test2.

Kind Regards
