### ISSUE TITLE
multi-purpose archive_command?

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#215]
For one setup, i have a customized script invoked by the archive_command to scp WALs over to a slave just in case slave gets too far behind.  I avoided slots because I don't want WAL to accumulate fast on the master if the slave is unresponsive since we generate a lot of WAL very fast.

My question is: should I embed the pgbackrest call in my customized script to archive to pgbackrest repo for maintaining backups on the master, so I would have something like this in my custom script besides the scp logic:
pgbackrest --stanza=lenderx2 archive-push %p

Or is there a better way to get pgbackrest to do both functions:
1. update its own pgbackrest repo
2. copy WALs to another location, ie, slave

**Comment by dwsteele** [comment]
Why wouldn't you just pull the WAL from the backrest repo using the archive-get command?  I don't recommend archiving WAL twice.  It's expensive and prone to error.

Here are instructions for setting up a replica to use the backrest WAL archive:
http://www.pgbackrest.org/user-guide.html#replication

This will keep the replica supplied with WAL even if streaming replication goes down or the master recycles xlogs too early.  I agree that using slots is not a great idea, but wal_keep_segments should certainly be set high enough that WAL is *likely* to be on the master.

**Comment by MichaelDBA** [comment]
Wow, pgbackrest enables WAL pulls instead of WAL pushes from master, nice!!!!

**Comment by dwsteele** [comment]
The pulls are not from master.  The master pushes to the repo with `archive-push`, then the standby pulls from the repo with `archive-get`.

**Comment by dwsteele** [comment]
But if your repo is on your master then I could see how it would seem that way.

**Comment by SaanSingh** [comment]
What if I have repo on master ,can I still get archives from primary to standby?

**Comment by SaanSingh** [comment]
Is m in this situation and it is difficult to configure repo for backup. Please suggest some solution as pgbasebackup is taking 10hrs to create standby.
Thanks in advance

**Comment by dwsteele** [comment]
@SaanSingh Please don't post on old issues.  Open a new issue and provide all requested details.

Also, this is not the place to get help on debugging pg_basebackup issues.  You should try pgsql-admin or psql-general instead.
