### ISSUE TITLE
Propagate annotations as tags for cloud storage

### ISSUE THREAD

**Issue by cyberdelia** [pgbackrest/pgbackrest#2150]
For cloud storage, it would be practical to propagate annotations as tags to each objects being written.
Said tags allow for in depth analysis for cost optimization, usage analysis and debugging.

All clouds support doing so via a header:
- [`x-amz-tagging`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestSyntax) for S3
- [`x-ms-tags`](https://learn.microsoft.com/en-us/rest/api/storageservices/put-blob#request-headers-all-blob-types) for Azure.
- [`x-goog-meta-`](https://cloud.google.com/storage/docs/xml-api/reference-headers#xgoogmeta) for GCP.

**Comment by dwsteele** [comment]
There are a couple of factors which will make this more complex than it looks:

1) How would we handle annotation updates? Would those be propagated out to all the files?
2) If an annotation update failed in the middle we could be left with mixed annotations.
2) On a backup resume we would need to update the files that are being kept with the new annotations.

Given that every file in a certain prefix (i.e. backup path) would be getting the same annotations, I wonder if there is a better way to do this.

Can you give an example of what these annotations look like and what they are used for?

**Comment by cyberdelia** [comment]
You can use [tagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html) APIs of each cloud to do most of this.

Ultimately, it's most likely that if you're using cloud storage, you not only don't change tags often but are expecting the propagation of tags to take as long as your retention policy allows, and not except to see all your files tagged instantly (since it could be costly to do so)

If you need instant up-to-date information, using annotations as-is is more than enough, tags in this scheme are more a long term reporting tool. I understand that the dichotomy between the two might be hard to document and might require a separate option (to force update or not for example).

Sadly, "bucket path" doesn't help much here, as different cloud have different limitations on bucket and paths, which can prevent the use of bucket level tagging.

Tags are very much alike annotations, they're a `key=value` scheme, most likely depicting some internal information that allows you to determine where your cost are allocated (`client_id=12344`, `service=perfect_service`) or apply a [lifecycle rule](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html) to some objects (but it's unlikely that someone use them alongside `pgbackrest`)

**Comment by dwsteele** [comment]
What about WAL and the backup.info/archive.info metadata files? The backup annotation system does not really cover them, but for billing seems like they would need to be tagged as well. 

It's starting to sound like you'd really want stanza or even repo level annotations, which might mean all files in the bucket get the same tag. Possibly there is a simpler way to do accounting than applying the same tags to every file in the bucket?

**Comment by cyberdelia** [comment]
Considering the size of the metadata files, it's probably negligible for reporting, but ideally, sure.

You could do tagging at the bucket level, but you have no guarantee that a repo is not sharing the same bucket with another repo under a different prefix (especially for AWS S3, for which it's a very common strategy). So the safest bet is usually to tag on object write.

**Comment by cyberdelia** [comment]
Ideally, WAL should also be tagged, yes.

**Comment by dwsteele** [comment]
@cyberdelia Closing this issue since there is a now a PR to implement this feature. The driver implementations look good, but we still need to come to a consensus on how this will be configured.
