### ISSUE TITLE
Intermittent issue with pgbackrest expire not running to expire oldest repo

### ISSUE THREAD

**Issue by mysterious-maniac** [pgbackrest/pgbackrest#2151]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.41

3. PostgreSQL version:  PostgreSQL 14.6

4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL

5. Did you install pgBackRest from source or from a package? Package

7. pgbackrest.conf relevant config:
repo1-retention-full=1

9. Describe the issue:

How am I able to troubleshoot reasons why pgbackrest expire doesn't work? There are times where pgbackrest doesn't expire the oldest repo, thus causing space issues in our environment. 

A new expire log in /var/log/pgbackrest/expire.log is created, but this is empty and doesn't help in troubleshooting reasons why the expire doesn't take place. 

The backup.log in this instance would have the regular errors that show up when the disk is out of space.

Note that this only happens from time to time, and I cannot accurately predict when it will happen next until we get alerts that our backups are failing because of disk space, which 9.9/10 times is due to pgbackrest not expiring the oldest backup (older than 1/2 weeks depending on the enviro).

**Comment by mysterious-maniac** [comment]
Actually, here is a pgbackrest info to help:
`    db (current)
        wal archive min/max (14): 000000010000025C00000001/000000010000026F00000028

        full backup: 20230813-003001F
            timestamp start/stop: 2023-08-13 00:30:01 / 2023-08-13 07:23:38
            wal start/stop: 000000010000025C00000001 / 000000010000025E00000040
            database size: 2630.8GB, database backup size: 2630.8GB
            repo1: backup set size: 207.5GB, backup size: 207.5GB

        incr backup: 20230813-003001F_20230814-003002I
            timestamp start/stop: 2023-08-14 00:30:02 / 2023-08-14 03:01:20
            wal start/stop: 000000010000025E000000CD / 000000010000025E000000E0
            database size: 2632.6GB, database backup size: 1156.8GB
            repo1: backup set size: 207.6GB, backup size: 128.6GB
            backup reference list: 20230813-003001F

        incr backup: 20230813-003001F_20230815-003002I
            timestamp start/stop: 2023-08-15 00:30:02 / 2023-08-15 02:50:33
            wal start/stop: 00000001000002610000003B / 000000010000026100000059
            database size: 2634GB, database backup size: 1090.5GB
            repo1: backup set size: 207.7GB, backup size: 114.3GB
            backup reference list: 20230813-003001F, 20230813-003001F_20230814-003002I

        incr backup: 20230813-003001F_20230816-003002I
            timestamp start/stop: 2023-08-16 00:30:02 / 2023-08-16 02:36:51
            wal start/stop: 000000010000026400000003 / 00000001000002640000001D
            database size: 2635.5GB, database backup size: 1003GB
            repo1: backup set size: 207.8GB, backup size: 98.3GB
            backup reference list: 20230813-003001F, 20230813-003001F_20230814-003002I, 20230813-003001F_20230815-003002I

        incr backup: 20230813-003001F_20230817-003001I
            timestamp start/stop: 2023-08-17 00:30:01 / 2023-08-17 02:58:40
            wal start/stop: 0000000100000266000000CB / 0000000100000266000000E7
            database size: 2636.9GB, database backup size: 1139.2GB
            repo1: backup set size: 207.9GB, backup size: 125.3GB
            backup reference list: 20230813-003001F, 20230813-003001F_20230814-003002I, 20230813-003001F_20230815-003002I, 20230813-003001F_20230816-003002I

        incr backup: 20230813-003001F_20230818-003002I
            timestamp start/stop: 2023-08-18 00:30:02 / 2023-08-18 03:02:35
            wal start/stop: 0000000100000269000000B7 / 0000000100000269000000D3
            database size: 2638.9GB, database backup size: 1172GB
            repo1: backup set size: 208GB, backup size: 129.7GB
            backup reference list: 20230813-003001F, 20230813-003001F_20230814-003002I, 20230813-003001F_20230815-003002I, 20230813-003001F_20230816-003002I, 20230813-003001F_20230817-003001I

        incr backup: 20230813-003001F_20230819-003002I
            timestamp start/stop: 2023-08-19 00:30:02 / 2023-08-19 02:58:11
            wal start/stop: 000000010000026C00000075 / 000000010000026C00000091
            database size: 2641GB, database backup size: 1143.3GB
            repo1: backup set size: 208.1GB, backup size: 123.2GB
            backup reference list: 20230813-003001F, 20230813-003001F_20230814-003002I, 20230813-003001F_20230815-003002I, 20230813-003001F_20230816-003002I, 20230813-003001F_20230817-003001I, 20230813-003001F_20230818-003002I
`
Reading [here ](https://github.com/pgbackrest/pgbackrest/issues/2103#issuecomment-1614287498)states "Archive is not expired until retention has been met" The backup size on the disk adds up to 926.9GB where the backup disk only has 956G worth of disk space. This will result in the next full backup not being able to complete due to lack of disk space.

If I am reading this correctly, is this entire issue due to the disk not having enough space for the next full backup to complete, and thus the old repo is not being expired? TIA

**Comment by dwsteele** [comment]
Looks to me like archive has been expired. You oldest WAL is `000000010000025C00000001` and that is used by your (only) full backup.

BTW -- `repo1-retention-full=1` is not a good retention scheme. More like an invitation to disaster.

**Comment by mysterious-maniac** [comment]
There are extenuating circumstances why the retention is 1 but I will not get into it here.

As for the expiry, if you could better help me understand this next question that would be great.

As far as I know, from the experience I have with PGBR, the expected behaviour here would be for this entire repo to be expired and thus deleted from the system with a new, full backup taking place on 8/20. Obviously that is not the case since the backups spanning from 8/13-8/19 are still present on the system.

Note that there are cronjobs that initiate a full backup every sunday, and an incremental throughout the week mon-sat.

**Comment by dwsteele** [comment]
If `repo1-retention-full=1` then there must always be *at least* one valid full backup. So, the old backup will not be expired until the new one is complete. For a while (before expiration completes) you will have two full backups and all associated WAL.

We do this because if the old backup is expired first and the new backup fails then you have *zero* backups, which seems like a pretty bad idea.

**Comment by mysterious-maniac** [comment]
Thanks, after exhibiting some older tickets with similar issues, it definitely seems related to what you just described. I will close this.
