### ISSUE TITLE
libssh2 

### ISSUE THREAD

**Issue by hunleyd** [pgbackrest/pgbackrest#2153]
The new `sftp` repo support seems to rely on `libssh2`. As RHEL no longer includes `libssh2` in RHEL 8 or above as of May 2019[^1][^2], I'm wondering if `libssh` would suffice or if `libssh2` is specifically needed? I understand that `libssh2` can be obtained from EPEL, but I have clients that cannot use EPEL, so if pgBackRest could instead use `libssh` that would be great. 

Thanks!

[^1]: https://github.com/libgit2/libgit2/issues/5225
[^2]: https://bugzilla.redhat.com/show_bug.cgi?id=1660344

**Comment by dwsteele** [comment]
For the current implementation, libssh2 is definitely required because the API is different between libssh and libssh2. As to why we picked libssh2, I'll defer to @jreidthompson or @sfrost.

**Comment by jreidthompson** [comment]
I thought I had notes on this, but can't seem to locate them.  From my recollection, for me, the bullet points were          
                                                                                                                                    
* platforms supported/availability
    available on all pgbackrest supported platforms/distros including macos (didn't realize that EPEL would be an issue). And if not available, as long as one of the supported cryptographic libraries (OpenSSL, wolfSSL, Libgcrypt, WinCNG, mbedTLS ) is available it should be easy enough to build.
* BSD license
* example code
* utilized as the ssh backend by curl, (i see where libssh was added as an alternative backend, maybe/likely related to the two footnotes above)

**Comment by hunleyd** [comment]
thank you both @dwsteele and @jreidthompson . for now we will also ship libssh2 to our clients.
