### ISSUE TITLE
Support for dual stack connections.

### ISSUE THREAD

**Issue by cyberdelia** [pgbackrest/pgbackrest#2154]
When using dualstack hostname (that resolves to an IPv6 or an IPv4 address), `pgbackrest`  doesn't seems to fallback to ipv4 if the ipv6 connection fails.

We have observed this behaviour with [dualstack s3 endpoints](https://docs.aws.amazon.com/AmazonS3/latest/userguide/dual-stack-endpoints.html#dual-stack-endpoints-description), and a missing ipv6 route. `pgbackrest` will [timeout](https://github.com/pgbackrest/pgbackrest/blob/1e6efd73e1fcf7bbe3d3f04d925fefde44847109/src/common/io/socket/common.c#L207C16-L207C16), and never fallback to ipv4, because only the ipv6 address seems to get [resolved](https://github.com/pgbackrest/pgbackrest/blob/main/src/common/io/socket/common.c#L60).

The expected behaviour here would be to try ipv6 and fallback on ipv4.

**Comment by dwsteele** [comment]
This makes sense to do, though fixing the route would be the obvious short-term fix. My guess is that has already been done.

Regarding retries, I wonder if we should cycle through the addresses as we retry? Or retry each address a few times before moving on? Seems like the former would be a better strategy, at least for non-transient errors.

**Comment by cyberdelia** [comment]
It turns out there is an [RFC about handling dualstack hosts](https://www.ietf.org/rfc/rfc6555.txt), that should cover what most people expect the behaviour to be. `curl` implements said RFC as well.

**Comment by dwsteele** [comment]
After discussion we decided against Happy Eyeballs and implemented a round-robin approach similar to what Postgres uses. My primary concern was the number of connections that might be opened when `process-max` is set very high. A simpler approach also allows us to get a solution into the upcoming release.

Of course, we can revisit this decision if we find the performance is not satisfactory.

**Comment by dwsteele** [comment]
Implemented in #2175.

**Comment by dwsteele** [comment]
Reopening this since #2175 did not work out as well as we hoped.

**Comment by dwsteele** [comment]
@cyberdelia New, improved version in PR #2235.
