### ISSUE TITLE
 ERROR: [124]: protocol version mismatch

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#216]
This new issue relates in part to another closed one entitled, "Nicer error message on SSH errors".

After reading that I realized my restore action from the slave to the master was failing because pgbackrest was attempting to use a user named, backrest, for the ssh connection.  Once I added "backup-user=postgres" to the global section on my slave, it worked ok.  So it was not a protocol mismatch error, since both master and slave show this:
PGBACKRESTREMOTE 1.03

when issuing this command from the slave (restore) and master(backup):
ssh -o Compression=no -o PasswordAuthentication=no postgres@msp0llexm021 '/usr/bin/pgbackrest --command=restore --repo-path=/pgdata/pgbackrest --stanza=demo remote'

I don't see anywhere in the documentation that talks about this "backrest" user.  If I missed it please let me know.  Otherwise, you should probably document this somewhere.  It would be nice to have a section about defining this backrest user to be used as the default user for pgbackrest functionality.

**Comment by dwsteele** [comment]
Currently backup-user is only discussed in the configuration reference:
http://www.pgbackrest.org/configuration.html#section-backup/option-backup-user

I agree that this should be explicit in the user guide.  Will add for the next version.

**Comment by dwsteele** [comment]
Clarification added in ee80b7b.
