### ISSUE TITLE
[Question] Is it possible to upload a backup to s3 via pre-signed URL?

### ISSUE THREAD

**Issue by sthompson-tsrgrow** [pgbackrest/pgbackrest#2160]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.47

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Mac OS

4. Did you install pgBackRest from source or from a package? from source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: I would like to backup to my s3 bucket via pre-signed url. Is this supported? If so, could you please advise how I may configure pgbackrest to use the pre-signed URL?

**Comment by dwsteele** [comment]
Pre-signed URLs are not currently supported. The fact that they expire and can't be renewed makes them less than ideal for a server process. Of course, the config can be updated, but keys can also be expired if needed.

I'm not entirely convinced there is a strong enough use case, but we would be willing to review a patch if you submit it. No need to write unit tests -- we'll take care of those.
