### ISSUE TITLE
Raising the proxy issue again

### ISSUE THREAD

**Issue by spapas** [pgbackrest/pgbackrest#2164]
Hey friends, I'd like to raise the proxy issue again. This hass been opened (and closed) already a bunch of times:

#1639, #1085, #888, #879 and possibly others. 

I'd like to explain why this is needed for me:

I've got a database cluster that is running in a corporate environment and can only access the internet through a proxy. In this case archiving to S3 is *not possible* at all without using that proxy. Please notice that this is usual for most coproprate environements, ie the database is inside their network and won't be able to access the internet for security reasons so the proxy is required. 

If you can recommend any other solution i'd be happy to listen to it. 

Thank you

**Comment by sfrost** [comment]
While this comes up from time to time, it's rather infrequent and would require an extensive amount of effort to write the code and tests for.  Also- what exact kind of proxy is it?  What other tools are you using with s3 through this proxy?

pgBackRest is certainly used in many, many, many corporate environments, though typically in server environments and on server networks where folks have realized that maybe not everything makes sense to force through a proxy.

There is also proxychains which might be interesting to see if that works in this case.

**Comment by spapas** [comment]
Hello @sfrost thank you for answering. The proxy we use is a simple squid proxy without any configuration (i.e setting `HTTPS_PROXY=http://proxy.example.com:8080` is enough in most cases).

Because our servers do not have access to the network we access our S3 server using HTTP requests so they are proxied without problems. 

I understand why it is problematic to pass big data through the proxy however in our case at least there isn't any other easy option because of security reasons in our network. Also, in most cases you don't really need too much work or tests to support the proxy because the http library already supports it by reading the env vars and acting accordingly (I guess this isn't the case with pgbackrest).

I will try the proxychains tool you recommended, if it works it should resolve this issue.

**Comment by sfrost** [comment]
By default squid won't allow CONNECT to be performed, with generally pretty good reason and because it ends up with there being rather little point in using squid over just having firewall rules. If you're using HTTPS_PROXY and s3 using https, then you're not using a default squid configuration as it must be allowing CONNECT.

Given that we could just open a connection, issue a CONNECT, and then ignore the fact that we're talking to a proxy for the rest of the https/tls connection, it's at least something we'd be open to exploring.  Might mean we get requests to also support proxy authorization but that doesn't look too difficult.

**Comment by spapas** [comment]
One thing that may help with the discussion is that other backup tools that are using S3 (for example clickhouse-backup https://github.com/Altinity/clickhouse-backup) work perfectly behind http proxies: https://github.com/Altinity/clickhouse-backup/pull/177

**Comment by sfrost** [comment]
If you're willing to write the implementation of it then please feel free to do so and submit it as a PR and we'll take a look at it.

**Comment by spapas** [comment]
Hello friends, I see that this issue is completed? Is now pgbackrest support using the proxy for S3 ? If yes, which release includes this functionality ?

**Comment by dwsteele** [comment]
For the time being at least, we are not planning to implement proxies, especially if proxychain is a reasonable alternative.
