### ISSUE TITLE
Restoring from one database server to a different database server

### ISSUE THREAD

**Issue by craigmj** [pgbackrest/pgbackrest#2167]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.47

2. PostgreSQL version: 14.9-1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: ubuntu 20.04

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I run pgbackrest to backup my production database, but I want to restore it to my development machine.
I'm doing the following:
1. Turning off my cluster: `pg_ctlcluster 14 main stop`
2. Disabling archiving on my machine. `postgres.conf` has: `archive_mode = off`
3. Configure my stanza file (`stanza-14-main.conf`) as:
```
[global]
repo1-path = /var/lib/localrepo/pgbackrest
repo1-retention-full = 2

repo2-type=s3
repo2-retention-full=4
repo2-s3-endpoint=s3...
repo2-s3-key=...
repo2-s3-key-secret=...
repo2-s3-region=...
repo2-s3-bucket=...
repo2-path=/mybackups/postgres

[global:archive-push]
compress-level = 3

[main]
pg1-path = /var/lib/postgresql/14/main
pg1-port = 5434
```
4. Delete `/var/lib/postgresql/14/main` and create a new, empty `/var/lib/postgresql/14/main` owned by postgres user
5. Running pgbackrest as:
`sudo -u postgres pgbackrest --config /home/craig/postgres-restore-configs/stanza-14-main.conf --log-level-console info --stanza main restore --archive-mode=off`
I get:
```2023-09-04 11:45:29.223 P00   INFO: repo1: restore backup set 20230831-105758F, recovery will start at 2023-08-31 10:57:58
2023-09-04 11:45:29.968 P00   INFO: write updated /var/lib/postgresql/14/main/postgresql.auto.conf
2023-09-04 11:45:29.971 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
2023-09-04 11:45:29.972 P00   INFO: restore size = 25.2MB, file total = 946
2023-09-04 11:45:29.972 P00   INFO: restore command end: completed successfully (758ms)
```
6. Restart the cluster: `sudo pg_ctlcluster 14 main start`
7. The log `/var/log/postgresql/postgresql-14-main.log` shows:
``` 2023-09-04 11:46:57.835 SAST [588580] LOG:  restored log file "000000010000000000000028" from archive
WARN: repo2: [ArchiveMismatchError] unable to retrieve the archive id for database version '14' and system-id '7014763184616102939'
2023-09-04 11:46:59.087 SAST [588580] LOG:  restored log file "000000010000000000000029" from archive
WARN: repo2: [ArchiveMismatchError] unable to retrieve the archive id for database version '14' and system-id '7014763184616102939'
```
When it completes and I connect to my cluster, I don't have the databases that are on the production server.
It seems from my reading that the issue is that I'm trying to restore to a different server, but since I'm trying to restore an _entire_ cluser, I would think this should be doable. Is there a setting to ignore or reset the system-id? Am I missing something obvious?
Kind regards,
Craig

**Comment by dwsteele** [comment]
> repo1-path = /var/lib/localrepo/pgbackrest

Yeah, and this looks a lot like a local path, so very unlikely to contain data from your prod server. Probably some old data from a test you ran.

**Comment by craigmj** [comment]
Hi, thank you - yes, that was wrong. I've changed it so that repo1 is now pointing to my s3 repo. I've got:
`2023-09-04 16:36:40.472 P00   INFO: repo1: restore backup set 20230831-091355F_20230831-142857I, recovery will start at 2023-08-31 16:28:57` and it just hangs. No error messages, nothing, in 10 minutes. Is that unusually long?

Even pointing to the wrong repo, though, I was having the same issue anyway, because surely it should have just restored my local backup (not the s3 one), and I wouldn't have had the db I wanted, but I was instead getting the `[ArchiveMismatchError]`?

**Comment by craigmj** [comment]
Thank you - `log-level-console=debug` showed it _was_ working, just slow over s3, but that's fine.
And the restore worked perfectly - I've now go the databases from production nicely on my development box.
Thank you so much - you've helped me massively!

**Comment by dwsteele** [comment]
> Even pointing to the wrong repo, though, I was having the same issue anyway, because surely it should have just restored my local backup (not the s3 one), and I wouldn't have had the db I wanted, but I was instead getting the [ArchiveMismatchError]?

It did restore from the local repo and then it fetched WAL successfully from the local repo, which is why you got a consistent recovery (but not with the data you expected). The warnings about repo2 were just to let you know that it did not match the data in repo one, but the archive-get was still successful, or you would have gotten an error. All warnings are non-fatal in pgBackRest, but they alert you to conditions that might need attention.
