### ISSUE TITLE
error 82 while trying to backup over sftp

### ISSUE THREAD

**Issue by gred7** [pgbackrest/pgbackrest#2168]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

pgBackRest 2.47

2. PostgreSQL version:

 PostgreSQL 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

N/A

5. Did you install pgBackRest from source or from a package?

installed from source

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
ERROR: [082]: WAL segment 00000001000000000000007D was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
       --------------------------------------------------------------------
       If SUBMITTING AN ISSUE please provide the following information:
       
       version: 2.47
       command: backup
       options: --exec-id=9075-642f1963 --log-level-console=debug --pg1-path=/var/lib/postgresql/14/main --pg1-user=postgres --repo1-path=/home/backup/pgbackrest --repo1-retention-full=3 --repo1-sftp-host=u365283.your-storagebox.de --repo1-sftp-host-key-hash-type=sha1 --repo1-sftp-host-port=23 --repo1-sftp-host-user=u365283 --repo1-sftp-private-key-file=/var/lib/postgresql/.ssh/id_rsa --repo1-sftp-public-key-file=/var/lib/postgresql/.ssh/id_rsa.pub --repo1-type=sftp --stanza=local
       
       stack trace:
       command/archive/common.c:walSegmentFind:467:(storage: {type: sftp, path: /home/backup/pgbackrest, write: false}, archiveId: {"14-1"}, walSegment: {"00000001000000000000007D"}, timeout: 60000)
       command/backup/backup.c:backupStart:(backupData: {BackupData})
       command/backup/backup.c:cmdBackup:(void)
       main.c:main:(debug log level required for parameters)
       --------------------------------------------------------------------
2023-09-04 16:58:36.496 P00 DETAIL: statistics: {"socket.client":{"total":1},"socket.session":{"total":1}}
2023-09-04 16:58:36.496 P00   INFO: backup command end: aborted with exception [082]
2023-09-04 16:58:36.496 P00  DEBUG:     command/exit::exitSafe: => 82
2023-09-04 16:58:36.496 P00  DEBUG:     main::main: => 82

psql (14.9 (Ubuntu 14.9-0ubuntu0.22.04.1))
Type "help" for help.

postgres=# show archive_command;
              archive_command              
-------------------------------------------
 pgbackrest --stanza=local archive-push %p
(1 row)

postgres=# show archive_mode;
 archive_mode 
--------------
 on
(1 row)

postgres=# show listen_addresses;
 listen_addresses 
------------------
 localhost
(1 row)

postgres=# show max_wal_senders;
 max_wal_senders 
-----------------
 10
(1 row)

postgres=# show wal_level;
 wal_level 
-----------
 logical
(1 row)

postgresql.log reads:

ERROR: [082]: unable to push WAL file '000000010000000000000079' to the archive asynchronously after 60 second(s)
       HINT: check '/var/log/pgbackrest/local-archive-push-async.log' for errors.
2023-09-04 17:15:44.122 EEST [7204] LOG:  archive command failed with exit code 82
2023-09-04 17:15:44.122 EEST [7204] DETAIL:  The failed archive command was: pgbackrest --stanza=local archive-push pg_wal/000000010000000000000079
WARN: configuration file contains invalid option 'archive-push-timeout'

pgbackrest.conf reads:

[global]
archive-async=y
repo1-type=sftp  
repo1-sftp-host=someuser.your-storagebox.de 
repo1-sftp-host-user=someuser
repo1-sftp-host-port=23
repo1-sftp-host-key-hash-type=sha1 
repo1-sftp-private-key-file=/var/lib/postgresql/.ssh/id_rsa 
repo1-sftp-public-key-file=/var/lib/postgresql/.ssh/id_rsa.pub
repo1-retention-full=3
repo1-path=/home/backup/pgbackrest
spool-path=/var/spool/pgbackrest
[global:archive-get]
process-max=2
 
[global:archive-push]
process-max=4

[local]
pg1-path=/var/lib/postgresql/14/main
pg1-user=postgres

local-backup.log file reads:
-------------------PROCESS START-------------------
2023-09-04 17:23:17.451 P00   INFO: backup command begin 2.47: --exec-id=10087-7d0699d8 --pg1-path=/var/lib/postgresql/14/main --pg1-user=postgres --repo1-path=/home/backup/pgbackrest --repo1-retention-full=3 --repo1-sftp-host=u365283.your-storagebox.de --repo1-sftp-host-key-hash-type=sha1 --repo1-sftp-host-port=23 --repo1-sftp-host-user=u365283 --repo1-sftp-private-key-file=/var/lib/postgresql/.ssh/id_rsa --repo1-sftp-public-key-file=/var/lib/postgresql/.ssh/id_rsa.pub --repo1-type=sftp --stanza=local
2023-09-04 17:23:19.499 P00   WARN: no prior backup exists, incr backup has been changed to full
2023-09-04 17:23:19.499 P00   INFO: execute non-exclusive backup start: backup begins after the next regular checkpoint completes
2023-09-04 17:23:20.000 P00   INFO: backup start archive = 000000010000000000000080, lsn = 0/80000028
2023-09-04 17:23:20.000 P00   INFO: check archive for prior segment 00000001000000000000007F
2023-09-04 17:24:21.420 P00  ERROR: [082]: WAL segment 00000001000000000000007F was not archived before the 60000ms timeout
                                    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
                                    HINT: check the PostgreSQL server log for errors.
                                    HINT: run the 'start' command if the stanza was previously stopped.
2023-09-04 17:24:21.420 P00   INFO: backup command end: aborted with exception [082]

**Comment by gred7** [comment]
also running pgbackrest start --stanza=local
doesn't make any difference:
postgres@greg$ pgbackrest start --stanza=local
postgres@greg$ pgbackrest backup --stanza=local
WARN: no prior backup exists, incr backup has been changed to full
ERROR: [082]: WAL segment 000000010000000000000083 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.

**Comment by gred7** [comment]
ERROR: [053]: unable to list file info for path '/home/backup/pgbackrest/archive/local/14-1/0000000100000000': libssh2 error [-43]
       --------------------------------------------------------------------
       If SUBMITTING AN ISSUE please provide the following information:
       
       version: 2.47
       command: backup
       options: --exec-id=11524-65393d2e --log-level-console=debug --pg1-path=/var/lib/postgresql/14/main --pg1-user=postgres --repo1-path=/home/backup/pgbackrest --repo1-retention-full=3 --repo1-sftp-host=u365283.your-storagebox.de --repo1-sftp-host-key-hash-type=sha1 --repo1-sftp-host-port=23 --repo1-sftp-host-user=u365283 --repo1-sftp-private-key-file=/var/lib/postgresql/.ssh/id_rsa --repo1-sftp-public-key-file=/var/lib/postgresql/.ssh/id_rsa.pub --repo1-type=sftp --stanza=local
       
       stack trace:
       storage/sftp/storage.c:storageSftpEvalLibSsh2Error:149:(test build required for parameters)
           ... function(s) omitted ...
       storage/sftp/storage.c:storageSftpList:(trace log level required for parameters)
       storage/iterator.c:storageItrPathAdd:(trace log level required for parameters)
       storage/iterator.c:storageItrNew:(driver: *void, path: {"/home/backup/pgbackrest/archive/local/14-1/0000000100000000"}, level: 4, errorOnMissing: false, nullOnMissing: true, recurse: false, sortOrder: 0, expression: {"^000000010000000000000097-[0-f]{40}(\.gz|\.lz4|\.zst|\.xz|\.bz2){0,1}$"})
       storage/storage.c:storageNewItr:(this: {type: sftp, path: /home/backup/pgbackrest, write: false}, pathExp: {"<REPO:ARCHIVE>/14-1/0000000100000000"}, param.level: 0, param.errorOnMissing: false, param.recurse: false, param.nullOnMissing: true, param.sortOrder: 0, param.expression: {"^000000010000000000000097-[0-f]{40}(\.gz|\.lz4|\.zst|\.xz|\.bz2){0,1}$"}, param.recurse: false)
       storage/storage.c:storageList:(this: {type: sftp, path: /home/backup/pgbackrest, write: false}, pathExp: {"<REPO:ARCHIVE>/14-1/0000000100000000"}, param.errorOnMissing: false, param.nullOnMissing: true, param.expression: {"^000000010000000000000097-[0-f]{40}(\.gz|\.lz4|\.zst|\.xz|\.bz2){0,1}$"})
       command/archive/common.c:walSegmentFind:(storage: {type: sftp, path: /home/backup/pgbackrest, write: false}, archiveId: {"14-1"}, walSegment: {"000000010000000000000097"}, timeout: 60000)
       command/backup/backup.c:backupStart:(backupData: {BackupData})
       command/backup/backup.c:cmdBackup:(void)
       main.c:main:(debug log level required for parameters)
       --------------------------------------------------------------------
2023-09-04 19:02:16.349 P00 DETAIL: statistics: {"socket.client":{"total":1},"socket.session":{"total":1}}
2023-09-04 19:02:16.349 P00   INFO: backup command end: aborted with exception [053]
2023-09-04 19:02:16.349 P00  DEBUG:     command/exit::exitSafe: => 53
2023-09-04 19:02:16.349 P00  DEBUG:     main::main: => 53

**Comment by pgstef** [comment]
Hi,

Before trying to take a backup, you should make sure that the archiving command succeeds, by running the check command.
Turning off asynchronous archiving might help you investigate: archiving errors will then directly come to the PG logs, and you might want to add `log-level-console=debug` to your archive-push configuration to have more info.

If `ERROR: [053]: unable to list file info for path '/home/backup/pgbackrest/archive/local/14-1/0000000100000000': libssh2 error [-43]` is the error you get with the archive command, then it's a system configuration problem. If I read the libssh2 source correctly, that [`[-43]` error](https://github.com/libssh2/libssh2/blob/master/include/libssh2.h#L551) means `LIBSSH2_ERROR_SOCKET_RECV`. So probably failing to get the banner message.

Have you managed to successfully connect over ssh to the sftp host?

**Comment by gred7** [comment]
well, it is now ok, at least the backup process is starting. I am closing this issue. will open another.

**Comment by gred7** [comment]
well, it is now ok, at least the backup process is starting. I am closing this issue. will open another as backup fails to write pg_data.gz file. ( but others written ok)
