### ISSUE TITLE
archive push command question about performance expectation

### ISSUE THREAD

**Issue by ikzelf** [pgbackrest/pgbackrest#2170]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.44

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: rhel8.8

4. Did you install pgBackRest from source or from a package? package

If our scp commands of WAL segments take 0,8s, what could/should we expect of the time reported in the completed message of the push wal? What we see is generally taking 2-3s per wal. (we did enable async push and see a benefit when large batches are run but still we wonder what makes the difference between a manual scp and pgbackrest push times)
Is this kind in difference in execution time (0,8s for scp, 2 to3s for pgbackrest push) to be expected?
If not, do you have suggestions to improve this?

2023-09-05 00:00:37.464 P00   INFO: archive-push command begin 2.44: [pg_wal/00000010000006B100000070] --no-archive-async --exec-id=2653983-1abcba49 --log-level-console=info --log-level-file=info --pg
1-path=/pgs02/data --process-max=1 --repo1-host=p-pgbackrest-cluster --repo1-host-config-path=/etc/pgbackrest/ --repo1-host-user=pgbackrest --stanza=thestanza
2023-09-05 00:00:40.557 P00   INFO: pushed WAL file '00000010000006B100000070' to the archive
2023-09-05 00:00:40.657 P00   INFO: archive-push command end: completed successfully (3194ms)

The backup cluster stores its files on NFS. The performance of scp commands to NFS is a lot worse than compared to local. (to local storage it takes 0,2s to scp a WAL segment)

**Comment by dwsteele** [comment]
pgBackRest performs compression -- scp does not. You can try using a faster compression type like lz4 or zstd, see https://pgbackrest.org/configuration.html#section-general/option-compress-type.

**Comment by ikzelf** [comment]
ha, I forgot about the compression.
This is done during the copy, on the database server I guess. We will first see the impact of a quicker compression method.
maybe compress on the backup server using some scheduled job? How will that impact our recovery options?
If possible I would make that an hourly process to compress all archives that are sure to be completely copied.
Thanks!

**Comment by ikzelf** [comment]
Thanks David,
we tested and go for zst1. A lot less CPU usage and a tiny bit less compression.

**Comment by ikzelf** [comment]
thanks for the recommendation, we tested this and are implementing this now. It's a huge improvement.
