### ISSUE TITLE
Pgbackrest Restore Error - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kimzella** [pgbackrest/pgbackrest#2172]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.27

2. PostgreSQL version:
PostgreSQL 11.15 (Ubuntu 11.15-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Operating System: ;;https://www.ubuntu.com/Ubuntu 20.04.3 LTS;;

5. Did you install pgBackRest from source or from a package?
i installed repo wget -q -O -        https://github.com/pgbackrest/pgbackrest/archive/release/2.27.tar.gz | 

7. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    -
[global]
repo1-host=hostname
repo1-host-user=postgres

[db3]
pg1-path=/var/lib/postgresql/11/
pg1-port=5432
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

8. Describe the issue:

When I restore the last full backup taken with pgbackrest, I get the following error, except this error, the logs do not print any errors. Can you help with this issue? >>> Segmentation fault (core dumped)

postgres@dev-test:~$ pgbackrest --config=/etc/pgbackrest/pgbackrest.conf --stanza=db3 --log-level-console=info --type=immediate restore

2023-09-06 06:54:45.826 P00 INFO: restore command begin 2.27: --config=/etc/pgbackrest/pgbackrest.conf --log-level-console=info --pg1-path=/var/lib/ postgresql/11 --repo1-host=0.0.0.1 --repo1-host-user=postgres --stanza=db3 --type=immediate
Segmentation fault (core dumped)

**Comment by dwsteele** [comment]
2.27 is over three years old and we have fixed many bugs since then (including several in configuration). Please update to 2.47 and let us know if you are still seeing the issue.

**Comment by kimzella** [comment]
We solved the problem by upgrading the version, thank you 👍

**Comment by dwsteele** [comment]
Glad it worked!
