### ISSUE TITLE
strange behavior depending on log levels configured

### ISSUE THREAD

**Issue by gred7** [pgbackrest/pgbackrest#2173]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.47

2. PostgreSQL version:
 PostgreSQL 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?
from source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

wal_level = logical			# minimal, replica, or logical
					# supported by the operating system:
archive_mode = on		# enables archiving; off, on, or always
archive_command = 'pgbackrest  archive-push --stanza=local %p'		# command to use to archive a logfile segment

7. Describe the issue:
ERROR: [041]: unable to open file '/home/backup/pgbackrest/backup/local/20230907-114313F/pg_data/backup_label.gz' for write
       --------------------------------------------------------------------
       If SUBMITTING AN ISSUE please provide the following information:
       
       version: 2.47
       command: backup
       options: --exec-id=65201-4b8f2f8e --log-level-console=debug --log-level-file=debug --pg1-path=/var/lib/postgresql/14/main --pg1-user=postgres --repo1-path=/home/backup/pgbackrest --repo1-retention-full=3 --repo1-sftp-host=u365283.your-storagebox.de --repo1-sftp-host-key-hash-type=sha1 --repo1-sftp-host-port=23 --repo1-sftp-host-user=u365283 --repo1-sftp-private-key-file=/var/lib/postgresql/.ssh/id_rsa --repo1-type=sftp --stanza=local
       
       stack trace:
       storage/sftp/write.c:storageWriteSftpOpen:101:(trace log level required for parameters)
       common/io/write.c:ioWriteOpen:(trace log level required for parameters)
       storage/storage.c:storagePut:(file: {type: sftp, name: /home/backup/pgbackrest/backup/local/20230907-114313F/pg_data/backup_label.gz, modeFile: 0640, modePath: 0750, createPath: true, syncFile: true, syncPath: false, atomic: true}, buffer: {used: 260, size: 260})
       command/backup/backup.c:backupFilePut:(backupData: {BackupData}, manifest: {Manifest}, name: {"backup_label"}, timestamp: 1694076876, content: {"START WAL LOCATION: 0/D7000028 (file 0000000100000000000000D7)
       CHECKPOINT LOCATION: 0/D7000060
       BACKUP METHOD: streamed
       BACKUP FROM: primary
       START TIME: 2023-09-07 11:43:13 EEST
       LABEL: pgBackRest backup started at 2023-09-07 11:43:13.64083+03
       START TIMELINE: 1
       "})
       command/backup/backup.c:backupStop:(backupData: {BackupData}, manifest: {Manifest})
       command/backup/backup.c:cmdBackup:(void)
       main.c:main:(debug log level required for parameters)
       --------------------------------------------------------------------
2023-09-07 11:54:36.421 P00 DETAIL: statistics: {"socket.client":{"total":2},"socket.session":{"total":2}}
2023-09-07 11:54:36.421 P00   INFO: backup command end: aborted with exception [041]
2023-09-07 11:54:36.421 P00  DEBUG:     command/exit::exitSafe: => 41
2023-09-07 11:54:36.421 P00  DEBUG:     main::main: => 41

Interestingly, it seems to be able to have written files on the server, but this one.

what's even more interesting it fails to write another file if I try to change log level:

~$ pgbackrest backup --stanza=local --log-level-console=error
WARN: no prior backup exists, incr backup has been changed to full
ERROR: [041]: unable to open file '/home/backup/pgbackrest/backup/local/20230907-121531F/backup.manifest.copy' for write

the files are always the same for log levels:
 pg_data/backup_label.gz  - for log-level-console=debug
 backup.manifest.copy - for all other log levels.

all works. when i am backing up locally.

**Comment by jreidthompson** [comment]
This branch attempts to dump the libssh2 error when libssh2_sftp_open_ex() fails. Could you post the log information from using it?  Do you have access to the sftp host such that you could check the pgbackrest logs on it and it's ssh/sftp server logs?

Thanks
https://github.com/jreidthompson/pgbackrest/tree/pr2173-dev

**Comment by gred7** [comment]
i switched from sftp to cifs mounted backup disc. so now it is ok.
