### ISSUE TITLE
Setup with PGPool2 cluster

### ISSUE THREAD

**Issue by Deltahedron** [pgbackrest/pgbackrest#2178]
I searched for any info on how to configure a PGPool2 cluster with pgBackRest and deal with changing primary node but came up empty handed other than this issue from a while back: https://github.com/pgbackrest/pgbackrest/issues/333
So I'm posting this for anyone who might have a similar setup.

My use case was:
- a HA cluster with 1 primary and 1 secondary node
- using a Floating/Virtual IP(VIP) and streaming replication
- installing pgBackRest on the DB nodes
- archive WAL and backup primary to S3
 
The primary nodes switches during a failover and I had some issues with configuring the pgbackrest.conf file to always point to the primary and whether I should have SSH connectivity between the nodes for PGBackrest and include them in my conf. After a bunch of testing I settled on the most simple approach and it seems to fit my needs.

The pgBackRest gets installed and configured with Ansible identically on both nodes and both node postgres.conf archive_command is set to ```pgbackrest --stanza=primary archive-push %p```.

The pgbackrest.conf is simple:
```
[primary]
pg1-path={{ postgres_data_directory }}

[global]
# keep last 7 full backups
repo1-retention-full=7
repo1-type=s3
repo1-path=/pgbackrest
repo1-s3-region={{ aws_region }}
repo1-s3-endpoint=s3.{{ aws_region }}.amazonaws.com
repo1-s3-bucket={{ aws_s3_backup_bucket_name }}
repo1-s3-key-type=auto
repo1-s3-role={{ aws_db_role_name }}
repo1-cipher-type=aes-256-cbc
repo1-cipher-pass={{ backup_encryption_password }}
repo1-block=y
repo1-bundle=y

# Force a checkpoint to start backup immediately.
start-fast=y
# Use delta restore.
delta=y

compress-type=gz
compress-level=6

log-level-console=info
log-level-file=debug
```

The config only references the primary node (WAL archiving) and during normal execution the secondary has no reason to use pgBackRest so after the failover it will correctly refer to itself as the primary.

For taking the backup on the correct node I added some checks from PGPool2 to make sure the script was ran on primary node something like this:
```pcp_node_info -h 127.0.0.1 -w -p 9898 -n $NODEID 2> /dev/null | grep "primary"```

Note I've yet to implement pgBackRest to my PGPool2 failover procedure and it's used purely for backups.

Hope this helps and if any developers can spot some obvious issues with this setup I'd appreciate some feedback.

**Comment by dwsteele** [comment]
This looks like a reasonable config to me. Another way to determine whether to run backups is to check pg_is_standby() via psql, but your way looks fine, and is arguably better in the case of split brain (assuming there is some sort of fencing going on here).
