### ISSUE TITLE
What kind of data in backup and archive folder

### ISSUE THREAD

**Issue by Welson-Yang** [pgbackrest/pgbackrest#2179]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
Will update if required
2. PostgreSQL version:
Will update if required
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Will update if required
4. Did you install pgBackRest from source or from a package?
Will update if required
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
Will update if required
7. Describe the issue:
Can anyone tell what data is store in backup and archive folder? If I want to backup/archive the backup files to a extra repo, what files I need to backup? The files in backup folder is enough or need to backup files in backup and archive folder?

**Comment by dwsteele** [comment]
You must copy all the files in the repository. If you pick and choose you will have failures on restore and recovery.
