### ISSUE TITLE
CryptoError: unable to verify certificate presented by 'xxx.blob.core.windows.net:443'

### ISSUE THREAD

**Issue by ocafebabe** [pgbackrest/pgbackrest#2180]
1. pgBackRest version: 2.47

2. PostgreSQL version: 15

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Debian

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:

repo2-type=azure
repo2-azure-account=xxx
repo2-azure-container=pg-backups
repo2-azure-key-type=sas
repo2-azure-key=?sv=2022-11-02&XXXXXX
repo2-path=/
repo2-retention-full=30

2023-09-14 16:21:26.464 P00  DEBUG:     common/io/http/request::httpRequestProcess: retry CryptoError: unable to verify certificate presented by 'xxx.blob.core.windows.net:443': [20] unable to get local issuer certificate

7. Describe the issue:

It seems that pgBackRest is unable to verify Azure's TLS certificate. Is this a known issue? Do I have to provide an actual cert file?

**Comment by dwsteele** [comment]
> Do I have to provide an actual cert file?

No, it just looks like you have not installed the certificates package on your host:
```
apt-get install ca-certificates
update-ca-certificates
```

**Comment by ocafebabe** [comment]
Indeed, thanks a lot @dwsteele that did the trick!

This is a vanilla container, so I guess it isn't installed by default.

**Comment by dwsteele** [comment]
> This is a vanilla container, so I guess it isn't installed by default.

Exactly. I pulled this from one of our container installs.
