### ISSUE TITLE
Pgbackrest for Solaris 11.4

### ISSUE THREAD

**Issue by sd7s** [pgbackrest/pgbackrest#2183]
How to compile version for sparc Solaris 11.4 ?

gmake: *** [Makefile:296: .build/command/server/server.o] Error 1

**Comment by dwsteele** [comment]
You did not provide the error message here. What is it?

**Comment by sd7s** [comment]
Has anyone tried to compile the project under sparc solaris 11.4?
During compilation I receive an error message. (In the attachment Pgb_make)
[pgb_make.txt](https://github.com/pgbackrest/pgbackrest/files/12682216/pgb_make.txt)
![Pgb_make](https://github.com/pgbackrest/pgbackrest/assets/22980587/993a050a-e7a8-418d-8526-f9a244b5e5ff)
[pgb_conf.txt](https://github.com/pgbackrest/pgbackrest/files/12682219/pgb_conf.txt)

**Comment by dwsteele** [comment]
Try adding `#include <signal.h>` to `src/command/server/server.c`.

**Comment by sd7s** [comment]
After adding  #include <signal.h> 
![IMG_0248](https://github.com/pgbackrest/pgbackrest/assets/22980587/89644354-086d-41cc-8ffa-976ae50c374f)

**Comment by dwsteele** [comment]
OK -- you are likely missing a header but I don't know which one. If you can figure it out submit a PR and we'll add it to `server.c`.
