### ISSUE TITLE
New S3 bucket for a running Prod instance

### ISSUE THREAD

**Issue by mattbunter** [pgbackrest/pgbackrest#2185]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.41
2. PostgreSQL version:
13.8
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 20.04
4. Did you install pgBackRest from source or from a package?
Package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
We need to change the S3 bucket (non-WORM bucket, we need to use WORM).
Would appreciate clarification on the quickest method of doing this, to avoid large downtime.
Our idea : 
pgbackrest stop, modify pgbackrest.conf with new bucket, pgbackrest start, pgbackrest create-stanza (can use same name as existing stanza). And we should be good to go, no need to stop the Postgresql cluster?
Can you confirm that this is 'the way'?
Thank you.

**Comment by dwsteele** [comment]
You'll get errors in the Postgres log no matter how you do this, so there's not real need to stop/start (though you can if you like). Otherwise, this looks fine.

WORM buckets are not supported by pgBackRest, though. Have you tested that?

**Comment by mattbunter** [comment]
Yes. 
Sometimes it works well. Sometimes it doesn't (https://github.com/pgbackrest/pgbackrest/issues/1899) - my apologies for not replying to you. We actually created a non-WORM bucket and the backups worked.
The majority of our S3 buckets are WORM and backups do work, restores also work. Performance isn't great though.

**Comment by mattbunter** [comment]
version enabled and object lock mode compliance

**Comment by dwsteele** [comment]
> version enabled and object lock mode compliance

OK, good to know. Getting pgBackRest to work on a strictly write-only bucket is a pretty big project, and I'm not sure it is even the right way top go given these settings are becoming widely available.

Our current plan is to determine the best settings available for each service, then give pgBackRest a "wayback" feature so you can restore from the repo at any point in time. This will handle the case where the repo has been tainted by later action and you want to get back to a point in the repo that is known good.

**Comment by mattbunter** [comment]
Sounds good.
