### ISSUE TITLE
Database size not match with source database after restore

### ISSUE THREAD

**Issue by Welson-Yang** [pgbackrest/pgbackrest#2187]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
Will provide if need
2. PostgreSQL version:
Will provide if need
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Will provide if need
4. Did you install pgBackRest from source or from a package?
Will provide if need
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I have a postgresql with 10 database in it, now I do a full backup and restore in a new postgresql, restore successfully and all 10 database can show in new postgresql，but when I use \l+ to list database info, I noticed that some database size is difference in old and new postgresql, I wonder why this happen?

**Comment by dwsteele** [comment]
Database sizes are updated by vacuum, so that might account for the difference. Also, unlogged tables are not included in backups, so if you have any of those that will also make a difference.

You haven't given any details, so not much more I can say.
