### ISSUE TITLE
Backup Fails | WAL segment 000... was not archived before the 60000ms timeout

### ISSUE THREAD

**Issue by vit-h** [pgbackrest/pgbackrest#2188]
1. pgBackRest version: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-2

2. PostgreSQL version: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-15.3-3.3-2

3. Operating system/version: AKS

4. Did you install pgBackRest from source or from a package? container

5. Please attach the following as applicable:
Not sure how to get it all but here is all I have here: https://github.com/CrunchyData/postgres-operator/issues/3725

7. Describe the issue: Please help me to enable Partial and Full backups and syncronize replicas.
Not sure It is a bug or my misconfig.
Please see logs and commands output here: https://github.com/CrunchyData/postgres-operator/issues/3725

Duplicating logs here:
[Explore-logs-2023-09-20 22_57_42.txt](https://github.com/pgbackrest/pgbackrest/files/12679943/Explore-logs-2023-09-20.22_57_42.txt)

**Comment by dwsteele** [comment]
Based on your updates in the other issue this doesn't really look like a pgBackRest problem, but this error indicates an issue with archiving:
```
WAL segment 00000013000000CA00000049 was not archived before the 60000ms timeout
HINT: check the archive_command to ensure that all options are correct (especially --stanza).
HINT: check the PostgreSQL server log for errors.
HINT: run the 'start' command if the stanza was previously stopped.
```
Did you follow up on all the hints?

**Comment by tribock-ix** [comment]
had the same issue. after changing the setting of the archive-timeout to 3600 the backup loops at:

2023-10-19 13:33:47.197 P00  DEBUG:     storage/iterator::storageItrNew: => {stack: {size: 0}}
2023-10-19 13:33:47.197 P00  DEBUG:     storage/storage::storageNewItr: => {stack: {size: 0}}
2023-10-19 13:33:47.197 P00  DEBUG:     storage/storage::storageList: => {[]}
2023-10-19 13:34:24.897 P00  DEBUG:     storage/storage::storageList: (this: {type: posix, path: /pgbackrest/repo1, write: false}, pathExp: {"<REPO:ARCHIVE>/13-1/00000031000006A2"}, param.errorOnMissing: false, param.nullOnMissing: true, param.expression: {"^00000031000006A20000002F-[0-f]{40}(\.gz|\.lz4|\.zst|\.xz|\.bz2){0,1}$"})

**Comment by dwsteele** [comment]
Then your archiving is erroring or falling behind. Check the Postgres log for errors and if there are none you should look at https://pgbackrest.org/user-guide-rhel.html#async-archiving and probably increase `process-max`.
