### ISSUE TITLE
build error pgBackRest 2.48dev 

### ISSUE THREAD

**Issue by ophilon** [pgbackrest/pgbackrest#2189]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.48dev
2. PostgreSQL version:
not applicable
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Linux ophils 6.2.0-33-generic #33-Ubuntu SMP PREEMPT_DYNAMIC Tue Sep  5 14:49:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
4. Did you install pgBackRest from source or from a package?
source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
my build process:

```
mkdir build && cd build
../src/configure && make
```

error build : ./build-code postgres ../src
ERROR: [055]: unable to open missing file '/home/local/src/postgresql/pgbackrest/src/src/postgres/interface/version.vendor.h' for read
       storage/posix/read.c:storageReadPosixOpen:82:(trace log level required for parameters)
       common/io/read.c:ioReadOpen:(trace log level required for parameters)
       storage/storage.c:storageGet:(debug log level required for parameters)
       build/main.c:main:(debug log level required for parameters)
make: *** [Makefile:257: postgres/interface.auto.c.inc] Error 55

The obvious error in double src in **pgbackrest/src/src/postgres**
Simple fix : cd ../src; ln -s . src
However, can't find where this double src/src  came from

**Comment by dwsteele** [comment]
Looks like a problem with the vpath build. We'll have a look at it when we get a chance, but for now you can use your hack or build in `src`.

**Comment by dwsteele** [comment]
We have now deprecated the autoconf/make builds. Try building with meson and let us know if you run into the same issue.
