### ISSUE TITLE
ERROR [125]: unable to acquire restore lock

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#219]
At the end of doing a pgbackrest restore from a slave, where pgbackrest backups are located on the master, I get this error (including last couple lines before it):

2016-07-24 09:00:45.290 T01   INFO: restore file /pgdata/lenderx2/base/1/11973 (0B)
2016-07-24 09:00:45.331 T03   INFO: restore file /pgdata/lenderx2/base/1/11897 (0B)
  2016-07-24 11:52:39.853 T03  ERROR: [125]: remote process terminated: 
                                         <shows company ssh banner here>
                                           ERROR [125]: unable to acquire restore lock

I see the code where this is generated (Lock.pm.lockAcquire method):

# Attempt to open the lock file
  $strCurrentLockFile = lockFileName($strLockType, optionGet(OPTION_STANZA, false), $bRemote, $iProcessIdx);

  sysopen($hCurrentLockHandle, $strCurrentLockFile, O_WRONLY | O_CREAT, oct(640))
      or confess &log(ERROR, "unable to open lock file ${strCurrentLockFile}", ERROR_FILE_OPEN);

  # Attempt to lock the lock file
  if (!flock($hCurrentLockHandle, LOCK_EX | LOCK_NB))
  {
      close($hCurrentLockHandle);

      if (!defined($bFailOnNoLock) || $bFailOnNoLock)
      {
          confess &log(ERROR, "unable to acquire ${strLockType} lock", ERROR_LOCK_ACQUIRE);

I guess I'm wondering if this indicates an SSH problem problem that occurs at the end of a restore and aborts before pgbackrest writes out a recovery.conf file in the slave's data directory.

And what is the purpose of this ssh command at the end if it is indeed an ssh command?  Now I am using postgres as the backup user and ssh using postgres user between master and slave works fine, but is it perhaps doing something with the replication user, replicator

Here is the slave's pgbackrest.conf file:

[global]
repo-path=/pgdata/pgbackrest
start-fast=y
stop-auto=y
archive-check=y
buffer-size=8388608
compress=y
thread-max=4
thread-timeout=3600
log-level-file=info
link-all=y
backup-host=msp<my haha>021
backup-user=postgres

[lenderx2]
db-path=/pgdata/lenderx2
db-port=5433
log-path=/pgdata/pgbackrest/log/lenderx2
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=10.80.129.22 port=5433 user=replicator

So the context is me syncing up a slave from scratch again.  So on the slave I do the following:
pg_ctlcluster 9.4 lenderx2 stop

-- clear out data directory, user tablespace, and separately located pg_xlog directories
find /pgdata/lenderx2 -mindepth 1 -delete;find /pgdata-qcr_tblspace/lenderx2 -mindepth 1 -delete;find /pgxlog/lenderx2 -mindepth 1 -delete

-- start a delta restore which will turn into a full restore by default since nothing is there anymore
 pgbackrest --stanza=lenderx2 --delta restore --log-level-console=info

Then I get the errors at the end.  

It seems to attempt the action whatever it was a few more times before you get this error:
                                           ERROR [125]: unable to acquire restore lock
Thread 3 terminated abnormally: main=HASH(0x7ff41582e2a0) at /usr/share/perl5/pgBackRest/Protocol/ThreadGroup.pm line 53.

**Comment by dwsteele** [comment]
I think I know what is causing this but I have not been able to reproduce it yet.  Your configuration is unusual (repo on master with remote standby) so it is not covered by the standard regression tests.

If you are in an environment where you feel comfortable testing you can try this branch:
https://github.com/pgbackrest/pgbackrest/compare/dev-010-remotebug

It has what I believe is the fix plus a bit more verbose debugging of the lock conflict.  If that works then I'll know how this needs to be tested.  If it doesn't work we'll have more information.

Thanks!

**Comment by MichaelDBA** [comment]
Can I just do the delta restore with your changes or do I have to do the full backup again, since i see changes above to Backup.pm?

btw, the final target is pgbackrest repo on the slave and pulling backups from the slave once the new version comes out.

**Comment by dwsteele** [comment]
Yes, you can try just the restore with these changes, no need to do a new backup.

You can store the backups on the standby now, just set db-host to the master.  Then when the new version comes out you would just set backup-standby=y and you would be backing from the standby (and still storing the repo on the standby).  This is the usual configuration when a backup server is not available.

**Comment by MichaelDBA** [comment]
Still aborts, here are the last few lines after updating the pbbackrest files as directed:
2016-07-26 06:40:09.479 T03 DETAIL: restore file /pgdata/lenderx2/pg_tblspc/16445/PG_9.4_201409291/64994208/141816238 - exists and is zero size (0B)
2016-07-26 06:40:09.479 T03  DEBUG:     File->exists(): strPath = /pgdata/lenderx2/pg_tblspc/16445/PG_9.4_201409291/64994208/141738532, strPathType = db:absolute
2016-07-26 06:40:09.480 T03  DEBUG:     File->exists=>: bExists = true
2016-07-26 06:40:09.480 T03  DEBUG:     File->hashSize(): bCompressed = <false>, strFile = /pgdata/lenderx2/pg_tblspc/16445/PG_9.4_201409291/64994208/141738532, strHashType = <sha1>, strPa thType = db:absolute
2016-07-26 06:40:09.480 T03  DEBUG:     File->hashSize=>: iSize = 0, strHash = da39a3ee5e6b4b0d3255bfef95601890afd80709
2016-07-26 06:40:09.480 T03 DETAIL: restore file /pgdata/lenderx2/pg_tblspc/16445/PG_9.4_201409291/64994208/141738532 - exists and is zero size (0B)
2016-07-26 06:40:09.481 T04  DEBUG:     File->hashSize=>: iSize = 1875968, strHash = 0516d0a9c81ee9d47eed0ce6a11ad9067f49fde0
2016-07-26 06:40:09.481 T04 DETAIL: restore file /pgdata/lenderx2/pg_tblspc/16445/PG_9.4_201409291/64994208/139970807 - exists and matches backup (1.7MB) checksum 0516d0a9c81ee9d47eed0ce6a 11ad9067f49fde0
2016-07-26 06:40:09.484 T03  ERROR: [141]: remote process terminated: ******************************************************************************
                                           ** PLEASE READ THIS NOTICE PRIOR TO PROCEEDING. THIS IS AN ASSURANT SYSTEM. **
                                           ******************************************************************************
                                                   blah blah blah
                                           ******************************************************************************
                                           ERROR [141]: unable to read line after 1830 seconds
2016-07-26 06:40:09.484 T04  ERROR: [141]: remote process terminated: ******************************************************************************
                                           ** PLEASE READ THIS NOTICE PRIOR TO PROCEEDING. THIS IS AN ASSURANT SYSTEM. **
                                           ******************************************************************************
                                                   blah blah blah
                                           ******************************************************************************
                                           ERROR [141]: unable to read line after 1830 seconds
Thread 3 terminated abnormally: main=HASH(0x9375200) at /usr/share/perl5/pgBackRest/Protocol/ThreadGroup.pm line 53.
Thread 4 terminated abnormally: main=HASH(0x383d6d0) at /usr/share/perl5/pgBackRest/Protocol/ThreadGroup.pm line 53.
2016-07-26 06:40:09.546 T00  ERROR: error in thread3: remote process terminated: ******************************************************************************
                                           ** PLEASE READ THIS NOTICE PRIOR TO PROCEEDING. THIS IS AN ASSURANT SYSTEM. **
                                           ******************************************************************************
                                                   blah blah blah
                                           ******************************************************************************
                                           ERROR [141]: unable to read line after 1830 seconds
2016-07-26 06:40:09.721 T00  DEBUG:     Exit::exitSafe(): iExitCode = 199, strSignal = [undef]
2016-07-26 06:40:09.722 T00   INFO: restore stop
2016-07-26 06:40:09.722 T00  DEBUG:     stop 4 threads
2016-07-26 06:40:09.828 T01  ERROR: [141]: remote process terminated: ******************************************************************************
                                           ** PLEASE READ THIS NOTICE PRIOR TO PROCEEDING. THIS IS AN ASSURANT SYSTEM. **
                                           ******************************************************************************
                                                   blah blah blah
                                           ******************************************************************************
                                           ERROR [141]: unable to read line after 1830 seconds
2016-07-26 06:40:09.830 T01   WARN: unable to shutdown protocol [141]: remote process terminated: ******************************************************************************
                                    ** PLEASE READ THIS NOTICE PRIOR TO PROCEEDING. THIS IS AN ASSURANT SYSTEM. **
                                    ******************************************************************************
                                                   blah blah blah
                                    ******************************************************************************
                                    ERROR [141]: unable to read line after 1830 seconds
                                    HINT: the process completed successfully but protocol-timeout may need to be increased.
Thread 1 terminated abnormally: main=HASH(0x7b5bc08) at /usr/lib/perl/5.14/threads.pm line 101.
2016-07-26 06:40:09.938 T02  ERROR: [141]: remote process terminated: ******************************************************************************
                                           ** PLEASE READ THIS NOTICE PRIOR TO PROCEEDING. THIS IS AN ASSURANT SYSTEM. **
                                           ******************************************************************************
                                                   blah blah blah
                                           ******************************************************************************
                                           ERROR [141]: unable to read line after 1830 seconds
2016-07-26 06:40:09.939 T02   WARN: unable to shutdown protocol [141]: remote process terminated: ******************************************************************************
                                    ** PLEASE READ THIS NOTICE PRIOR TO PROCEEDING. THIS IS AN ASSURANT SYSTEM. **
                                    ******************************************************************************
                                                   blah blah blah
                                    ******************************************************************************
                                    ERROR [141]: unable to read line after 1830 seconds
                                    HINT: the process completed successfully but protocol-timeout may need to be increased.
Thread 2 terminated abnormally: main=HASH(0x87698d0) at /usr/lib/perl/5.14/threads.pm line 101.
2016-07-26 06:40:10.278 T00  DEBUG:     Common:::Lock::lockRelease(): bFailOnNoLock = false

**Comment by dwsteele** [comment]
Is that the very end of the log?  Also, you seem to have run this test differently - the files were not deleted first.

Lastly, what distro/version are you running?

**Comment by MichaelDBA** [comment]
Yes, that is the very end of the log.  Also, the files were not deleted first, figured I would save some time with just doing a delta restore using local checksums to get back to where it failed.  But I will clear out files and redo the test.  

This is Debian Wheezy distro.

**Comment by dwsteele** [comment]
OK, I'm not currently testing on Wheezy, only Jessie.  Some platforms are less stable and what we are seeing in that last run is a crash in the threading layer at /usr/lib/perl/5.14/threads.pm line 101.  This can happen on any platform but is more common on some.

However, those warnings shouldn't be happening either, and I see now see what is going on there.

**Comment by MichaelDBA** [comment]
So the restore worked this time with your modified code, YEEEE HAAAAAAAAA!!!!! slave is now started and streamin from da masta.

What patch fix will this be in?

2016-07-26 10:29:47.863 T00  DEBUG:     File->owner(): strFile = /pgdata/lenderx2/global/pg_control.backrest.tmp, strGroup = postgres, strPathType = absolute, strUser = postgres
2016-07-26 10:29:47.869 T00   INFO: restore file /pgdata/lenderx2/global/pg_control (8KB) checksum f73e72513bc9498756850170bdc1fef080fc627f
2016-07-26 10:29:47.869 T00  DEBUG:     File->remove(): bIgnoreMissing = false, bTemp = [undef], strPath = /pgdata/lenderx2/backup.manifest, strPathType = db:absolute
2016-07-26 10:29:47.869 T00  DEBUG:     File->remove=>: bRemoved = true
2016-07-26 10:29:47.983 T00  DEBUG:     Exit::exitSafe(): iExitCode = 0, strSignal = [undef]
2016-07-26 10:29:47.983 T00   INFO: restore stop
2016-07-26 10:29:47.983 T00  DEBUG:     stop 4 threads
2016-07-26 10:29:48.496 T00  DEBUG:     Common:::Lock::lockRelease(): bFailOnNoLock = false

**Comment by MichaelDBA** [comment]
I'm closing this since the patch worked and the new code should be available in 1.04.

**Comment by dwsteele** [comment]
Glad that worked.  I consider this to be a serious bug so I'm preparing a new release now which will go out tomorrow.

As to the warnings you saw above, I have a fix for those as well on the `dev-025-rmterr` branch.  I think the crash in threading library may be due to handling exceptions in the threads making them less stable.  I've fixed the protocol timeout and that should keep those warnings from coming up.

If you could test the `dev-025-rmterr` *without* cleaning out the directories that would be great. That will test if the new fix works with the issue you saw last night.

**Comment by MichaelDBA** [comment]
Ok, now I'm gonna sound stupid, since I'm not a perl programmer (me likes the big snake).
If I download that branch, dev-025-rmterr, how does pgbackrest know how to get to the right pm modules in the download directory as opposed to finding them in /usr/share/perl5/pgBackRest/ where they were package installed?

**Comment by dwsteele** [comment]
You would have to install it per the normal installation instructions.

**Comment by dwsteele** [comment]
No worries if you are not comfortable doing that.

**Comment by dwsteele** [comment]
I was able to reproduce both of these issues (finally) so there's no need for you to do any testing.  I appreciate all your help tracking these down.

**Comment by dwsteele** [comment]
v1.04 has been released: https://github.com/pgbackrest/pgbackrest/releases/tag/release/1.04
