### ISSUE TITLE
[restoration] slow speed with one of the replicas.

### ISSUE THREAD

**Issue by Dboy-Even** [pgbackrest/pgbackrest#2192]
This issue is in relation to issue #2066, as the problem seems common.

1. pgBackRest version: 2.40

2. PostgreSQL version:
`psql (PostgreSQL) 13.9 - Percona Distribution (Debian 2:13.9-1.bullseye)`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
`debian 11`

4. Did you install pgBackRest from source or from a package? 
`build from source : `[release 2.40](https://github.com/pgbackrest/pgbackrest/tree/release/2.40)
```
/usr/bin/pgbackrest:  ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=ce8af0322d44dedc7d4fc0793f0c0006f3180bf4, for GNU/Linux 3.2.0, not stripped
```
The binary has then been copied over to all hosts.

5. Please attach the following as applicable:
- `pgbackrest.conf`:
```
[prod]
db-path=/var/lib/postgresql/13/main

[global]
compress-level=3
compress-type=lz4
start-fast=y
process-max=6
archive-async=y
archive-get-queue-max=100G

repo1-host=pgbr
repo1-host-type=tls
repo1-host-port=xxx
[...]
repo1-bundle=y

tls-server-address=*
tls-server-port=xxxx
[...]
tls-server-auth=replica2=prod
tls-server-auth=pgbr=prod
```

I do not feel the rest useful, as everything happens without PostgreSQL running. Please — ask if required.

7. Describe the issue:

During the preparation of a migration to PostgreSQL 15, I have used one of the `replica` as a test environment (replica2).
 
I have daily backups of the prod environment (still running as of today).
As my test are almost completed, I wiped everything and performed a full restoration of the node :
`time pgbackrest --stanza=prod restore --type=standby`
I must have stopped the restoration a couple of hours after that:
```
postgres@s21:~$ ps -p 420480 -o lstart,etime                                                                                   
                 STARTED     ELAPSED                                                                                           
Mon Sep 25 14:10:46 2023    22:43:04  
```
The idea was mostly to estimate before the upgrade the time needed post-upgrade to restore the replicas.
During that time, `1.5To` were restored, of a total of `2.5To`

everything is stored on a ZFS cluster (3*2 mirror span, block size 16k, compression lz4)

the network, while not being ideal, is a work in progress:
- infra1
  - master
  - replica1
  - replica2
- infra2
  - restore1
  - pgbr

The node `restore1` and `pgbr` are both Proxmox LXC stored on ZFS dataset.
`pgbr's` storage data is actually stored on a GlusterFS network storage inside `infra2`. (hence the `repo1-bundle=y` option)
`restore1` postgres data is configured with `zstd-6` compression.

ping between `restor1's` host and `replica2` is (over 7 pings) :
`rtt min/avg/max/mdev = 0.266/0.499/0.604/0.111 ms`

While the restoration on `replica2` was canceled after 23 hours and 1.5To of data.
The restoration on `restore1` took :
```
time pgbackrest --stanza=prod restore --type=standby

real    133m2.545s
user    51m50.747s
sys     16m16.455s
```

Though they are on the same network, they are also using TLS communication (same configuration).

Finally, once this restoration performed. I stopped `restor1`, performed a snapshot, and sent it over to `replica2`.
That transfer, still occurred from `infra2` to `infra1.replica2` but using ZFS send features.
That transfer occurred at : 
```
root# zfs send -ce subvol-613-disk-0@restoration_prod |pv -s 370911964464 | ssh replica2 'zfs recv -x compression -x recordsize -x keylocation -x encryption -x atime -x xattr -x primarycache storage/postgres/s21'
 347GiB 0:27:12 [ 217MiB/s] [==============================================================================================================================================================================================================>] 100%
 ```

Hence, In two hours and a half, I was able to fully restore and transfer the database over to `replica2`

What I don't understand :
- `pgbr` GlusterFS storage was *not* the limiting factor.
  - `pgbackrest` performed *admirably* restoring the data.
- `replica2` network and storage *weren't* limiting either.
  - During `replica2's` initial restoration, I could see the pgbackrest process in `D` state (same as #2066)
    - `iostat` during had spikes at 1 GB/sec, with an average at 30 MB/sec
  - Yet, the ZFS transfer over SSH happened at more than 200 MB/sec
    - `iostat` during had spikes at 800 MB/sec, with an average at 400 MB/sec
    - because of ZFS compression, written data are bigger than the one being sent.
- As is, *it's no-one's fault*, yet it is apparently impossible to viably fully restore from scratch.
  - I have yet to perform a `delta` restoration on the recovered data to correctly set `replica2` as a replica.

I am guessing something happened on `replica2`, I will post an update after performing the `delta restore`.

Would any of you have an idea or advice of where to start digging for a culprit?

Thank you for reading me. (and, in advance, for your response :stuck_out_tongue: ).

Regards,
Even

**Comment by dwsteele** [comment]
> While the restoration on replica2 was canceled after 23 hours and 1.5To of data.

Yes, that's absolutely terrible. Restore should be > 1TiB per hour even on a basic setup.

> During replica2's initial restoration, I could see the pgbackrest process in D state 

I guess the question is, why was the pgbackrest process in D state? There's nothing here to help us determine this. `iostat` output during the restore would be helpful. My guess is `%iowait` was high, but there's no way to know for sure with the information given.

> As is, it's no-one's fault, yet it is apparently impossible to viably fully restore from scratch.

Well, it definitely *is*, but obviously not on this host (`replica2`) as configured. So what is the difference between `replica2` and `restore1`? If you are getting different results with the same version of pgbackrest, my bet is on some difference in the host/storage/something.
