### ISSUE TITLE
Create patch to skip the storage/sftp unit test without libssh2

### ISSUE THREAD

**Issue by 50wu** [pgbackrest/pgbackrest#2193]
Hi Team,

Thanks for fixing to allow storage/sftp unit test to run without libssh2 installed in the [PR](https://github.com/pgbackrest/pgbackrest/pull/2177).

Recently we tried to use the latest code to run the tests but failed with the following error:

```
 run 2/37 ------------ L0647 error on missing SFTP fingerprint
        000.025s 000.001s L0662     expect OptionRequiredError: archive-push command requires option: repo1-sftp-host-fingerprint
    
    TEST FAILED WITH TestError:
    
    --------------------------------------------------------------------------------
    EXPECTED OptionRequiredError: archive-push command requires option: repo1-sftp-host-fingerprint
    
     BUT GOT OptionInvalidValueError: pgBackRest not built with 'repo1-type=sftp' support
    HINT: if pgBackRest was installed from a package, does the package support this feature?
    HINT: if pgBackRest was built from source, were the required development packages installed?
```
I tried to fix it by applying the following patch to pgbackrest/test/src/module/config/loadTest.c

```
--- loadTest.c  2023-09-28 14:41:23.000000000 +0800
+++ modified_loadTest.c 2023-09-28 14:48:01.000000000 +0800
@@ -644,6 +644,7 @@
         hrnCfgEnvKeyRemoveRaw(cfgOptRepoAzureKey, 1);

         // -------------------------------------------------------------------------------------------------------------------------
+#ifdef HAVE_LIBSSH2
         TEST_TITLE("error on missing SFTP fingerprint");

         argList = strLstNew();
@@ -738,6 +739,7 @@
         TEST_RESULT_UINT(
             cfgOptionIdxStrId(cfgOptRepoSftpHostKeyCheckType, 0), CFGOPTVAL_REPO_SFTP_HOST_KEY_CHECK_TYPE_FINGERPRINT,
             "check type");
+#endif // HAVE_LIBSSH2
     }

     // *****************************************************************************************************************************

```

Could you please make the changes in the code? Thanks.

Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: v2.48

2. PostgreSQL version: 15.4

**Comment by jreidthompson** [comment]
Thank you. I'll put this in. A bit distressed that I missed this, I'm usually overly conscientious about running through the test variations.

**Comment by dwsteele** [comment]
> A bit distressed that I missed this

This is something I added later to fixup the options for know hosts. We don't have any CI tests without SFTP so we're not going to catch these kinds of issues.

**Comment by jreidthompson** [comment]
Addressed in PR https://github.com/pgbackrest/pgbackrest/pull/2194
