### ISSUE TITLE
[FormatError] wal segment size is 67108864 but must be 16777216 for PostgreSQL <= 10

### ISSUE THREAD

**Issue by jianyang1982** [pgbackrest/pgbackrest#2196]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  v2.48

2. PostgreSQL version: v9.6.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
centos 7.9

4. Did you install pgBackRest from source or from a package?
yes
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
 I complied pg9.6.2 with this command
./configure --prefix=/paic/postgres/base/9.6.2 --with-blocksize=8 --with-wal-blocksize=16 --with-uuid=ossp --with-segsize=10 --with-wal-segsize=64  --with-python
I know may be  with-wal-segsize=64  ocur  this error,but it's the product setting。
Can pgbackuprest support this custom parameters "with-wal-segsize"  under 9.6 TO 10  ,Best Regards.
![image](https://github.com/pgbackrest/pgbackrest/assets/25600989/f01c5dac-9264-4ad4-b3e9-4f053184dca3)
pgbackuprest.conf  as follows:
[pg01]
pg01-path=/paic/pg5432/data
pg01-port=5432
pg01-socket-path=/tmp
[global]
repo1-path=/paic/pgbackup/pgbackrest2
backup-user=postgres
retention-full=2
start-fast=y
process-max=3
log-path=/var/log/pgbackrest
[global:archive-push]
compress-level=3
~

**Comment by dwsteele** [comment]
Alternate WAL segment sizes were never properly tested in PG < 11, so we don't support them. Also -- 9.6 has been EOL for the last two years. I recommend updating to a supported version of PostgreSQL that also allows WAL segment sizes to be specified at initdb time.

**Comment by jianyang1982** [comment]
Thank you for your reply。I will use pg_basebackup instead in pg9 and 10.
