### ISSUE TITLE
Is pgbackrest compatible with PostgreSQL 16.0?

### ISSUE THREAD

**Issue by stephane-klein** [pgbackrest/pgbackrest#2198]
Is pgbackrest compatible with PostgreSQL [16.0](https://www.postgresql.org/docs/16/release-16.html)?

In the documentation, where can I see the PostgreSQL version list supported by *pgbackrest*?

**Comment by jreidthompson** [comment]
The release notes for v2.46 indicate support for PostgreSQL 16

https://pgbackrest.org/release.html

**Comment by dwsteele** [comment]
Also see https://pgbackrest.org/#features/postgres-compatibility.
