### ISSUE TITLE
Installation documentation misinformation

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#220]
in the user guide http://www.pgbackrest.org/user-guide.html#installation, it says:
"No Debian/Ubuntu packages are currently available for pgBackRest but it is easy to download the source and install manually."

But I installed it from Debian Wheezy with apt-get install pgbackrest (version 1.02 and then after 1.03 came out and i did an apt-get update, 1.03 was there waiting for me)

**Comment by dwsteele** [comment]
Yeah, it got packaged.  I'll need to update that.
