### ISSUE TITLE
With versioned Bucket on minio retention-full option is not actually removing the data. 

### ISSUE THREAD

**Issue by minalkpatil** [pgbackrest/pgbackrest#2201]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.47
2. PostgreSQL version: 12.9
3. Operating system/version: debian 11
4. Did you install pgBackRest from source or from a package? : Package
5. Describe the issue:
S3 used: Minio.
When the versioned bucket is enabled on minio, repo-retention-full option is just creating the delete marker in the Minio. The objects   are not actually removed. 
I think we should improve the delete function to include the versions as well for complete cleanup.

**Comment by dwsteele** [comment]
I don't think this would make much sense. The purpose of having versions is to use them, e.g. to protect against ransomware, and they are generally expired with life-cycle policies defined on the bucket.

If you are not using the versions then you should disable them.

**Comment by minalkpatil** [comment]
> I don't think this would make much sense. The purpose of having versions is to use them, e.g. to protect against ransomware, and they are generally expired with life-cycle policies defined on the bucket.
> 
> If you are not using versions then you should disable them.

I donot agree with you.
Versioned bucket is requirement for replication of data across different Minio. Replication is an important step for configurating DR strategies. So without versioned bucket same would not simply work.

**Comment by dwsteele** [comment]
Removing versions is still your responsibility. See: https://min.io/docs/minio/linux/administration/object-management/object-lifecycle-management.html#id1

**Comment by pgstef** [comment]
> In my opinion this is bug with pgbackrest

I'd +1 what David said. pgBackRest can't handle all the variety of possibilities offered by all the platforms in the world. If you're using a specific feature of a specific platform, it's up to you to make it work. The main responsibility of pgBackRest is to handle PG backups and recovery, not handle your storage behind de scene imo.

**Comment by matthudsonatx** [comment]
I suspect a documentation change might help new pgBackRest users navigate this one better on their first install. I wouldn't want pgBackRest meddling in my versioning, though. @dwsteele raises a good point about the versioning and replication being potentially entangled under the hood, too.

I definitely created (and deleted) a versioned bucket that got unexpectedly huge the first time I setup pgBackRest. OP has my sympathies.
