### ISSUE TITLE
Can't backup to S3, Error 429

### ISSUE THREAD

**Issue by abadina** [pgbackrest/pgbackrest#2207]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.37
2. PostgreSQL version:
14.2

3. Operating system/version :
Debian-buster

4. Did you install pgBackRest from source or from a package?
From source 

5. Please attach the following as applicable:

logs:

ERROR: [039]: HTTP request failed with 429 (Too Many Requests):
    *** Path/Query ***:
    HEAD /<redacted>/backup.manifest
    *** Request Headers ***:
    authorization: <redacted>
    content-length: 0
    host: <redacted>
    x-amz-content-sha256: <redacted>
    x-amz-date: <redacted>
    *** Response Headers ***:
    cache-control: no-cache
    content-type: application/xml

7. Describe the issue:

I'm using pgbackrest to backup postgres14 to S3 and as we have many queries, we frequently receive the error 429 ( a transient error) .

My question is, does a retry mechanism exist on pgbackrest?
And if not wouldn't it be better to have one ?
Otherwise, how do you think I can manage the error ?

**Comment by dwsteele** [comment]
> My question is, does a retry mechanism exist on pgbackrest?

We have many levels of retries, but we do not retry 429 because it is not clear *when* we should retry. Minutes, hours? To comply with this request, pgBackRest would also need to scale down the resources it is using and that's a pretty big ask.

> Otherwise, how do you think I can manage the error ?

You could try reducing process-max to avoid hitting S3 as hard. Also, definitely enable `repo1-bundle`, which will drastically reduce the number of requests sent to S3.

And you should really upgrade pgBackRest. We are always making bug fixes and improvements.

**Comment by kerams** [comment]
I've noticed the same thing for the first time the other day where a scheduled diff backup to Cloudflare R2 failed:

```
2023-10-20 06:30:01.228 P00   INFO: backup command begin 2.48: --exec-id=2954412-b53c2934 --pg1-path=/var/lib/postgresql/16/main --repo=2 --repo2-bundle --repo2-bundle-limit=50MiB --repo2-bundle-size=100MiB --repo2-path=/ --repo2-retention-full=2 --repo2-s3-bucket=back --repo2-s3-endpoint=https://xxx.r2.cloudflarestorage.com --repo2-s3-key=<redacted> --repo2-s3-key-secret=<redacted> --repo2-s3-region=auto --repo2-s3-uri-style=path --repo2-storage-upload-chunk-size=25MiB --repo2-type=s3 --stanza=testing --type=diff
2023-10-20 06:30:04.022 P00   INFO: last backup label = 20231015-063003F, version = 2.48
2023-10-20 06:30:04.022 P00   INFO: execute non-exclusive backup start: backup begins after the next regular checkpoint completes
2023-10-20 06:30:04.724 P00   INFO: backup start archive = 000000010000000000000029, lsn = 0/29000028
2023-10-20 06:30:04.724 P00   INFO: check archive for prior segment 000000010000000000000028
2023-10-20 06:30:09.037 P00   INFO: execute non-exclusive backup stop and wait for all WAL segments to archive
2023-10-20 06:30:09.437 P00   INFO: backup stop archive = 000000010000000000000029, lsn = 0/29000100
2023-10-20 06:30:10.271 P00   INFO: check archive for segment(s) 000000010000000000000029:000000010000000000000029
2023-10-20 06:30:11.164 P00  ERROR: [039]: HTTP request failed with 429 (Too Many Requests):
                                    *** Path/Query ***:
                                    GET /back/?delimiter=%2F&list-type=2&prefix=archive%2Ftesting%2F16-2%2F0000000100000000%2F000000010000000000000029
                                    *** Request Headers ***:
                                    authorization: <redacted>
                                    content-length: 0
                                    host: xxx.r2.cloudflarestorage.com
                                    x-amz-content-sha256: xxx
                                    x-amz-date: <redacted>
                                    *** Response Headers ***:
                                    cf-ray: 818f35ee28ef0eb0-AMS
                                    connection: keep-alive
                                    content-length: 159
                                    content-type: application/xml
                                    date: Fri, 20 Oct 2023 06:30:11 GMT
                                    server: cloudflare
                                    *** Response Content ***:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>ServiceUnavailable</Code><Message>Reduce your concurrent request rate for the same object.</Message></Error>
```

It's really weird, since this is a tiny (`database size: 45MB`) test database with bundling enabled and default `process-max`. Unless there's a bug in pgbackrest, I wouldn't expect any concurrent access to the bucket, let alone one object. Not sure what to make of that error message from Cloudflare then.

**Comment by dwsteele** [comment]
> According to R2 GraphQL statistics, it would appear the diff backup issued 14 list object, 7 put object, 12 get object and 11 head object requests before being cut short. The day before, when the diff succeeded, it was 21, 16, 24 and 14, respectively.

Those really do not look like big numbers to me. We do pretty aggressively check for the presence of new WAL files during `check archive for segment(s) 000000010000000000000029:000000010000000000000029` using a Fibonacci-type back off, so 100ms, 200ms, 300ms, 500ms, etc. We made this more efficient in 2.48 if we are looking for more than one file, but with one file not much to do but keep trying.

I'm still loathe to put a retry on 429 for the reasons I gave above. Can you send error and statistics  to Cloudflare and see what they say?

**Comment by kerams** [comment]
Yeah, I can try asking on the community forums (I do not have access to prioritized support channels), but the chances that I'll get an official response are low.

Can I be sure that with `process-max=1` there's only 1 S3 request in flight at any given point during a backup?

**Comment by dwsteele** [comment]
There will be more than one, because `archive-push` is also running under PostgreSQL. So, `backup` plus `archive-push` equals two processes that could be listing/writing a single WAL file. Even so, it's pretty ridiculous if that is getting rate limited.

@abadina Are you also on Cloudflare R2?

If you both started getting this error on Cloudflare recently across difference versions of pgBackRest, then I would suspect a change in policy on Cloudflare.

**Comment by adkinsn** [comment]
Is this related to issue 2200?  Ours didn’t involve Cloud flare, but something changed on the update.

**Comment by dwsteele** [comment]
@adkinsn I can't see how #2020 would be related here.

**Comment by dwsteele** [comment]
@adkinsn Ah, sorry, I misread. I doubt these are related -- the symptoms are completely different and this issue also happens on 2.37 (which had presumably been running for a while).

If you'd respond to my information requests or suggestions on your issue we might be able to get it resolved.

**Comment by abadina** [comment]
@dwsteele thank you for the reply . Our process-max is set in 2 , I don't think we can go any low, as for repo1-bundle is not supported in pgbackrest 2.37. We'll plan the upgrades as soon as possible. Meanwhile is there some workaround that we can put in place ?

**Comment by dwsteele** [comment]
> Meanwhile is there some workaround that we can put in place?

You could ask your provider why you are being rate limited. It may have something to do with your account type or something your administrator has configured.
