### ISSUE TITLE
pgbackrest with postgresql in docker

### ISSUE THREAD

**Issue by kmolnef** [pgbackrest/pgbackrest#2210]
Hi

1. pgBackRest version:
-pgBackRest 2.48

2. PostgreSQL version:
-15.4 (docker)

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
-Debian 12.2
-One reposiotory, One PG cluster 

4. Did you install pgBackRest from source or from a package?
- from package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

-on VM on repository
[global]
repo1-path=/BACKUP
repo1-retention-full=2
start-fast=y
process-max=4
log-level-console=info
log-level-file=info

[itx]
pg1-path=/docker/pg/15/pgdata
pg1-host=itx
pg1-port=5434

-on VM with database
[global]
repo1-path=/BACKUP
repo1-host=REPO01

[pg1-server]
pg1-path=/docker/pg/15/pgdata
pg1-port=5434

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
- archive_command - pgbackrest --stanza=itx archive-push %p
- archive_mode - on
- listen_addresses - * (all)
- max_wal_senders - 3
- wal_level - replica
- port - in docker host redirect to 5434, inside the docker 5432

    - errors in the postgresql log file before or during the time you experienced the issue
 CEST [35] postgres-postgres-[local] pgBackRest [stanza-create] LOG:  disconnection: session time: 0:00:00.614 user=postgres database=postgres host=[local]

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
-------------------PROCESS START-------------------
2023-10-24 15:24:35.332 P00   INFO: stanza-create command begin 2.48: --exec-id=1608-6bbab49a --log-level-console=info --log-level-file=info --pg1-host=itx --pg1-path=/docker/pg/15/pgdata --pg1-port=5434 --repo1-path=/BACKUP --stanza=n>
2023-10-24 15:24:36.430 P00   WARN: unable to check pg1: [DbConnectError] raised from remote-0 ssh protocol on 'itx': unable to connect to 'dbname='postgres' port=5434': connection to server on socket "/var/run/postgresql/.s.PGSQL.5434>
                                        Is the server running locally and accepting connections on that socket?
2023-10-24 15:24:36.431 P00  ERROR: [056]: unable to find primary cluster - cannot proceed
                                    HINT: are all available clusters in recovery?
2023-10-24 15:24:36.431 P00   INFO: stanza-create command end: aborted with exception [056]

7. Describe the issue:

I cannot create stanza because socket file cannot be found. How to do that with docker env?any solution?

**Comment by philrhurst** [comment]
How have you configured the passwordless SSH between the repo host and the PG host inside the docker container? You may want to review the documentation section on setting up a Dedicated Repository Host.

- https://pgbackrest.org/user-guide.html#repo-host

You may need to set your `pg1-port` to 5432 - the port used by Postgres within the container. Once pgBackRest makes the SSH connection, I would think it connects to Postgres directly. It doesn't need or know about the port mapping between the docker host and the container.

If you're still having trouble, are you able to share how you configured Postgres and pgBackRest to run within the container? There may be a configuration issue there that needs to be addressed. That would help with reproducing your environment..

**Comment by pgstef** [comment]
Hi,

The problem might be harder than you think unfortunately. If the pgBackRest process is running on the VM (docker host), it will try to connect to PG locally using the unix socket, not the tcp "localhost" connection.

So to make your setup working (which ain't a typical one), you'll have to find a way to share the unix sockets between the docker container and its host. This isn't a situation we actively test afaik, so it might even lead to unexpected behaviors. But it's more a system config issue than a pgBackRest problem imho.

Kind Regards

**Comment by formagi** [comment]
Hi @kmolnef

I'm using pgbackrest in a docker container.
I not sure if it's going to help you, but it was simple for me, I create a shared volume containing the pg socket directory.
Check it out:
`
services:
  pg_backrest:
    restart: on-failure
    image: woblerr/pgbackrest:2.43
    environment:
    entrypoint: ['/bin/bash', '-c', 'while true; do printf "$(date +%F\ %T) - pgbackrest container\n"; sleep 300; done']
    volumes:
      - ${PGDATA}:${PGDATA}:ro
      - /var/run/postgres:/var/run/postgres:ro
      - pgbackrest:/backup
      - type: bind
        source: pgbackrest.conf
        target: /etc/pgbackrest/pgbackrest.conf
volumes:
  pgbackrest:
`
In my case PostgreSQL and Pgbackrest container are in the same host. I think that is the different point for your stack.

**Comment by kmolnef** [comment]
Hi  @formagi

Can you send me a configuration of postgresql docker and do you use a
official docker image of postgresql?


czw., 2 lis 2023 o 04:42 Alan Formagi ***@***.***> napisał(a):

**Comment by dwsteele** [comment]
> Can you send me a configuration of postgresql docker and do you use a official docker image of postgresql?

Perhaps you should have a look at something like https://github.com/CrunchyData/crunchy-containers.
