### ISSUE TITLE
question: pgbackrest and Rubrik, anybody did it?

### ISSUE THREAD

**Issue by algosoup** [pgbackrest/pgbackrest#2213]
Hello 
we are backing up our postgres databases (> 150 instances) with pgbackrest to s3.
We have been asked to backup to rubrik now.

just wondering if anybody already done it.

**Comment by dwsteele** [comment]
Searching closed issues for Rubrik, I see two: #1310, #2008. pgBackRest works with many storage devices, but Rubrik seems to enforce some constraints that do not work well for database backup.

If you get it working, feel free to respond here.

**Comment by rafapaisley** [comment]
We are using pgbackrest with Rubrik on my current company and it's working, but we needed to write a script that calls pgbackrest and backs up to a rubrik managed volume.

**Comment by thewillwilson** [comment]
@rafapaisley Would you be able to share this script?

**Comment by rafapaisley** [comment]
> @rafapaisley Would you be able to share this script?

Here you have it:

https://github.com/rafapaisley/rubrik-pgbackrest

I have sanitized it so it could be shared but I have tested and it works :)
