### ISSUE TITLE
New Feature - Make a backupset (on a different location) that don'f follows the normal expiration rules 

### ISSUE THREAD

**Issue by EVDBV** [pgbackrest/pgbackrest#2216]
Is it possible with pgbackrest to make "a save working copy, with just  the necessary WAL's " of a specific backup to a specific location.

 Some customers needs to "save a backup" for a longer period (several  years), 

 With the actual retention configs, I think it is not possible with  pgbackrest.

 Making a second repo, you'll have all the WAL's that will be copied to  this second repo, which we really don't need.

 Maybe a nice new feature for pgbackrest ?

Many thanks in advance,

**Comment by philrhurst** [comment]
You can instruct pgBackRest to also store the WAL files in the backup directory with the `--archive-copy=y` flag. Then your backup directory will be somewhat "portable" and completed (i.e. it contains the data directory files and WAL files needed for a restore). Then you can copy it to a different location. Would that be sufficient for your needs?

- https://pgbackrest.org/configuration.html#section-backup/option-archive-copy

The restore process may look different though. That would need to be tested out.

**Comment by EVDBV** [comment]
Hello,

That's not really what customers want.

It is too complex, if you have multiple backups, which directory needs to  be copied ?
Each user has to write his own scripts, testing with every new release, .... 

Using another repo: WAL are allways copied into, which we do not really want.

I think, as I can see in the posts pgbackrest, more customers asks susch a feature to be able to save a backup elsewhere, 

Kind regards

**Comment by dwsteele** [comment]
> Using another repo: WAL are allways copied into, which we do not really want.

We are working on a feature to allow WAL to be logged to a repo only during a backup. Unfortunately it is stuck behind some other improvements that need to be made first, so there is no ETA.
