### ISSUE TITLE
pgbackrest version - libpq.so.5: no version information available

### ISSUE THREAD

**Issue by pc-dok** [pgbackrest/pgbackrest#2217]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.47

2. PostgreSQL version: 16.0

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL

4. Did you install pgBackRest from source or from a package? source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
After installing pgbackrest in our env, backup itself is working /full or diff / but when i make pgbackrest version i get this message:
pgbackrest: /u01/app/postgres/product/16/db_0/lib/libpq.so.5: no version information available (required by pgbackrest)

I am not sure why. when i run the compile.sh with all parameters, i get no errors!

Any ideas? did i miss something?

regards
franco

**Comment by dwsteele** [comment]
Not sure what `compile.sh` is, but your problem is likely that the env is different when pgbackrest is unable to load libpq.so.

If you are running RHEL, why not just install the standard packages from yum.postgresql.org?

**Comment by pc-dok** [comment]
my compile .sh is only the make ( we do not use rpms in our company):

`PGHOME={{ pv_postgres_home }}
LD_LIBRARY_PATH=${PGHOME}/lib
PATH=$PATH:${PGHOME}/bin
export PGHOME LD_LIBRARY_PATH PATH
echo $LD_LIBRARY_PATH

./configure --prefix={{ pv_pgbackrest_home }} \
            --with-configdir={{ pv_postgres_dmk_install_dir }}/dmk/etc/
make
make install`

**Comment by dwsteele** [comment]
Well, as I said, there is likely something wrong with your env or libpq was not installed correctly. I don't see anything unusual about how you are building, though.
