### ISSUE TITLE
how to know if a reload succeed

### ISSUE THREAD

**Issue by Tiago-Anastacio** [pgbackrest/pgbackrest#2222]
Hello,

pgbackrest 2.48 community package SLES 15 postgres 15.3

Use case: 
Using pgbackrest server (without systemd for security reasons)

Without using systemd we use a kill -1 to send a reload signal but kill return code 
doesn't provide us information about pgbackrest reload success

The same applies for start and stop but there is a workaround for them (using pgbackrest server-ping to check).

Do you have something to check reload success ?

Thank you very much

**Comment by dwsteele** [comment]
If the changes you made to the configuration are working then it was reloaded. Not sure how else you'd be able to tell.

**Comment by dwsteele** [comment]
> If the changes you made to the configuration are working then it was reloaded.

To be a little clearer, the only options valid for the server are TLS setttings, so it should be possible to test the new values with server-ping.

**Comment by Tiago-Anastacio** [comment]
_To be a little clearer, the only options valid for the server are TLS setttings, so it should be possible to test the new values with server-ping._

Understood, thanks for you advice.

We had an issue on a pgbackest host , we add a new stanza configuration file so a new tls-server-auth=....   parameter under global section
we reload pgbackrest server process on pgbackrest host.

From the new PostgreSQL host the one we are adding we couldn't server-ping.

We had to restart pgbackrest server process on pgbackrest host, and then it worked.

we saw no error on all-server.log.

Also We user two dedicated pgbackrest hosts : on repo2 everything were working on repo1 we had this issue.

I understand the only way to check this is trigger a server ping but from a remote postgreSQL host ?

**Comment by dwsteele** [comment]
I just played with this and you should see a rather obvious restart message when the config is reloaded, e.g.:
```
-------------------PROCESS START-------------------
P00   INFO: server command begin 2.49dev: --exec-id=744-242f7aed --log-level-stderr=off --no-log-timestamp --tls-server-address=* --tls-server-auth=pgbackrest-client=* --tls-server-ca-file=/etc/pgbackrest/cert/ca.crt --tls-server-cert-file=/etc/pgbackrest/cert/server.crt --tls-server-key-file=/etc/pgbackrest/cert/server.key
```
Possibly we could make the messaging a bit better here (reload vs restart), but if you do not see this message when you do a reload (i.e. send SIGHUP to the server process) then the signal is not being sent.

**Comment by dwsteele** [comment]
You can also see an explicit reload message at detail log level.
