### ISSUE TITLE
Backup from a Standby

### ISSUE THREAD

**Issue by calvin2020** [pgbackrest/pgbackrest#2223]
Hello:

pgBackRest version: 2.48

PostgreSQL version: 16

OS:Rockylinux 9.2

I installed pgBackRest from a package

My pgbackrest.conf of standby as below:
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
backup-standby=y
process-max=3
start-fast=y
[test]
recovery-option=primary_conninfo=host=192.168.137.209 port=5432 user=replica
pg1-host=192.168.137.209
pg1-path=/data/pgsql/16/data
pg2-host=192.168.138.120
pg2-path=/data/pgsql/16/data

My postgresql.conf of standby as below:

wal_level = replica                 
archive_mode = on         
archive_command = 'pgbackrest --stanza=test archive-push %p'
hot_standby = on
primary_conninfo = 'host=192.168.137.209 port=5432 user=replica password=xxx' 
primary_slot_name = 'node1_slot'  
recovery_target_timeline = 'latest' 

My postgresql streaming replication is ok,when I use pgbackrest to backup from my standby,the error as below:
[postgres@gtlm 16-1]$ pgbackrest --stanza=test --log-level-console=info backup
2023-11-10 14:53:24.040 P00   INFO: backup command begin 2.48: --backup-standby --exec-id=414423-48bf95e0 --log-level-console=info --pg1-host=192.168.137.209 --pg2-host=192.168.138.120 --pg1-path=/data/pgsql/16/data --pg2-path=/data/pgsql/16/data --process-max=3 --repo1-path=/var/lib/pgbackrest --repo1-retention-full=2 --stanza=test --start-fast
2023-11-10 14:53:26.916 P00   INFO: last backup label = 20231107-153815F_20231107-172033I, version = 2.48
2023-11-10 14:53:26.916 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2023-11-10 14:53:27.424 P00   INFO: backup start archive = 000000060000000000000038, lsn = 0/38000028
2023-11-10 14:53:27.424 P00   INFO: wait for replay on the standby to reach 0/38000028
2023-11-10 14:53:27.728 P00   INFO: replay on the standby reached 0/38000028
2023-11-10 14:53:27.728 P00   INFO: check archive for prior segment 000000060000000000000037
ERROR: [082]: WAL segment 000000060000000000000037 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2023-11-10 14:54:27.728 P00   INFO: backup command end: aborted with exception [082]

I checked standby archive WAL,it doesn't archive standby WAL to /var/lib/pgbackrest/archive automatically，then I've checked as above three HINTs,still can't resolve this issue,would you please help me to find the reason?
thanks

**Comment by pgstef** [comment]
Hi,

First of all, you don't need both `pg1-host=192.168.137.209` and `pg2-host=192.168.138.120` in your config. You should only keep the one with the primary IP and remove the other one. The archive-push process is a "local" process so it won't run if you only define "remote" hosts.

Anyway, the WAL archives should be pushed from the primary (see PG archive_mode behavior). That's what we usually recommend unless you exactly know what you are doing.

So to take the **backup** from the standby, you need to configure pgBackRest on the primary too and have a common shared repo. See all the [supported](https://pgbackrest.org/configuration.html#section-repository/option-repo-type) repo types available.
Storing the WAL archives and backups locally on a PG host is a bad idea anyway.

Kind Regards

**Comment by calvin2020** [comment]
Hi:

Thanks for you reply.
Yes,I configure pgBackRest on the primary

My pgbackrest.conf of primary as below:
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
[test]
pg1-path=/data/pgsql/16/data
pg1-port=5432
pg1-host-user=postgres
pg1-user=postgres


My pgbackrest.conf of standby as below according to your suggestion:

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
backup-standby=y
process-max=3
start-fast=y
[test]
recovery-option=primary_conninfo=host=192.168.137.209 port=5432 user=replica
pg1-host=192.168.137.209
pg1-path=/data/pgsql/16/data

Both primary and standby have test repo，I still failed to backup from standby,I got same errors.
Would you please help me to check again?
thanks

**Comment by pgstef** [comment]
Well, I suggested to remove pg2-host, not pg2-path. Without pg1-host + pg1-path pointing to the remote cluster (primary) and pg2-path pointing to the local cluster (standby), you won't be able to take a backup.

Anyway that's not the most important part of my previous answer. Since the Wal archives are coming from the primary you need a shared common repository between primary and standby.
`/var/lib/pgbackrest` is a local directory as far as I can tell from the info you gave.

**Comment by calvin2020** [comment]
Okay,as I read from pgBackRest user-guide "pgBackRest can use TLS with client certificates to enable communication between the hosts. It is also possible to use SSH, see [Setup SSH](https://pgbackrest.org/user-guide.html#repo-host/setup-ssh)".Can I use SSH method to get Wal archives from primary without password using system user postgres?

**Comment by dwsteele** [comment]
> Can I use SSH method to get Wal archives from primary without password using system user postgres?

Doesn't look like this was answered, but yes. See https://pgbackrest.org/user-guide.html#repo-host/setup-ssh.
