### ISSUE TITLE
pgbackrest tests errors

### ISSUE THREAD

**Issue by RekGRpth** [pgbackrest/pgbackrest#2228]
I found errors in existing tests, but for some reason this does not lead to errors.

1) commit adds [code change for two U64 reads and one Str read](https://github.com/pgbackrest/pgbackrest/commit/6a1c0337ddee9900dda58b7d2fa74d82c0586ed2#diff-92125fd140c55b7060d5640a19ba4a751e59a99be784ff29a504c9626a170308R1049-R1051) and [test change for two U64 writes and one Str write](https://github.com/pgbackrest/pgbackrest/commit/6a1c0337ddee9900dda58b7d2fa74d82c0586ed2#diff-c5676b217804107fb7c1837098f527a1657ebb28e928ef5a5293543abb507c91R1327-R1329)

2) commit adds [code change for another U64 read](https://github.com/pgbackrest/pgbackrest/commit/34d649579eb3bd1530aa99f0ed1879e7d3125424#diff-92125fd140c55b7060d5640a19ba4a751e59a99be784ff29a504c9626a170308R1188), but does not add corresponding change in tests

3) commit adds [code change for another U64 read again](https://github.com/pgbackrest/pgbackrest/commit/912eec63bb971c10a545e582f628c982f4e00005#diff-92125fd140c55b7060d5640a19ba4a751e59a99be784ff29a504c9626a170308R1195), but does not add corresponding change in tests

Now test writes two U64 and one Str, but reads FOUR U64 and one Str!!! And DOES NOT break!

Bug was found during investigate  https://github.com/pgbackrest/pgbackrest/pull/2227

I think same bugs may be found in other places.

I suggest instead [this](https://github.com/pgbackrest/pgbackrest/blob/a9f34d0c74c41e583464d1d4341bdf8e5c36dcb6/src/command/backup/protocol.c#L90-L98) and [that](https://github.com/pgbackrest/pgbackrest/blob/a9f34d0c74c41e583464d1d4341bdf8e5c36dcb6/src/command/backup/backup.c#L1420-L1427) create 2 new functions for serialize and de-serialize, and also use these functions in [tests](https://github.com/pgbackrest/pgbackrest/blob/a9f34d0c74c41e583464d1d4341bdf8e5c36dcb6/test/src/module/command/backupTest.c#L2260-L2266).

**Comment by dwsteele** [comment]
> Now test writes two U64 and one Str, but reads FOUR U64 and one Str!!! And DOES NOT break!

This is expected behavior since NULL/default values are not written into the pack to save space. So the reader just sets them to defaults. See `pack.h` for more info.

Since we are processing a noop none of these fields are actually used, so nothing breaks.

> create 2 new functions for serialize and de-serialize

I think that's overkill for this case. I have removed the unused fields from the test and added a comment instead, see ac78b9658. We can revisit this if it seems to be causing a problem for other tests.
