### ISSUE TITLE
remote process terminated

### ISSUE THREAD

**Issue by gintoddic** [pgbackrest/pgbackrest#223]
I keep getting this error
2016-07-27 19:09:31.735 T05  ERROR: [141]: remote process terminated: ERROR [141]: unable to read line after 1830 seconds
2016-07-27 19:09:31.736 T05   WARN: unable to shutdown protocol [141]: remote process terminated: ERROR [141]: unable to read line after 1830 seconds

version 1.3
config
[data]
db-host=masterhost1
db-user=postgres
db-path=/dbdata/9.5/data
recovery-option=standby_mode=on
recovery-option=primary_conninfo=user=replication host=192.168.1.45 sslmode=prefer sslcompression=1
thread-max=7
thread-timeout=2000

[global]
repo-path=/dbdata/9.5/pgbackrest_repo
stop-auto=y

**Comment by dwsteele** [comment]
This issue should be fixed in 1.04 which will be released today or tomorrow.

It's appears the same as one of the issues brought up in #219.

**Comment by gintoddic** [comment]
This happens during backup. Same deal?

**Comment by dwsteele** [comment]
Yes - it's due to a missing keep-alive in main thread loop that handles both backup and restore.

See 095351f145003c62b24770e8a5ef96ec6125e624.

**Comment by dwsteele** [comment]
v1.04 has been released: https://github.com/pgbackrest/pgbackrest/releases/tag/release/1.04
