### ISSUE TITLE
Consider not compressing global/pg_control

### ISSUE THREAD

**Issue by mbanck** [pgbackrest/pgbackrest#2234]
It just occurred to me that if `global/pg_control.<ext>` was not compressed, `pg_controldata -D <base>/pgbackrest/backup/stanza/<timestam>F/pg_data` will just work - maybe worth considering, or will that break other things in pgBackRest? I think not having to decompress it manually and run `pg_controldata` might make things easier, though this was really just a passing thought while looking at some restore issues.

**Comment by dwsteele** [comment]
Sad to say, that would break backward compatibility. We don't look at the extension on restore because there could be files in PGDATA that end in .gz or .lz4 or whatever. So we go with whatever is stored in the manifest. We could create a new option for this, but that seems a bit much.

**Comment by dwsteele** [comment]
I think if we were going to do anything here, it would be to add a command to extract a file from a backup. But I don't think that's something we are going to work on anytime soon.
