### ISSUE TITLE
Clarify relation between local and remote pgbackrest settings when using pg-host

### ISSUE THREAD

**Issue by zifot** [pgbackrest/pgbackrest#2236]
I'm experimenting with pgbackrest for some time now, but one thing is still not clear to me and I can't find anything in the docs about it. 

What I want to understand is how settings in pgbackret.conf loaded by local pgbackrest process and settings present in the file loaded by `pgbackrest server` running on a remote host interact with each other when locally we use `pg1-host` setting (to execute commands remotely on the said remote host).

For example, let's consider a setup where we have a local host that wants to create stanza with local file system based repo and do it in the context of remote host which hosts both Postgresql server and pgbackrest server (using `pgbackrest server` with tls). For this, local pgbackrest uses config file with `pg1-host` pointing to this remote server.

From my experiments, it *looks like* there is some kind of configuration merging between local and remote config files in such a scenario.

For example: If I set `pg1-user` on the local side to a Postgresql user that does not have proper permissions, running `stanza-create` on local machine will fail. If I set such `pg1-user` only on the remote side pgbackrest.conf - same. If I set proper user in config file on remote host but wrong one locally, again, `stanza-create` fails due to insufficient permissions when reading tables in remote Postgres (so locally set `pg1-user` seem to take precedence and the one set on the remote is ignored).

This seem to indicate that there are some rules at play regarding conflicting settings and probably some best practices how to manage those two config files - where to keep source of truth? Are some settings needed in both places?

Or maybe setting `pg1-host` on the local side should mean that no more `pg1-` settings should be present on the local file, because all that matters are now values on the remote side config file and what I'm observing above is a result of undefined behavior? Or vice versa?

**Comment by dwsteele** [comment]
If the operation is local then only local settings are used. We never fetch remote settings unless the operation requires connection to a remote, for example backup from a repo host.

If the operation connects to a remote, then local settings (including command line or env) override remote settings.
