### ISSUE TITLE
libssh2 | pgbackrest-2.49 | RHEL9: unable to find deprecated libssh2 library

### ISSUE THREAD

**Issue by 3BK** [pgbackrest/pgbackrest#2237]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgbackrest-2.49-1PGDG.rhel9.src.rpm

2. PostgreSQL version:
postgresql16-16.1-2PGDG.rhel9.x86_64

3. Operating system/version:
RHEL 9

4. Did you install pgBackRest from source or from a package?
pgbackrest-2.49-1PGDG.rhel9.src.rpm

5. Please attach the following as applicable:
```
dnf install pgbackrest
Updating Subscription Management repositories.
Last metadata expiration check: 2:08:56 ago on Thu 30 Nov 2023 08:54:08 AM.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides libssh2 needed by pgbackrest-2.49-1PGDG.rhel9.x86_64 from pgdg-common
  - nothing provides libssh2.so.1()(64bit) needed by pgbackrest-2.49-1PGDG.rhel9.x86_64 from pgdg-common
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

```

7. Describe the issue:
pgbackrest-2.49 should not be dependent on deprecated libssh2 library.

**Comment by jreidthompson** [comment]
It appears that pgbackrest-2.49-1PGDG.rhel9.x86_64 from pgdg-common is built with libssh2 (i.e. supporting SFTP).  libssh2-1.10.0-1 is available from the EPEL respository for RHEL9.

**Comment by 3BK** [comment]
When should pgbackrest switch to libshh?

https://www.libssh.org/

https://[libssh2](https://libssh2.org/).org/

**Comment by jreidthompson** [comment]
pgbackrest SFTP only supports libssh2. It will not switch to libssh.

**Comment by 3BK** [comment]
I see the value in using a client interface.  Perhaps the libssh2 team need to update the library?

**Comment by jreidthompson** [comment]
Unless I'm misreading, all those CVE's appear to refer to version 1.8.0.  And were addressed in version Version 1.8.1 - March 18 2019. Currently libssh2 is at version Version 1.11.0 - May 30 2023.  Versions 1.10 and 1.11 both appear to add updated algorithms/support.

https://libssh2.org/changes.html

https://libssh2.org

**Comment by 3BK** [comment]
Correct.  Resolved show stoppers are used to statically estimate latent unfixed defects.

**Comment by vadius45** [comment]
Hello,

While libssh2 was available in appstream of RHEL8, that's no longer the case for RHEL9. 

The libssh2 requirement is therefore a massive roadblock, as I investigate the transition to RHEL9 in my company. We have strict controls about the location of the packages, and EPEL repositories are forbidden by construct. It's been a clear stance over the years and there's no appetite internally  from Cyber to review that approach. 

+1 for the adoption of libssh or for a pgbackrest package without sftp support. 

Thanks

**Comment by 3BK** [comment]
[like]  Brent Kimberley reacted to your message:
________________________________

**Comment by shp31** [comment]
Hello,

That's the same blocking point for us to switch to Redhat 9.

Thanks.

**Comment by dwsteele** [comment]
RHEL makes some odd decisions WRT to which libraries get placed in EPEL. For example, libzstd is *still* in EPEL despite being used by just about everyone.

So, this seems like a bad choice by RHEL but I don't think we are going to migrate to a new library (a lot of work) because if it.
