### ISSUE TITLE
Restore always throws: zlib threw error: [-3] data error

### ISSUE THREAD

**Issue by yennor** [pgbackrest/pgbackrest#2238]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.49

2. PostgreSQL version:
15+248

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Debian 12

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    
```
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full-type=time
repo1-retention-full=90
repo1-retention-archive-type=incr
repo1-retention-archive=15

repo1-bundle=y
repo1-block=y

start-fast=y
#repo1-cipher-pass=...
#repo1-cipher-type=aes-256-cbc

[lasso]
pg1-host=10.88.88.5
pg1-path=/var/lib/postgresql/15/main

```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
 
default debian ones. Shouldn't matter since the backups are successfull?

    - errors in the postgresql log file before or during the time you experienced the issue

none. The postgresql server isn't running during the restore.

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

```
-------------------PROCESS START-------------------
2023-12-04 13:40:41.670 P00   INFO: restore command begin 2.49: --archive-mode=off --exec-id=5413-11fe017c --log-level-console=info --log-level-file=info --pg1-path=/var/lib/postgresql/15/main --repo1-host=10.88.88.1 --repo1-host-user=postgres --repo1-path=/var/lib/pgbackrest --stanza=lasso
2023-12-04 13:40:43.031 P00   INFO: repo1: restore backup set 20231201-232231F_20231203-220002I, recovery will start at 2023-12-03 21:00:02
2023-12-04 14:07:40.519 P00  ERROR: [029]: raised from local-1 protocol: zlib threw error: [-3] data error
                                        [FormatError] on 2 retries from 37258-69964ms: zlib threw error: [-3] data error
2023-12-04 14:07:40.520 P00   INFO: restore command end: aborted with exception [029]

-------------------PROCESS START-------------------
2023-12-04 14:25:02.375 P00   INFO: restore command begin 2.49: --archive-mode=off --delta --exec-id=5673-338d14fb --log-level-console=info --log-level-file=info --pg1-path=/var/lib/postgresql/15/main --repo1-host=10.88.88.1 --repo1-host-user=postgres --repo1-path=/var/lib/pgbackrest --stanza=lasso
2023-12-04 14:25:03.877 P00   INFO: repo1: restore backup set 20231201-232231F_20231203-220002I, recovery will start at 2023-12-03 21:00:02
2023-12-04 14:25:03.879 P00   INFO: remove invalid files/links/paths from '/var/lib/postgresql/15/main'
2023-12-04 14:28:00.567 P00  ERROR: [029]: raised from local-1 protocol: zlib threw error: [-3] data error
                                        [FormatError] on 2 retries from 36207-69813ms: zlib threw error: [-3] data error
2023-12-04 14:28:00.567 P00   INFO: restore command end: aborted with exception [029]

-------------------PROCESS START-------------------
2023-12-04 14:29:20.349 P00   INFO: restore command begin 2.49: --archive-mode=off --delta --exec-id=5703-92dbbf7c --log-level-console=debug --log-level-file=info --pg1-path=/var/lib/postgresql/15/main --repo1-host=10.88.88.1 --repo1-host-user=postgres --repo1-path=/var/lib/pgbackrest --stanza=lasso
2023-12-04 14:29:21.702 P00   INFO: repo1: restore backup set 20231201-232231F_20231203-220002I, recovery will start at 2023-12-03 21:00:02
2023-12-04 14:29:21.704 P00   INFO: remove invalid files/links/paths from '/var/lib/postgresql/15/main'
2023-12-04 14:32:18.926 P00  ERROR: [029]: raised from local-1 protocol: zlib threw error: [-3] data error
                                        [FormatError] on 2 retries from 37482-71166ms: zlib threw error: [-3] data error
2023-12-04 14:32:18.926 P00   INFO: restore command end: aborted with exception [029]

```

7. Describe the issue:
I've set up pgbackrest 3 days ago, and now wanted to test the restore, on a temporary server.
But that always ends in below error.
I've also did a 
 pgbackrest verify --stanza=lasso
Which doesn't show any errors in the repository. So I guess there must be a problem with the datatransfer?
I've tried out the option --compress-level-network=0, but the same error appeared.
--compress-type=none doesn't seem to work with restore (for whatever reason? the documentation about compression is a bit confusing)

```
command/restore/restore::restoreJobResult: (manifest: {Manifest}, job: {state: done, key: {"pg_data/base/93110/93831.25"}, command: {name: rs-f}, result: null, code: 29, message: {"raised from local-1 protocol: zlib threw error: [-3] data error
                                            [FormatError] on 2 retries from 37482-71166ms: zlib threw error: [-3] data error"}}, zeroExp: null, sizeTotal: 114341606791, sizeRestored: 88046829568)
2023-12-04 14:32:18.926 P00  DEBUG:     command/exit::exitSafe: (result: 0, error: true, signalType: 0)
ERROR: [029]: raised from local-1 protocol: zlib threw error: [-3] data error
           [FormatError] on 2 retries from 37482-71166ms: zlib threw error: [-3] data error
       --------------------------------------------------------------------
       If SUBMITTING AN ISSUE please provide the following information:
       
       version: 2.49
       command: restore
       options: --archive-mode=off --delta --exec-id=5703-92dbbf7c --log-level-console=debug --log-level-file=info --pg1-path=/var/lib/postgresql/15/main --repo1-host=10.88.88.1 --repo1-host-user=postgres --repo1-path=/var/lib/pgbackrest --stanza=lasso
       
       stack trace:
       command/restore/restore.c:restoreJobResult:2254:(manifest: {Manifest}, job: {state: done, key: {"pg_data/base/93110/93831.25"}, command: {name: rs-f}, result: null, code: 29, message: {"raised from local-1 protocol: zlib threw error: [-3] data error
           [FormatError] on 2 retries from 37482-71166ms: zlib threw error: [-3] data error"}}, zeroExp: null, sizeTotal: 114341606791, sizeRestored: 88046829568)
       command/restore/restore.c:cmdRestore:(void)
       main.c:main:(debug log level required for parameters)
       --------------------------------------------------------------------
2023-12-04 14:32:18.926 P00   INFO: restore command end: aborted with exception [029]
2023-12-04 14:32:18.926 P00  DEBUG:     command/exit::exitSafe: => 29
2023-12-04 14:32:42.028 P00  DEBUG:     main::main: => 29
```

**Comment by yennor** [comment]
I've tried to do a new full backup and restore from that.
same result.

**Comment by yennor** [comment]
I've added
`compress-type=zst`
to the global options on the repo host. 
After doing another full backup, the restore works now.
Seems like there are some problems with zlib.

**Comment by yennor** [comment]
sorry, at the moment I can only connect irregularly.

pg server:
```
[global]
repo1-host=10.88.88.1
repo1-host-user=postgres
log-level-file=detail
#repo1-path=/var/lib/pgbackrest
#repo1-retention-full=2
#repo1-cipher-pass=...
#repo1-cipher-type=aes-256-cbc

[lasso]
pg1-path=/var/lib/postgresql/15/main

```

repository. 
"Compress-type = zst" is the new parameter, that makes the whole thing work, before compress=type wasn't set. Otherwise the config is unchanged.
 :
```
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full-type=time
repo1-retention-full=90
#repo1-retention-incr-type=time
#repo1-retention-incr=60
repo1-retention-archive-type=incr
repo1-retention-archive=15
compress-type=zst
repo1-bundle=y
repo1-block=y

start-fast=y
#repo1-cipher-pass=...
#repo1-cipher-type=aes-256-cbc

[lasso]
pg1-host=10.88.88.2
pg1-path=/var/lib/postgresql/15/main

```

Initial Command:
pgbackrest --type=full --stanza=lasso backup

and yes. after adding compress-type=zst i'm able to restore the initial backup. without I'm getting above described error.

**Comment by dwsteele** [comment]
Just to be clear, you changed `compress-type` to `zst`, then made a new full backup, and that is the one that worked?

**Comment by yennor** [comment]
exactly

**Comment by dwsteele** [comment]
We believe PR #2256 fixes this issue, so please let is know if you see it again after 2.50 is released.

**Comment by ka8725** [comment]
I tried to restore my backup and got the same error:

```
2024-02-08 23:55:16.373 P00   INFO: repo1: restore backup set 20240204-064702F_20240208-062502D, recovery will start at 2024-02-08 06:25:02
2024-02-08 23:55:16.373 P00   INFO: remap data directory to '/var/lib/postgresql/10/backup'
ERROR: [029]: raised from local-2 protocol: zlib threw error: [-3] data error
           [FormatError] on 2 retries from 8-15016ms: zlib threw error: [-3] data error
2024-02-08 23:55:31.440 P00   INFO: restore command end: aborted with exception [029]
```

The backup was made with v2.45. Restore didn't work on that version. Installed v2.5 and tried to restore it. Nothing changed. Is there a way to restore those backup made with v2.45?

My config:

```
[main]
pg1-path=/var/lib/postgresql/10/main
pg1-port=5432

[global]
beta=y
process-max=4
repo1-block=y
repo1-bundle=y
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y
```

**Comment by dwsteele** [comment]
> Interestingly, managed to restore to the previous backup version (but not to the latest one). Fortunately, that's enough for me.

Not sure what this means. You were able to use another version of pgBackRest to restore?

Another thing you can do is restore from the full backup instead by specifying `--set=20240204-064702F`.

**Comment by ka8725** [comment]
> > Interestingly, managed to restore to the previous backup version (but not to the latest one). Fortunately, that's enough for me.
> 
> Not sure what this means. You were able to use another version of pgBackRest to restore?
> 
> Another thing you can do is restore from the full backup instead by specifying `--set=20240204-064702F`.

I reproduced the error above for both pgBackRest versions. Then, I switched to the idea of restoring from the set backup instead of the latest version. That helped. I did it on the older pgBackRest version. I didn't try to run it with `--set` option on the new pgBackRest version. I also thought about restoring from the full backup, it was rather old though.

**Comment by dwsteele** [comment]
> Then, I switched to the idea of restoring from the set backup instead of the latest version. That helped.

It could be that the last backup is the only one that has an issue. If picking the one before works, then go with that.

**Comment by dwsteele** [comment]
> I am seeing this same issue. Running version 2.50

What version was this backup made with? Anything < 2.49 has known issues for block incremental.

**Comment by Gurmokh** [comment]
> > I am seeing this same issue. Running version 2.50
> 
> What version was this backup made with? Anything < 2.49 has known issues for block incremental.

The backup was made with v2.50

**Comment by Gurmokh** [comment]
I'm still getting this error. Do we know if the fix applied here https://github.com/pgbackrest/pgbackrest/pull/2256 definitely works on 2.5 ?

**Comment by dwsteele** [comment]
> I'm still getting this error. Do we know if the fix applied here https://github.com/pgbackrest/pgbackrest/pull/2256 definitely works on 2.5 ?

Yes -- it should, but this may be a different issue. This newest backup was made with 2.50, but were all the backups in the set (all the way back to the full) made with pgBackRest >= 2.49?

**Comment by Gurmokh** [comment]
Yes. The most recent full backup is taken with 2.50.
