### ISSUE TITLE
Only full backup option

### ISSUE THREAD

**Issue by thorro** [pgbackrest/pgbackrest#2241]
Is there a way to enable only daily full backups via pgbackrest?

We have many writes during the day and can afford to lose some data. During the day, a great number of WAL files are generated and transferred to S3, so it would be faster for us to restore only a full backup and then repopulate the databases, so backupping the WAL files isn't necessary, except those needed to complete a consistent full restore.

**Comment by pgstef** [comment]
Hi,

No, there's no way of achieving this out of the box currently.

The easiest way would be to change the archive_command (by let's say `/bin/true`) and then changing it back + `pgbackrest check` before running your backup.

Kind Regards
