### ISSUE TITLE
Unable create backup - docker container 

### ISSUE THREAD

**Issue by nidhin077** [pgbackrest/pgbackrest#2244]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.49
2. PostgreSQL version:
postgres-13

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

postgres is on the docker container, pgbackrest on local machine

5. Did you install pgBackRest from source or from a package?
 From source 

7. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

```
[demo]
pg1-path=/opt/pgbackrest/postgres/var/lib/postgresql/data
pg1-host=192.168.80.2
pg1-port=5432
pg1-user=postgres

[global]
repo1-path=/var/lib/pgbackrest/demo1
log-level-console=info
```

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

```
#------------------------------------------------------------------------------
# CUSTOMIZED OPTIONS
#------------------------------------------------------------------------------

# Add settings for extensions her
archive_command = 'pgbackrest --stanza=demo archive-push %p'
archive_mode = on
max_wal_senders = 3
wal_level = replica
pg1-socket-path= /var/run/postgresql
```

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
   
```
root@nidhin:/opt/pgbackrest/postgres# pgbackrest --stanza=demo --log-level-console=info stanza-create
2023-12-11 18:54:21.301 P00   INFO: stanza-create command begin 2.49: --exec-id=3556269-b5303957 --log-level-console=info --pg1-host=192.168.80.2 --pg1-path=/opt/pgbackrest/postgres/var/lib/postgresql/data --pg1-port=5432 --pg1-user=postgres --repo1-path=/var/lib/pgbackrest/demo1 --stanza=demo
WARN: unable to check pg1: [UnknownError] remote-0 process on '192.168.80.2' terminated unexpectedly [255]: ssh: connect to host 192.168.80.2 port 22: Connection timed out
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
2023-12-11 18:56:31.275 P00   INFO: stanza-create command end: aborted with exception [056]
```

8. Describe the issue:

Hi,

I'm trying to create a backup of postgres 13, postgres is in the docker container and pgbackrest is in my local machine, I mapped the docker volume to my local machine, and added the path to pg1-path section, but when trying to construct a stanza, getting some error.

I want to know if taking a backup of a Postgres database running on a Docker container is feasible without having a cluster. If so, kindly walk me through the processes as I'm not sure precisely what's wrong with this. Does it also need access to the container via SSH? if the Postgres volume has already been mapped to the local machine.

**Comment by dwsteele** [comment]
> I want to know if taking a backup of a Postgres database running on a Docker container is feasible

pgBackRest works fine with containers, but the way you are trying to configure it won't work. pgBackRest needs to be running inside the container to get a consistent backup of Postgres.

> If so, kindly walk me through the processes as I'm not sure precisely what's wrong with this

The user guide is built using containers so all examples there work in a containerized environment: https://pgbackrest.org/user-guide.html.

**Comment by nidhin077** [comment]
@dwsteele In general, the cluster is not present in the Postgres image therefore, how does it function within the container?  In addition, how can we install it in a Postgres:13 image if it works?

**Comment by dwsteele** [comment]
> In general, the cluster is not present in the Postgres image therefore, how does it function within the container?

Presumably it is mounted in the container, else how would PostgreSQL see it?

>  In addition, how can we install it in a Postgres:13 image if it works?

It is no different than installing any software in a container. I suggest you consult the Docker documentation or look at https://github.com/CrunchyData/crunchy-containers for a working example.

None of this resembles a pgBackRest issue so I'll close this now.
