### ISSUE TITLE
pgBackRest backups abnormal data out of sync

### ISSUE THREAD

**Issue by linzehai0801** [pgbackrest/pgbackrest#2245]
1. pgBackRest version:2.49

2. PostgreSQL version:12.17

3. Operating system：centos7

4. Did you install pgBackRest from source or from a package?  source 

5. pgsql pgbackrest.conf
```
[root@test-pgsql pgsql]# cat /etc/pgbackrest/pgbackrest.conf
[demo]
pg1-path=/var/lib/pgsql/12/data/
[global]
log-level-file=detail
repo1-host=10.0.15.196
```
pgbackrest
```
[pgbackrest@pgbackup ~]$ cat /etc/pgbackrest/pgbackrest.conf
[demo]
pg1-host=10.0.15.197
pg1-path=/var/lib/pgsql/12/data/
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y
```

7. Describe the issue: 
After installing pgBackRest and PostgreSQL I did the following
On the apbackup machine:
```
[pgbackrest@pgbackup ~]$ pgbackrest --stanza=demo stanza-create --log-level-console=info
2023-12-15 16:15:19.569 P00   INFO: stanza-create command begin 2.49: --exec-id=945-0d3b2de1 --log-level-console=info --pg1-host=10.0.15.197 --pg1-path=/var/lib/pgsql/12/data/ --repo1-path=/var/lib/pgbackrest --stanza=demo
2023-12-15 16:15:20.588 P00   INFO: stanza-create for stanza 'demo' on repo1
2023-12-15 16:15:20.735 P00   INFO: stanza-create command end: completed successfully (1168ms)


[pgbackrest@pgbackup ~]$ pgbackrest --stanza=demo check


[pgbackrest@pgbackup ~]$ pgbackrest --stanza=demo backup --log-level-console=info
2023-12-15 16:16:05.814 P00   INFO: backup command begin 2.49: --exec-id=1254-a00080bb --log-level-console=info --pg1-host=10.0.15.197 --pg1-path=/var/lib/pgsql/12/data/ --repo1-path=/var/lib/pgbackrest --repo1-retention-full=2 --stanza=demo --start-fast
WARN: no prior backup exists, incr backup has been changed to full
2023-12-15 16:16:06.944 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2023-12-15 16:16:07.956 P00   INFO: backup start archive = 000000160000000000000033, lsn = 0/33000028
2023-12-15 16:16:07.956 P00   INFO: check archive for prior segment 000000160000000000000032
2023-12-15 16:16:18.142 P00   INFO: execute non-exclusive backup stop and wait for all WAL segments to archive
2023-12-15 16:16:18.347 P00   INFO: backup stop archive = 000000160000000000000033, lsn = 0/33000138
2023-12-15 16:16:18.358 P00   INFO: check archive for segment(s) 000000160000000000000033:000000160000000000000033
2023-12-15 16:16:19.601 P00   INFO: new backup label = 20231215-161606F
2023-12-15 16:16:19.711 P00   INFO: full backup size = 24.3MB, file total = 984
2023-12-15 16:16:19.713 P00   INFO: backup command end: completed successfully (13903ms)
2023-12-15 16:16:19.714 P00   INFO: expire command begin 2.49: --exec-id=1254-a00080bb --log-level-console=info --repo1-path=/var/lib/pgbackrest --repo1-retention-full=2 --stanza=demo
2023-12-15 16:16:19.743 P00   INFO: expire command end: completed successfully (30ms)

```
The first backup did not have any data in postgres so it created a test database
postgres=# create database test;
CREATE DATABASE

Then perform another backup, this time an incremental backup that includes the test database
```
[pgbackrest@pgbackup ~]$ pgbackrest --stanza=demo backup --log-level-console=info
[pgbackrest@pgbackup ~]$ pgbackrest --stanza=demo info
stanza: demo
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12): 000000160000000000000031/000000160000000000000035

        full backup: 20231215-161606F
            timestamp start/stop: 2023-12-15 16:16:06+08 / 2023-12-15 16:16:18+08
            wal start/stop: 000000160000000000000033 / 000000160000000000000033
            database size: 24.3MB, database backup size: 24.3MB
            repo1: backup set size: 2.9MB, backup size: 2.9MB

        incr backup: 20231215-161606F_20231215-162651I
            timestamp start/stop: 2023-12-15 16:26:51+08 / 2023-12-15 16:26:57+08
            wal start/stop: 000000160000000000000035 / 000000160000000000000035
            database size: 32.1MB, database backup size: 7.9MB
            repo1: backup set size: 3.8MB, backup size: 975.7KB
            backup reference list: 20231215-161606F
```

Then test database delete again
```
postgres=# drop database test;
DROP DATABASE
```

Finally restore the backup
```
[root@test-pgsql pgsql]# rm -rf /var/lib/pgsql/12/data/*
[root@test-pgsql pgsql]# systemctl start postgresql-12
-bash-4.2$ pgbackrest --stanza=demo restore --log-level-console=info
2023-12-15 16:31:35.447 P00   INFO: restore command begin 2.49: --exec-id=9921-e2237c10 --log-level-console=info --log-level-file=detail --pg1-path=/var/lib/pgsql/12/data/ --repo1-host=10.0.15.196 --stanza=demo
2023-12-15 16:31:36.002 P00   INFO: repo1: restore backup set 20231215-161606F_20231215-162651I, recovery will start at 2023-12-15 16:26:51
2023-12-15 16:31:44.590 P00   INFO: write updated /var/lib/pgsql/12/data/postgresql.auto.conf

[root@test-pgsql pgsql]# systemctl start postgresql-12
postgres=# \l
                                     资料库列表
   名称    |  拥有者  | 字元编码 |  校对规则   |    Ctype    |       存取权限
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 |
 template0 | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 test      | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 |

```
It's normal at this point

And then I created the test1 database and then I did a restore and what is the test1 database still there
```
postgres=# create database test;
[root@test-pgsql pgsql]# rm -rf /var/lib/pgsql/12/data/*
[root@test-pgsql pgsql]# systemctl start postgresql-12
-bash-4.2$ pgbackrest --stanza=demo restore --log-level-console=info
[root@test-pgsql pgsql]# systemctl start postgresql-12
postgres=# \l
                                     资料库列表
   名称    |  拥有者  | 字元编码 |  校对规则   |    Ctype    |       存取权限
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 |
 template0 | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 test      | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 |
 test1     | postgres | UTF8     | zh_CN.UTF-8 | zh_CN.UTF-8 |
```
Under normal circumstances, only the test database should be in the incremental backup

**Comment by dwsteele** [comment]
> It's normal at this point

No, it's not. The `test` database should have been dropped again after recovery. This is what I see:
```
docker exec -it -u postgres doc-pg-primary pgbackrest --stanza=demo backup --start-fast
docker exec -it -u postgres doc-pg-primary psql -c 'create database test'
docker exec -it -u postgres doc-pg-primary pgbackrest --stanza=demo backup --start-fast
docker exec -it -u postgres doc-pg-primary psql -c 'drop database test'

docker exec -it -u postgres doc-pg-primary pg_ctlcluster 15 demo stop
docker exec -it -u postgres doc-pg-primary rm -rf /var/lib/postgresql/15/demo
docker exec -it -u postgres doc-pg-primary pgbackrest --stanza=demo restore
docker exec -it -u postgres doc-pg-primary pg_ctlcluster 15 demo start

docker exec -it -u postgres doc-pg-primary psql -c 'select datname from pg_database'

  datname
-----------
 postgres
 template1
 template0
```

Are you sure you started from a clean system and reproduced all the steps above exactly? PITR can be complicated (especially when run multiple times), but it is Postgres that does recovery, not pgBackRest. See https://www.postgresql.org/docs/current/continuous-archiving.html for more information.

**Comment by linzehai0801** [comment]
pgbackrest --stanza=demo restore is supposed to restore your incremental backups, isn't it? If you delete the test database after performing incremental backup after psql -c 'create database test', shouldn't the test database exist when you restore the database? Why wasn't the database there when you restored it

**Comment by dwsteele** [comment]
> shouldn't the test database exist when you restore the database?

No, since recovery by default replays WAL generated after the backup (which will contain the drop table). If you want to prevent the table from being dropped, you'd need to specify a recovery target, see https://pgbackrest.org/user-guide.html#pitr. 

Again, recovery is a function of Postgres, not pgBackRest. There are plenty of articles you can read about how recovery works -- including the Postgtres docs cited above.

**Comment by linzehai0801** [comment]
Thank you for your help

```
[pgbackrest@bakeup ~]$ pgbackrest --stanza=demo info
stanza: demo
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12): 0000000E000000000000001B/000000100000000000000024

        full backup: 20231216-214859F
            timestamp start/stop: 2023-12-16 21:48:59+08 / 2023-12-16 21:49:24+08
            wal start/stop: 0000000E000000000000001E / 0000000E000000000000001E
            database size: 25.5MB, database backup size: 25.5MB
            repo1: backup set size: 2.9MB, backup size: 2.9MB

        incr backup: 20231216-214859F_20231216-215455I
            timestamp start/stop: 2023-12-16 21:54:55+08 / 2023-12-16 21:55:27+08
            wal start/stop: 000000100000000000000023 / 000000100000000000000023
            database size: 33.4MB, database backup size: 7.9MB
            repo1: backup set size: 3.9MB, backup size: 975.1KB
            backup reference list: 20231216-214859F
```
The test database was included in my incremental backup, and the end time of the incremental backup was 2023-12-16 21:55:27+08, so I restored it according to the time
`pgbackrest --stanza=demo --type=time --target="2023-12-16 21:55:27+08" restore --log-level-console=info
`
```
-bash-4.2$ cat /var/lib/pgsql/12/data/postgresql.auto.conf
# Recovery settings generated by pgBackRest restore on 2023-12-16 22:06:44
restore_command = 'pgbackrest --stanza=demo archive-get %f "%p"'
recovery_target_time = '2023-12-16 21:55:27+08'
```
But the test database is still not there
```
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(3 rows)
```
If the database test is normal, it should exist

**Comment by linzehai0801** [comment]
Or you can tell me in your example if you want to restore the test database then restore it

**Comment by linzehai0801** [comment]
I seem to understand why the database test does not exist, is archive_command = 'pgbackrest-stanza =demo archive-push %p' enabled? Therefore, when I delete the test database, it will be logged and sent to the pgbackrest server. When pgbackres performs a restore, it reverts to the latest wal_log, so the test database does not exist. Can I understand that?

**Comment by pgstef** [comment]
> I seem to understand why the database test does not exist, is archive_command = 'pgbackrest-stanza =demo archive-push %p' enabled? Therefore, when I delete the test database, it will be logged and sent to the pgbackrest server. When pgbackres performs a restore, it reverts to the latest wal_log, so the test database does not exist. Can I understand that?

Hi,

As David mentioned earlier already, that's how PostgreSQL works indeed. Nothing to do with pgBackRest itself. 
You should really read carefully the PostgreSQL part of the doc about this: https://www.postgresql.org/docs/current/continuous-archiving.html

To say it very basically, yes, PostgreSQL triggers the archive_command as soon as a WAL segment is completed (usually 16MB by default). So everything you do in your system will eventually come up to the archives repository.

When taking a backup, WAL archives are also generated. And to make your backup consistent (since you're copying the data files while PostgreSQL is running and thus changing them), PostgreSQL will at least need to replay the WALs that have been generated during the copy (see "wal start/stop" in the pgBackRest info command).

By default, if you don't set any `recover_target_*` setting in PostgreSQL, PostgreSQL will try to recover as much data as it can (so yes, replay all the WAL archives in the repository, including your drop database). You need to perform point-in-time recovery by setting your recovery target. pgBackRest can help you with that when using the [restore --type option](https://pgbackrest.org/command.html#command-restore/category-command/option-type).

But ultimately, it is up to you to define the recovery target you want to reach (time, lsn, xid, restore point...). Taking backups is very easy. Finding a suitable recovery target is way harder. If you want to do something very simple, you could use the immediate recovery target (`pgbackrest restore --type=immediate` which will set PostgreSQL `recovery_target='immediate'`). The idea is to restore the backup set you want (by default the latest one but you can change it with `--set`) and replay only the WAL archives needed to reach the backup consistency point (backup stop location). That should bring back your test database if you do it right.

But really, all this is PostgreSQL PITR basics, nothing to do specifically with pgBackRest itself. I don't think there's a lot more that we'll be able to help you with in here. You should really consider reading the PostgreSQL docs about all this. (And if that's not enough, engage with some professional support or training)

Kind Regards

**Comment by dwsteele** [comment]
> You should really consider reading the PostgreSQL docs about all this. (And if that's not enough, engage with some professional support or training)

Agreed.
