### ISSUE TITLE
Enhancement : json output for backup/restore commands

### ISSUE THREAD

**Issue by clmntpllr** [pgbackrest/pgbackrest#2247]
Hi,

Having the possibility to choose « json output » for « info » and « repo-ls » commands is a great feature !
I’m using Ansible to backup my stanzas and it’d be easier for reporting purposes to deal with json output for the « backup command » too. And I think it’d be the case for any type of script language that is able to deal with json.
Hope to see this implemented in the future :).
Regards

**Comment by dwsteele** [comment]
If we provided a JSON format, I think people would expect the log format and messages to stay consistent over time and that's not a promise we are wiling to make at this time.

If there is information you need that you can't get from the info JSON then we can talk about that, but a wholesale switch to JSON logging is not likely in the foreseeable future.

**Comment by clmntpllr** [comment]
Thanks for your answer David. I had only in mind the objective of not launching unnecessary commands, but the « info » command at the end is the right solution although you’d have to process it to get only the last backups infos. Anyway, I’ve discovered a [pgbackrest_exporter ](https://github.com/woblerr/pgbackrest_exporter) for Prometheus and I think this will better suits my need.
