### ISSUE TITLE
Object Storage Lifecycle Policy Recommendations

### ISSUE THREAD

**Issue by maherbeg** [pgbackrest/pgbackrest#2258]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.48

3. PostgreSQL version: 11-15

4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Centos 7

5. Did you install pgBackRest from source or from a package? From a package

6. Please attach the following as applicable:
N/A

7. Describe the issue:
Are there any gotchas or recommendations for setting lifecycle policies for objects stored in repos like S3 or GCS? We're considering adding a policy to delete files older than 14 days for the backups and wals persisted by pgbackrest. We only need to be able to restore within a 7 day window.

We want to make sure that there aren't any files stored in S3 or GCS that are important but not updated / accessed with some regularity that would be critical for ensuring continued archiving or restoration for our retention window.

**Comment by dwsteele** [comment]
> We want to make sure that there aren't any files stored in S3 or GCS that are important but not updated / accessed with some regularity that would be critical for ensuring continued archiving or restoration for our retention window.

We believe all important files are updated, but currently we do not test this scenario so it is up to you to make sure it works for your use case.

We still believe that configuring retention (see https://pgbackrest.org/user-guide.html#retention) is a better option than policy-based expiration, which breaks the verify command, may make backups unrestorable, and risks corruption of even newer backups if there are dependencies. In addition, the info command will often give incorrect info about the repo. There's more, but you get the idea.

**Comment by efritz** [comment]
Specifically, we're looking for the policy to remove data that's no longer being managed by a former pgbackrest process (when a database in our fleet is removed), and wanted to ensure that setting a 2x longer expiration policy compared to our maximum supported backup interval wouldn't have any obvious issues with still-live processes.

**Comment by dwsteele** [comment]
It may be OK, depending on how you set retention vs auto-expiration. This is something you'll need to test to ensure it works correctly.

**Comment by pgstef** [comment]
> Hi, is "Object Storage Lifecycle" the only option? 

The only option? It even isn't the recommended option given we don't test that in CI.
S3 or any other repository type can be cleaned up by the `expire` command based on the retention settings. 
The expire command automatically runs after a successful backup. 

Given your config (`repo1-retention-full=1`) and the volume you're speaking about, or you have a very old backup with a lot of WAL archives (needed for PITR), or you have plenty of diff/incr backups.
To find out what is in your repo, you should use the `info` command.

**Comment by pgstef** [comment]
> I have to edit these settings in `postgresql.conf`
> 
> ```
> wal_keep_size = 10000           # in megabytes; 0 disables
> max_slot_wal_keep_size = 10000
> ```

Those have strictly nothing to do with the backups. That's the nb of WAL files PG will keep (mostly for streaming replication). Nothing to do with pgBackRest repository content.

The WAL archives in the backup repo are there for PG continuous archiving and PITR. When expiring backups, pgBackRest will expire the WAL archives that are not needed anymore. You'll have to take backups more often if you want to reduce the nb of WAL archives retained (and also lower your recovery time btw).
