### ISSUE TITLE
pgBackRest expire command fails with error "unable to find child 'Key':0 in node 'Error'"

### ISSUE THREAD

**Issue by yudelevi** [pgbackrest/pgbackrest#2259]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.49
2. PostgreSQL version:
15.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
One server, Rocky EL9

4. Did you install pgBackRest from source or from a package?
from package

5. Please attach the following as applicable:
[pgbackrest_error.log](https://github.com/pgbackrest/pgbackrest/files/13851360/pgbackrest_error.log)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/13851363/pgbackrest.conf.txt)

7. Describe the issue:
When running expire, the command fails with the following error:
```
ERROR: [029]: repo1: unable to find child 'Key':0 in node 'Error'
ERROR: [104]: expire command encountered 1 error(s), check the log file for details
```

The storage backend I'm using is Backblaze

**Comment by dwsteele** [comment]
It looks like B2 is returning a malformed (empty) error list. Since we request `Quiet` for the delete, we expect to see  errors in the response -- if there are no errors there should be no response. See https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html.

**Comment by yudelevi** [comment]
@dwsteele, this makes sense. Raised a ticket with B2 to review the compatibility on their end.

**Comment by dwsteele** [comment]
> Looks like this is fixed on B2 end, thank you for the help with debugging

Wow, that's geat. We've had a lot of issues with not-quite-compliant S3 clones over the years and they very rarely get fixed. Kudos to Backblaze!
