### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#226]
I understand how to setup pgbackrest to acommodate:

1. backups and restores
2. pulling from pgbackrest repo for streaming replication

But assume I have pgbackrest installed on a test server where I do backups and restores, but I also want to refresh with a backup from a production server.

How would I configure pgbackrest.conf to do both from the same test server?  Sorry if the answer should be obvious to all except me.

**Comment by dwsteele** [comment]
You could use multiple stanza and configure a different backup-host in each stanza.

I don't recommend mixing a test environment where you are doing backups with a production environment, though.  It's too easy to mix them up.  Test environments should only do restores only as a rule.
