### ISSUE TITLE
Unable to restore the timescale DB with postgresql on the Destination Server using pgbackrest 2.49

### ISSUE THREAD

**Issue by mudasirhaji** [pgbackrest/pgbackrest#2261]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.49

2. PostgreSQL version: 13.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 20.04

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I have  a staging timescaleDB with postgres 13.1 on which I took the backup using pgbackrest.
Then using scp I copied the backup into the destination server on which I installed the same version PostgreSQL 13.1 and timescale version extention.The copied database is in /var/lib/pgbackrest
Then in order to restore the database I first stopped the database on the destination server,deleted the data directory and the using the below command restored the database:
>> pgbackrest restore --stanza=Pgdb --log-level-console=info
The restoration was successful however after that I was not able to access the database:

psql -U postgres -h localhost
psql: error: connection to server at "localhost" (::1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
postgres@db-test:~$ psql -U postgres
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: Connection refused
        Is the server running locally and accepting connections on that socket?

I tried to use /usr/lib/postgresql/13/bin/pg_resetwal /var/lib/postgresql/13/main, however that didn't work also.

Kindly suggest what needs to be done to fix this issue?

[Pgdb-stanza-create.log](https://github.com/pgbackrest/pgbackrest/files/13884819/Pgdb-stanza-create.log)
[postgresql-13-main.log](https://github.com/pgbackrest/pgbackrest/files/13884821/postgresql-13-main.log)

Unable to down the .conf files so renamed them to .log:

[pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/13884970/pgbackrest.log)
[postgresql.log](https://github.com/pgbackrest/pgbackrest/files/13884971/postgresql.log)

Thanks

**Comment by pgstef** [comment]
The PG logs are pretty self-explanatory :

```
WARN: repo1: [ArchiveMismatchError] unable to retrieve the archive id for database version '13' and system-id '6989064693945008823'
ERROR: [103]: unable to find a valid repository
...
2024-01-10 07:15:38.128 UTC [57200] HINT:  If you are restoring from a backup, touch "/var/lib/postgresql/13/main/recovery.signal" and add required recovery options.
        If you are not restoring from a backup, try removing the file "/var/lib/postgresql/13/main/backup_label".
        Be careful: removing "/var/lib/postgresql/13/main/backup_label" will result in a corrupt cluster if restoring from a backup.
```

To me your restore command wasn't successful (the recovery signal would exist otherwise) and PG can't find the WAL archives needed for its consistency recovery.

> I have a staging timescaleDB with postgres 13.1 on which I took the backup using pgbackrest.

It would be good to have the config of that server, the backup command log and a view of your repo content (using `pgbackrest info`).

> using scp I copied the backup into the destination server

Your problem will most probably come from that step. Copying parts of the repo will break your recovery. You don't only need the backup set, you need the WAL archives, the info files,...
Usually the easiest way to restore a backup on a different server is to share the production repository and reach it (preferably in RO) from the server where you want to restore.

> I tried to use /usr/lib/postgresql/13/bin/pg_resetwal 

Don't do that. You'll corrupt your cluster. WAL recovery is a part of PG to reach consistency.

At this point, you probably need more readings about [PG backup/recovery](https://www.postgresql.org/docs/current/continuous-archiving.html) and to understand that for a successful `pgbackrest restore` you need a consistent repo.

Kind Regards

**Comment by mudasirhaji** [comment]
Hi pgstef,

pls find the attached data of the staging server.
[pgbackrest.info.log](https://github.com/pgbackrest/pgbackrest/files/13885194/pgbackrest.info.log)
[stagingbackup.log](https://github.com/pgbackrest/pgbackrest/files/13885196/stagingbackup.log)

I also copied manually the pg_wal from the staging to the destination:
scp -r /var/lib/postgresql/13/main/pg_wal/* 192.168.20.30:/var/lib/postgresql/13/main/pg_wal/

Will go through the documentation again.

Thanks

**Comment by pgstef** [comment]
> I also copied manually the pg_wal from the staging to the destination:
> scp -r /var/lib/postgresql/13/main/pg_wal/* 192.168.20.30:/var/lib/postgresql/13/main/pg_wal/

heh no, that's the current wal segments of your running database, not the wal segments that were generated during the backup. You definitely should read about PG backups basics.
You need to copy the pgBackRest repo, not something from the running database.

You even didn't specified what you copied exactly in your first post. 

> using scp I copied the backup into the destination server

If you want help, you'll need to tell us what you copied exactly (and the restore command used). As I mentioned earlier, you need the entire repo (basically you have a full and an incr backup, so even if you want to restore the incr, you'll need the full too).

Don't try to copy only some parts of the repository unless you exactly know what your are doing. 
Storing the backups on a shared storage and accessing it from the server where you want to restore will be much easier for you.

**Comment by mudasirhaji** [comment]
this is the command I used on the source database to copy the back on the destination server:
>>  scp -r /var/lib/pgbackrest/backup/Pgdb/* 192.168.20.30:/var/lib/pgbackrest/backup/Pgdb

then on the destination server I used the below command to restore:

>> pgbackrest restore --stanza=Pgdb --log-level-console=info

**Comment by pgstef** [comment]
> this is the command I used on the source database to copy the back on the destination server:
> 
> > scp -r /var/lib/pgbackrest/backup/Pgdb/* 192.168.20.30:/var/lib/pgbackrest/backup/Pgdb

Then you need to copy the archives directory too, as I mentioned several times already ;-)

**Comment by mudasirhaji** [comment]
you mean to say this one:
cd /var/lib/pgbackrest/
postgres@DB:/var/lib/pgbackrest$ ls
archive  backup

and after doing so will it be successfully restored?

**Comment by pgstef** [comment]
> you mean to say this one: cd /var/lib/pgbackrest/ postgres@DB:/var/lib/pgbackrest$ ls archive backup

Please, read https://www.postgresql.org/docs/current/continuous-archiving.html
You need the WAL archives for a succesful PG recovery.
So yes, you need to copy the entire content of your pgBackRest repository (`/var/lib/pgbackrest`), not only the `backup` part but the `archive` too.

> and after doing so will it be successfully restored?

If done correctly and nothing is missing, it could succeed. But I mentioned already several times that copying parts of the repository will make it harder unless you know exactly what you are doing. We don't recommend that at all.

**Comment by mudasirhaji** [comment]
thanks for sharing valuable information,

I copied the complete data from source /var/lib/pgbackrest into the destination server
the performed the restoration process:

>> pgbackrest restore --stanza=Pgdb --log-level-console=info
2024-01-10 10:34:51.335 P00   INFO: restore command begin 2.49: --exec-id=75456-7ec12a53 --log-level-console=info --pg1-path=/var/lib/postgresql/13/main --repo1-path=/var/lib/pgbackrest --stanza=Pgdb
2024-01-10 10:34:51.574 P00   INFO: repo1: restore backup set 20231228-112906F_20240101-080030I, recovery will start at 2024-01-01 08:00:30

However as it was still going on I lost the ssh connection to the remote server and was unable to access for sometime...
now I am able to access......
when i check the below command:

pgbackrest info
stanza: Pgdb
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13): 000000010000002B000000A5/000000010000002B000000A9

        full backup: 20231228-112906F
            timestamp start/stop: 2023-12-28 11:29:06+00 / 2023-12-28 12:08:26+00
            wal start/stop: 000000010000002B000000A7 / 000000010000002B000000A7
            database size: 53.0GB, database backup size: 53.0GB
            repo1: backup set size: 9.6GB, backup size: 9.6GB

        incr backup: 20231228-112906F_20240101-080030I
            timestamp start/stop: 2024-01-01 08:00:30+00 / 2024-01-01 08:00:32+00
            wal start/stop: 000000010000002B000000A9 / 000000010000002B000000A9
            database size: 53.0GB, database backup size: 8.3KB
            repo1: backup set size: 9.6GB, backup size: 444B
            backup reference list: 20231228-112906F
            
            Now after this I tried to login I am able to see all the schemas.
            
            Thanks a lot for your help....highly appreciate

**Comment by pgstef** [comment]
You should still read the PG logs on the restored cluster to find out if the recovery was good or not...

**Comment by mudasirhaji** [comment]
sure I will.....

**Comment by Jamal-B** [comment]
@pgstef In the Mudasirhaji's (very specific) use case (i.e no need of PITR), it would be possible to perform backups using the [--archive-copy](https://pgbackrest.org/configuration.html#section-backup/option-archive-copy) option to get consistent backup without having to get WALs from the `archive` pgbackrest directory, no? But indeed, it consumes more disk space, especially if the database is very transactional.

**Comment by pgstef** [comment]
> @pgstef In the Mudasirhaji's (very specific) use case (i.e no need of PITR), it would be possible to perform backups using the [--archive-copy](https://pgbackrest.org/configuration.html#section-backup/option-archive-copy) option to get consistent backup without having to get WALs from the `archive` pgbackrest directory, no? But indeed, it consumes more disk space, especially if the database is very transactional.

Theoretically, yes. But then you'd need to adjust the restore command to avoid fetching from archives etc. That requires more knowledge of the processes (both PG recovery and pgBackRest repository content).

Copying parts of the repository isn't something we recommend anyway. The largely easier solution is to share the original repo in read-only to the server where you want to restore.

Anyway, given the original question was leading towards missing WAL archives for the PG recovery, I assume we can close this issue now.

Kind regards

**Comment by Jamal-B** [comment]
>But then you'd need to adjust the restore command to avoid fetching from archives etc

Still for the Mudasirhaji use case, what about using [restore --type=none](https://pgbackrest.org/1/command.html#command-restore/category-command/option-type) in order to avoid any additional WAL recover? So only the WALs taken during the backup and included in it (thanks to the `--archive-copy` option), will be replayed by postgres at the first startup to reach a consistent state. And in this case, the (not generated) `restore_command` is not needed. Am I wrong?

However I completely agree that it's better and safer to use pgbackrest according to the best practices and the recommandations :slightly_smiling_face: 

Best regards.

**Comment by pgstef** [comment]
> Still for the Mudasirhaji use case, what about using [restore --type=none](https://pgbackrest.org/1/command.html#command-restore/category-command/option-type) in order to avoid any additional WAL recover? So only the WALs taken during the backup and included in it (thanks to the `--archive-copy` option), will be replayed by postgres at the first startup to reach a consistent state. And in this case, the (not generated) `restore_command` is not needed. Am I wrong?

Again, unless you exactly know what you are doing, you shouldn't do that. The recovery signal will be skipped and PG will in most cases see that as a crash recovery, not a backup recovery.

Our docs clearly states to stay away from that option:

>  Recovery type=none should be avoided because the timeline will not be incremented at the end of recovery. This can lead to, for example, PostgreSQL attempting to archive duplicate WAL, which will be rejected, and may cause the disk to fill up and result in a PostgreSQL panic. In addition, tools like pg_rewind may not work correctly or may cause corruption. 

I would rather recommend to use the `restore --type=immediate` and tweak `restore_command = 'false'`.
When the backup was taken with `--archive-copy`, this should let Postgres recovery successfully.

```
# in postgresql.auto.conf 
# Recovery settings generated by pgBackRest restore on 2024-01-12 15:46:44
restore_command = 'false'
recovery_target = 'immediate'
recovery_target_timeline = 'current'

# in Postgres logs
2024-01-12 15:47:14.622 UTC [25402] LOG:  starting point-in-time recovery to earliest consistent point
2024-01-12 15:47:14.627 UTC [25402] LOG:  redo starts at 0/683EB050
2024-01-12 15:47:17.957 UTC [25400] LOG:  restartpoint starting: wal
2024-01-12 15:47:20.210 UTC [25400] LOG:  restartpoint complete: wrote 1885 buffers (11.5%); 0 WAL file(s) added, 33 removed, 0 recycled; write=1.860 s, sync=0.299 s, total=2.253 s; sync files=11, longest=0.198 s, average=0.028 s; distance=536725 kB, estimate=536725 kB; lsn=0/A6D476A0, redo lsn=0/890104C8
2024-01-12 15:47:20.213 UTC [25400] LOG:  recovery restart point at 0/890104C8
2024-01-12 15:47:20.213 UTC [25400] DETAIL:  Last completed transaction was at log time 2024-01-12 15:27:23.992125+00.
2024-01-12 15:47:20.213 UTC [25400] LOG:  restartpoint starting: wal
2024-01-12 15:47:20.274 UTC [25402] LOG:  consistent recovery state reached at 0/C9EAFA68
2024-01-12 15:47:20.274 UTC [25402] LOG:  recovery stopping after reaching consistency
```

So yes, there are ways to use only some parts of the pgBackRest repository but that requires a good knowledge of PostgreSQL recovery and pgBackRest features.

**Comment by Jamal-B** [comment]
In my mind it wasn't critical to rely only on the crash recovery because, I really don't now why, I wrongly belevied the issue author was talking about a kind of ephemeral database instance daily restored from the primary backup only for testing purpose, and which didn't need to archive its own WALs.
Thank you for your valuable clarifications and the time you spent on that.

**Comment by mudasirhaji** [comment]
@pgstef are you available at the moment?
