### ISSUE TITLE
No stanzas exist in the repository

### ISSUE THREAD

**Issue by daulat0** [pgbackrest/pgbackrest#2262]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45

2. PostgreSQL version: 14.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  Amazon Linux2  (amzn2.x86_64 )

4. Did you install pgBackRest from source or from a package? Yes

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

archive_mode = on
archive_command = 'pgbackrest --stanza=dbtest1 archive-push %p'
max_wal_senders = 10
archive_timeout = 2700
listen_addresses = *

    - errors in the postgresql log file before or during the time you experienced the issue
    No error
Just, we are getting message "No stanzas exist in the repository" while running  "pgbackrest info" command

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We were running more than one cluster on the same server with different port (5432 and 5433). 
But after some time we deleted the cluster running on 5433 after that we are getting message "No stanzas exist in the repository" while running  "pgbackrest info" command.

Our backups are on s3 bucket.

If we check for one stanza  like "pgbackrest info --stanza=dbtest1" it gives output .

stanza: dbtest1
    status: error (no valid backups)
    cipher: none

    db (current)
        wal archive min/max (14): 0000000100000045000000DB/0000000100000045000000DD
[root@ip-172-31-8-67 data]#

No output for " pgbackrest info --output=json"

But for one stanza we get the output here also,

[root@ip-dummy]# pgbackrest info --stanza=dbtest1 --output=json

[{"archive":[{"database":{"id":1,"repo-key":1},"id":"14-1","max":"0000000100000045000000DD","min":"0000000100000045000000DB"}],"backup":[],"cipher":"none","db":[{"id":1,"repo-key":1,"system-id":7225859779290304301,"version":"14"}],"name":"dbtest1","repo":[{"cipher":"none","key":1,"status":{"code":2,"message":"no valid backups"}}],"status":{"code":2,"lock":{"backup":{"held":false}},"message":"no valid backups"}}][root@ip-172-31-8-67 data]#

I have tried by reinstalling pgbackrest but no solution.

**Comment by daulat0** [comment]
We deleted the Cluster by "rm -rf <DATA_DIRECTORY>"  without deleted the
stanza created by using the port 5433

pgbackrest.contains:

[dbtest1]
repo1-path=/pgB-bkp/
repo1-retention-full=2
repo1-s3-endpoint=s3.us-east-2.amazonaws.com
repo1-s3-bucket=
repo1-s3-region=us-east-2
repo1-type=s3
repo1-s3-key=
repo1-s3-key-secret=
start-fast=y
pg1-path=/opt/PostgreSQL-14/data
pg1-port=5432
pg1-user=postgres
pg1-socket-path=/tmp

Thanks,

**Comment by pgstef** [comment]
> We deleted the Cluster by "rm -rf <DATA_DIRECTORY>" without deleted the stanza created by using the port 5433 

Deleting a data directory won't affect the content of the repo. I mean that's the first step when you want to restore a backup. So you definitely not only did that.

> pgbackrest.contains:
> 
> [dbtest1]
> repo1-path=/pgB-bkp/
> repo1-retention-full=2
> repo1-s3-endpoint=s3.us-east-2.amazonaws.com
> repo1-s3-bucket=
> repo1-s3-region=us-east-2
> repo1-type=s3
> repo1-s3-key=
> repo1-s3-key-secret=
> start-fast=y
> pg1-path=/opt/PostgreSQL-14/data
> pg1-port=5432
> pg1-user=postgres
> pg1-socket-path=/tmp

There's your problem then. You don't specify the `[global]` section.
When specifying the `--stanza` option to the info command, it will get the `repo1` info from the `[dbtest1]` section while when you don't specify `--stanza`, it will get it from the `[global]` section.
Fix your configuration (by moving the `repo1` options to the global section for example) and it should be better.

Regards
