### ISSUE TITLE
Do repo numbers have to be consecutive?

### ISSUE THREAD

**Issue by pellepelster** [pgbackrest/pgbackrest#2266]
The documentation states that:

``` 
The repository section defines options used to configure the repository.
Indexing: All repo- options are indexed to allow for configuring multiple repositories. For example, a single repository is configured with the repo1-path, repo1-host, etc. options. If there is more than one repository configured and the --repo option is not specified for a command, the repositories will be acted upon in highest priority order (e.g. repo1 then repo2). 
```

Does this imply that the repository numbers need to be consecutive or are  gaps ok, like for example:

```
repo1-type=s3

...

repo2-type=posix

...

repo4-type=s3
```

I was not able to find any previous answer or issue regarding this issue.

**Comment by pgstef** [comment]
Hi,

Your example doesn't contain gaps. You don't have to group it by repository type if that's the question.
I haven't tried lately but I believe using repo1 and repo3 (omit repo2) would work fine.

I'd wouldn't recommend it though. When you don't specify the `--repo` option for some commands, repositories are treated in priority order (1, then 2, then 3,...). If your command is running fine with repo1+repo3 and then suddenly someone adds repo2 without you knowing, it could change your command behavior/result.

So it should work but I don't really see the point of having gaps :thinking: 

Kind Regards
