### ISSUE TITLE
Is it possible to use separate CA certs for generating the certificates used by the TLS server?

### ISSUE THREAD

**Issue by ErthoAers** [pgbackrest/pgbackrest#2269]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.49

2. PostgreSQL version: 15.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: debian

4. Did you install pgBackRest from source or from a package? from package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I'm setting up the TLS server in a database host `pg-srv` and a repository host `backup-srv` guided by the [documents](https://pgbackrest.org/user-guide-rhel.html#repo-host/config). I generated the certificates with 2 separate CA certs `ca1.crt` and `ca2.crt` for the repo host and the backup host. The pgbackrest config files look like:

```
# config in repo host backup-srv
[db]
pg1-host=pg1-srv
pg1-host-ca-file=/backup/certs/ca1.crt
pg1-host-cert-file=/backup/certs/backup-srv.crt
pg1-host-key-file=/backup/certs/backup-srv.key
pg1-host-type=tls
pg1-path=/mnt/disks/pgsql/data
pg1-socket-path=/tmp
pg1-user=pgbackrest

[global]
tls-server-address=*
tls-server-auth=pg1-srv=*
tls-server-ca-file=/backup/certs/ca1.crt
tls-server-cert-file=/backup/certs/backup-srv.crt
tls-server-key-file=/backup/certs/backup-srv.key
```

and 

```
# config in database host pg-srv
[global]
repo1-retention-full=9999999
repo1-path=/backup/repo
repo1-host=backup-srv
repo1-host-ca-file=/backup/certs/ca2.crt
repo1-host-cert-file=/backup/certs/pg-srv.crt
repo1-host-key-file=/backup/certs/pg-srv.key
repo1-host-type=tls
tls-server-address=*
tls-server-auth=backup-srv=*
tls-server-ca-file=/backup/certs/ca2.crt
tls-server-cert-file=/backup/certs/pg-srv.crt
tls-server-key-file=/backup/certs/pg-srv.key
```

I omit some parts of the pgbackrest config but only keep the parts for the TLS connections. However, I got and error when I tried to perform restore from the database host by running `pgbackrest restore`:

```
ERROR: [095]: unable to verify certificate presented by 'backup-srv:8432': [20] unable to get local issuer certificate
```

I also tried copy the `ca1.crt` to the database host and specify `repo1-host-ca-file=/backup/certs/ca1.crt` instead of `ca2.crt` to test out the same command, but got another error:

```
ERROR: [095]: unable to find hostname 'backup-srv' in certificate common name or subject alternative names
```

I'm pretty sure that I use the right common name for generating the certs but it still failed for this. I'm just wondering if it's possible to use 2 separate CAs to generates, or they should be the same CA for the 2 sets of certificates. Or did I misunderstand anything when setting up the TLS servers?

**Comment by dwsteele** [comment]
The client and server certs for each pair must be generated with the same CA. Other than that, you can use different CAs if you prefer and like making things difficult.
