### ISSUE TITLE
backup/restore a schema

### ISSUE THREAD

**Issue by JPGit** [pgbackrest/pgbackrest#227]
This is a request for a new feature to allow backup/restore of a specific schema within the database. The use case we have is to have multiple tenants in our database segregated by schemas. When upgrading a tenant,  I would like to backup the schema and then if need be,  restore the schema, either overwriting the existing or to a new schema. My current intention is to use pg_dump for this functionality, but it would be good take advantage of pgbackrest multi-threading.

**Comment by MichaelDBA** [comment]
While you are at it, perhaps integrate a bit more into it by use of the -T and -t pg_dump parms to exclude and include specific tables?  Am I being too greedy?

**Comment by dwsteele** [comment]
We're definitely thinking about this feature but it is not currently a priority.  I'll let you know if that changes.

**Comment by dwsteele** [comment]
Well, let me clarify a bit.  Restoring a schema into an existing cluster without affecting other schemas/dbs is not even on the roadmap (and definitely not while online!)  This would require fine manipulation of the catalogs which is not likely to be implemented in pgBackRest anytime soon, if ever.

In this case pg_dump really is your friend.

**Comment by JPGit** [comment]
Thank you for clarification. I will keep with pg_dump

**Comment by edib** [comment]
What about the cases like offline restore. For example I needed a 3GB table today but I had to restore whole cluster. It seems that ignoring the consistency I should restore single table with PITR. If I want to develop something like that, can I develop it over the code of pgbackrest?

**Comment by dwsteele** [comment]
Ignoring consistency is harder than you think.  If you bring in a table with a clog that doesn't match you might see anything -- or nothing.

Of course you are welcome to hack on it and see what you can come up with.  If it works we'd be happy have a look.

BTW, if you respond to a long-closed issue you may not always get a reply.  I only see the notification once and if it's not in open issues I'm not reminded.
