### ISSUE TITLE
Is it possible to create backup from s3 repo?

### ISSUE THREAD

**Issue by tomasz-grzesik** [pgbackrest/pgbackrest#2270]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by dwsteele** [comment]
Yes, but that's about all I can say since you have not given any details. See https://pgbackrest.org/user-guide.html#s3-support.

**Comment by tomasz-grzesik** [comment]
I have manage do it.
Basebackup from primary and on standby additional settings in postgres.conf:
`restore_command = 'pgbackrest --stanza=nsdb archive-get %f "%p"'`

Is it possible do it without basebackup?
Have I use to some s3 sync software to download all files or is some builtin in pgbackrest solution?

**Comment by dwsteele** [comment]
> Have I use to some s3 sync software to download all files or is some builtin in pgbackrest solution?

You have given us almost zero information about what you are doing -- so I have no idea.

What is your backup command? What is your restore command? Configuration on hosts? What are you trying to accomplish?
