### ISSUE TITLE
Does it support limiting IO rate during backup or recovery

### ISSUE THREAD

**Issue by 1053531172** [pgbackrest/pgbackrest#2273]
When I was backing up, the pgbackrest process filled up all of my machine's IO. If it were to recover across machines, it would also occupy all of my bandwidth. What should I do to limit it?

**Comment by pgstef** [comment]
Hi,

We don't have any throttling parameters ATM. There's a [project card](https://github.com/pgbackrest/pgbackrest/projects/2#card-8956984) about it, but not planned.

It is complicated to give you any advise without you providing any configuration used nor any information about your systems.

Kind Regards

**Comment by dwsteele** [comment]
Right now the only practical way to throttle is by setting `process-max` appropriately. Compression is expensive and it limits IO pretty effectively. If IO is maxed when `process-max=1` you may want to consider increasing resources on the host.

On a restore, generally, you'll want to use all available IO to make the restore run as quickly as possible.
