### ISSUE TITLE
ERROR: [058]: version '16' and path '/bitnami/postgresql/data' queried from cluster do not match version '13' and '/bitnami/postgresql/data' read from 

### ISSUE THREAD

**Issue by xci-mrt** [pgbackrest/pgbackrest#2284]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
**2.33**
2. PostgreSQL version:
**bitnami 16**
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
**linux (in docker)** 

5. Did you install pgBackRest from source or from a package?
from source (apt)

7. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
repo1-path=/opt/backup/postgres/
repo1-retention-full=2
log-level-console=info
log-level-file=debug

[backrest]
pg1-path=/bitnami/postgresql/data
pg1-socket-path=/tmp/
pg1-host-user=postgres
pg1-host-port=5432
pg1-user=postgres

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

**postgres@1dcd5fd5e2d7:/$ pgbackrest --stanza=xci check
2024-02-14 07:40:44.009 P00   INFO: check command begin 2.33: --exec-id=248-90fcc2b2 --log-level-console=info --log-level-file=debug --pg1-path=/bitnami/postgresql/data --pg1-socket-path=/tmp --pg1-user=postgres --repo1-path=/opt/backup/postgres --stanza=backrest
ERROR: [058]: version '16' and path '/bitnami/postgresql/data' queried from cluster do not match version '13' and '/bitnami/postgresql/data' read from '/bitnami/postgresql/data/global/pg_control'
       HINT: the pg1-path and pg1-port settings likely reference different clusters.
2024-02-14 07:40:44.621 P00   INFO: check command end: aborted with exception [058]**

**postgres@1dcd5fd5e2d7:cd /bitnami/postgresql/data/
postgres@1dcd5fd5e2d7:/bitnami/postgresql/data$ cat PG_VERSION
16**

**psql (16.1)
Type "help" for help.

postgres=# select * from pg_control_system();
 pg_control_version | catalog_version_no |  system_identifier  | pg_control_last_modified
--------------------+--------------------+---------------------+--------------------------
               1300 |          202307071 | 7335337203357933679 | 2024-02-14 07:42:53+00
(1 row)**

**psql (16.1)
Type "help" for help.

postgres=# show data_directory;
      data_directory
--------------------------
 /bitnami/postgresql/data
(1 row)**

8. Describe the issue:
I´m trying to do a stanza check. But keep getting the issue  version '16' and path '/bitnami/postgresql/data' queried from cluster do not match version '13' and '/bitnami/postgresql/data' read from '/bitnami/postgresql/data/global/pg_control'.
I have searched all the other issues about the same issue, but none of the solutions works for me, i have no symlink and data_directory is set in my postgresql.

**Comment by pgstef** [comment]
Hi,

This seems like a PG installation problem. pg_control_version is `1300`. What PG version did you install exactly and how?

**Comment by xci-mrt** [comment]
I downloaded the bitnami postgresql-repmngr 16.1.0, because i need the replication management. 

But the strange thing, is that if i use the official postgres 16 container, and check the pg_control_version, i get the same result, 1300, and version 16 in the PG_VERSION for the database, but the pgbackrest is working on that one. but without repmngr

**Output from vanilla postgres 16:**
psql (16.1 (Debian 16.1-1.pgdg120+1))
Type "help" for help.

postgres=# select * from pg_control_system();
 pg_control_version | catalog_version_no |  system_identifier  | pg_control_last_modified
--------------------+--------------------+---------------------+--------------------------
               1300 |          202307071 | 7335368586466066471 | 2024-02-14 08:16:30+00
(1 row)

root@e678c7759e77:/etc# cd /var/lib/postgresql/data
root@e678c7759e77:/var/lib/postgresql/data# ls
base  global  pg_commit_ts  pg_dynshmem  pg_hba.conf  pg_ident.conf  pg_logical  pg_multixact  pg_notify  pg_replslot  pg_serial  pg_snapshots  pg_stat  pg_stat_tmp  pg_subtrans  pg_tblspc  pg_twophase  PG_VERSION  pg_wal  pg_xact  postgresql.auto.conf  postgresql.conf  postmaster.opts  postmaster.pid
root@e678c7759e77:/var/lib/postgresql/data# cat PG_VERSION
16

**Comment by pgstef** [comment]
What if you run `show port;` in psql?
And what does `pg_controldata -D /bitnami/postgresql/data` returns?

**Comment by xci-mrt** [comment]
here is the output

psql (16.1)
Type "help" for help.

postgres=# show port;
 port
------
 5432
(1 row)

postgres=# exit
could not save history to file "//.psql_history": Permission denied
I have no name!@1dcd5fd5e2d7:/$ pg_controldata -D /bitnami/postgresql/data/
pg_control version number:            1300
Catalog version number:               202307071
Database system identifier:           7335337203357933679
Database cluster state:               in production
pg_control last modified:             Wed 14 Feb 2024 07:42:53 AM UTC
Latest checkpoint location:           0/4044568
Latest checkpoint's REDO location:    0/4044530
Latest checkpoint's REDO WAL file:    000000010000000000000004
Latest checkpoint's TimeLineID:       1
Latest checkpoint's PrevTimeLineID:   1
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0:762
Latest checkpoint's NextOID:          24639
Latest checkpoint's NextMultiXactId:  1
Latest checkpoint's NextMultiOffset:  0
Latest checkpoint's oldestXID:        722
Latest checkpoint's oldestXID's DB:   1
Latest checkpoint's oldestActiveXID:  762
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:0
Latest checkpoint's newestCommitTsXid:0
Time of latest checkpoint:            Wed 14 Feb 2024 07:42:53 AM UTC
Fake LSN counter for unlogged rels:   0/3E8
Minimum recovery ending location:     0/0
Min recovery ending loc's timeline:   0
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    replica
wal_log_hints setting:                off
max_connections setting:              600
max_worker_processes setting:         8
max_wal_senders setting:              16
max_prepared_xacts setting:           0
max_locks_per_xact setting:           64
track_commit_timestamp setting:       off
Maximum data alignment:               8
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float8 argument passing:              by value
Data page checksum version:           0
Mock authentication nonce:            fed8a8cce48a6acb5b7c1cbce294ce086f9945e4c3fbb64a2e5f2b8a77d22c70

**Comment by pgstef** [comment]
You're running pgBackRest from inside the db container right? 

`pg1-host-user=postgres` and `pg1-host-port=5432` won't be used since you're not trying to reach a `pg1-host` but a local path/cluster. The default `pg1-port` is 5432 which seems ok with your current cluster.

Maybe `show unix_socket_directories;` will give another lead but I kinda fear that you're not running pgBackRest on the db host directly.

**Comment by pgstef** [comment]
2.33 is very old. Does it do the same with the latest release?

**Comment by pgstef** [comment]
> 1. pgBackRest version:
>        **2.33**

> But the strange thing, is that if i use the official postgres 16 container, and check the pg_control_version, i get the same result, 1300, and version 16 in the PG_VERSION for the database, but the pgbackrest is working on that one. but without repmngr

Did you use 2.33 in both cases? Because 2.33 is pretty old and only supported up until PG 13 back then. 
Can you try again with the latest release? (or at least above 2.46 where PG 16 support was added)

**Comment by xci-mrt** [comment]
Hello again, got the 2.50 installed, and its now working. thanks for the brilliant support! :)

**Comment by pgstef** [comment]
Cool. Since 2.33 was only supporting up until PG 13, that can explain the `do not match version '13'`. 
That's why you didn't had the problem with testing vanilla PG, and why it's important to use the latest releases :-)

**Comment by xci-mrt** [comment]
I actually thought i had the newest version, but because i just used normal apt repo it only contains 2.33.. :)
