### ISSUE TITLE
Apply more pg_wals after restore.

### ISSUE THREAD

**Issue by mateivladimir** [pgbackrest/pgbackrest#2285]
Hello everyone. I've just test a PITR on a PostgreSQL 15 database, which works as I plan. After I PITR at 10:00:00 yesterday (let's say) I see that my data isnt that, so i need to increment PITR with 5 minute. The problem is that, if I remove the data dir and do another pgbackrest --stanza=my-stanza restore --type=time --target="2024-02-13 10:05:00", the backup restore in 3-4 hours, which is a lot of time (It's ok because my database is 1TB)

So, it exists a solution to apply only the rest of 5 minute remains and speed the process ?

**Comment by pgstef** [comment]
Imo you have 2 possibilities. 

If you handle correctly your PG recovery process, PG should pause the recovery once it reaches your target, letting you RO access to check it is like you want. If you don't promote, you can stop PG, change manually the "recovery_target_time" (which should be in `postgresql.auto.conf`) to a further point and start PG again. PG should be able to go ahead with the recovery. That's pretty easy to do, but that's a PG behavior, not pgBackRest (restore isn't recovery, those are 2 different things).

If you have to restore again, then simply don't remove the entire data directory. Just use `restore --delta` which will then skip copying the files that are already on disk and only delete/fetch what's needed.

**Comment by mateivladimir** [comment]
Thank you so much. I'm new in pgbackrest solution and that's why i choose to ask :). Many regards.

**Comment by pgstef** [comment]
Just keep in mind that even if pgBackRest can help with taking backups, the restore command is only preparing all the files for the PostgreSQL recovery. The recovery process is handled by PostgreSQL itself. I can suggest the [following reading](https://www.postgresql.org/docs/16/runtime-config-wal.html#RUNTIME-CONFIG-WAL-RECOVERY-TARGET) if you want to have a look at the available recovery targets.

**Comment by mateivladimir** [comment]
The classical restore command I used many times, but i didn't know that pgBackRest used the same mechanism. Thanks for clearing me up :).
