### ISSUE TITLE
Backup to object storage that are mounted

### ISSUE THREAD

**Issue by jagg1994** [pgbackrest/pgbackrest#2288]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.50 

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 22.04

4. Did you install pgBackRest from source or from a package? from source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: My server is mounted a object storage (NAS). when i tried to Create the Stanza. it will failed. It gives permission error even correct permissions are given. Please help to solve this issue.

**Comment by dwsteele** [comment]
You haven't provided any of the requested information, the error, or applicable logs, so there this nothing we can do here.
