### ISSUE TITLE
repo1-retention-full-type=time

### ISSUE THREAD

**Issue by YashCharpe** [pgbackrest/pgbackrest#2290]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.41

2. PostgreSQL version: PostgreSQL 13.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Debian 11

4. Did you install pgBackRest from source or from a package?

I install from source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

6. Describe the issue:
I changed pgbackrest.conf file to below from it's default values (repo1-retention-full-type=count)
```
repo1-retention-full-type=time
repo1-retention-full=14
repo1-retention-diff=3
```
But apparently, it doesn't seem to be working. According to the above values, as per my understanding, it should remove diff backups older than 3 days and full backups older than 14 days. But whenever the expire command is run, it retains the latest 3 diff backups and removes every other diff backups, so I think it's still working as per repo1-retention-full-type=count value.

Config:
1) pgbackrest.conf
```
[global]
repo1-type=s3
repo1-path=/physical-backups
repo1-s3-uri-style=path
repo1-s3-region=<some_value>
repo1-s3-endpoint= <some_value>
repo1-s3-key=<some_value>
repo1-s3-key-secret=<some_value>
repo1-s3-bucket=<some_value>
start-fast=y
repo1-retention-full-type=time
repo1-retention-full=14
repo1-retention-diff=3
log-level-console=info
log-level-file=debug
log-path=/var/log/pgbackrest/

<some_value>
pg1-path=/opt/pgsql/data/13
pg1-user=postgres
```

2) Stanza info (before running the diff backup)
```
db (current)
        wal archive min/max (13): 000000030000006300000010/00000003000000690000003C

        full backup: 20240218-010003F
            timestamp start/stop: 2024-02-18 01:00:03 / 2024-02-18 01:32:59
            wal start/stop: 0000000300000065000000A8 / 0000000300000065000000B5
            database size: 26GB, database backup size: 26GB
            repo1: backup set size: 18.0GB, backup size: 18.0GB

        full backup: 20240225-010002F
            timestamp start/stop: 2024-02-25 01:00:02 / 2024-02-25 01:31:05
            wal start/stop: 0000000300000068000000A5 / 0000000300000068000000A7
            database size: 26.1GB, database backup size: 26.1GB
            repo1: backup set size: 18.0GB, backup size: 18.0GB

        diff backup: 20240225-010002F_20240226-062621D
            timestamp start/stop: 2024-02-26 06:26:21 / 2024-02-26 06:26:39
            wal start/stop: 000000030000006900000035 / 000000030000006900000035
            database size: 26.1GB, database backup size: 2.8GB
            repo1: backup set size: 18.0GB, backup size: 621.6MB
            backup reference list: 20240225-010002F

        diff backup: 20240225-010002F_20240226-062836D
            timestamp start/stop: 2024-02-26 06:28:36 / 2024-02-26 06:28:54
            wal start/stop: 000000030000006900000037 / 000000030000006900000037
            database size: 26.1GB, database backup size: 2.8GB
            repo1: backup set size: 18.0GB, backup size: 621.7MB
            backup reference list: 20240225-010002F

        diff backup: 20240225-010002F_20240226-064318D
            timestamp start/stop: 2024-02-26 06:43:18 / 2024-02-26 06:43:36
            wal start/stop: 000000030000006900000039 / 000000030000006900000039
            database size: 26.1GB, database backup size: 2.8GB
            repo1: backup set size: 18.0GB, backup size: 621.7MB
            backup reference list: 20240225-010002F
```
3) Diff backup log file after running the diff backup
```
2024-02-26 07:41:59.953 P00   INFO: backup stop archive = 00000003000000690000003E, lsn = 69/3E0112E8
2024-02-26 07:42:00.074 P00   INFO: check archive for segment(s) 00000003000000690000003E:00000003000000690000003E
2024-02-26 07:42:00.595 P00   INFO: new backup label = 20240225-010002F_20240226-074139D
2024-02-26 07:42:02.134 P00   INFO: diff backup size = 2.8GB, file total = 61489
2024-02-26 07:42:02.137 P00   INFO: backup command end: completed successfully (23518ms)
2024-02-26 07:42:02.138 P00   INFO: expire command begin 2.41: --exec-id=17259-1062e2c4 --log-level-console=info --log-level-file=debug --log-path=/var/log/pgbackrest/ --repo1-path=/physical-backups --repo1-retention-diff=3 --repo1-retention-full=14 --repo1-retention-full-type=time --repo1-s3-bucket=<some_value> --repo1-s3-endpoint=<some_value> --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=<some_value> --repo1-s3-uri-style=path --repo1-type=s3 --stanza=<some_value>
2024-02-26 07:42:02.305 P00   INFO: repo1: expire diff backup 20240225-010002F_20240226-062621D
2024-02-26 07:42:02.508 P00   INFO: repo1: remove expired backup 20240225-010002F_20240226-062621D
2024-02-26 07:42:02.893 P00   INFO: repo1: time-based archive retention not met - archive logs will not be expired
2024-02-26 07:42:02.893 P00   INFO: expire command end: completed successfully (756ms)
```

As per my understanding and the rules we've set, it should not have expired any backup as we don't have any diff backups older than 3 days, but whenever I run diff backup, it retains latest 3 diff backups and expires other backups.

Kindly advise what steps can be done to resolve this issue. Thanks!

**Comment by pgstef** [comment]
Hi,

As per the documentation states, [--repo-retention-full-type](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-full-type) is applied to FULL backups.

[--repo-retention-diff](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-diff) is always a number of differential backups to retain. Since they are always referring to a prior FULL backup, DIFF will be expired with the FULL backup they are referring to. And you can lower the number of DIFF to retain with this option. But the time expiration is, as the option name let you guess, applied to full backups only.

Kind Regards

**Comment by YashCharpe** [comment]
Closing this issue. Thanks @pgstef for working on this!
