### ISSUE TITLE
pgbackrest note

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#2295]
How about a congrats to @dwsteele (David Steele) on the 10th anniversary (v0.10 Released March 5, 2014) of pgbackrest?

**Comment by dwsteele** [comment]
Haha, cool! I remembered about this last month but then completely forgot when it came around. It has been a good ten years -- things are certainly a lot different now than they were back then. Here's to ten more years!

**Comment by MichaelDBA** [comment]
closing now to avoid cluttering...
