### ISSUE TITLE
Replica only backup.

### ISSUE THREAD

**Issue by thedolphin** [pgbackrest/pgbackrest#2297]
Feature request

If leader has `archive_mode = off`, then on replica `archive-mode-check=n` should be automatically applied and backup should proceed. That means WALs are collected from replica only and backup is taken from replica only too.

**Comment by dwsteele** [comment]
We have discussed this a feature but it has not made it onto the roadmap. One issue is that we are not guaranteed to get the last WAL segment in the archive when the backup ends, i.e. we cannot guarantee the consistency of the backup.

Also, I did a pretty extensive review of replication and recovery when developing our current method and I was not satisfied with the backup from standby-only approach -- mainly copying pg_control last and expecting it to contain the correct values. Backup from primary appears safer and more reproducible.

**Comment by thedolphin** [comment]
I mean, while pgpackrest has access to the leader to make any checks for proper backup generation, leader's `archive_mode` setting check should not be the show stopper.

Okay, my scenario: I have pretty old legacy instance of non-interruptable postgres with no `archive_mode` set. I made a replica with `archive_mode` and `archive_command` set. pgbackrest has access to leader via ssh and counter part pgbackrest. Now I want to start backup from replica. At this point I have to restart leader to set `archive_mode`, while I will never backup from leader, because i will switch to new replica soon.

**Comment by dwsteele** [comment]
That seems pretty specific to your use case so I can't see us supporting it. If we do support backup from standby-only it will be in the case where access to the primary is not possible/preferred.
