### ISSUE TITLE
Combining backup/restore with replication

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#230]
Many production pg sites have the typical master and slave using streaming replication.  It is used as a way to have a partial manual HA.  

In our particular case, we have a custom script on the master that sends archived WALs to the slave so it can pick them up in the recovery.conf restore_command. (leaving out replication slots).   We do full backups nightly using pg_basebackup() against the slave on the slave.  These slave local backups are moved after it is completed to a remote location.

ENTER PGBACKREST
After I have configured pgbackrest on the master and the slave to control replication, I have the normal pgbackrest configuration on the master and the replication type stanza on the slave pointing to the master as the backup host.  On the master I have this in the global settings:
backup-host=myslave
backup-user=postgres

On the slave, the stanza has this:
db-host=mymaster
db-user=postgres

How would I additionally setup the slave to do the backups from the master (pgbackrest has not come out yet with the version that allows backups from the slave) and store them on the pgbackrest repo on the slave?

I'm guessing I add another stanza on the slave without the replication lines?

**Comment by dwsteele** [comment]
Looks like your slave is already setup to do backups from the master.  Just run 'backup'.

**Comment by MichaelDBA** [comment]
Yes, but what do I do about replication. I have to replace the custom archive command script on the master with the pgbackrest one.  That script copies WALs to the slave.

**Comment by MichaelDBA** [comment]
I guess I could also execute pg_receivexlog() as a daemon on the slave as a workaround to the archive command sending WALs to the slave, whatcha think?

**Comment by dwsteele** [comment]
I'm not clear on why you would need to work around this - the wal segments are in the repo.  If you want them use archive-get to retrieve them from wherever you like.

**Comment by MichaelDBA** [comment]
Sorry for my confusion here,
