### ISSUE TITLE
dump 9.6 and restore to 16

### ISSUE THREAD

**Issue by Abraka** [pgbackrest/pgbackrest#2300]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: latest
2. PostgreSQL version: 9.6
4. Did you install pgBackRest from source or from a package? yes

Hello, its possible use pgbackrest to dump backup from psql v9.6 and restore it in psql v16?

Thx.

**Comment by pgstef** [comment]
Hi,

No. pgBackRest relies on PostgreSQL physical backups using [continuous archiving and file system level backup](https://www.postgresql.org/docs/current/continuous-archiving.html).

Dumps are logical exports, not real "backups". See [PostgreSQL docs](https://www.postgresql.org/docs/current/backup-dump.html) to learn the difference.

Kind Regards

**Comment by Abraka** [comment]
ok :(. thx
