### ISSUE TITLE
The latest version 2.50 is not available in  postgressql common repo

### ISSUE THREAD

**Issue by ydevendra** [pgbackrest/pgbackrest#2301]
The latest version 2.50 is not available in [postgressql common repo ](https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7.9-x86_64/)

latest package is [pgbackrest-2.49-1PGDG.rhel7.x86_64.rpm](https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7.9-x86_64/pgbackrest-2.49-1PGDG.rhel7.x86_64.rpm) only. 
I don't want to build and install 2.50 version

**Comment by pgstef** [comment]
Hi,

That's a question for PGDG repositories maintainers. We're not building the packages.
AFAIK, RHEL 7 is EOL for PGDG repositories anyway: https://yum.postgresql.org/news/rhel7-postgresql-rpms-end-of-life/

Kind Regards

**Comment by ydevendra** [comment]
@pgstef  
[pgbackrest-2.49-1PGDG.rhel7.x86_64.rpm](https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7.9-x86_64/pgbackrest-2.49-1PGDG.rhel7.x86_64.rpm)             **02-Jan-2024 16:49**              409668

**Comment by ydevendra** [comment]
2.49 is published in Jan 24, not sure if any issues with 2.50
Anyway, you are right this is a question from a different repo not for this.
