### ISSUE TITLE
Disaster recovery repository

### ISSUE THREAD

**Issue by mateivladimir** [pgbackrest/pgbackrest#2302]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.50

2. PostgreSQL version: 15.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: one database server, a "control node" server and 2 minio configured

4. Did you install pgBackRest from source or from a package? source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: It's more like a question. Did exists an option to make my 2nd minio fault tolerant ? I mean, if i perform a backup and let's say the first minio is out of space, the second minio to take place and finish my job. Many thanks.

**Comment by pgstef** [comment]
Hi,

> 6\. It's more like a question. Did exists an option to make my 2nd minio fault tolerant ? I mean, if i perform a backup and let's say the first minio is out of space, the second minio to take place and finish my job. Many thanks.

It's more a MinIO question then.

From a pgBackRest point of view, no, you can't achieve what you describe directly.
You can define multiple repositories to be used but it has various impacts. It is useful for WAL archives but the backup command is per repo, so if the repo fails during the backup, you'll need to schedule another one.

Kind Regards

**Comment by mateivladimir** [comment]
Indeed, that could be a problem. Many thanks for your response. Many regards !
