### ISSUE TITLE
Exclude tablespaces from the backup

### ISSUE THREAD

**Issue by AlexMcTrees** [pgbackrest/pgbackrest#2308]
I am trying to exclude tablespaces from the backup but could not find anything about this in documentation, options like
exclude = pg_tblspc/523299339/PG_12_201909212/
or
exclude = exclude=../../../../../srv/postgres/testing/PG_12_201909212/
won't work.

Is there a way to exclude tablespaces from the backup or this is not possible?

**Comment by dwsteele** [comment]
This would more than likely make your cluster unrestorable. If any table in that tablespace received writes during the backup then recovery will fail.

**Comment by AlexMcTrees** [comment]
Thanks for the reply. I understand this could happen if tables of one database are split between tablespaces.
But in my setup main database and testing databases are separated by tablespaces. One tablespace for main database on fast sdds and second tablespace for testing databases on much slower hdds. Everything works fine, except I could not exclude testing databases from the backup.
Is there a solution for such setup or perhaps an advice how to make this in the right way?

**Comment by dwsteele** [comment]
All databases in a single cluster should be considered one unit for the purposes of backup and restore. This is a limitation of PostgreSQL. The normal thing is to put your test databases in a separate cluster.
