### ISSUE TITLE
ERROR: option db-path must be set when relative xlog paths are used

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#231]
I have a pgbackrest-managed cluster with no relative paths for pg_xlog for the specific stanza.  So why would I get this error on the slave pg log file when starting it up.?  Using 1.04.

Now I have other clusters that have relative paths for px_xlog, but not this cluster I am starting up with pg_ctlcluster 9.4 demo start.

**Comment by MichaelDBA** [comment]
Ha, I accidentally deleted the demo stanza on the slave, so this is the ambiguous error you get when u screw up your conf file.  Perhaps a better error message?

**Comment by MichaelDBA** [comment]
At least I'm helping you with better error messages for stupid mistakes in configuration, ya think?

**Comment by dwsteele** [comment]
Added hints in 3320559.
