### ISSUE TITLE
Pg backrest can support the posstgres pro standard 16 

### ISSUE THREAD

**Issue by iabdukhoshimov** [pgbackrest/pgbackrest#2310]
``` pgbackrest --stanza=postgres-production-my2 stanza-create
WARN: configuration file contains stanza-only option 'pg1-socket-path' in global section 'global'
WARN: configuration file contains invalid option 'include-path'
2024-03-21 17:51:44.157 P00   INFO: stanza-create command begin 2.50: --exec-id=91472-39249043 --log-level-console=info --log-level-file=detail --log-path=/var/log/pgbackrest --pg1-host=192.168.10.30 --pg2-host=192.168.10.31 --pg3-host=192.168.10.32 --pg4-host=192.168.10.33 --pg5-host=192.168.10.34 --pg1-path=/var/lib/pgpro/std-16/data --pg2-path=/var/lib/pgpro/std-16/data --pg3-path=/var/lib/pgpro/std-16/data --pg4-path=/var/lib/pgpro/std-16/data --pg5-path=/var/lib/pgpro/std-16/data --pg1-port=5432 --pg2-port=5432 --pg3-port=5432 --pg4-port=5432 --pg5-port=5432 --pg1-socket-path=/tmp --pg2-socket-path=/tmp --pg3-socket-path=/tmp --pg4-socket-path=/tmp --pg5-socket-path=/tmp --repo1-path=/opt/db_backup/pgbackrest --repo1-type=posix --stanza=postgres-production-my2
WARN: unable to check pg1: [VersionNotSupportedError] unexpected control version = 1347421460 and catalog version = 202308051
      HINT: is this version of PostgreSQL supported?
WARN: unable to check pg2: [VersionNotSupportedError] unexpected control version = 1347421460 and catalog version = 202308051
      HINT: is this version of PostgreSQL supported?
WARN: unable to check pg3: [VersionNotSupportedError] unexpected control version = 1347421460 and catalog version = 202308051
      HINT: is this version of PostgreSQL supported?
WARN: unable to check pg4: [VersionNotSupportedError] unexpected control version = 1347421460 and catalog version = 202308051
      HINT: is this version of PostgreSQL supported?
WARN: unable to check pg5: [VersionNotSupportedError] unexpected control version = 1347421460 and catalog version = 202308051
      HINT: is this version of PostgreSQL supported?
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
2024-03-21 17:51:48.547 P00   INFO: stanza-create command end: aborted with exception [056] ```

**Comment by vitabaks** [comment]
@dwsteele Please see if it is possible to add support for [PostgresPro](https://postgrespro.com/products/download), which has a different version number.

It seems the only difference is that the version has an additional number (16.2.2 instead of 16.2),\
 I think it shouldn't be difficult to handle, right?

**Comment by vitabaks** [comment]
@iabdukhoshimov Try the `pg-version-force` option with a value of `16`

I think this is what you need.

> The specified PostgreSQL version will be used instead of the version automatically detected by reading pg_control or WAL headers. This is mainly useful for PostgreSQL forks or development versions where those values are different from the release version. The version reported by PostgreSQL via `server_version_num` must match the forced version.

https://pgbackrest.org/configuration.html#section-maintainer/option-pg-version-force

**Comment by iabdukhoshimov** [comment]
I tried check postgres pro version it is 
```
postgres (PostgreSQL) 16.2
```
and when I tried then I run the query
```
postgres=# select setting from pg_settings where name = 'server_version_num';
 setting 
---------
 160002
(1 row)

```

**Comment by dwsteele** [comment]
> postgres (PostgreSQL) 16.2

That should be OK. Did you try setting `pg1-version-force=16`? You'll also need `pg2-version-force=16`, etc.

**Comment by vitabaks** [comment]
@dwsteele Thanks for the answer! I think it would be convenient to be able to specify an option globally or at the stanza level instead of setting it for each pg host individually.

**Comment by dwsteele** [comment]
> I think it would be convenient to be able to specify an option globally or at the stanza level instead of setting it for each pg host individually.

We may offer `pg*-version-force` functionality in the future (or something like that) but it's not in the plans for now.

**Comment by vitabaks** [comment]
> Did you try setting pg1-version-force=16? You'll also need pg2-version-force=16, etc.

As tests have shown, this does not work when adding for each index (pgN).  It is enough to specify `pg-version-force=16` once at the stanza level.

**Comment by dwsteele** [comment]
> t is enough to specify pg-version-force=16 once at the stanza level

Whoops! You are correct. And that makes more sense anyway.
