### ISSUE TITLE
Restore to specific backup with name?

### ISSUE THREAD

**Issue by GammaGames** [pgbackrest/pgbackrest#2311]
(This is a usage question)

1. pgBackRest version: 2.5
2. PostgreSQL version: 14.11
3. Operating system/version: Docker container based on `debian:bullseye-slim` -> `postgres:14-bullseye` -> `postgis/postgis:14-3.4`
4. Did you install pgBackRest from source or from a package? Package

I was reading through the documentation for target `--type` and have a question about restoring to a specific backup. I've got the following:

```
full backup: 20240315-144752F
    timestamp start/stop: 2024-03-15 14:47:52-06 / 2024-03-15 14:54:21-06

incr backup: 20240315-144752F_20240315-153451I
    timestamp start/stop: 2024-03-15 15:34:51-06 / 2024-03-15 15:35:06-06
    backup reference list: 20240315-144752F

incr backup: 20240315-144752F_20240315-153757I
    timestamp start/stop: 2024-03-15 15:37:57-06 / 2024-03-15 15:38:00-06
    backup reference list: 20240315-144752F, 20240315-144752F_20240315-153451I

incr backup: 20240315-144752F_20240315-154230I
    timestamp start/stop: 2024-03-15 15:42:30-06 / 2024-03-15 15:42:33-06
    backup reference list: 20240315-144752F, 20240315-144752F_20240315-153451I, 20240315-144752F_20240315-153757I
```

1. Is there any way to restore to a specific backup (aside from `--type=time`)? For example I'd like to restore using the backup's label of `20240315-144752F_20240315-153757I`
2. Reading the [blog post for auto-select backups](https://pgstef.github.io/2020/03/02/pgbackrest_auto_select_backup.html) I saw that you can restore with `--type=name --target=RP1`. The name was created with `pg_create_restore_point`, is there any way to set a name with `pgbackrest backup`?
3. Is there any way to restore using annotations? The [2.41 update notes](https://pgstef.github.io/2022/09/20/pgbackrest_2_41_released.html) shows off feature but I don't see any way to use the annotations as restore targets. Is that supported?

**Comment by dwsteele** [comment]
> Is there any way to restore to a specific backup (aside from --type=time)? For example I'd like to restore using the backup's label of 20240315-144752F_20240315-153757I

Yes, use the `--set` option, e.g. `--set=20240315-144752F_20240315-153757I`.

> I saw that you can restore with --type=name --target=RP1. The name was created with pg_create_restore_point, is there any way to set a name with pgbackrest backup?

No, only `pg_create_restore_point()` can set a restore point.

> Is there any way to restore using annotations?

No. It's an interesting idea, though.

**Comment by GammaGames** [comment]
> use the `--set` option

D'oh! I've been reading the documentation so much I overlooked that flag, that makes the rest of my questions unnecessary anyway. Thank you so much for your time!
