### ISSUE TITLE
Archive_command on a 5 node, Patroni Cluster

### ISSUE THREAD

**Issue by prime-minister-of-fun** [pgbackrest/pgbackrest#2313]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.48

2. PostgreSQL version: 14

3. Operating system/version: RHEL8 amd64

4. Did you install pgBackRest from source or from a package? Package, Percona repository.

7. Describe the issue:
Hi, 
I followed pgstef's how-to and everything works as it should on a 5 node PostgreSQL cluster with Patroni as the "orchestrator."  The HA cluster is configured as an active/passive style cluster.  Meaning, there is only one writer at any given time.

Pgbackrest is configured as a standalone backup repo for all 5 nodes.  All 5 nodes reach the pgbackrest repo.  All 5 nodes are included in the same stanza so backups can be taken off a reader.  WAL logs are streaming, and backups from the pgbackrest repo host are successful.

With Patroni managing much of the configuration of the nodes in the PostgreSQL HA cluster, archive_command gets set identically for every node in the cluster.   

My question: Is *only* the leader having WAL's streamed to pgbackrest?    I realize there might be an obvious answer and I might be missing it.

**Comment by dwsteele** [comment]
> Is only the leader having WAL's streamed to pgbackrest?

Yes, see https://pgbackrest.org/configuration.html#section-backup/option-archive-mode-check for details.

**Comment by prime-minister-of-fun** [comment]
Thank you!

**Comment by prime-minister-of-fun** [comment]
Thank you!
