### ISSUE TITLE
WAL segment 00000001000002E40000005D was not archived before the 60000ms timeout

### ISSUE THREAD

**Issue by ilwyiworld** [pgbackrest/pgbackrest#2314]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.50

2. PostgreSQL version:
15.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 22.04.3 LTS

4. Did you install pgBackRest from source or from a package?
from source 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
      [postgres]
      pg1-path=/var/lib/postgresql/15/main
      pg1-port=5433
      pg1-host-user=postgres
      pg1-user=postgres
      [global]
      repo1-path=/var/lib/pgbackrest
      repo1-retention-full=2
      repo1-cipher-pass=G2BpLcraxPcckRTrUoQfLOTV8li/GB7lrAU/mYMYlVLYIlBp4Ru8KP6KdI2dUa3oL
      repo1-cipher-type=aes-256-cbc
      process-max=3
      compress-type=zst
      [global:archive-push]
      compress-level=3

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
      archive_command = 'pgbackrest --stanza=postgres --log-level-console=detail archive-push %p'
      archive_mode = on
      listen_addresses = '*'
      port = 5433
      wal_level = replica
      max_wal_senders = 10

    - errors in the postgresql log file before or during the time you experienced the issue
   
2024-03-28 14:16:41.557 P00   INFO: archive-push command end: aborted with exception [041]
LOG:  archive command failed with exit code 41
DETAIL:  The failed archive command was: pgbackrest --stanza=postgres --log-level-console=detail archive-push pg_wal/00000001000002E40000005C
2024-03-28 14:16:42.569 P00   INFO: archive-push command begin 2.50: [pg_wal/00000001000002E40000005C] --compress-level=3 --compress-type=zst --exec-id=304647-969b1311 --log-level-console=detail --pg1-path=/var/lib/postgresql/15/main --process-max=3 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest --stanza=postgres
ERROR: [041]: unable to get info for path/file '/tmp/pgbackrest/postgres.stop': [13] Permission denied
2024-03-28 14:16:42.569 P00   INFO: archive-push command end: aborted with exception [041]
LOG:  archive command failed with exit code 41
DETAIL:  The failed archive command was: pgbackrest --stanza=postgres --log-level-console=detail archive-push pg_wal/00000001000002E40000005C
2024-03-28 14:16:43.581 P00   INFO: archive-push command begin 2.50: [pg_wal/00000001000002E40000005C] --compress-level=3 --compress-type=zst --exec-id=304650-e71b3161 --log-level-console=detail --pg1-path=/var/lib/postgresql/15/main --process-max=3 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest --stanza=postgres
ERROR: [041]: unable to get info for path/file '/tmp/pgbackrest/postgres.stop': [13] Permission denied
2024-03-28 14:16:43.581 P00   INFO: archive-push command end: aborted with exception [041]
LOG:  archive command failed with exit code 41
DETAIL:  The failed archive command was: pgbackrest --stanza=postgres --log-level-console=detail archive-push pg_wal/00000001000002E40000005C
WARNING:  archiving write-ahead log file "00000001000002E40000005C" failed too many times, will try again later

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    
-------------------PROCESS START-------------------
2024-03-28 14:20:04.597 P00   INFO: backup command begin 2.50: --compress-type=zst --exec-id=304811-038ce86c --log-level-console=info --pg1-path=/var/lib/postgresql/15/main --pg1-port=5433 --pg1-user=postgres --process-max=3 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest --repo1-retention-full=2 --stanza=postgres
2024-03-28 14:20:11.247 P00   WARN: no prior backup exists, incr backup has been changed to full
2024-03-28 14:20:11.247 P00   INFO: execute non-exclusive backup start: backup begins after the next regular checkpoint completes
2024-03-28 14:20:34.948 P00   INFO: backup start archive = 00000001000002E40000005E, lsn = 2E4/5E000028
2024-03-28 14:20:34.948 P00   INFO: check archive for prior segment 00000001000002E40000005D
2024-03-28 14:21:34.948 P00  ERROR: [082]: WAL segment 00000001000002E40000005D was not archived before the 60000ms timeout
                                    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
                                    HINT: check the PostgreSQL server log for errors.
                                    HINT: run the 'start' command if the stanza was previously stopped.
2024-03-28 14:21:34.949 P00   INFO: backup command end: aborted with exception [082]

7. Describe the issue:
When i user 'check' or 'backup' commend,it occur "Timeout" error:
<img width="848" alt="1" src="https://github.com/pgbackrest/pgbackrest/assets/7789175/54958f16-3226-4625-8081-994fb1c06c32">
<img width="854" alt="2" src="https://github.com/pgbackrest/pgbackrest/assets/7789175/f584158d-1756-4f1b-bb78-804b0715d1e7">

**but i found a different error with other issue in postgres log:**
<img width="868" alt="3 14 43 51" src="https://github.com/pgbackrest/pgbackrest/assets/7789175/7d7b599b-7d11-43a7-8194-25c840600160">

is it something wrong with dir permission?

by the way,all dir permission with pgbackrest("/var/log/pgbackrest","/etc/pgbackrest","/var/lib/pgbackrest) is postgres:postgres

**Comment by ilwyiworld** [comment]
soory, the permission of dir "/tmp/pgbackrest" is "root:root",but i changed permission to "postgres:postgres",it occur other permission error:

2024-03-28 15:16:34.373 P00   INFO: archive-push command end: aborted with exception [103]
LOG:  archive command failed with exit code 103
DETAIL:  The failed archive command was: pgbackrest --stanza=postgres --log-level-console=detail archive-push pg_wal/00000001000002E40000005C
2024-03-28 15:16:35.385 P00   INFO: archive-push command begin 2.50: [pg_wal/00000001000002E40000005C] --compress-level=3 --compress-type=zst --exec-id=307197-70bb6396 --log-level-console=detail --pg1-path=/var/lib/postgresql/15/main --process-max=3 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest --stanza=postgres
ERROR: [103]: unable to find a valid repository:
       repo1: [FileOpenError] unable to load info file '/var/lib/pgbackrest/archive/postgres/archive.info' or '/var/lib/pgbackrest/archive/postgres/archive.info.copy':
       FileOpenError: unable to open file '/var/lib/pgbackrest/archive/postgres/archive.info' for read: [13] Permission denied
       FileOpenError: unable to open file '/var/lib/pgbackrest/archive/postgres/archive.info.copy' for read: [13] Permission denied
       HINT: archive.info cannot be opened but is required to push/get WAL segments.
       HINT: is archive_command configured correctly in postgresql.conf?
       HINT: has a stanza-create been performed?
       HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
2024-03-28 15:16:35.385 P00   INFO: archive-push command end: aborted with exception [103]
LOG:  archive command failed with exit code 103
DETAIL:  The failed archive command was: pgbackrest --stanza=postgres --log-level-console=detail archive-push pg_wal/00000001000002E40000005C
WARNING:  archiving write-ahead log file "00000001000002E40000005C" failed too many times, will try again later

**Comment by ilwyiworld** [comment]
I found reason, when i changed permission of dir "/var/lib/pgbackrest" and its sub dir by "chown -R postgres:postgres /var/lib/pgbackrest",it solved

**Comment by ilwyiworld** [comment]
when i user Dedicated Repository Host,timeout error occur again.

Backup Host pgbackrest.conf:
`
[postgres]
pg1-host=172.17.2.141
pg1-host-port=3766
pg1-port=5433
pg1-path=/var/lib/postgresql/15/main
pg1-host-user=postgres
pg1-user=postgres

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=1
repo1-retention-diff=1
process-max=3
compress-type=zst

[global:archive-push]
compress-level=3
process-max=4
`

error log:
`
root@iZbp19ol9t384i127irataZ:/var/log/pgbackrest# sudo -u pgbackrest pgbackrest --stanza=postgres backup --log-level-console=detail
2024-03-29 15:31:21.725 P00   INFO: backup command begin 2.50: --compress-type=zst --exec-id=3909-2c7f23a8 --log-level-console=detail --pg1-host=172.17.2.141 --pg1-host-port=3766 --pg1-host-user=postgres --pg1-path=/var/lib/postgresql/15/main --pg1-port=5433 --pg1-user=postgres --process-max=3 --repo1-path=/var/lib/pgbackrest --repo1-retention-diff=1 --repo1-retention-full=1 --stanza=postgres
WARN: no prior backup exists, incr backup has been changed to full
2024-03-29 15:32:03.922 P00   INFO: execute non-exclusive backup start: backup begins after the next regular checkpoint completes
2024-03-29 15:43:21.327 P00   INFO: backup start archive = 00000001000002E50000002D, lsn = 2E5/2D21C7D8
2024-03-29 15:43:21.327 P00   INFO: check archive for prior segment 00000001000002E50000002B
ERROR: [082]: WAL segment 00000001000002E50000002B was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2024-03-29 15:44:21.327 P00   INFO: backup command end: aborted with exception [082]
`

and pgbackrest.conf in PGHOST is Same as above:
`
[postgres]
pg1-path=/var/lib/postgresql/15/main
pg1-port=5433
pg1-host-user=postgres
pg1-user=postgres
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=1
repo1-retention-diff=1
repo1-cipher-pass=G2BpLcraxPcckRTrUoQfLOTV8li/GB7lrAU/mYMYlVLYIlBp4Ru8KP6KdI2dUa3oL
repo1-cipher-type=aes-256-cbc
process-max=3
compress-type=zst

[global:archive-push]
compress-level=3
`

besides, all permission of dir with pgbackrest in Dedicated Repository Host is "pgbaskrest:pgbackrest"

**Comment by ilwyiworld** [comment]
pgbackrest info shows:
```
root@iZbp19ol9t384i127irataZ:/var/log/pgbackrest# sudo -u pgbackrest pgbackrest infostanza: postgres
    status: error (no valid backups)
    cipher: none

    db (current)
        wal archive min/max (15): none present
```

**Comment by pgstef** [comment]
Your configuration doesn't look correct to me. You're not sending backups and archives at the same place.

Repo host config:

```ini
[postgres]
pg1-host=172.17.2.141
pg1-host-port=3766
pg1-port=5433
pg1-path=/var/lib/postgresql/15/main
pg1-host-user=postgres
pg1-user=postgres

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=1
repo1-retention-diff=1
process-max=3
compress-type=zst

[global:archive-push]
compress-level=3
process-max=4
```

This means you want to backup the `pg1-host` using ssh port `pg1-host-port` and ssh user `pg1-host-user`. `pg1-user` isn't used here (and `pg1-port` neither iirc)
The backups and archives will be stored locally on this host in `repo1-path` and only keep 1 full and 1 diff backup.
The `[global:archive-push]` section is useless here since the archive-push command is run on PG hosts.
And `process-max=4` for archive-push is useless if you don't use async archiving btw.
The `repo1-cipher-type` and `repo1-cipher-pass` should be defined here too.

PG host config:

```ini
[postgres]
pg1-path=/var/lib/postgresql/15/main
pg1-port=5433
pg1-host-user=postgres
pg1-user=postgres
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=1
repo1-retention-diff=1
repo1-cipher-pass=G2BpLcraxPcckRTrUoQfLOTV8li/GB7lrAU/mYMYlVLYIlBp4Ru8KP6KdI2dUa3oL
repo1-cipher-type=aes-256-cbc
process-max=3
compress-type=zst

[global:archive-push]
compress-level=3
```

`pg1-host-user=postgres` isn't used here. But this config means the backups/archives repository is also located in `/var/lib/pgbackrest` but locally on the PG host.

> I cant see error log in postgres.log(PGHOST) just like before

That's normal. Your PG archive_command is sending archives locally in `/var/lib/pgbackrest`(PG host) but your backup command look for the archives in `/var/lib/pgbackrest`(backup host).
So yes, the archive command is working but you're not using it correctly. All backups and archives should reach the same location.
You need to adjust your PG host config to use repo1-host options so the archive-push command will send archives into the repo host backup directory. 
See https://pgbackrest.org/user-guide.html#repo-host/config for the details.

Probably something like this would work:

```ini
# PG Host
[global]
repo1-host=REPO_HOST_NAME_OR_IP
repo1-host-user=pgbackrest
repo1-cipher-pass=xxx
repo1-cipher-type=aes-256-cbc
compress-type=zst

[postgres]
pg1-path=/var/lib/postgresql/15/main
pg1-port=5433
pg1-user=postgres

[global:archive-push]
compress-level=3

# Backup Host
[global]
repo1-path=/var/lib/pgbackrest
repo1-cipher-pass=xxx
repo1-cipher-type=aes-256-cbc
repo1-retention-full=1
repo1-retention-diff=1
process-max=3
compress-type=zst

[postgres]
pg1-host=172.17.2.141
pg1-host-port=3766
pg1-host-user=postgres
pg1-path=/var/lib/postgresql/15/main
```

**Comment by ilwyiworld** [comment]
> The repo1-cipher-type and repo1-cipher-pass should be defined here too.

this pass is same with PG host,or generated by backup host itself

**Comment by pgstef** [comment]
> this pass is same with PG host,or generated by backup host itself

since you should use a common location: same repo = same cipher-pass

**Comment by ilwyiworld** [comment]
according to your config,it worked,thanks
