### ISSUE TITLE
[Q] compressed backup bundle file  extension. (just suggestion)

### ISSUE THREAD

**Issue by hellower** [pgbackrest/pgbackrest#2316]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.51

2. PostgreSQL version:
  15

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
rocky linux 8.9

4. Did you install pgBackRest from source or from a package?
rpm 

5. Please attach the following as applicable:

```
[global]
# repo details
repo1-path=/app/postgres-backup_space
repo1-retention-full=4
 
repo1-bundle=y                    ### bundle feature on !!!
repo1-bundle-limit=2MiB
repo1-bundle-size=20MiB
compress-type=lz4
```

6. Describe the issue:
This is the file list in repository when full backup was performed with the (bundle option + lz4 compression option) turned on.

[postgres@postgres:/app/postgres-backup_space/backup/tarantuladb15-cluster-aa/latest]
$ find .
.
./backup.manifest.copy
./bundle
./bundle/1           <----------    mising extension (1.lz4 ?)
./bundle/2           <----------    mising extension (2.lz4 ?)
./bundle/3           <----------    mising extension (3.lz4 ?)
./pg_data
./pg_data/base
./pg_data/base/32898
./pg_data/base/32898/41122.lz4
./pg_data/base/32898/32919.lz4
./pg_data/base/32898/32911.lz4
./pg_data/base/32898/32911.1.lz4
./pg_data/backup_label.lz4
./pg_data/pg_wal
./pg_data/pg_wal/000000AB0000000E000000C9.lz4
./backup.manifest
[postgres@tdb-safekeeper:/app/postgres-backup_space/backup/tarantuladb15-cluster-aa/latest]
$ file ./bundle/1 ./bundle/2  ./bundle/3     
./bundle/1: LZ4 compressed data (v1.4+)
./bundle/2: LZ4 compressed data (v1.4+)
./bundle/3: LZ4 compressed data (v1.4+)
[postgres@tdb-safekeeper:/app/postgres-backup_space/backup/tarantuladb15-cluster-aa/latest]
$ 

1 -> 1.lz4
2 -> 2.lz4
3 -> 3.lz4
How about having the lz4 extension?

**Comment by dwsteele** [comment]
These bundles are not in lz4 format. They may start with a lz4 format file but they are a concatenation of lz4 compressed files, lz4 compressed blocks, and non-compressed block maps. Plus encryption may be applied to any or all of those parts.

Even if this were a mistake, changing it would break backward compatibility so we wouldn't do it.
