### ISSUE TITLE
ERROR: [082]: WAL segment xxx was not archived before the 1800000ms timeout [GCS]

### ISSUE THREAD

**Issue by Vox1984** [pgbackrest/pgbackrest#2318]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
`2.51`
2. PostgreSQL version:
`14.10-1 `
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
`debian 10`
4. Did you install pgBackRest from source or from a package?
`deb package`

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

```
[main]
pg1-path=/var/lib/postgresql/14/main/

[global]
#repo1
repo1-bundle=y
repo1-bundle-size=1024MiB
repo1-bundle-limit=128MiB
repo1-cipher-pass=redacted
repo1-cipher-type=aes-256-cbc
repo1-gcs-bucket=01-disasterrecovery
repo1-path=/disaster_recovery
repo1-retention-full=28
repo1-retention-full-type=time
repo1-gcs-key-type=auto
repo1-type=gcs
#repo2
repo2-bundle=y
repo2-bundle-size=1024MiB
repo2-bundle-limit=128MiB
repo2-cipher-pass=redacted
repo2-cipher-type=aes-256-cbc
repo2-gcs-bucket=01-archive
repo2-path=/longterm_archive
repo2-retention-full=540
repo2-retention-full-type=time
repo2-gcs-key-type=auto
repo2-type=gcs

#common settings
log-level-console=info
log-level-file=debug
start-fast=y
archive-timeout=1800

[global:archive-push]
compress-type=gz
compress-level=3 
process-max=4

```
   - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

```
archive_mode = on
max_wal_senders = 3
wal_level = replica
archive_command = 'pgbackrest --stanza=main --log-level-console=detail archive-push %p'

max_wal_size = 1GB
min_wal_size = 80MB
```

   - errors in the postgresql log file before or during the time you experienced the issue
`    There is no errors. Just file by file being pushed`

   - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
```
2024-04-08 18:43:51.916 P00  DEBUG:     storage/iterator::storageItrNew: (driver: *void, path: {"/longterm_archive/archive/main/14-1/000000010001222D"}, level: 1, errorOnMissing: false, nullOnMissing: false, recurse: false, sortOrder: 0, expression: {"^000000010001222D000000E0-[0-f]{40}(\.gz|\.lz4|\.zst|\.xz|\.bz2){0,1}$"})
2024-04-08 18:43:51.933 P00  DEBUG:     storage/iterator::storageItrNew: => {stack: {size: 0}}
2024-04-08 18:43:51.933 P00  DEBUG:     storage/storage::storageNewItr: => {stack: {size: 0}}
2024-04-08 18:43:51.933 P00  DEBUG:     storage/storage::storageList: => {[]}
2024-04-08 18:43:51.933 P00  DEBUG:     command/exit::exitSafe: (result: 0, error: true, signalType: 0)
2024-04-08 18:43:51.933 P00  ERROR: [082]: WAL segment 000000010001222D000000E0 was not archived before the 1800000ms timeout
                                    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
                                    HINT: check the PostgreSQL server log for errors.
                                    HINT: run the 'start' command if the stanza was previously stopped.
                                    --------------------------------------------------------------------
                                    If SUBMITTING AN ISSUE please provide the following information:
                                    
                                    version: 2.51
                                    command: backup
                                    options: --archive-timeout=1800 --exec-id=5001-40f88648 --log-level-console=info --log-level-file=debug --pg1-path=/var/lib/postgresql/14/main/ --repo=2 --repo1-bundle --repo2-bundle --repo1-bundle-limit=128MiB --repo2-bundle-limit=128MiB --repo1-bundle-size=1024MiB --repo2-bundle-size=1024MiB --repo1-cipher-pass=<redacted> --repo2-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo2-cipher-type=aes-256-cbc --repo1-gcs-bucket=01-disasterrecovery --repo2-gcs-bucket=01-archive --repo1-gcs-key-type=auto --repo2-gcs-key-type=auto --repo1-path=/disaster_recovery --repo2-path=/longterm_archive --repo1-retention-full=28 --repo2-retention-full=540 --repo1-retention-full-type=time --repo2-retention-full-type=time --repo1-type=gcs --repo2-type=gcs --stanza=main --start-fast --type=full
                                    
                                    stack trace:
                                    command/archive/find.c:walSegmentFind:197:(this: {WalSegmentFind}, walSegment: {"000000010001222D000000E0"})
                                    command/archive/find.c:walSegmentFindOne:(storage: {type: gcs, path: /longterm_archive, write: false}, archiveId: {"14-1"}, walSegment: {"000000010001222D000000E0"}, timeout: 1800000)
                                    command/backup/backup.c:backupStart:(backupData: {BackupData})
                                    command/backup/backup.c:cmdBackup:(void)
                                    main.c:main:(debug log level required for parameters)
                                    --------------------------------------------------------------------
2024-04-08 18:43:51.933 P00 DETAIL: statistics: {"http.client":{"total":2},"http.request":{"total":25},"http.retry":{"total":3},"http.session":{"total":5},"socket.client":{"total":2},"socket.retry":{"total":1},"socket.session":{"total":5},"tls.client":{"total":1},"tls.session":{"total":4}}
2024-04-08 18:43:51.933 P00   INFO: backup command end: aborted with exception [082]
2024-04-08 18:43:51.933 P00  DEBUG:     command/exit::exitSafe: => 82
2024-04-08 18:43:51.933 P00  DEBUG:     main::main: => 82
```

7. Describe the issue:

The full backup command `sudo -u postgres pgbackrest --stanza=main --repo=2 --type=full --log-level-console=info backup` fails with error above... After timeout of 1800 seconds (increased as a try to fix issue, same failure for 60 seconds). Whats strange it looks like the wal files are still being consumed (pg_wal directory size shrinks).

There is another side issue - the files as seen in gcs bucket does not seem to be bundled. (As I expect them to be), they are in size 2-5 MB.

There is no error in postgresql log. Any ideas?

**Comment by dwsteele** [comment]
> Whats strange it looks like the wal files are still being consumed (pg_wal directory size shrinks).

This can happen if you are very far behind on WAL archiving. The backup process is looking for a recent WAL segment, which may be all the way at the end of the queue. You set `process-max=4` for `archive-push`, but that is useless without also setting `archive-async=y. You might also consider a faster compression algorithm, e.g. zstd.

> the files as seen in gcs bucket does not seem to be bundled

If you see anything in the `bundle` path they are being bundled. Size varies a lot based on workload and compression. The point is not to have the maximum size file, but to avoid very small files being stored separately, which is inefficient and increases costs on some platforms.

**Comment by Vox1984** [comment]
Thanks, I will try async and ztsd. The long time full backup takes is an issue.

What do you mean by `bundle` path?
When I go to the GCS bucket, I have 2 main folders
`archive` and `backup`
I don't see `bundle` dir anywhere?

**Comment by dwsteele** [comment]
In the backup dir, e.g. `/backup/[stanza]/2024...`.

**Comment by Vox1984** [comment]
Its not there. It is there for same setup in azure container though for different DB (edited reply above)
So something went wrong = during this 30 minutes of backup this wasnt created, I suppose.

**Comment by Vox1984** [comment]
I have set up the archive_command to `true`. That have cleansed up `pg_wal` directory and, now backup works fine, without any changes in configuration. Looks like indeed there was trouble with too many wal files in the queue, or some corrupted single wal file... I will do more testing with `pg_bench` and special test vm.

**Comment by dwsteele** [comment]
OK -- but it is certainly possible to get a large queue again, so you should definitely look at async and possibly zstd.

**Comment by Vox1984** [comment]
Would it be normal, to have following number of files for 60 GB database backup?
It is a single run, clean, successful full backup, on an empty new bucket, on repo1.
It took 7 hours to complete.

`gsutil du  gs://xxx-01-disasterrecovery | wc -l`
`43435`

And then just in bundle folder, just 11 1files of sizes 200-500 MB
`gsutil du  gs://xxx-01-disasterrecovery/disaster_recovery/backup/main/20240409-191359F/bundle/ | wc -l`
 `11`

`gsutil du  gs://xxx-01-disasterrecovery/disaster_recovery/backup/main/20240409-191359F/pg_data | wc -l`
 `494`

The most files are in:
`gsutil du  gs://xxx-01-disasterrecovery/disaster_recovery/archive/main/14-1/ | wc -l`
 `43649`

Which contains files of size ~ 3.3MB each. And there is so many of those `archive` files, which is suspicious to me.
I imagined having just few files that are bundled - and it seems some are, in `bundle` subfolder, but in a great scheme of things its just a small subset of all files, having probably small impact on execution time. What do you think?

**Comment by pgstef** [comment]
Do you know what WAL segment files are? And what's their impact on PG data files? This is common PG knowledge, nothing specific to pgBackRest itself. The backup directory will contain data files from the backups (bundled or not), while the archive directory will contain WAL segment archives for backup consistency and PITR.

The volume of WAL files generated is highly dependent on the write activity of your PG cluster. 
To find out how fast 1 WAL segment is archived, you should look at the archive-push output (in PG logs).
If you generate WAL faster than the archive-push can archive it, then as David mentioned already, you should look for async archiving and zstd compression to speed it up.

Regards

**Comment by Vox1984** [comment]
Hi,

I really appreciate your help Guys.

Yes I know whats the purpose of WAL files, I just wondered, could pgbackrest bundle them too,
just for the sake of fast upload to the cloud bucket.

I will try the async too, separately.

**Comment by pgstef** [comment]
> Yes I know whats the purpose of WAL files, I just wondered, could pgbackrest bundle them too, just for the sake of fast upload to the cloud bucket.

They are pushed individually by PG itself, there's no point to bundle them. Imo, if you're not happy with the cloud bucket performance, change your storage and/or investigate your cluster activity. Async can help, but zstd compression usually helps even more.

**Comment by dwsteele** [comment]
> Should those archive files be bundled into bigger ones too?

Bundling is most effective with small files, i.e. < 2MiB, which is why we use this value for the repo-bundle-limit default. WAL files are generally 16MiB so they are way out of this range. A compressed WAL file can be uploaded in a single PUT but bundles of WAL files would need to be chunked and then assembled at the end, which pretty much defeats the point.
