### ISSUE TITLE
Large number of GetObjectTagging requests with S3 Scality storage

### ISSUE THREAD

**Issue by MonChr** [pgbackrest/pgbackrest#2319]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

**1. pgBackRest version:**
pgBackRest 2.50

**2. PostgreSQL version:**
PostgreSQL 15.6

**3. Operating system/version:**
Red Hat Enterprise Linux 8.9

**4. Install pgBackRest:**
From package : pgbackrest-2.50-1PGDG.rhel8.x86_64

**5. pgbackrest configuration:**
[global]
compress-type=none
delta=y
lock-path=/var/run/postgresql
process-max=3
log-level-console=info
log-level-file=info
log-level-stderr=info
log-path=/var/log/pgbackrest
log-timestamp=y
archive-async=y
archive-missing-retry=y
archive-push-queue-max=50GiB
archive-get-queue-max=20GiB
spool-path=/applis/spoolwal
archive-check=y
archive-copy=y
archive-mode-check=y
backup-standby=n
expire-auto=y
start-fast=y
repo1-retention-full-type=time
repo1-retention-archive-type=full
repo1-retention-full=15
repo1-retention-diff=15
repo1-retention-history=0
repo1-type=s3
repo1-s3-uri-style=path
repo1-s3-bucket=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
repo1-s3-endpoint=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
repo1-s3-key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
repo1-s3-key-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
repo1-path=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
repo1-s3-region=eu-west-3
repo1-s3-verify-tls=n
repo1-bundle=y
repo1-block=y
repo1-bundle-limit=1MiB
repo1-bundle-size=10MiB

[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
pg1-host-type=ssh
pg1-socket-path=/var/run/postgresql
pg1-host-user=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
pg1-path=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
pg1-port=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**7. Description of the issue:**
Hi,
We are surprised by the pgbackrest activity profile with very numerous GetObjectTagging requests at the S3 Scality ring. Is this "normal" behavior, is it due to our configuration?
Thank you for your insight.
![image](https://github.com/pgbackrest/pgbackrest/assets/36842812/74c570ec-ddf0-472c-be77-75f6e89f6937)

**Comment by dwsteele** [comment]
We do not explicitly fetch tags (https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectTagging.html) so not sure where this is coming from. It could be that Scality is piggy-backing these requests on a list request.

**Comment by dwsteele** [comment]
Closing since there has been no further word on this. I would be curious to know if you got a response from Scality.
