### ISSUE TITLE
Restore is not very scalable, more cores just creates contention

### ISSUE THREAD

**Issue by David-Gould** [pgbackrest/pgbackrest#232]
I did a full backup of a 350 GB postgresql 9.4 instance with several thousand tables and indexes and then restored it to an empty directory with different values of thread-max. As the number of threads increased the benefit of additional cores was eaten up in system time. According to perf top this was all in kernel spinlocks. This suggests to me that the threading or data interchange between threads is doing too much synchronization. Parallel restores of each file should be able to work pretty independently. 

If there is more information or testing I can do let me know.

```
jobs    real    user     sys  
  1   3382.2  2784.8   566.1 
  2   1727.9  2840.8   570.0 
  4    977.5  2836.7   694.0 
  6    729.3  2813.1   893.7 
  8    622.0  2820.5  1139.8 
 10    562.9  2843.7  1440.9 
 12    534.0  2869.8  1727.3 
 16    466.3  2919.0  2214.3 
 24    409.7  2980.9  3171.3 
 32    500.0  3009.4  7322.3 
 48    499.3  3192.9 11690.4 
 64    467.9  3578.2 15419.4 

The host has 1TB of memory and 80 hardware threads (40 cores). Files were all on the same ext4 filesystem on a FusionIO flash device.
$ cat /proc/version 
Linux version 2.6.32-504.1.3.el6.x86_64 (mockbuild@x86-022.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-9) (GCC) ) #1 SMP Fri Oct 31 11:37:10 EDT 2014
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.6 (Santiago)

$ perl --version
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

perf top with 48 jobs
 74.97%  [kernel]                      [k] _spin_lock_irqsave
  6.26%  [kernel]                      [k] _spin_lock
  3.49%  [iomemory_vsl]                [k] 0x0000000000006abb
  2.96%  SHA.so                        [.] 0x0000000000002fad
  1.27%  libz.so.1.2.3                 [.] inflate_fast
  0.81%  libz.so.1.2.3                 [.] crc32
  0.57%  [kernel]                      [k] _spin_unlock_irqrestore
  0.32%  [kernel]                      [k] __remove_hrtimer
  0.31%  [kernel]                      [k] schedule
  0.30%  [kernel]                      [k] copy_user_generic_string
  0.22%  [kernel]                      [k] end_buffer_async_write
  0.18%  [kernel]                      [k] __hrtimer_start_range_ns
  0.18%  [kernel]                      [k] kmem_cache_free
  0.18%  [kernel]                      [k] hrtimer_force_reprogram
  0.16%  [kernel]                      [k] ktime_get
  0.15%  [dm_mod]                      [k] dec_pending
  0.15%  [kernel]                      [k] memset
  0.15%  [kernel]                      [k] thread_return
  0.13%  [kernel]                      [k] update_curr
  0.13%  [dm_mod]                      [k] clone_endio
  0.13%  [kernel]                      [k] rb_erase
  0.13%  [kernel]                      [k] tick_nohz_stop_sched_tick
  0.12%  [kernel]                      [k] tick_dev_program_event
  0.12%  [kernel]                      [k] mempool_free
  0.12%  libc-2.12.so                  [.] _wordcopy_fwd_dest_aligned
  0.11%  [kernel]                      [k] try_to_wake_up
  0.11%  [kernel]                      [k] task_rq_lock
  0.11%  [kernel]                      [k] tick_program_event
  0.10%  [kernel]                      [k] _spin_lock_irq
```

**Comment by dwsteele** [comment]
Currently multi-processing is done with Perl threads which mostly work independently but pull work and send results through queues and that's where all the spinlock activity is coming from.  This is more noticeable when then there are a large number of small files and also during restore vs backup since compression is more CPU intensive (thus less queue activity) than decompression.  In general, though, your numbers match what I've seen.

The solution to this problem is to move to multi-processing (see #48).  This is very high on our priority list and if everything goes well I hope to have that out in the next month or two at the latest.

**Comment by David-Gould** [comment]
I also noticed that it did a lot of 8KB IO, is it working page by page? Could it simply work in larger chunks?

**Comment by dwsteele** [comment]
Are you sure that's not 8MB?  That's how it is set y default:

https://github.com/pgbackrest/pgbackrest/blob/master/lib/pgBackRest/Config/Config.pm#L403

**Comment by dwsteele** [comment]
Sorry, the default is 4MB - max is 8MB.

**Comment by dwsteele** [comment]
Another thing, there are generally a LOT of 8KB files in a cluster with a lot of small tables, or any cluster, really.  8KB is the PG page size a minimum allocation.  Various forks may never go beyond 8KB even when the main heap does.  For instance, _vm files only consume 8KB per 4MB of heap.

You can search the backup.manifest file and see how many there are in your cluster.

**Comment by MichaelDBA** [comment]
David,  what is your max-thread when doing this?  I've been playing with 6, 8, and 10 values on our 20 CPUs, and with 10 our load is about 60% steady.  Unfortunately, I don't have "perf record/perf report" capacity on our VMs, so I cannot check spin locks.  But my best times for backup are when I use 10.

**Comment by David-Gould** [comment]
The first block of data in my post above has the times for thread-max of 1, 2, 4, 8, 10, 12, 16, 24, 32, 48, 64. The fastest was at 24, but took about twice as much total cpu as for  4 threads. 8 to 10 look like a good compromise between excess overhead and restore time, but I have 80 and enough memory and IO to make use of them.

Btw, I just found pgbackrest and it looks great. Thanks for making it.

**Comment by dwsteele** [comment]
Thanks, David - I appreciate that!

**Comment by David-Gould** [comment]
A bit of background on the problem I'm hoping pgbackrest can help with: There are several hosts with 40 cores (80 threads), 1TB memory, 10GB ethernet and a 12TB postgres instance on FusionIO storage. They are very write intense, so much so that postgresql streaming replication cannot keep up as recovery is only single threaded.  pg_basebackup takes about 1 - 2 hours per TB and once it is complete the recovery just falls further behind. So they can't really be replicated or even backed up in a timely way. I was planning a custom solution, but pgbackrest really covers all the tricky bits like cataloging, pitr, wal shipping, timelines, incrementals etc which are fussy and hard to get right and even harder to verify. It would be great to be able to use pgbackrest for this application. The concern is to get as much speed backing up as possible and to limit recovery time.

**Comment by dwsteele** [comment]
Hi David,

Threads have been converted to child processes in v1.07 released this morning (it's already in apt.p.o).

I've seen some modest gains in my testing but I'd really like to see what happens when you open it up on your big box.

**Comment by David-Gould** [comment]
On Wed, 07 Sep 2016 08:01:03 -0700
David Steele <notifications@github.com> wrote:

> Hi David,
> 
> Threads have been converted to child processes in v1.07 released this morning (it's already in apt.p.o).
> 
> I've seen some modest gains in my testing but I'd really like to see what happens when you open it up on your big box.

I've been jammed up with work, but I should get a chance to test this
sometime this week. Thanks for the update.

I've also been using a very rough and ready script that performs well for
making local compressed copies of a stopped postgres instance. Consider it an
upper bound on how fast you could go.

# source me
# usage: pgzipdir PGDATA PGDATA_ZIPPED [ JOBS ] [ GZIPLEVEL ]
#        pgunzipdir PGDATA_ZIPPED PGDATA [ JOBS ]
#
# note: both source and destination must be on the same file system

pgzipdir () {
    local src=$1
    local dst=$2
    local jobs=${3:-8}
    local lvl=${4:-4}
    local TIMEFORMAT="jobs $jobs lvl $lvl real %1R user %1U sys %1S pct %P"
    cp -rpl $src $dst
    time find $dst -type f -printf "%k\t%p\n" \
          | sort -nrk1 | cut -f2- \
          | parallel --gnu -j $jobs "gzip -f -$lvl"
}

pgunzipdir () {
    local src=$1
    local dst=$2
    local jobs=${3:-8}
    local TIMEFORMAT="jobs $jobs real %1R user %1U sys %1S pct %P"
    cp -rpl $src $dst
    time find $dst -type f -printf "%k\t%p\n" \
          | sort -nrk1 | cut -f4- \
          | parallel --gnu -j $jobs "gzip -df"
}

-dg


-- 
David Gould              510 282 0869         daveg@sonic.net
If simplicity worked, the world would be overrun with insects.

**Comment by dwsteele** [comment]
Well, those definitely do the trick!

No worries on the testing, whenever you get to it is fine.

**Comment by dwsteele** [comment]
I was able to test the new processing on a 36 core box with process-max=32.  It scaled 3.87x from --process-max=8 on the same box so I feel like the bottleneck has been greatly reduced at the least.  Restores have a higher protocol to CPU ratio (since decompression is fast) so they may not perform quite as well but should still be much faster than before.

**Comment by David-Gould** [comment]
On Thu, 22 Sep 2016 15:18:23 -0700
David Steele <notifications@github.com> wrote:

> I was able to test the new processing on a 36 core box with process-max=32.  It scaled 3.87x from --process-max=8 on the same box so I feel like the bottleneck has been greatly reduced at the least.  Restores have a higher protocol to CPU ratio (since decompression is fast) so they may not perform quite as well but should still be much faster than before.
> 

That is an awesome result! I will test to confirm, but it looks like you beat
me to it. This is incredibly helpful for my current set of problems.

One thing I noticed testing with the shell functions using parallel is that
at high core counts, decompression is actually slower than compression
because it becomes IO bound even on FusionIO devices.

I'll update when I test again.

Thanks,

-dg
