### ISSUE TITLE
ERROR: [056]: unable to find primary cluster - cannot proceed

### ISSUE THREAD

**Issue by julienc256** [pgbackrest/pgbackrest#2322]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

**2.51**

2. PostgreSQL version:

**14.11**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

**Red Hat Enterprise Linux release 8.4**

4. Did you install pgBackRest from source or from a package?

**From RPM Package : pgbackrest-2.51-1PGDG.rhel8.x86_64.rpm**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

**Here are postgresql.conf and pgbackrest.conf files :**
[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/14947763/postgresql.conf.txt)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/14947764/pgbackrest.conf.txt)

7. Describe the issue:
**When I try to create a stanza I get the following error:**
```
[ecv-rh84-2:postgres:pgserver2]$pgbackrest --stanza=DEMO --log-level-console=info stanza-create
2024-04-11 16:43:03.519 P00   INFO: stanza-create command begin 2.51: --exec-id=1021166-5fd7ee31 --log-level-console=info --log-path=/opt/pgsql/log/pgserver2/pgbackrest --pg1-path=/pgqdata/pgserver2/data --repo1-path=/pgqdata/backup/pgserver2/pgbackrest --stanza=DEMO
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
2024-04-11 16:43:04.131 P00   INFO: stanza-create command end: aborted with exception [056]
```
I spent several hours trying to resolve the issue, without success.
Please help !

**Comment by dwsteele** [comment]
Well, since there are no connection errors I would say this is the problem:
```
HINT: are all available clusters in recovery?
```
The cluster you are trying to connect to is a standby. I suggest you read https://pgbackrest.org/user-guide-rhel.html#standby-backup.

**Comment by julienc256** [comment]
Thank you for your reply.

But how did you know that the server is a standby server?

I thought, perhaps wrongly, that it was not a standby server!

Indeed, here is what I get:
```
[ecv-rh84-2:postgres:pgserver2]$psql -c "select pg_is_in_recovery();"
 pg_is_in_recovery
-------------------
 f
(1 row)

```
Furthermore, the server is in R/W mode, I can create tables, update datas!
For me it's not a standby server but maybe I am wrong ...

**Comment by pgstef** [comment]
> But how did you know that the server is a standby server?

It is just an HINT when the process can't connect to a primary cluster, using the default connection settings (socket/port/db/user...).

> I would like to understand why pgbackrest is looking for a primary cluster!

Because it needs a working connection to the cluster to pick the data needed for the stanza creation, and then to start the backup session,... I'm pretty sure your problem comes from a failing connection.

```ini
port = 5433
unix_socket_directories = '/pgqdata/pgserver2/data'
```

If your cluster is using those values: these are not the defaults. So you need to change your stanza configuration accordingly. See https://pgbackrest.org/configuration.html#section-stanza, more specifically pg-port and pg-socket-path.

Regards,

**Comment by julienc256** [comment]
Thanks, it worked ! 👍 

```
[ecv-rh84-2:postgres:pgserver2]$pgbackrest --stanza=DEMO --log-level-console=info stanza-create
2024-04-12 17:34:41.525 P00   INFO: stanza-create command begin 2.51: --exec-id=1420341-1eb774c5 --log-level-console=info --log-path=/opt/pgsql/log/pgserver2/pgbackrest --pg1-path=/pgqdata/pgserver2/data --pg1-port=5433 --repo1-path=/pgqdata/backup/pgserver2/pgbackrest --stanza=DEMO
2024-04-12 17:34:50.160 P00   INFO: stanza-create for stanza 'DEMO' on repo1
2024-04-12 17:34:50.171 P00   INFO: stanza-create command end: completed successfully (8647ms)
```

The solution was to add this line in /etc/pgbackrest.conf file in the stanza section named DEMO :
pg1-port=5433
