### ISSUE TITLE
Feature request:  Add AEAD cipher-type

### ISSUE THREAD

**Issue by udf2457** [pgbackrest/pgbackrest#2324]
As far as I can tell,  the only supported `cipher-type` at present is `aes-256-cbc`.

There is nothing wrong with `aes-256-cbc` in itself, of course.  Except for the fact that it is not an AEAD-type cipher.  Which means that you're only getting confidentiality, not authenticity.

In addition, the side benefit of this would be that you could introduce use a modern algorithm such as `XChaCha20-Poly1305`.  This has the benefit of being a CPU-crypto friendly algorithm, as opposed to AES which really only performs when hardware-assisted (where available, of course ... i.e. not in VMs).  `XChaCha20-Poly1305` can be up to 3x faster on systems that are not AES-accelerated.

**Comment by dwsteele** [comment]
We do have a card to support AES-256-GCM, but it has not risen to the top of the list yet: https://github.com/pgbackrest/pgbackrest/projects/2#card-51634743
