### ISSUE TITLE
Docs:  Replace "service" wording

### ISSUE THREAD

**Issue by udf2457** [pgbackrest/pgbackrest#2325]
In the docs section 20, _"Starting and Stopping"_, `pgbackrest` is referred to as a _"service"_.

I would argue that on Linux, the word _"service"_ has quite a specific well-understood meaning, i.e. a daemon.

Meanwhile, my understanding of the docs, is that when you talk about _"Stop the pgBackRest services"_ and _"Start the pgBackRest services"_, what you are really doing is _"Disable pgBackRest configuration"_ and _"Enable pgBackRest configuration"_.

In and itself `pgbackrest` does nothing unless you manually run it or call it via cron or systemd timers.  So it doesn't meet the definition of a _"service"_ IMHO.

**Comment by dwsteele** [comment]
Well, pgbackrest does also run as a service, but I see what you are getting at.

But I don't think `Disable pgBackRest configuration` really describes it either. Really what we are doing here is stopping writes to the repo going forward, but in fact stop will terminate any pgbackrest process that is currently running.

In truth I rather regret this feature. It was written for a particular user use case years ago and just didn't have enough thought put into it. Now it sort of works for certain use cases but I don't think it is effective overall.

**Comment by dwsteele** [comment]
I have updated the start/stop documentation to remove "service" in #2352.
