### ISSUE TITLE
question on a slighly complex retention scenario

### ISSUE THREAD

**Issue by mzwettler2** [pgbackrest/pgbackrest#2329]
**my requirements:**
keep monthly full backups of the last 12 months
keep weekly differential backups within the last full backup (last month)
keep daily incremental backups based on these differential backups
keep all WALs since the last full backup (last month) to enable PITR

**I came up with this pgbackrest configuration (notation in yaml style):**
repo1-retention-full: '12'
repo1-retention-full-type: count
repo1-retention-diff: '5'
repo1-retention-archive: '1'

**this are my schedules (notation in yaml style):**
full: "0 23 1 * *"
differential: "0 22 * * 7"
incremental: "0 22 * * 1-6"

**questions:**
a) this should do the job. agreed?

b) I am not sure how I would restore a full backup from 10 months ago now? Is it enough to set the backup set name of the related full backup?

`pgbackrest --stanza=stanza-name --set=backup-set-name restore`

**Comment by dwsteele** [comment]
> this should do the job. agreed?

Looks right to me.

> Is it enough to set the backup set name of the related full backup?

Yes.

**Comment by mzwettler2** [comment]
Any WALs before the last full backup will be deleted (repo1-retention-archive: '1').

Will there still be enough WALs to get the full backup from 10 months ago consistent?

**Comment by mzwettler2** [comment]
Thanks!
