### ISSUE TITLE
Faster compression?

### ISSUE THREAD

**Issue by David-Gould** [pgbackrest/pgbackrest#233]
In some environments speed it more important than compression ratio, could pgbackrest be extended to use other compression than zlib?

**Comment by dwsteele** [comment]
Well, it's certainly possible, but hasn't been a huge priority.  BZip2 has been requested and has stable modules for Perl, but I'm guessing you are thinking something more like XZ.  I've looked into that before but the only available Perl module states, "DO NOT use in production code."

That hasn't changed in a while but I'm still hopeful it will be stable at some point.  Of course I could write my own module but I'd rather avoid that of possible.
