### ISSUE TITLE
[Question] Is it possible to have a "WAL only" stanza?

### ISSUE THREAD

**Issue by thecatontheflat** [pgbackrest/pgbackrest#2330]
We are using an HDD minio for storing multi-TB backups of a busy cluster. The problem is that it's being bottlenecked by IOPS, which I believe is caused by WAL archiving. 

One way to address that would be to increase the size of the WAL file, but I see that as a last resort and would like to explore other options. I thought that if I used a faster storage for WAL archives only and slow storage for backups, it would solve the problem, but I'm not sure how to achieve this with pgBackrest.

Is it possible to configure separate stanzas for this? 

For example:

- Slow Stanza, which would store backup data
- Fast Stanza, which would store WAL archives

I do understand that there is a risk that "Fast Stanza" archives expiry becomes independent of the actual backups, which is just something that requires additional management.

**Comment by pgstef** [comment]
Using separated stanza names won't work afaik. And there's no built-in way to split backups and archives. Backups without archives are useless, so it would be too dangerous to allow it imo.

I've seen "creative" people achieving something like this by using nfs mount points: create a local directory used as repo-path with 1 `archive` mount point and 1 `backup` mount point, to replace the directories created by the `stanza-create`.
But as you mentioned, it's a high risk of losing everything.

**Comment by thecatontheflat** [comment]
Thanks you for your swift reply and for the suggestion. I was thinking about how to achieve that on the minio side, but haven't realized I could use NFS mounts (instead of S3) for that too. Will give it a try!
I do understand the implications of course.
