### ISSUE TITLE
Question on maximum safe node

### ISSUE THREAD

**Issue by Tiago-Anastacio** [pgbackrest/pgbackrest#2333]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.51 

2. PostgreSQL version: 16

3. Operating system/version - RHEL 9.2
4. 
5. Did you install pgBackRest from source or from a package?
Community package

About parameter *archive-push-queue-max*
https://pgbackrest.org/configuration.html#section-archive/option-archive-push-queue-max
I see no default value, so I understand by default queue has unlimited size am I right ?

thank you

**Comment by pgstef** [comment]
Hi,

Not sure about what you mean by this `maximum safe node` title.

By default the archive-push queue isn't used, or as unlimited size if you prefer. The result is the same: pgBackRest will try to archive all WAL segments requested by PG (via archive_command), and PG will not recycle/remove those WAL segments until they are successfully archived. Which is the safest option for your PITR capability indeed.

Regards
