### ISSUE TITLE
How should I install dependencies when the machine does not have yum

### ISSUE THREAD

**Issue by 1053531172** [pgbackrest/pgbackrest#2339]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.4.7

2. PostgreSQL version:12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos7

4. Did you install pgBackRest from source or from a package?
source

5. Describe the issue:
How should I install dependencies when the machine does not have yum?I tried using rpm to install dependencies, but it is not easy to use

**Comment by dwsteele** [comment]
You are right, `rpm` is not easy to use. You should be able to download all the dependencies and install them using `rpm` but we don't any instructions for that.

If you do figure it out, please post the results here so others can benefit. Thanks!

**Comment by 1053531172** [comment]
> You are right, `rpm` is not easy to use. You should be able to download all the dependencies and install them using `rpm` but we don't any instructions for that.
> 
> If you do figure it out, please post the results here so others can benefit. Thanks!

I did this by creating a Centos7 system using a virtual machine and changing the /etc/yum.conf configuration as follows
`[main]
#cachedir=/var/cache/yum/$basearch/$releasever
cachedir=/app/yum
keepcache=1
debuglevel=2
logfile=/var/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
installonly_limit=5
bugtracker_url=http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?category=yum
distroverpkg=centos-release
`
Cache the dependencies downloaded through yum in a folder, and then download the dependencies using the following command
`sudo yum install -y bzip2-devel 
sudo yum install -y libssh2-devel 
sudo yum install -y libxml2-devel 
sudo yum install -y libyaml-devel 
sudo yum install -y libzstd-devel 
sudo yum install -y lz4-devel 
sudo yum install -y openssl-devel 
sudo yum install -y postgresql 
sudo yum install -y postgresql-devel 
sudo yum install -y postgresql-libs 
sudo yum install -y zstd 
sudo yum install -y lz4`
Finally, upload the cached rpm dependencies to the target machine and force the installation of dependencies on the target machine through rpm
`sudo rpm -ihv --force depend/*`

**Comment by pgstef** [comment]
On RHEL systems, the [downloadonly](https://access.redhat.com/solutions/10154) plugin is pretty handy too. But indeed, if your target server doesn't have repo access, you'll need another server with the same characteristics to download the packages to be able to install them later somewhere else offline.

It probably could have been a good question for the [pgsql-pkg-yum](https://www.postgresql.org/list/pgsql-pkg-yum/) mailing list (even though RHEL 7 is [EOL](https://yum.postgresql.org/news/rhel7-postgresql-rpms-end-of-life/) for PGDG yum repos).

Not receiving new updates on the server would make me uncomfortable from a stability and security point of view. If you don't want your production servers to have internet access to those repos, maybe it would worth having a repo mirror inside your local network to control what you can update more easily :thinking:

**Comment by 1053531172** [comment]
> On RHEL systems, the [downloadonly](https://access.redhat.com/solutions/10154) plugin is pretty handy too. But indeed, if your target server doesn't have repo access, you'll need another server with the same characteristics to download the packages to be able to install them later somewhere else offline.
> 
> It probably could have been a good question for the [pgsql-pkg-yum](https://www.postgresql.org/list/pgsql-pkg-yum/) mailing list (even though RHEL 7 is [EOL](https://yum.postgresql.org/news/rhel7-postgresql-rpms-end-of-life/) for PGDG yum repos).
> 
> Not receiving new updates on the server would make me uncomfortable from a stability and security point of view. If you don't want your production servers to have internet access to those repos, maybe it would worth having a repo mirror inside your local network to control what you can update more easily 🤔

Yes, for security, my server cannot connect to the Internet. I will update the image regularly to upgrade related plug-ins. However, my scenario is not just that, some servers do not use the images I create. Therefore, I need a method that can solve the above two scenarios. When compiling PostgreSQL, I will compile it on the server where the relevant plugins exist, so that the installation package of PostgreSQL has the required plugins. I have tried compiling pgbackrest using the same method, but it did not work.
