### ISSUE TITLE
Can not archive to S3

### ISSUE THREAD

**Issue by killerwzb** [pgbackrest/pgbackrest#2341]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.51 dev

2. PostgreSQL version: pg9.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
 
I have two servers ,The one is database and the other is repo server .

All server operating systems are CentOS 7.

5. Did you install pgBackRest from source or from a package?

from source

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    
[global]
repo2-path=/repo
repo2-type=s3
repo2-s3-endpoint=cos.ap-chengdu.myqcloud.com
repo2-s3-bucket=pgbackrest-1301801789
repo2-s3-key=AKIDmWoaKzmV9gJ8sYBi9PdwBIIRkuvqs0
repo2-s3-key-secret=645ERZo2Mes29DNOClChK0gH0eBjM9
repo2-cipher-pass=L8yY5t2uaAf6/+uHb0rEWBDZ+n5ZA9yIk3BxrtCTwEns7znjwpLb0ReIxcSHnqxg
repo2-cipher-type=aes-256-cbc
repo2-s3-region=ap-chengdu
log-path=/home/tests3/log

repo1-path=/var/lib/pgbackrest

repo3-path=/repo
repo3-type=s3
repo3-s3-endpoint=minio.local
repo3-s3-bucket=pgbackrest
repo3-s3-key=0jN9wQF6iPAoPVFPPP
repo3-s3-key-secret=OG71PgzSAnEqpASLNUjG55h4vZGZAD0nitmUON
repo3-s3-verify-tls=n
repo3-s3-region=eu-west-3
repo3-s3-port=443

process-max=4
repo3-block=y
repo3-bundle=y
start-fast=y

[demo]
pg1-host=192.168.21.222
pg1-host-user=highgo
pg1-user=system
pg1-database=postgres
pg1-path=/home/highgo/data
pg1-port=6666
pg-version-force=9.5

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

postgres=# show archive_command;
                                              archive_command
------------------------------------------------------------------------------------------------------------
 pgbackrest --config=/home/highgo/conf/pgbackrest.conf --pg-version-force=9.5 --stanza=demo archive-push %p
(1 row)

postgres=# show archive_mode;
 archive_mode
--------------
 on
(1 row)

postgres=# show listen_addresses;
 listen_addresses
------------------
 localhost
(1 row)

postgres=# show max_wal_senders;
 max_wal_senders
-----------------
 0
(1 row)

postgres=# show wal_level;
  wal_level
-------------
 hot_standby
(1 row)

postgres=# show port;
 port
------
 6666
(1 row)

7. Describe the issue:

I've already configured the above settings on a single server, and I can archive and backup on all three repositories. However, if I use one database server and one backup server, it fails.

I'm successfully creating stanza now, all three repositories are fine, but when archiving logs to S3 storage, it fails due to timeout issues. It is repo2 and repo3.

The output like this:

ERROR: [082]: WAL segment 000000010000000000000023 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
       --------------------------------------------------------------------
       If SUBMITTING AN ISSUE please provide the following information:

       version: 2.51dev
       command: backup
       options: --config=/home/tests3/conf/pgbackrest.conf --exec-id=10774-f10400a1 --log-level-console=debug --log-path=/home/tests3/log --pg1-database=postgres --pg1-host=192.168.21.222 --pg1-host-user=highgo --pg1-path=/home/highgo/data --pg1-port=6666 --pg1-user=system --pg-version-force=9.5 --process-max=4 --repo=3 --repo3-block --repo3-bundle --repo2-cipher-pass=<redacted> --repo2-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest --repo2-path=/repo --repo3-path=/repo --repo2-s3-bucket=pgbackrest-1301801789 --repo3-s3-bucket=pgbackrest --repo2-s3-endpoint=cos.ap-chengdu.myqcloud.com --repo3-s3-endpoint=minio.local --repo2-s3-key=<redacted> --repo3-s3-key=<redacted> --repo2-s3-key-secret=<redacted> --repo3-s3-key-secret=<redacted> --repo2-s3-region=ap-chengdu --repo3-s3-region=eu-west-3 --repo3-storage-port=443 --no-repo3-storage-verify-tls --repo2-type=s3 --repo3-type=s3 --stanza=demo --start-fast --type=full

       stack trace:
       command/archive/find.c:walSegmentFind:197:(this: {WalSegmentFind}, walSegment: {"000000010000000000000023"})
       command/archive/find.c:walSegmentFindOne:(storage: {type: s3, path: /repo, write: false}, archiveId: {"9.5-1"}, walSegment: {"000000010000000000000023"}, timeout: 60000)
       command/backup/backup.c:backupStart:(backupData: {BackupData})
       command/backup/backup.c:cmdBackup:(void)
       main.c:main:(debug log level required for parameters)
       --------------------------------------------------------------------
2024-04-26 12:17:24.929 P00 DETAIL: statistics: {"http.client":{"total":1},"http.request":{"total":16},"http.session":{"total":1},"socket.client":{"total":1},"socket.session":{"total":1},"tls.client":{"total":1},"tls.session":{"total":1}}
2024-04-26 12:17:24.929 P00   INFO: backup command end: aborted with exception [082]
2024-04-26 12:17:24.929 P00  DEBUG:     command/exit::exitSafe: => 82
2024-04-26 12:17:25.029 P00  DEBUG:     main::main: => 82

**Comment by dwsteele** [comment]
Did you:
```
HINT: check the PostgreSQL server log for errors.
```
Also, you have exposed your S3 and encryption keys. I suggest you change them now.

**Comment by pgstef** [comment]
And you didn't provided the configuration used on the db host. A common source of mistake when using multiple repos on the same repo-host is not using repo1-host, repo2-host, repo3-host config on the db host btw.

**Comment by killerwzb** [comment]
**This is db host configuration  of pgbackrest**

[global]
repo1-host=192.168.21.223
repo1-host-user=tests3

process-max=2
log-level-console=info
log-level-file=debug

[demo]
pg1-path=/home/highgo/data
pg1-user=system
pg1-port=6666
pg-version-force=9.5
pg1-socket-path=/tmp


**so I specified three repository paths on the backup repository like this**


[global]
repo2-path=/repo
repo2-type=s3
repo2-s3-endpoint=cos.ap-chengdu.myqcloud.com
repo2-s3-bucket=pgbackrest-1301801789
repo2-s3-key=AKIDmWoaKzmV9gJ8sYBi9PdwBIIRkuvqs0
repo2-s3-key-secret=645ERZo2Mes29DNOClChK0gH0eBjM9
repo2-cipher-pass=L8yY5t2uaAf6/+uHb0rEWBDZ+n5ZA9yIk3BxrtCTwEns7znjwpLb0ReIxcSHnqxg
repo2-cipher-type=aes-256-cbc
repo2-s3-region=ap-chengdu
log-path=/home/tests3/log

repo1-path=/var/lib/pgbackrest

repo3-path=/repo
repo3-type=s3
repo3-s3-endpoint=minio.local
repo3-s3-bucket=pgbackrest
repo3-s3-key=0jN9wQF6iPAoPVFPPP
repo3-s3-key-secret=OG71PgzSAnEqpASLNUjG55h4vZGZAD0nitmUON
repo3-s3-verify-tls=n
repo3-s3-region=eu-west-3
repo3-s3-port=443

process-max=4
repo3-block=y
repo3-bundle=y
start-fast=y

[demo]
pg1-host=192.168.21.222
pg1-host-user=highgo
pg1-user=system
pg1-database=postgres
pg1-path=/home/highgo/data
pg1-port=6666
pg-version-force=9.5

**Comment by pgstef** [comment]
Then I just gave you a possible answer in my last comment.

You must tell the archive_command to push the wal archive to multiple repositories.
To do so, you need to have something like this in your db host config:
```ìni
repo1-host=192.168.21.223
repo1-host-user=tests3
repo2-host=192.168.21.223
repo2-host-user=tests3
repo3-host=192.168.21.223
repo3-host-user=tests3
```
And as David said, if not enough, check the PG logs for more info why it would be failing.

And you've just exposed your cipher-pass and secret keys. You should consider to change them and redact it next time you post something ;-)

**Comment by killerwzb** [comment]
Thanks. I try change this.
