### ISSUE TITLE
pgbackrest info json output doesn't show percentage complete

### ISSUE THREAD

**Issue by ajayrahul97** [pgbackrest/pgbackrest#2343]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.48

2. PostgreSQL version: 12.12

3. Operating system/version - Ubuntu 23.04.

4. Did you install pgBackRest from source or from a package? : Source

5. Please attach the following as applicable:
    pgbackrest.conf file(s)
    [seg0]
    pg1-socket-path = /tmp
    pg1-user = myadmin
    log-path = /usr/local/ajay/logs
    repo1-type = posix
    repo1-path = /home/myadmin/ajay/archive/seg0

6. Describe the issue: 
 `pgbackrest info --output=json` does not show the `pct-cplt` field when a backup is in progress.
I can see that here: https://github.com/pgbackrest/pgbackrest/blame/main/src/command/info/info.c#L243,  there is a condition to specifically not include `Percentage Complete` for output type `json`.  Please let me know if there is any specific reason for the condition to exist.

**Comment by jreidthompson** [comment]
See https://github.com/pgbackrest/pgbackrest/issues/2007. The comments explain why and offer a means to calculate percentage complete using size and size-cplt.
