### ISSUE TITLE
WAL segment was not archived before the timeout

### ISSUE THREAD

**Issue by notyuuko** [pgbackrest/pgbackrest#2345]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45

2. PostgreSQL version: 15.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Debian 12

5. Did you install pgBackRest from source or from a package?
Package

6. Please attach the following as applicable:
pgbackrest.conf:
```
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
repo1-cipher-pass=xxx
repo1-cipher-type=aes-256-cbc
archive-timeout=3000

[demo]
pg1-path=/etc/postgresql/15/demo
pg1-port=5433

[synap]
pg1-path=/mnt/HC_Volume_100606862/postgres/15/main/main
pg1-port=5432
```
postgresql.conf:

```
archive_mode = on	
archive_command = 'pgbackrest --stanza=synap archive-push %p'
max_wal_senders = 3
wal_level = replica	
```
log:
```
2024-05-05 19:13:01.670 P00   INFO: check command begin 2.45: --archive-timeout=3000 --exec-id=3006092-91b2dbeb --log-level-console=detail --pg1-path=/mnt/HC_Volume_100606862/postgres/15/main/main --pg1-port=5432 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/var/lib/pgbackrest --stanza=synap
2024-05-05 19:13:02.275 P00   INFO: check repo1 configuration (primary)
2024-05-05 19:13:02.776 P00   INFO: check repo1 archive for WAL (primary)
ERROR: [082]: WAL segment 000000010000128E00000011 was not archived before the 3000000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2024-05-05 20:03:02.876 P00   INFO: check command end: aborted with exception [082]
```

7. Describe the issue:
Hey, so upon running `pgbackrest --stanza=synap --log-level-console=detail check`, I get 
`ERROR: [082]: WAL segment 000000010000128E00000011 was not archived before the 3000000ms timeout`
As you can see I've tried to increase archive-timeout to no avail, I still get the error. Postgres logs show no errors. I've never stopped the stanza.

Synap is the stanza im trying to check, demo is just a leftover from testing - setting it up on demo worked
Sorry if im making an obvious mistake
Thanks.

**Comment by pgstef** [comment]
Hi,

With this log there's unfortunately nothing we can do to help. The check command is only looking at the repository to see if PG has been able to push the archive using archive_command. So you should definitely see something in the PG logs: a failure or a success...

Try adding the following configuration to see more details in your PG logs:
```ini
[global:archive-push]
log-level-console=detail
```

And alternatively, look at the `pg_stat_archiver` view of PG to see if the archiver is running correctly.

Kind Regards,
