### ISSUE TITLE
on FreeBSD 13.3 cron executes pgbackrest but config file is not loaded

### ISSUE THREAD

**Issue by ferz** [pgbackrest/pgbackrest#2347]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.51

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  FreeBSD 13.3

4. Did you install pgBackRest from source or from a package?    From source

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I can backup successfully from shell (tcsh and /bin/sh) from pgbackrest user.
When pgbackrest is executed from pgbackrest cron, it doesn't load config from files located in /usr/local/etc/pgbackrest/conf.d/
Using truss from cron I see pgbackrest to look for pgbackrest.conf only filename in different paths.

**Comment by dwsteele** [comment]
> When pgbackrest is executed from pgbackrest cron, it doesn't load config from files located in /usr/local/etc/pgbackrest/conf.d/

So where does it try to load them from?
