### ISSUE TITLE
Best Practices for Securely Managing Cloud Storage Credentials with pgBackRest

### ISSUE THREAD

**Issue by markosutic** [pgbackrest/pgbackrest#2348]
Hello,

I am currently evaluating pgBackRest for managing backups of our PostgreSQL databases and plan to store the backups in cloud storage services like AWS S3, Google Cloud Storage, and Azure Blob Storage. Given the critical nature of these backups, I am concerned about the security implications of storing the repository credentials directly in the pgBackRest configuration files on the database host. This could potentially expose our backups to risk if the host is compromised.

Could you please provide guidance or recommend best practices for securely managing cloud storage sensitive credentials? 

Thank you for the info.

Best regards,
Marko

**Comment by dwsteele** [comment]
>  I am concerned about the security implications of storing the repository credentials directly in the pgBackRest configuration files on the database host.

Well, at that point the attacker has access to your database as well, so your backups may be the least of your worries.

> Could you please provide guidance or recommend best practices for securely managing cloud storage sensitive credentials?

Two things you can do:

1) Make sure the `pgbackrest.conf` file is readable only for the user that runs pgbackrest (usually postgres but could be another user based on your config).

2) Use the `auto` key type for s3/gcs. This means the host *itself* is authenticated and there will be no auth info in the config file. The attacker still has access to the database and backups, but they will not be able to access the backups from another host.

**Comment by markosutic** [comment]
Thank you David for the info.
