### ISSUE TITLE
retention policy question

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#235]
Documentation says:
"If set to diff (differential) pgBackRest will keep archive logs for the number of full and differential backups defined by retention-archive."  But it does not say what is implied by not specifying it.

So in the case here where I have 2 full backups and perhaps 6 differentials (3 for each full)...

What does the following imply as far as WALs to keep?  It seems as if the following configuration keeps WALs going back to the oldest backup not purged yet.  I guess what I am really asking is what is implied by retention-archive not being specified  like it is here (commented out).

`# retention policy

retention-full=2

retention-diff=3

retention-archive-type=diff

`# retention-archive=2

**Comment by dwsteele** [comment]
Does this help: http://www.pgbackrest.org/configuration.html#section-expire/option-retention-archive-type?

**Comment by MichaelDBA** [comment]
That link did not help.  It is the link I quoted from above that confused me:

Documentation says:
"If set to diff (differential) pgBackRest will keep archive logs for the number of full and differential backups defined by retention-archive." But it does not say what is implied by not specifying it.

**Comment by dwsteele** [comment]
Ah, I see.  It defaults to the number of backups that the archive retention type has.  So if, `retention-archive-type=diff` then `retention-archive` will default to `retention-diff`.

I'll make that clearer in the docs.
