### ISSUE TITLE
recursive user tablespace symlink 

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#236]
When I backup my master to the slave, it does not copy the user tablespace area.  The only difference I can think between one environment where it worked and this one, is that the environment where it works has one symlink for user tablespace, but the one that doesn't work has 2:

cd /pgdata/lenderx/pg_tblspc
ls -la
lrwxrwxrwx  1 postgres postgres   11 May  9  2015 16420 -> /var/pgts/1
cd /var/pgts
ls -la
lrwxrwxrwx 1 postgres postgres 28 Apr  3  2015 1 -> /pgdata-qcr_tblspace/lenderx
cd 1
ls -l
drwx------ 3 postgres postgres 18 May  9  2015 PG_9.4_201409291

Can this be related at all to the fix for 1.05?   This is critical or else I have to backout my production changes.

Or can I use the link-map option when doing backup and restore: 
link-map=pg_tblspace/16420=/pgdata-qcr_tblspace/lenderx

Looks like link-map option assumes PG data directory as start point?

**Comment by dwsteele** [comment]
I don't believe this is related to 1.05.  In any case you should not have a link to a link.  I have code to error on this case but it doesn't seem to be catching this instance for some reason.

Fix your link and I'll make sure this is detected as an error in the future.  Links to links won't be supported as a feature.

**Comment by MichaelDBA** [comment]
Thanks so much, Daniel for gettting back to me quickly on a Saturday!  Much appreciated!

**Comment by dwsteele** [comment]
Fixed in f9fa127.
