### ISSUE TITLE
repo1-retention-diff doesn't work as it supposed to be

### ISSUE THREAD

**Issue by threenotrump** [pgbackrest/pgbackrest#2366]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.49 and 2.51

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos 7

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

[global]
repo1-path=/home/pgbackrest/repo
repo-cipher-pass=secret
repo-cipher-type=aes-256-cbc
start-fast=y
compress-type=zst
repo1-bundle=y
repo1-bundle-limit=10MiB
repo1-bundle-size=50MiB
repo1-block=y

[test]
pg1-host=192.168.213.180
pg1-path=/var/lib/pgsql/14/data
repo1-retention-full=30
repo1-retention-full-type=time
repo1-retention-archive-type=diff
repo1-retention-diff=4

7. Describe the issue:
Hi First thank you very much for developing and maintaining pgbackrest.

Pgbackrest expires diff backup when full backup is taken an example can be see below. Is this expected ?

[root@centos2 burak]# sudo -u pgbackrest pgbackrest --stanza=test info
stanza: test
    status: ok
    cipher: aes-256-cbc

    db (current)
        wal archive min/max (14): 000000010000000000000014/00000001000000000000001C

        full backup: 20240529-201726F
            timestamp start/stop: 2024-05-29 20:17:26+03 / 2024-05-29 20:17:29+03
            wal start/stop: 000000010000000000000014 / 000000010000000000000014
            database size: 25.9MB, database backup size: 25.9MB
            repo1: backup size: 3.0MB

        diff backup: 20240529-201726F_20240529-201741D
            timestamp start/stop: 2024-05-29 20:17:41+03 / 2024-05-29 20:17:44+03
            wal start/stop: 000000010000000000000016 / 000000010000000000000016
            database size: 25.9MB, database backup size: 8.3KB
            repo1: backup size: 408B
            backup reference list: 20240529-201726F

        diff backup: 20240529-201726F_20240529-201747D
            timestamp start/stop: 2024-05-29 20:17:47+03 / 2024-05-29 20:17:50+03
            wal start/stop: 000000010000000000000017 / 000000010000000000000018
            database size: 25.9MB, database backup size: 22.2KB
            repo1: backup size: 2KB
            backup reference list: 20240529-201726F

        diff backup: 20240529-201726F_20240529-201753D
            timestamp start/stop: 2024-05-29 20:17:53+03 / 2024-05-29 20:17:56+03
            wal start/stop: 00000001000000000000001A / 00000001000000000000001A
            database size: 25.9MB, database backup size: 22.2KB
            repo1: backup size: 2KB
            backup reference list: 20240529-201726F

        diff backup: 20240529-201726F_20240529-201759D
            timestamp start/stop: 2024-05-29 20:17:59+03 / 2024-05-29 20:18:02+03
            wal start/stop: 00000001000000000000001B / 00000001000000000000001C
            database size: 25.9MB, database backup size: 22.4KB
            repo1: backup size: 2KB
            backup reference list: 20240529-201726F
[root@centos2 burak]# sudo -u pgbackrest pgbackrest --stanza=test backup --type=full
[root@centos2 burak]# sudo -u pgbackrest pgbackrest --stanza=test info
stanza: test
    status: ok
    cipher: aes-256-cbc

    db (current)
        wal archive min/max (14): 000000010000000000000014/00000001000000000000001E

        full backup: 20240529-201726F
            timestamp start/stop: 2024-05-29 20:17:26+03 / 2024-05-29 20:17:29+03
            wal start/stop: 000000010000000000000014 / 000000010000000000000014
            database size: 25.9MB, database backup size: 25.9MB
            repo1: backup size: 3.0MB

        diff backup: 20240529-201726F_20240529-201747D
            timestamp start/stop: 2024-05-29 20:17:47+03 / 2024-05-29 20:17:50+03
            wal start/stop: 000000010000000000000017 / 000000010000000000000018
            database size: 25.9MB, database backup size: 22.2KB
            repo1: backup size: 2KB
            backup reference list: 20240529-201726F

        diff backup: 20240529-201726F_20240529-201753D
            timestamp start/stop: 2024-05-29 20:17:53+03 / 2024-05-29 20:17:56+03
            wal start/stop: 00000001000000000000001A / 00000001000000000000001A
            database size: 25.9MB, database backup size: 22.2KB
            repo1: backup size: 2KB
            backup reference list: 20240529-201726F

        diff backup: 20240529-201726F_20240529-201759D
            timestamp start/stop: 2024-05-29 20:17:59+03 / 2024-05-29 20:18:02+03
            wal start/stop: 00000001000000000000001B / 00000001000000000000001C
            database size: 25.9MB, database backup size: 22.4KB
            repo1: backup size: 2KB
            backup reference list: 20240529-201726F

        full backup: 20240529-201832F
            timestamp start/stop: 2024-05-29 20:18:32+03 / 2024-05-29 20:18:35+03
            wal start/stop: 00000001000000000000001E / 00000001000000000000001E
            database size: 25.9MB, database backup size: 25.9MB
            repo1: backup size: 3.0MB

**Comment by pgstef** [comment]
Hi

> Pgbackrest expires diff backup when full backup is taken an example can be see below. Is this expected ?

Yes it is expected. First of all, backups are expired by the expire command which runs automatically after a new successful backup is taken (see expire-auto option).

From the retention point of view, as you can see in the [source code](https://github.com/pgbackrest/pgbackrest/blob/main/src/command/expire/expire.c#L193), full backups are considered differential for the purpose of retention.

This is kinda logical behavior if you look at it from the retention period point of view, it gives you a total number of backups after the oldest full backup in the repository. But I agree this isn't very clear from the docs.

Kind Regards

**Comment by threenotrump** [comment]
Hi @pgstef 

Thank you for quick and good explanation. Please update this part in the [docs](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-diff) which made me think this is a bug.
