### ISSUE TITLE
Unable to sync slave

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#237]
As the slave is my backup host, I did a full backup from the master and restored it locally on the slave.  Everything worked fine.  But when I started the slave and it went through the normal recovery motions, it found a WAL that it thinks it needed and got these errors in the slave's log:

   2016-08-13 19:44:33.914 CDT replicator@[unknown][11279:idle] 10.100.128.210(54383) walreceiver : ERROR:  requested WAL segment 00000002000022F400000096 has already been removed

Here is the snippet from backup: start / stop timestamp: 2016-08-13 14:00:42 / 2016-08-13 17:09:06

But I only see these in the pgbackrest archive directory:
   drwxr-x--- 2 postgres postgres 24576 Aug 13 06:39 00000002000022F3
   drwxr-x--- 2 postgres postgres 12288 Aug 13 08:42 00000002000022F2
   drwxr-x--- 2 postgres postgres 24576 Aug 13 11:09 00000002000022F4
   drwxr-x--- 2 postgres postgres 24576 Aug 13 17:09 00000002000022F5
   drwxr-x--- 2 postgres postgres 16384 Aug 13 19:46 00000002000022F6
   
   The wal segment, 00000002000022F400000096, is still in the primary pg_xlog directory with date: 
   -rw------- 1 postgres postgres 16777216 Aug 13 09:12 00000002000022F400000096
   
   So I'm kinda confused about the the full WAL file name missing in pgbackrest archive.  And why it doesn't pull all the WALs from primary and not just a few of them every 2 hours or so.  And why is the full name of the WAL truncated in the pgbackrest repo?

**Comment by MichaelDBA** [comment]
Interesting...

I did another full backup followed by a restore and the slave goes into recovery mode pulling the WALs from the master as expected, but then when it is caught up with the master, I still get this same error message for the WAL from the previous backup and restore!

2016-08-14 06:52:12.362 CDT replicator@[unknown][6055:idle] 10.100.128.210(42264) walreceiver : ERROR:  requested WAL segment 00000002000022F400000096 has already been removed

Here are my commands from the slave:
pgbackrest --stanza=lenderx --type=full --log-level-console=info --archive-check --start-fast backup
pg_ctlcluster 9.4 lenderx stop -m immediate
find /pgdata/lenderx -mindepth 1 -delete;find /pgdata-qcr_tblspace/lenderx -mindepth 1 -delete;find /pgxlog/lenderx -mindepth 1 -delete;find /pglog/lenderx -mindepth 1 -delete;
pgbackrest --stanza=lenderx --delta restore --log-level-console=info
pg_ctlcluster 9.4 lenderx start

**Comment by MichaelDBA** [comment]
I'm wondering if I should just clear out the pgbackrest repo and try the backup and restore again?

**Comment by dwsteele** [comment]
The top level of the archive directory contains directories, not files.  If you look in the directories you will find the actual WAL files.

I'm not sure what's going on here but I'm not convinced it's a backrest issue.  In any case you haven't provided any config files or logs so there's not much to go on.

The archive-test command became the check command.

**Comment by MichaelDBA** [comment]
I'm gonna clear out the pgbackrest repo and try the backup and restore again tonight.  Then if I have any problems, I will send you the requested info.

Yeah, second look confirms those are directories not files, my bad, too many hours recently....

**Comment by MichaelDBA** [comment]
Again, the slave is my backup host.  I have just deleted everything under the pgbackrest repo on the slave.  As expected an archive directory was automatically created moments later since archiving on the master is sending them over to the backup host.  I have nothing under my  backup directory.

Shortly I am going to start my full backup and then start the restore to resync the slave.  Afterwards I will restart the slave cluster expecting to see the usual replay WALs for the recovery followed by streaming replication mode (recovery.conf being created by pg backrest at the end of the restore).  Does everything seem kosher at this point?  Hopefully I don't get the WAL file error:
"requested WAL segment blahblahblah has already been removed

**Comment by dwsteele** [comment]
Sounds plausible but I don't think any of that was your issue.

**Comment by MichaelDBA** [comment]
Same problem same WAL file:
016-08-16 02:58:28.984 CDT replicator@[unknown][17378:idle] 10.100.128.210(49089) walreceiver : ERROR:  requested WAL segment 00000002000022F400000096 has already been removed

The oldest WAL on the master is dated yesterday august 15 at 3:17pm.  The backup started yesterday at 8:40pm, over 5 hours after the oldest WAL on the master as shown below:

-rw-r--r-- 1 postgres postgres       33 May 12  2015 00000002.history
-rw------- 1 postgres postgres 16777216 Aug 15 15:17 000000020000230F000000E2
-rw------- 1 postgres postgres 16777216 Aug 15 15:17 000000020000230F000000E3
-rw------- 1 postgres postgres 16777216 Aug 15 15:18 000000020000230F000000E4
-rw------- 1 postgres postgres 16777216 Aug 15 15:18 000000020000230F000000E5
-rw------- 1 postgres postgres 16777216 Aug 15 15:18 000000020000230F000000E6
-rw------- 1 postgres postgres 16777216 Aug 15 15:18 000000020000230F000000E7
-rw------- 1 postgres postgres 16777216 Aug 15 15:18 000000020000230F000000E8
-rw------- 1 postgres postgres 16777216 Aug 15 15:19 000000020000230F000000E9
-rw------- 1 postgres postgres 16777216 Aug 15 15:19 000000020000230F000000EA
-rw------- 1 postgres postgres 16777216 Aug 15 15:19 000000020000230F000000EB
-rw------- 1 postgres postgres 16777216 Aug 15 15:20 000000020000230F000000EC
-rw------- 1 postgres postgres 16777216 Aug 15 15:20 000000020000230F000000ED
-rw------- 1 postgres postgres 16777216 Aug 15 15:20 000000020000230F000000EE
-rw------- 1 postgres postgres 16777216 Aug 15 15:20 000000020000230F000000EF
-rw------- 1 postgres postgres 16777216 Aug 15 15:20 000000020000230F000000F0
-rw------- 1 postgres postgres 16777216 Aug 15 15:21 000000020000230F000000F1
-rw------- 1 postgres postgres 16777216 Aug 15 15:21 000000020000230F000000F2
-rw------- 1 postgres postgres 16777216 Aug 15 15:21 000000020000230F000000F3
-rw------- 1 postgres postgres 16777216 Aug 15 15:22 000000020000230F000000F4
-rw------- 1 postgres postgres 16777216 Aug 15 15:22 000000020000230F000000F5
-rw------- 1 postgres postgres 16777216 Aug 15 15:22 000000020000230F000000F6
--More--

After starting the slave, it went through all the WALs starting with:
2016-08-16 02:50:38.727 T00   INFO: get WAL segment 000000020000230E00000015
2016-08-16 02:50:38.898 CDT [unknown]@[unknown][15758:] [local] [unknown] : LOG:  connection received: host=[local]
2016-08-16 02:50:38.898 CDT postgres@postgres[15758:] [local] [unknown] : FATAL:  the database system is starting up
2016-08-16 02:50:39.053 T00   INFO: archive-get stop
2016-08-16 02:50:39.095 CDT @[15744:]   : LOG:  restored log file "000000020000230E00000015" from archive
2016-08-16 02:50:39.165 CDT @[15744:]   : LOG:  redo starts at 230E/15002B38

Here is the snippet at the end where the error first occurs:
2016-08-16 02:56:02.433 CDT @[15744:]   : LOG:  restored log file "000000020000230F0000008D" from archive
2016-08-16 02:56:02.908 T00   INFO: archive-get start: --buffer-size=8388608 --compress --db-path=/pgdata/lenderx --log-level-console=info --log-level-file=info --log-path=/pgarchive/pgbackrest/log/lenderx --repo-path=/pgarchive/pgbackrest --stanza=lenderx
2016-08-16 02:56:02.908 T00   INFO: get WAL segment 000000020000230F0000008E
2016-08-16 02:56:03.350 T00   INFO: archive-get stop
2016-08-16 02:56:03.393 CDT @[15744:]   : LOG:  restored log file "000000020000230F0000008E" from archive
2016-08-16 02:56:03.521 CDT [unknown]@[unknown][17049:] 10.100.128.210(49031) [unknown] : LOG:  connection received: host=10.100.128.210 port=49031
2016-08-16 02:56:03.650 CDT replicator@[unknown][17049:authentication] 10.100.128.210(49031) [unknown] : LOG:  replication connection authorized: user=replicator SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=on)
2016-08-16 02:56:03.708 CDT replicator@[unknown][17049:idle] 10.100.128.210(49031) walreceiver : ERROR:  requested WAL segment 00000002000022F400000096 has already been removed

**Comment by dwsteele** [comment]
Looks like restore and recovery were successful and replication is working correctly.  Not sure what the error is about.  If you are using replication slots you might check if the slot needs to be reset.

**Comment by MichaelDBA** [comment]
Nope, we don't use replication slots.  Any ideas about how that during the recovery and the ordered sequence of WALs being applied, that this one walreceiver error comes up, and then the recovery continues to process the WALs sequentially until the end?

Any other ideas?  I have never seen this symptom before.  I have attached the pgbackrest backup and restore logs.

How would I go about pulling the WALs from the local pgbackrest repo and not letting PG pull them using walreceiver from the master?

[pgbackrest.zip](https://github.com/pgbackrest/pgbackrest/files/420587/pgbackrest.zip)
