### ISSUE TITLE
Restoring backup takes long time

### ISSUE THREAD

**Issue by jahnavisana2812** [pgbackrest/pgbackrest#2370]
I was testing the backup and restore procedure for our postgres cluster using pgbackrest.During the restoration process, I faced some issues, particularly the prolonged duration it took. Specifically, it required around 160 minutes to restore a 1.9 GB backup.Do you have any suggestions or insights that might help quicken the restoration process?

**Comment by pgstef** [comment]
Hi,

To be able to help, we'll need more context. Please follow the issue template and provide configurations, command logs, etc.

Regards

**Comment by jahnavisana2812** [comment]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:Using inbuilt pgbackrest of crunchydata postgres operator version 5.5.0,image being used for pgbackrest is registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-2

2. PostgreSQL version:16.1

3. Operating system/version - We are running postgres on kubernetes cluster and the operating system is Ubuntu 22.04

4. Did you install pgBackRest from source or from a package?
From a package as it is supplied by crunchydata

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    ```
log-path = /pgdata/pgbackrest/log
repo1-path = /pgbackrest/repo1
repo1-s3-bucket = ***
repo1-s3-endpoint = ***
repo1-s3-region = us-east-1
repo1-type = s3

[db]
pg1-path = /pgdata/pg16
pg1-port = 5432
pg1-socket-path = /tmp/postgres
```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    ```
    archive_command = 'pgbackrest --stanza=db archive-push "%p"'
archive_mode = 'on'
listen_addresses = '*'
max_wal_senders = '10'
wal_level = 'logical'
port=5432
```
    - errors in the postgresql log file before or during the time you experienced the issue
    No errors as such
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[db-restore.log](https://github.com/user-attachments/files/15547891/db-restore.log)

7. Describe the issue:
During the restoration process, I faced some issues, particularly the prolonged duration it took. Specifically, it required around 160 minutes to restore a 1.9 GB backup

**Comment by pgstef** [comment]
You're basically using s3 repository with only 1 process to fetch the files.
If you look at the DETAIL level log, you'll see most of your files are really small (95% < 24KB, lots of 0B).
It is particularly slow to establish connections to s3, so retrieving around 6578 files individually 1 by 1 is very slow.

You should see a pretty good improvement by using [repo bundling](https://pgbackrest.org/configuration.html#section-repository/option-repo-bundle) which is made exactly for that. And ofc using [multiple-processes](https://pgbackrest.org/configuration.html#section-general/option-process-max), not only 1.

It seems like you're using 2.47 atm and for file bundling I'd recommend to use more recent release (at least 2.50, but 2.52 would be better ofc).
