### ISSUE TITLE
Where is the stanza data stored

### ISSUE THREAD

**Issue by pgodfrin-nov** [pgbackrest/pgbackrest#2372]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
`2.38`
2. PostgreSQL version:
`13.5`
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
`Ubuntu 20.4`
4. Did you install pgBackRest from source or from a package?
`package`
5. Please attach the following as applicable:
```
[global]
buffer-size=16MB
log-path=/postgres/admin/logs
spool-path=/var/spool/pgbackrest
start-fast=y
archive-async=y
log-level-file=detail
archive-timeout=120

repo-type=s3
repo-s3-endpoint=s3.us-east-1.amazonaws.com
repo-s3-bucket=app04p1-prod-timescale-unidb-data-bucket
repo-s3-region=us-east-1
repo-cipher-type=none
repo-path=/prdudb01
repo1-s3-uri-style=path
repo1-s3-key-type=auto
repo1-retention-full=5

[global:archive-get]
process-max=8

[global:archive-push]
process-max=12

[unidb01]
pg1-port=5432
pg1-path=/postgres/udb01/data

[unidb01-push]
pg1-port=5432
pg1-path=/postgres/wal/udb01
```
7. Describe the issue:
I have a 2 node Patroni cluster that I am 'cloning' from snapshots. I can bring up the first node and create a new stanza (with a different name) as that instance is the primary. However to bring up the second instance, it will need to read archives from the primary stored in the new stanza. I cannot bring up the second node with it referring to the old stanza.

**Q: Is there a way to copy the stanza data from one instance to another?**

**Comment by dwsteele** [comment]
You haven't provided enough information to make any sense of this question. You'll need to at least provide your configuration as requested in the issue instructions.

> Is there a way to copy the stanza data from one instance to another?

There is no need to do this if you have everything configured correctly. Did you follow the multi-host setup in the user guide?

**Comment by pgodfrin-nov** [comment]
I don't see a multi-host setup. What chapter is that?

**Comment by dwsteele** [comment]
https://pgbackrest.org/user-guide.html#repo-host and https://pgbackrest.org/user-guide.html#replication.

**Comment by pgodfrin-nov** [comment]
Thanks much! I'm reviewing the links.

**Comment by pgodfrin-nov** [comment]
Please help me understand. 

1. Are you suggesting I need a "dedicated repository host"?
2. Is a dedicated repo host indicated by the "repo1-host" setting?
3. In section 18.3, the example shows `repo1-host=repository` , but the command reference (2.4.9) shows `repo1-host=repo1.domain.com` - is "repository" a placeholder for hostname (IP or DNS)?
4. Will a dedicated repo host work with `repo-type=s3` ?


It appears that section _21 Replication_ describes how to create a standby with a 
pgbackrest restore, but I don't see how that helps me in this situation.

Perhaps I should clarify. Since each clone (primary and standby) is created from a snapshot, the pgbackrest.conf files are exactly the same as the source that was snapped. If the db instance is brought up with the same stanza, archives and backups from the cloned instance will intermingle with the actual production database (_is this true?_). This is why I believe a new stanza should be created. And so the instance must be the primary. The two instances are configured with streaming replication and governed by patroni. It is possible to bring up the standby, as a primary using `pg_ctl start` and then create the new stanza on the standby, but then the timelines are out of sync and patroni will not be able to reconcile the two nodes (I tried...).

This is why I was asking where the results of the `stanza-create` command are stored so that I may simply move that information (and the new conf file) to the standby.

In the end, are you suggesting the only way to do this is to restore the standby by a backup?

Thanks for helping.

**Comment by dwsteele** [comment]
> Are you suggesting I need a "dedicated repository host"?

You don't need one, but you'll have a tough time without one. If you have a repo host pgBackRest will automatically detect failover but without a repo host you'll need to reconfigure on he fly.

> Is a dedicated repo host indicated by the "repo1-host" setting?

Yes.

> In section 18.3, the example shows repo1-host=repository , but the command reference (2.4.9) shows repo1-host=repo1.domain.com - is "repository" a placeholder for hostname (IP or DNS)?

In the env where we build the docs `repository` is the actual host name.

> Will a dedicated repo host work with repo-type=s3 ?

Yes. It will work with any repo type.

> If the db instance is brought up with the same stanza, archives and backups from the cloned instance will intermingle with the actual production database (is this true?). 

No, since the replicas will not archive. But if you are bring up a primary for, e.g., reporting or testing then you'll want to specify `archive-mode=n` to prevent archiving.

> The two instances are configured with streaming replication and governed by patroni.

Sorry -- I don't have any Patroni experience so I can't help here. There are a number of blogs you could check out with info, e.g. https://pgstef.github.io/2022/07/12/patroni_and_pgbackrest_combined.html

**Comment by pgstef** [comment]
> 7\. I have a 2 node Patroni cluster that I am 'cloning' from snapshots. I can bring up the first node and create a new stanza (with a different name) as that instance is the primary. However to bring up the second instance, it will need to read archives from the primary stored in the new stanza. I cannot bring up the second node with it referring to the old stanza.

I think your misunderstanding come from here. A primary and a standby server linked by streaming replication should use the same stanza (name and repository). Which is quite well described in the stanza options section:

> Indexing: All pg- options are indexed to allow for configuring multiple PostgreSQL hosts. For example, a single primary is configured with the pg1-path, pg1-port, etc. options. If a standby is configured then index the pg- options on the repository host as pg2- (e.g. pg2-host, pg2-path, etc). 

Although, indexing is useful when you use a repo-host. When you're pushing backups from the PG hosts, then you can have symmetric configuration but you need a shared storage using the same stanza name for the entire cluster.

**Comment by pgodfrin-nov** [comment]
Thanks @pgstef , see my comments berlow:

> I think your misunderstanding come from here. A primary and a standby server linked by streaming replication should use the same stanza (name and repository). Which is quite well described in the stanza options section:

For the Primary and Standby, I have a config where they use the same stanza. The challenge is when I _clone _production__ At that point I now have P/S and Pclone/Sclone instances all with the same stanza. And as such, when the cloned instances start they have the potential of archiving to the same repository (S3). To avoid this, I keep the cloned instances down, change the Primary's stanza name in `pgbackrest.conf`, and archive command : `archive_command: 'pgbackrest --stanza=clndb01 archive-push %p'` . When the cloned instance comes up, I run the stanza creation and it works fine. 

Bringing up the standby is not so smooth. Patroni, as the cluster management software, wants to keep the timelines in sync. But I can't bring up the standby 'normally' as it will attempt a warmstart using the WAL archives, and if the WAL archives needed are in S3, it will go there and grab the original archives. However, the primary was brought up using a different repo, and so the standby startup simply won't work. If I startup the standby manually using `pg_ctl`, I can change the stanza, but now the timelines are different, and so the nodes are out of sync and Patroni won't start up.

I've used rsynch to get the cloned standby to work, but that takes time for a 4TB database. As such, it seems so much easier to clone the pgbackrest configuration's _binary_ configuration. And so far, the pgbackrest folks have not addressed my original question:

> [Where is the stanza data stored](https://github.com/pgbackrest/pgbackrest/issues/2372#top)
#2372

**Comment by pgstef** [comment]
> And so far, the pgbackrest folks have not addressed my original question:
> [Where is the stanza data stored](https://github.com/pgbackrest/pgbackrest/issues/2372#top)
> Q: Is there a way to copy the stanza data from one instance to another?

No, there's not.
If there would have been a simple answer to that question, we would have told you.

**Comment by pgodfrin-nov** [comment]
Well, that answers that. Thanks.
