### ISSUE TITLE
Excessive Data Size in Pgbackrest incremental Backup

### ISSUE THREAD

**Issue by abdullahergin** [pgbackrest/pgbackrest#2373]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: `2.51`

2. PostgreSQL version:1`3.3`

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: `Ubuntu 20.04`

4. Did you install pgBackRest from source or from a package? repo;
    `  sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -`

6. Please attach the following as applicable:
    `- `pgbackrest.conf` file(s);

```
Backup Node;
[global]
repo1-path=/mnt/dbbackup
repo1-retention-full=1
process-max=8
start-fast=y
log-level-console=info
log-level-file=info

[my_tanza]
pg1-host=primary_hostname
pg1-path=/data_path
pg1-port=5433


Primary Node;
[global]
log-level-file=info
repo1-host=backup_hostname

archive-async          = y
process-max            = 2
spool-path             = /var/spool/pgbackrest

[global:archive-get]
process-max=8

[global:archive-push]
process-max=8

[my_stanza]
pg1-path=/data_path
pg1-port=5433
```
   
 - postgresql.conf settings;

           `- archive_mode = on
            - archive_command = 'pgbackrest --stanza=my_stanza archive-push %p'
            - listen_addresses = *
            - max_wal_senders = 10 
            - wal_level = replica
            - port = 5433`

   - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
`2024-06-12 02:00:06.179 P00   INFO: last backup label = 20240609-105403F_20240611-020004I, version = 2.51
2024-06-12 02:00:06.179 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2024-06-12 02:00:15.287 P00   INFO: backup start archive = 000000010000058C00000068, lsn = 58C/680003C0
2024-06-12 02:00:15.287 P00   INFO: check archive for prior segment 000000010000058C00000067
2024-06-12 03:26:46.987 P00   INFO: execute non-exclusive backup stop and wait for all WAL segments to archive
2024-06-12 03:26:47.192 P00   INFO: backup stop archive = 000000010000058C0000007C, lsn = 58C/7C079EE0
2024-06-12 03:26:47.198 P00   INFO: check archive for segment(s) 000000010000058C00000068:000000010000058C0000007C
2024-06-12 03:26:52.640 P00   INFO: new backup label = 20240609-105403F_20240612-020005I
2024-06-12 03:26:52.752 P00   INFO: incr backup size = 581.0GB, file total = 4241
2024-06-12 03:26:52.752 P00   INFO: backup command end: completed successfully (5211265ms)`
7. Describe the issue:

With pgbackrest, I take full backup 1 day a week and incr backup for the remaining 6 days. The database I have backed up is currently 2.2 TB and this is as of the day this full backup was taken, so there have been very little changes in the data size. But the incr backups I take after the full backup absurdly take up excessive space. My info command;
`stanza: my_stanza_stanza
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13): 000000010000053300000017/00000001000005A50000002D

        full backup: 20240609-105403F
            timestamp start/stop: 2024-06-09 10:54:03+03 / 2024-06-09 15:20:27+03
            wal start/stop: 000000010000053300000017 / 00000001000005330000005D
            database size: 2071.6GB, database backup size: 2071.6GB
            repo1: backup set size: 1977.4GB, backup size: 1977.4GB

        incr backup: 20240609-105403F_20240610-020004I
            timestamp start/stop: 2024-06-10 02:00:04+03 / 2024-06-10 02:08:24+03
            wal start/stop: 000000010000053500000029 / 000000010000053500000030
            database size: 2071.7GB, database backup size: 51.6GB
            repo1: backup set size: 1977.4GB, backup size: 42.1GB
            backup reference list: 20240609-105403F

        incr backup: 20240609-105403F_20240611-020004I
            timestamp start/stop: 2024-06-11 02:00:04+03 / 2024-06-11 03:22:13+03
            wal start/stop: 000000010000055E0000001A / 000000010000055E00000033
            database size: 2138.2GB, database backup size: 527.8GB
            repo1: backup set size: 2040.4GB, backup size: 498.8GB
            backup reference list: 20240609-105403F, 20240609-105403F_20240610-020004I

        incr backup: 20240609-105403F_20240612-020005I
            timestamp start/stop: 2024-06-12 02:00:05+03 / 2024-06-12 03:26:47+03
            wal start/stop: 000000010000058C00000068 / 000000010000058C0000007C
            database size: 2195.5GB, database backup size: 581.0GB
            repo1: backup set size: 2094.9GB, backup size: 548GB
            backup reference list: 20240609-105403F, 20240609-105403F_20240610-020004I, 20240609-105403F_20240611-020004I
`

As you can see, especially in the last two incr backups, there is a terrible magnitude, but there has been no such change since the last incr backups. There was no such size in my database as of the last full backup, let alone the last incr backup. What is the reason for this? Is it related to wal archiving? I found the following topic related to wal archiving management, but I am not sure what value to enter: [Pgbackrest Retention Archive](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-archive)
Or are there parameters I need to change in my config files?

**Comment by dwsteele** [comment]
You'll get better results with block incremental. See https://pgbackrest.org/user-guide.html#backup/block.

**Comment by abdullahergin** [comment]
Thank you. I will try it now but I have a different structure where I get the backups on the standby server. (backup-standby=y) Should I enter this parameter in the config file of my primary server or in the config file of the standby server?

What I was asked was to take an incr backup every 15 minutes to go back to 15 minutes ago. I think this is not suitable for the pgbackrestin backup strategy.

**Conf;**
`**pg-backup;**
[global]
repo1-path=/mnt/dbbackup
repo1-retention-full=2
process-max=2
start-fast=y
log-level-console=info
#log-level-file=debug
log-level-file=info
backup-standby=y


[my_stanza]
pg1-host=primary_hostname
pg1-path=/data
pg1-port=5433
pg2-host=standby_hostname
pg2-path=/data
pg2-port=5433
`

`**pg-primary;**
[global]
log-level-file=info
repo1-host=backup_hostname
start-fast=y
archive-async = y
process-max = 2
spool-path = /var/spool/pgbackrest

[global:archive-get]
process-max=4

[global:archive-push]
process-max=4

[my_stanza]
pg1-path=/data
pg1-port=5433
`

`**pg-standby;**
[global]
log-level-file=info
repo1-host=backup_hostname
start-fast=y
process-max = 2
spool-path = /var/spool/pgbackrest

[my_stanza]
pg1-path=/data
pg1-port=5433
`

`**crontab command;**
*/15 03-23 * * MON,TUE,WED,THU,FRI,SAT sudo -u pgbackrest pgbackrest --stanza=my_stanza --type=incr backup --log-level-console=info
`
I set up this structure hoping that every time I take an incr backup every 15 minutes I will make the changes from the previous incr backup, but each time the incr backups grew quickly and started to take up too much space. First of all, can I go back to 15 minutes ago without this structure, that is, by taking an incr backup once a day instead of every 15 minutes?

Should I install the block incr structure on the primary server or standby server?
