### ISSUE TITLE
Restore question

### ISSUE THREAD

**Issue by tdavis** [pgbackrest/pgbackrest#238]
I attempted to restore from a remote backup host. The restore part completed successfully, but after starting the database postgres is now (very slowly) restoring every WAL segment file from the *remote* database. My question is, fundamentally, what does the ``restore`` command do? The documentation claims:

> A restore is the act of copying a backup to a system where it will be started as a live database cluster.

However, that doesn't appear to have happened in my case. Postgres has been unavailable since starting up and appears to be replaying the entire WAL history through the remote database, not through a local optimized archive or simply booting up without any recovery following the successful ``restore`` command.

**Comment by dwsteele** [comment]
The `restore` command copies all the files that are required for Postgres to do recovery.  Recovery is the operation that replays WAL and is entirely under the control of Postgres and can only be performed by Postgres.  

If streaming replication is enabled, Postgres will prefer to get WAL segments from the master (the remote database).  If your remote connection is slow and you would rather pull from the archive you'll need to disable streaming replication during initial recovery.

**Comment by tdavis** [comment]
Good to know for next time! Is there any query or log that indicates the percentage number of segments left to go?

**Comment by dwsteele** [comment]
Nothing quite so tidy I'm afraid.  The current WAL being replayed can be found in the Postgres log (or with `pg_last_xlog_replay_location()` and that can be compared against the last WAL in the archive.  That will only work if you are replaying to the end, not for PITR.
