### ISSUE TITLE
Recovery from folder (related to #2042)

### ISSUE THREAD

**Issue by birtalevente** [pgbackrest/pgbackrest#2386]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.52

2. PostgreSQL version: 14.12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: rocky linux 8.10

4. Did you install pgBackRest from source or from a package? from rpm

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Related to the https://github.com/pgbackrest/pgbackrest/issues/2042:
I see backup.info growing in size. (You said before that backup.info remain constant)
This mean that the actual file contain all the keys from all full backups for the backup.manifest? 
And when a full backup (and related diff,inc) deleted because retention policy then a key is deleted too?

Following the above logic, let's say, I have a full backup dated from 2023-08-01. This can be decrypted with any backup.info newer than 2023-08-01?

Thank you
Levi

**Comment by dwsteele** [comment]
> I see backup.info growing in size. (You said before that backup.info remain constant)

Hmm, I don't think I said that.

> This mean that the actual file contain all the keys from all full backups for the backup.manifest?

`backup.info` contains the key to decrypt any manifest that has been created in the stanza -- ever.

> And when a full backup (and related diff,inc) deleted because retention policy then a key is deleted too?

Not exactly. The backup.manifest is deleted and it contains the key used to decrypt the backup files. No key is removed from `backup.info`.

> Following the above logic, let's say, I have a full backup dated from 2023-08-01. This can be decrypted with any backup.info newer than 2023-08-01?

Since the key in `backup.info` does not change, sure.
