### ISSUE TITLE
ERROR: [029]: manifest validation failed 

### ISSUE THREAD

**Issue by threenotrump** [pgbackrest/pgbackrest#2391]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.52.1

2. PostgreSQL version: 14

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS 7

4. Did you install pgBackRest from source or from a package? Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I am seeing the error below despite my pgbackrest version is 2.52.1
`ERROR: [029]: manifest validation failed:
       repo size must be > 0 for file 'pg_tblspc/16400/PG_14_202107181/16403/221322027_fsm'
       repo size must be > 0 for file 'pg_tblspc/16401/PG_14_202107181/16403/83220546_fsm'
2024-07-01 16:05:51.893 P00   INFO: backup command end: aborted with exception [029]`

**Comment by dwsteele** [comment]
Please provide the backup log and the command you ran. If this is an `incr` backup then it won't work if made from a 2.52 `diff/incr` since the issue is in the existing manifest. You'll need to run a new `diff` or `full` before an `incr` will work.

**Comment by threenotrump** [comment]
Hi @dwsteele 

You are right as usual. After taking a diff backup with 2.52.1 version errors are cleared. Thank you .

**Comment by dwsteele** [comment]
> You are right as usual.

You are kind but not sure that is true! :)

> After taking a diff backup with 2.52.1 version errors are cleared.

Glad to hear it -- you had me a bit worried there. But after a cup of coffee I realized what it probably was.
