### ISSUE TITLE
gcs module with private endpoint 

### ISSUE THREAD

**Issue by svsteam** [pgbackrest/pgbackrest#2392]
pgBackRest version: 2.52

we tried the gcs backend with a service account (json) file. it worked BUT it tried to get the token by looking up the host 
oauth2.googleapis.com. But wee need to use a private endpoint (which we have configured). when adding a line in the /etc/hosts file that point oauth2.googleapis.com to the private endpoint  then it works. 

What it should do: if a private endpoint is configured it should use that private endpoint also for getting the token from the service account key file and not try the public IP. So it should us what is configured in the gcs-endpoint= option.

**Comment by dwsteele** [comment]
You should set `token_uri` in the service file. That's where we get the endpoint from, see: https://github.com/pgbackrest/pgbackrest/blob/release/2.52.1/src/storage/gcs/storage.c#L1219.

**Comment by svsteam** [comment]
thank you! this should solve the issue..
