### ISSUE TITLE
Containers backup setup

### ISSUE THREAD

**Issue by ggefgreh** [pgbackrest/pgbackrest#2393]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.45

2. PostgreSQL version: 14.12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
database: **altered** official 14.12 postgres version
repository: **custom** image from **debian bookworm**

my host on which I am testing: **Ubuntu 22.04.4 LTS** in **wsl2** under windows 10 (specific version is probably irrelevant)

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[pgbackrest.conf.txt](https://github.com/user-attachments/files/16113581/pgbackrest.conf.txt)
[postgres-pgabckrest.conf.txt](https://github.com/user-attachments/files/16113588/postgres-pgabckrest.conf.txt)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_command = 'pgbackrest --stanza=stanzaTestowa archive-push %p'
archive_mode = on
listen_addresses = '*'
max_wal_senders = 5
wal_level = replica
port = 5432
    - errors in the postgresql log file before or during the time you experienced the issue
There is no ERROR specifically, only LOGS and Debug information.
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
[stanzaTestowa-backup.log](https://github.com/user-attachments/files/16113568/stanzaTestowa-backup.log)

7. Describe the issue:
I am new to postgres and pgbackrest and I am not sure if this is related more to pgbackrest or postgresql, but...
## About the setup
I am trying to set up separate containers for postgresql and pgbackrest (so I belive it is called dedicated host repository). 
Currently I am testing it on same host and since I didn't found good enough reason to use preconfigured pgbackrest docker image, I am building my own for pgbackrest and postgres as well (altering official one, to install `openssh`, `pgbackrest` and `nano`). Also I built up the shell script to always build images,create containers and exchange ssh keys, because I had problems with trigerring some actions on startup and exchange them as in docs.

## Issue itself
When I am trying to `check` stanza, after creating one, I am getting timeout, but it works if I first check it from database host -> then on repo host it gives no output whatsoever (or success showing logs). I belive docker-compose might be usefull.
[docker-compose.yaml.txt](https://github.com/user-attachments/files/16113591/docker-compose.yaml.txt)
But when trying to backup I am getting error (attached as [stanzaTestowa-backup.log](https://github.com/user-attachments/files/16113568/stanzaTestowa-backup.log))

**Comment by dwsteele** [comment]
You should have a look at (or just use) an established solution like Crunchy Containers. Our project has no particular experience in this area and since it is not a pgBackRest issue I'm going to close it. You could also try the #pgbackrest channel on PostgreSQL Slack.
