### ISSUE TITLE
Azure Storage Account Permissions (Best Practice/Security)

### ISSUE THREAD

**Issue by tferfce** [pgbackrest/pgbackrest#2394]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.42

2. PostgreSQL version: 13.9

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Docker image - timescale/timescaledb-ha:pg13.9-ts2.8.1-p3

5. Did you install pgBackRest from source or from a package?
Already installed on image.

7. Please attach the following as applicable: Non applicable
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

8. Describe the issue:

Mostly it is a general question regarding access on Azure Storage Account. It came to our attention that in order to use pgbackrest we need to have a SAS token with: Read, Write, List, Delete, Create. The question is whether there is way to avoid delete permission and what actions does the delete action do on pgbackrest. From traces i noticed these logs:

```
ERROR: [039]: HTTP request failed with 403 (This request is not authorized to perform this operation using this permission.):
       *** Path/Query ***:
       DELETE /pgbackups/postgres/repo1/backup/postgres/latest?se=2024-07-08T21%3A08%3A26Z&sig=<redacted>&sp=rcwl&spr=https&sr=c&st=2024-07-08T13%3A08%3A26Z&sv=2022-11-02
       *** Request Headers ***:
       content-length: 0
       host: pgtempback.blob.core.windows.net
       *** Response Headers ***:
       content-length: 279
       content-type: application/xml
       date: Mon, 08 Jul 2024 13:24:40 GMT
       server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
       x-ms-error-code: AuthorizationPermissionMismatch
       x-ms-request-id: 71c0dbcc-f01e-004b-093a-d1db0a000000
       x-ms-version: 2022-11-02
       *** Response Content ***:
       ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
       RequestId:71c0dbcc-f01e-004b-093a-d1db0a000000
       Time:2024-07-08T13:24:41.3580470Z</Message></Error>
2024-07-08 13:24:40.771 P00 DETAIL: statistics: {"http.client":{"total":2},"http.request":{"total":32},"http.session":{"total":2},"socket.client":{"total":2},"socket.session":{"total":2},"tls.client":{"total":2},"tls.session":{"total":2}}
2024-07-08 13:24:40.771 P00   INFO: backup command end: aborted with exception [039]
2024-07-08 13:24:40.771 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)
2024-07-08 13:24:40.772 P00  DEBUG:     common/lock::lockRelease: => true
2024-07-08 13:24:40.772 P00  DEBUG:     command/exit::exitSafe: => 39
2024-07-08 13:24:40.772 P00  DEBUG:     main::main: => 39
```

And also with trace logs:
```
DELETE, path: /pgbackups/postgres/repo1/backup/postgres/20240708-132953F/bundle/1
```

**Comment by dwsteele** [comment]
> The question is whether there is way to avoid delete permission and what actions does the delete action do on pgbackrest.

Delete is required for expiration, which is what you see here:
```
DELETE, path: /pgbackups/postgres/repo1/backup/postgres/20240708-132953F/bundle/1
```
It's possible that we could do without this delete (which is more for Posix file systems):
```
DELETE /pgbackups/postgres/repo1/backup/postgres/latest
```
But in general pgBackRest does not work correctly without deleted privileges so there doesn't seem to be much point.

The general answer is to enable versioning so older versions of a file are not removed, but in order for that to be truly useful to pgBackRest we'd need to be able to look at versions at a point in time, which is not currently supported.
