### ISSUE TITLE
[Question] restore single db PITR, in a cluster that have many databases

### ISSUE THREAD

**Issue by Vox1984** [pgbackrest/pgbackrest#2396]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.50
2. PostgreSQL version:
14
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Debian 11
4. Did you install pgBackRest from source or from a package?
package

7. Describe the issue:
I have similar issue to this one from 2020:
https://github.com/pgbackrest/pgbackrest/issues/1157

Has anything has changed? Do I need to go intermediate machine path, or can I just use `--db-include` option?

I want to restore single corrupted database in a production cluster that have 17 other databases **that should not be changed.**

How to do it with pgbackrest?
Would this command work as expected?

` pgbackrest --config=/etc/pgbackrest/pgbackrest.conf --log-level-console=info --stanza=demo  --db-include=percona --type=time "--target=2022-11-04 14:24:31" restore`

**Comment by pgstef** [comment]
Hi,

That's a PG limitation, PITR can't be applied to only 1 database or table. When restoring a physical backup, you need to restore everything first, then extract the db you want from that restored cluster (possibly on another server) using pg_dump and then import it in your production cluster with pg_restore.

The `--db-include` option should let you save some disk-space/restore time when restoring that temporary cluster in another location, by tricking PG : restore the other dbs as empty files, so PG can try to perform its recovery but those emptied dbs will be unavailable/broken after the restore.

Kind Regards

**Comment by Vox1984** [comment]
Hi pgstef, thanks for prompt reply.

What if I drop PITR requirement and want to restore only to the time of the full backup for that single db?

I took full backup last night. Would using `--type=immediate` change anything in my scenario?

**Comment by pgstef** [comment]
> What if I drop PITR requirement and want to restore only to the time of the full backup for that single db?

You can't rewind only one part of the cluster. That's a PG limitation. Physical backups are for the entire cluster, so the entire cluster has to be restored up to the same point.

See https://www.postgresql.org/docs/current/backup-file.html for some of the limitations of physical backups:
> file system backups only work for complete backup and restoration of an entire database cluster.

**Comment by Vox1984** [comment]
For anyone else reading this:

I tried restoring the cluster on intermediate machine, with `--db-include` option. Unfortunately that results with being unable to use `pg_dump` due to errors.

I have restored the whole cluster without the option above, and then `pg_dump` finally worked.
Then I have applied dump.sql file on the prod db.

Please close my question.
