### ISSUE TITLE
issue 237 revisited

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#240]
Can you reopen that issue?  We are able to use pg_basebackup to setup the slave without the offending WAL message in the slave's log file.  So something is different between setting up the slave with pgbackrest vs the normal way with pg_basebackup.

**Comment by MichaelDBA** [comment]
I found the problem, the error message is a slave trying to get this wal from this slave

**Comment by dwsteele** [comment]
I'm glad you figured it out, but please note that this is not a general support channel.

If you have a verifiable bug then I'm always happy to look at it, but I usually don't have time to diagnose general PostgreSQL configuration issues, which this clearly was.

**Comment by MichaelDBA** [comment]
Hi Daniel, yeah I hear ya,  been pressed for getting pgbackrest in prod, so I kinda pushed the "help me daniel" button too often recently.

But there are those times when a problem is not so easily identifiable as pgbackrest vs other stuff, so there still may be times, hopefully very infrequently, when your help to rule out a pgbackrest bug is still needed.

**Comment by dwsteele** [comment]
It's not my responsibility to help you rule out a bug, the onus is on you to show one exists.  This is not a support channel.

Also, my name is David.

**Comment by MichaelDBA** [comment]
Hi David!

First off, sorry for calling you by the wrong name, we have some daniels here and somewhere along the line I made this mental mistake. I think Hillary Clinton refers to it as a brain "short-circuit".  Also, I take your point regarding bugs and the onus on me to prove it.

You are doing a great job with not just maintaining pgbackrest, but being so responsive to issues.  I do appreciate that!
