### ISSUE TITLE
ERROR :  backup command end: aborted with exception 

### ISSUE THREAD

**Issue by BabaTataKaka** [pgbackrest/pgbackrest#2400]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

3.52.1

4. PostgreSQL version:
16.3

5. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 22.04.4 LTS

6. Did you install pgBackRest from source or from a package?
  package

8. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    
**pgbackrest.conf** 
```
[global]

log-level-file=detail

log-path=/var/log/pgbackrest

repo1-type=posix

repo1-path=/var/lib/pgbackrest

repo1-retention-full=4

repo1-retention-archive=4

start-fast=y

stop-auto=y

resume=n

link-all=y

spool-path=/var/spool/pgbackrest

archive-async=y

archive-get-queue-max=1GiB



[postgres-cluster]

process-max=4

log-level-console=info

recovery-option=recovery_target_action=promote

pg1-socket-path=/var/run/postgresql

pg1-path=/var/lib/postgresql/16/main
```

**postgresql.conf**
```

archive_command = 'pgbackrest --stanza=postgres-cluster archive-push %p'

archive_mode = 'True'

archive_timeout = '1800s'

listen_addresses = 'pg-2.server.ta,127.0.0.1'

max_wal_senders = '10'

port = '5432'

wal_level = 'logical'

# recovery.conf

primary_conninfo = 'user=replicator host=pg-1.server.ta port=5432 sslmode=verify-full sslcert=/etc/postgresql/certs/tls.crt sslkey=/etc/postgresql/certs/pkc8.key sslrootcert=/etc/ssl/certs/ca-certificates.crt application_name=svr117 gssencmode=prefer channel_binding=prefer'

primary_slot_name = 'svr117'
```

**posgres.log**
[postgres.log](https://github.com/user-attachments/files/16256207/postgres.log)

9. Describe the issue:

I'm deploying a postgres cluster using patroni. There is 2 replicas and 1 master. When running the backup(cronjob) on the replica if fail with the following error(no other error/warning in pgbackrest backup log) and no backup is created:

```
2024-07-16 19:22:01.441 P00   INFO: backup command begin 2.52.1: --exec-id=72272-554fc3d9 --log-level-console=info --log-level-file=detail --log-path=/var/log/pgbackrest --pg1-path=/var/lib/postgresql/16/main --pg1-socket-path=/var/run/postgresql --process-max=4 --repo1-path=/var/lib/pgbackrest --repo1-retention-archive=4 --repo1-retention-full=4 --repo1-type=posix --no-resume --stanza=postgres-cluster --start-fast --stop-auto --type=full

2024-07-16 19:22:02.060 P00  ERROR: [056]: unable to find primary cluster - cannot proceed

                                    HINT: are all available clusters in recovery?

2024-07-16 19:22:02.060 P00   INFO: backup command end: aborted with exception [056]
```

The backup is only successful on the master server. I don't think its a connection problem because a get a successful connection entry in the postgres logs:

```
`2024-07-16 19:22:01 UTC [72273-1] [local] [unknown]@[unknown] LOG:  connection received: host=[local]

2024-07-16 19:22:01 UTC [72273-2] [local] postgres@postgres LOG:  connection authorized: user=postgres database=postgres
`

```
Not sure what the issue is. Thanks for your help.

**Comment by pgstef** [comment]
Hi,

Have you read this https://pgbackrest.org/user-guide.html#standby-backup?
To be able to take a backup from a standby, you need to define both standby and primary in the configuration (pg1*, pg2*).

Kind Regards,

**Comment by BabaTataKaka** [comment]
> Hi,
> 
> Have you read this https://pgbackrest.org/user-guide.html#standby-backup? To be able to take a backup from a standby, you need to define both standby and primary in the configuration (pg1*, pg2*).
> 
> Kind Regards,

I have to admit that I'm relatively(and not a DBA) new to postgres and pgbackrest. My configs are based on the following ansible [playblook(https://github.com/vitabaks/postgresql_cluster/tree/master). I believe patroni require the master to run in standby mode(hot_standby = on). However, I don't have a dedicated standby server. The issue with the solution above is that , because of patroni, I have no guarantee which server is going to be the master(HA). Therefore that solution would require to dynamically change the pgbackrest config(pg1*, pg2*).

**Comment by pgstef** [comment]
> I believe patroni require the master to run in standby mode(hot_standby = on). 

No. Standby mode and hot_standby is the behavior for.. the standby, not the primary.

> The issue with the solution above is that , because of patroni, I have no guarantee which server is going to be the master(HA). Therefore that solution would require to dynamically change the pgbackrest config(pg1*, pg2*).

You won't have to change the configs. pgBackRest is smart enough to detect the primary and the standbies from the pg1/pg2/... list. However, the biggest challenge will be to trigger the backup on the good server (since you wouldn't want to have 2 backups running on your 2 standby servers). That's why we usually recommend to setup a repository host, aka dedicated backup server.

But feel free to ask the maintainer of your ansible script how to handle that then.

**Comment by BabaTataKaka** [comment]
> > I believe patroni require the master to run in standby mode(hot_standby = on).
> 
> No. Standby mode and hot_standby is the behavior for.. the standby, not the primary.
> 
> > The issue with the solution above is that , because of patroni, I have no guarantee which server is going to be the master(HA). Therefore that solution would require to dynamically change the pgbackrest config(pg1*, pg2*).
> 
> You won't have to change the configs. pgBackRest is smart enough to detect the primary and the standbies from the pg1/pg2/... list. However, the biggest challenge will be to trigger the backup on the good server (since you wouldn't want to have 2 backups running on your 2 standby servers). That's why we usually recommend to setup a repository host, aka dedicated backup server.
> 
> But feel free to ask the maintainer of your ansible script how to handle that then.

So I guess replicas would be the standby servers in my case?

**Comment by BabaTataKaka** [comment]
Now getting the same error but with 2 warnings:


```
2024-07-17 20:29:01.072 P00   INFO: backup command begin 2.52.1: --backup-standby --exec-id=83988-da309fc4 --log-level-console=info --log-level-file=detail --log-path=/var/log/pgbackrest --pg2-host=pg-1.server.ta --pg3-host=pg-3.server.ta --pg1-host-ca-file=/etc/postgresql/certs/tls-ca.crt --pg1-host-cert-file=/etc/postgresql/certs/tls.crt --pg1-host-key-file=/etc/postgresql/certs/pkc8.key --pg1-host-type=tls --pg1-path=/var/lib/postgresql/16/main --pg2-path=/var/lib/postgresql/16/main --pg3-path=/var/lib/postgresql/16/main --pg2-port=5432 --pg3-port=5432 --pg1-socket-path=/var/run/postgresql --process-max=4 --repo1-path=/var/lib/pgbackrest --repo1-retention-archive=4 --repo1-retention-full=4 --repo1-type=posix --no-resume --stanza=postgres-cluster --start-fast --stop-auto --type=full

2024-07-17 20:29:01.992 P00   WARN: unable to check pg2: [UnknownError] remote-0 process on 'pg-1.server.ta' terminated unexpectedly [1]

2024-07-17 20:29:02.329 P00   WARN: unable to check pg3: [UnknownError] remote-0 process on 'pg-3.server.ta' terminated unexpectedly [1]

2024-07-17 20:29:02.329 P00  ERROR: [056]: unable to find primary cluster - cannot proceed

                                    HINT: are all available clusters in recovery?
```
I only accept cert auth connection in my pg_hba file. I guess I should configure pgbackrest to auth with certs? However, if I look on pg2 and pg3 server postgres log I see no connection attempt at all. So it might be something else?

**Comment by pgstef** [comment]
> So I guess replicas would be the standby servers in my case?

Leader/replica or primary/standby are quite synonyms yes. The "replica" word comes from "connected in replication" (commonly, in streaming replication).

What you need to know is that pgBackRest only talk locally to PG using unix sockets. The backup from standby option is an hybrid backup where the backup control session will be initiated on the primary server, then the data files will be copied from the standby and the backup will then be finalized on the primary. That's why you need the 1 pgBackRest process on each node being able to talk to each other. This communication can be done through ssh or through the TLS server functionality.

Honestly, given the questions you already asked here and in the other issue, I would recommend to stick with something simple and use ssh + repository host (dedicated backup server). Taking backups from standby in an HA environment is not that easy.

Regards,

**Comment by BabaTataKaka** [comment]
Here are my new pgbackrest.conf settings:

```
[global]

backup-standby=y

log-level-file=detail

log-path=/var/log/pgbackrest

repo1-type=posix

repo1-path=/var/lib/pgbackrest

repo1-retention-full=4

repo1-retention-archive=4

start-fast=y

stop-auto=y

resume=n

link-all=y

spool-path=/var/spool/pgbackrest

archive-async=y

archive-get-queue-max=1GiB



[postgres-cluster]

process-max=4

log-level-console=info

recovery-option=recovery_target_action=promote

pg1-socket-path=/var/run/postgresql

pg1-path=/var/lib/postgresql/16/main

pg1-host-type=tls

pg1-host-cert-file=/etc/postgresql/certs/tls.crt

pg1-host-key-file=/etc/postgresql/certs/pkc8.key

pg1-host-ca-file=/etc/postgresql/certs/tls-ca.crt

pg2-host=pg-1.server.ta

pg2-port=5432

pg2-path=/var/lib/postgresql/16/main

pg3-host=pg-3.server.ta

pg3-port=5432

```



Now getting the same error but with 2 warnings:

```
2024-07-17 20:29:01.072 P00   INFO: backup command begin 2.52.1: --backup-standby --exec-id=83988-da309fc4 --log-level-console=info --log-level-file=detail --log-path=/var/log/pgbackrest --pg2-host=pg-1.server.ta --pg3-host=pg-3.server.ta --pg1-host-ca-file=/etc/postgresql/certs/tls-ca.crt --pg1-host-cert-file=/etc/postgresql/certs/tls.crt --pg1-host-key-file=/etc/postgresql/certs/pkc8.key --pg1-host-type=tls --pg1-path=/var/lib/postgresql/16/main --pg2-path=/var/lib/postgresql/16/main --pg3-path=/var/lib/postgresql/16/main --pg2-port=5432 --pg3-port=5432 --pg1-socket-path=/var/run/postgresql --process-max=4 --repo1-path=/var/lib/pgbackrest --repo1-retention-archive=4 --repo1-retention-full=4 --repo1-type=posix --no-resume --stanza=postgres-cluster --start-fast --stop-auto --type=full

2024-07-17 20:29:01.992 P00   WARN: unable to check pg2: [UnknownError] remote-0 process on 'pg-1.server.ta' terminated unexpectedly [1]

2024-07-17 20:29:02.329 P00   WARN: unable to check pg3: [UnknownError] remote-0 process on 'pg-3.server.ta' terminated unexpectedly [1]

2024-07-17 20:29:02.329 P00  ERROR: [056]: unable to find primary cluster - cannot proceed
```
I only accept cert auth connection in my pg_hba file(zero trust). I guess I should configure pgbackrest to auth with certs? However, if I look on pg2 and pg3 server postgres log I see no connection attempt at all. So it might be something else?

**Comment by pgstef** [comment]
> I only accept cert auth connection in my pg_hba file(zero trust). I guess I should configure pgbackrest to auth with certs? However, if I look on pg2 and pg3 server postgres log I see no connection attempt at all. So it might be something else?

Yes. I told you already: the communication between a backup server and the PG hosts needs to be done through ssh or through the TLS server functionality. That's nothing to do with PG direct connection using pg_hba+ssl since we use unix sockets.

All the details are here: https://pgbackrest.org/user-guide.html#repo-host
There are also lots of other examples on the web. In example, this (quite old) [blog post](https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html).

And btw, the archive-push command will only run on the PG hosts, so those settings should go on the PG host.

**Comment by BabaTataKaka** [comment]
> > I only accept cert auth connection in my pg_hba file(zero trust). I guess I should configure pgbackrest to auth with certs? However, if I look on pg2 and pg3 server postgres log I see no connection attempt at all. So it might be something else?
> 
> Yes. I told you already: the communication between a backup server and the PG hosts needs to be done through ssh or through the TLS server functionality. That's nothing to do with PG direct connection using pg_hba+ssl since we use unix sockets.
> 
> All the details are here: https://pgbackrest.org/user-guide.html#repo-host There are also lots of other examples on the web. In example, this (quite old) [blog post](https://pgstef.github.io/2020/11/21/combining_pgbackrest_dedicated_repository_host_and_streaming_replication.html).
> 
> And btw, the archive-push command will only run on the PG hosts, so those settings should go on the PG host.

Sorry, I replied to you on a un-refreshed page so I didn't see you previous reply. However, good to know that the pg_hba has nothing to do with pgbackrest. I'll investigate the alernative you presented me. If I undertand correctly, using  ssh + repository host (dedicated backup server) would mean I would not bakcup the standby(replicas) and only the master , right?

**Comment by pgstef** [comment]
> If I undertand correctly, using ssh + repository host (dedicated backup server) would mean I would not bakcup the standby(replicas) and only the master , right?

No. You would define all PG nodes in the backup server config and it would be smart enough to detect which nodes are primary or replica. And if you use `backup-standby` it would act as I mentioned earlier (backup control session on primary, data files from standby/replica).

**Comment by BabaTataKaka** [comment]
> backup-standby

Ok, after reading a little bit more on a subject I think now I understand it more. I don't think backing up from standby is requirement( we can deal with the extra slow down during backup) for us so I might simply backup from a dedicated repo server.
