### ISSUE TITLE
Run restore command as root user in docker container leaves pg_control as 'root' ownership

### ISSUE THREAD

**Issue by QixiaLu** [pgbackrest/pgbackrest#2407]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.51

2. PostgreSQL version: 16.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Debian12

4. Did you install pgBackRest from source or from a package? package

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Since 2.51 release, When I run the restore command as root user in docker container, it leaves pg_control as 'root' ownership. Is this an expected behavior? Or should we always run the restore command as postgres?

**Comment by dwsteele** [comment]
> it leaves pg_control as 'root' ownership. Is this an expected behavior?

No, this appears to be a bug introduced by e634fd85ced. Looks like here (https://github.com/pgbackrest/pgbackrest/blob/release/2.53/src/command/restore/restore.c#L2621) we need to add `.noAtomic = true`. The problem appears to be it is creating a new file rather than overwriting an existing one.

> Or should we always run the restore command as postgres?

I'd say this is a good idea in general and will probably fix your issue here. Restoring as root is unusual and may be why this bug has gone undetected.

**Comment by dwsteele** [comment]
@QixiaLu How would you like your name to appear in the release notes?

**Comment by QixiaLu** [comment]
> @QixiaLu How would you like your name to appear in the release notes?

Thanks for responding so quickly! I will need to chat with my colleagues, since they spot this issue.
Just to double check, is there an estimation about when will 2.54 be released? This will help estimate our patching planning

**Comment by dwsteele** [comment]
2.54 will be released October 28th. A fix for this bug might make it into a 2.53 patch release in Aug or Sep but I don't think this bug alone is enough to trigger a patch release since there is a fairly easy workaround, i.e. fix the permissions on pg_control.

**Comment by QixiaLu** [comment]
sure, thanks!

**Comment by QixiaLu** [comment]
> @QixiaLu How would you like your name to appear in the release notes?

Hi @dwsteele , could you put the name as Will M? thanks!

**Comment by dwsteele** [comment]
This is fixed in #2416 so closing. Feel free that give that patch a try.
