### ISSUE TITLE
ERROR: [053]: unable to list file info for path '/home/old_ws_pgbackrest/archive/my_stanza/12-1/000000010000013E': libssh2 error [-7]

### ISSUE THREAD

**Issue by maheshrana2002** [pgbackrest/pgbackrest#2408]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.52.1

2. PostgreSQL version: 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
 - Ubuntu 20.04.2 LTS

4. Did you install pgBackRest from source or from a package?
 - source installation

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    `[global]
#remote repo settings
repo2-sftp-host=sftp_host_name
repo2-sftp-host-port=sftp_port
repo2-sftp-host-user=sftp_username
repo2-sftp-host-key-hash-type=md5
repo2-sftp-private-key-file=/var/lib/postgresql/.ssh/id_rsa
repo2-sftp-public-key-file=/var/lib/postgresql/.ssh/id_rsa.pub
repo2-sftp-host-key-check-type=accept-new
repo2-type=sftp
repo2-path=/home/old_ws_pgbackrest
repo2-retention-full-type=time
repo2-retention-full=60
repo2-bundle=y
compress-level=6
log-level-console=info
start-fast=y
process-max=4

[pg_5435]
pg1-path=postgres_data_directory
pg1-port=5435
`
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    `#pgbackrest
archive_mode = on
archive_command = 'pgbackrest --stanza=pg_5435 archive-push %p`
    
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
<img width="1435" alt="Screenshot 2024-07-24 at 10 59 31 PM" src="https://github.com/user-attachments/assets/a5d470d7-9939-44f2-a6e0-e69c5dacbcd3">

7. Describe the issue:
i was not able to take the backup of my postgres database, it always goes till 100% backup and then shows me unable to list file info for path '/home/old_ws_pgbackrest/archive/my_stanza/12-1/000000010000013E': libssh2 error [-7]

**Comment by jreidthompson** [comment]
libssh2 error [-7] is #define LIBSSH2_ERROR_SOCKET_SEND               -7.  It implies that maybe your connection to the sftp server is dropping/being closed.  Can you find more information in pgbackrest or sftp server logs?  

what does pgbackrest check --stanza=pg_5435 --log-level-console=debug  return?

**Comment by MaheshRana2002** [comment]
pgbackrest check --stanza=pg_5435 --log-level-console=debug return
![image](https://github.com/user-attachments/assets/dae9be12-b390-4ced-a2f0-38f634f8b602)

**Comment by pgstef** [comment]
Something is bugging me here. Your error mentions ` '/home/old_ws_pgbackrest/archive/my_stanza/12-1/000000010000013E': libssh2 error [-7]` with `my_stanza`  as stanza name while you're using `--stanza=pg_5435` :thinking:

**Comment by MaheshRana2002** [comment]
![image](https://github.com/user-attachments/assets/bc2a0966-1459-4a20-bf69-21a29a2d6ea2) actually that my_stanza is also having the same configuartion but no worries i got the same error while uploading remote this stanza also 🥲

**Comment by MaheshRana2002** [comment]
understood your point actually we got to know that hetzner storage box allows only 10 connections simultaneously. Is there a way to enforce that in pgbackrest may be that is what causing issue

**Comment by jreidthompson** [comment]
https://pgbackrest.org/configuration.html#section-general/option-process-max .  It looks like you've got it set to 4 so I don't think that's the issue. The error I get when I set it to 12 is "unable to init libssh2_sftp session" per below

``` pgbackrest backup  --stanza=local  --log-level-file=debug --log-level-console=info --type=full
2024-07-30 23:49:16.708 P00   INFO: backup command begin 2.53dev: --buffer-size=1MiB --compress-type=lz4 --exec-id=225382-429b838c --log-level-console=info --log-level-file=debug --log-path=/tmp --pg1-path=/home/rthompso/pgsql/16/datastore --pg1-socket-path=/tmp --process-max=12 --no-repo1-bundle --repo1-path=/reposftp --repo1-retention-full=2 --repo1-sftp-host=xxxxxx.your-storagebox.de --repo1-sftp-host-key-hash-type=sha256 --repo1-sftp-host-user=xxxxx --repo1-sftp-private-key-file=/home/rthompso/.ssh/hetznerPEM --repo1-sftp-public-key-file=/home/rthompso/.ssh/hetznerPEM.pub --repo1-type=sftp --stanza=local --start-fast --type=full
2024-07-30 23:49:21.817 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2024-07-30 23:49:22.219 P00   INFO: backup start archive = 000000010000000000000016, lsn = 0/16000028
2024-07-30 23:49:22.219 P00   INFO: check archive for prior segment 000000010000000000000015
2024-07-30 23:49:31.036 P00   WARN: resumable backup 20240730-234759F of same type exists -- invalid files will be removed then the backup will resume
2024-07-30 23:51:33.854 P00  ERROR: [101]: raised from local-11 protocol: unable to init libssh2_sftp session
                                        [ServiceError] on 2 retries from 2995-18851ms: unable to init libssh2_sftp session
2024-07-30 23:51:33.854 P00   INFO: backup command end: aborted with exception [101]
```

**Comment by jreidthompson** [comment]
Change your repo1-sftp-host-port to 22 rather than 23 and see what happens

**Comment by MaheshRana2002** [comment]
but hertzner server is runnnig on port 23 it will not connect if we change the port to 22

**Comment by jreidthompson** [comment]
both 22 and 23 *should* work, the standard port is 22, hetzner repurposes port 23 ( which is normally telnet). From their documents "The Storage Box offers SFTP via the default port 22 and additionally via port 23. " They state that performance will be better via 23. 

I'm asking primarily to see if you get the same error on port 22. I cannot recall if I successfully utilized port 23 in the past, but trying today on port 23 doesn't work for me while port 22 is successful.

this is my configuration that is working for hetzner. I have the log-path and pg1-socket-path set to /tmp because i'm currently testing this with everything under my username, rather than the system postgres instance/user.  You can comment out/remove those options if you want to use this as a test template. 

```
[global]                                                                                                                            
repo1-bundle=n                                                                                                                      
start-fast=y                                                                                                                        
repo1-block=y                                                                                                                       
process-max=6                                                                                                                       
compress-type=lz4                                                                                                                   
                                                                                                                                    
[local]                                                                                                                             
pg1-socket-path=/tmp                                                                                                                
repo1-type=sftp                                                                                                                     
pg1-path=/home/rthompso/pgsql/16/datastore                                                                                          
repo1-retention-full=2                                                                                                              
repo1-path=/reposftp                                                                                                                
repo1-sftp-host=xxxxxx.your-storagebox.de                                                                                          
repo1-sftp-host-key-hash-type=sha256                                                                                                
repo1-sftp-host-user=xxxxxx                                                                                                        
repo1-sftp-private-key-file=/home/rthompso/.ssh/hetznerPEM                                                                          
repo1-sftp-public-key-file=/home/rthompso/.ssh/hetznerPEM.pub                                                                       
log-path=/tmp                                                                                                                       
start-fast=y                                                                                                                        
repo1-sftp-host-port=22                                                                                                             
repo1-sftp-host-key-check-type=accept-new
```

**Comment by MaheshRana2002** [comment]
thanks i will give that a try and let you know

**Comment by MaheshRana2002** [comment]
as soon as i change the port to 22 i got the public key authentication error and one more i cant connect to my storage box using port 22 so any help or steps i need to follow before doing the backup

**Comment by Reid-Thompson** [comment]
Post the information for the error you got on port 22

**Comment by MaheshRana2002** [comment]
![Screenshot 2024-08-06 at 1 25 22 PM](https://github.com/user-attachments/assets/e9281a8c-a37a-41e6-ac04-73475ab397c5)
connection is successfull if i change the port to 23

**Comment by Reid-Thompson** [comment]
What does ssh-keygen -lf /var/lib/postgresql/.ssh/id_rsa  return?
There is a minimum bits value that has to be met. Not meeting the minimum is one of the cases that will cause the above error  #define LIBSSH2_ERROR_PUBLICKEY_UNVERIFIED      -19

**Comment by Reid-Thompson** [comment]
I did some tests, I think you can ignore the comment above about the minimum bits value. I can successfully connect to 22 with a 1024 bit rsa key after I've installed the public key via the command from the above link ala their example
```
server> cat ~/.ssh/id_rsa.pub | ssh -p23 uXXXXX@uXXXXX.your-storagebox.de install-ssh-key
uXXXXX@uXXXXX.your-storagebox.de's password:
Key No. 1 (ssh-rsa user@host) was installed in RFC4716 format
Key No. 1 (ssh-rsa user@host) was installed in OpenSSH format```

**Comment by MaheshRana2002** [comment]
> also -- did you upload your public key for both ports using the instructions here https://docs.hetzner.com/robot/storage-box/backup-space-ssh-keys

I have uploaded both the keys following the doc and i was able to sftp to hertzner server through port 22 also

**Comment by MaheshRana2002** [comment]
![Screenshot 2024-08-07 at 11 49 09 AM](https://github.com/user-attachments/assets/fb2ed9c1-304c-4147-ba44-5d211575e327)
But now i'm getting this error

**Comment by jreidthompson** [comment]
The first thing that I would try is to start from a clean repo environment. I.E. the above indicates that prior attempts (on port 23?) had had some success. I would try to start with a clean slate for port 22.  Does the path /home/old* exist?  can you remove or rename it so that stanza-create on port 22 can create the repo paths/files?

sftp error [4] is a generic sftp failure #define LIBSSH2_FX_FAILURE                  4UL  It doesn't provide any specific information.
