### ISSUE TITLE
QUESTION: ubuntu 22.04 pgbackrest package

### ISSUE THREAD

**Issue by BabaTataKaka** [pgbackrest/pgbackrest#2409]
Trying to install the latest version(or any recent version) of pgbackrest on ubuntu 22.0.4. Looks like the only option is to compile from source which i would like to avoid. However and based on some research I made,  looks like some users were able to install version 2.52.1 from packages on ubuntu 22.0.4. I find it weird because the only version available is 2.37(https://packages.ubuntu.com/jammy/pgbackrest)

So, it there something I'm missing? Where can I find a copy of 2.52.1 package if its not on the ubuntu repo?

Thanks

**Comment by dwsteele** [comment]
You can find instructions for getting more recent packages at https://wiki.postgresql.org/wiki/Apt.

**Comment by BabaTataKaka** [comment]
Not sure I understand. The link you provided is for the postgres repo.

**Comment by BabaTataKaka** [comment]
> You can find instructions for getting more recent packages at https://wiki.postgresql.org/wiki/Apt.

Not sure I understand. The link you provided is for the postgres repo.

**Comment by BabaTataKaka** [comment]
Ok, I think the issue is your nexus proxy repo. If I try to install from my local machine(no proxy) it actually install version 2.52.1.

**Comment by pgstef** [comment]
> > You can find instructions for getting more recent packages at https://wiki.postgresql.org/wiki/Apt.
> 
> Not sure I understand. The link you provided is for the postgres repo.
> 

We're not providing the packages ourselves. Just as a lot of other tools, we're relying on the Postgres community packagers who are maintaining the PGDG apt and yum repositories. Those repo doesn't only contain postgres binaries but a lot of other tools too. 
You should rely on those repositories.

If we don't have a FAQ entry about it yet, it might be worth adding one.

**Comment by dwsteele** [comment]
> If we don't have a FAQ entry about it yet, it might be worth adding one.

This is documented in the user guide: https://pgbackrest.org/user-guide.html#installation
