### ISSUE TITLE
Request for consistent semantic version number and server_version_num equivalent

### ISSUE THREAD

**Issue by keithf4** [pgbackrest/pgbackrest#2410]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.52.1, 2.53

2. PostgreSQL version: N/A

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: N/A

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable: N/A

7. Describe the issue:

In pgMonitor we have a metric for the pgBackRest version just in case that was something people wanted to monitor for (watching for one system to upgrade while others didn't and breaking things). With version 2.52.1 that broke because previously all version numbers had been ##.## and easily converted to a float. With an actual 3 digit semantic version, that doesn't work, but that can, and will, be fixed on pgMonitor's end.

However, I see that version 2.53 went back to a 2 digit version. If semantic versioning is going to be used, can it stay consistent with the 3 version number? Ex. 2.53.0. It appears version 2 kept with the two digit version at that time. Ex. 2.00

As an added bonus, maybe also add something like the equivalent of the `server_version_num` in core postgres that always gives back an integer value for the version. This is what we plan to do in pgMonitor to handle things going forward, but a value in the json output like this would be great.

```
postgres=# SELECT (split_part('2.52.1', '.', 1) || lpad(split_part('2.52.1', '.', 2), 2, '0') || lpad(coalesce(nullif(split_part('2.52.1', '.', 3), ''), '00'), 2, '0'))::int AS backrest_repo_version;
-[ RECORD 1 ]---------+------
backrest_repo_version | 25201

postgres=# SELECT (split_part('2.53', '.', 1) || lpad(split_part('2.53', '.', 2), 2, '0') || lpad(coalesce(nullif(split_part('2.53', '.', 3), ''), '00'), 2, '0'))::int AS backrest_repo_version;
-[ RECORD 1 ]---------+------
backrest_repo_version | 25300

postgres=# SELECT (split_part('3.0', '.', 1) || lpad(split_part('3.0', '.', 2), 2, '0') || lpad(coalesce(nullif(split_part('3.0', '.', 3), ''), '00'), 2, '0'))::int AS backrest_repo_version;
-[ RECORD 1 ]---------+------
backrest_repo_version | 30000

postgres=# SELECT (split_part('3.00', '.', 1) || lpad(split_part('3.00', '.', 2), 2, '0') || lpad(coalesce(nullif(split_part('3.00', '.', 3), ''), '00'), 2, '0'))::int AS backrest_repo_version;
-[ RECORD 1 ]---------+------
backrest_repo_version | 30000
```

**Comment by dwsteele** [comment]
> However, I see that version 2.53 went back to a 2 digit version

Yes, this was a mistake on our part. We'll make sure that 2.54.0 gets the patch version.

> As an added bonus, maybe also add something like the equivalent of the server_version_num

This sounds like a good idea but we don't currently have plans to implement it. You are welcome to submit a PR if you like.

**Comment by dwsteele** [comment]
@keithf4 @pgstef has added version-num to the info and version output, see #2526. This works pretty well for the version command but is a little awkward for info output since we don't have a global section of the JSON to put the version in so it gets added to each stanza, which is as top-level as we can get. Thoughts?
