### ISSUE TITLE
[documentation] file bundles cannot be resumed?

### ISSUE THREAD

**Issue by atsaloli** [pgbackrest/pgbackrest#2412]
Hello! I'm just going through the User Guide for the first time.  BTW, the documentation is very polished, it's a pleasure to read such a professional product.

Quick question, the user guide says "Lastly, file bundles cannot be resumed, so be careful not to set repo-bundle-size too high."

Is the word "resumed" used intentionally or is there some typo?  To resume doing something means to start doing it again after a pause or interruption, that does not seem to fit here?  Or am I missing something?

Thanks again for such a great product!

**Comment by atsaloli** [comment]
Okay, I figured this out.  Hitting `repo-bundle-size` can interrupt file bundle creation.

**Comment by dwsteele** [comment]
> the documentation is very polished, it's a pleasure to read such a professional product.

Thank you!

> Lastly, file bundles cannot be resumed, so be careful not to set repo-bundle-size too high

This refers to resuming a backup after is has failed (for whatever reason). See https://pgbackrest.org/configuration.html#section-backup/option-resume.

**Comment by atsaloli** [comment]
Love it! Thank you, sir!
