### ISSUE TITLE
Ubuntu package puts config file in /etc/pgbackrest.conf instead of in /etc/pgbackrest/pgbackrest.conf

### ISSUE THREAD

**Issue by atsaloli** [pgbackrest/pgbackrest#2415]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.52.1

2. PostgreSQL version: N/A

3. Operating system/version: Ubuntu 20.04 and 24.04

4. Did you install pgBackRest from source or from a package?  From package

5. Please attach the following as applicable:  N/A

7. Describe the issue:  The user guide says the default config file location changed in version 2.02 from /etc/pgbackrest.conf to /etc/pgbackrest/pgbackrest.conf.  Is there a reason the package installs the config file in /etc/pgbackrest.conf still? 

```
root@a14241ef425f:/# ls -lh /etc/pgbackrest.conf
-rw-r----- 1 postgres postgres 165 Jun 25 03:17 /etc/pgbackrest.conf
root@a14241ef425f:/# ls -lh /etc/pgbackrest/
ls: cannot access '/etc/pgbackrest/': No such file or directory
root@a14241ef425f:/# pgbackrest --version
pgBackRest 2.52.1
root@a14241ef425f:/# cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
...
```

On a related note, is there a reason the package doesn't provide the `pgbackrest` user?  Why is the config file is owned by the user `postgres`?

```
root@a14241ef425f:/# ls -lh /etc/pgbackrest
ls: cannot access '/etc/pgbackrest': No such file or directory
root@a14241ef425f:/# ls -lh /etc/pgbackrest.conf
-rw-r----- 1 postgres postgres 165 Jun 25 03:17 /etc/pgbackrest.conf
root@a14241ef425f:/# grep pgbackrest /etc/passwd
root@a14241ef425f:/# grep postgres /etc/passwd
postgres:x:101:103:PostgreSQL administrator,,,:/var/lib/postgresql:/bin/bash
root@a14241ef425f:/#
```

Thanks!

**Comment by dwsteele** [comment]
> Is there a reason the package installs the config file in /etc/pgbackrest.conf still?

Apparently this is something that is hard to update in the Debian package. We don't have any control over packaging so not much we can do about it.

> is there a reason the package doesn't provide the pgbackrest user?

A pgbackrest user is most appropriate on a separate repo host and the package does not take that into account (by possibly asking the question). Again, not something we control.

**Comment by atsaloli** [comment]
> Apparently [the config file location] is something that is hard to update in the Debian package.

Is that because of Debian packaging conventions?  Or why is it hard to update?  

Thanks for being so responsive!

**Comment by pgstef** [comment]
> Is that because of Debian packaging conventions? Or why is it hard to update?

As David mentioned, we're not the ones maintaining the packages: the PGDG packagers do.

**Comment by atsaloli** [comment]
Ah! I get it now. Thank you!  :)

All my questions have been answered.
