### ISSUE TITLE
Remove restore_* and recovery_* configuration options after recovery

### ISSUE THREAD

**Issue by david-szabo97** [pgbackrest/pgbackrest#2417]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.50

2. PostgreSQL version:
16

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 24.04 LTS

5. Did you install pgBackRest from source or from a package?
apt

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
```
restore_command = 'pgbackrest --stanza=main archive-get %f "%p"'
recovery_target = 'immediate'
recovery_target_action = 'promote'
```

7. Describe the issue:
`pgbackrest` adds a couple of configuration options to the `postgresql.auto.conf`. Are we supposed to remove these options manually from the config file after the recovery finished successfully?

I have a primary and a standby server. I restored to a full backup with immediate, promote options. After the restore, I deleted the data directory of the standby server and used `pg_basebackup` to initialize the standby server. After starting the standby server it started the recovery process, because `pg_basebackup` copied over the `postgresql.auto.conf` file from the primary to the standby server. For some reason, the standby server became a primary and now I have two primaries in the cluster.
After I figured out that the recover_* and restore_* options in the auto.conf cause the issues, I removed them from the primary and redid everything, and now everything works as expected.

This might be out-of-scope for `pgbackrest`, but I was expecting this tool to remove the configuration options after a successful recovery. Although it makes sense to leave such critical processes to the user to finalize.

Are we supposed to remove these options manually from the config file after the recovery finished successfully?

**Comment by dwsteele** [comment]
> This might be out-of-scope for pgbackrest, but I was expecting this tool to remove the configuration options after a successful recovery

This would be very complicated and unpredictable since pgbackrest does not do recovery. At what point should pgbackrest jump in and start removing settings? How does it get executed to do so -- some sort of watchdog process?

Postgres used to remove these settings itself after recovery (by renaming recovery.conf) but that functionality was lost in v12 in order to make primary_conninfo reloadable.

In general pgbackrest will manage these settings for you, but if you combine a tool that does manage the settings (pgbackrest) with one that does not (pg_basebackup) then you'll need to do your own cleanup.

But why use pg_basebackup to build a standby if you already have pgbackrest?

**Comment by david-szabo97** [comment]
Thanks @dwsteele  for the quick response!

Sorry for my lack of experience here. Just jumped into PostgreSQL and I barely find any resources online. I found some resources where they mentioned `recovery.conf`, which confused me a lot since it's not relevant in the current version of PG.

`recovery_end_command` could be a way to remove these settings maybe? I'm not sure, just speculating.

> In general pgbackrest will manage these settings for you, but if you combine a tool that does manage the settings (pgbackrest) with one that does not (pg_basebackup) then you'll need to do your own cleanup.

You are right. Just tested a restore with `--type=standby` and it correctly comments out the recovery options:
```
# Recovery settings generated by pgBackRest restore on 2024-08-01 12:39:24
restore_command = 'pgbackrest --stanza=main archive-get %f "%p"'
# Removed by pgBackRest restore on 2024-08-01 12:48:35 # recovery_target = 'immediate'
# Removed by pgBackRest restore on 2024-08-01 12:48:35 # recovery_target_timeline = 'current'
```

I used `pg_basebackup` because it automatically adds the primary_conninfo and the standby.signal. But after all I can also use `recovery-option` to configure it.

> But why use pg_basebackup to build a standby if you already have pgbackrest?

I couldn't build a standby with `pgbackrest` because I couldn't do a backup from a standby. But I realized I can do the initial backup without the standby using the `--backup-standby=n` flag when I run the command on the standby.

Can you please confirm this restore process is correct? Let's assume I want to go back 1 hour, current time is 2024-08-01 14:00:00
(primary = postgresql primary server, standby = postgresql hot standby server + pgbackrest repository)
1. Create full backup day 1
2. Create full back up day 2
3. Let's assume we made a huge mistake on day 2 and we want to revert back to day 1
4. Stop primary, stop standby, delete primary data directory (we could use delta restore too I guess?)
5. Restore primary using `--type=immediate --target-action=promote --set=SET_DAY_1`
6. Start primary, wait until promote
7. Take a backup of the primary `--backup-standby=n --type=full backup` (Since the primary is now on a new timeline, I guess we can't just restore SET_DAY_1 on standby)
8. Restore standby from the last backup `--type=standby restore` (Do we need to specify the set here? It will take the last backup as far as I know so it can be omitted)
9. Start standby

> This would be very complicated and unpredictable since pgbackrest does not do recovery. At what point should pgbackrest jump in and start removing settings? How does it get executed to do so -- some sort of watchdog process?

After writing all this up, I realized this is not necessary if pgbackrest is used to restore the standby. I ran into issues because the `pg_basebackup` copied over the exact same `postgresql.auto.conf` which contained the recovery options. A standby always run the recovery process, therefore it goes on a different timeline.

**Comment by pgstef** [comment]
> Sorry for my lack of experience here. Just jumped into PostgreSQL and I barely find any resources online.

That's very weird. There a tons of material both online and in books! There are even webinars and online meetups done regularly. But I guess it depends on what you're looking for. The PG documentation itself is a great starting point imo.

> Can you please confirm this restore process is correct? Let's assume I want to go back 1 hour, current time is 2024-08-01 14:00:00 (primary = postgresql primary server, standby = postgresql hot standby server + pgbackrest repository)

Have a look at https://www.postgresql.org/docs/current/continuous-archiving.html
It's pretty easy to achieve PITR when you understand that the cluster activity between the backups are stored in the WAL archives.

>     3. Let's assume we made a huge mistake on day 2 and we want to revert back to day 1

Did that mistake occurred before or after the day 2 backup?

>     5. Restore primary using `--type=immediate --target-action=promote --set=SET_DAY_1`

You don't specifically have to use `type=immediate`, you can use PITR and chose your recovery target (time, xid, restore point,...). If the error occurred after the day 2 backup, you could restore that backup and still use PITR. Thanks to WAL archives, you can recover more data. And you can reach the same target with any backup (made before the target); the difference will be in the number of WAL activity to replay and impact the recovery duration.

>     Since the primary is now on a new timeline, I guess we can't just restore SET_DAY_1 on standby

You could re-use the same backup and set PG `recovery_target_timeline` to latest so during WAL replay, the recovery would switch to the new timeline at the location it was generated by your recovered primary. That's the magic of WAL files and timelines...

But generally speaking, it's a good practice to take a new backup of the recovered cluster anyway, so using that to `restore --delta` should be faster indeed.

**Comment by david-szabo97** [comment]
> That's very weird. There are tons of material both online and in books! There are even webinars and online meetups done regularly. But I guess it depends on what you're looking for. The PG documentation itself is a great starting point imo.

Yeah, sorry, that was an exaggeration from my side. My issue was I couldn't find any resources on what to do with the recovery_target and other recovery configuration options after a restore. But after all, using pg_basebackup together with pgbackrest that lead me into a very deep rabbit hole. So it wasn't an issue at all just a mistake from my side, that's why about zero resources on the topic.

> You could re-use the same backup and set PG recovery_target_timeline to latest so during WAL replay, the recovery would switch to the new timeline at the location it was generated by your recovered primary. That's the magic of WAL files and timelines...

That's nice to know, thank you!

> Did that mistake occurred before or after the day 2 backup?

After day 2 backup. When I first tried to restore a full backup, it still replayed all the WAL archives, so I was basically back to the point where I was before the restore. This is helpful in case of a disaster, but it's not when you want to "revert" the database to a previous snapshot. As far as I understand, that's where `type=immediate` or the other target options are helpful. You can pick the point you want to go back to.

**Comment by pgstef** [comment]
> After day 2 backup. When I first tried to restore a full backup, it still replayed all the WAL archives, so I was basically back to the point where I was before the restore. This is helpful in case of a disaster, but it's not when you want to "revert" the database to a previous snapshot. As far as I understand, that's where `type=immediate` or the other target options are helpful. You can pick the point you want to go back to.

Yes, but then you can apply `--type=immediate` or any recovery target and restore backup set from day 2. You don't have to go back to day 1 backup unless the mistake happened between day 1 and day 2 backups.
