### ISSUE TITLE
Different sftp repos with the same repo-path: ERROR: [032].

### ISSUE THREAD

**Issue by woblerr** [pgbackrest/pgbackrest#2418]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.53

2. PostgreSQL version: 16

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 22.04

4. Did you install pgBackRest from source or from a package? source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Hi,
If several independent sftp servers are used and specify the same `repo-path` for them, an error is returned:
```
2024-07-31 22:26:43.950 P00  ERROR: [032]: local repo1 and repo2 paths are both '/demo-repo' but must be different
```

Example pgbackrest.conf that returns an error:
```sh
[demo]
pg1-path=/var/lib/postgresql/16/main

[global]
log-level-console=warn
# repo 1
repo1-path=/demo-repo
repo1-sftp-host=sftp-1
repo1-sftp-host-port=22
repo1-sftp-host-key-hash-type=sha1
repo1-sftp-host-user=pgbackrest
repo1-sftp-private-key-file=/var/lib/postgresql/.ssh/id_rsa_sftp
repo1-sftp-public-key-file=/var/lib/postgresql/.ssh/id_rsa_sftp.pub
repo1-type=sftp
repo1-retention-full=2
repo1-retention-diff=2
# repo 2
repo2-path=/demo-repo
repo2-sftp-host=sftp-2
repo2-sftp-host-port=22
repo2-sftp-host-key-hash-type=sha256
repo2-sftp-host-user=pgbackrest
repo2-sftp-private-key-file=/var/lib/postgresql/.ssh/id_ed25519_sftp
repo2-sftp-public-key-file=/var/lib/postgresql/.ssh/id_ed25519_sftp.pub
repo2-type=sftp
repo2-retention-full=2
repo2-retention-diff=2
```

If different `repo-path` are specified for sftp repos, but one of them matches, for example, with local `repo-path` , then there is no error.
```bash
# repo 2
repo2-path=/demo-repo
repo2-sftp-host=sftp-2
repo2-sftp-host-port=22
repo2-sftp-host-key-hash-type=sha256
repo2-sftp-host-user=pgbackrest
repo2-sftp-private-key-file=/var/lib/postgresql/.ssh/id_ed25519_sftp
repo2-sftp-public-key-file=/var/lib/postgresql/.ssh/id_ed25519_sftp.pub
repo2-type=sftp
repo2-retention-full=2
repo2-retention-diff=2
# repo 3
repo3-path=/demo-repo
repo3-retention-full=2
```

**Comment by dwsteele** [comment]
Closing since PR #2421 has been opened for this issue.
