### ISSUE TITLE
  pgbackrest verify command for a single backup set

### ISSUE THREAD

**Issue by paulovcabral** [pgbackrest/pgbackrest#2419]
- pgBackRest version: **2.43**

- PostgreSQL version: **15.7**

- Operating system/version : **pgBackrest and Postgres on CentOS 7.9, repo on AWS S3 bucket**

I've been exploring some pgBackrest features and found the `pgbackrest verify` command, which would be useful for some validations on backup files in my scenario.

Assuming the issue #1032 as a motivator to this `verify` feature, I've tried to make use of it with the `--set` option. However, this command returned a verification for all backups in my repo, not only for the backup set I specified. In other words, this option made no difference in my return.

```
-bash-4.2$ pgbackrest verify --stanza=pg-pvc-pa --verbose --log-level-console=info --set=20240805-094004F
2024-08-05 09:57:11.575 P00   INFO: verify command begin 2.43: --buffer-size=4MB --exec-id=608-d5067c7e --log-level-console=info --log-level-file=detail --log-level-stderr=warn --log-path=/var/log/pgbackrest --process-max=2 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/pgbackrest --repo1-s3-bucket=database-backups --repo1-s3-endpoint=s3.amazonaws.com --repo1-s3-key-type=auto --repo1-s3-region=us-east-1 --repo1-storage-ca-file=/etc/pki/tls/certs/ca-bundle.crt --repo1-type=s3 --set=20240805-094004F --stanza=pg-pvc-pa --verbose
2024-08-05 09:58:39.996 P00   INFO: stanza: pg-pvc-pa
                                    status: ok
                                      archiveId: 15-1, total WAL checked: 203, total valid WAL: 203
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20240805-035004F, status: valid, total files checked: 1689, total valid files: 1689
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
                                      backup: 20240805-094004F, status: valid, total files checked: 1689, total valid files: 1689
                                        missing: 0, checksum invalid: 0, size invalid: 0, other: 0
2024-08-05 09:58:39.997 P00   INFO: verify command end: completed successfully (88429ms)
```

As I received no error messages, I assumed the `--set` was a valid option.

For small stanzas I see no problem in this behavior, but in some stanzas the amount of files would be extremely large and this verify command may take a lot of time to finish for the entire backup sets, specially using a S3 bucket.

Should this be the expected behavior of this option?

**Comment by dwsteele** [comment]
Yeah, set exists as an option but it doesn't show up on online or command help and if you explicitly request help it returns:
```
pgBackRest 2.54dev - 'verify' command - 'set' option help

Backup set to verify.

Verify all database and archive files associated with the specified backup set.

FOR INTERNAL USE ONLY. DO NOT USE IN PRODUCTION.
```
Emphasis on the `FOR INTERNAL USE ONLY. DO NOT USE IN PRODUCTION.`. Honestly I'm not quite sure why this is a option at all (might be something legacy), but it is pretty clearly marked as not to be used.

Of course, it would be great if verify supported this option, but we haven't gotten there yet.
