### ISSUE TITLE
pgbackrest for upgrades

### ISSUE THREAD

**Issue by jungle-boogie** [pgbackrest/pgbackrest#242]
Hi,

I'm following postgresql development builds and often build from source a few times a month. Because of how Postgres works, I haven't been able to stop/start the postgres service and have it load the data in as nothing happened. `/usr/local/pgsql/data/serverlog ` usually report something to the effect of:
`FATAL:  database files are incompatible with server`.

Can pgbackrest be used to follow postgres' development and pgbackrest to backup/restore data? 

Currently I use pg_dump and psql to restore data.

Thanks!

**Comment by sfrost** [comment]
A given set of PostgreSQL files can only be read by the PostgreSQL version which created them (in other words, if you initialize a database with PostgreSQL 9.4, then only PostgreSQL 9.4 can read those files).  pgBackRest performs a file-based backup, which means that if you use pgBackRest to back up a PostgreSQL 9.4 cluster, then when you restore those files, you have to use PostgreSQL 9.4 to read them.

PostgreSQL provides the "pg_upgrade" utility to perform upgrades of PostgreSQL from one version to another (in other words, you can use pg_upgrade to upgrade from PostgreSQL 9.4 to PostgreSQL 9.5).

The "pg_dump" utility does not perform a file-level backup, it performs a logical backup, where the data is extracted as "INSERT" commands.  Logical based backups generally allow you to migrate between PostgreSQL versions, though you should always use the "pg_dump" from the later version of PostgreSQL to back up the data from the older version, to ensure that the logical dump will restore into the later version.

**Comment by jungle-boogie** [comment]
> A given set of PostgreSQL files can only be read by the PostgreSQL version which created them

I got it. That's why I see that message in serverlog.

> PostgreSQL provides the "pg_upgrade"

I'll check that out. Thanks for the tip. Are there any plans to implement that in pgBackRest, or is that feature creep/reinventing the wheel?

**Comment by sfrost** [comment]
There are no plans to implement PostgreSQL upgrades or calling pg_upgrade into pgBackRest.
