### ISSUE TITLE
Postgres REL_17_BETA3 pgbackrest 2.53.1 ERROR: [058]: version '18'

### ISSUE THREAD

**Issue by wildhi** [pgbackrest/pgbackrest#2427]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
version: 2.53.1

2. PostgreSQL version:
psql (PostgreSQL) 18devel

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
SUSE Linux Enterprise Server 15 SP4

4. Did you install pgBackRest from source or from a package?
installed from source

5. Please attach the following as applicable:
pgbackrest.conf
`[psqlbackup]
pg1-path=/opt/postgres/data

[global]
repo1-path=/opt/postgres/backup/pgbackrest
repo1-retention-full=3
repo1-retention-diff=6
repo1-retention-history=10
link-all=y
spool-path=/var/lib/pgbackrest
process-max=2
start-fast=y
compress-type=lz4

[global:archive-push]
compress-level=3
archive-async=y

[global:archive-get]
archive-async=y

[global:restore]
delta=y`

Postgres is Listen on Port 5432

`2024-08-23 11:34:56.723 P00  ERROR: [058]: version '18' and path '/opt/postgres/data' queried from cluster do not match version '17' and '/opt/postgres/data' read from '/opt/postgres/data/global/pg_control'
                                    HINT: the pg1-path and pg1-port settings likely reference different clusters.
                                    --------------------------------------------------------------------
                                    If SUBMITTING AN ISSUE please provide the following information:

                                    version: 2.53.1
                                    command: stanza-create
                                    options: --exec-id=17591-00891f6c --log-level-console=debug --pg1-path=/opt/postgres/data --repo1-path=/opt/postgres/backup/pgbackrest --stanza=psqlbackup

                                    stack trace:
                                    command/check/common.c:checkDbConfig:69:(test build required for parameters)
                                        ... function(s) omitted ...
                                    command/stanza/create.c:cmdStanzaCreate:(void)
                                    main.c:main:(debug log level required for parameters)
                                    --------------------------------------------------------------------
2024-08-23 11:34:56.723 P00   INFO: stanza-create command end: aborted with exception [058]
2024-08-23 11:34:56.723 P00  DEBUG:     command/exit::exitSafe: => 58
2024-08-23 11:34:56.723 P00  DEBUG:     main::main: => 58`

This is upcoming from here
https://github.com/pgbackrest/pgbackrest/blob/main/src/command/check/common.c#L45

6. Describe the issue:

I Build Postgres from Source
https://github.com/postgres/postgres/tree/REL_17_BETA3
and also pgbackrest build from source with version 2.53.1 and wan´t to test the BETA version from PSQL 17

And at the Stanza Creation 
`pgbackrest --stanza=psqlbackup stanza-create --log-level-console=debug`
This error is occurred 
`ERROR: [058]: version '18' and path '/opt/postgres/data' queried from cluster do not match version '17' and '/opt/postgres/data' read from '/opt/postgres/data/global/pg_control'`

`cat data/PG_VERSION
18`

Is Only the Postgres STABLE Version is possible to use ?
[REL_17_STABLE](https://github.com/postgres/postgres/tree/REL_17_STABLE)

Thx

**Comment by pgstef** [comment]
Hi,

> cat data/PG_VERSION 18

I think you got something messed up. The current Postgres master branch is version 18. The 17beta3 should say PG_VERSION 17.

It's working fine with the beta packages/snapshots provided in the yum/apt PGDG repositories for me.

**Comment by wildhi** [comment]
Hi @pgstef 
okay, but i clone the Repo directly from github with both Tags. And both Tags gives me the PG_VERSION = 18.
Is this a Bug in postgres ?

**Comment by pgstef** [comment]
It is probably a bug in your compilation process, not in postgres. Did you make sure to checkout the good tag/branch?

If you're not familiar enough with source compilation, I would recommend to use the packages provided by the apt/yum PGDG repositories. They have beta packages too.

And if you struggle with git, just download the source from [postgresql.org](https://www.postgresql.org/ftp/source/v17beta3/).

Anyway, given your question most probably come from your PG installation process and not from pgBackRest itself, I think we could close this issue.

Regards

**Comment by wildhi** [comment]
@pgstef okay fine. Thx
