### ISSUE TITLE
pgbackrest doesn't refresh S3 tokens during execution

### ISSUE THREAD

**Issue by graveland** [pgbackrest/pgbackrest#2428]
When using an S3 repo with web-id authentication, using time-limited tokens, the token can expire in the middle of a backup or restore. It looks like the S3 configuration is populated on first-use and is never updated. When running pgbackrest in kubernetes for example, the `AWS_WEB_IDENTITY_TOKEN_FILE` contains the token information, and is automatically updated when the token is renewed.

If pgbackrest gets an authentication error, it would be good to re-read the file and retry at least once in order to handle rotated tokens. Other options could be to re-read the file periodically, or stat it when building S3 requests and re-reading it if it's changed since the last time it was read?

If this seems reasonable, we could probably come up with a PR. Possibly adding an optional StorageInterface function to re-read credentials?

**Comment by dwsteele** [comment]
> If this seems reasonable, we could probably come up with a PR. Possibly adding an optional StorageInterface function to re-read credentials?

I think it would be easier to just move this code block (https://github.com/pgbackrest/pgbackrest/blob/release/2.53.1/src/storage/s3/helper.c#L58) into this function (https://github.com/pgbackrest/pgbackrest/blob/release/2.53.1/src/storage/s3/storage.c#L380).

If you could put together a PR for that it would be very helpful.

**Comment by dwsteele** [comment]
Closing since PR #2429 has been opened.
