### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by avandras** [pgbackrest/pgbackrest#2431]
At https://github.com/pgbackrest/pgbackrest/issues/1698#issuecomment-1116950782 it was mentioned that there were plans to port to Windows.  Is there any progress on that front?

**Comment by dwsteele** [comment]
There was a GSoC project to port pgBackRest to Windows, which was unsuccessful. In the process we discovered that the port was a larger project than we had anticipated, in part due to quirks in MSVC. In the end we decided not to continue with the port.
