### ISSUE TITLE
pgbackrest stanza-create failing

### ISSUE THREAD

**Issue by alexislychine** [pgbackrest/pgbackrest#2432]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.49

2. PostgreSQL version:15.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: rhel8.10 on each server

4. Did you install pgBackRest from source or from a package? from package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Sorry for I can't attach the files. this website is blocked on my work computer
Error in the logs: DETAIL: The failed archive command was : pgbackrest --stanza=Splunk_soar_sit archive-push /data/postgresql/15/pg_wal/000000.history
I started getting this error after changing the archive command. if you attempt to remove pgbackrest, it works

While running the stanza-create command it's asking for the password, and then fail with the following error 
WARN: unable to check pg1: [UnknownError] remote-0 process on 'ip_address" terminated unexpectedly [255]: user@ip_address: Permission denied (publicly, gssapi-with-mic,password,keyboard-interactive).
Giving me the same error for pg1, pg2, pg3 and prompting me to provide the password  3 times for each pg
But the user (same user )We've used to configure pgbackrest and postgresql can ssh without password and can also remotely run psql commands.

pgbackrest.conf
repo1-path=/pgdbbackup/pgbackrest

[Splunk_soar_sit]
pg1-host=ip_address
pg1-path=/data/postgresql/15
pg1-user=my_user
pg1-port=5432
pg1-socket-path=/var/run/postgresql

pg2-host=ip_address
pg2-path=/data/postgresql/15
pg2-user=my_user
pg2-port=5432
pg2-socket-path=/var/run/postgresql

pg3-host=ip_address
pg3-path=/data/postgresql/15
pg3-user=my_user
pg3-port=5432
pg3-socket-path=/var/run/postgresql

archive_command= 'pgbackrest --stanza=Splunk_soar_sit archive-push %p'
archive_mode=on
listen_addresses=server's ip (since we use Patroni)
max_wal_senders=10
wal_level=replica
port=5432

Thanks,

**Comment by dwsteele** [comment]
It looks like you have not setup SSH correctly. See https://pgbackrest.org/user-guide.html#repo-host/setup-ssh.

**Comment by alexislychine** [comment]
Hey, David! Thanks a lot for clarifying our doubts. The issue we’re facing is that we used a specific user, which isn’t pgbackrest or postgres, to set up both PostgreSQL and pgbackrest.

**Comment by pgstef** [comment]
> The issue we’re facing is that we used a specific user, which isn’t pgbackrest or postgres, to set up both PostgreSQL and pgbackrest.

Then you should use `pg-host-user`, not `pg-user`. You mentioned that you're using a repo-host but you don't provide the configuration you use for the pg hosts, nor the user you want to use for the ssh connection etc... so it would be hard to help imo.

**Comment by alexislychine** [comment]
Thank you so much guys, it's working. It was related to the ssh not properly setup since we use a different user to manage PostgreSQL
