### ISSUE TITLE
ERROR: [058]: version '16' and path '/var/lib/postgresql/data' queried from cluster do not match version '16' and '/opt/1panel/apps/postgresql/postgresql/data' read from '/opt/1panel/apps/postgresql/postgresql/data/global/pg_control' HINT: the pg1-path and pg1-port settings likely reference different clusters.

### ISSUE THREAD

**Issue by 2598142880** [pgbackrest/pgbackrest#2440]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.53.1

2. PostgreSQL version:16.3 (Docker image: postgres:16.3-alpine)

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:Ubuntu 22.04 LTS

4. Did you install pgBackRest from source or from a package?
pgbackrest installed from [apt.postgresql.org](https://www.postgresql.org/download/linux/ubuntu/)
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
repo1-path=/www/pgbackrest
repo1-retention-full=500
process-max=4
log-level-console=info
log-level-file=debug

[podman-pg]
pg1-path=/opt/1panel/apps/postgresql/postgresql/data
pg1-port=port
pg1-host=ip
pg1-host-user=postgres
pg1-host-type=ssh

# 压缩设置
compress-type=zst
compress-level=6

# 网络设置
spool-path=/var/spool/pgbackrest
buffer-size=4194304

# 归档设置
archive-async=y
archive-push-queue-max=4GiB

# 备份设置
backup-standby=y
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
root@SYDX-BL-3F-DC-1-1-1-32:~# sudo -u postgres pgbackrest --stanza=podman-pg --log-level-console=debug check
2024-09-11 20:29:00.626 P00   INFO: check command begin 2.53.1: --backup-standby --buffer-size=4194304 --exec-id=2343813-f98845c4 --log-level-console=info --log-level-file=debug --pg1-host=ip --pg1-host-type=ssh --pg1-host-user=postgres --pg1-path=/opt/1panel/apps/postgresql/postgresql/data --pg1-port=port --repo1-path=/www/pgbackrest --stanza=podman-pg
2024-09-11 20:29:01.949 P00   WARN: option 'backup-standby' is enabled but standby is not properly configured
2024-09-11 20:29:01.958 P00  ERROR: [058]: version '16' and path '/var/lib/postgresql/data' queried from cluster do not match version '16' and '/opt/1panel/apps/postgresql/postgresql/data' read from '/opt/1panel/apps/postgresql/postgresql/data/global/pg_control'
                                    HINT: the pg1-path and pg1-port settings likely reference different clusters.
2024-09-11 20:29:01.958 P00   INFO: check command end: aborted with exception [058]

7. Describe the issue:
Here's the translation:

'/var/lib/postgresql/data' is the path inside the container, and '/opt/1panel/apps/postgresql/postgresql/data' is the path mapped from the container. However, an error is occurring:

ERROR: [058]: version '16' and path '/var/lib/postgresql/data' queried from cluster do not match version '16' and '/opt/1panel/apps/postgresql/postgresql/data' read from '/opt/1panel/apps/postgresql/postgresql/data/global/pg_control' HINT: the pg1-path and pg1-port settings likely reference different clusters.

Could you please let me know how to resolve this issue?

**Comment by pgstef** [comment]
Where are you running the `pgbackrest` command exactly? And what's the configuration of pgBackRest on the PG node?
Since you're speaking about containers, it would be interesting to give us a better overview of your infrastructure.

When using the pg-host configuration, the `pgbackrest` command will try to ssh connect to that host and run a local `pgbackrest` command over there (so in your case, inside the PG container). And in there, the local `pgbackrest` command would try to login to the database using the unix socket.

**Comment by 2598142880** [comment]
When I continue using ‘PG Back Web’, no errors occurred. Due to other tasks, I might not be able to provide effective information at the moment, and I apologize for that. However, I believe the issue is caused by my pgbackreset configuration error, and I will continue to try in my free time. Thank you very much for your help and support!

**Comment by dwsteele** [comment]
It looks like you have incorrectly configured `pg1-path` for the port you are connecting on. The cluster is reporting that is is running in `/var/lib/postgresql/data` but you have configured `/opt/1panel/apps/postgresql/postgresql/data`.

Could be that `/opt/1panel/apps/postgresql/postgresql/data` is a symlink but your should always configured pgbackrest with the real path.

**Comment by 2598142880** [comment]
> It looks like you have incorrectly configured `pg1-path` for the port you are connecting on. The cluster is reporting that is is running in `/var/lib/postgresql/data` but you have configured `/opt/1panel/apps/postgresql/postgresql/data`。看来您为要连接的端口配置了错误的`pg1-path` 。集群报告正在`/var/lib/postgresql/data`中运行，但您已配置 `/opt/1panel/apps/postgresql/postgresql/data` 。
> 
> Could be that `/opt/1panel/apps/postgresql/postgresql/data` is a symlink but your should always configured pgbackrest with the real path.可能是这样 `/opt/1panel/apps/postgresql/postgresql/data` 是一个符号链接，但您应该始终使用真实路径配置 pgbackrest。

The path /opt/1panel/apps/postgresql/postgresql/data is the absolute path on the host system, which is mapped to a path inside the Docker container.
The path /var/lib/postgresql/data is the actual path where PostgreSQL data is stored inside the Docker container.
