### ISSUE TITLE
Minor docs observation (7.0 Monitoring -> 7.1  In PostgreSQL)

### ISSUE THREAD

**Issue by udf2457** [pgbackrest/pgbackrest#2441]
Just a minor observation, in the example function, you have:

```sql
create temp table temp_pgbackrest_data (data text);
--
-- snip
--
drop table temp_pgbackrest_data;
```

This could be tidied up as follows

```sql
create temp table temp_pgbackrest_data (data text) on commit drop;
```

Per [the docs](https://www.postgresql.org/docs/current/sql-createtable.html):
> Temporary tables are automatically dropped at the end of a session, or optionally at the end of the current transaction (see ON COMMIT below)
>
> ON COMMIT
> The ON COMMIT clause for temporary tables also resembles the SQL standard, but has some differences. If the ON COMMIT clause is omitted, SQL specifies that the default behavior is ON COMMIT DELETE ROWS. However, the default behavior in PostgreSQL is ON COMMIT PRESERVE ROWS. The ON COMMIT DROP option does not exist in SQL.

**Comment by dwsteele** [comment]
Looks like this will fail if the function is called twice in the same transaction. You could add `create table ... if not exists` but then you would also need to delete the contents of the table. What we have now seems simpler overall.

Anyway, this is just a sample. The user is free to implement however they like.
