### ISSUE TITLE
feature requests - backup from hotstandy/replica without primary host

### ISSUE THREAD

**Issue by internetuser2008** [pgbackrest/pgbackrest#2443]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.53.1

2. PostgreSQL version: 16

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 22

4. Did you install pgBackRest from source or from a package? yes

5. Please attach the following as applicable:
```
    - [global]
        repo1-path=/var/lib/postgresql/pgbackrest
        repo1-retention-full=2
        repo1-retention-diff=5
        repo1-cipher-pass=xxxxxxxxxx
        repo1-cipher-type=aes-256-cbc
        start-fast=y
        process-max=2
        backup-standby=y
        
        [global:archive-push]
        compress-level=3
        
        [backup03]
        pg1-path=/var/lib/postgresql/16/main
        pg1-host=192.168.0.103 <-- hot standby
```
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
```
    - ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
```

7. Describe the issue:
    Provide ability to backup from replica/hotstandby without primary host info due to DC limitation and security.

**Comment by dwsteele** [comment]
We have considered this feature but it is not currently on the roadmap.
