### ISSUE TITLE
pgbackrest broken after disk ran full

### ISSUE THREAD

**Issue by step21** [pgbackrest/pgbackrest#2444]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.37

2. PostgreSQL version:
14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu Linux 22.04.3 LTS

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run 

7. Describe the issue:
Likely due to improper backup retention, the full backups were not expired, and the disk filled up. After freeing some other space, the database recovered, but wal-archiving and also manually running pgbackrest ist broken. Of course I don't expect any disaster recovery help, but just looking for ideas, if there is f.e. a command that can start from the last working backup state or otherwise recover, that would be awesome. Otherwise, I will likely start with a fresh backup, unless someone has a better idea.

[pgbackrest.conf.txt](https://github.com/user-attachments/files/17005651/pgbackrest.txt)
[postgres_log.txt](https://github.com/user-attachments/files/17005676/postgres_log.txt)
[postgresql.conf.txt](https://github.com/user-attachments/files/17005731/postgresql.conf.txt)
[pgbackrest_expire_log.txt](https://github.com/user-attachments/files/17005737/pgbackrest_expire_log.txt)

**Comment by dwsteele** [comment]
Looks like you have permissions issues on `/tmp/pgbackrest`:
```
ERROR: [041]: unable to get info for path/file '/tmp/pgbackrest/odoomain_backup.stop': [13] Permission denied
```
Those should be easy enough to fix. Not sure how this is related to out-of-space issues, but might be why you have them in the first place.

This one looks familiar from a while back:
```
ASSERT: [025]: option 'compress-level-network' is not valid for the current command
```
We have fixed some bugs in this area over the last couple of years but I'm not going to take the time to track down the commits. I would recommend upgrading and if you see the same issue we'll have a closer look.

It appears to me that these issues were not caused by the disk running out of space, but instead were the cause of it running out of space.

**Comment by step21** [comment]
Thanks. The disk was mostly full, and there were some other errors related to that. I thought the permission error was just misleading, as nothing was changed there.
Thanks for the pointers, will try these first and probably close the issue then.
