### ISSUE TITLE
respository backup removed - recreate directory, recreate stanza, and check fails with [82] error

### ISSUE THREAD

**Issue by seadba** [pgbackrest/pgbackrest#2447]
[pgbackrest_conf.txt](https://github.com/user-attachments/files/17048588/pgbackrest_conf.txt)
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. PgBackRest version:2.51

2. PostgreSQL version:14.1

3. Operating system/version: RH8

4. Did you install pgBackRest from source or from a package? 

5. Please attach the following as applicable:
  

7. Describe the issue:   pgbackrest repository was deleted - we recreated the directory, recreated the same stanza, and when running check we get the following 

version: 2.51

       command: check

       options: --exec-id=1718819-52214e76 --log-level-console=debug --pg1-path=/var/lib/postgresql/14/main --pg1-port=5432 --repo1-path=/var/lib/postgresql/pgbackup/pgbr --stanza=mailman

 

       stack trace:

       command/archive/find.c:walSegmentFind:191:(this: {WalSegmentFind}, walSegment: {"00000004000001BC00000095"})

       command/archive/find.c:walSegmentFindOne:(storage: {type: posix, path: /var/lib/postgresql/pgbackup/pgbr, write: false}, archiveId: {"14-1"}, walSegment: {"00000004000001BC00000095"}, timeout: 60000)

       command/check/check.c:checkPrimary:(dbGroup: {DbGetResult}, storage: {type: posix, path: /var/lib/postgresql/pgbackup/pgbr, write: false}, pgVersion: 140000, pgSystemId: 7250538707365939316, cipherType: none)

       command/check/check.c:cmdCheck:(void)

       main.c:main:(debug log level required for parameters)

       --------------------------------------------------------------------

2024-09-18 17:41:38.353 P00   INFO: check command end: aborted with exception [082]

2024-09-18 17:41:38.353 P00  DEBUG:     command/exit::exitSafe: => 82

2024-09-18 17:41:38.353 P00  DEBUG:     main::main: => 82

**Comment by seadba** [comment]
postgres=# show archive_command;

               archive_command

---------------------------------------------

pgbackrest --stanza=mailman archive-push %p


mailman-stanza-create.log

 

-------------------PROCESS START-------------------

2024-09-18 17:24:33.236 P00   INFO: stanza-create command begin 2.51: --exec-id=1706308-2aa72260 --log-level-console=info --pg1-path=/var/lib/postgresql/14/main --pg1-port=5432 --repo1-path=/var/lib/postgresql/pgbackup/pgbr --stanza=mailman

2024-09-18 17:24:33.842 P00   INFO: stanza-create for stanza 'mailman' on repo1

2024-09-18 17:24:33.873 P00   INFO: stanza-create command end: completed successfully (638ms)

**Comment by seadba** [comment]
waiting on pg log from client - will update asap thanks

**Comment by pgstef** [comment]
Hi

> INFO: check command end: aborted with exception [082]

Exception `[082]` means `ArchiveTimeoutError`.

> waiting on pg log from client - will update asap thanks

That will be necessary to help since `archive-push` output will be in the PG logs.

Regards,

**Comment by seadba** [comment]
thanks - sorry for delay
[postgresql-Wed.log](https://github.com/user-attachments/files/17059401/postgresql-Wed.log)

**Comment by seadba** [comment]
this instance was a standby that was failed over to a few weeks back -

**Comment by seadba** [comment]
ERROR: [062]: stop file exists for all stanzas

**Comment by pgstef** [comment]
> ERROR: [062]: stop file exists for all stanzas

It shouldn't have been possible to use `stanza-create` then :thinking: 

Anyway, that means you have a `all.stop` file in your lock-path.
Should be fixed if you run `pgbackrest --stanza=all start`.

**Comment by seadba** [comment]
thanks  for very fast response - i recreated the stanza with the same name - will test and update asap - thanks again

**Comment by pgstef** [comment]
> thanks for very fast response - i recreated the stanza with the same name - will test and update asap - thanks again

```bash
$ pgbackrest --stanza=ro9pg stanza-create
P00  ERROR: [062]: stop file exists for all stanzas
P00   INFO: stanza-create command end: aborted with exception [062]
```

Stanza creation should fail if you have a stop file locally...
