### ISSUE TITLE
Differential backup uses much more space than expected, wrong config?

### ISSUE THREAD

**Issue by chlordk** [pgbackrest/pgbackrest#2448]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.53.1

2. PostgreSQL version: 12.20

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: All Ubuntu 20.04.6

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

prodsyngyps100:/etc/pgbackrest.conf
[global]
repo1-host=pprodsyngyps101
repo1-host-user=pgbackrest
log-level-console=info
log-level-file=debug
delta=y

[prod]
pg1-path=/global/data/postgresql/12/main

pprodsyngyps101:/etc/pgbackrest.conf
[prod]
pg1-host=prodsyngyps100
pg1-path=/global/data/postgresql/12/main

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=1
start-fast=y

pgbackrest@pprodsyngyps101:~$ crontab -l | grep -v ^#
00 06  *   *   0     pgbackrest --stanza=prod backup --type=full
00 06  *   *   1-6   pgbackrest --stanza=prod backup --type=diff

7. Describe the issue:
This is my first pgbackrest production installation.
The plan is to make one full backup each Sunday and differential rest of the week.

The number of daily UPDATE in PostgreSQL should be very few and INSERT is about 10GBytes.

A full backup is 1116GB and the diff is 629.5GB. I would have expected to be much less than that.
Can I reconfigure something or is that it should be?
Is it better to use incremental than differential?

One thing I find strange with PostgreSQL: When I have a table which is say 2.5GB it consist of 3 files with names like:
1.0GB 22271
1.0GB 22271.1
512MB 22271.2
If the content/payload of the 22271.1 file does not change during backups, why does the md5sum change from day to day? Is there some vacuum writing to the file?

best regards

---
Extra info:

pgbackrest@pprodsyngyps101:~$ pgbackrest info --stanza=prod
stanza: prod
    status: ok (backup/expire running - 33.78% complete)
    cipher: none

    db (current)
        wal archive min/max (12): 0000000100000C480000006E/0000000100000C5400000089

        full backup: 20240917-011255F
            timestamp start/stop: 2024-09-17 01:12:55+02 / 2024-09-17 17:19:30+02
            wal start/stop: 0000000100000C480000006E / 0000000100000C4E0000001E
            database size: 1534.2GB, database backup size: 1534.2GB
            repo1: backup set size: 1116GB, backup size: 1116GB

        diff backup: 20240917-011255F_20240918-060002D
            timestamp start/stop: 2024-09-18 06:00:02+02 / 2024-09-18 15:07:40+02
            wal start/stop: 0000000100000C50000000D8 / 0000000100000C5200000048
            database size: 1544.9GB, database backup size: 975.4GB
            repo1: backup set size: 1123.4GB, backup size: 629.5GB
            backup reference list: 20240917-011255F
pgbackrest@pprodsyngyps101:~$ df -h /var/lib/pgbackrest/
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/pg-pgbackrest  2.5T  2.0T  388G  84% /var/lib/pgbackrest

 Sizes of the biggest raw databases:
postgres@prodsyngyps100:/global/data/postgresql/12/main/base$ du -sm * | sort -nr
871374  596449
528734  4896963
138407  67546647
42276   20652
130     19666
50      66553385

$ egrep '^archive_command|^archive_mode|^listen_addresses|^max_wal_senders|^wal_level|^port' /etc/postgresql/12/main/postgresql.conf
listen_addresses = '*'          # what IP address(es) to listen on;
port = 5432                             # (change requires restart)
wal_level = replica                     # minimal, replica, or logical
archive_mode = on               # enables archiving; off, on, or always
archive_command = 'pgbackrest --stanza=prod archive-push %p'
max_wal_senders = 3

**Comment by pgstef** [comment]
> A full backup is 1116GB and the diff is 629.5GB. I would have expected to be much less than that. Can I reconfigure something or is that it should be? Is it better to use incremental than differential?

Differential will always copy every changes since last full backup. So it will grow over time over the week. That's the difference with the incremental type which only copy changes since the last backup (any type).

Also, by default, those backups are file-level backups. So if 1 page change in the 1GB PG data file, it will have to copy the entire 1GB file. If you want block level backups, you need to enable [repo-block](https://pgbackrest.org/configuration.html#section-repository/option-repo-block) and use incremental backups.

> The number of daily UPDATE in PostgreSQL should be very few and INSERT is about 10GBytes.

It really depends on how those 10GB are spread over the PG data files. Nothing we can really do about it except advising to use block level incremental.

> One thing I find strange with PostgreSQL: When I have a table which is say 2.5GB it consist of 3 files with names like: 1.0GB 22271 1.0GB 22271.1 512MB 22271.2 If the content/payload of the 22271.1 file does not change during backups, why does the md5sum change from day to day? Is there some vacuum writing to the file?

That's a PG specific question, would definitely be too long to explain in a GH issue imo. I guess [PG docs](https://www.postgresql.org/docs/current/storage.html) could be a good reading starting point to learn about fill-factor, free space map,...

Kind Regards

**Comment by chlordk** [comment]
Thanks, I will try [repo-block](https://pgbackrest.org/configuration.html#section-repository/option-repo-block) + repo-bundle next week when I have a new full backup.

**Comment by chlordk** [comment]
Follow up: Incremental + repo-block + repo-bundle made the daily backup:

- run faster
- use less disk space

Thanks.

```
db (current)
        wal archive min/max (12): 0000000100000C5C00000058/0000000100000C65000000A3

        full backup: 20240922-091702F
            timestamp start/stop: 2024-09-22 09:17:02+02 / 2024-09-23 01:12:11+02
            wal start/stop: 0000000100000C5C00000058 / 0000000100000C5E00000072
            database size: 1556GB, database backup size: 1556GB
            repo1: backup size: 1131.1GB

        incr backup: 20240922-091702F_20240923-060102I
            timestamp start/stop: 2024-09-23 06:01:02+02 / 2024-09-23 06:29:44+02
            wal start/stop: 0000000100000C5E0000007B / 0000000100000C5E0000007B
            database size: 1556.8GB, database backup size: 354.9GB
            repo1: backup size: 4.5GB
            backup reference list: 20240922-091702F

        incr backup: 20240922-091702F_20240924-060102I
            timestamp start/stop: 2024-09-24 06:01:02+02 / 2024-09-24 06:58:33+02
            wal start/stop: 0000000100000C6200000052 / 0000000100000C6200000062
            database size: 1561.0GB, database backup size: 835.3GB
            repo1: backup size: 12.6GB
            backup reference list: 20240922-091702F, 20240922-091702F_20240923-060102I
```

**Comment by chlordk** [comment]
Case closed
