### ISSUE TITLE
Full backup error

### ISSUE THREAD

**Issue by gintoddic** [pgbackrest/pgbackrest#245]
2016-08-23 11:04:56.420 T00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2016-08-23 11:35:27.050 T00  ERROR: [134]: raised on datawarehouse001
[data-backup.log.txt](https://github.com/pgbackrest/pgbackrest/files/434903/data-backup.log.txt)
 host: statement timed out after 1830.058 second(s):
                                           select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), lsn::text, null as labelfile, null as spcmapfile from pg_stop_backup() as lsn
2016-08-23 11:35:27.073 T00   INFO: backup stop

**Comment by gintoddic** [comment]
Is it because of the wal archive not finishing? When would I know this completes so I can start a backup?

**Comment by dwsteele** [comment]
WAL archiving never really completes if your system is active.  I thought you increased db-timeout and protocol-timeout to allow the WAL more time to arrive?

**Comment by gintoddic** [comment]
I may have set that on backup host. Those two parameters should be set on the global stanza of the db host correct?

**Comment by dwsteele** [comment]
Those settings should be on the backup host.
