### ISSUE TITLE
Remote replica backup without SSH

### ISSUE THREAD

**Issue by duyguHsnHsn** [pgbackrest/pgbackrest#2454]
1. pgBackRest version: 2.37

2. PostgreSQL version: versions 12-16

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:

6. Describe the issue:

From https://pgstef.github.io/2020/09/04/combining_pgbackrest_and_streaming_replication.html,  it appears that performing backups from a standby/secondary server is possible. However, I would like to know if it is feasible to perform backups from a standby server without using SSH communication between hosts. 

  I intend to solely rely on the standby’s data directory for backups. Do you see any concern with that approach?   

In my current situation, I am working on disaster recovery and managing a remote replica. Setting up SSH communication for backups, however, is impractically expensive, making it nearly impossible for the case. I have already attempted to use it but it clearly does not work.

   I need to maintain separate backups for the remote replica and the primary server. The backups from the replica should mirror those of the primary, as if the replica were the primary, with full backups being performed accordingly.  

Additionally, it should not matter whether the repositories for the backups are the same or different, as long as both backups are managed properly fully separated.

Regards, 
Duygu

**Comment by pgstef** [comment]
Hi,

Same question as [this](https://github.com/pgbackrest/pgbackrest/issues/2443) issue.

Short answer: not, it is not possible to take a backup from the standby only, it will require an access to the primary and the backup repository should be shared between the standby and the primary.

See [this](https://pgstef.github.io/2024/09/23/pgbackrest_backups_from_the_standby_server.html) more recent blog post to learn a bit more about why it currently requires that.

If SSH is an issue, you can setup a TLS connection (example [here](https://pgbackrest.org/user-guide-rhel.html#repo-host/config)) which has better performance than SSH btw.

Kind Regards

**Comment by duyguHsnHsn** [comment]
Thanks
