### ISSUE TITLE
pgbackrest restore

### ISSUE THREAD

**Issue by adnanhamdussalam** [pgbackrest/pgbackrest#2455]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.53.1
2. PostgreSQL version:
16.4
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
OEL 9.4
4. Did you install pgBackRest from source or from a package?
source 
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    -     - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I have taken full backup from existing postgresql instance then i have drop the  postgresql instance and recreate it but when saw the error log of postgresql found below error:
2024-09-26 23:11:52.590 P00  ERROR: [103]: unable to find a valid repository:
                                    repo1: [ArchiveMismatchError] PostgreSQL version 16, system-id 7419015133708679104 do not match repo1 stanza version 16, system-id 7418999855603813694
                                    HINT: are you archiving to the correct stanza?
Now I have to restore the old full backup to this new database  on the same server but it is showing the db backup is prior:
 
 [postgres@testbed03 data]$ pgbackrest --stanza=coord --log-level-console=info info
stanza: coord
    status: ok
    cipher: aes-256-cbc

    db (prior)
        wal archive min/max (16): 0000000B00000005000000FE/0000000F0000000C00000081

        full backup: 20240925-102055F
            timestamp start/stop: 2024-09-25 10:20:55-04 / 2024-09-25 10:26:36-04
            wal start/stop: 0000000B0000000C0000007A / 0000000B0000000C0000007A
            database size: 20.9GB, database backup size: 20.9GB
            repo1: backup size: 2.6GB

    db (prior)
        wal archive min/max (16): 000000020000000000000004/000000030000000000000007

    db (prior)
        wal archive min/max (16): 000000010000000000000002/000000030000000000000006

    db (current)
        wal archive min/max (16): 000000010000000000000001/000000030000000000000006
is it possible to get the old backup to db (current) ?

[Uploading pgbackrest.txt…]()

**Comment by dwsteele** [comment]
Restore won't pick the backup you need by default since it is from a prior cluster. You'll need to add `--set=20240925-102055F` to your restore command.

**Comment by adnanhamdussalam** [comment]
Thank you for the update.
Currently in my envirnoment I have one primary and one replica sync standby configured via patroni. Now I am configuring the pgbackrest on standby / replica side to take backup But I am facing the below error when I am executing the check command from standby / replica side :

[postgres@testbed05 ~]$  pgbackrest --stanza=coord check --log-level-console=info --log-subprocess --log-level-stderr=error
2024-09-30 11:53:22.957 P00   INFO: check command begin 2.53.1: --backup-standby --exec-id=853214-ab983951 --log-level-console=info --log-level-stderr=error --log-subprocess --pg1-host=testbed01 --pg2-host=testbed05 --pg1-path=/data/ctdatabase --pg2-path=/data/ctdatabase --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/backup/coord --stanza=coord
2024-09-30 11:53:24.736 P00   INFO: check repo1 (standby)
2024-09-30 11:53:24.737 P00   INFO: switch wal not performed because this is a standby
2024-09-30 11:53:24.738 P00   INFO: check repo1 configuration (primary)
2024-09-30 11:53:24.943 P00   INFO: check repo1 archive for WAL (primary)
ERROR: [082]: WAL segment 0000001700000000000000A5 was not archived before the 60000ms timeout
       HINT: check the archive_command to ensure that all options are correct (especially --stanza).
       HINT: check the PostgreSQL server log for errors.
       HINT: run the 'start' command if the stanza was previously stopped.
2024-09-30 11:54:24.944 P00   INFO: check command end: aborted with exception [082]



ssh on both servers are configured and it is working
PFA the file pgbackrest.conf
[my_pgbackrest.txt](https://github.com/user-attachments/files/17192854/my_pgbackrest.txt)

**Comment by pgstef** [comment]
That's because you don't share your backup repository with your primary probably. Is `repo1-path=/backup/coord` a shared location like an nfs mount point for example ?
The WAL archives (needed for the backup consistency) are pushed from the primary to the backup repo. And the backup command on the standby will need to check if those WAL archives successfully comes to the backup repo used for the backup, within the 60s timeout. So you need a shared storage for this and make sure your WAL archiver process isn't lagging too far behind on the primary.
