### ISSUE TITLE
About disabling archive-check

### ISSUE THREAD

**Issue by booven** [pgbackrest/pgbackrest#2456]
Hello, we are conducting an experiment and have found that when the wal log archiving is turned off, for example, with archive_command = 'true', it is not possible to recover instances even based on full backup sets. Is there a separate configuration item in the configuration file that needs to be configured? 
Looking forward to your reply！

**Comment by pgstef** [comment]
Hi,

As the `archive-check` option describes: the backup command checks that all WAL segments required to make the backup consistent are present in the WAL archive. It's a good idea to leave this as the default unless you are using another method for archiving. 

Backing up a running PostgreSQL cluster requires WAL archiving to be enabled. See [PostgreSQL docs](https://www.postgresql.org/docs/current/continuous-archiving.html).

Kind Regards

**Comment by booven** [comment]
We now have a running PG instance that does not need to be restored by point in time (PITR), only by backup set, so do archive-check and archive-command also have to be configured if pgbackrest backup is relied upon?

If it is an active instance, this results in a large number of wal logs being archived, occupying backup space.

Thank you very much for your reply.

**Comment by pgstef** [comment]
> We now have a running PG instance that does not need to be restored by point in time (PITR), only by backup set, so do archive-check and archive-command also have to be configured if pgbackrest backup is relied upon?

That how PostgreSQL physical backups work. You need the WAL archives (at least generated during the backup) for the consistency of the backup. So you can't turn off archiving.

You can manually disable it between the backups if you want, but that adds complexity and we definitely wouldn't recommend to do so unless you exactly know what you are doing.

**Comment by slardiere** [comment]
to complete @pgstef, if you play with [repo-retention-archive](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-archive), please, enable [archive-copy](https://pgbackrest.org/configuration.html#section-backup/option-archive-copy) for your backup's consistency.

**Comment by dwsteele** [comment]
> if you play with [repo-retention-archive](https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-archive), please, enable [archive-copy](https://pgbackrest.org/configuration.html#section-backup/option-archive-copy) for your backup's consistency.

pgBackRest will never remove WAL required for recovering backups to consistency, so this is not necessary.

**Comment by booven** [comment]
Thanks for all your answers!
