### ISSUE TITLE
Trouble Running First Backup on ~200Gb Database

### ISSUE THREAD

**Issue by betterthanever2** [pgbackrest/pgbackrest#2457]
1. pgBackRest version: **2.53.1**
2. PostgreSQL version: **16**
3. Operating system/version: **Ubuntu 22**
4. Did you install pgBackRest from source or from a package? **From source.**
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
[wapaganda-main]
pg1-path=/var/lib/postgresql/16/main
pg1-port=6002
pg1-user=pgbackrest
pg1-database=wapadb

[global]
archive-async=y
archive-timeout=1d
log-level-file=detail
spool-path=/mnt/volume160/spool/pgbackrest
#repo1-host=repository
repo1-path=/mnt/volume160/pgbackrest
repo1-retention-full=1
repo1-cipher-pass=qLUXg0XUzws2kkDzkR0LpdV/ui9PNVyvqfeE3I29VamaufGPzDAVMuot+ofJtLmW
repo1-cipher-type=aes-256-cbc
repo1-bundle=y
repo1-block=y
start-fast=y
compress-type=zst

[global:archive-get]
process-max=2

[global:archive-push]
process-max=4
```
    - `postgresql.conf` settings applicable to pgBackRest 
    - `archive_command`, 'pgbackrest --stanza=wapaganda-main archive-push %p' 
    - `archive_mode`, on
    - `listen_addresses`, *
    - `max_wal_senders`, 5
    - `wal_level`, replica

`backup` log:
```
-------------------PROCESS START-------------------
2024-09-30 12:28:43.280 P00   INFO: backup command begin 2.53.1: --archive-timeout=60m --compress-type=zst --exec-id=1252384-f9afdf9a --log-level-console=detail --log-level-file=detail --pg1-database=wapadb ->2024-09-30 12:28:44.006 P00   WARN: no prior backup exists, incr backup has been changed to full
2024-09-30 12:28:44.006 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2024-09-30 12:28:44.407 P00   INFO: backup start archive = 0000000100000030000000F6, lsn = 30/F6000028
2024-09-30 12:28:44.408 P00   INFO: check archive for prior segment 0000000100000030000000F5
2024-09-30 13:28:44.434 P00  ERROR: [082]: WAL segment 0000000100000030000000F5 was not archived before the 3600000ms timeout
                                    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
                                    HINT: check the PostgreSQL server log for errors.
                                    HINT: run the 'start' command if the stanza was previously stopped.
2024-09-30 13:28:44.434 P00   INFO: backup command end: aborted with exception [082]

-------------------PROCESS START-------------------
2024-09-30 13:41:27.931 P00   INFO: backup command begin 2.53.1: --archive-timeout=1d --compress-type=zst --exec-id=1264617-10474cd3 --log-level-console=detail --log-level-file=detail --pg1-database=wapadb -->2024-09-30 13:41:28.662 P00   WARN: no prior backup exists, incr backup has been changed to full
2024-09-30 13:41:28.662 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2024-09-30 13:41:29.264 P00   INFO: backup start archive = 0000000100000030000000F8, lsn = 30/F8000028
2024-09-30 13:41:29.264 P00   INFO: check archive for prior segment 0000000100000030000000F7

-------------------PROCESS START-------------------
2024-10-01 07:29:48.024 P00   INFO: backup command begin 2.53.1: --archive-timeout=1d --compress-type=zst --exec-id=1455241-5a074677 --log-level-file=detail --pg1-database=wapadb --pg1-path=/var/lib/postgresq>2024-10-01 07:29:48.754 P00   WARN: no prior backup exists, incr backup has been changed to full
2024-10-01 07:29:48.754 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2024-10-01 07:29:49.355 P00   INFO: backup start archive = 000000010000003100000084, lsn = 31/84000028
2024-10-01 07:29:49.355 P00   INFO: check archive for prior segment 000000010000003100000083
2024-10-01 08:36:38.722 P00   INFO: backup command end: terminated on signal [SIGHUP]
```

7. Describe the issue:

I'm only beginning to use pgbackrest, so I started with following the [tutorial](https://pgbackrest.org/user-guide.html), which went perfectly fine: I was able to create config, a demo stanza, and make a backup. 

After this I went on to apply this to my existing database (roughly 200 Gb in size). It was a bit of a struggle figuring out how to make pgbackrest to connect to it, but eventually I conquered that, and was able to create a stanza for the main db instance. 

After this I tried running `check` and `backup` commands, but neither succeeded. I ended up increasing the archive-timeout period to max (1d), but I don't think that helped. Right now, when I run `info` command, I get `status: error (no valid backups)`. See the `backup` command logs above.

Are there any recommendations for setting up `pgbackrest` for plus-sized databases? Is there anything I'm doing wrong?

**Comment by pgstef** [comment]
Hi,

> Are there any recommendations for setting up pgbackrest for plus-sized databases? Is there anything I'm doing wrong?

The problem is probably not the size (which is still quite small tbh) but hard to say given you didn't provided the exact steps followed (like stanza-create and check command result).

> I started with following the [tutorial](https://pgbackrest.org/user-guide.html)

That's strange to end up with `pg1-user=pgbackrest` then. I'm curious to know what permissions you granted to that db role.

> I ended up increasing the archive-timeout period to max (1d)

That's definitely a bad solution. Archives should be pushed to the repo as fast as possible. So rather than increasing that timeout drastically, it would be best to figure out what's wrong with the archiving process.

```
ERROR: [082]: WAL segment 0000000100000030000000F5 was not archived before the 3600000ms timeout
    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
    HINT: check the PostgreSQL server log for errors.
    HINT: run the 'start' command if the stanza was previously stopped.
```

The `archive-push` command is run by the PostgreSQL server (using `archive_command`). Can you look at the PostgreSQL logs to see what's going on ? And you can look at the `pg_stat_archiver` view in the database to know what's the state of the archiver process. 
That process should run successfully before trying to take a backup.

As you are using `archive-async=y`, you might need to look at the async archive log too. It's usually easier to disable the async while debugging. First make sure the normal archiving works and then enable async imho.

**Comment by betterthanever2** [comment]
> That's strange to end up with pg1-user=pgbackrest then. I'm curious to know what permissions you granted to that db role.

This user was set up already after moving on to the prod db. When creating, I followed [these instructions](https://www.enterprisedb.com/docs/supported-open-source/pgbackrest/10-non-superuser/).

I will disable async and look into these additional logs, thank you for pointing them out!

**Comment by betterthanever2** [comment]
Inspecting the logs led me to discover 2 kinds of relevant error I've been getting:
```
2024-09-29 19:16:25.628 UTC [1067155] LOG:  archive command failed with exit code 103                                                                                                                            2024-09-29 19:16:25.628 UTC [1067155] DETAIL:  The failed archive command was: pgbackrest --stanza=wapaganda-main archive-push pg_wal/0000000100000030000000E5
2024-09-29 19:16:26.669 P00  ERROR: [103]: unable to find a valid repository:                                                                                                                                                                        repo1: [FileMissingError] unable to load info file '/mnt/volume160/pgbackrest/archive/wapaganda-main/archive.info' or '/mnt/volume160/pgbackrest/archive/wapaganda-main/arch>                                    FileMissingError: unable to open missing file '/mnt/volume160/pgbackrest/archive/wapaganda-main/archive.info' for read
                                    FileMissingError: unable to open missing file '/mnt/volume160/pgbackrest/archive/wapaganda-main/archive.info.copy' for read
                                    HINT: archive.info cannot be opened but is required to push/get WAL segments.                                                                                                                                    HINT: is archive_command configured correctly in postgresql.conf?                                                                                                                                                HINT: has a stanza-create been performed?                                                                                                                                                                        HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.  
```
and
```
2024-09-30 21:50:49.660 UTC [1207706] DETAIL:  The failed archive command was: pgbackrest --stanza=wapaganda-main archive-push pg_wal/0000000100000030000000E5                                                   2024-09-30 21:50:50.721 P00  ERROR: [041]: unable to get info for path/file '/mnt/volume160/spool/pgbackrest/archive/wapaganda-main/out/0000000100000030000000E5.ok': [13] Permission denied   
```

So, it's pretty clear that I'm having permissions issues. I went back to the guide, and I can see following lines related to repo permissions:
```
sudo mkdir -p /var/lib/pgbackrest
sudo chmod 750 /var/lib/pgbackrest
sudo chown postgres:postgres /var/lib/pgbackrest
```
It's the 3rd line that I think I skipped when setting things up (and forgot about it, too; sorry about that). This is because I'm not sure how it should be, given that I'm using non-default database role. I'm not too knowledgeable with Linux; I'm assuming that `postgres:postgres` in that line refers to the os user which is probably set up when you create db instance. **Should I create a custom system user for this?** 

I find lack of documentation for this a bit surprising, to be honest, is this usecase really atypical?

**Comment by pgstef** [comment]
> ERROR: [103]: unable to find a valid repository

That often means you didn't run stanza-create, which would catch the permission issues.

> So, it's pretty clear that I'm having permissions issues. I went back to the guide, and I can see following lines related to repo permissions

This is in the case of using a local folder as repository, typically when taking backups from a repository host (backup server). You should never store the backups locally on a PG host. Using a mount point (nfs) is perfectly fine, but indeed the first step is to make sure that the system user running the pgbackrest commands have enough permissions to r/w on that mount point and then run the stanza-create command to initialize the repository content.

> It's the 3rd line that I think I skipped when setting things up (and forgot about it, too; sorry about that). This is because I'm not sure how it should be, given that I'm using non-default database role. I'm not too knowledgeable with Linux; I'm assuming that postgres:postgres in that line refers to the os user which is probably set up when you create db instance. Should I create a custom system user for this?

No. You should use the same system user used to run your PG instance. PG itself will run the `pgbackrest archive-push` so that system user will need to work for pgBackRest anyway. Adding another system user would just make things overly complicated while you even don't master the Linux basics. So same rule as usual for backups and high-availability, keep it simple (KISS).

> I find lack of documentation for this a bit surprising, to be honest, is this usecase really atypical?

Documentation for what ? Linux permissions on a folder ? That's not the point for a backup tool where most of the time people are using a cloud repo store (s3, azure, gcs) or a dedicated backup host, which are pretty good documented imo. Using an NFS mount point with proper permissions for the `postgres` system user is supposed to be the easiest one tbh.

As we're using the same system user, there's not really a point in using a dedicated db user as you could simply use the pre-built user for the sake of simplicity. Messing with db auth for a specific db user while the backup command needs to read all the data files anyway looks atypical to me yes.

> This user was set up already after moving on to the prod db. When creating, I followed [these instructions](https://www.enterprisedb.com/docs/supported-open-source/pgbackrest/10-non-superuser/).

To be honest, I don't see the point of those instructions. I can't imagine a specifically interesting use-case for this as pgBackRest relies on local processes to connect using unix sockets. And somebody with enough linux/pg knowledge to run a PG instance with another system user (not the `postgres` default one) would have enough knowledge to create a db user too imho.

Anyway, to solve your issue, you need to identify where you want to store your backups and archives. Once that done, you make sure that the `postgres` system user can reach it (r/w), you adjust your configuration and run the `stanza-create` command. If that command succeeds, then you can trigger a `check` and if the archiving is working, then run a `backup`.
Enabling `archive-async` will require extra permissions on the spool path (which should be a local directory, definitely not a remote storage).

**Comment by betterthanever2** [comment]
First of all, thank you for the detailed response. I really appreciate your effort.

> That often means you didn't run stanza-create, which would catch the permission issues.

Not in this case. Here's my final log for creating stanza:
```
-------------------PROCESS START-------------------                                                                     2024-09-30 08:02:18.554 P00   INFO: stanza-create command begin 2.53.1: --exec-id=1209650-130d105c --log-level-console=>2024-09-30 08:02:19.181 P00   INFO: stanza-create for stanza 'wapaganda-main' on repo1                                  2024-09-30 08:02:19.196 P00   INFO: stanza-create command end: completed successfully (647ms)  
```

> No. You should use the same system user used to run your PG instance. PG itself will run the `pgbackrest archive-push` so that system user will need to work for pgBackRest anyway. Adding another system user would just make things overly complicated while you even don't master the Linux basics. So same rule as usual for backups and high-availability, keep it simple (KISS).

This is something that should be stated in the docs explicitly.

> Documentation for what ? Linux permissions on a folder ? 

Documentation on setting up pgbackrest with pre-existing databases. You have a wonderful guide about a demo instance, but when things proceed to working with production db, there are nuances that aren't even mentioned there.

> As we're using the same system user, there's not really a point in using a dedicated db user as you could simply use the pre-built user for the sake of simplicity. Messing with db auth for a specific db user while the backup command needs to read all the data files anyway looks atypical to me yes.

You are probably correct that this is a round-about way of doing things. But I only went there because having dedicated users for specific things seems like a generally good idea to me, and nothing to the contrary is mentioned in the documentation.

> To be honest, I don't see the point of those instructions. I can't imagine a specifically interesting use-case for this as pgBackRest relies on local processes to connect using unix sockets. And somebody with enough linux/pg knowledge to run a PG instance with another system user (not the `postgres` default one) would have enough knowledge to create a db user too imho.

Fair enough.

> Anyway, to solve your issue, you need to identify where you want to store your backups and archives. Once that done, you make sure that the `postgres` system user can reach it (r/w), you adjust your configuration and run the `stanza-create` command. If that command succeeds, then you can trigger a `check` and if the archiving is working, then run a `backup`. Enabling `archive-async` will require extra permissions on the spool path (which should be a local directory, definitely not a remote storage).

Do you have any idea why `stanza-create` command worked successfully in this case? Seems like it shouldn't have.

Thank you for your help!

**Comment by pgstef** [comment]
> This is something that should be stated in the docs explicitly.

The only time where we mention setting up a specific system user, is when we setup the dedicated repo host (backup server): `The pgbackrest user is created to own the pgBackRest repository. Any user can own the repository but it is best not to use postgres (if it exists) to avoid confusion`. But that's on the repo host, not on the PG hosts.

I'm certainly not saying that the docs are perfect and contains every answer to any questions (or I wouldn't write so many blog post about it), but as everything done in the user-guide is done with the `postgres` system user, if you follow the guide, you shouldn't even have to think about it ;-) 

> Documentation on setting up pgbackrest with pre-existing databases. You have a wonderful guide about a demo instance, but when things proceed to working with production db, there are nuances that aren't even mentioned there.

Honestly, it's even easier with pre-existing db. Always the same steps:
- decide where your backups/archives will be stored and make sure the linux user can reach that
- setup configuration (pgbackrest and postgres)
- run `stanza-create` with the system user that would run the pgbackrest commands
- run `check` to make sure archiving is working
You just skip the initdb/createcluster step...

But that's a "quick start". As those docs are used for the CI runs, we can't document each and every possible user-specific use-cases unfortunately.

> Do you have any idea why stanza-create command worked successfully in this case? Seems like it shouldn't have.

You could have run it on a different repository. Or if you run it with like `root`, it will work from the permissions point of view, but then when PG will try to run with the `postgres` system user, it will fail. Usually we use the `postgres` db user too so we can rely on `peer` in the hba for the local connection. If you ran stanza-create with "root", but the db connection went trough, I hope you don't have any "trust" line in your hba :-)

```bash
sudo -u postgres pgbackrest --stanza=demo --log-level-console=info stanza-create
```

In the user-guide, this is pretty clear to me that the `stanza-create` command should run with the postgres user...

**Comment by betterthanever2** [comment]
> but as everything done in the user-guide is done with the postgres system user, if you follow the guide, you shouldn't even have to think about it ;-)

Well, I see exactly this as an issue. When following the guide, I really wasn't thinking about it, but then I have the db I actually want to back up, and it was set up a while back, and with nuances I may not even remember by now. Of course, you cannot and should not try to cover every possible usecase. I'm just saying that things that seem obvious to you (such as that you should always use the default `postgres` user unless there is a very good reason not to) would not necessarily be obvious to others.

I agree that your documentation is pretty good. But this summary:
>    decide where your backups/archives will be stored and make sure the linux user can reach that
>    setup configuration (pgbackrest and postgres)
>    run stanza-create with the system user that would run the pgbackrest commands
>    run check to make sure archiving is working

should be added to the userguide somewhere in the beginning. 

> Or if you run it with like root, it will work from the permissions point of view, but then when PG will try to run with the postgres system user, it will fail. 

Indeed, I ran it as root. 

> In the user-guide, this is pretty clear to me that the stanza-create command should run with the postgres user...

Yeah, I suppose you're right.

**Comment by pgstef** [comment]
> should be added to the userguide somewhere in the beginning.

To me, it is.

> 6.1 Setup Demo Cluster
> 6.2 Configure Cluster Stanza
> 6.3 Create the Repository
> 6.4 Configure Archiving
> 6.5 Configure Retention
> 6.6 Configure Repository Encryption
> 6.7 Create the Stanza
> 6.8 Check the Configuration 

Skip step 1 if you already have a running PG cluster. And that step 1 says:

> Creating the demo cluster is optional but is strongly recommended, especially for new users, since the example commands in the user guide reference the demo cluster; the examples assume the demo cluster is running on the default port (i.e. 5432).

Anyway, back to your actual problem.

> Indeed, I ran it as root.

Then or your reset the stanza and create it again using the `postgres` system user, or you fix permissions and ownership of the current repo and you should be fine.

And one last thing, if you plan to use asynchronous archiving, please don't use `spool-path=/mnt/volume160/spool/pgbackrest`. The spool path is intended to be located on a local Posix-compatible filesystem (= local directory), not a remote filesystem such as NFS or CIFS. The default location should be good enough.

Kind Regards

**Comment by betterthanever2** [comment]
> To me, it is.
I'm sorry, but it's not the same. The reasoning why something needs to be done the way it is described is important. Also, would it be a really bad thing to add a separate instruction for the usecase? After all, this is not code, where redundancy is a bad thing, it's a user guide, and people in general tend to, you know, _underthink_.

> Creating the demo cluster is optional but is strongly recommended, especially for new users, since the example commands in the user guide reference the demo cluster; the examples assume the demo cluster is running on the default port (i.e. 5432).

Thanks for reminding me! I think it would be beneficial to add something like "And if your DB is running on a different port, here's what you should do... " - because it was a confusion point for me.

**Comment by dwsteele** [comment]
> I'm sorry, but it's not the same. The reasoning why something needs to be done the way it is described is important. 

The user guide explicity states exactly which user should be used for each command, e.g.:
```
sudo -u postgres pgbackrest --stanza=demo --log-level-console=info stanza-create
```
I'm not sure how much more explicit we could be. I think a general statement like, "commands in this section should be run as postgres" would be worse because it might not always be true. And different sections will have different rules.

**Comment by betterthanever2** [comment]
> I'm not sure how much more explicit we could be

I'm seriously telling you that if you add the summary steps @pgstef listed earlier as is, it would make the things clearer. It made things clearer to me just now. And I'm a bit more attentive when reading docs than the average developer.

It's all a matter of framing, really. The way you put it ("commands in this section _should_ be run...") is not great. What would be better is a single block somewhere in the intro section stating something to the effect "The following guide assumes that your are using `postgres` user. This is not just because it's simple to set up for demo purposes, but also a generally good idea because setting up a dedicated user is not needed for most usecases and requires advanced understanding of OS-database interoperability".

Things like that.

**Comment by dwsteele** [comment]
Well, I'm not against it, but as this does not seems to be an issue for the majority of users, I'm not planning to spend time on it, either.

**Comment by dwsteele** [comment]
Not to mention that we already address how commands should be run in the introduction.

**Comment by dwsteele** [comment]
You are, of course, welcome to submit a PR, though I would caveat that I believe we already cover this topic in the introduction. Make sure your PR takes that into account.
