### ISSUE TITLE
Backup timeout issue with lot of databases (~6000)

### ISSUE THREAD

**Issue by NaPs** [pgbackrest/pgbackrest#2458]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.50, also tried on 2.53.1

2. PostgreSQL version: 13.6.1

3. Operating system/version: Ubuntu 20.04

4. Did you install pgBackRest from source or from a package? From PGDG repository

5. Please attach the following as applicable: n/a

7. Describe the issue:

PgBackRest fails to backup a PostgreSQL cluster with approximately 6000 databases due to a timeout error.

Environment:

- xx-db-1, xx-db-2 (PostgreSQL instances managed by pg_autofailover)
- xx-db-monitor (pg_autofailover cluster monitor and PgBackRest backup runner)

Error:

```
2024-10-07 01:30:01.586 P00   INFO: backup command begin 2.50: --backup-standby --compress-type=zst --exec-id=1834694-c57010f3 --pg1-host=xx-db-1 --pg2-host=xx-db-2 --pg1-host-ca-file=/etc/pgbackrest/cert/CA-cert.pem --pg2-host-ca-file=/etc/pgbackrest/cert/CA-cert.pem --pg1-host-cert-file=/etc/pgbackrest/cert/xx-db-monitor-crt.pem --pg2-host-cert-file=/etc/pgbackrest/cert/xx-db-monitor-crt.pem --pg1-host-key-file=/etc/pgbackrest/cert/xx-db-monitor-key.pem --pg2-host-key-file=/etc/pgbackrest/cert/xx-db-monitor-key.pem --pg1-host-type=tls --pg2-host-type=tls --pg1-path=/var/lib/postgresql/13/main --pg2-path=/var/lib/postgresql/13/main --protocol-timeout=3600 --repo1-block --repo1-bundle --repo1-path=/ --repo1-retention-archive=7 --repo1-retention-archive-type=diff --repo1-retention-diff=7 --repo1-retention-full=30 --repo1-retention-full-type=time --repo1-s3-bucket=xx-pg-pgbackrest --repo1-s3-endpoint=xxx.xxx.xxx.xxx --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=minio --repo1-s3-uri-style=path --repo1-storage-port=9000 --no-repo1-storage-verify-tls --repo1-type=s3 --stanza=xx --start-fast --stop-auto --type=diff
2024-10-07 01:31:25.301 P00   INFO: last backup label = 20240922-013002F, version = 2.50
2024-10-07 01:31:25.301 P00   INFO: execute non-exclusive backup start: backup begins after the requested immediate checkpoint completes
2024-10-07 02:01:25.606 P00  ERROR: [057]: raised from remote-0 tls protocol on 'xx-db-2': query 'select oid::oid, datname::text, (select oid::oid from pg_catalog.pg_database where datname = 'template0') as datlastsysoid from pg_catalog.pg_database' timed out after 1800000ms
2024-10-07 02:01:25.606 P00   INFO: backup command end: aborted with exception [057]
```

**Investigation:**

The query executes instantly when run directly on xx-db-2 and returns the ~6000 rows.

Strace analysis of the PgBackRest process on xx-db-2 during backup reveals exponential sleeps between ~16KB reads of the PostgreSQL query response:

![image](https://github.com/user-attachments/assets/85240433-60ee-492b-a0d2-788015b9edaa)

Digging into the source code led us to the cause of the behavior observed in strace: https://github.com/pgbackrest/pgbackrest/blob/main/src/postgres/client.c#L196-L201

The `waitMore` function implements exponential sleeps between calls to `PQconsumeInput` (which is the function performing the actual reads on the socket).

According to the [libpq doc](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQCONSUMEINPUT):

> A typical application using these functions will have a main loop that uses select() or poll() to wait for all the conditions that it must respond to. One of the conditions will be input available from the server, which in terms of select() means readable data on the file descriptor identified by [PQsocket](https://www.postgresql.org/docs/current/libpq-status.html#LIBPQ-PQSOCKET). When the main loop detects input ready, it should call [PQconsumeInput](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQCONSUMEINPUT) to read the input. It can then call [PQisBusy](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQISBUSY), followed by [PQgetResult](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQGETRESULT) if [PQisBusy](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQISBUSY) returns false (0). It can also call PQnotifies to detect NOTIFY messages (see [Section 32.9](https://www.postgresql.org/docs/current/libpq-notify.html)).

It seems that PgBackRest's implementation may not be optimal for handling large result sets because of those sleeps.

As a workaround, we increased the `db-timeout`. It works but it takes ~1.5h to run the `pg_database` query and to fetch its result before initiating the backup process.

Thank you!
Antoine

**Comment by dwsteele** [comment]
Thank you for the extremely detailed 

> Strace analysis of the PgBackRest process on xx-db-2 during backup reveals exponential sleeps between ~16KB reads of the PostgreSQL query response:

It's Fibonacci backoff but the end is similar.

> It seems that PgBackRest's implementation may not be optimal for handling large result sets because of those sleeps.

I tried a backup with 6000 databases and it took about one minute to return the results, which works but is not great. I wonder why your query is taking so much longer.

> As a workaround, we increased the db-timeout. It works but it takes ~1.5h to run the pg_database query and to fetch its result before initiating the backup process.

That definitely sucks but at least you were able to get the backups running.

PR #2459 fixes this issue but writing tests for it is going to be a bit tricky. Any chance you can test and make sure it solves your issue? It definitely worked for me -- brought my query time down from a minute to a few ms.

**Comment by NaPs** [comment]
> > It seems that PgBackRest's implementation may not be optimal for handling large result sets because of those sleeps.
> 
> I tried a backup with 6000 databases and it took about one minute to return the results, which works but is not great. I wonder why your query is taking so much longer.

Our database names are quite long, like "xx_production_yyyyy". Perhaps x6000, it could make the difference to the size of the answer?

```
$ echo "select oid::oid, datname::text, (select oid::oid from pg_catalog.pg_database where datname = 'template0') as datlastsysoid from pg_catalog.pg_database" | psql | wc -c
341997
```

> PR #2459 fixes this issue but writing tests for it is going to be a bit tricky. Any chance you can test and make sure it solves your issue? It definitely worked for me -- brought my query time down from a minute to a few ms.

Yep it worked. We didn't time it but but the operation felt "instantaneous" (compared to the 1.5 hours of the previous run :-))

**Comment by dwsteele** [comment]
> Our database names are quite long, like "xx_production_yyyyy". Perhaps x6000, it could make the difference to the size of the answer?

Seems plausible. I created 6000 databases with really long names (.e.g. `abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz6000`) and it had not returned after ten minutes.

> Yep it worked. We didn't time it but the operation felt "instantaneous"

I bet it did. I pushed an updated version that I think is more efficient overall. We'll get it reviewed and then maybe have you test it one more time if you can.

**Comment by dwsteele** [comment]
Also, closing this issue since there is a PR, but feel free to leave comments here.

**Comment by NaPs** [comment]
> I bet it did. I pushed an updated version that I think is more efficient overall. We'll get it reviewed and then maybe have you test it one more time if you can.

Before the patch

> 2024-10-08 09:58:49.602 P00  DEBUG:     postgres/client::pgClientQuery: (this: {host: null, database: {"postgres"}, user: null, port: 5432, queryTimeout 7200000}, query: {"select oid::oid, datname::text, (select oid::oid from pg_catalog.pg_database where datname = 'template0') as datlastsysoid from pg_catalog.pg_database"}, resultType: any)
> 2024-10-08 11:16:06.209 P00  DEBUG:     postgres/client::pgClientQuery: => {Pack}


After the patch

> 2024-10-09 12:15:50.970 P00  DEBUG:     postgres/client::pgClientQuery: (this: {host: null, database: {"postgres"}, user: null, port: 5432, queryTimeout 7200000}, query: {"select oid::oid, datname::text, (select oid::oid from pg_catalog.pg_database where datname = 'template0') as datlastsysoid from pg_catalog.pg_database"}, resultType: any)
> 2024-10-09 12:15:50.974 P00  DEBUG:     postgres/client::pgClientQuery: => {Pack}

I think it's safe to say it works :-)

Thanks a lot!
Antoine

**Comment by dwsteele** [comment]
Cool, did you do that with the most recent code, i.e. 1d24155b54 that I pushed up at 13:01 GMT+3?

> I think it's safe to say it works :-)

That's more than a million times faster. I feel like our work here is done!

**Comment by npdgm** [comment]
> Cool, did you do that with the most recent code, i.e. [1d24155](https://github.com/pgbackrest/pgbackrest/commit/1d24155b5491cccf7f400a09d723845df95ab0bf) that I pushed up at 13:01 GMT+3?

Yes, this was `fix-client-throttling 1d24155b5 Try with new wait code.`

> That's more than a million times faster. I feel like our work here is done!

Indeed. Thanks a lot David.

**Comment by dwsteele** [comment]
@npdgm Would you like your name in the release notes as Thibault VINCENT or Thibault Vincent?

**Comment by npdgm** [comment]
> @npdgm Would you like your name in the release notes as Thibault VINCENT or Thibault Vincent?

Both are fine, you can use the usual form with a single uppercase letter. I only use full capitalization in some contexts because both names are firstnames in french and it sometimes causes confusion :)
Thanks for asking!
