### ISSUE TITLE
ERROR: [031]: option '-global--compress-level' cannot begin with a dash

### ISSUE THREAD

**Issue by oggers** [pgbackrest/pgbackrest#2460]
I get the error referred in the title, whatever command I execute. For example, without pgbackrest.conf:

```
# src/pgbackrest check
P00  ERROR: [031]: option '-global--compress-level' cannot begin with a dash
# src/pgbackrest info
P00  ERROR: [031]: option '-global--compress-level' cannot begin with a dash
# src/pgbackrest annotate
P00  ERROR: [031]: option '-global--compress-level' cannot begin with a dash
```

When I execute with the following /etc/pgbackrest/pgbackrest.conf I get the same error:
```
[global]
compress-level=3
```
I tested with pgRestBack version 2.53.1 compiled from sources and version 2.53.1-1.pgdg110+1 installed from apt.postgresql.org.

postgresql version: 16.4-1.pgdg110+1
operating system: docker image debian bullseye 11.10

Thank you.

**Comment by pgstef** [comment]
> For example, without pgbackrest.conf

What do you mean without configuration file? The configuration file is always loaded if existing.

> When I execute with the following /etc/pgbackrest/pgbackrest.conf I get the same error:
> 
> ```
> [global]
> compress-level=3
> ```

That's only an extract of the file. Please provide the complete configuration file used as asked in the issue template so we can try to reproduce your error.

Using `compress-level` shouldn't give you any error (see below). You probably have a typo (invisible character) in your configuration file.

```bash
$ cat /etc/pgbackrest.conf
[global]
compress-level=3
repo1-path=/repo1

[test-stanza]
pg1-path=/var/lib/pgsql/16/main/data

$ pgbackrest version
pgBackRest 2.53.1

$ pgbackrest --stanza=test-stanza check --log-level-console=info
P00   INFO: check command begin 2.53.1: ...
P00   INFO: check repo1 configuration (primary)
P00   INFO: check repo1 archive for WAL (primary)
P00   INFO: WAL segment 000000010000000000000011 successfully archived to '....gz' on repo1
P00   INFO: check command end: completed successfully

$ pgbackrest --stanza=test-stanza backup --type=full
$ pgbackrest --stanza=test-stanza info
stanza: test-stanza
    status: ok
    cipher: none

    db (current)
        wal archive min/max (16): 00000001000000000000000F/000000010000000000000013

        full backup: 20241009-063506F
            timestamp start/stop: 2024-10-09 06:35:06+00 / 2024-10-09 06:35:09+00
            wal start/stop: 000000010000000000000013 / 000000010000000000000013
            database size: 22.2MB, database backup size: 22.2MB
            repo1: backup set size: 3.2MB, backup size: 3.2MB
```

Regards

**Comment by oggers** [comment]
> > For example, without pgbackrest.conf
> 
> What do you mean without configuration file? The configuration file is always loaded if existing.

Without configuration file = **non existing** configuration file
> 
> > When I execute with the following /etc/pgbackrest/pgbackrest.conf I get the same error:
> > ```
> > [global]
> > compress-level=3
> > ```
> 
> That's only an extract of the file. Please provide the complete configuration file used as asked in the issue template so we can try to reproduce your error.

No, it's the whole file. I also tested it with a long configuration file, but in order to provide the simplest example I narrowed it down to only 1 line and only the global section.
> 
> Using `compress-level` shouldn't give you any error (see below). You probably have a typo (invisible character) in your configuration file.

I don't thing so. Even if I use the following configuration file `/etc/pgbackrest/pgbackrest.conf` it throws the same error:
```
[global]
delta=y
```
There is no other `pgbackrest.conf` file in the container.
I have been struggling with the file for 2 days, generating the configuration file using ansible, manually using echo >, etc. so, I don't think there is always an invisible character in the file.
Anyway, here is the hex dump of the configuration file:
```
# od -xc /etc/pgbackrest/pgbackrest.conf 
0000000    675b    6f6c    6162    5d6c    630a    6d6f    7270    7365
          [   g   l   o   b   a   l   ]  \n   c   o   m   p   r   e   s
0000020    2d73    656c    6576    3d6c    0a33
          s   -   l   e   v   e   l   =   3  \n
0000032
```
> 
> ```shell
> $ cat /etc/pgbackrest.conf
> [global]
> compress-level=3
> repo1-path=/repo1
> 
> [test-stanza]
> pg1-path=/var/lib/pgsql/16/main/data
> 
> $ pgbackrest version
> pgBackRest 2.53.1
> 
> $ pgbackrest --stanza=test-stanza check --log-level-console=info
> P00   INFO: check command begin 2.53.1: ...
> P00   INFO: check repo1 configuration (primary)
> P00   INFO: check repo1 archive for WAL (primary)
> P00   INFO: WAL segment 000000010000000000000011 successfully archived to '....gz' on repo1
> P00   INFO: check command end: completed successfully
> 
> $ pgbackrest --stanza=test-stanza backup --type=full
> $ pgbackrest --stanza=test-stanza info
> stanza: test-stanza
>     status: ok
>     cipher: none
> 
>     db (current)
>         wal archive min/max (16): 00000001000000000000000F/000000010000000000000013
> 
>         full backup: 20241009-063506F
>             timestamp start/stop: 2024-10-09 06:35:06+00 / 2024-10-09 06:35:09+00
>             wal start/stop: 000000010000000000000013 / 000000010000000000000013
>             database size: 22.2MB, database backup size: 22.2MB
>             repo1: backup set size: 3.2MB, backup size: 3.2MB
> ```

Now, I have tested it with the following configuration file:
```
# cat /etc/pgbackrest/pgbackrest.conf 
[global]
compress-level=3
repo1-path=/repo1

[test-stanza]
pg1-path=/var/lib/postgresql/data
```

Same result:
```
# src/pgbackrest --stanza=test-stanza info
P00  ERROR: [031]: option '-global--compress-level' cannot begin with a dash
```

> 
> Regards

**Comment by pgstef** [comment]
> Without configuration file = **non existing** configuration file

It just uses the internal default config then.

Still, with fresh install, without any configuration file, there's no error:

```bash
$ ls -l /etc/pgbackrest.conf
ls: cannot access '/etc/pgbackrest.conf': No such file or directory
$ ls -l /etc/pgbackrest/pgbackrest.conf
ls: cannot access '/etc/pgbackrest/pgbackrest.conf': No such file or directory
$ pgbackrest version
pgBackRest 2.53.1
$ pgbackrest info
No stanzas exist in the repository.
```

Even with your config snippet, I can't reproduce your error:

```bash
$ cat /etc/pgbackrest/pgbackrest.conf 
[global]
compress-level=3
$ pgbackrest info
No stanzas exist in the repository.
```

So now we need to find out what's wrong with your environment or source compilation.
Did you use some environment variable to provide the configuration to the pgbackrest command ?

**Comment by pgstef** [comment]
> After this I have checked the pgbackrest doc searching about the environment variables it uses, but couldn't find anything at first glance.

See https://pgbackrest.org/command.html#introduction for the details:

>  Commands are used to execute the various pgBackRest functions. Here the command options are listed exhaustively, that is, each option applicable to a command is listed with that command even if it applies to one or more other commands. This includes all the options that may also be configured in pgbackrest.conf.
>
> Non-boolean options configured in pgbackrest.conf can be reset to default on the command-line by using the reset- prefix. This feature may be used to restore a backup directly on a repository host. Normally, pgBackRest will error because it can see that the database host is remote and restores cannot be done remotely. By adding --reset-pg1-host on the command-line, pgBackRest will ignore the remote database host and restore locally. It may be necessary to pass a new --pg1-path to force the restore to happen in a specific path, i.e. not the path used on the database host.
>
> The no- prefix may be used to set a boolean option to false on the command-line.
>
> Any option may be set in an environment variable using the PGBACKREST_ prefix and the option name in all caps replacing - with _, e.g. pg1-path becomes PGBACKREST_PG1_PATH and stanza becomes PGBACKREST_STANZA. Boolean options are represented as they would be in a configuration file, e.g. PGBACKREST_COMPRESS="n", and reset-* variants are not allowed. Options that can be specified multiple times on the command-line or in a config file can be represented by separating the values with colons, e.g. PGBACKREST_DB_INCLUDE="db1:db2".
>
> Command-line options override environment options which override config file options. 

Glad you sorted it out :+1: 
Kind Regards
