### ISSUE TITLE
infinite retention in pgbackgrest/backup/maindb/backup.history

### ISSUE THREAD

**Issue by udf2457** [pgbackrest/pgbackrest#2461]
pgBackRest version:

pgBackRest 2.52.1

 PostgreSQL version:

psql (PostgreSQL) 16.3 (Debian 16.3-1.pgdg120+1)

Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Debian Bookworm (12)

Did you install pgBackRest from source or from a package?

Package

Describe the issue:

I have noticed in my S3 storage that "pgbackgrest/backup/maindb/backup.history" appears to be storing infinitely.

e.g. I have files there from `2024-06-05`, whilst `pgbackrest info` shows oldest backup `2024-10-02` newest backup `2024-10-09`

**Comment by pgstef** [comment]
Hi,

See more information about this in https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-history.

Kind Regards

**Comment by udf2457** [comment]
Aah.  I must have missed that, I've got `retention-full` and `retention-diff` set but not `retention-history` !  Thanks @pgstef 

Can I just add it to `pgbackrest.conf` or do I also need to run `stanza-upgrade` or something ?

**Comment by pgstef** [comment]
Just add it to the config and it will be enough. You can manually run the expire command if you want to expire those right away or just wait that the next successful backup triggers that clean-up.
