### ISSUE TITLE
documnetation pgBackRest User Guides

### ISSUE THREAD

**Issue by gurucubano** [pgbackrest/pgbackrest#2464]
We use PostgreSQL since version 11.x for our customers on SuSE Linux Enterprise, today SLES 15. The database cluster get created with something like
```
pg_ctl -D /data/postgresql151/data initdb
```
The UserGuides say in section 6.2: "Make sure that pg-path is exactly equal to data_directory in postgresql.conf."

In our config files we never configured anything for `data_directory`:
```
# grep data_directory  postgresql162/data/postgresql.conf database/postgresql151/data/postgresql.conf
postgresql162/data/postgresql.conf:#data_directory = 'ConfigDir'               # use data in another directory
database/postgresql151/data/postgresql.conf:#data_directory = 'ConfigDir'      # use data in another directory
```
As the comment in the file says, this variable is only used when the data is in elsewhere and not where the config file itself is. So, it's not a good reference for what to configure for `pg-path` in pgBackRest's config file.

**Comment by pgstef** [comment]
Hi,

The pg-path should match what the query `select setting from pg_catalog.pg_settings where name = 'data_directory'` returns. `data_directory` always has a value in PostgreSQL configuration even if it can be set by various means (config file,  initdb,...).

I agree `in postgresql.conf` might be confusing and could probably be replaced by `in PostgreSQL configuration` but even then, it should imho be pretty self-explanatory for someone with at least some basic PG knowledge.

Kind Regards

**Comment by dwsteele** [comment]
We could change it to "as reported by PostgreSQL". That should be accurate enough?

**Comment by pgstef** [comment]
> We could change it to "as reported by PostgreSQL". That should be accurate enough?

For me it is indeed. Let's wait for OP's feedback about this proposal? :-)

**Comment by gurucubano** [comment]
`as reported by PostgreSQL` is the description.

Btw: is there some mailing-list to discuss or ask pgBackRest problems which are not in every case an issue, sometimes user errors?

**Comment by pgstef** [comment]
> `as reported by PostgreSQL` is the description.

Cool :+1: 

> Btw: is there some mailing-list to discuss or ask pgBackRest problems which are not in every case an issue, sometimes user errors?

Usually I would say here is good, because we have the issue template which is often very helpful to get the context of the error (with config files, described error,...).

Other than that, there's the pgbackrest slack channel on the postgresteam slack

**Comment by dwsteele** [comment]
Closing since #2467 has been opened to clarify this.
