### ISSUE TITLE
Is pgBackRest compatible with PostgreSQL17?

### ISSUE THREAD

**Issue by mihneamateihpe** [pgbackrest/pgbackrest#2465]
Hello,

I have just upgraded a test cluster to psql17 and I am trying to install and run pgbackrest 2.52 with it, but at stanza create it throws error regarding control version. Is pgbackrest 2.52 compatible with psql17 [as stated in the release notes of 2.52](https://pgbackrest.org/release.html)?
Below you can find the error

```
[pgbackrest@treport-b ~]$pgbackrest --stanza=realtime-database stanza-create
2024-10-15 13:56:21.048 P00   INFO: stanza-create command begin 2.52: --exec-id=357742-c1b54b71 --log-level-console=info --log-level-file=detail --pg1-host=10.96.132.30 --pg2-host=10.96.132.31 --pg1-path=/data/postgresql --pg2-path=/data/postgresql --pg1-port=5432 --pg2-port=5432 --pg1-socket-path=/data/postgresql --pg2-socket-path=/data/postgresql --repo1-path=/var/lib/pgbackrest --stanza=realtime-database
WARN: unable to check pg1: [VersionNotSupportedError] unexpected control version = 1700 and catalog version = 202406281
      HINT: is this version of PostgreSQL supported?
WARN: unable to check pg2: [VersionNotSupportedError] unexpected control version = 1700 and catalog version = 202406281
      HINT: is this version of PostgreSQL supported?
ERROR: [056]: unable to find primary cluster - cannot proceed
       HINT: are all available clusters in recovery?
2024-10-15 13:56:22.721 P00   INFO: stanza-create command end: aborted with exception [056]

[pgbackrest@treport-b ~]$pgbackrest version
pgBackRest 2.52
```

and the psql version
```
realtimedb=# SELECT version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 17.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22), 64-bit
(1 row)
```

Thank you!

**Comment by pgstef** [comment]
Hi,

`2.52` was released before PostgreSQL 17 was actually released and hackers have bumped the catalog version since then.
@dwsteele made the adjustments in [this](https://github.com/pgbackrest/pgbackrest/commit/80c9b3001c8f4689837d46783d348a2c839645c0) commit. 

`2.54.0` (which should be released soon) will be fully compliant with PostgreSQL 17, even though the specific commit was embedded in `2.53.1` and that version is already working with PostgreSQL 17.

Kind Regards

**Comment by mihneamateihpe** [comment]
I understand and I appreciate very much your fast response. Thank you very much!

Kind Regards,
Mihnea

**Comment by dwsteele** [comment]
2.53.1 (which has already been released) is fully compatible with PG17. The changes in 2.54.0 are only to finalize the catalog version.
