### ISSUE TITLE
pgBackRest 

### ISSUE THREAD

**Issue by gurucubano** [pgbackrest/pgbackrest#2468]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.53

2. PostgreSQL version: 15.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: SuSE Linux Enterprise SLES 15 SP6

4. Did you install pgBackRest from source or from a package? from source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
 ```
# see https://pgbackrest.org/user-guide.html#build
[demo]
pg1-path=/data/postgresql151/data

[global]
repo1-path=/data/postgresql151/data/pgbackrest
repo1-retention-full=2
start-fast=y
```

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
 ```
# config for pgBackRest
# guru@unixarea.de, October 2024
#
archive_command = '/home/sisis/guru/pgbackrest --stanza=demo archive-push %p'
archive_mode = on
log_filename = 'postgresql.log'
max_wal_senders = 3
wal_level = replica
archive_timeout = 600           # force a logfile segment switch after this
                                # number of seconds; 0 disables
#
# end of config changes for pgBackRest
```

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: The archiving from the PostgreSQL server seems to work:
```
du -sh /data/postgresql151/data/pgbackrest/archive
2,1G    /data/postgresql151/data/pgbackrest/archive
```
A backup with `full` worked too:
```
/home/sisis/guru/pgbackrest --type=full --stanza=demo backup
...
ls -ltr /data/postgresql151/data/pgbackrest/backup/demo/
insgesamt 6
drwxr-x--- 3 postgres postgres 1024 15. Okt 14:29 backup.history
drwxr-x--- 3 postgres postgres 1024 15. Okt 14:29 20241015-135531F
lrwxrwxrwx 1 postgres postgres   16 15. Okt 14:29 latest -> 20241015-135531F
-rw-r----- 1 postgres postgres 1067 15. Okt 14:29 backup.info
-rw-r----- 1 postgres postgres 1067 15. Okt 14:29 backup.info.copy 
```
but a backup of type `diff` gives an error:
```
/home/sisis/guru/pgbackrest --type=diff --stanza=demo backup
2024-10-16 07:08:38.180 P00  ERROR: [070]: link 'pgbackrest/backup/demo/latest' destination '/data/postgresql151/data/pgbackrest/backup/demo/20241015-135531F' is in PGDATA
```
I know that the pgBackRest top level directory is below `PGDATA` I did this with intention because I read that if not the PostgreSQL server can't do archiving if it is elsewhere.

What is my error? Why the baclup of type `full` worked?

**Comment by pgstef** [comment]
Hi,

> I know that the pgBackRest top level directory is below `PGDATA` I did this with intention because I read that if not the PostgreSQL server can't do archiving if it is elsewhere.

Please don't do that. I don't know where you read that but that's totally wrong! Why would we have so many repository types supported (s3, azure,...) otherwise? All the user-guides are showing how to properly use various repository locations, never inside the PGDATA. 

Actually one of the most important rule when speaking about backups (not only true for PG) is to never store the backups at the same place than your production data.

> The 3-2-1 Rule is a data protection strategy that recommends having three copies of your data, stored on two different types of media, with one copy kept off-site

Anyway, to fix your problem, move your repository somewhere else.

Kind Regards

**Comment by dwsteele** [comment]
> I know that the pgBackRest top level directory is below PGDATA I did this with intention because I read that if not the PostgreSQL server can't do archiving if it is elsewhere.

Seriously, if you remember where you read this I would like to know the URL. It is dangerously wrong and should be taken down.
