### ISSUE TITLE
Cloning PostgreSQL Database using pgbackrest 

### ISSUE THREAD

**Issue by Delkady** [pgbackrest/pgbackrest#2469]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **pgBackRest 2.53.1**

2. PostgreSQL version: **PostgreSQL 15.8**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: **Red Hat Enterprise Linux 9.4**

4. Did you install pgBackRest from source or from a package? **Package** 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
    **As we do not have any real problematic issues so far, I did not attach any files.**

7. Describe the issue:

Hello,
  we are currently testing pgbackrest on our RHEL 9 PostgreSQL 15 VMs. So far, we see it as the perfect tool for backing up and restoring our databases. Yet we are questioning our current approach/procedure to clone a database X into a database Y.  X and Y share the same Repo but have different Stanza Names.
   
   Having Database X on VMx and Database Y on VMy the Scenario goes as follows :
   

-      Run pgbackrest to backup X fully.
-      Copy Y PostgreSQL Configuration Files to a backup directory.
-      Delete Y Data Directory (PGDATA) and all WAL records on VMy.
-      Start pgbackrest to restore backup of X on VMy.
-      Start database on VMy , which triggers the recovery of WAL records of X.
-      Recopy Y PostgreSQL Configuration Files to Data Directory and Restart Y.
-      Rename database X to Y on VMy and redefine users , authorizations…etc.

   
   Regarding the DB structure, we only create and operate one database in the cluster. 
   Please note thatDatabase Y is used for test and development purposes. So, defining a  Stanza on the DB is unnecessary; yet it is 
    undesirable to have different Ansible deployment scripts executing on VMs.  The clone process is a daily activity and can span over multiple databases, i.e.  database X can be cloned into multiple test databases.
   
   Kindly advise on:
   
     * Are there specific pgbackrest Parameters to consider in this scenario?
     * Is there a problem that all source and target databases share the same Repo?

Thank you in Advance
Dalia Elkady

**Comment by dwsteele** [comment]
> Delete Y Data Directory (PGDATA) and all WAL records on VMy.

It would be more efficient to add `--delta` to the restore: https://pgbackrest.org/user-guide.html#restore/option-delta

> Recopy Y PostgreSQL Configuration Files to Data Directory and Restart Y.

You should be able to do this before `Start pgbackrest to restore backup of X on VMy.`. Postgres is not going to overwrite your config.

> Are there specific pgbackrest Parameters to consider in this scenario?

`--delta` as noted above.

> Is there a problem that all source and target databases share the same Repo?

The danger here is that a development database will write into the production repo if it is configured incorrectly. When restoring production databases into dev I always mount the repo read-only. Note that this is also possible for object stores like S3 via roles and permissions. For dev systems it is also best to disable archiving, see https://pgbackrest.org/configuration.html#section-restore/option-archive-mode.
