### ISSUE TITLE
db-include question

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#247]
The documentation leaves the impression that "**db-include=**" can only be specified for restore operations.  Does that imply that you cannot do backups with this option, and that you only have the choice to backup everything in a cluster?  If so, can that be a feature enhancement in the future to allow specific databases to be backed up instead of all databases in a cluster?

**Comment by dwsteele** [comment]
Yes, that's correct, db-include can only be used on restore.

There are no plans to include this as a backup option.  If you have databases you don't want to backup it's best to put them in a separate cluster.

**Comment by dwsteele** [comment]
If you have backups of your clusters you should be able to use db-include to restore the databases you want into a new cluster.  It's not clear to me why you would want to do a partial backup?
