### ISSUE TITLE
Server power outage ：[ArchiveMismatchError] unable to retrieve the archive id for database version '14' and system-id '7311631382040695464'

### ISSUE THREAD

**Issue by gechengxiang1224** [pgbackrest/pgbackrest#2475]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

pgBackRest version:
2.46

PostgreSQL version:
14.7

Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
centos7.6

Did you install pgBackRest from source or from a package?
pgbackrest-2.46-2.rhel7.x86_64.rpm

Please attach the following as applicable:
N/A

Describe the issue:
Server power outage ，sudo -u postgres  pgbackrest info：

stanza: mirrorPg
    status: error (other)
            [ArchiveMismatchError] unable to retrieve the archive id for database version '14' and system-id '7311631382040695464'
    cipher: none

    db (current)
        wal archive min/max (14): none present

Thanks for the great product.

**Comment by pgstef** [comment]
Hi,

What is your question exactly? I mean if the repository is not reachable you'll indeed have lots of errors. And as you didn't provided any configuration we can't even try to reproduce your case.

Kind Regards

**Comment by gechengxiang1224** [comment]
pgbackrest.conf file(s)
[global]
repo1-path=/var/lib/pgbackrest

#[main]
#pg1-path=/var/lib/pgsql/10/data
[root@1 pgbackrest]# cat /etc/pgbackrest/pgbackrest.conf
[global]
repo-path=/data/pgbackup/pgbackrest/
backup-user=postgres
retention-full=4
process-max=4
log-path=/data/pgbackup/log/pgbackrest
[mirrorPg]
pg1-path=/var/lib/pgsql/14/data


postgresql.conf settings applicable to pgBackRest

 CONFIG FILE INCLUDES
#------------------------------------------------------------------------------

# These options allow settings to be loaded from files other than the
# default postgresql.conf.  Note that these are directives, not variable
# assignments, so they can usefully be given more than once.

#include_dir = '...'                    # include files ending in '.conf' from
                                        # a directory, e.g., 'conf.d'
#include_if_exists = '...'              # include file only if it exists
#include = '...'                        # include file


#------------------------------------------------------------------------------
# CUSTOMIZED OPTIONS
#------------------------------------------------------------------------------

# Add settings for extensions here
archive_command = 'pgbackrest --stanza=mirrorPg archive-push %p'
archive_mode = on
listen_addresses = '*'
log_line_prefix = ''
max_wal_senders = 3
wal_level = hot_standby[ CONFIG FILE INCLUDES
#------------------------------------------------------------------------------

# These options allow settings to be loaded from files other than the
# default postgresql.conf.  Note that these are directives, not variable
# assignments, so they can usefully be given more than once.

#include_dir = '...'                    # include files ending in '.conf' from
                                        # a directory, e.g., 'conf.d'
#include_if_exists = '...'              # include file only if it exists
#include = '...'                        # include file


#------------------------------------------------------------------------------
# CUSTOMIZED OPTIONS
#------------------------------------------------------------------------------

# Add settings for extensions here
archive_command = 'pgbackrest --stanza=mirrorPg archive-push %p'
archive_mode = on
listen_addresses = '*'
log_line_prefix = ''
max_wal_senders = 3
wal_level = hot_standby[

**Comment by pgstef** [comment]
``ìni
[global]
repo-path=/data/pgbackup/pgbackrest/
backup-user=postgres
retention-full=4
process-max=4
log-path=/data/pgbackup/log/pgbackrest

[mirrorPg]
pg1-path=/var/lib/pgsql/14/data
```

What is `/data/pgbackup/` ? A mount point ? That's your repository and you should be able to successfully reach it if you want that pgBackRest can do so too.

Btw, `backup-user` is the deprecated name for `repo1-host-user` which isn't needed since you're not using a repo-host in the provided config.

But again, I don't see any question from you so I don't understand what's your expectation here...

**Comment by dwsteele** [comment]
Looks to me like corruption in the repo. Is this repo stored on the local file system?
