### ISSUE TITLE
--help and --version on pgbackrest 2.54.0 showing permission denied

### ISSUE THREAD

**Issue by l00ptr** [pgbackrest/pgbackrest#2476]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.54.0

2. PostgreSQL version: None

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Debian 12

4. Did you install pgBackRest from source or from a package?

both from source and from package.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

nothing very important on those file, except they are owned by `postgres`:

```
ls -ahltr /etc/pgbackrest.conf 
-rw-r----- 1 postgres postgres 165 Oct 27 13:13 /etc/pgbackrest.conf
```
 
7. Describe the issue:

When running `pgbackrest --version` or `--help` and probably some other commands with another user than `root` or `postgres`, pgbackrest fails and display an error because it cannot read /etc/pgbackrest.conf (or /etc/pgbackrest/pgbackrest.conf).

``` console
simpeuser@66760f821821 $ pgbackrest --version
P00  ERROR: [041]: unable to open file '/etc/pgbackrest.conf' for read: [13] Permission denied
root@66760f821821:/home/runner# pgbackrest --version
pgBackRest 2.54.0
```

I think it's some kind of error / regression, it was possible to run those commands with another user (than root or the owner of the config files) on pbackrest 2.53.0 (and even before).

**Comment by dwsteele** [comment]
It's definitely a regression. We found it before packaging (but after the release) but decided to go ahead with packaging since it is not too severe but a bit tricky to fix. We don't want to make things worse with a hasty patch release.

Is this a showstopper for you or just something you noticed?

**Comment by l00ptr** [comment]
we have some failing tests on our side, even if don't use (or probably because) the default config file provided by the pgbackrest package.   

`pgbackrest server-ping` also shows the same error, i think in our case we can simply `rm`, `chown` or chmod the default /etc/pgbackrest.conf or /etc/pgbackrest/pgbackrest.conf... but i don't know if there are some potential side effects. 

Do you plan to fix this issue ?

**Comment by pgstef** [comment]
> Do you plan to fix this issue ?

Just to understand, what does prevent you to run those command with the appropriate user ? (aka the user who would need to run the backups or archiving commands)

**Comment by pgstef** [comment]
> in some situation we can't run those command with the owner of the /etc/pgbackrest.conf file. When you have a dedicated backup server (using SSH) and use a different user than `postgres` (which is the default owner of `/etc/pgbackrest.conf`).
> 
> Off course we can use `--config-path` has a workaround for most situations, but it doesn"t work in all cases (eg; `--version`, `--help` and i don't know if it's the case with some other sub-command).

When using a repo-host, the ssh connection is made between the 2 locally running pgBackRest processes. So you should always run pgBackRest on the DB server with the user who will run the backup/archive commands. And when using non-default config location then obviously you need to teach the commands where you stored your config. That doesn't seem to be a problem to me honestly.

And even if you use another user to login to the server, if that user can't sudo or access the config file, it won't even be able to run the info command. So I don't really buy your arguments here as having to run the pgBackRest command with the system user which will access the config/db/repo doesn't look bad to me.

> From my point of view, regarding the help and version commands, having to read /etc/pgbackrest.conf seems to contradict the principle of least privilege. Do we really need to read a config file to print the version and help ?

Having to use the system user which will ultimately run the commands doesn't look that bad to me. But I agree, that there could be valid cases where you would want to run the command with only command line options and no config file at all.

I'm mostly wondering why we didn't noticed that behavior earlier (I didn't to be honest). Anyway, as David mentioned, it's trickier to fix than it sounds.

**Comment by l00ptr** [comment]
> When using a repo-host, the ssh connection is made between the 2 locally running pgBackRest processes. So you should always run pgBackRest on the DB server with the user who will run the backup/archive commands. And when using non-default config location then obviously you need to teach the commands where you stored your config. That doesn't seem to be a problem to me honestly.

Ok, but there are some situation where users don't run postgres with the `postgres` user (or owner of the default pgbackrest config file). There are also some cases where users can run postgres servers with differents users (other than `postgres`) on the same host; So IMHO a "permission denied" error for basic command seems to be a bug in such contexts.

As a workaround we can change the permission on that file (this is what the RPM  PGDG packagers did); but i don't think it will fit all situation (eg; users can't store sensitive information there).

**Comment by pgstef** [comment]
> Ok, but there are some situation where users don't run postgres with the `postgres` user (or owner of the default pgbackrest config file). There are also some cases where users can run postgres servers with differents users (other than `postgres`) on the same host; So IMHO a "permission denied" error for basic command seems to be a bug in such contexts.

Still in that case, the process will need to connect to the local sockets. So permission management depends on the degree of complexity you add to your installation.

Anyway, I agree, failing to run the commands with missing config file looks like a pretty bad behavior change.

**Comment by dwsteele** [comment]
> pgbackrest server-ping also shows the same error, i think in our case we can simply rm, chown or chmod the default /etc/pgbackrest.conf or /etc/pgbackrest/pgbackrest.conf... but i don't know if there are some potential side effects.

server-ping needs to be able to read the conf file and I do not believe this is a change in behavior. If your config file is not readable to the user that is running pgbackrest and you are not using it, you should probably just remove it.

> Do you plan to fix this issue ?

Definitely yes. But as I said above we were hesitant to patch Debian specially or issue an immediate patch release for a somewhat tricky fix. So this fix will likely go into the November patch release, depending on how widespread the issues seems to be.

**Comment by dwsteele** [comment]
PR #2477 fixes this. Not entirely happy with the fix but the tests are solid so I'm willing to go forward with it. Comments welcome.

I'll leave this issue open for a while to make it more visible for others experiencing the same issue.

**Comment by l00ptr** [comment]
thx for your reactivity on this issue!

**Comment by pgstef** [comment]
> thx for your reactivity on this issue!

It would be great and helpful imho if you could try this PR and see if it fixes your problem ;-)
