### ISSUE TITLE
Backup with S3 config against GCS bucket failed

### ISSUE THREAD

**Issue by yixinzhangvv** [pgbackrest/pgbackrest#2482]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.48

3. PostgreSQL version:
4. 14

5. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

6. Did you install pgBackRest from source or from a package?

7. Please attach the following as applicable:

8. Describe the issue:

I was testing pgbackrest with s3 repo settings. Since I don't have access to aws bucket, I created a gcs bucket instead. But the backup failed. Here is the trace info:
version: 2.48
       command: backup
       options: --config-path=/backup --exec-id=1227-74711eb9 --log-level-console=trace --log-level-file=info --log-path=/obs/pgbackrest --pg1-path=/mnt/disks/pgsql/data --pg1-socket-path=/tmp --pg1-user=pgbackrest --repo1-bundle --repo1-path=/backups --repo1-retention-full=9999999 --repo1-s3-bucket=bugbash-backup --repo1-s3-endpoint=https://storage.googleapis.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --no-repo1-storage-verify-tls --repo1-type=s3 --stanza=db --type=full
       ```
       stack trace:
       common/io/http/request.c:httpRequestError:302:(this: {verb: DELETE, path: /backups/backup/db/latest, contentSize: 0, query: null, header: {content-length: '0', x-amz-content-sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', x-amz-date: <redacted>, host: 'bugbash-backup.storage.googleapis.com', authorization: <redacted>}}, response: {code: 404, reason: Not Found, contentChunked: false, contentSize: 201, contentRemaining: 0, closeOnContentEof: false, contentExists: true, contentEof: true, contentCached: true}, header: {content-type: 'application/xml; charset=UTF-8', content-length: '201', vary: 'Origin', x-guploader-uploadid: 'AHmUCY2cJm1KMcCACGqZgyYiXoj_Tj6iP5E3cyhyYnU5GcRx1XCJFiAidS6h04VACCPpWBZsVUI', date: 'Fri, 08 Nov 2024 21:34:58 GMT', expires: 'Fri, 08 Nov 2024 21:34:58 GMT', cache-control: 'private, max-age=0', server: 'UploadServer'}})
       storage/s3/storage.c:storageS3Response:(request: {verb: DELETE, path: /backups/backup/db/latest, contentSize: 0, query: null, header: {content-length: '0', x-amz-content-sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', x-amz-date: <redacted>, host: 'bugbash-backup.storage.googleapis.com', authorization: <redacted>}}, param.allowMissing: false, param.contentIo: false)
       storage/s3/storage.c:storageS3Request:(this: {StorageS3}, verb: {"DELETE"}, path: {"/backups/backup/db/latest"}, param.header: null, param.query: null, param.content: null, param.allowMissing: false, param.contentIo: false, param.sseKms: false, param.tag: false)
       storage/s3/storage.c:storageS3Remove:(this: {StorageS3}, file: {"/backups/backup/db/latest"}, param.errorOnMissing: false)
       storage/storage.c:storageRemove:(this: {type: s3, path: /backups, write: true}, fileExp: {"/backups/backup/db/latest"}, param.errorOnMissing: false)
       command/backup/backup.c:backupComplete:(infoBackup: {InfoBackup}, manifest: {Manifest})
       command/backup/backup.c:cmdBackup:(void)
       main.c:main:(debug log level required for parameters)
```

**Comment by yixinzhangvv** [comment]
After looking into the code, I think this error coming from this line:
https://github.com/pgbackrest/pgbackrest/blob/db912c049c7e4b98ec1cdfa5b4e45b3bbb7d1a6b/src/storage/s3/storage.c#L1156

DeleteRequest would fail with GCS when object is missing, thus gcs implementation has the allowMissing=true in its implementation:
https://github.com/pgbackrest/pgbackrest/blob/db912c049c7e4b98ec1cdfa5b4e45b3bbb7d1a6b/src/storage/gcs/storage.c#L1160

DeleteRequest success with S3 when object is missing, thus  s3 implementation doesn't has the allowMissing=true in its implementation:
https://github.com/pgbackrest/pgbackrest/blob/db912c049c7e4b98ec1cdfa5b4e45b3bbb7d1a6b/src/storage/s3/storage.c#L1156

I'm testing a special combination here with S3 implementation against a GCS bucket, thus wondering would it make sense to all the allowMissing flag to s3 endpoint as well?

We have customers want to use GCS bucket the same way as other S3 endpoints.

**Comment by dwsteele** [comment]
We don't have any plans to make the S3 driver work with GCS. GCS violates the S3 API in several areas (not just this one) and there are features we use that are not supported by the GCS XML API.

This is why we have a GCS driver which uses the JSON API and is enabled with `--repo-type=gcs`. Long story short -- use the GCS driver.

**Comment by yixinzhangvv** [comment]
Thanks for the response and suggestions. Will seek another way from our side.

**Comment by dwsteele** [comment]
What is the use case here anyway? Why not just use the provided GCS driver?

**Comment by dwsteele** [comment]
Searching around on Google this looks like it might be a linking error. Are you building from source?

**Comment by yixinzhangvv** [comment]
Thanks, I was able to make it work after setup the Zenko CloudServer to have SSL: https://s3-server.readthedocs.io/en/latest/GETTING_STARTED.html#using-ssl.
