### ISSUE TITLE
When performing incremental backups, enabling delta io is very high

### ISSUE THREAD

**Issue by 1053531172** [pgbackrest/pgbackrest#2484]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.47

2. PostgreSQL version:
13.16

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
 CentOS Linux release 7.2.1511
4. Did you install pgBackRest from source or from a package?
source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
My instance data is approximately 3 t，When performing incremental backups, enabling delta io is very high.Will pgbackbrest continue to read data from pg when this parameter is enabled? Do we not need to enable this parameter when doing incremental backups?

**Comment by dwsteele** [comment]
A delta backup will checksum every file as documented here: https://pgbackrest.org/configuration.html#section-general/option-delta. So yes, this will take longer.

If you are looking for block incremental, then you want the repo-block feature, although I would not use that feature on such an old version. RHEL 7 is EOL and they stopped building pgbackrest for it last year.

**Comment by 1053531172** [comment]
> A delta backup will checksum every file as documented here: https://pgbackrest.org/configuration.html#section-general/option-delta. So yes, this will take longer.
> 
> If you are looking for block incremental, then you want the repo-block feature, although I would not use that feature on such an old version. RHEL 7 is EOL and they stopped building pgbackrest for it last year.

Okay, I understand. I really feel your response.
