### ISSUE TITLE
compress-type=none looks doesn't work

### ISSUE THREAD

**Issue by zhihuiFan** [pgbackrest/pgbackrest#2485]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.47

2. PostgreSQL version:
PostgreSQL 12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

CentOS 7

4. Did you install backrest from source or from a package?

Not sure.  Probably build from source. 

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)   only one entry about compress, it is compress-type = none. 
 

7. Describe the issue:
I find the following stack which confused me a lot. 

As we can see the in the call of achivePushFile, **the compressType is None already, however we still see the gzCompressProcess then.**  Is there anything I understand wrong?

**Comment by zhihuiFan** [comment]
Add the missed photo: 

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/8d382d70-45c3-4dba-9f42-88a4bb4ea419">

**Comment by dwsteele** [comment]
I'm not sure how you are getting this. With gz compression in HEAD I see:
```
P00  DEBUG:     command/archive/push/file::archivePushFile: (walSource: {"/var/lib/postgresql/15/demo/pg_wal/00000001000000000000000A"}, headerCheck: true, modeCheck: true, pgVersion: 150000, pgSystemId: 7436102061201604772, archiveFile: {"00000001000000000000000A"}, compressType: 2, compressLevel: 3, repoList: *void, priorErrorList: {[]})
```
And with no compression:
```
P00  DEBUG:     command/archive/push/file::archivePushFile: (walSource: {"/var/lib/postgresql/15/demo/pg_wal/000000010000000000000010"}, headerCheck: true, modeCheck: true, pgVersion: 150000, pgSystemId: 7436102061201604772, archiveFile: {"000000010000000000000010"}, compressType: 0, compressLevel: 3, repoList: *void, priorErrorList: {[]})
```
I doubt this is different in 2.47 but I'm not going to take the time to test it . Perhaps your debug symbols are mistatched? Also, you are running an older version of pgBackRest on an EOL version of RHEL.

**Comment by zhihuiFan** [comment]
I have figured out the reason. The fact is if we want to disable compression (for less CPU usage), we need both compress=none and compress-level-network=0, the later one is missed when I opened this issue.

**Comment by dwsteele** [comment]
Ah, I see. Since you did not include any config info I did not realize you were operating with a remove.

Disabling protocol compression is probably a bad idea. It is easy to flood your network. In the next release (more than likely) we will be moving protocol compression to lz4 to increase performance.
