### ISSUE TITLE
Backup From Standby - Why it works even repo1 related information is not set in Standby

### ISSUE THREAD

**Issue by evan-dayy** [pgbackrest/pgbackrest#2487]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: Latest

2. PostgreSQL version: 15.5.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

 A repository host server;
 One Primary Database Server;
 Multiple Standby Database Server;

4. Did you install pgBackRest from source or from a package?

 From Source.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
My question is that when I want to take a backup from standby, it seems that standby doesn't need any repo / pg1 related information. My configuration looks like:

For Repo Server Pod:
- we have all pg1 / pg2 / tls-server / tls-client / repo1 configuration;
```
[db]
pg1-path=/mnt/disks/pgsql/data
pg1-socket-path=/tmp
pg1-user=pgbackrest
pg1-host=34.118.224.75
pg1-host-ca-file=....
pg1-host-cert-file=....
pg1-host-key-file=....
pg1-host-type=tls
pg2-path=/mnt/disks/pgsql/data
pg2-socket-path=/tmp
pg2-user=pgbackrest
pg2-host=34.118.224.28
pg2-host-ca-file=...
pg2-host-cert-file=....
pg2-host-key-file=....
pg2-host-type=tls

[global]
backup-standby=y
log-path=/backup/logs
log-level-file=info

tls-server-address=*
tls-server-auth=...=*
tls-server-ca-file=...
tls-server-cert-file=....
tls-server-key-file=....

repo1-path=/backup/repo
repo1-retention-full=9999999
repo1-bundle=y
```

For Primary Pod:
- we have pg1, repo1 / tls-server / tls-client / achiveconfig

```
[global:archive-push]
compress-level=3
process-max=2
archive-async=y
spool-path=/tmp/spool/pgbackrest

[db]
pg1-path=/mnt/disks/pgsql/data
pg1-socket-path=/tmp
pg1-user=pgbackrest

[global]
log-path=/obs/pgbackrest
log-level-file=detail
repo1-path=/backup/repo
repo1-retention-full=9999999
repo1-bundle=y
repo1-host=34.118.224.102
repo1-host-ca-file=...
repo1-host-cert-file=...
repo1-host-key-file=...
repo1-host-type=tls
tls-server-address=*
tls-server-auth=...=*
tls-server-ca-file=...
tls-server-cert-file=...
tls-server-key-file=...

```

For Standby Pod:
- I only set up the server-related config

```
[global]
tls-server-address=*
tls-server-auth=...=*
tls-server-ca-file=...
tls-server-cert-file=...
tls-server-key-file=...
```

But it seems the backup from standby works! why is that? I am thinking the standby need the repo1 related config to know where to send the data. but it seems that even repo1 is not set in the standby, the back for standby still works.

Thanks,

**Comment by pgstef** [comment]
> But it seems the backup from standby works! why is that? I am thinking the standby need the repo1 related config to know where to send the data. but it seems that even repo1 is not set in the standby, the back for standby still works.

That's because the standby doesn't push anything and you don't run any command there (yet). The pg-path and repo location are needed for i.e. the archive-push command which is run on the primary PG node by archive_command.

David might correct me on this if I'm wrong but AFAIK the backup command executed from the repo-host will start processes on the PG node remotely (through ssh or in your case through the tls server) and pass the pg-path to look for (as it is defined in the repo host config). If you look at the DEBUG log, you'll see lots of `{type: remote, path:/mnt/disks/pgsql/data, write: false}`.

**Comment by dwsteele** [comment]
> That's because the standby doesn't push anything and you don't run any command there (yet). The pg-path and repo location are needed for i.e. the archive-push command which is run on the primary PG node by archive_command.

Exactly, but if there is a failover archiving will not longer work. So you need to keep your standby configured as if it were a primary -- because it might be one someday.

**Comment by evan-dayy** [comment]
Thank you guys so much!! This is super helpful! 

Previously, I assume standby needs repo's configuration (the client key and certificate) to send the data back to the repo server. But it is not the case?  Actually it is using repo server's certificate to encrypt?

**Comment by pgstef** [comment]
> Previously, I assume standby needs repo's configuration (repo1-host--ca/cert/key, the client key and certificate) to send the data back to the repository host. But it is not the case? Actually it is using repository host's certificate to encrypt?

Again, this configuration will be needed when you'll run commands on the standby. The backup is running from the repo-host, so it connects to the standby server using the TLS connection and trigger local process there. Nothing is pushed by the standby itself at this point.
But as mentioned by David, as soon as you'll failover and try to push archives, it will fail unless your configuration is the same as the primary.
