### ISSUE TITLE
restore specified wal

### ISSUE THREAD

**Issue by glushakov** [pgbackrest/pgbackrest#2491]
Hi.
Sometimes it is necessary to restore a set of wal segments (for example, when they have already been deleted, but are needed for a logical replication slot) in running cluster.

This can be done with the standard manual executeion command "pgbackrest archive-get" by specifying the necessary file and directory for restoration.
Is this a suitable(safely) method or is there a more reliable one that will allow to restore a set of wal (range)?

Thanks

**Comment by dwsteele** [comment]
Generally Postgres does this for you via `restore_command`. There's no way to manually recover a range of WAL without calling `archive-get` multiple times.

If you are not doing recovery (in which case Postgres will take care of this) then what is your use case?

**Comment by glushakov** [comment]
We use patroni and its ability to synchronize logical replication slots on a standby host.
But in rare cases after a double failover and pg_rewind, a situation may arise that the wal segments are deleted before the slot is synchronized and logical replication stops working.

For such cases, we would like to have an algorithm for manually restoring the required wal from the archive on the primary node, without re-creating the slot.

**Comment by dwsteele** [comment]
Well, you can certainly use `archive-get` for this, but you'll need to wrap it to get the range you need.

**Comment by glushakov** [comment]
Thanks for your help!

**Comment by dwsteele** [comment]
My 2c  -- if you get into this situation it would probably be easier to run a delta restore than rely on pg_rewind.
