### ISSUE TITLE
Not able to access data in Cohesity S3 by pgbackrest, while s3cmd works fine

### ISSUE THREAD

**Issue by plamenk** [pgbackrest/pgbackrest#2495]
[pg-repo-ls.txt](https://github.com/user-attachments/files/17903161/pg-repo-ls.txt)
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.47

3. PostgreSQL version: PostgreSQL 15.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18), 64-bit

4. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Red Hat Enterprise Linux 8.8 (Ootpa) (part of OpenShift 4.14.38

5. Did you install pgBackRest from source or from a package? Crunchy Postgres for Kubernetes, 5.4.2 provided by Crunchy Data

6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Hello,
I am trying to switch from working AWS S3 set-up to a Cohesity S3 local set-up. pgbackrest repo-ls returns ERROR: [039]: HTTP request failed with 403 (Forbidden). Very similar to #1623 . But, the s3cmd from (another host, as I cannot install it in the container) with the same access & secret keys) works fine. I let the Cohesity admon to double-check that the worker hosts where the pgbackrest request come from are whitelisted. I am providing the command I test with (current set-up is for the AWS S3 and is working [fine).]([url]([pg-repo-ls.txt](https://github.com/user-attachments/files/17903146/pg-repo-ls.txt)))
Many thanks for your help.
Plamen

**Comment by dwsteele** [comment]
Not much to go on here since you did not supply the requested configuration files, but generally with S3 clones you need to set `repo1-s3-uri-style=path`. See https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-uri-style.

**Comment by dwsteele** [comment]
> I did not provide the configuration files, as they are set up towards AWS

Yeah, that's not too useful since it is not the config you are currently using.

But if your new config looks anything like this it is not going to work:
```
repo1-s3-endpoint = s3.eu-central-1.amazonaws.com/392154716686-oncite-backup-devel
```
You've appended a path to the host but we don't support this. This came up elsewhere recently (#2473) but I can't find anywhere in the S3 docs where a path is allowed in the endpoint.

We'd be willing to add it if somebody can point to the relevant documentation.

**Comment by plamenk** [comment]
Many thanks for the valuable heads hints. It is working now. Important points were:
- repo1-s3-uri-style=path
- Taking out the bucket as path from the endpoint, even if AWS S3 accepts it
- Using the configuration file, opposed to the command line

**Comment by dwsteele** [comment]
> Taking out the bucket as path from the endpoint, even if AWS S3 accepts it

Do you mean this configuration (endpoint with path) worked on S3 with pgbackrest or that it worked with awscli?

awscli is based on boto3, which supports non-standard options for s3 clones. We tend to stick to only what is documented for S3.

**Comment by plamenk** [comment]
Yes, the linked config file has been used for the backups for the past months. We are going to switch to the local S3 now (without the bucket in the uri of endpoint).

**Comment by dwsteele** [comment]
> Yes, the linked config file has been used for the backups for the past months.

OK, the path portion gets stripped off the endpoint so it was never being used on S3 at all.
