### ISSUE TITLE
Pgbackrest install  error: ‘OPENSSL_INIT_LOAD_CONFIG’ undeclared 

### ISSUE THREAD

**Issue by jasonchenTJ** [pgbackrest/pgbackrest#2496]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgbackrest-release-2.54.0

2. PostgreSQL version:
PG17.2 

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Red Hat Enterprise Linux Server release 7.9 (Maipo)

4. Did you install pgBackRest from source or from a package?
from source code

Install Error:

INFRA [postgres@dc02psqldbuat04 src]# sudo make install
gcc -std=gnu11   -std=c99 -Wall -Wextra -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-clobbered -O2 -D_POSIX_C_SOURCE=200809L -I. -I/opt/pgsql-17/include -I/usr/include/libxml2   -I. -I. -c -o .build/common/crypto/common.o common/crypto/common.c -MMD -MP -MF .build/common/crypto/common.dep
common/crypto/common.c: In function ‘cryptoInit’:
common/crypto/common.c:63:9: warning: implicit declaration of function ‘OPENSSL_init_ssl’ [-Wimplicit-function-declaration]
         OPENSSL_init_ssl(OPENSSL_INIT_LOAD_CONFIG, NULL);
         ^
common/crypto/common.c:63:26: error: ‘OPENSSL_INIT_LOAD_CONFIG’ undeclared (first use in this function)
         OPENSSL_init_ssl(OPENSSL_INIT_LOAD_CONFIG, NULL);
                          ^
common/crypto/common.c:63:26: note: each undeclared identifier is reported only once for each function it appears in
common/crypto/common.c: At top level:
cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough" [enabled by default]
make: *** [.build/common/crypto/common.o] Error 1

OPENSSL version: 

INFRA [postgres@dc02psqldbuat04 src]# rpm -qa | grep openssl
openssl-1.0.2k-26.el7_9.x86_64
openssl-libs-1.0.2k-26.el7_9.x86_64
xmlsec1-openssl-1.2.20-8.el7_9.x86_64
openssl-devel-1.0.2k-26.el7_9.x86_64

Thanks
Jason

**Comment by dwsteele** [comment]
OpenSSL 1.02 has been EOL for five years and we no longer support it as of cf8625d24bd95.

**Comment by jasonchenTJ** [comment]
@dwsteele  Big thanks, David! Have a good day! :)
