### ISSUE TITLE
Run two repos in parallel?

### ISSUE THREAD

**Issue by chlordk** [pgbackrest/pgbackrest#2499]
Hi

I have a setup with repo-1 which is local from pg-server to another one standing next to it, and a repo-2 remote s3 backup. Both of them running full backup in the weekend and incremental the other days. Raw db-file-size i 1.8TB.

Repo-1 full takes **18 hours** on Saturday. Incremental takes 1 hour all the other week days.

Repo-2 full takes **28 hours** on Sunday. Incremental has not been run yet but expected to be 1½ hour.

It seems like two pgbackrest backup can't run at the same time. Is this correctly understood?

So the solution is to schedule the two repo's to run backup in sequential manner, one after the other? Is there other solutions?

Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.54.0

2. PostgreSQL version:
17.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
PostgreSQL-server: Ubuntu 20.04.6 
Pgbackrest-server: Ubuntu 20.04.6
S3-server: Remote

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

[prod]
pg1-path=/global/data/postgresql/12/main

[global]
log-level-console=info
log-level-file=debug
delta=y

# Repo 1
repo1-host=pgb101
repo1-host-user=pgbackrest

# repo 2
repo2-retention-full=1
repo2-path = /prod
repo2-block=y
repo2-bundle = y
repo2-retention-full-type = count
repo2-s3-uri-style = path
repo2-storage-ca-file = /etc/pgbackrest/conf.d/s3-ca-certificate.crt
repo2-storage-verify-tls = y
repo2-s3-bucket = main
repo2-s3-endpoint = https://e.example.com
repo2-s3-region = us-east-1
repo2-type = s3
repo2-s3-key=X
repo2-s3-key-secret=X

7. Describe the issue:

**Comment by pgstef** [comment]
> It seems like two pgbackrest backup can't run at the same time. Is this correctly understood?

If I remember correctly, we changed that in 2.53. See [this PR](https://github.com/pgbackrest/pgbackrest/pull/2389).

Although your config is a bit weird, you're using `repo-host` for repo 1 and direct storage for repo 2. So it becomes complicated to know where to trigger the backup command. You should consider to define your s3 storage on the repo host too imho. That would be easier for you to manage from a configuration point of view and for triggering the backup commands.

> So the solution is to schedule the two repo's to run backup in sequential manner, one after the other? Is there other solutions?

Remember that if you run both backups in //, you'll consume more resources on your cluster to read the data files (and on the host running the backup command). So sometimes running things simultaneously is slowing things down and it would be better to have different schedules.

**Comment by pgstef** [comment]
> I can understand the "repo-host" but what do you mean with "direct storage"?

Directly attached storage. Like nfs, s3, azure,...

> Current situation is now that I have no backup since 2024-11-27, which is **a bit critical**.

Well you added this weird hybrid config. But if you have an old backup and WAL archives, you still have a valid backup, just a slower one to recover.

> pgbackrest@pprodsyngyps101:~$ pgbackrest --stanza=prod backup --repo=1 --type=incr
> 2024-11-29 07:09:54.050 P00  ERROR: [082]: WAL segment 0000000100000E4600000044 was not archived before the 60000ms timeout
> HINT: check the archive_command to ensure that all options are correct (especially --stanza).
> HINT: check the PostgreSQL server log for errors.
> HINT: run the 'start' command if the stanza was previously stopped.

As the HINT mentions, have you checked the PostgreSQL logs to find out if there are any WAL archiving issue?
If there's no WAL archiving issue, it means the WAL archive didn't hit the s3 repo within the 60s timeout.
So you'd need to check the archiving speed and find out if adding async archiving or raising that timeout would help you.

> After adding S3 to the config I have not changed the `archive_command` on the postgresql server

If you changed the pgbackrest config, you changed the archive_command behavior as it relies on that config too.

> [prod]
> pg1-host=prodsyngyps100
> pg1-path=/global/data/postgresql/12/main
> [global]
> start-fast=y
> repo1-path=/var/lib/pgbackrest
> repo1-retention-full=1
> repo1-block=y
> repo1-bundle=y
> repo2-retention-full=1
> repo2-path = /prod
> repo2-block=y
> repo2-bundle = y
> repo2-retention-full-type = count
> repo2-s3-uri-style = path
> repo2-storage-ca-file = /etc/pgbackrest/conf.d/s3-ca-certificate.crt
> repo2-storage-verify-tls = y
> repo2-s3-bucket = phi
> repo2-s3-endpoint = https://e.example.com
> repo2-s3-region = us-east-1
> repo2-type = s3
> repo2-s3-key = redacted
> repo2-s3-key-secret = redacted

> [prod]
> pg1-path=/global/data/postgresql/12/main
> [global]
> log-level-console=info
> log-level-file=debug
> delta=y
> repo1-host=pprodsyngyps101
> repo1-host-user=pgbackrest
> repo2-retention-full=4
> repo2-path = /prod
> repo2-block=y
> repo2-bundle = y
> repo2-retention-full-type = count
> repo2-s3-uri-style = path
> repo2-storage-ca-file = /etc/pgbackrest/conf.d/s3-ca-certificate.crt
> repo2-storage-verify-tls = y
> repo2-s3-bucket = phi
> repo2-s3-endpoint = https://e.example.com
> repo2-s3-region = us-east-1
> repo2-type = s3
> repo2-s3-key = redacted
> repo2-s3-key-secret = redacted

Why are you using `repo2-type=s3` on both postgres and backup server rather than using `repo2-host`?

> Any hint very much appreciated

At this point the only error message you've shown is a WAL archiving issue.
As mentioned above, look at the Postgres logs and make sure the `check` command is working (from both postgres and backup server).

**Comment by chlordk** [comment]
> Why are you using repo2-type=s3 on both postgres and backup server rather than using repo2-host?

It looks like I have misconfigured the serveres. My goal was to run a local backup for weekly retention backup and a S3 backup with 4 weeks retention. I have looked around but did not find any description of a combination of two repos, and one of them is S3. So is actually possible?

Anyway, my primary problem is that I don't have a backup right now, so I'll try to solve that first.

In postgresql log it sometimes (not always) says:

> ERROR: [104]: archive-push command encountered error(s):

The error message when running backup:

> pgbackrest@pprodsyngyps101:~$ pgbackrest --stanza=prod backup --repo=1 --type=incr
2024-11-29 09:55:06.636 P00  ERROR: [082]: WAL segment 0000000100000E4600000079 was not archived before the 60000ms timeout
                                    HINT: check the archive_command to ensure that all options are correct (especially --stanza).
                                    HINT: check the PostgreSQL server log for errors.
                                    HINT: run the 'start' command if the stanza was previously stopped.

It seems like the archiving was not running fast enough.
So now I tried to uncomment everything about S3 and then the pg-log showed it was running a lot archive-push, so they might have piled up in the background.

I then started the backup again and now **it is running**:

> pgbackrest@pprodsyngyps101:~$ pgbackrest info --stanza=prod
stanza: prod
>    status: ok (backup/expire running - 5.71% complete)

My plan is now to wait for the full backup is completed on Monday. Then figure out exactly how this dual-repo local/S3 pgbackrest should be configured.

It seems like if I'm only running S3 it would actually work.

Just for the record, there was this error in the logfile:

> 2024-11-29 08:18:38.966 P00  ERROR: [104]: archive-push command encountered error(s):
>                                    repo2: [ProtocolError] HTTP request failed with 409 (Conflict):
> (?xml version="1.0" encoding="UTF-8"?) (Error)(Code)BucketAlreadyExists(/Code)(Message)The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
> 2024-11-29 08:18:38.966 P00   INFO: archive-push command end: aborted with exception [104]
2024-11-29 08:18:39.070 CET [1585] LOG:  archive command failed with exit code 104
2024-11-29 08:18:39.070 CET [1585] DETAIL:  The failed archive command was: pgbackrest --stanza=prod archive-push pg_wal/0000000100000E4300000090
2024-11-29 08:18:40.081 P00   INFO: archive-push command begin 2.54.0: [pg_wal/0000000100000E4300000090] --exec-id=1111575-6123fb48 --log-level-console=info --log-level-file=debug --pg1-path=/global/data/postgresql/12/main --repo1-host=pprodsyngyps101 --repo1-host-user=pgbackrest --repo2-path=/prod --repo2-s3-bucket=phi --repo2-s3-endpoint=https://rossak.v2v.dk --repo2-s3-key=<redacted> --repo2-s3-key-secret=<redacted> --repo2-s3-region=us-east-1 --repo2-s3-uri-style=path --repo2-storage-ca-file=/etc/pgbackrest/conf.d/s3-ca-certificate.crt --repo2-storage-verify-tls --repo2-type=s3 --stanza=prod
2024-11-29 08:18:44.142 P00   WARN: WAL file '0000000100000E4300000090' already exists in the repo1 archive with the same checksum
                                    HINT: this is valid in some recovery scenarios but may also indicate a problem.
2024-11-29 08:18:44.142 P00   INFO: pushed WAL file '0000000100000E4300000090' to the archive
2024-11-29 08:18:44.243 P00   INFO: archive-push command end: completed successfully (4163ms)

As this was several hours ago it is a periodic failure and it also made a retry which was successful.

**Comment by pgstef** [comment]
> It looks like I have misconfigured the serveres. My goal was to run a local backup for weekly retention backup and a S3 backup with 4 weeks retention. I have looked around but did not find any description of a combination of two repos, and one of them is S3. So is actually possible?
> 
> Anyway, my primary problem is that I don't have a backup right now, so I'll try to solve that first.

I already answered that in my previous answer. Yes it is possible but it needs to be configured correctly and requires a bit of expertise and knowledge on how to do it. Long story short, use repo2-host on the postgres node and repo2-type=s3 on the repository host.

**Comment by chlordk** [comment]
We have decided only to use one repo.
And 28 hours for a full backup was too long so we will keep the local repo.
Anyway, now we know it is possible.
Thanks for help.
