### ISSUE TITLE
pgbackrest and spool path for more instance postgresql

### ISSUE THREAD

**Issue by joyful88** [pgbackrest/pgbackrest#2505]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.51

2. PostgreSQL version: 15

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
[db1]
[db2]
[db3]
[db4]
[db5]
[db6]
[db7]
...

5. Did you install pgBackRest from source or from a package?
install from apt repo
6.
[cmdb_adapter]
pg1-path=/pgdata_cmdb_adapter
pg1-user=postgres
pg1-port=54325

[ftdeals]
pg1-path=/pgdata_ftdeals
pg1-user=postgres
pg1-port=54322

[krpc_mock_adapter]
pg1-path=/pgdata_krpc_mock_adapter
pg1-user=postgres
pg1-port=54324

[smftb_slife_catalog]
pg1-path=/pgdata_smftb_slife_catalog
pg1-user=postgres
pg1-port=54327

[sonarqube_1c]
pg1-path=/pgdata_sonarqube_1c
pg1-user=postgres
pg1-port=54320

[srss]
pg1-path=/pgdata_srss
pg1-user=postgres
pg1-port=54328
#spool-path=/var/lib/postgresql/srss_spool/
#archive-async=y
#process-max=3

[standard_checker]
pg1-path=/pgdata_standard_checker
pg1-user=postgres
pg1-port=54321

[superset_analytics]
pg1-path=/pgdata_superset_analytics
pg1-user=postgres
pg1-port=54329

[taskevent]
pg1-path=/pgdata_taskevent
pg1-user=postgres
pg1-port=54323

[global]
repo1-host=10.23.2.253
repo1-host-user=backrest
process-max=4
log-level-file=detail

7. Describe the issue:
I have 10 separate postgresql instances on one machine. For one instance you need to set spool-path, but the setting is global, I don’t want to use it for other database instances. If I specify the setting for one database, then archiving is simply interrupted. Tell me what should I do?

**Comment by pgstef** [comment]
> asynchronous send via reel

What does that mean?

> HINT: check the PostgreSQL server log for errors.

What's the error there and what's the configuration used?

**Comment by joyful88** [comment]
I want to enable asynchronous sending, here are my settings

[allure_testops_prod]
pg1-path=/pgdata_allure_testops_prod
pg1-user=postgres
pg1-port=54329

[be_happy_strapi]
pg1-path=/pgdata_be_happy_strapi
pg1-user=postgres
pg1-port=54327

[bim_storage]
pg1-path=/pgdata_bim_storage
pg1-user=postgres
pg1-port=54322

[bim_task_planner]
pg1-path=/pgdata_bim_task_planner
pg1-user=postgres
pg1-port=54325

[notifier]
pg1-path=/pgdata_notifier
pg1-user=postgres
pg1-port=54324

[slimon]
pg1-path=/pgdata_slimon
pg1-user=postgres
pg1-port=54320

[global]
repo1-host=10.23.2.253
repo1-host-user=backrest
process-max=4
log-level-file=detail
spool-path=/var/spool/pgbackrest
log-path=/var/log/pgbackrest
archive-async=y

archive_command in postgresql - 'pgbackrest --stanza=[name] archive-push %p';

the postgresql log displays the error ERROR: [082]: unable to push WAL file '0000000100000BAA00000092' to the archive asynchronously after 60 second(s)
       HINT: check '/var/log/pgbackrest/allure_testops_prod-archive-push-async.log' for errors.
but the file is not created

**Comment by joyful88** [comment]
I checked on version 2.54.0 this error does not occur again. I'll probably update
