### ISSUE TITLE
archive-push async questions

### ISSUE THREAD

**Issue by nms9403** [pgbackrest/pgbackrest#2506]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.54.0
2. PostgreSQL version:
15
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
4. Rocky 8

5. Did you install pgBackRest from source or from a package?
package
6. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Hello,

I want to confirm my understanding of the archive-push process in async mode and ask a related question.

My Understanding:
When using archive-push in async mode, pgBackRest creates a queue for .ready WAL files and sends them to the repository in parallel using a background process.
Once the WAL files are added to the queue, pgBackRest returns success to the archive_command before the actual transfer to the repository is completed.
The archive-push async mode does not copy WAL files to any temporary directory or perform additional storage operations other than managing the background process for repository transfers.
Is my understanding correct?

My Question:
If my understanding is correct, I’m curious about the following scenario:

If WAL files are generated rapidly, and due to network delays, the background process is significantly slower in transferring the WAL files to the repository, PostgreSQL might mark the WAL files as .done after receiving success from the archive_command. PostgreSQL could then potentially reuse these WAL files.

In such a situation:

Would the untransferred WAL files be reused and thus unable to be archived?
Does pgBackRest have any mechanism to handle this kind of issue?
Or, is there a misunderstanding in my understanding of how archive-push works?

Thank you for your clarification!

**Comment by pgstef** [comment]
Hi,

That's not how it works. See https://pgbackrest.org/user-guide.html#async-archiving/async-archive-push and https://pgbackrest.org/configuration.html#section-general/option-spool-path.

Every time Postgres runs `archive_command` (let's say to archive `000000010000000200000003`), pgBackRest will spawn async processes (based on `process-max`) to look into the archive_status directory for `.ready` files (let's say `000000010000000200000004.ready`) and already push that one to the repository.

Once written in the repository, the process would create an ack file in `spool-path` (typically `000000010000000200000004.ok`). So the next time Postgres will run the `archive_command` (to ask to archive `000000010000000200000004`), as it would already be done, pgBackRest will check for the `.ok` file and answer very fast to Postgres, so Postgres can continue and ask for the other one, etc.

While Postgres asks to archive `000000010000000200000004`, in the background, pgBackRest would already handle `000000010000000200000005` if it is `.ready`... So it is a very good way to speed up the archive_command using multiple processes in //.

If the `.ok` file disappears, before trying to push the archive to the repository, pgBackRest would look if it already exists or not. So the ack file avoids a repository lookup.

> If WAL files are generated rapidly, and due to network delays, the background process is significantly slower in transferring the WAL files to the repository, PostgreSQL might mark the WAL files as .done after receiving success from the archive_command.

As we don't use a temporary local buffer anymore and directly push from pg_wal to the repository, the foreground and background processes shouldn't see very much difference and Postgres would never receive "ok" if the WAL isn't properly archived.

If you want the implementation details, see https://github.com/pgbackrest/pgbackrest/blob/main/src/command/archive/push/push.c#L305.

The local queue you're probably referring to is for `archive-get` and Postgres `restore_command` to speed-up the recovery. But that's a totally different story.

Kind Regards

**Comment by nms9403** [comment]
Hi, pgstef
I'm sorry, but there's still something I don't fully understand.

Suppose WAL files 00000001 to 00000009 are in the .ready state. When the archive_command tries to archive the 00000001 file, I understand that archive-push starts asynchronous processes for .ready files 1 to 9 based on process-max and begins transferring them.

In this case, does the success of the archive_command for file 00000001 return only after the corresponding 00000001.ok is created in the spool path, or does it wait until the transfer of all files from 00000001 to 00000009 is successfully completed and return success for archive_command?

**Comment by pgstef** [comment]
> Suppose WAL files 00000001 to 00000009 are in the .ready state. When the archive_command tries to archive the 00000001 file, I understand that archive-push starts asynchronous processes for .ready files 1 to 9 based on process-max and begins transferring them.
> 
> In this case, does the success of the archive_command for file 00000001 return only after the corresponding 00000001.ok is created in the spool path, or does it wait until the transfer of all files from 00000001 to 00000009 is successfully completed and return success for archive_command?

With `process-max=2`, the foreground process should push 00000001 to the repository and return success code to `archive_command`, and a background process would push 00000002 to the repository and write 00000002.ok in the spool-path. Then, `archive_command` would ask for 00000002, pgBackRest would see 00000002.ok and return success code to `archive_command`.

It's sequential, 1 file at a time from Postgres point-of-view. You can read the source code to get the details or try by your own with reading the logs, that's often quite useful to understand what's going on.

**Comment by pgstef** [comment]
If you don't have any more question, we can probably close this issue. Don't hesitate to re-open it if you have further questions.

Kind Regards
