### ISSUE TITLE
chown and chmod options on backups, owner

### ISSUE THREAD

**Issue by cryptofuture** [pgbackrest/pgbackrest#257]
I have `backup-user=username` in pgbackrest.conf, but pgbackrest makes backups with postgres owner:group anyway.  
Username is in postgres group. More above I didn't found config options to make folders 755 and specify rights on backups files.

**Comment by dwsteele** [comment]
The `backup-user` option is for use in conjunction with the `backup-host` option:
http://www.pgbackrest.org/configuration.html#section-backup/option-backup-user

If you are backing up locally then permissions will always be for the user that ran pgBackRest.

**Comment by cryptofuture** [comment]
Thanks. Seems like I just need to move cron jobs from postgres user to username. But what about files (packed wars?) in archive folder, is this folder vital for backup, or only backup folder?

**Comment by dwsteele** [comment]
The backup process on the db server needs to run as postgres (or whatever user the db was created as).  This is a limitation of postgres itself, though it is something we are working on.

As for completion target, it's not possible to do what you are asking.  Postgres does not provide the required information.  One more checkpoint a day should not make a difference and if it does then using `start-fast=y` is probably not a good idea.  `stop-auto` does not have any performance implications, though, so it is safe to use even on a busy system.

**Comment by cryptofuture** [comment]
Really, thanks for answers, and for what you doing.
