### ISSUE TITLE
pg_xlogs linked to another partition

### ISSUE THREAD

**Issue by gintoddic** [pgbackrest/pgbackrest#258]
We are trying to link our pg_xlogs to another partition which is on SSDs. Problem is pgbackrest doesn't seem to like the link to it. Is there any way around that?

2016-09-15 01:02:11.190 P00  ERROR: [145]: link '/dbdata/postgres/9.5-prod/pg_tblspc/16400' -> '/dbdata-aux' cannot reference another link

**Comment by dwsteele** [comment]
It looks like you may have changed a tablespace link instead of pg_xlog link.  In any case, pgbackrest does not allow links to links - each link in $PGDATA must reference a directory.

Can you provide:
```
ls -lah $PGDATA
ls -lah $PGDATA/pg_tblspc
```

**Comment by gintoddic** [comment]
-bash-4.1$ cd /dbdata/postgres/9.5-prod/
-bash-4.1$ ls -trl
total 632
-rw------- 1 postgres postgres      4 Mar 24 15:52 PG_VERSION
drwx------ 2 postgres postgres   4096 Mar 24 15:52 pg_twophase
drwx------ 2 postgres postgres   4096 Mar 24 15:52 pg_snapshots
drwx------ 2 postgres postgres   4096 Mar 24 15:52 pg_serial
drwx------ 2 postgres postgres   4096 Mar 24 15:52 pg_replslot
drwx------ 4 postgres postgres   4096 Mar 24 15:52 pg_logical
drwx------ 2 postgres postgres   4096 Mar 24 15:52 pg_dynshmem
drwx------ 2 postgres postgres   4096 Mar 24 15:52 pg_commit_ts
-rw------- 1 postgres postgres     88 Mar 24 15:52 postgresql.auto.conf
-rw------- 1 postgres postgres   1636 Mar 24 15:52 pg_ident.conf
drwx------ 4 postgres postgres   4096 Mar 24 16:03 pg_multixact
-rw-r--r-- 1 postgres postgres   3406 Mar 24 17:39 server.req
-rw------- 1 postgres postgres   1675 Mar 24 17:39 server.key
-rw-r--r-- 1 postgres postgres   4254 Mar 24 17:39 server.crt
drwx------ 9 postgres postgres   4096 Mar 24 18:03 base
drwx------ 2 postgres postgres   4096 Jul  6 20:57 pg_tblspc
drwx------ 3 postgres postgres 385024 Jul 24 21:59 pg_xlog_bkup
-rw-r--r-- 1 postgres postgres    715 Jul 24 22:45 recovery.conf.bak
-rw-r--r-- 1 postgres postgres    219 Aug 16 18:51 recovery.conf
-rw------- 1 postgres postgres     89 Aug 16 18:51 postmaster.pid
drwx------ 2 postgres postgres   4096 Aug 16 18:52 pg_stat_tmp
drwx------ 2 postgres postgres   4096 Aug 16 18:52 pg_notify
-rw------- 1 postgres postgres     61 Aug 16 18:52 postmaster.opts
drwx------ 2 postgres postgres   4096 Aug 16 18:52 pg_stat
-rw------- 1 postgres postgres  24356 Sep  3 09:28 postgresql.conf
drwx------ 2 postgres postgres  12288 Sep 15 07:36 pg_clog
drwx------ 2 postgres postgres   4096 Sep 15 11:40 pg_log
-rw------- 1 postgres postgres   3189 Sep 15 12:06 pg_hba.conf
drwx------ 2 postgres postgres   4096 Sep 15 14:03 pg_subtrans
drwx------ 3 postgres postgres 102400 Sep 15 15:04 pg_xlog
drwx------ 2 postgres postgres   4096 Sep 15 15:04 global


-bash-4.1$ cd pg_tblspc/
-bash-4.1$ ls -tlr
total 0
lrwxrwxrwx 1 postgres postgres 11 Mar 24 16:03 16400 -> /dbdata-aux
lrwxrwxrwx 1 postgres postgres 15 Jul  6 20:57 736177568 -> /dbdata-ramdisk

**Comment by dwsteele** [comment]
OK, how about:
```
ls -lah /dbdata-aux
ls -lah /dbdata-ramdisk
```
Is /dbdata-aux a link?

**Comment by dwsteele** [comment]
It also scares me a lot that you appear to be putting a tablespace in a ramdisk.  Nothing I have seen so far indicated that pg_xlog is linked anywhere.

**Comment by gintoddic** [comment]
This is a link in /dbdata/postgres/9.5-prod/pg_tblspc
lrwxrwxrwx 1 postgres postgres 11 Mar 24 16:03 16400 -> /dbdata-aux

/dbdata-aux is another partition using SSDs
/dbdata is HDDs

[root@datawarehouse002 pg_tblspc]# ls -lah /dbdata-aux
total 88K
drwxrwxr-x     5 postgres postgres 4.0K Aug 24 02:04 .
dr-xr-xr-x.   22 root     root     4.0K Jul 19 15:35 ..
drwx------     2 postgres postgres 4.0K Mar 16  2016 lost+found
drwx------     3 postgres postgres 4.0K Mar 24 16:03 PG_9.5_201510051
drwxr-x---  1869 postgres postgres  68K Sep 15 14:07 pgbackrest-wal-archive

[root@datawarehouse002 pg_tblspc]# ls -ltr /dbdata-ramdisk
total 0
drwxr-xr-x 2 postgres postgres 40 Jul 19 15:31 pg_stat_tmp
drwxr-xr-x 2 postgres postgres 40 Jul 19 15:31 PG_9.5_201510051

**Comment by gintoddic** [comment]
Something might be reverted back I'm double checking where the actual pg_xlogs link is

**Comment by gintoddic** [comment]
wrong host

lrwxrwxrwx 1 postgres postgres      18 Sep 14 10:48 pg_xlog -> /ssd-mount/pg_xlog

**Comment by gintoddic** [comment]
[root@datawarehouse001 9.5-prod]$ ls -lah $PGDATA
total 1.9M
drwx------ 21 postgres postgres 4.0K Sep 15 01:01 .
drwxr-xr-x  4 postgres postgres 4.0K Sep 14 13:24 ..
-rw-------  1 postgres postgres  244 Sep 15 01:01 backup_label
-rw-------  1 postgres postgres  244 Aug 16 16:09 backup_label.old
drwx------  9 postgres postgres 4.0K Mar 24 17:30 base
drwx------  3 postgres postgres 4.0K Jul 14 04:37 cstore_fdw
drwx------  2 postgres postgres 4.0K Sep 15 15:18 global
drwx------  2 postgres postgres  16K Sep 15 07:51 pg_clog
drwx------  2 postgres postgres 4.0K Mar 24 15:52 pg_commit_ts
drwx------  2 postgres postgres 4.0K Mar 24 15:52 pg_dynshmem
-rw-------  1 postgres postgres 2.9K Sep 14 02:33 pg_hba.conf
-rw-------  1 postgres postgres 1.6K Mar 24 15:52 pg_ident.conf
drwx------  2 postgres postgres 4.0K Sep 15 11:35 pg_log
drwx------  4 postgres postgres 4.0K Sep 15 14:59 pg_logical
drwx------  4 postgres postgres 4.0K Mar 24 16:03 pg_multixact
drwx------  2 postgres postgres 4.0K Sep 15 15:06 pg_notify
drwx------  2 postgres postgres 4.0K Mar 24 15:52 pg_replslot
drwx------  2 postgres postgres 4.0K Mar 24 15:52 pg_serial
drwx------  2 postgres postgres 4.0K Mar 24 15:52 pg_snapshots
drwx------  2 postgres postgres 4.0K Sep 14 11:05 pg_stat
drwx------  2 postgres postgres 4.0K Sep 14 11:05 pg_stat_tmp
drwx------  2 postgres postgres 4.0K Sep 15 12:42 pg_subtrans
drwx------  2 postgres postgres 4.0K Jul  6 20:57 pg_tblspc
drwx------  2 postgres postgres 4.0K Mar 24 15:52 pg_twophase
-rw-------  1 postgres postgres    4 Mar 24 15:52 PG_VERSION
lrwxrwxrwx  1 postgres postgres   18 Sep 14 10:48 pg_xlog -> /ssd-mount/pg_xlog
drwx------  3 postgres postgres 1.7M Sep 14 09:48 pg_xlog_bkup
-rw-------  1 postgres postgres  161 Sep 14 13:25 postgresql.auto.conf
-rw-------  1 postgres postgres  24K Sep 14 14:25 postgresql.conf
-rw-------  1 postgres postgres   61 Sep 14 11:05 postmaster.opts
-rw-------  1 postgres postgres   90 Sep 14 11:05 postmaster.pid
-rw-r--r--  1 postgres postgres 4.2K Mar 24 17:11 server.crt
-rw-------  1 postgres postgres 1.7K Mar 24 17:11 server.key
-rw-r--r--  1 postgres postgres 3.4K Mar 24 17:11 server.req
-rw-------  1 postgres postgres   44 Sep 15 01:01 tablespace_map
-rw-------  1 postgres postgres   44 Aug 16 16:09 tablespace_map.old

[root@datawarehouse001 9.5-prod]$ ls -trl pg_tblspc
total 0
lrwxrwxrwx 1 postgres postgres 11 Mar 24 16:03 16400 -> /dbdata-aux
lrwxrwxrwx 1 postgres postgres 15 Jul  6 20:57 736177568 -> /dbdata-ramdisk

lrwxrwxrwx 1 postgres postgres 22 Sep 14 10:47 /dbdata-aux -> ssd-mount/tablespaces/

**Comment by dwsteele** [comment]
OK, you shouldn't put other directories in the same directory that a tablespace points to.  So it should look more like:
```
/dbdata-aux/
/dbdata-aux/ts1/
/dbdata-aux/wal
```
backrest is upset because you are linking deeper into another directory that is already linked elsewhere.  This makes sane restores nearly impossible.

**Comment by dwsteele** [comment]
OK, there is is - and the error is correct.  The link is pg_tblspc should point to a directory, not to another link.  This is another thing that makes restores a real pain.

**Comment by gintoddic** [comment]
Ok thank you!

**Comment by dwsteele** [comment]
By the way, if you get the link-to-link error fixed don't be surprised if you get a "link X references a subdirectory of or the same directory as link X".  This will happen as described above.
