### ISSUE TITLE
remote archive-push too slow

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#261]
I am having a problem where the archive-push command to a remote location is too slow, so pgxlog fills up (*.ready files).

archive-push is taking about 30 WALs per minute
*.ready files are increasing at a rate of 200 per minute

The remote is actually the slave on the same sublan.

What is the archive-push actually doing? And is there something there that can be optimized?

As I'm thinking about this more, I guess I could do a work-around by setting archive_command = '/bin/true' for the duration of the action that is generating so much WAL (refreshing parts of a prod database on a lower environment), but then of course I lose control over PITR since the last pgbackrest differential.  This would not work for big WAL generating tasks in a prod environment though...

I'm thinking here about such things as VACUUM FULL on a very large table.

**Comment by dwsteele** [comment]
Using async archiving will help if your repo is remote, but if it is local not so much.  Most of the time is spent in compression so you can set `compress-level=3` to reduce compression and increase speed.

We are planning parallel compression for `archive-push` but I'm not sure when that will happen.  By the end of the year, hopefully.

**Comment by MichaelDBA** [comment]
Thanks David for the elaboration, suggestions, and future path!!!
