### ISSUE TITLE
Cascading Replication question

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#263]
First of all, thanks for implementing backups from a slave!

Assuming this scenario, where I have the following:
db-host1 (master) --> db-host2 (slave) --> db-host3 (cascading slave)

I want to treat db-host2 as a master and db-host3 as the slave to it.

So can I configure backups from the cascaded slave and pull the few extra files during backup from the db-host2 instead of db-host1?  I saw in the documentation that pgbackrest knows how to differentiate between master and slave and I'm wondering if that infers that pgbackrest assumes one of these to be a real master.

[global]
...
backup-standby=y

[config on db-host3]
db1-host=db-host2
db1-path=/mypath
db1-user=postgres
db2-host=db-host3
db2-path=/mypath
db2-user=postgres
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=db-host2 port=5432 user=replicator password=whatever 

The reason I don't want to pull backups from the real master is that the master is in a physically different location than the slaves which are in the same location.

**Comment by dwsteele** [comment]
You must have a master as one of your databases or the backup will not work.  pgBackRest will copy as little as possible from master, usually just a few MB.  If you are storing logs in $PGDATA/pg_log I would recommend putting them elsewhere to further reduce the data copied from master.

It should be possible to use the cascaded standby as the backup standby.  It will either work correctly or not at all - my bet is that it will be fine, though I admit I have not tested that scenario.
