### ISSUE TITLE
pgbackrest not working in cascaded mode

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#265]
We haven't allocated a separate server for the pgbackrest repo yet.

I have an environment where there is one master and slave and the pgbackrest repo is on the slave.

I also have a DR setup where the slave there pulls WALs from pgbackrest repo, but I can't get pgbackrest to do a restore on the cascaded slave that is dependent upon the main DR slave

env1:
dbhost1 (master) --> dbhost2 (slave, also the pgbackrest repo location)

env2:
dbhost3(slave replicating from dbhost1) --> dbhost4 (cascaded slave)

And I want to do a restore on dbhost4 to be in sync with dbhost3.  

Obviously I can do a pg_basebackup or an rsync to do it, but I want pgbackrest to do it.

**Comment by dwsteele** [comment]
> but I can't get pgbackrest to do a restore on the cascaded slave that is dependent upon the main DR slave.

You'll need to provide a lot more information than that.  What error are you getting, what do your configs look like?
