### ISSUE TITLE
Warnings break json output of info command

### ISSUE THREAD

**Issue by sbiberhofer** [pgbackrest/pgbackrest#268]
Some warnings seem to break the json output when calling pgbackrest info with --output=json:

```
2016-10-03 10:46:39.497 P00   WARN: backup 20160925-051703F_20160930-025956D missing in repository removed from backup.info
[
    {
        "backup" : [
            {
                "archive" : {
....
```

It would be nice if this output is either incorporated into the json output or moved to stderr.

**Comment by dwsteele** [comment]
You can suppress warnings with `--log-level-console=error` or by configuring `log-level-console=error` in the `[global:info]` section of `pgbackrest.conf`.  The latter method will only affect the `info` command.

**Comment by sbiberhofer** [comment]
While I agree that passing `--log-level-console=error` might be a workaround for this particular case, it doesn't solve the actual problem. 

Maybe I should explain this in slightly more detail: 

I usually parse the json output of pgbackrest with a python script to monitor backups. As such, I don't want to blindly suppress warnings but collect/parse them in a meaningful way. 

It is easy for me to parse json output. It is also easy for me to parse stderr seperately from the expected output. However, parsing becomes unnecessarily difficult if warnings and errors are mixed with the default output, especially if that output is expected to be json but suddenly isn't.

**Comment by dwsteele** [comment]
You have a point but since warnings are generally transient I'm not sure how useful it will be to try and report them.

I think this merits a configuration setting, perhaps something like `log-console-stderr` (default `error`) to define which log levels are reported on stderr.  Make sense?

**Comment by sbiberhofer** [comment]
This would definitely suffice for my purposes and sounds like a nice feature in any case.

**Comment by dwsteele** [comment]
Agreed, and it probably makes sense to set the default to `warn`.  There are cases where this may not be desirable but the `log-console-stderr` option will allow fine-tuning when needed.

**Comment by dwsteele** [comment]
Added in commit 2a18674111d8ee.
