### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by tsykes** [pgbackrest/pgbackrest#269]
I started using pgbackrest recently. It worked consistently for about a month and then started failing with "Out of Memory." There weren't any significant changes in the database being backed up. I'm on CentOS 7 and updated to version 1.08. I still get the error but with more detail now:  

2016-10-04 14:39:43.842 P00  ERROR: [198]: process terminated due to an unhandled exception:
                                           open3: fork failed: Cannot allocate memory at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/IO.pm line 110.
                                            at /bin/pgbackrest line 15.
                                                main::__ANON__('open3: fork failed: Cannot allocate memory at /usr/share/perl...') called at /usr/share/perl5/vendor_perl/Carp.pm line 100
                                                Carp::croak('open3: fork failed: Cannot allocate memory') called at /usr/share/perl5/IPC/Open3.pm line 236
                                                IPC::Open3::_open3('open3', 'GLOB(0x2a456fb8)', 'GLOB(0x2a4570f0)', 'GLOB(0x3f4f2f98)', '/usr/bin/pgbackrest --command=backup --db-host=10.69.25.39 --...') called at /usr/share/perl5/IPC/Open3.pm line 350
                                                IPC::Open3::open3('GLOB(0x2a456fb8)', 'GLOB(0x2a4570f0)', 'GLOB(0x3f4f2f98)', '/usr/bin/pgbackrest --command=backup --db-host=10.69.25.39 --...') called at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/IO.pm line 110
                                                pgBackRest::Protocol::IO::new3(undef, 'local-1', '/usr/bin/pgbackrest --command=backup --db-host=10.69.25.39 --...', 1830, 4194304) called at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/CommonMaster.pm line 69
                                                pgBackRest::Protocol::CommonMaster::new(undef, 'none', 'local', 'local-1', '/usr/bin/pgbackrest --command=backup --db-host=10.69.25.39 --...', 4194304, 6, 3, 1830, ...) called at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/LocalMaster.pm line 41
                                                pgBackRest::Protocol::LocalMaster::new(undef, '/usr/bin/pgbackrest --command=backup --db-host=10.69.25.39 --...', 1) called at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/LocalProcess.pm line 163
                                                pgBackRest::Protocol::LocalProcess::hostConnect('pgBackRest::BackupProcess=HASH(0x47a3a240)') called at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/LocalProcess.pm line 210
                                                pgBackRest::Protocol::LocalProcess::init('pgBackRest::BackupProcess=HASH(0x47a3a240)') called at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/LocalProcess.pm line 264
                                                pgBackRest::Protocol::LocalProcess::process('pgBackRest::BackupProcess=HASH(0x47a3a240)') called at /usr/share/perl5/vendor_perl/pgBackRest/Backup.pm line 411
                                                pgBackRest::Backup::processManifest(undef, 'pgBackRest::File=HASH(0x19e07b0)', '/data/pgdata/data', '/data/pgdata/data', 'full', 9.4, 1, 0, 'pgBackRest::Manifest=HASH(0x19dda00)', ...) called at /usr/share/perl5/vendor_perl/pgBackRest/Backup.pm line 857
                                                pgBackRest::Backup::process('pgBackRest::Backup=HASH(0x18e9108)') called at /bin/pgbackrest line 218
                                                eval {...} called at /bin/pgbackrest line 248

**Comment by dwsteele** [comment]
Please attach your `pgbackrest.conf` or copy the first INFO line from the log file for this execution.  It will look something like:
```
P00   INFO: backup start: <...>
```
It looks like it is having trouble allocating memory to startup the child processes that do the compression and transfer.  1.07 changed from Perl threads to processes for this work, which is faster but also requires more memory.

**Comment by tsykes** [comment]
I just tried reducing the buffer-size a bit from default, but that didn't fix it. I am backing up to a smaller server than the database (2 processors/4GB). Here's the INFO line: 


2016-10-04 15:09:44.934 P00   INFO: backup start: --buffer-size=3145728 --db-host=10.69.25.39 --db-path=/data/pgdata/data --db-user=postgres --log-level-console=info --log-path=/data/pgdata/log --repo-path=/data/pgdata/pgbackrest --retention-archive=2 --retention-full=2 --stanza=dsg_dev --start-fast --stop-auto --type=full

**Comment by dwsteele** [comment]
I don't see anything out of the ordinary in your settings.  You shuld expect RES+SHR to be 25-30MB depending on your settings.  If you are seeing more than that, please let me know, otherwise I think this has something to do with your system.

**Comment by tsykes** [comment]
When I run htop during the backup, a few minutes into the backup, I see RES run up and peak over 2000M before crashing.  Here's an output I captured. 

 4619 postgres   20   0 2147M **1924M  4000** R 100. 50.8  0:59.20 │     └─ /usr/bin/perl /bin/pgbackrest --stanza=dsg_dev --log-level-c
 4620 postgres   20   0 84784  8696  3416 S  0.0  0.2  0:01.01 │        └─ ssh -o LogLevel=error -o Compression=no -o PasswordAuthen

**Comment by dwsteele** [comment]
Wow.  Can you please run with --log-level-file-debug and attach the output from /var/log/pgbackrest/dsg_dev_backup.log?

**Comment by dwsteele** [comment]
Also, can you provide details of OS and version?

**Comment by tsykes** [comment]
The log file is attached. The OS is 
CentOS Linux release 7.2.1511 (Core)

[dsg_dev-backup.log.gz](https://github.com/pgbackrest/pgbackrest/files/509642/dsg_dev-backup.log.gz)

**Comment by dwsteele** [comment]
You definitely have a large number of tables but nothing we haven't seen before.  I created a test database with 40,000 tables (~82K files vs your ~78K) and while resident memory usage was high (~115MB) it was nothing like what you are seeing:
```
 time    vsz (  diff)    rss (  diff) shared (  diff)   code (  diff)   data (  diff)
    0  125732 ( 125732)  20748 ( 20748)   6328 (  6328)      8 (     8)  14228 ( 14228) startup
    2  129032 (  3300)  22296 (  1548)   6576 (   248)      8 (     0)  15428 (  1200) before manifest build
   11  221348 ( 92316)  114524 ( 92228)   6604 (    28)      8 (     0)  107744 ( 92316) before manifest process
   11  221348 (     0)  114524 (     0)   6604 (     0)      8 (     0)  107744 (     0) before backup queue
   28  222536 (  1188)  115576 (  1052)   6604 (     0)      8 (     0)  108932 (  1188) before process queue
  146  226712 (  4176)  115632 (    56)   6560 (   -44)      8 (     0)  113108 (  4176) before process pg_control
  146  234904 (  8192)  115968 (   336)   6560 (     0)      8 (     0)  121300 (  8192) after manifest process
```
I see similar results on other OS's.

Are you running a special build of Perl or have you installed CPAN or any unusual modules (like a debugger/profiler)?

Your Perl version should be:
```
[root@db-master /]# perl --version

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 29 registered patches, see perl -V for more detail)
```

**Comment by tsykes** [comment]
Both the database server and the backup server are running the same perl as you show. You have 1 more registered patch. I haven't written perl for years so there isn't anything I did with perl knowingly. 

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 28 registered patches, see perl -V for more detail)

**Comment by dwsteele** [comment]
Are these boxes bare metal or virtualized?  If virtualized, what virtualization are you using?

**Comment by dwsteele** [comment]
Can you provide the manifest for your last successful full backup:
```
/data/pgdata/pgbackrest/backup/dsg_dev/backup.history/2016/20160918-103641F.manifest.gz
```
And the manifest from the last failed backup:
```
/data/pgdata/pgbackrest/temp/dsg_dev/backup.manifest
```

**Comment by tsykes** [comment]
The servers are in an openstack environment. 

[20160918-103641F.manifest.gz](https://github.com/pgbackrest/pgbackrest/files/511760/20160918-103641F.manifest.gz)
[backup.manifest.txt](https://github.com/pgbackrest/pgbackrest/files/511763/backup.manifest.txt)

**Comment by dwsteele** [comment]
The manifests look pretty normal.  They are not particularly large and there are no links other than the tablespaces.

I've tried a few other things, including loading the manifests you provided as if they were being created by a backup to see if the Perl hashes blew up.  At this point I am out of ideas.

The only thing I can think of is to run the backup on bare metal or using another virtualization technology to implicate or eliminate OpenStack as an issue.

**Comment by tsykes** [comment]
I've moved most of the data to a new server and have started backing up from there. I don't get the Out of Memory issue backing up from this server.  It's still OpenStack but a different cluster. Thanks for the help.

**Comment by dwsteele** [comment]
Interesting, perhaps there was not as much as memory available as was being reported.  Glad it is working now!
