### ISSUE TITLE
ERROR: stop file exists for all stanzas

### ISSUE THREAD

**Issue by saifulmuhajir** [pgbackrest/pgbackrest#270]
**Background:** the backup and archiving was running fine until one day my colleague has to delete and stop pgbackrest archive because of the disk space issue. This is a very busy server and the WALs are huge.

**Problem:** the problem occurs when I tried to re-enable the archive-push for pgbackrest stating like this:
```
2016-10-11  T00  ERROR: [137]: stop file exists for all stanzas
2016-10-11 @: [23157] FATAL:  archive command failed with exit code 137
2016-10-11 @: [23157] DETAIL:  The failed archive command was: cp pg_xlog/0000000100002F27000000CE /arch/0000000100002F27000000CE && pgbackrest --stanza=mystanza archive-push pg_xlog/0000000100002F27000000CE
2016-10-11 @: [18059] LOG:  archiver process (PID 23157) exited with exit code 1
```
I cannot find anything that leads me to solve this anywhere.

My archive_command is: `'cp %p /arch/%f && pgbackrest --stanza=mystanza archive-push %p'`

And my stanza config is:
```
[mystanza]
db-path=/data/postgres/data

[global]
repo-path=/mnt/external/backup
retention-full=1
retention-diff=1
retention-archive=1
start-fast=y
stop-auto=y
```

What does **stop file** mean and how do I fix this? FYI, this is master server. Thanks.

**Comment by dwsteele** [comment]
Since the `stop` command was run then `start` must be run for pgBackRest will operate normally again.  See http://www.pgbackrest.org/user-guide.html#start-stop.

**Comment by saifulmuhajir** [comment]
Ah, so this is because I have `stop-auto=y.` Thanks for the help.

**Comment by dwsteele** [comment]
This is not related to `stop-auto`.  That determines whether a previously run database backup will automatically be stopped and restarted.  See http://www.pgbackrest.org/user-guide.html#backup/option-stop-auto.

**Comment by pinakesh** [comment]
Hi Dwsteele,

Thanks for your input, however for testing purpose I need to first check if backups can be taken from the Standby server and document the procedure.

What I understood from your last comment is that in Primary's pgbackrest.conf pg2-host='Standby's hostname' and on standby's pgbackrest.conf pg2-host='Primary's hostname'

So my configuration is as below ::

On Server02cn
----------------

[postgres@Server02cn ~]$ cat /etc/pgbackrest/pgbackrest.conf
[newdemo]
#pg1-host=Server02cn
pg1-path=/u02/pb/postgres/pgbackrest_test/data
pg2-host=Server04cn
pg2-path=/u02/pb/postgres/pgbackrest_test/data
log-level-console=info

[global]
backup-standby=y
process-max=3
repo1-path=/u02/pb/postgres/pgbackrest_test/backup
repo1-retention-full=2
start-fast=y


On Server04cn
----------------

[postgres@Server04cn ~]$ cat /etc/pgbackrest/pgbackrest.conf
[newdemo]
#pg1-host=Server02cn
pg1-path=/u02/pb/postgres/pgbackrest_test/data
pg2-host=Server0r2cn
pg2-path=/u02/pb/postgres/pgbackrest_test/data

[global]
backup-standby=y
process-max=3
repo1-path=/u02/pb/postgres/pgbackrest_test/backup
repo1-retention-full=2
start-fast=y

Now, while running stanza-create on Primary I am getting below error.

On Server02cn
-------------


[postgres@Server02cn ~]$
[postgres@Server02cn ~]$ pgbackrest stanza-create --stanza newdemo  --pg1-port 55432 --pg2-port 55432
2019-07-22 01:18:41.167 P00   INFO: stanza-create command begin 2.13: --backup-standby --log-level-console=info --pg2-host=Server04cn --pg1-path=/u02/pb/postgres/pgbackrest_test/data --pg2-path=/u02/pb/postgres/pgbackrest_test/data --pg1-port=55432 --pg2-port=55432 --repo1-path=/u02/pb/postgres/pgbackrest_test/backup --stanza=newdemo
WARN [056]: : raised from remote process on 'Server04cn': could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.55432"?
ERROR [049]: : unable to find standby database - cannot proceed
2019-07-22 01:18:42.281 P00   INFO: stanza-create command end: aborted with exception [049]
[postgres@Server02cn ~]$


I also checked that passwordless SSH is properly set.

[postgres@Server02cn ~]$
[postgres@Server02cn ~]$ hostname
Server02cn
[postgres@Server02cn ~]$
[postgres@Server02cn ~]$ ssh Server04cn
Last login: Mon Jul 22 01:09:45 2019
[postgres@Server04cn ~]$ hostname
Server04cn
[postgres@Server04cn ~]$
[postgres@Server04cn ~]$ exit
logout
Connection to Server04cn closed.
[postgres@Server02cn ~]$
[postgres@Server02cn ~]$ psql -p 55432 -h Server04cn
psql (11.0)
Type "help" for help.

postgres=# \conninfo
You are connected to database "postgres" as user "postgres" on host "Server04cn" at port "55432".
postgres=#

Please can you help with the proper configuration for getting backup from standby server?

Regards,
Pinakesh
