### ISSUE TITLE
Backup failed and pgbackrest defunct processes

### ISSUE THREAD

**Issue by gintoddic** [pgbackrest/pgbackrest#274]
I have a debug log with a backup that failed at 99%.
[data-backup.zip](https://github.com/pgbackrest/pgbackrest/files/544671/data-backup.zip)

**Comment by dwsteele** [comment]
As far as I can see the backup was complete but it got stuck waiting for WAL to make it into the archive.  Have you run the `check` command to see if archiving is working?

**Comment by gintoddic** [comment]
I have had backups succeed over the past few days. Although I do get an error when trying to run a check

2016-10-24 18:25:27.301 P00   INFO: switch xlog 000000010000B51C000000F0
ERROR [157]: could not find WAL segment 000000010000B51C000000F0 after 500 second(s)
ERROR [157]: could not find WAL segment 000000010000B51C000000F0 after 500 second(s)
WARN: WAL segment 000000010000B51C000000F0 did not reach the archive:
HINT: Check the archive_command to ensure that all options are correct (especialy --stanza).
HINT: Check the PostreSQL server log for errors.
2016-10-24 18:33:48.075 P00   INFO: check stop

**Comment by dwsteele** [comment]
It sounds like the archive process is falling behind due to high volumes.  If you have high WAL volume you might consider using async archiving (http://www.pgbackrest.org/user-guide.html#backup-host/async-archiving) which gives some performance benefits.  In the near future this will also be parallelized like backup and restore.

**Comment by gintoddic** [comment]
We do have async enabled already. Anything else to check?

**Comment by dwsteele** [comment]
You could try reducing `compress-level` in the database `pgbackrest.conf` file (so only archiving is affected, not backup).  Or increase `db-timeout` to prevent timeouts in `pg_stop_backup()`.
