### ISSUE TITLE
Allow SSH port to be configured

### ISSUE THREAD

**Issue by dwsteele** [pgbackrest/pgbackrest#275]
Currently port 22 is always used.  Make this configurable with `db-host-port` option (or `db-ssh-port`?)

**Comment by ms3rgio** [comment]
Are you predicted when this will be implemented?

**Comment by dwsteele** [comment]
Well, it certainly has been around for a while.  Somebody suggested it to me but didn't have a strong need so it never got done.  Are you in need of this feature?  If so, what is driving the requirement?

**Comment by ms3rgio** [comment]
Yes I need. I plan to deploy Pgbackrest to make our backups, but our servers listen on ports other than the default ssh.

**Comment by dwsteele** [comment]
We'll try to get this into the next release, which will probably be late-May, early June.

**Comment by ms3rgio** [comment]
That's nice. This feature is important to us. Tks.

**Comment by dwsteele** [comment]
Committed at ce2b18c5b84c5066.
