### ISSUE TITLE
Trigger Remote Backup From DB

### ISSUE THREAD

**Issue by jasonodonnell** [pgbackrest/pgbackrest#278]
It would be really great if I could request a remote backup from a database.  This would really help automated deployments where I want to stand up read replicas from a newly created master database using backrest restore.

**Comment by uspen** [comment]
Yes, init backup from pg is good. And try https://github.com/zalando/patroni

**Comment by dwsteele** [comment]
Moved to feature request board: https://github.com/pgbackrest/pgbackrest/projects/2.

**Comment by dkumarr2** [comment]
can I get a configuration steps on how to make remote backup in pgbackrest?

**Comment by jasonodonnell** [comment]
There are no configuration steps to doing a remote backup in backrest.  To get around this you could ssh from your database server to the backrest server (assuming you have ssh keys setup already for backrest):

```
$ ssh -i <ssh_key> <backup_user>@<backup_host_ip> pgbackrest --stanza=mystanza backup
```
