### ISSUE TITLE
pgbackrest doesn't complain about a wrong stanza

### ISSUE THREAD

**Issue by disco-stu** [pgbackrest/pgbackrest#282]
Somewhere between 1.06 and 1.09 the behavior of pgbackrest changed when a wrong (not defined) stanza is used.

1.06:
pgbackrest --stanza=asdf  --log-level-console=info backup; echo $? 
ERROR [112]: backup command requires option: db-path
HINT: does this stanza exist?
112

1.09:
pgbackrest --stanza=asdf  --log-level-console=info backup; echo $?
112

The current release also contains this bug 1.11:
pgbackrest --stanza=asdf  --log-level-console=info backup; echo $?
112

**Comment by dwsteele** [comment]
Hi Adrian,

I noticed this the other day an opened issue #281 for it.  I've pasted your notes into that ticket.
