### ISSUE TITLE
Integration with other Tools 

### ISSUE THREAD

**Issue by abhirathore2006** [pgbackrest/pgbackrest#290]
hi, i would like to use pgbackrest , however i also want to achieve the connection pooling and high availability, i looked into repmgr and pgpool2 those two can give me what i need , but the exception is backups. so it would be great if you can provide suggestions or show some configuration which we can use for achieving this .

my environment will be 1 master, 1 standby and 1 pgpool 2 server.  any other configuration will work too.

**Comment by uspen** [comment]
Hi!

You need ssh access from remote backup server (pgbackrest server) for make backups.

I use every week cmd:
``
pgbackrest --type=full --stanza=mydb backup
``
And everyday:
``
pgbackrest --type=diff --stanza=mydb backup
``
And config:

[global]
repo-path=/data/pgbackrest
retention-full=30
process-max=4
[mydb]
db1-host=host1.example.com
db1-port=5432
db1-path=/data/pg/mydb
db1-user=postgres
db2-host=host2.example.com
db2-port=5432
db2-path=/data/pg/mydb
db2-user=postgres
db3-host=host3.example.com
db3-port=5432
db3-path=/data/pg/mydb
db3-user=postgres

Client pgbackrest (on PG host):

[global]
repo-path=/data/pgbackrest
backup-host=backup.db.example.com
backup-user=postgres
[mydb]
db-path=/data/pg/mydb


But pgBackRest now is not support backup from > 2 nodes... Master must be db1-host or db2-host

**Comment by dwsteele** [comment]
At Crunchy Data we use both Consul and Pacemaker/Corosync for HA and pgBackRest will work with either of them.  I haven't tried repmgr.

I'm planning to add HA instructions to the user guide but don't have a specific timeline for that.

**Comment by abhirathore2006** [comment]
@dwsteele  thanks a lot for information :), currently am trying to implement HA and Backup using barman-repmgr-pgbouncer then i will try to integrate the pgbackrest in place of barman. the only problem i see is the archive command,  repmgr doesn't need an archive command, it will be okay even if i put "cd ." or "/bin/true" in archive command.  the thing is am not sure if it executes the command when it replicates to standby. beause if it does and i put  pgbackrest command in it then it will execute that too

**Comment by dwsteele** [comment]
I'd be interested to see how that turns out.  Pretty sure nobody has integrated pgBackRest with repmgr before!
