### ISSUE TITLE
question: how bout a "check" command for slaves?

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#291]
I like the check command which makes sure WALs can be sent successfully to the pgbackrest repo, which works from either the master or the pgbackrest repo location.  But what about a slave?  You cannot execute WAL control functions during recovery.

How bout enhancing the check command or adding a new "check" kinda command altogether that includes checks for slaves. So if it is run from a slave, it will:
1. Make sure the slave is in recovery mode.
2. Make sure the slave is not out of sync with the master, i.e., not waiting for a WAL that the master doesn't have anymore.
3. Making sure the slave can talk to the pgbackrest repo server and vice versa.
4. Flag any inconsistencies between the  pgbackrest.conf files on both the slave and repo server.

I know that some of the functionality listed above is PG-specific (1, 2), but wouldn't be too hard to add them anyway.

**Comment by dwsteele** [comment]
We are already working on making the check command behave better on a slave.  Most of the rest of this falls into the category of monitoring, however, so it's unlikely to happen in the near future, if ever.

**Comment by MichaelDBA** [comment]
"behave better"?  It fails when run on the slave with a message that indicates you cannot execute WAL commands on a slave.

**Comment by dwsteele** [comment]
We're aware of that, yes.

**Comment by MichaelDBA** [comment]
ok thanks
