### ISSUE TITLE
Backup from standby requires to install pgbackrest on standby server?

### ISSUE THREAD

**Issue by kotsachin** [pgbackrest/pgbackrest#293]
Hi,

Sorry for asking small query but please revert as soon as possible.

I am trying to take backup from standby DB server but it fails saying 
```
ERROR [127]: remote process terminated on x.x.x.x host: bash: /usr/bin/pgbackrest: No such file or directory
```

I have installed pgbackrest on Master DB server.
Do I need to install pgbackrest on standby server as well?

**Comment by dwsteele** [comment]
Yes.  See http://www.pgbackrest.org/user-guide.html#replication for setting up pgBackRest on a standby.

**Comment by kotsachin** [comment]
@dwsteele 

Thanks for reply and documentation path.

It means we have to setup pgbackrest on each server, Master DB as well as Stabdby DB server.

Consider scenario: 
If someone want to take backup to Backup server from either Master DB server or Standby DB server.
He has to setup pgbackrest on all three machines. Isn't it unnecessary ?
I don't think it is good idea to ask to install pgbackrest on all Machines as we are taking remote hostname and user_name in pgbackrest.conf. We should be able to take backup from remote machines like pg_basebackup taking.

Are you planning to add feature which will take backup from any server where pgbackrest in installed and not need to install on server from where backup is being taken?

**Comment by dwsteele** [comment]
pgBackRest can't really be compared to pg_basebackup.  pg_basebackup doesn't do continuous archiving, multi-processing, or incremental backups, checksums, etc.  All these things are made possible by having a local agent.

There are no plans for an agent-less mode.  It would make implementing the above features quickly and reliably nearly impossible.  Beyond that, there would be no reliable way to do archiving -- cp, scp, and rsync are not reliable solutions.

**Comment by kotsachin** [comment]
ok. I understood it. 
Thanks for you support !!
