### ISSUE TITLE
check command reference confusion

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#299]
I'm confused by chapter 5 in the command reference that deals with the check command.
At the top it describes the check command, but then the ensuing subsections, 5.1 thru 5.4 deal with other commands not related to the check command.  Am I missing something here?

`http://www.pgbackrest.org/command.html#command-check`

**Comment by sfrost** [comment]
Michael,

* Michael Vitale (notifications@github.com) wrote:
> I'm confused by chapter 5 in the command reference that deals with the check command.
> At the top it describes the check command, but then the ensuing subsections, 5.1 thru 5.4 deal with other commands not related to the check command.  Am I missing something here?

Those are the options which are relevant to the 'check' command.

Thanks!

Stephen
