### ISSUE TITLE
Archive fetch problems after crash and reboot (take 2)

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#302]
You closed the issue before I had a chance to respond to your comment regarding issue, #301

You said: It looks like there are problems with the permissions on msp0llexp039:/tmp/pgbackrest.

But that directory, /tmp/pgbackrest, is owned by postgres (our backrest user) and has a lot of current lock files in it:

```
-rw-r----- 1 postgres postgres 6 Jan  3 09:47 model_local_remote-6.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:18 sandbox_archive-push_remote.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:43 model_archive-get_remote.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-3.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-2.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-1.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-7.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-6.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-5.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-4.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-9.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-8.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-10.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-13.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-12.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:45 model_backup_remote-11.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:47 model_archive-push_remote.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:52 test96_archive-push_remote.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:53 prod_archive-push_remote.lock
-rw-r----- 1 postgres postgres 6 Jan  3 12:53 demo_archive-get_remote.lock
```

**Comment by MichaelDBA** [comment]
Is it safe to delete all the files from this directory?  I think the server crash during a restore contributed to this problem.

**Comment by dwsteele** [comment]
You can delete the files if you like but their presence should not pose a problem unless a process is holding a lock.  Perhaps you have a stuck process?

**Comment by MichaelDBA** [comment]
Once I deleted the lock files in the /tmp/pgbackrest dirctory, everything proceeded smoothly thereafter.
I'm wondering if this is something that must be manually done in unusual cases like this, server crash.

Looking for your final feedback before you close this issue, thanks in advance.

**Comment by dwsteele** [comment]
It should not be necessary to remove the files unless a process is still holding a lock, but weird stuff can happen on a system crash.
