### ISSUE TITLE
Refreshing a Lower Environment Using pgbackrest

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#304]
Hey, I was able to use pgbackrest to refresh my lower environment clusters.  Can you validate that what I did seems valid to you all?

A major assumption: The lower environment (target) has the same PG cluster configuration as the source PG cluster environment (exact same sizes, locations or symlinks for data directory, user tablespaces, pg_log, pg_xlog, etc.)

Basically, I "fool" pgbackrest. Create a temporary stanza on the lower environment target that has the same stanza as the production environment. Then you can do a restore, effectively copying your production PG cluster to the lower environment. Then once the restore is complete, remove the temporary prod stanza on the lower environment target, and point once again to your lower environment stanza. The details of this follow. 

In this example, we will use "stage" as the lower environment stanza target, and "prod" as the higher environment stanza source. Create the temporary prod stanza on the stage server. 

```
[prod]
db1-path=/mypath/mydatadir
db1-port=5432
db1-user=postgres
db1-socket-path=/var/run/postgresql
```

Start the restore from the stage server using this temporary prod stanza. The example shows getting it using latest timeline.  You can choose other ways of course.
`pgbackrest --stanza=prod --delta "--target-timeline=latest" --log-level-console=info restore`

After the restore on the lower environment, you must start it but not before you modify the archive_command on the stage server's postgresql.conf file to point to the production stanza. Thus, the recovery will ensue getting the latest stuff from production that occurred during the restore operation.
`archive_command = 'pgbackrest --stanza=prod archive-push %p'`

After the restore is complete and if successful, you should see recovery.conf is automatically renamed to recovery.done in the stage data directory. Make sure the stage PG cluster is down. 

Edit the stage postgresql.conf archive_command on the stage server to point back to the stage stanza.
`archive_command = 'pgbackrest --stanza=stage archive-push %p'`

Now, we must purge completely the pgbackrest stage directories on the pgbackrest repo or pgbackrest will complain about mismatches when we try to start stage pointing to its own stanza again, stage. This means we lose all our backups and archive files for stage. The following example assumes path to pgbackrest repo on backup server is /pgarchive/pgbackrest.

```
-- ssh to pgbackrest host
find /pgarchive/pgbackrest/backup/stage  -mindepth 1 -delete;
find /pgarchive/pgbackrest/archive/stage -mindepth 1 -delete;
-- NOTE: make sure no other processes are running before deleting the following:
find /pgarchive/pgbackrest/temp -mindepth 1 -delete;
find /tmp/pgbackrest -mindepth 1 -delete;
```

Start the stage server making sure it comes up successfully. The archive command will fail until we initiate the stage stanza on the pgbackrest repo server:
`pgbackrest --stanza=stage --log-level-console=info stanza-create`

At this point, we have a fully functional, refreshed lower environment. Do the first full backup of the newly refreshed stage cluster.

`pgbackrest --type=full --stanza=stage  backup --log-level-file=info --log-level-console=info --archive-check --start-fast`

**Comment by sfrost** [comment]
Michael,

This is not a general support forum but one for reporting bugs about pgbackrest.

Thanks!
