### ISSUE TITLE
WALs not being removed from pgbackrest spool directory

### ISSUE THREAD

**Issue by MichaelDBA** [pgbackrest/pgbackrest#305]
When there is a lot of activity on our master, ie, refresh a prod snapshot into our environment, the slaves get out of sync with the master, pgbackrest check command fails on the backrest server, and a lot of files remain in the pgbackrest spool directory on the master.

Is there some timeout parameter than I can use to increase the time it takes to do an archive-get so it won't timeout?

**Comment by dwsteele** [comment]
Postgres will automatically retry archive-get so I don't believe there's a need for a configurable timeout.

We're working to make async archiving faster.
