### ISSUE TITLE
Add Warning message fore remap-tablespace in PostgreSQL < 9.2

### ISSUE THREAD

**Issue by blogh** [pgbackrest/pgbackrest#306]
Hi,

It would be nice to have a warning message when trying to do a `--remap-tablespace` `--tablespace-map-all` with postgreSQL < 9.2. (I saw the warning in the documentation)

Maybe something like: 

`pg_catalog.pg_tablespace.spclocation should be updated to reflect the new tablespace location in PostgreSQL < 9.2`

If the idea is ok with you, I can do a PR for this.

I noticed a missing space in the following warning message : 

`/usr/share/perl5/pgBackRest/Db.pm:            &log(WARN, OPTION_STOP_AUTO . 'option is only available in PostgreSQL >= ' . PG_VERSION_93);`

Thx for the efforts

Benoit

**Comment by dwsteele** [comment]
> pg_catalog.pg_tablespace.spclocation should be updated to reflect the new tablespace location 
> in PostgreSQL < 9.2

I'd probably leave off the pg_catalog schema but otherwise it looks good.

> If the idea is ok with you, I can do a PR for this.

Go for it.

> Thx for the efforts

Thank you!
-David

**Comment by dwsteele** [comment]
Committed at b6fa146f9b1b9e622f456d73585423538c04ad17 from PR #309.
