### ISSUE TITLE
zstd compression

### ISSUE THREAD

**Issue by mvrhov** [pgbackrest/pgbackrest#308]
Have you thought of using zstd as alternative compression method?

Level 6 compression should be faster and should compress better. Also the decompression is faster than on the zlib.

**Comment by dwsteele** [comment]
Hi Miha,

We are planning to allow different compression algorithms at some point but it is not currently a priority.  The mostly likely next choice would be bzip2, for users who want maximum compression.

gzip was chosen because it is ubiquitous and known to be unencumbered by patents.

**Comment by jungle-boogie** [comment]
Hi @dwsteele,

Before settling on bzip2, please consider something more modern. Doesn't look like bzip2 has been updated going on 7 years now.

zstd is quite nice and fast and lz4 is also a worthy, modern contender.  https://github.com/lz4/lz4

Thanks!

**Comment by mvrhov** [comment]
Hi David,
AFAIR bzip2 is slower and has lesser compression than zstd. We've tested e.g zstd and lzma for one of our products, and we found out that the compression ratio of zstd is similar to lzma but faster. Also the memory consumption for zstd was lower.

**Comment by dwsteele** [comment]
Thanks for the input!  I had also been looking at xz as an alternative to bzip2.  I don't think lz4 has the compression ratios to be a contender - yeah it's fast but gzip at level 3 is pretty fast as well.

When the time comes I'll do a thorough comparison, but bzip2 has the advantage of ubiquitous cmd line tools and packaged Perl modules on most major distros, so it is still the most likely choice.

I know it's not very sexy, but in the backup world stability and compatibility generally win.

**Comment by MichaelDBA** [comment]
Any reason why pigz is not being considered?

**Comment by dwsteele** [comment]
pgBackRest already does parallel compression and pigz is still gzip.

**Comment by mvrhov** [comment]
The speed also matters as well as compression ratio :) Zstd has a really nice comparison graph speed/ratio and the points are compression level. 

![Compression](https://github.com/facebook/zstd/blob/dev/doc/images/Cspeed4.png)
