### ISSUE TITLE
Point In Time recovery for point after last backup

### ISSUE THREAD

**Issue by jsheperd** [pgbackrest/pgbackrest#320]
I am able to successfully restore for any target point between the last and any previous backup points on record level, but when I use target time later than the last backup point it rolls back till the last backup. It seems to be not handle the wal files after the last backup.
Setup: centOS 6.8, postgres 9.4, pgbackup1.12
I have no idea, where to look for the roots.

**Comment by uspen** [comment]
Hello!
Which command you run?

I use:
`
pgbackrest --stanza=test --delta --recovery-option='recovery_target_time=2016-12-27 18:17:00' restore
`

**Comment by jsheperd** [comment]
I have used the next command:
`data]# sudo -u postgres pgbackrest --stanza=demo --delta --type=time "--target=2017-02-09 13:24:06" restore
`
I have made a blank new installation with a blank new centos server, and it works fine now. It was able to recover to point after the last incremental backup.

It seems to be not an issue with the software but with my prev. installation.

**Comment by dwsteele** [comment]
Glad you figured it out - I've been a little swamped.  @uspen Thanks for jumping in and helping!

I prefer the pgBackRest style restore (`--type=time "--target=2017-02-09 13:24:06"`) , but of course specifying your own recovery options works just as well.
