### ISSUE TITLE
Allow more than one standby to be configured

### ISSUE THREAD

**Issue by dwsteele** [pgbackrest/pgbackrest#322]
This will help with three node configurations.

**Comment by uspen** [comment]
Is it possible to create a backup of more than 3 nodes in a cluster?

**Comment by dwsteele** [comment]
Yes.  Once we get to three then I would feel comfortable with n.  The problem is that we have not yet written tests for more than one standby.  The code change is just a single constant, but without testing I'm not comfortable releasing it.

**Comment by uspen** [comment]
Thank you! This feature is very important for me

**Comment by jamessewell** [comment]
This would be really great

**Comment by dwsteele** [comment]
Committed at 36e576b4839d5d9323597014d6f478de with seven standbys allowed.  Currently, only one will be used for the backup.
