### ISSUE TITLE
Can't load '/usr/lib64/perl5/vendor_perl/auto/DBD/Pg/Pg.so' for module DBD::Pg: libssl.so.1.0.0:

### ISSUE THREAD

**Issue by seadba** [pgbackrest/pgbackrest#325]
Hello, trying to configure v1.15 on RH7.3 - have installed all perl mods but when i try to create a stanza i get the following error 

[postgres@asydev3 ~]$ pgbackrest --stanza=btpg94 --log-level-console=info stanza-create
2017-02-20 12:33:46.721 P00   INFO: stanza-create command begin 1.15: --db-path=/opt/postgresql/data/pg94 --log-level-console=info --repo-path=/instance1/postgres/PG94/backup --stanza=btpg94
2017-02-20 12:33:46.836 P00  ERROR: [198]: process terminated due to an unhandled exception:
                                        Can't load '/usr/lib64/perl5/vendor_perl/auto/DBD/Pg/Pg.so' for module DBD::Pg: libssl.so.1.0.0: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190.
                                         at /usr/share/perl5/pgBackRest/Db.pm line 10.
                                         at /bin/pgbackrest line 15.
                                        	main::__ANON__('Can\'t load \'/usr/lib64/perl5/vendor_perl/auto/DBD/Pg/Pg.so\...') called at /usr/share/perl5/vendor_perl/Carp.pm line 100
                                        	Carp::croak('Can\'t load \'/usr/lib64/perl5/vendor_perl/auto/DBD/Pg/Pg.so\...') called at /usr/lib64/perl5/DynaLoader.pm line 98
                                        	DynaLoader::croak('Can\'t load \'/usr/lib64/perl5/vendor_perl/auto/DBD/Pg/Pg.so\...') called at /usr/lib64/perl5/DynaLoader.pm line 190

**Comment by dwsteele** [comment]
Looks like you don't have `libssl` installed and `DBD::Pg` requires it.

**Comment by seadba** [comment]
ok, thanks for fast response - its part of openssl correct? thats installed - would a yum reinstall openssl work?  thanks again

**Comment by seadba** [comment]
also, its on the system

[root@asydev3 yum.repos.d]# locate libssl.so.1.0.0
/opt/postgresql/pg94/lib/libssl.so.1.0.0

**Comment by seadba** [comment]
i got it so far - created symbolic links to libssl and crypto - thanks - cool utility

**Comment by dwsteele** [comment]
I'm not exactly sure why you needed to create symbolic links, but glad it works!
