### ISSUE TITLE
pgbackrest with pgpool

### ISSUE THREAD

**Issue by golpa** [pgbackrest/pgbackrest#333]
What is the recommended way of backing up a pgpool based DB cluster?

In our setup we have multiple postgres databases setup with streaming replication behind a load balancing pgpool instance. Additionally, on master failure pgpool is setup promote a standby server to new master.

What would be the best to setup pgbackrest to back it up?

**Comment by dwsteele** [comment]
The best way would be to configure the backup server with all the servers in the pool and let pgBackRest figure out which is the master.  Unfortunately, at the moment you can only configure two db servers and it sounds like you have more than that.  We are changing this soon: #322.

For the time being you will need to manually change the config on the backup server when the master changes.  Archiving will move automatically as long as the archive command is configured on all servers.
