### ISSUE TITLE
Best way to run master?

### ISSUE THREAD

**Issue by jungle-boogie** [pgbackrest/pgbackrest#341]
Hi All,

I've installed p5-DBD-Pg for freebsd, cloned your repo and now what's the best way to run master of pgbackrest?

```
% bin/pgbackrest
zsh: bin/pgbackrest: bad interpreter: /usr/bin/perl: no such file or directory
```

```
% perl -v

This is perl 5, version 24, subversion 1 (v5.24.1) built for i386-freebsd-thread-multi-64int
```

```
% which perl
/usr/local/bin/perl
```

AH, that's the problem -- the `bin/pgbackrest` is looking in `/usr/bin/perl` for perl and not `/usr/local/bin/perl`

Is it possible to use an env so it can find perl on different systems?

**Comment by dwsteele** [comment]
Well, it looks like:
```
#!/usr/bin/env perl
```
might solve this problem, but not sure I want to do that universally since it makes it less clear which Perl is going to run.  I imagine if this were packaged for FreeBSD they would patch bin/pgbackrest with the correct path.

Thoughts?

**Comment by jungle-boogie** [comment]
> might solve this problem, but not sure I want to do that universally since it makes it less clear which Perl is going to run.

Which perl is required? `/usr/bin/perl` doesn't exactly specify which perl to use, just something under /usr/bin, right?

>  packaged for FreeBSD they would patch bin/pgbackrest 

I think your prognosis is correct for this.

**Comment by dwsteele** [comment]
> Which perl is required? /usr/bin/perl doesn't exactly specify which perl to use, just something under /usr/bin, right?

At least it gives you one place to look.  The above solution would search the path in order, meaning that any change to the path could change your Perl.

Obviously a symlink would also work and might be the best short term solution.

I'll think about this, but I'm not in a hurry to make a change.

**Comment by dwsteele** [comment]
I think I'd rather leave this as-is.  If it gets package for a system with an alternate Perl location it can be patched.
