### ISSUE TITLE
stanza-create raises P00  ERROR: [131]: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by seadba** [pgbackrest/pgbackrest#342]
hello, i am running v1.7 and trying to create a new stanza with the following

-bash-4.1$ pgbackrest --stanza=edb --log-level-console=detail stanza-create
2017-04-13 15:25:09.832 P00   INFO: stanza-create command begin 1.17: --db-path=/u01/PostgresPlus/9.5AS/data --db-port=5444 --log-level-console=detail --repo-path=/u03/backup --stanza=edb
2017-04-13 15:25:09.924 P00  ERROR: [131]: fe_sendauth: no password supplied
2017-04-13 15:25:09.928 P00   INFO: stanza-create command end: aborted with exception [131]

i assume this is a pg_hba.conf issue but my .pgpass file is set correctly - what am i missing?  thanks

**Comment by seadba** [comment]
sorry, had to set trust in hba - that worked - is it possible to avoid that?

bash-4.1$ pgbackrest --stanza=edb --log-level-console=detail stanza-create
2017-04-13 15:45:50.613 P00   INFO: stanza-create command begin 1.17: --db-path=/u01/PostgresPlus/9.5AS/data --db-port=5444 --log-level-console=detail --repo-path=/u03/backup --stanza=edb
2017-04-13 15:45:51.043 P00   INFO: stanza-create command end: completed successfully
-bash-4.1$

**Comment by dwsteele** [comment]
The best way is to allow peer access to postgres, since the process must run as postgres anyway.  Seems like a .pgpass file should work as well but I have not tried it.  I don't ever set a password for postgres.

**Comment by seadba** [comment]
thanks for the fast response - great product

**Comment by dkumarr2** [comment]
pgbackrest --stanza=demo stanza-create
2017-08-16 08:51:45.499 P00  ERROR: [056]: could not connect to server: No such file or directory
                                                Is the server running locally and accepting
                                                connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Can you please guide me why the error is raising as I done all the configuration correct

**Comment by dwsteele** [comment]
If you already had a cluster on your system the new one was probably created on port 5433.  Try using `db-port=5433`.

**Comment by dkumarr2** [comment]
ERROR [042]: : process 'itsusraorclic02 remote' terminated unexpectedly: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

I got this error when I performed remote server backup. Anyone please guide me how to take remote server backup with the configuration steps?

**Comment by krisdba** [comment]
> pgbackrest --stanza=demo stanza-create
> 2017-08-16 08:51:45.499 P00 ERROR: [056]: could not connect to server: No such file or directory
> Is the server running locally and accepting
> connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
> Can you please guide me why the error is raising as I done all the configuration correct

export LD_LIBRARY_PATH to postgre home lib directory solved this for me
