### ISSUE TITLE
Pgbackrest error while trying to take backup.

### ISSUE THREAD

**Issue by jyothsna01** [pgbackrest/pgbackrest#346]
sh: 1: pgbacKrest: not found
LOG:  archive command failed with exit code 127
DETAIL:  The failed archive command was: pgbacKrest --stanza=demo1 archive-push pg_xlog/000000010000000000000004
WARNING:  archiving transaction log file "000000010000000000000004" failed too many times, will try again later

**Comment by dwsteele** [comment]
Looks like you have a typo.  `pgbacKrest` should be `pgbackrest`.
