### ISSUE TITLE
changing the location of /etc/pgbackrest.conf

### ISSUE THREAD

**Issue by nawazahmed1** [pgbackrest/pgbackrest#348]
Hi Folks,

I have a question regarding changing the location of /etc/pgbackrest.conf location. I had installed pgbackrest and I was playing around with it and at some point i wanted to change the location of pgbackrest.conf file from /etc to somewhere else. 

I came across the parameters --db-config, --backup-config and --config (http://www.pgbackrest.org/command.html), and i understand that these parameters can be used to pass the location of the configuration file when it is not in the default location.

The issue here is, I have created a stanza and executed the check command with pgbackrest.conf in the default location and it all worked fine. Then, i changed the pgbackrest.conf to a non-default location and ran the check command again and this is how it unfolds.

> [node2 ~]$ pgbackrest --stanza=95mas --log-level-console=info check
> ERROR [037]: : check command requires option: db-path
> HINT: does this stanza exist?

so then i pass the --config parameter as below, the execution takes a while to return an error as shown

> [node2 ~]$ pgbackrest --stanza=95mas --log-level-console=info --config=/bkup/pgbackrest_conf/pgbackrest.conf check
> 2017-05-04 14:07:21.116 P00   INFO: check command begin 1.18: --config=/bkup/pgbackrest_conf/pgbackrest.conf --db-path=/bkup/fep95AE/95mas/data --db-port=29001 --log-level-console=info --repo-path=/bkup/pgbackrest --stanza=95mas
> 
> ERROR [082]: : could not find WAL segment 00000001000000010000009E after 60 second(s)
> ERROR [082]: : could not find WAL segment 00000001000000010000009E after 60 second(s)
> WARN: WAL segment 00000001000000010000009E did not reach the archive:9.5-1
> HINT: Check the archive_command to ensure that all options are correct (especialy --stanza).
> HINT: Check the PostreSQL server log for errors.
> 2017-05-04 14:08:21.971 P00   INFO: check command end: completed successfully

additionally, i see the below errors in the postgresql_db.log

> ERROR [073]: : **repo-path '/var/lib/pgbackrest'** does not exist
> 2017-05-04 14:11:35 AEST [3891]: [572-1] user=,db=,app=,client= LOG:  archive command failed with exit code 73 (11263)
> 2017-05-04 14:11:35 AEST [3891]: [573-1] user=,db=,app=,client= DETAIL:  The failed archive command was: pgbackrest --stanza=95mas archive-push pg_xlog/00000001000000010000009E (14792)
> 2017-05-04 14:11:35 AEST [3891]: [574-1] user=,db=,app=,client= WARNING:  archiving transaction log file "00000001000000010000009E" failed too many times, will try again later (11262)

As you can see, the repo-path refers to the default /var/lib/pgbackrest location when the default location pf pgbackrest.conf is changed from /etc to /bkup/pgbackrest_conf.

- Has anyone else come across this issue and how do i change the location of pgbackrest.conf on the fly ?
- 
- Do i need to create a stanza after the change of location of pgbackrest.conf file ?
- 
- And if i do so, will pgbackrest be able to pick old backups for a restore ?

Thanks & Regards in advance
Nawaz Ahmed

**Comment by nawazahmed1** [comment]
Followup...

I did create a stanza with the new location for pgbackrest.conf and ran check command with and without --config option, but there was no success. The database log also kept showing the same errors as below.

> [node2 ~]$ pgbackrest --stanza=95mas --log-level-console=info --config=/bkup/pgbackrest_conf/pgbackrest.conf stanza-create
> 2017-05-04 14:16:11.403 P00   INFO: stanza-create command begin 1.18: --config=/bkup/pgbackrest_conf/pgbackrest.conf --db-path=/bkup/fep95AE/95mas/data --db-port=29001 --log-level-console=info --repo-path=/bkup/pgbackrest --stanza=95mas
> 2017-05-04 14:16:11.959 P00   INFO: stanza-create command end: completed successfully


> [node2 ~]$ pgbackrest --stanza=95mas --log-level-console=info check
> ERROR [037]: : check command requires option: db-path
> HINT: does this stanza exist?


> [node2 ~]$ pgbackrest --stanza=95mas --log-level-console=info --config=/bkup/pgbackrest_conf/pgbackrest.conf check
> 2017-05-04 14:17:58.640 P00   INFO: check command begin 1.18: --config=/bkup/pgbackrest_conf/pgbackrest.conf --db-path=/bkup/fep95AE/95mas/data --db-port=29001 --log-level-console=info --repo-path=/bkup/pgbackrest --stanza=95mas
> ERROR [082]: : could not find WAL segment 00000001000000010000009F after 60 second(s)
> ERROR [082]: : could not find WAL segment 00000001000000010000009F after 60 second(s)
> WARN: WAL segment 00000001000000010000009F did not reach the archive:9.5-1
> HINT: Check the archive_command to ensure that all options are correct (especialy --stanza).
> HINT: Check the PostreSQL server log for errors.
> 2017-05-04 14:18:59.565 P00   INFO: check command end: completed successfully



> ERROR [073]: : repo-path '/var/lib/pgbackrest' does not exist
> 2017-05-04 14:22:13 AEST [3891]: [649-1] user=,db=,app=,client= LOG:  archive command failed with exit code 73 (11263)
> 2017-05-04 14:22:13 AEST [3891]: [650-1] user=,db=,app=,client= DETAIL:  The failed archive command was: pgbackrest --stanza=95mas archive-push pg_xlog/00000001000000010000009E (14792)
> 2017-05-04 14:22:13 AEST [3891]: [651-1] user=,db=,app=,client= WARNING:  archiving transaction log file "00000001000000010000009E" failed too many times, will try again later (11262)

**Comment by nawazahmed1** [comment]
Hi Guys,

This is resolved, i changed the archive_command to include --config=/bkup/pgbackrest_conf/pgbackrest.conf and it worked like a charm. However, there is another issue that i came across with recovery which i will raise as a separate issue.

Thanks & Regards,
Nawaz

**Comment by dwsteele** [comment]
Glad you got it resolved!
