### ISSUE TITLE
defunct processes

### ISSUE THREAD

**Issue by tvernick** [pgbackrest/pgbackrest#352]
We seem to getting a lot of defunct processes from backup jobs with version 1.18 using CentOS 7.3.1611. It looks like the most recent backup is stuck at 96% as well.

[root@datawarehouse002 ~]# ps -ef |grep pg
postgres   487   486  0 00:45 ?        00:01:38 /usr/bin/perl /usr/bin/pgbackrest --stanza=data --db-port=5433 --type=full backup
postgres   490   487  0 00:45 ?        00:00:00 ssh -o LogLevel=error -o Compression=no -o PasswordAuthentication=no postgres@10.100.131.136 /usr/bin/pgbackrest-release-1.18 --buffer-size=8388608 --command=backup --compress-level=3 --compress-level-network=3 --db-port=5433 --db-socket-path=/tmp --db-timeout=30000 --protocol-timeout=35000 --repo-path=/data/backups/postgres/pgbackrest_repo --stanza=data --type=db remote
postgres   683   487  0 00:47 ?        00:06:25 /usr/bin/perl /usr/bin/pgbackrest-release-1.18 --buffer-size=8388608 --command=backup --compress-level=3 --db-host=10.100.131.136 --db-socket-path=/tmp --db-timeout=30000 --db-user=postgres --db2-host=datawarehouse002.peer1.jfk.corp.squarespace.net --db2-user=postgres --host-id=1 --process=1 --protocol-timeout=35000 --repo-path=/data/backups/postgres/pgbackrest_repo --stanza=data --type=db local
postgres   684   683  0 00:47 ?        00:00:00 ssh -o LogLevel=error -o Compression=no -o PasswordAuthentication=no postgres@10.100.131.136 /usr/bin/pgbackrest-release-1.18 --buffer-size=8388608 --command=backup --compress-level=3 --compress-level-network=3 --db-socket-path=/tmp --db-timeout=30000 --process=1 --protocol-timeout=35000 --repo-path=/data/backups/postgres/pgbackrest_repo --stanza=data --type=db remote
postgres   685   487  0 00:47 ?        00:04:38 [pgbackrest-rele] <defunct>
postgres   687   487  0 00:47 ?        00:04:27 [pgbackrest-rele] <defunct>
postgres   692   487  0 00:47 ?        00:04:10 [pgbackrest-rele] <defunct>
postgres   695   487  0 00:47 ?        00:04:44 [pgbackrest-rele] <defunct>
postgres   698   487  0 00:47 ?        00:04:40 [pgbackrest-rele] <defunct>
postgres   701   487  0 00:47 ?        00:04:20 [pgbackrest-rele] <defunct>
postgres   704   487  0 00:47 ?        00:04:05 [pgbackrest-rele] <defunct>
postgres   707   487  0 00:47 ?        00:04:33 [pgbackrest-rele] <defunct>
postgres 25830     1  0 Apr30 ?        00:03:48 /usr/pgsql-9.6/bin/postgres -D /dbdata/9.6/data

**Comment by tvernick** [comment]
The bottom processes were defunct, didn't show up in my original paste

postgres   685   487  0 00:47 ?        00:04:38 [pgbackrest-rele] <defunct>
postgres   687   487  0 00:47 ?        00:04:27 [pgbackrest-rele] <defunct>
postgres   692   487  0 00:47 ?        00:04:10 [pgbackrest-rele] <defunct>
postgres   695   487  0 00:47 ?        00:04:44 [pgbackrest-rele] <defunct>
postgres   698   487  0 00:47 ?        00:04:40 [pgbackrest-rele] <defunct>
postgres   701   487  0 00:47 ?        00:04:20 [pgbackrest-rele] <defunct>
postgres   704   487  0 00:47 ?        00:04:05 [pgbackrest-rele] <defunct>
postgres   707   487  0 00:47 ?        00:04:33 [pgbackrest-rele] <defunct>

**Comment by tvernick** [comment]
`postgres   685   487  0 00:47 ?        00:04:38 [pgbackrest-rele] <defunct>
postgres   687   487  0 00:47 ?        00:04:27 [pgbackrest-rele] <defunct>
postgres   692   487  0 00:47 ?        00:04:10 [pgbackrest-rele] <defunct>
postgres   695   487  0 00:47 ?        00:04:44 [pgbackrest-rele] <defunct>
postgres   698   487  0 00:47 ?        00:04:40 [pgbackrest-rele] <defunct>
postgres   701   487  0 00:47 ?        00:04:20 [pgbackrest-rele] <defunct>
postgres   704   487  0 00:47 ?        00:04:05 [pgbackrest-rele] <defunct>
postgres   707   487  0 00:47 ?        00:04:33 [pgbackrest-rele] <defunct>`

**Comment by dwsteele** [comment]
There's not a lot to go on here.  Did the backup finish?

Can you provide logs at DEBUG level?

**Comment by dwsteele** [comment]
Looking through the code a bit, I can see that child processes are not always reaped until all of them have finished.  I think the issue probably lies elsewhere, but without logs it's hard to say.
