### ISSUE TITLE
Tiny error in installation documentation

### ISSUE THREAD

**Issue by LaetitiaLoxo** [pgbackrest/pgbackrest#356]
Hi,

I just wanted to point a tiny error in installation documentation. If you're not root, you can't
`sudo wget -q -O - \
       https://github.com/pgbackrest/pgbackrest/archive/release/1.18.tar.gz | \
       tar zx -C /root`

You must do:
`sudo wget -q -O - \
       https://github.com/pgbackrest/pgbackrest/archive/release/1.18.tar.gz | \
       sudo tar zx -C /root`

It's a tiny error and most users can solve it by themself (and those who can't shouldn't have root permissions), but I think it was worth reporting it.

Regards,

Lætitia

**Comment by dwsteele** [comment]
Definitely worth reporting!  Even small issues can be really annoying...

How would you like to appear in the release notes?  Is "Lætitia Loxo" correct?

**Comment by LaetitiaLoxo** [comment]
Just Lætitia is OK...

**Comment by dwsteele** [comment]
Fixed at 74053ed.
