### ISSUE TITLE
Issue starting backup using pgbackrest 1.09 and postgresql db with 9.6 version

### ISSUE THREAD

**Issue by jyothsna01** [pgbackrest/pgbackrest#358]
ERROR [133]: version '9.6' and db-path '/var/lib/postgresql/9.6/main' queried from cluster does not match version '9.6' and db-path '/var/lib/postgresql/9.6/demo' read from '/var/lib/postgresql/9.6/demo/global/pg_control'
HINT: the db-path and db-port settings likely reference different clusters
2017-05-18 13:43:34.893 P00   INFO: backup stop

**Comment by cmwshang** [comment]
Your pgbackrest.conf db-path and/or stanza appears to be configured incorrectly. The cluster indicates it is "main" but the conf file indicates "demo". Is this a new install? The Users Guide uses demo as an example cluster, but you need to configure it for how you set up your cluster.

Also, version 1.09 is rather old so I'd also recommend upgrading to the latest release if possible (see http://www.pgbackrest.org/release.html <http://www.pgbackrest.org/release.html>).

Cynthia Shang
www.crunchydata.com

**Comment by jyothsna01** [comment]
Awesome, I changed the configurations to main and its good now.
I have few questions on PGBACKREST before I implement it in my environment.
1.How much time will it take backup the database of 1Tb in size.
2.My database is 9.5 version and which version of pgbackrest is better for this version in postgresql.
3.Can we have secure backups with this.

**Comment by cmwshang** [comment]
> 1.How much time will it take backup the database of 1Tb in size.
> 

That all depends on your environment. Are you using VMs? Is your backup server offsite? Is pgBackRest running on its own server? etc. To get the most speed will depend on your hardware as well. A good rule of thumb for a dedicated backup server is to run with process-max set to 25% of CPUs (say machine has 8 CPUs then you could start with process-max=2). I would recommend testing different settings (compression as well) before going live in production. Generally a backup schedule will consist of a weekly full backup and then incremental and/or differential backups off the full back up during the week - which will of course be much faster.

> 2.My database is 9.5 version and which version of pgbackrest is better for this version in postgresql.
> 
The latest version of pgBackRest is always recommended, especially for new installs.

> 3.Can we have secure backups with this.
> 

If you mean encryption, pgBackRest does not encypt the data however there are other ways, such as encrypted disks, to handle this.

Thanks for your interest in pgBackRest!

Cynthia Shang
www.crunchydata.com

**Comment by jyothsna01** [comment]
Appreciate your response  on this issue.
