### ISSUE TITLE
Validation of pgbackrest.conf

### ISSUE THREAD

**Issue by uspen** [pgbackrest/pgbackrest#363]
I use v 1.17, but after upgrade to 1.18:
WARN: /etc/pgbackrest.conf file contains invalid option 'db4-host'
WARN: /etc/pgbackrest.conf file contains invalid option 'db3-user'
WARN: /etc/pgbackrest.conf file contains invalid option 'db3-path'
WARN: /etc/pgbackrest.conf file contains invalid option 'db4-path'
WARN: /etc/pgbackrest.conf file contains invalid option 'db3-port'
WARN: /etc/pgbackrest.conf file contains invalid option 'db4-port'
WARN: /etc/pgbackrest.conf file contains invalid option 'db4-user'

May be its only 2 node cluster? I use more 3 replica

And backup not started - WAL archive failed.

**Comment by blogh** [comment]
Hi, 

I think you get the warning because in 1.18:
> Added validation of pgbackrest.conf to display warnings if options are not valid or are not in the correct section. (Contributed by Cynthia Shang.)

I think it's two node only. cf #248

Benoit

**Comment by uspen** [comment]
Hm.. strange. I changed the value

db-timeout=3600
protocol-timeout=3630

and WAL not push.

I remove this option and WAL work again

**Comment by dwsteele** [comment]
Any errors in the Postgres log?  They should help track down why setting the timeouts was an issue.

**Comment by uspen** [comment]
pgbackrest --stanza=prod01 check

ERROR [157]: could not find WAL segment 0000000B000000E4000000AF after 60 second(s)
ERROR [157]: could not find WAL segment 0000000B000000E4000000AF after 60 second(s)
WARN: WAL segment 0000000B000000E4000000AF did not reach the archive:9.6-1
HINT: Check the archive_command to ensure that all options are correct (especialy --stanza).
HINT: Check the PostreSQL server log for errors.

log:

2017-05-24 15:15:55 MSK 1495628155.552 [16104]: [3-1] user=postgres,db=postgres,client=[local] LOG:  restore point "pgBackRest Archive Check" created at E4/AF1C5A48
2017-05-24 15:15:55 MSK 1495628155.552 [16104]: [4-1] user=postgres,db=postgres,client=[local] STATEMENT:  select pg_create_restore_point('pgBackRest Archive Check');
ERROR [107]: remote process terminated on backup.db host: no error on stderr
2017-05-24 15:15:56 MSK 1495628156.511 [15458]: [13118-1] user=,db=,client= LOG:  archive command failed with exit code 107
2017-05-24 15:15:56 MSK 1495628156.511 [15458]: [13119-1] user=,db=,client= DETAIL:  The failed archive command was: pgbackrest --stanza=prod01 archive-push pg_xlog/0000000B000000E4000000AF

**Comment by dwsteele** [comment]
Nothing is jumping out at me here.  I'm making improvements in this area - perhaps we'll be able to get a better error in the next version.

Meanwhile, I would keep the timeouts at defaults as long as that is not causing issues.

**Comment by uspen** [comment]
Thank you
