### ISSUE TITLE
aborted with exception [134]

### ISSUE THREAD

**Issue by seadba** [pgbackrest/pgbackrest#364]
hello , we've been running daily backups on 3TB db with no issues - today we received following error  
2017-05-31 18:41:03.802 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2017-05-31 19:11:04.043 P00   INFO: backup command end: aborted with exception [134]

db is up and accessible - -check works fine - i can't find an occurrence of this - any idea?

Thanks - great product

**Comment by dwsteele** [comment]
Looks like the `pg_stop_backup()` command timed out.  You can increase `db-timeout` (which defaults to 30 minutes) or use parallel archiving to make archiving run faster.

PostgreSQL will not return from `pg_stop_backup()` until all WAL required for the backup has been archived. I added a feature to 10.0 which eliminates this wait, but for now we have to live with it.

**Comment by seadba** [comment]
thanks very much for the fast response - it appears that another admin was running vacuum full on several large tables yesterday, so that explains it, - great tool, thats the first error we've seen using this - thanks again

**Comment by dwsteele** [comment]
No problem - glad you like it!

Quick question - there should have also been an ERROR message in the log.  Did you not see one?

The `aborted with exception [134]` is just a catchall that reports the exit code, but it doesn't give details.  Those are given in the ERROR message.

**Comment by seadba** [comment]
no, no error message - we use this setting  --log-level-console=info

**Comment by seadba** [comment]
plenty of these in the  db log at the time 

2017-05-31 17:50:43 EDT [29394]: [1285-1] user=,db=,app=,client=LOG:  checkpoints are occurring too frequently (21 seconds apart)
2017-05-31 17:50:43 EDT [29394]: [1286-1] user=,db=,app=,client=HINT:  Consider increasing the configuration parameter "max_wal_size".
