### ISSUE TITLE
unable to backup from standby 9.6

### ISSUE THREAD

**Issue by internetuser2008** [pgbackrest/pgbackrest#368]
I am unable to backup from streaming standby slave, following steps per documentation. Am I missing something?

archive_command = 'pgbackrest --stanza=uv archive-push %p'

[global]
backup-standby=y
process-max=3
repo-path=/mnt/backup/pgbackrest/
retention-full=2
start-fast=y
retention-diff=8
stop-auto=y
archive-check=y
#thread-timeout=300
db-timeout=180
protocol-timeout=200

[db]
db1-host=192.168.99.103
db1-path=/mnt/db/pgsql/data/
db1-user=postgres
db2-host=192.168.99.100
db2-path=/mnt/db/pgsql/data/
db2-user=postgres
#db-port=5432

2017-06-04 09:11:29.180 P00   INFO: check command begin 1.18: --archive-check --backup-standby --db-host=192.168.99.103 --db-path=/mnt/db/pgsql/data/ --db-timeout=180 --db-user=postgres --db2-host=192.168.99.100 --db2-path=/mnt/db/pgsql/data/ --db2-user=postgres --log-level-console=detail --protocol-timeout=200 --repo-path=/mnt/backup/pgbackrest/ --stanza=db
ERROR [082]: : could not find WAL segment 000000010000000000000055 after 60 second(s)
ERROR [082]: : could not find WAL segment 000000010000000000000055 after 60 second(s)
WARN: WAL segment 000000010000000000000055 did not reach the archive:9.6-1
HINT: Check the archive_command to ensure that all options are correct (especialy --stanza).
HINT: Check the PostreSQL server log for errors.
2017-06-04 09:12:32.522 P00   INFO: check command end: completed successfully

postgres.log
HINT: Is %f passed to archive-push instead of %p?
HINT: PostgreSQL may pass relative paths even with %p depending on the environment.
< 2017-06-04 09:21:59.765 PDT > LOG:  archive command failed with exit code 37
< 2017-06-04 09:21:59.765 PDT > DETAIL:  The failed archive command was: pgbackrest --stanza=db archive-push pg_xlog/00000001000000000000004E
< 2017-06-04 09:21:59.765 PDT > WARNING:  archiving transaction log file "00000001000000000000004E" failed too many times, will try again later

**Comment by dwsteele** [comment]
Is this config from your backup host?  If so, it would be helpful to see the configs from the master and slave.

The error code you are getting is "missing option", though the portion of the log you pasted does not show any of the pgbackrest output.  Are you sure you got all of it?

**Comment by markovii** [comment]
Is it possible to backup from streaming Standby (in postgresql style implementation)?
Since master is already archiving to to Standby (archive_command 'rsync -a %p rsync://192.168.0.233/sync/%f') then I tried to configure Standby archive configuration (archive_command = 'pgbackrest --stanza=demo archive-push %p').

Testing this gives me error 'ERROR [068]: : archive_command 'rsync -a %p rsync://192.168.0.233/sync/%f' must contain 'pgbackrest'' which seems to indicate that only archiving from master is allowed.

Is it so or is there is there a way to use replication in postgresql style and use pgbackrest standby backup?

**Comment by dwsteele** [comment]
The `archive_command` must be configure on the master.  pgBackRest does not support streaming replication for WAL archiving, primarily because it is slow and transmits uncompressed data.

**Comment by internetuser2008** [comment]
Setup has one Master and one Slave configuration using pg native replication. Pgbackreset configured same way on both nodes and executing pgbackreset backup from the salve node so, basically using slave host as backup node.

Both nodes have same postgressql.conf and pgbackrest.conf settigns:
archive_command = 'pgbackrest --stanza=uv archive-push %p'

[global]
 backup-standby=y
 process-max=3
 repo-path=/mnt/backup/pgbackrest/
 retention-full=2
 start-fast=y
 retention-diff=8
 stop-auto=y
 archive-check=y
 #thread-timeout=300
 db-timeout=180
 protocol-timeout=200

[db]
 db1-host=192.168.99.103
 db1-path=/mnt/db/pgsql/data/
 db1-user=postgres
 db2-host=192.168.99.100
 db2-path=/mnt/db/pgsql/data/
 db2-user=postgres
 #db-port=5432

Let me know if still additional information is needed.

**Comment by cmwshang** [comment]
Why is your stanza=uv in the archive_command but in the pgbackrest.conf file it is [db]?

**Comment by dwsteele** [comment]
Backing up to your standby is not recommended.  It's possible, but the configurations are not symmetric and do not play well with failover.

**Comment by internetuser2008** [comment]
Sorry that stanza should be [db] I have updated that.

**Comment by dwsteele** [comment]
If you don't have a backup server, v1.19 introduces S3 support.  Have you considered that?  Backing up to one of your database servers is not a good configuration.
