### ISSUE TITLE
add support for IA storage class in S3 buckets

### ISSUE THREAD

**Issue by hunleyd** [pgbackrest/pgbackrest#371]
Now that we have support for S3 buckets as a backend (thanks!!) can we get support for IA as well? I use `duplicity` to backup my non-pg bits and it has a `--s3-use-ia` option:
> Store volumes using Standard - Infrequent Access when uploading to Amazon S3. This storage class has a lower storage cost but a higher per-request cost, and the storage cost is calculated against a 30-day storage minimum. According to Amazon, this storage is ideal for long-term file storage, backups, and disaster recovery.

I know that I can accomplish this by setting a Lifecycle on my bucket (and I have) but the files need to be *at least* 30 days old before they will migrate to IA via Lifecycle. It would be great if I could store them in IA from the get-go like `duplicity` allows. Maybe a new option like:
```
repo-s3-storage-class = normal (default)
repo-s3-storage-class = ia
```

Thanks for considering!

**Comment by dwsteele** [comment]
I definitely thought about this but it's not as much of an advantage as it seems.  There are parts of the repo that are deleted (diff, incr backups) and retrieved (WAL, backup resume, restore) quite frequently so you can really end up racking up a lot of surcharges by using IA too quickly.  It depends on your usage patterns, but for the systems I administer I determined IA would always end up being more expensive.

Duplicity is a bit different because you are not really expecting to access those files except in an emergency - the pgBackRest repo is expected to be a living backup that is frequently accessed.

That doesn't mean we won't do it.  I've just been trying to think of a way to do it that makes sense and does not end up costing more money than standard storage.

**Comment by hunleyd** [comment]
Understood. Just thought I'd ask to get it out there :)

FWIW, even if _some_ of the files went to IA and others did not that could be a win (depending on use case, as you say). That's actually what I do for duplicity (the manifests and other metadata stay in normal storage, the actual archives go to IA).

I'm just happy to hear that someone is thinking about it, so thanks!

**Comment by dwsteele** [comment]
I'm still struggling to see how this would be a good thing for most backup scenarios.  Just deleting the differential and incremental backups will chew up any savings you might have for the repo, not to mention the extra data transfer costs.  I think the 30 day transition in the S3 bucket is the way to go.  Of course metatdata could stay in normal storage but that's hardly a big cost.

I'm going to close this for now, but I'll keep it in mind.

**Comment by ganeshkannan** [comment]
@dwsteele - We have a use case where we have a massive Postgres DB (multiple TB in size), and given the nature of the data we plan to do a full backup, and then a bunch of incrementals/differentials. Our first backup (full) will be huge, but the new added to the db will be relyatively tin (appx. 0.5% daily change). 

It would be ideal if we could store each full back up in s3-IA, and the incremental in s3 given we don't need to keep them around for more than a few days. Another option would be if we could set up s3 lifecycle policy to transfer from s3 to s3-IA, however the s3 key (prefix) convention used by pgbackrest now won't work. 

If direct s3-IA support is not being considered, could you consider either restructuring the path of backups in s3 (full, differential, incremental) such that users can set up lifecycle based on prefix. (or), if you support adding Tags" to objects, then we could set up lifecycle policy based on tag values. Thank you for your consideration.

**Comment by dwsteele** [comment]
You'd need to keep the full backups for more than 30 days for this scheme to work, but it seems like it could be helpful.

We are just about to start migrating the backup command to C so nothing will happen on this until that is done, at the earliest.  While I'm working on that code I'll think about what we can do about IA.
