### ISSUE TITLE
S3 backups fail: SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by sfrazer** [pgbackrest/pgbackrest#372]
Fresh installation, trying to backup to S3. Server is CentOS 7.3.1611, Postgres 9.6 from the postgresql.ord redhat repo

Conf file:
```
[global]
repo-path=/var/lib/pgbackrest
log-level-console=info
repo-s3-bucket=backups.example.com
repo-s3-endpoint=s3.amazonaws.com
repo-s3-key=***
repo-s3-key-secret=***
repo-s3-region=us-east-1
repo-type=s3
retention-full=2
start-fast=y


[96]
db-path=/var/lib/pgsql/9.6/data
db-port=5432
repo-path=/database13

```

Trying to create the stanza give me this:
```
$ sudo -u postgres pgbackrest --stanza=96 stanza-create
2017-06-15 10:17:47.377 P00   INFO: stanza-create command begin 1.19: --db-path=/var/lib/pgsql/9.6/data --db-port=5432 --log-level-console=info --repo-path=/database13 --repo-s3-bucket=backups.example.com --repo-s3-endpoint=s3.amazonaws.com --repo-s3-region=us-east-1 --repo-type=s3 --stanza=96
2017-06-15 10:17:47.886 P00  ERROR: [039]: unable to connect : IO::Socket::IP configuration failed SSL connect attempt failed with unknown error error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2017-06-15 10:17:47.888 P00   INFO: stanza-create command end: aborted with exception [039]

```

This seems to be a curl error trying to open the S3 bucket?

**Comment by dwsteele** [comment]
You CA certs are probably out of date.  Have you run `sudo yum update ca-certificates`?

**Comment by sfrazer** [comment]
`ca-certificates.noarch 0:2017.2.14-70.1.el7_3 `

still gives the same error

**Comment by dwsteele** [comment]
What's the output from this command: `openssl s_client -connect s3.amazonaws.com:443`

**Comment by dwsteele** [comment]
Mostly you'll be interested in this info at the end.  This is from a CentOS 7.3.1611 system:
```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 1AD84948AAC0E5C3D915E59B3D2979468A1F09C79022C55169177F3CB7E3869F
    Session-ID-ctx:
    Master-Key: C57AC7056CD4B8B82D7271F48DC1AE0115ED14D7D66AD610B9EAA24EE43667CE33ADA0C8E576D20884373EBDE50200B5
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1497621084
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```

**Comment by sfrazer** [comment]
```
sudo -u postgres openssl s_client -connect s3.amazonaws.com:443
CONNECTED(00000003)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Baltimore CA-2 G2
verify return:1
depth=0 C = US, ST = Washington, L = Seattle, O = Amazon.com Inc., CN = s3.amazonaws.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Washington/L=Seattle/O=Amazon.com Inc./CN=s3.amazonaws.com
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Baltimore CA-2 G2
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Baltimore CA-2 G2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
<snip>
-----END CERTIFICATE-----
subject=/C=US/ST=Washington/L=Seattle/O=Amazon.com Inc./CN=s3.amazonaws.com
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Baltimore CA-2 G2
---
No client certificate CA names sent
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 3146 bytes and written 373 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: B95954B87DF94D19A757E0CA0895F2A0186B3E101FB0A8F5CA0596CCFF363172
    Session-ID-ctx: 
    Master-Key: B877B4319FE7DAA70F20BAE0D8D5EB85DC85832F3ACD5EEA5509847D9D1B47FA19F255B9B9C2411476BE55A1D696878D
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1497622033
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
closed
```

**Comment by sfrazer** [comment]
It seems like it's only libcurl that isn't able to complete the handshake. Calling curl from the commandline doesn't give an error:

```
sudo -u postgres curl -I https://s3.amazonaws.com
HTTP/1.1 405 Method Not Allowed
x-amz-request-id: A34AA3948A03D3F4
x-amz-id-2: d8TJC7i5FbrwVe2Zlc/K/osWFJ+5/98ABpKDEU3FojDPVzIFrVY9bFlCsH2O2eZNKOtzyMzsUWg=
Allow: GET
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Fri, 16 Jun 2017 14:20:02 GMT
Server: AmazonS3
```

**Comment by dwsteele** [comment]
OK, I have reproduced it:
```
perl -e 'use IO::Socket::SSL qw(debug3);IO::Socket::SSL->new(PeerAddr=>"s3.amazonaws.com",PeerPort=> 443,Proto=>"TCP",SSL_verify_mode=>SSL_VERIFY_PEER) or die $!'
```

This command works on every OS/version we test on (including CentOS 6) but does not work on CentOS 7.  SELinux does not appear to be a factor - I think it must be some version mismatch or some kind of enforcement.  I can't look at this any more today but I'll pick it up next week.

**Comment by dwsteele** [comment]
I found a few more minutes to play with this.  Looks like upgrading `IO::Socket::SSL` works:
```
cpanm install IO::Socket::SSL
```
This is not a good solution in my opinion but the version of IO::Socket::SSL on CentOS7 is truly ancient and is likely missing required security fixes.  You could source this package from a new Fedora version but I personally wouldn't do that on a production system.

I'll check with colleagues who know RH/CentOS better than I do.

**Comment by sfrazer** [comment]
Thanks much for looking into this!

**Comment by dwsteele** [comment]
It appears that Rad Hat is aware of this issue (since 2016-12): https://bugzilla.redhat.com/show_bug.cgi?id=1402588

I tried their proposed patch and it works.  I've left a comment to see if it will make it into an upcoming release.  Either way I will probably add some additional options to BR to use alternate CA files.

**Comment by dwsteele** [comment]
Even if Red Hat does fix this, it'll probably be a while before it comes out.  I have added new options, `s3-repo-ca-file` and `s3-repo-ca-path` which will solve this problem and add some flexibility in general (5b9291b80323).

In your case the config would be:
```
s3-repo-ca-file=/etc/pki/tls/certs/ca-bundle.crt
```
If you are just testing you can use `repo-s3-verify-ssl=n` for the time being.  I'm expecting another release next week sometime.

**Comment by sfrazer** [comment]
Thanks! I'm out of the office this week but I'll try it out early next week and let you know how it goes.

**Comment by sfrazer** [comment]
This works like a charm! Thanks!

**Comment by dwsteele** [comment]
I appreciate you testing that!  We'll get the official 1.20 release out by Wednesday.

**Comment by dwsteele** [comment]
They did finally fix the issue (https://bugzilla.redhat.com/show_bug.cgi?id=1402588): https://access.redhat.com/errata/RHEA-2018:0688

So the workaround should no longer be needed with an up-to-date RHEL 7.5.
