### ISSUE TITLE
Cannot backup with custom archieve_command 

### ISSUE THREAD

**Issue by edib** [pgbackrest/pgbackrest#373]
code [767:776 lines] in ./lib/pgBackRest/Db.pm requires pgbackrest command  in archieve_command. I have a custom script as an archieve_command, then pgbacrest does not work.

**Comment by dwsteele** [comment]
You must set `archive-check=n` if you want to use your own `archive_command`.

However, you should only use your own archive command in the most extreme circumstances.  Archiving is a lot harder that it looks and you are losing a lot by not using the built-in command.

Is there some need that the pgBackRest archive command is not fulfilling?

**Comment by edib** [comment]
Yes, we have a streaming replication via archive_command, then we put  pgbackrest archive command  into custom bash script.

**Comment by dwsteele** [comment]
I prefer to feed a replica directly off the repository if it is not too far away.  Maintaining two WAL archives is costly in terms of time and space.

Anyway, food for thought.

**Comment by edib** [comment]
Thanks, I will consider.
