### ISSUE TITLE
pgbackrest delete backup

### ISSUE THREAD

**Issue by petercelentano** [pgbackrest/pgbackrest#379]
I've searched through the documentation, and I cannot find any options to delete a specific backup using pgbackrest.  If this is not already a feature, I would like to submit this feature request.

**Comment by uspen** [comment]
This is break WAL archiving. Its hard work

**Comment by petercelentano** [comment]
I can accomplish it by manually editing the backup.info file within a stanza directory (to delete the backup to remove) and delete the directory containing the backup to remove).  Is this a bad idea?  I wish that backrest had this functionality (this can easily be done in barman).

**Comment by sfrost** [comment]
The appropriate way to expire out a backup is to use the 'expire' command and set the retention to how many backups you would like to keep.  This also ensures that the WAL is cleaned up.

**Comment by petercelentano** [comment]
What if I have a failed backup in sandwiched in-between several other good backups, and I only want to remove the failed backup?  Is is possible to "expire" a specific backup in this circumstance?

**Comment by sfrost** [comment]
Failed backups never make it into the repo proper, they only exist in a tmp directory and will never show up in info or be considered viable.

**Comment by dwsteele** [comment]
This behavior has changed a bit in 1.19.  S3 support required that directories not be moved around, so that last backup *might* be in progress/invalid.  However, pgBackRest will always resume or remove that backup when a new backup begins so the overall behavior remains the same.

**Comment by tszilv** [comment]
I tried to delete one full backup. I don't have place in the directory of backup. Recently I try the possibilities of pgbackrest.My opinion is, that the manually delete from repository is important.
I tried to set -repo1-retention-full=0, but the vali value for this parameter:1-99999..
How can I delete only one full backup?

**Comment by dwsteele** [comment]
@tszilv There must always be at least one full backup -- if you delete it the repository is useless.  If you are done with the repository you can use `stanza-delete` to remove it.

**Comment by cmwshang** [comment]
@tszilv It is good practice to set a retention schedule so that pgBackRest automatically expires (deletes) old backups for you based on the schedule you define. See https://pgbackrest.org/user-guide.html#retention for more information.

**Comment by tszilv** [comment]
Problem is that by the https://pgbackrest.org/configuration.html , the  --repo-retention-full parameter valid values are:
allowed: 1-9999999
By my situation the  --repo-retention-ful should have been =0.
If I delete the directories, I have got warning by check command.
How can I eliminate this warning, I mean not to delete from backup.info by hand?

**Comment by tszilv** [comment]
Thank you. 

There is life situation, when I have to delete an full
or incemental backup, not the latest, the backup is between oldest and
newest one. 

Ho can I proceed this situation? 

Some time there is not
enough space in the filesystem, and backup is running, I have to free
space immedietly. The oldest full backup is important some reason. 

I
have the all wal logs , and I can restore the oldest full backup, and
rollforward ba wal logs. 

Regrads, 

  

Szilvia 

  

On Mon, 30 Jul
2018 07:14:42 -0700, David Steele wrote: 

> @tszilv [1] There must
always be at least one full backup -- if you delete it the repository is
useless. If you are done with the repository you can use stanza-delete
to remove it. 
> 
> —
> You are receiving this because you were
mentioned.
> Reply to this email directly, view it on GitHub [2], or
mute the thread [3].

  

Links:
------
[1]
https://github.com/tszilv
[2]
https://github.com/pgbackrest/pgbackrest/issues/379#issuecomment-408878368
[3]

**Comment by cmwshang** [comment]
@tszilv If you are having to scramble to make room for backups then it doesn't matter what backup software solution you are trying to use because you aren't optimized to safely backup your environment. You should go back and reevaluate what your "best practices" should be for your environment. At a minimum, in pgbackrest, you can set retention to one so that you at least have a full backup (since not having at least one is useless) and figure out a proper schedule for differential and/or incremental backups that meet your needs.

**Comment by tszilv** [comment]
I search the possibities to delete an backup by tag or by date.
This possibilities are in barman and rman . 

On Tue, 31 Jul 2018
08:07:23 -0700, Cynthia Shang wrote: 

> @tszilv [1] If you are having
to scramble to make room for backups then it doesn't matter what backup
software solution you are trying to use because you aren't optimized to
safely backup your environment. You should go back and reevaluate what
your "best practices" should be for your environment. At a minimum, in
pgbackrest, you can set retention to one so that you at least have a
full backup (since not having at least one is useless) and figure out a
proper schedule for differential and/or incremental backups that meet
your needs. 
> 
> —
> You are receiving this because you were
mentioned.
> Reply to this email directly, view it on GitHub [2], or
mute the thread [3].

  

Links:
------
[1]
https://github.com/tszilv
[2]
https://github.com/pgbackrest/pgbackrest/issues/379#issuecomment-409254274
[3]

**Comment by dwsteele** [comment]
We are planning to add a feature to allow a single backup to be removed out of schedule, but have not yet done so.  It sounds like you would be best off doing only full backups so that older backups are easier to expire.  You can always manually expire older backups like this:
```
pgbackrest --stanza=<name> --repo1-retention-full=1 expire
```

**Comment by tszilv** [comment]
If some backup is damaged in the repository( myba sombody deleted
it), ho can I validate/syncronize repository? 

If I have deleted an
file from the backup, after I made check on stanza,the check did not
realize the missing file. 

  

On Mon, 30 Jul 2018 07:14:42 -0700,
David Steele wrote: 

> @tszilv [1] There must always be at least one
full backup -- if you delete it the repository is useless. If you are
done with the repository you can use stanza-delete to remove it. 
> 
>
—
> You are receiving this because you were mentioned.
> Reply to this
email directly, view it on GitHub [2], or mute the thread [3].

 


Links:
------
[1] https://github.com/tszilv
[2]
https://github.com/pgbackrest/pgbackrest/issues/379#issuecomment-408878368
[3]

**Comment by dwsteele** [comment]
Backups are validated during restore.  Currently there's no way to independently validate a backup.  Regularly testing restores should be part of your DR strategy.

As the documentation states, "The check command validates that pgBackRest and the archive_command setting are configured correctly for archiving and backups."
