### ISSUE TITLE
restore stanza backup to remote target

### ISSUE THREAD

**Issue by petercelentano** [pgbackrest/pgbackrest#380]
In pgbackrest, is there a method to restore a backup of a given stanza onto a different remote host (which is not the same host that is being backed up).  If there is no means to do this already, I would like to request that the feature be added.

**Comment by uspen** [comment]
pgbackrest --stanza=STANZA --delta --db-path=THIS! restore

**Comment by petercelentano** [comment]
This only works for changing the local DB restore location.  Is there a way to accomplish this so that I can REMOTE from a remote backup server onto a REMOTE host?

**Comment by uspen** [comment]
Not have a function.
ssh

**Comment by sfrost** [comment]
In this scenario:

Backup server (where the pgbackrest repository lives) is: 'backup'
System to restore the backup on to is: 'db1'

You should configure /etc/pgbackrest.conf on 'db1' to be:

-----------------
[db1]
db-path=/path/to/restore/to

[global]
backup-host=backup
repo-path=/path/to/repo
-----------------

Then, ON db1, run the command:

pgbackrest --stanza=db1 restore

In this scenario, pgbackrest will connect over SSH to 'backup' from 'db1' and will pull the latest backup and restore it into the location specified for 'db-path' in /etc/pgbackrest.conf on 'db1' (in this example: '/path/to/restore/to')

Thanks!
