### ISSUE TITLE
pgbackrest restore a specific backup

### ISSUE THREAD

**Issue by petercelentano** [pgbackrest/pgbackrest#382]
I've searched through the documentation, and I cannot find any options to restore a specific backup using pgbackrest.  I can restore the "latest" backup, but what if I need to restore an older backup?  I'm sure this can be accomplished via PITR, but I would prefer to restore an entire full or differential backup by name/tag (it's simpler for periodic testing of backups).  

If this is not already a feature, I would like to submit this feature request.

**Comment by sfrost** [comment]
The option you're looking for is '--set'

http://www.pgbackrest.org/command.html#command-restore/category-command/option-set

Thanks!

**Comment by petercelentano** [comment]
Great thanks!
