### ISSUE TITLE
ERROR [059]: : statement timed out after

### ISSUE THREAD

**Issue by internetuser2008** [pgbackrest/pgbackrest#388]
I have environment where there is a heavy writes DB. The diff or incr backups will fail with statement timeout. How large should I increase the db-timeout to have successful backups?

I have increased the timeout from 180 to 300 and still fails.
db-timeout=300
protocol-timeout=400

Postgersql.conf
# - Checkpoints -
checkpoint_timeout = 5min               # range 30s-1h
checkpoint_completion_target = 0.5      # checkpoint target duration, 0.0 - 1.0
checkpoint_warning = 30s                # 0 disables

Here is the exact error from log.
INFO: incr backup size = 286.3GB
INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
ERROR: [059]: statement timed out after 300.042 second(s):
                                        select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, labelfile, case when length(trim(both '\t\n ' from spcmapfile)) = 0 then null else spcmapfile end as spcmapfile from pg_stop_backup(false)
 ERROR: [059]: statement timed out after 300.042 second(s):
                                        select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, labelfile, case when length(trim(both '\t\n ' from spcmapfile)) = 0 then null else spcmapfile end as spcmapfile from pg_stop_backup(false)
INFO: backup command end: aborted with exception [059]

**Comment by dwsteele** [comment]
Well, the default is 1800 - I should think that would be more appropriate.  It looks like your db has a backlog archiving WAL and that's why pg_stop_backup() times out.  You can increase the timeout, but you should also consider using async archiving (http://www.pgbackrest.org/user-guide.html#backup-host/async-archiving) which is quite a bit faster.

**Comment by internetuser2008** [comment]
Thanks, I'll look into async. After increasing the timeout has been working fine.
