### ISSUE TITLE
pg9.5.0 Can not be backed up

### ISSUE THREAD

**Issue by liuqian1990** [pgbackrest/pgbackrest#393]
vim lib/pgBackRest/Db.pm 
Need to be modified 201510051 => PG_VERSION_95 change to  201512101 => PG_VERSION_95

**Comment by sfrost** [comment]
Hi there!

That number is specifically the catalog version and PG 9.5's catversion has been 201510051 for every released version of 9.5, and amusingly, I was actually the one who ended up making the last catversion bump for 9.5 and so I was the one who set that number for 9.5.

I'm very curious where you're getting the 201512101 number from, as the git history says we went from 201510051 to 201510052 (for the master branch) to 201510161, then 201511071, then 201601041.  There was never a 201512101 that I can see.

Where did you get the version of PostgreSQL that you're trying to use pgbackrest with..?

Thanks!

Stephen

**Comment by liuqian1990** [comment]
Postgres-XL 9.5.5

**Comment by dwsteele** [comment]
We don't currently test on Postgres-XL so can't guarantee that pgBackRest will work correctly with it.  If you decided to go forward you should definitely test _very_ carefully.

**Comment by liuqian1990** [comment]
Thank you
