### ISSUE TITLE
The port is not the default value of 5432

### ISSUE THREAD

**Issue by liuqian1990** [pgbackrest/pgbackrest#395]
lib/pgBackRest/Config/Config.pm 
use constant OPTION_DEFAULT_DB_PORT                                 => 5432 
change to
 use constant OPTION_DEFAULT_DB_PORT                                 => 5433

He will be based "select (regexp_matches(split_part(version(), ' ', 2), '^[0-9]+\.[0-9]+'))[1], setting from pg_settings where name = 'data_directory'" on the search data directory

**Comment by dwsteele** [comment]
`5432` is the proper PostgreSQL default.  You can modify it with the `db-port` option.
