### ISSUE TITLE
Why not support it archive_mode=always

### ISSUE THREAD

**Issue by liuqian1990** [pgbackrest/pgbackrest#396]
if ($strArchiveMode eq 'always')
        {
            confess &log(ERROR, "archive_mode=always not supported", ERROR_FEATURE_NOT_SUPPORTED);
        }

**Comment by dwsteele** [comment]
This requires us to have have two processes writing into the WAL archive which right now may not work correctly in all circumstances and may throw spurious errors even for safe configurations.  Until we have limits and tests we thought it best to disallow the feature.
