### ISSUE TITLE
remote server backup configuration in pgbackrest

### ISSUE THREAD

**Issue by dkumarr2** [pgbackrest/pgbackrest#400]
ERROR [042]: : process 'itsusraorclic02 remote' terminated unexpectedly: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

I got this error when I performed remote server backup. Anyone please guide me how to take remote server backup with the configuration steps?

**Comment by dwsteele** [comment]
You need to setup ssh keys so that `postgres@db-master` can logon to `backrest@backup` and vice versa without requiring a password.  You can use `backup-user` to change the user name if you don't use `backrest`.

This isn't in the docs - I guess it never came up before, but we'll add it.

**Comment by dkumarr2** [comment]
how to setup the sshkey for postgres user? I have generated the ssh key for postgres user but unable to login into the server. Permission denied shows. Also I need to generate backrest user also? . Please provide me the exact steps to be followed

**Comment by dwsteele** [comment]
We'll be adding instructions for this to the documentation, but for the time being you can take a look at this tutorial: https://www.tecmint.com/ssh-passwordless-login-using-ssh-keygen-in-5-easy-steps/

I would recommend creating and `backrest` user if you are running a dedicated backup server but it's not required.

**Comment by dkumarr2** [comment]
I'm facing difficult in connecting with remote server. can you please tell me when you will be adding the steps for taking remote backup?

**Comment by cmwshang** [comment]
Could you be more specific? What error are you getting? When is it happening? Are you able to ssh with the user you set up, without using pgBackRest (in other words, have you tested your ssh setup manually)?

**Comment by dkumarr2** [comment]
I have checked the ssh setup for backrest user by creating it manually and
break the keygen. But I cant connect with that user to another server where
I broke the password for backrest user. It still shows
*[postgres@itsusraorclic01 ~]$ pgbackrest --stanza=demo backup*
*WARN: option retention-full is not set, the repository may run out of
space*
*HINT: to retain full backups indefinitely (without warning), set option
'retention-full' to the maximum.*
*ERROR [042]: : process 'itsusraorclic02 remote' terminated unexpectedly:
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).*

**Comment by dkumarr2** [comment]
Hi ,

Can I get the steps for doing remote server backup in pgbackrest. I'm not getting a clear idea on how to configure the pgbackrest config file for taking remote level backup. Anyone please respond me.

Thanks

**Comment by arogozin** [comment]
Did you add public key to authorized_keys for that user?

**Comment by dwsteele** [comment]
@dkumarr2 I have added a section that describes how to setup trusted SSH:

http://www.pgbackrest.org/user-guide.html#backup-host/setup-ssh
