### ISSUE TITLE
Invalid block header - Unable to deflate data files when doing backups

### ISSUE THREAD

**Issue by Underhunden** [pgbackrest/pgbackrest#404]
We are running backups with 24 concurrent processes and from time to time we get this error:
log:ERROR [042]: : raised on 'local-19' host: invalid block header '{"out":"unable to deflate '/var/lib/pgsql/9.6/data/base/16400/41573.67': stream error","err":42}'

Half the time we get the same error with files in pg_log directory and since these files are just a tiny fraction of the database size, it seems to be related to the fact that they are appended to all the time.

I've tried to track it down and it may be because of a network error but not completely sure.
If we run the backup again, it will run without problem.

Would it make sense to mitigate network problems with a retry of some sort?

**Comment by dwsteele** [comment]
This appears to be the same issue as #403, see that ticket for more details.

What version of pgBackRest are you running?  Did you upgrade from a previous version where things were working? If so, what version what that?

**Comment by arogozin** [comment]
1.22 same problem here.

**Comment by dwsteele** [comment]
I would recommend reverting to 1.18 until we resolve this issue.  Unless you are using S3 for your backups there should be no loss in functionality.

BTW, what OS/Version are you on?  I'm trying to determine if this is a zlib issue - or at least a version compatibility issue.

**Comment by arogozin** [comment]
`CentOS Linux release 7.2.1511 (Core) with zlib-1.2.7-15.el7.x86_64`

**Comment by Underhunden** [comment]
pgBackRest 1.22 here

CentOS Linux release 7.3.1611 (Core) with zlib-1.2.7-17.el7.x86_64

**Comment by dwsteele** [comment]
@Underhunden  @arogozin OK, looks like I have found a fix for this.  The compression loop was continuing to read even after a zero read flushed the compression buffer.  If there *was* more to read then the compression state was bad and a stream error was thrown on deflate.

How would you like your names to appear in the release notes?

**Comment by arogozin** [comment]
@dwsteele Aleksandr Rogozin

**Comment by Underhunden** [comment]
@dwsteele That sounds perfect! Thank you for looking into it.
Jesper St John

**Comment by dwsteele** [comment]
Fixed at 206415d4c75.
