### ISSUE TITLE
archive error

### ISSUE THREAD

**Issue by tvernick** [pgbackrest/pgbackrest#411]
Hi, our WAL files wont seem to write and seeing this error in the postgres log. postgres user has permission to write to the directory. Any other details that might be useful?

2017-09-09 17:08:38.569 GMT,,,3365,,59b41496.d25,534,,2017-09-09 16:19:34 GMT,,0,LOG,00000,"archive command failed with exit code 55","The failed archive command was: pgbackrest --stanza=data archive-push pg_xlog/0000000300010E1900000028",,,,,,,,""

**Comment by dwsteele** [comment]
It's hard to say for sure since you haven't included any output from backrest, but I would guess your `repo-path` is incorrect, `backup-host` is missing, or something is wrong with the repo.  Error 55 is file missing, and in this context that almost certainly means `archive.info`.

**Comment by tvernick** [comment]
This might have been a bad file somewhere. The archive.info was there but it was not finding it. The repo was recreated and it seems to work now.

**Comment by dwsteele** [comment]
Recreated?  Did you start from scratch or do a `stanza-create --force`?
