### ISSUE TITLE
Restore backup to alternate location

### ISSUE THREAD

**Issue by kkartaltepe** [pgbackrest/pgbackrest#412]
This is something of a twist on what appear to be two different questions already in posed #386 and #366.

I was recently trying to restore a backup into an alternate location in order to practice the restoration process and confirm our backups are indeed working as expected. However this process is not documented anywhere I can find or even hinted at being possible. All documentation centers on working in and on the live database the backup was sourced from. 

Following hints gleaned off the previous posts I was able to accomplish my goals with the commands outlined below for any future inquirers.
```
cp /pgbackrest/.../backup/.../pg_data /target
gunzip -r /target
# since I hadnt taken the backup with `archive-copy=true`
# get the wal names out of `backup_label` and restoring with
pgbackrest --db-path=/target 0000000 /target/pg_xlog/000000 # repeat
# Modify postgresql.conf if required
pg_ctl -D /target start
```

While not awfully difficult for a small database, it seems this is precisely what restore already does, except the target location cannot be changed. The manual process also prevents usage of any of the niceties pgbackrest provides. Could this have been accomplished by use of `db-path` with the `pgbackrest restore` command? Or will this potentially affect the existing database? (possibly due to links or tablespaces?)

Something like this would perfectly handle a db export as you could construct a database at precisely the place you need, stop it, compress it and ship it (presumably this would not restore links unless explicitly requested, since its likely you would be restoring this backup into a new machine or if on the same machine dont want to overlay the existing database). Potentially it could be an alternate command like `export`, if only because it would ignore links by default or such a flag could be added to `restore` in addition to the alternate location flag.

**Comment by dwsteele** [comment]
The restore location can be changed using the `db-path` option on the cmd-line when doing a restore (or in the config file if the path is always different).  A "compact" restore can be created by using the `tablespace-map-all` option.  Currently the only way to get the WAL is to do what you did or use `archive-copy`.  A restore type could be added for this functionality.

I can see that `db-path` is not discussed with regard to restores in the user guide or configuration reference and `tablespace-map-all` is only discussed in the configuration reference.  This could definitely stand to be improved.
