### ISSUE TITLE
exclude pg_log from backups

### ISSUE THREAD

**Issue by javierwilson** [pgbackrest/pgbackrest#413]
Is there a way to exclude pg_log from backups, I don't need to backup log files.
I wonder if I should add a "next if..." to lib/pgBackRest/Manifest.pm or if there's already a way to configure not backing up log files.

**Comment by dwsteele** [comment]
The best way to exclude logs from the backups is to move them out of $PGDATA using the `log_directory` setting in `postgresql.conf`.

I would add it to the standard list of exclusions but some users want to backup their logs.  I'm not sure that it's worth adding an option.
