### ISSUE TITLE
in PG 10,do we have to manually resume wal replay to start PG for operations?

### ISSUE THREAD

**Issue by blabblab** [pgbackrest/pgbackrest#415]
Hello ,

I am trying pgbackrest 1.23 with PG 10 and getting below in my database log after performing PITR.
LOG:  recovery stopping before commit of transaction 589, time 2017-09-14 00:24:14.462472+10
LOG:  recovery has paused
HINT:  Execute pg_wal_replay_resume() to continue.  

In order to use database I need to manually execute 'pg_wal_replay_resume()'  command but this is not the case with PG 9.6 (I tried with same settings).Below lines are from 9.6 logs(which are same as shown in pgbackrest 1.23 doc)

 LOG:  database system was interrupted; last known up at 2017-09-14 02:42:56 AEST
 LOG:  starting point-in-time recovery to 2017-09-14 02:43:01+10
 LOG:  restored log file "00000001000000000000000A" from archive
 LOG:  redo starts at 0/A000028
 LOG:  consistent recovery state reached at 0/A0000F8
 LOG:  restored log file "00000001000000000000000B" from archive
 LOG:  recovery stopping before commit of transaction 1761, time 2017-09-14 02:43:21.067704+10
 LOG:  redo done at 0/B003220
 LOG:  selected new timeline ID: 2
 LOG:  archive recovery complete
 LOG:  MultiXact member wraparound protections are now enabled
 LOG:  database system is ready to accept connections
 LOG:  autovacuum launcher started

Can anybody tell me is there something to do with version 1.23 as I believe there is no such difference in PITR as far as PG is concerned.

Thanks
Rajni

**Comment by dwsteele** [comment]
`hot_standby=on` by default in PG10.  If you want the same behavior as 9.6 you'd need to set `hot-standby=off`.  Or you could use `target-action=promote` on the backrest cmd-line during restore.

**Comment by blabblab** [comment]
Thanks for the reply. I will try it out.

Just a suggestion ,since we are targeting PG 10 in release 1.23 ,is it worth mentioning this point in pgbackrest document as well ??? My be as a note only.

Thanks

**Comment by dwsteele** [comment]
This suggestion has been added to the documentation backlog.  Thanks!
