### ISSUE TITLE
Bulk Fetch of WAL Files on Restore

### ISSUE THREAD

**Issue by procuratorelephanti** [pgbackrest/pgbackrest#416]
When performing restore operations on our large (10 TB), busy PostgreSQL 9.6 databases, there are a considerable number of WAL files generated during the backup. Upon restore, the sequential fetching of these files from our separate backup servers takes considerable time, much more than the restoration of the database files themselves actually.

Could we have a facility to fetch N WAL files at once, where N is a new configurable parameter? It could default to "1" to reproduce the current behavior, but be increased up to 256, to fetch a full set of files in a single operation. Alternatively, use "process-max" as a good estimate of the maximum number of files the recovering server can handle at once, and bound N on the range [1 , process-max].

**Comment by dwsteele** [comment]
Yeah, this one has been on the radar for a while.  See #16.

The good news is that this feature is on the roadmap for this Fall.  I don't have an exact date, but you can expect it by the end of the year.

Meanwhile, if you are pulling WAL from a remote server (i.e. `backup-host`=something) then you can use SSH control master to speed this process.  Not perfect, but it helps a lot.

**Comment by dwsteele** [comment]
This feature was released in v2.02.  Give it a try and let us know what you think.
