### ISSUE TITLE
Use a database user with a different name to the operating system user

### ISSUE THREAD

**Issue by jamessewell** [pgbackrest/pgbackrest#417]
Hi,

We use EDB PostgreSQL at a customer site, and we end up with the following:

postgresql OS user: `enterprisedb`
postgresql database superuser: `postgres`

Ideally I'd like to run pgbackrest as the `enterprisedb` OS user, connecting to a specific  `pgbackrest` database user.

I can't seem to work out a way to make this happen. For normal connections I use `pg_ident` mappings from `enterprisedb` -> `postgres` , making use of this would be fine as well.

**Comment by dwsteele** [comment]
Hmm - I'm not really sure.  You are running pgBackRest as `enterprisedb`?  There's nothing special about how we connect to PostgreSQL so it seems like that should work.  

What error are you getting?

**Comment by jamessewell** [comment]
Hi,

The issue is I need to run from the enterprisedb OS user and use the
Postgres database user.

Ideally you'd just respect $PGUSER I suppose.

Cheers,
James Sewell

**Comment by dwsteele** [comment]
We've had this in the backlog for a long time, but it's never come up in the real world so it never got done.  We'd have to test that peer auth and pg_ident play well together but it's doable.

Meanwhile, depending on your version of Postgres (it would need to be >= 9.5), you should be able to create an `enterprisedb` user and grant execute on '`pg_start_backup`, `pg_stop_backup`, etc.

**Comment by jamessewell** [comment]
Yeah we have a workaround - it's just annoying to have to create a user
which doesn't semantically map to the role use.

Ideally I'd like to use the enterprisedb OS user and the backrest or backup
role.

Thanks for the help!

**Comment by dwsteele** [comment]
This has been added to the v2 feature backlog: https://github.com/pgbackrest/pgbackrest/projects/5#card-4892687

I'd like to allow $PGUSER to be used when no user is specified in pgbackrest.conf.  Unfortunately this could cause some awkward regressions in the 1.x line.  1.25 is our last planned 1.x release so we'll be working on v2 soon.

**Comment by jamessewell** [comment]
Sounds great David.

Is there a place to request features for v2 - or are issues the best place
to get things onto the roadmap?

Cheers,

**Comment by dwsteele** [comment]
Issues are the best way to request features.  We are only planning one more big feature for v1 (encryption) so anything else will be considered for v2 by default.

**Comment by dwsteele** [comment]
This feature was committed at dc1e7ca22dbdae2 for pgBackRest 2.21.
