### ISSUE TITLE
Clarify archive-timeout is different than archive_timout

### ISSUE THREAD

**Issue by keithf4** [pgbackrest/pgbackrest#423]
Going through the User Guide, I was initially confused at the mention of the `archive-timeout` option and thought it was referring to the postgresql.conf option: `archive_timeout`. 

Some clarity between the two in the documentation would be helpful. Suggest that the first mention of it in the User Guide be explicitly clear with a sentence or two explaining the difference. Would also suggest clarifying how the postgresql.conf option is useful to set to ensure long periods of inactivity don't cause missing data due to no WAL file being sent to the backup. Then later uses of it refer to it as `pgbackrest's archive-timeout` option.

**Comment by dwsteele** [comment]
Agreed.  We'll update this for the next release.

**Comment by dwsteele** [comment]
Committed at 2be93036f1c8de734 with minor edits.
