### ISSUE TITLE
Authentication restrict in pg_hba.conf file for pgbackrest

### ISSUE THREAD

**Issue by dkumarr2** [pgbackrest/pgbackrest#426]
Hi,

I can find that pgbackrest allows trust authentication mode to run the operations. Is there any way to restrict the user with md5 authentication? Please reply back on this issue. 

Thanks

Dinesh Kumar

**Comment by dwsteele** [comment]
pgBackRest is intended to run as the database superuser with `peer` authentication in `pg_hba.conf`.  There is no way to specify a password for `trust` authentication and it should not be used.
