### ISSUE TITLE
Backup failing in async mode

### ISSUE THREAD

**Issue by mjramtech** [pgbackrest/pgbackrest#427]
The backup operation appears to work in synchronous mode, but in async I'm just getting a varying number of defunct child processes and it times out:

E.g:

From server:
```
pgbackrest --stanza=cie_spt_4096 --type=diff --log-level-console=info backup
```

On client:

Sync:
```
 7997 ?        Ss     0:00  \_ postgres: archiver process   archiving 000000010000000200000077.00000028.backup
 9110 ?        S      0:00  |   \_ sh -c pgbackrest --stanza=cie_spt_$(psql rem_sys_conf -t -c "select local_port from ssh_tunnels where remote_port = 2022 order by id asc limit 1" | tr -d "[:space:]") archive-push pg_xlog/00000001000000
 9122 ?        S      0:00  |       \_ /usr/bin/perl /usr/bin/pgbackrest --stanza=cie_spt_4096 archive-push pg_xlog/000000010000000200000077.00000028.backup
 9128 ?        S      0:00  |           \_ sh -c ssh -o LogLevel=error -o Compression=no -o PasswordAuthentication=no -p 2022 backrest@192.168.0.203 '/usr/bin/pgbackrest --buffer-size=4194304 --command=archive-push --compress-level=6 --c
 9129 ?        S      0:00  |               \_ ssh -o LogLevel=error -o Compression=no -o PasswordAuthentication=no -p 2022 backrest@192.168.0.203 /usr/bin/pgbackrest --buffer-size=4194304 --command=archive-push --compress-level=6 --comp
```

Async:
```
 7997 ?        Ss     0:00  \_ postgres: archiver process   archiving 000000010000000200000078
10788 ?        S      0:00  |   \_ sh -c pgbackrest --stanza=cie_spt_$(psql rem_sys_conf -t -c "select local_port from ssh_tunnels where remote_port = 2022 order by id asc limit 1" | tr -d "[:space:]") archive-push pg_xlog/00000001000000
10800 ?        S      0:01  |       \_ /usr/bin/perl /usr/bin/pgbackrest --stanza=cie_spt_4096 archive-push pg_xlog/000000010000000200000078
10801 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10802 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10803 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10805 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10806 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10807 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10808 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10809 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10810 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10811 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10812 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10813 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10814 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10815 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10816 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10817 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10818 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10819 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10820 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10821 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10822 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10823 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10824 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
10825 ?        Zs     0:00  |           \_ [pgbackrest] <defunct>
 7998 ?        Ss     0:00  \_ postgres: stats collector process
```

Config (commented lines in/out for above test):
```
[global]
backup-host=192.168.0.203
backup-user=backrest
backup-ssh-port=2022
#archive-async=y
#spool-path=/var/spool/pgbackrest
log-level-file=detail

#[global:archive-push]
#process-max=2

[cie_spt_4096]
db-path=/media/usb-hdd/database/postgresql/9.5/main
```

```
$ ls -l /var/spool
total 16
drwxr-xr-x 3 root        root        4096 Mar 18  2016 cron
drwxr-x--- 5 Debian-exim Debian-exim 4096 May 26 10:51 exim4
lrwxrwxrwx 1 root        root           7 Mar 18  2016 mail -> ../mail
drwxr-xr-x 2 postgres    postgres    4096 Sep 29 08:33 pgbackrest
drwx------ 2 root        root        4096 Jan 23  2016 rsyslog
```

The above is client side. Backup server side I have (I think it was timing out eventually, but the only scrollback I currently have is where I'd grown impatient and CTRL-C'd it):
```
2017-10-13 16:39:17.142 P00   INFO: execute exclusive pg_start_backup() with label "pgBackRest backup started at 2017-10-13 16:39:14": backup begins after the next regular checkpoint completes
2017-10-13 16:39:17.849 P00   INFO: backup start archive = 000000010000000200000079, lsn = 2/79000028
2017-10-13 16:39:25.326 P01   INFO: backup file 127.0.0.1:/media/usb-hdd/database/postgresql/9.5/main/base/124274/2619 (200KB, 92%) checksum 2487d550742c03bedf1826da780e303fba6e748d
2017-10-13 16:39:25.344 P01   INFO: backup file 127.0.0.1:/media/usb-hdd/database/postgresql/9.5/main/global/pg_control (8KB, 96%) checksum e2d0c8b418a5f0764985925d6d2a560a31e48bdb
2017-10-13 16:39:25.360 P01   INFO: backup file 127.0.0.1:/media/usb-hdd/database/postgresql/9.5/main/base/124274/144397 (8KB, 99%) checksum b1e20066024f565fa5f5e5e69d2cc9dbdad49567
2017-10-13 16:39:25.402 P01   INFO: backup file 127.0.0.1:/media/usb-hdd/database/postgresql/9.5/main/backup_label (238B, 100%) checksum 6e247898eb84d4fec235159003eee227f85d262e
2017-10-13 16:39:25.484 P00   INFO: diff backup size = 216.2KB
2017-10-13 16:39:25.484 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
```

Version on both server and client is pgBackRest 1.24. This is as obtained from Debian Buster, which I know is still in test, but I need the failry recently added non-default ssh port option for both amd64 and armhf and they don't yet both appear to be available anywhere else.

I'm happy enough using synchronous mode, just thought this might be of interest. Thanks.

**Comment by dwsteele** [comment]
Well, looks like sync mode is your best option until we figure this out.

Was there anything interesting in the postgresql log or the /var/log/pgbackrest/<stanza>-archive-async log on the db server?

**Comment by mjramtech** [comment]
No, sorry. The postgres log appears to roll daily, which is something I need to change actually. I think I did look in there at the time though and don't remember seeing anything interesting.

On the DB host /var/log/pgbackrest/ is empty. On the backup server the only pgbackrest logs are cie_spt_4096-backup.log and cie_spt_4096-stanza-create.log. There's no async log ... -backup.log basically just contains what I posted from the console before. If there's anything specific you're looking for let me know, but I stopped and started, changed config, restarted postgres many times so unfortunately I couldn't really say which bit of the log was in which context, sorry. I could try and recreate with different logging options if that helps?

**Comment by dwsteele** [comment]
You may not be getting an async log because something bad is happening because it gets a chance to WARN or ERROR.  Maybe upping the `log-level-file` to `debug` and trying to turn on async again would yield some valuable info.

**Comment by mjramtech** [comment]
Still not an async log, but:

[cie_spt_4096-backup.log.gz](https://github.com/pgbackrest/pgbackrest/files/1390777/cie_spt_4096-backup.log.gz)

It hung for about 5 minutes, defunct processes on the remote end as before, then I killed it.

**Comment by dwsteele** [comment]
The backup failed because archiving was not working.  I would check the permissions on your `/var/log/pgbackrest` directory and make sure the user you are running pgbackrest as on the db server (usually `postgres`) has permissions.  Probably wouldn't hurt to have a look at `/var/spool/pgbackrest` and `/tmp/pgbackrest` as well.  If pgbackrest gets run as root it can create files that later cause problems.

**Comment by mjramtech** [comment]
Ah, changing permissions on the log directly on the DB host has fixed it. Does it not log anything locally in sync mode then? Anyway, all good now, thanks.

**Comment by dwsteele** [comment]
In sync mode it only logs to the Postgres log.  We have had an open issue for a while to let the async process proceed even if the log cannot be opened, but just have not quite gotten around to it.

Glad you got it working!
