### ISSUE TITLE
unable to acquire pgBackRest advisory lock

### ISSUE THREAD

**Issue by dkumarr2** [pgbackrest/pgbackrest#430]
WARN: no prior backup exists, incr backup has been changed to full
ERROR [050]: : unable to acquire pgBackRest advisory lock
HINT: is another pgBackRest backup already running on this cluster?
2017-10-18 06:54:27.197 P00   INFO: backup command end: aborted with exception [050]

Can you please give a solution to recover it?

**Comment by dwsteele** [comment]
Are you sure you didn't have another backup running?

**Comment by M1hacka** [comment]
I've also catched this error after stopping pgbackrest backup with Ctrl+C. The problem was solved with restarting postgres service (cleaning busy locks), if I'm not mistaken.

**Comment by dwsteele** [comment]
Could be that the PostgreSQL connection did not get properly closed.  You could just terminate the pgBackRest session rather than restart the entire cluster.  The app name is set so it should be easy to find.

**Comment by M1hacka** [comment]
There was no pgBackRest session or `sudo -u postgres pgbackrest stop --force` was enable to find it.

**Comment by dwsteele** [comment]
I meant a session on PostgreSQL.  pgBackRest maintains a connection to Postgres for the entire backup.  It looks like Postgres was still holding this session open even though the initiating process was killed.
