### ISSUE TITLE
Feature request: Replica fail causes backup fail

### ISSUE THREAD

**Issue by M1hacka** [pgbackrest/pgbackrest#431]
Hey
As a result of [this issue](https://github.com/pgbackrest/pgbackrest/issues/429), another one occured. We have cron-planned backup, which is scheduled every night. It is done with `backup-standby=y` option. But once replica has failed and retention grew up, backup also failed by timeout, waiting for standby catch up with primary. So if standby fails for some reason => backup will not be done too...
What I suggest, is adding parameter, causing backup from primary, if backup from standby failed.

**Comment by dwsteele** [comment]
We've held off on this because most people doing backup from standby really *don't* want it to fail back to the master because of load issues.  We'll discuss and let you know.

**Comment by dwsteele** [comment]
We looked into this and discovered that it gets complicated if the standby is running but not caught up.  

We are winding down development for 1.X but I have added this to the feature board for future consideration: https://github.com/pgbackrest/pgbackrest/projects/2#card-5671076
