### ISSUE TITLE
ERROR [044]: : WAL segment system-id  does not match archive system-id 

### ISSUE THREAD

**Issue by eldrik** [pgbackrest/pgbackrest#432]
Get those messages while trying to get pgbackrest to work on a server with a single postgresql database.

Installed version 1.24 with postgres 9.5 and did the config steps, for configuring postgresql.conf, pgbackrest.conf, creating stanza, checking stanza and postgresql log is displaying those messages

ERROR [044]: : WAL segment system-id 72057595546437761 does not match archive system-id 6479000364798447222

pg_controldata shows - Database system identifier:           6479000364798447222

pgbackrest archive.info shows - db-system-id=6479000364798447222

Did a full postgresql wipe out and after installing the latest version 10, the error is still the same.

Where is those 72057595546437761  coming from?

**Comment by dwsteele** [comment]
I just initialized a cluster and got a system id of `6479085164637032549` so `72057595546437761` seems way out of line (it's current timestamp + process id with some fiddling).

Anything interesting about the system?  32-bit, big-endian, etc?

**Comment by eldrik** [comment]
A debian vm on x86 hardware nothing to special I guess.

Linux fhem 3.16.0-4-686-pae #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) i686

Any other things I could check?

**Comment by liuqian1990** [comment]
Whether there are multiple instances of PG

**Comment by eldrik** [comment]
from my unterstanding there is one instance running on port 5432 with one cluster and two dbs (postgres and my application db)

**Comment by dwsteele** [comment]
Make sure `db-path` matches the db whose `port` you have specified.  If you cross those then you could be pulling the wrong WAL.

**Comment by eldrik** [comment]
$ pg_lsclusters
Ver Cluster Port Status Owner    Data directory                                         Log file
10  main    5432 online postgres /media/nfsshare/rasp_images/fhem_db/postgresql/10/main /var/log/postgresql/postgresql-10-main.log

pgbackrest.conf
[main]
db-path=/media/nfsshare/rasp_images/fhem_db/postgresql/10/main
db-port=5432
db-user=postgres
[global]
repo-path=/media/nfsshare/rasp_images/fhem_db/pgbackrest
retention-full=1

Should be ok or do I miss something? :(

Regards

**Comment by dwsteele** [comment]
Did you install from packages or install manually?

**Comment by eldrik** [comment]
While the server was running on wheezy I used postgresql 9.5 on debian package base and after updating to stretch the version 10 I am using right now is also package based.

**Comment by dwsteele** [comment]
Sorry, I meant was pgBackRest installed from packages.  Just grasping at straws here, really.

The issue is that pgBackRest is getting a WAL segment via archive-push that does not match the stanza it is being pushed to.  This is usually because of incorrect stanza or db-path.  You seem to have all that right so I can't tell where this is coming from.

**Comment by eldrik** [comment]
I installed it manually following the steps documented under:
http://www.pgbackrest.org/user-guide.html#installation

If I find the time I will try to duplicate my debian vm and test some different combinations.

Any other system items that maybe influence pgbackrest?

**Comment by cmwshang** [comment]
You mentioned you upgraded from PG 9.5 to 10 - did you also perform a pgbackrest stanza-upgrade?

Cynthia Shang
www.crunchydata.com

**Comment by eldrik** [comment]
yeah after upgrading I also did a stanza upgrade, but the posted error message is there right from the beginning.

**Comment by dwsteele** [comment]
Set `log-level-console=debug` in `pgbackrest.conf` and send the output.  The logging will show up in the postgres log just as the original error did.

**Comment by dwsteele** [comment]
Closed due to inactivity.  Feel free to respond with details if you are still seeing the issue.

**Comment by dwsteele** [comment]
This appears to be the same issue as #445.  It slipped right by me that this is a 32-bit system.   We'll work on a fix for the next release.
