### ISSUE TITLE
Backup and restore from EC2 to RDS.

### ISSUE THREAD

**Issue by jyothsna01** [pgbackrest/pgbackrest#436]
Can we take backup of the database on EC2 and restore it to RDS using PGBACKREST?

**Comment by dwsteele** [comment]
Unfortunately, no.  RDS is not compatible with file-level backups tools such as pgBackRest, pg_basebackup, etc.  This is a limitation of the RDS service.

**Comment by jyothsna01** [comment]
Thanks for the quick response David.
