### ISSUE TITLE
pgbackrest's feature

### ISSUE THREAD

**Issue by Umpat** [pgbackrest/pgbackrest#438]
I have few questions about pgbackrest, which are as (I've tried to look in doc but unable to find it - may be I overlooked)

1) Will I able to restore given backup to another server for verification purpose or will it restore to same original Database server?
2) Will I able to restore manually (without able to use 'pgbackrest' utility) by using backups created by pgbackrest?
3) How do I keep WAL archive longer lets say 15 days while keep full backup for 7 days (based on doc WAL segment expire based on retention-full)?

Please provide pointers to above questions.

**Comment by dwsteele** [comment]
Hi!

> Will I able to restore given backup to another server for verification purpose or will it restore to same original Database server?

You can restore to any server you want. There is an example of this here:
http://pgbackrest.org/user-guide.html#replication/hot-standby

> Will I able to restore manually (without able to use 'pgbackrest' utility) by using backups created by pgbackrest?

pgBackrest backups are stored in Postgres cluster format so you can manually restore if needed.  If you are using differential and incremental backups you'll want to enable the `hardlink` option so each backup directory contains all the files.  **Note**: this will only work on Posix-compliant file systems.  On S3 or CIFS only the full backups will contain all the files.

> How do I keep WAL archive longer lets say 15 days while keep full backup for 7 days (based on doc WAL segment expire based on retention-full)?

There is currently no way to keep WAL archive earlier than the last backup.  This is not likely to be useful if your backup retention is reasonable, i.e. >= two weeks.

**Comment by Umpat** [comment]
David,

Thanks for quick reply. 
Last question/clarification about restoring backup to diff. server, in order to restore a given backup to another server, does it have to set-up/configured as hot-standby or can we use other method?
e.g. let's say we want to refresh DEV database from PRODUCTION backup as of time 't' (given that we backups available), can we do that ? Please point me to example if you have.

question: "Will I able to restore given backup to another server for verification purpose or will it restore to same original Database server?"
Your answer: "You can restore to any server you want. There is an example of this here:
http://pgbackrest.org/user-guide.html#replication/hot-standby"

**Comment by uspen** [comment]
Use --db-path

**Comment by dwsteele** [comment]
Restore options (and postgres options) will determine what kind of server you get when you restore (i.e. new master, host standby, warm standby, etc).  See http://pgbackrest.org/command.html#command-restore/category-command for the pgBackRest restore options.

**Comment by Umpat** [comment]
David,

Thanks a lot again for quick reply.
