### ISSUE TITLE
pgbackrest in failover and crash recovery scenarios

### ISSUE THREAD

**Issue by jhammerman79** [pgbackrest/pgbackrest#440]
Hi pgbackrest devs,

I'm looking for some clarity regarding pgbackrest's role in a crash & recovery scenario. I've hunted through the documentation for answers to these questions and contact methods, but I couldn't find anything. Hopefully it is ok to seek some information via posting here. We are using archive-async method with archive_command set to archive-push in postgresql.conf.

1. If we promote a machine that is misconfigured in some way, PG daemon will accumulate the archive WAL's for some retention period, and once pgbackrest configuration is fixed, they will flush. Is that correct?

2. If we have archived WAL's on disk, can we manually push them to the repository using archive-push command as postgres user? In order to include these files in our recovery scenario, do we need to incorporate them into the backup using archive-copy?

3. In an automated failover scenario, will the promoted node be able to simply begin writing to the same S3 bucket repository? We had issues with system-id mismatch errors in our live fire exercises - should pgbackrest be run with the stanza-upgrade option after failover to indicate to the program that the system-id is in fact correct? Do we need to ensure a full backup runs that night to have a recoverable backup? In testing with a dramatically reduced write load, we were unable to reproduce this issue - is a quiesced database a precondition for seamless backup generation post-failover?

4. This page https://wiki.postgresql.org/wiki/Binary_Replication_Tools suggests that automated failover is unsupported for pgbackrest; how can we incorporate the tool into an HA strategy? Or czn we not do that?

5. When attempting a full restore to a newly created node, the db will not start do to 'invlaid checkpoint record', and archive push fails due to system-id mismatch. I've reviewed the restore documentation, but I can't find guidance - am I missing something?

Thanks in advance for any assistance that you guys can provide! My apologies if this is not hte correct forum to seek out this sort of guidance, if there is an alternative channel please point me that way and I will seek enlightenment there.

**Comment by dwsteele** [comment]
> If we promote a machine that is misconfigured in some way, PG daemon will accumulate the archive WAL's for some retention period, and once pgbackrest configuration is fixed, they will flush. Is that correct?

Yes.  Be careful, though, because if the disk fills the Postgres daemon will panic.

> If we have archived WAL's on disk, can we manually push them to the repository using archive-push command as postgres user? In order to include these files in our recovery scenario, do we need to incorporate them into the backup using archive-copy?

You can certainly call `archive-push` manually.  However, you cannot modify an existing backup by copying WAL to it.  `archive-get` will pull the WAL from the archive during recovery.  `archive-copy` is only for scenarios where normal recovery will not be performed.

> In an automated failover scenario, will the promoted node be able to simply begin writing to the same S3 bucket repository? 

Yes.

> We had issues with system-id mismatch errors in our live fire exercises - should pgbackrest be run with the stanza-upgrade option after failover to indicate to the program that the system-id is in fact correct? 

No need to run stanza-upgrade.  If you are getting system-id mismatches then you have likely specified the wrong stanza.  They stanze name should be the same for all related clusters.

> Do we need to ensure a full backup runs that night to have a recoverable backup? In testing with a dramatically reduced write load, we were unable to reproduce this issue - is a quiesced database a precondition for seamless backup generation post-failover?

You can use an older backup, but you have to be sure to specify which timeline you want to follow.  The data never needs to be idle to take a backup.

> This page https://wiki.postgresql.org/wiki/Binary_Replication_Tools suggests that automated failover is unsupported for pgbackrest; how can we incorporate the tool into an HA strategy? Or czn we not do that?

You can use pgBackRest as the restore part of any HA strategy.  It does not initiate HA, though.

> When attempting a full restore to a newly created node, the db will not start do to 'invlaid checkpoint record', and archive push fails due to system-id mismatch. I've reviewed the restore documentation, but I can't find guidance - am I missing something?

Likely a stanza mismatch as above.

**Comment by jhammerman79** [comment]
Good afternoon dwsteele,

Thank you for responding! New nodes were unnecessarily recreating the stanza on provisioning, with the --force flag, which was wrecking the timeline / System Id when restores were attempted. So we are good on almost all my questions from above.

Thanks!
Joe Hammerman

**Comment by dwsteele** [comment]
Ah, yeah, that would definitely cause a problem!  Glad you worked it out.
