### ISSUE TITLE
WAL segment system-id does not match archive system-id

### ISSUE THREAD

**Issue by javierwilson** [pgbackrest/pgbackrest#445]
1. pgBackRest version: 1.25 - 32bit
2. PostgreSQL version: 9.4 - 32bit
3. Operating system/version - if you have more than one server (for example, a database server, a backup host server, one or more standbys), please specify each: Ubuntu 14.03 - 32bit
4. Did you install pgBackRest from source or from a package? apt-get

7. Describe the issue:
I have the same issue as https://github.com/pgbackrest/pgbackrest/issues/432
also running on a 32bit system, the WAL system-id doesn't match the archiive system-id, or so claims pgbackrest.
I did an hexdump of the WAL file and I can see the system-id is correct, only pgbackrest is usin the wrong offset, the issue gets fixed if I set PG_WAL_SYSTEM_ID_OFFSET_GTE_93 = 16, instead of 20.  I wonder is this is something that affects only 32bit systems. See https://github.com/pgbackrest/pgbackrest/blob/master/lib/pgBackRest/Archive/Common.pm#L35

**Comment by javierwilson** [comment]
Quoting https://wiki.postgresql.org/images/a/af/FOSDEM-2015-New-WAL-format.pdf
the XLogRecord in 9.4 and below uses 32 bytes in total (but 28 on 32-bit systems),  4 bytes less, so it makes sense to lower this to 16 if arch is 32bit.  Other messages on postgresql mailing list confirm this.

**Comment by dwsteele** [comment]
Hi Javier,

You are correct about the alignment being different on 32-bit architectures.

We have tests (https://anonscm.debian.org/cgit/pkg-postgresql/pgbackrest.git/tree/debian/tests/suite) which should run on all architectures.  The tests are pretty basic but should have caught this.

Any idea why the tests did not catch this, @disco-stu?

**Comment by disco-stu** [comment]
The only test we run automatically on i386 (and all other architectures) is "make test" of the libc module. However, that test passes [1].

Unfortunately ci.debian.net (which automatically runs the full suite) doesn't run on architectures others than amd64 [2]. I would like to have autopkg-tests on all architectures, but that's future stuff.
 
[1] https://buildd.debian.org/status/fetch.php?pkg=pgbackrest&arch=i386&ver=1.25-1&stamp=1509026334&raw=0
[2] https://ci.debian.net/packages/p/pgbackrest/

**Comment by dwsteele** [comment]
Thank you for the clarification, Adrian!  Let me know if there's anything I can do to move the `autopkg-tests` stuff along.  I'm working on getting the bulk of the test suite running without Docker.  Currently, only the S3 tests won't run that way.

@javierwilson - did everything work once you made the offset change?

**Comment by javierwilson** [comment]
Yes it did... pgbackrest working happily.  I basically did an hexdump of several WAL files to confirm the system-id

**Comment by dwsteele** [comment]
Thanks - I will make that change for 1.26, then.  Can you run:
```
perl -V:ivsize
```
And send me the result?  It should be `ivsize='4'`.

**Comment by javierwilson** [comment]
$ uname -a 
Linux example 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:12 UTC 2014 i686 i686 i686 GNU/Linux

$ perl -V:ivsize
ivsize='8';

*shrug*

**Comment by dwsteele** [comment]
How about:
```
perl -V:ptrsize
```

**Comment by javierwilson** [comment]
$ perl -V:ptrsize
ptrsize='4';

that is actually different from other 64bit servers

**Comment by dwsteele** [comment]
OK - we'll go with that.  This next version is the last in the 1.X line (except for bug fixes).  Version 2.x will require the C library and then I can push all this logic down into C and pull structures straight from the Postgres source.

Thanks for testing those out for me!

**Comment by javierwilson** [comment]
cool, thank *you* for all your work!

**Comment by dwsteele** [comment]
Fixed at 550d4fb9c591a2.
