### ISSUE TITLE
Unable to install pgbackrest 1.26 on Centos 7 (and 6)

### ISSUE THREAD

**Issue by plocharz-9livesdata** [pgbackrest/pgbackrest#449]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 1.26

2. PostgreSQL version: none

3. Operating system/version - if you have more than one server (for example, a database server, a backup host server, one or more standbys), please specify each: Centos 7

4. Did you install pgBackRest from source or from a package?
from https://ftp.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm

5. Please attach the following as applicable:
none applicable

7. Describe the issue:

```
centos-7 ~ # yum install pgbackrest
(...)
--> Processing Dependency: perl(pgBackRest::LibC) for package: pgbackrest-1.26-1.rhel7.noarch
--> Finished Dependency Resolution
Error: Package: pgbackrest-1.26-1.rhel7.noarch (pgdg96)
           Requires: perl(pgBackRest::LibC)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by plocharz-9livesdata** [comment]
This might be strictly yum repo problem, reported it here: https://redmine.postgresql.org/issues/2914

**Comment by dwsteele** [comment]
Yes - I heard from Devrim about it this morning.  The C library is not required by pgBackRest (yet) but apparently the package is expecting it.  It would be best if the package included the C Library, which enables page checksum validation and encryption, but the short-term fix is to remove the dependency.

**Comment by dwsteele** [comment]
Devrim has released new packages that should solve this problem.
