### ISSUE TITLE
How does one test the restoration of a backup without affecting db server?

### ISSUE THREAD

**Issue by pritammobisoft** [pgbackrest/pgbackrest#451]
Hi,

I am trying out pbgackrest. After completing the setup procedure, I realized the current user guide doesn't mention how can one test the restoration of a backup without actually restoring it on the current DB server. 

As a part of DB management, I would like to periodically restore the backups on a test machine to ensure that the backups are actually working. 

Is there a way to achieve this? For now, I am thinking of bringing up a "temp" server identical to the current DB server, and change the db1-host setting in pgbackrest to test the restore. 

Regards,

Pritam.

**Comment by dwsteele** [comment]
You can use the instructions for setting up a standby which is exactly the same thing: http://pgbackrest.org/user-guide.html#replication/hot-standby

**Comment by pritammobisoft** [comment]
Just tried it out. Worked perfectly. The manual is indeed written very well. Thanks.
