### ISSUE TITLE
Unable to restore

### ISSUE THREAD

**Issue by slardiere** [pgbackrest/pgbackrest#452]
with pgBackrest 1.26 on Debian Stretch (up to date) with PostgreSQL 10.1, on the repo host, I'm unable to restore. I've got this message : 

~~~
DEBUG: Protocol::Local::Process->hostConnect: start local process: iHostConfigIdx = 1, iHostIdx = 0, iHostProcessIdx = 0, iProcessId = 1, strHostType = backup
DEBUG: Protocol::Local::Master->new(): iProcessIdx = 1, strCommand = /usr/bin/pgbackrest --command=restore --db1-path=/home/postgres/10/restore/ --host-id=1 --process=1 --repo-path=/home/backrest --stanza=nkaal10 --type=backup local
DEBUG: Protocol::Command::Master->new(): iBufferMax = 4194304, iCompressLevel = 6, iCompressLevelNetwork = 3, iProtocolTimeout = 1830, strCommand = /usr/bin/pgbackrest --command=restore --db1-path=/home/postgres/10/restore/ --host-id=1 --process=1 --repo-path=/home/backrest --stanza=nkaal10 --type=backup local, strId = local-1 process, strName = local
DEBUG: Protocol::Local::Process->hostConnect=>: bResult = true
DEBUG: Protocol::Local::Process->init: init local process: iDirection = 1, iHostIdx = 0, iProcessId = 1, iQueueIdx = 0, iQueueLastIdx = 0
DEBUG: Protocol::Local::Process->init=>: bResult = true
DEBUG: Protocol::Local::Process->process: get job from queue: iHostIdx = 0, iProcessId = 1, strKey = pg_data/base/28493/237820, strQueueIdx = 0
ERROR [042]: : unexpected EOF reading line from local-1 process
ERROR [042]: : local-1 process terminated unexpectedly [000]
WARN: unable to shutdown protocol [042]: local-1 process terminated unexpectedly [000]
DEBUG: Protocol::Command::Master->close=>: iExitStatus = 42
DEBUG: Common::Exit::exitSafe(): iExitCode = [undef], oException = [object], strSignal = [undef]
DEBUG: Protocol::Helper::protocolDestroy(): bComplete = false, iRemoteIdx = [undef], strRemoteType = [undef]
DEBUG: Protocol::Helper::protocolDestroy=>: iExitStatus = 0
DEBUG: Common::Lock::lockRelease(): bFailOnNoLock = false
INFO: restore command end: aborted with exception [042]
DEBUG: Common::Exit::exitSafe=>: iExitCode = 42

~~~

See full log attached. 

PostgreSQL and pgBackRest come from PGDG Debian Packages. 

`/etc/pgbackrest.conf` : 

~~~
[nkaal10]
db-host=nkaal.lardiere.net
db-path=/home/postgres/10/main
db-port=5432
db-user=postgres

[global]
repo-path=/home/backrest
retention-full=2
retention-archive=2
~~~

Full Command : 

~~~
pgbackrest --stanza=nkaal10 --log-level-stderr=debug --db-path=/home/postgres/10/restore/ restore
~~~

Backups and archiving are OK. Checksum are enabled in the PG cluster. 

[pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/1518058/pgbackrest.log)

**Comment by dwsteele** [comment]
Can you run: 
```
gzip -t /home/backrest/backup/nkaal10/20171130-095837F/pg_data/base/28493/237820.gz
```
I don't think this is a compression issue but I would like to be sure before proceeding.

**Comment by slardiere** [comment]
~~~
postgres@muuroi:~$ gzip -t /home/backrest/backup/nkaal10/20171130-095837F/pg_data/base/28493/237820.gz
postgres@muuroi:~$ echo $?
0
~~~

**Comment by dwsteele** [comment]
Also, what does the `/etc/pgbackrest.conf` file look like on your db server?  I only see one config above and it looks like it is off your backup server.

**Comment by slardiere** [comment]
Indeed : 
~~~
[nkaal10]
db-path=/home/postgres/10/main
backup-host=muuroi.lardiere.net
backup-user=postgres


[global]
repo-path=/home/backrest
~~~

**Comment by dwsteele** [comment]
Oh, I see - you are trying to restore on the same host as the repo -- which to be clear is a different host from the db host?

**Comment by slardiere** [comment]
Yes, I'm trying to restore on the same host as the repo, which is is a different host from the db host.

**Comment by dwsteele** [comment]
OK, yes, I can see that from the last config.

**Comment by dwsteele** [comment]
OK, I think I see what is going on here.  Try creating a new config file `/etc/pgbackrest.restore.conf`:
```
[global]
repo-path=/home/backrest
```
Then run your restore with the new config file:
```
pgbackrest --config=/etc/pgbackrest.restore.conf --stanza=nkaal10 --log-level-stderr=debug --db-path=/home/postgres/10/restore/ restore
```
It looks like the master process is working fine, but when the local minion starts up it gets confused about what server it is running on and tries to connect to the database server.

**Comment by slardiere** [comment]
Indeed, it works ! I'm pretty sure it has been ok by the past, without the given config command line and config.

**Comment by dwsteele** [comment]
It's certainly possible that it *was* working and got broken somewhere along the way.  We'll get a fix for this into the next release, but at least you have a workaround for the time being.

**Comment by slardiere** [comment]
Thanks, I'm ready to test a patch if any.

**Comment by dwsteele** [comment]
OK, so there were a few issues here.

First was that the error we used to have in this case went by the wayside a while ago.  This has been fixed here at c5fc88d34097ba03cd4fce3fbfce.

But, that just makes the error message more comprehensible.  So, I also added a patch that allows you to "negate" certain options in a config so you don't have to write a new one: 99a072163192e754663.

So, in your case you could add `--no-db1-host` and your restore would work.

There are a few problems, though.  For instance, how is anyone ever going to figure that out?  We could add some hints or documentation but I don't think that would solve the problem.  It would be best if pgBackRest could just "figure out" what is going on but I'm not sure how to make that happen.

Two is, I have only committed this to master, which is currently working towards 2.0.  I'm not sure this is worth back-patching to 1.X unless a more serious bug comes in that *must* be fixed.

What do you think?

**Comment by dwsteele** [comment]
We decided that this will be back-patched to 1.X but won't trigger a release.  I'll close this issue when the back-patch is complete.

**Comment by slardiere** [comment]
Thanks ! 

It seems correct, as the error message is more clear and there is a workaround. The "negate" behavior should be documented, though. 

I can't test today, but I've a look soon.

**Comment by dwsteele** [comment]
I documented the negate feature here 3cc367185e1a9be.  However, this feature will not be part of 1.X .  For 1.X the solution will be to use a separate config file (as you are already doing).  I have committed various fixes required to make that more practical and fixed the bad error message you were getting.  You can expect 1.27 to be release soon.
