### ISSUE TITLE
Backup using Amazon S3 without internet connection

### ISSUE THREAD

**Issue by ilpereira** [pgbackrest/pgbackrest#453]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 1.26

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a backup host server, one or more standbys), please specify each:
RHEL 7
4. Did you install pgBackRest from source or from a package?
Package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I am working on the following scenario: a remote machine (to which I have access) runs a PostgreSQL database and I want it to perform backups to my Amazon S3 server, but the problem is that this machine does not have an internet connection. What I've tried to do is setting up an SSH tunnel from this machine to my machine (which has internet connection) using the following command:
ssh  -f user@remote.machine -R 5555:localhost:8888 -N 
which, from my understanding, routes connections in port 5555 on the remote machine to port 8888 on my machine. I have also set the "http_proxy" environment variable to https://127.0.0.1:5555 on the remote machine, so that HTTP requests will go through port 5555 and end up in my port 8888 (via the tunnel).

I have tested this setup by executing, for instance, "curl www.google.com" on the remote machine and it works, I am able to get the content of the website, but when I try to create the stanza for the backup (after properly setting the file "/etc/pgbackrest.conf, as in the user guide), I get the following error:
ERROR: [049]: Invalid argument: IO::Socket::IP configuration failed
INFO: stanza-create command end: aborted with exception [049]

I don't know if pgBackRest actually uses HTTP when connecting to an Amazon S3 server. Maybe I'm also missing something else for this setup to work. I have done some research online, but haven't found any useful answers for the problem. Does anyone have any hints on how to perform a backup to Amazon S3 without internet connection (if it's possible)?

Thanks!

**Comment by dwsteele** [comment]
pgBackRest uses HTTPS to connect with S3.  I doubt it will be happy with this approach.

Try setting up your machine as a backup server as described in http://pgbackrest.org/user-guide.html#backup-host.  You can set up the s3 repository on the backup server and then the db server will backup to S3.  Note that this requires two-way communication or a working ssh tunnel to function.  You can use the `db-ssh-port` and `backup-ssh-port` options to set a custom port for pgBackRest to communicate through (instead of the default port 22).

**Comment by ilpereira** [comment]
I tried to set up my machine as a backup server, as described in the user guide. However, when I run the command to create the stanza, I'm getting the following error: 

ERROR: [124]: process terminated due to an unhandled exception:
                                        Use of uninitialized value in string eq at /usr/share/perl5/pgBackRest/Db.pm line 762.
                                         at /bin/pgbackrest line 15.
                                        	main::__ANON__('Use of uninitialized value in string eq at /usr/share/perl5/p...') called at /usr/share/perl5/pgBackRest/Db.pm line 762
                                        	pgBackRest::Db::configValidate(undef) called at /usr/share/perl5/pgBackRest/Stanza.pm line 613
                                        	pgBackRest::Stanza::dbInfoGet('pgBackRest::Stanza=HASH(0x6b7918)') called at /usr/share/perl5/pgBackRest/Stanza.pm line 52
                                        	pgBackRest::Stanza::new('pgBackRest::Stanza') called at /bin/pgbackrest line 213
                                        	eval {...} called at /bin/pgbackrest line 284

I don't know if that's a problem, but I set the "db-user" option in /etc/pgbackrest.conf (in my machine) as 'root', not 'postgres', because I'm not able to access the remote machine via ssh using user postgres. 

Do you have any idea about how can I debug the error?

Once again, thanks!

**Comment by dwsteele** [comment]
If you are trying to log on as root, you need to be sure that root has the superuser privilege.  The query that DB.pm is trying to run is:
```
select (select setting from pg_settings where name = 'server_version_num'),
           (select setting from pg_settings where name = 'data_directory');
```
This query is apparently returning NULLs which is probably down to a permissions issue -- I've never see it before.

You'll also need to grant execute permission explicitly to root to run all the functions that pgBackRest uses pg_start_backup, pg_stop_backup, etc.  You can find these by searching through Db.pm or seeing what errors you get.

**Comment by ilpereira** [comment]
Ok, but this query tries to get the info from which directories? I set permissions to 777 in /var/lib/pgsql/ and all its files and subdirectories, but the error remains the same.

Also, how do I grant execute permission to root to run all the functions that pgBackRest uses? Is there a directory that contains binaries for these functions? I searched but was not able to find it.

Another question: do I have to set any option in /etc/pgbackrest.conf when using the tunnel that I mentioned previously? You told me about 'db-ssh-port' and 'backup-ssh-port' options, but these are only used if I don't want to use the default port 22 for ssh communication, which is not the case (if I got it right), because ssh is running on port 22 in both machines. For example, if I have the following tunnel:

ssh -f user@remote.machine -R 5555:localhost:8888 -N

and remote.machine is the db-primary, would I have to set 'db-ssh-port' to 8888 (in my machine) and 'backup-ssh-port' (in the remote machine) to 5555?

**Comment by dwsteele** [comment]
I meant a permissions issue on **postgres**, i.e. you are logging on as a user that has incorrect/insufficient permissions.

I honestly don't think running an ssh tunnel over ssh is going to work.  If postgres doesn't have permission to logon via ssh, then you will have to get the backup to run as root somehow -- but I really don't recommend that.

We don't test a configuration like this so I don't have anything pre-tested to provide you.
