### ISSUE TITLE
archive-copy=y: will WAL in pg_xlog/pg_wal be complete after "pgbackrest ... backup" has finished?

### ISSUE THREAD

**Issue by mnullmei** [pgbackrest/pgbackrest#454]
1. pgBackRest version: 1.26
2. PostgreSQL version: 9.6.6
3. Debian 9 on both PG server and backup server
4. installed from pgbackrest_1.26-1.pgdg90+2_amd64.deb from apt.postgresql.org
5. pgbackrest.conf: [backrest_pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/1539951/backrest_pgbackrest.conf.txt) , [postgres_pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/1539949/postgres_pgbackrest.conf.txt)

For a use case that is essentially using Postgres as an analytics database worth a couple of TB, I have a setup with "archive-copy=y" that is able to start Postgres on a spare machine directly from the backup.

However, there is an additional requirement of archiving WAL merely during backups, for the backup host is not supposed to receive the WAL created during data processing, etc.
Now I had the idea of enabling pgbackrest as "archive_command" in postgresql.conf exclusively while testing and performing backups, by forcing a reload of postgresql.conf (using /bin/true to disable). But then I do not know at what time I can be sure that all the WAL I need has indeed arrived in the pg_xlog/pg_wal directory of the backup.

Is it guaranteed that all WAL will have been transferred when the "pgbackrest ... backup" command on the backup host has terminated successfully, or are there other means to check this?

**Comment by dwsteele** [comment]
If `archive-check=y` (the default) then the `backup` command will wait until all WAL has arrived in the archive before successfully completing the backup.  So it looks like your plan will work.

I wonder if the extra complexity is worth it, though.  What's the reason for not archiving during normal operations, space or performance?

**Comment by mnullmei** [comment]
Thank you very much for your answer -- only now I see that most of it is essentially included in the documentation of `archive-check` -- I must have somehow overlooked that option. Maybe one could still add something along the lines of 
> This also applies to WAL segments in the backup if `archive-copy` is enabled.

as a second sentence of [http://pgbackrest.org/configuration.html#section-backup/option-archive-check](http://pgbackrest.org/configuration.html#section-backup/option-archive-check).
I will now explicitly activate `archive-check` in the configuration files in order to stress that I am relying on it.

As for the "stop archiving after backup" requirement, this is due to performance after a fashion, and also due to perceived fragility of old hardware.
It turns out we are rather short of hardware resources, and the no-too-recent backup server primarily has got other duties, which should not slow down too much, or even fail. For it came to pass some time ago that a few data ingestion jobs on the (OLAP) database server killed several (5 year old) RAID hard disks in one fell swoop. The disks of the backup/etc. server are even older, and thus a decision was taken not to extend its load beyond mere backups.

As the timings of the backups and of all essential changes to the database can be scheduled in coordination, the plan described above seems to be workable, although it is certainly far from ideal.

**Comment by dwsteele** [comment]
I added documentation to clarify the relationship between `archive-copy` and `archive-check` as you suggested at 0bfda1a908edd1ca.

Having some sort of backup is better than having none at all but you might make it known that backups are running in a degraded mode.  Maybe that will help spur a hardware upgrade.
