### ISSUE TITLE
Add command for "stanza-delete"

### ISSUE THREAD

**Issue by mhagander** [pgbackrest/pgbackrest#457]
Right now pgbackrest has a "stanza-create" and a "stanza-upgrade".

It would be useful to also have a "stanza-delete", to clean up old stanzas for decomissioned systems.

**Comment by dwsteele** [comment]
Agreed.  This has been on the backlog for a long time, but it's probably time to move the priority up.

**Comment by dwsteele** [comment]
We are targeting this feature for 2.0,  but we will likely backpatch it into 1.X as long as it is not too invasive.

**Comment by dwsteele** [comment]
Feature added at 0e9ba98a50159fc1f26792f in master.

**Comment by dwsteele** [comment]
Committed to `release/1` at c36997bfb5df56c612.
