### ISSUE TITLE
archive location issue

### ISSUE THREAD

**Issue by dkumarr2** [pgbackrest/pgbackrest#458]
Hi,

In my environment, we have set archive_command previously for moving archives to our desired location whenever the transaction completed. But after changed the archive_command value for pgbackrest, if the transaction got committed it is not moving to our desired location. The archives just moving to repo-path when only backup performed. Can you please let me know how to fix this issue. we need to have the archives to be generated when the transaction completed to our location.

**Comment by dwsteele** [comment]
I can't understand what you are trying to say here.  Please answer the questions that were asked when you opened the issue and provide a more detailed explanation.

Have you tried running the `check` command?  Maybe there is not enough write activity to generate the WAL segments?

**Comment by dwsteele** [comment]
Closing this issue because it is idle.

If you are still having the issue, please respond with details and we'll have a look.
