### ISSUE TITLE
Don't print '   db (prior)' once prior major version is expired out

### ISSUE THREAD

**Issue by sfrost** [pgbackrest/pgbackrest#460]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 

1.26

2. PostgreSQL version: 

9.6, then 10

3. Operating system/version - if you have more than one server (for example, a database server, a backup host server, one or more standbys), please specify each:

Debian / jessie

4. Did you install pgBackRest from source or from a package?

Yes, packages from apt.postgresql.org

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Not applicable.

7. Describe the issue:

We write out '   db (prior)' as the last output from a 'pgbackrest info' command (and without a newline) even when there aren't any backups or WAL from the prior DB version any longer following a stanza upgrade, which is odd and leads to an info command that looks like this:

...
        diff backup: 20171201-090001F_20171217-090001D
            timestamp start/stop: 2017-12-17 09:00:01 / 2017-12-17 09:24:12
            wal start/stop: 0000000100000141000000B1 / 0000000100000141000000B1
            database size: 155.5GB, backup size: 36.4GB
            repository size: 26.9GB, repository backup size: 5.7GB
            backup reference list: 20171201-090001F

        incr backup: 20171201-090001F_20171218-090001I
            timestamp start/stop: 2017-12-18 09:00:01 / 2017-12-18 09:20:57
            wal start/stop: 00000001000001420000002B / 00000001000001420000002B
            database size: 155.7GB, backup size: 31.7GB
            repository size: 26.9GB, repository backup size: 4.8GB
            backup reference list: 20171201-090001F, 20171201-090001F_20171217-090001D

    db (prior)backrest@bajor:~$ 

(note the shell prompt being displayed right after the 'db (prior)').

**Comment by dwsteele** [comment]
Committed at 67c8f0dc5b (v1) and ef3ef85c33ac871a49 (v2).
