### ISSUE TITLE
Error running full backup v1.26

### ISSUE THREAD

**Issue by avegamwala** [pgbackrest/pgbackrest#462]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 1.26

2. PostgreSQL version: 9.2

3. Operating system/version - Ubuntu 16.04 (xenial)

4. Did you install pgBackRest from source or from a package? Package

5. Getting the following error when running a full backup of a specific database:

**backrest@hostname:~$ pgbackrest --stanza=name backup --type=full**

WARN: stop-auto option is only available in PostgreSQL >= 9.3
WARN: aborted backup 20171219-163708F of same type exists, will be cleaned to remove invalid files and resumed

WARN: resumed backup file pg_data/base/16387/9314020 should have checksum 4e24507bbdab774525590d7e5599de9dd5e0a028 but actually has checksum 3362e6a49ed42654851ebee3d29a246e751b2868. The file will be recopied and backup will continue but this may be an issue unless the backup temp path is known to be corrupted.

ERROR [057]: : raised from remote process on 'hostname': no statement executing:
select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, null as labelfile, null as spcmapfile from pg_stop_backup() as lsn

**Comment by cmwshang** [comment]
The following are applicable to this issue:

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

**Comment by dwsteele** [comment]
Closing this because it is idle.

If you are still having the issue, feel free to provide the information Cynthia requested and we'll have a look.
