### ISSUE TITLE
Is full backup necessary after switchover or failover?

### ISSUE THREAD

**Issue by pritammobisoft** [pgbackrest/pgbackrest#467]
Let's assume the following scenario: 

We have 4 hosts: 

Postgres: pg1, pg2, and pg3
Backup: backup

pg1 is master and pg2 and pg3 are standby hosts. Native PgSQL async Streaming Replication is configured. The backup is managed with PgBackRest. Backup from standby is enabled in PgBackRest. 

1. We switchover the master to pg2 (when there is 0 replication lag) and pg1 becomes a standby without any data loss. Is full backup necessary so as to ensure that the consistent backup is available for the cluster? 

2. pg1 goes down because of some operational failure. We lose access to it. Now we find the leader in p2 and pg3. Let's say pg2 is ahead, but there might be some data loss as we can't really determine if pg2 was in sync before pg1 went down. We failover to pg2 and pg3 is standby.  Backup from standby is enabled in PgBackRest.  Is full backup necessary so as to ensure that the consistent backup is available for the cluster?

**Comment by pritammobisoft** [comment]
I tried this out. In both the cases after failover and swicthover I ran the following command:

`sudo -u pgbackrest pgbackrest --stanza=main --log-level-console=info backup`

In both the cases, PgBackRest chose to do an incremental backup. So I am assuming incremental backup is sufficient. 

**After failover:**

```
sudo -u pgbackrest pgbackrest --stanza=main info
stanza: main
    status: ok

    db (current)
        wal archive min/max (9.6-1): 000000010000000000000002 / 000000020000000000000010

        full backup: 20180116-152146F
            timestamp start/stop: 2018-01-16 15:21:46 / 2018-01-16 15:21:58
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 20.9MB, backup size: 20.9MB
            repository size: 2.4MB, repository backup size: 2.4MB

        incr backup: 20180116-152146F_20180116-152339I
            timestamp start/stop: 2018-01-16 15:23:39 / 2018-01-16 15:23:46
            wal start/stop: 000000010000000000000005 / 000000010000000000000005
            database size: 20.9MB, backup size: 72.2KB
            repository size: 2.4MB, repository backup size: 1KB
            backup reference list: 20180116-152146F

        incr backup: 20180116-152146F_20180116-154058I
            timestamp start/stop: 2018-01-16 15:40:58 / 2018-01-16 15:41:12
            wal start/stop: 000000020000000000000010 / 000000020000000000000010
            database size: 177.6MB, backup size: 156.8MB
            repository size: 11.3MB, repository backup size: 8.9MB
            backup reference list: 20180116-152146F
```

Here, after failover, it is interesting to note that PgBackRest gives DB size as 177.6 MB. This is for a fresh PgSQL installation, with no other data. 

**After switchover:**

```
stanza: main
    status: ok

    db (current)
        wal archive min/max (9.6-1): 000000010000000000000002 / 000000020000000000000009

        full backup: 20180116-155134F
            timestamp start/stop: 2018-01-16 15:51:34 / 2018-01-16 15:51:47
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 20.9MB, backup size: 20.9MB
            repository size: 2.4MB, repository backup size: 2.4MB

        incr backup: 20180116-155134F_20180116-155331I
            timestamp start/stop: 2018-01-16 15:53:31 / 2018-01-16 15:53:38
            wal start/stop: 000000010000000000000005 / 000000010000000000000005
            database size: 20.9MB, backup size: 72.2KB
            repository size: 2.4MB, repository backup size: 1KB
            backup reference list: 20180116-155134F

        incr backup: 20180116-155134F_20180116-160949I
            timestamp start/stop: 2018-01-16 16:09:49 / 2018-01-16 16:09:57
            wal start/stop: 000000020000000000000009 / 000000020000000000000009
            database size: 20.9MB, backup size: 72.2KB
            repository size: 2.4MB, repository backup size: 1KB
            backup reference list: 20180116-155134F

```

**Comment by dwsteele** [comment]
>     We switchover the master to pg2 (when there is 0 replication lag) and pg1 becomes a standby without any data loss. Is full backup necessary so as to ensure that the consistent backup is available for the cluster?

If you have to restore before taking a full backup then you can use `recovery_target_timeline=latest` to follow the new timeline created after promition.

It's best to get a full backup as soon as possible.  A full backup should be taken after a failover evern though pgBackRest doen't insist on it.

>     pg1 goes down because of some operational failure. We lose access to it. Now we find the leader in p2 and pg3. Let's say pg2 is ahead, but there might be some data loss as we can't really determine if pg2 was in sync before pg1 went down. We failover to pg2 and pg3 is standby. Backup from standby is enabled in PgBackRest. Is full backup necessary so as to ensure that the consistent backup is available for the cluster?

Yes - for the same reason as above.  It's also possible that pg3 would play past pg2 and would need to be restored to follow pg2.  This could be done initially with `recovery_target_timeline=latest` however.

> Here, after failover, it is interesting to note that PgBackRest gives DB size as 177.6 MB

Not sure what is going on here - if you attach the backup.manifest files (found in each backup dir) for these backups I could have a look.

**Comment by pritammobisoft** [comment]
Hi, Thanks for the info. I will recommend full backup after failover and switchover. 

Also, the 177.6 MB thing is a false alarm. Actually, I am automating this setup and had added a few pgbench commands just before the failover.  That's what was causing the DB size to grow. Really sorry for the misinformation. It's a side project, I am doing in between some other crazy schedule :-)

**Comment by dwsteele** [comment]
No worries -- glad it wasn't an issue!
