### ISSUE TITLE
P00  ERROR: [042]: local-4 process terminated unexpectedly [000]

### ISSUE THREAD

**Issue by Tostino** [pgbackrest/pgbackrest#468]
1. pgBackRest version:
1.26/1.27

2. PostgreSQL version:
10.1

3. Operating system/version - if you have more than one server (for example, a database server, a backup host server, one or more standbys), please specify each:
Debian Stretch on both backup / DB

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. 
[db-pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/1635707/db-pgbackrest.txt)
[bak-pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/1635708/bak-pgbackrest.txt)

[main-backup.log](https://github.com/pgbackrest/pgbackrest/files/1635717/main-backup.log)

7. Describe the issue:
pgbackrest will crash when trying to run a full backup from the backup server after some time.

Nothing was obvious in the syslogs on either the backup or db server to include, nor was there anything interesting in the postgres logs during the backup / crash.

**Comment by Tostino** [comment]
Ugh, sorry. Never mind. Missed that there was an OOM killer message in syslog on backup server. Explains it.

**Comment by dwsteele** [comment]
Yeah, that would do it.  I'm a little surprised that it returned 0, but I haven't spent any time experimenting with how the OOM killer affects remote processes.
