### ISSUE TITLE
general questions about backups and WAL archives

### ISSUE THREAD

**Issue by ftc2** [pgbackrest/pgbackrest#469]
i have some general questions about pgbackrest and in a way postgresql.
to be more specific, i have questions about what is required to do db restorations, backups vs WAL archives, and what's going on at the filesystem level in pgbackrest's repo dir.

i'll start with a simple one that will probably clear up a lot for me:

1) consider creating a full backup and then ONLY having the `backup` dir `/var/lib/pgbackrest/backup`. i.e. pretend you delete the `archive` dir after making the backup. is it possible to restore this full backup on a fresh cluster?

i've tried and failed. if the answer is 'no', obviously don't bother reading the rest of this post, and i'll ask a follow-up question afterwards. thanks!

```
$ sudo cat /etc/pgbackrest.conf
[global]
repo-path=/var/lib/pgbackrest
start-fast=y
stop-auto=y
retention-full=6

[main]
db-path=/var/lib/postgresql/9.6/main
```

after deleting everything in the `archive` dir in the repo:

```
$ sudo -u postgres pgbackrest --stanza=main info
stanza: main
    status: ok

    db (current)
        wal archive min/max (9.6-1): none present

        full backup: 20171224-014016F
            timestamp start/stop: 2017-12-24 01:40:16 / 2017-12-24 01:40:28
            wal start/stop: 000000010000000000000006 / 000000010000000000000006
            database size: 34.5MB, backup size: 34.5MB
            repository size: 3.6MB, repository backup size: 3.6MB

        incr backup: 20171224-014016F_20171224-014831I
            timestamp start/stop: 2017-12-24 01:48:31 / 2017-12-24 01:48:34
            wal start/stop: 000000010000000000000008 / 000000010000000000000008
            database size: 34.5MB, backup size: 8.2KB
            repository size: 3.6MB, repository backup size: 401B
            backup reference list: 20171224-014016F

        incr backup: 20171224-014016F_20171224-015056I
            timestamp start/stop: 2017-12-24 01:50:56 / 2017-12-24 01:50:59
            wal start/stop: 00000001000000000000000A / 00000001000000000000000A
            database size: 34.5MB, backup size: 8.2KB
            repository size: 3.6MB, repository backup size: 398B
            backup reference list: 20171224-014016F

        full backup: 20171224-015126F
            timestamp start/stop: 2017-12-24 01:51:26 / 2017-12-24 01:51:37
            wal start/stop: 00000001000000000000000C / 00000001000000000000000C
            database size: 34.5MB, backup size: 34.5MB
            repository size: 3.6MB, repository backup size: 3.6MB

        incr backup: 20171224-015126F_20180120-030339I
            timestamp start/stop: 2018-01-20 03:03:39 / 2018-01-20 03:03:44
            wal start/stop: 00000001000000000000000F / 00000001000000000000000F
            database size: 34.5MB, backup size: 2.5MB
            repository size: 3.6MB, repository backup size: 306.1KB
            backup reference list: 20171224-015126F

        incr backup: 20171224-015126F_20180120-031027I
            timestamp start/stop: 2018-01-20 03:10:27 / 2018-01-20 03:10:31
            wal start/stop: 000000010000000000000011 / 000000010000000000000011
            database size: 34.5MB, backup size: 1.2MB
            repository size: 3.6MB, repository backup size: 142.3KB
            backup reference list: 20171224-015126F, 20171224-015126F_20180120-030339I
```

then delete and recreate the cluster:

```
$ sudo pg_ctlcluster 9.6 main stop
$ sudo pg_dropcluster 9.6 main
$ sudo -u postgres /usr/lib/postgresql/9.6/bin/initdb -D /var/lib/postgresql/9.6/main -k
$ sudo pg_createcluster 9.6 main
$ sudo pg_ctlcluster 9.6 main start
```

then re-configuring archiving in `/etc/postgresql/9.6/main/postgresql.conf`, restarting postgresql, and recreating the stanza:

```
$ sudo -u postgres pgbackrest --stanza=main --log-level-console=info stanza-create --force
2018-01-20 05:06:46.433 P00   INFO: stanza-create command begin 1.25: --db1-path=/var/lib/postgresql/9.6/main --force --log-level-console=info --repo-path=/var/lib/pgbackrest --stanza=main
2018-01-20 05:06:48.047 P00   INFO: stanza-create command end: completed successfully
```

but i'm getting kind of stuck here:

```
$ sudo -u postgres pgbackrest --stanza=main info
ERROR [125]: : unable to retrieve the archive id

$ sudo -u postgres pgbackrest --stanza=main --log-level-console=info check
2018-01-20 05:16:18.587 P00   INFO: check command begin 1.25: --db1-path=/var/lib/postgresql/9.6/main --log-level-console=info --repo-path=/var/lib/pgbackrest --stanza=main
2018-01-20 05:16:19.571 P00   INFO: WAL segment 000000010000000000000003 successfully stored in the archive at '/var/lib/pgbackrest/archive/main/9.6-1/0000000100000000/000000010000000000000003-a21d5c75b9ac0223b4b654c3c6ad9ebc6c86b154.gz'
2018-01-20 05:16:19.572 P00   INFO: check command end: completed successfully
```

btw the `backup` dir is still intact:

```
$ sudo du -sh /var/lib/pgbackrest/*
1.4M	/var/lib/pgbackrest/archive
23M	/var/lib/pgbackrest/backup
```

**Comment by dwsteele** [comment]
WAL is required to restore a PostgreSQL backup of any kind.  However, it is possible to use the `archive-copy` option to copy just enough WAL to make the backup consistent into the backup directory.  That doesn't mean you should delete the archive directory, though.

The info command is not working because you forced the repo to a new system id but backup.info still has the old system id as well.  This might be something we can improve, but since the old backups in your repo are useless I'm not sure how much it would help.

**Comment by ftc2** [comment]
that makes sense. thank you.

my next question: why is WAL needed in the archive to restore a pgbackrest full backup?

i get why you need WAL to do PITR between backups for example, but i guess i had a misconception that full backups are self-contained in the `backup` dir in the repo.

is it because at the moment of backup, the db (probably) has newer commits that exist only as WAL, and pgbackrest backups are stored in this same manner?

**Comment by dwsteele** [comment]
> is it because at the moment of backup, the db (probably) has newer commits that exist only as WAL, and pgbackrest backups are stored in this same manner?

Yes.  The WAL generated during the backup is required during restore to make the database consistent.  After that the WAL is required if you want to play forward past the end of the backup.

See https://www.postgresql.org/docs/10/static/continuous-archiving.html for more information.
