### ISSUE TITLE
Safe way to delete orphaned incremental backups (missing base full backup)

### ISSUE THREAD

**Issue by pshlykov** [pgbackrest/pgbackrest#471]
Hi All,

I've got a situation where there are 2 orphaned incremental backups are left without their base full or differential backup. There's little visibility of what has caused this, more importantly is that there is a full backup and its incrementals we'd want to be unharmed while being able to remove the two orphaned incremental backups to reclaim the disk space to allow a new full backup to be taken.

Here's what on the filesystem, two redundant backups to be removed are marked in bold:
-bash-4.2$ ll
total 36
**drwxr-x---. 4 enterprisedb enterprisedb    6 Jan  7 01:55 20171231-160000F_20180107-010000I
drwxr-x---. 4 enterprisedb enterprisedb    6 Jan  8 01:54 20171231-160000F_20180108-010000I**
drwxr-x---. 4 enterprisedb enterprisedb    6 Jan 14 08:22 20180114-010000F
drwxr-x---. 4 enterprisedb enterprisedb    6 Jan 15 01:54 20180114-010000F_20180115-010000I
drwxr-x---. 4 enterprisedb enterprisedb    6 Jan 16 01:45 20180114-010000F_20180116-010000I
drwxr-x---. 4 enterprisedb enterprisedb    6 Jan 17 01:47 20180114-010000F_20180117-010000I
drwxr-x---. 4 enterprisedb enterprisedb    6 Jan 18 01:46 20180114-010000F_20180118-010000I
drwxr-x---. 4 enterprisedb enterprisedb    6 Jan 20 01:52 20180114-010000F_20180119-010000I
drwxr-x---. 4 enterprisedb enterprisedb    4 Jan 12 16:04 backup.history
-rw-r-----. 1 enterprisedb enterprisedb 6755 Jan 22 19:36 backup.info
-rw-r-----. 1 enterprisedb enterprisedb 6755 Jan 22 19:36 backup.info.copy
lrwxrwxrwx. 1 enterprisedb enterprisedb   33 Jan 20 01:52 latest -> 20180114-010000F_20180119-010000I

The environment is: 
Postgres EDB 9.6 AS
pgBackRest 1.22
Oracle Linux Server release 7.3

What is the best / safest way to remove these two incrementals without breaking anything?

Thanks
Pav

**Comment by dwsteele** [comment]
Hi Pavel,

I would sure like to know how that happened.  Can you do an `ls` of those two directories and see if the `backup.manifest` file exists?  Also, could you attach a copy of your `backup.info` file?  There is not much sensitive in there, but mainly I want to see the list of backups under `[backup:current]`.

After you get that information it should be safe to simple delete those directories: `20171231-160000F_20180107-010000I`, `20171231-160000F_20180108-010000I`.  You will likely get some warnings on your next backup that they were removed, but other than that you should be fine.

I think I have an idea what happened here.  If the expire process died or was killed while removing the `backup.manifest` files from the backup directories then it might not try again.  Is there any record of a crash/abort in your backup logs?  If you can provide me with the information requested above it will help us track this down.

Thanks!
-David

**Comment by pshlykov** [comment]
Hi David,

Thanks for the quick reply!

I am convinced the issue is caused by a manual cleanup in the backup repo directory. I don't know what exactly was done but the cluster was failed over to its standby and back a few times as a planned changes. There's a pretty good chance that some things were moved around or deleted to facilitate the volume of WALs copied between primary and standby hosts for faster resync. 

You're saying if I just delete these two directories, pgbackrest will be able to handle it and update the backup.info files accordingly, is this correct? 

Please see the listing of the directories below:
```
-bash-4.2$ ll
total 2809
-rw-r-----. 1 enterprisedb enterprisedb 3938935 Jan  7 01:55 backup.manifest
-rw-r-----. 1 enterprisedb enterprisedb 3938935 Jan  7 01:55 backup.manifest.copy
drwxr-x---. 7 enterprisedb enterprisedb       9 Jan  7 01:55 pg_data
drwxr-x---. 3 enterprisedb enterprisedb       3 Jan  7 01:03 pg_tblspc
-bash-4.2$ cd ../20171231-160000F_20180108-010000I
-bash-4.2$ ll
total 2867
-rw-r-----. 1 enterprisedb enterprisedb 4045652 Jan  8 01:54 backup.manifest
-rw-r-----. 1 enterprisedb enterprisedb 4045652 Jan  8 01:54 backup.manifest.copy
drwxr-x---. 7 enterprisedb enterprisedb       9 Jan  8 01:54 pg_data
drwxr-x---. 3 enterprisedb enterprisedb       3 Jan  8 01:05 pg_tblspc
```
Please find the backup.info attached here: 
[backup_info.zip](https://github.com/pgbackrest/pgbackrest/files/1654658/backup_info.zip)

Thanks,
Pav

**Comment by dwsteele** [comment]
Thanks for the info, Pavel!  What I'm seeing is consistent with manually removed (or not moved) directories.

> I am convinced the issue is caused by a manual cleanup in the backup repo directory. I don't know what exactly was done but the cluster was failed over to its standby and back a few times as a planned changes. There's a pretty good chance that some things were moved around or deleted to facilitate the volume of WALs copied between primary and standby hosts for faster resync.

OK, got it.  Still, I'm not happy that these backups are not being expired when they are clearly orphaned.  I don't want to to do it automatically, but perhaps a `--force` option on `expire` would be useful.

> You're saying if I just delete these two directories, pgbackrest will be able to handle it and update the backup.info files accordingly, is this correct?

Yes, you can manually remove them without hurting the next backup set.  You will get warnings on your next backup that they have been removed from `backup.info`.

**Comment by pshlykov** [comment]
Thanks for the solution David!

I assume the backups were not made expired due to the subsequent full backups after `20180114-010000F` one were failing due to the disk space issue. 

I've managed to get the filesystem extended and it allowed to take a full backup -- my calculations showed that removing the orphaned incrementals wouldn't have helped.

Thanks again! Really appreciate!!!

Best,
Pavel

**Comment by dwsteele** [comment]
You're welcome.  Glad it worked out!
