### ISSUE TITLE
pgBackRest restoring a malformed postgresql.conf file

### ISSUE THREAD

**Issue by jhammerman79** [pgbackrest/pgbackrest#473]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest 1.18

2. PostgreSQL 9.6.5

3. CentOS 7.2

4. Installed from source
[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/1657831/postgresql.conf.txt)
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/1657835/pgbackrest.conf.txt)

7. On pgbackrest restore, the restored postgresql.conf is malfromed (there are a few additional repeated lines). My theory is that the initial full backup was done with a mlformed postgresql.conf on disk. We are creating a test stanza on a 'known good' machine with syntactically correct postgresql.conf to test this theory.

Have you guys heard of anyone experiencing anything similar in the past? Is there any other avenue of troubleshooting that you would would like us to pursue?

This issue is reproducible (by which I mean restores always have a malformed postgresql.conf file.).

Thanks!
Joseph Hammerman

**Comment by dwsteele** [comment]
Hi Joseph,

Hmm, no, never seen anything like this.  Any chance Ansible was writing the file while pgBackRest was taking a backup?  If Ansible does not write to temp and move then this is possible, though unlikely.

If you can reproduce I'd certainly like to see the results.

Regards,
-David

**Comment by dwsteele** [comment]
Closing since there has been no response.  Feel free to reply with additional information or a repro.
