### ISSUE TITLE
Question about standby and archive_command

### ISSUE THREAD

**Issue by vadius8998** [pgbackrest/pgbackrest#475]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
1.27

2. PostgreSQL version:
9.6.6
3. Operating system/version - if you have more than one server (for example, a database server, a backup host server, one or more standbys), please specify each:
RHEL 7.4

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
On primary and standby: 
archive_mode = on               # enables archiving; off, on, or always
archive_command = 'pgbackrest  --config=/pgsql/dba/inst1/cfg/pgbackrest.conf --stanza=inst1 archive-push %p'            # command to use to archive a logfile segment

Identical pgbackrest.conf on both nodes:
[global]
repo-path=/pgsql/dump/inst1
retention-full=2
start-fast=y
process-max=2

[inst1]
db-path=/pgsql/data/9.6/inst1
db-port=5433
db-socket-path=/tmp

7. Describe the issue:
Streaming replication is enabled, in sync mode, and managed with repmgr. No remote backup node and pgbackrest backups run on the primary database. Everything runs fine. 
Backups are scheduled on both nodes, I check for the status of the database and call pgbackrest only on the primary node. 
On the standby database, WAL files are recycled as expected, but the archive_command pushes the WAL files to the local pgbackrest repository thanks to archive_command = 'pgbackrest ...' We accumulate WAL files until we switchover or failover and that's not manageable. 

My questions:
- shall I configure the backup from standby capability ? 
- or should I just set archive_mode = off on standby and update it again when the db is promoted ?

In both cases, I need to update either postgresql.conf or the pgbackrest config files on each node to change the roles of the databases, which I find a bit painful. 

Any advice on the best approach ?

**Comment by dwsteele** [comment]
The standby should not be pushing WAL unless if is set to `archive_mode = always`.  Are you sure that is not set somewhere?  PostgreSQL uses the last setting it finds.

Let's check that first, just execute `show archive_mode;` in psql on the standby.

**Comment by vadius8998** [comment]
Hi, 
I rebuilt both prim and standby from scratch, and the behavior I observe on the standby side looks fine. archive_mode is set to on, and no wal is pushed to pgbackrest. 
Not sure what happened, likely the leftover of other tests I performed. 
Sorry about the noise, pg_backrest rocks. 

Thx

**Comment by dwsteele** [comment]
Thanks! And glad you got it working.
