### ISSUE TITLE
Feature Request - Statsd (or similar) output on backup progress.

### ISSUE THREAD

**Issue by ianhiddleston** [pgbackrest/pgbackrest#480]
Feature Request 

7. Describe the issue:
Would it be possible to emit statsd format updates on backup progress and status? It'd be really useful to plumb that into our monitoring/metrics feeds upstream rather than scraping the info command output.

**Comment by dwsteele** [comment]
I can see how that would be useful, but there are a number of monitoring solutions that could be supported and it doesn't seem practical to cover them all.  So far our strategy has been to provide everything we can via the `info` command.

When you say "scraped" it makes me wonder if you have tried the `--output=json` option?

**Comment by ianhiddleston** [comment]
Yep, I've been using the json output. Scraping is the wrong way to describe it really.

I'm really looking for a way to check on the backup as it runs, rather than only once it finishes. Currently I tie that together with log output but it would be neater to get from a single location. Couple that to an output format that's easy to parse (json is fine) and I'd be pretty happy. I mentioned statsd as it's what I'm using and I'm biased, also because there are plugins to adapt it to Nagios which means others could use it.

To be fair, I'd also be happy with nothing, I fully appreciate it's an open source project and as I'm not really skilled up to contribute it's down to what makes sense for you.

**Comment by dwsteele** [comment]
We are planning to add currently running backup to the info output, so hopefully that will meet your needs.  I'm not sure when that's coming but it's on the roadmap.

Suggestions are always appreciated, but as you say, it's an open source project and we need to prioritize what we work on (and maintain).  However, there's no question that we can add more to the info output.
