### ISSUE TITLE
Files/folders required to be copied safely to another machine for future restore 

### ISSUE THREAD

**Issue by Pasayadaan** [pgbackrest/pgbackrest#482]
1. pgBackRest version: 1.12
2. PostgreSQL version: 9.2
3. Operating system/version - CentOS
4. Did you install pgBackRest from source or from a package? Package

Describe the issue:
Once the backup is complete, which files and folders are required to be copied safely to another machine for future restore if required? Are these /var/lib/pgbackrest/backup_info.txt, /var/lib/pgbackrest/backup/ and /var/lib/pgbackrest/archive/?
Is there any script to identify the most recent backup and move the required files / folders to a remote machine?

**Comment by dwsteele** [comment]
There is no script to do this, but all the information is available via the `info --output=json` command if you chose to script it.  I wouldn't recommend it though.  It would be really easy to make a mistake.

An easier option might be to use the `archive-copy` option.  This copies all WAL required to make the backup consistent into the backup dir.  Then you can just copy the backup wherever you want and drop it right in place.  Be sure to use `--hardlink` if you do this with backups that are not full backups.

**Comment by Pasayadaan** [comment]
What exactly this --hardlink option does and is it mandatory for incremental backup with --archive-copy?

**Comment by dwsteele** [comment]
Please have a look at the docs http://pgbackrest.org/configuration.html#section-backup/option-hardlink and let me know if they are not clear.

--hardlink is not required for --archive-copy.

**Comment by dwsteele** [comment]
Read this: http://www.linfo.org/hard_link.html.

We use hardlinks to make each backup directory contain all the files without using additional space.  Not available on S3 repos, of course.
