### ISSUE TITLE
How to get the most current backup's related archive folder name?

### ISSUE THREAD

**Issue by Pasayadaan** [pgbackrest/pgbackrest#484]
1. pgBackRest version: 1.12

2. PostgreSQL version: 9.2

3. Operating system/version - CentOS 6.8
4. Did you install pgBackRest from source or from a package? Package
Describe the issue:
Assuming for the successful restore in future, the backup folder and the related archive folder need to be preserved. One can get the latest backup folder name using pgbackrest info but is there any way to get the related archive folder name?

**Comment by dwsteele** [comment]
The `info --output=json` command will tell you what WAL is used for the backup.  You are looking for this section:
```
"archive" : {
                    "start" : "00000003000001AB00000043",
                    "stop" : "00000003000001AB00000043"
                },
```

The backup dir name is the same as the label which you can also find in the json output:
```
"label" : "20180211-063119F",
```

**Comment by Pasayadaan** [comment]
This shall be useful but the archive file name has some additional (checksum?) info. Also the first 16 chars of WAL segment is used as folder name inside.

**Comment by dwsteele** [comment]
Yes, the files are broken up to keep the directories from getting too large.  There is a SHA1 checksum in the filename to verify the integrity of the file.

The `archive-copy` option moves all the WAL to the pg_xlog/pg_wal dir in the backup with no subdirectories or extensions.
