### ISSUE TITLE
ERROR: [056]: raised from remote process on 'pgserver1': could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by palabre** [pgbackrest/pgbackrest#487]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:    1.28

2. PostgreSQL version:  10.1

3. Operating system/version - Oracle Linux 7

4. Did you install pgBackRest from source or from a package?
From yum

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I want to create a dedeicated host to backup 2 servers 
dedicated host : pgservertools (a user backupowner is used
server1 : pgserver1 with 2 clusters (on ports 5432 and 5433)
server2:  pgserver2 with 2 clusters (on ports 5432 and 5433)

when I want to create the stanza I am getting error
[backupowner@pgservertools ~]$ pgbackrest --stanza=pgserver1pgdata --log-level-console=detail --db-port=5432 --db-host=pgserver1 stanza-create
2018-02-20 16:04:48.596 P00   INFO: stanza-create command begin 1.28: --db1-host=pgserver1 --db1-path=/u90/pgdata/pg101 --db1-port=5432 --db1-user=postgres --log-level-console=detail --repo-cipher-pass=<redacted> --repo-cipher-type=aes-256-cbc --repo-path=/u90/backup --stanza=pgserver1pgdata
2018-02-20 16:04:49.697 P00  ERROR: [056]: raised from remote process on 'pgserver1': could not connect to server: No such file or directory
                                                Is the server running locally and accepting
                                                connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2018-02-20 16:04:49.712 P00   INFO: stanza-create command end: aborted with exception [056]

Find attached configuration files

Can you help

Thanks

[srpgbackrest.zip](https://github.com/pgbackrest/pgbackrest/files/1740727/srpgbackrest.zip)

**Comment by uspen** [comment]
db-port=5433?

**Comment by palabre** [comment]
Hi

on each server I have two clusters. For example on pgserver1 I have a cluster runnning on port 5432 and another runing on port 5433. And for each cluster I want to create a stanza. Is it the normal way?

**Comment by uspen** [comment]
Yes, but in config on backup server you must have option db1-port, db2-port etc

**Comment by palabre** [comment]
So even if a I have many cluster in a database server, I have to create only one stanza with options db1-port, db1_path, db2-port, db2-path and so on. 
Instead of this
[root@pgservertools backup]# cat /etc/pgbackrest.conf
[pgserver1pgdata]
db1-host=pgserver1
db1-path=/u90/pgdata/pg101
db1-user=postgres

[pgserver1pgdata2]
db1-host=pgserver1
db1-path=/u90/pgdata2/pg101
db1-user=postgres

My config file should be

[root@pgservertools backup]# cat /etc/pgbackrest.conf
[pgserver1pgdata]
db1-host=pgserver1
db1-path=/u90/pgdata/pg101
db1-user=postgres

db2-host=pgserver1
db2-path=/u90/pgdata2/pg101
db2-user=postgres

Is it right?

**Comment by uspen** [comment]
No
just add db-port

```
[pgserver1pgdata]
db1-host=pgserver1
db1-path=/u90/pgdata/pg101
db1-user=postgres
db1-port=5432

[pgserver1pgdata2]
db1-host=pgserver1
db1-path=/u90/pgdata2/pg101
db1-user=postgres
```

**Comment by uspen** [comment]
You have all confused at all

[THIS CLUSTER NAME]
db1-host=CONTAIN THIS CLUSTER
db1-path=...
etc...
db2-host=CONTAIN THIS CLUSTER
db2-path=...
etc...

**Comment by palabre** [comment]
Ok to be sure to understand

Can we have more than one stanza cluster in a server?

Regards

**Comment by dwsteele** [comment]
On the backup server I think you have some typos in pgbackrest.conf.  The `pgserver2pgdata` and `pgserver2pgdata2`  stanza should have `db1-host=pgserver2`.

On the db server, you should remove the `-host` and `-user` settings from the stanzas.  These clusters are local so no need to give a host and user.  Ports should be specified for all stanzas that are not on 5432.

But, I don't think those are the reasons for *this* error.  Likely Postgres on Oracle Linux is not storing the sockets in the usual place.  Look in `/tmp` for `.s.PGSQL.5432`.  If you find it there you can use  `db1-socket-path=/tmp` in each stanza on the db side to fix it.  Check the `unix_socket_directories` setting in `postgresql.conf` as well in case it was manually set.

**Comment by palabre** [comment]
Hi dwsteele

It works with the settings you suggest me
. The check command is failing because archive_command is not set. But I will manage this side.
The stanza creation is working now thanks

[backupowner@pgservertools ~]$  pgbackrest --stanza=pgserver1pgdata --log-level-console=detail --db-port=5432 --db-host=pgserver1 stanza-create
2018-02-21 15:21:42.815 P00   INFO: stanza-create command begin 1.28: --db1-host=pgserver1 --db1-path=/u90/pgdata/pg101 --db1-port=5432 --db1-user=postgres --log-level-console=detail --repo-cipher-pass=<redacted> --repo-cipher-type=aes-256-cbc --repo-path=/u90/backup --stanza=pgserver1pgdata
2018-02-21 15:21:46.881 P00   INFO: stanza-create command end: completed successfully

[backupowner@pgservertools ~]$  pgbackrest --stanza=pgserver1pgdata2 --log-level-console=detail --db-port=5433 --db-host=pgserver1 stanza-create
2018-02-21 15:23:39.116 P00   INFO: stanza-create command begin 1.28: --db1-host=pgserver1 --db1-path=/u90/pgdata2/pg101 --db1-port=5433 --db1-user=postgres --log-level-console=detail --repo-cipher-pass=<redacted> --repo-cipher-type=aes-256-cbc --repo-path=/u90/backup --stanza=pgserver1pgdata2
2018-02-21 15:23:41.360 P00   INFO: stanza-create command end: completed successfully
[backupowner@pgservertools ~]$

Below my config files

Backup host:
[root@pgservertools ~]# cat /etc/pgbackrest.conf
[pgserver1pgdata]
db1-host=pgserver1
db1-path=/u90/pgdata/pg101
db1-user=postgres

[pgserver1pgdata2]
db1-host=pgserver1
db1-path=/u90/pgdata2/pg101
db1-user=postgres
db1-port=5433

[pgserver2pgdata]
db1-host=pgserver2
db1-path=/u90/pgdata/pg101
db1-user=postgres

[pgserver2pgdata2]
db1-host=pgserver2
db1-path=/u90/pgdata2/pg101
db1-user=postgres
db1-port=5433

Pgserver1
[root@pgserver1 postgres]# cat /etc/pgbackrest.conf
[pgserver1pgdata]
db1-path=/u90/pgdata/
db1-socket-path=/tmp

[pgserver1pgdata2]
db1-path=/u90/pgdata2/pg101
db1-port=5433
db1-socket-path=/tmp

[global]
backup-host=pgservertools
backup-user=backupowner
log-level-file=detail
[root@pgserver1 postgres]#


Thanks Guys

**Comment by dwsteele** [comment]
No problem!
