### ISSUE TITLE
Question: Recreate a dedicated backup host from S3 after hardware failure

### ISSUE THREAD

**Issue by pritammobisoft** [pgbackrest/pgbackrest#488]
1. pgBackRest version: 1.27 or later

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Master DB, Standby DB, and Dedicated Backup server: All running Ubuntu 16.04

4. Did you install pgBackRest from source or from a package?
Github tar.gz release as per the user guide instructions.

**Question:**

In the above setup, let's say on the dedicated backup host we are using S3. So all the backup files are on S3. Becuase of some hardware issue, we lose the backup host. Now to keep the setup running, can we create a new server to play the role of the dedicated backup server by using the same "/etc/pgbackrest.conf" backed up from the old server and by pointing it to the same S3 location. (Also we make sure that all the hostnames and IP addresses are updated accordingly and SSH communication works amongst all hosts.)

Will this work properly? I think the question is, when using S3, does PgBackRest store anything on the local disk, that might be needed again to recreate the backup host.

**Comment by dwsteele** [comment]
Yes.  Nothing important is stored outside the `repo-path` except the configuration file.  You would lose your logs, though.

**Comment by pritammobisoft** [comment]
Great to know. Thanks!
