### ISSUE TITLE
Can't locate JSON/PP.pm in @INC 

### ISSUE THREAD

**Issue by seadba** [pgbackrest/pgbackrest#492]
Hi, ive been running verious 1.x versions of pgbackrest successfully on RH7 for several 9x versions of postgres - both standard and edb - i have a new rh7 server running edb 10.3 - i installed V2 pgbackrest - all compiled sucessfully - i have several JSON/PP.pm modules installed 
./root/perl5/lib/perl5/JSON/PP.pm
./opt/edb/languagepack-9.6/Perl-5.20/lib/JSON/PP.pm
./opt/edb/languagepack-10/Perl-5.24/lib/JSON/PP.pm

these directories are all accessable to postgres user - if i set the first in $PERL5LIB i get 
Can't locate JSON/PP.pm in @INC (@INC contains: /root/perl5/lib/perl5/JSON /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/perl5/pgBackRest/Config/Config.pm line 13.

if i set the edb in $PERL5LIB i get - 
pgbackrest: symbol lookup error: /opt/edb/languagepack-10/Perl-5.24/lib/auto/Tie/Hash/NamedCapture/NamedCapture.so: undefined symbol: Perl_xs_handshake

i realize that this is not pgbackrest issue so dont spend any time on it - i can close the issue and try to run pgbackrest from remote box where its working -  i just cant figure out where the issue is thanks

**Comment by dwsteele** [comment]
You'd actually need to set the path to `/root/perl5/lib/perl5`.  Perl expects the package name `JSON` to be in the specified path.

**Comment by seadba** [comment]
thanks for the fast update - i think i have gotten past the pm issues - now i get the following

ERROR [124]: : process terminated due to an unhandled exception:
Exiting subroutine via next at /usr/share/perl5/pgBackRest/Common/Lock.pm line 103.


2018-03-02 19:06:34.843 P00   INFO: stanza-create command end: aborted with exception [124]
2018-03-02 19:06:34.844 P00  DEBUG:     Common::Lock::lockRelease(): bFailOnNoLock = false
2018-03-02 19:06:34.844 P00  DEBUG:     Common::Exit::exitSafe=>: iExitCode = 124

**Comment by dwsteele** [comment]
This is a terrible error (which we will look at), but the root cause is that the lock file cannot be opened.  Are you setting `lock-path` explicitly?  Is `/tmp/pgbackrest` owned by another user?

**Comment by seadba** [comment]
yes i was trying to get around the json error with another user in the postgres group - the initial issue was json was installed under root - postgres couldnt access/find the pm - in addition, edb creates $HOME for postgres in software dir - postgres user has no write access there - i created a new user in postgres group, installed json under that user, but user cannot access pg_global -  i think its probably best to figure out the json issue then to bother you further with whats not a pgbackrest problem - thanks for the help and sorry for the hassle -

**Comment by seadba** [comment]
thanks again - its running - had to open access to json - great product - thanks again

-bash-4.2$ pgbackrest --stanza=btpg10 --log-level-console=info check
2018-03-05 09:34:06.792 P00   INFO: check command begin 2.00: --log-level-console=info --pg1-path=/opt/PostgreSQL/10/data --pg1-port=5432 --repo1-path=/instance1/postgres/10/backup --stanza=btpg10
2018-03-05 09:34:09.349 P00   INFO: WAL segment 000000010000000000000024 successfully stored in the archive at '/instance1/postgres/10/backup/archive/btpg10/10-1/0000000100000000/000000010000000000000024-d19a5662153cee1903a3609c7d22e890146ab6cc.gz'
2018-03-05 09:34:09.350 P00   INFO: check command end: completed successfully
-bash-4.2$

**Comment by dwsteele** [comment]
You are welcome!

**Comment by spavan27** [comment]
Hello All,

I am getting similar problem reported by "seadba" . kindly help me with  the solution

2019-05-24 15:36:05.105 P00   INFO: stanza-create command begin 2.14: --log-level-console=info --log-level-file=detail --log-path=/oratrace/pg_alert_log --pg1-path=/oradbaudit/pg_data_dir --repo1-path=/orabackup/WORM/PGBACKUP/visa-demo-5400 --stanza=visa-demo
Can't locate JSON/PP.pm in @INC (@INC contains: CODE(0x1fb77c8) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /loader/0x1fb77c8/pgBackRest/Config/Config.pm line 13.
BEGIN failed--compilation aborted at /loader/0x1fb77c8/pgBackRest/Config/Config.pm line 13.
Compilation failed in require at /loader/0x1fb77c8/pgBackRest/Common/Lock.pm line 19.
BEGIN failed--compilation aborted at /loader/0x1fb77c8/pgBackRest/Common/Lock.pm line 19.
Compilation failed in require at /loader/0x1fb77c8/pgBackRest/Main.pm line 17.
BEGIN failed--compilation aborted at /loader/0x1fb77c8/pgBackRest/Main.pm line 17.
Compilation failed in require at (eval 3) line 1.
BEGIN failed--compilation aborted at (eval 3) line 1.

**Comment by dwsteele** [comment]
Did you follow the installation instructions? https://pgbackrest.org/user-guide-centos7.html#installation
