### ISSUE TITLE
Question: Backup Archived wal logs

### ISSUE THREAD

**Issue by brunre01** [pgbackrest/pgbackrest#493]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.0

2. PostgreSQL version: 9.6.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHAT 7.2

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

pgbackrest.conf

[global]
repo-path=/BACKUP1/lhrrhenppp001
retention-diff=3
retention-full=3
retention-archive=1
start-fast=y
process-max=6

[NPP_lhrrhenppp001]
db-path=/DATA/data

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

postgresql.conf
wal_level = replica
archive_mode = on
archive_command = 'pgbackrest --stanza=NPP_lhrrhenppp001 archive-push %p'
max_wal_senders = 6

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I have a space problem with the number of archived wal logs being created. Is it possible to back up archived wal logs only using pgbackrest? If so how would I go about doing this as the backup type options are only full,diff and incr?  

Thank you in advance

**Comment by dwsteele** [comment]
It's possible to archive only WAL using the `archive_command`, but expiration is tied to backups so they would accumulate forever in the repository.

We considered implementing archive-only expiration, but honestly this is the first time it has ever come up.  Without backups, WAL have limited usefulness.

Why not create backups as well?  If you are worried about space, store them in S3.  pgBackRest supports S3 storage (and encryption) natively.

**Comment by brunre01** [comment]
thank you for your response. are there any plans to implement archive-only expiration in a future release? In our case its not practical to run a full backup every time our archive destination reaches a threshold.  the cluster  size is many terrabytes

**Comment by dwsteele** [comment]
This feature is not a priority at this time.  That may change in the future, but for now we consider it to be an edge case.  There are many features with broader applicability that are higher priority.

**Comment by brunre01** [comment]
Thank you.
