### ISSUE TITLE
pgbackrest full backup failed 

### ISSUE THREAD

**Issue by brunre01** [pgbackrest/pgbackrest#495]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.0

2. PostgreSQL version: 9.6.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHAT 7.2

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_mode = on               
archive_command = 'pgbackrest --stanza=NPP_lhrrhenppp001 archive-push %p'
listen_addresses = '*'
port = 5432
max_wal_senders = 6
wal_level = replica
[log_files.zip](https://github.com/pgbackrest/pgbackrest/files/1786383/log_files.zip)

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Backup failed with following error

ERROR [059]: : statement timed out after 1800.001 second(s):
select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, labelfile, case when length(trim(both '\t\n ' from spcmapfile)) = 0 then null else spcmapfile end as spcmapfile from pg_stop_backup(false) as lsn

**Comment by dwsteele** [comment]
Looks like your archive command is failing.  Check your Postgres log for the errors.

**Comment by dwsteele** [comment]
Closing this issue since it has been idle.  Did you find an issue with the archive command?

**Comment by brunre01** [comment]
the archive  command was fine.  It appears that somehow the stanza was corrupted after i tried recreating. I removed the pgbackrest package from the system, reinstalled  created the stanza and the backup worked fine.

**Comment by dwsteele** [comment]
Hmmm - did you install manually at some point, or have you been using packages the entire time?

**Comment by brunre01** [comment]
my first pgbackrest installation was manual and then i updated it through the yum repository

**Comment by dwsteele** [comment]
OK -- if you have any other systems where you need to do this I would recommend doing a manual uninstall before installing the package.  You can find the instructions at: https://pgbackrest.org/user-guide.html#installation

Glad you got it working!
