### ISSUE TITLE
some options do not exist anymore

### ISSUE THREAD

**Issue by edib** [pgbackrest/pgbackrest#498]
1. pgBackRest version:
2.0
7. Describe the issue:
Before 2.0 I could restore a stanza to local dir of backup server for some purposes by below command.
`pgbackrest --stanza=mystanza --no-config --repo-path=/var/lib/pgbackrest --db-path=/mypath/data --log-level-console=info restore`
With 2.0, some parameters has been changed, db-path became pg-path etc. But it seems there is parameter like "no-config" and command says "--pg-path" is invalid option.
What am I doing wrong?

**Comment by dwsteele** [comment]
Can you provide output?

There is no `pg-path` option, if you are using the new names you must use `pg1-path`.   You can still use `db-path`, `db1-path`, etc. from v1, of course.

The reason there was a `db-path` option is because it existed before multiple clusters could be configured.  It was left in for compatibility, but not continued into the new naming convention.

**Comment by edib** [comment]
my command is this:
pgbackrest --stanza=mystanza --no-config --repo-path=/data/pgbackrest/
--pg1-path=/data/restore/restore20180308/data --log-level-console=info
restore

return output is:

ASSERT [025]: : , or } expected while parsing object/hash, at character
offset 177 (before ""negate":true},"db-i...") at
/usr/share/perl5/vendor_perl/pgBackRest/Config/Config.pm line 105.
 at /usr/share/perl5/vendor_perl/pgBackRest/Main.pm line 15.
pgBackRest::Main::__ANON__(', or } expected while parsing object/hash, at
character offse...') called at /usr/share/perl5/vendor_perl/Carp.pm line 100
Carp::croak(', or } expected while parsing object/hash, at character
offse...') called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 1213
JSON::PP::decode_error(', or } expected while parsing object/hash') called
at /usr/share/perl5/vendor_perl/JSON/PP.pm line 1004
JSON::PP::object() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line
724
JSON::PP::value() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 969
JSON::PP::object() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line
724
JSON::PP::value() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 688
JSON::PP::PP_decode_json('JSON::PP=HASH(0x9322e8)',
'{"buffer-size":{"value":4194304},"cmd-ssh":{"value":"ssh"},"c...', 0)
called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 148
JSON::PP::decode('JSON::PP=HASH(0x9322e8)',
'{"buffer-size":{"value":4194304},"cmd-ssh":{"value":"ssh"},"c...') called
at /usr/share/perl5/vendor_perl/pgBackRest/Config/Config.pm line 105
eval {...} called at
/usr/share/perl5/vendor_perl/pgBackRest/Config/Config.pm line 109
pgBackRest::Config::Config::configLoad(undef, 'pgbackrest', 'restore',
'{"buffer-size":{"value":4194304},"cmd-ssh":{"value":"ssh"},"c...') called
at /usr/share/perl5/vendor_perl/pgBackRest/Main.pm line 45
eval {...} called at /usr/share/perl5/vendor_perl/pgBackRest/Main.pm line
306
pgBackRest::Main::main('pgbackrest', 'restore',
'{"buffer-size":{"value":4194304},"cmd-ssh":{"value":"ssh"},"c...') called
at (eval 76) line 1
eval
'pgBackRest::Main::main(\'pgbackrest\',\'restore\',\'{"buffer-size":{"value":4194304},"cmd-ssh":{"value":"ssh"},"compress":{"value":true},"compress-level":{"value":6},"compress-level-network":{"value":3},"config":{"source":"param""negate":true},"db-include":{},"delta":{"value":false},"force":{"value":false},"link-all":{"value":false},"link-map":{},"lock-path":{"value":"/tmp/pgbackrest"},"log-level-console":{"source":"param","value":"info"},"log-level-file":{"value":"info"},"log-level-stderr":{"value":"warn"},"log-path":{"value":"/var/log/pgbackrest"},"log-timestamp":{"value":true},"neutral-umask":{"value":true},"perl-option":{},"pg1-host":{},"pg2-host":{},"pg3-host":{},"pg4-host":{},"pg5-host":{},"pg6-host":{},"pg7-host":{},"pg8-host":{},"pg1-path":{"source":"param","value":"/data/restore/restore20180308/data"},"pg2-path":{},"pg3-path":{},"pg4-path":{},"pg5-path":{},"pg6-path":{},"pg7-path":{},"pg8-path":{},"process-max":{"value":1},"protocol-timeout":{"value":1830},"recovery-option":{},"repo1-cipher-pass":{},"repo1-cipher-type":{"value":"none"},"repo1-host":{},"repo1-host-cmd":{},"repo1-host-config":{},"repo1-host-port":{},"repo1-host-user":{},"repo1-path":{"source":"param","value":"/data/pgbackrest/"},"repo1-s3-bucket":{},"repo1-s3-ca-file":{},"repo1-s3-ca-path":{},"repo1-s3-endpoint":{},"repo1-s3-host":{},"repo1-s3-key":{},"repo1-s3-key-secret":{},"repo1-s3-region":{},"repo1-s3-verify-ssl":{},"repo1-type":{"value":"posix"},"set":{"value":"latest"},"stanza":{"source":"param","value":"mystanza"},"tablespace-map":{},"tablespace-map-all":{},"target":{},"target-action":{},"target-exclusive":{},"target-timeline":{},"type":{"value":"default"}}\')
;' called at (eval 76) line 0
:
{"buffer-size":{"value":4194304},"cmd-ssh":{"value":"ssh"},"compress":{"value":true},"compress-level":{"value":6},"compress-level-network":{"value":3},"config":{"source":"param""negate":true},"db-include":{},"delta":{"value":false},"force":{"value":false},"link-all":{"value":false},"link-map":{},"lock-path":{"value":"/tmp/pgbackrest"},"log-level-console":{"source":"param","value":"info"},"log-level-file":{"value":"info"},"log-level-stderr":{"value":"warn"},"log-path":{"value":"/var/log/pgbackrest"},"log-timestamp":{"value":true},"neutral-umask":{"value":true},"perl-option":{},"pg1-host":{},"pg2-host":{},"pg3-host":{},"pg4-host":{},"pg5-host":{},"pg6-host":{},"pg7-host":{},"pg8-host":{},"pg1-path":{"source":"param","value":"/data/restore/restore20180308/data"},"pg2-path":{},"pg3-path":{},"pg4-path":{},"pg5-path":{},"pg6-path":{},"pg7-path":{},"pg8-path":{},"process-max":{"value":1},"protocol-timeout":{"value":1830},"recovery-option":{},"repo1-cipher-pass":{},"repo1-cipher-type":{"value":"none"},"repo1-host":{},"repo1-host-cmd":{},"repo1-host-config":{},"repo1-host-port":{},"repo1-host-user":{},"repo1-path":{"source":"param","value":"/data/pgbackrest/"},"repo1-s3-bucket":{},"repo1-s3-ca-file":{},"repo1-s3-ca-path":{},"repo1-s3-endpoint":{},"repo1-s3-host":{},"repo1-s3-key":{},"repo1-s3-key-secret":{},"repo1-s3-region":{},"repo1-s3-verify-ssl":{},"repo1-type":{"value":"posix"},"set":{"value":"latest"},"stanza":{"source":"param","value":"mystanza"},"tablespace-map":{},"tablespace-map-all":{},"target":{},"target-action":{},"target-exclusive":{},"target-timeline":{},"type":{"value":"default"}}



2018-03-08 16:39 GMT+03:00 David Steele <notifications@github.com>:

**Comment by dwsteele** [comment]
OK, I see what's going on here.  It's a formatting issue passing the parameters from C to Perl.

There are two workarounds:
1) Create a config file with your settings and load it using `--config`
2) Revert to 1.28

We'll fix this for 2.01.  There's another important fix in the pipeline so that should be soon.

**Comment by dwsteele** [comment]
This has been committed at 62a9bdbd4c25b9801bcc6a48.

It looks like the other bug was not as serious as I thought so it's not going to trigger a release.

**Comment by dwsteele** [comment]
You may also try the new --reset functionality in 2.0.  You can put --reset before any option and it will reset that option to default (even if the default is not defined).

Usually, it's `pg1-host` that needs to be reset, then other things can be overridden as needed.  This way, you don't have to re-specify repo1-path, etc.
