### ISSUE TITLE
ERROR [157]: unable to push WAL 00000001000000000000003D asynchronously after 60 second(s)

### ISSUE THREAD

**Issue by did16** [pgbackrest/pgbackrest#499]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 1.28

2. PostgreSQL version:
PostgreSQL 9.6.7
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS release 6.6 

4. Did you install pgBackRest from source or from a package?
PGDG rpm package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
N/A

7. Describe the issue:
I want to backup current wal files and I run the following commands 
find pg_wal/* -maxdepth 0 -type f -exec pgbackrest --stanza=pgaemtest-9.6 archive-push {} \;
ERROR [157]: unable to push WAL 00000001000000000000003D asynchronously after 60 second(s)
ERROR [157]: unable to push WAL 00000001000000000000003E asynchronously after 60 second(s)
ERROR [157]: unable to push WAL 00000001000000000000003F asynchronously after 60 second(s)
ERROR [157]: unable to push WAL 000000010000000000000040 asynchronously after 60 second(s)
ERROR [157]: unable to push WAL 000000010000000000000041 asynchronously after 60 second(s)
ERROR [157]: unable to push WAL 000000010000000000000042 asynchronously after 60 second(s)
ERROR [157]: unable to push WAL 000000010000000000000043 asynchronously after 60 second(s)
ERROR [157]: unable to push WAL 000000010000000000000044 asynchronously after 60 second(s)
ERROR [157]: unable to push WAL 000000010000000000000045 asynchronously after 60 second(s) 

I would like to solve this problem. What is the root cause of this issue ?

**Comment by dwsteele** [comment]
This is an **extremely** dangerous thing to do!

The archive command should be setup using the `archive_command` setting in `postgresql.conf`.  Postgres decides when WAL files should be archived.  PostgreSQL recycles old WAL files to be used in the future so you'll pollute you repository by running a command like this.

Following the examples in the [user guide](https://pgbackrest.org/user-guide.html) is a good place to start.

**Comment by dwsteele** [comment]
Closing this issue since it has been idle.
