### ISSUE TITLE
 error: unknown type name ‘sigjmp_buf’

### ISSUE THREAD

**Issue by seadba** [pgbackrest/pgbackrest#501]
Hello, installing V2 on RH7  (pg V9.5) - during the make src cmd i get the folowing error

[root@asydev3 ~]# make -C /root/pgbackrest-release-2.00/src
make: Entering directory `/root/pgbackrest-release-2.00/src'
gcc -I. -std=c99 -O2 -Wfatal-errors -Wall -Wextra -Wwrite-strings -Wno-clobbered `perl -MExtUtils::Embed -e ccopts`  -c perl/exec.c -o perl/exec.o
In file included from /usr/local/lib/perl5/5.26.1/x86_64-linux/CORE/perl.h:3923:0,
                 from perl/exec.c:30:
/usr/local/lib/perl5/5.26.1/x86_64-linux/CORE/cop.h:34:5: error: unknown type name ‘sigjmp_buf’
     Sigjmp_buf  je_buf;  /* uninit if je_prev is NULL */
     ^
compilation terminated due to -Wfatal-errors.
make: *** [perl/exec.o] Error 1
make: Leaving directory `/root/pgbackrest-release-2.00/src'
[root@asydev3 ~]#

thanks - all steps prior completed successfully - im running V2 on another RH 7 server with no issues - thanks again

**Comment by dwsteele** [comment]
Well, that's a new one:
```
unknown type name ‘sigjmp_buf’ Sigjmp_buf je_buf
```
Did you install `build-essentials`?

On the other had, you can get pgBackRest as a package from yum.postgresql.org.  I'd really recommend doing that if you are running RHEL 7.  Personally, I'm not a big fan of installing build tools on a production server.

**Comment by seadba** [comment]
thanks for the fast response - not sure about the build-essentials - one of the admin's may have - i didnt know it was available in yum - that works well, thanks - dont bother with this error - one last question, we set up a v11 cluster to start testing - will this version of pgbackrest work against that?  thanks again, great product, ran 3 restore/recoveries over the weekend  - worked perfectly

**Comment by dwsteele** [comment]
We haven't updated pgBackRest for v11 yet so it won't work.  We usually do the updates after the first beta releases in June/July, once we know that the catalog/control numbers are likely to be stable.

We may start a little earlier this year if our group permissions patch is accepted for v11.  We're eager to be able to do backups as a non-privileged user.

**Comment by dwsteele** [comment]
@seadba We have added PG11 support in master and it will be in the next release (no date planned for that yet).

**Comment by seadba** [comment]
excellent - thanks very much for the update - looking forward to it
