### ISSUE TITLE
typos in the user guide

### ISSUE THREAD

**Issue by hunleyd** [pgbackrest/pgbackrest#506]
Looking at the user guide, I see several instances of:
```
[demo]
pg1-path=/var/lib/postgresql/9.4/demo

[global]
repo1-path=/var/lib/pgbackrest
```

and I believe the '1' is errant and incorrect. That should be `pg-path` and `repo-path`, no?

**Comment by hunleyd** [comment]
Nope. PEBKAC error in understanding the new naming conventions. My bad. Thanks for the clarity on Slack, sfrost.

**Comment by dwsteele** [comment]
Yes, this is completely intentional.  When we introduced indexed options in v1 we had to make sure the old, non-indexed forms still worked.  No need for that in v2 since we have new option names.  All the v1 options still work, of course, and will until v3.
