### ISSUE TITLE
creating stanza fails with error

### ISSUE THREAD

**Issue by brunre01** [pgbackrest/pgbackrest#508]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.01

2. PostgreSQL version:  10.1.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Red Hat Enterprise Linux Server release 7.4 (Maipo)

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

[AOD_tparheposp001]
db-path=/pgDATA/data

[global]
repo-path=/pgBACKUP/tparheposp001
retention-full=14
retention-archive=14
process-max=10
start-fast=y

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Recieved error when trying to create a stanza

==> pgbackrest --stanza=AOD_tparheposp001 --log-level-console=info stanza-create --db-port=5444
2018-03-30 13:05:21.440 P00   INFO: stanza-create command begin 2.01: --log-level-console=info --pg1-path=/pgDATA/data --pg1-port=5444 --repo1-path=/pgBACKUP/tparheposp001 --stanza=AOD_tparheposp001
ERROR [124]: : process terminated due to an unhandled exception:
Exiting subroutine via next at /usr/share/perl5/vendor_perl/pgBackRest/Common/Lock.pm line 103.
at /usr/share/perl5/vendor_perl/pgBackRest/Main.pm line 15.
       pgBackRest::Main::__ANON__('Exiting subroutine via next at /usr/share/perl5/vendor_perl/p...') called at /usr/share/perl5/vendor_perl/pgBackRest/Common/Lock.pm line 103
       pgBackRest::Common::Lock::lockAcquire('stanza-create') called at /usr/share/perl5/vendor_perl/pgBackRest/Main.pm line 223
       eval {...} called at /usr/share/perl5/vendor_perl/pgBackRest/Main.pm line 321
       pgBackRest::Main::main('pgbackrest', 'stanza-create') called at (eval 77) line 1
       eval 'pgBackRest::Main::main(\'pgbackrest\',\'stanza-create\')
;' called at (eval 77) line 0

2018-03-30 13:05:21.683 P00   INFO: stanza-create command end: aborted with exception [124]

**Comment by dwsteele** [comment]
It looks the the user running pgbackrest (usually postgres) does not have permissions to write into the `/tmp/pgbackrest` directory.

This is a terrible message, though.  We are already working on improving this for 2.02.

**Comment by brunre01** [comment]
thank you

that seemed to work
