### ISSUE TITLE
remote backup use archive-copy=y and --type=diff ，fail with error？

### ISSUE THREAD

**Issue by yummyliu** [pgbackrest/pgbackrest#509]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
 2.01
2. PostgreSQL version:
10.2
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
database server: CentOS Linux release 7.2.1511 (Core)
repository host server: CentOS Linux release 7.2.1511 (Core)
4. Did you install pgBackRest from source or from a package?
yum install...
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
repo-path=/var/backups
retention-full=2
retention-diff=2
retention-archive=2
stop-auto=y
#archive-copy=y
start-fast=y
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

    - errors in the postgresql log file before or during the time you experienced the issue

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
ERROR [073]: : unable to open '/var/backups/backup/putong/20180402-142926F_20180402-143349D/pg_data/pg_wal/0000000100000000000000CF.gz': No such file or directory

**Comment by yummyliu** [comment]
when delete archive-copy=y in conf file, noerror。。。

**Comment by dwsteele** [comment]
This appears to be a very long-standing bug in archive-copy.  I was trying to figure out how it could escape detection so long and realized that this usage of `archive-copy` is not very functional.

`archive-copy` is generally used to make a backup directory look complete (including WAL) to PostgreSQL so it is easy to copy around.  A differential backup is not complete and so you can't do this without combining it with the previous full backup (which I don't recommend doing manually).

It would be best to either 1) use `archive-copy` only with the full backups or 2) use the `hardlink` option to make the differential backups look like full backups (the links keep it from using up more space).  The combination of `hardlink` and `archive-copy` should work fine for differentials.

We'll also fix this bug for 2.02, of course.  How would you like your name to appear in the release notes?

**Comment by dwsteele** [comment]
Fix committed at 8dbbf2de929813.

**Comment by yummyliu** [comment]
thank you , it's my pleasure to have my name on release-note...
