### ISSUE TITLE
automatically switch to --type=full if the last full is over N days old

### ISSUE THREAD

**Issue by hunleyd** [pgbackrest/pgbackrest#511]
It would be swell to have a config option to automatically switch from the default incremental mode to full mode when the last full is older than N days old. This would make cron scripting easier as the invocation would always be the same and would have to do its own data math. You'd simply call 'pgbackrest backup' and it would determine if an incremental or full is needed on its own.

**Comment by dwsteele** [comment]
We are been planning to do time-based retention and this would be a part of that.  I don't have a good idea of when we might be able to get to this.  It's basically a case of too many features and too little time.

**Comment by dwsteele** [comment]
Closing this since we won't be looking at it immediately.  As mentioned above, time-based retention is in the plans and is recorded on the feature board here: https://github.com/pgbackrest/pgbackrest/projects/2#card-8956827.
