### ISSUE TITLE
pgbackrest help restore - ERROR: [029]: unable to force KeyValue to String

### ISSUE THREAD

**Issue by clad** [pgbackrest/pgbackrest#514]
pgBackRest 2.01, postgres 9.6.8, Linux (centos)  4.11.3-1.el7.elrepo.x86_64

Error with - 
 pgbackrest help restore
2018-04-13 10:06:30.804 P00   INFO: restore command begin 2.01: --buffer-size=8388608 --compress --compress-level=3 --log-level-console=info --log-level-file=info --process-max=6 --recovery-option=standby_mode=on --repo1-type=posix
ERROR: [029]: unable to force KeyValue to String
2018-04-13 10:06:30.805 P00   INFO: restore command end: aborted with exception [029]

Happens with following pgbackrest.conf -
[global]
log-level-file=info
log-level-console=info
compress=y
compress-level=3
process-max=6
repo-type=posix
buffer-size=8388608
start-fast=y
recovery-option=standby_mode=on

[main]
pg1-path=/var/lib/pgsql/9.6/data

Commenting out "recovery-option=standby_mode=on" or moving it to [main] gets past the error.

**Comment by dwsteele** [comment]
Does it work in `[main]`, or is it ignored?

**Comment by clad** [comment]
It does work in [main], i.e. it will be used in a 'pgbackrest restore' command, and the 'pgbackrest help restore' works as well.

**Comment by dwsteele** [comment]
Ah, this is just the help?

**Comment by clad** [comment]
Yes, just  the 'help restore' command. Other help commands work fine.

**Comment by clad** [comment]
Happens on 2.00 as well, fwiw.

**Comment by dwsteele** [comment]
Yeah, I think I see what's going on here.  Just the be clear, the actual restore command works, but the restore help is broken.

**Comment by dwsteele** [comment]
Fix committed at fd1984239e5d602.  It wasn't a bug so much as code that was completely missing.

Thanks for the report!
