### ISSUE TITLE
pgBackRest as deployment handler

### ISSUE THREAD

**Issue by Raphyyy** [pgbackrest/pgbackrest#515]
Hello and thanks for your work :) 

I am sorry to post this here as it's not an issue but a quick question and I couldn't find any answer on Google.

I am looking for a deployment solution for my PostgreSQL cluster.
Here is the plan : 
- I will have pgBackRest on a remote host that will perform remote backup from the master PostgreSQL daily.
- What I want is the ability to "deploy" a new instance from this backup using the restore function (once PostgreSQL is set up on the new instance of course)

I could use basebackup feature from PostgreSQL but the idea is to deploy new instance if the master goes down. 

Could you tell me if the restore function could make it without problem ?

Thanks

**Comment by uspen** [comment]
Yes, I did so a hundred times

**Comment by uspen** [comment]
Example:

`su - postgres -c "pgbackrest --backup-host=${backup_host} --config=${backup_local_config} --repo-path=${backup_remote_repo} --stanza=${FROM} --delta --db-path=${pg_dir}/${TO} --recovery-option='recovery_target_action=shutdown' --recovery-option='recovery_target=immediate' restore"`

**Comment by Raphyyy** [comment]
Thanks ! There is no any particular indications to perform a restore on a new remote host ?

**Comment by uspen** [comment]
Check config. e.g. archive_command (new stanza)

**Comment by dwsteele** [comment]
This is one of the primary purposes of pgBackRest.  Building a new server from backups is faster and puts less load on the primary than pg_basebackup.  Following the steps in https://pgbackrest.org/user-guide.html#replication/hot-standby will generally work, though every situation is different so some customization may be needed.
