### ISSUE TITLE
multiple backup locations

### ISSUE THREAD

**Issue by brunre01** [pgbackrest/pgbackrest#516]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.01

2. PostgreSQL version:  v10.3-2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Redhat 7

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

[CDAR_dayrhepgsp006]
db-path=/pgDATA/data

[global]
process-max=8
repo-path=/pgBACKUP/dayrhepgsp006
retention-full=7
retention-archive=7
start-fast=y

7. Describe the issue:

I have 2 mount points. 
/pgBACKUP
/pgBACKUP1

Is it possible to span the pgbackrest repository across multiple mount points?  i want to backup databases to /pgBACKUP and the archived wal files to another /pgBACkUP2? If so what will my /etc/pgbackrest.conf look like?

**Comment by dwsteele** [comment]
There's no way to do this with configuration, but you can use symlinks or create the mounts where you need them in the repo.

For instance, if your repo-path was `/repo`, you could create a mounts at `/repo/archive` and `/repo/backup` to store your archives and backups on different file systems.
