### ISSUE TITLE
doc bug for pgbackrest help backup

### ISSUE THREAD

**Issue by clad** [pgbackrest/pgbackrest#517]
pgbackrest 2.01

Output of "pgbackrest help backup" shows a --resume option, that should be --no-resume

**Comment by dwsteele** [comment]
The option name is `resume`, `--no-resume` is the way to negate it.  All boolean options can be negated.  If `resume=n` is set in `pgbackrest.conf` you can enable resume again with `--resume`.

**Comment by clad** [comment]
Thanks for the clarification. I had missed the difference between the command line and conf for the boolean options.
