### ISSUE TITLE
ERROR [070]: : link /var/lib/postgresql/9.4/main/pg_ident.conf (/etc/postgresql/9.4/main) references a subdirectory of or the same directory as link

### ISSUE THREAD

**Issue by vitabaks** [pgbackrest/pgbackrest#522]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.01

2. PostgreSQL version:
9.4.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Debian GNU/Linux 8
Linux CAS-5-EU-206 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

4. Did you install pgBackRest from source or from a package?
dpkg -i pgbackrest_2.01-1.pgdg80+1_amd64.deb

5. Please attach the following as applicable:

postgresql.conf:
archive_mode = on
archive_command = 'pgbackrest --stanza=main archive-push %p'
archive_timeout = 60
wal_level = hot_standby
max_wal_senders = 5
listen_addresses = '*'
port = 5432

pgbackrest.conf:
[global]
repo1-path=/pgdata/pgbackrest
repo1-retention-full=2
start-fast=y
archive-check=y
archive-copy=n
stop-auto=y
resume=n
compress=y
compress-level=6
process-max=1
log-level-console=info
log-level-file=detail
**link-all=y**

[main]
pg1-path=/var/lib/postgresql/9.4/main

7. Describe the issue:
I created symbolic links to the configuration files so that they are included in the backup.

ln -s /etc/postgresql/9.4/main/postgresql.conf /var/lib/postgresql/9.4/main/postgresql.conf
ln -s /etc/postgresql/9.4/main/pg_hba.conf /var/lib/postgresql/9.4/main/pg_hba.conf
ln -s /etc/postgresql/9.4/main/pg_ident.conf /var/lib/postgresql/9.4/main/pg_ident.conf

pgbackrest --stanza=main --type=full backup --process-max=2

2018-04-28 17:32:34.923 P00   INFO: backup command begin 2.01: --archive-check --no-archive-copy --compress --compress-level=6 --log-level-console=info --log-level-file=detail --pg1-path=/var/lib/postgresql/9.4/main --process-max=2 --repo1-path=/pgdata/pgbackrest --repo1-retention-full=2 --no-resume --stanza=main --start-fast --stop-auto --type=full
WARN: the cluster is already in backup mode but no pgBackRest backup process is running. pg_stop_backup() will be called so a new backup can be started.
2018-04-28 17:32:36.353 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2018-04-28 17:32:38.460 P00   INFO: execute exclusive pg_start_backup() with label "pgBackRest backup started at 2018-04-28 17:32:35": backup begins after the requested immediate checkpoint completes
2018-04-28 17:32:38.762 P00   INFO: backup start archive = 0000000A000000BF000000DC, lsn = BF/DC0000C8
**ERROR [070]: : link /var/lib/postgresql/9.4/main/pg_ident.conf (/etc/postgresql/9.4/main) references a subdirectory of or the same directory as link /var/lib/postgresql/9.4/main/pg_hba.conf (/etc/postgresql/9.4/main)**
2018-04-28 17:32:40.067 P00   INFO: backup command end: aborted with exception [070]

**Comment by dwsteele** [comment]
Yeah, that was basically a bug -- the paths should not be be compared for files.  Unless a path link and a file link share the same path, in which case it still errors.  Fix committed at 5e090ba30501b76717.

Thanks for the report!  Keep in mind that you may have problems on restore because the conf files in /etc are generally owned by root and postgres won't be able to overwrite them if they need to be changed.  You could always run the restore as root but I don't really recommend that.
