### ISSUE TITLE
Doc : [global:archive-push]

### ISSUE THREAD

**Issue by Krysztophe** [pgbackrest/pgbackrest#523]
When reading https://pgbackrest.org/configuration.html and https://pgbackrest.org/user-guide.html, I can't find a definition of the [global:archive-push] syntax, just two examples hidden rather deep that can be easily missed.
I suggest to add a line or two in 5.4 about it.

Without a colleague, I would not have found that the following could reduce the compression level for archives only, and not for a full backup - at least we suppose.
```
[global:archive-push]
compress-level=1
```

**Comment by cmwshang** [comment]
Those are the only variations: [global] and [global:cmd] where cmd is the command.

Cynthia Shang
www.crunchydata.com

**Comment by MichaelDBA** [comment]
so cmd can be any valid parameter in addition to the **archive-push** one noted in this issue?

**Comment by Krysztophe** [comment]
This small hint would have been a good clue, yes. Perhaps add a line on the precedence (I suppose that [global:cmd] overrides [global], right?) and a small example (as the different compress-level for wals archiving?)

**Comment by dwsteele** [comment]
@Krysztophe How does this e0b5bd74f331 look?

Also, how would you like your name to appear in the release notes?

**Comment by dwsteele** [comment]
Committed at 9d9fad88a25b0f4bafcae1f2e9b.  Thank you for the suggestion!
