### ISSUE TITLE
mini resetting backup 

### ISSUE THREAD

**Issue by edib** [pgbackrest/pgbackrest#524]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.01
2. PostgreSQL version:
9.6.8
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
centos 7.3
4. Did you install pgBackRest from source or from a package?
no
7. Describe the issue:
something bad happened and master did not send wals to pgbackrest repo server. So we had to cut the archive command for a while to save the master's disk. But now giving up for some ours, we want to reestablish the backup procedure but when we run the config naturally log says some wal files are missing. I need to do now if it is possible, take incremental backup and start wal archiving after that.
Is it possible?

**Comment by dwsteele** [comment]
There's really no point in taking a backup without WAL archiving -- it won't be any good.

You'll need to be more specific about what you are doing.  What command are you running?  What's the error?  What do you configs look like?

**Comment by edib** [comment]
For one hour period to save the masters disk, we drop the archive command to "/bin/true".  At that time period, naturally wals were recycled. when put the old archive command back
`archive_command = 'pgbackrest --stanza=myst1 archive-push %p'`
and I have checked the config then produced below.
`pgbackrest --stanza=myst1 --log-level-console=info check
2018-04-30 22:46:54.689 P00   INFO: check command begin 2.01: --log-level-console=info --log-level-file=detail --pg1-host=pgmaster --pg1-host-user=postgres --pg1-path=/db/data --pg1-port=5432 --repo1-path=/data/pgbackrest --stanza=myst1
ERROR [082]: : could not find WAL segment 000000010000078B000000CF after 60 second(s)
ERROR [082]: : could not find WAL segment 000000010000078B000000CF after 60 second(s)
WARN: WAL segment 000000010000078B000000CF did not reach the archive:9.6-1
HINT: Check the archive_command to ensure that all options are correct (especially --stanza).
HINT: Check the PostgreSQL server log for errors.
2018-04-30 22:48:11.423 P00   INFO: check command end: completed successfully`

**Comment by dwsteele** [comment]
It looks like you haven't fixed the issue that caused WAL archiving to fail in the first place.  Have you looked in the postgresql log for errors?
