### ISSUE TITLE
Configuration question for archive-get command with backup-standby

### ISSUE THREAD

**Issue by clad** [pgbackrest/pgbackrest#525]
pgbackrest 2.01

A question on configuration with backup on standby and multiple pg#-hosts, as it looks like I have something incorrect and am getting errors in logs for archive-get command on db-server-102 - "ERROR [072]: : archive-get operation must run on db host"

I can do backups from a standby, and have edited the pgbackrest.conf for that -

db-server-102's pgbackrest.conf
[global]
log-level-file=info
log-level-stderr=warn
log-level-console=info
log-path=/var/lib/pgsql_wal/pgbackrest.log
repo1-retention-full=2
repo1-retention-archive=2
backup-standby=y
compress=y
compress-level=3
process-max=6
repo-type=posix
#buffer-size=8388608
repo-path=/mnt/nfs/backups/db_backups/db-101/pgbackrest
start-fast=y
recovery-option=standby_mode=on

[main]
#db-path=/var/lib/pgsql/9.6/data
pg1-path=/var/lib/pgsql/9.6/data
pg2-path=/var/lib/pgsql/9.6/data
pg1-host=db-server-101
pg2-host=db-server-102
pg1-host-user=postgres
pg2-host-user=postgres

 The standby host db-server-102 restore command is
restore_command = 'pgbackrest --stanza=main archive-get %f "%p"'

log output ->
2018-05-02 11:57:14.086 P00   INFO: archive-get command end: aborted with exception [072]
2018-05-02 11:57:14.435 P00   INFO: archive-get command begin 2.01: --compress --compress-level=3 --log-level-console=info --log-level-file=info --log-level-stderr=warn --log-path=/var/lib/pgsql_wal/pgbackrest.log --pg1-host=db-server-101 --pg2-host=db-server-102 --pg1-path=/var/lib/pgsql/9.6/data --pg2-path=/var/lib/pgsql/9.6/data --repo1-path=/mnt/nfs/backups/db_backups/db-101/pgbackrest --rep
o1-type=posix --stanza=main
ERROR [072]: : archive-get operation must run on db host
2018-05-02 11:57:14.720 P00   INFO: archive-get command end: aborted with exception [072]

I have worked around the issue by having the restore_command use an alternative config that has [main] stripped of all but pg1-path.

**Comment by dwsteele** [comment]
The way you've configured this host it thinks it's a backup server since no db is configured as being local.  `[main]` should look like:
```
[main]
pg1-path=/var/lib/pgsql/9.6/data
pg2-host=db-server-101
pg2-path=/var/lib/pgsql/9.6/data
```
The local database is always assumed to be `pg1`.  We are working on a way to indicate locality, but for now that's the deal.

So yeah, the config is not symmetric but that's the downside of using a single server as both backup host and database host.
