### ISSUE TITLE
stanza-create command end: aborted with exception [025]

### ISSUE THREAD

**Issue by vitabaks** [pgbackrest/pgbackrest#528]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.01

2. PostgreSQL version:
9.4.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Debian GNU/Linux 8
3.16.0-4-amd64

4. Did you install pgBackRest from source or from a package?
dpkg -i pgbackrest_2.01-1.pgdg80+1_amd64.deb

5. Please attach the following as applicable:

postgresql.conf:
archive_mode = on
archive_command = 'pgbackrest --stanza=main archive-push %p'
archive_timeout = 600
wal_level = hot_standby
max_wal_senders = 5
listen_addresses = '*'
port = 5432

pgbackrest.conf:
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=3
start-fast=y
archive-check=y
archive-copy=n
stop-auto=y
resume=n
compress=y
compress-level=6
process-max=2
log-level-console=info
log-level-file=detail
link-all=y

[main]
pg1-path=/var/lib/postgresql/9.4/main
recovery-option=pause_at_recovery_target=false

7. Describe the issue:

 pgbackrest --stanza=main --log-level-console=info stanza-create
2018-05-08 13:38:02.150 P00   INFO: stanza-create command begin 2.01: --compress-level=6 --log-level-console=info --log-level-file=detail --pg1-path=/var/lib/postgresql/9.4/main --repo1-path=/var/lib/pgbackrest --stanza=main
ASSERT: [025]: option id 139 invalid - must be >= 0 and < 139
2018-05-08 13:38:02.294 P00   INFO: **stanza-create command end: aborted with exception [025]**

**Comment by dwsteele** [comment]
That definitely should not happen.  Can you check the file log and see if there is any more information?

Also, please run with `--log-level-console=debug` and attach the output.

**Comment by dwsteele** [comment]
Also, can you update to 2.02?  There have been a lot of changes since 2.01 and I would like to do the debugging on the newer code base.  I don't see any reason why 2.02 would have fixed this issue, but we moved a lot of stuff around so we might get some clues.

**Comment by vitabaks** [comment]
I could not successfully install version 2.02 from the sources... ([make_from_source-Error1.txt](https://github.com/pgbackrest/pgbackrest/files/1983741/make_from_source-Error1.txt)), so I installed v.2.01 from package.


pgbackrest --stanza=main --log-level-console=**debug** stanza-create
2018-05-08 14:37:03.253 P00   INFO: stanza-create command begin 2.01: --compress-level=6 --log-level-console=debug --log-level-file=detail --pg1-path=/var/lib/postgresql/9.4/main --repo1-path=/var/lib/pgbackrest --stanza=main
ASSERT: [025]: option id 139 invalid - must be >= 0 and < 139
2018-05-08 14:37:03.401 P00   INFO: stanza-create command end: aborted with exception [025]

**Comment by dwsteele** [comment]
Perhaps you need to do an `apt-get update`?  The new pgbackrest packages were just released on `apt.postgresql.org` yesterday.

**Comment by vitabaks** [comment]
pgbackrest_2.02-1.pgdg80+1_amd64.deb requires perl >= 5.20.2-3+deb8**u10**.
On this server we must use the version 5.20.2-3+deb8**u1** ...

Maybe I should try again to install v.2.0**2** from the source?

**Comment by dwsteele** [comment]
I would not recommend installing from source.  I think you'll need to update your Perl at some point anyway since it contains fixes for security issues.  I don't control the Perl version -- that's set by Debian.

It's good info that this error is also happening for archive-push.  That gives me a little more to work with.

**Comment by vitabaks** [comment]
pgbackrest --no-config --stanza=main --pg1-path=/var/lib/postgresql/9.4/main --log-level-console=debug stanza-create
2018-05-08 16:36:53.223 P00   INFO: stanza-create command begin 2.01: --no-config --log-level-console=debug --pg1-path=/var/lib/postgresql/9.4/main --stanza=main
ASSERT: [025]: option id 139 invalid - must be >= 0 and < 139
2018-05-08 16:36:53.396 P00   INFO: stanza-create command end: aborted with exception [025]

**Comment by vitabaks** [comment]
and...

**pgbackrest stop**
2018-05-08 17:12:20.524 P00   INFO: stop command begin 2.01: --log-level-console=info --log-level-file=detail --repo1-path=/var/lib/pgbackrest
ASSERT: [025]: option id 139 invalid - must be >= 0 and < 139
2018-05-08 17:12:20.708 P00   INFO: stop command end: aborted with exception [025]

**pgbackrest start**
INFO: start command begin 2.01: --log-level-console=info --log-level-file=detail --repo1-path=/var/lib/pgbackrest
ASSERT: [025]: option id 139 invalid - must be >= 0 and < 139
2018-05-08 17:12:27.248 P00   INFO: start command end: aborted with exception [025]

**Comment by dwsteele** [comment]
I built a Debian system and installed both 2.01 and 2.02 from apt.p.o and I can't reproduce this error.

I'm wondering if you somehow have mixed versions.  A lot of options were added in 2.02 so if you had a 2.02 exe and 2.01 libc maybe we'd see something like this.

Can you run:
```
pgbackrest version
```
That'll at least let us know what the main binary is.

**Comment by vitabaks** [comment]
`~$ pgbackrest version`
pgBackRest 2.01

**Comment by vitabaks** [comment]
I tried to completely remove:
```
dpkg --purge pgbackrest
dpkg --purge pgbackrest-doc
```
And reinstall the package

```
dpkg -i /tmp/pgbackrest_2.01-1.pgdg80+1_amd64.deb
dpkg -i /tmp/pgbackrest-doc_2.01-1.pgdg80+1_all.deb
```
But...
```
ASSERT: [025]: option id 139 invalid - must be >= 0 and < 139
2018-05-08 17:43:27.280 P00   INFO: start command end: aborted with exception [025]
```

**Comment by vitabaks** [comment]
> **I could not successfully install version 2.02 from the sources**... (make_from_source-Error1.txt), so I installed v.2.01 from package.

Maybe this is the cause of the problem?

**Comment by dwsteele** [comment]
A few more things:

1) Is the build above the only time you tried to install from source?  Any chance any of that got installed.

Are you really running Perl 5.20.2-3+deb8u1?  That's missing three years of updates.  Please run:
```
apt-cache show perl
```

3) Any chance there is a stray version of pgbackrest lying around?
```
find / -name pgbackrest -print
```

**Comment by dwsteele** [comment]
Let's also look for any LibC.so files you might have:
```
find / -name LibC.so -print
```

**Comment by vitabaks** [comment]
`find / -name pgbackrest -print`
/usr/bin/pgbackrest
/usr/share/doc-base/pgbackrest
/usr/share/doc/pgbackrest
/var/log/pgbackrest
/var/spool/pgbackrest
/var/lib/pgbackrest

`find / -name LibC.so -print`
/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/pgBackRest/LibC/LibC.so
/usr/lib/x86_64-linux-gnu/perl/5.20.2/auto/pgBackRest/LibC/LibC.so

**Comment by dwsteele** [comment]
Two version of `LibC.so` is bad.

Remove `/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/pgBackRest/LibC/LibC.so` and see what happens.

**Comment by vitabaks** [comment]
I deleted the file.

New error:
pgbackrest --stanza=main --log-level-console=debug stanza-create
```
2018-05-08 18:20:20.517 P00   INFO: stanza-create command begin 2.01: --compress-level=6 --log-level-console=debug --log-level-file=detail --pg1-path=/var/lib/postgresql/9.4/main --repo1-path=/var/lib/pgbackrest --stanza=main
pgBackRest::LibC object version 2.01 does not match bootstrap parameter 2.02 at /usr/lib/x86_64-linux-gnu/perl/5.20/DynaLoader.pm line 210.
Compilation failed in require at /usr/share/perl5/pgBackRest/Config/Config.pm line 21.
BEGIN failed--compilation aborted at /usr/share/perl5/pgBackRest/Config/Config.pm line 21.
Compilation failed in require at /usr/share/perl5/pgBackRest/Common/Lock.pm line 19.
BEGIN failed--compilation aborted at /usr/share/perl5/pgBackRest/Common/Lock.pm line 19.
Compilation failed in require at /usr/share/perl5/pgBackRest/Common/Exit.pm line 16.
BEGIN failed--compilation aborted at /usr/share/perl5/pgBackRest/Common/Exit.pm line 16.
Compilation failed in require at /usr/share/perl5/pgBackRest/Main.pm line 20.
BEGIN failed--compilation aborted at /usr/share/perl5/pgBackRest/Main.pm line 20.
Compilation failed in require.
BEGIN failed--compilation aborted.
Undefined subroutine &pgBackRest::Main::configSet called at (eval 75) line 1.
```

And PostgreSQL log:
```
2018-05-08 18:21:37.329 P00   INFO: archive-push command begin 2.01: --compress --compress-level=6 --log-level-console=info --log-level-file=detail --pg1-path=/var/lib/postgresql/9.4/main --process-max=2 --repo1-path=/var/lib/pgbackrest --stanza=main
pgBackRest::LibC object version 2.01 does not match bootstrap parameter 2.02 at /usr/lib/x86_64-linux-gnu/perl/5.20/DynaLoader.pm line 210.
Compilation failed in require at /usr/share/perl5/pgBackRest/Config/Config.pm line 21.
BEGIN failed--compilation aborted at /usr/share/perl5/pgBackRest/Config/Config.pm line 21.
Compilation failed in require at /usr/share/perl5/pgBackRest/Common/Lock.pm line 19.
BEGIN failed--compilation aborted at /usr/share/perl5/pgBackRest/Common/Lock.pm line 19.
Compilation failed in require at /usr/share/perl5/pgBackRest/Common/Exit.pm line 16.
BEGIN failed--compilation aborted at /usr/share/perl5/pgBackRest/Common/Exit.pm line 16.
Compilation failed in require at /usr/share/perl5/pgBackRest/Main.pm line 20.
BEGIN failed--compilation aborted at /usr/share/perl5/pgBackRest/Main.pm line 20.
Compilation failed in require.
BEGIN failed--compilation aborted.
Undefined subroutine &pgBackRest::Main::configSet called at (eval 75) line 1.
2018-05-08 18:21:37 MSK [4994]  LOG:  archive command failed with exit code 2
```

**Comment by vitabaks** [comment]
How do I delete pgbackrest correctly?

**Comment by dwsteele** [comment]
Is there anything else in `/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/pgBackRest`?  If `LibC.pm` is in there then that's the problem.  I'd remove the entire directory.

**Comment by vitabaks** [comment]
Before I used this manual https://pgbackrest.org/user-guide.html#installation
I stopped at this stage "Build and Install Binary" (sudo make -C /tmp/pgbackrest-release-2.02/src)

**Comment by vitabaks** [comment]
> Is there anything else in /usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/pgBackRest?

/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/pgBackRest/LibC/autosplit.ix

**Comment by dwsteele** [comment]
So, remove `/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/pgBackRest` and also remove `/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/pgBackRest`.  That's where LibC.pm should be.

**Comment by vitabaks** [comment]
I deleted:
/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/pgBackRest
/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/pgBackRest
and reinstall pgbackrest,
chown postgres:postgres /tmp/pgbackrest/

And now...
INFO: stanza-create command end: **completed successfully**
INFO: archive-push command end: completed successfully

Thank you very much for your help!
