### ISSUE TITLE
Cannot compile pgbackrest C components

### ISSUE THREAD

**Issue by cabell312** [pgbackrest/pgbackrest#531]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

pgBackRest v2.02

2. PostgreSQL version:

ostgres@ip-10-30-5-70:~$ psql --version
psql (PostgreSQL) 10.1
postgres@ip-10-30-5-70:~$ psql
psql (10.1, server 9.6.8)
Type "help" for help.

postgres=# select version();
                                                          version                                                          
---------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.8 on x86_64-pc-linux-gnu (Debian 9.6.8-1.pgdg80+1), compiled by gcc (Debian 4.9.2-10+deb8u1) 4.9.2, 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

cbell@ip-10-30-5-70:~/pgbackrest-release-2.01$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie

4. Did you install pgBackRest from source or from a package? 

From source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Here is the error generated:

cbell@ip-10-30-5-70:~/pgbackrest-release-2.01$ sudo make -C /root/pgbackrest-release-2.02/src
make: Entering directory '/root/pgbackrest-release-2.02/src'
gcc -o pgbackrest command/archive/common.o command/archive/get/get.o command/archive/push/push.o command/help/help.o command/command.o common/fork.o common/error.o common/exit.o common/io/handle.o common/ini.o common/lock.o common/log.o common/memContext.o common/regExp.o common/time.o common/type/buffer.o common/type/keyValue.o common/type/list.o common/type/string.o common/type/stringList.o common/type/variant.o common/type/variantList.o common/wait.o config/config.o config/define.o config/load.o config/parse.o perl/config.o perl/exec.o postgres/info.o storage/driver/posix/driver.o storage/driver/posix/driverFile.o storage/driver/posix/driverRead.o storage/driver/posix/driverWrite.o storage/fileRead.o storage/fileWrite.o storage/helper.o storage/storage.o main.o `perl -MExtUtils::Embed -e ldopts` 
/usr/bin/ld: cannot find -lperl
collect2: error: ld returned 1 exit status
Makefile:104: recipe for target 'pgbackrest' failed
make: *** [pgbackrest] Error 1
make: Leaving directory '/root/pgbackrest-release-2.02/src'

I apologize in advance if this is a repeat issue. Please refer me to the link explaining how to resolve.

**Comment by dwsteele** [comment]
It doesn't look like you have the Perl development libraries installed.

There are pre-built packages available at yum.postgresql.org.  It would be easier to use those.

**Comment by dwsteele** [comment]
Oops, this is Debian.  You'll want apt.postgresql.org.

**Comment by cabell312** [comment]
David,

Thank you for your help.

I ran: sudo apt-get install liberal-dev and everything worked.
