### ISSUE TITLE
Backing up Postgres running in Docker

### ISSUE THREAD

**Issue by avegamwala** [pgbackrest/pgbackrest#533]
1. pgBackRest version:
2.02

2. PostgreSQL version:
9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
UB16

4. Did you install pgBackRest from source or from a package?
Package

7. Describe the issue:
Wondering if anyone has tried to use pgBackrest to backup a Postgres DB running in a Docker container, and have been successful?

Thanks

**Comment by dwsteele** [comment]
Crunchy Containers (https://github.com/CrunchyData/crunchy-containers) use pgBackRest and run on a variety of Docker-based platforms.

**Comment by avegamwala** [comment]
Has anyone configured this before? First time and a bit unsure how to go about this
