### ISSUE TITLE
Lock archive-get issue

### ISSUE THREAD

**Issue by uspen** [pgbackrest/pgbackrest#534]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.02

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS 7.4

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

After upgrade from pgbackrest 1.26 to 2.02 еhere was an error:

`ERROR [050]: : raised from remote process on 'backup.server': unable to acquire lock on file '/tmp/pgbackrest/prod02-archive.lock': Resource temporarily unavailable
HINT: is another pgBackRest process running? at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/Base/Minion.pm line 158.
 at /usr/share/perl5/vendor_perl/pgBackRest/Main.pm line 12.
	pgBackRest::Main::__ANON__('PGBRCLIB:50:../src/common/lock.c:104:unable to acquire lock o...') called at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/Base/Minion.pm line 158
	eval {...} called at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/Base/Minion.pm line 167
	eval {...} called at /usr/share/perl5/vendor_perl/pgBackRest/Protocol/Base/Minion.pm line 223
	pgBackRest::Protocol::Base::Minion::process('pgBackRest::Protocol::Remote::Minion=HASH(0x249c020)', '/tmp/pgbackrest', 'archive-get', 'prod02') called at /usr/share/perl5/vendor_perl/pgBackRest/Main.pm line 118
	eval {...} called at /usr/share/perl5/vendor_perl/pgBackRest/Main.pm line 276
	pgBackRest::Main::main('remote') called at (eval 77) line 1
	eval '($result, $message) = pgBackRest::Main::main(\'remote\')
;' called at (eval 77) line 0
`

I restore one cluster to multiple DEV servers simultaneously. Why lock archive while GET
[cmd.txt](https://github.com/pgbackrest/pgbackrest/files/2016455/cmd.txt)

**Comment by dwsteele** [comment]
Is this during the restore or during recovery (archive-get)?

**Comment by dwsteele** [comment]
Never mind -- I see archive-get in the call stack.

**Comment by dwsteele** [comment]
OK, I see what's going on here.  This is a regression in 2.02 when we introduced the new lock code.

We'll fix this, but in the meantime I'd recommend reverting to 2.01.

**Comment by dwsteele** [comment]
Fixed at ada5c5c0d96e63f9f13009b6b08.

Another option (other than using <= 2.01) is to use 2.02 with async archive-get (https://pgbackrest.org/user-guide.html#async-archiving).  The async version does not take a lock and is much more efficient anyway.

We're considering a release this week for this bug, but haven't made a final decision yet.

**Comment by uspen** [comment]
Thank you
