### ISSUE TITLE
Using backup host as a restoration server

### ISSUE THREAD

**Issue by marceloslacerda** [pgbackrest/pgbackrest#535]
I'm trying to setup a server as both the backup server and as a restore point for a remote database.

I have drawn a diagram based on what I've set up:

```
_______________________________                      _______________
|            host1            |   get backups from   |    host2    |
|-----------------------------|--------------------->|-------------|
|  pgbackrest   | postgresql  |                      |  postgresql |
-------------------------------                      ---------------
         ^            |
         |            |
         | restore to |
         --------------
```

Here's the /etc/pgbackrest.conf of host1
```
[global]
repo1-path=/var/lib/pgbackrest
stop-auto=y
backup-host=host1

[production-general]
pg1-host=host2
pg1-host-user=postgres
pg1-path=/var/lib/pgsql/9.6/data

[recovery]
db-path=/var/lib/pgsql/9.6/data
```

And here's the /etc/pgbackrest.conf of host2
```
[global]
log-level-file=detail
repo1-host=host1


[production-general]]
pg1-path=/var/lib/pgsql/9.6/data/
```

I tried to do a restore (given that I already have some backups from host2)

    sudo -u pgbackrest pgbackrest --stanza=recovery restore

And I got the output:

    ERROR [055]: : raised from remote process on '10.0.255.4': unable to open '/var/lib/pgbackrest/backup/recuperacao/backup.info': No such file or directory

I found that to be natural, after all I have not created a stanza so I tried doing just that:

    sudo -u pgbackrest pgbackrest --stanza=recovery stanza-create

But I got this error:

    ERROR [072]: : stanza-create command must be run on the repository host

Now I'm scratching my head because I am on the repository host, what's happening?

**Comment by dwsteele** [comment]
You have `backup-host` host set which tells pgBackRest that this is not the repository host.

You have two hosts but I only see one config and I'm not sure which host it belongs to.  If this is the config for host1 then definitely remove `backup-host`.

**Comment by marceloslacerda** [comment]
I have updated the question with the configuration of host2.

I removed `backup-host` as you suggested and ~~did a lot of acrobatics to make postgresql run as pgbackrest user~~ managed to create a stanza named `recovery` on host1 but I don't know how to tell pgbackrest to recover the `production-general` backups into `recovery`.

**Comment by dwsteele** [comment]
You don't need the `recovery` stanza at all -- you just need to reset the pg host so it doesn't think you are trying to restore there (you could also set pg1-path if you wanted).  So, on host2:
```
pgbackrest --stanza=production-general --reset-pg1-host restore
```
See https://pgbackrest.org/command.html#introduction for a more detailed explanation of reset.

**Comment by marceloslacerda** [comment]
Sweet, it worked. Out of curiosity is it possible specify the port of the postgres server on host1?

**Comment by dwsteele** [comment]
You can use the `pg-port` option to specify the Postgres port.
