### ISSUE TITLE
Question about archive command on remote host

### ISSUE THREAD

**Issue by Raphyyy** [pgbackrest/pgbackrest#536]
Hi and thank you for your work.

I want to use pgBackRest as a remote backup handler from many cluster.

The setup is simple : pgBackRest is on a remote host and PostgreSQL cluster are on different host each.

I am facing trouble trying to setup WAL archiving and restore command.

If I get it well, here is an example of the archive command to set in postgresql.conf : 
`archive_command = 'pgbackrest --stanza=demo archive-push %p'`

And here is an example of the restore command in recovery.conf : 
`restore_command = 'pgbackrest --stanza=demo archive-get %f "%p"'`

But in my case, how do I proceed to perform these command if pgbackrest is on a remote host ?

**Comment by dwsteele** [comment]
Please see https://pgbackrest.org/user-guide.html#repo-host for instructions on setting up a remote host.

**Comment by Raphyyy** [comment]
Ew sorry for missing some parts... Thanks ! 👍
