### ISSUE TITLE
[question] Best way to backup the repository

### ISSUE THREAD

**Issue by Raphyyy** [pgbackrest/pgbackrest#537]
Hi and thank you for your work

I would like to set up a safest way to backup.. bgbackrest.

I would like to now if there is a gentle way to export weekly the entiere compressed repository. 

My question is : If I save the entiere repository, deploy a new pgbackrest host, and set back the saved repository on the new pgbackrest, am I be able to recover all my stanzas ?

Thank you

**Comment by dwsteele** [comment]
You can use any tool you like to backup the repository.  If a backup is in progress during the copy it will be marked invalid in the copy and will not be usable, but other than that the rest of the repo will work.

**Comment by Raphyyy** [comment]
Thanks !
