### ISSUE TITLE
[question] Backup from a Standby

### ISSUE THREAD

**Issue by Raphyyy** [pgbackrest/pgbackrest#538]
Hello again

Sorry to bother you with questions, I hope this will be the last.

I want to set up a stanza from a primary and a standby hosts like described here : https://pgbackrest.org/user-guide.html#standby-backup

I have a failover process that promote the standby if the primary goes down.
So I have the same WAL configuration on both primary and standby.

My question is : If I configure archive_command with pgbackrest archive-push command on both, is this could cause trouble to pgbackrest to receive WAL from these two or not ?

**Comment by uspen** [comment]
No

Its PostgreSQL opportunity

**Comment by keithf4** [comment]
A postgresql replica does not execute the archive_command, so this should be safe to do. It will also ensure that no WAL files are missed during a failover since it will immediately start firing once it becomes the primary.

**Comment by dwsteele** [comment]
@keithf4 and @uspen are correct -- however the archive mode must not be set to `always` or the replica *will* try to archive before it is promoted.  pgBackRest will error if it sees `archive_mode = always`.

**Comment by Raphyyy** [comment]
Thanks guys !
