### ISSUE TITLE
Unable to create stanza on repository server

### ISSUE THREAD

**Issue by vancouvertreehouse** [pgbackrest/pgbackrest#541]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 

**2.02**

2. PostgreSQL version: 

**9.5**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

**3.10.0-862.3.2.el7.x86_64 GNU/Linux**

4. Did you install pgBackRest from source or from a package?

**Package**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

**REPOSITORY:

repo1-path=/data/pgbackrest

[g01-inst1]
pg1-host=<IP Of DB Server>
pg1-port=5432
pg1-host-user=postgres
pg1-path=/pgdata/inst1

DBServer:

repo1-host=<IP of Repository>
repo1-host-user=pgbackrest
repo1-path=/data/pgbackrest

[g01-inst1]
pg1-path=/pgdata/inst1
pg1-port=5432**

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

**I haven't set this up, this is as this requires PostgreSQL restart, I'm trying to get stanza created before I go ahead with setting up archiving command, it allowed me create stanza on test servers without setting up archive_command**

    - errors in the postgresql log file before or during the time you experienced the issue

**No**

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

**-------------------PROCESS START-------------------
2018-06-01 12:24:59.505 P00   INFO: stanza-create command begin 2.02: --pg1-host=<myDBServerName> --pg1-host-user=postgres --pg1-path=/pgdata/inst1 --pg1-port=5432 --repo1-path=/data/pgbackrest --stanza=g01-inst1
2018-06-01 12:25:00.781 P00  ERROR: [056]: raised from remote process on '<IP of DB Server>': could not connect to server: No such file or directory
                                                Is the server running locally and accepting
                                                connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2018-06-01 12:25:00.786 P00   INFO: stanza-create command end: aborted with exception [056]**

7. Describe the issue:

**I've setup and tested trusted ssh between db server and repository server:

I'm able to access database from Repository with both postgres user and pgbackrest user.

I got following error when I tried to create stanza on Repository: $pgbackrest stanza-create --stanza=g01-inst1**

**ERROR [056]: : raised from remote process on 'IP of DB Server': could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?**

**I've tested this on my testing servers, all work fine.   

Please help, thanks!**

**Comment by dwsteele** [comment]
Does `/var/run/postgresql/.s.PGSQL.5432` exist?  Have you set `unix_socket_directories` to another location?  If so, use `pg-socket-path` to tell pgBackRest where it is.

**Comment by vancouvertreehouse** [comment]
No, it doesn't, it was changed to another location, this seems to be the cause.


I will set pg-socket-path, thank you very much!




Email: xdsun@hotmail.com<mailto:xdsun@hotmail.com>



________________________________
