### ISSUE TITLE
Missing perl-Time-HiRes dependencies on rpm package (from pgdg)

### ISSUE THREAD

**Issue by thelan** [pgbackrest/pgbackrest#544]
I'm not sure if this is the best place to report this issue but after after installing a fresh Fedora 27 minimal, it seems pgbackrest is missing a dependencies to `perl-Time-HiRes` package.

1. pgBackRest version: 
```
# dnf info pgbackrest.x86_64
Last metadata expiration check: 0:08:22 ago on Wed 13 Jun 2018 02:30:22 PM CEST.
Installed Packages
Name         : pgbackrest
Version      : 2.03
Release      : 2.f27
Arch         : x86_64
Size         : 1.4 M
Source       : pgbackrest-2.03-2.f27.src.rpm
Repo         : @System
From repo    : pgdg10
```

2. PostgreSQL version: 10.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
Fedora 27 (x86_64)

4. Did you install pgBackRest from source or from a package?
Package from pgdp

5. Please attach the following as applicable:
pgbackrest.conf
```ini
[global]
repo1-path=/var/lib/pgbackrest

[data]
pg1-path=/var/lib/pgsql/10/data
repo1-retention-full=2

[global:archive-push]
compress-level=3
```

7. Describe the issue:

Running pgbackrest fail this an Perl error.

```
$ pgbackrest --stanza=data --log-level-console=info stanza-create
2018-06-13 14:35:00.030 P00   INFO: stanza-create command begin 2.03: --log-level-console=info --pg1-path=/var/lib/pgsql/10/data --repo1-path=/var/lib/pgbackrest --stanza=data
Can't locate Time/HiRes.pm in @INC (you may need to install the Time::HiRes module) (@INC contains: CODE(0x55c68cfeafc8) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /loader/0x55c68cfeafc8/pgBackRest/Common/Log.pm line 16.
BEGIN failed--compilation aborted at /loader/0x55c68cfeafc8/pgBackRest/Common/Log.pm line 16.
Compilation failed in require at /loader/0x55c68cfeafc8/pgBackRest/Common/Lock.pm line 16.
BEGIN failed--compilation aborted at /loader/0x55c68cfeafc8/pgBackRest/Common/Lock.pm line 16.
Compilation failed in require at /loader/0x55c68cfeafc8/pgBackRest/Main.pm line 17.
BEGIN failed--compilation aborted at /loader/0x55c68cfeafc8/pgBackRest/Main.pm line 17.
Compilation failed in require at (eval 3) line 1.
BEGIN failed--compilation aborted at (eval 3) line 1.
```

After installing package `perl-Time-HiRes` it seems to run fine

```$ pgbackrest --stanza=data --log-level-console=info stanza-create
2018-06-13 14:36:48.680 P00   INFO: stanza-create command begin 2.03: --log-level-console=info --pg1-path=/var/lib/pgsql/10/data --repo1-path=/var/lib/pgbackrest --stanza=data
2018-06-13 14:36:49.497 P00   INFO: stanza-create command end: completed successfully (818ms)
```

**Comment by dwsteele** [comment]
Bugs can be reported here: https://redmine.postgresql.org (you'll need a community account). @devrimgunduz.

**Comment by devrimgunduz** [comment]
Hi,

I thought Time-HiRes was only needed on RHEL 6. Weird.

Committed changes to git repo:

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=commit;h=09ea98fce8c798ef530e83a97732e82a3953b737

No need to create a ticket at this point. @thelan , thanks for the report, and thanks @dwsteele for the mention.

Regards, Devrim

**Comment by dwsteele** [comment]
Thanks, @devrimgunduz! Perhaps they have decided to drop the package as a default for the Fedora releases.  I'm actually planning move this code to C and drop the dependency soon as well.  I'll let you know when that happens.

**Comment by devrimgunduz** [comment]
Hi @dwsteele , package is in the repo, so pulling it with the RPM will not hurt. Anyway, glad that you are removing that dependency, so I'll wait for the next version to release updated package.

Regards, Devrim

**Comment by dwsteele** [comment]
@devrimgunduz It looks `Time::HiRes` is needed before the C time functions are exported to Perl.  I may be able to fix this in the future, but for the time being I think we should just add this module to the RHEL package.

**Comment by dwsteele** [comment]
Added a request on redmine to add this with the 2.04 release.
