### ISSUE TITLE
pb_backrest aborted with exception [057]

### ISSUE THREAD

**Issue by Rene1089** [pgbackrest/pgbackrest#547]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.02

2. PostgreSQL version: 9.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Debian Stretch

4. Describe the issue:
Hi,
our backup doesnt start. It seems that there is a running process with a backup job. I cant find or stop the process. 
![image](https://user-images.githubusercontent.com/40357295/41533787-50a38b22-72fc-11e8-97da-5f66a044c0d7.png)
Can you help us?

**Comment by Rene1089** [comment]
Hi,
thanks for the quick answer but thats doesnt solve the problem. We put stop-auto=y in pgbackrest.conf but nothing happen. We tried pg_stop_backup() in every Database but there is only the message "ERROR:  a backup is not in progress". We cant run a full backup since 14 days and we also restart the SQL and Fileserver.

**Comment by dwsteele** [comment]
The error message is pretty clear -- are you sure you are connecting to the right server?

If you are still having the issue, please provide the pgbackrest config files and the full debug output from a backup.

**Comment by dwsteele** [comment]
Closing this since it is idle.  Let us know if you are still seeing the issue.
