### ISSUE TITLE
pgbackrest aborted with exception [059]

### ISSUE THREAD

**Issue by brunre01** [pgbackrest/pgbackrest#548]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:   2.02

2. PostgreSQL version:   9.6.5.10

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  Red Hat Enterprise Linux Server release 7.3

4. Did you install pgBackRest from source or from a package?  package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
pgbackrest started failing 3 days ago with  
2018-06-19 04:05:09.643 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2018-06-19 04:35:09.705 P00  ERROR: [059]: statement timed out after 1800.034 second(s):
                                        select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, labelfile, case when length(trim(both '\t\n ' from spcmapfile)) = 0 then null else spcmapfile end as spcmapfile from pg_stop_backup(false) as lsn
2018-06-19 04:35:10.725 P00   INFO: backup command end: aborted with exception [059]

[Postgres_EDB_INC_LEVEL_1_Mon_2000.log](https://github.com/pgbackrest/pgbackrest/files/2115566/Postgres_EDB_INC_LEVEL_1_Mon_2000.log)

[postgresql.conf.zip](https://github.com/pgbackrest/pgbackrest/files/2115569/postgresql.conf.zip)

**Comment by dwsteele** [comment]
It looks like WAL archiving is failing.  Check for errors in the postgres log.

**Comment by brunre01** [comment]
I implemented async archiving which cleared the huge backlog of wal files i had the pg_xlog (  approx 60000) I ran another check which worked successfully

==> pgbackrest --stanza=CDAR_dayrhepgsp005 --log-level-console=detail check --db-port=5444
2018-06-20 14:11:37.055 P00   INFO: check command begin 2.02: --log-level-console=detail --log-level-file=detail --pg1-path=/pgDATA/data --pg1-port=5444 --repo1-path=/pgBACKUP/dayrhepgsp005 --stanza=CDAR_dayrhepgsp005
2018-06-20 14:12:48.881 P00   INFO: WAL segment 000000010000197000000051 successfully stored in the archive at '/pgBACKUP/dayrhepgsp005/archive/CDAR_dayrhepgsp005/9.6-1/0000000100001970/000000010000197000000051-8814e55089cd63141e969a70faf248929b0672c8.gz'
2018-06-20 14:12:48.882 P00   INFO: check command end: completed successfully

**Comment by brunre01** [comment]
Problem considered resolved.

**Comment by dwsteele** [comment]
Yeah, latency can also cause that timeout.  In this case async parallel archiving is definitely your friend.

Curious, how much WAL are you generating per hour at peak?

**Comment by brunre01** [comment]
peak time between 400 and 500 wal files in an hour

**Comment by dwsteele** [comment]
That rate can be done without async depending on other factors (compression speed, network throughput, etc) but it's on the edge.

Glad you got it working!
