### ISSUE TITLE
Compress remote backup on pgbackrest host rather than postgres host

### ISSUE THREAD

**Issue by powzer** [pgbackrest/pgbackrest#553]
When performing a compressed base backup of a remote database, the compression is currently performed on the database host.  This creates significant cpu overhead on the database host, and makes compressed base backups impractical for large databases.  

It would be great if we had the option to compress the backups on the backup host instead.

**Comment by dwsteele** [comment]
It's generally even more impractical to send a lot of ucompressed data over the network.  If your database is large enough and process-max is high enough then you can easily flood even a 10Gb network.  Also, database servers tend to be beefy while backup servers generally are not.  If one backup server is backing up many database servers it quickly becomes a bottleneck.

Backups don't have to be that fast as long as you can keep to a regular schedule.  Backup slowly, restore quickly is my motto.  Or you can reduce compress-level to save CPU.  We are planning to introduce lz4 compression soon which might also be a good option for you.

**Comment by powzer** [comment]
I agree that backing up slowly and compressing on the database server will be sufficient in most cases.

We're trying to backup a 47TB database which produces up to 1TB of WAL per day.  It's got a dedicated 10Gb interface to a 32 core backup server.  Offloading the compression to the backup server and flooding the 10Gb interface should allow us to back this up in under 14 hours.  As it is, we can only use 10 processes on the database host (even this puts a strain on cpu resources and probably won't be sustainable) and the backup will take ~80 hours.  This means storing heaps of WAL with the backup, and significantly increases the time to recover the database to a consistent state.

LZ4 will definitely be better than gzip (at the cost of compression ratio), but either way I think it would be useful to have the option of doing the compression on the backup host.

**Comment by dwsteele** [comment]
We've considered this feature and decided that it doesn't make sense to implement, at least at this time.  We do plan to add lz4 support and hopefully that will answer your need.
