### ISSUE TITLE
Require checksum delta backup if a timeline switch is detected

### ISSUE THREAD

**Issue by dwsteele** [pgbackrest/pgbackrest#555]
A timeline switch is a likely indication that a cluster has failed over. Require a full backup in this case for safety.  Disable resume because timestamps cannot be trusted on the new cluster.

**Comment by uspen** [comment]
Yes, feature is good!
But i have nuance. We use Patroni (https://github.com/zalando/patroni). Patroni always run postgresql master as a replica, checks everything is fine and promote replica.
This mean, timeline id always incremented with each restart

**Comment by dwsteele** [comment]
@uspen Yes, that's a good point.  We've decided to implement a checksum delta backup instead.  This will preserve the backup type (full, diff, incr) but use checksums instead of timestamps for the delta in cases where we think the timestamps may not be trust-worthy.

**Comment by dwsteele** [comment]
Committed at 880fbb5e578c387e52f from PR #595.
