### ISSUE TITLE
Use S3 with ip (e.g. minio)

### ISSUE THREAD

**Issue by xantalor** [pgbackrest/pgbackrest#556]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.03

2. PostgreSQL version:
postgresql-9.6.1-0.0.1136

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS7

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
`*stanza-create.log``
-------------------PROCESS START-------------------
2018-07-04 14:43:29.600 P00   INFO: stanza-create command begin 2.03: --config=/tmp/pgbackrest.conf --log-level-console=detail --pg1-path=/opt/data/postgresql/pgdata --pg1-socket-path=/opt/postgresql --repo1-cipher-type=none --repo1-path=/tmp/pgbackrest-test --repo1-s3-bucket=pgbackrest-test --repo1-s3-endpoint=10.134.127.28 --repo1-s3-host=10.134.127.28:9000 --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=eu-west-1 --no-repo1-s3-verify-ssl --repo1-type=s3 --stanza=dev-cluster
2018-07-04 14:43:30.130 P00  ERROR: [049]: Das Argument ist ungültig: IO::Socket::IP configuration failed
2018-07-04 14:43:30.131 P00   INFO: stanza-create command end: aborted with exception [049]

7. Describe the issue:
The normal backup works fine. Now want to push it to an S3 storage but I am getting the following error : Argument is invalid : IO::Socket::IP configuration failed.

Is there any restriction to amazonaws.com? 
Any hints or help is very welcome.

Greetz.

**Comment by dwsteele** [comment]
pgBackRest will only use verified, encrypted connections to the s3 store.  If you are using a real cert you'll need to let pgBackRest know where the CAs are stored by using `repo1-s3-ca-file` or `repo1-s3-ca-path`.  For RHEL 7 `repo1-s3-ca-file=/etc/pki/tls/certs/ca-bundle.crt` will work.

If you are using a self-signed cert then you can use `--repo1-s3-verify-ssl=n` to disabled verification of the cert.  There's no option to disable HTTPS but minio can be configured to do HTTPS.

**Comment by xantalor** [comment]
Thanks for your quick response. I will try it.

**Comment by xantalor** [comment]
The connection is working now. There is still a problem in the process of backup.
Minio returns 
`
?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioPartsSizeUnequal</Code><Message>All parts except the last part should be of the same size.</Message><Key></Key><BucketName></BucketName><Resource>/mypostgresissocool/backup/dev-cluster/20180717-121446F/pg_data/base/16400/28772.gz</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
`

I watched the traffic with traefik these are the corresponding calls:
`
- [17/Jul/2018:10:24:21 +0000] "PUT /mypostgresissocool/backup/dev-cluster/20180717-121446F/backup.manifest.copy? HTTP/1.1" 200 0 "-" "-" 149 "frontend1" "http://127.0.0.1:9000" 8ms
- [17/Jul/2018:10:24:46 +0000] "POST /mypostgresissocool/backup/dev-cluster/20180717-121446F/pg_data/base/16400/204416.gz?uploads= HTTP/1.1" 200 335 "-" "-" 150 "frontend1" "http://127.0.0.1:9000" 3ms
- [17/Jul/2018:10:24:47 +0000] "PUT /mypostgresissocool/backup/dev-cluster/20180717-121446F/pg_data/base/16400/204416.gz?partNumber=1&uploadId=742d9529-9840-4bef-88cc-6c2c8df04fcf HTTP/1.1" 200 0 "-" "-" 151 "frontend1" "http://127.0.0.1:9000" 113ms
- [17/Jul/2018:10:25:07 +0000] "PUT /mypostgresissocool/backup/dev-cluster/20180717-121446F/pg_data/base/16400/204416.gz?partNumber=2&uploadId=742d9529-9840-4bef-88cc-6c2c8df04fcf HTTP/1.1" 200 0 "-" "-" 152 "frontend1" "http://127.0.0.1:9000" 117ms
- [17/Jul/2018:10:25:07 +0000] "PUT /mypostgresissocool/backup/dev-cluster/20180717-121446F/pg_data/base/16400/204416.gz?partNumber=3&uploadId=742d9529-9840-4bef-88cc-6c2c8df04fcf HTTP/1.1" 200 0 "-" "-" 153 "frontend1" "http://127.0.0.1:9000" 5ms
- [17/Jul/2018:10:25:07 +0000] "POST /mypostgresissocool/backup/dev-cluster/20180717-121446F/pg_data/base/16400/204416.gz?uploadId=742d9529-9840-4bef-88cc-6c2c8df04fcf HTTP/1.1" 400 357 "-" "-" 154 "frontend1" "http://127.0.0.1:9000" 1ms
`

Did you have any hints according to this problem?
The normal upload to minio looks good. Looks like its affected by the multipart upload.

**Comment by dwsteele** [comment]
This behavior seems broken to me.  S3 requires each part (except the last) to be >= 5MB and <= 5GB but there's no requirement for them all to be the same size.

Here's the issue where they discuss introducing this limitation: https://github.com/minio/minio/issues/4881.  Apparently they decided that performance is more important than S3 compatibility.  If you want to use minio you choices are to use erasure-coded mode or an older version.

**Comment by xantalor** [comment]
Great thanks, this is what I was looking for. I will try it and give feedback.

**Comment by xantalor** [comment]
Thanks for your response. This helps a lot with the Erasure coded option all worked like a charm.
