### ISSUE TITLE
Async archiving failed due to "Could not create directory '/home/postgres/.ssh"

### ISSUE THREAD

**Issue by vancouvertreehouse** [pgbackrest/pgbackrest#562]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

**2.02**

2. PostgreSQL version:

**9.5**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

**RedHat 7**

4. Did you install pgBackRest from source or from a package?

**Package**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

**[global]
archive-async=y
repo1-host=*.*.*.*
repo1-host-user=pgbackrest
repo1-path=/var/lib/pgbackrest

[prod-inst1]
pg1-path=/pgdata/inst1
pg1-port=5432**

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

**archive_command = 'pgbackrest --stanza=prod-inst1 archive-push %p'**

    - errors in the postgresql log file before or during the time you experienced the issue

**ERROR: [042]: remote process on '172.27.93.227' terminated unexpectedly: Could not create directory '/home/postgres/.ssh'.^M
Host key verification failed.**

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

prod-inst1-archive-push-async.log

**-------------------PROCESS START-------------------
2018-07-23 17:05:21.310 P00   INFO: archive-push command begin 2.02: [pg_xlog/00000001000007B3000000B8] --archive-async --log-level-console=off --log-level-stderr=off --pg1-path=/pgdata/inst1 --repo1-host=*.*.*.* --repo1-path=/var/lib/pgbackrest --spool-path=/var/spool/pgbackrest --stanza=prod-inst1
2018-07-23 17:05:21.410 P00   INFO: push 1 WAL file(s) to archive: 00000001000007B3000000B8
2018-07-23 17:05:21.437 P00  ERROR: [042]: remote process on '*.*.*.*' terminated unexpectedly: Could not create directory '/home/postgres/.ssh'.^M
                                        Host key verification failed.
2018-07-23 17:05:21.440 P00   INFO: archive-push command end: completed successfully**

7. Describe the issue:

**Asyn Archiving failed due to the error described above. [042]

**ERROR: [042]: remote process on '*.*.*.*' terminated unexpectedly: Could not create directory '/home/postgres/.ssh'.^M
                                        Host key verification failed**

Santa was created with user pgbackrest on Repository Server successfully, permissions should be alright.

I'm assuming the user running on Repository should be pgbackrest, not sure why it's trying to create .ssh in /home/postgres

**

**Comment by dwsteele** [comment]
Trusted ssh should be set up in both directions.  Does the /home/postgres/.ssh directory exist on the database server?  Does it have authorized_hosts setup for the repo server?

A good test is to ssh from the database server to pgbackrest@repo and see what happens.

**Comment by vancouvertreehouse** [comment]
Yes, /home/postgres/.ssh exists on database server, /home/pgbackrest/.ssh exists on repo server, trusted ssh has been tested working properly both ways, stanza was created successfully from repo server with pgbackrest.

**Comment by vancouvertreehouse** [comment]
Thanks, I will give it(log-level-file=debug) a try.   It works fine on the testing environment.

**Comment by vancouvertreehouse** [comment]
@cmwshang, it's part of the error message from the log file.

**Comment by cmwshang** [comment]
@vancouvertreehouse OK, it's weird because pgBackRest doesn't support windows so it was just strange to see a Windows carriage return in the log.

**Comment by dwsteele** [comment]
@vancouvertreehouse Have you had a chance to produce debug output?

**Comment by dwsteele** [comment]
Closing -- let us know if you are still seeing the issue.
