### ISSUE TITLE
What is buffer-size limit?

### ISSUE THREAD

**Issue by saspg** [pgbackrest/pgbackrest#566]
Hello, 

1. pgBackRest version: 
2.04

2. PostgreSQL version: 
9.4

3. Operating system/version :
debian 8

4. Did you install pgBackRest from source or from a package?
package

7. Describe the issue:
The documentation says one can set a buffer-size as a string with unit (M,K,G...).
I tried 64M, I got this error : 
ERROR [032]: : local-1 process terminated unexpectedly [032]: ERROR: [032]: '67108864' is not allowed for 'buffer-size' option
2018-08-08 19:16:33.927 P00   INFO: backup command end: aborted with exception [032]

Then I tried 32M, and got same error (with 33554432 as value not permitted).
I could set a 16M buffer.

I have at least 600MB free on the backup server, and 1.5GB free on the PostgreSQL server.

So my question is : if there is a hard limit to the buffer-size, which one is it. Otherwise, how is is calculated?

What's more the documentation may be more explicit on the unit suffix. It states that size can be entered in KB, MB, GB, TB, or PB. But, I guess, it should be written as '8K', '8M'...

**Comment by dwsteele** [comment]
Yes, the buffer size is limited to certain values and they are not listed in the docs.  We'll fix that.

Meanwhile you can find the allowed values here: https://github.com/pgbackrest/pgbackrest/blob/31167d8f987cf171bd655c5ccb1bebebac9d7997/src/config/define.auto.c#L527

In this case `16MB` is the highest value allowed.  The parser will also accept `16M`, `16mb`, `16mB` and any other case-only variation.

In general, buffers over 4MB are not going to provide any additional performance and will simply use more memory.  Unless you have a specific reason to think this will help, I'd stick with the default.

**Comment by saspg** [comment]
Thank you for the explanation. I thought I could speed up the backup (1To), but it indeed seems there is no improvement.

**Comment by dwsteele** [comment]
Buffer-size option allowed values added to the docs at cabb3f8577d6de2a6fe.
