### ISSUE TITLE
How can I save the postgresql.conf file ?

### ISSUE THREAD

**Issue by LaetitiaAvrot** [pgbackrest/pgbackrest#567]
Hi,

In debian-based default postgres installation, the configuration file postgresql.conf is not included in $PGDATA. 
I advise my customer to use a version control system as git on a remote server for their configuration files.

But wouldn't it be nice to be able to save the configuration file while performing a backup, even if that conf file is not in $PGDATA ?

Have a nice day,

Lætitia

**Comment by dwsteele** [comment]
Hi Lætitia,

If you create a symlink from $PGDATA to /etc/postgresql/[cluster] then pgBackRest will include the config files in the backup.  Note that on restore link contents are restored into $PGDATA, not the original location by default.  To restore links you'll need to use `--link-all` or `--link-map` with an alternate mapping.

See: https://pgbackrest.org/configuration.html#section-restore/option-link-all and https://pgbackrest.org/configuration.html#section-restore/option-link-map.

-David

**Comment by LaetitiaAvrot** [comment]
Thank you :-)

**Comment by dwsteele** [comment]
You are welcome!

**Comment by dwsteele** [comment]
You are welcome!
