### ISSUE TITLE
Unhandled exception when missing group on restore

### ISSUE THREAD

**Issue by c4milo** [pgbackrest/pgbackrest#571]
### pgBackRest version:
2.04

### PostgreSQL version
9.6.8

### Did you install pgBackRest from source or from a package?
From source.

### Describe the issue:
I was trying to bootstrap a replica from backups and got this exception: 

Aug 10 02:37:42 ubuntu-xenial sudo[5275]: pam_unix(sudo:session): session closed for user root
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]: INFO: restore backup set 20180810-023048F
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]: ERROR: [124]: process terminated due to an unhandled exception:
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:        Use of uninitialized value $strOwner in concatenation (.) or string at /loader/0x558f35ff6490/pgBackRest/Restore.pm line 132.
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:         at /loader/0x558f35ff6490/pgBackRest/Main.pm line 12.
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:                pgBackRest::Main::__ANON__("Use of uninitialized value \$strOwner in concatenation (.) or "...) called at /loader/0x558f35ff6490/pgBackRest/Restore.pm line 132
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:                pgBackRest::Restore::manifestOwnershipCheck(undef, pgBackRest::Manifest=HASH(0x558f37113be8)) called at /loader/0x558f35ff6490/pgBackRest/Restore.pm line 323
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:                pgBackRest::Restore::manifestLoad(undef, undef) called at /loader/0x558f35ff6490/pgBackRest/Restore.pm line 1105
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:                pgBackRest::Restore::process(pgBackRest::Restore=HASH(0x558f369e5cf8)) called at /loader/0x558f35ff6490/pgBackRest/Main.pm line 220
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:                eval {...} called at /loader/0x558f35ff6490/pgBackRest/Main.pm line 276
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:                pgBackRest::Main::main("restore") called at (eval 194) line 1
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:                eval '($result, $message) = pgBackRest::Main::main(\'restore\')' called at (eval 194) line 0
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]:
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]: INFO: restore command end: aborted with exception [124]
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]: ERROR: Error creating replica using method pgbackrest: /usr/bin/pgbackrest --config /etc/enigma/postgres-ha/pgbackrest.conf --stanza=postgres-dr restore -- exited with code=124
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]: INFO: Removing data directory: /var/lib/enigma/postgres-ha/data
Aug 10 02:37:42 ubuntu-xenial enigma-postgres-ha[5224]: pg_basebackup: initiating base backup, waiting for checkpoint to complete
Aug 10 02:37:47 ubuntu-xenial enigma-postgres-ha[5224]: pg_basebackup: checkpoint completed
Aug 10 02:37:47 ubuntu-xenial enigma-postgres-ha[5224]: transaction log start point: 0/8000028 on timeline 3
Aug 10 02:37:47 ubuntu-xenial enigma-postgres-ha[5224]: pg_basebackup: starting background WAL receiver

**Comment by c4milo** [comment]
hmm, I believe it is because the group with which the backup was originally taken does not exist in the machine where the backup is being restore.

**Comment by dwsteele** [comment]
It that case it should remap to root but it certain container environments (like OpenShift) that often won't work without some finessing.

It definitely should not be throwing a stack trace like this, though.  We'll have a look at it.

**Comment by dwsteele** [comment]
I had a look at the code. The user id running pgBackRest does not map to a name, probably due to no entry in `/etc/passwd`.

This seems a bit broken to me.  Our fix will probably be limited to throwing a clear error when the user id does not map to a name.  Thoughts, @Dwaligon?

**Comment by dwsteele** [comment]
Hmmm - change all references above to "group".  The user id running pgBackRest does not map to a group.  All the above still holds, too.

You can use nss_wrapper to map group/user names to IDs as show here: https://github.com/CrunchyData/crunchy-containers/blob/master/bin/common/common_lib.sh.

**Comment by dwsteele** [comment]
Added a specific error message for this case at e6abdfb5b864b6526e0e5c.

We plan to a `--no-owner` feature in the future to skip all ownership checks, but that doesn't have a date yet.
