### ISSUE TITLE
pgbackrest backup fails

### ISSUE THREAD

**Issue by brunre01** [pgbackrest/pgbackrest#576]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: v2.04

2. PostgreSQL version:  edb v10.3.8

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Red Hat Enterprise Linux Server release 7.4 (Maipo)

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[AOD_dayrheposp003]
db-path=/pgDATA/data

[global]
process-max=12
repo-path=/pgBACKUP/dayrheposp003
retention-full=7
retention-archive=2
start-fast=y
log-level-file=detail
archive-async=y

[global:archive-push]
process-max=4

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_command = 'cp -i %p /pgBACKUP/archivelogs/%f;pgbackrest --stanza=AOD_dayrheposp003 archive-push %p'
archive_mode=on
listen_addresses='*'
max_wal_senders = 4
wal_level = hot_standby
port = 5444

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

------------------PROCESS START-------------------
2018-08-14 15:49:05.245 P00   INFO: backup command begin 2.04: --log-level-file=detail --pg1-path=/pgDATA/data --process-max=12 --repo1-path=/pgBACKUP/dayrheposp003 --repo1-retention-archive=2 --repo1-retention-full=7 --stanza=AOD_dayrheposp003 --start-fast
2018-08-14 15:49:07.087 P00   INFO: last backup label = 20180805-200001F, version = 2.04
2018-08-14 15:49:07.102 P00  ERROR: [056]: could not connect to server: No such file or directory
                                                Is the server running locally and accepting
                                                connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2018-08-14 15:49:07.109 P00   INFO: backup command end: aborted with exception [056]

7. Describe the issue:

pgbackrest fails with error "could not connect to server: No such file or directory                                               Is the server running locally and accepting"   when the server is up and running.

**Comment by dwsteele** [comment]
It looks like you are running Postgres in on port 5444 but you didn't let pgBackRest know about that.  Use `pg1-port` to specify the port that pgBackRest should use to connect to Postgres.

**Comment by brunre01** [comment]
I'm still getting the error even if i'm using the correct port

==> pgbackrest --stanza=AOD_dayrheposp003 backup --db-port=5444 --log-level-console=detail
2018-08-15 09:30:12.337 P00   INFO: backup command begin 2.04: --log-level-console=detail --log-level-file=detail --pg1-path=/pgDATA/data --pg1-port=5444 --process-max=12 --repo1-path=/pgBACKUP/dayrheposp003 --repo1-retention-archive=2 --repo1-retention-full=7 --stanza=AOD_dayrheposp003 --start-fast
2018-08-15 09:30:14.183 P00   INFO: last backup label = 20180805-200001F, version = 2.04
ERROR [056]: : could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5444"?
2018-08-15 09:30:14.204 P00   INFO: backup command end: aborted with exception [056]

**Comment by dwsteele** [comment]
Perhaps the socket file is located in `/tmp` (or somewhere else) instead of `/var/run/postgresql`?  You can use `pg1-socket-path` to change the socket path.  This should be detected automatically by pqlib but if you have a mix of community and EDB packages it may be confused.

**Comment by brunre01** [comment]
Am i missing something?
==> pgbackrest --stanza=AOD_dayrheposp003 backup --db-port=5444 --log-level-console=detail --pg-socket-path=/tmp
ERROR: [031]: invalid option '--pg-socket-path=/tmp'

I can see that the socket is located in /tmp

-rw-------   1 enterprisedb enterprisedb    40 Aug 15 23:54 .s.PGSQL.5444.lock
srwxrwxrwx   1 enterprisedb enterprisedb     0 Aug 15 23:54 .s.PGSQL.5444

**Comment by brunre01** [comment]
if the unix_socket_directories parameter is set to /tmp then where does pgbackrest get Unix domain socket "/var/run/postgresql/.s.PGSQL.5444"   from?

**Comment by dwsteele** [comment]
As shown above the option name is `pg1-socket-path`.  It looks like you are using v1 option names (e.g. `db-port`) which confuses things a bit, although they will work.

As for the path issue, I would guess you are not using EDB's libpq, probably because you also have the community version installed.  Just a guess, though -- you should ask them.

**Comment by dwsteele** [comment]
Closing -- let us know if you are still having the issue.

**Comment by abis8170** [comment]
Hi,

While creating stanza I'm getting below error. Kindly suggest a solution for this issue. 
Query : pgbackrest --stanza=main  stanza-create

Error: 
ERROR [056]: : could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by dwsteele** [comment]
@abis8170 Please don't post on closed threads.  If you have a problem open a new issue and be sure to answer all the questions and give as much information as possible.
