### ISSUE TITLE
Is it reasonable for diff back up to take more than 4 hours to for database with size +/- 3.2 TB?

### ISSUE THREAD

**Issue by laurentiuspurba** [pgbackrest/pgbackrest#579]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **pgBackRest 2.03**

2. PostgreSQL version: *9.3*

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
- Database server (Master): CentOS 7.4
- Database server (Slave): CentOS 7.4
- Repository host server: CentOS 7.4

4. Did you install pgBackRest from source or from a package?
From the source.

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```[app]```
```pg1-host=DB-MASTER```
```pg1-host-user=postgres```
```pg1-path=/mnt/pg-data/data```
```pg1-port=5439```
``` ```
```[global]```
```repo1-path=/var/lib/pgbackrest```
```repo1-retention-full=2```
```repo1-retention-diff=6```
```start-fast=y```
```stop-auto=y```
```process-max=3```
``` ```
```[global:archive-get]```
```process-max=3```
```compress-level=3```
``` ```
```[global:archive-push]```
```compress-level=3```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
```archive_command = /bin/pgbackrest --stanza=app archive-push %p'```
``` ```
```archive_mode = on ```
``` ```
```listen_addresses = 'xxx.xxx.xxx.xxx'```
```max_wal_senders = 10```
```wal_level = hot_standby```
```port = 5439```
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
This is a question. My database size is +/- 3.2 TB. I have 2 cron jobs as follows:
```0  4  *   *   0     pgbackrest --type=full --stanza=app backup```
```0  */4 *   *   *     pgbackrest --type=diff --stanza=app backup```
My initial diff backup took less than 4 hours. After few days, my diff backup takes more than 4 hours. With the above configuration and database size, is it reasonable to take +/- 4 hours to have diff backup?

Thanks!
-Laurentius

**Comment by dwsteele** [comment]
A differential backup is an incremental based on the last full backup.  It is normal for the size/time of a diff backup to grow until the next full backup.

The advantage of diff backups is that they can be expired individually, so you can have a weekly full and a rolling set of three diff backups for the last three days:
```
repo1-retention-diff=3
```
This is more space efficient than keeping incrementals for the entire week but the trade-off is that the backups may take longer.  Which schedule makes more sense depends on your workload, i.e. how many tables are modified each day and the pattern of modification.

**Comment by laurentiuspurba** [comment]
Also, since we have 5 different database instances plus pgbackrest in one host. So when pgbackrest starts the diff backup, the load in the host is spiking up and is affecting the database load, and also application.

Do you think if I have incremental backup, some of this load issue will be alleviated?
I apologized for this kind of question if you think this is not related to pgbackrest. But again, thanks for replying my initial question, really appreciated.
