### ISSUE TITLE
Segmentation fault when duplicate boolean args are passed to pgbackrest

### ISSUE THREAD

**Issue by sharmay** [pgbackrest/pgbackrest#580]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.04

2. PostgreSQL version:
PostgreSQL 9.6.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28), 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.5.1804 (Core)

4. Did you install pgBackRest from source or from a package?
rpm

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Not relevant.

7. Describe the issue:
When any boolean parameter is duplicated to pgbackrest arg list it causes Segmentation fault
`pgbackrest --delta --delta`
```Segmentation fault```
`pgbackrest --compress --compress`
```Segmentation fault```

**Comment by dwsteele** [comment]
This was an issue in the config parser.  Fixed at ad989068d283.
