### ISSUE TITLE
Inconsitency between pgbackrest help restore and accepted options

### ISSUE THREAD

**Issue by rdunklau** [pgbackrest/pgbackrest#583]
1. pgBackRest version: pgBackRest 2.04

2. PostgreSQL version: 10.4

3. Operating system/version : Debian / 9.5

4. Did you install pgBackRest from source or from a package? From the PGDG package

5. Please attach the following as applicable: N/A

7. Describe the issue:

Launching pgbackrest help restore produces the following output:
```
....
Stanza Options:

  --pg-path                        postgreSQL data directory
```
Trying to use this option results in an error.

However, using the --db-path option works as expected.

**Comment by dwsteele** [comment]
All the pg-* options in 2.x are indexed as specified here: https://pgbackrest.org/configuration.html#section-stanza, so you want `--pg1-path` in this case.  The old options (before we introduced indexing) are still accepted for backwards compatibility.

We've struggled a bit with how to document this in the command-line help.  Does `--pg[1-8]-path` make sense?  Any ideas?

**Comment by rdunklau** [comment]
Now that you mention it, it's obvious since it's what I wrote in the config file :)

I think your proposal of using ```--pg[1-8]-path``` would make more sense, yes

**Comment by dwsteele** [comment]
I'm still not completely happy with this solution as it causes various formatting problems in the documentation.  It's not clear how far this pattern should be propagated.

I'm going close this issue but we'll continue to consider solutions.
