### ISSUE TITLE
Archive command can leak s3 access (not secret) key in Postgres logs

### ISSUE THREAD

**Issue by bradnicholson** [pgbackrest/pgbackrest#585]
Under certain circumstances when archiving to s3, the `repo-s3-key` can be leaked in the Postgres logs.  

This comes back because s3 returns the request header, which has the credentials in it. Postgres picks that up and logs it to the PG log.

The first time I saw this was when there was an s3 issue and authentication was failing.  It's easy to reproduce in test.  

Setup pgBackRest to archive to s3.  Once it's working, change the `repo-s3-key-secret` to an invalid key and try archiving a transaction log.

pgBackRests logging is configured as:
```
log-level-console=warn
log-level-file=info
log-level-stderr=warn
```

A heavily redacted version of the log output is:

```
2018-08-30 18:54:14 UTC [104]: [12-1] user=,db=,client= LOG:  archive command failed with exit code 39
2018-08-30 18:54:14 UTC [104]: [13-1] user=,db=,client= DETAIL:  The failed archive command was: pgbackrest --stanza=mydb --config=/conf/pgbackrest.conf archive-push pg_xlog/000000030000000000000007
ERROR: [039]: raised from local-1 process: S3 request error [403] Forbidden
        *** request header ***
        GET /aa-software/xxxxxxxxxxxx/pgbackrest/archive/mydb/archive.info? HTTP/1.1
        authorization: AWS4-HMAC-SHA256 Credential=<repo-s3-key is here>/.....
       
<headers continue>
```

**Comment by dwsteele** [comment]
Ah, yes, I see.  I thought you were taking about the *secret* key, but leaking the access key is not great, either.

It's easy enough to exclude that header from the output.  I'd still like to be able to see it for testing but we can make that depend on the --test switch.

**Comment by bradnicholson** [comment]
secret key is definitely not leaked.  This is of limited sensitivity, but still work surpassing IMHO.

**Comment by dwsteele** [comment]
Committed at bf873be4aa2688416e.
