### ISSUE TITLE
info command should include encryption info

### ISSUE THREAD

**Issue by hunleyd** [pgbackrest/pgbackrest#586]
It would be swell if the `info` command included the encryption info:

```
stanza: 10.0
    status: ok
    encryption: none

    db (current)
```

and:

```
stanza: 10.0
    status: ok
    encryption: aes-256-cbc

    db (current)
```

This way you can see at a glance if encryption is enabled and, if so, which encryption was used (thinking ahead to when multiple encryption methods are supported)

**Comment by dwsteele** [comment]
Sounds reasonable.  We'll target that for the next release.

**Comment by dwsteele** [comment]
Committed at e351b8c67ca16f42.
