### ISSUE TITLE
[Q]how to extract archive from backup repository server

### ISSUE THREAD

**Issue by hellower** [pgbackrest/pgbackrest#588]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.0.5

2. PostgreSQL version:
10.5.12

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
centos 7 

4. Did you install pgBackRest from source or from a package?
yes

-----------------------------------------------------
[enterprisedb@tntbackup:/opt/edb/as10/data/pg_wal]
$ pgbackrest info
stanza: kss_master
    status: ok

    db (current)
        wal archive min/max (10-1): 0000003E000000050000006A / 0000003F0000000600000025

        full backup: 20180906-000559F
            timestamp start/stop: 2018-09-06 00:05:59 / 2018-09-06 00:09:11
            wal start/stop: 0000003E000000050000006A / 0000003E000000050000006A
            database size: 1.3GB, backup size: 1.3GB
            repository size: 115.1MB, repository backup size: 115.1MB

        full backup: 20180906-083319F
            timestamp start/stop: 2018-09-06 08:33:19 / 2018-09-06 08:36:33
            wal start/stop: 0000003E000000050000006C / 0000003E000000050000006C
            database size: 1.3GB, backup size: 1.3GB
            repository size: 115.1MB, repository backup size: 115.1MB
[enterprisedb@tntbackup:/opt/edb/as10/data/pg_wal]

**I could extract one archive file using  below command**

[enterprisedb@tntlab:/tmp/archive]
$ ls -l 
total 0

[enterprisedb@tntlab:/tmp/archive]
$ pgbackrest archive-get 0000003E000000050000006A  /tmp/archive/0000003E000000050000006A --stanza=kss_master --log-level-console=info --no-archive-async
2018-09-06 08:40:03.460 P00   INFO: archive-get command begin 2.05: [0000003E000000050000006A, /tmp/archive/0000003E000000050000006A] --no-archive-async --log-level-console=info --log-level-file=detail --pg1-path=/opt/edb/as10/data --process-max=2 --repo1-host=myhostus --repo1-host-port=2234 --repo1-host-user=enterprisedb --repo1-path=/BACKREST_REPO --stanza=kss_master
2018-09-06 08:40:05.307 P00   INFO: got WAL segment 0000003E000000050000006A
2018-09-06 08:40:05.381 P00   INFO: archive-get command end: completed successfully (1922ms)

[enterprisedb@tntlab:/tmp/archive]
$ ls -l
total 16388
-rw-r----- 1 enterprisedb enterprisedb 16777216 Sep  6 08:40 0000003E000000050000006A
[enterprisedb@tntlab:/tmp/archive]
$ 

Question

1. pgbackrest archive-get 0000003E000000050000006B  /tmp/archive/0000003E000000050000006B --stanza=kss_master --log-level-console=info --no-archive-async
2. pgbackrest archive-get 0000003E000000050000006C  /tmp/archive/0000003E000000050000006C --stanza=kss_master --log-level-console=info --no-archive-async
......................
3. pgbackrest archive-get 0000003E000000050000006F  /tmp/archive/0000003E000000050000006F --stanza=kss_master --log-level-console=info --no-archive-async

**Extracting files one by one is too inefficient.

Is there a good way to extract multiple archive files at once?**

Sorry for poor enligh.

**Comment by dwsteele** [comment]
Using async archiving (combined with `process-max`) will significantly improve the performance of the archive-get command: https://pgbackrest.org/user-guide.html#async-archiving/async-archive-get.

**Comment by hellower** [comment]
thanks.

**Comment by hellower** [comment]
thanks
