### ISSUE TITLE
Unable to create symlink on HPE StoreOnce

### ISSUE THREAD

**Issue by renesepp** [pgbackrest/pgbackrest#592]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgbackrest-2.05-1.rhel7.x86_64
2. PostgreSQL version:
postgresql10-server-10.5
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
both Centos 7 
4. Did you install pgBackRest from source or from a package?
No
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
target_host config:
[global]
backup-host=pgbackrest.just.sise
backup-user=backrest
log-level-file=detail
[test1]
db-path=/var/lib/pgsql/10/data

Backup_host config:
[global]
repo-path=/var/lib/pgbackrest/mountpoint
repo-type=posix
process-max=1
compress=y
compress-level=3
compress-level-network=3
retention-full=2
[test1]
db-host=test1.just.sise
db-path=/var/lib/pgsql/10/data
db-user=postgres

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, 
`listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_mode = on
archive_command = 'pgbackrest --stanza=test1 archive-push %p'
listen_addresses = '*'
max_wal_senders = 10
wal_level = replica
port = 5432
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
2018-09-11 11:20:59.764 P03   INFO: backup file test1.just.sise:/var/lib/pgsql/10/data/base/13806/2662 (32KB, 99%) checksum 09b202ff8a81fe98fd185368d7d10653580d64dd
2018-09-11 11:20:59.803 P04   INFO: backup file test1.just.sise:/var/lib/pgsql/10/data/base/13806/2655 (32KB, 99%) checksum 6d513af962716f4c076d42c0bc6fd5b96aeb02e3
2018-09-11 11:20:59.839 P02   INFO: backup file test1.just.sise:/var/lib/pgsql/10/data/base/13805/3609 (32KB, 99%) checksum cc97a27eebd0ae434dd614741344f8dcbf833dc5
2018-09-11 11:20:59.840 P03   INFO: backup file test1.just.sise:/var/lib/pgsql/10/data/base/13805/2757 (32KB, 99%) checksum e47c70c122dee70a0e99f3a682468baa5f0b5106
2018-09-11 11:20:59.843 P01   INFO: backup file test1.just.sise:/var/lib/pgsql/10/data/base/13806/2603 (32KB, 99%) checksum 16f326d72cdc82ec96be2bcf24d33ef176d0d7e6
ERROR [041]: : raised from local-2 process: unable to open '/var/lib/pgbackrest/mountpoint/backup/test1/20180911-105634F/pg_data/base/13805/2662.gz': Input/output error
ERROR [042]: : local-1 process terminated unexpectedly [000]: (in cleanup) malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "           BRBLOCK0") at /loader/0x8b2ef8/pgBackRest/Protocol/Base/Master.pm line 165.
 at /loader/0x8b2ef8/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('malformed JSON string, neither array, object, number, string ...') called at /usr/share/perl5/vendor_perl/Carp.pm line 100
        Carp::croak('malformed JSON string, neither array, object, number, string ...') called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 1213
        JSON::PP::decode_error('malformed JSON string, neither array, object, number, string ...') called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 1045
        JSON::PP::word() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 728
        JSON::PP::value() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 688
        JSON::PP::PP_decode_json('JSON::PP=HASH(0x15d41a8)', 'BRBLOCK0', 0) called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 148
        JSON::PP::decode('JSON::PP=HASH(0x15d41a8)', 'BRBLOCK0') called at /loader/0x8b2ef8/pgBackRest/Protocol/Base/Master.pm line 165
        pgBackRest::Protocol::Base::Master::outputRead(undef) called at /loader/0x8b2ef8/pgBackRest/Protocol/Storage/File.pm line 164
        pgBackRest::Protocol::Storage::File::close('pgBackRest::Protocol::Storage::File=HASH(0x15f6338)') called at /loader/0x8b2ef8/pgBackRest/Common/Io/Base.pm line 111
        pgBackRest::Common::Io::Base::DESTROY('pgBackRest::Protocol::Storage::File=HASH(0x15f6338)') called at /usr/share/perl5/vendor_perl/Carp.pm line 101
        eval {...} called at /usr/share/perl5/vendor_perl/Carp.pm line 101
        eval {...} called at /loader/0x8b2ef8/pgBackRest/Protocol/Base/Minion.pm line 224
        pgBackRest::Protocol::Base::Minion::process('pgBackRest::Protocol::Local::Minion=HASH(0x15ce190)') called at /loader/0x8b2ef8/pgBackRest/Main.pm line 151
        eval {...} called at /loader/0x8b2ef8/pgBackRest/Main.pm line 286
        pgBackRest::Main::main('local') called at (eval 269) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'local\')
;' called at (eval 269) line 0
        (in cleanup) pgBackRest::Common::Exception=HASH(0x2229fd0) at /usr/share/perl5/vendor_perl/Carp.pm line 101.
ERROR [042]: : local-3 process terminated unexpectedly [000]: (in cleanup) malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "           BRBLOCK0") at /loader/0x224aef8/pgBackRest/Protocol/Base/Master.pm line 165.
 at /loader/0x224aef8/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('malformed JSON string, neither array, object, number, string ...') called at /usr/share/perl5/vendor_perl/Carp.pm line 100
        Carp::croak('malformed JSON string, neither array, object, number, string ...') called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 1213
        JSON::PP::decode_error('malformed JSON string, neither array, object, number, string ...') called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 1045
        JSON::PP::word() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 728
        JSON::PP::value() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 688
        JSON::PP::PP_decode_json('JSON::PP=HASH(0x2f6eff8)', 'BRBLOCK0', 0) called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 148
        JSON::PP::decode('JSON::PP=HASH(0x2f6eff8)', 'BRBLOCK0') called at /loader/0x224aef8/pgBackRest/Protocol/Base/Master.pm line 165
        pgBackRest::Protocol::Base::Master::outputRead(undef) called at /loader/0x224aef8/pgBackRest/Protocol/Storage/File.pm line 164
        pgBackRest::Protocol::Storage::File::close('pgBackRest::Protocol::Storage::File=HASH(0x2f6e440)') called at /loader/0x224aef8/pgBackRest/Common/Io/Base.pm line 111
        pgBackRest::Common::Io::Base::DESTROY('pgBackRest::Protocol::Storage::File=HASH(0x2f6e440)') called at /usr/share/perl5/vendor_perl/Carp.pm line 101
        eval {...} called at /usr/share/perl5/vendor_perl/Carp.pm line 101
        eval {...} called at /loader/0x224aef8/pgBackRest/Protocol/Base/Minion.pm line 224
        pgBackRest::Protocol::Base::Minion::process('pgBackRest::Protocol::Local::Minion=HASH(0x2f68fe0)') called at /loader/0x224aef8/pgBackRest/Main.pm line 151
        eval {...} called at /loader/0x224aef8/pgBackRest/Main.pm line 286
        pgBackRest::Main::main('local') called at (eval 269) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'local\')
;' called at (eval 269) line 0
        (in cleanup) pgBackRest::Common::Exception=HASH(0x2227060) at /usr/share/perl5/vendor_perl/Carp.pm line 101.
ERROR [042]: : local-2 process terminated unexpectedly [000]: (in cleanup) malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "           BRBLOCK0") at /loader/0x1ea1ef8/pgBackRest/Protocol/Base/Master.pm line 165.
 at /loader/0x1ea1ef8/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('malformed JSON string, neither array, object, number, string ...') called at /usr/share/perl5/vendor_perl/Carp.pm line 100
        Carp::croak('malformed JSON string, neither array, object, number, string ...') called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 1213
        JSON::PP::decode_error('malformed JSON string, neither array, object, number, string ...') called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 1045
        JSON::PP::word() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 728
        JSON::PP::value() called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 688
        JSON::PP::PP_decode_json('JSON::PP=HASH(0x2bc5ff8)', 'BRBLOCK0', 0) called at /usr/share/perl5/vendor_perl/JSON/PP.pm line 148
        JSON::PP::decode('JSON::PP=HASH(0x2bc5ff8)', 'BRBLOCK0') called at /loader/0x1ea1ef8/pgBackRest/Protocol/Base/Master.pm line 165
        pgBackRest::Protocol::Base::Master::outputRead(undef) called at /loader/0x1ea1ef8/pgBackRest/Protocol/Storage/File.pm line 164
        pgBackRest::Protocol::Storage::File::close('pgBackRest::Protocol::Storage::File=HASH(0x2bc0340)') called at /loader/0x1ea1ef8/pgBackRest/Common/Io/Base.pm line 111
        pgBackRest::Common::Io::Base::DESTROY('pgBackRest::Protocol::Storage::File=HASH(0x2bc0340)') called at /usr/share/perl5/vendor_perl/Carp.pm line 101
        eval {...} called at /usr/share/perl5/vendor_perl/Carp.pm line 101
        eval {...} called at /loader/0x1ea1ef8/pgBackRest/Protocol/Base/Minion.pm line 224
        pgBackRest::Protocol::Base::Minion::process('pgBackRest::Protocol::Local::Minion=HASH(0x2bbffe0)') called at /loader/0x1ea1ef8/pgBackRest/Main.pm line 151
        eval {...} called at /loader/0x1ea1ef8/pgBackRest/Main.pm line 286
        pgBackRest::Main::main('local') called at (eval 269) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'local\')
;' called at (eval 269) line 0
        (in cleanup) pgBackRest::Common::Exception=HASH(0x2227090) at /usr/share/perl5/vendor_perl/Carp.pm line 101.
2018-09-11 11:21:00.124 P00   INFO: backup command end: aborted with exception [041]

7. Describe the issue:
Testing out full backup to a NFS share with following command:
sudo -u backrest pgbackrest --stanza=test1 --log-level-console=info backup

**Comment by dwsteele** [comment]
I'm not sure why we are getting so many errors shutting down the locals, but the root error is:
```
unable to open '/var/lib/pgbackrest/mountpoint/backup/test1/20180911-105634F/pg_data/base/13805/2662.gz': Input/output error
```
This could be caused by network issues or possibly a misconfiguration of NFS.  I would try manually cp'ing a number of files over to the NFS mount and see if that works reliably.

Running with `--log-level-console=debug` may also be helpful, though I'm pretty sure I see where this error is coming from.

**Comment by renesepp** [comment]
> I'm not sure why we are getting so many errors shutting down the locals, but the root error is:
> 
> ```
> unable to open '/var/lib/pgbackrest/mountpoint/backup/test1/20180911-105634F/pg_data/base/13805/2662.gz': Input/output error
> ```
> This could be caused by network issues or possibly a misconfiguration of NFS. I would try manually cp'ing a number of files over to the NFS mount and see if that works reliably.
> 
> Running with `--log-level-console=debug` may also be helpful, though I'm pretty sure I see where this error is coming from.

Tweaked some NFS mount parameters and backup runs fine now, but at the end got ERROR: 
"ERROR: [047]: unable to create link '/var/lib/pgbackrest/mountpoint/backup/test1/latest': Input/output error"

Also changed parameter repo-type to cifs. Now it won't try to create link.
repo-type parameter need to be cifs when using NFS share for repository?

**Comment by dwsteele** [comment]
It should be possible to create symlinks on an NFS mount so `repo1-type=posix` should be used.

Using `repo1-type=cifs` is not a great plan because it disables directory fsyncs as well as symlinks.

**Comment by renesepp** [comment]
> It should be possible to create symlinks on an NFS mount so `repo1-type=posix` should be used.
> 
> Using `repo1-type=cifs` is not a great plan because it disables directory fsyncs as well as symlinks.
Did a little test:
ln -s test/1 test2/1
ln: failed to create symbolic link ‘test2/1’: Input/output error

So looks like our network NFS share does not support symlinks(nfs vers 2 btw)

Can we ignore the symlink error and use posix or stay with cifs parameter?

**Comment by dwsteele** [comment]
To be frank I would not run on NFS v2 at all -- that is an incredibly ancient version.  I wonder if this NFS service is being exposed by a Windows server somewhere.

You should be able to run with `repo1-type=cifs` if you must.  NFS v2 should be syncing all writes and any inconsistencies will be detected on restore.  You should be doing restore testing in any case.  I don't really recommend this configuration but some backups are better than none.

Ignoring the link error is not a good idea -- there are a few steps that won't be run if you do this.  While pgBackRest is able to recover these steps later your monitoring will be affected and it will generally cause confusion.

My advice -- upgrade to at least NFS v3 and enable the sync option.

**Comment by renesepp** [comment]
> To be frank I would not run on NFS v2 at all -- that is an incredibly ancient version. I wonder if this NFS service is being exposed by a Windows server somewhere.
> 
> You should be able to run with `repo1-type=cifs` if you must. NFS v2 should be syncing all writes and any inconsistencies will be detected on restore. You should be doing restore testing in any case. I don't really recommend this configuration but some backups are better than none.
> 
> Ignoring the link error is not a good idea -- there are a few steps that won't be run if you do this. While pgBackRest is able to recover these steps later your monitoring will be affected and it will generally cause confusion.
> 
> My advice -- upgrade to at least NFS v3 and enable the sync option.

Actually I got it wrong the NFS share indeed supports NFS v3 proto. 
Its actually HPE StoreOnce solution, no idea what solution is running background can be Windows for sure. 

Quick google about the error message relates to a Windows: https://github.com/winnfsd/vagrant-winnfsd/issues/66

I will ask from HPE why symlinks seems to fail on NFS mounts.

**Comment by renesepp** [comment]
> I'm not sure why we are getting so many errors shutting down the locals, but the root error is:
> 
> ```
> unable to open '/var/lib/pgbackrest/mountpoint/backup/test1/20180911-105634F/pg_data/base/13805/2662.gz': Input/output error
> ```
> This could be caused by network issues or possibly a misconfiguration of NFS. I would try manually cp'ing a number of files over to the NFS mount and see if that works reliably.
> 
> Running with `--log-level-console=debug` may also be helpful, though I'm pretty sure I see where this error is coming from.

Below input/output error game back...

2018-09-25 11:42:36.193 P01   INFO: backup file testdb.just.sise:/var/lib/pgsql/9.3/data/base/16387/19500_fsm (24KB, 99%) checksum 7424bbf23412a76b2a728a754b7a2582bf7fa89f
ERROR [041]: : raised from local-1 process: unable to open '/var/lib/pgbackrest/mountpoint/backup/l-rmpdb/20180923-043001F_20180925-043002D/pg_data/base/16387/181143_fsm': Input/output error': Input/output error

On a HPE StoreOnce events logs getting error: Too many open files handle on NAS share backup/l-rmpdb/20180923-043001F_20180925-043002D/pg_data/base/16387/181143_fsm': Input/output error

So all issues we had are related to a HPE StoreOnce backup solution, the linking error and above backup error.
Is there a way to backup pg_data to a one pack like pg_basebackup does, not every pg base file independently? 
We can close the case cause its not pgbackrest issue...

**Comment by dwsteele** [comment]
There's no way to do a tar-style backup with pgBackRest, but I'm not sure that would help anyway.

pgBackRest should only have 1 file per process open on the NFS volume and it looks like you have `process-max` set to 1.  WAL archiving will also open 1 file per process so during a backup you may use 2 even if `process-max` is set to 1.

My guess is some other process is using resources and pgBackRest is randomly exceeding the limit.

**Comment by Dizzy3339** [comment]
> I will ask from HPE why symlinks seems to fail on NFS mounts.

Did you ever get an answer from HPE on getting symlinks to work? We're having the exact same problem on the exact same device.

**Comment by renesepp** [comment]
Not an adequate answer, maybe you have better luck(basically they told that its a Linux problem). 
We use CIFS share on a HPE Storeonce instead. pgBackRest disables symlinks when backuping to CIFS.

**Comment by Dizzy3339** [comment]
> Not an adequate answer, maybe you have better luck(basically they told that its a Linux problem).
> We use CIFS share on a HPE Storeonce instead. pgBackRest disables symlinks when backuping to CIFS.

Okay thanks, I am thinking we might have to go down the same path. 

Their answer was pretty bad as I've never had this problem with any Linux or UNIX system in over 20 years of using them.

I'll let you know what answer we get. Appreciate your help.

**Comment by Dizzy3339** [comment]
> Not an adequate answer, maybe you have better luck(basically they told that its a Linux problem).
> We use CIFS share on a HPE Storeonce instead. pgBackRest disables symlinks when backuping to CIFS.

Answer we got back from HPE was that they had no documentation supporting symbolic links.

Oh well, I guess we are stuck with CIFs also.

Thanks for your help.

**Comment by dwsteele** [comment]
@Dizzy3339 @renesepp We would be OK with an option to disable symlinks in the repo, something like `repo1-link=n`, but we don't have the time to look at that right now.  If either of you would like to take a crack at it you are more than welcome.
