### ISSUE TITLE
PITR Issue with recovery to required time

### ISSUE THREAD

**Issue by AlexMartin12** [pgbackrest/pgbackrest#593]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.03
2. PostgreSQL version:
 9.6.9
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Linux db-primary 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
-bash-4.2$ cat /etc/pgbackrest.conf
[global]
log-level-stderr=off
log-timestamp=n
repo-path=/var/lib/pgbackrest
retention-diff=2
retention-full=2
start-fast=y

[main]
db-path=/var/lib/pgsql/9.6/data
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Full Database Backup Taken at Time0

Database Change 1 Made & Time1 (2018-07-05 15:32:51.267192+00)  Noted after change.
Database Change 2 Made & Time2 Noted after change.
Database Change 3 Made & Time3 Noted after change.

Incremental Backup Taken Now at Time3

PITR is not stopping at the point required ( Time1) . It ignores the point and recovers the database to the last transaction ( Time3) which is much further away from the required point.
[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/2374753/postgresql.conf.txt)

Resore/Recover Command used:
pgbackrest --stanza=main --delta --type=time "--target=2018-07-05 15:32:51.267192+00" --target-action=promote restore

**Comment by slardiere** [comment]
Could you rovide the recovery.conf file made by pgbackrest ? It should be named recovery.done after the promotion.
Maybe the command should be : 
`pgbackrest --stanza=main --delta --type=time --target="2018-07-05 15:32:51.267192+00" --target-action=promote restore`
 instead of yours, then the target would be correctly set up ?

**Comment by dwsteele** [comment]
You'll need to specify the full backup (`--set-`) if you want to play forward to time 1.  By default the latest backup is restored (the incremental after time 3) and it is not possible to play backward.

**Comment by AlexMartin12** [comment]
Thanks
