### ISSUE TITLE
Support Alternate Compression Library

### ISSUE THREAD

**Issue by bradnicholson** [pgbackrest/pgbackrest#596]
zlib is a pretty big CPU hog, it would be nice to support something less intensive such as lz4 or snappy.

Would you be open to contributions here?

**Comment by dwsteele** [comment]
Yes, we are very interested in having lz4 as a compression option. We did an evaluation a few months ago and were very impressed with the speed vs. compression ratio.  We like zstd better, but packages are not available for many distros yet, while lz4 has extensive support.

We considered adding support for lz4 this summer, but we are currently migrating the codebase from Perl to C and we're loathe to write Perl code if it can be avoided.

That said, we are planning to have archive-get and archive-push entirely migrated to C by the end of December.  That means we could be using lz4 for archive operations by then, with backup and restore to follow as they are migrated.

The gzip filters have already been migrated to C: https://github.com/pgbackrest/pgbackrest/tree/master/src/compress.  If you are interested in contributing lz4 filters that would be much appreciated.  The general filter interface is here: https://github.com/pgbackrest/pgbackrest/blob/master/src/common/io/filter/filter.h.  Here's an example of where the gzip filters are integrated into the archive-get code: https://github.com/pgbackrest/pgbackrest/blob/master/src/command/archive/get/file.c#L125.

Have a look.  We'll be happy to provide any support you need.

**Comment by dwsteele** [comment]
We have this in our backlog so I'm going to close the issue.
