### ISSUE TITLE
allow `--type` to filter output of `info` command

### ISSUE THREAD

**Issue by hunleyd** [pgbackrest/pgbackrest#600]
What do you think of allowing `--type` to filter the output of the `info` command? 

For example, `pgbackrest --type=full info` would be the command for 'show me all my full backups' .. instead of having to scroll up/down the output eyeballing it yourself?

Of course, you'd want to be able to use `--type=diff` and `--type=incr` as well and it should also work when `stanza` is specified..

**Comment by dwsteele** [comment]
What do you think @cmwshang?  If it's easy it might be worth doing in Perl, otherwise we can wait for the C port.

**Comment by cmwshang** [comment]
Devil is in the details so it's not as "easy" as you'd think. It's a good requested yet I would strongly suggest we wait until after we have ported it to C.

**Comment by dwsteele** [comment]
OK, agreed.  I've added this to the backlog at https://github.com/pgbackrest/pgbackrest/projects/2#card-13503164

I hope to start the C port of the info command soon, but we can't change the behavior as long as some code paths run through Perl which will probable be the case into December.

**Comment by dwsteele** [comment]
The `info` command has been migrated to C, but this is not a huge priority at the moment. Unless you want to take a whack at it?

**Comment by dwsteele** [comment]
@hunleyd PR #1651 has been submitted for this. You might want to have a look.
