### ISSUE TITLE
Patroni - Pgbackrest take backup from server out of the cluster

### ISSUE THREAD

**Issue by Elmo8** [pgbackrest/pgbackrest#601]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.05

2. PostgreSQL version: 10.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: centos 7

4. Did you install pgBackRest from source or from a package? from yum

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

[livepsql1]
db-path=/var/lib/pgsql/10/data
db-port=5432
db-host=livepsql1
retention-full=1

[global]
repo1-path=/var/lib/pgbackrest
backup-user=postgres
backup-cmd=/usr/bin/pgbackrest

7. Describe the issue:
I have a cluster of three postgres server with patroni and i want to get backup with pgbackrest that is installed into another server outside of that cluster. Is that possible? Do you have any guide to help me? 

Thanks

**Comment by dwsteele** [comment]
We don't have a guide for pgBackRest + Patroni, but I know people are using this combination.

I don't think there's anything special about the setup except as noted here: https://github.com/zalando/patroni/blob/master/docs/replica_bootstrap.rst (search for pgBackRest).

**Comment by uspen** [comment]
Using replicas with and without the Patroni does not affect the way pgbackrest is configured
