### ISSUE TITLE
Is there a way to disable checksums for each backup file

### ISSUE THREAD

**Issue by marceloslacerda** [pgbackrest/pgbackrest#604]
I'm considering on using pgbackrest for backing up a large database (more than a terabyte) however I'm concerned that running a checksum for each file transferred might make the process prohibitive. Is there a way to disable checksums for every file?

**Comment by sfrost** [comment]
Running a checksum is actually very cheap, certainly much cheaper than doing compression or encryption.  This is really something that all backup tools should be doing and every user should be expecting of their tools.

There's no way to disable checksum'ing and there's no plan to add one- it's extremely important to calculate and store the checksum to detect latent corruption in the repository and it's very cheap to do so, so there really isn't any real excuse not to.

pgBackRest is used with much, much larger systems than just a terrabyte and is able to be run in parallel across multiple CPUs to perform a backup.

I'd encourage you to try pgBackRest out and see if it meets your needs.  If you run into performance issues then it might be interesting to look into where the time is going; it's unlikely to be bottlenecked on checksuming- you're more likely to run out of i/o or network bandwidth or for something else (such as compression) to be dwarfing the CPU time.

**Comment by marceloslacerda** [comment]
Indeed doing a regular scp I'm finding that the network transfer is dominating the backup process.

**Comment by marceloslacerda** [comment]
I've noticed that the problem is related to ssh. Doing a netcat across the hosts we get a transfer rate of about 4 seconds for each 1GB of file, 2 seconds if I'm writing to /dev/null, Our network rate is supposed to be greater than 1Gbps so I'm guessing a large part of the transfer time is taken reading from disk.

Transferring trough ssh using a chacha20 (the fastest cypher we had available) we are able to transfer with 79-89Mbps throughput without disk write.

Is there anything that can be done to speed up the transfer?

**Comment by sfrost** [comment]
Have you tried running pgbackrest in parallel?

**Comment by cmwshang** [comment]
@marceloslacerda See https://pgbackrest.org/user-guide.html#parallel-backup-restore for details.

**Comment by marceloslacerda** [comment]
Thanks I'll try that. I managed to cut down some of the time to backup buy
enabling arcfour cipher on the ssh server and making it the default for
transfers initiated by the pgpbackrest user to the postgres host.

By using 3 cores and a weak cypher I'm expecting to take 1 hour to finish a
backup of 1TB.

**Comment by dwsteele** [comment]
1TB/hr with 3 cores is pretty reasonable throughput.

**Comment by marceloslacerda** [comment]
I did a little benchmarking to find the ideal number of workers for our servers here. Maybe someone else with find it useful.

[postgresql-benchmark.pdf](https://github.com/pgbackrest/pgbackrest/files/2484226/postgresql-benchmark.pdf)

**Comment by dwsteele** [comment]
Nice!  We have found that 32 processes is optimal on a 10Gb/s network when disk I/O is not bound, which usually means SSD-based.  That seems to be the same result you have gotten here.
