### ISSUE TITLE
Support archive_mode = always

### ISSUE THREAD

**Issue by jesperpedersen** [pgbackrest/pgbackrest#605]
It would be nice to have support for `archive_mode = always` in order to do backups of replicas.

**Comment by sfrost** [comment]
pgbackrest already supports backing up using replicas for most of the work, so I'm not quite sure what you're getting at here.

**Comment by cmwshang** [comment]
See https://pgbackrest.org/user-guide.html#standby-backup for more information.

**Comment by jesperpedersen** [comment]
Having `archive_mode = always` gives

Primary:
```
pgbackrest --type=full --stanza=main backup
ERROR [067]: : archive_mode=always not supported
```

Replica:
```
pgbackrest --type=full --stanza=main backup
ERROR [057]: : ERROR:  recovery is in progress
HINT:  pg_walfile_name() cannot be executed during recovery.:
select to_char(current_timestamp, 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_walfile_name(lsn), lsn::text, (select setting::int8 from pg_settings where name = 'wal_segment_size') from pg_start_backup('pgBackRest backup started at 2018-10-01 11:58:56', true, false) as lsn
```

This is against PostgreSQL 11Beta4 instances.

**Comment by cmwshang** [comment]
@jesperpedersen Correct. archive_mode = always is not supported.

**Comment by sfrost** [comment]
That's correct, archive_mode = always isn't supported, but we don't need to support archive_mode=always to perform backups from replicas.  See Cynthia's link to the documentation about how to perform a backup which uses a replica for most of the work.

We may support archive_mode = always in the future but it's not needed to be able to perform a backup from a replica.
