### ISSUE TITLE
option 'log-level-file' not valid for command 'remote' 

### ISSUE THREAD

**Issue by powzer** [pgbackrest/pgbackrest#606]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.05

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Master DB Host: Oracle Linux 7.3
Standby DB Host: Oracle Linux 7.3
Restore Target DB Host: Oracle Linux 7.3
Backup host:  RHEL 7.3

4. Did you install pgBackRest from source or from a package? Installed from PGDG rpm.

5. Please attach the following as applicable:

BACKUP HOST pgbackrest.conf
[stanza1]
pg1-host=master-db
pg2-host=standby-db
pg1-host-user=db_user
pg2-host-user=db_user
pg1-path=/path/to/pg_data
pg2-path=/path/to/pg_data
repo1-retention-full=2
repo1-retention-archive-type=incr
repo1-retention-archive=4

[global]
start-fast=y
stop-auto=y
process-max=24
repo-path=/backup
compress-level=1
archive-timeout=10800

RESTORE TARGET pgbackrest.conf
[stanza1]
db-path=/path/to/pg_data
process-max=24
repo1-host=backup-host
repo1-host-user=backup-user

7. Describe the issue:

I have configured a two node cluster to backup to a remote pgbackrest host.  Backups and restores on the master and standby work as expected.  I'm attempting to restore a backup of this cluster on a third database host using this command:

pgbackrest --stanza=stanza1 --set=latest --log-level-console=trace restore

which returns the error:

ERROR [031]: : remote process on 'backup-host' terminated unexpectedly [031]: ERROR: [031]: option 'log-level-file' not valid for command 'remote'

This option is not being set anywhere that I can find.  I've attached the console output from the restore command:
[pgbackrest-restore.log](https://github.com/pgbackrest/pgbackrest/files/2436606/pgbackrest-restore.log)

Thanks

**Comment by dwsteele** [comment]
Are you sure you updated the version of pgBackRest on your repo host to 2.05?

This option was added to the remote command in 2.05 and since option parsing happens before the protocol handshake this error might indicate mismatched versions.

**Comment by powzer** [comment]
Yes, that was the issue.  The repo host was still on 2.04.  

Thanks

**Comment by dwsteele** [comment]
Glad to hear it.

We have plans to improve this error message, but it needs to wait on some other work we are doing.
