### ISSUE TITLE
pgbackrest  restore remote host or different place

### ISSUE THREAD

**Issue by forall** [pgbackrest/pgbackrest#611]
Hi,
We want to use pgbackrest for backup our postgresql-9.3 environment (~250GB database), but it possible:
- restore database from dedicated repository host to another host or in different place on backup database without stop main cluster?
- we want to do that scenario
- repo-host 
- db1  - main db for backup
- db2 -  slave in different location - we need send database from db1? - I found in documentation answer - pgbackrest --stanza=demo --delta restore :-) https://pgbackrest.org/user-guide.html#replication/hot-standby

**Comment by dwsteele** [comment]
Yes, you found the right place in the documentation.  This will restore a copy of the database from the repository to a new server.  The primary database is not required to make this work.

**Comment by forall** [comment]
dwsteele - do you plan add a feature to remote restore with pgbackrest?
