### ISSUE TITLE
 fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by nevzatgul** [pgbackrest/pgbackrest#612]
Hi,
pbackrest and postgresql  is same host, My conf file is follow 

[postgres@lnxegzoz06s01 ~]$ cat /etc/pgbackrest.conf
[pg1]
pg1-path=/data/postgreSQL/9.6/
pg1-socket-path=/tmp/
pg1-host-user=postgres
pg1-host=localhost
pg1-port=5432

[global]
repo-path=/data/pgbackrest
retention-full=2

But pgbackrest check command is failed. 

[postgres@lnxegzoz06s01 ~]$  pgbackrest     --stanza=pg1     --log-level-console=info     check
2018-10-16 17:32:54.215 P00   INFO: check command begin 2.05: --log-level-console=info --pg1-host=localhost --pg1-host-user=postgres --pg1-path=/data/postgreSQL/9.6/ --pg1-port=5432 --pg1-socket-path=/tmp/ --repo1-path=/data/pgbackrest --stanza=pg1
ERROR [056]: : raised from remote process on 'localhost': fe_sendauth: no password supplied
ERROR [056]: : Database: 9.6 6590569714573435594 raised from remote process on 'localhost': fe_sendauth: no password supplied
2018-10-16 17:32:55.109 P00   INFO: check command end: aborted with exception [056]

Please help me!

**Comment by dwsteele** [comment]
You'll need to setup passwordless SSH as documented here: https://pgbackrest.org/user-guide.html#repo-host/setup-ssh

**Comment by nevzatgul** [comment]
My ssh passwordless no problem ,

[backrest@lnxegzoz06s01 ~]$ ssh postgres@lnxegzoz06s01
Last login: Wed Oct 17 09:27:01 2018 from lnxegzoz06s01
[postgres@lnxegzoz06s01 ~]$ ssh backrest@lnxegzoz06s01
Last login: Wed Oct 17 09:28:45 2018

Both user can ssh with  passwordless.

**Comment by dwsteele** [comment]
Closing since there has been no response.  Let us know if this is still and issue.
