### ISSUE TITLE
[Q] pgbackrest support EDB officially?

### ISSUE THREAD

**Issue by hellower** [pgbackrest/pgbackrest#614]
pgbackrest is fully functional with postgresql and edb very well  by self testing.
Does pgbackrest officially support edb database (cf. enterprisedb.com)?

sorry for poor english.

**Comment by dwsteele** [comment]
pgBackRest is only tested and officially supported on the open-source community version.

That said, we haven't see any issues running pgBackRest on EDB AS and a number of people do it.

**Comment by hellower** [comment]
Thanks.
