### ISSUE TITLE
AWS instance roles are not used properly.

### ISSUE THREAD

**Issue by progre55** [pgbackrest/pgbackrest#616]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.05

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS 7

4. Did you install pgBackRest from source or from a package?
from package

5. N/A

7. Describe the issue:
In AWS, if running from within an AWS EC2 instance, instead of using an access/secret keypair, you can attach an instance role, which gives you IAM permissions to different AWS resources. In this case, S3.
With any other libraries using AWS, you can simply provide no (empty) access/secret keypair, and they try to connect to AWS directly, which succeeds if your instance has the proper role permissions.

We would like to utilise that feature, instead of having our credentials in the config file.
However, when run with no `repo1-s3-key` and `repo1-s3-key-secret`, pgbackrest complains:
```
# pgbackrest --stanza=my-test-db --log-level-console=info restore
ASSERT [025]: : option repo1-s3-key is required
2018-10-18 14:03:08.301 P00   INFO: restore command end: aborted with exception [025]
```

The question is, is it possible to run pgbackrest with instance roles instead of AWS credentials? If not, would it be possible to request for that feature?

**Comment by dwsteele** [comment]
We currently use ScallityS3 for testing and it does not support this feature.  However, we are working on a new test harness that will allow us to test against the full range of S3 features so we'll be able to support this feature (and others).

I can't give you an exact release date, but the feature should be available in the next few months.
