### ISSUE TITLE
Unable to set ownership 

### ISSUE THREAD

**Issue by jasonodonnell** [pgbackrest/pgbackrest#624]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.0X

2. PostgreSQL version:
All versions

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL7 OpenShift Container Platform

4. Did you install pgBackRest from source or from a package?
PGDG and Crunchy Packages

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

```
ERROR [088]: : unable to set ownership for '/pgdata/backrest-full-restored/base': Operation not permitted
```

7. Describe the issue:

BackRest is trying to alter group permissions of files owned by another container.  On OpenShift this is not permitted due to security constraints on the running containers.  It would be helpful if there was a way to stop BackRest from altering ownership of files to avoid this issue.

**Comment by sfrost** [comment]
There's a few things here which are at least concerning/confusing to me:

First- per discussion with Jason, pgbackrest is being run as 'postgres', so should pgbackrest really be trying to change the ownership of anything...?  I didn't think we did in that case.

Second- Also according to Jason, the files that pgbackrest restores are actually owned by the user/group that the backup was done with, in which case, we shouldn't need to actually chown the files anyway, so why is pgbackrest trying to..?  Is it possible that pgbackrest is confused and thinks that the 'postgres' user isn't the user that owns the files post-restore..?  Maybe because of an issue with etc/passwd or similar?

Just some thoughts.  I can see some possible independent value in being able to explicitly tell pgbackrest to not try to chown anything, but it seems like we shouldn't be trying to do this chown in the first place...

**Comment by jasonodonnell** [comment]
Here's just a little bit more insight into what we're seeing technically:

```
bash-4.2$ ls -la
total 8
drwxr-x---. 4 postgres root 109 Nov 19 15:20 .
drwxr-x---. 3 postgres root  16 Nov 19 15:18 ..
drwxr-x---. 3 postgres root  72 Nov 19 15:20 20181119-152022F
drwxr-x---. 3 postgres root  18 Nov 19 15:20 backup.history
-rw-r-----. 1 postgres root 956 Nov 19 15:20 backup.info
-rw-r-----. 1 postgres root 956 Nov 19 15:20 backup.info.copy
lrwxrwxrwx. 1 postgres root  16 Nov 19 15:20 latest -> 20181119-152022F
bash-4.2$ id
uid=1000210000(postgres) gid=0(root) groups=0(root),1000210000(postgres)

bash-4.2$ chown postgres:postgres backup.history/
chown: changing ownership of 'backup.history/': Operation not permitted
```

**Comment by sfrost** [comment]
Just to be clear, that isn't actually the chown that pgbackrest is doing, is it?  If anything, we should be trying to do a chown to postgres:root, since that's what the owner/group was when the backup was done, right..?

**Comment by dwsteele** [comment]
It seems clear that pgBackRest is setting ownership even when it does not need to.  We'll fix that.

It may also be a good idea to warn on ownership issues rather than throwing a hard error.  We can also add an option to suppress the warnings.

**Comment by dwsteele** [comment]
Committed some of this in e73416e9e391.  At least be smart enough to not call chown() when the permissions won't be changed.

@jasonodonnell , it would be helpful to confirm from your original example that chown'ing a file owned by postgres:root to postgres:root will error in this environment (that was Stephen's question above as well).  If that's not the case then this commit won't work for you.

**Comment by jasonodonnell** [comment]
@dwsteele chowning`postgres:root` worked fine and I was able to find the problem with `chown postgres:postgres` (believe I briefed you on this but you can find the fix here https://github.com/CrunchyData/crunchy-containers/pull/913).

What I believed backrest was doing was trying to change the permissions of a file from `postgres:root` to `postgres:postgres`.  Even if that's the case (doesn't seem so though) it works now after my bug fix.

**Comment by dwsteele** [comment]
Yes, that's what I think as well -- and it should be able to do so.  It certainly works in my tests.

Hmmm - so what are we fixing in pgBackRest now?

**Comment by jasonodonnell** [comment]
In the end I don't think this was a pgBackRest problem.  Originally I had thought it was being too aggressive with permission changes and would have liked an option to not do that but seems like a nonissue to me personally.  Thoughts?

**Comment by dwsteele** [comment]
This particular issue is solved so let's just close it.
