### ISSUE TITLE
Issue with User Guide: S3 Support Section - I get Error: TemporaryRedirect - Please re-send this request to the specified temporary endpoint.

### ISSUE THREAD

**Issue by pritammobisoft** [pgbackrest/pgbackrest#627]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **2.07**

2. PostgreSQL version: **9.6**

3. Operating system/version: **Ubuntu 18.04 on AWS**

4. Did you install pgBackRest from source or from a package? **Source**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) - Attached

7. Describe the issue:

The S3 endpoint mentioned in the docs doesn't work for the Singapore region. 

From the docs:

`repo1-s3-endpoint=s3.amazonaws.com`

If this value is used I get S3 error: `<Code>TemporaryRedirect</Code><Message>Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.</Message>`

But If I change the endpoint to: 

`repo1-s3-endpoint=s3-ap-southeast-1.amazonaws.com`

It works correctly. 

[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/2616817/pgbackrest.conf.txt)

**Comment by dwsteele** [comment]
`s3.amazonaws.com` is an alias for `us-east-1` according to https://docs.aws.amazon.com/general/latest/gr/rande.html so I'm not surprised that it didn't work.

We'll try to make it clearer in the docs that this is just a sample configuration.

**Comment by pritammobisoft** [comment]
Ok. Thanks for the clarification. Since there are 2 properties in the config:

```
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-region=us-east-1
```

I (incorrectly) assumed that the program derives the API endpoint automatically from these 2 settings. But then got the correct endpoint after Googling a bit. Hence posted this issue for future Google Searches.

**Comment by dwsteele** [comment]
Clarified this in 977506b44615cc9d9.  Hopefully that will help users in the future.

**Comment by pritammobisoft** [comment]
Thanks.
