### ISSUE TITLE
Feature Request: Determine correct backupset during Point in Time Restore/Recover

### ISSUE THREAD

**Issue by guruguruguru** [pgbackrest/pgbackrest#628]
Hi together,

first: Thanks for the great work everyone!

We sometimes have to use point-in-time recovery and if you just use the --type=time with the according timestamp it can happen (as it is described in the docs) that pgbackrest uses a backupset that is newer than the timestamp used so we have to manually choose a backupset (--set) that was created before the timestamp. It would be great if pgbackrest could determine which backup is needed to get to the chosen timestamp by itself.

Regards,
Dennis

**Comment by dwsteele** [comment]
This is a planned feature and is already in the backlog: https://github.com/pgbackrest/pgbackrest/projects/2#card-8956672.  I have linked this issue in as well.

It's a little trickier than it sounds because we need to parse the date the way postgres would and the database is not up to help us.

**Comment by cmwshang** [comment]
Committed: https://github.com/pgbackrest/pgbackrest/commit/495dec44f0f512478ac942091ca2a29c60ad4911
