### ISSUE TITLE
Perl DBD::pg still require for run ?

### ISSUE THREAD

**Issue by tigerfoot** [pgbackrest/pgbackrest#629]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.07

2. PostgreSQL version: 10.(1-6)

3. Operating system/version : openSUSE Leap 15.0

4. Did you install pgBackRest from source or from a package?
From package build here 
https://build.opensuse.org/package/show/server:database:postgresql/pgbackrest

5. Describe the issue:
I'm the maintainer of this package and during preparation of pgbackrest 2.06 it seems I made a mistake but I'm not 100% sure.

For the build I've all Perl requires as the following

BuildRequires:  openssl-devel
BuildRequires:  perl
BuildRequires:  perl-libxml-perl
BuildRequires:  perl(DBD::Pg)
BuildRequires:  perl(IO::Socket::SSL)
BuildRequires:  perl(Digest::SHA)
BuildRequires:  perl(JSON::PP)

Now that pgbackrest once builded should be an single autonomous binary I've removed the previous Requires I had like
-Requires:       perl
-Requires:       perl-libxml-perl
-Requires:       perl(DBD::Pg)
-Requires:       perl(IO::Socket::SSL)
-Requires:       perl(Digest::SHA)
-Requires:       perl(JSON::PP)
 
Today on a fresh machine (yep my bad to not have test that before) I've installed pgbackrest and it failed to run due to missing perl-DBD-pg module. (the other one being most of the time already installed).

So could you confirm that what is needed as BuildRequires is still needed to make the pgbackrest binary work ?

Thanks to help me to make the package perfect .

**Comment by dwsteele** [comment]
The Perl code is included in the C binary and embedded Perl is used when a command is executed that is not migrated to C, which right now means most of them.

For now, all these modules are still required.  We'll be reducing the requirements as we migrate functionality.

**Comment by tigerfoot** [comment]
Thanks a lot @dwsteele for the clarification. I will bring them back to my package.
