### ISSUE TITLE
Info output breaks visual backup chronology after --stanza-upgrade

### ISSUE THREAD

**Issue by rustprooflabs** [pgbackrest/pgbackrest#630]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.07

2. PostgreSQL version:  Upgraded 9.5.15 to 11.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:  Ubuntu Linux 16.04

4. Did you install pgBackRest from source or from a package?  Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Output from command in question:

```
~$ sudo -u pgbackrest pgbackrest --stanza=pgdev01 info
stanza: pgdev01
    status: ok
    cipher: none

    db (current)
        wal archive min/max (11-2): 0000000100000000000000CA / 0000000100000000000000CC

        full backup: 20181202-132211F
            timestamp start/stop: 2018-12-02 13:22:11 / 2018-12-02 13:23:37
            wal start/stop: 0000000100000000000000CA / 0000000100000000000000CA
            database size: 190.8MB, backup size: 190.8MB
            repository size: 36.8MB, repository backup size: 36.8MB

        incr backup: 20181202-132211F_20181202-132524I
            timestamp start/stop: 2018-12-02 13:25:24 / 2018-12-02 13:25:34
            wal start/stop: 0000000100000000000000CC / 0000000100000000000000CC
            database size: 190.8MB, backup size: 18.7MB
            repository size: 36.8MB, repository backup size: 16.3MB
            backup reference list: 20181202-132211F

    db (prior)
        wal archive min/max (9.5-1): 00000001000000000000001C / 000000040000000000000062

        full backup: 20180622-114546F
            timestamp start/stop: 2018-06-22 11:45:46 / 2018-06-22 11:47:03
            wal start/stop: 00000001000000000000001C / 00000001000000000000001C
            database size: 49.8MB, backup size: 49.8MB
            repository size: 20.1MB, repository backup size: 20.1MB

        full backup: 20180622-140134F
            timestamp start/stop: 2018-06-22 14:01:34 / 2018-06-22 14:02:45
            wal start/stop: 000000040000000000000021 / 000000040000000000000021
            database size: 49.8MB, backup size: 49.8MB
            repository size: 20.1MB, repository backup size: 20.1MB
```

7. Describe the issue:

During normal use of pgbackrest, the `info` command outputs the details of the stanza's backups in chronological order with the most recent backup being output last.  This puts the most time-relevant information easily accessible to the end user running the command.

This chronological output breaks after `--stanza-upgrade` has been ran and new backups are taken from the upgraded pg server.  The `db (current)` block gets printed first (with its backups in chronological order), then the `db (prior)` block gets printed.  By printing `db (prior)` second this puts the latest backups under `db (current)` somewhere in the middle of the output.

**Comment by dwsteele** [comment]
That definitely make sense to us and luckily we don't guarantee that the text format won't change between versions.

We'll try to get this in for the next release.

**Comment by dwsteele** [comment]
Committed at 35bbb5bd6. Thanks for the suggestion!
