### ISSUE TITLE
Multiple status files being generated on severe error

### ISSUE THREAD

**Issue by fpa-postgres** [pgbackrest/pgbackrest#633]
1. pgBackRest version: 2.07

2. PostgreSQL version: 10.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL 7

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) -

------ pgbackrest.conf-------------
[pg-node-1]
#xpg1-host=
pg1-path=/apps/postgres/data
pg1-socket-path=/tmp
pg1-port=5432
pg1-host-user=postgres
pg1-host-cmd=/usr/bin/pgbackrest
archive-async=y
archive-push-queue-max=107374182400
process-max=10
#repo1-host-user=postgres

[global]
repo1-host=findp-alln-prd-01
repo1-host-cmd=/usr/bin/pgbackrest
repo1-host-user=postgres
repo1-path=/apps/postgres/backup
#repo-cipher-type=aes-256-cbc
#repo1-cipher-
pass=
process-max=10
repo1-retention-full=2
---------------------
----------------------------- postgrtesql.conf------
archive_command = '/usr/bin/pgbackrest --stanza=pg-node-1 --config=/apps/postgres/pgbackrest.conf archive-push %p'
wal_level = logical                     # minimal, replica, or logical
#wal_compression = off                  # enable compression of full-page writes
#wal_log_hints = off                    # also do full page writes of non-critical updates
wal_buffers = 16MB                      # min 32kB, -1 sets based on shared_buffers
max_wal_size = 8GB
min_wal_size = 4GB
checkpoint_completion_target = 0.9      # checkpoint target duration, 0.0 - 1.0
checkpoint_timeout = 10min              # range 30s-1d
archive_mode = on               # enables archiving; off, on, or always
                                # (change requires restart)
max_wal_senders = 20            # max number of walsender processes
max_replication_slots = 20      # max number of replication slots
seq_page_cost = 1.0                     # measured on an arbitrary scale
random_page_cost = 2.0                  # same scale as above
min_parallel_table_scan_size = 1GB
min_parallel_index_scan_size = 100MB
effective_cache_size = 1100GB
----------

7. Describe the issue:
  PGBACKREST Missed Archiving Some WAL Files. Pls refer to attached file for detailed info. Any suggestion on this will help.

Thanks
[PGBACKREST WAL FILE ISSUE.txt](https://github.com/pgbackrest/pgbackrest/files/2650316/PGBACKREST.WAL.FILE.ISSUE.txt)

**Comment by dwsteele** [comment]
These are some pretty odd errors.  The only thing I can think of is that you are archiving multiple systems into the same stanza -- which means they would have the same system id.  Perhaps replicas that have been promoted?  

It also looks like you might be sharing a spool directory between two clusters.

All the config files are for `pg-node-1` but the logs (and errors) are all for `pg-node-5`.  You'll need to provide config files for `pg-node-5` and `findp-alln-prd-01` at the least if we want to see what went wrong here.

Your path structure is very unusual.  Is this a container environment?  If so are you sharing any volumes?

**Comment by fpa-postgres** [comment]
Yes, we are archiving from multiple systems to the same host, but to different stanzas. 

Thanks

**Comment by dwsteele** [comment]
You'll need to provide the information we requested above if you want us to have a look: config files for pg-node-5 and findp-alln-prd-01.

**Comment by fpa-postgres** [comment]
Below are conf files of pg-node-5 and findp-alln-prd-01.
---pgbackrest.conf - pg-node-5---------
[pg-node-5]
pg1-path=/apps/postgres/data
pg1-socket-path=/tmp
pg1-port=5432
pg1-host-user=postgres
pg1-host-cmd=/usr/bin/pgbackrest
archive-async=y
archive-push-queue-max=107374182400
process-max=10

[global]
repo1-host=findp-alln-prd-01
repo1-host-cmd=/usr/bin/pgbackrest
repo1-host-user=postgres
repo1-path=/apps/postgres/backup
pass=
process-max=10
repo1-retention-full=2
--------------------

------ findp-alln-prd-01 -pgbackrest.conf-----------
[global]
repo1-host-cmd=/usr/bin/pgbackrest
repo1-host-user=postgres
repo1-path=/apps/postgres/backup
pass=
process-max=10
repo1-retention-full=2

[pg-node-1]
pg1-host=finpg-rcdn-prd-01
pg1-path=/apps/postgres/data
pg1-socket-path=/tmp
pg1-port=5432
pg1-host-user=postgres
pg1-host-cmd=/usr/bin/pgbackrest
archive-async=y
archive-push-queue-max=107374182400
process-max=10

[pg-node-5]
pg1-host=finpg-rcdn-prd-05
pg1-path=/apps/postgres/data
pg1-socket-path=/tmp
pg1-port=5432
pg1-host-user=postgres
pg1-host-cmd=/usr/bin/pgbackrest
archive-async=y
archive-push-queue-max=107374182400
process-max=10
----------------------------------

Also, we  are noticing that every time disk is full on host, pgbackrest gets messed up. Could you please suggest some pointers. 

ASSERT: [025]: multiple status files found in '/var/spool/pgbackrest/archive/pg-node-2/out' for WAL segment '00000001000009DA00000097'
        STACK TRACE:
        command/archive/common:archiveAsyncStatus:47:(debug log level required for parameters)
        command/archive/push/push:cmdArchivePush:(debug log level required for parameters)
        main:main:(debug log level required for parameters)


Thanks

**Comment by dwsteele** [comment]
Hmm, not sure why a full disk would cause this to happen.  We'll have a look at it, but it may be filesystem issues that are beyond our control.  On the other hand, it might be a good idea to retry in this scenario rather than giving a hard error.  We've never seen this error in production before so it has never come up.

But -- the best thing is to use monitoring so your disk does not fill up.  If this is happening on a regular basis that is a very bad thing.

**Comment by fpa-postgres** [comment]
Thanks for the reply. We are surprised to see this happen as well. Yes, we do have monitoring setup for disk space.

**Comment by dwsteele** [comment]
I'm not sure what is causing your problem, but we'll add retries here since it can't hurt, and in your case may help.

**Comment by dwsteele** [comment]
I see how this is happening now.  If a severe error happens in the middle of async processing it can cause all the files in the queue to get .error files even if some of them have already had .ok files saved.  Then, pgBackRest is not happy when it sees .ok and .error files for the same file on retry.

It seems like both need to be addressed.  Even if we fix the bug that is causing multiple status files there may be other ways that .ok and .error could exist -- we should error and retry in that case.

**Comment by dwsteele** [comment]
@fpa-postgres @hunleyd This has been fixed at 8f6d324b2c.  @fpa-postgres Please let me know if you want to appear in the release notes as other than `fpa-postgres`.

**Comment by fpa-postgres** [comment]
Thankyou, David.


We will checkout and verify in our hosts. Is this commit part of v2.08 Release<https://pgbackrest.org/release.html#2.08> as I see it added in master branch.  Yes, please do add in the release notes.


Thanks

Vidhya

________________________________

**Comment by dwsteele** [comment]
This commit will part of 2.09 which has not been released yet.

**Comment by fpa-postgres** [comment]
Sounds good. We will embed patch fix in our current version (2.07). Hope that works.


Thanks

Vidhya

________________________________
