### ISSUE TITLE
Different backup path for each stanza

### ISSUE THREAD

**Issue by rtammineni** [pgbackrest/pgbackrest#639]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.07

2. PostgreSQL version:
9.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.4.1708

4. Did you install pgBackRest from source or from a package?
source

5. Please attach the following as applicable:
postgresql.conf:
archive_mode = on
archive_command = 'pgbackrest --stanza=cluster01 archive-push %p && cp %p /pg_archive/pgsql-9.4/data/%f
wal_level = hot_standby
max_wal_senders = 20
listen_addresses = '*'
port = 5432

pgbackrest.conf:
[cluster01]
pg1-host=db1-host-pri
pg1-path=/pg_data/pgsql-9.4/data
pg2-host=db1-host-stdby
pg2-path=/pg_data/pgsql-9.4/data

[cluster02]
pg1-host=db2-host-pri
pg1-path=/pg_data/pgsql-9.4/data
pg2-host=db2-host-stdby
pg2-path=/pg_data/pgsql-9.4/data

[global]
backup-standby=y
process-max=4
repo1-cipher-type=none
repo1-path=/pgbackup/ERMS/ERMSPGDB-01
repo1-retention-diff=2
repo1-retention-full=2
start-fast=y
stop-auto=y

[global:archive-push]
compress-level=3

7. Describe the issue:

We have around 10 Postgres database clusters running on different hosts.  We want to configure one centralized pgbackrest backup host but we want to configure different backup directory for each cluster due to size of each database (each database is ~3TB).  Is it possible to define different backup directory for each stanza/cluster? 

Ex: 
cluster01 - repo1-path=/pgbackup/ERMS/ERMSPGDB-01
cluster02 - repo2-path=/pgbackup/ERMS/ERMSPGDB-02
cluster03 - repo3-path=/pgbackup/ERMS/ERMSPGDB-03

**Comment by dwsteele** [comment]
Yes -- the `repo1-path` option can be specified per stanza, e.g.:
```
[cluster02]
repo1-path=/pgbackup/ERMS/ERMSPGDB-02
pg1-host=db2-host-pri
pg1-path=/pg_data/pgsql-9.4/data
pg2-host=db2-host-stdby
pg2-path=/pg_data/pgsql-9.4/data
```

**Comment by rtammineni** [comment]
Thank you so much David! 

It worked.  I have one more question, we want restore one large database (~1.4TB) from one cluster to another cluster.  
-- This is the main cluster and we are storing the backups under "/pgbackup/ERMS/ERMSPGDB-01"
[cluster01]
repo1-path=/pgbackup/ERMS/ERMSPGDB-01
pg1-host=db1-host-pri

-- Second cluster
[cluster04]
repo1-path=/pgbackup/ERMS/ERMSPGDB-04
pg1-host=db4-host-pri

We want to restore database from cluster01 to cluster04.  There are two more databases in 04 and we want to keep those two and restore the new database from 01 to 40 cluster.  Please let me know how can we do it.

**Comment by dwsteele** [comment]
Do you mean a single database within a cluster?  Postgres does not support that.

You can restore a single database with pgBackRest, but not into a running cluster.  See https://pgbackrest.org/user-guide.html#restore/option-db-include.

If you want to restore a single database into a cluster then use `pg_dump`/`pg_restore`.

**Comment by rtammineni** [comment]
Thank you David!

I want to restore single database within a different cluster.  But its not working.  We useed pg_dump and restore to dump single database.
