### ISSUE TITLE
Restoring between major versions of Postgres

### ISSUE THREAD

**Issue by vahtos** [pgbackrest/pgbackrest#640]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **pgbackrest/bionic-pgdg,now 2.07-1.pgdg18.04+1 amd64 [installed]**

2. PostgreSQL version: **10 and 11**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: **Ubuntu 18.04.1**

4. Did you install pgBackRest from source or from a package? **Apt package**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

As far as I understand, you cannot restore a cluster that is running a newer (major) version of Postgres from a backup of the same cluster that is from an older (major) version of Postgres.

After migrating from Postgres version 10 to 11, I left version 10 installed and have done a stanza-upgrade. The company that I work for plans to migrate to using Postgres (and use Pgbackrest) in the future. It is a consulting company, so it is important to have the ability to restore the cluster to any point in time and be able to see a snapshot of the databases at that time (it is possible a client may ask us to "revert a change" or want to know something like "well what did it look like at X time").

So my question is, would it be acceptable to keep the older install of Postgres and just delete the data (to save space), so that I can restore an instance of Postgres 10 (in this case) to say, a year ago, if needed? Is there any potential issue with doing this, or any reason this would not be recommended?

**Comment by dwsteele** [comment]
> As far as I understand, you cannot restore a cluster that is running a newer (major) version of Postgres from a backup of the same cluster that is from an older (major) version of Postgres.

Correct.

> So my question is, would it be acceptable to keep the older install of Postgres and just delete the data (to save space), so that I can restore an instance of Postgres 10 (in this case) to say, a year ago, if needed? Is there any potential issue with doing this, or any reason this would not be recommended?

Yes, this is fine.  Being able to restore backups from before a stanza-upgrade is supported and having multiple versions of Postgres installed is normal.  There are a number of reasons why you might want to do this.

If you want to restore backups from a year back, you'll need a much longer retention than is typical, but if you have the space it's not an issue.

Also, whatever your use case is, be sure to test it.

**Comment by vahtos** [comment]
Excellent. Thank you so much for the quick reply, and the awesome tool!

**Comment by dwsteele** [comment]
You are welcome.  Glad you like it!
