### ISSUE TITLE
Forcing a backup to expire

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#641]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.07
2. PostgreSQL version:
9.6.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 6.9 x64

4. Did you install pgBackRest from source or from a package?
From the Postgresql.org package.

5. Please attach the following as applicable:
N/A

7. Describe the issue:

How do I manually purge a backup set (full, incrementals and WALs) even though the retention period hasn't been reached yet?

**Comment by dwsteele** [comment]
You can't expire a backup set in the middle, but you can expire the oldest ones by running `expire` with a retention.  This will keep only the last two full backups:
```
pgbackrest --stanza=xxx --repo1-retention-full=2 expire
```

**Comment by cmwshang** [comment]
The settings you have in pgbackrest.conf will not be modified. Using the --repo1-retention-full on the command line simply overrides the setting in the config file for that one execution of the command.
