### ISSUE TITLE
Best approach to move from local to nfs storage live

### ISSUE THREAD

**Issue by laurentiuspurba** [pgbackrest/pgbackrest#646]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: **pgBackRest 2.03**

2. PostgreSQL version: **9.3**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

- Database server (Master): CentOS 7.4
- Database server (Slave): CentOS 7.4
- Repository host server: CentOS 7.4

4. Did you install pgBackRest from source or from a package?
From the source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```[app]```
```pg1-host=DB-MASTER```
```pg1-host-user=postgres```
```pg1-path=/mnt/pg-data/data```
```pg1-port=5439```
``` ```
```[global]```
```repo1-path=/var/lib/pgbackrest```
```repo1-retention-full=2```
```repo1-retention-diff=6```
```start-fast=y```
```stop-auto=y```
```process-max=3```
``` ```
```[global:archive-get]```
```process-max=3```
```compress-level=3```
``` ```
```[global:archive-push]```
```compress-level=3```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
```archive_command = /bin/pgbackrest --stanza=app archive-push %p'```
``` ```
```archive_mode = on ```
``` ```
```listen_addresses = 'xxx.xxx.xxx.xxx'```
```max_wal_senders = 10```
```wal_level = hot_standby```
```port = 5439```
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
This is actually a question not an issue.
Currently, I have pgBackrest working on local storage. Since our database size is increasing rapidly, I am creating nfs shared storage that will be used by pgbackrest.

What I have done so far is synching **archive** and **backup** directories from local to that nfs shared. I also stopped cron for running the backup, so I don't have to worry about out of sync in backup directory.

The issue right now is with archive directory. I would like to know, what is the best approach to switch from local to nfs storage, so the replication is still working while I switch from local to nfs storage.

Any pointers and helps are appreciated.

Thank you,
-Laurentius

**Comment by dwsteele** [comment]
First, there is a critical bug present in 2.03 that was fixed in 2.04.  You should upgrade as soon as possible, or set `resume=n`.  See https://pgbackrest.org/release.html#2.04 for details.

The safest way to copy a repo is:
1) Use rsync to create an initial copy of the repo
2) Run rsync again to make the copy as update-to-date as possible
3) Set `archive_command=false` (this will produce errors in the postgres log but no archive will be lost)
4) Run rsync one last time
5) Update pgbackrest.conf to the new path
6) Set `archive_command` back to the previous value

**Comment by laurentiuspurba** [comment]
Hello David,

Thank you for your response.
Is it correct setting `archive_command = false` resulting slave database will be delayed? If that's the case, since my application also reads from slave database, do you think I should point slave database DNS to master DB?

Again, it's excellent response, I didn't think about step 3. Thank you.

**Comment by dwsteele** [comment]
`archive_command=false` will not affect replication to the standby.  They are entirely independent.  

You will want to minimize the time that you have this set, however, since WAL will build up in the `pg_xlog` directory.
