### ISSUE TITLE
Client-side encryption?

### ISSUE THREAD

**Issue by baburdick** [pgbackrest/pgbackrest#647]
I'm currently using wal-e, gnupg, and some bash/tty gymnastics to encrypt archive data locally before pushing to S3, so that I don't need to depend on AWS's unverifiable promise that my data is encrypted (thus closing off a possible avenue for data leakage).

Does pgbackrest support client-side encryption? I haven't been able to find clear documentation on how to accomplish this with pgbackrest. I'd like to switch, but can't until I have a reliable way to do this. Anyone have a tutorial they're hiding somewhere?

**Comment by baburdick** [comment]
Perhaps I misunderstand the documentation (https://pgbackrest.org/user-guide.html#quickstart/configure-encryption). Does this configure pgbackrest to conduct the encryption itself? Or does it configure pgbackrest with values used by AWS/S3 when encryption is effectively delegated to it?

**Comment by sfrost** [comment]
pgbackrest always does client-side encryption, regardless of the repository type.

**Comment by baburdick** [comment]
Thank you @sfrost! I recommend that be a clearly trumpeted feature in the README. Glad to know I can start switching over.

**Comment by baburdick** [comment]
Perfect, @dwsteele. Thank you very much.
