### ISSUE TITLE
2.08 wont compile on osx

### ISSUE THREAD

**Issue by hunleyd** [pgbackrest/pgbackrest#648]
Since 2.08 moves some of the locking bits to the C code, you get the following issue around the use of `flock()`:

```
gcc -I. -I../libc -std=c99 -D_POSIX_C_SOURCE=200112L -O2 -Wfatal-errors -Wall -Wextra -Wwrite-strings -Wswitch-enum -Wconversion -Wformat=2 -Wformat-nonliteral -Wno-clobbered -Wno-missing-field-initializers -Wstrict-prototypes -Wpointer-arith -Wvla `xml2-config --cflags` `perl -MExtUtils::Embed -e ccopts` -DWITH_PERL -DNDEBUG  -c common/lock.c -o common/lock.o
warning: unknown warning option '-Wno-clobbered'; did you mean '-Wno-consumed'?
      [-Wunknown-warning-option]
common/lock.c:76:21: warning: implicit declaration of function 'flock' is invalid in C99
      [-Wimplicit-function-declaration]
                if (flock(result, LOCK_EX | LOCK_NB) == -1)
                    ^
common/lock.c:76:21: warning: this function declaration is not a prototype [-Wstrict-prototypes]
common/lock.c:76:35: fatal error: use of undeclared identifier 'LOCK_EX'
                if (flock(result, LOCK_EX | LOCK_NB) == -1)
                                  ^
3 warnings and 1 error generated.
make: *** [common/lock.o] Error 1
```

You can correct this by changing `src/Makefile` to `CSTD = -std=c99 -D_DARWIN_C_SOURCE` on line 12 as `LOCK_EX` is apparently only defined for `_DARWIN_C_SOURCE` in `<sys/file.h>`

**Comment by dwsteele** [comment]
Interesting -- the code you are referring to was released in v2.02 and there haven't been any changes since 2.07 that I can see (just the names of a few constants).

I did add `-D_POSIX_C_SOURCE=200112L` which had previously been specified directly in some C files, but not in lock.c.

I'm not sure why is suddenly an issue.  Thoughts?

**Comment by hunleyd** [comment]
Oh, hrm. No idea. This is the first release I've encountered this particular issue. I would have suspected a recent OSX patch, but when googling to find the resolution, I found several somewhat old references in other github projects, so it's been around for a bit apparently. 

I just know that changing that one line in the Makefile fixes it here.

 ¯\_(ツ)_/¯

**Comment by hunleyd** [comment]
FWIW, adding `-D_POSIX_C_SOURCE=200112L` to 2.07 makes it fail here as well.

**Comment by dwsteele** [comment]
Ah, that's it, then.  Interesting.

I hesitate to just add _DARWIN_C_SOURCE until we have a configure script.  What happens if you leave -D_POSIX_C_SOURCE=200112L and compile with both?

**Comment by hunleyd** [comment]
Having them both compiles cleanly

**Comment by dwsteele** [comment]
@sfrost What do you think about adding that flag to the Makefile?  Likely to hurt anything?

**Comment by sfrost** [comment]
I wouldn't think having both would break things, in general, though it'd be cleaner to only have that set on OSX, of course.

**Comment by dwsteele** [comment]
Alright, we'll do both then.

@hunleyd It would be better in your blog post to recommend:
```
make CEXTRA=_DARWIN_C_SOURCE
```
rather than editing the Makefile.

**Comment by hunleyd** [comment]
Yeah, but I already edit the makefile to add the openssl libs under `/usr/local` and to edit the install path. For the next release, I'll use command line flags for all of them and write up a new post :)

**Comment by dwsteele** [comment]
Committed at 7272d6e24.
