### ISSUE TITLE
Ability to back up all stanzas in one command

### ISSUE THREAD

**Issue by mhagander** [pgbackrest/pgbackrest#650]
Today, the `pgbackrest backup` command requires the specification of a stanza.

When using a dedicated backrest host to backup a set of PostgreSQL hosts, it would be very convenient to have a single backrest command "deal with them all". So being able to either skip the stanza parameter or maybe even better have a `--all-stanzas` or `--stanza=*` (to make sure it's an explicit wish).

**Comment by keithf4** [comment]
I was thinking that going in the order listed in the config file by default would be good. 

The `process-max` option that's in there now was for how many are allowed per backup for compression & transfer, correct? So not sure how that could be applied to multiple backups running. Was thinking that by default it would just do one at a time in that order. And then have some sort of global config option to say how many actual to run in parallel when the `all` option is given.

**Comment by dwsteele** [comment]
It's an interesting idea and I can see how it would make things simpler -- and of course it would be optional.

There's no notion of ordering in our config system.  I'm not even sure that that would mean with included config files.  I think we'd need to go in alpha order and (at least at first) run one backup at a time.

I like the idea of something like --stanza=* to be sure it's not a typo.

**Comment by mhagander** [comment]
If predictable then yeah, alpha seems like the right order. Unless you want to go all-in and actually add an ordering key that could (optionally) be configured for each stanza to control the ordering?

**Comment by dwsteele** [comment]
This is a good idea but it's just not practical to implement it in the Perl code base since Perl has no notion that there are other stanzas in the config -- only C has this information.

Since the backup command is the last planned migration we are putting this in the backlog: https://github.com/pgbackrest/pgbackrest/projects/2#card-18615900
