### ISSUE TITLE
Restore to latest available WAL files in archive

### ISSUE THREAD

**Issue by qmnonic** [pgbackrest/pgbackrest#654]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.0.7

2. PostgreSQL version: 9.6

3. Operating system/version - docker container: postgres:9.6-alpine

4. Did you install pgBackRest from source or from a package?
From source, compiled in postgres:9.6-alpine docker container

5. Please attach the following as applicable:
Backing up to S3, which works great.
Archive mode works great.
Hot standby mode works great.
No errors.

7. Describe the issue:
My issue is - it's unclear how i'd flip my hot_standby, which is continuously pulling WAL files via archive_get, to a full production server.  Every command I try to restore, it seems to restore from the most recent backup and NOT from the current state of the hot_standby (which is continuously applying the most recent WAL files).

Should I just shutdown the database, remove the recovery.conf and restart?
Or do I need to 'promote' it?

My use case:  I want to replicate a database to another machine, then start it so it runs on it's own and forks from the original.  

I am clearly missing something simple here, but I just can't figure it out.

**Comment by dwsteele** [comment]
> Should I just shutdown the database, remove the recovery.conf and restart?

This is not a good idea.  The cluster will stay on the same timeline and this can cause conflicts in the WAL archive.

> Or do I need to 'promote' it?

The best way to promote a standby is to run `pg_ctl promote ...`.  This will promote the standby to a primary and switch to a new timeline.

Promoting a cluster is independent of how it was restored (i.e. not related to pgBackRest) so you should be able to find some tutorials that will show you procedures.  The pg_ctl docs are also helpful: https://www.postgresql.org/docs/9.6/app-pg-ctl.html.  You may also want to consider using an HA tool like Patroni.
