### ISSUE TITLE
Backup issue when specifying a different configuration file location

### ISSUE THREAD

**Issue by EtienneM** [pgbackrest/pgbackrest#655]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 

2.08

2. PostgreSQL version: 

10.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 

Debian Stretch

4. Did you install pgBackRest from source or from a package?

Package

5. Please attach the following as applicable:

pgbackrest.conf
```
[biniou_6964]
pg1-path=/var/lib/postgresql/postgresql0
pg1-socket-path=/tmp

[global]
repo1-cipher-pass=XXX
repo1-cipher-type=aes-256-cbc
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
repo1-s3-bucket=postgresql-backups-development
repo1-s3-endpoint=s3.eu-central-1.amazonaws.com
repo1-s3-key=XXXX
repo1-s3-key-secret=XXX
repo1-s3-region=eu-central-1
repo1-type=s3
stop-auto=y

[global:archive-push]
compress-level=3
```

postgresql.conf
```
archive_mode = on
archive_command = 'pgbackrest --stanza=biniou_6964 archive-push %p'
unix_socket_directories = '/tmp'
wal_keep_segments = '8'
wal_level = 'replica'
wal_log_hints = 'on'
```

PostgreSQL logs indicating an issue:

```
[postgresql-2] HINT: Is %f passed to archive-push instead of %p?
[postgresql-2] HINT: PostgreSQL may pass relative paths even with %p depending on the environment.
[postgresql-2] 2019-01-21 13:26:32 UTC LOG:  archive command failed with exit code 37
[postgresql-2] 2019-01-21 13:26:32 UTC DETAIL:  The failed archive command was: pgbackrest --stanza=biniou_793 archive-push pg_wal/000000010000000000000001
[postgresql-2] ERROR [037]: : option 'pg1-path' must be specified when relative wal paths are used
[postgresql-2] 2019-01-21 13:26:33 UTC DETAIL:  The failed archive command was: pgbackrest --stanza=biniou_793 archive-push pg_wal/000000010000000000000001
[postgresql-2] 2019-01-21 13:26:33 UTC LOG:  archive command failed with exit code 37
[postgresql-2] HINT: Is %f passed to archive-push instead of %p?
[postgresql-2] ERROR [037]: : option 'pg1-path' must be specified when relative wal paths are used
[postgresql-2] HINT: PostgreSQL may pass relative paths even with %p depending on the environment.
[postgresql-2] ERROR [037]: : option 'pg1-path' must be specified when relative wal paths are used
[postgresql-2] HINT: Is %f passed to archive-push instead of %p?
[postgresql-2] HINT: PostgreSQL may pass relative paths even with %p depending on the environment.
[postgresql-2] 2019-01-21 13:26:34 UTC LOG:  archive command failed with exit code 37
[postgresql-2] 2019-01-21 13:26:34 UTC DETAIL:  The failed archive command was: pgbackrest --stanza=biniou_793 archive-push pg_wal/000000010000000000000001
[postgresql-2] 2019-01-21 13:26:34 UTC WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
```

[biniou_6964-backup.log](https://github.com/pgbackrest/pgbackrest/files/2779109/biniou_6964-backup.log)

7. Describe the issue:

I want the configuration file for pgBackRest to be at `/var/lib/postgresql/pgbackrest.conf`. I define the environment variable `PGBACKREST_CONFIG=/var/lib/postgresql/pgbackrest.conf` and create a new backup. I have the above-mentioned errors in my logs.

If I duplicate my configuration to have it in both locations `/var/lib/postgresql/pgbackrest.conf` and `/etc/pgbackrest/pgbackrest.conf`, it works without modifying the environment variable.

**Comment by dwsteele** [comment]
The config files you provided are for stanza `biniou_6964` but the log errors are for stanza `biniou_793` so that's a bit confusing.

Anyway, I think the problem is that the `archive-push` command is not getting the env var you are passing to `backup`.  `archive-push` is called directly from postgres so it running in that environment.

So I think you need to either add `PGBACKREST_CONFIG` to your postgres env or pass `--config` on the command line to your `archive_command`.

**Comment by EtienneM** [comment]
Woups sorry, probably because the config files and the logs come from two different tests I did... But you got the idea. 

Isn't the backup supposed to correctly call `archive-push`? I mean, from my point of view, I call `backup` and expect `archive-push` to get the same configuration. They are both called from a context where `PGBACKREST_CONFIG` is defined.

Adding `--config` to the `archive_command` in the pgbackrest.conf file did the trick.

**Comment by dwsteele** [comment]
The backup does not call `archive-push`, postgres does.  This happens even when a backup is not running so they are independent processes.  If `archive-push` were to somehow get it's configuration from the `backup` command what would happen before the first backup runs?  Would it fail?  Ignore WAL?  What if the backup runs on another server?

Maybe it's possible to make these two processes communicate configuration but it's certainly the case that they don't now.  Using `--config` or sharing the env vars with the postgres user (before it starts the cluster) is the way to go.

**Comment by EtienneM** [comment]
OK thanks a lot for the clarification :+1:
