### ISSUE TITLE
 Is it possible to create a backup on the replication server?

### ISSUE THREAD

**Issue by Dreych** [pgbackrest/pgbackrest#658]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.08

2. PostgreSQL version:   

> PostgreSQL 10.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 

>  PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
> NAME="Debian GNU/Linux"
> VERSION_ID="9"
> VERSION="9 (stretch)"
> ID=debian
> 

4. Did you install pgBackRest from source or from a package? source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
[global]

repo1-path=/data/postgresql/backup
start-fast=y
stop-auto=y
archive-async = y

[test]

pg1-path=/data/postgresql/10
recovery-option=standby_mode=on
repo1-retention-full=2
```

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
```
archive_command = 'pgbackrest --stanza=test archive-push %p; cp -i %p /data/postgresql/wms-sam/archive/%f < /dev/null'
archive_mode = on
listen_addresses = '*'
max_wal_senders = 3 
wal_level = hot_standby
port = 5432

```

    - errors in the postgresql log file before or during the time you experienced the issue

> 2019-01-24 15:27:36.676 MSK,"postgres","postgres",23284,"[local]",5c49af37.5af4,22,"SELECT",2019-01-24 15:27:35 MSK,2/147,0,ERROR,55000,"recovery is in progress",,"pg_walfile_name() cannot be executed during recovery.",,,,"select to_char(current_timestamp, 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_walfile_name(lsn), lsn::text, (select setting::int8 from pg_settings where name = 'wal_segment_size') * (select setting::int8 from pg_settings where name = 'wal_block_size') from pg_start_backup('pgBackRest backup started at 2019-01-24 15:27:35', true, false) as lsn",,,"pgBackRest [backup]"

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

> -------------------PROCESS START-------------------
> 2019-01-24 18:32:22.307 P00   INFO: backup command begin 2.08: --log-level-console=info --pg1-path=/data/postgresql/10 --repo1-path=/data/postgresql/backup --repo1-retention-full=2 --stanza=test --start-fast --stop-auto
> 2019-01-24 18:32:22.478 P00   WARN: no prior backup exists, incr backup has been changed to full
> 2019-01-24 18:32:22.986 P00   INFO: execute non-exclusive pg_start_backup() with label "pgBackRest backup started at 2019-01-24 18:32:22": backup begins after the requested immediate checkpoint completes
> 2019-01-24 18:32:23.387 P00  ERROR: [124]: process terminated due to an unhandled exception:
>                                     Wide character in syswrite at /loader/0x5620aceb93a0/pgBackRest/Common/Log.pm line 720.
>                                      at /loader/0x5620aceb93a0/pgBackRest/Main.pm line 12.
>                                         pgBackRest::Main::__ANON__("Wide character in syswrite at /loader/0x5620aceb93a0/pgBackRe"...) called at /loader/0x5620aceb93a0/pgBackRest/Common/Log.pm line 720
>                                         pgBackRest::Common::Log::log("ERROR", "ERROR:  recovery is in progress\x{a}\x{41f}\x{41e}\x{414}\x{421}\x{41a}\x{410}\x{417}\x{41a}\x{410}:  pg_walfile_name()"..., 57) called at /loader/0x5620aceb93a0/pgBackRest/Db.pm line 311
>                                         pgBackRest::Db::executeSql(undef, "select to_char(current_timestamp, 'YYYY-MM-DD HH24:MI:SS.US T"...) called at /loader/0x5620aceb93a0/pgBackRest/Db.pm line 379
>                                         pgBackRest::Db::executeSqlRow(undef, "select to_char(current_timestamp, 'YYYY-MM-DD HH24:MI:SS.US T"...) called at /loader/0x5620aceb93a0/pgBackRest/Db.pm line 699
>                                         pgBackRest::Db::backupStart(undef, "pgBackRest backup started at 2019-01-24 18:32:22", 1) called at /loader/0x5620aceb93a0/pgBackRest/Backup/Backup.pm line 843
>                                         pgBackRest::Backup::Backup::process(pgBackRest::Backup::Backup=HASH(0x5620adf3b648)) called at /loader/0x5620aceb93a0/pgBackRest/Main.pm line 263
>                                         eval {...} called at /loader/0x5620aceb93a0/pgBackRest/Main.pm line 286
>                                         pgBackRest::Main::main("backup") called at (eval 266) line 1
>                                         eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'backup\')' called at (eval 266) line 0
> 
> 2019-01-24 18:32:23.388 P00   INFO: backup command end: aborted with exception [124]

7. Describe the issue:
I have master and replication server. Now backup make on master server without problem, but i want make backup on replication server. I can't make backup on replication server, because pgbacrest back ERROR 124. It's possible?

**Comment by Dreych** [comment]
Thanks, but i want make backup only on replication server. 
I will wait for updates :)

**Comment by dwsteele** [comment]
We don't have plans to support standby-only backup.  Our method is a big improvement over standby-only backups and puts almost no load on the primary.  Also, in the future we plan to allow distributing the backup among multiple standbys.

**Comment by Dreych** [comment]
Ok, I will try to configure standby backup. Thanks for support!
