### ISSUE TITLE
src/common/io/tls/client.c getbyhostname() has to be ported to getaddrinfo()

### ISSUE THREAD

**Issue by tigerfoot** [pgbackrest/pgbackrest#659]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.08

Trying to build the new 2.08 for openSUSE I discover the following warning
[   28s] RPMLINT report:
[   28s] ===============
[   29s] pgbackrest.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/pgbackrest
[   29s] The binary calls gethostbyname(). Please port the code to use getaddrinfo().

To make it short gethostbyname() is almost now old century way of doing thing. It has no idea about what ipv6 is.

Long explanation 
https://beej.us/guide/bgnet/html/multi/getaddrinfoman.html

Would you mind to check if that can be fixed and get again modern code ? :-)

**Comment by dwsteele** [comment]
Whoops, I meant to replace that after I finished the TLS prototype and forgot to leave myself a note to actually do it.  Thanks for catching that and we'll get proper lookup code into the next release.

**Comment by dwsteele** [comment]
Committed at 053972bfe01.  We still only try the first address returned but this could be improved in the future.  It's more a matter of how to setup reproducible tests and report errors sensibly than the code being all that complicated.

**Comment by tigerfoot** [comment]
Without being expert in that case, perhaps the test can also be run with reserved IP address like those especially defined for documentation

[Wikipedia Reserved address](https://en.wikipedia.org/wiki/Reserved_IP_addresses)

ipv6 2001:db8::/32 
ipv4 192.0.2.0/24

Just a rought idea. Thanks for the patch, I just integrate it on my build.
Congrats for your excellent celerity as always!

**Comment by dwsteele** [comment]
The big issue for testing is actually generating stuff that will error in the appropriate way.  For that I think I may need to setup a DNS server just for testing.  I'm not sure it's worth it at this point.

**Comment by tigerfoot** [comment]
Without being expert in that case, perhaps the test can also be run with reserved IP address like those especially defined for documentation

[Wikipedia Reserved address](https://en.wikipedia.org/wiki/Reserved_IP_addresses)

ipv6 2001:db8::/32 
ipv4 192.0.2.0/24

Just a rought idea. Thanks for the patch, I just try to integrate it on my build, or just wait 2.09 ;)

Congrats for your excellent celerity as always!

**Comment by dwsteele** [comment]
2.09 should be out in the next day or so.
