### ISSUE TITLE
 How can i deploy backup on another server

### ISSUE THREAD

**Issue by Dreych** [pgbackrest/pgbackrest#660]
pgBackRest version: 2.07

PostgreSQL version:

`PostgreSQL 10.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit`

Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian

```
Did you install pgBackRest from source or from a package? source

Please attach the following as applicable:

pgbackrest.conf file(s)
```
[global]

repo1-path=/data/postgresql/backup

[test]

pg1-path=/data/postgresql/10
repo1-retention-full=2
```

- `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
```
archive_command = 'pgbackrest --stanza=test archive-push %p; cp -i %p /data/postgresql/wms-sam/archive/%f < /dev/null'
archive_mode = on
listen_addresses = '*'
max_wal_senders = 3 
wal_level = hot_standby
port = 5432

```
- errors in the postgresql log file before or during the time you experienced the issue

- log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Describe the issue:
 How can i deploy backup on another server with send file's pgbackrest on remote server?
I try archiving an sending files: /data/postgresql/backup/20190127-220001F, but i see differents error in logs of postgres.

**Comment by dwsteele** [comment]
You can find an example of setting up a remote server here: https://pgbackrest.org/user-guide.html#repo-host
