### ISSUE TITLE
Fail to restore a backup on Patroni cluster

### ISSUE THREAD

**Issue by EtienneM** [pgbackrest/pgbackrest#661]
1. pgBackRest version: 

2.08

2. PostgreSQL version: 

10.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 

Debian Stretch

4. Did you install pgBackRest from source or from a package?

Package

7. Describe the issue:

I am struggling setting up Patroni along with pgBackRest. I opened an issue on Patroni (zalando/patroni#959) to ask for help but eventually have been asked to see with you. 

The problem is that I fail to restore a backup made with pgBackRest. I eventually found that the issue might be that I need to use `keep_existing_recovery_conf: True` parameter on Patroni configuration. But I fail to have a working configuration with this parameter. Does anybody have a working sample of this?

**Comment by dwsteele** [comment]
It looks like you have not setup a `pgbackrest.conf` file on the host you are restoring to so pgBackRest is looking in the default directory for `repo1-path`.  Before you try automating anything with Patroni you should familiarize yourself with how to setup pgBackRest and restore to a new host:  https://pgbackrest.org/user-guide.html#replication.
