### ISSUE TITLE
correct the usage of DESTDIR in Makefile

### ISSUE THREAD

**Issue by hunleyd** [pgbackrest/pgbackrest#662]
Was compiling 2.09 this morning and trying not to edit the Makefile but use env overrides as you suggested in my last issue, and I realized that I still have to edit the Makefile since it appears DESTDIR is used incorrectly.

Existing Makefile:
line 54: `DESTDIR =`
line 169: `install -d $(DESTDIR)/usr/bin`
line 170: `install -m 755 pgbackrest $(DESTDIR)/usr/bin`

Which means if I set DESTDIR to anything it gets prepended to `/usr/bin` (e.g. setting it to `/usr/local` would get me `/usr/local/usr/bin`). This is incorrect. It should be:

line 54: `DESTDIR = /usr/bin`
line 169: `install -d $(DESTDIR)`
line 170: `install -m 755 pgbackrext $(DESTDIR)`

Which would give `/usr/bin/pgbackrest` by default, and allow me to set `make DESTDIR=/usr/local/bin -C src install` and have it install to `/usr/local/bin/pgbackrest` correctly.

You want a PR for this?

**Comment by dwsteele** [comment]
Committed at 786e77a9.
