### ISSUE TITLE
Backup Type Flag Requirement

### ISSUE THREAD

**Issue by jasonodonnell** [pgbackrest/pgbackrest#664]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
N/A

2. PostgreSQL version:
N/A

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
N/A

4. Did you install pgBackRest from source or from a package?
N/A

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
  N/A

6. Describe the issue:

pgBackRest defaults to `incr` backups if no `--type=<backup type>` flag is provided to `pgbackrest backup`.  This means commands such as `pgbackrest backup --stanza=db full` still work but the resulting backups are incremental (provided a full backup exists).

Although the default backup type is convenient it might make sense to make the `--type` flag a required parameter to prevent subtle bugs with the backup command.

**Comment by dwsteele** [comment]
The commands that expect parameters enforce how many they expect to get, but the commands that don't expect parameters just ignore them.

This is not great from a user-friendliness perspective so we'll fix that.

**Comment by dwsteele** [comment]
Implemented at 60fe5b7365c9eaaa0.  Thanks for the suggestion!
