### ISSUE TITLE
wrong year in v2.09 Release Notes

### ISSUE THREAD

**Issue by achix** [pgbackrest/pgbackrest#666]
text here : https://pgbackrest.org/release.html reads : 
v2.09 Release Notes
Minor Improvements and Bug Fixes
Released January 30, 2018

maybe you mean 2019 ?

**Comment by sfrost** [comment]
Whoops, you're quite right, we'll see about getting that fixed. :)  Thanks!

**Comment by dwsteele** [comment]
Fixed at 51971617a82a3.  Thanks!
