### ISSUE TITLE
pgbackrest 2.10 fails when `pg_control` and config have different paths pointing to the same location

### ISSUE THREAD

**Issue by gozdal** [pgbackrest/pgbackrest#671]
1. pgBackRest version: 2.10
2. PostgreSQL version: 9.6
3. Operating system/version - CentOS 7
4. from package

https://github.com/pgbackrest/pgbackrest/commit/6e88f93991171632f33fd1b12fc1090d4a9f02a5 fixed a check that the paths in `pg_control` match pgbackrest config. It fails however if one path is a symlink to the other. I believe if one is a symlink to the other it shouldn't complain.

**Comment by sfrost** [comment]
Agreed, we should probably allow this, though at least it should be reasonably straight-forward to work around.

I'm not sure if it will be worthwhile to fix this in the perl code, but we'll see.  In any case, this doesn't seem to be a critical issue, but one we'll address in due time.

Thanks!

**Comment by dwsteele** [comment]
I think it is preferable to set data_directory to the actual path rather than to a symlink.

That said, we may address this, but I'm not sure it's worth doing in Perl, which means it probably won't happen soon.

Sorry this broke, though.  That's not great, but it is the way the feature was designed before it got disabled at some point.

**Comment by gozdal** [comment]
My problem is actually kinda backwards - we're passing real directory to pgbackrest, but PG itself is installed in a directory which is now a symlink.
Initially we created the DB in `/var/lib/postgresql/...` but it got moved to another disk (say `/mnt/db`) and a symlink was left in `/var/lib/postgresql/...` to `/mnt/db`. PG is configured for `/var/lib/postgresql/...` and we're trying to configure pgbackrest with `/mnt/db`.

Do you have any ideas on how we can work around it?

**Comment by sfrost** [comment]
Wouldn't it make sense to just configure pgbackrest with the /var/lib/postgresql/ path too..?

**Comment by dwsteele** [comment]
I was thinking to set `data_directory` in `postgresql.conf` to `/mnt/db`.

pgBackRest won't work if it is pointed at a symlink, but since the patch check was broken it was ignoring the fact that PG was pointed at a symlink.  Now, we should probably fix that since PG does allow symlinks, but updating `data_directory` should do the trick for now.

**Comment by gozdal** [comment]
Any reason why pgBackRest refuses to work when pointed at a symlink? I wanted to avoid changing `data_directory` as it requires PG restart but if it's the only way to go I'd bite the bullet.

**Comment by gozdal** [comment]
Also: the wording of error I get:
```
ERROR [058]: : version '9.6' and path '/var/lib/postgresql/9.6/main' queried from cluster do not match version '9.6' and pg1-path '/mnt/pg/9.6' read from '/mnt/pg/9.6/global/pg_control'
```
suggests that the path is read from `pg_control` file. Is the wording wrong and it's actually read from PostgreSQL GUC?

**Comment by dwsteele** [comment]
Basically -- on restore, where does the data go?  The symlink location? What it points to? Should we recreate the symlink and the directory?  How does link-map work in that situation?  Would anyone ever be able to figure it out?

So, we've just taken a hard line on symlinks where they are not needed (and symlinks to symlinks for other use cases) and generally it has not been too much of an issue.

And yeah, the wording is wrong there (we do get the version from pg_control, though) so we'll update that.

A reboot isn't ideal, but that's your best short-term solution.

**Comment by dwsteele** [comment]
Did this work for you?

**Comment by gozdal** [comment]
Yes, thanks. I updated `data_directory` to point to physical directory and restarted PG.

**Comment by dwsteele** [comment]
Glad it worked!

**Comment by edib** [comment]
It is not fair that a backup software force me to use a specific configuration to work.
