### ISSUE TITLE
pgbackrest fails after timeout reached

### ISSUE THREAD

**Issue by brunre01** [pgbackrest/pgbackrest#673]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:  2.02

2. PostgreSQL version:   9.6.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Red Hat Enterprise Linux Server release 7.3

4. Did you install pgBackRest from source or from a package?
 
From package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

[CDAR_servername]
db-path=/pgDATA/data

[global]
process-max=10
repo-path=/pgBACKUP/servername
retention-full=2
retention-diff=7
retention-archive=2
start-fast=y
log-level-file=detail
db-timeout=2400
protocol-timeout=2450
archive-async=y

[global:archive-push]
process-max=4

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

port = 5444
listen_addresses = '*' 
wal_level = replica
archive_mode = on
archive_command = 'pgbackrest --stanza=CDAR_servername archive-push %p'
max_wal_senders = 3

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

see error in description

7. Describe the issue:

backup fails after timeout

2019-02-11 10:05:13.953 P08   INFO: backup file /pgDATA/data/pg_tblspc/16455/PG_9.6_201608131/16456/53572713 (0B, 100%)
2019-02-11 10:05:13.954 P09   INFO: backup file /pgDATA/data/pg_tblspc/16455/PG_9.6_201608131/16456/39650781 (0B, 100%)
2019-02-11 10:05:18.164 P00   INFO: full backup size = 8996.1GB
2019-02-11 10:05:18.188 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2019-02-11 10:45:18.387 P00  ERROR: [059]: statement timed out after 2400.006 second(s):
                                        select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, labelfile, case when length(trim(both '\t\n ' from spcmapfile)) = 0 then null else spcmapfile end as spcmapfile from pg_stop_backup(false) as lsn
2019-02-11 10:45:19.457 P00   INFO: backup command end: aborted with exception [059]

**Comment by brunre01** [comment]
extract from logfile at time of failure

2019-02-11 10:45:19 EST [55331]: [229-1]WARNING:  aborting backup due to backend exiting before pg_stop_backup was called
2019-02-11 10:45:19 EST [55331]: [230-1]LOG:  disconnection: session time: 21:09:14.980 user=enterprisedb database=postgres host=localhost port=43640

**Comment by sfrost** [comment]
There's been quite a few releases of pgbackrest since 2.02 and I strongly encourage you to start off by getting on to a recent version.

Have you run `pgbackrest check` to make sure that WAL archiving is working properly?

**Comment by brunre01** [comment]
as soon as i performed as 'check'  the archives started being backed up.   Since i'm using pgbackrest with enterprisedb advanced server, updating pgbackrest to a later release will throw a segmentation fault.

**Comment by sfrost** [comment]
If a segfault is happening, it's possible that it's because multiple different versions of libpq are ending up linked into the pgbackrest process, or perhaps it was compiled against one version of libpq but then links against a different version.  As I recall, there was a prior issue opened where this was discovered to be an issue and a workaround provided, but I don't currently have time to go hunt it down.

**Comment by dwsteele** [comment]
@brunre01 edb is now available as a package which should solve your lib conflicts.  We know for sure the installer creates lib conflicts (openssl and libpq) and there's not much we can do about it.

But -- are you working now?  Possibly this was a large WAL queue that needed to be cleared?

**Comment by brunre01** [comment]
I believe that was the problem. There was a large WAL queue that needed to be cleared.  It works as expected.
Thanks

**Comment by dwsteele** [comment]
BTW - if you are running 2.02 be sure to set `resume=n` in `pgbackrest.conf`.  There is a resume bug in that version (which goes back to 1.00) that was fixed in 2.04.  See https://pgbackrest.org/release.html#2.04.

**Comment by brunre01** [comment]
Thank you. would it be "safe" to upgrade to the latest version of pgbackrest in an edb system?

**Comment by dwsteele** [comment]
If you used their binary installer then probably not due to their custom versions of openssl and libpq.  If you use the packages then you should be OK.
