### ISSUE TITLE
Info Command: return error code if stanza doesn't exist

### ISSUE THREAD

**Issue by jasonodonnell** [pgbackrest/pgbackrest#676]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: N/A

2. PostgreSQL version: N/A

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: N/A

4. Did you install pgBackRest from source or from a package? N/A

5. Please attach the following as applicable: N/A
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

As a user if I run `pgbackrest info --stanza=somestanza` and that stanza does not exist, pgBackRest will say so in the info string, however, its return code is 0.  If we wanted to determine if the stanza was created using pgBackRest we would need to parse the info output which is prone to changing (it recently changed in in 2.10).

It would be really helpful if pgBackRest would return a unique error code if the requested stanza doesn't exist.

**Comment by dwsteele** [comment]
Well, the error is a lot more obvious in the JSON format (which does not change), so that's possibly an option.

I'm on the fence about this.  The info command did run OK so I prefer a zero exit.  Also, we make no guarantees about the stability of our non-zero error codes.

**Comment by dwsteele** [comment]
We still think it is best to report the error in JSON.  The info command ran successfully so returning an error is not ideal.
