### ISSUE TITLE
pgbackrest archive_command use with copy

### ISSUE THREAD

**Issue by nevzatgul** [pgbackrest/pgbackrest#678]
* pgBackRest version:  pgBackRest 2.09
* PostgreSQL version:   11.1
* Oracle Linux 7.5
 

cat /etc/pgbackrest.conf 
[mystanza]
db-path=/var/lib/pgsql/11/data/
db-port=5432
db-host=mystanza
retention-full=1

[global]
repo-path=/BACKUP/pgbackrest
backup-user=postgres
backup-cmd=/usr/bin/pgbackrest
start-fast=y 
stop-auto=y
process-max=8
repo1-retention-full=1

listen_addresses='*'
wal_level=replica
archive_mode=on
archive_command= 'pgbackrest --stanza=mystanza  archive-push %p'
max_wal_senders=20

Hi 

My question:

is possible archive_comand parameter   
test ! -f /ARSIV/%f && cp %p /ARSIV/%f    
with 
'pgbackrest --stanza=mystanza  archive-push %p'  

both use 

Example :

'test ! -f /ARSIV/%f && cp %p /ARSIV/%f && pgbackrest --stanza=mystanza  archive-push %p'

**Comment by dwsteele** [comment]
This won't work because if a WAL segment already exists in `/ARSIV` then `pgbackrest` will not be executed.  Doing it the other way around should be OK:
```
'pgbackrest --stanza=mystanza archive-push %p && test ! -f /ARSIV/%f && cp %p /ARSIV/%f'
```
You'll need to test that carefully because this is not a common use case.

Please note: `test ! -f /ARSIV/%f && cp %p /ARSIV/%f` is not recommended because it is not completely safe.  I know it is in the Postgres documentation but we are working to fix that.

**Comment by nevzatgul** [comment]
Thank you for response .
Unfortunately  does not work above syntax.
We  want to use pgbackrest with archive_mode .  
My environment are occurs postgresql master server , replication server  and pgbackrest server. 

How to do it  both "pgbackrest" and  "cp %p /ARSIV/%f "  use. 

Thanks..

**Comment by dwsteele** [comment]
Well, you are going to need to give me some idea of why it does not work.  What's the error message?  What problem are you seeing?

**Comment by nevzatgul** [comment]
My environment  


CASE 1: 
-------
[postgres@egzozdb06s01 pg_wal_11_archive]$ ls -ltrh  |  tail -5f
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B600000038
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B600000039
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B60000003A
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B60000003B
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B60000003C


postgres=# show archive_command 
                              archive_command                               
----------------------------------------------------------------------------
 test ! -f /ARSIV/pg_wal_11_archive/%f && cp %p /ARSIV/pg_wal_11_archive/%f
(1 row)


 
postgres=# select pg_switch_wal();
 pg_switch_wal 
---------------
 B6/3D2B9E20
(1 row)

[postgres@egzozdb06s01 pg_wal_11_archive]$ ls -ltrh  |  tail -5f
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B600000039
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B60000003A
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B60000003B
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B60000003C
-rw------- 1 postgres postgres 16M Feb 19 14:26 00000006000000B60000003D  // wal file created 

CASE 2:
-------
postgres=# show archive_command ;
                                                     archive_command                                                      
--------------------------------------------------------------------------------------------------------------------------
 pgbackrest --stanza=egzoz  archive-push %p && test ! -f /ARSIV/pg_wal_11_archive/%f && cp %p /ARSIV/pg_wal_11_archive/%f
(1 row)

postgres=# select pg_switch_wal();
 pg_switch_wal 
---------------
 B6/3F0005D8
(1 row)

[postgres@egzozdb06s01 pg_wal_11_archive]$ ls -ltrh  |  tail -5f
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B600000039
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B60000003A
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B60000003B
-rw------- 1 postgres postgres 16M Feb 19 09:24 00000006000000B60000003C
-rw------- 1 postgres postgres 16M Feb 19 14:26 00000006000000B60000003D // wal file not created

**Comment by dwsteele** [comment]
Hmm, not sure why that isn't working.  You might try wrapping `test ! -f /ARSIV/pg_wal_11_archive/%f && cp %p /ARSIV/pg_wal_11_archive/%f` in a shell script.
