### ISSUE TITLE
pgbackrest info output differ when specifying --stanza

### ISSUE THREAD

**Issue by renesepp** [pgbackrest/pgbackrest#683]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.09
2. PostgreSQL version:
10
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Repository host: CentOS 7
Database server: CentOS 7
4. Did you install pgBackRest from source or from a package?
Package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

Repository host: pgbackrest.conf
```
[global]
repo-type=cifs
repo-path=/var/lib/pgbackrest/mountpoint2
process-max=4
compress=n
compress-level=0
compress-level-network=2
retention-full=4
retention-diff=15
start-fast=y
stop-auto=y

[exampledb1]
db-host=exampledb1.just.sise
db-path=/var/lib/pgsql/10/data
db-user=postgres
```

Database: pgbackrest.conf
```
[global]
backup-host=pgbackrest.domain
backup-user=backrest
log-level-file=detail

[global:archive-get]
process-max=2
[global:archive-push]
process-max=2

[exampledb1]
db-path=/var/lib/pgsql/10/data

```

7. Describe the issue:
`pgbackrest info` command output displays _**wal archive min/max (10-1): none present**_ when running with a --stanza option

`pgbackrest --stanza exampledb1 info`

> stanza: exampledb1
>     status: ok
>     cipher: none
>     db (current)
>         wal archive min/max (10-1): **none present**

`pgbackrest  info`

> stanza: exampledb1
>     status: ok
>     cipher: none
>     db (current)
>         wal archive min/max (10-1): **000000010000045E0000001D/00000001000004610000006A**

**Comment by dwsteele** [comment]
This bug was introduced in 2.10.  It was reported as part of #675 and fixed at 80df1114bdc97a9304.

Thanks for the report, though!  I doubt a search of the issues would have brought up a clear hit.
