### ISSUE TITLE
Backup timeout

### ISSUE THREAD

**Issue by dcolhoun19** [pgbackrest/pgbackrest#684]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.10

2. PostgreSQL version: 9.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Centos 7

4. Did you install pgBackRest from source or from a package? from package

5. Please attach the following as applicable:
   
postgresql.conf

Relevant lines
wal_level = archive
archive_mode = on		# allows archiving to be done
				# (change requires restart)
archive_command = 'pgbackrest --stanza=db2 archive-push %p'

 
pgbackrest.conf on repository/backup server

[global]
repo-path=/var/lib/pgbackrest
retention-full=14
retention-diff=1
start-fast=y

[db2]
db-host=db2
db-path=/var/lib/pgsql/9.4/data
db-user=postgres

And on DB server

[global]
backup-host=vault
backup-user=backrest
log-level-file=detail

[db2]
db-path=/var/lib/pgsql/9.4/data

    - errors in the postgresql log file before or during the time you experienced the issue
ERROR [042]: : remote process on 'vault' terminated unexpectedly: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
< 2019-02-28 11:50:38.693 GMT >LOG:  archive command failed with exit code 42
< 2019-02-28 11:50:38.693 GMT >DETAIL:  The failed archive command was: pgbackrest --stanza=db2 archive-push pg_xlog/00000001000002CC000000D9
ERROR [042]: : remote process on 'vault' terminated unexpectedly: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
< 2019-02-28 11:50:40.409 GMT >LOG:  archive command failed with exit code 42
< 2019-02-28 11:50:40.409 GMT >DETAIL:  The failed archive command was: pgbackrest --stanza=db2 archive-push pg_xlog/00000001000002CC000000D9
ERROR [042]: : remote process on 'vault' terminated unexpectedly: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
< 2019-02-28 11:50:41.955 GMT >LOG:  archive command failed with exit code 42
< 2019-02-28 11:50:41.955 GMT >DETAIL:  The failed archive command was: pgbackrest --stanza=db2 archive-push pg_xlog/00000001000002CC000000D9

    - log file in `/var/log/pgbackrest` for the commands run (e.g. 

2019-02-28 10:30:26.644 P01   INFO: backup file db2:/var/lib/pgsql/9.4/data/base/1/12769 (0B, 100%)
2019-02-28 10:30:26.653 P01   INFO: backup file db2:/var/lib/pgsql/9.4/data/base/1/12759 (0B, 100%)
2019-02-28 10:30:26.731 P01   INFO: backup file db2:/var/lib/pgsql/9.4/data/base/1/12749 (0B, 100%)
2019-02-28 10:30:27.265 P00   INFO: full backup size = 42.6GB
2019-02-28 10:30:27.266 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2019-02-28 11:00:27.359 P00  ERROR: [059]: raised from remote process on 'db2': statement timed out after 1800.074 second(s):
                                        select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text, null as labelfile, null as spcmapfile from pg_stop_backup() as lsn
2019-02-28 11:00:27.455 P00   INFO: backup command end: aborted with exception [059]

7. Describe the issue:

New install of pgbackrest. SSH passwordless connection working, but check and backup command fail

**Comment by dcolhoun19** [comment]
this is correct pgbackrest.conf

[global]
repo-path=/var/lib/pgbackrest
retention-full=14
retention-diff=1
start-fast=y


[db2]
db-host=db2
db-path=/var/lib/pgsql/9.4/data
db-user=postgres

**Comment by dwsteele** [comment]
It looks like your `archive_command` is not working.  Have you run the `check` command?  Errors will be in the postgres logs.

See: https://pgbackrest.org/user-guide.html#quickstart/check-configuration

**Comment by dcolhoun19** [comment]
sudo -u pgbackrest pgbackrest --stanza=db2 check
ERROR [082]: : could not find WAL segment 00000001000002DB0000001C after 60 second(s)
ERROR [082]: : could not find WAL segment 00000001000002DB0000001C after 60 second(s)
WARN: WAL segment 00000001000002DB0000001C did not reach the archive:9.4-1
HINT: Check the archive_command to ensure that all options are correct (especially --stanza).
HINT: Check the PostgreSQL server log for errors.

my archive command on db server is 

pgbackrest --stanza=db2 archive-push %p

Any suggestions on why this archive_command wouldn't work

**Comment by dwsteele** [comment]
The errors will be in the postgres log: `HINT: Check the PostgreSQL server log for errors.`

**Comment by dcolhoun19** [comment]
I cannot see any errors in the Postgress logs

Message I am getting is

< 2019-02-28 13:19:23.914 GMT >LOG:  restore point "pgBackRest Archive Check" created at 2DB/201C88F8
< 2019-02-28 13:19:23.914 GMT >STATEMENT:  select pg_create_restore_point('pgBackRest Archive Check');

Nothing after this

**Comment by dwsteele** [comment]
Is there a `pgbackrest` process running?  It might be stuck trying to connect to the database.

**Comment by dwsteele** [comment]
Also, try running `psql` as the `postgres` user.  If this doesn't work then you have an auth issue.

**Comment by dcolhoun19** [comment]
This on db host

postgres  5959  5958  1 14:01 ?        00:00:00 ssh -o LogLevel=error -o Compression=no -o PasswordAuthentication=no backrest@vault pgbackrest --buffer-size=4194304 --command=archive-push --compress-level=6 --compress-level-network=3 --log-level-file=off --pg1-path=/var/lib/pgsql/9.4/data --process=0 --protocol-timeout=1830 --stanza=db2 --type=backup remote

And on repository host

ps -ef|grep pgbackrest
backrest 28150 28149 39 14:05 ?        00:00:00 pgbackrest --buffer-size=4194304 --command=archive-push --compress-level=6 --compress-level-network=3 --log-level-file=off --pg1-path=/var/lib/pgsql/9.4/data --process=0 --protocol-timeout=1830 --stanza=db2 --type=backup remote

**Comment by dwsteele** [comment]
Have you tried connecting directly with `psql` yet?  As asked above.

**Comment by dcolhoun19** [comment]
Hi David

I have just managed to get it to work by increasing the archive-timeout=180. Then re-ran the check/backup commands and they both worked.

Thanks for your help
