### ISSUE TITLE
Newbie Question: Cannot perform backup when postgres is not running

### ISSUE THREAD

**Issue by grayaii** [pgbackrest/pgbackrest#685]
1. pgBackRest version:
`# pgbackrest version
pgBackRest 2.10`

2. PostgreSQL version:
`# yum list installed | grep postgresql95`
`postgresql95.x86_64                9.5.16-1PGDG.rhel6`

3. Operating system/version:
AWS EC2 Instance
`# uname -a`
`Linux ip-10-55-0-152 4.14.97-74.72.amzn1.x86_64 #1 SMP Tue Feb 5 20:59:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

4. Did you install pgBackRest from source or from a package?
From a package:
`https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7.0-x86_64/pgbackrest-2.10-1.rhel7.x86_64.rpm`

5. Please attach the following as applicable:
    - `pgbackrest.conf`:

`# cat /etc/pgbackrest.conf`

    [global]
    process-max=32
    repo1-cipher-type=none
    repo1-path=/ccodb-test-repo
    repo1-retention-diff=2
    repo1-retention-full=2
    repo1-s3-endpoint=s3.amazonaws.com
    repo1-s3-bucket=ccodb-backup-298394155355-alex01-us-west-2
    repo1-s3-region=us-west-2
    repo1-type=s3
    repo1-s3-key=xxxx
    repo1-s3-key-secret=xxxx
    repo1-s3-ca-file=/etc/pki/tls/certs/ca-bundle.crt
    start-fast=y
    stop-auto=y

    [global:archive-push]
    compress-level=3

    [main]
    pg1-path=/pgdata/data

    [backup]
    pg1-path=/pgdata_snapshot/data

7. Describe the issue:

I'm getting my feet wet with pgbackrest.
I have a dedicated backup box running postgres.
My basic steps are (just to get my feet wet):
1) stop postgres service:` /etc/init.d/postgres95 stop`
2) create an lvm snapshot of postgres's data dir. Basically copy /pgdata/data to /pgdata_snapshot/data
3) Run pgbackrest to create a backup of /pgdata_snapshot/data to an AWS S3 bucket (this is where it's failing)
4) start postgres service: `/etc/init.d/postgres95 start`

When I run pgbackrest to create a backup from the snapshot directory, I get this error:

    # pgbackrest --stanza=backup backup --force \
        --no-online --type full --log-level-console info
    2019-02-28 14:35:23.572 P00   INFO: backup command begin 2.10: --force --log-level-console=info --no-online --pg1-path=/pgdata_snapshot/data --process-max=32 --repo1-cipher-type=none --repo1-path=/ccodb-test-repo --repo1-retention-diff=2 --repo1-retention-full=2 --repo1-s3-bucket=ccodb-backup-298394155355-alex01-us-west-2 --repo1-s3-ca-file=/etc/pki/tls/certs/ca-bundle.crt --repo1-s3-endpoint=s3.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-west-2 --repo1-type=s3 --stanza=backup --start-fast --stop-auto --type=full

    ERROR [055]: : unable to open /ccodb-test-repo/backup/backup/backup.info or /ccodb-test-repo/backup/backup/backup.info.copy
    ERROR [055]: : /ccodb-test-repo/backup/backup/backup.info does not exist and is required to perform a backup.
    HINT: has a stanza-create been performed?
    2019-02-28 14:35:23.909 P00   INFO: backup command end: aborted with exception [055]

**Comment by dwsteele** [comment]
You can do an offline backup using the --no-online option.

Your primary issue is that you have not run `stanza-create` to initialize the repo.  See https://pgbackrest.org/user-guide.html#quickstart/create-stanza.  This will also require the `--no-online` option if the database is not running.

BTW, not at all a newbie question.  Doing backups from a snapshot is a very interesting idea, but if the snapshot is on the db server it's not going to help your performance any.  If it has been exported to another server then that's a different story.  You'll still need a valid `archive_command` on your primary if you want to do PITR.  And test!
