### ISSUE TITLE
Question about other object storage support

### ISSUE THREAD

**Issue by EtienneM** [pgbackrest/pgbackrest#688]
Hello,

We would like to use pgbackrest to handle our PostgreSQL backups but are wondering whether there are already some works done about adding support for different object storage or not? We noticed it's present in the roadmap (https://github.com/pgbackrest/pgbackrest/projects/2) since a couple of years. If no work started, how much of a work do you think it can be to add support for Swift?

Thanks a lot for this project

**Comment by dwsteele** [comment]
We do want to have more drivers and they are reasonably easy to implement, see https://github.com/pgbackrest/pgbackrest/tree/master/src/storage/driver.

However, right now we are in the midst of a migration from Perl to C, so implementing a new driver means writing it in two languages which does seem worth the effort.

As soon as the migration is complete, we'll be very interested in a Swift driver.
