### ISSUE TITLE
Can't get backup info from s3 bucket

### ISSUE THREAD

**Issue by spacejam101** [pgbackrest/pgbackrest#692]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.10

2. PostgreSQL version:
10.7

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

1 postgres instance
1 s3 bucket to store my backups

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

First of all great work for this wondeful tool! I can push all my backup to s3 but I can't get its info from my postgres instance.

![image](https://user-images.githubusercontent.com/17024847/54247469-13aae300-4574-11e9-8a81-56ce5b5ff7e5.png)

`No stanzas exist in the repository.`

**Comment by spacejam101** [comment]
Linking this https://github.com/pgbackrest/pgbackrest/issues/691 as this solves my problem and currently a bug. Thanks!

**Comment by dwsteele** [comment]
Thanks for the report!  We'll have this one fixed by the next release.

**Comment by dwsteele** [comment]
Fixed at 9382283586da4.
