### ISSUE TITLE
Unable to restore a dropped table in DB when foreign keys are present.

### ISSUE THREAD

**Issue by computeminionstest** [pgbackrest/pgbackrest#693]
Hello, 
My PosgreSQL + pgBackRest setup is as following:

1. pgBackRest version: 2.08

2. PostgreSQL version: 10.6

3. Operating system/version - CentOS 7 

4. Did you install pgBackRest from source or from a package?
    Source

5. pgBackRest Configuration:
[global]
repo-path=/home/TSDB_Backup_S3IA/deepr_historical_db_backup
archive-async=y
log-level-file=detail

[localhost]
pg1-path=/home/databases/timescaledb/10/data
retention-full=2

6. postgresql.conf Settings:
        archive_mode = on	
        archive_command = 'pgbackrest --stanza=localhost archive-push %p'
        listen_addresses = '*'
        max_wal_senders = 10
        wal_level = replica	
        port = 5432
        shared_preload_libraries = 'timescaledb'
				
7.  Log file for pgbackrest is attached (called localhost-restore.log)

8. Describe the issue:
My DB contains a TimescaleDB extension. My DB host and  Archive Repository are on the same host but in different locations. I am trying to recover a dropped table that was related to another table by foreign key constraints and was dropped by calling DROP.... CASCADE.
After stopping the postgresql-10 server , 
Recovery is run using recovery command 
                      pgbackrest --delta --stanza=localhost --log-level-console=detail  restore
But after recovery is complete, table is not present in the DB. 
**However if I try to restore a table that has no foreign key constraints, it is successfully recovered after pgbackrest restore. But if the dropped table has foreign key constraint it is not recovered.
I want to know what am I doing wrong or is it that pgbackrest is unable to recover dropped tables that have foreign key constraints.**

[localhost-restore.log](https://github.com/pgbackrest/pgbackrest/files/2963295/localhost-restore.log)

**Comment by dwsteele** [comment]
If you restore in this way then Postgres will recover to the end of the WAL stream and re-drop the table.  You need to set a recovery target that is *before* the table was dropped and select a backup made *before* the table was dropped.

See https://pgbackrest.org/user-guide.html#pitr for more information on how this works.
