### ISSUE TITLE
hard limit on process-max 

### ISSUE THREAD

**Issue by Rakshitha-BR** [pgbackrest/pgbackrest#696]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 
pgbackrest-2.06

2. PostgreSQL version:
postgres 10

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 7

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

/usr/bin/pgbackrest  --stanza={{ mystanza }} --config=/apps/postgres/pgbackrest.conf --pg1-path=/apps/postgres/data --log-level-console=info --type=full --process-max=96  --no-resume --compress --compress-level=5 --compress-level-network=3 backup

7. Describe the issue:
hard limit on --process-max is 96. Cant we use more ?

**Comment by dwsteele** [comment]
The limit is not completely arbitrary -- it's based on the type of hardware that can be acquired today, together with recommendations for load on the database server and available network technologies.

We recommend in the user guide to use no more that 25% of the available virtual cores for backup to avoid undue load on the system.  It's generally better to lower compression level when more throughput is needed.  I see you have done that somewhat, but 3 would probably be a better value.

How many virtual cores are actually in this system? `grep -c ^processor /proc/cpuinfo`

**Comment by Rakshitha-BR** [comment]
-bash-4.2$ grep -c ^processor /proc/cpuinfo
224

**Comment by Rakshitha-BR** [comment]
ERROR:

"ERROR: [032]: '100' is out of range for 'process-max' option"

We agree on recommendation but in some critical situation when we want it to be more, cant we use the complete cores.

**Comment by dwsteele** [comment]
We'll raise this limit for the next release.

Are you really able to run all those cores at 90%+?  I would imagine you'd get I/O bound.

What does `top -bn 1 | grep pgbackrest` look like when you are running with `process-max=96`?

**Comment by Rakshitha-BR** [comment]
Hi ,

[postgres@finpg-stg-01 ~]$ top -bn 1 | grep pgbackrest
 42133 postgres  20   0  252648  37480   4948 R 100.0  0.0   0:14.99 pgbackrest
 42457 postgres  20   0  252636  35448   4948 R 100.0  0.0   0:13.74 pgbackrest
 42473 postgres  20   0  252648  35412   4948 R 100.0  0.0   0:13.76 pgbackrest
 42950 postgres  20   0  252636  33400   4948 R 100.0  0.0   0:13.07 pgbackrest
 42122 postgres  20   0  252384  33184   4952 R 100.0  0.0   0:14.91 pgbackrest
 42128 postgres  20   0  252648  37564   4948 R 100.0  0.0   0:14.86 pgbackrest
 42129 postgres  20   0  252636  39308   4948 R 100.0  0.0   0:14.95 pgbackrest
 42315 postgres  20   0  252384  33036   4952 R 100.0  0.0   0:13.99 pgbackrest
 42316 postgres  20   0  252636  35400   4948 R 100.0  0.0   0:13.99 pgbackrest
 42319 postgres  20   0  252648  35432   4948 R 100.0  0.0   0:13.99 pgbackrest
 42320 postgres  20   0  252636  35412   4948 R 100.0  0.0   0:13.98 pgbackrest
 42438 postgres  20   0  252648  35484   4948 R 100.0  0.0   0:13.74 pgbackrest
 42439 postgres  20   0  252384  33460   4952 R 100.0  0.0   0:13.76 pgbackrest
 42440 postgres  20   0  252636  35384   4948 R 100.0  0.0   0:13.73 pgbackrest

**Comment by Rakshitha-BR** [comment]
Attaching complete output

**Comment by Rakshitha-BR** [comment]
[pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/3007252/pgbackrest.txt)

**Comment by dwsteele** [comment]
So, yeah, wow.  It looks like in this case you have `--process-max=90`?

**Comment by Rakshitha-BR** [comment]
Yes we have it set to 90 as of now.

**Comment by dwsteele** [comment]
OK, good, that's what I gleaned from the output.

So you definitely have a good case for process-max > 96, but it is baked in so it will require a release.  We'll get that in 2.12.

Just out of curiosity, how big is the database?

**Comment by Rakshitha-BR** [comment]
We actually have a citus cluster with each node around 3to4TB of data

**Comment by dwsteele** [comment]
This limit was increased in c72a94cfec64.  If you would like to appear in the release notes as something other that `Rakshitha-BR` just let me know.
