### ISSUE TITLE
Restore the physical backup(pgbackrest) present in one server into another server 

### ISSUE THREAD

**Issue by Maseer123** [pgbackrest/pgbackrest#697]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.07

2. PostgreSQL version: Postgres 10.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:RHAT 7.4

4. Did you install pgBackRest from source or from a package?
https://www.postgresql.org/download/linux/redhat/

5. Describe the issue:
Is it possible to restore using the physical backup's present in one server in to an another server where pgbackrest has been configured. if yes , could you please provide us the steps?

**Comment by dwsteele** [comment]
Yes, that's one of the major capabilities of the software.  You haven't given any details about your configuration, but in general it works like this: https://pgbackrest.org/user-guide.html#replication

These instructions assume you have a backup server, but they can be adapted to NFS storage, S3, etc.

**Comment by Maseer123** [comment]
Thanks Team..

My requirement is i have no relation between the servers and i have physical backup's in one server and i wanted to use that backup's file ( copy to another server) to restore in another server .. Is it possible?

**Comment by dwsteele** [comment]
Well, you can just copy the repo and use that.

But if you have a network connection between the servers is best to just setup pgBackRest to restore over ssh as described in the docs.

**Comment by Maseer123** [comment]
Thanks.

I copied the repository of the one server (replication enabled primary server ) and restored the data in to the other server . When i did that iam getting the below error.

2019-03-28 06:29:05.936 P00   INFO: found 000000010000000500000062 in the archive
2019-03-28 06:29:05.937 P00   INFO: archive-get command end: completed successfully (50ms)
2019-03-28 06:29:05 EDT::@:[31823]: LOG:  restored log file "000000010000000500000062" from archive
2019-03-28 06:29:05 EDT::@:[31823]: LOG:  invalid resource manager ID in primary checkpoint record
2019-03-28 06:29:05 EDT::@:[31823]: LOG:  invalid secondary checkpoint link in control file
2019-03-28 06:29:05 EDT::@:[31823]: PANIC:  could not locate a valid checkpoint record
2019-03-28 06:29:05 EDT::@:[31821]: LOG:  startup process (PID 31823) was terminated by signal 6: Aborted
2019-03-28 06:29:05 EDT::@:[31821]: LOG:  aborting startup due to startup process failure
2019-03-28 06:29:06 EDT::@:[31821]: LOG:  database system is shut down

**Comment by Maseer123** [comment]
Hi Team,

Could you please advise on the above error?

**Comment by dwsteele** [comment]
If you post your restore log we can have a look.

**Comment by Maseer123** [comment]
Thanks.

I successfully restored the backup . But when i tried to make the postgres instance up , i am getting the above error . Please check and get back..

2019-03-28 06:29:05.936 P00 INFO: found 000000010000000500000062 in the archive
2019-03-28 06:29:05.937 P00 INFO: archive-get command end: completed successfully (50ms)
2019-03-28 06:29:05 EDT::@:[31823]: LOG: restored log file "000000010000000500000062" from archive
2019-03-28 06:29:05 EDT::@:[31823]: LOG: invalid resource manager ID in primary checkpoint record
2019-03-28 06:29:05 EDT::@:[31823]: LOG: invalid secondary checkpoint link in control file
2019-03-28 06:29:05 EDT::@:[31823]: PANIC: could not locate a valid checkpoint record
2019-03-28 06:29:05 EDT::@:[31821]: LOG: startup process (PID 31823) was terminated by signal 6: Aborted
2019-03-28 06:29:05 EDT::@:[31821]: LOG: aborting startup due to startup process failure
2019-03-28 06:29:06 EDT::@:[31821]: LOG: database system is shut down

**Comment by dwsteele** [comment]
We're looking for the log for the `restore` command that you ran when restoring the database.  It will look like `/var/log/pgbackrest/[stanza]-restore.log`.  Since you have not provided any configs with your issue I'm not sure what the stanza name should be.

**Comment by Maseer123** [comment]
[AOD_tparhepost001-restore.log](https://github.com/pgbackrest/pgbackrest/files/3023109/AOD_tparhepost001-restore.log)

Attached the log . Please check.

**Comment by dwsteele** [comment]
I don't see any issues in the log.  It could be corruption in the source cluster or some other issue.  There's not enough information here to tell.

You'll need to document what you've done step by step.  For the record, making a copy of the repo is a bad idea.  The configuration shown in the user guide is more robust.  If your backup is stored on the primary server that's a bad idea as well.

**Comment by Maseer123** [comment]
We having the backup's mounts in the same server . Each day script is running to trigger the physical backup's and it is getting stored in the /pgBACKUP mount.

Could you please suggest us how we can restore the physical backup (if we have some issues with the server) of one server in to another.

* As you suggested in the above mail . 
1. I copied the repository of one server into another and changed the stanza name of the folder repositories accordingly to the current server pgbackrest.conf file.
2.Changed the location of the repo path in the conf file  where i have copied the repository and then ran the below command

pgbackrest --stanza=AOD_tparhepost001 --log-level-console=info --db-path=/pgBACKUP/data4 --set=20190327-200002F restore --tablespace-map-all=/pgBACKUP/data3/pg_tblspc --delta

Restore the mentioned path is successful  and i have provided you the log of the restore.

3. After restore , when i try to bring the instance up by changing the port in the postgresql.conf path in the restored folder. It is throwing the error.

2019-03-28 06:29:05.936 P00 INFO: found 000000010000000500000062 in the archive
2019-03-28 06:29:05.937 P00 INFO: archive-get command end: completed successfully (50ms)
2019-03-28 06:29:05 EDT::@:[31823]: LOG: restored log file "000000010000000500000062" from archive
2019-03-28 06:29:05 EDT::@:[31823]: LOG: invalid resource manager ID in primary checkpoint record
2019-03-28 06:29:05 EDT::@:[31823]: LOG: invalid secondary checkpoint link in control file
2019-03-28 06:29:05 EDT::@:[31823]: PANIC: could not locate a valid checkpoint record
2019-03-28 06:29:05 EDT::@:[31821]: LOG: startup process (PID 31823) was terminated by signal 6: Aborted
2019-03-28 06:29:05 EDT::@:[31821]: LOG: aborting startup due to startup process failure
2019-03-28 06:29:06 EDT::@:[31821]: LOG: database system is shut down

Could you please check and let me know what is the correct way to do this ?

**Comment by dwsteele** [comment]
Hmmm, I'm not seeing the problem, but this certainly looks odd: `--db-path=/pgBACKUP/data4`.  Why would you be restoring backups into your backup path? I suspect something may be overwritten but I'm not seeing it.

I can tell you this:

1) Never, ever, backup directly on your primary.  If the primary fails you'll lose it and your backups at the same time.  The repo should be somewhere you can get to it from multiple servers: a dedicated repo host (https://pgbackrest.org/user-guide.html#repo-host) or S3 (https://pgbackrest.org/user-guide.html#s3-support) or NFS.
2) If you find yourself copying the repo around, you have probably gone wrong (there are some situations where copying offsite makes sense).  The configs on your PG servers should be symmetric and ideally all the pg paths should be in the same place.

I can't stress how important it is to follow the user guide for good configuration.  What you are trying to do is fragile and complicated and not recommended.

**Comment by Maseer123** [comment]
The reason i use /pgBACKUP/data4 is the space , i have enough space there to hold my DB so i have created the folder and restored in that directory which was successful.

I completely agree with your suggestions. 

Also the main reason why we would be needing this approach is if some objects got deleted unknowingly in the DB and if we wanted to restore those tables alone , how can we would be restoring it ? Since the pgbackrest takes the physical backup's for the whole cluster and we cannot able to restore one single object/DB from it (Also if we dont have enough space in the server to restore the last full cluster backup in the same server ).. We can copy that repository to the other server where we have enough space and restore it and take a dump of the missing objects.

Please let me know if it doesn't sounds good considering our all servers has backup in the same server strategy .

**Comment by dwsteele** [comment]
If you keep your backups in a central location then you can restore to anywhere you have enough space.  The documentation covers this type of configuration in detail.

Also, it is possible to restore a single database (but not a single table): https://pgbackrest.org/user-guide.html#restore/option-db-include

**Comment by dwsteele** [comment]
Another thing to check would be sure that `pg_control` matches the backup after the restore.  I'm starting to suspect that you may have some corruption in the source database, but we should rule out some kind of overwrite or corruption on the restore.

In `/pgBACKUP/cgkcosaisp001/backup/AOD_tparhepost001/20190327-200002F/pg_data/backup.manifest` you'll find the sha1 hash for `pg_control`.  You can match this to `sha1sum /pgBACKUP/data4/global/pg_control` after a restore.  If they are the same then the restore has been successful.  If they are different then something is going wrong during the restore.
