### ISSUE TITLE
 Use of uninitialized value in numeric eq (==) at /loader/0x19080a8/pgBackRest/Db.pm line 511  when create stanza

### ISSUE THREAD

**Issue by cheucheu** [pgbackrest/pgbackrest#698]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 211

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 

 RDH 7.3 3.10.0-693.17.1.el7.x86_64 on a standalone server

4. Did you install pgBackRest from source or from a package? from package : pgbackrest-2.11-1.rhel7.x86_64.rpm 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

[global]
repo1-path=/images/repository
[localhost]
db-path=/pgqdata/pgserver01/data/backup

[global:archive-push]
compress-level=3
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

wal_level = replica                     # minimal, replica, or logic
archive_mode =  on # enables archiving; off, on, or always
                                # (change requires restart)
archive_command = 'pgbackrest --stanza=localhost archive-push %p'               # command to use to archive a logfile segment

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

NOTHING because i'am at beginning .
7. Describe the issue:

When i create the stanza with this command :

sudo -u postgres pgbackrest --stanza=localhost --log-level-console=info stanza-create

I obtain this error : 

[root@dvxx2dbc0p data]# sudo -u postgres pgbackrest --stanza=localhost --log-level-console=info stanza-create
2019-03-26 16:14:47.003 P00   INFO: stanza-create command begin 2.11: --log-level-console=info --pg1-path=/pgqdata/pgserver01/data/backup --repo1-path=/images/repository --stanza=localhost
ERROR: [124]: process terminated due to an unhandled exception:
       Use of uninitialized value in numeric eq (==) at /loader/0x19080a8/pgBackRest/Db.pm line 511.
        at /loader/0x19080a8/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('Use of uninitialized value in numeric eq (==) at /loader/0x19...') called at /loader/0x19080a8/pgBackRest/Db.pm line 511
        pgBackRest::Db::info(undef) called at /loader/0x19080a8/pgBackRest/Db.pm line 778
        pgBackRest::Db::configValidate(undef) called at /loader/0x19080a8/pgBackRest/Stanza.pm line 719
        pgBackRest::Stanza::dbInfoGet('pgBackRest::Stanza=HASH(0x2180058)') called at /loader/0x19080a8/pgBackRest/Stanza.pm line 59
        pgBackRest::Stanza::new('pgBackRest::Stanza') called at /loader/0x19080a8/pgBackRest/Main.pm line 241
        eval {...} called at /loader/0x19080a8/pgBackRest/Main.pm line 275
        pgBackRest::Main::main('stanza-create') called at (eval 270) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'stanza-create\')
       ;' called at (eval 270) line 0

2019-03-26 16:14:47.125 P00   INFO: stanza-create command end: aborted with exception [124]

Could you help me ?

Thanks a lot

**Comment by dwsteele** [comment]
Is the path to the Postgres data directory really `/pgqdata/pgserver01/data/backup`?  That looks odd.

This is a really strange error because it indicates that pg_control exists but is zero size.

What's the output of this command:
```
ls -lah /pgqdata/pgserver01/data/backup/global/pg_control
```

**Comment by cheucheu** [comment]
Hi David

Thanks a lot for your answer.

Yes, I confirm that the directory exist because i have before created.
If i dont' create it, i have this error.

[root@dvxx2dbc0p ~]# sudo -u postgres pgbackrest --stanza=localhost --log-level-console=info stanza-create
2019-03-26 17:42:10.100 P00   INFO: stanza-create command begin 2.11: --log-level-console=info --pg1-path=/pgqdata/pgserver01/data/backup --repo1-path=/images/repository --stanza=localhost
ERROR [041]: : unable to open /pgqdata/pgserver01/data/backup/global/pg_control
2019-03-26 17:42:10.222 P00   INFO: stanza-create command end: aborted with exception [041]

BR

**Comment by dwsteele** [comment]
That's not what I meant.  It looks like you are pointing `pg1-path` to a backup directory.  You shouldn't need to create the `pg1-path` directory before performing a backup.  It should already exist if you have a running Postgres cluster.

**Comment by cheucheu** [comment]
David

The Pg1-path variable was commented.  OK I suppress it in the config file but i always have the same errror.

[root@dvxx2dbc0p ~]# sudo -u postgres pgbackrest --stanza=localhost --log-level-console=info stanza-create
2019-03-26 21:17:49.919 P00   INFO: stanza-create command begin 2.11: --log-level-console=info --pg1-path=/pgqdata/pgserver01/data/backup --repo1-path=/images/repository --stanza=localhost
ERROR [041]: : unable to open /pgqdata/pgserver01/data/backup/global/pg_control
2019-03-26 21:17:50.041 P00   INFO: stanza-create command end: aborted with exception [041]

[global]
repo1-path=/images/repository

[localhost]
db-path=/pgqdata/pgserver01/data/backup

[global:archive-push]
compress-level=3

BR

**Comment by dwsteele** [comment]
`db-path` is a deprecated alias for `pg1-path`.  It's from before 2.0 so you have an old installation or old instructions.  That's fine since we support older names for options.

But it's clearly still there when you run: `stanza-create command begin 2.11: --log-level-console=info --pg1-path=/pgqdata/pgserver01/data/backup --repo1-path=/images/repository --stanza=localhost`

**Comment by cheucheu** [comment]
Hi David

Sorry for the delay
I have made a mistake with the pg1-path.   It's not corresponding to the PGDATA directory 
After fixed it, the create stanza is now OK.

Now, i have an another problem when i run a backup.

[dvxx2dbc0p:postgres:pgserver01]$pgbackrest --stanza=main  --log-level-console=info --pg1-path=/pgqdata/pgserver01/data backup
2019-03-27 14:14:42.162 P00   INFO: backup command begin 2.11: --log-level-console=info --pg1-path=/pgqdata/pgserver01/data --repo1-path=/pgqdata/pgserver01/data/backup --stanza=main
WARN: option repo1-retention-full is not set, the repository may run out of space
      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
WARN: no prior backup exists, incr backup has been changed to full
2019-03-27 14:14:43.018 P00   INFO: execute non-exclusive pg_start_backup() with label "pgBackRest backup started at 2019-03-27 14:14:42": backup begins after the next regular checkpoint completes
2019-03-27 14:14:43.231 P00   INFO: backup start archive = 000000010000008D00000064, lsn = 8D/64000028
ERROR [071]: : tablespace symlink /pgqdata/pgserver01/data/tbs_pxx201 destination must not be in $PGDATA
2019-03-27 14:14:43.733 P00   INFO: backup command end: aborted with exception [071]
[dvxx2dbc0p:postgres:pgserver01]$


[dvxx2dbc0p:postgres:pgserver01]$ls -lah /pgqdata/pgserver01/data/tbs_pxx201
total 12K
drwx------  3 postgres postgres 4.0K Jan 17 10:59 .
drwx------ 22 postgres postgres 4.0K Mar 27 03:04 ..
drwx------  3 postgres postgres 4.0K Jan 17 10:59 PG_9.6_201608131


Have you an idea ?

BR

**Comment by blogh** [comment]
Hi, 

It's not recommended to put your tablespaces in $PGDATA. [1]

Plus pgbackrest will add the content of any symlinked directory to the backup. [2]
In the backup, you would end up with the tablespace in $PGDATA and $PGDATA/pg_tbspc if pgbackrest didn't stop you from doing this.

hope this helps
Benoit

[1] https://www.postgresql.org/docs/11/manage-ag-tablespaces.html
[2] https://github.com/pgbackrest/pgbackrest/issues/252

**Comment by dwsteele** [comment]
It's just as Benoit said.  Newer versions of PostgreSQL will actually error if you do this, but older versions allowed it.

If you want to use pgBackRest, you'll need to bring the cluster down and relocate the tablespaces.  See http://www.databasesoup.com/2013/11/moving-tablespaces.html for guidance.

**Comment by cheucheu** [comment]
Hi David and Benoit

Thanks a lot for you answers.
By default, we create some tbs in PGDATA and i confirm that we will have to change our implementation.

Do you have a version of PGBACKREST that does not do this presence check? Or could you evolve your product to inhibit this control by positioning for example a specific flag?

BR

**Comment by dwsteele** [comment]
No -- this has not been supported by any version of pgBackRest and we won't support it.  It's just too risky to take backups this way and restores are even trickier.  Be careful of other backup solutions that don't have this check -- they may give you an inconsistent or doubled backup in this case.

**Comment by cheucheu** [comment]
Hi David

I understand that it will never be supported.
Could you explain to me for their existence are a problem and risks to generate inconsistency or even double the volume of backup?

Thanks a lot

BR

**Comment by dwsteele** [comment]
For example, pg_basebackup is going to make two copies of the data.  One in the tablespace dir, and one in pg_data.  On restore you'll have to reconcile that or you'll have two copies, one of which will slowly get out of data as you run the server.  That old copy will be backed up again on the next backup -- and then you need to reconcile again on restore.  This time, do you select the correct copy?  The first time it doesn't matter, the second time it really does.  It you don't get it right then you'll lose data and have corruption.

**Comment by cheucheu** [comment]
Hi David

Sorry for the delay. Thanks for your answer.

Can you tell us if your tool is able to internally store the backups catalog that you obtain  via the command pgbackrest info --stanza = test?
we would like to be able to have it if we delete by mistake the corresponding file?

BR

**Comment by dwsteele** [comment]
> Can you tell us if your tool is able to internally store the backups catalog that you obtain via the command pgbackrest info --stanza = test?

This data for the info command is stored in `archive.info` and `backup.info`.

> we would like to be able to have it if we delete by mistake the corresponding file?

We keep multiple copies of these files (e.g.`archive.info` and `archive.info.copy`) to help prevent this.  You are welcome to make copies yourself.

**Comment by cheucheu** [comment]
Hi David

I have several questions :

1/ Is it possible to separate the  backup and archive directories builded in the "repo-path"  ? In fact we have a specific directory to receive archived wals.

2/ How to restore a dropped database?     
 After, After restoring a backup containing the deleted database. this database not appears.  
 If i do the same restoration with  PITR options ( type=time and target="TS") , the database appears but i  have this message :

Template1=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 monitor   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 pgbench   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 pgbench10 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(6 rows)

template1=# \c pgbench10
FATAL:  database "pgbench10" does not exist
DETAIL:  The database subdirectory "base/25227" is missing.
Previous connection kept
template1=# \c pgbench

-3/ During a recovery process through pgbackrest, is it possible to control applied wals ?

Thanks a lot of

BR

**Comment by dwsteele** [comment]
> 1/ Is it possible to separate the backup and archive directories builded in the "repo-path" ? In fact we have a specific directory to receive archived wals.

You can symlink `<repo-path>/archive` if you like, or mount it from a different volume.

> 2/ How to restore a dropped database?

Sure, if you play to the end of WAL the the database will be gone.  If you do PITR you'll need to pick the time carefully.  DROP DATABASE is not atomic so it's possible (though unlucky) to end up in the situation above using the wrong timestamp.  Try something a bit earlier.

> -3/ During a recovery process through pgbackrest, is it possible to control applied wals ?

If you mean, apply WAL until segment X, then no.  You'll need to specify an xid, time, or restore point using `--type` and `--target`.  This is the way Postgres works, not a limitation of pgBackRest.

**Comment by cheucheu** [comment]
Hi David,

Thanks a lot of your answers. We continue to test and explore all the features.

-1 / Assuming that we decide to provide a backup strategy, 1 FULL on Sunday, incrementals on weekdays, should we plan a retention of 1 week on disk in the space dedicated to backups and archives ?

-2/ In this context, if pgbackrest deletes the previous backup full,  Is there an interest in keeping incremental backups? Does PPGBACKREST do all the cleaning?

BR

**Comment by dwsteele** [comment]
> -1 / Assuming that we decide to provide a backup strategy, 1 FULL on Sunday, incrementals on weekdays, should we plan a retention of 1 week on disk in the space dedicated to backups and archives ?

I actually prefer weekly full for as many weeks as you have space for (`repo1-retention-full=X`) and three days of differentials (`repo1-retention-diff=3`).  Differentials can be expired independently so they end up taking up less space in the end.  It's unusual to need to recover from a backup more than a few days old but the full backups are there for that case (but you'll spend more time in recovery).

> -2/ In this context, if pgbackrest deletes the previous backup full, Is there an interest in keeping incremental backups? Does PPGBACKREST do all the cleaning?

pgBackRest will automatically clean up any backups that are not needed during expiration.  So, expiring a full will remove any diff/incr that depends on it, and expiring a diff will remove any incr that depends on it.
