### ISSUE TITLE
pgbackrest restore issue

### ISSUE THREAD

**Issue by prakashrnse** [pgbackrest/pgbackrest#700]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by prakashrnse** [comment]
1.pgbackrest 2.1 version.
2.postgresql 10.4
3.rhel 7.5 
4.using yum command to installed pgbackrest.
==> cat /etc/pgbackrest.conf
[global]
repo1-path=/pgBACKUP/A4_sydcosafpp001
retention-diff=6
retention-full=1
retention-archive=7
#repo1-retention-archive-type=diff
start-fast=y
process-max=18
archive-async=y


[global:archive-push]
process-max=8

[A4_sydcosafpp001]
#db-path=/Postgres/pgDATA/data
pg1-path=/Postgres/pgDATA/data
port - 5432 listen_address=* max_wal_senders=8 wal_level=archive achive_mode=on

Hi Team,
we have installed in pgbackrest in source server i need to restore in target server in different mount point can you please help this issue how can i solve this need steps like source and target server and command to restore single db.

**Comment by prakashrnse** [comment]
Hi Team,

Please do the needful

**Comment by uspen** [comment]
pgbackrest --stanza=A4_sydcosaooo001 --pg1-path=/you/new/mount restore

**Comment by prakashrnse** [comment]
Hi uspen,

thanks for your reply we have two servers and different mount points and pgbackrest configuration file .
and i need to move source full backup to another server .
did it scp command to move the full backup set and size 450gb .
now i need to restore the single database backup using source backup file set this is our requirements.
please fine below details.

Source:

source pgbackrest config file

postgres@sydcosapp001.enterprisenet.org:/home/postgres
==> cat /etc/pgbackrest.conf
[global]
repo1-path=/pgBACKUP/A4_sydcosapp001
retention-diff=6
retention-full=1
retention-archive=7
#repo1-retention-archive-type=diff
start-fast=y
process-max=18
archive-async=y


[global:archive-push]
process-max=8

[A4_sydcosappp001]
#db-path=/Postgres/pgDATA/data
pg1-path=/Postgres/pgDATA/data

source full backup set - 20190310-200002F

scp did it in target server.

target --

target pgbackrest config file,

[global]
repo1-path=/Postgres/pgBACKUP/A4_sydcosausd001
retention-diff=4
retention-full=4
retention-archive=2
start-fast=y
process-max=6
archive-async=y


[global:archive-push]
process-max=4

[A4_sydcosausd001]
db-path=/Postgres/pgDATA/data

now source backup file in mount point - /Postgres/backup set - 20190310-200002F

now i need to restore the single database using above backup set can we provide the commands it liitle bit emergency.Thanks in advance

**Comment by dwsteele** [comment]
It's not clear exactly what you are trying to do here or why you have made a copy of the repo.  If you copy part of the repo that will almost certainly not work.

I would recommend that you follow the directions in the user-guide, in particular https://pgbackrest.org/user-guide.html#replication, which covers restoring to a new server.

**Comment by prakashrnse** [comment]
Hi dwsteele,

I am not needed for replication server just need to restore source full backup set into another production server and full backup set too restore one single database this what i need and both are production servers and they not needed for replication purpose just scp to target and need to restore do you any idea and both servers having different mount points and pgbackrest config files please do the needful.

**Comment by prakashrnse** [comment]
Hi dwsteele,

we taken the backup in production server and copy to the development to trying to recover the single database using source backup set and file system are different here now you got my point

**Comment by dwsteele** [comment]
If both servers are configured the same then you should just be able to do a restore as suggested above.  You haven't told us what commands you are running or what errors you are getting, if any.

If you want help, you'll need to provide all the steps you've taken so far and any errors you have encountered.

**Comment by prakashrnse** [comment]
Hi Dwsteele,

We have two servers one is production another one is uat .
now we have to restore the full backup backup file into uat  and using that backup file to restore single database in uat using full backup file.
both production and uat mount points are different and pgbackrest.conf file entries also different in both servers.
now i did copy the full backup file prod to uat copy done.
need to restore single database using prod source backup file in existing uat server.
so can you help me the scenario what i will do now?

**Comment by dwsteele** [comment]
You'll need to work through the user guide and develop your own backup/restore architecture.  If you have specific questions or run into issues we'll help as we can.  Most Postgres support companies work with pgBackRest so that's another option if you need help.
