### ISSUE TITLE
Error and Issues with stanza-create in master (patroni-cluster)

### ISSUE THREAD

**Issue by omm1979** [pgbackrest/pgbackrest#702]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

_______________________________________________________________________________________________________________

**1.-** pgbackrest 2.11
**2.-** postgresql 10.7-1 - patroni HA (1 master, 2 slaves) - just 1 installed pgbackrest in master (for testing).
**3.-** Ubuntu Server bionic 18.04 (virtualbox VM)
**4.-** pgbackrest installed via: apt-get install libdbd-pg-perl pgbackrest
**5.-** All ssh passwordless machines conect each other even localhost
     pgbackrest.conf
[pgbackrest.conf.txt](https://github.com/pgbackrest/pgbackrest/files/3031869/pgbackrest.conf.txt)
     patroni postgresql.conf:
[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/3031870/postgresql.conf.txt)
     patroni postgresql.base.conf:
[postgresql.base.conf.txt](https://github.com/pgbackrest/pgbackrest/files/3031871/postgresql.base.conf.txt)
     pgbackrest log file:
      [patronibkup-stanza-create.log](https://github.com/pgbackrest/pgbackrest/files/3031832/patronibkup-stanza-create.log)

**6.-** ???

**7.-** My Issue:
     I installed correctly pgbackrest as provilege user, as I show it:
     ![image](https://user-images.githubusercontent.com/43590372/55367142-1ea1c500-54db-11e9-8522-4ac3562781d6.png)

    Then check permission from pgbackrest directories:
![image](https://user-images.githubusercontent.com/43590372/55368351-0634a900-54e1-11e9-9d58-f53b584d2b62.png)

![image](https://user-images.githubusercontent.com/43590372/55368458-72afa800-54e1-11e9-8254-b934691e61ea.png)
   
    And tried: 
    start create-stanza command
#     pgbackrest --stanza=patronibkup --log-level-console=info --db-user=postgres --db-host=(patroni_prueba1/localhost) --db-port=5432 stanza-create

    **Also: Restart node, postgresql, patroni, stop/start pgbackrest**
    
    But I got the same error:
.....
    **ERROR: [050]: raised from remote process on 'patroni_prueba1': unable to acquire lock on file '/tmp/pgbackrest/patronibkup-archive.lock': Resource temporarily unavailable
                                        HINT: is another pgBackRest process running? at /loader/0x55f5d5792370/pgBackRest/Protocol/Base/Minion.pm line 159.**
.....

      error output:
![image](https://user-images.githubusercontent.com/43590372/55368597-2c0e7d80-54e2-11e9-93aa-73a4860c0654.png)
     
![image](https://user-images.githubusercontent.com/43590372/55368624-4e080000-54e2-11e9-8925-c96ec655ceca.png)

And also show /data/patroni/ (previously data directory in: /var/lib/postgresql/10/main):
      ![image](https://user-images.githubusercontent.com/43590372/55367912-e308fa00-54de-11e9-9ada-b0836366573d.png)

So as you can see, it's a bit complex, I'm just testing pgbackrest tool, I'm planning to do the localhost's backup and then the try another destination (slave/NAS storage/S3 cloud) to do remote backup. I'm stucked in this point, I hope you can help me with this, thanks, regards.

**Comment by dwsteele** [comment]
It looks like you are trying to connect backup to the same host and treat it as a remote.  If you are doing the backup from the primary then there is no reason to specify `--pg1-host`.  This is for when you are running the backup from a remote repo-host.

**Comment by omm1979** [comment]
Thanks for your reply, I tried that way because if I try with normal params, it makes the next output:
![image](https://user-images.githubusercontent.com/43590372/55424491-e8625500-556f-11e9-9c25-a94154ad5b14.png)

So I don't have any other chances to make it running? because of the configuration of patroni path? or it's another issue that I hadn't realize?, I'll wait for you reply, regards.

**Comment by dwsteele** [comment]
You can use `--pg1-socket-path=/data/patroni` to point pgBackRest at Patroni's socket directory.  Leave the `--lock-path` as default.

**Comment by omm1979** [comment]
:O, I though it wouldn't working, awesome, good tip, it works, :D, I'm very happy to make it running, I thank you very much, I will continue programming full backups y incremental, best regards.

**Comment by dwsteele** [comment]
Glad you got it working.
