### ISSUE TITLE
anyone help me about  cron  and max backup count ?

### ISSUE THREAD

**Issue by bumblebeey** [pgbackrest/pgbackrest#703]
hi i just begin use pgbackrest its really awesome. but i cant configure some settings.
i want every day full backup on 03AM, after every hour backup difference, but when create full backup delete old backups until last one ?

any one can help me about this config ?

**Comment by uspen** [comment]
repo1-retention-full=2
and other retention opt

**Comment by bumblebeey** [comment]
can u explain more? what about crons ?

**Comment by uspen** [comment]
`00 01 * * 0   postgres pgbackrest --config-path=/etc/pgbackrest-dev --type=full --stanza=dev backup &> /dev/null`
`
00 01 * * 1-6 postgres pgbackrest --config-path=/etc/pgbackrest-dev --type=full --stanza=dev backup &> /dev/null
`
https://pgbackrest.org/user-guide.html#retention

**Comment by omm1979** [comment]
Hi, My test configs are: 

#m h   dom mon dow   command
# Every day at 3 am 
0 03 * * * postgres pgbackrest --type=full --stanza=instance_name backup 2> /dev/null
**or if you do "crontab -e" with user postgres just:**
0 03 * * * pgbackrest --type=full --stanza=instance_name backup 2> /dev/null

# every hour every day
0 * * * * postgres pgbackrest --type=incr --stanza=instance_name backup 2> /dev/null
**or if you do "crontab -e" with user postgres just:**
0 * * * * pgbackrest --type=incr --stanza=instance_name backup 2> /dev/null

I hope this could help you, regards.

**Comment by bumblebeey** [comment]
thank you all, i understant  now retentions. thank you again
