### ISSUE TITLE
backup command end: aborted with exception [082]

### ISSUE THREAD

**Issue by fluca1978** [pgbackrest/pgbackrest#704]
Running pgbackrest `2.10` against PostgreSQL `11.1`, when issuing the first backup command I get:

```
2019-04-03 12:35:02.818 P00   INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
2019-04-03 12:35:02.958 P00   INFO: backup stop archive = 0000000100000037000000ED, lsn = 37/ED1EC1A0
ERROR [082]: : could not find WAL segment 0000000100000037000000ED after 60 second(s)
2019-04-03 12:36:03.211 P00   INFO: backup command end: aborted with exception [082]
```

on the server logs I have:

```
2019-04-03 12:47:39.205 CEST [9589] LOG:  comando di archiviazione fallito con codice di uscita 32
2019-04-03 12:47:39.205 CEST [9589] DETTAGLI:  Il comando di archiviazione fallito era: pgbackrest --stanza=main archive-push pg_wal/0000000100000037000000EC
```

that states the `archive_command` has failed too many times with exit code `32`.
Moreover this seems to prevent me to get also the `check` command to run. The command `pgbackrest info` states `No stanzas exist in the repository.`

What am I missing?

**Comment by dwsteele** [comment]
What does you config file look like?  It appears you have `--log-level-console=off` so you are not seeing the error, which appears to be a missing or invalid option.

Make sure you don't have any traling / characters in your paths -- 2.10 is not tolerant of that but it has been fixed for 2.12 (not yet released).

**Comment by fluca1978** [comment]
This is my configuration file, the same on the target and backup machine (is it ok to have the same?):

```
[global]
compress=y
stop-auto=y
start-fast=y
log-level-console=info
log-level-file=detail
log-timestamp=y

[main]
pg1-host=main
pg1-path=/postgres/data
pg1-host-cmd=/usr/bin/pgbackrest
pg1-host-config=/etc/pgbackrest/pgbackrest.conf
pg1-host-user=postgres

repo1-path=/mnt/backup/BACKUP/pgbackrest
```

I suspect the command is failing because trying to push the wal segment to a non existent path, could it be? I mean `repo1-path` exists only on the backup machine from which I launch `pgbackrest backup`.

**Comment by fluca1978** [comment]
I've tried to execute the `archive-push` command on an arbitrary wal segment on the database host, in order to see if I could catch a more detailed error, and in fact:

```
ERROR [072]: : archive-push operation must run on db host
2019-04-04 08:39:11.427 P00   INFO: archive-push command end: aborted with exception [072]
```

so definitely something is screwed up with my configuration.
I therefore split the configuration for the stanza on the database host configuring only `repo-xxx` parameters, and `pg1-host-xxx` parameters on the backup machine. Is this correct?

**Comment by dwsteele** [comment]
The user guide should give a pretty clear idea of what settings go where.  In general you want the pg settings on the repo server and repo settings on the pg server.  You'll need the pg1-path on both sides.

An example: https://pgbackrest.org/user-guide.html#repo-host/config
