### ISSUE TITLE
improvement ciphering per stanza

### ISSUE THREAD

**Issue by jacks33** [pgbackrest/pgbackrest#706]
Hello,

in companies some applications are critical some don't, so some require ciphering some don't.

Is it possible to provide ciphering per stanza rather than the whole repo ?

If not, as of today in backrest configuration file only one repository is supported. Recently naming has changed to add -1 to name "repo1-path"

Do you plan to manage several repositories in the same configuration file ? 

Thank you 

Tiago ANASTACIO

**Comment by dwsteele** [comment]
You can do encryption per stanza -- just put the cipher options in the stanza section.

You can also have as many repos as you like -- even one for each cluster -- by configuring the repo in the stanza section.  Or use different config files (though this is a bit more of a pain).

Note that if you have different encryption per stanza then the `info` function won't work correctly unless you specify a stanza.  We plan to fix this at some point but it has not been a high priority.

**Comment by jacks33** [comment]
Thank you that's Great work.

By the way do you have planned the "time base retention" improvement https://github.com/pgbackrest/pgbackrest/issues/54 ?

Tiago ANASTACIO
Banque de France - PostgreSQL Lead

**Comment by dwsteele** [comment]
> By the way do you have planned the "time base retention" improvement #54 ?

Yes -- we are just starting the migration of expire to C this week.  Once we have that done we are planning to add this feature before the end of the year.
