### ISSUE TITLE
Update pgbackrest from 2.07 to 2.11  backup failed with ERROR [058]

### ISSUE THREAD

**Issue by nightwish9** [pgbackrest/pgbackrest#708]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.11

2. PostgreSQL version:(PostgreSQL) 10.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Centos 7.5
4. Did you install pgBackRest from source or from a package?
yes
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
Attached
7. Describe the issue:
2019-04-10 08:00:01.431 P00   INFO: backup command begin 2.11: --log-level-console=info --pg1-host=njqmsdev --pg1-host-user=postgres --pg1-path=/dbqas/data/ --pg1-port=5532 --pg1-socket-path=/tmp --repo1-path=/var/lib/pgbackrest --repo1-retention-full=30 --stanza=qmsqas --start-fast --stop-auto --type=full
ERROR [058]: : version '10' and path '/dbqas/data' queried from cluster do not match version '10' and pg1-path '/dbqas/data/' read from '/dbqas/data//global/pg_control'
HINT: the pg1-path and pg1-port settings likely reference different clusters
2019-04-10 08:00:02.516 P00   INFO: backup command end: aborted with exception [058]

[postgresql.conf.txt](https://github.com/pgbackrest/pgbackrest/files/3061597/postgresql.conf.txt)

**Comment by dwsteele** [comment]
> Did you install pgBackRest from source or from a package?
> yes

So which one was it? :)

This should be fixed in 2.12, but you can work around it for now by removing the trailing slash from `pg1-path`.  This was an unfortunate regression in the C migration.

So `pg1-path=/dbqas/data/` => `pg1-path=/dbqas/data` should do the trick.

**Comment by nightwish9** [comment]
Got it ,it works.
Thanks a lot.
