### ISSUE TITLE
ERROR: [058]: version '9.6' and path '/var/lib/pgsql/9.6/data' queried from cluster do not match version '9.6' and pg1-path '/my/real-path' read from '/my/real-path/global/pg_control'

### ISSUE THREAD

**Issue by edib** [pgbackrest/pgbackrest#709]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
Upgrade from 2.07 -> 2.11
2. PostgreSQL version:
9.6
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
centos 7
5. Please attach the following as applicable:
-------------------PROCESS START-------------------
2019-04-12 23:00:01.471 P00   INFO: backup command begin 2.11: --log-level-file=info --pg1-host=master_ip --pg1-host-user=postgres --pg1-path=/my/real-path --pg1-port=5432 --process-max=3 --repo1-path=/my/pgbackrest --repo1-retention-full=2 --stanza=mystanza --start-fast --type=full
2019-04-12 23:00:02.745 P00  ERROR: [058]: version '9.6' and path '/var/lib/pgsql/9.6/data' queried from cluster do not match version '9.6' and pg1-path '/my/real-path/' read from '/my/real-path/global/pg_control'
                                        HINT: the pg1-path and pg1-port settings likely reference different clusters
2019-04-12 23:00:02.755 P00   INFO: backup command end: aborted with exception [058]

7. Describe the issue:
After upgrade from 2.07 -> 2.11, I am getting the same error. 
ERROR [058]: : version '9.6' and path '/var/lib/pgsql/9.6/data' queried from cluster do not match version '9.6' and pg1-path '/my/real-path' read from '/my/real-path/global/pg_control'
HINT: the pg1-path and pg1-port settings likely reference different clusters
Because, I am using symlink from the beginning, but it seems it does not understand relation in this version.

**Comment by dwsteele** [comment]
I agree this is annoying, but it is really about limiting the possibilities of things that can go wrong, especially for restore.  Having symlinks, or worse, chains of symlinks makes it very hard to reason about where a restore is going to go or how to remap the restore location.  in my experience, this causes confusion in time critical circumstances which is not good.

In RHEL, clusters can only be started from one location, but that doesn't mean postgres and pgbackrest shouldn't know about the actual path.

**Comment by dan-aksenov** [comment]
Got this problem today after upgrading to 2.15.1. pgbackrest.conf has pg1-path pointed to real(not symlinked) directory. Any advice?

**Comment by dwsteele** [comment]
@dan-aksenov Please open an issue and provide all requested information.  It appears the solution was deleted from this issue and your problem may be different anyway.

**Comment by dan-aksenov** [comment]
Created issue #779
