### ISSUE TITLE
Can I Restore a DB with different encoding using pgbackrest?

### ISSUE THREAD

**Issue by ullas-lr** [pgbackrest/pgbackrest#714]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.12

2. PostgreSQL version:
psql (PostgreSQL) 9.5.9

3. Describe the issue:
I need to change the encoding of a huge DB from ASCII to UTF8. I can do this with pg_dump and pg_restore but the DB is in production and need to minimize the downtime as much as possible. Is it possible to restore a specific DB with encoding as UTF-8 using pgbackrest? 
Please let me know if there are any other options I can look into. 

Note: The size of the DB I need to fix is 4 TB. 

Thanks in Advance!

**Comment by dwsteele** [comment]
No -- changing encoding requires rewriting the entire database.  pg_dump is the only way to do it as far as I know.
