### ISSUE TITLE
Retention for the incremental backup in pgbackrest.conf file

### ISSUE THREAD

**Issue by Maseer123** [pgbackrest/pgbackrest#716]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.06

2. PostgreSQL version:10.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

[global]
repo1-path=/pgBACKUP/A4_sydcosafpp001
retention-diff=3
retention-full=1
retention-archive=2
start-fast=y
process-max=12
archive-async=y

[global:archive-push]
process-max=4

[A4_sydcosafpp001]
pg1-path=/Postgres/pgDATA/data

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We have incremental backup scheduled in the pgbackrest . Incremental backup is running fine without any issues .. But retention is the issue we want to hold the backup's as per the retention .

retention-incr=3 seems to be not working ... Could you please let me know what conf we need to set for the incremental retention?

**Comment by dwsteele** [comment]
Incrementals can't be expired that way because all prior incrementals (back to the last full or diff) are needed to reconstruct the backup.    If you have seven incrementals in a row you can't expire the first four.

Diff backups are far more useful in this regard (even though they may be larger) since they only depend on the last full and can be expired independently.

Incidentally, setting `retention-full=1` is a bad idea.  This should be 2 at a minimum.

**Comment by Maseer123** [comment]
Yes Understood . As per the business requirement we have changed the strategy of differential to  incremental . Suppose i need to hold two full backup and rest incremental

Ex: Saturday -  Full backup 
From Sunday to friday - Incremental which is totally 6 .

What config i need to set in .conf file .

**Comment by cmwshang** [comment]
Please let us know if something in https://pgbackrest.org/configuration.html#section-repository/option-repo-retention-full and https://pgbackrest.org/user-guide.html#retention is unclear to explain the settings you need.
