### ISSUE TITLE
Error when backuping from standBy 

### ISSUE THREAD

**Issue by ahmedjami** [pgbackrest/pgbackrest#718]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):
Hello,

1. pgBackRest version: 2.11

2. PostgreSQL version: 11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package? From package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
[global]
backup-standby=y
repo-path=/opt/db/pgbackrest
repo1-retention-full=2
[MyDB]
pg1-path=/opt/db/postgresql/11/main
```

7. Describe the issue:
I'm trying to execute a backup from the standby, when performing the backup I got this error:

`pgbackrest --stanza=MyDB--log-level-console=info --type=full backup`
```

2019-04-26 21:20:40.463 P00   INFO: backup command begin 2.11: --backup-standby --log-level-console=info --pg1-path=/opt/db/postgresql/11/main --repo1-path=/opt/db/pgbackrest --repo1-retention-full=2 --stanza=MyDB--type=full
WARN: option backup-standby is enabled but standby is not properly configured - backups will be performed from the master
2019-04-26 21:20:41.067 P00   INFO: execute non-exclusive pg_start_backup() with label "pgBackRest backup started at 2019-04-26 21:20:40": backup begins after the next regular checkpoint completes
ERROR [057]: : ERROR:  recovery is in progress
HINT:  pg_walfile_name() cannot be executed during recovery.:
select to_char(current_timestamp, 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_walfile_name(lsn), lsn::text, (select setting::int8 from pg_settings where name = 'wal_segment_size') from pg_start_backup('pgBackRest backup started at 2019-04-26 21:20:40', false, false) as lsn
2019-04-26 21:20:41.271 P00   INFO: backup command end: aborted with exception [057]
```

Can you help me to resolve this issue please ?

Thx

**Comment by dwsteele** [comment]
Your primary must also be configured since some files are copied from the primary.  See: https://pgbackrest.org/user-guide.html#standby-backup.

**Comment by dwsteele** [comment]
Looks like you are trying to run backup on both servers or you have an error in your config.  What does your config look like?

**Comment by ahmedjami** [comment]
Yes, I'm trying to run backup on both servers (primary and standby) but not on the same time, this is a problem for pgbackrest ?

thanks

**Comment by dwsteele** [comment]
It looks like it was running on both at the same time because of the lock error.
