### ISSUE TITLE
Can't use stanza-delete if pgbackrest not available on DB host

### ISSUE THREAD

**Issue by hatifnatt** [pgbackrest/pgbackrest#720]
1. pgBackRest version: 2.11-1.pgdg90+1
2. PostgreSQL version: 9.6
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
DB server(s): Debian 9.9
Repo server: Debian 9.5
4. Did you install pgBackRest from source or from a package?
From official PostgreSQL repository.
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

**pgbackrest.conf**:
```
[dev-db]
compress=y
compress-level=3
compress-level-network=3
pg1-host=dev-db-03
pg1-path=/var/lib/postgresql/9.6/main
process-max=5
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y
```

**Log file**:
```
-------------------PROCESS START-------------------
2019-05-05 20:03:57.795 P00   INFO: stanza-delete command begin 2.11: --compress-level=3 --compress-level-network=3 --log-level-console=info --pg1-host=dev-db-03 --pg1-path=/var/lib/postgresql/9.6/main --repo1-path=/var/lib/pgbackrest --stanza=dev-db
2019-05-05 20:03:58.124 P00  ERROR: [042]: remote process on 'dev-db-03' terminated unexpectedly [127]: bash: pgbackrest: command not found
2019-05-05 20:03:58.125 P00   INFO: stanza-delete command end: aborted with exception [042]
```

7. Describe the issue:
Can't delete stanza from repository host if pgBackRest removed from DB host. Same if DB host not available via network.
I may be wrong, but I see no reason for connecting to remote hosts when deleting stanza on repository host.

**Comment by dwsteele** [comment]
The reason we connect to the db host is to ensure the Postgres cluster is not still running.  This is to prevent accidental deletions.

We have a `--force` option but it is checked too late to be of use here.  @cmwshang, what do you think of moving the force option up to prevent connection to the remote when it is used?

**Comment by hatifnatt** [comment]
Good reason, but I think `--force` must delete local stanza data without checks, or some new parameter required, to skip remote checks.

**Comment by dwsteele** [comment]
We discussed this and decided that we'll make `--force` to skip contacting the pg server, but running `pgbackrest stop` (a local-only operation) before `pgbackrest stanza-delete` will still be required to give some protection.  Sound good?

**Comment by hatifnatt** [comment]
Sound good for me, 2 actions must prevent accidental data deletion in most cases I think.

**Comment by dwsteele** [comment]
Committed at 18d4cb574180d2.  Let us know if you want to appear in the release notes with a name other than just "Roman", i.e. would you like us to use your full name?

**Comment by hatifnatt** [comment]
@dwsteele nickname 'hatifnatt' can be even better, if it's possible. Thank you for fixing this issue!

**Comment by dwsteele** [comment]
You are welcome!  And your contributor name has been updated.
