### ISSUE TITLE
Suggestions for configuration to back up very large databases (30-40 TB)

### ISSUE THREAD

**Issue by sean0101n** [pgbackrest/pgbackrest#722]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.13

2. PostgreSQL version: 9.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
db-host: Red Hat Enterprise Linux Server release 7.6 (Maipo) , 16 CPU 120GB mem
backup-host: CentOS Linux release 7.6.1810 (Core), 8 CPU 20 GB mem

4. Did you install pgBackRest from source or from a package?
yum install pgbackrest

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

***backup-host /etc/pgbackrest.conf***
```
[global]
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-bucket=db-backups
repo1-path=/pgbackrest
repo1-s3-key=<access_key>
repo1-s3-key-secret=<secret_key>
repo1-s3-region=us-east-1
repo1-type=s3
repo1-s3-ca-file=/etc/pki/tls/certs/ca-bundle.crt
compress-level=5

[db1]
pg1-host=db-host
pg1-host-user=postgres
pg1-path=/postgres_data/data
process-max=8
repo1-retention-full=1
repo1-retention-diff=3
```

***db-host /etc/pgbackrest.conf***
```
[global]
backup-host=bkup-host
backup-user=backrest
log-level-file=detail

[global:archive-push]
compress-level=5

[db1]
db-path=/postgres_data/data
```

***db-host postgresql.conf***
```
archive_command = 'pgbackrest --stanza=db1 archive-push %p'
archive_mode = on
listen_addresses = '*'
max_wal_senders = 5
wal_level = hot_standby
port = 5432
```

7. Describe the issue:

I wanted to ask if you have any suggestions on configuration options to use for very large databases.  We have a couple databases of over 30 TB each, and we would like to backup and restore as quickly as possible.  One database would be stored on HDD (AWS EBS sc1 volume type), while the other would be stored on SSD (AWS EBS gp2 volume type), both striped using lvm with a stripe-size of 2.  With the configurations as above, we are getting backup rates of 1TB every 5.5 hours for the database stored on HDD, and we're currently testing with SSD storage (both to s3 through the dedicated backup host).  Restore rates for HDD were 1TB every 2 hours and 22 munutes, while with SSD were 1TB every 1 hours and 12 minutes (from s3 through backup host to db server).

Is there anything in the pgbackrest configuration that you think would be able to speed backups and/or restores?

Thanks

**Comment by dwsteele** [comment]
The main thing I can see is to reduce `compress-level` to 3.  5 is not really a big change from 6.  Before you do that, though, make sure you are maxing out the 8 processes you are using (just check top during a backup).  This may just be latency from writing to (and reading from) S3.

If you maxing out the processes then adding more processes for reducing compression will help.

This summer we'll be introducing lz4 compression which is significantly faster than gzip and the new C S3 driver which is quite a bit more efficient, especially for small files.

**Comment by sean0101n** [comment]
Thanks for the suggestions.  When I was trying out compress-level of 5, all 8 cores of the backup-host were maxed out the entirety of the backup, while the database server ran ~20% usage.  I'd imagine it's due to the compression, but I thought I read in the docs that compression happens on the database server.

**Comment by dwsteele** [comment]
Compression is done on the database server.  The only thing the backup server should be doing is TLS encryption and some checksumming for S3.  Not sure why that would drive CPUs to 100% unless they are really slow.
