### ISSUE TITLE
Version 1 (>= 1.24) still available in any deb repos?

### ISSUE THREAD

**Issue by mjramtech** [pgbackrest/pgbackrest#724]
Is there a debian repository somewhere that I can pull a version 1 pgbackrest other than what seems to be the ubiquitous 1.12?

We opted for pgbackrest some time ago, prior to v2.x being released, and at that time installed version 1.24 via http://ftp.uk.debian.org/debian buster/main (we're using Stretch, not Buster, but according to my notes at the time Buster was the only release to carry an armhf build, and we needed both that and amd64).

I'm now faced with having to set a new server up (long story) and want the same version installed so I know it's on a level with all the armhf machines, but I can't find v1.24 anywhere. I dare say I could live with a more recent 1.x, but the only options I can find are 1.12 and 2.10. I can't use 1.12 because we're using non-standard ssh ports and the port option was introduced after this, and I'm very reluctant to move to 2.x given everything done to date on client/server has been with version 1.

Why such an old version 1 as the only option???

I understand BTW I could download and build/install from source, but for the sake of policy I'd much rather install a published version.

Thanks.

**Comment by dwsteele** [comment]
Unfortunately, I don't think so.  1.12 is available because it shipped with the last version of Debian.  The rest of 1.x seems to have expired.  @disco-stu may know more.

Note that if you are using ssh then the versions on each side of the connection must match.  i.e., if you update to 1.29 you'd need to update all your other servers so you might was well go to 2.x.

Furthermore, 1.24 has a known corruption bug (see https://pgbackrest.org/release.html#1.29) so if you end up building your own package be sure to set `resume=n`.

**Comment by mjramtech** [comment]
Ok thanks. I do worry a bit about dependencies installing from source also, but maybe that's what I'm stuck with.

How strict is this "same versions for ssh" requirement? It looks like there's a 1.25 still available for Ubuntu Bionic, but perhaps cross distro-ing is another can of worms anyway ...

**Comment by dwsteele** [comment]
Very strict.  Installing from source or building RPMs is likely your best bet.

Don't forget to set `resume=n` and I recommend upgrading to 2.x as soon as possible.

**Comment by disco-stu** [comment]
There is http://snapshot.debian.org/binary/pgbackrest/. It contains every version of pgBackRest that Debian  ever saw.
Hope it helps.

**Comment by mjramtech** [comment]
> 
> 
> There is http://snapshot.debian.org/binary/pgbackrest/. It contains every version of pgBackRest that Debian ever saw.
> Hope it helps.

That helps a lot disco-stu. Thank you.
