### ISSUE TITLE
ASSERT: [025]: local-1 process terminated unexpectedly [25]: ASSERT: [025]: zlib threw error: [-5] no space in buffer

### ISSUE THREAD

**Issue by rtammineni** [pgbackrest/pgbackrest#725]
pgBackRest version:
pgBackRest 2.12

PostgreSQL version:
9.4

Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.6.1810 (Core)

Did you install pgBackRest from source or from a package?
source

Please attach the following as applicable:

postgresql.conf:
archive_mode = on
archive_command = 'pgbackrest --stanza=cluster04 archive-push %p && cp %p /pg_archive/pgsql-9.4/data/%f'
wal_level = hot_standby
max_wal_senders = 20
listen_addresses = '*'
port = 5432

pgbackrest.conf:
[cluster05]
pg1-host=smoermspgdbp05p.jhaerms.com
pg1-path=/pg_data/pgsql-9.4/data
pg2-host=smoermspgdbs04p.jhaerms.com
pg2-path=/pg_data/pgsql-9.4/data
repo1-path=/pg_backup/ERMS/SMOERMSPGDB-05

[global]
backup-standby=y
repo1-retention-diff=2
repo1-retention-full=1
repo1-retention-archive=1
process-max=4
repo1-cipher-type=none
start-fast=y
stop-auto=y
log-level-console=info
log-level-file=detail

[global:archive-push]
compress-level=3

Describe the issue: 
Encountered the issue while running the following command.
pgbackrest --stanza=cluster05 --type=incr --log-level-console=info backup

WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (240 seconds elapsed)
HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.

2019-05-09 09:24:59 CDT  @ 1562 sql_error_code = 00000LOG:  archive command failed with exit code 25
2019-05-09 09:24:59 CDT  @ 1562 sql_error_code = 00000DETAIL:  The failed archive command was: pgbackrest --stanza=cluster05 archive-push pg_xlog/00000002000034440000006C
 && cp pg_xlog/00000002000034440000006C /pg_archive/pgsql-9.4/data/00000002000034440000006C
ASSERT: [025]: local-1 process terminated unexpectedly [25]: ASSERT: [025]: zlib threw error: [-5] no space in buffer
                STACK TRACE:
                common/compress/gzip/common:gzipError:85:(test build required for parameters)
                    ... function(s) ommitted ...
                common/compress/gzip/compress:gzipCompressProcess:(trace log level required for parameters)
                common/io/filter/group:ioFilterGroupProcess:(trace log level required for parameters)
                common/io/read:ioReadInternal:(trace log level required for parameters)
                common/io/read:ioRead:(trace log level required for parameters)
                storage/storage:storageCopy:(trace log level required for parameters)
                command/archive/push/file:archivePushFile:(trace log level required for parameters)
                command/archive/push/protocol:archivePushProtocol:(trace log level required for parameters)
                protocol/server:protocolServerProcess:(trace log level required for parameters)
                command/local/local:cmdLocal:(debug log level required for parameters)
                main:main:(debug log level required for parameters)
        STACK TRACE:
        command/archive/common:archiveAsyncStatus:142:(debug log level required for parameters)
        command/archive/push/push:cmdArchivePush:(debug log level required for parameters)
        main:main:(debug log level required for parameters)
2019-05-09 04:02:34 CDT  @ 1562 sql_error_code = 00000LOG:  archive command failed with exit code 25
2019-05-09 04:02:34 CDT  @ 1562 sql_error_code = 00000DETAIL:  The failed archive command was: pgbackrest --stanza=cluster05 archive-push pg_xlog/00000002000034440000006C
 && cp pg_xlog/00000002000034440000006C /pg_archive/pgsql-9.4/data/00000002000034440000006C
2019-05-09 04:02:34 CDT  @ 1562 sql_error_code = 01000WARNING:  archiving transaction log file "00000002000034440000006C" failed too many times, will try again later

**Comment by dwsteele** [comment]
This was fixed in 2.13.  See #712.

**Comment by rtammineni** [comment]
Thank you David!

Could you please send me the upgrade steps?  Also, what is the ideal value for compress-level (3 or 6)?  All our databases are close to 2TB.

**Comment by dwsteele** [comment]
> Could you please send me the upgrade steps?

There are no upgrade steps.  Just build the new version and deploy to your hosts.

> Also, what is the ideal value for compress-level (3 or 6)? 

That depends on if you want to save CPU/time or space.
