### ISSUE TITLE
Possibility to set pgbackrest nice level

### ISSUE THREAD

**Issue by marco44** [pgbackrest/pgbackrest#726]
Hi, just a suggestion… It may be interesting to be able to reduce priority of pgbackrest when it is running… so setting a nice level, or even setting it SCHED_IDLEPRIO may be interesting.

**Comment by dwsteele** [comment]
This might be a nice feature but you can do this by using `nice` so it doesn't seem like a high priority.  We prefer that any options we create make sense across a variety of platforms, including Windows.
