### ISSUE TITLE
ERROR [088]: : unable to set ownership for '/apps/postgres/n1tmp/t2/backup': Operation not permitted

### ISSUE THREAD

**Issue by Rakshitha-BR** [pgbackrest/pgbackrest#727]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:For both versions we are seeing this issue
pgbackrest-2.06  and pgbackrest-2.12
2. PostgreSQL version
postgres 10
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 7.6

4. Did you install pgBackRest from source or from a package?
package 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We are seeing the issue during restore.

[postgres@findp-dev-01 ~]$  pgbackrest restore --stanza=finpg-dev-01 --reset-pg1-host  --pg1-path=/apps/postgres/n1tmp --config=/apps/postgres/pgbackrest.conf --repo1-host=findp-dev-01 --delta
WARN: group fds in manifest cannot be used for restore, set to postgres
WARN: group root in manifest cannot be used for restore, set to postgres
WARN: user root in manifest cannot be used for restore, set to postgres
ERROR [088]: : unable to set ownership for '/apps/postgres/n1tmp/backup': Operation not permitted

ATTACHING DEBUG LOG
[debug.txt](https://github.com/pgbackrest/pgbackrest/files/3171219/debug.txt)

**Comment by dwsteele** [comment]
Does the `postgres` user exist on the host you are restoring to?  Currently it is not possible to change/ignore the user so it must exist.  You can figure out which user pgbackrest is expecting from the warnings:
```
WARN: group fds in manifest cannot be used for restore, set to postgres
WARN: group root in manifest cannot be used for restore, set to postgres
WARN: user root in manifest cannot be used for restore, set to postgres

**Comment by Rakshitha-BR** [comment]
Hi dwsteele,

We are running as postgres user itself.

**Comment by dwsteele** [comment]
Check the permissions on `/apps/postgres/n1tmp`:
```
ls -lah /apps/postgres/n1tmp
```

**Comment by Rakshitha-BR** [comment]
ls -lah /apps/postgres/n1tmp/
total 1.8M
drwxr-xr-x.  4 postgres fds  176 May  9 08:21 .
drwxr-xr-x. 27 postgres fds 4.0K May 13 19:48 ..
-rw-r-----.  1 postgres fds 194K May  9 06:11 20190509-045901F.manifest.gz
drwxr-xr-x.  2 postgres fds   10 May  9 00:41 backup
-rw-r-----.  1 postgres fds 1.6K May  9 08:18 backup.info
-rw-r-----.  1 postgres fds 933K May  9 06:51 backup.manifest
-rw-r-----.  1 postgres fds 676K May  9 08:15 backup.manifest.20190509-074725F
drwxr-xr-x.  3 postgres fds   53 May  9 22:44 t3

**Comment by dwsteele** [comment]
It looks like the permissions on your original directory were postgres:postgres but now they are postgres:fds.  pgBackRest wants to set the group to postgres but it does not have permission.

There's no way around this currently -- you'll need the user on the new system to be in the postgres group.

**Comment by Rakshitha-BR** [comment]
our permissions were always postgres:fds. Nothing has changed .I even attached the debug log.

is there any dependency issue which could cause such error.

**Comment by dwsteele** [comment]
It looks like your original PGDATA dir had a mix of things.  The root dir was owned by postgres:postgres but there was also root and fds ownership.  I could tell more if you send the `backup.manifest` of the backup you are trying to restore.

**Comment by Rakshitha-BR** [comment]
Hi dwsteele,

We caught the issue.Issue was with /apps/postgres/data folder where it was postgres:postgres and underlying files under this was postgres:fds. Where postgres is part of fds group.
After changing the data folder to postgres:fds, issue was resolved

**Comment by dwsteele** [comment]
OK, glad you figured it out, but it shouldn't have been that hard.  We're planning to make this simpler to avoid the problems you ran into.

**Comment by Rakshitha-BR** [comment]
Why would pgbackrest force to set the permissions? why cant it just restore as it is in the source?

**Comment by dwsteele** [comment]
I'm not quite sure what you mean, but we will be making it simpler in the near future.
