### ISSUE TITLE
pg_backrest  build dependencies packages

### ISSUE THREAD

**Issue by spavan27** [pgbackrest/pgbackrest#731]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.14

2. PostgreSQL version: 10, 11.2, 11.3

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: RHEL7

4. Did you install pgBackRest from source or from a package? source 

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue: where can i download  build dependencies packages for RHEL 6 and RHEL7 version ?
i verified RHEL portal, listed packages in the user guide is not part of rhel package 
install build-essential libssl-dev libxml2-dev libperl-dev zlib1g-dev

**Comment by dwsteele** [comment]
Those are the Debian packages from the Debian install guide.  You can find RHEL7 build instructions here: https://pgbackrest.org/user-guide-centos7.html#build

Better yet, use the packages available from https://yum.postgresql.org.
