### ISSUE TITLE
FATAL:  requested recovery stop point is before consistent recovery point

### ISSUE THREAD

**Issue by mjramtech** [pgbackrest/pgbackrest#733]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

1.24

2. PostgreSQL version:

9.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Debian, Stretch

4. Did you install pgBackRest from source or from a package?

Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

[global]
backup-host=[private server]
backup-user=backrest
backup-ssh-port=2022
log-level-file=detail
archive-async=y
spool-path=/var/spool/pgbackrest

[global:archive-push]
process-max=2

[cie_spt_4096]
db-path=/media/usb-hdd/database/postgresql/9.5/main

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

I've tried a few PITRs and am hitting the same error each time, e.g.:

pgbackrest --log-level-console=info --stanza=cie_spt_4096 --delta --type=time "--target=2019-05-27 22:00:00.00+00" restore
2019-05-29 13:34:08.897 P00   INFO: restore command begin 1.24: --backup-host=cie_backup.ramtech.co.uk --backup-ssh-port=2022 --backup-user=backrest --db1-path=/media/usb-hdd/database/postgresql/9.5/main --delta --log-level-console=info --log-level-file=detail --stanza=cie_spt_4096 "--target=2019-05-27 22:00:00.00+00" --type=time

Postgres log:
2019-05-29 13:36:39.238 P00   INFO: archive-get command end: completed successfully
2019-05-29 13:36:39.841 P00   INFO: archive-get command begin 1.24: --backup-host=[private server] --backup-ssh-port=2022 --backup-user=backrest --db1-path=/media/usb-hdd/database/postgresql/9.5/main --log-level-console=info --log-level-file=detail --stanza=cie_spt_4096
2019-05-29 13:36:40.081 P00   INFO: get WAL segment 00000002000000080000005D
2019-05-29 13:36:41.530 P00   INFO: archive-get command end: completed successfully
2019-05-29 12:36:41 UTC [5596-3] LOG:  restored log file "00000002000000080000005D" from archive
2019-05-29 12:36:41 UTC [5596-4] LOG:  redo starts at 8/5D000098
2019-05-29 12:36:41 UTC [5596-5] LOG:  recovery stopping before commit of transaction 12365805, time 2019-05-29 00:00:22.707493+00
2019-05-29 12:36:41 UTC [5596-6] FATAL:  requested recovery stop point is before consistent recovery point
2019-05-29 12:36:41 UTC [5595-1] LOG:  startup process (PID 5596) exited with exit code 1
2019-05-29 12:36:41 UTC [5595-2] LOG:  terminating any other active server processes

Now I've read a number of similar posts, but all suggest this is because I'm attempting a restore for a time that isn't available or that falls within a backup start/stop window. Varying the time/date doesn't seem to change anything though. As I understand it the full and differential backups detailed below should facilitate the requested restore, no?

cat /media/usb-hdd/database/postgresql/9.5/main/recovery.conf
restore_command = '/usr/bin/pgbackrest --log-level-console=info --stanza=cie_spt_4096 archive-get %f "%p"'
recovery_target_time = '2019-05-27 22:00:00.00+00'

pgbackrest info
stanza: cie_spt_4096
    status: ok

    db (current)
        wal archive min/max (9.5-1): 000000020000000800000044 / 00000002000000080000005F

        full backup: 20190523-163401F
            timestamp start/stop: 2019-05-23 17:34:01 / 2019-05-23 17:35:46
            wal start/stop: 000000020000000800000044 / 000000020000000800000044
            database size: 63.8MB, backup size: 63.8MB
            repository size: 6.9MB, repository backup size: 6.9MB

        diff backup: 20190523-163401F_20190524-000001D
            timestamp start/stop: 2019-05-24 01:00:01 / 2019-05-24 01:00:49
            wal start/stop: 000000020000000800000047 / 000000020000000800000047
            database size: 63.8MB, backup size: 3.6MB
            repository size: 6.9MB, repository backup size: 626.8KB
            backup reference list: 20190523-163401F

        diff backup: 20190523-163401F_20190525-000001D
            timestamp start/stop: 2019-05-25 01:00:01 / 2019-05-25 01:01:04
            wal start/stop: 00000002000000080000004C / 00000002000000080000004C
            database size: 64.1MB, backup size: 10.2MB
            repository size: 7MB, repository backup size: 1.4MB
            backup reference list: 20190523-163401F

        full backup: 20190526-000001F
            timestamp start/stop: 2019-05-26 01:00:01 / 2019-05-26 01:01:26
            wal start/stop: 000000020000000800000051 / 000000020000000800000051
            database size: 64.1MB, backup size: 64.1MB
            repository size: 7MB, repository backup size: 7MB

        diff backup: 20190526-000001F_20190527-000001D
            timestamp start/stop: 2019-05-27 01:00:01 / 2019-05-27 01:00:24
            wal start/stop: 000000020000000800000055 / 000000020000000800000055
            database size: 63.9MB, backup size: 9.3MB
            repository size: 7MB, repository backup size: 1.2MB
            backup reference list: 20190526-000001F

        diff backup: 20190526-000001F_20190528-000001D
            timestamp start/stop: 2019-05-28 01:00:01 / 2019-05-28 01:00:52
            wal start/stop: 000000020000000800000059 / 000000020000000800000059
            database size: 63.8MB, backup size: 9.5MB
            repository size: 6.9MB, repository backup size: 1.2MB
            backup reference list: 20190526-000001F

        diff backup: 20190526-000001F_20190529-000001D
            timestamp start/stop: 2019-05-29 01:00:01 / 2019-05-29 01:01:01
            wal start/stop: 00000002000000080000005D / 00000002000000080000005D
            database size: 63.8MB, backup size: 9.7MB
            repository size: 6.9MB, repository backup size: 1.3MB
            backup reference list: 20190526-000001F

**Comment by mjramtech** [comment]
Update:

It seems I can restore to a point prior to the last full back, but not after. Are the subsequent diff backups of no use?

This succeeded:
pgbackrest --log-level-console=info --stanza=cie_spt_4096 --set=20190523-163401F_20190525-000001D --delta --type=time "--target=2019-05-25 22:00:00.00+00" restore

**Comment by dwsteele** [comment]
You can't restore *any* backup to a time before it achieves consistency (i.e. between the backup start and end times.)  You'd use to previous backup for that target instead.

This limitation is not related to pgbackrest -- it is the way recovery works in PostgreSQL.

**Comment by mjramtech** [comment]
Sorry, I don't quite get your last comment. What times are counted as "between the backup start and end times"? I'd take that to mean literally between the timestamps below for diff backup 20190526-000001F_20190529-000001D:

timestamp start/stop: 2019-05-29 01:00:01 / 2019-05-29 01:01:01

Given the output of 'pgbackrest info' above, why would the below command be requesting a restore between a backup start and end time?

pgbackrest --log-level-console=info --stanza=cie_spt_4096 --delta --type=time "--target=2019-05-27 22:00:00.00+00" restore

Sorry if I've missed something here.

**Comment by dwsteele** [comment]
A better way to say it is your target must be after `timestamp stop`.  Postgres does not reach consistency until that time and it cannot go backwards.

Your example target above is two days before the backup was taken.  You'd need to pick a backup that ended before that time to hit that target.
