### ISSUE TITLE
stanza-create failing: not using $PGUSER

### ISSUE THREAD

**Issue by julianzhang98** [pgbackrest/pgbackrest#735]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.1.4

2. PostgreSQL version: 11.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS release 6.10 (Final)

4. Did you install pgBackRest from source or from a package? Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

[demo]
pg1-path=/var/data/persistent/postgresql
pg1-socket-path=/var/tmp/data

[global]
repo1-path=/var/data/persistent/pgbackrest
repo1-retention-full=2

[global:archive-push]
compress-level=3

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

archive_mode = on
archive_command = 'pgbackrest --stanza=demo archive-push %p'
listen_addresses = '*'
max_wal_senders = 7
wal_level = hot_standby
port = 5432

    - errors in the postgresql log file before or during the time you experienced the issue

Role 'vagrant' does not exist 

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

-------------------PROCESS START-------------------
2019-05-30 01:26:07.516 P00   INFO: stanza-create command begin 2.14: --log-level-console=info --pg1-path=/var/data/persistent/postgresql --repo1-path=/var/data/persistent/pgbackrest --stanza=demo
2019-05-30 01:26:07.652 P00  ERROR: [056]: FATAL:  password authentication failed for user "vagrant"
2019-05-30 01:26:07.654 P00   INFO: stanza-create command end: aborted with exception [056]

7. Describe the issue:

when I run pgbackrest --stanza=demo --log-level-console=info stanza-create, if i don't specify pg-host, why does it assume my postgres user is my logon user instead of the user set in the $PGUSER variable?

**Comment by dwsteele** [comment]
Good question -- it has never come up before that I can recall.  pgBackRest commands are generally run with peer-authenticated users so there's hasn't been a need to worry about using a different user on the local host.

It seems like a reasonable thing to do, but I wonder how much breakage it would cause if we changed this behavior now.

**Comment by mashuma** [comment]
I've run into the same issue.

My use case is one where the PG instance had been init with different than default superuser. It is not postgres.
```
$ export PGUSER=postgres_superuser
$ pgbackrest --stanza=demo stanza-create
2019-06-06 19:06:27.568 P00   INFO: stanza-create command begin 2.14: --log-level-console=info --pg1-path=/data/db/data --pg1-port=5431 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/data/pgbackrest --stanza=demo
ERROR [056]: : FATAL:  Peer authentication failed for user "postgres"
2019-06-06 19:06:27.722 P00   INFO: stanza-create command end: aborted with exception [056]
```

We will in future and for legacy push for not using custom superuser, however for time being, I'm unable to utilise pgbackrest because of this.

psql peer auth works ok
```
$ psql -U postgres_superuser -d postgres -p5431
psql (9.4.22)
Type "help" for help.

postgres=#
```

**Environment**
```
Ubuntu 18.04.2 LTS
```
```
$ id
uid=114(postgres) gid=119(postgres) groups=119(postgres),118(ssl-cert)
```
```
$ cat /data/db/data/pg_ident.conf
# MAPNAME       SYSTEM-USERNAME         PG-USERNAME
auth_map    postgres        postgres_superuser
```
```
$ cat /data/db/data/pg_hba.conf
local   all           all                          ident   map=auth_map
...
```
```
$ cat /etc/pgbackrest.conf
[global]
process-max=8
repo1-path=/data/pgbackrest
repo1-retention-diff=2
repo1-retention-full=2
repo1-cipher-pass=<redacted>
repo1-cipher-type=aes-256-cbc
start-fast=y
log-level-console=info

[global:archive-push]
compress-level=3

[demo]
pg1-path=/data/db/data
pg1-port=5431
```

**Comment by dwsteele** [comment]
That's not an ideal situation, but it should certainly work.  We'll target this change for the next release in about two weeks.

**Comment by dwsteele** [comment]
Committed at 0efdf2576f02b1768fb.
