### ISSUE TITLE
ERROR: [124]: process terminated due to an unhandled exception:

### ISSUE THREAD

**Issue by rishabh2018** [pgbackrest/pgbackrest#736]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.14

2. PostgreSQL version:PostgreSQL 11.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: PostgreSQL 11.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit

4. Did you install pgBackRest from source or from a package? yes

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:GO_ETL@ykt2pslpoc1.globeop.com:/optware/postgres>pgbackrest --stanza=GO_ETL --log-level-console=info stanza-create
2019-05-30 20:50:47.007 P00   INFO: stanza-create command begin 2.14: --log-level-console=info --log-path=/postbackup/LOG/pgbackrest --pg1-path=/optware/postgres/GOETL --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/optware/postgres/pgbackrest --stanza=GO_ETL
ERROR: [124]: process terminated due to an unhandled exception:
       DBD::Pg object version 0 does not match bootstrap parameter 3.7.4 at /usr/lib64/perl5/DynaLoader.pm line 213.
        at /loader/0x1e2d298/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('DBD::Pg object version 0 does not match bootstrap parameter 3...') called at /usr/lib64/perl5/DynaLoader.pm line 213
        DynaLoader::bootstrap('DBD::Pg', 'version=HASH(0x26dbfb8)') called at /usr/local/lib64/perl5/DBD/Pg.pm line 79
        require DBD/Pg.pm called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        pgBackRest::Db::BEGIN() called at /usr/local/lib64/perl5/DBD/Pg.pm line 0
        eval {...} called at /usr/local/lib64/perl5/DBD/Pg.pm line 0
        require pgBackRest/Db.pm called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        pgBackRest::Archive::Common::BEGIN() called at /usr/local/lib64/perl5/DBD/Pg.pm line 0
        eval {...} called at /usr/local/lib64/perl5/DBD/Pg.pm line 0
        require pgBackRest/Archive/Common.pm called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        pgBackRest::Archive::Info::BEGIN() called at /usr/local/lib64/perl5/DBD/Pg.pm line 0
        eval {...} called at /usr/local/lib64/perl5/DBD/Pg.pm line 0
        require pgBackRest/Archive/Info.pm called at /loader/0x1e2d298/pgBackRest/Stanza.pm line 23
        pgBackRest::Stanza::BEGIN() called at /usr/local/lib64/perl5/DBD/Pg.pm line 0
        eval {...} called at /usr/local/lib64/perl5/DBD/Pg.pm line 0
        require pgBackRest/Stanza.pm called at /loader/0x1e2d298/pgBackRest/Main.pm line 227
        eval {...} called at /loader/0x1e2d298/pgBackRest/Main.pm line 264
        pgBackRest::Main::main('stanza-create') called at (eval 273) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'stanza-create\')
       ;' called at /usr/local/lib64/perl5/DBD/Pg.pm line 0
       Compilation failed in require at /loader/0x1e2d298/pgBackRest/Db.pm line 10.
        at /loader/0x1e2d298/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('DBD::Pg object version 0 does not match bootstrap parameter 3...') called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        pgBackRest::Db::BEGIN() called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        eval {...} called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        require pgBackRest/Db.pm called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        pgBackRest::Archive::Common::BEGIN() called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        eval {...} called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        require pgBackRest/Archive/Common.pm called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        pgBackRest::Archive::Info::BEGIN() called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        eval {...} called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        require pgBackRest/Archive/Info.pm called at /loader/0x1e2d298/pgBackRest/Stanza.pm line 23
        pgBackRest::Stanza::BEGIN() called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        eval {...} called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        require pgBackRest/Stanza.pm called at /loader/0x1e2d298/pgBackRest/Main.pm line 227
        eval {...} called at /loader/0x1e2d298/pgBackRest/Main.pm line 264
        pgBackRest::Main::main('stanza-create') called at (eval 273) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'stanza-create\')
       ;' called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
       BEGIN failed--compilation aborted at /loader/0x1e2d298/pgBackRest/Db.pm line 10.
        at /loader/0x1e2d298/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('DBD::Pg object version 0 does not match bootstrap parameter 3...') called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        require pgBackRest/Db.pm called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        pgBackRest::Archive::Common::BEGIN() called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        eval {...} called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        require pgBackRest/Archive/Common.pm called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        pgBackRest::Archive::Info::BEGIN() called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        eval {...} called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        require pgBackRest/Archive/Info.pm called at /loader/0x1e2d298/pgBackRest/Stanza.pm line 23
        pgBackRest::Stanza::BEGIN() called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        eval {...} called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
        require pgBackRest/Stanza.pm called at /loader/0x1e2d298/pgBackRest/Main.pm line 227
        eval {...} called at /loader/0x1e2d298/pgBackRest/Main.pm line 264
        pgBackRest::Main::main('stanza-create') called at (eval 273) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'stanza-create\')
       ;' called at /loader/0x1e2d298/pgBackRest/Db.pm line 10
       Compilation failed in require at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16.
        at /loader/0x1e2d298/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('DBD::Pg object version 0 does not match bootstrap parameter 3...') called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        pgBackRest::Archive::Common::BEGIN() called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        eval {...} called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        require pgBackRest/Archive/Common.pm called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        pgBackRest::Archive::Info::BEGIN() called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        eval {...} called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        require pgBackRest/Archive/Info.pm called at /loader/0x1e2d298/pgBackRest/Stanza.pm line 23
        pgBackRest::Stanza::BEGIN() called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        eval {...} called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        require pgBackRest/Stanza.pm called at /loader/0x1e2d298/pgBackRest/Main.pm line 227
        eval {...} called at /loader/0x1e2d298/pgBackRest/Main.pm line 264
        pgBackRest::Main::main('stanza-create') called at (eval 273) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'stanza-create\')
       ;' called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
       BEGIN failed--compilation aborted at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16.
        at /loader/0x1e2d298/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('DBD::Pg object version 0 does not match bootstrap parameter 3...') called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        require pgBackRest/Archive/Common.pm called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        pgBackRest::Archive::Info::BEGIN() called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        eval {...} called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        require pgBackRest/Archive/Info.pm called at /loader/0x1e2d298/pgBackRest/Stanza.pm line 23
        pgBackRest::Stanza::BEGIN() called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        eval {...} called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
        require pgBackRest/Stanza.pm called at /loader/0x1e2d298/pgBackRest/Main.pm line 227
        eval {...} called at /loader/0x1e2d298/pgBackRest/Main.pm line 264
        pgBackRest::Main::main('stanza-create') called at (eval 273) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'stanza-create\')
       ;' called at /loader/0x1e2d298/pgBackRest/Archive/Common.pm line 16
       Compilation failed in require at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20.
        at /loader/0x1e2d298/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('DBD::Pg object version 0 does not match bootstrap parameter 3...') called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        pgBackRest::Archive::Info::BEGIN() called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        eval {...} called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        require pgBackRest/Archive/Info.pm called at /loader/0x1e2d298/pgBackRest/Stanza.pm line 23
        pgBackRest::Stanza::BEGIN() called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        eval {...} called at /loader/0x1e2d298/pgBackRest/Archive/Info.pm line 20
        require pgBackRest/Stanza.pm called at /loader/0x1e2d298/pgBackRest/Main.pm line 227
        eval {...} called at /loader/0x1e2d298/pgBackRest/Main.pm line 264
        pgBackRest:
2019-05-30 20:50:47.118 P00   INFO: stanza-create command end: aborted with exception [124]

[pgbackrest_conf.txt](https://github.com/pgbackrest/pgbackrest/files/3239260/pgbackrest_conf.txt)
[postgresql_conf.txt](https://github.com/pgbackrest/pgbackrest/files/3239262/postgresql_conf.txt)

**Comment by dwsteele** [comment]
It looks the the .so that goes with this module is the wrong version.  Given that it is reporting 0 it could be corruption or a bad build.

Note that this appears to be an issue with the DBD::Pg module, not pgBackRest.
