### ISSUE TITLE
Outdated documentation 6.4 Configure Archiving wal_level = hot_standby

### ISSUE THREAD

**Issue by hitech73** [pgbackrest/pgbackrest#737]
1. pgBackRest version: 2.14
2. PostgreSQL version: 11
3. Operating system/version : CentOS/7
4. Did you install pgBackRest from source or from a package? package
7. Describe the issue:
In the documentation "pgBackRest User Guide" section "6.4 - Configure Archiving" 
the wal_level = hot_standy no longer exists in 9.6 and up. Should probably be replaced with replica

**Comment by dwsteele** [comment]
Indeed.  The old value is still accepted, but we shouldn't be using it in the documentation for newer versions.

Should we use `hitech73` in the release notes or would you prefer another name?

**Comment by hitech73** [comment]
Can we use my name ?


Panamel Solutions d'Affaires Inc.
Patrick McLaughlin
Chargé de projet
T: (514) 667-4526
www.panamel.com

**Comment by dwsteele** [comment]
Committed at d7bd0c58cdd9a434aa.  Thanks!
