### ISSUE TITLE
Time based retention

### ISSUE THREAD

**Issue by sujiplr** [pgbackrest/pgbackrest#741]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by sujiplr** [comment]
@dwsteele , There is already an issue raised long back with #54 for a time based backup retention management,  is this time based backup retention feature got added in some other way ? or adding this time based retention is not going to be considered? Can you please help.

In our environment, backup retention is based on days. Can you help, how can I implement that using pgbackrest ?

**Comment by cmwshang** [comment]
@sujiplr Considering the following schedule in cron, where F is Full and d is Differential backups:
Sun - F1
Mon - d1a
Tues - d1b
Wed - F2
Thus - d2a
Fri - d2b
Sat - d2c
Sun - F3
Mon - d3a
Tues - d3b
Wed - F4

You keep a weeks worth of all your backups by setting full retention to 3. That way when the second Wednesday rolls around, full backup F4 will be generated which will be part of the 3 you are retaining, and then F1, d1a, d1b will be expired and the first Wednesday to the second Wednesday (1 week) will be retained.

This is a very simplistic example, but should get you started.

**Comment by sujiplr** [comment]
We can't trust on number of backups.
 If we are keeping the retention based on number of backups, if we want to
take an ad-hoc backup,then in those cases it will be a problem.

So always better to keep backups with retention. So that we can't trust
that.
Also we have monthly and yearly separate backups,that will go to 1 year and
7 year retention respectively. This is the ideal situation for a enterprise
backups.

Is there any option for the same?

**Comment by dwsteele** [comment]
There is currently no easy way to do what you want.  One thing you could do is disable retention and then expire backups according to your needs.  There's no command for that (yet) but removing the `backup.manifest` file from a backup is how we expire internally (then the files are deleted later).  Adding a command to expire a specific backup is also something that would be pretty easy to add.

**Comment by sujiplr** [comment]
One suggestion from my side is that, If you you can add the backup Renton
time range parameter option for each stanza or global block and if the same
can be added to the backup.info file backup set and based on that, tool can
expire the backups.

We can use the same file (parse the file info)  for the reporting purpose
as well.

Reporting is always a critical piece in backups.

**Comment by dwsteele** [comment]
We have discussed this internally and time-based retention is not going to make it onto the roadmap until next year.  Your scheme sounds complicated enough that our implementation might not suit your needs anyway.

Of course, you are welcome to develop a patch but if you do so be sure to discuss it with us first to be sure it meets our requirements.
