### ISSUE TITLE
pgbackrest version mismatch

### ISSUE THREAD

**Issue by Yuxael** [pgbackrest/pgbackrest#742]
Hello,
I have a question regarding changes introduced in commit e01e6b9e1a9c598715f7ad86177930fb3963e56

From that moment pgbackrest checks for precise version of repo and client binary and if it's not the same it will throw an error. What was the reason behind this? Is it really necessary to check pgbackrest version all the way down to the minor release version (and also revision and build if it were used)? Couldn't we settle for one protocol version and keep that throughout some number of releases or just check major version?

I'm asking this because, frankly, it's a royal pain in the a*s to keep all clients and repo server version consistent. Especially when dealing with various older as well as fresh new client servers. Whenever I'm adding new postgresql server to be backed up by pgbackrest I'm essentially forced to update repo server as well as all clients, which is not always possible. This is a huge blocker for me to automate it and deploy pgbackrest backups on a bigger scale.

inb4 - In my case building from source is not a solution since it would greatly increase time and cost of maintenance.

**Comment by dwsteele** [comment]
It's always been like that -- commit 2e01e6b9e1a9c598715f7ad86177930fb3963e56 just made the error reporting better.

I agree that it's a pain to deal with and we want to get to a point where we have a stable protocol layer but we are not there yet.  Especially during this migration the protocol changes with every release.  The protocol format stays they same, but the capabilities change.

When you build a new server install the version of pgbackrest that is on your other servers.  Then you can schedule your upgrades for more convenient times.  Or you can use shared storage which allows different versions to be installed on your servers.

**Comment by Yuxael** [comment]
Thanks for quick response.
If I want to back up several different distro releases with various postgresql versions it's not that simple. That was my initial plan - install the same version that's on repo server, but reality kicked in ;) If only official apt repo kept older versions... Also it's not the problem of building new server from scratch, but adding _new_ client server, usually with older/different OS.
Can you shed a little light on the planned timeline of getting stable protocol? Is it weeks, months, years?
Maybe I can contribute somehow to the project? :)

**Comment by dwsteele** [comment]
> If only official apt repo kept older versions

You can find almost all past versions of pgBackRest for Debian here: http://snapshot.debian.org/binary/pgbackrest.  That's not always helpful depending on your distro, but it is a resource.  I do wish apt.p.o kept more versions but I'm sure it's a space issue (@disco-stu?).

> Can you shed a little light on the planned timeline of getting stable protocol? Is it weeks, months, years?

My hope is year (singular) but it's hard to say for sure how that will go.  Until we finish the migration we can't even think about stable protocol versions.

> Maybe I can contribute somehow to the project? :)

We welcome all sorts of contributions! Right now we are mainly interested in new storage drivers but there are plenty of other areas that could be interesting.  What were you thinking?

**Comment by disco-stu** [comment]
@dwsteele: The main problem why apt.p.o doesn't provides multiple versions of the same package is reprepro. reprepro isn't capable of holding different versions. Disk space would be the next problem to solve.

**Comment by dwsteele** [comment]
@disco-stu Good to know.  I was wondering if perhaps we could get more funding for disks...

@Yuxael A good thing to do here is run a Debian mirror for your enterprise.  Then you can pin versions and only upgrade when you are ready.

**Comment by Yuxael** [comment]
@disco-stu Are you referring to https://salsa.debian.org/brlink/reprepro/blob/debian/docs/FAQ paragraph 1.2? What amount of disk space are we talking about?

@dwsteele Yeah, I will try to pursue the problem in that direction. Although for now faster and cheaper would be to install from source. We'll see how it goes. As to contributing... Well, I'm no developer, not a good one, to say the least ;) My area is sysops/devops so in that matter if feel more confident to help.

**Comment by dwsteele** [comment]
> Well, I'm no developer, not a good one, to say the least ;) My area is sysops/devops so in that matter if feel more confident to help.

Fair enough.  Just reporting issues that you see is very helpful for us.

**Comment by df7cb** [comment]
apt.postgresql.org is providing old versions at https://wiki.postgresql.org/wiki/Apt/FAQ#Where_are_older_versions_of_the_packages.3F

**Comment by dwsteele** [comment]
I'm adding an FAQ entry with this URL and one that Adrian posted on another issue.
