### ISSUE TITLE
Google Cloud Bucket Support

### ISSUE THREAD

**Issue by mspruthv** [pgbackrest/pgbackrest#743]
Hi Team, 

This is not an issue filing, I'm just curious to know is there any plans to support Google Cloud Buckets (Ref: #631 milestone: 2.08)? along with AWS S3.

Since we are in the GCP platform, it would be easy for us to use the GCP buckets for backups storage.

1. pgBackRest version: 2.14

2. PostgreSQL version: 11.3-1

3. Operating system/version: Ubuntu 18.04 

Thanks In Advance,
Pruthviraj

**Comment by dwsteele** [comment]
Yes, we are planning to support GCS, but we don't have a timeline for it yet.  GCS and Swift are the first additional storage drivers that we want to add.

**Comment by dwsteele** [comment]
GCS support was added in 088662d and will be released with pgBackRest 2.33.
