### ISSUE TITLE
backup withe different retentions

### ISSUE THREAD

**Issue by sujiplr** [pgbackrest/pgbackrest#744]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by sujiplr** [comment]
@dwsteele  , as per the business team requirement. We have to take backups with three different strategy (for production).

1. Daily backups -> That should be kept with 45 days retention.
2. Monthly Full backup -> Should kept for 1 year retention.
3. Yearly full backups -> Should kept for 7 year retention.

When I checked and tested with pgbackrest, there is no option for time based retention. Also,thought of keeping the backup expiry in the configuration as unlimited and try removing the backup can be expired through a custom script from our side ( by removing backup.manifest file) . But in that case also, the backups which are moving to monthly and yearly , will force the WAL files to be there . So that will hold the complete WAL files generated by the database for always. 

What is the option to implement this, requirement?

**Comment by dwsteele** [comment]
Please don't open new issues for the same question.  If you have additional details add them to issue #741.
