### ISSUE TITLE
PGBACKREST: Restoring  DB Backups with out stanza 

### ISSUE THREAD

**Issue by srichunduru** [pgbackrest/pgbackrest#745]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.14

2. PostgreSQL version:11.2 Still in PC mode 

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?
Yes

7. Describe the issue:
1)We want to restore the backup in a new server if the primary node crashes and stanza  info is lost
2)How do we do DB refreshes with out Stanza  on a different server

In oracle rman backup, we can restore backups in no catalog mode by giving a command , catalog start with which  will recover the files with out stanza 

Pls help ..

**Comment by dwsteele** [comment]
> 1)We want to restore the backup in a new server if the primary node crashes and stanza info is lost

Not sure what you mean by this.  If you are doing backup locally on the primary then that's a bad idea.  You should backup to another host, shared storage (e.g. NFS), or an object store (e.g. S3).

> 2)How do we do DB refreshes with out Stanza on a different server

See https://pgbackrest.org/user-guide.html#replication for instructions on how to restore to another server.

> In oracle rman backup, we can restore backups in no catalog mode by giving a command , catalog start with which will recover the files with out stanza

I'm not familiar with rman so this doesn't make much sense to me.

**Comment by mahomedh** [comment]
Why don't you just backup your `pgbackrest.conf`? That way you just install pgbackrest on another server, restore your `pgbackrest.conf` and assuming your data is stored on a different storage other than your primary DB server, then you can run your info and restore commands just fine on another server (also assuming you've also already just installed postgresql and deleted the contents of the new data directory as I wouldn't use the `--delta` option for such a restore on a new server)

**Comment by srichunduru** [comment]
I was planning to create stanza in the same  prod server so that i skip the network for the backing up 
Pls correct me if i am thinking wrong

**Comment by mahomedh** [comment]
If you don't backup to the network, or external drive or tape drive etc. What happens when your server won't boot, or your drives fail or your RAID card fails or the data on the server gets corrupted/encrypted?

It's the same as locking your door when you go out, but leave the key in the door because you don't want to carry the key or keep taking it out and putting it back in the door.

**Comment by srichunduru** [comment]
we normally scp the backups to DR servers after  taking the backups in current system 
we have lot of data which will take hours to recover if we store the backups on network

**Comment by dwsteele** [comment]
You might want to test that.  Delta restore is very fast.

But if you do backup to the primary also make a backup of your `pgbackrest.conf` file, or automate creating it with your favorite CM tool.
