### ISSUE TITLE
Post Backup hook script for slack notifications

### ISSUE THREAD

**Issue by mahomedh** [pgbackrest/pgbackrest#747]
1. pgBackRest version: `2.14`

2. PostgreSQL version: `11.3`

3. Operating system/version: `Ubuntu 18.04.2` on all three servers

4. Did you install pgBackRest from source or from a package? `apt get install` from `postresql repo`

Hi

Firstly thanks for this awesome software. I found the learning curve to be a bit steep but I've now got the backups and restores working from the command line and I know I can put the commands into cron to schedule it. Ideally though I'd like to send the backup success/failure notification to slack rather than having to check the logs manually as I'll have several stanzas. 

My setup is: 1 backup server with multiple replication database server pairs for each customer. All backing up to a MinIO repo. So all the cron jobs will run from the backup server for each of the stanzas. Ideally I'd like to run a notification script when the backup job works, but I can't see any way of doing this other than writing my own script to call pgBackRest and then when the backup finishes, I send the status to slack. I am fine to do this, apart from the fact that I am not too sure how I can get the outcome of the backup job.

The current solution I am thinking of is to read each output line and then capture the `command end` line and send this text to slack.

Is there a better way? Any help or direction will be greatly appreciated. Thanks.

**Comment by dwsteele** [comment]
The biggest issue with this type of design is that it doesn't tell you when *nothing* happens.  The general solution is to have an independent process monitoring your backups (pgmonitor, etc.)

Also, the info command will tell you when the last backup ran so you can generate an alert based on that.  Some examples for using the info command are here: https://pgbackrest.org/user-guide.html#monitor.

**Comment by mahomedh** [comment]
Thanks @dwsteele I totally understand the point about not getting a notification when the backup fails to run at all. But we would combine this with manual checking too.

pgmonitor looks great. But it would be yet another system to learn, setup and maintain. Not to mention it only officially supports CentOS/RHEL and we run Ubuntu and Windows. I've seen that the individual components of pgmonitor will run on Ubuntu but seems like I'd be having to work some bits out for myself.

> the info command will tell you when the last backup ran so you can generate an alert based on that

This is a great way of checking whether "_nothing_ happens" as you put it. But it doesn't give you any notification if there are any warnings or errors for a specific run. For example below I've shutdown the standby and attempted a backup. It correctly generates the WARN and ERROR events but the info command will only show you successful backups.

```
root@torrington:~# sudo -u pgbackrest pgbackrest --stanza=CustA-Cluster --log-level-console=info backup            
2019-06-19 08:54:30.138 P00   INFO: backup command begin 2.14: --backup-standby --log-level-console=info --log-level-file=detail --pg1-host=postg1.servers --pg2-host=db2.local --pg1-path=/var/lib/postgresql/11/main --pg2-path=/var/lib/postgresql/11/main --process-max=4 --repo1-cipher-type=none --repo1-path=/CustA --repo1-retention-diff=2 --repo1-retention-full=2 --repo1-s3-bucket=pg-backups --repo1-s3-endpoint=mydomain.co.uk --repo1-s3-host=pg-backups.mydomain.co.uk --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --no-repo1-s3-verify-ssl --repo1-type=s3 --stanza=CustA-Cluster --start-fast --stop-auto
WARN [042]: : remote process on 'db2.local' terminated unexpectedly: ssh: connect to host db2.local port 22: No route to host
ERROR [049]: : unable to find standby database - cannot proceed
2019-06-19 08:54:51.563 P00   INFO: backup command end: aborted with exception [049]
```

```
root@torrington:~# sudo -u pgbackrest pgbackrest --stanza=CustA-Cluster --log-level-console=info info                                                                                                                                       
stanza: CustA-Cluster
    status: ok
    cipher: none

    db (current)
        wal archive min/max (11-1): 0000001F0000000400000076/00000020000000040000006F

        full backup: 20190617-152545F
            timestamp start/stop: 2019-06-17 15:25:45 / 2019-06-17 15:34:53
            wal start/stop: 0000001F0000000400000076 / 0000001F0000000400000076
            database size: 9.5GB, backup size: 9.5GB
            repository size: 4.3GB, repository backup size: 4.3GB

        full backup: 20190619-084304F
            timestamp start/stop: 2019-06-19 08:43:04 / 2019-06-19 08:52:01
            wal start/stop: 0000001F0000000400000078 / 0000001F0000000400000078
            database size: 9.5GB, backup size: 9.5GB
            repository size: 4.3GB, repository backup size: 4.3GB
```

Ideally it would be handy to get a "backup/command status" output from pgbackrest when it is run from a script. Another possible case for this is when you want to automate a full backup when primary/standby switchover occurs and you want to report the outcome of that backup (this is just an off-the-cuff example)

For now, I'm going to use the `--log-level-console=warn` parameter and check the output from it. `No Output == Success` and `Any Output == Fail` and I'll send that output text to slack. If you (or anyone else) have a better/simpler suggestion then I'd be most grateful if you could share. I'm probably over-complicating things, but this seems the best flow for our case. Thanks again.

**Comment by dwsteele** [comment]
> For now, I'm going to use the --log-level-console=warn parameter and check the output from it. No Output == Success and Any Output == Fail and I'll send that output text to slack. If you (or anyone else) have a better/simpler suggestion then I'd be most grateful if you could share.

This seems reasonable for your use case.

There are a number of improvements we want to make in this area, including pre/post hooks and better `info` reporting for failed backups.  But all that has to wait until we complete the C migration.

**Comment by mahomedh** [comment]
This is my humble attempt at a script that will call the pgBackRest backup command, read the console output and then send the result to slack. The file logs still have the full output for troubleshooting etc.

I'm sure there's a lot of things that could be done better in the script, so I welcome any feedback, otherwise, I think this issue can be closed.

Simply save it as `pgBackRestToSlack.sh` to a directory where your pgBackRest user can access it, give it execute permission and change ownership to your pgBackRest user.

I hope this helps someone :)

```bash
#!/bin/bash

# Script runs the pgBackRest backup, reads back the status messages and posts the final results
# to slack.

# USAGE: pgBackRestToSlack.sh --stanza StanzaName --backupType full

function notify_slack
{
  # Update the Slack Channel and URL below to match your settings
  local slack_channel="#general"
  local slack_url="https://hooks.slack.com/services/Change-This-To-Your-URL"

  local alert_type="${1^^}"
  local escaped_message=$(printf "%s" "${2}" | sed 's/"/\\"/g' | sed "s/'/\\'/g" )
  local slack_color="#336699"

  case "$alert_type" in
    "ERROR")
      slack_color="#ff3300"
    ;;
    "WARNING")
      slack_color="#ff8000"
    ;;
    "SUCCESS")
      slack_color="#00b300"
    ;;
    "INFO")
      slack_color="#0080ff"
    ;;
    *)
      slack_color="#336699"
    ;;
  esac

  IFS='' read -r -d '' content <<-EOF
    "attachments": [
      {
        "mrkdwn_in": ["text", "fallback"],
        "fallback": "Backup for stanza: [${stanza}]: ${escaped_message}",
        "title": "Backup for stanza: [${stanza}]",
        "text": "${escaped_message}",
        "color": "$slack_color",
        "footer": "Source Time",
        "ts": "$(date +"%s")"
      }
    ]
EOF

  IFS='' read -r -d '' json_load <<-EOF
    {"channel": "$slack_channel",
      "mrkdwn": true,
      "username": "pgBackRest",
      ${content},
      "icon_emoji": ":pgbackrest:"
    }
EOF

  curl -s -d "payload=$json_load" $slack_url > /dev/null

}

# Stanza as defined in the pgbackrest.conf. Must be specified when script is called
stanza=""
# Backup type can be 'diff', 'incr' or 'full'. Default to 'incr'
backupType="incr"

while [ "$1" != "" ]; do
  case "$1" in
    --stanza)
      shift
      stanza="$1"
    ;;
    --backuptype)
      shift
      backupType="${1,,}"
    ;;
  esac
  shift
done

if [ -z "$stanza" ]; then
  notify_slack "ERROR" "Backup script called without ``stanza`` specified on the command line"
  exit 1
fi

if [ "$backupType" != "full" ] && [ "$backupType" != "incr" ] && [ "$backupType" != "diff" ]; then
  notify_slack "ERROR" "Incorrect ``backupType`` specified on the command line"
  exit 1
fi


# echo "Starting"

stdbuf -oL pgbackrest --stanza=$stanza --log-level-console=info --type=${backupType} backup 2>&1 | {

    while IFS= read -r line
    do
        if [[ "$line" == *"backup command end"* ]]; then
          backupEndStatus=$(printf "$line" | awk -F "end: " '{print $2} ')
        elif [[ "$line" == *"new backup label"* ]]; then
          backupLabel=$(printf "$line" | awk -F "label = " '{print $2} ')
        elif [[ "$line" == *"backup size"* ]]; then
          backupSize=$(printf "$line" | awk -F "INFO: " '{print $2} ')
        elif [[ "$line" == *"WARN"* ]]; then
          warningMessages+="$line"
        elif [[ "$line" == *"ERROR"* ]]; then
          errorMessages+="$line"
        fi
    done

  if [[ "$backupEndStatus" == *"success"* ]]; then
    # echo "Backup Label: ${backupLabel}"
    # echo "$backupSize"
    # echo "Backup ${backupEndStatus}"
    notify_slack "SUCCESS" "Backup ${backupEndStatus} \n \n *Backup Label:* ${backupLabel} \n ${backupSize}"
  else

    if [ -n "$warningMessages" ]; then
      printf "WARNINGS:\n%s\n" "$warningMessages"
      alertType="WARNING"
      notificationMsg="\n *Warnings* \n\n ${warningMessages} \n"
    fi
    if [ -n "$errorMessages" ]; then
      printf "ERRORS:\n%s\n" "$errorMessages"
      alertType="ERROR"
      notificationMsg+="\n *Errors* \n\n ${errorMessages} \n"
    fi

    printf "Backup %s\n" "$backupEndStatus"

    notify_slack "$alertType" "Backup ${backupEndStatus} \n ${notificationMsg}"
    
  fi

  # echo "Finished"
}

```

**Comment by dwsteele** [comment]
This looks reasonable, but I will warn you that we make no guarantees that log messages won't change.  The <command> begin/end messages are pretty safe, but we do adjust other messages as needed.

**Comment by mahomedh** [comment]
> I will warn you that we make no guarantees that log messages won't change

Thanks. I saw this warning in other issues. That's why I am just capturing based on the `WARN` and `ERROR` tag. But hopefully this is just to tide me over until (hopefully) we get the pre/post hooks. In the mean time I'll keep an eye on the release notes.
