### ISSUE TITLE
--archive-copy parameter passing in command line is failing

### ISSUE THREAD

**Issue by sujiplr** [pgbackrest/pgbackrest#749]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
    2.14
2. PostgreSQL version:
    11.2
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
  RHEL 7
4. Did you install pgBackRest from source or from a package?
  Yes
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Not able to pass --archive-copy=y parameter as inline argument. Getting below error, If I configure this in the configuration file, able to get the required output.

pgbackrest --stanza=n01rdb003_53000 --log-level-console=info --pg1-path=/pg_data/PostgreSQL/11/data --repo1-path=/app/pgbackrest/db_backup_monthly  --pg1-port=5432 --type=full --archive-copy=y backup
ERROR: [031]: invalid option '--archive-copy=y'

**Comment by dwsteele** [comment]
On the command line it is just `--archive-copy`. See https://pgbackrest.org/command.html#command-backup
