### ISSUE TITLE
ERROR: [044]: unable to retrieve the archive id for database version '11' and system-id '6697210049222451933'

### ISSUE THREAD

**Issue by oebeledrijfhout** [pgbackrest/pgbackrest#751]
pgBackRest version: 2.14-1.rhel7.x86_64 (RPM package)
 PostgreSQL version: 11.3
 Operating system/version: Centos 7

`pgbackrest.conf` file(s)

```
[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=1
process-max=4
log-level-console=info
log-level-file=detail
archive-async=y
#archive-push-queue-max=8GB
spool-path=/var/spool/pgbackrest
compress=n
backup-standby=y
delta=y

[pgdb2]
pg1-host=10.100.130.20
pg1-path=/var/lib/pgsql/11/data
pg2-path=/var/lib/pgsql/11/data
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=10.100.130.20 port=5432 user=replication
recovery-option=recovery_target_timeline=latest

```

`postgresql.conf` settings applicable to pgBackRest

```
archive_mode = on
archive_command = 'pgbackrest --stanza=pgdb2 archive-push %p'
listen_addresses = '*'
max_wal_senders = 10
wal_level = replica
port = 5432
```

errors in the postgresql log file before or during the time you experienced the issue: none

log file in `/var/log/pgbackrest` for the commands run: none

Contents of backup.info of the stanza (pgdb2)

```
[backrest]
backrest-checksum="0d0b833ce6714d5cb44acba905f780016a0063f6"
backrest-format=5
backrest-version="2.14"

[backup:current]
20190618-110131F={"backrest-format":5,"backrest-version":"2.14","backup-archive-start":"0000000300000282000000E0","backup-archive-stop":"000000030000028C000000EC","backup-info-repo-size":822794940794,"backup-info-repo-size-delta":822794940794,"backup-info-size":822794940794,"backup-info-size-delta":822794940794,"backup-timestamp-start":1560848491,"backup-timestamp-stop":1560861128,"backup-type":"full","db-id":4,"option-archive-check":true,"option-archive-copy":false,"option-backup-standby":true,"option-checksum-page":false,"option-compress":false,"option-hardlink":false,"option-online":true}

[db]
db-catalog-version=201809051
db-control-version=1100
db-id=4
db-system-id=6701198204233739981
db-version="11"

[db:history]
1={"db-catalog-version":201809051,"db-control-version":1100,"db-system-id":6697210049222451933,"db-version":"11"}
2={"db-catalog-version":201809051,"db-control-version":1100,"db-system-id":6700805644126865727,"db-version":"11"}
3={"db-catalog-version":201809051,"db-control-version":1100,"db-system-id":6700887895566588212,"db-version":"11"}
4={"db-catalog-version":201809051,"db-control-version":1100,"db-system-id":6701198204233739981,"db-version":"11"}
```

Contents of archive.info of the stanza (pgdb2)

```
[backrest]
backrest-checksum="18542aa1a64b7099a5a1926c77aad68c29eb3e6e"
backrest-format=5
backrest-version="2.14"

[db]
db-id=1
db-system-id=6701198204233739981
db-version="11"

[db:history]
1={"db-id":6701198204233739981,"db-version":"11"}

```
7. Describe the issue:
**bash-4.2$ pgbackrest info
ERROR: [044]: unable to retrieve the archive id for database version '11' and system-id '6697210049222451933'**

Why doesn't this work? Looking at the postgresql log, archiving works and backup commands also finish successfully.

**Comment by cmwshang** [comment]
The archive.info file and backup.info file should have the same history. Did something happen to your archive directory or archive.info file? Did either file or directory go missing and you were forced to do a stanza-create --force or a manual remedy (copy an old file/dir from somewhere)?

**Comment by oebeledrijfhout** [comment]
That's correct, while creating this setup I deleted the archive directory a few times and at one point I did have to do a stanza-create --force. I didn't move any files around manually in there though.

**Comment by oebeledrijfhout** [comment]
I understand this is most likely user error and not a bug, but if you would have any pointers on how I can fix this, it would be hugely appreciated!

**Comment by dwsteele** [comment]
Since there is only one backup I think doing `stanza-delete` and then `stanza-create` is the best thing to do.  Then take a new backup.

**Comment by oebeledrijfhout** [comment]
Checking pgbackrest help stanza-delete:

To delete a stanza:

* Shut down the PostgreSQL cluster associated with the stanza (or use --force
to override).
* Run the stop command on the repository host.
* Run the stanza-delete command on the repository host.

I would like to avoid shutting down the whole cluster. Is it safe to use --force?

**Comment by dwsteele** [comment]
`--force` is safe to use this this case since you are wiping the repo.  These safeguards are in place to keep accidents from happening.

**Comment by oebeledrijfhout** [comment]
thanks, everything is working as expected now :)

**Comment by dwsteele** [comment]
Glad to hear it!
