### ISSUE TITLE
wrong error message when arguments are incorrect

### ISSUE THREAD

**Issue by davecramer** [pgbackrest/pgbackrest#755]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgBackRest 2.12
2. PostgreSQL version:
11
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
ubuntu

4. Did you install pgBackRest from source or from a package?
package

7. Describe the issue:

pgbackrest --stanza=demo -delta --type=name "--target=before_drop" --target-action=promote --target-timeline=2 restore
ERROR: [031]: invalid option '--stanza=demo'

Actual error is -delta

**Comment by dwsteele** [comment]
@sharmay reported this a while back but it appears to be a bug in `getopt_long()` and I wasn't able to find a workaround.  At some point I'm planning to write our own command line parser but until then I'm not sure what to do.

**Comment by davecramer** [comment]
possibly just leave this open so people are aware.

**Comment by dwsteele** [comment]
PR #1396 fixes this issue, so closing.
