### ISSUE TITLE
How often is the archive backed up? question

### ISSUE THREAD

**Issue by cheucheu** [pgbackrest/pgbackrest#757]
Hi David,

I would like to know how pgbackrest decides to copy the archives to the backup directory and which frequency.

Thanks a lot of

BR

**Comment by mahomedh** [comment]
I believe this is determined by your WAL segment size and by postgresql, not by pgBackRest. When postgresql determines it has a WAL to archive, it calls the archive command that you'd have configured in your `postgresql.conf`, which happens to be a call to pgBackRest. This link might help - https://www.postgresql.org/docs/11/continuous-archiving.html

**Comment by dwsteele** [comment]
PostgreSQL decides when WAL segments are archived and calls pgbackrest to do the archiving.  See https://www.postgresql.org/docs/11/continuous-archiving.html.

**Comment by cheucheu** [comment]
Thanks a lot for your answers ! 
BR
