### ISSUE TITLE
archive_command ... must contain 'pgbackrest': really?

### ISSUE THREAD

**Issue by Xof** [pgbackrest/pgbackrest#759]
Is it possible to have an option to suppress this error? While, in general, you want to check for `pgbackrest` in the archive_command, there are time one wants to have a script that calls pgbackrest instead.

**Comment by dwsteele** [comment]
You can set `archive-check=n` but that disables all checking (including if the WAL is complete at end of backup) not just the name.

You just need `pgbackrest` in the archive_command somewhere, lots of ways to do that.  We're not against an option but since this is the first time the issue has come up it doesn't seem especially pressing.

Do be careful to return the correct result code from the script.  If errors get swallowed then WAL may be lost.

**Comment by Xof** [comment]
Fair enough! I just renamed the script pgbackrest.sh.

**Comment by dwsteele** [comment]
Yeah, that will do it!  Again, we're not against an option, though we would prefer the option be an expression that says what to look for rather than just disable.  It's amazing how easy it is to lose the archive_command on upgrade, fail over, etc.

**Comment by sfrost** [comment]
Christoph, can you share with us exactly what your script is like and why you feel the need to have one at all..?

If there's a real use-case here that we aren't already planning to support then we'd really like to know about it and have an opportunity to at least think about how we might support it more cleanly.  Particularly if we manage to get our way and have pgbackrest, in the future, be a library that's linked into the archiver itself, removing the archive_command...

**Comment by Xof** [comment]
The installation is transitioning from a dedicated backup server to an S3 repo, but temporarily, they need to be able to do backups to both. We've implemented this as two different stanzas, which means the WAL segments need to be archived twice.

**Comment by sfrost** [comment]
Ah, ok, our recommendation is typically to do:

pgbackrest --stanza=s1 archive-push %f && pgbackrest --stanza=s2 archive-push %f

(or something along those lines- this is just top-of-mind)

That removes the risk that the shell script ends up swallowing up error results from either, and it's perfectly fine to call pgbackrest again on a given WAL file even if it was already successfully archived (PG does this in some cases too).

We do have plans to implement better support for this in the future though.

**Comment by dwsteele** [comment]
Or you can use the same stanza name and set `--config=` for each command to archive to different repo types.  I've been using that configuration on my personal clusters for years and it works.  I keep a week of backups locally for quick/cheap access and three months of backups on S3.

**Comment by dwsteele** [comment]
One caveat, you'll need to set a unique `--spool-path` for each archiver if they are both archiving async, or have one sync and one async, or both sync.  As Stephen said, we plan to make this easier in the future.
