### ISSUE TITLE
Upgrade pgbackrest from 2.13 to 2.15 (problem version)

### ISSUE THREAD

**Issue by rpclaude** [pgbackrest/pgbackrest#761]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 
2.13 to 2.15

2. PostgreSQL version: 
9.6.12

3. Operating system/version
CentOS Linux release 7.6.1810 (Core)

4. Did you install pgBackRest from source or from a package?
From package 
https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7.6-x86_64/pgbackrest-2.15-1.rhel7.x86_64.rpm

5. Please attach the following as applicable:
skip 

----------------------
----------------------

6. Describe the issue:
I don't know if I'm in the right place or if I should post to the postgresql repository team but I don't know how to contact them. 

I just try to upgrade from pgbackrest 2.13 to 2.15 by installing the new package.
https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7.6-x86_64/pgbackrest-2.15-1.rhel7.x86_64.rpm

After the installation pgbackrest version return "pgBackRest 2.16dev".

I rollback because it's not acceptable for me to install a version I'm not sure it's the stable version. 

Can you tell me who to contact to fixe this issue ? 

Below the command after the upgrade : 
[pgbackrest@my_server pgbackrest]$ yum info pgbackrest
Modules complémentaires chargés : fastestmirror
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Loading mirror speeds from cached hostfile
Paquets installés
Nom                 : pgbackrest
Architecture        : x86_64
Version             : 2.15
Révision            : 1.rhel7
Taille              : 1.0 M
Dépôt               : installed
Résumé              : Reliable PostgreSQL Backup & Restore
URL                 : http://www.pgbackrest.org/
Licence             : MIT
Description         : pgBackRest aims to be a simple, reliable backup and restore system that can
                    : seamlessly scale up to the largest databases and workloads.
                    :
                    : Instead of relying on traditional backup tools like tar and rsync, pgBackRest
                    : implements all backup features internally and uses a custom protocol for
                    : communicating with remote systems. Removing reliance on tar and rsync allows
                    : for better solutions to database-specific backup challenges. The custom remote
                    : protocol allows for more flexibility and limits the types of connections that
                    : are required to perform a backup which increases security.

[pgbackrest@my_server pgbackrest]$ which pgbackrest
/bin/pgbackrest
[pgbackrest@my_server pgbackrest]$ /bin/pgbackrest version
**pgBackRest 2.16dev**
[pgbackrest@my_server pgbackrest]$ date
jeu jun 27 08:36:15 CEST 2019

Thank you for your help. 

Please redirect me to the correct person if this is the wrong place.

**Comment by mhagander** [comment]
This happens also when downloading the release tarball at https://github.com/pgbackrest/pgbackrest/archive/release/2.15.tar.gz -- the code is full of references to 2.16dev.

**Comment by dwsteele** [comment]
Thank you for bringing this to our attention.  I managed to put the tag on the commit following the release, so the code is identical but the version had been updated for 2.16 development.

I have asked Devrim to rebuild the package.

**Comment by mhagander** [comment]
Did you just put out a second tarball with exactly the same version as before? That seems... bad and unprecictable? :) Please consider at least naming it 2.15.1!

**Comment by devrimgunduz** [comment]
Hi @dwsteele  ,

Now there are two 2.15 tarballs around. Can you please release 2.15.1 or whatever?

Thanks, Devrim

**Comment by dwsteele** [comment]
Hmmm -- not sure we can do that without breaking more stuff.  Might have to go to 2.16.

**Comment by dwsteele** [comment]
OK, for the moment I have removed the 2.15 tag.  @devrimgunduz , can you remove the erroneous packages until we can get this resolved?

**Comment by rpclaude** [comment]
Thank you for the quick responses. 

I also rather have a new version and be sure there is no mixe code. I will wait for the next stable release.

It's a great software thank you for your work, we appreciate.

**Comment by dwsteele** [comment]
@rpclaude Thanks, and sorry for the confusion.

**Comment by mhagander** [comment]
Then I do agree that rolling a 2.16 will be better. Having two potentially different tarballs with the same version number in circulation can cause a lot of confusion down the road I think.

**Comment by devrimgunduz** [comment]
There are users out there who already have 2.15 installed, and they are using a broken version. Removing RPMS only will help users who did not update yet.

We need either 2.15.1 or 2.16 ASAP.

Regards, DEvrim

**Comment by devrimgunduz** [comment]
That said, just removed 2.15 RPMs.

**Comment by dwsteele** [comment]
@devrimgunduz What's the specific issue here?  Can't you just rebuild and change the version of the RPM to 2.15-2.

**Comment by devrimgunduz** [comment]
@dwsteele as I and @mhagander wrote above, there are two 2.15 tarballs, which is not good.

**Comment by dwsteele** [comment]
OK, I looked at the Debian stuff and it seems like it should be OK with 2.15.1.  I tag that way unless there are objections.

**Comment by devrimgunduz** [comment]
No objections from here.

**Comment by dwsteele** [comment]
@devrimgunduz has built the new package and I have checked it, so we should be good to go now.
