### ISSUE TITLE
Improvement throttle Bandwith

### ISSUE THREAD

**Issue by jacks33** [pgbackrest/pgbackrest#763]
Hello,

Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.14
2. PostgreSQL version:
9.5 / 11
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 7 dedicated repository host, several pg hosts.

4. Did you install pgBackRest from source or from a package?
Package from Community

5. Please attach the following as applicable:

7. Describe the issue:
Currently we are facing network issues (bandwith is full).
We use file compression option in pgbackrest, I did not found an options to throttle bandwith

Did I miss something  ?

Thank you
Tiago ANASTACIO

**Comment by dwsteele** [comment]
You didn't miss anything -- we don't currently support throttling.  You can adjust `process-max` and `compress-level` to achieve a similar result.
