### ISSUE TITLE
Is it possible to create stanza with client offline?

### ISSUE THREAD

**Issue by niksabaldun** [pgbackrest/pgbackrest#764]
Hello,

I am using a dedicated repository host with remote clients. I've tried issuing `stanza-create` command with `--no-online` option, however pgBackRest still tries to connect (I can see ssh authenticity warning). Is it possible to create the stanza without an active connection to the client? If not, what does the `--no-online` option do?

**Comment by cmwshang** [comment]
Yes it is possible. Please provide the error you are receiving along with the other information requested when posting an issue.

**Comment by niksabaldun** [comment]
I am not receiving an error, but when pgBackRest tries to connect to database host I am getting ssh authenticity warning because authentication keys are not created yet (and pgBackRest is not installed on database host yet). What I am asking is: is it possible to create a stanza on repository host without pgBackRest even trying to connect to database host. I need this because I am trying to fully automate configuration with a script, which needs to be run on repository host first, and the database host second.

1. pgBackRest version: 2.15.1

2. PostgreSQL version: 9.6

3. Operating system/version - Debian 9

4. Did you install pgBackRest from source or from a package? package

5. pgbackrest.conf on repository host:
[test]
pg1-host=10.66.66.230
pg1-path=/var/lib/postgresql/9.6/main
pg1-port=5432
repo1-path=/home/test/pgbackrest
repo1-retention-full=2
start-fast=y

**Comment by dwsteele** [comment]
The Postgres cluster can be down (--no-online) but the host must be up and contactable.  The stanza-create command needs the system-id and version for the cluster and it gets this information from `pg_control`.

**Comment by niksabaldun** [comment]
Thanks a lot for the explanation, David. I managed to work around this by invoking stanza-create remotely from the database host script, as the ssh connectivity is established at that time. Best regards.
