### ISSUE TITLE
upgrade from pgbackrest v2.14  to v2.15

### ISSUE THREAD

**Issue by hellower** [pgbackrest/pgbackrest#767]
CONTAINER$ /usr/bin/pgbackrest --stanza=tnt_processor check
ERROR [049]: : found name '2.14' in protocol greeting instead of expected '2.15'
(postgres@tnt-manager:/var/lib/pgsql/11)

CONTAINER$ /usr/bin/pgbackrest --stanza=tnt_processor stanza-upgrade
ERROR [049]: : found name '2.14' in protocol greeting instead of expected '2.15'
(postgres@tnt-manager:/var/lib/pgsql/11)
CONTAINER$ 

Should I RECREATE stanza?

**Comment by mahomedh** [comment]
You shouldn't need to recreate the stanza, you just need to make sure all your servers in the stanza are running `2.15` including the backup server if you are using one.

**Comment by dwsteele** [comment]
@mahomedh is correct.  Make sure all your servers are running the same version and you should be OK.

**Comment by hellower** [comment]
oops, my fault.
I also installed new pgbackrest in backup server.
It resolved.
Thanks.
