### ISSUE TITLE
Issues with 2.14 to 2.15 upgrade

### ISSUE THREAD

**Issue by mahomedh** [pgbackrest/pgbackrest#768]
Apologies in advance for the long post (and the flurry of issues logged)

1. pgBackRest version: 2.14 and 2.15

2. PostgreSQL version: PostgreSQL 11.3 and 11.4 - 64-bit

3. Operating system/version - Ubuntu 18.04.1 on all three servers

4. Install Source: package (apt from postgresql)

    - `pgbackrest.conf` on backup server
	
			```
			[CustA-Cluster]
			pg1-host=pg1.local
			pg1-path=/var/lib/postgresql/11/main
			pg2-host=pg2.local
			pg2-path=/var/lib/postgresql/11/main
			repo1-path=/CustA

			[global:backup]
			backup-standby=y

			[global]
			repo1-type=s3
			# for compatibility - see pgbackrest issue 645
			repo1-s3-host=pg-backups.mydomain.co.uk
			repo1-s3-endpoint=mydomain.co.uk
			repo1-s3-verify-ssl=n
			repo1-s3-bucket=pg-backups
			repo1-s3-key=xxxxxxxxxxxxxxxxxxx
			repo1-s3-key-secret=yyyyyyyyyyyyyyyyyyyyyyy
			repo1-s3-region=us-east-1
			repo1-retention-full=2
			repo1-retention-diff=2
			repo1-cipher-type=none
			repo1-host-user=postgres
			start-fast=y
			stop-auto=y
			process-max=4
			log-level-file=detail

			[global:archive-push]
			compress-level=3
			```
			
    - `pgbackrest.conf` on db servers
	
			```
			[CustA-Cluster]
			pg1-path=/var/lib/postgresql/11/main
			pg2-path=/var/lib/postgresql/11/main
			repo1-path=/CustA

			[global:backup]
			backup-standby=y

			[global]
			repo1-type=s3
			# for compatibility - see pgbackrest issue 645
			repo1-s3-host=pg-backups.mydomain.co.uk
			repo1-s3-endpoint=mydomain.co.uk
			repo1-s3-verify-ssl=n
			repo1-s3-bucket=pg-backups
			repo1-s3-key=xxxxxxxxxxxxxxxxxxx
			repo1-s3-key-secret=yyyyyyyyyyyyyyyyyyyyyyy
			repo1-s3-region=us-east-1
			repo1-retention-full=2
			repo1-retention-diff=2
			repo1-cipher-type=none
			repo1-host-user=postgres
			start-fast=y
			stop-auto=y
			process-max=4
			log-level-file=detail

			[global:archive-push]
			compress-level=3
			```

5. Describe the issue:

I intend to have one backup server (repo host) that would have multiple stanzas for different pairs of db servers (a primary and standby for each customer). I wanted to see if backups would continue if I upgrade the backup server to `2.15` and still have the db servers on `2.14` as I wouldn't be able to upgrade all the servers on the same night or even within a few nights. I expected this to work, where having the backup server ahead of the db servers would be "backwards compatibile". I had tested and found that upgrading the DB servers only (to 2.15) before upgrading the backup server did not work.

#### Problem 1: Use of `repo1-s3-verify-ssl=n` with `stanza-create` fails

I deleted the stanza before rolling back my DB server VM to `2.14`. This was to avoid the WAL file conflict with a WAL file already in the archive. Unfortunately the `stanza-create` fails as below.

```
$ pgbackrest --stanza=CustA-Cluster --log-level-console=detail --no-online stanza-create

2019-07-03 08:49:16.919 P00   INFO: stanza-create command begin 2.15: --log-level-console=detail --log-level-file=detail --no-online --pg1-host=pg1.local --pg2-host=pg2.local --pg1-path=/var/lib/postgresql/11/main --pg2-path=/var/lib/postgresql/11/main --repo1-cipher-type=none --repo1-path=/CustA --repo1-s3-bucket=pg-backups --repo1-s3-endpoint=mydomain.co.uk --repo1-s3-host=pg-backups.mydomain.co.uk --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --no-repo1-s3-verify-tls --repo1-type=s3 --stanza=CustA-Cluster
ERROR [031]: : remote process on 'pg1.local' terminated unexpectedly [031]: ERROR: [031]: invalid option '--no-repo1-s3-verify-tls'
2019-07-03 08:49:18.211 P00   INFO: stanza-create command end: aborted with exception [031]
```

So I removed `repo1-s3-verify-ssl=n` from the config on the backup server and I got past the above error (I have a proper SSL Cert on the server anyway - or so I thought. See later). But this gets me to the next problem.

#### Problem 2: Cannot create stanza due to protocol version mismatch

I tried again and included the `--force` option to see if I could coax it to create the stanza but that still failed as below.

```
$ pgbackrest --stanza=CustA-Cluster --log-level-console=detail --no-online --force stanza-create

2019-07-03 09:16:30.359 P00   INFO: stanza-create command begin 2.15: --force --log-level-console=detail --log-level-file=detail --no-online --pg1-host=pg1.local --pg2-host=pg2.local --pg1-path=/var/lib/postgresql/11/main --pg2-path=/var/lib/postgresql/11/main --repo1-cipher-type=none --repo1-path=/CustA --repo1-s3-bucket=pg-backups --repo1-s3-endpoint=mydomain.co.uk --repo1-s3-host=pg-backups.mydomain.co.uk --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --repo1-type=s3 --stanza=CustA-Cluster
ERROR [049]: : found name '2.14' in protocol greeting instead of expected '2.15'
2019-07-03 09:16:32.357 P00   INFO: stanza-create command end: aborted with exception [049]
```

#### Problem 3: Create stanza fails on primary due to "more than one master database found"

So I then decided to just create the stanza on the primary server to see if that works around the issue (after all in a live scenario, I'm unlikely to delete and recreate the stanza anyway). But this failed as below until I used the `--no-online` option. This could be expected behaviour, I'm just curious about what it means by "more than one master database found"

```
$ pgbackrest --stanza=CustA-Cluster --log-level-console=detail stanza-create

2019-07-03 10:52:58.249 P00   INFO: stanza-create command begin 2.14: --log-level-console=detail --log-level-file=detail --pg1-path=/var/lib/postgresql/11/main --pg2-path=/var/lib/postgresql/11/main --repo1-cipher-type=none --repo1-path=/CustA --repo1-s3-bucket=pg-backups --repo1-s3-endpoint=mydomain.co.uk --repo1-s3-host=pg-backups.mydomain.co.uk --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --no-repo1-s3-verify-ssl --repo1-type=s3 --stanza=CustA-Cluster
ERROR [125]: : more than one master database found
2019-07-03 10:52:58.923 P00   INFO: stanza-create command end: aborted with exception [125]
```

#### Problem 4: Can't complete the backup now due to SSL verification failure

As a side effect of taking off `repo1-s3-verify-ssl=n` from my config, I've now learnt that although my browser can verify the Let's Encrypt certificate correctly, pgBackRest does not like it. Even when I download the cafile and specify `--repo1-s3-ca-file=~/.minio/certs/letsencryptauthorityx3.pem` on the command line, I still get `ERROR [049]: : SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`

So my next task is get MinIO serving the SSL certificate in a way that pgBackRest can then verify it.

Technically at this point I could just make sure I roll out `2.15` everywhere and then deal with this upgrade issue "next time" but some feedback about whether I am doing something wrong would be helpful.

**Comment by dwsteele** [comment]
> Problem 1: Use of repo1-s3-verify-ssl=n with stanza-create fails

`repo1-s3-verify-ssl` is now deprecated and replaced by `repo1-s3-verify-tls` but the older remote does not understand that, so it errors.

> Problem 2: Cannot create stanza due to protocol version mismatch

The versions must match.  We'd like to remove this requirement some day but during the C migration the protocol is changing with every version.

> Problem 3: Create stanza fails on primary due to "more than one master database found"

You have two clusters configured here and both of them are primaries.  This looks like a split-brain situation to pgBackRest and it refuses to continue.

> Problem 4: Can't complete the backup now due to SSL verification failure

Looks like something is wrong with your cert, according to openssl at least.  You shouldn't need to add the Let's Encrypt CA (I've never had to) so it's something else, more than likely.

**Comment by mahomedh** [comment]
Thanks. I suppose Problems 1 & 2 become a "non-issue" when I/the user accept that there's no backward compatibility at the application level. The intro on the releases page gave me the impression that there should be backward compatibility at the application level for minor versions. On reading it further though, I can see it is carefully worded to allow the introduction of such breaking features :) Not an issue per se, but maybe it could be made clearer (at least until the full migration to C is complete). 

> You have two clusters configured here and both of them are primaries. 

Thanks. I removed `pg2-path` below and that worked now.

```
  [CustA-Cluster]
  pg1-path=/var/lib/postgresql/11/main
  pg2-path=/var/lib/postgresql/11/main
```

A related follow-on question: What is the relationship between the `/etc/pgbackrest.conf` on the DB servers and the backup server? I mean if the backup is being initialised from the backup server, I assume it only uses the options from `pgbackrest.conf` from the backup server and ignores any settings in the config on the database servers. Is this correct?

Regarding Problem 4, this was indeed a misconfiguration issue on MinIO. The solution was to make sure that the `public.crt` was the Full Chain certificate and this resolved it.

**Comment by dwsteele** [comment]
> I assume it only uses the options from pgbackrest.conf from the backup server and ignores any settings in the config on the database servers. Is this correct?

pgBackRest uses the most local settings it can.  So it will use settings on the pg server first, then the repo server when doing a restore.

**Comment by sfrost** [comment]
Looks like everything on this was answered/addressed, so I'm closing it.  Thanks!
