### ISSUE TITLE
S3 Error: The difference between the request time and the current time is too large.

### ISSUE THREAD

**Issue by Underhunden** [pgbackrest/pgbackrest#769]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
pgbackrest-2.15.1-1.rhel7.x86_64

2. PostgreSQL version:
11.4

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS Linux release 7.6.1810 (Core) on all nodes.

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[backup]
pg1-path=/var/lib/pgsql/11/data

[global]
backup-standby=n
archive-async=y
archive-copy=n
spool-path=********
start-fast=y
stop-auto=y
process-max=16
repo1-cipher-type=none
repo1-path=*********
repo1-retention-diff=2
repo1-retention-full=2
repo1-s3-bucket=*******
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-region=*********
repo1-s3-ca-file=/etc/pki/tls/certs/ca-bundle.crt
repo1-type=s3

[global:archive-push]
compress-level=3

pgbackrest log for backup:
2019-07-04 12:20:01.361 P00  ERROR: [039]: raised from local-3 process: S3 request error [403] Forbidden
                                        *** request header ***
                                        PUT **********20190704-114955F/pg_data/base/16401/6963808.3.gz?partNumber=3&uploadId=*******
 HTTP/1.1
                                        authorization: <redacted>
                                        content-length: 18439888
                                        content-md5: EKLj+NPNYh0aN1QXYthfCg==
                                        host: ***********
                                        x-amz-content-sha256: 47119956809ea209f5d33b3656d8e482cb143541854eccc5ac7f0fa3d431b941
                                        x-amz-date: 20190704T100428Z
                                        *** canonical request ***
                                        PUT
                                        ***********/pg_data/base/16401/6963808.3.gz
                                        partNumber=3&uploadId=***********
                                        content-length:18439888
                                        content-md5:EKLj+NPNYh0aN1QXYthfCg==
                                        host:**************************
                                        x-amz-content-sha256:47119956809ea209f5d33b3656d8e482cb143541854eccc5ac7f0fa3d431b941
                                        x-amz-date:20190704T100428Z

                                        content-length;content-md5;host;x-amz-content-sha256;x-amz-date
                                        47119956809ea209f5d33b3656d8e482cb143541854eccc5ac7f0fa3d431b941
                                        *** signed headers ***
                                        content-length;content-md5;host;x-amz-content-sha256;x-amz-date
                                        *** string to sign ***
                                        AWS4-HMAC-SHA256
                                        20190704T100428Z
                                        20190704/********/s3/aws4_request
                                        d6ad8a9fb43248141bcfa193a9f7e24212cbf11aef64bc33285a6ab93bb5ba1a
                                        *** response header ***
                                        x-amz-request-id: 3137D5350F2C765C
                                        x-amz-id-2: Ppa2p8JylLHsFplIMN2rWYUTkf/YqO8qTq35lcUG8kXlgGVz8Z3TT9ONXh2S+vRDGxmxzm/SyB4=
                                        Content-Type: application/xml
                                        Transfer-Encoding: chunked
                                        Date: Thu, 04 Jul 2019 10:20:00 GMT
                                        Connection: close
                                        Server: AmazonS3
                                        *** response body ***
                                        <?xml version="1.0" encoding="UTF-8"?>
                                        <Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>20190704T100428Z</RequestTime><ServerTime>2019-07-04T10:20:01Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>3137D5350F2C765C</RequestId><HostId>Ppa2p8JylLHsFplIMN2rWYUTkf/YqO8qTq35lcUG8kXlgGVz8Z3TT9ONXh2S+vRDGxmxzm/SyB4=</HostId></Error>

7. Describe the issue:
This has been working for a long time. Since this weekend it doesn't and all backups end with this error about 15-20 mins after start. The server is synced properly with ntp (several google posts suggest this). I've tried both pgbackrest 2.14 and 2.15. 

Not sure if AWS changed anything and I haven't checked the code thoroughly but a hint could be that the "x-amz-date"-part of the request-header isn't updated with every push. Or it's cached.

**Comment by Underhunden** [comment]
Turns out this is working perfectly on another host. There is most likely some other issue with this particular server.

**Comment by dwsteele** [comment]
This looks like the same issue as #707.  You might find some clues there.
