### ISSUE TITLE
Postgresql.conf file -> include files/directory not considering in backup

### ISSUE THREAD

**Issue by sujiplr** [pgbackrest/pgbackrest#770]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
      2.14

2. PostgreSQL version:
    11.2
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
   RHEL 7
4. Did you install pgBackRest from source or from a package?
    Source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
     We have the option in postgresql file to include an external file or directory. But when pgbackrest is taking backup its not considering the files mentioned in the include option of postgresql.conf.
Do we need to make any changes in the pgbackrest configuration file for this or we don't have any provision currently available for this. Can you please help on this.

**Comment by mahomedh** [comment]
This might help - https://github.com/pgbackrest/pgbackrest/issues/567#issuecomment-411507982

**Comment by sujiplr** [comment]
@mahomedh , thanks for sharing this . I have already went through this. In our case, all my database instances configuration files are mapped through the include option , which is provided by postgresql. Can we have the same and take the backup using pgbackrest. Or can we have this as a feature enhancement in the pgbackrest too. Appreciate your response.

**Comment by dwsteele** [comment]
This is not something we are planning to support.  We recommend using the technique in #567, backing up the files with traditional backup software, or recreating them with CM tools.
