### ISSUE TITLE
info "verbose" maybe?

### ISSUE THREAD

**Issue by sfrost** [pgbackrest/pgbackrest#774]
Feature request.

It'd be really nice to be able to see information like tablespaces, symlinks, and other things using the info command, which could facilitate setting up to perform a restore.  This might be best done by passing in a "verbose" option, or similar, to the info command.

**Comment by dwsteele** [comment]
Also include db information per issue #818.

**Comment by dwsteele** [comment]
Committed at f96c54c4ba0e5 in #843.
