### ISSUE TITLE
Exit Code 57 randomly returns exit code 0

### ISSUE THREAD

**Issue by dpitera** [pgbackrest/pgbackrest#775]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

pgBackRest 2.10

2. PostgreSQL version:

10.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.7 (stretch)
Release:	9.7
Codename:	stretch

4. Did you install pgBackRest from source or from a package?

Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

`pgbackrest.conf`:

```
[global]
log-level-console=warn
log-level-file=off
log-level-stderr=warn
repo-s3-bucket=postgresql-2
repo-s3-endpoint=<REDACTED>
repo-s3-key=<REDACTED>
repo-s3-key-secret=<REDACTED>
repo-s3-region=us-standard
repo-type=s3
retention-full=2000
retention-diff=2000
start-fast=y
backup-standby=n
repo-path=/postgresql_backup_postgresql-2
recovery-option=standby_mode=on
archive-async=y
spool-path=/data/postgresql/spool
process-max=2
compress-level=1
[formation]
db-path=/data/postgresql/10
db-port=5432
[global:archive-get]
process-max=2
[global:archive-push]
```

7. Describe the issue:

Here is the relevant python code that calls the pgbackrest process and checks for exceptions (non-0 exit codes):

```
        cmd = 'runuser -l ibm -c "%s --type %s backup"' % (
            self.pgbackrest_command, backup_type)
        try:
            subprocess.check_call(
                shlex.split(cmd),
                stdout=sys.stdout,
                stderr=sys.stderr,
                shell=False)
            print("completed")
        except subprocess.CalledProcessError as ex:
            if ex.returncode == self.HostConnectError:
                # Try again, usually a transient connection error
                print("Transient error; trying again in 60s")
                time.sleep(60)
                subprocess.check_call(
                    shlex.split(cmd),
                    stdout=sys.stdout,
                    stderr=sys.stderr,
                    shell=False)
            else:
                print("Encountered error: " + str(ex))
                raise ex
        except Exception as ex:
            print("Encountered error: " + str(ex))
            raise ex
```

Sometimes, it is the case that pgbackrest logs exit code 57 and properly returns that exit code to the caller (we see below that the python caller caught the exception (printed `Encountered error...`)):

```
ERROR [057]: : server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.:
select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_walfile_name(lsn), lsn::text, labelfile, case when length(trim(both '\t\n ' from spcmapfile)) = 0 then null else spcmapfile end as spcmapfile from pg_stop_backup(false, false) as lsn
Encountered error: Command '['runuser', '-l', 'ibm', '-c', '/usr/bin/pgbackrest --stanza=formation  --config=/conf/postgresql//pgbackrest.conf  --type diff backup']' returned non-zero exit status 57
```

while other times, it is the case that pgbackrest logs exit code 57 but seemingly returns exit code 0 to the caller (we see below that the python caller did not catch any exception (printed `completed`)):

```
ERROR [057]: : server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.:
select to_char(clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_walfile_name(lsn), lsn::text, labelfile, case when length(trim(both '\t\n ' from spcmapfile)) = 0 then null else spcmapfile end as spcmapfile from pg_stop_backup(false, false) as lsn
completed
```

**Comment by sfrost** [comment]
Hi there,

There's been improvements in a couple of releases specifically around addressing error handling- I'd suggest you upgrade to 2.15.1 to start with and see if you are still having this issue.

Thanks!
