### ISSUE TITLE
pgbackrest restore issue

### ISSUE THREAD

**Issue by prakashtcs30** [pgbackrest/pgbackrest#778]
1.pgBackRest 2.15 production and development server
2.postgres=# select version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 10.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit
(1 row)
3.CentOS Linux release 7.6.1810 (Core)
4.yes using yum install.
5.
a)dev server - pgbackrest.conf file

==> cat /etc/pgbackrest.conf
#[global]
#repo1-path=/Postgres/pgBACKUP/A4_sydcosausd001
#retention-diff=4
#retention-full=4
#retention-archive=2
#start-fast=y
#process-max=4
#archive-async=y

#[global:archive-push]
#process-max=4

#[A4_sydcosausd001]
#db-path=/Postgres/pgDATA/data

[global]
repo1-host=sydcosafpp001.enterprisenet.org
repo1-host-user=postgres
repo1-host-config=/etc/pgbackrest.conf
repo1-path=/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001

[A4_sydcosafpp001]
pg1-path=/Postgres/pgDATA/data

b)prod server pgbackrest.conf

==> cat /etc/pgbackrest.conf
[global]
repo1-path=/pgBACKUP/A4_sydcosafpp001
retention-diff=3
retention-full=1
retention-archive=2
start-fast=y
process-max=12
archive-async=y

[global:archive-push]
process-max=4

[A4_sydcosafpp001]
pg1-path=/Postgres/pgDATA/data

7.We are trying to restore the database using below command 
source prod and target is dev server but in production we have backup and and path but not able to restore the database.
Please do the needfull.

==> pgbackrest --stanza=A4_sydcosafpp001 --log-level-console=info --db-path=/Postgres/prakash_pgbackrest --process-max=2 --db-include=A4_Copy restore --repo1-path=/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001
2019-07-14 00:13:56.015 P00 INFO: restore command begin 2.15: --db-include=A4_Copy --log-level-console=info --pg1-path=/Postgres/prakash_pgbackrest --process-max=2 --repo1-host=sydcosafpp001.enterprisenet.org --repo1-host-config=/etc/pgbackrest.conf --repo1-host-user=postgres --repo1-path=/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001 --stanza=A4_sydcosafpp001
Password:
ERROR [055]: : raised from remote process on 'sydcosafpp001.enterprisenet.org': unable to open '/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001/backup/A4_sydcosafpp001/backup.info': No such file or directory
2019-07-14 00:14:06.586 P00 INFO: restore command end: aborted with exception [055]

**Comment by dwsteele** [comment]
You have set `--repo1-path=/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001` on the command-line but it looks like it should be `--repo1-path=/pgBACKUP/A4_sydcosafpp001` according to your config.

**Comment by prakashtcs30** [comment]
Hi Dave,

I tried as you suggested repo path still am not able to restore the dump can you please check below error ,

==> pgbackrest --stanza=A4_sydcosafpp001 --log-level-console=info --db-path=/Postgres/prakash_pgbackrest --process-max=2 --db-include=A4_Copy restore --repo1-path=/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001/backup/A4_sydcosafpp001/
2019-07-15 21:56:07.706 P00 INFO: restore command begin 2.15: --db-include=A4_Copy --log-level-console=info --pg1-path=/Postgres/prakash_pgbackrest --process-max=2 --repo1-host=sydcosafpp001.enterprisenet.org --repo1-host-config=/etc/pgbackrest.conf --repo1-host-user=postgres --repo1-path=/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001/backup/A4_sydcosafpp001 --stanza=A4_sydcosafpp001
Password:
**ERROR [073]: : remote process on 'sydcosafpp001.enterprisenet.org' terminated unexpectedly [073]: repo1-path '/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001/backup/A4_sydcosafpp001' does not exist
2019-07-15 21:56:13.458 P00 INFO: restore command end: aborted with exception [073]**


==> cat /etc/pgbackrest.conf
#[global]
#repo1-path=/Postgres/pgBACKUP/A4_sydcosausd001
#retention-diff=4
#retention-full=4
#retention-archive=2
#start-fast=y
#process-max=4
#archive-async=y


#[global:archive-push]
#process-max=4

#[A4_sydcosausd001]
#db-path=/Postgres/pgDATA/data


[global]
repo1-host=sydcosafpp001.enterprisenet.org
repo1-host-user=postgres
repo1-host-config=/etc/pgbackrest.conf
repo1-path=/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001

[A4_sydcosafpp001]
pg1-path=/Postgres/pgDATA/data

**Comment by prakashtcs30** [comment]
Hi Dave ,

Please find the source path also,

==> cd /pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001/
postgres@sydcosafpp001.enterprisenet.org:/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001
==> ls -lrth
total 104K
drwxr-x---. 4 postgres postgres   44 Jan  7  2019 backup.history
drwxr-x---. 3 postgres postgres   96 Jul 13 21:33 20190713-190001F
drwxr-x---. 3 postgres postgres   96 Jul 14 20:56 20190713-190001F_20190714-190002I
drwxr-x---. 3 postgres postgres   96 Jul 15 20:14 20190713-190001F_20190715-190002I
lrwxrwxrwx. 1 postgres postgres   33 Jul 15 20:14 latest -> 20190713-190001F_20190715-190002I
-rw-r-----. 1 postgres postgres 2.4K Jul 15 20:14 backup.info
-rw-r-----. 1 postgres postgres 2.4K Jul 15 20:14 backup.info.copy

**Comment by cmwshang** [comment]
From what I can tell, the line
repo1-path=/pgBACKUP/A4_sydcosafpp001/backup/A4_sydcosafpp001
should be
repo1-path=/pgBACKUP/A4_sydcosafpp001

**Comment by prakashtcs30** [comment]
Thanks for the quick response but am getting one error not able to start
the database,

2019-07-17 00:45:50.089 AEST,,,21181,,5d2de31d.52bd,1,,2019-07-17 00:45:49
AEST,,0,LOG,00000,"ending log output to stderr",,"Future log output will go
to log destination ""csvlog"".",,,,,,,""
2019-07-17 00:45:50.095 AEST,,,21185,,5d2de31e.52c1,1,,2019-07-17 00:45:50
AEST,,0,LOG,00000,"database system was interrupted; last known up at
2019-07-16 20:09:07 AEST",,,,,,,,,""
2019-07-17 00:45:50.986 AEST,,,21185,,5d2de31e.52c1,2,,2019-07-17 00:45:50
AEST,,0,LOG,00000,"invalid primary checkpoint record",,,,,,,,,""
2019-07-17 00:45:50.986 AEST,,,21185,,5d2de31e.52c1,3,,2019-07-17 00:45:50
AEST,,0,LOG,00000,"invalid secondary checkpoint record",,,,,,,,,""
2019-07-17 00:45:50.986 AEST,,,21185,,5d2de31e.52c1,4,,2019-07-17 00:45:50
AEST,,0,PANIC,XX000,"could not locate a valid checkpoint record",,,,,,,,,""
2019-07-17 00:45:50.986 AEST,,,21181,,5d2de31d.52bd,2,,2019-07-17 00:45:49
AEST,,0,LOG,00000,"startup process (PID 21185) was terminated by signal 6:
Aborted",,,,,,,,,""
2019-07-17 00:45:50.987 AEST,,,21181,,5d2de31d.52bd,3,,2019-07-17 00:45:49
AEST,,0,LOG,00000,"aborting startup due to startup process
failure",,,,,,,,,""
2019-07-17 00:45:51.071 AEST,,,21181,,5d2de31d.52bd,4,,2019-07-17 00:45:49
AEST,,0,LOG,00000,"database system is shut down",,,,,,,,,""
~

**Comment by prakashtcs30** [comment]
Hi cmwshang and dwsteele,

Thanks for your help now am successfully restore the single database restore but not able to start the database getting below errors,

==> cat backup_label
START WAL LOCATION: 3907/2000028 (file 000000010000390700000002)
CHECKPOINT LOCATION: 3907/20425A0
BACKUP METHOD: streamed
BACKUP FROM: master
START TIME: 2019-07-16 19:00:06 AEST
LABEL: pgBackRest backup started at 2019-07-16 19:00:02
postgres@sydcosausd001.enterprisenet.org:/home/postgres
==> cat recovery.conf
restore_command = 'pgbackrest --log-level-console=info --pg1-path=/Postgres/prakash_pgbackrest --process-max=2 --repo1-path=/pgBACKUP/A4_sydcosafpp001 --stanza=A4_sydcosafpp001 archive-get %f "%p"'


**2019-07-17 00:45:50.089 AEST,,,21181,,5d2de31d.52bd,1,,2019-07-17 00:45:49 AEST,,0,LOG,00000,"ending log output to stderr",,"Future log output will go to log destination ""csvlog"".",,,,,,,""
2019-07-17 00:45:50.095 AEST,,,21185,,5d2de31e.52c1,1,,2019-07-17 00:45:50 AEST,,0,LOG,00000,"database system was interrupted; last known up at 2019-07-16 20:09:07 AEST",,,,,,,,,""
2019-07-17 00:45:50.986 AEST,,,21185,,5d2de31e.52c1,2,,2019-07-17 00:45:50 AEST,,0,LOG,00000,"invalid primary checkpoint record",,,,,,,,,""
2019-07-17 00:45:50.986 AEST,,,21185,,5d2de31e.52c1,3,,2019-07-17 00:45:50 AEST,,0,LOG,00000,"invalid secondary checkpoint record",,,,,,,,,""
2019-07-17 00:45:50.986 AEST,,,21185,,5d2de31e.52c1,4,,2019-07-17 00:45:50 AEST,,0,PANIC,XX000,"could not locate a valid checkpoint record",,,,,,,,,""
2019-07-17 00:45:50.986 AEST,,,21181,,5d2de31d.52bd,2,,2019-07-17 00:45:49 AEST,,0,LOG,00000,"startup process (PID 21185) was terminated by signal 6: Aborted",,,,,,,,,""
2019-07-17 00:45:50.987 AEST,,,21181,,5d2de31d.52bd,3,,2019-07-17 00:45:49 AEST,,0,LOG,00000,"aborting startup due to startup process failure",,,,,,,,,""
2019-07-17 00:45:51.071 AEST,,,21181,,5d2de31d.52bd,4,,2019-07-17 00:45:49 AEST,,0,LOG,00000,"database system is shut down",,,,,,,,,""**

Anything need to be added or how can i start the database please share your inputs.

**Comment by dwsteele** [comment]
Are you sure the restore succeeded?  Can you provide the restore command and a debug log using `--log-level-console=debug`?

**Comment by prakashtcs30** [comment]
Hi dwsteele,

While restoring am getting some errors and please find the below details,

**restore_command = 'pgbackrest --log-level-console=info --pg1-path=/Postgres/prakash_pgbackrest --process-max=2 --repo1-path=/pgBACKUP/A4_sydcosafpp001 --stanza=A4_sydcosafpp001 archive-get %f "%p"'**

2019-07-17 00:37:39.260 P00   INFO: write /Postgres/prakash_pgbackrest/recovery.conf
2019-07-17 00:37:39.266 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
2019-07-17 00:37:39.292 P00   INFO: restore command end: completed successfully (51908ms)

after this try to up the cluster i did comment the archive_command and mv backup_label.
again getting same error like,

2019-07-17 00:45:50.089 AEST,,,21181,,5d2de31d.52bd,1,,2019-07-17 00:45:49 AEST,,0,LOG,00000,"ending log output to stderr",,"Future log output will go to log destination ""csvlog"".",,,,,,,""
2019-07-17 00:45:50.095 AEST,,,21185,,5d2de31e.52c1,1,,2019-07-17 00:45:50 AEST,,0,LOG,00000,"database system was interrupted; last known up at 2019-07-16 20:09:07 AEST",,,,,,,,,""


so i did pg_resetwal then i started the database working fine need to do big database i need some details while during restore the single db am getting could not locate a valid checkpoint record error so do we need to give any timing or anything need to add command in pgbackrest restore command .

if i trigger the restore it will anything affect for prod server ?

postgres=# \l+

                                                                               List of databases
    Name     |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   |  Size   | Tablespace |
                                                                                                                                          Description

-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------
 A4          | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |                       | 993 GB  | pg_default |

 A4_Copy     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |                       | 46 MB   | pg_default | This DB is a copy of A4 schema DB
 postgres    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |                       | 11 MB   | pg_default | default administrative connection database
 template0   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +| 7737 kB | pg_default | unmodifiable empty database
             |          |          |             |             | postgres=CTc/postgres |         |            |
 template1   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +| 8061 kB | pg_default | default template for new databases
             |          |          |             |             | postgres=CTc/postgres |         |            |
(6 rows)


postgres=# \c A4
FATAL:  relation mapping file "base/92806997/pg_filenode.map" contains invalid data
Previous connection kept


==> cat backup_label
START WAL LOCATION: 3907/2000028 (file 000000010000390700000002)
CHECKPOINT LOCATION: 3907/20425A0
BACKUP METHOD: streamed
BACKUP FROM: master
START TIME: 2019-07-16 19:00:06 AEST
LABEL: pgBackRest backup started at 2019-07-16 19:00:02

and how can we do this restore without any error need your inputs please verify.

**Comment by prakashtcs30** [comment]
Hi dwsteele,

Can you please help me to solve the above issue.

**Comment by prakashtcs30** [comment]
Hi dwsteele,

Can you please help me to solve the above issue still waiting for your inputs

**Comment by dwsteele** [comment]
You have not provided the output of your `restore` with `--log-level-console=debug` as requested.  There's not much we can do without that.

**Comment by sfrost** [comment]
Greetings,

You can not move the backup_label after performing a restore, that file is absolutely critical to having the restore properly replay all of the necessary WAL.

Running pg_resetwal almost certainly caused your restore to be corrupted and that's why the system isn't functional.

Blow away what you restored, go back to pgbackrest, perform a restore, make sure that the recovery.conf is in place and you have a working restore command and then start up PG and let it go through crash recovery.  Once that's all done, you should be good to go.  Do NOT use pg_resetwal and do NOT move the backup_label file- that will be done by PG once it's finished recovering.

None of this seems to be an issue with pgbackrest.

Thanks,

Stephen

**Comment by prakashtcs30** [comment]
Hi Dwsteele ,

I will update you soon we have some issues in server
