### ISSUE TITLE
ERROR [058]: : version '10' and path '/var/lib/pgsql/10/data' queried from cluster do not match version '10' and pg1-path '/usr/local/pgsql/data10' read from '/usr/local/pgsql/data10/global/pg_control'

### ISSUE THREAD

**Issue by dan-aksenov** [pgbackrest/pgbackrest#779]
1. pgBackRest version:
    **2.15.1(upbraded from -2.07)**

2. PostgreSQL version:
**10.6**

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
**Database server Centos 7 Kernel 3.10.0**

4. Did you install pgBackRest from source or from a package?
**pgbackrest installed from pgdg10 repo**

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

> [global]
> repo1-path=/mnt/nfs/backup
> repo1-retention-full=2
> start-fast=y
> 
> [somename]
> pg1-path=/usr/local/pgsql/data10
> pg1-port=5432
> 
> [global:archive-push]
> compress-level=3

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

> port = 5432
> archive_mode = on
> listen_addresses = '*'
> archive_command = 'pgbackrest --stanza=somename archive-push %p'
> max_wal_senders = 10
> wal_level=replica(default)

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. /var/log/pgbackrest/mystanza_backup.log`

> -------------------PROCESS START-------------------
> 2019-07-15 13:52:27.620 P00   INFO: backup command begin 2.15: --pg1-path=/usr/local/pgsql/data10 --pg1-port=5432 --repo1-path=/mnt/nfs/backup --repo1-retention-full=2 --stanza=somename --start-fast --type=full
> 2019-07-15 13:52:28.506 P00  ERROR: [058]: version '10' and path '/var/lib/pgsql/10/data' queried from cluster do not match version '10' and pg1-path '/usr/local/pgsql/data10' read from '/usr/local/pgsql/data10/global/pg_control'
>                                         HINT: the pg1-path and pg1-port settings likely reference different clusters
> 2019-07-15 13:52:28.507 P00   INFO: backup command end: aborted with exception [058]

7. Describe the issue:
After upgrade from 2.07 to 2.15 got ERROR [058].
My database directory (/var/lib/pgsql/10) contains symlink to /usr/local/pgsql/data10, but pgbackrest is using /usr/local/pgsql/data10 as pg_path1

**Comment by dwsteele** [comment]
This is due to a regression that was fixed for 2.10, 6e88f93991171632f.  The solution is to configure `data_directory` in `postgresql.conf` to the directory `/usr/local/pgsql/data10`.

We're planning to make this better during the C migration of backup (i.e. follow links in the check), but for now that's the way it is.

**Comment by dan-aksenov** [comment]
Thanks for response. I guess I'll just remount my volumes to avoid symlinks. It's "legacy" from previous admin anyway. Should fix it long time ago. Good reason to do it now.
