### ISSUE TITLE
Question - S3 configuration with minio

### ISSUE THREAD

**Issue by pgstef** [pgbackrest/pgbackrest#781]
Hi,

I'm trying to test the pgBackRest "S3" configuration (and I'm not really familiar with AWS S3).

I've just installed minio following this guide : https://www.centosblog.com/install-configure-minio-object-storage-server-centos-linux/.

As seen in other issues, I've added `MINIO_DOMAIN=minio.local` to the minio configuration and `127.0.0.1 pgbackrest.minio.local minio.local` to the hosts file.

I've then installed s3cmd to create the bucket:

```
# cat .s3cfg 
host_base = minio.local:9000 
host_bucket = pgbackrest.minio.local:9000
bucket_location = eu-west-3
use_https = false
access_key = ***
secret_key = ***

# s3cmd mb s3://pgbackrest
Bucket 's3://pgbackrest/' created
# s3cmd sync repo s3://pgbackrest
upload: 'repo/sample_file' -> 's3://pgbackrest/repo/sample_file'  [1 of 1]
# s3cmd ls s3://pgbackrest/repo/sample_file
2019-07-17 13:48         0   s3://pgbackrest/repo/sample_file
```

Finally, installed pgBackRest 2.15 (using the rpm provided in the PGDG repository) with this configuration:

```
[global]
repo1-path=/repo
repo1-type=s3
repo1-s3-endpoint=minio.local
repo1-s3-bucket=pgbackrest
repo1-s3-host=pgbackrest.minio.local
repo1-s3-verify-ssl=n
repo1-s3-key=***
repo1-s3-key-secret=***
repo1-s3-region=eu-west-3
```

The `stanza-create` command fails with a "connection refused" error:

```
P00  DEBUG:     Storage::S3::Request->new(): bVerifySsl = false, iPort = [undef], lBufferMax = 4194304, strAccessKeyId = <redacted>, strBucket = pgbackrest, strCaFile = [undef], strCaPath = [undef], strEndPoint = minio.local, strHost = pgbackrest.minio.local, strRegion = eu-west-3, strSecretAccessKey = <redacted>, strSecurityToken = [undef]
P00  DEBUG:     Storage::Local->new(): bAllowTemp = <true>, hRule = [hash], lBufferMax = 4194304, oDriver = [object], strCipherPassUser = [undef], strCipherType = [undef], strDefaultFileMode = <0640>, strDefaultPathMode = <0750>, strPathBase = /repo, strTempExtension = pgbackrest.tmp
P00  DEBUG:     Storage::Local->pathExists(): strPathExp = /repo/archive/main
ERROR [049]: : unable to create socket: Connection refused
```

What am I missing here? Maybe some port issue? Can we specify a specific port in pgBackRest configuration?

If I add ":9000" to the repo1-s3-host parameter, I got: `ERROR [049]: : unable to create socket: Name or service not known`.

Any advice here?

Many thanks in advance,
Kind regards

**Comment by dwsteele** [comment]
Try setting `repo1-s3-endpoint=minio.local:9000` and remove the `repo1-s3-host` param.  This is generally needed only for debugging.  Or run minio on port 443.

**Comment by pgstef** [comment]
Thanks for the suggestion.

I just tried it but then:

```
P00  DEBUG:     Storage::S3::Request->new(): bVerifySsl = false, iPort = [undef], lBufferMax = 4194304, strAccessKeyId = <redacted>, strBucket = pgbackrest, strCaFile = [undef], strCaPath = [undef], strEndPoint = minio.local:9000, strHost = [undef], strRegion = eu-west-3, strSecretAccessKey = <redacted>, strSecurityToken = [undef]
P00  DEBUG:     Storage::Local->new(): bAllowTemp = <true>, hRule = [hash], lBufferMax = 4194304, oDriver = [object], strCipherPassUser = [undef], strCipherType = [undef], strDefaultFileMode = <0640>, strDefaultPathMode = <0750>, strPathBase = /repo, strTempExtension = pgbackrest.tmp
P00  DEBUG:     Storage::Local->pathExists(): strPathExp = /repo/archive/main
ERROR [049]: : unable to create socket: Name or service not known
```
I'll check how to run MinIO on 443

**Comment by dwsteele** [comment]
Here's the config for the minio container we use to build the documentation: https://github.com/pgbackrest/pgbackrest/blob/master/doc/xml/user-guide.xml#L633

**Comment by pgstef** [comment]
Hello David,

Thank you very much for all those suggestions. I managed to make MinIO work with https using the same config (self-signed certificates,...).

pgBackRest then works fine (stanza-create, backup, archive-push). I think I'll make a blog post about it.

Just some thoughts, wouldn't it be interesting to have some `repo1-s3-port` configuration parameter (or re-use the repo1-host-user) to be able to specify another port than the default "https 443" ? That would allow other S3 compatible api to work easily with pgBackRest.

Thanks again for your help.

Kind regards,

**Comment by dwsteele** [comment]
> wouldn't it be interesting to have some repo1-s3-port configuration parameter (or re-use the repo1-host-user) to be able to specify another port than the default "https 443"

We have been planning to do this, just haven't quite gotten around to it yet.

**Comment by pgstef** [comment]
Great. Good to know. Thanks.
We can close this issue. Thanks again for your advices.
Kind regards,
