### ISSUE TITLE
basic pgbackrest setup not working and not connecting to Standby

### ISSUE THREAD

**Issue by pinakesh** [pgbackrest/pgbackrest#783]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.13

2. PostgreSQL version: psql (PostgreSQL) 11.0

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Linux RHEL 7.6 (Maipo) both

4. Did you install pgBackRest from source or from a package? Yes

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
 
[postgres@Server02cn data]$ cat /etc/pgbackrest/pgbackrest.conf  (Same in both Primary and Standby)
[newdemo]
pg1-host=Server02cn
pg1-path=/u02/pb/postgres/pgbackrest_test/data
pg2-host=Server04cn
pg2-path=/u02/pb/postgres/pgbackrest_test/data

[global]
backup-standby=y
process-max=3
repo1-path=/u02/pb/postgres/pgbackrest_test/backup
repo1-retention-full=2
start-fast=y
[postgres@Server02cn data]$

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

listen_addresses = '*'         
port = 55432                           
wal_level = replica
archive_mode = off             
archive_command = 'pgbackrest --stanza=newdemo archive-push %p'
max_wal_senders = 10

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

This is a new setup, created new postgres cluster and new /etc/pgbackrest/pgbackrest.conf file on both Primary (Server02cn) and Standby (Server04cn - used pg_basebackup and recovery.conf) but when I am trying to create stanza I am getting below error, please help.

Note : Passwordless SSH is already setup between Primary and Standby for the OS user named postgres (same user in both Primary and Standby)

[postgres@Server02cn data]$ pgbackrest stanza-create --stanza newdemo --pg1-port=55432 --pg2-port=55432
WARN [050]: : raised from remote process on 'Server02cn': unable to acquire lock on file '/tmp/pgbackrest/newdemo-archive.lock': Resource temporarily unavailable
HINT: is another pgBackRest process running? at /loader/0x8bc468/pgBackRest/Protocol/Base/Minion.pm line 159.
 at /loader/0x8bc468/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('PGBRCLIB:50:common/lock.c:109:unable to acquire lock on file ...') called at /loader/0x8bc468/pgBackRest/Protocol/Base/Minion.pm line 159
        eval {...} called at /loader/0x8bc468/pgBackRest/Protocol/Base/Minion.pm line 168
        eval {...} called at /loader/0x8bc468/pgBackRest/Protocol/Base/Minion.pm line 224
        pgBackRest::Protocol::Base::Minion::process('pgBackRest::Protocol::Remote::Minion=HASH(0x1634d38)', '/tmp/pgbackrest', 'stanza-create', 'newdemo', 0) called at /loader/0x8bc468/pgBackRest/Main.pm line 104
        eval {...} called at /loader/0x8bc468/pgBackRest/Main.pm line 264
        pgBackRest::Main::main('remote') called at (eval 272) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'remote\')
;' called at (eval 272) line 0

WARN [056]: : raised from remote process on 'Server04cn': could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.55432"?
ERROR [049]: : unable to find standby database - cannot proceed
[postgres@Server02cn data]$

Regards,
Pinakesh

**Comment by SaanSingh** [comment]
archive_mode = off , should be 'on'

Try setting it 'on' and restart postgres.

**Comment by pinakesh** [comment]
Hi Saan,

Thanks for responding.

I changed archive_mode=on (on both primary and standby) then restarted primary and standby.

But, still while trying to create stanza (on primary) I am getting the same error as below ::

[postgres@Server02cn data]$ pgbackrest stanza-create --stanza newdemo --pg1-port=55432 --pg2-port=55432
WARN [050]: : raised from remote process on 'Server02cn': unable to acquire lock on file '/tmp/pgbackrest/newdemo-archive.lock': Resource temporarily unavailable
HINT: is another pgBackRest process running? at /loader/0x1f09468/pgBackRest/Protocol/Base/Minion.pm line 159.
 at /loader/0x1f09468/pgBackRest/Main.pm line 12.
        pgBackRest::Main::__ANON__('PGBRCLIB:50:common/lock.c:109:unable to acquire lock on file ...') called at /loader/0x1f09468/pgBackRest/Protocol/Base/Minion.pm line 159
        eval {...} called at /loader/0x1f09468/pgBackRest/Protocol/Base/Minion.pm line 168
        eval {...} called at /loader/0x1f09468/pgBackRest/Protocol/Base/Minion.pm line 224
        pgBackRest::Protocol::Base::Minion::process('pgBackRest::Protocol::Remote::Minion=HASH(0x2c84ff8)', '/tmp/pgbackrest', 'stanza-create', 'newdemo', 0) called at /loader/0x1f09468/pgBackRest/Main.pm line 104
        eval {...} called at /loader/0x1f09468/pgBackRest/Main.pm line 264
        pgBackRest::Main::main('remote') called at (eval 272) line 1
        eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'remote\')
;' called at (eval 272) line 0

WARN [056]: : raised from remote process on 'Server04cn': could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.55432"?
ERROR [049]: : unable to find standby database - cannot proceed
[postgres@Server02cn data]$

Please suggest.

**Comment by pinakesh** [comment]
Hi,

Just wanted to keep you informed about this thing.

I tried to create a new cluster (only primary without standby) to check if indeed pgbackrest is working or not.

the entry for the stanza was as below ::

[testdemo]
pg1-host=appftd02cn
pg1-path=/u02/pb/postgres/pgbackrest_test/test_data
pg1-port=45432

postgresql.conf was set up correctly this time, but when I tried to create stanza, again I got this error ::

-------------------PROCESS START-------------------
2019-07-19 06:13:15.075 P00   INFO: stanza-create command begin 2.13: --backup-standby --pg1-host=Server02cn --pg1-path=/u02/pb/postgres/pgbackrest_test/test_data --pg1-port=45432 --repo1-path=/u02/pb/postgres/pgbackrest_test/backup --stanza=testdemo
2019-07-19 06:13:45.984 P00  ERROR: [050]: raised from remote process on 'Server02cn': unable to acquire lock on file '/tmp/pgbackrest/testdemo-archive.lock': Resource temporarily unavailable
                                        HINT: is another pgBackRest process running? at /loader/0x115c428/pgBackRest/Protocol/Base/Minion.pm line 159.
                                         at /loader/0x115c428/pgBackRest/Main.pm line 12.
                                                pgBackRest::Main::__ANON__('PGBRCLIB:50:common/lock.c:109:unable to acquire lock on file ...') called at /loader/0x115c428/pgBackRest/Protocol/Base/Minion.pm line 159
                                                eval {...} called at /loader/0x115c428/pgBackRest/Protocol/Base/Minion.pm line 168
                                                eval {...} called at /loader/0x115c428/pgBackRest/Protocol/Base/Minion.pm line 224
                                                pgBackRest::Protocol::Base::Minion::process('pgBackRest::Protocol::Remote::Minion=HASH(0x1ed8018)', '/tmp/pgbackrest', 'stanza-create', 'testdemo', 0) called at /loader/0x115c428/pgBackRest/Main.pm line 104
                                                eval {...} called at /loader/0x115c428/pgBackRest/Main.pm line 264
                                                pgBackRest::Main::main('remote') called at (eval 272) line 1
                                                eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'remote\')
                                        ;' called at (eval 272) line 0

2019-07-19 06:13:45.993 P00   INFO: stanza-create command end: aborted with exception [050]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

But then when I removed the entry 'pg1-host=appftd02cn' from the stanza in pgbackrest.conf then stanza create was successful as below ::

-------------------PROCESS START-------------------
2019-07-19 06:14:39.211 P00   INFO: stanza-create command begin 2.13: --backup-standby --pg1-path=/u02/pb/postgres/pgbackrest_test/test_data --pg1-port=45432 --repo1-path=/u02/pb/postgres/pgbackrest_test/backup --stanza=testdemo
2019-07-19 06:14:39.900 P00   INFO: stanza-create command end: completed successfully (690ms)


Please suggest if it is mandatory to use pg[12]-host parameter in pgbackrest.conf in order to take backup from Standby server??

Regards,
Pinakesh

**Comment by dwsteele** [comment]
> Please suggest if it is mandatory to use pg[12]-host parameter in pgbackrest.conf in order to take backup from Standby server??

Don't configure the pg?-host if the database is local to the host.  The pg instance that is local to the host should always be configured with pg1-*.

Using the standby to perform backups is a poor configuration which is why we don't cover it in the user guide.  It's also confusing because the config on the primary and standby must be different to get it to work.  We recommend using a repo host for a more robust system and simpler configuration.

**Comment by pinakesh** [comment]
Hi Dwsteele,

Thanks for your input, however for testing purpose I need to first check if backups can be taken from the Standby server and document the procedure and then I will have to work on using separate backup server.

What I understood from your last comment is that in Primary's pgbackrest.conf pg2-host='Standby's hostname' and on standby's pgbackrest.conf pg2-host='Primary's hostname'

So my configuration is as below ::

On Server02cn
----------------

[postgres@Server02cn ~]$ cat /etc/pgbackrest/pgbackrest.conf
[newdemo]
#pg1-host=Server02cn
pg1-path=/u02/pb/postgres/pgbackrest_test/data
pg2-host=Server04cn
pg2-path=/u02/pb/postgres/pgbackrest_test/data
log-level-console=info

[global]
backup-standby=y
process-max=3
repo1-path=/u02/pb/postgres/pgbackrest_test/backup
repo1-retention-full=2
start-fast=y


On Server04cn
----------------

[postgres@Server04cn ~]$ cat /etc/pgbackrest/pgbackrest.conf
[newdemo]
#pg1-host=Server02cn
pg1-path=/u02/pb/postgres/pgbackrest_test/data
pg2-host=Server0r2cn
pg2-path=/u02/pb/postgres/pgbackrest_test/data

[global]
backup-standby=y
process-max=3
repo1-path=/u02/pb/postgres/pgbackrest_test/backup
repo1-retention-full=2
start-fast=y

Now, while running stanza-create on Primary I am getting below error.

On Server02cn
-------------


[postgres@Server02cn ~]$
[postgres@Server02cn ~]$ pgbackrest stanza-create --stanza newdemo  --pg1-port 55432 --pg2-port 55432
2019-07-22 01:18:41.167 P00   INFO: stanza-create command begin 2.13: --backup-standby --log-level-console=info --pg2-host=Server04cn --pg1-path=/u02/pb/postgres/pgbackrest_test/data --pg2-path=/u02/pb/postgres/pgbackrest_test/data --pg1-port=55432 --pg2-port=55432 --repo1-path=/u02/pb/postgres/pgbackrest_test/backup --stanza=newdemo
WARN [056]: : raised from remote process on 'Server04cn': could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.55432"?
ERROR [049]: : unable to find standby database - cannot proceed
2019-07-22 01:18:42.281 P00   INFO: stanza-create command end: aborted with exception [049]
[postgres@Server02cn ~]$


I also checked that passwordless SSH is properly set.

[postgres@Server02cn ~]$
[postgres@Server02cn ~]$ hostname
Server02cn
[postgres@Server02cn ~]$
[postgres@Server02cn ~]$ ssh Server04cn
Last login: Mon Jul 22 01:09:45 2019
[postgres@Server04cn ~]$ hostname
Server04cn
[postgres@Server04cn ~]$
[postgres@Server04cn ~]$ exit
logout
Connection to Server04cn closed.
[postgres@Server02cn ~]$
[postgres@Server02cn ~]$ psql -p 55432 -h Server04cn
psql (11.0)
Type "help" for help.

postgres=# \conninfo
You are connected to database "postgres" as user "postgres" on host "Server04cn" at port "55432".
postgres=#

postgres=# \conninfo
You are connected to database "postgres" as user "postgres" on host "Server04cn" at port "55432".
postgres=#

Please can you help with the proper configuration for getting backup from standby server?

Regards,
Pinakesh

**Comment by pinakesh** [comment]
Hi Team,

Please can someone help me with this issue?

Regards,
Pinakesh

**Comment by dwsteele** [comment]
Are you sure the standby cluster exists and is running on port `55432`?  If not try running `stanza-create` with `--no-backup-standby`.  You'll need to do the same for your first backup until there is a functional standby.

**Comment by pinakesh** [comment]
Hi,

Yes I am sure that the standby cluster exists and is running on port 55432, please find output of commands ran from Primary (Server02cn)

Standby Details
------------------

[postgres@Server02cn postgres]$ psql -p 55432 -c "select client_addr, state, sent_lsn, write_lsn,flush_lsn, replay_lsn from pg_stat_replication;"
 client_addr  |   state   | sent_lsn  | write_lsn | flush_lsn | replay_lsn
--------------+-----------+-----------+-----------+-----------+------------
 10.112.1.111 | streaming | 0/40151F0 | 0/40151F0 | 0/40151F0 | 0/40151F0
(1 row)

[postgres@Server02cn postgres]$ ssh postgres@10.112.1.111 "hostname"
Server04cn
[postgres@Server02cn postgres]$


Checking if Standby is running
------------------------------------

[postgres@Server02cn postgres]$ psql -p 55432 -h 10.112.1.111
psql (11.0)
Type "help" for help.

postgres=# \conninfo
You are connected to database "postgres" as user "postgres" on host "10.112.1.111" at port "55432".
postgres=#
postgres=# select pg_is_in_recovery();
 pg_is_in_recovery
-------------------
 t
(1 row)

postgres=#


Just to bring to your notice.
--------------------------------

I configured passwordless SSH for the OS user named 'postgres' on both Primary and Standby server using 'ssh-keygen' and 'ssh-copy-id' commands and kept passphrase as null.

Regards,
Pinakesh

**Comment by pinakesh** [comment]
Hi Team,
Please can you help fix the issue?
Regards,
Pinakesh

**Comment by sfrost** [comment]
pgbackrest is trying to connect to PG over the *unix* socket, not the TCP socket, they're not the same thing.

Make sure that the *Unix* socket exists at /var/run/postgresql/.s.PGSQL.55432

That's what the error message is very clearly telling you- it's not there.  You need to either configure PG to put it there, or configure pgbackrest to find it in whatever location you have it.

There's no issue here with pgbackrest as far as I can tell, just a matter of you needing to configure it properly.

Thanks.
