### ISSUE TITLE
Feature Request: Progress Logging and lesser log log levels

### ISSUE THREAD

**Issue by bradnicholson** [pgbackrest/pgbackrest#784]
When backing up and restoring large databases, it would be nice to get a periodic log message logging the progress.  

While we can get that with the `info` log level, it would be nice to get some periodic indicator at a lower log volume.

**Comment by dwsteele** [comment]
Our plan is to add the status of the currently running backup to the `info` command.  Would that work for you?

The next log level above `info` is `warn` and that would not be appropriate for status messages.

**Comment by bradnicholson** [comment]
> Our plan is to add the status of the currently running backup to the info command. Would that work for you?

That would work great - thanks!
