### ISSUE TITLE
Can I recreate standby using pg_basebackup when pgbackrest is running on primary?

### ISSUE THREAD

**Issue by SaanSingh** [pgbackrest/pgbackrest#786]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
>2.13
2. PostgreSQL version:
>9.5
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
>CentOS Linux release 7.6.1810 (Core)

4. Did you install pgBackRest from source or from a package?
>package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by dwsteele** [comment]
You can use pg_basebackup on the same cluster as pgbackrest, but you'd be better off building your standby with pgbackrest.  It's faster and does not put load on your primary.  See https://pgbackrest.org/user-guide-centos7.html#replication.

**Comment by SaanSingh** [comment]
Thanks for the reply mate.
My primary is 5TB and pgbackrest is running on it. 
My standby was out of sync, so I initiated basebackup from standby. It failed after copying 2TB data with Connection timeout error. My wal_keep segments is 8000 on primary.

I am not sure what is wrong. I tried this many times and same thing happened.
We can rule out network, disk size issues here.

Is it possible when basebackup was trying to get the wals from primary,pgbackrest archived and deleted those WALS ?
Any help will be much appreciated. 

Thanks

**Comment by SaanSingh** [comment]
Is it mandatory to have seperate repo server?
Can’t I take backup on master and recover standby using archive-get?

**Comment by dwsteele** [comment]
It is possible to take a backup on the primary but it is a very dangerous configuration.  If the primary goes out you lose your primary and standby at the same time.

**Comment by SaanSingh** [comment]
Thanks David.

**Comment by dwsteele** [comment]
Let me caveat by saying that it's OK to run the backup on your primary if the repo is located on NFS, CIFS, S3, etc.  The important thing is that the backup is *not* stored directly on the primary host.

**Comment by SaanSingh** [comment]
Thanks David
