### ISSUE TITLE
Backup failed because of a "simple" warning

### ISSUE THREAD

**Issue by LaetitiaJV** [pgbackrest/pgbackrest#790]
We're trying to upgrade Postgres from 9.3 to 10. We have new hosts to perform that. So, we decided to turn the new host into princesses waiting for the old queen to die…

1. pgBackRest version: 2.15 (on both sides)

2. PostgreSQL version: PostgreSQL 9.3.5 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
- queen on jessie
- princess to be on stretch (that's the host I'm performing the backup from)

4. Did you install pgBackRest from source or from a package?
From package, on the old host, it was tricky according to the sysadmin

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
On queen:

```
[global]
backup-host=jv-sql-www-primary-one-new.eu2.wbd.tech
backup-user=postgres

[jvone]
pg1-path=/var/lib/postgresql/9.3/main
```

On princess:

```
[global]
repo-path=/var/lib/pgbackrest
repo1-retention-full=1
compress-level=9

[jvone]
pg1-host=jv-sql-www-primary-one.eu1.wbd.tech
pg1-path=/var/lib/postgresql/9.3/main
repo1-host-user=postgres
```

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
Archiving is performing very well. 

    - errors in the postgresql log file before or during the time you experienced the issue
No error

    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
Here is the end of the backup log. everything went well except the end (after more than 9 hours)

```
2019-07-25 18:07:53.059 P00   INFO: full backup size = 148GB
2019-07-25 18:07:53.059 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
2019-07-25 18:08:04.180 P00   INFO: backup stop archive = 00000004000054460000002A, lsn = 5446/2A0529E8
2019-07-25 18:08:04.194 P00  ERROR: [042]: remote process on 'jv-sql-www-primary-one.eu1.wbd.tech' terminated unexpectedly [000]: perl: warning: Setting locale failed.
                                        perl: warning: Please check that your locale settings:
                                                LANGUAGE = (unset),
                                                LC_ALL = (unset),
                                                LC_PAPER = "en_US.UTF-8",
                                                LC_ADDRESS = "en_US.UTF-8",
                                                LC_MONETARY = "en_US.UTF-8",
                                                LC_NUMERIC = "en_US.UTF-8",
                                                LC_TELEPHONE = "en_US.UTF-8",
                                                LC_IDENTIFICATION = "en_US.UTF-8",
                                                LC_COLLATE = "en_US.UTF-8",
                                                LC_MEASUREMENT = "en_US.UTF-8",
                                                LC_TIME = "en_US.UTF-8",
                                                LC_NAME = "en_US.UTF-8",
                                                LANG = "fr_FR.UTF-8"
                                            are supported and installed on your system.
                                        perl: warning: Falling back to a fallback locale ("fr_FR.UTF-8").
2019-07-25 18:08:04.212 P00   INFO: backup command end: aborted with exception [042]
```

7. Describe the issue:
A "simple" warning (no locale set for perl) raises an error and the backup is therefore considered as not valid.

I understand that with backup we really want to be cautious, but isn't it too much ?

Then I'd like to use my backup (more than 9 hours, 148GB) and I can't find a way to "tell" backrest it's ok. Could you save me one day of work (which I'm really short of for this mission) ?

**Comment by sfrost** [comment]
If you simply fix the locale issue and run a new backup of the same type, and you haven't disabled 'resume', then pgbackrest should be able to use the existing files in the temp directory (it'll have to checksum on the remote server to verify, but that should be much, much faster than actually doing the backup).  I'm kind of curious how you ended up only hitting that issue at the very end of the backup too...

**Comment by dwsteele** [comment]
pgBackRest errors if it finds anything on stderr during protocol shutdown.  This is for safety since nothing should be there.  So, this was surely output when Perl was started, but did not cause an issue until the end.

I'm with Stephen, fix the locale issue on the pg host and you should be OK.  And the next backup should resume and complete much faster.

**Comment by LaetitiaJV** [comment]
Thanks for your quick answer…

Of course, I can't do it myself… Why trust DBAs with production server? So I'll advise the right guy to do it…
