### ISSUE TITLE
(doc) db timeout does not reference protocol timeout relationship

### ISSUE THREAD

**Issue by jameschancojr** [pgbackrest/pgbackrest#793]
Not version specific*

On https://pgbackrest.org/configuration.html#section-general/option-db-timeout section 4.11 (protocol timeout) states: "The protocol-timeout option must be greater than the db-timeout option.", however, there is no reciprocal comment for db-timeout. 

If the user experiences a db-timeout, backrest will inform them of the same, and if you go to look at section 4.6 in the documentation it doesn't tell you about the relationship with 4.11 (protocol-timeout) this can lead to the user setting them inappropriately (as I did).

**Comment by cmwshang** [comment]
Thanks for pointing this out! We will attempt to target this fix for the next release.

**Comment by dwsteele** [comment]
Committed at f57e119b25d from #824.
