### ISSUE TITLE
pgbackrest from standby feature

### ISSUE THREAD

**Issue by rpiras** [pgbackrest/pgbackrest#794]
Is correct my understanding that in case of backup from standby (backup-standby option enabled ) the backup would fail if the standby node is not running?
Doesn't make it sense to backup from primary in this occurrence? Or at least could it be a configurable behavior?

The scenario I have in mind is the following:
- I configure a postgresql cluster with 2 nodes via streaming replication
- I set up periodic backups with pgbackrest leveraging the possibility to backup from standby
- I also put in place some automation to switch to the replica in case primary server fails

At this point I'd like scheduled backups to still work even if no standby is running (as long as the issue with it is fixed) without the need to reconfigure pgbackrest

Thanks

**Comment by dwsteele** [comment]
See #753 for discussion of this feature request.
