### ISSUE TITLE
WAL contains references to invalid pages

### ISSUE THREAD

**Issue by julianzhang98** [pgbackrest/pgbackrest#796]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.15.1

2. PostgreSQL version: 11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CENTOS 6

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

pgbackrest restore is run with these flags, which result in a recovery.conf file with these corresponding values.

--recovery-target = immediate
--recovery-target-action = promote

7. Describe the issue:

I have 7 or 8 databases, and sometimes, I don't want to restore all of them. this is the process in which this error is reproduced:

First, I stanza-create, then I backup immediately after. When I try to restore it, with --db-include=xxx, then start up the cluster again, I get the following in the postgresql logs

WARNING:  page XX of relation base/YYYYY/ZZZZ is uninitialized
PANIC:  WAL contains references to invalid pages
LOG:  startup process (PID 24648) was terminated by signal 6: Aborted
LOG:  terminating any other active server processes
LOG:  database system is shut down

However, if I don't restore with --db-include flags, it works perfectly fine. Could you guys help me out? Thanks!

**Comment by dwsteele** [comment]
I had a look at the Postgres source and this error happens when full page writes have been disabled.  Backups should be re-enabling them (during the backup at least) but it may still cause a problem in this case.  Do you have `full_page_writes=off` or any other unusual settings?

**Comment by julianzhang98** [comment]
No I don't believe so, just to verify, full_page_writes and rsync are on by default correct?

**Comment by dwsteele** [comment]
> just to verify, full_page_writes and rsync are on by default correct?

Yes, they are.

This query is a simple way to find non-default values in your config:
```
select name, setting from pg_settings where sourcefile is not null;
```

**Comment by julianzhang98** [comment]
Yea both full_page_writes and rsync are on.

**Comment by dwsteele** [comment]
Anything interesting about this db/relation?

**Comment by julianzhang98** [comment]
Nope :( I couldn't replicate the error without recreating the stanza immediately before though, if that tells you something.

**Comment by julianzhang98** [comment]
as in, i'd have to specifically run stanza-create, backup immediately, and then restore with --db-include...

**Comment by Yuxael** [comment]
I recently run into the same problem when trying PITR-restore of specific database. My restore command was something like:
```
pgbackrest --stanza stanza1 restore --db-include test --type time --set xxxxxxxx "--target=somedate"
```
When I tried to start the cluster I got the same error message that `WAL contains references to invalid pages` but the base and table OID was from totally different than I was restoring.

What helped was to set an earlier target date untill specific WAL was not processed during restore. I think I might be able to reproduce it, but TBH I have no idea what to look for.

**Comment by uspen** [comment]
I also came across this. I just removed the option --db-include (only one database behaves this way). In general, it is better to use a paradigm 'database per cluster'

**Comment by Yuxael** [comment]
And again I've hit this problem today, when restoring single db, but this time the only thing that helped was to set `recovery_target = 'immediate'` in restore.conf. Otherwise I would get this:
```
2019-11-21 16:46:49.242 CET [23018] LOG:  restored log file "000000010000019A000000EE" from archive
2019-11-21 16:46:49.434 CET [23018] LOG:  consistent recovery state reached at 19A/EEB101C0
2019-11-21 16:46:49.434 CET [23017] LOG:  database system is ready to accept read only connections
2019-11-21 16:46:49.447 CET [23018] WARNING:  page 133 of relation base/16715/2326801 is uninitialized
2019-11-21 16:46:49.447 CET [23018] CONTEXT:  WAL redo at 19A/EEC44E08 for Heap2/VISIBLE: cutoff xid 258049327 flags 1
2019-11-21 16:46:49.447 CET [23018] PANIC:  WAL contains references to invalid pages
2019-11-21 16:46:49.447 CET [23018] CONTEXT:  WAL redo at 19A/EEC44E08 for Heap2/VISIBLE: cutoff xid 258049327 flags 1
2019-11-21 16:46:49.452 CET [23017] LOG:  startup process (PID 23018) was terminated by signal 6: Aborted
2019-11-21 16:46:49.452 CET [23017] LOG:  terminating any other active server processes
2019-11-21 16:46:49.472 CET [23017] LOG:  database system is shut down
```

Can anyone even point out the direction to look at when trying to debug this thing? The only related info with this kind of log messages are from 2013 regarding transaction replay bug in postgres 9.5.

**Comment by dwsteele** [comment]
Well, we've spent some time looking at this and we suspect it may be a bug in Postgres.  The only place we can see this error happening is when a partial page write is being applied on top of a zeroed page (which is how selective restore works, by zeroing out relations you are not interested in).

Unfortunately, we are wrapping up the C migration so have not had any more time to look at it.  Once we are done, we do plan to get back to it.

**Comment by sfrost** [comment]
You could debug this further by looking at pg_waldump for the WAL, figure out where the parial page write came from and then back up in the WAL to see when the last full page write happened for that same page.  If you can't find a prior full page write in the WAL since the point of time that the backup was started, that's a pretty clear smoking gun that PG is being naughty and doing a partial page write of a page that it hadn't previously done a full page write of during that checkpoint and that's a very clear and very bad PG bug.

If you can get down to that point and can share the WAL and specifics about the database cluster, I'm sure the folks on pgsql-hackers (or pgsql-bugs, but please pick one or the other, don't post the same thing to both) would be VERY interested...

**Comment by woblerr** [comment]
> And again I've hit this problem today, when restoring single db, but this time the only thing that helped was to set `recovery_target = 'immediate'` in restore.conf.

We had the same problem when restoring a specific db. Parameter  `recovery_target = 'immediate'` is helped.

pgBackRest version: 2.30
PostgreSQL version: 9.6

> Unfortunately, we are wrapping up the C migration so have not had any more time to look at it. Once we are done, we do plan to get back to it.

Do you have any plans for further analysis of the problem?

**Comment by cmwshang** [comment]
@wobler above, @sfrost mentioned some information to collect - is it possible to provide that information?

**Comment by woblerr** [comment]
@cmwshang, I hope this information will be useful.

pgBackRest version: 2.30
PostgreSQL version: 9.6

Restore command:
```bash
pgbackrest restore --stanza foo-db --db-include foo --tablespace-map-all /var/lib/pgsql/9.6/tablespace --log-level-console info
```

Backup info:
```
stanza: foo-db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (9.6-1): 00000001000000790000002D/000000010000007E0000009F

        full backup: 20210221-010009F
            timestamp start/stop: 2021-02-21 01:00:09 / 2021-02-21 01:34:17
            wal start/stop: 000000010000007E0000007D / 000000010000007E0000007E
            database size: 10.7GB, backup size: 10.7GB
            repository size: 1.2GB, repository backup size: 1.2GB
            database list: foo (16386), bar (17221), postgres (13323)
```

<details>
<summary>The error at database startup:</summary>

    < 2021-02-21 10:34:57.950 UTC > LOG:  starting archive recovery
    < 2021-02-21 10:34:58.137 UTC > LOG:  restored log file "000000010000007E0000007D" from archive
    < 2021-02-21 10:34:58.151 UTC > LOG:  redo starts at 7E/7D0090A8
    < 2021-02-21 10:34:58.521 UTC > LOG:  restored log file "000000010000007E0000007E" from archive
    < 2021-02-21 10:34:58.711 UTC > LOG:  consistent recovery state reached at 7E/7EF5E478
    < 2021-02-21 10:34:58.915 UTC > LOG:  restored log file "000000010000007E0000007F" from archive
    < 2021-02-21 10:34:59.415 UTC > LOG:  restored log file "000000010000007E00000080" from archive
    < 2021-02-21 10:35:01.521 UTC > LOG:  restored log file "000000010000007E00000081" from archive
    < 2021-02-21 10:35:02.110 UTC > LOG:  restored log file "000000010000007E00000082" from archive
    < 2021-02-21 10:35:02.577 UTC > LOG:  restored log file "000000010000007E00000083" from archive
    < 2021-02-21 10:35:03.045 UTC > LOG:  restored log file "000000010000007E00000084" from archive
    < 2021-02-21 10:35:03.544 UTC > LOG:  restored log file "000000010000007E00000085" from archive
    < 2021-02-21 10:35:03.985 UTC > LOG:  restored log file "000000010000007E00000086" from archive
    < 2021-02-21 10:35:05.394 UTC > LOG:  restored log file "000000010000007E00000087" from archive
    < 2021-02-21 10:35:05.945 UTC > LOG:  restored log file "000000010000007E00000088" from archive
    < 2021-02-21 10:35:06.623 UTC > LOG:  restored log file "000000010000007E00000089" from archive
    < 2021-02-21 10:35:07.264 UTC > LOG:  restored log file "000000010000007E0000008A" from archive
    < 2021-02-21 10:35:07.831 UTC > LOG:  restored log file "000000010000007E0000008B" from archive
    < 2021-02-21 10:35:08.318 UTC > LOG:  restored log file "000000010000007E0000008C" from archive
    < 2021-02-21 10:35:08.892 UTC > LOG:  restored log file "000000010000007E0000008D" from archive
    < 2021-02-21 10:35:09.050 UTC > WARNING:  page 22659 of relation base/17221/17557 is uninitialized
    < 2021-02-21 10:35:09.050 UTC > CONTEXT:  xlog redo at 7E/8D9C04C0 for Heap2/VISIBLE: cutoff xid 810424291 flags 1
    < 2021-02-21 10:35:09.050 UTC > PANIC:  WAL contains references to invalid pages
    < 2021-02-21 10:35:09.050 UTC > CONTEXT:  xlog redo at 7E/8D9C04C0 for Heap2/VISIBLE: cutoff xid 810424291 flags 1
    < 2021-02-21 10:35:09.675 UTC > LOG:  startup process (PID 9) was terminated by signal 6: Aborted

</details>

<details>
<summary>pg_controldata information:</summary>

    pg_control version number:            960
    Catalog version number:               201608131
    Database system identifier:           6454899257236535574
    Database cluster state:               in archive recovery
    pg_control last modified:             Sun Feb 21 10:34:58 2021
    Latest checkpoint location:           7E/7D0090E0
    Prior checkpoint location:            7E/7D0090E0
    Latest checkpoint's REDO location:    7E/7D0090A8
    Latest checkpoint's REDO WAL file:    000000010000007E0000007D
    Latest checkpoint's TimeLineID:       1
    Latest checkpoint's PrevTimeLineID:   1
    Latest checkpoint's full_page_writes: on
    Latest checkpoint's NextXID:          0:810727445
    Latest checkpoint's NextOID:          476718
    Latest checkpoint's NextMultiXactId:  1
    Latest checkpoint's NextMultiOffset:  0
    Latest checkpoint's oldestXID:        628489828
    Latest checkpoint's oldestXID's DB:   16386
    Latest checkpoint's oldestActiveXID:  810727445
    Latest checkpoint's oldestMultiXid:   1
    Latest checkpoint's oldestMulti's DB: 17221
    Latest checkpoint's oldestCommitTsXid:0
    Latest checkpoint's newestCommitTsXid:0
    Time of latest checkpoint:            Sat Feb 20 22:00:10 2021
    Fake LSN counter for unlogged rels:   0/1
    Minimum recovery ending location:     7E/7EF5E478
    Min recovery ending loc's timeline:   1
    Backup start location:                0/0
    Backup end location:                  0/0
    End-of-backup record required:        no
    wal_level setting:                    replica
    wal_log_hints setting:                off
    max_connections setting:              800
    max_worker_processes setting:         8
    max_prepared_xacts setting:           0
    max_locks_per_xact setting:           64
    track_commit_timestamp setting:       off
    Maximum data alignment:               8
    Database block size:                  8192
    Blocks per segment of large relation: 131072
    WAL block size:                       8192
    Bytes per WAL segment:                16777216
    Maximum length of identifiers:        64
    Maximum columns in an index:          32
    Maximum size of a TOAST chunk:        1996
    Size of a large-object chunk:         2048
    Date/time type storage:               64-bit integers
    Float4 argument passing:              by value
    Float8 argument passing:              by value
    Data page checksum version:           0

</details>

In WAL there is only one line for `page 27536`:
```bash
rmgr: Heap2       len (rec/tot):     59/    59, tx:          0, lsn: 7E/8D9C04C0, prev 7E/8D9BE508, desc: VISIBLE cutoff xid 810424291 flags 1, blkref #0: rel 1663/17221/17557 fork vm blk 0, blkref #1: rel 1663/17221/17557 blk 22659
```

I tried to find another information in WALs for `xid 810424291` and `blk 22659` - nothing.

<details>
<summary>A few records before 7E/8D9C04C0 from last checkpoint:</summary>

    bash-4.2$ pg_xlogdump 000000010000007E0000008D -s 7E/8D99C4B0 -e 7E/8D9C0500

    rmgr: XLOG        len (rec/tot):    106/   106, tx:          0, lsn: 7E/8D99C4B0, prev 7E/8D99C478, desc: CHECKPOINT_ONLINE redo 7E/8D90D0D8; tli 1; prev tli 1; fpw    true; xid 0:810982162; oid 476718; multi 1; offset 0; oldest xid 628489828 in DB 16386; oldest multi 1 in DB 17221; oldest/newest commit timestamp xid: 0/0; oldest    running xid 810982162; online
    rmgr: Heap2       len (rec/tot):     57/  7965, tx:          0, lsn: 7E/8D99C520, prev 7E/8D99C4B0, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 3, blkref #0: rel    1663/17221/17557 blk 22557 FPW
    rmgr: Heap2       len (rec/tot):     57/  8213, tx:          0, lsn: 7E/8D99E458, prev 7E/8D99C520, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 1, blkref #0: rel    1663/17221/17557 blk 22631 FPW
    rmgr: Heap2       len (rec/tot):     57/  8229, tx:          0, lsn: 7E/8D9A0488, prev 7E/8D99E458, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 3, blkref #0: rel    1663/17221/17557 blk 22632 FPW
    rmgr: Heap2       len (rec/tot):     57/  8117, tx:          0, lsn: 7E/8D9A24C8, prev 7E/8D9A0488, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 3, blkref #0: rel    1663/17221/17557 blk 22633 FPW
    rmgr: Heap2       len (rec/tot):     57/  8093, tx:          0, lsn: 7E/8D9A4498, prev 7E/8D9A24C8, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 1, blkref #0: rel    1663/17221/17557 blk 22634 FPW
    rmgr: Heap2       len (rec/tot):     64/  8256, tx:          0, lsn: 7E/8D9A6450, prev 7E/8D9A4498, desc: VISIBLE cutoff xid 0 flags 2, blkref #0: rel 1663/17221/17557     fork vm blk 0 FPW, blkref #1: rel 1663/17221/17557 blk 22634
    rmgr: Heap2       len (rec/tot):     57/  8101, tx:          0, lsn: 7E/8D9A84A8, prev 7E/8D9A6450, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 4, blkref #0: rel    1663/17221/17557 blk 22639 FPW
    rmgr: Heap2       len (rec/tot):     57/  8149, tx:          0, lsn: 7E/8D9AA468, prev 7E/8D9A84A8, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 1, blkref #0: rel    1663/17221/17557 blk 22640 FPW
    rmgr: Heap2       len (rec/tot):     57/  8213, tx:          0, lsn: 7E/8D9AC458, prev 7E/8D9AA468, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 1, blkref #0: rel    1663/17221/17557 blk 22641 FPW
    rmgr: Heap2       len (rec/tot):     57/  8093, tx:          0, lsn: 7E/8D9AE488, prev 7E/8D9AC458, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 4, blkref #0: rel    1663/17221/17557 blk 22642 FPW
    rmgr: Heap2       len (rec/tot):     57/  8141, tx:          0, lsn: 7E/8D9B0440, prev 7E/8D9AE488, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 2, blkref #0: rel    1663/17221/17557 blk 22643 FPW
    rmgr: Heap2       len (rec/tot):     57/  8125, tx:          0, lsn: 7E/8D9B2428, prev 7E/8D9B0440, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 1, blkref #0: rel    1663/17221/17557 blk 22646 FPW
    rmgr: Heap2       len (rec/tot):     57/  8245, tx:          0, lsn: 7E/8D9B4400, prev 7E/8D9B2428, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 3, blkref #0: rel    1663/17221/17557 blk 22648 FPW
    rmgr: Heap2       len (rec/tot):     57/  8237, tx:          0, lsn: 7E/8D9B6450, prev 7E/8D9B4400, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 1, blkref #0: rel    1663/17221/17557 blk 22649 FPW
    rmgr: Heap2       len (rec/tot):     57/  8221, tx:          0, lsn: 7E/8D9B8498, prev 7E/8D9B6450, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 3, blkref #0: rel    1663/17221/17557 blk 22652 FPW
    rmgr: Heap2       len (rec/tot):     57/  8229, tx:          0, lsn: 7E/8D9BA4D0, prev 7E/8D9B8498, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 3, blkref #0: rel    1663/17221/17557 blk 22653 FPW
    rmgr: Heap2       len (rec/tot):     57/  8157, tx:          0, lsn: 7E/8D9BC510, prev 7E/8D9BA4D0, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 3, blkref #0: rel    1663/17221/17557 blk 22655 FPW
    rmgr: Heap2       len (rec/tot):     57/  8093, tx:          0, lsn: 7E/8D9BE508, prev 7E/8D9BC510, desc: FREEZE_PAGE cutoff xid 760982701 ntuples 1, blkref #0: rel    1663/17221/17557 blk 22657 FPW
    rmgr: Heap2       len (rec/tot):     59/    59, tx:          0, lsn: 7E/8D9C04C0, prev 7E/8D9BE508, desc: VISIBLE cutoff xid 810424291 flags 1, blkref #0: rel 1663/    17221/17557 fork vm blk 0, blkref #1: rel 1663/17221/17557 blk 22659
    
</details>

File `base/17221/17557` - is a file for DB `bar (17221)`, which not restored.

If any additional information is able to help, please describe how to collect it.

---

I also conducted a second test. Added to recovery the `bar (17221)` database. The recovery was successful, there were no errors.

Restore command:
```bash
pgbackrest restore --stanza foo-db --db-include foo --db-include bar --tablespace-map-all /var/lib/pgsql/9.6/tablespace --log-level-console info
```

<details>
<summary>Startup log:</summary>

    < 2021-02-21 11:38:36.340 UTC > LOG:  starting archive recovery
    < 2021-02-21 11:38:36.537 UTC > LOG:  restored log file "000000010000007E0000007D" from archive
    < 2021-02-21 11:38:36.547 UTC > LOG:  redo starts at 7E/7D0090A8
    < 2021-02-21 11:38:36.828 UTC > LOG:  restored log file "000000010000007E0000007E" from archive
    < 2021-02-21 11:38:37.012 UTC > LOG:  consistent recovery state reached at 7E/7EF5E478
    < 2021-02-21 11:38:37.272 UTC > LOG:  restored log file "000000010000007E0000007F" from archive
    < 2021-02-21 11:38:37.650 UTC > LOG:  restored log file "000000010000007E00000080" from archive
    < 2021-02-21 11:38:38.267 UTC > LOG:  restored log file "000000010000007E00000081" from archive
    < 2021-02-21 11:38:38.728 UTC > LOG:  restored log file "000000010000007E00000082" from archive
    < 2021-02-21 11:38:39.071 UTC > LOG:  restored log file "000000010000007E00000083" from archive
    < 2021-02-21 11:38:39.459 UTC > LOG:  restored log file "000000010000007E00000084" from archive
    < 2021-02-21 11:38:39.862 UTC > LOG:  restored log file "000000010000007E00000085" from archive
    < 2021-02-21 11:38:40.205 UTC > LOG:  restored log file "000000010000007E00000086" from archive
    < 2021-02-21 11:38:40.544 UTC > LOG:  restored log file "000000010000007E00000087" from archive
    < 2021-02-21 11:38:40.932 UTC > LOG:  restored log file "000000010000007E00000088" from archive
    < 2021-02-21 11:38:41.348 UTC > LOG:  restored log file "000000010000007E00000089" from archive
    < 2021-02-21 11:38:41.769 UTC > LOG:  restored log file "000000010000007E0000008A" from archive
    < 2021-02-21 11:38:42.199 UTC > LOG:  restored log file "000000010000007E0000008B" from archive
    < 2021-02-21 11:38:42.572 UTC > LOG:  restored log file "000000010000007E0000008C" from archive
    < 2021-02-21 11:38:43.069 UTC > LOG:  restored log file "000000010000007E0000008D" from archive
    < 2021-02-21 11:38:43.674 UTC > LOG:  restored log file "000000010000007E0000008E" from archive
    < 2021-02-21 11:38:44.096 UTC > LOG:  restored log file "000000010000007E0000008F" from archive
    < 2021-02-21 11:38:44.751 UTC > LOG:  restored log file "000000010000007E00000090" from archive
    < 2021-02-21 11:38:45.220 UTC > LOG:  restored log file "000000010000007E00000091" from archive
    < 2021-02-21 11:38:45.818 UTC > LOG:  restored log file "000000010000007E00000092" from archive
    < 2021-02-21 11:38:46.376 UTC > LOG:  restored log file "000000010000007E00000093" from archive
    < 2021-02-21 11:38:46.850 UTC > LOG:  restored log file "000000010000007E00000094" from archive
    < 2021-02-21 11:38:47.421 UTC > LOG:  restored log file "000000010000007E00000095" from archive
    < 2021-02-21 11:38:47.964 UTC > LOG:  restored log file "000000010000007E00000096" from archive
    < 2021-02-21 11:38:48.591 UTC > LOG:  restored log file "000000010000007E00000097" from archive
    < 2021-02-21 11:38:49.076 UTC > LOG:  restored log file "000000010000007E00000098" from archive
    < 2021-02-21 11:38:49.718 UTC > LOG:  restored log file "000000010000007E00000099" from archive
    < 2021-02-21 11:38:50.274 UTC > LOG:  restored log file "000000010000007E0000009A" from archive
    < 2021-02-21 11:38:50.771 UTC > LOG:  restored log file "000000010000007E0000009B" from archive
    < 2021-02-21 11:38:51.304 UTC > LOG:  restored log file "000000010000007E0000009C" from archive
    < 2021-02-21 11:38:51.769 UTC > LOG:  restored log file "000000010000007E0000009D" from archive
    < 2021-02-21 11:38:52.216 UTC > LOG:  restored log file "000000010000007E0000009E" from archive
    < 2021-02-21 11:38:52.628 UTC > LOG:  restored log file "000000010000007E0000009F" from archive
    < 2021-02-21 11:38:53.081 UTC > LOG:  restored log file "000000010000007E000000A0" from archive
    < 2021-02-21 11:38:53.541 UTC > LOG:  restored log file "000000010000007E000000A1" from archive
    < 2021-02-21 11:38:53.792 UTC > LOG:  redo done at 7E/A1FFE5E8
    < 2021-02-21 11:38:53.792 UTC > LOG:  last completed transaction was at log time 2021-02-21 11:38:13.924344+00
    < 2021-02-21 11:38:54.065 UTC > LOG:  restored log file "000000010000007E000000A1" from archive
    < 2021-02-21 11:38:54.110 UTC > LOG:  selected new timeline ID: 2
    < 2021-02-21 11:38:54.143 UTC > LOG:  archive recovery complete
    < 2021-02-21 11:38:54.381 UTC > LOG:  MultiXact member wraparound protections are now enabled
    < 2021-02-21 11:38:54.393 UTC > LOG:  autovacuum launcher started
    < 2021-02-21 11:38:54.393 UTC > LOG:  database system is ready to accept connections

</details>

---

As a result, even if this is an internal problem in PG, it will be useful to describe workaround for this problem in the FAQ.

**Comment by cmwshang** [comment]
@woblerr There are two things here that are curious: 1) the indication that recovery_target = 'immediate' helped, and 2) including the other database (indicating a dependency on that database) helped.  Have you had an opportunity to provide this information (or maybe just a link to this issue) to the postgres folks as @sfrost suggested?

**Comment by dwsteele** [comment]
We believe the problem here is a WAL record that PG won't apply on top of a zero page. There are a smaller number of logical WAL records (mostly btree related) that apply an operation rather than fixed binary data.

So limited WAL replay with `immediate` may help because that record never gets replayed. Including that database that needs to replay the record also helps.

@woblerr If you have an exact repro with data that would help us narrow it down.

**Comment by woblerr** [comment]
@cmwshang I opened bug in pgsql-bugs: [BUG #16894: PANIC: WAL contains references to invalid pages](https://www.postgresql.org/message-id/CABPPpF3mym72xDOyvvfBb4e-rV1Z2Qdip7qQSf2axdnuj-sv=Q@mail.gmail.com). If you can add some additional information , that would be great.

@dwsteele Unfortunately, I can't extract our repo with data, because it contains business information. It takes time for analysis to attempt depersonalization and to check problem reproducing.

**Comment by dwsteele** [comment]
I just had a chance to read through your message and I think it contains the information we need. Thank you! 

It points to an issue in Postgres, I think, because it should be possible to apply a heap record over a zeroed page. It looks like a full page write might be missing here.

I'll follow up on the bug with some more information about the implementation.

**Comment by dwsteele** [comment]
I spent some time looking through the code this morning. As I read it, WAL replay allows uninitialized (and missing) pages up to the point where consistency is achieved and after that flags uninitialized (or missing) pages as errors. It's pretty hard to argue with this logic and it addresses my concern about torn pages in the backups, i.e. torn/zero/missing pages will be repaired without complaint up to consistency.

So I believe that means Postgres is working as expected.

For pgBackRest selective restore there are two solutions:

- It appears `recovery_target = 'immediate'` works fine. This was verified in Anton's case.
- PG13 introduced the `ignore_invalid_pages` GUC (https://www.postgresql.org/message-id/E1iu6D8-0000tK-Cm%40gemulon.postgresql.org) which should allow replay to work past consistency. Note that the onus would be on the user to ensure that there were no invalid pages in the database(s) they are restoring.

The eventual goal is to filter the excluded databases out of the WAL before replay but we don't know when that functionality will be added.  For now we can:

- Document that replay may fail without `recovery_target = 'immediate'` on PG < 13
- Document that `ignore_invalid_pages` can be used on PG >= 13.
- Perhaps add `ignore_invalid_pages` automatically on PG >= 13?

**Comment by woblerr** [comment]
> So I believe that means Postgres is working as expected.

Great news, thank you!

>     * Perhaps add `ignore_invalid_pages` automatically on PG >= 13?

Probably, the correct step is to implement the idea of filtering the excluded databases out of the WAL before replay.

In a perfect world, it would be great if all exceptions were described in the documentation.
Since pgBackRest works with different versions of PostgreSQL, from user experience side, the same commands of pgBackRest should give the same results regardless of the version of PostgreSQL.
Otherwise, the deviations should be described in the documentation. As an example, #1314

**Comment by dwsteele** [comment]
> Probably, the correct step is to implement the idea of filtering the excluded databases out of the WAL before replay.

That's the goal, but we have a lot of code to write to get there (which has not been started) so I doubt it will happen anytime soon.

> In a perfect world, it would be great if all exceptions were described in the documentation.

We'll start by documenting the exceptions. I have created PR #1329 for this purpose.
