### ISSUE TITLE
WARN: environment contains invalid option 'version'

### ISSUE THREAD

**Issue by waldner** [pgbackrest/pgbackrest#799]
pgBackRest version 2.12 and 2.13, PostgreSQL version 11.3, 
Docker container, built from official postgres:11.3-alpine by adding pgbackrest (built from source).

Pgbackrest config:

```
[global]
repo1-cipher-pass=xxxxxxxxxxxx
repo1-cipher-type=aes-256-cbc
repo1-path=/home/pgbackrest
repo1-retention-full=2

[my-pg]
pg1-path=/var/lib/postgresql/data
pg1-socket-path=/var/run/postgresql
```
In postgresql.conf:

```
archive_command = 'pgbackrest --stanza=my-pg archive-push %p'
archive_mode = on
max_wal_senders = 3
wal_level = replica
```
Everything works perfectly fine, however the logs are full of messages like:

```
WARN: environment contains invalid option 'version'
```

which, AFAICT, comes from pgbackrest. No config file or pgbackrest invocation contain "version", so I'm not sure where the warning is coming from. 
The only thing I can see is that if I manually run `pgbackrest version` inside the container (which I never do anyway), then the bash environment will contain a special "_" variable whose value is "version" (or "last argument to the previous simple command executed  in  the  foreground" as documented), but I can't see how this could affect pgbackrest.

**Comment by cmwshang** [comment]
"environment" in the warning indicates pgBackRest is parsing the environment variables that begin with PGBACKREST_ so check your environment variables.

**Comment by waldner** [comment]
Doh! There is indeed this:

```
# echo $PGBACKREST_VERSION 
2.13
```
which comes from the Dockerfile and is used to install the right version of pgBackRest in the container. My fault. Thanks!

**Comment by cmwshang** [comment]
Glad we could help!
