### ISSUE TITLE
Cannot  install pgbackrest-2.15.1 on Amazon Instance

### ISSUE THREAD

**Issue by grayaii** [pgbackrest/pgbackrest#801]
1. pgBackRest version:
```
# rpm -i pgbackrest-2.15.1-1.rhel6.x86_64.rpm
 error: Failed dependencies:
	perl(:MODULE_COMPAT_5.10.1) is needed by pgbackrest-2.15.1-1.rhel6.x86_64
```

2. PostgreSQL version:
```
# yum list installed | grep postgresql
postgresql95.x86_64                9.5.16-1PGDG.rhel6
```
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
```
# uname -a
Linux ip-172-31-25-69 4.14.114-82.97.amzn1.x86_64 #1 SMP Sun Apr 28 07:27:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
4. Did you install pgBackRest from source or from a package?
From a package: pgbackrest-2.15.1-1.rhel6.x86_64.rpm

7. Describe the issue:
When I try to install pgbackrest-2.15.1-1.rhel6.x86_64.rpm, it says perl(:MODULE_COMPAT_5.10.1) is needed.  I have perl installed from Amazon, 5.16.3:
```
# perl  --version

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
```
If I try to install perl from the centos repo (not the amzn repo), it says it's already installed:
```
# yum install --disablerepo="*" --enablerepo=centos6 perl
Loaded plugins: priorities, update-motd, upgrade-helper
Package matching 4:perl-5.10.1-144.el6.x86_64 already installed. Checking for update.
Nothing to do
```
But if I  UNINSTALL perl, and then install it from the centos repo, I can install pgbackrest (unfortunately, that breaks other things on the box), so I'm at a loss of how to install pgbackrest on AWS.

**Comment by grayaii** [comment]
Note: this also happens if simply running:
```
# yum install pgbackrest
...
--> Finished Dependency Resolution
Error: Package: pgbackrest-2.15.1-1.rhel6.x86_64 (postgres-rhel6)
           Requires: perl(:MODULE_COMPAT_5.10.1)
```

**Comment by dwsteele** [comment]
These packages are intended for RHEL/CentOS so it's not too surprising they don't work.

Perl 5.16.3 is the version that ships with RHEL/CentOS 7 so you might be better off using that package version.  Note that we don't test with Amazon Linux so we don't know if it works, nor would we recommend it for production.
