### ISSUE TITLE
Log files have execution bit

### ISSUE THREAD

**Issue by dalbani** [pgbackrest/pgbackrest#804]
PgBackRest log files are created with the following permissions on disk: `0770`, i.e. with the execution bit.
Probably due to the code at https://github.com/pgbackrest/pgbackrest/blob/master/lib/pgBackRest/Common/Log.pm#L133.
Although not really problematic, I don't think it's appropriate to mark log files as executable, isn't it?
Using `0660` seems more logical to me — that's actually how they are opened a few lines below in the file mentioned previously.

**Comment by dwsteele** [comment]
These perms were actually coming out of the C code, but there's no question that the perms were inconsistent and the execute bits made no sense.  I decided using 750/640 in both Perl and C made the most sense.

Committed at 41b6795a3743.

**Comment by dalbani** [comment]
Excellent! Thanks for your reactivity.
