### ISSUE TITLE
process still running but doing nothing after failure

### ISSUE THREAD

**Issue by jwpit** [pgbackrest/pgbackrest#805]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.16

2. PostgreSQL version: 10

3. Operating system/version: Debian Stretch

4. Did you install pgBackRest from source or from a package? 

Debian Packages

5. Please attach the following as applicable:

7. Describe the issue:

The is still running after a failure but does nothing for hours after this error:
ERROR: [042]: unable to read line after 1830 second(s) from remote process on '10.101.0.6'

postgres@svr-file19:~$ cat /tmp/pgbackrest/adrpb-backup.lock
30316
postgres@svr-file19:~$ ps wax|grep 30316
15836 pts/7    S+     0:00 grep 30316
30316 ?        S      0:00 pgbackrest --type=full --stanza=adrpb backup

> 2019-08-15 20:04:01.476 P00   INFO: backup command begin 2.16: --no-archive-check --cmd-ssh=/usr/bin/ssh --compress --compress-level=1 --log-level-console=warn --log-level-file=info --pg1-host=10.101.0.6 --pg1-host-cmd=/usr/bin/pgbackrest --pg1-host-config=/etc/pgbackrest.conf --pg1-host-user=postgres --pg1-path=/data/adrPB --pg1-port=5434 --pg1-socket-path=/var/run/postgresql --process-max=16 --repo1-path=/adr/backup/svr_sql19/pgbackrest --repo1-retention-full=4 --stanza=adrpb --start-fast --stop-auto --type=full
> 2019-08-15 20:04:02.784 P00   INFO: execute non-exclusive pg_start_backup() with label "pgBackRest backup started at 2019-08-15 20:04:01": backup begins after the requested immediate checkpoint completes
> 2019-08-15 20:04:03.488 P00   INFO: backup start archive = 00000003000001340000000B, lsn = 134/B000028
> 2019-08-15 20:34:33.763 P00  ERROR: [042]: unable to read line after 1830 second(s) from remote process on '10.101.0.6'
> 
> -------------------PROCESS START-------------------
> 2019-08-16 11:45:01.614 P00   INFO: backup command begin 2.16: --no-archive-check --cmd-ssh=/usr/bin/ssh --compress --compress-level=1 --log-level-console=warn --log-level-file=info --pg1-host=10.101.0.6 --pg1-host-cmd=/usr/bin/pgbackrest --pg1-host-config=/etc/pgbackrest.conf --pg1-host-user=postgres --pg1-path=/data/adrPB --pg1-port=5434 --pg1-socket-path=/var/run/postgresql --process-max=16 --repo1-path=/adr/backup/svr_sql19/pgbackrest --repo1-retention-full=4 --stanza=adrpb --start-fast --stop-auto --type=full
> 2019-08-16 11:45:01.614 P00  ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/adrpb-backup.lock': Resource temporarily unavailable
>                                     HINT: is another pgBackRest process running?
> 2019-08-16 11:45:01.614 P00   INFO: backup command end: aborted with exception [050]
>

**Comment by jwpit** [comment]
The timeout Error seems to be introduced in Version 2.16.

**Comment by dwsteele** [comment]
Hmmm, not a lot to go on here.  Is this happening every time?  Does the remote process ever exit?

Would be useful to get output from `--log-level-file=trace` here.  Based on that we might want to get some output from the remote process so may as well add `--log-subprocess`.  It might also be beneficial to reduce `--process-max=1` to limit logging.

**Comment by jwpit** [comment]
Yes, it does happen on every full backup. I did not test diff backups.
WAL archiving is working.

**Comment by dwsteele** [comment]
Thanks for the logs.  It appears a leak in the new manifest generation code is causing the number of allocations in the memory context to balloon which causes *very* poor performance.  You may be able to get around this by increasing protocol-timeout, but obviously performance is going to be bad.

How many files do you have in PGDATA?

**Comment by jwpit** [comment]
find /data/adrPB |wc -l
252947

The Database size is 109GB.

**Comment by dwsteele** [comment]
This has been fixed at 9eaeb33c882b79a.  We are trying to decide whether to do a release for this fix.  Are you able to run on 2.15?

**Comment by jwpit** [comment]
Thanks David!
Yes, i'm fine with 2.15.

**Comment by dwsteele** [comment]
Thanks, Jens.  We may still do a release depending on how things go, but for now we'll direct users with this issue to 2.15.

**Comment by bradnicholson** [comment]
@dwsteele - has any decision been made on releasing this fix?

We have systems on 2.15 that need the `S3 RequestTimeTooSkewed` - but I'm hesitant to release 2.16 because of this issue.

**Comment by dwsteele** [comment]
@bradnicholson We are currently not planning to release -- we wanted to see if it impacted more than a few users.  Do you have clusters with more than 50K+ files?

**Comment by bradnicholson** [comment]
> Do you have clusters with more than 50K+ files?

I haven't dug, but I suspect we do, yes.

**Comment by dwsteele** [comment]
This would generally mean you have a cluster with 15K+ tables or is 50TB, or some combination of the two.

**Comment by bradnicholson** [comment]
Certainly not 50TB, but we might with 15K (customers are free to do what they want with their databases). 

I don't track the number of files across, so I'm not sure.  I certainly understand not taking a "we might have a problem" report like this in consideration for patching.

I was mainly just curious if it was coming.  Is there any ETA on when the next version will be released under normal release cadence?

**Comment by dwsteele** [comment]
Normal cadence would have the release on Sep 5.  We are also working on another issue regarding socket files in PGDATA that might tip the balance towards a release.

**Comment by bradnicholson** [comment]
Ah - Sept 5th is great (even if we did have potential exposures) - thanks!

**Comment by dwsteele** [comment]
@jwpit We looked at the new logs you sent and were able to reproduce the issue.  We have made an improvement in the speed of manifest build at 7d8068f27b6b695f96.  This should get you back to where you were with 2.15.
