### ISSUE TITLE
Documentation recommends to build as root user

### ISSUE THREAD

**Issue by laurenz** [pgbackrest/pgbackrest#806]
I don't know if that is the proper place for this complaint, but I don't know where else to file it.

[The documentation](https://pgbackrest.org/user-guide-centos7.html#build) recommends to build pgBackRest as `root`:

    (cd /root/pgbackrest-release-2.16/src && ./configure)
    sudo make -s -C /root/pgbackrest-release-2.16/src

Is that really required? Normally, it is considered an absolute no-go to run anything but `make install` as `root`.

**Comment by dwsteele** [comment]
You are correct, building as root is neither required nor best practice.

Fixed at 286a106ae4932ae821.
