### ISSUE TITLE
ERROR: [098]: invalid type for '/data/application/postgresql/data_db1/.s.PGSQL.5432'

### ISSUE THREAD

**Issue by rachid-casa** [pgbackrest/pgbackrest#810]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by rachid-casa** [comment]
We are using: pgbackrest-2.16-1
postgresql version: 10.10
CentOS Linux release 7.6.1810
pgBackRest installed from a package

pgbackrest.conf: See the attached files.

We have been running pgbackrest error free for weeks. Since 2 days we receive the following error message. We have made no changes to the config files. We receive the following error message for 2 days: See the attached logfile (log file pgbackrest.log)
The output with the check parameter is:
sudo -u postgres pgbackrest --stanza=data_db --log-level-console=info check
2019-08-22 09:57:15.887 P00   INFO: check command begin 2.16: --log-level-console=info --pg1-path=/data/application/postgresql/data_db1 --pg1-socket-path=/data/application/postgresql/data_db1 --repo1-path=/data/dumps/postgres/backup --stanza=data_db
ERROR [098]: : Database: 10 6654536264873672564 invalid type for '/data/application/postgresql/data_db1/.s.PGSQL.5432' at /loader/0x271b918/pgBackRest/Storage/Storage.pm line 403.
 at /loader/0x271b918/pgBackRest/Main.pm line 12.
	pgBackRest::Main::__ANON__('PGBRCLIB:98:storage/posix/storage.c:146:invalid type for \'/d...') called at /loader/0x271b918/pgBackRest/Storage/Storage.pm line 403
	pgBackRest::Storage::Storage::manifest(undef, '/data/application/postgresql/data_db1', 'HASH(0x30ead10)') called at /loader/0x271b918/pgBackRest/Manifest.pm line 819
	pgBackRest::Manifest::build(undef, 'pgBackRest::Storage::Storage=HASH(0x30ea638)', '/data/application/postgresql/data_db1', undef, 0, 0, 'HASH(0x30ea6b0)') called at /loader/0x271b918/pgBackRest/Check/Check.pm line 98
	eval {...} called at /loader/0x271b918/pgBackRest/Check/Check.pm line 105
	pgBackRest::Check::Check::process('pgBackRest::Check::Check=HASH(0x302d380)') called at /loader/0x271b918/pgBackRest/Main.pm line 118
	eval {...} called at /loader/0x271b918/pgBackRest/Main.pm line 238
	pgBackRest::Main::main('check') called at (eval 279) line 1
	eval '($iResult, $bErrorC, $strMessage) = pgBackRest::Main::main(\'check\')
;' called at (eval 279) line 0

2019-08-22 09:57:22.059 P00   INFO: check command end: aborted with exception [098]



[log file pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/3529212/log.file.pgbackrest.log)
[patroni parameters.log](https://github.com/pgbackrest/pgbackrest/files/3529237/patroni.parameters.log)
[config file pgbackrest.log](https://github.com/pgbackrest/pgbackrest/files/3529238/config.file.pgbackrest.log)

**Comment by rachid-casa** [comment]
The problem does not appear with the version pgbackrest-2.15.1.

**Comment by dwsteele** [comment]
I'm going to combine this with #803 since that's where it was first reported.  See that issue for details.
