### ISSUE TITLE
make pgbackrest error 

### ISSUE THREAD

**Issue by zhengyingshu** [pgbackrest/pgbackrest#811]
1. pgBackRest version:
2.16

2. PostgreSQL version:
pg11.2

3. Operating system
CentOS Linux release 7.6.1810 (Core)

make error like this ：
......
orage.o storage/driver/s3/fileRead.o storage/driver/s3/fileWrite.o storage/driver/s3/storage.o storage/fileRead.o storage/fileWrite.o storage/helper.o storage/storage.o main.o -lcrypto -lssl -lxml2 -lz `perl -MExtUtils::Embed -e ldopts` 
common/crypto/cipherBlock.o: In function `cipherBlockFree':
cipherBlock.c:(.text+0xa9): undefined reference to `EVP_CIPHER_CTX_reset'
common/crypto/common.o: In function `cryptoInit':
common.c:(.text+0x1c8): undefined reference to `OPENSSL_init_crypto'
common.c:(.text+0x1d4): undefined reference to `OPENSSL_init_crypto'
common.c:(.text+0x1e0): undefined reference to `OPENSSL_init_ssl'
common/crypto/hash.o: In function `cryptoHashFree':
hash.c:(.text+0x34): undefined reference to `EVP_MD_CTX_free'
common/crypto/hash.o: In function `cryptoHashNew':
hash.c:(.text+0x1f1): undefined reference to `EVP_MD_CTX_new'
common/crypto/hash.o: In function `cryptoHash':
hash.c:(.text+0x833): undefined reference to `EVP_MD_CTX_free'
common/io/tls/client.o: In function `asn1ToStr':
client.c:(.text+0x579): undefined reference to `ASN1_STRING_get0_data'
common/io/tls/client.o: In function `tlsClientHostVerify':
client.c:(.text+0x7fa): undefined reference to `OPENSSL_sk_num'
client.c:(.text+0x808): undefined reference to `OPENSSL_sk_value'
client.c:(.text+0x834): undefined reference to `OPENSSL_sk_free'
client.c:(.text+0x874): undefined reference to `OPENSSL_sk_free'
common/io/tls/client.o: In function `tlsClientNew':
client.c:(.text+0xa54): undefined reference to `TLS_method'
client.c:(.text+0xaa5): undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status
make: *** [pgbackrest] Error 1

**Comment by zhengyingshu** [comment]
> Are you running `make` on the same host you ran `configure` on? looks like you are missing `libcrypto`/`libssl` but `configure` should have caught that.


configure  caught nothing~~ , for example: 

[root@szydb src]# ./configure 
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... -std=gnu99
checking for perl_parse in -lperl... yes
checking for PQconnectdb in -lpq... yes
checking for EVP_get_digestbyname in -lcrypto... yes
checking for SSL_new in -lssl... yes
checking for xmlSaveToBuffer in -lxml2... yes
checking for deflate in -lz... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating build.auto.h
config.status: build.auto.h is unchanged

**Comment by dwsteele** [comment]
Hmm, not sure what is going on here.  If configure found libcrypto and libssl then make should have no problem.  I suspect there is a problem with your build environment.

**Comment by zhengyingshu** [comment]
> Hmm, not sure what is going on here. If configure found libcrypto and libssl then make should have no problem. I suspect there is a problem with your build environment.

tks, 
finally i used rpm to install the pgbackrest.
