### ISSUE TITLE
2.16 SSH login fails

### ISSUE THREAD

**Issue by oebeledrijfhout** [pgbackrest/pgbackrest#814]
After upgrade to 2.16, archiving started to fail with the below error. Downgrading to 2.15 solved the issue. 

pgBackRest version: `2.16`, PostgreSQL version: `11.5`, OS: `CentOS 7`, pgBackrest installed from `pgdg11` RPM repo

`pgbackrest.conf`:

```
[global]
repo1-path=/var/lib/pgbackrest/mnt
repo1-retention-full=1
process-max=2
log-level-console=info
log-level-file=detail
archive-async=y
#archive-push-queue-max=8GB
spool-path=/var/spool/pgbackrest
compress-level=0
backup-standby=y
delta=y
db-timeout=3600

[pgdb1]
pg1-host=10.100.130.200
pg1-path=/var/lib/pgsql/11/data
pg2-path=/var/lib/pgsql/11/data
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=10.100.130.200 port=5432 user=replication
recovery-option=recovery_target_timeline=latest
```

`postgresql.conf` settings:

```
archive_mode = on
archive_command = 'pgbackrest --stanza=pgdb1 archive-push %p
wal_level = replica
max_wal_senders = 20

```

`/var/log/pgbackrest/pgdb1-archive-push-async.log`:

```
-------------------PROCESS START-------------------
2019-08-26 10:15:38.119 P00   INFO: archive-push-async command begin 2.16: [/var/lib/pgsql/11/data/pg_wal] --compress-level=0 --db-timeout=3600 --log-level-console=off --log-level-file=detail --log-level-stderr=off --pg1-host=10.100.130.200 --pg1-path=/var/lib/pgsql/11/data --pg2-path=/var/lib/pgsql/11/data --process-max=2 --repo1-path=/var/lib/pgbackrest/mnt --spool-path=/var/spool/pgbackrest --stanza=pgdb1
2019-08-26 10:15:44.004 P00  ERROR: [125]: remote-0 process on '10.100.130.200' terminated unexpectedly [255]: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password,keyboard-interactive).
2019-08-26 10:15:44.004 P00   INFO: archive-push-async command end: aborted with exception [125]

```

`/var/log/secure`:

```

Aug 26 10:14:26 ph-sql-02 sshd[42447]: error: PAM: User not known to the underlying authentication module for illegal user (null) from ph-sql-02.prod.ams.i.rdmedia.com
Aug 26 10:14:26 ph-sql-02 sshd[42447]: Failed keyboard-interactive/pam for invalid user (null) from 10.100.130.110 port 42370 ssh2
Aug 26 10:14:26 ph-sql-02 sshd[42447]: Connection closed by 10.100.130.110 port 42370 [preauth]

````

**Comment by oebeledrijfhout** [comment]
Yes there are multiple systems involved, a master and a standby server. The IP is the floating ip that is active on the current master, the backup is run from the standby. The repo is mounted via NFS (on both servers).

**Comment by dwsteele** [comment]
Could you provide the pgbackrest config files for both your servers and note which is which?

Just glancing at the one file, I can't see how it would work.  Maybe seeing both will help.

**Comment by oebeledrijfhout** [comment]
So in this cluster there are two servers, `ph-sql-01` and `ph-sql-02`. Currently `ph-sql-02` is the master Backups are taken from the standby, `ph-sql-01`. The pgBackrest config files on both servers are identical.

`pgbackrest.conf` on `ph-sql-01`:

```
[global]
repo1-path=/var/lib/pgbackrest/mnt
repo1-retention-full=1
process-max=2
log-level-console=info
log-level-file=detail
archive-async=y
#archive-push-queue-max=8GB
spool-path=/var/spool/pgbackrest
compress-level=0
backup-standby=y
delta=y
db-timeout=3600

[pgdb1]
pg1-host=10.100.130.200
pg1-path=/var/lib/pgsql/11/data
pg2-path=/var/lib/pgsql/11/data
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=10.100.130.200 port=5432 user=replication
recovery-option=recovery_target_timeline=latest
```

`pgbackrest.conf` on `ph-sql-02`:

```
[global]
repo1-path=/var/lib/pgbackrest/mnt
repo1-retention-full=1
process-max=2
log-level-console=info
log-level-file=detail
archive-async=y
#archive-push-queue-max=8GB
spool-path=/var/spool/pgbackrest
compress-level=0
backup-standby=y
delta=y
db-timeout=3600

[pgdb1]
pg1-host=10.100.130.200
pg1-path=/var/lib/pgsql/11/data
pg2-path=/var/lib/pgsql/11/data
recovery-option=standby_mode=on
recovery-option=primary_conninfo=host=10.100.130.200 port=5432 user=replication
recovery-option=recovery_target_timeline=latest
```

**Comment by cmwshang** [comment]
Due to a regression during the c code migration, the configuration you have would appear to work until 2.16 (although the check command should have failed). Having your repository on a standby server is a very fragile configuration that we do not recommend because all pgbackrest configuration files on the database host systems should be symmetrical in order to seamlessly handle failovers. 
If you insist on moving forward with such a configuration, then you must remove pg2-path and pg1-host from pgbackrest.conf on your postgres master (ph-sql-02) and then in your other configuration file, you must change pg1-host to be pg2-host.  But remember, on any kind of failure, the asymmetrical configuration files will be just the start of your problems.
