### ISSUE TITLE
Latest backup is chosen, even if it is newer than target time

### ISSUE THREAD

**Issue by jpuris** [pgbackrest/pgbackrest#817]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.16

2. PostgreSQL version:
9.4.24

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 18.04.3 LTS

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

**_pgbackrest.conf_**
```ini
[global]
process-max=8

archive-async=y
spool-path=/data/db/pgbackrest_spool
archive-get-queue-max=10G
archive-push-queue-max=10GB

log-level-file=debug
log-level-console=info

start-fast=y

repo1-cipher-type=aes-256-cbc

repo1-retention-diff=2
repo1-retention-full=2

pg1-port=5431

[osl1-dev:archive-push]
compress-level=3

[osl1-dev]
pg1-port=5431
repo1-path=/data/pgbackrest
repo1-cipher-pass=<redacted>

pg1-path=/data/db/data
```

pgbackrest info
```
$ pgbackrest --stanza=osl1-dev info
stanza: osl1-dev
    status: ok
    cipher: aes-256-cbc

    db (current)
        wal archive min/max (9.4-1): 00000026000000500000007B/0000002700000056000000D1

        full backup: 20190825-040029F
            timestamp start/stop: 2019-08-25 04:00:29 / 2019-08-25 04:03:20
            wal start/stop: 00000026000000500000007B / 00000026000000500000007B
            database size: 22GB, backup size: 22GB
            repository size: 1.2GB, repository backup size: 1.2GB

        full backup: 20190901-040029F
            timestamp start/stop: 2019-09-01 04:00:29 / 2019-09-01 04:03:19
            wal start/stop: 0000002600000051000000DA / 0000002600000051000000DA
            database size: 22GB, backup size: 22GB
            repository size: 1.2GB, repository backup size: 1.2GB

        diff backup: 20190901-040029F_20190903-030029D
            timestamp start/stop: 2019-09-03 03:00:29 / 2019-09-03 03:00:45
            wal start/stop: 00000026000000520000003C / 00000026000000520000003C
            database size: 22GB, backup size: 47.7MB
            repository size: 1.2GB, repository backup size: 5.6MB
            backup reference list: 20190901-040029F

        diff backup: 20190901-040029F_20190904-030029D
            timestamp start/stop: 2019-09-04 03:00:29 / 2019-09-04 03:03:35
            wal start/stop: 0000002700000056000000B8 / 0000002700000056000000B8
            database size: 22GB, backup size: 20GB
            repository size: 1.2GB, repository backup size: 911MB
            backup reference list: 20190901-040029F
```

Without `--set` opt
```
$ pgbackrest --stanza=osl1-dev --target-action=promote --type=time --target="2019-09-03 23:00:00 CET" restore
2019-09-04 14:39:51.709 P00   INFO: restore command begin 2.16: --log-level-console=info --log-level-file=debug --pg1-path=/data/db/data --process-max=8 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/data/pgbackrest --stanza=osl1-dev --target="2019-09-03 23:00:00 CET" --target-action=promote --type=time
2019-09-04 14:39:51.843 P00   INFO: restore backup set 20190901-040029F_20190904-030029D
2019-09-04 14:40:19.697 P05   INFO: restore file /data/db/data/base/8761571/8764080.8 (1GB, 4%) checksum 494e33fcc9a2bc2309f7506c00f511803abcbf7f
[..]
```
With `--set` opt
```
$ pgbackrest --stanza=osl1-dev --set=20190901-040029F_20190903-030029D --target-action=promote --type=time --target="2019-09-04 00:00:00 CET" restore
2019-09-04 14:49:39.394 P00   INFO: restore command begin 2.16: --log-level-console=info --log-level-file=debug --pg1-path=/data/db/data --process-max=8 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/data/pgbackrest --set=20190901-040029F_20190903-030029D --stanza=osl1-dev --target="2019-09-04 00:00:00 CET" --target-action=promote --type=time
2019-09-04 14:49:39.540 P00   INFO: restore backup set 20190901-040029F_20190903-030029D
2019-09-04 14:49:40.564 P03   INFO: restore file /data/db/data/base/8754123/8756039 (2MB, 99%) checksum 52140244f94283a404d883f021be58765a3987df
[..]
```

7. Describe the issue:

When running PITR with `--type=time --target="2019-09-03 23:00:00 CET"`, I'd expect the 
restore to grab the latest backup before the timestamp, not the actual latest. This behaviour can be observed in log output ```Without `--set` opt```.
When this happens, the `--target=` is ignored by postgres, because this recovery setting is invalid and the WALs are restored to latest available, then promote happens.

It does work as expected, when `--set` has been provided, and can be observed in ```With `--set` opt``` output. The correct differential backup is used and postgresql then will honor the PITR target TS.

Is this expected behaviour or is this a bug ?

**Comment by dwsteele** [comment]
This is expected behavior because pgBackRest does not take the target into account when choosing a backup.  Partly we didn't want to deal with the date parsing that would be required in Perl.  But mostly we never got the chance to code it.

The `restore` command is being migrated right now and we'd be open to a patch when that is done.

**Comment by jpuris** [comment]
I see. Thanks for the feedback @dwsteele.
It would be a superb improvement for pgBackRest to be smart about `--type=time --target` opt.

It would make automatic recoveries much more straight forward.
Right now, we'd need to parse the `pgbackrest info`, find the most fresh viable backup, and finally include it in the restore cmd to achieve the desired PITR.

**Comment by sfrost** [comment]
Yes, it's our intent to do a few neat things here, once the migration to C is done- we want to parse the WAL and find all the restore points, for example, so that we can be smart when a user picks a restore point too, and, yes, we want to add in logic to know exactly which backup to use when a user picks a time to restore to as well.  We might also get smart about transaction IDs but that could be more complicated.  In any case, we're definitely aware of this being something that folks would like to see, but right now we need to finish the C migration and adding in a bunch of intelligence around handling timezones and such isn't gonna happen right away. ;)  As David says, patches welcome...

**Comment by sfrost** [comment]
oh, also note that there's a JSON format for info results, which is what we'd recommend you use, so you're not parsing text...

**Comment by jpuris** [comment]
This is great news. Will be looking for this change :) until then, we'll manage.
