### ISSUE TITLE
Is there a way to show databases in the backup taken?

### ISSUE THREAD

**Issue by ejberdecia** [pgbackrest/pgbackrest#818]
Is there a way to show/display the databases backed up from the cluster at the time a given backup was taken?

If not, can this be an added feature?

**Comment by dwsteele** [comment]
Currently there is no way to do this except to look at the `[db]` section in `backup.manifest` located in the backup directory.

We'll add this to issue #774.

**Comment by dwsteele** [comment]
Committed at f96c54c4ba0e5 in #843.  How would you like your name to appear in the release notes?

**Comment by ejberdecia** [comment]
ejberdecia

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 30, 2019 at 3:39 PM, David Steele<notifications@github.com> wrote:   
Committed at f96c54c in #843. How would you like your name to appear in the release notes?
