### ISSUE TITLE
Backup cmd is aggresivelly using swap in 2.16

### ISSUE THREAD

**Issue by jpuris** [pgbackrest/pgbackrest#822]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.16

2. PostgreSQL version:
9.4.24

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
All involved servers run Ubuntu 18.04.3 LTS

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

_PostrgeSQL_
```
archive_command = 'pgbackrest --stanza=osl1-dev archive-push %p && pgbackrest --stanza=osl1-dev_s3 archive-push %p'
archive_mode = 'on'
archive_timeout = '1800s'
```
_pgbackrest.conf_ (node)
```ini
[global]
process-max=8

log-level-file=debug
log-level-console=info

start-fast=y

repo1-cipher-type=aes-256-cbc

repo1-retention-diff=2
repo1-retention-full=2

[osl1-dev:archive-push]
compress-level=3

[osl1-dev]
pg1-port=5431
repo1-path=/data/pgbackrest
repo1-cipher-pass=<redacted>

pg1-path=/data/db/data

[osl1-dev_s3:archive-push]
compress-level=3

[osl1-dev_s3]
pg1-port=5431
repo1-type=s3
repo1-s3-endpoint=s3.eu-central-1.amazonaws.com
repo1-s3-bucket=backrest
repo1-path=/
repo1-s3-key=<redacted>
repo1-s3-key-secret=<redacted>
repo1-s3-region=eu-central-1

repo1-cipher-pass=<redacted>

pg1-path=/data/db/data
```
_pgbackrest.conf_ (backup server)
```ini
[global]
process-max=8

log-level-file=debug
log-level-console=info

start-fast=y

repo1-cipher-type=aes-256-cbc

repo1-retention-diff=7
repo1-retention-full=4

backup-standby=y

[osl1-dev]
repo1-path=/data/pgbackrest

repo1-cipher-pass=<redacted>

pg1-host=host1.domain.com
pg1-port=5431
pg1-path=/data/db/data
pg2-host=host2.domain.com
pg2-port=5431
pg2-path=/data/db/data
pg3-host=host3.domain.com
pg3-path=/data/db/data
pg3-port=5431

repo1-retention-diff=2
repo1-retention-full=2

[osl1-dev_s3]
repo1-type=s3
repo1-s3-endpoint=s3.eu-central-1.amazonaws.com
repo1-s3-bucket=backrest
repo1-path=/
repo1-s3-key=<redacted>
repo1-s3-key-secret=<redacted>
repo1-s3-region=eu-central-1

repo1-cipher-pass=<redacted>

pg1-host=host1.domain.com
pg1-path=/data/db/data
pg1-port=5431
pg2-host=host2.domain.com
pg2-path=/data/db/data
pg2-port=5431
pg3-host=host2.domain.com
pg3-path=/data/db/data
pg3-port=5431

repo1-retention-diff=2
repo1-retention-full=2
```

Log from backup server:
```
Sep 04 03:00:29 ms-vg-backrest-01 systemd[1]: Started pgBackRest differential backup for stanza: osl1-dev.
Sep 04 03:00:29 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:00:29.619 P00   INFO: backup command begin 2.16: --backup-standby --log-level-console=info --log-level-file=debug --pg1-host=host1.domain.com --pg2-host=host2.domain.com --pg3-host=host3.domain.com --pg1-path=/data/db/data --pg2-path=/data/db/data --pg3-path=/data/db/data --pg1-port=5431 --pg2-port=5431 --pg3-port=5431 --process-max=8 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/data/pgbackrest --repo1-retention-diff=2 --repo1-retention-full=2 --stanza=osl1-dev --start-fast --type=diff
Sep 04 03:00:40 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:00:40.459 P00   INFO: last backup label = 20190901-040029F, version = 2.16
Sep 04 03:00:40 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:00:40.879 P00   INFO: execute exclusive pg_start_backup() with label "pgBackRest backup started at 2019-09-04 03:00:29": backup begins after the requested immediate checkpoint completes
Sep 04 03:00:41 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:00:41.282 P00   INFO: backup start archive = 0000002700000056000000B8, lsn = 56/B8000028
Sep 04 03:00:41 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:00:41.489 P00   INFO: wait for replay on the standby to reach 56/B8000028
Sep 04 03:00:41 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:00:41.794 P00   INFO: replay on the standby reached 56/B8000100
Sep 04 03:00:41 ms-vg-backrest-01 pgbackrest[89160]: WARN: a timeline switch has occurred since the last backup, enabling delta checksum
Sep 04 03:00:44 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:00:44.858 P01   INFO: backup file host1.domain.com:/data/db/data/global/pg_control (8KB, 0%) checksum f69d632eca1305f5d1ed1aac6a1d6275eb80745c
Sep 04 03:00:44 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:00:44.925 P01   INFO: backup file host1.domain.com:/data/db/data/postgresql.conf.backup (751B, 0%) checksum 59c287f735dbd204f42a55d3dbb3d36038ff9629
[..]
Sep 04 03:03:31 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:03:31.965 P00   INFO: diff backup size = 22GB
Sep 04 03:03:31 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:03:31.966 P00   INFO: execute exclusive pg_stop_backup() and wait for all WAL segments to archive
Sep 04 03:03:35 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:03:35.274 P00   INFO: backup stop archive = 0000002700000056000000B8, lsn = 56/B8000128
Sep 04 03:03:35 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:03:35.604 P00   INFO: new backup label = 20190901-040029F_20190904-030029D
Sep 04 03:03:35 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:03:35.701 P00   INFO: backup command end: completed successfully (186083ms)
Sep 04 03:03:35 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:03:35.701 P00   INFO: expire command begin
Sep 04 03:03:35 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:03:35.736 P00   INFO: expire diff backup 20190901-040029F_20190902-030030D
Sep 04 03:03:35 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:03:35.746 P00   INFO: remove expired backup 20190901-040029F_20190902-030030D
Sep 04 03:03:36 ms-vg-backrest-01 pgbackrest[89160]: 2019-09-04 03:03:36.228 P00   INFO: expire command end: completed successfully (527ms)
Sep 05 03:00:29 ms-vg-backrest-01 systemd[1]: Started pgBackRest differential backup for stanza: osl1-dev.
```

7. Describe the issue:

When running backup from the backup server, secondary is chosen. Backups run is successful, however the swap space on replica occasionally is exhausted, while there is plenty of available memory space on the host.

The problem does not manifest every time.. sometime the swap usage is tiny, but other times it is completely exhausted.

The backup schedule is as follows
- diff every night, except sundays
- full every sunday night
First it is local backup done (no _s3), then half hour later, the remote backup is done (_s3).

Screenshot of the swap consumption from Thu to Sat differential backups on replica
https://dl.dropboxusercontent.com/s%2Fba21tmsa9h8gcx3%2FPrometheus%2520Time%2520Series%2520Collection%2520and%2520Processing%2520Server%25202019-09-09%252011-43-18%25281%2529.png

_Observations_
- The replica in question has only 4 cores (pgbackrest process count is set to 8)
- This also happens when running on primary node itself locally or with the backup server
- When process count is set to 3 (4 cores), it happens much less, but backup process is slower
- When run on primary locally, it "seems" the swap usage is much less. But it could be it is not reproducable, _as sometimes this does not happen_
- I have not checked it without compression

This started to happen only recently, thus far we have not managed to pinpoint the change done. There is no evidence to link it to upgrade of 2.16 from 2.15 however.

I realise this may be difficult to reproduce, but this is quite a problem for us.

**Comment by dwsteele** [comment]
The C code uses more buffers than the Perl code did so memory use will be higher.  I have been meaning to test smaller buffer sizes in C because I suspect it would handle them better than the Perl code did but I haven't had the chance to benchmark it yet.

Try setting `buffer-size=1mb` and see how that goes.  If you don't see any performance regressions you can try smaller values and see how it goes.  We would be interested in the results.

**Comment by jpuris** [comment]
Still happens with buffer-size.. the odd thing is, I can not reproduce this on SSD drives. It could be coincidence in needs much more testing.

I will add this opt to all backups and report back, if the situation has improved. Should be very obvious, if it does, as when this happens, all swap is consumed pretty much.

**Comment by jpuris** [comment]
Unfortunately this has not helped. Saturdays differential backup has nuked all swap again on the replica node.
I can not reproduce this behaviour when running the backup directly on primary node, however.

When inspecting contents of swap space, it seems it is postgres server is occupying almost all of it and afterwards running `./postgresqltuner.pl`, its clear the server is misconfigured
```[INFO]    max memory+effective_cache_size is 361.38% of total RAM```
ouch..

While I'm not 100% convinced this is the problem, I will report back, if this is solved when cluster has been reconfigured.

This does not seem to happen as frequently in cluster identically misconfigured, the only difference seems, it is using ssd backed storage.

**Comment by dwsteele** [comment]
During the backup pgBackRest will use a lot of Linux block cache which will put it in contention with PostgreSQL for that resource.  I can't see how that would affect execution plans, but I suppose the kernel could decide to swap Postgres allocations to disk if the pressure on block cache is high enough.

**Comment by jpuris** [comment]
I've done some changes as to how PG uses memory and pgbackrest, seems to not impact swap usage.

_Following changes were done_
- increase huge pages to 4 GB in /etc/sysctl.conf and disabled overcommit
```
vm.overcommit_memory=2
vm.nr_hugepages=2195
```
- Reduced overall postgres memory footprint, some settings were grossly bad
- Enabled postgres usage of memory huge pages

While this may be not exactly root cause fix, but it has most definately has eliminated the problem in my setup.

**Comment by jpuris** [comment]
Still no problems observed. I believe the problem was caused by PG memory footprint. Closing.

**Comment by dwsteele** [comment]
Glad to hear it.  Thanks for the investigation!
