### ISSUE TITLE
Feature Request: new s3 setting s3-path

### ISSUE THREAD

**Issue by gmr** [pgbackrest/pgbackrest#832]
I'm currently using pgBackRest version: 2.16

As I'm rolling out pgBackRest, I'm running into an issue where I'd like to have my s3 backups sent to a different path than the local repo path.

ie, on the server I want to use `/var/lib/pgbackrest`, but in the s3 bucket, I'd like to use `/postgres/[STANZA-NAME]/[FQDN]/` (example `postgres/main/db1.internal-domain`)

For now I am creating a directory tree at `postgres/[STANZA-NAME]/` and am sym-linking the `FQDN` to `/var/lib/pgbackrest` but it would be nice to not have that in my filesystem.

If doing so, my config might look like:

```ini
[main]
pg1-path=/var/lib/postgresql/11/main

[global]
repo1-path=/var/lib/pgbackrest
repo1-type=s3
repo1-s3-bucket=my-bucket
repo1-s3-path=postgres/main/postgres/main/db1.internal-domain
repo1-s3-endpoint=s3.us-east-1.amazonaws.com
repo1-s3-region=us-east-1
```

And files would make it to `s3://my-bucket/postgres/main/postgres/main/db1.internal-domain`

Thanks for the nice tool/project :)

**Comment by gmr** [comment]
Err my-bad, I started with a file based backup and switched to s3 and assumed the errors I was receiving was due to the need for parity in the path, not that I needed to delete and recreate the stanza.

**Comment by dwsteele** [comment]
Glad you got it working.  And thanks for the compliment!
