### ISSUE TITLE
Error when build with v2.16 in rhel6(CentOS 6.8) 

### ISSUE THREAD

**Issue by bylee5** [pgbackrest/pgbackrest#836]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: v2.16

2. PostgreSQL version: v10

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: CentOS 6.8

4. Did you install pgBackRest from source or from a package? source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
In v2.15.1 the source build works fine.

> [agens@42e220286418 src]$ git checkout -b 2.15.1 release/2.15.1
Switched to a new branch '2.15.1'
[agens@42e220286418 src]$ ./configure --prefix=$(pwd)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... -std=gnu99
checking for perl_parse in -lperl... yes
checking for EVP_get_digestbyname in -lcrypto... yes
checking for SSL_new in -lssl... yes
checking for xmlSaveToBuffer in -lxml2... yes
checking for deflate in -lz... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating build.auto.h
config.status: build.auto.h is unchanged

In v2.16 version, the source build does not work. The error details are as follows:

> [agens@42e220286418 pgbackrest]$ git checkout -b 2.16 release/2.16
Switched to a new branch '2.16'
[agens@42e220286418 src]$ ./configure --prefix=$(pwd)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... -std=gnu99
checking for perl_parse in -lperl... yes
checking for PQconnectdb in -lpq... no
configure: error: library 'pq' is required

Can't install v2.16 version on CentOS 6.8?

**Comment by dwsteele** [comment]
Did you follow the build instructions at: https://pgbackrest.org/user-guide-centos6.html?

**Comment by bylee5** [comment]
@dwsteele Thank you.
After installing the postgresql-devel library, the build works well.
