### ISSUE TITLE
What is the archiveId?

### ISSUE THREAD

**Issue by fluca1978** [pgbackrest/pgbackrest#837]
Every version of pgbackrest has the notion of archiveId which is displayed as 10-1 or 11-1.
What is the meaning of such string (i.e., what do the numbers refer to)?
Example:
```
% pgbackrest info
stanza: miguel
    status: ok
    cipher: none

    db (current)
        wal archive min/max (11-1): 0000000500000213000000D6/0000000600000213000000DA
...
```

Near `wal archive` there's `11-1`.

Thanks

**Comment by cmwshang** [comment]
archiveId is a quick reference that is used in archiving and backups to refer to the database via an id. Each time the database is upgraded (say you upgrade 9.6 to 10) this id increments (9.6-1, 10-2).

**Comment by fluca1978** [comment]
@cmwshang thanks, if I get it right from <https://github.com/pgbackrest/pgbackrest/blob/master/src/info/infoPg.c#L397> it is the major version of the target database a kind of historical index, that from what you say is the number of times it has been upgraded.

So it seems the `archiveId` is only an information about the archive source, not any reference to the repository or the backup set itself.

**Comment by dwsteele** [comment]
> So it seems the archiveId is only an information about the archive source, not any reference to the repository or the backup set itself.

Yes.  The backups contains the archive-id so we can find their archive, and the archive-id is also used during archive-push/get operations to find the correct archive location.
