### ISSUE TITLE
Dry run for expiration

### ISSUE THREAD

**Issue by marco44** [pgbackrest/pgbackrest#838]
We're having a repository where we have never expired, and would like to do a dry run expiration before doing the real expiration.

A dry-run option for expire would be great.

**Comment by dwsteele** [comment]
We agree.  Not sure when we'll be able to get to that, though.  That code is entirely migrated to C so you are welcome to submit a patch if you have time before we do.

**Comment by dwsteele** [comment]
This was committed at 2fa69af for pgBackRest 2.25. I forgot to add you to the release notes in that commit but amended at 2ec379fa40.
