### ISSUE TITLE
Corrupt WAL

### ISSUE THREAD

**Issue by jamessewell** [pgbackrest/pgbackrest#842]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.05

2. PostgreSQL version: 9.6 

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: OEL 7.4

4. Did you install pgBackRest from source or from a package? RPM

I have a corrupt WAL in my WAL archive:

```
[napback@rprnab001 tmp]$ gunzip 000000340003406C0000004C-d006890f13dcc7c0ac980385752ea3172595dc4a.gz

gzip: 000000340003406C0000004C-d006890f13dcc7c0ac980385752ea3172595dc4a.gz: unexpected end of file
```

Backrest does actually manage to extract this WAL when I request it - but I end up with an 8MB WAL which obviously is of no use.

Has this been seen before?

**Comment by dwsteele** [comment]
This was fixed in February for 2.11 (https://pgbackrest.org/release.html#2.11) in d211c2b8b51ae5b7.

**Comment by jamessewell** [comment]
OK. There is no fix correct? I’m the data is just lost?

**Comment by dwsteele** [comment]
Correct, it is just lost.
