### ISSUE TITLE
[pgbackrest] <defunct> with  archive-async=y

### ISSUE THREAD

**Issue by clauzio** [pgbackrest/pgbackrest#846]
[Please]
[dbectgeo_w0-expire.log](https://github.com/pgbackrest/pgbackrest/files/3637219/dbectgeo_w0-expire.log)
[dbectgeo_w0-backup.log](https://github.com/pgbackrest/pgbackrest/files/3637220/dbectgeo_w0-backup.log)
[postgresql-2019-09-20_105333.log](https://github.com/pgbackrest/pgbackrest/files/3637221/postgresql-2019-09-20_105333.log)
[pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/3637237/pgbackrest.txt)

 provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.17

2. PostgreSQL version: PostgreSQL 11.4 (Debian 11.4-1) on sparc64-unknown-linux-gnu, compiled by gcc (Debian 8.3.0-7) 8.3.0, 64-bit OR PostgreSQL 11.3 (Debian 11.3-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Debian GNU/Linux bullseye/sid [Linux ? 4.19.0-5-sparc64-smp #1 SMP Debian 4.19.37-6 (2019-07-18) sparc64 GNU/Linux] OR Debian GNU/Linux 9.9 (stretch) [Linux ? 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux]

4. Did you install pgBackRest from source or from a package?
Source

7. Describe the issue:
After param archive-async=y the pgbackrest --stanza=qweqwe_w0 archive-push will be '[pgbackrest] <defunct>'. 
postgres 141907 204950  0 14:05 ?        00:00:00 sh -c pgbackrest --stanza=qweqwe_w0 archive-push pg_wal/000000010000017400000047
postgres 141908 141907  0 14:05 ?        00:00:00 pgbackrest --stanza=qweqwe_w0 archive-push pg_wal/000000010000017400000047
postgres 141909 141908  0 14:05 ?        00:00:00 [pgbackrest] <defunct>

With archive-async=n (default) the backup is ok.

**Comment by cmwshang** [comment]
There are some SSL issues in the postgres log and a permissions issue on /tmp/pgbackrest in the expire log but there is no indication of the stanza 'qweqwe_w0' nor the [pgbackrest] as you mention in the problem description. Could you please provide the data relevant to your problem description?

**Comment by dwsteele** [comment]
We have fixed several bugs in this command since 2.15.  Can you retest with 2.21 and let us know if you are still seeing issues?
