### ISSUE TITLE
ERROR: [046]: unexpected control version = 1201 and catalog version = 201909212

### ISSUE THREAD

**Issue by seadba** [pgbackrest/pgbackrest#850]
hi - testing with v12 pgbackrest 2.17 - is this expected condition with pre-GA 12 release?

ERROR: [046]: unexpected control version = 1201 and catalog version = 201909212

thanks

**Comment by dwsteele** [comment]
PG12 support should be out tomorrow.  There were extensive changes to recovery and we wanted to wait until the restore command was migrated to C so we would not need to code the changes twice.

**Comment by seadba** [comment]
excellent - thanks very much - great tool
