### ISSUE TITLE
ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/demo-archive.lock': Permission denied

### ISSUE THREAD

**Issue by yeswithae** [pgbackrest/pgbackrest#852]
1. pgBackRest version:2.16

2. PostgreSQL version:11.5

3. Operating system/version -  please specify each:linux(Ubuntu 11.5-1.pgdg18.04+1)

4. Did you install pgBackRest from source or from a package
  Source is from Github
 [demo-stanza-create.log](https://github.com/pgbackrest/pgbackrest/files/3686333/demo-stanza-                                        create.log)

5.Describe the issue:
  I am trying to create stanza for loading data incrementally,("https://access.crunchydata./documentation/pgbackrest/2.00/pdf/backrest.pdf")but is it showing the following error:
 
 

>  ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/demo-archive.lock': Permission  denied
>    HINT: does the user running pgBackrest have permissions on the '/tmp/pgbackrest/demo- archive.lock' file?
>  2019-10-03 16:54:29.496 P00   INFO: stanza-create command end: aborted with exception [050]
>

**Comment by dwsteele** [comment]
```
HINT: does the user running pgBackrest have permissions on the '/tmp/pgbackrest/demo- archive.lock' file?
```
This indicates that the user you are running pgbackrest as does not have permssions on the `/tmp/pgbackrest` directory or the `/tmp/pgbackrest/demo- archive.lock` file.  This can happen if you run pgbackrest as another user first.  Correct the permissions and you should be fine.

**Comment by yeswithae** [comment]
I have enabled the permissions,know again if i run the command to create stanza it is raising the error
like:

> 

> ERROR: [058]: version '9.6' and path '/var/lib/postgresql/9.6/main' queried from cluster do not match version '11' and '/var/lib/postgresql/11/demo' read from '/var/lib/postgresql/11/demo/global/pg_control'

       HINT: the pg1-path and pg1-port settings likely reference different clusters
2019-10-07 19:56:30.647 P00   INFO: stanza-create command end: aborted with exception [058]

**Comment by cmwshang** [comment]
@yeswithae This is checking your pgbackrest.conf against the database and clearly it is not configured properly because you have a mismatch.

Please see the user-guide (https://pgbackrest.org/user-guide.html) to familiarize yourself with how to setup and configure a system. You mentioned crunchydata documentation, but I don't recognize your moniker so if you need internal assistance, please feel free to ping us on Slack.

**Comment by yeswithae** [comment]
I have tried to configure still issue persists can you please suggest the way,how to configure to make it work...? how can i make the database and cluster on to be same version?

**Comment by cmwshang** [comment]
You did not provide any of the requested documentation when opening a ticket (see below) so I can only tell you that the error is saying that pgBackRest is querying the postgresql database cluster you have configured on pg1-port (if that is not set in pgbackrest.conf, then it will default to 5432). The database is responding that it is version 9.6 and it is located at /var/lib/postgresql/9.6/main. So your pgbackrest.conf has pg1-path set (and maybe pg1-port, but I cannot know without seeing or knowing anything about your configuration) and that is set to /var/lib/postgresql/11/demo but that is not the cluster the port is set to.

----------------------------------------------------------------
Please provide the following information when **submitting** an issue (feature requests or general comments can skip this):

1. pgBackRest version:

2. PostgreSQL version:

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
