### ISSUE TITLE
S3 EOF readding HTTP content

### ISSUE THREAD

**Issue by garthgoodson** [pgbackrest/pgbackrest#855]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.17

2. PostgreSQL version:
11.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Linux ip-XXXX-aws #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

4. Did you install pgBackRest from source or from a package?
Source

5. Please attach the following as applicable:
[production1]
pg1-path=/data/pgdata/postgres

[global]
backup-standby=y
process-max=16
repo1-path=/pgbackup
repo1-cipher-type=none
repo1-retention-full=2
repo1-s3-bucket=XXXX
repo1-s3-endpoint=s3.XXXX.amazonaws.com
repo1-s3-key=XXXX
repo1-s3-key-secret=XXXXX
repo1-s3-region=us-XXXX
repo1-type=s3
repo1-s3-verify-ssl=n
start-fast=y
stop-auto=y
log-path=/data/logs/pgbackrest

[global:archive-push]
compress-level=3

7. Describe the issue:
Happens multiple times during restore.  If I restart using --delta it picks up from where it left off.  Seems like a transient error, might be good to add a retry.

Restore command:

INFO: restore command begin 2.17: --delta --log-path=/data/logs/pgbackrest --pg1-path=/data/pgdata/postgres --process-max=16 --repo1-cipher-type=none --repo1-path=/pgbackup --repo1-s3-bucket=XXXX --repo1-s3-endpoint=s3.XXXX.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=<redacted> --no-repo1-s3-verify-tls --repo1-type=s3 --stanza=production1 --target=20190929-073002F_20191001-073001D --type=xid

Error message from logs:
2019-10-07 23:18:26.516 P00  ERROR: [042]: raised from local-10 process: unexpected EOF reading HTTP content
                                        common/io/http/client:httpClientRead:127:(trace log level required for parameters)
                                        common/io/read:ioReadInternal:(trace log level required for parameters)
                                        common/io/read:ioRead:(trace log level required for parameters)
                                        storage/s3/read:storageReadS3:(trace log level required for parameters)
                                        common/io/read:ioReadInternal:(trace log level required for parameters)
                                        common/io/read:ioRead:(trace log level required for parameters)
                                        storage/storage:storageCopy:(debug log level required for parameters)
                                        command/restore/file:restoreFile:(debug log level required for parameters)
                                        command/restore/protocol:restoreProtocol:(debug log level required for parameters)
                                        protocol/server:protocolServerProcess:(debug log level required for parameters)
                                        command/local/local:cmdLocal:(debug log level required for parameters)
                                        main:main:(debug log level required for parameters)

**Comment by dwsteele** [comment]
We are intending to add a general retry to the restore/backup local processes.  A simple S3 retry won't work here because the request has already been passed on to the IO layer for processing.

In my experience these types of errors are fairly rare once the initial S3 request succeeds.  You may want to check for issues in your environment/network/etc if this is a common occurence.

**Comment by garthgoodson** [comment]
It took us a few days to restore a 2TB backup due to these issues.  We were running the restore from an EC2 machine in the same region and AZ as the S3 bucket.  I had to put the restore command in a bash file with a loop to keep retrying using --delta, not optimal...a retry would be highly appreciated.

**Comment by sean0101n** [comment]
I just received this same error while restoring a 35TB database.  Same setup as @garthgoodson, in regards to AWS services.  Is the best workaround currently to retry with the --delta option?  It's definitely not ideal, as this error occurred ~75% in and now a delta requires checksum matches on everything that was already brought down from s3.

**Comment by dwsteele** [comment]
I think that's the best solution for now.  Should still be a lot faster than a non-delta restore.

**Comment by sean0101n** [comment]
After retrying, I think my issue was not allocating enough space to one of my tablespaces, which may have caused this issue to come up.

**Comment by dwsteele** [comment]
Did you actually get `ERROR: [042]: raised from local-10 process: unexpected EOF reading HTTP content`?  I'd hope running out of space on the restore would produce a better error...

**Comment by sean0101n** [comment]
Yeah, that's the original error I got when I first tried restoring.  Sadly, I didn't notice space was an issue until trying a delta restore 2 more times, which I received this error instead:

`ERROR: [064]: raised from local-26 protocol: unable to write '/pg_dir/pg95_dir/data/pg_tblspc/56611/PG_9.5_201510051/16407/63693.1'`

**Comment by dwsteele** [comment]
Automatic retries were added in 620a8d17cfc0d6 for v2.28.
