### ISSUE TITLE
@yeswithae This is checking your pgbackrest.conf against the database and clearly it is not configured properly because you have a mismatch.

### ISSUE THREAD

**Issue by yeswithae** [pgbackrest/pgbackrest#859]
@yeswithae This is checking your pgbackrest.conf against the database and clearly it is not configured properly because you have a mismatch.

Please see the user-guide (https://pgbackrest.org/user-guide.html) to familiarize yourself with how to setup and configure a system.

_Originally posted by @cmwshang in https://github.com/pgbackrest/pgbackrest/issues/852#issuecomment-539111940_

**Comment by dwsteele** [comment]
Please stop opening new issues for replies -- simply reply on the original issue.
