### ISSUE TITLE
Only Restore the Backup

### ISSUE THREAD

**Issue by arenius** [pgbackrest/pgbackrest#861]
1. pgBackRest version:
2.13

2. PostgreSQL version:
11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 18.04

4. Did you install pgBackRest from source or from a package?
source

Question: Is there an option to only restore the most recent backup but not load any of the WAL that took place after that backup?

**Comment by cmwshang** [comment]
See https://pgbackrest.org/user-guide.html#pitr. The info command displays the "timestamp start/stop" and the "wal start/stop" so you can be quite specific as to where you want to play to. Use the --set option to use an earlier backup.

**Comment by arenius** [comment]
I am currently doing things that way.  However, if I want to automate, say, loading yesterdays backup onto a dev machine, it would be simpler if I could tell it to just load the backup and nothing after it.  Otherwise I have to create some (likely to be error prone) scripts to parse the info output.

**Comment by dwsteele** [comment]
Restore `--type=immediate` will only replay enough WAL to make the backup consistent.

**Comment by arenius** [comment]
Not sure how I missed that.  Thank you.

**Comment by dwsteele** [comment]
You're welcome!
