### ISSUE TITLE
Remote backup is too slow

### ISSUE THREAD

**Issue by appleajay** [pgbackrest/pgbackrest#862]
I have a Centos 7 server which runs Postgresql 10.7
I am running backup from another server (centos 7).[remote backup]
problem is backup is too slow.
my data dir size is 9.6 and full backup runtime is 22 mins
I also tried using process-max=3 full backup runtime = 21 mins

Following are the backrest configurations:
backrest.conf for pg-primary:
```

[data]
pg1-path=/var/lib/pgsql/10/data

[global]
log-level-file=detail
repo1-host=cheesecheaters
process-max=3
```

backrest.conf for repository:
```
[data]
pg1-host=pgprimary
pg1-path=/var/lib/pgsql/10/data

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y
```
Am i doing something wrong here.
In production we have database of size more than 500GB.  It would not be feasible for me to use it as it is.
 
pgbackrest version is 2.18-1.rhel7.x86_64 install from pgdg yum repo.

Thanks for help in advance

**Comment by appleajay** [comment]
Update: I tried to take backup from the local machine as well, just to make sure network bandwidth is not to slow.
It again took approx 20 mints.
pgbackrest.conf
```
[data]
pg1-path=/var/lib/pgsql/10/data

[global]
log-level-file=detail
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y
process-max=3
```

**Comment by dwsteele** [comment]
I see you gotten some suggestions on pgsql-general.  If you produce a log of your backup with `--log-level-console=debug` that would help us diagnose the bottleneck.

**Comment by dwsteele** [comment]
Looks like you've solved this problem.  For the record, from your pgsql-general email.
```
Thanks for your previous replies.
It turns out my machine was having kernel Issues, which made it slow.
I setup another cluster in different machine now I could able to backup 42G in 6 min(s).
```
