### ISSUE TITLE
Disarm archive_command during recovery phase of a restore

### ISSUE THREAD

**Issue by eradman** [pgbackrest/pgbackrest#865]
pgBackRest version: 2.18
PostgreSQL version: 11 and 12
Operating system/version: CentOS 7.4

postgresql.conf

    archive_mode = on
    archive_command = 'pgbackrest --stanza=main archive-push %p'

In one case I ran a restore and it appears that the `archive_command` was scribbling on
my backup location while PostgreSQL was replaying WAL

    restore_command = 'pgbackrest --stanza=main archive-get %f "%p"'

To avoid this I added the following instruction to an internal document

    sed -ie '/^archive_mode = /d' 12/postgresql.conf
    systemctl start postgresql-12

Since I only run pgbackrest from the master, I could create a wrapper script that aborts if `standby.signal` or `recovery.conf` is present. Is there a better way to avoid this potential danger?

**Comment by dwsteele** [comment]
Are you saying that `archive_command` is being called during recovery?  Do have Postgres logs to show this?

Lastly, Is this happening on both 11 and 12, or just 12?

**Comment by eradman** [comment]
Apologies for the noise; I thought that `archive_command` is being called during recovery (on 12), but  I have not been able to reproduce this.  I probably made some other sort of mistake.

If I want to avoid all writes to the repo I'm restoring from, it seems all I really had to do was point to an alternate location

    pgbackrest --repo1-path=/pgbackup-0/dbtest1.restore ... restore

**Comment by dwsteele** [comment]
There shouldn't be any writes to the repo until you promote, but yeah, switching the path or disabling the archive command will both prevent writes at that point.
