### ISSUE TITLE
Unable to install pgbackrest from source on CentOS 6.5

### ISSUE THREAD

**Issue by hlakshmi** [pgbackrest/pgbackrest#866]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.18
2. PostgreSQL version:
11.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS 6.5

4. Did you install pgBackRest from source or from a package?
Source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by hlakshmi** [comment]
Here is the output of `./configure`
```
[root@mysql1 src]# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... -std=gnu99
checking for perl_parse in -lperl... yes
checking for PQconnectdb in -lpq... no
configure: error: library 'pq' is required
```

I did install the `postgresql11-devel` package. Here is the yum output:
```
[root@mysql1 src]# yum list installed postgresql11-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: sjc.edge.kernel.org
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: sjc.edge.kernel.org
 * updates: mirrors.ocf.berkeley.edu
https://562e20f499b9342f7035557eeb6b212eaba94995d1550de7:@repos.citusdata.com/enterprise/el/6/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 401"
Trying other mirror.
https://562e20f499b9342f7035557eeb6b212eaba94995d1550de7:@repos.citusdata.com/enterprise/el/6/SRPMS/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 401"
Trying other mirror.
Installed Packages
postgresql11-devel.x86_64                                                           11.5-1PGDG.rhel6                                                            @pgdg11
```

**Comment by dwsteele** [comment]
Did you follow the build instuctions at: https://pgbackrest.org/user-guide-centos6.html#build?

Also note that yum.postgresql.org has pre-built packages for RHEL6.
