### ISSUE TITLE
ssh option in pgbackrest command

### ISSUE THREAD

**Issue by appleajay** [pgbackrest/pgbackrest#867]
I am using pgbackrest 2.18 on centos 7.6 with postgresql 10.
I understand pgbackrest uses ssh to connect repo and  database server. While there is option to provide ssh path(--cmd-ssh) and ssh port, I dont see any way to provide ssh  options in pgbackrest command or in pgbackrest.conf
There are some use cases where it can be usefull.

**Comment by dwsteele** [comment]
Do you have an example use case in mind?  It's good to be more configurable, but we also need to consider the additional code and tests this would add.

**Comment by dwsteele** [comment]
Please let us know if you have a specific use case.

We have been considering a general purpose configuration what would allow you to use ssh, rsh, etc.  That would probably be more flexible overall.
