### ISSUE TITLE
Database size is not  increasing with backup size..

### ISSUE THREAD

**Issue by yeswithae** [pgbackrest/pgbackrest#868]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.18

2. PostgreSQL version:12

3. Operating system/version - linux (Ubuntu 12.0-1.pgdg18.04+1)

4. Did you install pgbackrest from source or from a package: Source is from Github

5. Please attach the following as applicable:sudo -u postgres pgbackrest --stanza=demo24 info
stanza: demo24
    status: ok
    cipher: aes-256-cbc

    db (current)
        wal archive min/max (12-1): 0000000B0000000000000043/0000000C000000000000004C

        full backup: 20191024-102345F
            timestamp start/stop: 2019-10-24 10:23:45 / 2019-10-24 10:24:20
            wal start/stop: 0000000B0000000000000043 / 0000000B0000000000000043
            database size: 38.7MB, backup size: 38.7MB
            repository size: 4.7MB, repository backup size: 4.7MB

        diff backup: 20191024-102345F_20191024-123448D
            timestamp start/stop: 2019-10-24 12:34:48 / 2019-10-24 12:34:55
            wal start/stop: 0000000C000000000000004A / 0000000C000000000000004A
            database size: 38.7MB, backup size: 2.2MB
            repository size: 4.7MB, repository backup size: 231.0KB
            backup reference list: 20191024-102345F

        diff backup: 20191024-102345F_20191024-123518D
            timestamp start/stop: 2019-10-24 12:35:18 / 2019-10-24 12:35:24
            wal start/stop: 0000000C000000000000004C / 0000000C000000000000004C
            database size: 38.7MB, backup size: 2.2MB
            repository size: 4.7MB, repository backup size: 231.0KB
            backup reference list: 20191024-102345F
6. Describe the issue:
   There is a rise in backup size but the database size is still remains same.

**Comment by dwsteele** [comment]
It looks like the database size is staying the same.  The backup size will vary based on what kind of backup it is.  See https://pgbackrest.org/user-guide.html#quickstart/backup-info.
