### ISSUE TITLE
FIPS error when using stanza-create on RHEL7 FIPS / GovCloud

### ISSUE THREAD

**Issue by thunderkeys** [pgbackrest/pgbackrest#869]
1. pgBackRest version: 2.18

2. PostgreSQL version: 11.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 7 with FIPS mode enabled

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

[pgbackrest-debug.txt](https://github.com/pgbackrest/pgbackrest/files/3779264/pgbackrest-debug.txt)

[pgbackrest-redacted.conf.txt](https://github.com/pgbackrest/pgbackrest/files/3779267/pgbackrest-redacted.conf.txt)

[servername-stanza-create.log.txt](https://github.com/pgbackrest/pgbackrest/files/3779285/servername-stanza-create.log.txt)

7. Describe the issue:

When running pgbackrest stanza-create against an S3 GovCloud bucket I get the following error:

ERROR: [095]: unable to initialize hash context: [101187747] disabled for fips

If I point to a local filesystem path on the same system, it works successfully.

The error happens no matter if I use the non-fips endpoint (s3.us-gov-west-1.amazonaws.com) or the fips endpoint (s3-fips.us-gov-west-1.amazonaws.com).

Let me know if I can provide any other artifacts or assist in debugging further.

**Comment by dwsteele** [comment]
Hrm, I'm not sure how it would know that the repo is remote.  As far as I know a system is either fips-enabled or not.

Just to confirm, if you use *encryption* on the local filesystem it works?

Is the host accessing S3 also running in gov cloud?

**Comment by sfrost** [comment]
If I had to take a wild guess, I would suspect that what it's actually complaining about is:

                encodeToStr(encodeBase64, bufPtr(cryptoHashOne(HASH_TYPE_MD5_STR, body)), HASH_TYPE_M5_SIZE, md5Hash);

src/storage/s3/storage.c:278

**Comment by dwsteele** [comment]
Yes, that makes sense.  MD5 is not FIPS compliant, but it is required for S3 multi-part upload.  I'm not sure how to get around that.  Might be a question for Amazon?

**Comment by dwsteele** [comment]
Correction, MD5 is required for any S3 request body.

**Comment by dwsteele** [comment]
This appears to be a common issue (see https://github.com/boto/botocore/issues/1700).  The only workaround (it seems) is to not use OpenSSL for md5 calculations.  We know that the `content-md5` header does not need to be cryptographically secure, but OpenSSL doesn't.

**Comment by thunderkeys** [comment]
If it's just the content-md5 header, it might be replacable with x-amz-content-sha256?

https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/

**Comment by dwsteele** [comment]
I presume that disabling FIPS mode on the host is not an option?

I'm not too excited about integrating a custom md5 solution, but that may end up being the only option.

**Comment by dwsteele** [comment]
Also, I'm surprised that you got backup working -- any request with a body requires `content-md5` as far as I can see.

**Comment by dwsteele** [comment]
Ah, when you say "fiddled with it" you mean removed the `content-md5` header?  I believe we add that header even when it is not needed to keep things simple.

**Comment by thunderkeys** [comment]
Correct, Content-MD5 appears to be optional on many of the S3 API calls (so long as you are using signature 4 and the x-amz-content-sha256 header) .. but not on others.  By fiddle I mean I just added a conditional of && !FIPS_mode() before the Content-MD5 header was sent.

I will provide feedback to our Amazon rep on this ... maybe a future S3 API could be updated to use the sha256 header instead for the calls that need content verification.

Disabling FIPS mode is not a long term tenable solution for systems that will undergo a FedRAMP assessment.

**Comment by dwsteele** [comment]
> I will provide feedback to our Amazon rep on this ... maybe a future S3 API could be updated to use the sha256 header instead for the calls that need content verification.

I think this is a good idea, even if it is unlikely to be helpful in the short term.

> Disabling FIPS mode is not a long term tenable solution for systems that will undergo a FedRAMP assessment.

Agreed.  I was thinking more of something to get you going while we find a way to make this work on our side.

**Comment by dwsteele** [comment]
Just attached a PR (#1041) to add a local MD5 implementation for use in FIPS environments.

Comments welcome.

**Comment by dwsteele** [comment]
The PR has been committed and is included in v2.27 being released today.
