### ISSUE TITLE
NFS : doc should give officlal recommandations

### ISSUE THREAD

**Issue by Krysztophe** [pgbackrest/pgbackrest#871]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.17
2. PostgreSQL version: 12
3. Operating system/version : Linux
4. Did you install pgBackRest from source or from a package? package
7. Describe the issue:

For people not so fluent with NFS, is it possible to add recommendations on how to use an NFS share as a repo in a secure way and be sure not to lose some wals? In my understanding, the recommendations from the PG12 doc (https://www.postgresql.org/docs/current/creating-cluster.html#NFS : 'sync' on the server, 'hard' on the client) is probably enough, but I may be wrong.

**Comment by dwsteele** [comment]
The Postgres recommendations are also fine for pgBackRest.  We'll add this recommendation with a link to the Postgres docs.

**Comment by cmwshang** [comment]
PR created for this issue.
