### ISSUE TITLE
Question: advanced rentention

### ISSUE THREAD

**Issue by jamessewell** [pgbackrest/pgbackrest#872]
Hi,

I've seen a few closed questions on this - but it's a pretty major thing.

I need to retain x days of backups, currently it seems I can't do this if ad-hoc backups could happen? Even a way to run a backup which doesn't contribute to the number of backups (label as ad-hoc) could work here.

I also need to retain the first backup of the month for a longer period. I know this is not possible - can I do this manually somehow?

Cheers,
james

**Comment by bradnicholson** [comment]
> I need to retain x days of backups, currently it seems I can't do this if ad-hoc backups could happen? Even a way to run a backup which doesn't contribute to the number of backups (label as ad-hoc) could work here.

If you have control of the backup types and can make those ad-hoc backups incrementals you can make this work.

We have similar requirements around keeping backups around based on time periods.  We ensure that our daily backups are full or differentials, and any other backups are incremental. With this approach, you can set rotation policies to keep things around based on time.

**Comment by mahomedh** [comment]
> I also need to retain the first backup of the month for a longer period.

We have a similar requirement. Just had a thought, not tested it yet. But if we can have multiple stanzas on the server and do backups to multiple stanzas from the same pg cluster, then that might solve it. What I mean for example is you could have a stanza `Monthly-Stanza` where you do a full backup once a month and your `Regular-Stanza` where your archives are written to and you could do full backups weekly and incrementals daily to keep the size down. So if you want to do a recent PITR recovery, you'd do it from the `Regular-Stanza` but if you need an older backup, then you'd look at `Monthly-Stanza`

**Comment by jamessewell** [comment]
That would only work if you could backup without streaming WAL - I dint
think this is possible?

**Comment by dwsteele** [comment]
Correctly configuring multiple stanzas is tricky and we don't recommend it, but it *is* possible by joining multiple archive commands with `&&`.  There are a number of caveats, though, so it is not for the faint of heart.

We are currently considering three expiration features that should help with these concerns:
1) Time-based retention -- we are still researching what this would look like.
2) Pin a backup -- prevent a backup from being expired (this could be used to help you preserve the first backup of the month for whatever duration).
3) Ad-hoc backup expire -- A completely novel retention policy could be built with this feature.

Some combination of these features are on our radar, though we haven't decided on deadlines.

I like the idea of adhoc backups, but I feel that time-based retention is a better option.  We'll consider it, though.

**Comment by dwsteele** [comment]
As of 2.27 pgBackRest has time-based full retention and adhoc expiration. You should be able to accomplish your original ask with the latter. Let us know if you run into any problems.
