### ISSUE TITLE
is it possible to run pgbackrest behind a proxy

### ISSUE THREAD

**Issue by kikijolicoeur** [pgbackrest/pgbackrest#879]
Hello.

pgBackRest version:
2.19

PostgreSQL version:
10.6

Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
debian 9 (stretch)

Did you install pgBackRest from source or from a package?
installation from a package (repo http://apt.postgresql.org/pub/repos/apt/) : 2.19-1.pgdg90+1
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
I set http_proxy and https_proxy variables. I can run aws to show my bucket content. But with pgbackrest I have a connection timeout to connect on my bucket to s3.amazonaws.com
How can I use pgbackrest behind a proxy ?

Thanks

**Comment by dwsteele** [comment]
No, not currently.  Proxies are generally not a good fit for the high bandwidth and connection reuse requirements of pgBackRest.

**Comment by kikijolicoeur** [comment]
Thanks for your response
