### ISSUE TITLE
Multiple Point in Time recoveries in a row create, how to handle?

### ISSUE THREAD

**Issue by Soulou** [pgbackrest/pgbackrest#881]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:

```
2.19
```

2. PostgreSQL version:

```
12.1
```

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

```
Ubuntu Bionic docker container, database is alone
```

4. Did you install pgBackRest from source or from a package?

** From package **

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

```
[stanza-name]
pg1-path=/var/lib/postgresql/12/postgresql0
pg1-socket-path=/tmp

[global]
repo1-cipher-pass=<pass>
repo1-cipher-type=aes-256-cbc
repo1-path=/var/lib/pgbackrest
repo1-retention-diff=6
repo1-retention-full=2
repo1-s3-bucket=<bucket>
repo1-s3-endpoint=<endpoint>
repo1-s3-key=<key>
repo1-s3-key-secret=<secret>
repo1-s3-region=<region>
repo1-type=s3
stop-auto=y
start-fast=y
log-level-console=off
log-level-stderr=info

[global:archive-push]
# a lower compression level may be set to speed archiving without affecting
# the compression used for backups.
compress-level=3
```

With environment:

```
PGBACKREST_CONFIG=/var/lib/postgresql/12/pgbackrest.conf
PGBACKREST_REPO1_CIPHER_PASS=<pass>
PGBACKREST_REPO1_S3_ENDPOINT=<endpoint>
PGBACKREST_REPO1_S3_KEY=<key>
PGBACKREST_REPO1_S3_KEY_SECRET=<secret>
PGBACKREST_REPO1_S3_BUCKET=<bucket>
PGBACKREST_REPO1_S3_REGION=<region>
```

7. Describe the issue:

I'm currently working around Point in Time Recovery (PiTR), I'm trying the following scénario.

1. *t* : Creation of base backup (on **Timeline 1**)
2. Continuous insertion of data
2. *t+1h* : Triggering point in time recovery at *t+30min*

```
pgbackrest --stanza=$STANZA --delta --type=time "--target=$PITR_TIME" restore
```

postgresql.conf

```
restore_command ='pgbackrest --config=/var/lib/postgresql/12/pgbackrest.conf --stanza=$STANZA archive-get %f "%p"'
recovery_target_time = '$PITR_TIME'
recovery_target_action = promote
recovery_target_inclusive = false
```

It recovers very smoothly then promote to **Timeline 2** history file are uploaded.

→ Database is up and running at the right PiTR time here.

3. *t+1h10* : Triggering point in time recovery at *t+20min* (because the data at t+30min) were not the ones I actually wanted.

- pgbackrest restores correctly the base backup and then WAL segments are downloaded to get back to the requried time, on **Timeline 1**

Database is promoted again, but here, we've again **Timeline 2**.

So here we've 2 **Timeline 2** which are completely different, as one is coming from a first PiTR at **t+30min**, and the other from a second PiTR at **t+20min**. Obviously it creates conflicts

Is there a way to handle smoothly this situation?

Is there a way to ask PG to create a new timeline different from all the forks which happened before?

Any hint would be very welcome.

Thanks a lot.

**Comment by Soulou** [comment]
Actually, the problem has been identified,

The process which was finalizing the PiTR didn't have archive_mode enabled, as a result the history file from the new timeline was not uploaded correctly.

So PostgreSQL was getting lost at some point.

**Comment by dwsteele** [comment]
That looks right to me.  Glad you figured it out!
