### ISSUE TITLE
Same project for MYSQL ?

### ISSUE THREAD

**Issue by bumblebeey** [pgbackrest/pgbackrest#883]
Hi its not issue, i really love pgbackrest and i am using for my postgresql databases,
easy installation easy usage, i am lookin similar solution for mysql any one can advice to me ?

**Comment by dwsteele** [comment]
Sorry, we don't have any MySQL experience.  The best we could do is google (but you can do that) and we don't have any recommendations.

Glad you like pgBackRest, though!
