### ISSUE TITLE
thank you for great S3 backup option!

### ISSUE THREAD

**Issue by slava-pagerduty** [pgbackrest/pgbackrest#884]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
latest.

2. PostgreSQL version:
11.6

3. Operating system/version
ubuntu 16  on i3.8xlarge AWS EC2 instance

4. Did you install pgBackRest from source or from a package?
package

7. Describe the issue:
There is no issue. I just want to say Thank you for releasing this tool.
It is a game changer for Postgres when you want to backup to S3.

I am able to backup incrementally our 2.5 TB db in around 1 hour and restore it under 30 minutes from S3. Process is extremely efficient and works as fast as the hardware/network bandwidth allows. Thank you again and please keep up great work.
Pagerduty analytics team.

**Comment by dwsteele** [comment]
We're glad you like it!  We are just finishing up the C migration for this release and then we have many more features planned for the new year.

Just curious -- how long does your full backup to S3 take, and what is `process-max` set to?

**Comment by slava-pagerduty** [comment]
these are the setting I use:
```
cat /etc/pgbackrest.conf
[global]
process-max=12
start-fast=y
archive-async=y
...
```
i3.8xlarge has 32 vCPUs, so we have plenty of CPU left.

full backup, which we run on Sundays, takes 3 hours 6 minutes and comresses 2.6TB into 600GB.
Very nice and can't be more happy with the whole process.
