### ISSUE TITLE
parallel restore 

### ISSUE THREAD

**Issue by edib** [pgbackrest/pgbackrest#885]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.19
2. PostgreSQL version:
11
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
centos 7
4. Did you install pgBackRest from source or from a package?
no

7. Describe the issue:
As far as I can see, archiving can be parallel but filenode restore is not parallel. Especially in remote restore, checksums take time and really slow. Is there a way to improve restore performance?

**Comment by dwsteele** [comment]
Not sure what you mean by "filenode", but restore certainly runs in parallel (and always has).

See https://pgbackrest.org/user-guide.html#parallel-backup-restore.

**Comment by edib** [comment]
The main reason behind my question is I have a 3TB cluster and I tried the restore it to remote machine recently. Also, it takes almost 12 hours to restore and It always takes the almost same amount of time for full backup. 
I just simply analyzed and I think it is because of single pgbackrest process that restore/transfer the data files to another machine over ssh and ssh uses single core transfer files and I coud not find any related parameter for that. I am not mentioning wal files backup/restore because it is really fast as you stated. 
That is why I think that data files backup/restore is single threaded not parallel. Am I wrong?

**Comment by dwsteele** [comment]
How long backup and restore take really depend on your host (i.e. CPU and network bandwidth), process-max, compress-level.  You haven't provided any configs so it's hard to say.

Backup and restore are single-threaded by default, but see https://pgbackrest.org/user-guide.html#parallel-backup-restore for details on how to parallelize.
