### ISSUE TITLE
s3 timeout errors

### ISSUE THREAD

**Issue by kethineni1** [pgbackrest/pgbackrest#888]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.19

2. PostgreSQL version:
10.6
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
rhel 8/7.6
4. Did you install pgBackRest from source or from a package?
yum
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

[postgres~]$ cat /postgres/pgbackrest.conf
[global]
repo1-s3-verify-tls=n
repo1-type=s3
repo1-s3-host=east.x.com
repo1-s3-endpoint=east.x.com
repo1-s3-key=xxxxxxxxxxxx
repo1-s3-key-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
repo1-s3-region=east
repo1-retention-full=1
process-max=90
log-level-console=info
log-level-file=detail
start-fast=y
delta=y
buffer-size=16777216
protocol-timeout=18000

repo-s3-ca-file=/ca.crt
repo1-path=/
repo1-s3-bucket=mybucket

[mystanza]
pg1-path=/postgres/data

archive_command = '/bin/pgbackrest --stanza=mystanza --config=/postgres/pgbackrest.conf archive-push /postgres/data/%p'"

7. Describe the issue:

Restore/Backup to s3 (endpoint is not aws server but localhost implementing some proxy sort) is failing with different errors related to timeout. Is there a way to retry any s3 request for x times before failing? or please help me locate the place in codebase to add such condition.

pgbackrest --stanza=mystanza --config=/postgres/pgbackrest.conf  --log-level-console=info   --type=incr backup

2019-12-06 06:13:44.471 P14   INFO: restore file /postgres/data/base/16384/7318312.14 (1GB, 39%) checksum 835e2cb497f9fa84abc78d625d8168a02acce8e7
2019-12-06 06:13:44.471 P00  DEBUG:     command/restore/restore::restoreJobResult: => 2290297678519
2019-12-06 06:13:44.849 P00  DEBUG:     command/restore/restore::restoreJobResult: (manifest: {Manifest}, 
	job: {state: done, key: {"pg_data/base/16384/7318552.8"}, command: {command: restoreFile}, code: 29, 
	message: {"raised from local-19 protocol: zlib threw error: [-3] data error
                                        common/compress/gzip/common:gzipError:87:(test build required for parameters)
                                            ... function(s) omitted ...
                                        common/compress/gzip/decompress:gzipDecompressProcess:(trace log level required for parameters)
                                        common/io/filter/group:ioFilterGroupProcess:(trace log level required for parameters)
                                        common/io/write:ioWrite:(trace log level required for parameters)
                                        storage/storage:storageCopy:(debug log level required for parameters)
                                        command/restore/file:restoreFile:(debug log level required for parameters)
                                        command/restore/protocol:restoreProtocol:(debug log level required for parameters)
                                        protocol/server:protocolServerProcess:(debug log level required for parameters)
                                        command/local/local:cmdLocal:(debug log level required for parameters)
                                        main:main:(debug log level required for parameters)"}, result: null}, zeroExp: null, 
                                        	sizeTotal: 5864501623142, sizeRestored: 2290297678519)
2019-12-06 06:13:44.854 P00  DEBUG:     common/exit::exitSafe: (result: 0, error: true, signalType: 0)
ERROR: [029]: raised from local-19 protocol: zlib threw error: [-3] data error
       common/compress/gzip/common:gzipError:87:(test build required for parameters)
           ... function(s) omitted ...
       common/compress/gzip/decompress:gzipDecompressProcess:(trace log level required for parameters)
       common/io/filter/group:ioFilterGroupProcess:(trace log level required for parameters)
       common/io/write:ioWrite:(trace log level required for parameters)
       storage/storage:storageCopy:(debug log level required for parameters)
       command/restore/file:restoreFile:(debug log level required for parameters)
       command/restore/protocol:restoreProtocol:(debug log level required for parameters)
       protocol/server:protocolServerProcess:(debug log level required for parameters)
       command/local/local:cmdLocal:(debug log level required for parameters)
       main:main:(debug log level required for parameters)
^C
Uncaught AssertError: cannot free inactive context
    thrown at common/memContext.c:585

**Comment by dwsteele** [comment]
We already do S3 retries -- it looks like the proxy is returning bad data to pgbackrest and causing decompression to fail: `raised from local-19 protocol: zlib threw error: [-3] data error`.

I'm pretty sure that an EOF in this case would return an unexpected EOF error.  Do you have a reason to suspect that a retry here would result in good data?

Any info on this proxy?  Name, version, etc?

You could implement a higher-level retry by wrapping this block in a loop:
https://github.com/pgbackrest/pgbackrest/blob/2d10293d041cbbc72e4a2bac32401f6f384ecb1a/src/command/restore/file.c#L146

We are planning retries at an even higher level that would work for backup, restore, etc., but you are welcome to give it a try yourself.
