### ISSUE TITLE
Is it possible not to use dns bucket style?

### ISSUE THREAD

**Issue by skilyazhnev** [pgbackrest/pgbackrest#889]
Hi.

I want to put a backup in  s3 minio. but my minio instance is configured by another department. and mini doesn't support dns default style of bucket definition. Is it possible to switch your utility to "bucket in path" mode for minio s3? 

pgBackRest 2.19 
PostgreSQL version: 10.5, 11.3, 9.6
CentOS 7
install pgBackRest from a package

`pgbackrest.conf` file(s)
```
[global]
repo1-path=/backups/pgwall
repo1-type=s3
repo1-s3-endpoint=minio.domain.ru:443
repo1-s3-bucket=bucket
repo1-s3-verify-tls=n
repo1-s3-key=key
repo1-s3-key-secret=key_s
repo1-s3-region=eu-west-3

repo1-retention-full=1
process-max=2
log-level-console=info
log-level-file=debug
start-fast=y
delta=y

[base]
#pg1-path=/var/lib/pgsql/10/data
pg1-host=base1
pg2-host=base2
pg1-path=/var/lib/pgsql/10/data

```

thanks in advance.

**Comment by dwsteele** [comment]
You didn't send the error message.  Presumably it's something like `host bucket.minio.domain.ru not found`?

You may be able to get this working with something like:
```
repo1-s3-endpoint=minio.domain.ru
repo1-s3-bucket=bucket
repo1-s3-host=minio.domain.ru
repo1-s3-port=443
repo1-s3-verify-tls=n
```

This will still send host-style requests, but it will send them to `minio.domain.ru` instead of `bucket.minio.domain.ru`.  Generally minio seems to be OK with this, but it does depend on configuration.

Since Amazon deprecated url-style requests we have not felt a lot of pressure to implement them, but we may still do so.  We'd be willing to accept a patch as well.

**Comment by skilyazhnev** [comment]
Yes you are right. it was such an error that was originally.

my infrastructure implies the presence of nginx before minio. so I had to try your advice, but refine it with a “crutch”

```
[global]
repo1-path=/bucket/path
repo1-type=s3
repo1-s3-endpoint=domain.ru             # <-----
repo1-s3-host=minio.domain.ru
repo1-s3-port=443
repo1-s3-bucket=host                           # <-----
repo1-s3-verify-tls=n
repo1-s3-key=key
repo1-s3-key-secret=key_s
repo1-s3-region=eu-west-3
```

as a result, the desired domain name is formed. and the path actually points to the desired bucket. 
but such a solution looks very unreliable.

**Comment by dwsteele** [comment]
Well, it is pretty hard to read.  If it works, I'm not sure it will be unreliable, though.  It does work?

**Comment by skilyazhnev** [comment]
so so. 
i can create stanza, i can copy wal file and backup. 
but when i call info pgBackrest return "No stanzas exist in the repository". и при check, возвращает WAL segment  was not archived before the 60000ms timeout

I see that the files are physically in the repository. but pgbackuprest doesn't seem to see them

**Comment by dwsteele** [comment]
Hmm, OK.  I don't think we are against supporting path-style URLs but we don't have the time to take it on right now.  It's just never been an issue before and it increases our test matrix.

**Comment by dwsteele** [comment]
I just tried with Minio and I was able to get it to work with this config:
```
repo1-path=/demo-bucket
repo1-retention-full=2
repo1-s3-bucket=demo-bucket
repo1-s3-endpoint=local.myserver.org
repo1-s3-host=local.myserver.org
repo1-s3-key=accessKey1
repo1-s3-key-secret=verySecretKey1
repo1-s3-region=us-east-1
repo1-s3-verify-tls=n
repo1-type=s3
```

There's definitely some repetition here which is not ideal, but we can clean that up later.

The question is: does it work?

Note that in our tests we have setup minio's host as `s3.us-east-1.amazonaws.com` by default (this makes the docs look like they are using S3) so the above configuration required `repo1-s3-verify-tls=n`, but if your Minio cert is valid you should not need that.

**Comment by dwsteele** [comment]
So it looks like for the above config to work the endpoint and host *must* be set to the same value as MINIO_DOMAIN.

But while I was figuring that out I ended up implementing path-style URIs, so that should be in the next release.

**Comment by dwsteele** [comment]
Committed at fe263e87b182.
