### ISSUE TITLE
Question: Steps required to do PITR on a streaming replication setup.

### ISSUE THREAD

**Issue by gowtham500** [pgbackrest/pgbackrest#891]
Hello team,

Thanks for this amazing tool. I do have few questions as to how we can recover from a disaster and bring up a streaming replication setup as quick as possible with minimum downtime.

This is the setup which i have configured through pgbackrest.
PRIMARY - NODE 1
STANDBY - NODE 2
STANDBY - NODE 3.
BACKUP   - NODE 4. 

Node 4 is dedicated backup host. Backups occur through standby node -2.  
All nodes have common WAL archive. pgbackrest is working great.

Let say a disaster happens and we want to do PITR.  These are steps which we currently follow.

1. Destroy all standby nodes - wipe away data directory.
2. Restore PRIMARY with delta restore with latest backup set. 
3. Turn off archive_mode on PRIMARY. 
4. Start PRIMARY and verify if data is ok.
Now these steps so far are great as we do delta restore and we are able to do recovery quickly with additional options of --parallel-max. We are able to do PITR with this as quick as possible.

Now for creating STANDBY nodes and re setting up STREAMING REPLICATION, what is the best way to recreate the standby nodes with less time.

We had previously configured backup host config to take backup from standby nodes. Now the standby nodes are down.
Steps which I do (need help on these steps) 
1. Modify config on backup host and new PRIMARY to 
       a.) Create a new stanza. (My idea of creating a new stanza is when I was doing a PITR for the PRIMARY, someone started the standby by mistake and it became a new primary and pushed WAL into archive. I had to then stop it manually and to prevent it reading from archive, i thought new stanza would be a best option.)
       b)  Enable archive on new Primary.
       c) Modify archive_command and restore_command to new stanza with pgbackrest.
       c)  Run pgbackrest check.

At this step I have created a new stanza for the FRESH primary.

2. Use this to create other replicas.

Are these the best steps for achieving minimum downtime ? Can we do a delta restore on all nodes?

**Comment by dwsteele** [comment]
Here's a simpler procedure:
*) Shutdown primary
*) Set `archive_command` on primary to `false` (note that this will cause archiving errors in the log)
*) Perform PITR on primary (repeat until you have the right PIT).
*) Set `archive_command` on primary to `true` and let archiving catch up
*) Delta restore standbys from the same backup with `--target-timeline=latest`

There's no need to make a new backup after PITR.

It's always fine to do a delta restore.  There are some cases where it can be slower (all files have changed since the backup) but in most cases it is a lot faster.

**Comment by gowtham500** [comment]
Thanks for the info, let me try. 

One more observation during PITR with archive_mode: off is, the history files dont get archived during timeline switch. The WAL files get copied though.
They get copied only when PITR is done with archive_mode is on. Is this a intended setting?

Is turning archive_mode off a good thing or can we keep it on even during PITR?

Version info:
pgbackrest version 2.19
postgres 12.0

**Comment by dwsteele** [comment]
When `archive_mode=off` nothing at all should be archived, but this means you will lose important data as soon as your primary is promoted after PITR.

If you set `archive_command=false` then PostgreSQL will not be able to archive but it will keep the .history file and all WAL segments.  Once you set archive_command back to normal, i.e. `pgbackrest --stanza <...>` then all the held WAL and .history will be archived.  This is what allows the standbys to recover from an older backup.

Please be sure to test your procedure in advance!  Let us know if you run into any issues.
