### ISSUE TITLE
ERROR: [056]: unable to find primary cluster - cannot proceed

### ISSUE THREAD

**Issue by yeswithae** [pgbackrest/pgbackrest#895]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.20

2. PostgreSQL version:psql (PostgreSQL) 12.1 (Ubuntu 12.1-1.pgdg18.04+1)

3. Operating system/version - linux (ubuntu )
both database and backup server using same version 

4. Did you install pgBackRest :From package

5. Please attach the following as applicable:

- pgbackrest.conf` file(s)

[rtt_cluster]
pg1-path=/var/lib/postgresql/12/rtt_cluster
pg1-host=139.59.6.129
[global]
repo1-cipher-pass=zWaf6XtpjIVZC5444yXB+cgFDFl7MxGlgkZSaoPvTGirhPygu4jOKOXf9LO4vjfO
repo1-cipher-type=aes-256-cbc
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y

[global:archive-push]
compress-level=3

- postgres.conf:

archive_command = 'pgbackrest --stanza=rtt_cluster archive-push %p'
archive_mode = on
hot_standby = on
listen_addresses = '*'
log_filename = 'postgresql.log'
log_line_prefix = ''
max_wal_senders = 3
wal_level = replica

6. Describe the issue:
Iam trying to create connection between backup server and database host after configuring,while creating stanza i am facing the issue saying that connection terminated unexpectedly..

> WARN: unable to check pg-1: [UnknownError] remote-0 process on '139.59.6.129' terminated unexpectedly [255]: postgres@139.59.6.129: Permission denied (publickey,password).

> ERROR: [056]: unable to find primary cluster - cannot proceed

**Comment by dwsteele** [comment]
You need to setup password-less SSH.  See https://pgbackrest.org/user-guide.html#repo-host/setup-ssh.

**Comment by yeswithae** [comment]
I have made password less connection to other user and trying to connect from pg backrest as user.Know,configured from pg backrest user and it's working...
