### ISSUE TITLE
Question about backup size

### ISSUE THREAD

**Issue by K3ndu** [pgbackrest/pgbackrest#898]
Hello!

I have question about backup size for differential backups. We do once in a week a full backup and then 6 days a differential backup and when I check in the filesystem a differential backup size, it's way smaller than reported by pgbackrest info command.

Pgbackrest version 2.18-1 installed from package
PostgreSQL version 11.5
OS: Centos 7.6.1810

    db (current)
        wal archive min/max (11-1): 0000000100000077000000E1/000000010000007F0000001F

        full backup: 20191124-004501F
            timestamp start/stop: 2019-11-24 00:45:01 / 2019-11-24 00:50:20
            wal start/stop: 0000000100000077000000E1 / 0000000100000077000000E1
            database size: 23.1GB, backup size: 23.1GB
            repository size: 23.1GB, repository backup size: 23.1GB

        full backup: 20191201-004502F
            timestamp start/stop: 2019-12-01 00:45:02 / 2019-12-01 00:50:32
            wal start/stop: 000000010000007A00000077 / 000000010000007A00000077
            database size: 23.2GB, backup size: 23.2GB
            repository size: 23.3GB, repository backup size: 23.3GB

        diff backup: 20191201-004502F_20191207-004502D
            timestamp start/stop: 2019-12-07 00:45:02 / 2019-12-07 00:51:33
            wal start/stop: 000000010000007B000000EF / 000000010000007B000000EF
            database size: 23.4GB, backup size: 22.6GB
            repository size: 23.4GB, repository backup size: 22.6GB
            backup reference list: 20191201-004502F

        full backup: 20191208-004502F
            timestamp start/stop: 2019-12-08 00:45:02 / 2019-12-08 00:50:27
            wal start/stop: 000000010000007C0000002B / 000000010000007C0000002B
            database size: 23.4GB, backup size: 23.4GB
            repository size: 23.4GB, repository backup size: 23.4GB

        diff backup: 20191208-004502F_20191209-004502D
            timestamp start/stop: 2019-12-09 00:45:02 / 2019-12-09 00:49:25
            wal start/stop: 000000010000007C0000003C / 000000010000007C0000003C
            database size: 23.4GB, backup size: 18.6GB
            repository size: 23.4GB, repository backup size: 18.6GB
            backup reference list: 20191208-004502F

        diff backup: 20191208-004502F_20191210-004502D
            timestamp start/stop: 2019-12-10 00:45:02 / 2019-12-10 00:49:51
            wal start/stop: 000000010000007C00000085 / 000000010000007C00000085
            database size: 23.4GB, backup size: 21.6GB
            repository size: 23.4GB, repository backup size: 21.6GB
            backup reference list: 20191208-004502F

        diff backup: 20191208-004502F_20191211-004501D
            timestamp start/stop: 2019-12-11 00:45:01 / 2019-12-11 00:49:59
            wal start/stop: 000000010000007C000000CB / 000000010000007C000000CB
            database size: 23.4GB, backup size: 22.6GB
            repository size: 23.4GB, repository backup size: 22.7GB
            backup reference list: 20191208-004502F

        diff backup: 20191208-004502F_20191212-004502D
            timestamp start/stop: 2019-12-12 00:45:02 / 2019-12-12 00:50:02
            wal start/stop: 000000010000007D0000000C / 000000010000007D0000000C
            database size: 23.4GB, backup size: 22.7GB
            repository size: 23.4GB, repository backup size: 22.7GB
            backup reference list: 20191208-004502F

        diff backup: 20191208-004502F_20191213-004502D
            timestamp start/stop: 2019-12-13 00:45:02 / 2019-12-13 00:50:10
            wal start/stop: 000000010000007D00000069 / 000000010000007D00000069
            database size: 23.5GB, backup size: 22.7GB
            repository size: 23.5GB, repository backup size: 22.7GB
            backup reference list: 20191208-004502F

        diff backup: 20191208-004502F_20191214-004501D
            timestamp start/stop: 2019-12-14 00:45:01 / 2019-12-14 00:50:08
            wal start/stop: 000000010000007D000000B4 / 000000010000007D000000B4
            database size: 23.5GB, backup size: 22.7GB
            repository size: 23.5GB, repository backup size: 22.7GB
            backup reference list: 20191208-004502F

        full backup: 20191215-004502F
            timestamp start/stop: 2019-12-15 00:45:02 / 2019-12-15 00:50:27
            wal start/stop: 000000010000007E0000000E / 000000010000007E0000000E
            database size: 23.5GB, backup size: 23.5GB
            repository size: 23.5GB, repository backup size: 23.5GB

        diff backup: 20191215-004502F_20191216-004501D
            timestamp start/stop: 2019-12-16 00:45:01 / 2019-12-16 00:49:32
            wal start/stop: 000000010000007E0000001E / 000000010000007E0000001E
            database size: 23.5GB, backup size: 18.7GB
            repository size: 23.5GB, repository backup size: 18.7GB
            backup reference list: 20191215-004502F

        diff backup: 20191215-004502F_20191217-004502D
            timestamp start/stop: 2019-12-17 00:45:02 / 2019-12-17 00:50:16
            wal start/stop: 000000010000007E0000005E / 000000010000007E0000005E
            database size: 23.5GB, backup size: 22.7GB
            repository size: 23.5GB, repository backup size: 22.7GB
            backup reference list: 20191215-004502F

        diff backup: 20191215-004502F_20191218-004501D
            timestamp start/stop: 2019-12-18 00:45:01 / 2019-12-18 00:50:03
            wal start/stop: 000000010000007E0000009A / 000000010000007E0000009A
            database size: 23.5GB, backup size: 22.7GB
            repository size: 23.5GB, repository backup size: 22.8GB
            backup reference list: 20191215-004502F

        diff backup: 20191215-004502F_20191219-004501D
            timestamp start/stop: 2019-12-19 00:45:01 / 2019-12-19 00:50:07
            wal start/stop: 000000010000007E000000D3 / 000000010000007E000000D3
            database size: 23.5GB, backup size: 22.8GB
            repository size: 23.5GB, repository backup size: 22.8GB
            backup reference list: 20191215-004502F

        diff backup: 20191215-004502F_20191220-004502D
            timestamp start/stop: 2019-12-20 00:45:02 / 2019-12-20 00:50:06
            wal start/stop: 000000010000007F00000016 / 000000010000007F00000016
            database size: 23.6GB, backup size: 22.8GB
            repository size: 23.6GB, repository backup size: 22.8GB
            backup reference list: 20191215-004502F

        diff backup: 20191215-004502F_20191220-095852D
            timestamp start/stop: 2019-12-20 09:58:52 / 2019-12-20 10:04:04
            wal start/stop: 000000010000007F0000001E / 000000010000007F0000001E
            database size: 23.6GB, backup size: 22.8GB
            repository size: 23.6GB, repository backup size: 22.8GB
            backup reference list: 20191215-004502F

[root@pgadmin ~]# du -ha /backup/backup/database/ | sort -h -r | head -n 50
111G    /backup/backup/database/
6.8G    /backup/backup/database/20191215-004502F/pg_data/base/16401
6.8G    /backup/backup/database/20191215-004502F/pg_data/base
6.8G    /backup/backup/database/20191215-004502F/pg_data
6.8G    /backup/backup/database/20191215-004502F
6.8G    /backup/backup/database/20191208-004502F/pg_data/base
6.8G    /backup/backup/database/20191208-004502F/pg_data
6.8G    /backup/backup/database/20191208-004502F
6.7G    /backup/backup/database/20191215-004502F_20191220-095852D/pg_data/base/16401
6.7G    /backup/backup/database/20191215-004502F_20191220-095852D/pg_data/base
6.7G    /backup/backup/database/20191215-004502F_20191220-095852D/pg_data
6.7G    /backup/backup/database/20191215-004502F_20191220-095852D
6.7G    /backup/backup/database/20191215-004502F_20191220-004502D/pg_data/base/16401
6.7G    /backup/backup/database/20191215-004502F_20191220-004502D/pg_data/base
6.7G    /backup/backup/database/20191215-004502F_20191220-004502D/pg_data
6.7G    /backup/backup/database/20191215-004502F_20191220-004502D
6.7G    /backup/backup/database/20191215-004502F_20191219-004501D/pg_data/base/16401
6.7G    /backup/backup/database/20191215-004502F_20191219-004501D/pg_data/base
6.7G    /backup/backup/database/20191215-004502F_20191219-004501D/pg_data
6.7G    /backup/backup/database/20191215-004502F_20191219-004501D
6.7G    /backup/backup/database/20191215-004502F_20191218-004501D/pg_data/base/16401
6.7G    /backup/backup/database/20191215-004502F_20191218-004501D/pg_data/base
6.7G    /backup/backup/database/20191215-004502F_20191218-004501D/pg_data
6.7G    /backup/backup/database/20191215-004502F_20191218-004501D
6.7G    /backup/backup/database/20191215-004502F_20191217-004502D/pg_data/base/16401
6.7G    /backup/backup/database/20191215-004502F_20191217-004502D/pg_data/base
6.7G    /backup/backup/database/20191215-004502F_20191217-004502D/pg_data
6.7G    /backup/backup/database/20191215-004502F_20191217-004502D
6.7G    /backup/backup/database/20191208-004502F/pg_data/base/16401
6.7G    /backup/backup/database/20191208-004502F_20191214-004501D/pg_data/base/16401
6.7G    /backup/backup/database/20191208-004502F_20191214-004501D/pg_data/base
6.7G    /backup/backup/database/20191208-004502F_20191214-004501D/pg_data
6.7G    /backup/backup/database/20191208-004502F_20191214-004501D
6.7G    /backup/backup/database/20191208-004502F_20191213-004502D/pg_data/base/16401
6.7G    /backup/backup/database/20191208-004502F_20191213-004502D/pg_data/base
6.7G    /backup/backup/database/20191208-004502F_20191213-004502D/pg_data
6.7G    /backup/backup/database/20191208-004502F_20191213-004502D
6.7G    /backup/backup/database/20191201-004502F/pg_data/base/16401
6.7G    /backup/backup/database/20191201-004502F/pg_data/base
6.7G    /backup/backup/database/20191201-004502F/pg_data
6.7G    /backup/backup/database/20191201-004502F
6.7G    /backup/backup/database/20191124-004501F/pg_data/base/16401
6.7G    /backup/backup/database/20191124-004501F/pg_data/base
6.7G    /backup/backup/database/20191124-004501F/pg_data
6.7G    /backup/backup/database/20191124-004501F
6.6G    /backup/backup/database/20191208-004502F_20191212-004502D/pg_data/base/16401
6.6G    /backup/backup/database/20191208-004502F_20191212-004502D/pg_data/base
6.6G    /backup/backup/database/20191208-004502F_20191212-004502D/pg_data
6.6G    /backup/backup/database/20191208-004502F_20191212-004502D
6.6G    /backup/backup/database/20191208-004502F_20191211-004501D/pg_data/base/16401

What is the calculation behind backup size and what am i missing?

**Comment by dwsteele** [comment]
You didn't provide a configuration.  Are you disabling compression?

It looks like you have compression disabled but your storage device or file system is doing compression.  pgBackRest makes an attempt to report compression done by the storage device or file system but is not always able to do so, depending on how it is reported.

**Comment by K3ndu** [comment]
This is the configuration:
[global]
repo1-path=/backup
repo1-retention-full=4
repo1-retention-diff=15
compress-level=0
compress-level-network=3
process-max=2
log-level-console=info
log-level-file=debug
start-fast=y
stop-auto=y

**Comment by dwsteele** [comment]
`compress-level=0` is not a very good way to disable compression -- this actually uses *more* space since it uses the store mode of gzip which includes a header.  `compress=n` is what you are looking for.

So, it looks like your filesystem is doing compression on its own.  I'm not sure why pgBackRest is not able to report it.  What kind of filesystem is it?  Is the compression done immediately or later?

**Comment by K3ndu** [comment]
It's a ZFS filesystem on Freenas and compression is done on the fly.

**Comment by dwsteele** [comment]
We haven't tested with ZFS recently but I can't see any difference between the older Perl code (which we have tried) and the newer C code.

How are you connecting to freenas?  NFS?  Perhaps it is reporting the apparent size?

Basically, we are using the st_size field from stat() to determine the size on disk.  If compression is not reported there then pgBackRest will not see it.
