### ISSUE TITLE
unable to give path of stand_by host for storing backups...

### ISSUE THREAD

**Issue by yeswithae** [pgbackrest/pgbackrest#899]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1.  pgBackRest version:2.20

2. PostgreSQL version:psql (PostgreSQL) 12.1 (Ubuntu 12.1-1.pgdg18.04+1)

3.  Operating system/version - linux (ubuntu )
    both database host and backup server using same version

4. Did you install pgBackRest :From package

    pgbackrest.conf` file(s)

[rtt_cluster]
pg1-path=/mnt/volume_blr1_01/dbbackup
pg1-host=139.59.6.129
[global]
repo1-cipher-pass=zWaf6XtpjIVZC5444yXB+cgFDFl7MxGlgkZSaoPvTGirhPygu4jOKOXf9LO4vjfO
repo1-cipher-type=aes-256-cbc
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y

[global:archive-push]
compress-level=3

    postgres.conf:

archive_command = 'pgbackrest --stanza=rtt_cluster archive-push %p'
archive_mode = on
hot_standby = on
listen_addresses = '*'
log_filename = 'postgresql.log'
log_line_prefix = ''
max_wal_senders = 3
wal_level = replica

5.Describe the issue:
For remote backup,I have given path as mentioned below for stand_by host in primary server(i.e, backup server).while stanza create command has given issue is raising saying pg_control is missing.

> ERROR: [055]: raised from remote-0 protocol on '139.59.6.129': unable to open missing file '/mnt/volume_blr1_01/dbbackup/global/pg_control' for read

**Comment by dwsteele** [comment]
I'm not sure what you are asking.  To do backup from standby you'd need a standby configured and `backup-standby=y`.

Your `pg1-path=/mnt/volume_blr1_01/dbbackup` looks suspiciously like a backup path.  Are you sure that's correct?  That seems to be the source of your immediate error.

**Comment by yeswithae** [comment]
Hi,Thanks for the input.But,I am taking  backup from repository not from standby.The pg1-path=/mnt/volume_blr1_01/dbbackup is a backup path only.

**Comment by dwsteele** [comment]
`pg1-path` is for setting the path to the PostgreSQL cluster, not the backup directory.

**Comment by yeswithae** [comment]
yes...I have changed the setting for PostgreSQL cluster, in repository stanza command has created whereas in standby while running stanza check command,Again,issue is raising as follows:

> ERROR: [055]: unable to open missing file '/mnt/volume_blr1_01/dbbackup/global/pg_control' for read

**Comment by dwsteele** [comment]
Well, this still looks like you've got a backup path `/mnt/volume_blr1_01/dbbackup` set for `pg1-path`.  You indicated you have multiple hosts but you have not provided list of hosts or config files for all of them.

All the configuration you need in in the user guide: https://pgbackrest.org/user-guide.html.

**Comment by yeswithae** [comment]
Hi,the path which I have given  /mnt/volume_blr1_01/dbbackup has to be set for repo1-path not for pg1-path.Because repo1-path is where backups and restores will be stored that i have changed and it is working.
