### ISSUE TITLE
How to fix missing full backup?

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#902]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.07

2. PostgreSQL version:
9.6.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
RHEL 6.10

4. Did you install pgBackRest from source or from a package?
Package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

As seen below, there's no `full backup: 20191130-222954`.  (I think someone rm'ed those files.)  How can I safely delete those files without corrupting the repository?

```
-bash-4.1$ pgbackrest info
stanza: localhost
    status: ok
    cipher: none
 
    db (current)
        wal archive min/max (9.6-1): 00000001000008A7000000DB / 000000010000092000000087
 
        incr backup: 20191130-222954F_20191202-000003I
            timestamp start/stop: 2019-12-02 00:00:03 / 2019-12-02 00:07:36
            wal start/stop: 00000001000008A7000000DB / 00000001000008A7000000DE
            database size: 1630.2GB, backup size: 22.9GB
            repository size: 1630.2GB, repository backup size: 22.9GB
            backup reference list: 20191130-222954F
 
        incr backup: 20191130-222954F_20191203-000002I
            timestamp start/stop: 2019-12-03 00:00:02 / 2019-12-03 00:11:32
            wal start/stop: 00000001000008AB000000D7 / 00000001000008AB000000E2
            database size: 1601.3GB, backup size: 39.5GB
            repository size: 1601.3GB, repository backup size: 39.5GB
            backup reference list: 20191130-222954F, 20191130-222954F_20191202-000003I
(snip)
        incr backup: 20191130-222954F_20191207-000002I
            timestamp start/stop: 2019-12-07 00:00:02 / 2019-12-07 00:15:43
            wal start/stop: 00000001000008B5000000E9 / 00000001000008B5000000E9
            database size: 1617.8GB, backup size: 49.9GB
            repository size: 1617.8GB, repository backup size: 49.9GB
            backup reference list: 20191130-222954F, 20191130-222954F_20191202-000003I, 20191130-222954F_20191203-000002I, 20191130-222954F_20191204-000002I, 20191130-222954F_20191205-000002I, 20191130-222954F_20191206-000002I
 
        full backup: 20200104-222755F
            timestamp start/stop: 2020-01-04 22:27:55 / 2020-01-05 01:32:35
            wal start/stop: 00000001000009190000006D / 00000001000009190000006D
            database size: 1632.7GB, backup size: 1632.7GB
           repository size: 1632.7GB, repository backup size: 1632.7GB
 
        incr backup: 20200104-222755F_20200106-000003I
            timestamp start/stop: 2020-01-06 00:00:03 / 2020-01-06 00:10:29
            wal start/stop: 000000010000091A0000006F / 000000010000091A00000074
            database size: 1634.6GB, backup size: 33.2GB
            repository size: 1634.6GB, repository backup size: 33.2GB
            backup reference list: 20200104-222755F
(snip)
        incr backup: 20200104-222755F_20200107-000002I
            timestamp start/stop: 2020-01-07 00:00:02 / 2020-01-07 00:14:37
            wal start/stop: 000000010000091E000000BB / 000000010000091E000000C4
            database size: 1642.3GB, backup size: 49.3GB
            repository size: 1642.3GB, repository backup size: 49.3GB
            backup reference list: 20200104-222755F, 20200104-222755F_20200106-000003I

```

**Comment by dwsteele** [comment]
Yeah, it looks like those incrementals won't be expired if the full is deleted manually from the repo.

The good news is you'll get an error if you try to restore any of them -- the bad news is that it seems the only way to get rid of them is more `rm`.  If you manually remove the incrementals that depended on the full then you should be OK.  The next time you run backup or expire you'll get warnings that the backups have been removed.

Caveat: You are running a pretty old version -- I tested this behavior on 2.20.  The behavior should be the same, though.

We'll have a look at this issue.  We should definitely be cleaning up orphaned backups, however they got that way.
