### ISSUE TITLE
Restore not Restoring Deleted Records

### ISSUE THREAD

**Issue by jaemoore** [pgbackrest/pgbackrest#903]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.15

2. PostgreSQL version: 9.4.15

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 

Only one server: centos-release-7-7.1908.0.el7.centos.x86_64

4. Did you install pgBackRest from source or from a package?

package

5. Please attach the following as applicable:
- `pgbackrest.conf` file(s) 
[pgbackrest.conf.log](https://github.com/pgbackrest/pgbackrest/files/4032781/pgbackrest.conf.log)

- `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
[postgresql.conf-sample.log](https://github.com/pgbackrest/pgbackrest/files/4032782/postgresql.conf-sample.log)

- errors in the postgresql log file before or during the time you experienced the issue
No Errors

- log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

[phantom-backup.log](https://github.com/pgbackrest/pgbackrest/files/4032773/phantom-backup.log)
[phantom-restore.log](https://github.com/pgbackrest/pgbackrest/files/4032774/phantom-restore.log)
[phantom-stanza-create.log](https://github.com/pgbackrest/pgbackrest/files/4032775/phantom-stanza-create.log)

7. Describe the issue:

We recently ran into an issue with pgbackrest.

The steps are basically:
- Perform full backup
- Delete database record
- Perform restore
- Database does not contain deleted record

However, performing the restore twice will restore the deleted record. 

We also have an export feature that tars the pgbackrest repo. Transferring the tar to a different machine and then restoring, will also restore the deleted record.

Any help would be greatly appreciated in diagnosing this issue.

**Comment by dwsteele** [comment]
I'm not able to reproduce this behavior following these instructions on the current version (2.20).

Multiple restores means multiple timelines.  The difference is how WAL is being applied (and perhaps even how quickly), but without the Postgres logs it's not possible to see what is going on.

**Comment by jaemoore** [comment]
I don't have access to the machine this was tried on, but I can do it on another. 

I'll provide the logs again and the postgresql log. Are there any other logs that would be useful?

**Comment by dwsteele** [comment]
I would be helpful to have the exact sequence of commands that were run.  Basically, whatever you do I need to be able to reproduce on my side.  Can this be reproduced on a clean database or does it need your dataset?  Clean database is preferred, of course.

**Comment by jaemoore** [comment]
Okay. I can get the exact sequence of commands that were run. 

Running on a clean database is more difficult since it's required for the product to work.
