### ISSUE TITLE
Compile pgBackRest on SLES 12

### ISSUE THREAD

**Issue by loehrson** [pgbackrest/pgbackrest#905]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 
2.20

2. PostgreSQL version: 
12.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: 
SLES 12

4. Did you install pgBackRest from source or from a package? 
source

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
n/a

7. Describe the issue:
We compiled postgres 12.1 from source on SLES 12
For the backup we would like to use pgbackrest 2.20, as well compiled from source. But we get the following error in the configure phase:

$ cd /x01/app/postgres/software/pgbackrest-release-2.20/src/
$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... -std=gnu99
checking for perl_parse in -lperl... yes
checking for PQconnectdb in -lpq... no
configure: error: library 'pq' is required

I saw for RH, the following package is necessary: postgresql-devel
For SLES, I found this in my repository: postgresql10-devel
Can this be used? Or are there different installation instructions for SLES?

Many thanks in advance! Really appreciate.
Roland

**Comment by dwsteele** [comment]
You need whichever package gives the most recent `libpq` development lib/headers on your platform.  It looks like `postgresql10-devel` will do the trick though it's possible there's a more specific package for this purpose.

Note that we will be releasing the pure C version of pgBackRest this week which has no Perl dependencies.

**Comment by tigerfoot** [comment]
@loehrson there's a dep in pgbackrest on pg_config you will find that binary in postgresql10-server-devel
We are on the way to fix that in pgbackrest (as the real only dep is libpq).

**Comment by loehrson** [comment]
@tigerfoot this would be great! I'll follow the upcoming releases to see when it it has been fixed. Thanks!
