### ISSUE TITLE
Can not restore backup because of ERROR:  requested WAL segment has already been removed

### ISSUE THREAD

**Issue by maipeng** [pgbackrest/pgbackrest#906]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.19

2. PostgreSQL version:10.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
debian 9

4. Did you install pgBackRest from source or from a package?
package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) 
[pgbackrest.txt](https://github.com/pgbackrest/pgbackrest/files/4053653/pgbackrest.txt)

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
[postgresql.txt](https://github.com/pgbackrest/pgbackrest/files/4053660/postgresql.txt)

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
We can not restore a backup on a slave .
pgbackrest --stanza=stanzaname --type=standby restore --compress-level-network=6 --log-level-console=trace --log-level-file=trace --log-level-stderr=trace --pg1-path=/var/lib/postgresql/10/main --process-max=6 --recovery-option=standby_mode=on --recovery-option="primary_conninfo=host=xx.xx.xx.xx user=replication password=xxxxxxxx" --recovery-option=recovery_target_timeline=latest --recovery-option=trigger_file=/tmp/postgresql.trigger --repo1-host=xx.xx.xx.xx

We have this error 
FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 00000002000164090000000B has already been removed

thanks

**Comment by dwsteele** [comment]
The two common ways to improve performance are to increase `process-max` or decrease `compress-level`.

Having said that, how fast do you really need your backup to run?  It's generally better to let the backup run a little more slowly and not put stress on your primary database.

**Comment by maipeng** [comment]
@dwsteele I've updated the title and added more information about our issue.

**Comment by dwsteele** [comment]
Please don't completely change the meaning of an issue.  If you have a new problem open a new issue.  You haven't provided any logs or details so it's pretty hard to see what might be going on.  At a minimum we'd need the postgres logs, current config files, and `recovery.conf` to diagnose anything.

Honestly, this looks like a misconfiguration on your part, not something wrong in pgBackRest.
