### ISSUE TITLE
Error: Config owner (postgres:111) and data owner (rtt:1000) do not match, and config owner is not root

### ISSUE THREAD

**Issue by yeswithae** [pgbackrest/pgbackrest#918]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.22

2. PostgreSQL version:psql (PostgreSQL) 12.1 (Ubuntu 12.1-1.pgdg18.04+1)

3. Operating system/version - Iam doing it locally (Ubuntu 12.1-1.pgdg18.04+1)

4. Did you install pgBackRest from source or from a package:From package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s):
 [rtt_cluster]
pg1-path=/var/lib/postgresql/12/rtt_cluster

[global]
repo1-path=/mnt/volume_blr1_01/dbbackup
repo1-cipher-pass=zWaf6XtpjIVZC5444yXB+cgFDFl7MxGlgkZSaoPvTGirhPygu4jOKOXf9LO4vjfO
repo1-cipher-type=aes-256-cbc
repo1-retention-full=2
repo1-retention-diff=2
log-level-file=detail

[global:archive-push]
compress-level=3
postgresql config:
archive_command = 'pgbackrest --stanza=rtt_cluster archive-push %p'
archive_mode = on
listen_addresses = '*'
log_line_prefix = ''
max_wal_senders = 3
wal_level = replica
             
  
7. Describe the issue:
I have created another user(i,e.,rtt)other than PostgreSQL user and tried to create stanza,issue raising saying that :

> ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/rtt_cluster-archive.lock': Permission denied

       HINT: does the user running pgBackRest have permissions on the '/tmp/pgbackrest/rtt_cluster-archive.lock' file?
After changing permissions when I restart the cluster error is raising like:.

> Error: Config owner (postgres:111) and data owner (rtt:1000) do not match, and config owner is not root

Can we do backup and restoring by changing user other than PostgreSQL.If "yes" then config.files (postgresql.conf)will be in postgres,how can I change it to other user.

**Comment by dwsteele** [comment]
Since PostgreSQL 11 is is possible to run pgBackRest as a user other than postgres, but it is a tricky configuration and we have not had time to test and document it yet.

**Comment by yeswithae** [comment]
okay....Thanq
