### ISSUE TITLE
2.23 build introduce postgresql server devel tools (pg_config)

### ISSUE THREAD

**Issue by tigerfoot** [pgbackrest/pgbackrest#920]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.23

2. PostgreSQL version: 9.6 to 12.x

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
openSUSE 15 / SLE 12 and 15 / Tumbleweed

4. Did you install pgBackRest from source or from a package?
Packaging from source 
[https://build.opensuse.org/package/show/server:database:postgresql/pgbackrest](build.opensuse.org )

7. Describe the issue:

With commit
https://github.com/pgbackrest/pgbackrest/commit/b1c5885017c035320804c5d16ed57b149a33ab10

dependency on pg_config is created for no valid reason. 

pg_config is used to locate server development files aka for example building a server extension.
it was abused during years, but since 1.5 year when you just need code linked to libpq you are encouraged to use pkg-config libpq 

So to handle and resolve what was attempted by the commit a another approach is needed.

For the moment I've created a patch that remove the commit on our package.

**Comment by dwsteele** [comment]
I'm a bit confused.  The dependency on `pg_config` has been there for a while, i.e. `pg_config --includedir`.

Having said that, using `pkg-config` is certainly a better idea.

**Comment by dwsteele** [comment]
Ah, yes, now I see why the second `pg_config` works and first one doesn't.  We've reverted `b1c588501`.

How do you feel about CMake?

**Comment by tigerfoot** [comment]
Thanks for your comment, since yesterday I discovered that effectively there was a pg_config call in the previous versions. Glad to know you discovered why it was working. I roughly guess a non call or non tracked returned error ?.

On my side to be able to build correctly client.c I've still a local patch 
https://build.opensuse.org/package/view_file/server:database:postgresql/pgbackrest/libpq-fe.h_localisation.patch?expand=1 which add the pgsql for finding libpq-fe.h (this can be completely specific to openSUSE/SUSE) 

For CMake, I'm would really appreciate it, it seems that most of open source project has used it, or migrate to it (Easier windows build certainly). I'm saying that as maintainer / packager, not the one who would wrote it completely ;-)

**Comment by dwsteele** [comment]
> Glad to know you discovered why it was working. I roughly guess a non call or non tracked returned error ?.
It looks like AC_CHECK_LIB() is setting the path so this will work.  I haven't delved into it, though.

>  I'm saying that as maintainer / packager, not the one who would wrote it completely ;-)

That's good -- I was asking you as a maintainer/packager!
