### ISSUE TITLE
Question about user guide.

### ISSUE THREAD

**Issue by igoryonya** [pgbackrest/pgbackrest#921]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.22

2. PostgreSQL version:
9.4.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 12.04.5 LTS x86_64 server

4. Did you install pgBackRest from source or from a package?
source

7. Describe the issue:
It's a question, not an issue:
I am going through a user guide https://pgbackrest.org/user-guide.html
Got to a Quick Start section 6.1 Setup Demo Cluster.
There, it suggests to configure a demo cluster, but it's not a new DB server. It already has databases, running on it. I am afraid, if creating a cluster, will damage or affect somehow the existing databases.
Can you tell if it's safe to do it on the live server and the existing databases will be intact?

**Comment by dwsteele** [comment]
*Do not* experiment on a production server.

You should set up a test system to run through the user guide and develop procedures for your production servers, which should then be tested on your development and staging servers before being deployed.
