### ISSUE TITLE
[Feature request] Index of the first WAL files for the timelines

### ISSUE THREAD

**Issue by psuderevsky** [pgbackrest/pgbackrest#925]
pgBackRest version: tested 2.19

PostgreSQL version: 11.6

Operating system/version - Centos 7.6

Did you install pgBackRest from source or from a package? - package

Config:
```
[platform]
pg1-path=/db/postgres/11/pgdata
repo1-cipher-pass=<redacted>
repo1-cipher-type=aes-256-cbc
repo1-s3-bucket=<redacted>
repo1-s3-endpoint=<redacted>
repo1-path=/bucket
repo1-s3-region=<redacted>
repo1-s3-key=<redacted>
repo1-s3-key-secret=<redacted>
repo1-type=s3<redacted>
repo1-s3-verify-ssl=n
repo1-retention-full=5
repo1-retention-diff=3
process-max=4
start-fast=n
stop-auto=n
backup-standby=n
compress=y
compress-level=5
spool-path=/dbwal/backrest
buffer-size=8388608

[platform:backup]
pg1-host=localhost
pg1-host-port=2293
pg1-path=/db/postgres/11/pgdata
pg2-path=/db/postgres/11/pgdata
compress-level=6
process-max=32

[platform:restore]
process-max=64 

[platform:archive-get]
archive-async=y
archive-get-queue-max=2GB
process-max=6

[platform:archive-push]
archive-async=y
archive-push-queue-max=8GB
process-max=6
```
Describe the issue:
PostgreSQL has a feature: if PostgreSQL starts recovery and finds a history file for a timeline that is higher than current one, it will request file with the segment for the future timeline (that most likely doesn't exist yet) and only then it will request file with that segment for the current timeline. 
If archive is located on remote storage it can take huge time to find that segments for the future timelines do not exist yet and therefore recovery can take too long (usualy it is easier to take new backup).
Example:
recovery.conf:
```
restore_command = 'echo -e "Searching WAL: %f, location: %p"; /usr/bin/pgbackrest --stanza=platform archive-get %f "%p"'
recovery_target_timeline = 'latest'
standby_mode = 'on'
```
postgresql log:
```
2019-12-06 07:11:16 CST  LOG:  database system was shut down in recovery
at 2019-12-06 07:11:08 CST
Searching WAL: 00000022.history, location: pg_wal/RECOVERYHISTORY
2019-12-06 07:11:16 CST  LOG:  restored log file "00000022.history" from
archive
Searching WAL: 00000023.history, location: pg_wal/RECOVERYHISTORY
2019-12-06 07:11:16 CST  LOG:  entering standby mode
Searching WAL: 00000022.history, location: pg_wal/RECOVERYHISTORY
2019-12-06 07:11:16 CST  LOG:  restored log file "00000022.history" from
archive
Searching WAL: 00000022000018C60000003F, location: pg_wal/RECOVERYXLOG
Searching WAL: 00000021000018C60000003F, location: pg_wal/RECOVERYXLOG
2019-12-06 07:11:20 CST  LOG:  restored log file
"00000021000018C60000003F" from archive
Searching WAL: 00000021.history, location: pg_wal/RECOVERYHISTORY
2019-12-06 07:11:20 CST  LOG:  restored log file "00000021.history" from
archive
Searching WAL: 00000022000018BF0000001B, location: pg_wal/RECOVERYXLOG
Searching WAL: 00000021000018BF0000001B, location: pg_wal/RECOVERYXLOG
2019-12-06 07:11:27 CST  LOG:  restored log file
"00000021000018BF0000001B" from archive
2019-12-06 07:11:27 CST  LOG:  redo starts at 18BF/1B311260
Searching WAL: 00000022000018BF0000001C, location: pg_wal/RECOVERYXLOG
Searching WAL: 00000021000018BF0000001C, location: pg_wal/RECOVERYXLOG
2019-12-06 07:11:34 CST  LOG:  restored log file
"00000021000018BF0000001C" from archive
Searching WAL: 00000022000018BF0000001D, location: pg_wal/RECOVERYXLOG
Searching WAL: 00000021000018BF0000001D, location: pg_wal/RECOVERYXLOG
2019-12-06 07:11:40 CST  LOG:  restored log file
"00000021000018BF0000001D" from archive
Searching WAL: 00000022000018BF0000001E, location: pg_wal/RECOVERYXLOG
Searching WAL: 00000021000018BF0000001E, location: pg_wal/RECOVERYXLOG
2019-12-06 07:11:46 CST  LOG:  restored log file
"00000021000018BF0000001E" from archive
Searching WAL: 00000022000018BF0000001F, location: pg_wal/RECOVERYXLOG
Searching WAL: 00000021000018BF0000001F, location: pg_wal/RECOVERYXLOG
2019-12-06 07:11:53 CST  LOG:  restored log file
"00000021000018BF0000001F" from archive
```
If standby is more than 1 timeline behind, it is even more nightmare.
With Patroni it can be an issue even after simple restart, because timeline is increased with service restart.
Each non-existing WAL search can take 2-10 seconds in my case (1gbit/s interconnect to AWS S3). So if 1000 files must be obtained, it would take `1000 * (current master timeline - current standby timeline) * [2-10]seconds + time of getting actually existing WALs`.

It would be great if pgBackRest had a feature to workaround this PostgreSQL behaviour. E.g. index file with the first WAL file name for each timeline, so it could check it first and not to search whole archive for the non-existing WAL.

**Comment by psuderevsky** [comment]
Probably fix can be implemented on the PostgreSQL development side.
https://www.postgresql.org/message-id/20200129.120222.1476610231001551715.horikyota.ntt%40gmail.com

**Comment by dwsteele** [comment]
You are right, this is a lot of negative requests that could possibly be avoided.  I think that Kyotaro's patch seems sane but let's see where that thread goes.

Having an index looks like a good idea but we would probably store that by timeline which might lead to some of the same performance penalties for negative requests.  Avoiding that will be complicated.

**Comment by psuderevsky** [comment]
Fix for this issue was included in latest minor PostgreSQL release.
```
Avoid scanning irrelevant timelines during archive recovery (Kyotaro Horiguchi)

This can eliminate many attempts to fetch non-existent WAL files from archive storage, which is helpful if archive access is slow.
```
So I believe this issue can be closed, Thanks, David.
