### ISSUE TITLE
Running restore hangs on defunct process

### ISSUE THREAD

**Issue by ejberdecia** [pgbackrest/pgbackrest#928]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.20

2. PostgreSQL version: 11.1

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Linux  3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

4. Did you install pgBackRest from source or from a package? 
package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `
[detail_pgbackrest_error.txt](https://github.com/pgbackrest/pgbackrest/files/4140432/detail_pgbackrest_error.txt)
max_wal_senders`, `wal_level`, `port`)
archive_command= pgbackrest --stanza=anly_heds archive-push %p
archive_mode=on
listen_address=*
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
While running a restore --delta command, at times the pgbackrest process goes into a defunct state. I'm able to cd to the postgres PGDATA directory and manually run the archive-get command then cd to the pg_wal directory and
[pgbackrest_conf.txt](https://github.com/pgbackrest/pgbackrest/files/4140430/pgbackrest_conf.txt)

 rename the RECOVERYXLOG file then kill the pgbackrest parent defunct process and the restore continues.

**Comment by dwsteele** [comment]
To be clear, this is after the restore completes and while PostgreSQL is doing recovery?

This sounds a bit like #834, which we have not made any progress on.  Hopefully this will help.

**Comment by ejberdecia** [comment]
That is correct, is after the restore completes and while Postgresql is recalling the wal logs from the archive that it hangs with a defunct process.
It does looks very similar to #834.
In my case is strange that at times it does get passed a particular wal file to only get stuck on some other "random" log file request.
Thanks,Efrain J. Berdecia 

    On Friday, January 31, 2020, 11:56:01 PM EST, David Steele <notifications@github.com> wrote:  
 
 
To be clear, this is after the restore completes and while PostgreSQL is doing recovery?

This sounds a bit like #834, which we have not made any progress on. Hopefully this will help.

**Comment by ejberdecia** [comment]
For what is worth... I'm noticing that at times when manually run pgbackrest command, it seems to go on a loop and keep grabbing more wal files than just the one I asked for and it does go into a defunct state eventually. Having said that, while it goes into that loop postgres keeps applying the logs;
pgbackrest --reset-pg1-host --pg1-path=/localpart0/db/postgres/11/heds_meta/data --stanza=anly_heds archive-get 00000001000283A400000049 pg_wal/RECOVERYXLOG --log-level-stderr=debug --log-level-console=detail
DEBUG:     storage/storage::storageExists: => false
DEBUG:     command/archive/common::archiveAsyncStatus: (archiveMode: 1, walSegment: {"00000001000283AD00000014"}, confessOnError: true)
DEBUG:     storage/storage::storageExists: (this: {type: posix, path: {"/localpart0/db/postgres/pgbackrest/spool"}, write: false}, pathExp: {"<SPOOL:ARCHIVE:IN>/00000001000283AD00000014.ok"}, param.timeout: 0)
DEBUG:     storage/storage::storageExists: => false
DEBUG:     storage/storage::storageExists: (this: {type: posix, path: {"/localpart0/db/postgres/pgbackrest/spool"}, write: false}, pathExp: {"<SPOOL:ARCHIVE:IN>/00000001000283AD00000014.error"}, param.timeout: 0)
DEBUG:     storage/storage::storageExists: => false
DEBUG:     storage/storage::storageExists: (this: {type: posix, path: {"/localpart0/db/postgres/pgbackrest/spool"}, write: false}, pathExp: {"<SPOOL:ARCHIVE:IN>/global.error"}, param.timeout: 0)
DEBUG:     storage/storage::storageExists: => false
DEBUG:     command/archive/common::archiveAsyncStatus: => false
DEBUG:     storage/storage::storageExists: (this: {type: posix, path: {"/localpart0/db/postgres/pgbackrest/spool"}, write: false}, pathExp: {"<SPOOL:ARCHIVE:IN>/00000001000283AD00000014"}, param.timeout: 0)
DEBUG:     storage/storage::storageExists: => false

**Comment by ejberdecia** [comment]
postgres@dtord03pgm33p:~>ps -ef|grep pgbackrest
postgres 38539 49756  0 22:26 pts/1    00:00:00 pgbackrest --reset-pg1-host --pg1-path=/localpart0/db/postgres/11/heds_meta/data --stanza=anly_heds archive-get 00000001000283AD00000014 pg_wal/RECOVERYXLOG --log-level-stderr=debug --log-level-console=detail
postgres 38540 38539  0 22:26 ?        00:00:00 [pgbackrest] <defunct>
postgres 41382 18767  0 22:29 ?        00:00:00 pgbackrest --reset-pg1-host --pg1-path=/localpart0/db/postgres/11/heds_meta/data --stanza=anly_heds archive-get 00000001000283B0000000D4 pg_wal/RECOVERYXLOG
postgres 41383 41382  0 22:29 ?        00:00:00 [pgbackrest] <defunct>
postgres 41877 31633  0 22:31 pts/0    00:00:00 grep --color=auto pgbackrest

**Comment by dwsteele** [comment]
> I'm noticing that at times when manually run pgbackrest command, it seems to go on a loop and keep grabbing more wal files than just the one I asked for

This is the purpose of async mode.  It looks ahead so that future files are already in the spool dir when Postgres requests them.

We are looking at the daemon-izer code.  We think there may be a problem because the parent can exit before the child process in some cases.  That would explain why this only happens sometimes.

**Comment by dwsteele** [comment]
We believe this is fixed at e2c304d47.  Let's see how it goes after the next release.  If you are still seeing the problem we'll reopen this issue.

**Comment by ejberdecia** [comment]
Thanks

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 12, 2020 at 4:00 PM, David Steele<notifications@github.com> wrote:   
Closed #928.
