### ISSUE TITLE
Error expiring full backup from older timeline

### ISSUE THREAD

**Issue by sean0101n** [pgbackrest/pgbackrest#929]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.20

2. PostgreSQL version: 9.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Original backup was run on RHEL 7.2 server.  Newer backup was run on CentOS 7.7

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)

```[global]
backup-user=postgres
log-level-file=detail
compress-level=6
archive-async=y
process-max=6
archive-push-queue-max=150GB
spool-path=/pg_dir/pg95_dir/wal

[ocean]
repo1-s3-bucket=dbbackups
repo1-path=/ocean
pg1-path=/pg_dir/pg95_dir/data
repo1-s3-endpoint=s3.us-east-1.amazonaws.com
repo1-s3-region=us-east-1
repo1-type=s3
start-fast=y
repo1-s3-key=<redacted>
repo1-s3-key-secret=<redacted>
repo1-retention-full=1
repo1-retention-diff=1
```

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

```listen_addresses = '*'
archive_mode = on
archive_command = 'pgbackrest --stanza=ocean archive-push %p'
max_wal_senders = 5
wal_level = hot_standby
port = 5432
```

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
After creating a backup on the RHEL server, I restored to the CentOS server and had both databases running at the same time.  The RHEL server was shut off, then a full backup was created on the CentOS server.  After the backup finished, the expire command was set to remove the original backup, but I received this error:

```
2020-02-01 04:30:49.261 P00   INFO: expire command begin 2.20: --log-level-console=warn --log-level-file=info --repo1-path=/ocean --repo1-retention-diff=1 --repo1-retention-full=1 --repo1-s3-bucket=dbbackup --repo1-s3-endpoint=s3.us-east-1.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-east-1 --repo1-type=s3 --stanza=ocean 
2020-02-01 04:30:49.494 P00   INFO: expire full backup set: 20191215-072556F, 
20191215-072556F_20191226-110729D, 20191215-072556F_20200105-202645I                                                                                      
2020-02-01 04:30:49.759 P00   INFO: remove expired backup 20191215-072556F_20200105-202645I                         
2020-02-01 04:30:57.144 P00   INFO: remove expired backup 20191215-072556F_20191226-110729D                         
2020-02-01 04:31:05.913 P00   INFO: remove expired backup 20191215-072556F                                          
2020-02-01 04:31:16.432 P00  ERROR: [060]: unable to remove file 'ocean/backup/ocean/20191215-072556F/pg_tblspc/133704/PG_9.5_201510051/16407/133892.7.gz': [InternalError] We encountered an internal error. Please try again.
2020-02-01 04:31:16.433 P00   INFO: http statistics: objects 2, sessions 386, requests 28245, retries 101, closes 284
2020-02-01 04:31:16.433 P00   INFO: expire command end: aborted with exception [060]
```

There was also a diff and incr backup on the original server that expired fine before pgbackrest tried expiring the full backup.  I have also tried executing the expire command by itself and receive the same error, however it's not always the same file that it fails on.  Also, running the info command does not show this backup set.  Is it safe manually remove the backup set?

**Comment by dwsteele** [comment]
You can safely delete the backup directory, but `[InternalError] We encountered an internal error. Please try again.` is a pretty nasty S3 error.

Let us know if you are successful deleting this directory via the web interface.  Note that you will get a warning on the next backup that this directory was removed.

**Comment by sean0101n** [comment]
@dwsteele I was able to remove it successfully, thanks for the quick response!

**Comment by dwsteele** [comment]
We don't expect any specific files when doing the delete (i.e., we don't work from the manifest).  Even if we did delete a non-existent file, S3 does not error in that case.  The fact that you are getting an `internal error` means something is wrong on their side.  Hopefully that kind of issue is rare.

**Comment by sean0101n** [comment]
It seems to error out again when trying to purge old archives.  Just to be sure, If I take a look at the oldest backup, I should be able to manually remove any WAL up to, but not including the "wal start", correct?

**Comment by dwsteele** [comment]
Yes, that will work.

We would sure like to see a trace log of an `expire` command before you do that.  This looks like an S3 malfunction, but you never know...

**Comment by sean0101n** [comment]
Unfortunately (well, technically fortunately), after running the expire command manually, it finished without error.  If it pops up again, I'll try to get a trace log for you.

**Comment by levkk** [comment]
Hi there,

I'm seeing the same issue with S3 and archive cleaning. When running expire automatically as part of back up, it pretty consistently fails with this error `[060]: unable to remove file`. When I look in S3, the file isn't there.

I'm using PostgreSQL 12 and pgBackRest 2.26.

**Comment by dwsteele** [comment]
The retry logic is here: https://github.com/pgbackrest/pgbackrest/blob/release/2.27/src/common/io/http/client.c#L453

Internal errors are so common from AWS S3 that you often can't complete a single backup without retries. In some environments they are more common than others.

We already retry these errors for 60 seconds by default but it may help to increase `io-timeout`.  We use a Fibonacci back-off for retries so a longer `io-timeout` will provide longer retry intervals which may help if the issue is rate limiting.

**Comment by dwsteele** [comment]
Looks like this was a bug after all. See #1650 for details.
