### ISSUE TITLE
Restoring to new server

### ISSUE THREAD

**Issue by luthv** [pgbackrest/pgbackrest#931]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.20

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Repo host server: Ubuntu 18.04
Target server: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package?
package

5. Describe the issue:
I'm trying to restore to a new server, I'm not creating a standby server, I just want to restore a previous version of the database to another server and do some query to compare the old data with the currently running database.
I'm using this command to restore the backup in the new server:

`pgbackrest --stanza=devdbmicro --delta --target=20200202-170001F_20200206-170001D --type=name`

but the new cluster failed to start with this error:
```
LOG:  unrecognized configuration parameter "restore_command" in file "/var/lib/postgresql/9.6/main/postgresql.auto.conf" line 5
LOG:  unrecognized configuration parameter "recovery_target_name" in file "/var/lib/postgresql/9.6/main/postgresql.auto.conf" line 6
FATAL:  configuration file "/var/lib/postgresql/9.6/main/postgresql.auto.conf" contains errors
```

**Comment by luthv** [comment]
It turns out that I was restoring from postgres v12 to v9.6, so pgbackrest created the postgresql.auto.conf instead of recovery.conf file.

On a side note, is there any documentation on how to restore to another server that is not a standby server? Because all the other questions regarding remote restore always get referred to the standby restore documentation.

**Comment by dwsteele** [comment]
> It turns out that I was restoring from postgres v12 to v9.6

Yes, the recovery configuration is written based on the PostgreSQL version stored in the backup, not on the restore path or what version of PostgreSQL is installed locally.

> On a side note, is there any documentation on how to restore to another server that is not a standby server?

Well, to some extent every restored cluster starts as a standby (i.e. it is in recovery) before it is promoted to primary.

Sections 6.12, 10, and 11 talk about restoring to a primary.  Note that if you restore a new primary for testing purposes (i.e. the real primary is still running) you'll want to disable archiving.

**Comment by luthv** [comment]
> Sections 6.12, 10, and 11 talk about restoring to a primary. Note that if you restore a new primary for testing purposes (i.e. the real primary is still running) you'll want to disable archiving.

Thanks. I ended up using the PITR guide with target-action=promote, also my understanding is that pgbackrest will not modify any configuration in postgresql.conf so if I start with clean cluster data then this should be safe right? Since no archiving configuration is set with the default config. Is this the correct assumption?

**Comment by dwsteele** [comment]
This is correct for Debian/Ubuntu.  Other platforms store the config in the PGDATA directory.  `postgresql.auto.conf` is always in the PGDATA directory so be careful of settings there as well.
