### ISSUE TITLE
archive-get command causes "Invalid user (null)" in auth.log

### ISSUE THREAD

**Issue by Underhunden** [pgbackrest/pgbackrest#933]
1. pgBackRest version:
pgBackRest 2.23

2. PostgreSQL version:
11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
CentOS 7 latest and greatest.

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[main]
pg1-host=*
pg1-path=/var/lib/pgsql/11/data
pg2-host=*
pg2-path=/var/lib/pgsql/11/data

[global]
backup-standby=y
archive-async=y
archive-copy=n
spool-path=/db/logs/spool
start-fast=y
stop-auto=y
process-max=8
repo1-cipher-type=none
repo1-path=/backup
repo1-retention-diff=2
repo1-retention-full=2
repo1-s3-bucket=****
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-region=*****
repo1-s3-ca-file=*****
repo1-type=s3
repo1-s3-verify-tls=n

[global:archive-push]
compress-level=3

    - errors in the postgresql log file before or during the time you experienced the issue
ERROR: [125]: remote-0 process on '***' terminated unexpectedly [255]: Permission denied (publickey).
ERROR: [125]: remote-0 process on '***' terminated unexpectedly [255]: Permission denied (publickey).
ERROR: [125]: remote-0 process on '***' terminated unexpectedly [255]: Permission denied (publickey).
ERROR: [125]: remote-0 process on '***' terminated unexpectedly [255]: Permission denied (publickey).
ERROR: [125]: remote-0 process on '***' terminated unexpectedly [255]: Permission denied (publickey).
ERROR: [125]: remote-0 process on '***' terminated unexpectedly [255]: Permission denied (publickey).

 - errors in pg1-host auth.log
Feb 10 21:11:33 *** sshd[34047]: Invalid user (null) from 10.*.*.* port 46252
Feb 10 21:11:33 *** sshd[34047]: input_userauth_request: invalid user (null) [preauth]

7. Describe the issue:
We use pgbackrest as a tool for restoring periodically, since a few versions ago this started popping up in our logs when trying to catch up to the master from the repository. The whole restore works perfectly, but as soon as the restore_command in recovery.conf gets executed we get the stated error(s). The same goes running the restore_command manually: 
restore_command = 'pgbackrest --stanza=main archive-get %f "%p"'

However, downgrading to version 2.16 does not cause the errors to show up and the restore_command works perfectly.

Ssh keys are all setup.

**Comment by dwsteele** [comment]
Can we get debug output for the archive-get command?  I'd like to see what the command sent to ssh looks like.

The config above looks like it is on a repo host.  What does the config on your pg host look like?

**Comment by dwsteele** [comment]
Ah, this is probably related to #924.  pgBackRest gets confused because pg1-host is set and it thinks the pg host must be remote.

We believe this behavior would have been the same in older Perl versions, but it has worked for a long time in C because backup is the only command that needs a remote connection to a pg host and that was migrated last (and was started in 2.17).

That being said, it seems like restore should run into the same problem.  Try passing `--reset-pg1-host` to the restore command and see if it works.

**Comment by Underhunden** [comment]
After your comment about passing --reset-pg1-host to the restore command, we tested it with the archive-get command in restore_command. It now seems to be working. Happy days!

We already had it with the restore command so you are right about the "restore" would have failed as well.

pg1-host for us is always the master and pg2-host is always localhost. We usually run the backup from one of the replicas. The master host does not have a pg2-host in its pgbackrest config file. Not sure if this information is useful.

On 2.16 it does work without --reset-pg1-host in the archive-get command. Not on 2.17+. Perhaps this should be noted somewhere.

Thank you for your lightning fast replies :)

**Comment by Underhunden** [comment]
Would you still like to have a debug output?

**Comment by dwsteele** [comment]
> Would you still like to have a debug output?

No, thanks.  We still need to figure out how to resolve this issue (fix or document) but it's pretty clear what is going on.

**Comment by dwsteele** [comment]
We have restored the original error, see 6353e9428, so at least it will be obvious what is happening when pgbackrest is configured this way.

We have a long-term plan for dealing with this -- a `pg-local-id` option that allows you to set a pg host as local even if there are host settings.  But, that's a too big to make this release and we are still working on the best way to implement it.
