### ISSUE TITLE
[Question] Specify multiple parameters in recovery-option

### ISSUE THREAD

**Issue by Anthares** [pgbackrest/pgbackrest#944]
Dear Team,

I want to specify both `primary_conninfo` and `primary_slot_name` in `recovery-option` but I cannot find the syntax neither in pgbackrest documentation nor in existing issues.

Could you tell me how to do it ?

Thanks,

Nicolas

**Comment by dwsteele** [comment]
You can specify `recovery-option` as many times as you like.  So in the config:
```
recovery-option=x
recovery-option=y
```
At the command line:
```
--recovery-option=x --recovery-option=y
```

**Comment by Anthares** [comment]
Hello David,

Thank you for the answer.
I just realised I missed that point in the documentation, so sorry for the waste of time.

Best regards,

Nicolas
