### ISSUE TITLE
Is there a way to delete a specific full backup by providing a label

### ISSUE THREAD

**Issue by hlakshmi** [pgbackrest/pgbackrest#953]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.22

2. PostgreSQL version: Postgres 11

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

**Comment by dwsteele** [comment]
Not currently, but we are planning to implement this soon: https://github.com/pgbackrest/pgbackrest/projects/2#card-34196669

You can expire the *oldest* full backups by running the `expire` command directly with a custom `repo1-retention-full` setting.

**Comment by dwsteele** [comment]
You can remove a specific backup as of pgBackRest 2.27. See the `--set` option for the expire command: https://pgbackrest.org/command.html#command-expire.
