### ISSUE TITLE
recovery-target-action pause missing in recovery.conf

### ISSUE THREAD

**Issue by devops93** [pgbackrest/pgbackrest#958]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 
2.24

2. PostgreSQL version: 
EnterpriseDB 10.12.20 on x86_64-pc-linux-gnu

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Debian 9 - Stretch

4. Did you install pgBackRest from source or from a package?
Debian's deb package (from PGDG)

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

Hi David,

A simple question. Unless I am mistaken, when we specify the option --target-action=pause, a line should appear (explicitly) in recovery.conf like shutdown ?
`recovery_target_action = 'pause'`

The corresponding restore command :
`$ pgbackrest --stanza=master10 --set=20200228-170933F_20200302-102818I --type=time "--target=2020-03-04 16:10:00" --target-action=pause restore`

Thanks

Files : 
[postgresql_conf.txt](https://github.com/pgbackrest/pgbackrest/files/4307803/postgresql_conf.txt)
[recovery_conf.txt](https://github.com/pgbackrest/pgbackrest/files/4307715/recovery_conf.txt)
[pgbackrest_conf.txt](https://github.com/pgbackrest/pgbackrest/files/4307781/pgbackrest_conf.txt)

**Comment by dwsteele** [comment]
The default value for `recovery_target_action` is `pause` so we don't write it.  See https://www.postgresql.org/docs/10/recovery-target-settings.html.

In PG <= 9.5 there was an boolean option called `pause_at_recovery_target` instead.

The pgBackRest default for `target-action` is also `pause` so there's not need to specify it unless you need to override a config setting elsewhere.

**Comment by devops93** [comment]
Initially I thought that specifying it **explicitly** would have added the option to the file recovery.conf.

Thanks
