### ISSUE TITLE
Page-level incremental backups

### ISSUE THREAD

**Issue by szhem** [pgbackrest/pgbackrest#959]
I'm currently choosing a backup solution and there are three most feature-complete ones:
- [pgBackRest](https://github.com/pgbackrest/pgbackrest)
- [WAL-G](https://github.com/wal-g/wal-g)
- [pg_probackup](https://github.com/postgrespro/pg_probackup)

I would choose pgBackRest, but currently its incremental backups work only on the file level comparing to the page-level incremental backups of WAL-G and pg_probackup.

So are there any plans to implement page-level incremental backups in pgBackRest?

**Comment by dwsteele** [comment]
We are currently working on a page-level incremental implementation but do not have a release date.  Possibly May or June but certainly by the end of summer.

**Comment by philflorent** [comment]
Hi David,
Sounds highly promising. Do you already have a global idea about the specifications ? One of our concerns is about rather large databases...that are not considered very large these days (e.g 20Tb but only XXGb of daily changes). 
For very large databases, we have to use different methods anyway but page level incremental backups could eliminate the need to use them for smaller databases.  
Incremental backups are even more useful if they completely eliminate the need to do periodical full backups. A commercial product calls that "incrementally updated backups" : one initial copy of the database (full backup) then incremental backups only. The incremental backup produced N days ago is used to roll forward the full backup and an incremental backup is produced. It's not useful for VLDB if the amount of daily changes is too important anyway but it's still interesting.
Regards
Phil

**Comment by szhem** [comment]
Hi @dwsteele,

That's good to know! Thank you!

**Comment by Wim1234** [comment]
555555

**Comment by Wim1234** [comment]
sorry,

**Comment by Wim1234** [comment]
Our team discuss the pgbackrest vs pg_probackup,
page-level incr  is the BIG point
I perfer the pgbackrest,
but....

**Comment by dwsteele** [comment]
@Wim1234 This feature is still a high priority on our roadmap and is in progress but we don't have a release date yet.

**Comment by Wim1234** [comment]
Good news, thanks u.

**Comment by dwsteele** [comment]
Added project card: https://github.com/pgbackrest/pgbackrest/projects/2#card-84439046.

**Comment by dwsteele** [comment]
This will be included in pgBackRest 2.44 as an internal feature (i.e. don't use in production) and it would be helpful if you could test against your workload and provide feedback.
