### ISSUE TITLE
pgbackrest restore unable to load info file

### ISSUE THREAD

**Issue by qoo100116** [pgbackrest/pgbackrest#965]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
==>pgBackRest 2.24
2. PostgreSQL version:
==>PostgreSQL 11.7
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
==>NO ,master and pgbackrest together
4. Did you install pgBackRest from source or from a package?
==>package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
```
  [global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2

[demo]
pg1-path=/var/lib/pgsql/11/data
```
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)

max_wal_senders = 10
wal_keep_segments = 20
listen_addresses = '*'
port = 5432
wal_level = replica 
fsync = on
synchronous_commit = on
full_page_writes = on
archive_mode = on
archive_command = '/usr/bin/pgbackrest --stanza=demo archive-push %p'

    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
```
-------------------PROCESS START-------------------
2020-03-17 16:14:07.377 P00   INFO: stanza-create command begin 2.24: --log-level-console=detail --pg1-path=/var/lib/pgsql/11/data --repo1-path=/var/lib/pgbackrest --stanza=demo
2020-03-17 16:14:07.894 P00   INFO: stanza-create command end: completed successfully (518ms)
-bash-4.2$ cat demo-expire.log 
-------------------PROCESS START-------------------
2020-03-17 16:25:16.346 P00   INFO: expire command begin 2.24: --log-level-console=detail --repo1-path=/var/lib/pgbackrest --repo1-retention-full=2 --stanza=demo
2020-03-17 16:25:16.349 P00   INFO: full backup total < 2 - using oldest full backup for 11-1 archive retention
2020-03-17 16:25:16.450 P00   INFO: expire command end: completed successfully (104ms)

-------------------PROCESS START-------------------
2020-03-17 16:33:22.186 P00   INFO: expire command begin 2.24: --log-level-console=detail --repo1-path=/var/lib/pgbackrest --repo1-retention-full=2 --stanza=demo
2020-03-17 16:33:22.189 P00   INFO: full backup total < 2 - using oldest full backup for 11-1 archive retention
2020-03-17 16:33:22.291 P00   INFO: expire command end: completed successfully (105ms)
```

7. Describe the issue:
The information of /var/log/pgbackrest all show successfully, but the log of PostgreSQL shows the wrong information as below:

```
ERROR: [055]: unable to load info file '/var/lib/pgbackrest/archive/demo/archive.info' or '/var/lib/pgbackrest/archive/demo/archive.info.copy':
       FileMissingError: unable to open missing file '/var/lib/pgbackrest/archive/demo/archive.info' for read
       FileMissingError: unable to open missing file '/var/lib/pgbackrest/archive/demo/archive.info.copy' for read
       HINT: archive.info cannot be opened but is required to push/get WAL segments.
       HINT: is archive_command configured correctly in postgresql.conf?
       HINT: has a stanza-create been performed?
       HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
```

**Comment by dwsteele** [comment]
This is due to the archive_command failing. Did you run the check command as recommended in the user guide (https://pgbackrest.org/user-guide.html#quickstart/check-configuration)?

It seems the `postgres` user is not able to access `/var/lib/pgbackrest` but not sure why if it is all on the same system.  Add `--log-level-console=debug` to the `archive_command` and see if we get some more info.

**Comment by qoo100116** [comment]
Thank you! David 
I had rebuilt the stanza and check the privileges of pgbackrest, then it didn’t show the wrong messages after I checked command.

**Comment by dwsteele** [comment]
Glad you got it fixed!
