### ISSUE TITLE
archive expiration cannot continue - archive and backup history lists do not match

### ISSUE THREAD

**Issue by melrifa1** [pgbackrest/pgbackrest#966]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.24
2. PostgreSQL version:
11.5
3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Debian Stretch
4. Did you install pgBackRest from source or from a package?
Source
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
```
[global]
log-level-console=warn
log-level-file=info
log-level-stderr=warn
repo-s3-bucket=<redacted>
repo-s3-endpoint=<redacted>
repo-s3-key=<redacted>
repo-s3-key-secret=<redacted>
repo-s3-region=<redacted>
repo-type=s3
retention-full=2000
retention-diff=2000
start-fast=y
stop-auto=y
backup-standby=n
repo-path=/my_repo_path
recovery-option=standby_mode=on
archive-async=y
spool-path=/data/postgresql/spool
process-max=2
compress-level=1
log-level-console=error
log-level-stderr=info
[mydb]
db-path=/data/postgresql/11
db-port=5432
```
```
archive_command: '/usr/bin/pgbackrest --config /conf/postgresql/pgbackrest.conf --stanza=formation archive-push %p
max_wal_senders: 12
archive_mode: 'on'
wal_level: hot_standby
```
7. Describe the issue:
We recently upgraded from pgbackrest 2.20 to version 2.24 and we have a deployment with backups taken with v2.20 and currently it is failing to take new backup with version 2.24. The failure is happening at the WAL expiry level as I can see new backups taken when listing the backups available by pgbackrest.

```
INFO: last backup label = 20200315-163154F, version = 2.20
INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
INFO: backup start archive = 0000001C00000001000000D3, lsn = 1/D3000028
WARN: a timeline switch has occurred since the 20200315-163154F backup, enabling delta checksum
INFO: backup file /data/postgresql/11/base/1/1255 (632KB, 2%) checksum ca42ef4dd7d40c8aae498455dd2f666040cb38c2
INFO: backup file /data/postgresql/11/base/16471/1255 (632KB, 4%) checksum 14e3f2d7ac60b783e0bc2cbbd0113e23521e6040
INFO: backup file /data/postgresql/11/base/13340/1255 (616KB, 9%) checksum 39b6d687ae0e75068c21abe03baf19113be5332e
INFO: backup file /data/postgresql/11/base/16471/2608 (448KB, 12%) checksum 162651735b6bc90e9053facfd2fe6b81343b6a23
INFO: backup file /data/postgresql/11/base/1/2608 (448KB, 37%) checksum aaeab941c3ccdd3b77d4a2c6fd67198be88ac49a
INFO: backup file /data/postgresql/11/base/16471/2691 (264KB, 39%) checksum 48d208b9fed220db0bdf86a21824eefb1d9d25af
INFO: backup file /data/postgresql/11/base/1/2691 (264KB, 52%) checksum e0b81f67108f5f003ba98f9671ba2fcc698749a3
INFO: backup file /data/postgresql/11/base/16471/2690 (88KB, 52%) checksum c2c6007a7938bfd2bd90194c4682bc40fd037ed6
INFO: backup file /data/postgresql/11/base/1/2690 (88KB, 68%) checksum 91f3a8d9e1559e9f78c49b2a34572b29cb9b72cc
INFO: backup file /data/postgresql/11/base/1/1255_fsm (24KB, 77%) checksum af2c836234f1b313be7f84355a7f5f7bda881a94
INFO: backup file /data/postgresql/11/base/16471/1255_fsm (24KB, 88%) checksum f5c135ffb1040ad53a13cbda5f28490caad1057d
INFO: backup file /data/postgresql/11/global/pg_control (8KB, 88%) checksum a1f161bb3651f7a00fdb9efb42b92773ab42f5c9
INFO: backup file /data/postgresql/11/global/2964 (8KB, 88%) checksum 213da78b4478f59eb5bab6f3673c72c8c02c479e
INFO: backup file /data/postgresql/11/global/1261 (8KB, 88%) checksum 32cdd5c9bcb63fac41a7e0dc9158bfa83c0e9fcf
INFO: backup file /data/postgresql/11/global/1260 (8KB, 97%) checksum 4d426734997da14ea2c7de990cf351c665c0ffe2
INFO: backup file /data/postgresql/11/patroni.dynamic.json (1.7KB, 100%) checksum a607a3bf8e5aa8e91989876fc41657c9a505334e
INFO: diff backup size = 30.4MB
INFO: execute non-exclusive pg_stop_backup() and wait for all WAL segments to archive
INFO: backup stop archive = 0000001C00000001000000D3, lsn = 1/D3000130
INFO: check archive for segment(s) 0000001C00000001000000D3:0000001C00000001000000D3
INFO: new backup label = 20200315-163154F_20200317-213408D
INFO: http statistics: objects 2, sessions 2, requests 202, retries 0, closes 0
INFO: backup command end: completed successfully (31771ms)
INFO: expire command begin 2.24: --config=/conf/postgresql/pgbackrest.conf --log-level-console=info --log-level-file=debug --log-level-stderr=info --log-path=/data/postgresql/pgbackrest_logs/pgbackrest_global_logs --repo1-path=/postgresql_backup_cffa0cee-082c-4695-8b73-91f3e8437d93 --repo1-retention-diff=2000 --repo1-retention-full=2000 --repo1-s3-bucket=cffa0cee-082c-4695-8b73-91f3e8437d93 --repo1-s3-endpoint=s3-api.us-geo.objectstorage.service.networklayer.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-standard --repo1-type=s3 --stanza=formation
ERROR: [029]: archive expiration cannot continue - archive and backup history lists do not match
INFO: http statistics: objects 2, sessions 2, requests 390, retries 0, closes 0
INFO: expire command end: aborted with exception [029]
```

**Comment by dwsteele** [comment]
The good news is your backup was successful: `backup command end: completed successfully (31771ms)`.  But the expire command did fail.  This is not critical but of course you'll be using more space in your repo.

Are you sure you upgraded from 2.20?  This change (b498188f01f8d2ccd) went out with 2.15 and was designed to catch issues introduced by `stanza-update --force` after files had been deleted from the repo.  Any chance you had that happen in the past?

Can you please provide your `[repo]/archive/archive.info` and `[repo]/backup/backup.info` files? We like to see what's wrong and more than likely we can provide you with updated files that will work.

**Comment by melrifa1** [comment]
At one point we were using v2.15 and then we upgraded to 2.19, 2.22 and downgraded to 2.20 and finally upgraded to 2.24. This follow of upgrades happened across almost a year. Attached are the files you asked for, and I do see in `arcchive.info` it says `backrest-version="2.15"` but in `backup.info` it says `backrest-version="2.24"`, and I am not sure what is unique about this deployment, since we have many more deployments that went through the same round of upgrades and we are not seeing problems like this happening to them. 
[pgbackrest_info.zip](https://github.com/pgbackrest/pgbackrest/files/4356311/pgbackrest_info.zip)

**Comment by dwsteele** [comment]
I still can't figure out what happened here.  The expire code is unchanged between 2.20 and 2.24.  There's definitely a mismatch, though.  The version numbers are normal, that's just the last version of pgBackRest that updated the file.  `archive.info` does not get updated very often.

Do you know if this stanza ever had `'stanza-upgrade` run? My theory is this is an old issue that was suddenly exposed by new code but I can't prove it.

Anyway, if you replace your current `archive.info` with the attached file it should fix the issue.  If everything looks normal you should also replace `archive.info.copy`.

[archive.info.gz](https://github.com/pgbackrest/pgbackrest/files/4357297/archive.info.gz)

**Comment by melrifa1** [comment]
I can't really confirm if `stanza-upgrade` executed on this deployment or not, but it has a chance it might be, as we have done this before on rare occasions. I noticed with the `archive.info` you shared, that you are recommending to keep only the latest in `[db:history]` in `archive.info`, but I noticed the difference in the value of `backrest-checksum` between the original `archive.info` file I posted and the modified `archive.info` you recommended and wondering why the change and how you retrieved the new value?
Original:
```
[backrest]
backrest-checksum="b028b7233f5a7cff9c9c476f2f820387f8300a67"
```
Modified:
```
[backrest]
backrest-checksum="8cbcf17e3f652e8cb01a7aa189f755c428ac744d"
```

**Comment by dwsteele** [comment]
We updated `db:history` in `archive.info` to match `backup.info`.  We're not sure how they got out of sync, but it was probably due to a `stanza-upgrade --force` or an older file being copied into the repo.

The checksum has to be changed if the file is changed.  You can get the new value from the error that gets thrown when the checksum is not as expected.

**Comment by melrifa1** [comment]
Thanks for the help @dwsteele
