### ISSUE TITLE
Generate a recovery.conf without restore  pgbackrest command?

### ISSUE THREAD

**Issue by cheucheu** [pgbackrest/pgbackrest#971]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.18

2. PostgreSQL version: 11.5

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

4. Did you install pgBackRest from source or from a package?

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:

We have configured a streaming replication with PG 11.5 and   we operate pgbackrest backups on the master.  The configuration is OK.  

We would like to resync the slave about rync commands. After the resync, a recovery is necessary.

How to generate the recovery.conf file without run a  restore pgbackrest command ?   
Is it possible to realize a sort of "fake recovery" ?

Thanks a lot

**Comment by slardiere** [comment]
Hi, 

Why do you want to resync the slave with rsync ? 

The `restore` command with the `--delta` should do the job,  and make the `recovery.conf`

Please see : https://pgbackrest.org/command.html#command-restore/category-general/option-delta 

Best regards, 
Sébastien

**Comment by cheucheu** [comment]
Hi Sébastien,

The main reason is that we want to use a procedure that we use in our production environments. 
We were able to test resync, failover and switchover in the pgbackrest context.

Best regards,

Hervé

**Comment by slardiere** [comment]
So maybe your procedure should use pgbackrest, or make recovery.conf by themself ? 
I don't think there is a way to make recovery.conf only in pgbackrest, 

Best regards, 
Sébastien

**Comment by cheucheu** [comment]
In fact, yes for the new deployment with ansible but no for legacy.    We have also  automatic PRAs which use the actual procedure.

So, the best compromise is to adapt our procedure to allow the two worlds to work.

BR
Hervé

**Comment by dwsteele** [comment]
As Sébastien noted, there is no way to generate a `recovery.conf` file without doing a restore.  It's not something we are planning to do, either.  It seems like too much of an edge case.

Writing `recovery.conf` is pretty easy so you should be able to do that to support your legacy process until you can retire it.

BTW -- `rsync` is not safe to use for updating a standby unless you use the `-c` option.
