### ISSUE TITLE
Uncaught ExecuteError: local-1 process did not exit when expected

### ISSUE THREAD

**Issue by pg-chaos** [pgbackrest/pgbackrest#982]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:2.25

2. PostgreSQL version:11.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
epository host server: centos 7.6
database server : centos 7.6

4. Did you install pgBackRest from source or from a package?
package
5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
pgbackrest.conf：
[global]
backup-standby=y
process-max=3
repo1-retention-full=9999999
repo1-path=/pgbackrest
start-fast=y
log-path=/xx/pgbackrest
exclude=archive
archive-timeout=600
protocol-timeout=3600

repo1-s3-bucket=xx
repo1-s3-endpoint=xx
repo1-s3-port=443
repo1-s3-key=xx
repo1-s3-key-secret=xx
repo1-s3-verify-tls=xx
repo1-s3-region=xx
repo1-type=s3

[global:backup]
process-max=8

[global:archive-push]
process-max=3
spool-path=/xx/archive_spool

[global:restore]
process-max=6

[global:archive-get]
process-max=3
7. Describe the issue:
pgbackrest --stanza=pg-xx --pg1-host=xx.xx --pg1-path=/var/lib/pgsql/11/data --pg1-port=5432 --pg2-host=127.0.0.1 --pg2-path=/var/lib/pgsql/11/data --pg2-port=5432 --lock-path=/var/lib/pgsql/11 --type=full backup --log-level-console=info

use pgbackrest backup on standby node,but when end I have this error:
Uncaught ExecuteError: local-1 process did not exit when expected 
thrown at common/exec.c:101
exit status 124

but backup have already completed,only when process local-1 shutdown failed

**Comment by dwsteele** [comment]
Does this happen every time or is it intermittent?  Getting a log at debug level (`--log-level-console=debug` or `--log-level-file=debug`) would be helpful.

**Comment by dwsteele** [comment]
This issue has been consolidated with #1112 .

Please let us know how you would like your name to appear in the release notes when we commit the fix.
