### ISSUE TITLE
FEATURE: Remove a backup adhoc.

### ISSUE THREAD

**Issue by cmwshang** [pgbackrest/pgbackrest#988]
REFERENCE: #953

Allow the user to remove a specified backup regardless of retention settings.  Expire all dependent backups and archive per the usual rules.

Requirements:
1. Given a backup set label, expire that backup and its dependencies. 
2. Allow Full, Diff and Incr to be expired along with dependents.
3. Cannot expire the only full backup. However, if there are 2 full backups and the newest is requested to be expired, then allow it.
4. If the newest backup is expired and there is an aborted backup, the aborted backup will be removed if it requires a prior backup to be valid and the prior backup has been/will be removed.
5. Retention rules will be ignored and only the backup selected (and its dependents) will be expired (i.e. no further backup expiration will occur). Archive retention will not be affected and will proceed as normal.
6. The --set option will be used to pass the label.

**Comment by cmwshang** [comment]
If the latest backup is allowed to be removed the "backup.history" will not be affected but the "latest" link will point to a backup that has been removed. We do not use the "latest" link for anything and it is not supported on all systems, so the question is do we attempt to update it (which can only be done if not a dry run and after the manifests have been removed)? 

Maybe the following code from backup.c can be moved into a common function that can be called by expire:

```
        // Create a symlink to the most recent backup if supported.  This link is purely informational for the user and is never
        // used by us since symlinks are not supported on all storage types.
        // -------------------------------------------------------------------------------------------------------------------------
        const String *const latestLink = storagePathP(storageRepo(), STRDEF(STORAGE_REPO_BACKUP "/" BACKUP_LINK_LATEST));

        // Remove an existing latest link/file in case symlink capabilities have changed
        storageRemoveP(storageRepoWrite(), latestLink);

        if (storageFeature(storageRepoWrite(), storageFeatureSymLink))
        {
            THROW_ON_SYS_ERROR_FMT(
                symlink(strPtr(backupLabel), strPtr(latestLink)) == -1, FileOpenError,
                "unable to create symlink '%s' to '%s'", strPtr(latestLink), strPtr(backupLabel));
        }

        // Sync backup path if required
        if (storageFeature(storageRepoWrite(), storageFeaturePathSync))
            storagePathSyncP(storageRepoWrite(), STORAGE_REPO_BACKUP_STR);
```

Thoughts?

**Comment by sfrost** [comment]
Since we don't actually use it for anything, should we be thinking about just dropping it..?  We typically don't encourage people to dig down into our repo directory in the first place...

**Comment by dwsteele** [comment]
> should we be thinking about just dropping it

Well, it's been there for a long time so this could be a pretty big change for some people. But, of course, it only works when the repo is Posix-compatible which I feel is becoming less common.

Not sure if I want to break it for this feature though. It's not too hard to figure out what the last backup is.

**Comment by cmwshang** [comment]
Well, I guess we could find out who uses it by dropping it :-) But seriously, I think we should just update it since it is only something that can happen during adhoc and only if they remove the latest...

**Comment by dwsteele** [comment]
If nothing else, I use it all the time when I'm testing. Go ahead and move that logic to a function in `command/backup/common.c` and update `backup.c`. Keep it with the rest for now but I'll commit it separately.

**Comment by dwsteele** [comment]
Committed at 1c1a710.
