### ISSUE TITLE
pgbackrest backup is too slow. 

### ISSUE THREAD

**Issue by arvindsaket** [pgbackrest/pgbackrest#989]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: pgBackRest 2.25

2. PostgreSQL version: 9.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each: Ubuntu 18.04

4. Did you install pgBackRest from source or from a package? package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s) 
```
[global]
repo-path              = /pgBackup/yoda/central/shard-0
repo1-retention-full   = 30
start-fast             = y
process-max            = 4
archive-async          = y
archive-get-queue-max  = 1GB
compress-level         = 3
compress-level-network = 3
delta                  = y
repo1-s3-bucket        = *****************
repo1-s3-endpoint      = s3.us-west-2.amazonaws.com
repo1-s3-key           = *********************
repo1-s3-key-secret    = ************************
repo1-s3-region        = us-west-2
repo1-type             = s3

[backup]
db1-path = /var/lib/postgresql/9.6/main/
```

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
archive_mode=on
archive_command = 'pgbackrest --stanza=backup archive-push %p' 
max_wal_senders=25
listen_addresses='*'
    - errors in the postgresql log file before or during the time you experienced the issue
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)

7. Describe the issue:
Postgres Database size is 65GB, pgbackrest is taking hours for backup. CPU utilization is around 15-20%.
```
op - 19:36:48 up 221 days,  2:05,  1 user,  load average: 0.48, 0.62, 1.20
Tasks: 609 total,   1 running, 557 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.8 us,  1.3 sy,  0.0 ni, 96.3 id,  0.5 wa,  0.0 hi,  0.0 si,  0.1 st
KiB Mem : 31391256 total,   659680 free,  5381916 used, 25349660 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 21469820 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
21048 postgres  20   0  223820  47756  12276 S   3.3  0.2   3:49.16 pgbackrest
29808 postgres  20   0 2718160 2.183g  12516 S   3.0  7.3  25:51.05 pgbackrest
 7156 postgres  20   0 4093260 167560 165684 S   0.7  0.5   5037:22 postgres
17443 postgres  20   0   45104   4572   3376 R   0.7  0.0   0:00.12 top
 2928 td-agent  20   0  225800  48576   4456 S   0.3  0.2  74:09.50 ruby
 7164 postgres  20   0  396548 237972   3036 S   0.3  0.8  22841:33 postgres
16587 postgres  20   0 4095672  48516  45548 S   0.3  0.2   0:00.01 postgres
17037 postgres  20   0 4095524  39056  36124 S   0.3  0.1   0:00.01 postgres
```

Below is the error in postgresql-9.6-main.log:

```
ERROR: [082]: unable to push WAL file '000000050000020300000073' to the archive asynchronously after 60 second(s)
2020-04-07 19:40:24.255 UTC [7163] LOG:  archive command failed with exit code 82
2020-04-07 19:40:24.255 UTC [7163] DETAIL:  The failed archive command was: pgbackrest --stanza=backup archive-push pg_xlog/000000050000020300000073
2020-04-07 19:40:24.255 UTC [7163] WARNING:  archiving transaction log file "000000050000020300000073" failed too many times, will try again later
```

**Comment by dwsteele** [comment]
> Postgres Database size is 65GB, pgbackrest is taking hours for backup. CPU utilization is around 15-20%

This generally indicates the process is IO bound, usually on the network.

You may also be affected by this issue: https://github.com/pgbackrest/pgbackrest/issues/940. Recent kernels have caused slowdowns for unknown reasons, but we are working on it.

> ERROR: [082]: unable to push WAL file '000000050000020300000073' to the archive asynchronously after 60 second(s)

Is WAL logging happening at all, or is it just really slow?

**Comment by soulhunter** [comment]
Is that PostgreSQL server running on AWS? (EC2 instance)  I would believe you might have a slow uplink, and so you cannot upload fast enough... but if your server is in AWS, it might be something else.

**Comment by arvindsaket** [comment]
My PostgreSQL server running on AWS.

**Comment by justinfalk** [comment]
We have the same issue with 2.25.  Backups to s3 are taking over 3 times as long to complete.

**Comment by dwsteele** [comment]
@justinfalk This is likely due to #940. What version were you running before 2.25?

**Comment by justinfalk** [comment]
Thanks @dwsteele .  We were on 2.16 I believe.  Looks like this might be fixed in 2.26.  We'll try it out.

**Comment by dwsteele** [comment]
@justinfalk 2.16 was already on the C storage layer so this regression may be tied to a kernel update (see #940 for details of affected kernel versions). Some users had systems on the older kernel that worked fine and the newer kernel that saw slowdowns, but used the same version of pgBackRest.

Unfortunately we were never able to determine the root cause, but moving to async IO allowed us to control timeouts rather than the kernel and that appears to have solved the issue.

**Comment by arvindsaket** [comment]
Now I am using pgbackrest 2.26:with below config 
```
[global]
repo-path              = /postgres/central/shard-0
repo1-retention-full   = 3
process-max            = 8
compress-level         = 3
compress-level-network = 3
repo1-s3-bucket        = **********backup***********
repo1-s3-endpoint      = s3.us-west-2.amazonaws.com
repo1-s3-key           = *****************
repo1-s3-key-secret    = ****************
repo1-s3-region        = us-west-2
repo1-type             = s3
tcp-keep-alive-idle     = 15
tcp-keep-alive-count    = 3
tcp-keep-alive-interval = 15
start-fast              = y

[global:archive-get]
process-max            = 6
compress-level         = 3

[global:archive-push]
process-max            = 3
compress-level         = 3

[backup]
db1-path = /var/lib/postgresql/9.6/main/
```

My postgres is in AWS and having 350GB of data. 
While backup it took around 10hrs and while restoration it took around 12hrs.

Will you please guide we are missing in configuration and how we can improve the performace.

**Comment by dwsteele** [comment]
Have you checked your CPU usage during backup? Is it high or low? Does your instance type limit your CPU usage?

If your CPU usage is lower than 100% and you don't have CPU limits, then your bottleneck may be the network.

If your CPU usage is close to 100% then you can try using a faster compression type such as lz4, `compress-type=lz4`.

**Comment by sfrost** [comment]
You can also try adding more processes to pgbackrest, even if your CPU isn't at 100%, as that can result in more throughput since sometimes we end up having to wait on s3 and more processes means more connections to s3.

**Comment by justinfalk** [comment]
I just wanted to follow up and confirm that upgrading to 2.26 resolved our performance issues  that we encountered in 2.25.  Thanks everyone.

**Comment by dwsteele** [comment]
@justinfalk Glad to hear it!
