### ISSUE TITLE
RPMs removed from official Postgres RPM Repos?

### ISSUE THREAD

**Issue by guruguruguru** [pgbackrest/pgbackrest#993]
Hi,

am I right that the pgbackrest rpm packages were removed from the official postgres repos?

https://yum.postgresql.org/11/redhat/rhel-7-x86_64/
https://yum.postgresql.org/12/redhat/rhel-7-x86_64/

Is there an explanation for this? Was this a mistake?

Thanks a lot,
Dennis

**Comment by dwsteele** [comment]
The packages were moved, see: https://www.postgresql.org/about/news/2027/

We are not directly involved with maintaining the RPM packages so this was a surprise to us as well.

**Comment by kmatt** [comment]
This was the relevant section in my CentOS 7 `pgdg-redhat-all.repo.rpmnew` that had to be migrated to re-enable yum installs of add on components:

```
[pgdg-common]
name=PostgreSQL common RPMs for RHEL/CentOS $releasever - $basearch
baseurl=https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-$releasever-$basearch
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG
```
