### ISSUE TITLE
Regular expression issue on macOS

### ISSUE THREAD

**Issue by dpr11** [pgbackrest/pgbackrest#997]
1. pgBackRest version:
    
    pgBackRest: 2.25
    
2. PostgreSQL version:

    PostgreSQL: 12.2

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:

    macOS: 10.14.6 (Darwin Kernel Version 18.7.0)
    and
    macOS: 10.11.6 (Darwin Kernel Version 15.6.0)

4. Did you install pgBackRest from source or from a package?

    Compiled it from source

5. Please attach the following as applicable:

- `pgbackrest.conf` file(s)

    [pgdata]
    pg1-path=/Users/postgres/pgdata

    [global:archive-push]
    compress-level=3

    [global]
    repo1-cipher-pass=<redacted>
    repo1-cipher-type=aes-256-cbc
    repo1-retention-full=2
    stop-auto=y
    start-fast=y
    repo1-path=/Users/postgres/pgbackrest

- `postgresql.conf` file(s)

    archive_command = '/usr/local/bin/pgbackrest --stanza=pgdata archive-push %p'
    archive_mode = on
    listen_addresses = 'localhost'
    max_wal_senders = 10
    wal_level = logical
    port = 5432

7. Describe the issue:

Hi

I've been using pgbackrest for a year or so on macOS and love it. I've used versions 2.08 and 2.15 and they have worked great. I recently upgraded to 2.25 so that I could get PostgreSQL 12 support, but I am having trouble getting it to work.

I compiled it from source as I don't think binaries are available for my platform. I have used Homebrew to get the latest versions of the dependencies, then ran 'configure', changed the Makefile so the libraries and headers for libxml2 and openssl are included in CPPFLAGS and LDFLAGS, then ran 'make' and 'make install'.

Here are the versions I'm using:

    pgBackRest: 2.25
    PostgreSQL: 12.2
    libxml2: 2.9.10_1
    openssl: 1.1.1f
    macOS: 10.14.6 (Darwin Kernel Version 18.7.0)
    and
    macOS: 10.11.6 (Darwin Kernel Version 15.6.0)

It compiles without errors or warnings and seems to run fine. But it fails every time when making a backup with the following error:

...
2020-04-11 16:11:15.134 P00   INFO: execute non-exclusive pg_start_backup(): backup begins after the requested immediate checkpoint completes
2020-04-11 16:11:16.651 P00   INFO: backup start archive = 000000010000000000000006, lsn = 0/6000028
ERROR: [029]: empty (sub)expression
2020-04-11 16:11:16.668 P00   INFO: http statistics: objects 1, sessions 1, requests 2, retries 0, closes 0
2020-04-11 16:11:16.668 P00   INFO: backup command end: aborted with exception [029]
...

I stripped back my pgbackrest.conf so it backs up to a local directory rather than to S3 like I have been doing, but it makes no difference.

After much Googling, I think this might be due to the macOS's regular expression handling - it doesn't seem to like some expressions that Linux is happy with. Particularly, it doesn't like:

    (|_(fsm|vm))

where there is nothing either before or after the pipe character.

I found this in the source code, in src/info/manifest.c (line 847):

    #define RELATION_EXP    "[0-9]+(|_(fsm|vm)){0,1}(\\.[0-9]+){0,1}"

and have replaced it with

    #define RELATION_EXP    "[0-9]+((_(fsm|vm))?){0,1}(\\.[0-9]+){0,1}"

and it seems to compile and run fine, but my regular expression knowledge is not great and these two expressions may not be equivalent.

Before I hit upon this change, I installed GNU's grep using brew and ensured it appeared early in the path during compilation and running, but it still gave the same error at runtime. So I'm not sure - maybe some other code or library is using the macOS's default regular expression behaviour.

Do you think this is a suitable fix? Or is there another way for me to get around this issue during compilation with leaving the source code as it was? I'm not entirely sure how the build/configuration system works, and am kind of guessing.

Any help would be appreciated.

Thanks

**Comment by dwsteele** [comment]
I can certainly see an empty sub expression in the original expression. I'm not sure why it's there, probably a typo, but it seems Linux tolerates it.

Your expression works but it's a bit redundant.  Can you try:
```
#define RELATION_EXP    "[0-9]+(_(fsm|vm)){0,1}(\\.[0-9]+){0,1}"
```
and see if that works?

**Comment by dpr11** [comment]
That seemed to work too. There was no error during the backup.

Thanks.

**Comment by dwsteele** [comment]
Cool, we'll update that for the next release. How would you like your name to appear in the release notes?

**Comment by dpr11** [comment]
That’s very kind. Glad I could help. My name is David Raftis. Thanks.

**Comment by dwsteele** [comment]
Committed at 0c07c5111fb73.

We appreciate you taking the time to report the issue and we like to give credit where it is due.  Thank you!
